### ISSUE TITLE
Unable to disable Logging with sensitive user data

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#1000]
## Expected Behavior

On production, I should be able to disable all kind of logging that contains sensible user data like the email/username.

## Current Behavior

I'm not able to disable logging with sensible data even if I set all of this three to false:

- name: OAUTH2_PROXY_REQUEST_LOGGING
  value: "false"
- name: OAUTH2_PROXY_STANDARD_LOGGING
  value: "false"
- name: OAUTH2_PROXY_AUTH_LOGGING
  value: "false"

I still can see log entries like:

`refreshed access token Session{email:john.doe@example.de user:aa4980ee-0939-4ea7-b67f-81883f143d39 PreferredUsername:john.doe@example.de token:true id_token:true created:2021-01-19 15:44:53.649175874 +0000 UTC m=+49.297994089 expires:2021-01-19 15:45:53.615354568 +0000 UTC m=+109.264172798 refresh_token:true} (expired on 2021-01-19 15:45:53.615354568 +0000 UTC m=+109.264172798)`

## Possible Solution

Make it possible to disable logging of any kind of session data. Additionally, by default I would recommend to disable it.

## Your Environment

- Version used: 6.1.1

**Comment by JoelSpeed** [comment]
This makes me wonder if we need to do an audit of our logging, I don't think we log too much in terms of PII, but it would be good if we could log none! 

Perhaps there's a way we can ensure all session logging is handled in a way that allows us to set the sensitivity 🤔

**Comment by Bibob7** [comment]
What about handling it with typical log levels? I think logging of sensible data is only acceptable in debug mode. For Info -> Warning -> Error we have to make sure, that we never log any user specific data.

 I think [logrus](https://github.com/sirupsen/logrus) has a good support for that.

**Comment by JoelSpeed** [comment]
We've been discussing logging with different levels before and I have some ideas around using klog for that, but, under the hood so we don't break the existing interface.

I'm not 100% sure whether we want to have it completely disabled at levels other than debug, some people may be using this logging as a type of audit, ie, which users logged in when, and if this kind of information were only available at debug level they would have a lot of log pollution

**Comment by Bibob7** [comment]
Makes sense, but what about logging only the unique user id from the idp. Of course this would only work, if there is something provided. But for example in the case of refreshed session, we could log the uuid instead of the email. Just an idea.

**Comment by JoelSpeed** [comment]
I think the only thing with that, is that in some cases it is not particularly easily identifiable, and if you are using this as an audit, you may want it to be something like the email address for the user, perhaps we need to make it configurable?

If you're running this to protect company resources, logging your employees email addresses I believe should be ok

**Comment by Bibob7** [comment]
> If you're running this to protect company resources, logging your employees email addresses I believe should be ok

This is true, but we also want to use it for customers. :)

**Comment by JoelSpeed** [comment]
I definitely think we would want to make some configurable thing here in that case 🤔

**Comment by Bibob7** [comment]
How we should proceed here? I would like to have this config with the next release, if possible. 

What do you think? Adding just another log config attribute called sensitive-logging = true or false and then search for all cases, where we log session information?
