### ISSUE TITLE
GitLab cookie secret config docs missing

### ISSUE THREAD

**Issue by MakerT** [oauth2-proxy/oauth2-proxy#1003]
## Expected Behavior

Redirect to page regarding GitLab Cookie Secret configuration.

## Current Behavior

In the guide regarding [GitLab provider configuration](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#gitlab-auth-provider) there is a link to Cookie Secret config. This redirects you to blank page with error 404.

## Possible Solution

Adding the missing file to documents.

## Steps to Reproduce (for bugs)

1. Go to GitLab provider configuration.
2. Click on the `these steps` link in this sentence To get a cookie secret follow these steps

## Context

Due to this I can't setup OAUTH2 proxy with selfhosted GitLab instance as provider.

## Your Environment

GitHub documentation of OAUTH2 proxy.

- Version used:

Latest

**Comment by JoelSpeed** [comment]
Good catch! The link should be updated to point to https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview I think, there's some instructions at the top of that for how to generate a cookie secret
