### ISSUE TITLE
[Question] How to handle multiple parallel requests and Refresh Token Rotation?

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#1006]
We plan to use oauth2-proxy with session data stored in a cookie.
In addition, we use refresh tokens to update the access and id_token when they expire.

This works well if the client only sends one request at a time. But in the case of an SPA for example, it could be possible that several parallel requests are sent. In this case, it could be possible that one request contains a refresh token that has already been used.

How would you deal with this problem? Is the only way to solve it to use a central session store like redis?
Is the oauth2 proxy able to handle this in this case?

**Comment by JoelSpeed** [comment]
I would recommend using redis as you've suggested, in my experience, that greatly reduces the likelihood of sessions being killed as they are refreshed.

You can also improve the situation further by using some sort of caching in front of the auth endpoint, for an example of this, [here is some configuration](https://gist.github.com/JoelSpeed/9f4dbf6f79f6498d12ccd6ff0bc096e2) that I used to use in NGINX.

Ideally, long term, we would handle this is a clever way within the proxy, but it somehow would mean having a lock on the session to be able to perform the refresh, which, without something like redis to act as a central lock, could cause issues

**Comment by Bibob7** [comment]
Another idea is to perform retries. We talked to our IDP and they recommend to perform retries with a newer version of the auth cookie or entry from Redis.

So let's say the IDP responds with error `refresh token revoked`.
The reason for this could be that another parallel request already used it. oauth2-proxy could then responds with a specific https code or response so that the client knows, it could try to send the request again, but with a newer version of the auth cookie or if we use Redis, we could try to fetch again the current version of the session and oauth2-proxy would validate the session to true, because it was already renewed by a previous request.

I hope you can follow me. :)

**Comment by JoelSpeed** [comment]
In this case, if I follow correctly, rather than clearing the session as we do now, we would request the client try again? How would we track if we have already asked them to retry? What if a retry fails, do we tell the to retry again? What happens if the token has actually been revoked and there is no valid refresh token existing?

**Comment by Bibob7** [comment]
> In this case, if I follow correctly, rather than clearing the session as we do now, we would request the client try again? How would we track if we have already asked them to retry? What if a retry fails, do we tell the to retry again? What happens if the token has actually been revoked and there is no valid refresh token existing?

Good point. This has to be handled in the frontend or another backend component that is calling the oauth2/auth endpoint.

What about having retries when fetching the stored session from Redis, if we noticed that refreshing of the session is not possible. If there was another parallel request that already has updated the session correctly in Redis, with the second or third fetch from Redis, we would receive the refreshed session and can continue.

**Comment by NickMeves** [comment]
We have this closed issue that might be of interest: https://github.com/oauth2-proxy/oauth2-proxy/issues/667

While it doesn't fix events at the same time across horizontally scaled nodes, adding support for something like `singleflight` groups into our request builder for refresh requests could solve some of the contention (at least within nodes).

**Comment by Bibob7** [comment]
Thanks for the Link to the issue. It seems that the Problem/Idea is not new.

Having a lock with Redis would probably also solve the Problem. I would also try to go the most easy way as possible. That's why I suggested the retry for loading and refreshing the session. This might be not possible with all providers, but in the case of our provider we can try to refresh an access token as often we want with a revoked refresh token without invalidating the currently valid refresh token. I think this is an essential behaviour that makes it possible to have this naiv approach. However, is this something we could try to integrate as a possible config or would you say, this is a behaviour that in most cases would not work and should not be provided?
