### ISSUE TITLE
Cannot pass allowed_groups as query parameter to /auth endpoint

### ISSUE THREAD

**Issue by JohanLindvall** [oauth2-proxy/oauth2-proxy#1009]
## Expected Behavior

I am passing query parameters to /auth:
 /auth?allowed_groups=mygroup and I would expect this query parameter to be honored and used.

## Current Behavior

The query parameter allowed_groups is ignored

## Possible Solution

The routing compares absolute strings so an extra query parameter will obviously cause a mismatch.

- Version used:
latest master

**Comment by JoelSpeed** [comment]
When you refer to `/auth`, do you actually mean `/oauth2/auth`? Normally there is a proxy prefix (default `oauth2`) to these, I wonder if you're just not hitting the right endpoint here, the path shouldn't be including the query string so I wouldn't expect this to cause routing issues in the routing switch

**Comment by JohanLindvall** [comment]
Yes, I mean /oauth2/auth :) I am hitting the right endpoint and after the fix I provided in the PR things do work as intended

**Comment by JoelSpeed** [comment]
The fix proposed concerns me a little as that would mean I could request `/oauth2/authbad` and get end up with the wrong behaviour, I wouldn't expect this page to be served as the AuthOnly page.

Have you printed the `req.URL.Path` out in the cases you are trying to see if it is indeed including the query string? This is definitely not what I would have expected from the HTTP library, it should have taken the query string off when parsing the URL

**Comment by JohanLindvall** [comment]
Apologies, you are absolutely right. I was bitten by the nginx bug/feature where query params in auth_requests aren't handled.
