### ISSUE TITLE
Only pass Groups/Roles that matches pattern

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#1012]
## Expected Behavior

In our IDP we can not group user groups and roles by app or client.
But the upstream services should not be able to see which groups and roles a user has for other apps/clients registered in the IDP. Let's say our groups has the format {client}.{group}, then I want to filter out only groups for the specific client.

## Current Behavior

I can't find a possible configuration for this use case. But maybe, I just missed it.

## Possible Solution

Implement a similar group filtering feature described above.

**Comment by JoelSpeed** [comment]
> But the upstream services should not be able to see which groups and roles a user has for other apps/clients registered in the IDP.

Can you provide an example of why this might be harmful?

**Comment by NickMeves** [comment]
I take it if group filtering functionality were in place for the `X-Forwarded-Groups` header, would you also want to filter `/oauth2/userinfo`?

Or are you fine with that returning all groups, since that call is user driven and only returns the data to them?

**Comment by NickMeves** [comment]
> > But the upstream services should not be able to see which groups and roles a user has for other apps/clients registered in the IDP.
> 
> Can you provide an example of why this might be harmful?

I see the merit, @Bibob7 feel free to elaborate if you have a more concreate scenario for your organization:

For instance if in my IdP for my company, I assign users that are part of an NDA Proprietary project to a special group for them to grant access to project resources -- if the membership in that group is confidential information, we'd currently leak it to backend generic applications that are unrelated to the proprietary project.

**Comment by Bibob7** [comment]
> I take it if group filtering functionality were in place for the `X-Forwarded-Groups` header, would you also want to filter `/oauth2/userinfo`?
> 
> 
> 
> Or are you fine with that returning all groups, since that call is user driven and only returns the data to them?

I think it makes also sense to have it for oauth2/userinfo but forwarding groups is more important.

**Comment by TwoStone** [comment]
I will hook up on this feature request with another scenario. We are facing the issue that a user has many groups we are getting from our idp. This results in a http error 400 when forwarding the request to the upstream because the header is to big.

**Comment by JoelSpeed** [comment]
IMO, if we are planning to implement this, we should be filtering the groups before they are persisted to the session. Therefore they're filtered before Authz, before header injection and before userinfo.

> This results in a http error 400 when forwarding the request to the upstream because the header is to big.

This may not solve this issue, if you have the ID Token being stored and this is large, we won't be affecting the size of the ID Token by adding filtering here. You should be able to increase the proxy buffer size, 8kb should be enough normally

**Comment by NickMeves** [comment]
> I will hook up on this feature request with another scenario. We are facing the issue that a user has many groups we are getting from our idp. This results in a http error 400 when forwarding the request to the upstream because the header is to big.

Using the persistent Redis store is another solution to this problem. We recommend this approach to people that have large tokens from their IdP -- the session lives there & then the session cookie is small & light and doesn't risk colliding with the header max unexpectedly (individual users with large tokens, or backend apps with extra larger headers pushing you toward that 8k max).

**Comment by PoudNL** [comment]
I am wondering if you were able to solve this issue @Bibob7 ?
Currently I am migrating from Microsoft ADFS to Microsoft AzureAD connector.

In the Microsoft ADFS I was able to filter the groups before sending them to oauth-proxy. On Azure that isn't the case anymore. I need some way of filtering for exactly the same reasons as you suggested.
