### ISSUE TITLE
Current Build of v7.0.0 Branch Reporting as 6.1.1

### ISSUE THREAD

**Issue by knightian** [oauth2-proxy/oauth2-proxy#1014]
## Expected Behavior

Make a Binary that reports version 7.0.0

## Current Behavior

I run make oauth2-proxy after switching to the release-v7.0.0 branch, and it tells me it is creating main.VERSION=v6.1.1-183-gdab174e

## Steps to Reproduce (for bugs)

git checkout release-v7.0.0
make oauth2-proxy

## Your Environment

Ubuntu Server 20.04

- Version used: v7 release branch

**Comment by JoelSpeed** [comment]
Hey @knightian we haven't actually quite finalised the v7 release just yet, the branch you're referring to is the base for #1007 which prepares the repository for the next release. We will only actually create the v7 release once that branch is merged, hence the version string still saying v6.1.1

**Comment by knightian** [comment]
Ah ok gotcha. I assume the documentation that says current binary is v7 is ahead of its time then? Because that’s what prompted me to switch to v7.

**Comment by JoelSpeed** [comment]
I think this is an unfortunate side effect of our migration to go modules, we updated the module (and hence the docs for building the binary) but haven't made the release yet. So, kinda ahead of its time? Kinda not? It's a difficult one 😅

**Comment by knightian** [comment]
Expected as v7 not actually released yet.
