### ISSUE TITLE
CLI parameters have become order dependent with 7.0.0

### ISSUE THREAD

**Issue by UiP9AV6Y** [oauth2-proxy/oauth2-proxy#1018]
Configuration passed via CLI parameters does not seem to be used depending on the
order in which they are supplied.

## Expected Behavior

7.x creates a new [flags set](https://github.com/oauth2-proxy/oauth2-proxy/blob/06985879e19c3d47ed73ff650b67e2e775f88feb/main.go#L22) with support for the
following flags:

- config
- alpha-config
- convert-config-to-alpha
- version

if i pass any of the other configuration parameters (e.g. http-address) on the CLI *before*
one of the flags above, they are processed but cause the other parameters to be skipped.

## Current Behavior

`docker run --rm -p 127.0.0.1:4180:4180 -v $PWD/oauth2_proxy.cfg:/etc/oauth2-proxy.cfg:ro,z quay.io/oauth2-proxy/oauth2-proxy:v7.0.0 --http-address=127.0.0.1:4180 --config=/etc/oauth2-proxy.cfg`

> [main.go:53] invalid configuration:
>   missing setting: cookie-secret
>   missing setting: client-id
>   missing setting: client-secret or client-secret-file
>   missing setting for email validation: email-domain or authenticated-emails-file required.
>       use email-domain=* to authorize all email addresses

## Possible Solution

reordering the parameters will result in oauth2-proxy consuming all instructions properly

`docker run --rm -p 127.0.0.1:4180:4180 -v $PWD/oauth2_proxy.cfg:/etc/oauth2-proxy.cfg:ro,z quay.io/oauth2-proxy/oauth2-proxy:v7.0.0 --config=/etc/oauth2-proxy.cfg --http-address=127.0.0.1:4180`

flags other than the ones from the initial flag set must appear last on the CLI for all flags to
be consumed properly.

## Steps to Reproduce (for bugs)

`docker run --rm -p 127.0.0.1:4180:4180 -v $PWD/oauth2_proxy.cfg:/etc/oauth2-proxy.cfg:ro,z quay.io/oauth2-proxy/oauth2-proxy:v7.0.0 --email-domain='*' --config=/etc/oauth2-proxy.cfg`

> [main.go:53] invalid configuration:
>   missing setting: cookie-secret
>   missing setting: client-id
>   missing setting: client-secret or client-secret-file

the config file *does* contain the missing information but does not seem to be parsed.

## Context

before 7.x the order of the parameters did not matter, as the code used the *Options* flagset as basis for further customization.

`docker run --rm -p 127.0.0.1:4180:4180 -v $PWD/oauth2_proxy.cfg:/etc/oauth2-proxy.cfg:ro,z quay.io/oauth2-proxy/oauth2-proxy:v6.1.1 --http-address=127.0.0.1:4180 --config=/etc/oauth2-proxy.cfg`

i believe this is due to 7.x creating a new [flags set](https://github.com/oauth2-proxy/oauth2-proxy/blob/06985879e19c3d47ed73ff650b67e2e775f88feb/main.go#L22) with *pflag.ContinueOnError*
set as error behaviour. this causes pflag to bail on the first unknown flag, which in turn
causes e.g. `--config` to be passed to the seconf flag set, which does not support it. therefor
the config file is never parsed.

we deploy oauth2-proxy using a helm chart which places configuration parameters before
the `--config` parameter. we could patch the chart, but would at least like to see a warning
or note about the change of flag parsing behaviour.

## Your Environment

the configuration should not really be of importance here, but just in case, this is what i used
to reproduce the bug.

```toml
upstreams = [
    "http://127.0.0.1:8080/"
]
email_domains = [
    "yourcompany.com"
]

client_id = "123456.apps.googleusercontent.com"
client_secret = "123456"
cookie_secret = "4VGFAz4J7qplOWhObw-vHw=="

provider = "oidc"
provider_display_name = "My OIDC Provider"
redirect_url = "http://127.0.0.1:4180/oauth2/callback"
oidc_issuer_url = "http://127.0.0.1:5556/dex"
```

- Version used: 6.1.1
- Version used: 7.0.0

**Comment by NickMeves** [comment]
Is this an order issue of all flags? Or an order issue when mixing command line flags with a config file? Any impact on environment variable provided configuration?

CC: @JoelSpeed -- Anything jump to mind for you related to the alpha-configs refactor of configurations?

**Comment by UiP9AV6Y** [comment]
> Is this an order issue of all flags? Or an order issue when mixing command line flags with a config file? Any impact on environment variable provided configuration?

i have not tested it with all flags TBH.

environment parsing seems not affected. a quick test run with the following setup worked
`docker run --rm -p 127.0.0.1:4180:4180 -v $PWD/oauth2_proxy.cfg:/etc/oauth2-proxy.cfg:ro,z -e OAUTH2_PROXY_COOKIE_SECRET='4VGFAz4J7qplOWhObw-vHw==' -e OAUTH2_PROXY_CLIENT_ID=123456.apps.googleusercontent.com -e OAUTH2_PROXY_CLIENT_SECRET=123456 -e OAUTH2_PROXY_PROVIDER=google quay.io/oauth2-proxy/oauth2-proxy:v7.0.0 --email-domain='*'`
> [oauthproxy.go:137] OAuthProxy configured for Google Client ID: 123456.apps.googleusercontent.com
> [oauthproxy.go:143] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
> [http.go:57] HTTP: listening on 127.0.0.1:4180

the problem seems to be in combination with the config/alpha-config flags

works: `docker run --rm -p 127.0.0.1:4180:4180 -v $PWD/oauth2_proxy.cfg:/etc/oauth2-proxy.cfg:ro,z quay.io/oauth2-proxy/oauth2-proxy:v7.0.0 --config=/etc/oauth2-proxy.cfg --email-domain='*'`

the config parameter comes first, followed by a flag from the options.Flagset


> [proxy.go:71] mapping path "/" => upstream "http://127.0.0.1:8080/"
> [oauthproxy.go:137] OAuthProxy configured for Google Client ID: 123456.apps.googleusercontent.com
> [oauthproxy.go:143] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
> [http.go:57] HTTP: listening on 127.0.0.1:4180

does not work: `docker run --rm -p 127.0.0.1:4180:4180 -v $PWD/oauth2_proxy.cfg:/etc/oauth2-proxy.cfg:ro,z quay.io/oauth2-proxy/oauth2-proxy:v7.0.0 --email-domain='*' --config=/etc/oauth2-proxy.cfg`

the *email-domain* argument is the first one in this case

> [main.go:53] invalid configuration:
  missing setting: cookie-secret
  missing setting: client-id
  missing setting: client-secret or client-secret-file

the used configuration for completeness sake:
```toml
upstreams = [
    "http://127.0.0.1:8080/"
]

client_id = "123456.apps.googleusercontent.com"
client_secret = "123456"
cookie_secret = "4VGFAz4J7qplOWhObw-vHw=="

provider = "google"
```

**Comment by jonkerj** [comment]
I think I may be facing the same issue. I am using v7.0.0 on Kubernetes using the (legacy) helm file, and it's complaining about `email-domain`, which it did not with v6.1.0:

> "missing setting for email validation: email-domain or authenticated-emails-file required. use email-domain=* to authorize all email addresses"

This setting is in my config file (`email_domains = ['REDACTED']`), but apparantly not picked up. When I try to work around it by supplying it through the CLI (`--email-domain REDACTED`) it is getting picked up, but other settings from the config file are ignored, such as oidc settings, I get "Google" instead of my Keycloak.

The effective invocation of oauth2-proxy in my case is: `--http-address=0.0.0.0:4180 --email-domain=REDACTED --config=/etc/oauth2_proxy/oauth2_proxy.cfg` and `OAUTH2_PROXY_CLIENT_ID`, `OAUTH2_PROXY_CLIENT_SECRET` and `OAUTH2_PROXY_COOKIE_SECRET` are provided through environment.

I think I could work around it by supplying everything as CLI flags, but I prefer to use the config file.

**Comment by JoelSpeed** [comment]
I've opened #1026 which I believe resolves this issue, @UiP9AV6Y @jonkerj do you have time to test the patch out?

**Comment by jonkerj** [comment]
> I've opened #1026 which I believe resolves this issue, @UiP9AV6Y @jonkerj do you have time to test the patch out?

Sure, if there is a Docker image, I'll test it tomorrow right away

**Comment by jonkerj** [comment]
Took a while, as I had to build/push the docker image somewhere. I can confirm #1026 fixes this problem for me.

**Comment by NickMeves** [comment]
> Took a while, as I had to build/push the docker image somewhere. I can confirm #1026 fixes this problem for me.

Awesome! Thanks for the help confirming the fix @jonkerj
