### ISSUE TITLE
How we can get the username and email? (Okta & OAuth2 Proxy)

### ISSUE THREAD

**Issue by nissimbitan** [oauth2-proxy/oauth2-proxy#1022]
Hi, 

We using oauth2 proxy with okta. 
and after the user logged in we unable to identify which user is it. the only data that we have its the _oauth2_proxy cookie.

This is the current configuration we using.
```yaml
- '--provider=oidc'
- '--redirect-url=https://<DOMAIN>/oauth2/callback'
- '--oidc-issuer-url=<OIDC ISSUER>'
- '--email-domain=*'
- '--upstream=file:///dev/null'
- '--http-address=0.0.0.0:4180'
- '--pass-access-token=true'
- '--set-xauthrequest=true'
- '--prefer-email-to-user=true'
- '--pass-basic-auth=true'
- '--pass-user-headers=true'
- '--pass-authorization-header=true'
- '--skip-provider-button=true'
```

**how we can get the username and email?**

**Comment by JoelSpeed** [comment]
If you are logged in, and access `/oauth2/auth`, you should see `X-Auth-Request-User` and `X-Auth-Request-Email` response headers based on your current configuration.

Since you are not using an upstrream the `--pass-...` options will have no effect

**Comment by nissimbitan** [comment]
@JoelSpeed how can i set it to pass the headers to the application after logged in?

**Comment by JoelSpeed** [comment]
I don't really have enough information to answer that question.

Are you using Nginx or something with external with to protect your resources? (It looks as though you may be from your upstreams). The answer will depend on what exactly is making the actual requests to your application

**Comment by glikpsc** [comment]
almost 3 years from the last record :(  I do have the same or similar question
I need to figure user info on backend app (flask)
We use nginx + oAuth proxy + Okta. I am trying to send  OAUTH2_PROXY_SET_XAUTHREQUEST headers I am getting from the proxy to flas back-end app. I see headers in nginx logs but they are not sent to the upstream backend app. What can be tweaked in proxy setup and/or nginx? 
Alternatively, I see that the oauth_proxy cookie is always sent to the backend how I can use it to get user info from the proxy?

**Comment by tuunit** [comment]
@glikpsc your upstream is not your flask but nginx. Therefore you have to configure your nginx to forward headers from the auth_request. 

For an example, please checkout the following:
https://serverfault.com/a/950019

```
location = /jwtverify {
  internal;
  proxy_pass              http://auth-module:8080/auth/verify;
  proxy_pass_request_body off;
  proxy_set_header        Content-Length "";
  proxy_set_header        X-Original-URI $request_uri;
}

location /profile {
  auth_request /jwtverify;

  # this gets called right after auth_request returns.
  # it reads http "authorization" header from upstream (= auth_request)
  # and sets it to the variable $auth_header
  # https://stackoverflow.com/a/31485557/1759845
  auth_request_set $auth_header $upstream_http_authorization;

  # this gets called right before sending response to client.
  # it adds the previously set variable (= "authorization" 
  # header from auth_request) to the response
  more_set_headers "Authorization: $auth_header";

  proxy_pass        http://private-profile:80;
}
```

**Comment by glikpsc** [comment]
@tuunit Thank you for your help. After reviewing back and-forth samples I ended up reconfiguring location (made a specific route for protected call).  Then big part was figuring exact name for upstream variable and last tweak the headers should use dash in name, not underscore :) 

`			auth_request /oauth2/auth ;
		
			auth_request_set $id $upstream_http_x_auth_request_preferred_username;
			
			proxy_set_header  My-User $id;
			proxy_pass_header My-User;
`
my next thing is https://github.com/oauth2-proxy/oauth2-proxy/issues/334

**Comment by tuunit** [comment]
Glad that you got it working @glikpsc. Maybe get in touch with @bakito how he was able to solve the issue mentioned in #334.
