### ISSUE TITLE
Early Refresh of Access Token

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#1030]
## Expected Behavior

I want to configure a buffer time for valid access tokens so that the access tokens are updated before their expiration time.

For example, if an access token is valid for 15 minutes, I want to renew it 2 minutes before it expires to ensure that the forwarded access token is valid for some remaining time.

## Current Behavior

An access token is refreshed only when the current expiration date is reached. For example, if the access token expires 1 second later, it is possible that the access token has already expired when it is checked later as part of the request.

## Possible Solution

Add a configuration attribute to specify a buffer time for the expiration time of an access token.

## Context

In our use cases we use oauth2-proxy primarily to decode the auth cookie or to fetch the access token as part of the session data from redis. In a sidecar proxy of the backend app, we additionally check specific conditions on the passed jwt. If the jwt is then already expired, this checks will fail.

- Version used:

- 6.1.1

**Comment by NickMeves** [comment]
Does this existing issue track all your requirements? https://github.com/oauth2-proxy/oauth2-proxy/issues/856
