### ISSUE TITLE
New version of Keycloak (v12) breaks login (Invalid scope: api)

### ISSUE THREAD

**Issue by craftbyte** [oauth2-proxy/oauth2-proxy#1033]
## Expected Behavior

When logging in with a Keycloak backend the login works

## Current Behavior

Logging in with a default client setup of Keycloak in Keycloak v12 throws an Exception of `invalid_request` with `Invalid scopes: api` in the URL.

## Possible Solution

Allow user to set manual scopes or remove `api` scope from the Keycloak provider by default.

## Steps to Reproduce (for bugs)

1.  Set up a new Keycloak instance (we use the `jboss/keycloak` docker image)
2.  Add the client and configure oauth2-proxy with the keycloak provider
3.  Try to log in

## Context

I had to create a manual `api` scope in Keycloak that does nothing and add it to the client for the login to work.

## Your Environment

Keycloak v 12.0.2 in a Docker, client with all default scopes (email, profile, roles, web-origins) set up in Keycloak.

- Version used: 7.0.0

**Comment by NickMeves** [comment]
We are looking to move to Keycloak using OIDC natively and ditching the OAuth2 `api` scope.  In the meantime, you can use the OIDC Provider directly with your keycloak server. I think if you search the issues or checkout the slack channel we've helped out a few people with the specifics of setting up Keycloak as a generic OIDC.

**Comment by NickMeves** [comment]
https://github.com/oauth2-proxy/oauth2-proxy/issues/956

**Comment by NickMeves** [comment]
BTW - thanks for raising this issue in the new Keycloak version up to us! This puts some fire under my butt to spike out the Keycloak OIDC refactor 😄

**Comment by Electrofenster** [comment]
I've found a workaround to get it working with latest keycloak and oauth2-proxy

**Comment by craftbyte** [comment]
Should we close this issue in favor of #956 or keep it open?

**Comment by JoelSpeed** [comment]
I think we may want to add a short term fix of mentioning within the documentation that users need to set the scope, if that's already done, then we can go ahead and close this
