### ISSUE TITLE
Doesn't connect to upstream endpoint when environment variable is used

### ISSUE THREAD

**Issue by tejas-sme** [oauth2-proxy/oauth2-proxy#1035]
Doesn't connect to upstream endpoint: I have a simple nginx running behind oauth2-proxy. I am using Keycloak as OIDC provider. Authentication works happily but I always end up with "404 page not found" as the response in my browser and I see no requests against my upstream endpoint at all.

Here is what I found:
It does not work when I use `OAUTH2_PROXY_UPSTREAM` environment variable. It works fine if I use command line parameter `--upstream` I've verified this behavior with other applications too. So it seems there a bug in the code which ignores `OAUTH2_PROXY_UPSTREAM` environment variable

## Expected Behavior

`OAUTH2_PROXY_UPSTREAM` should behave the same way as `--upstream` parameter

## Current Behavior

Fails to reach the application after being authenticated via keycloak.

## Your Environment
- Oauth2-proxy version: 7.0.0
- Keycloak version: 11.0.0
- Environment variables....
OAUTH2_PROXY_PROVIDER keycloak
OAUTH2_PROXY_CLIENT_ID	<client_id>
OAUTH2_PROXY_CLIENT_SECRET	<client_secret>
OAUTH2_PROXY_COOKIE_SECRET  <cookie_secret>
OAUTH2_PROXY_LOGIN_URL	https://<keycloak server url>/auth/realms/INTERNAL/protocol/openid-connect/auth
OAUTH2_PROXY_REDEEM_URL https://<keycloak server url>/auth/realms/INTERNAL/protocol/openid-connect/token
OAUTH2_PROXY_PROFILE_URL  https://<keycloak server url>/auth/realms/INTERNAL/protocol/openid-connect/userinfo
OAUTH2_PROXY_VALIDATE_URL https://<keycloak server url>/auth/realms/INTERNAL/protocol/openid-connect/userinfo
OAUTH2_PROXY_EMAIL_DOMAINS	*
OAUTH2_PROXY_HTTP_ADDRESS	0.0.0.0:8080
OAUTH2_PROXY_SCOPE	openid
# this doesn't work
#OAUTH2_PROXY_UPSTREAM	http://nginx:8000

**Comment by NickMeves** [comment]
The `--upstream` flag is an array config option, so it can be specified multiple times on the command line.

For array flags in config or envvar format, they are pluralized.

You need to add an `S` - `OAUTH2_PROXY_UPSTREAMS`

**Comment by tejas-sme** [comment]
Setting `OAUTH2_PROXY_UPSTREAMS` worked for me.
