### ISSUE TITLE
OAuth2 Proxy Specific ID Token from SessionState - Replacing Gap-Signature

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#1036]
Let's serialize all the various parts of our session into an OAuth2 Proxy signed ID Token (sub, email, groups, iat, exp) that we can pass to the upstream applications in a user configured header (e.g. Authorization or X-*).

This can replace the legacy GAP-Signature functionality that uses symmetric keys to sign specific headers to provide trust between the proxy and the upstream layer

## Expected Behavior

We turn the SessionState into a barebones valid OIDC ID Token with the `RS256` alg. To support the backends consuming and validating the signature, we add 2 new OIDC endpoints to the proxy: `/oauth2/.well-known/openid-configuration` & `/oauth2/.well-known/jwks.json`.

The discovery document would be barebones & look like this that AWS IRSA uses for machine generated ID Tokens: https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#create-the-oidc-discovery-and-keys-documents

## Current Behavior

Identity is passed to the upstream servers with `X-Forwarded-*` headers, while trust is done (if desired, but rarely used) with the header signatures. Original IdP information can be used by sending their ID Token to the backend, but that leads to inconsistent tokens in the backend potentially.

This can replace the header signature implementation, while augmenting the mechanisms we support to transmit authorization details on the user to the upstream server.

**Comment by JoelSpeed** [comment]
How would this work where we currently forward ID Tokens and Access Tokens, are we going to have to capture those into our new ID Token as well? 

How do you plan to support key sharing between multiple OAuth2 Proxy instances? Each instance will need to have access to the same keys, and if they need rotating, that will mean some central store for the keys right?

**Comment by NickMeves** [comment]
In the future structured configs, what type of data into which header was completely customizable right? I had envisioned Access vs ID vs This Internal would be config driven for what type of header it would go into.

And yeah, horizontally scaled instances would need to use the same private key (similar to needing the same signature secret at the moment). 🤔 

The rotation aspect of that is tough in environments that aren't easy like Kubernetes mounting a TLS Secret.

The JWKS could somehow support multiple public keys (common keys but during rotation, it stores all keypairs seen since startup even if they refresh with a TLS refresher handler to a new private key file)... but all nodes would need to be aware of that new key promotion at the same time.

Or we do purely with configs and have users explicitly set public keys (so they can prestage rotation keys of old + new).

**Comment by NickMeves** [comment]
Actually, after thinking through -- I think I like the ability to explicitly spell out the public keys (multiple allows to support rotations).

Then we'll use all that are supplied in the JWKS we build out (rather than only requiring the private key and trying to figure out the public key from it).

More setup required on the user perspective, but will graceful handle both horizontal scalability & rotations.

Would sacrifice the convenience of potentially coding it with a cert fresher handler to automatically pick up if something like Kubernetes refreshed a mounted secret if it changed -- but is ready for no issue rotations (which auto-refresher would not handler gracefully between nodes).

**Comment by JoelSpeed** [comment]
> Kubernetes refreshed a mounted secret

Kubernetes doesn't do this, once a secret has been mounted it won't be refreshed if it changes, so the multiple certs idea sounds reasonable to me

**Comment by NickMeves** [comment]
> > Kubernetes refreshed a mounted secret
> 
> Kubernetes doesn't do this, once a secret has been mounted it won't be refreshed if it changes, so the multiple certs idea sounds reasonable to me

I haven't tried, but I thought it might refresh is done with a projected volume? (since other projected volume types get the content dyncamically refreshed from the kubelet where applicable)

https://kubernetes.io/docs/concepts/storage/volumes/#secret (not sure if that `subPath` note means refreshing isn't possible in all cases with secrets or just that case).

**Comment by JoelSpeed** [comment]
> but I thought it might refresh is done with a projected volume?

I was under the impression there was some security reason that meant they didn't ever refresh, but I haven't tried with projected volumes, it may be different. Maybe I'm just wrong altogether, going to have to go and check now 🤔
