### ISSUE TITLE
allowed_groups provider configuration for azure

### ISSUE THREAD

**Issue by virtrixke** [oauth2-proxy/oauth2-proxy#1040]
## Expected Behavior

- There is no current documentation on the allowed_groups/allowed-group flag usage for the azure auth provider.
- It would be nice to have a decent example configuration.

## Current Behavior

I would like to add the allowed_groups flag using something like this:

```
provider = "azure"
client_id = "<client id>"
client_secret = "<client secret>"
cookie_secret = "<cookie secret>"
email_domains: [
  "*"
]
allowed_groups: [
  "54648-ccf3-485d-9898-8789gf98778"
]
```
The config works perfectly without the allowed_groups flag in the config. 
When it is added I always get a 403 access denied.
Docs refers to two different azure sections (?) but the explanation is very limited.

I added the claims for **applicationgroup** and **securitygroups** in the manifest in the azure app registration.
I also added the **user.read** and **groupmembership.read.all** options

- Version used: v7.0.0

**Comment by NickMeves** [comment]
Azure doesn't support this flag. We'll need an Azure user in the community to make a PR giving the azure provider authorization capabilities.

Allowed groups was new in v7 for OIDC and we backported it to other providers that had hacked in authorization logic themselves before it was a standard in v7.

**Comment by jdthorpe** [comment]
Related question / suggestion: It seems like using the `roles` attributes instead of the `groups` attribute should be trivial.  For example, I have a user with a JWT like this: 

```json
{
  "aud": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "iss": "https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/",
  "iat": 1616010166,
  "nbf": 1616010166,
  "exp": 1616014066,
  "amr": [
    "rsa",
    "mfa"
  ],
  "family_name": "Doe",
  "given_name": "Jane",
  "name": "Jane Doe",
  "oid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "rh": "0.xxxxxxxxxxxxx0GRqy180BHbR7EkkCXUtKRPgPKFKSFWlmkaANk.",
  "roles": [
    "cats",
    "dogs"
  ],
  "sub": "xxxxxxxxxxxxxCIrH5AdRCLx6FDpKui2n0VsceEBB8A",
  "tid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "unique_name": "janedoe@helloworld.com",
  "upn": "janedoe@helloworld.com",
  "uti": "xxxxxxxafkeJka_QIJ2SAA",
  "ver": "1.0"
}
```

and would like to validate against the user's assigned roles.  However, these options result in a 403: 

```sh
    --allowed-group=dogs
    --oidc-groups-claim=roles
```
