### ISSUE TITLE
Oauth2 Proxy - OIDC (DEX) Scope Not delivering groups.

### ISSUE THREAD

**Issue by psreddy22** [oauth2-proxy/oauth2-proxy#1042]
Hello Experts,

Thanks for your help in advance.

Configured oauth2-proxy in-front of kubernetes-dashboard ingress & DEX as OIDC. 

Able to authenticate & login successfully. 
Group Names are mentioned in Clusterrolebinding But only Users in CRB are allowed to see dashboard but not other group members.

From the DEX logs, found something like - not delivering groups. OIDC scope is limited to email, profile. 

I tried with adding below scope options for OIDC config, but didn't work.
scope = "openid, profile, email, groups" 

Error logs :-
level=error msg="Failed to parse authorization request: Missing required scope(s) [\"openid\"]."
level=error msg="Failed to parse authorization request: Missing required scope(s) [\"openid\"]."
level=error msg="Failed to parse authorization request: Missing required scope(s) [\"openid\"]."

- Version used:
 V6.1.1

**Comment by JoelSpeed** [comment]
Scope is a space separated list not a comma separated list, try `scope = "openid profile email groups"` instead

**Comment by psreddy22** [comment]
@JoelSpeed Thank you very much. You made my day. I tried all the options separated with comma(,).

Once again thank you very much!!
