### ISSUE TITLE
Google OAuth flow fails in 7.0.1 because redirect_uri doesn't have a scheme

### ISSUE THREAD

**Issue by hoffrocket** [oauth2-proxy/oauth2-proxy#1044]
Google does not allow an OAuth `redirect_uri` in the form of `//host/path`

## Expected Behavior

After click the "Sign in with Google" button I would expect to see a google sign-in page

## Current Behavior

Instead of a Google sign-in page I see a Google error screen with this text:

```
Authorization Error
Error 400: invalid_request
Invalid parameter value for redirect_uri: Missing scheme: //mysite.com/oauth2/callback
``` 

## Possible Solution

This was working as expected in version 6.1.1, but the behavior has changed in 7.0.1. I know that I can specify the redirect-url in the configuration as workaround (or stick with 6.1.1)

## Steps to Reproduce (for bugs)

1. Create a Google Oauth2 application
2. Start up a 7.0.1 proxy with these params: `--upstream=http://xxx:8000/ --http-address=0.0.0.0:4180 --cookie-secret xxx --email-domain=xxx.com --client-id=XXX.apps.googleusercontent.com --client-secret=XXX`
3. visit the proxy URL and click "Sign in with Google"

## Context

This is not blocking me right now, but seems like a regression.

## Your Environment

OSX Docker Host
Running this docker image: `quay.io/oauth2-proxy/oauth2-proxy@sha256:15eaf47e0ca8b15d668f5cb5da67f028abe251a2855a6b1c9344080c5735b59a`

Upstream is another docker app managed by docker-compose

- Version used: 7.0.1

**Comment by JoelSpeed** [comment]
@NickMeves This logic for this was changed during #964, any obvious ideas why this might have broken?

**Comment by JoelSpeed** [comment]
Looks like we used to check if the scheme was empty (in `getOAuth2RedirectURI`) and default it to `http`, but lost that logic during #964

**Comment by JoelSpeed** [comment]
@hoffrocket Are you using OAuth2 Proxy on a `http` or `https` scheme ultimately? I'm raising a PR to restore the original behaviour but am intrigued what scheme was being sent to google and what scheme you are using, looking at the logic it infers google would have received plain `http`, not secure

**Comment by hoffrocket** [comment]
> @hoffrocket Are you using OAuth2 Proxy on a `http` or `https` scheme ultimately? I'm raising a PR to restore the original behaviour but am intrigued what scheme was being sent to google and what scheme you are using, looking at the logic it infers google would have received plain `http`, not secure

I tried both-- localhost with http and https on a public domain name

**Comment by grimurd** [comment]
Have same problem with keycloak provider, changing back to 6.1.1 fixed it.

redirect_uri is set to //internal.domain.com/oauth2/callback

**Comment by NeoTechni** [comment]
I am having the same problem, even using the URIs from the JSON credentials file 

"urn:ietf:wg:oauth:2.0:oob" and "http://localhost"

I am making a desktop app! I shouldn't even need a redirect URI, since it won't be redirecting to it
