### ISSUE TITLE
Enable m2m authentication via client credentials grant

### ISSUE THREAD

**Issue by adevnoob** [oauth2-proxy/oauth2-proxy#1046]
Hi,

m2m authentication became very important for my current project.
I did not found any proxy alternatives regarding the m2m-auth-issue. So it would be great if oauth2-proxy would be enabled for this.

Considering the rfc 6749 there are 2 requests necessary for the client:

Token-Request:

```
curl -X POST "https://[Auth-Server-Host]/token" \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=[clients name]' \
--data-urlencode 'client_secret=[clients secret]' \
--data-urlencode 'grant_type=client_credentials'
```

You'll get an access token with valid credentials. No user is involved in this request.

```
curl -X GET "https://[Application-Host]/protectedResource" \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIA.shortened'
```

I'm not sure with the endpoint for the token-validation. Looking at the Keycloak-Provider it could be solved against the token-introspection endpoint, right?

In case of a valid token an active-key would be sent in a json-body with boolean value.

Because [issue 811](https://github.com/oauth2-proxy/oauth2-proxy/issues/811) is closed I have created this new issue.

**Comment by p53** [comment]
@adevnoob you can use https://github.com/gogatekeeper/gatekeeper

**Comment by adevnoob** [comment]
@p53 Thank you for the fast reply. I'll test gogatekeeper as you suggested.

**Comment by adevnoob** [comment]
> @p53 Thank you for the fast reply. I'll test gogatekeeper as you suggested.

**Comment by adevnoob** [comment]
(The closing before happend accidentally)

> @adevnoob you can use https://github.com/gogatekeeper/gatekeeper, it does use resource owner grant but we are planning to add also client credentials grant

I tried the gogatekeeper with these params:
```
      - --listen=0.0.0.0:8090
      - --upstream-url=http://127.0.0.1:8080
      - --discovery-url=https://our.keycloak-host.de/auth/realms/test-realm/.well-known/openid-configuration
      - --client-id=m2m-test
```

It should work in my opinion but unfortunately doesn't.

I requested a token:

```
curl -X POST 'https://app-host-with-proxy.de/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=m2m-test' \
--data-urlencode 'client_secret=z7g50e21-40a6-4p66-999c-3384da9c79b4' \
--data-urlencode 'grant_type=client_credentials'
```

**Comment by adevnoob** [comment]
> (The closing before happend accidentally)
> 
> > @adevnoob you can use https://github.com/gogatekeeper/gatekeeper, it does use resource owner grant but we are planning to add also client credentials grant
> 
> I tried the gogatekeeper with these params:
> 
> ```
>       - --listen=0.0.0.0:8090
>       - --upstream-url=http://127.0.0.1:8080
>       - --discovery-url=https://our.keycloak-host.de/auth/realms/test-realm/.well-known/openid-configuration
>       - --client-id=m2m-test
> ```
> 
> It should work in my opinion but unfortunately doesn't.
> 
> I requested a token:
> 
> ```
> curl -X POST 'https://app-host-with-proxy.de/' \
> --header 'Content-Type: application/x-www-form-urlencoded' \
> --data-urlencode 'client_id=m2m-test' \
> --data-urlencode 'client_secret=z7g50e21-40a6-4p66-999c-3384da9c79b4' \
> --data-urlencode 'grant_type=client_credentials'
> ```

I got:
` error    no session found in request, redirecting for authorization    {"error": "authentication session not found"}`

The request directly against Keycloak gave me an access token. So the configuration of the client seems to be correct regarding client-credential grant.

**Comment by p53** [comment]
@adevnoob as i said currently client credentials grant isn't supported (but it is in plan in few weeks/month), right now you can use grant_type=password (you need to set up this also in keycloak)

**Comment by NickMeves** [comment]
I wrote a blog post on this topic in case you can use this architecture to fit you m2m use cases: https://medium.com/in-the-weeds/service-to-service-authentication-on-kubernetes-94dcb8216cdc

**Comment by rstoermer** [comment]
Any news on this? Is this supported in some way now?

**Comment by ksaadDE** [comment]
#2944 #2966
