### ISSUE TITLE
Basic auth is broken when using the new allowed-group configuration

### ISSUE THREAD

**Issue by stefansedich** [oauth2-proxy/oauth2-proxy#1051]
When using the new allowed-group feature in combination with basic auth, the basic auth will initially succeed but then the session will be removed due to what I assume is the groups validation check running.

## Expected Behavior

For basic auth to continue to work even when allowed-groups is set.

## Current Behavior

The basic auth will initially succeed but then when the groups check logic runs the session will be removed and access will be deined.

## Possible Solution

I am not sure yet need to dig back into this as it has been a while since I submitted the PR for allowed-groups.

## Steps to Reproduce (for bugs)

1.  Enable basic auth using an htpasswd file
2.  Configure the proxy using an allowed-group
3.  Attempt to authenticate using the username/password using Basic auth
4.  Denied

## Context

This is a regression I introduced with my changes in https://github.com/oauth2-proxy/oauth2-proxy/pull/616 I am going to look into a fix but am opening this issue for visibility into the bug.

## Your Environment

- Version used: 7.0.1

**Comment by stefansedich** [comment]
Looks like ALOT has changed since my original PR :laughing: will take me a while to catchup on the changes and get digging.

**Comment by stefansedich** [comment]
So the quickest fix I can think of is to support an `--basic-auth-groups` option which would add those groups to the Session for a basic auth request.

The main issue from what I can tell right now is we go through the session chain, get the validated basic auth session, then later on call `provider.Authorize` which performs the authz on the provider itself.

The other option could be to perhaps flag the session `IsBasicAuth` or something, and then skipping the provider authz if that is set.

Does anyone have any thoughts here?

**Comment by stefansedich** [comment]
@JoelSpeed any thoughts here? the current option I think is simplest is that we just append all `AllowedGroups` to the session created for the basic auth request.

This assumes that basic auth is intended to bypass any group validation which for us is the case.

**Comment by NickMeves** [comment]
> Looks like ALOT has changed since my original PR 😆 will take me a while to catchup on the changes and get digging.

LOL - we had a large gap between `v6.1.1` and `v7.0.0` since once you broke the seal on AuthZ support, we really wanted to get the support for it streamlined everywhere with the major release.

**Comment by NickMeves** [comment]
So I think we somehow need to allow group assignment to `htpasswd` based usernames that use basic auth (so we can set the `Group` field in the session in the `middleware/basic_session.go` instead of only setting `User` (how does that even work with `email-domains` -- are you forced to set that to `*` since there is no email 🤔 )

I don't think bypassing authorize for htpasswd is appropriate, it should fall under that purview (and hence have some sort of group).

There's optional parameters to things like `/oauth2/auth` where in shared environments you can specify stricter specialized `allowed_group` settings (hence you can't assume if they were in an htpasswd we allow them anyway).

**Comment by NickMeves** [comment]
Alternatively -- we could pick a static group that all htpasswd basic users get assigned to (and set in the `session.Group` we make for them) 🤔 

Then if you want to support that & allowed_groups with your main provider, you just have to spell out the hardcoded basic group name.

This might be the easiest way to support this without breaking stuff.

**Comment by NickMeves** [comment]
> So the quickest fix I can think of is to support an `--basic-auth-groups` option which would add those groups to the Session for a basic auth request.

Lol -- I should read more closely, the static group thing is essentially what you are proposing 😅 

I think this is the best route.

**Comment by stefansedich** [comment]
> > So the quickest fix I can think of is to support an `--basic-auth-groups` option which would add those groups to the Session for a basic auth request.
> 
> Lol -- I should read more closely, the static group thing is essentially what you are proposing 😅 
> 
> I think this is the best route.

OK awesome! I felt this one was safest, PR incoming!

**Comment by JoelSpeed** [comment]
So while I think this is probably the best approach, my only concern is the naming. `--basic-auth-groups` doesn't suggest to me that this is a set of groups to add to the basic auth users defined in the `htpasswd` file 🤔 

That said, I don't have a better suggestion right now 😞 

The alternative is to do something like what [Dex does](https://github.com/dexidp/dex/blob/0f68fadb9ade1cc4cac2ccd9e40b78e4a4588638/examples/config-dev.yaml#L136-L142) and allow you to build out your users inline, in the config file, this may be better in the long term as we move towards structured configuration

**Comment by NickMeves** [comment]
This merged - Thanks!

**Comment by stefansedich** [comment]
> This merged - Thanks!

Thanks :tada:! when can we expect a point release to go out?

**Comment by NickMeves** [comment]
We are feeling like we have a good critical mass of features to release a minor version (v7.1.0) when we next meet up in a couple of weeks.
