### ISSUE TITLE
Support private_key_jwt in OIDC Provider

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#1062]
The `private_key_jwt` authentication method (as opposed to the client secret) in the OIDC spec seems to be the only aspect we are missing from our OIDC implementation that the LoginGov provider requires that we can't meet with the OIDC Provider

## Expected Behavior

Let's support that `private_key_jwt` in the generic OIDC Provider so LoginGov (and any other IdPs that support it) can use it. 
 And then let's look to deprecate LoginGov.

## Current Behavior

Only client secret token redeem authentication is supported.

## Possible Solution

https://kb.authlete.com/en/s/oauth-and-openid-connect/a/client-auth-private-key-jwt

Look at existing LoginGov provider for implementation details.

## Context

Let's simplify the codebase, specifically in the Providers which have a lot of duplication.

**Comment by NickMeves** [comment]
CC: @timothy-spencer

With this plus nonce support in this PR: https://github.com/oauth2-proxy/oauth2-proxy/pull/967 -- Is their anything else missing from the generic OIDC Provider that Login.gov needs?

**Comment by ghermana** [comment]
Could not find a way to use private_key_jwt with OIDC. Am I missing something? The issue still seems open

**Comment by tuunit** [comment]
Hi @ghermana,

yes this indeed was never implemented. A PR was recently opened: https://github.com/oauth2-proxy/oauth2-proxy/pull/2305

**Comment by ghermana** [comment]
Thank you for the link @tuunit , please let me know if there is anything that can be done to help with the PR

**Comment by tuunit** [comment]
@ghermana if you want to, give it a code review and / or build the branch locally and test if it works for your use case as well.
