### ISSUE TITLE
Impossible to use fixed Basic Auth username with Alpha Options

### ISSUE THREAD

**Issue by alice-sawatzky** [oauth2-proxy/oauth2-proxy#1067]
## Expected Behavior

It would be much more convenient if the user could set a fixed Basic Auth username in a [HeaderValue](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config#headervalue) object, perhaps using the `value` field.

## Current Behavior

Currently the only source for a Basic Auth username in the [HeaderValue](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config#headervalue) object is `claim`, which is dynamically filled by oidc claim values.

## Context

The goal is to provide the functionality discussed in https://github.com/oauth2-proxy/oauth2-proxy/pull/804. Currently the only way to accomplish this is to generate a fully encoded Authorization header value and set that, which is a pain.

**Comment by JoelSpeed** [comment]
It was always intended that if you wanted to set a static value (which is essentially what you're asking for here), then you would generate that value and set it yourself in the `fromValue`. It should just be a case of `echo -n $name:$password | base64` to get the string you need.

This is currently undocumented though as it is an alpha feature and may change.

Did you have issues generating the string?

**Comment by alice-sawatzky** [comment]
i don't, it's just a pain when the app has the ability to generate the string itself, and leads to a less transparent config file. i suppose the issue title should've been "inconvenient", not "impossible"
