### ISSUE TITLE
Compare Azure Auth Provider vs Microsoft Azure AD Provider

### ISSUE THREAD

**Issue by MNF** [oauth2-proxy/oauth2-proxy#1073]
In the documentation page https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider there are sections 
 Azure Auth Provider and Microsoft Azure AD Provider.
Are they describe two different implementations fro the same Azure AAD providers?
It will be good to keep them next to each other in the document , explain the differences and add the recommendation when one or another should be used

**Comment by JoelSpeed** [comment]
AFAIK, we only have the one provider, hadn't noticed it's in the docs twice though, we should clean that up and consolidate the two blocks

**Comment by michael-freidgeim-webjet** [comment]
re-activate the issue

**Comment by kmcrawford** [comment]
Thanks I had the same question.

**Comment by michael-freidgeim-webjet** [comment]
re-activate the issue.

**Comment by pierluigilenoci** [comment]
@JoelSpeed I'm not able to remove the stale. 😞

**Comment by MNF** [comment]
re-activate the issue.

**Comment by pierluigilenoci** [comment]
@JoelSpeed again please.
