### ISSUE TITLE
Can a single instance of oauth proxy be used at a login domain so there's only one redirect url for several apps?

### ISSUE THREAD

**Issue by farcaller** [oauth2-proxy/oauth2-proxy#1074]
I got a k8s + istio setup with several internal resources that I protect with oauth2-proxy. The latter is used in the static:// mode, paired with istio's ExtAuthn (so oauth2-proxy only validates the cookie and does redirects, otherwise passing the JWT back to istio to handle).

## Expected Behavior

1. User visits myapp.example.com
2. Istio calls oauth2-proxy to verify the cookie
3. Oauth2-proxy cannot validate the cookie so it saves the original request url in the session and redirects to oauth.example.com
4. Istio serves the same oauth2-proxy on oauth.example.com, oauth2-proxy does the login redirect now from the authorized origin being oauth.example.com with a redirect set to e.g. oauth.example.com/oauth2/callback
5. OAuth happens
6. Istio serves the same oauth2-proxy on oauth.example.com/oauth2/callback, oauth2-proxy finishes the OAuth flow, sets the cookie for example.com and redirects back to myapp.example.com
7. User sees myapp.example.com and step [2] passes now as the request has a valid cookie

## Current Behavior

1. User visits myapp.example.com
2. Istio calls oauth2-proxy to verify the cookie
3. Oauth2-proxy cannot validate the cookie so it does the login redirect now from the authorized origin being myapp.example.com with a redirect set to e.g. myapp.example.com/oauth2/callback

Thus I have to include every single app's origin and redirect url in the oauth provider.

**Comment by JoelSpeed** [comment]
You'll need to set the final redirect when you start the authentication flow using the `rd` query string parameter or `X-Auth-Request-Redirect` header, and you'll also need to use the whitelist-domain option to allow the redirect domains you need (this can be any subdomain under a domain).

I know this works with nginx, so it should work with istio but I've not done this myself so can't help you set that particular bit up

**Comment by jpugliesi** [comment]
@farcaller did you ever successfully configure this redirect with istio?
