### ISSUE TITLE
Is there an option to fetch client-secret stored in Hashicorp valut from oauth2-proxy deployment file.

### ISSUE THREAD

**Issue by r-kotagudem** [oauth2-proxy/oauth2-proxy#1075]
@JoelSpeed  @NickMeves 

Could someone please let me know if this is possible ?

Current state:  hard coding client-secret in oauth2-proxy deployment file.

required state: able to pull client-secret from Hashicorp valut(secrets manager) and refer it in deployment file.

**Comment by NickMeves** [comment]
This is on our backlog once structured configs go out in v8: https://github.com/oauth2-proxy/oauth2-proxy/issues/864

We would need help from the community adding support for Vault to that `SecretSource` paradigm.

**Comment by JoelSpeed** [comment]
In the mean time you can provide the client secret via a file, if that might help? I think there are solutions out there that allow you to sync vault secrets to a file on the system 🤔

**Comment by r-kotagudem** [comment]
Thanks for help!

our organization enforces teams to use central vault location to store the passwords/secrets. Also fortify scanner would not allow build to be succesful with plain text passwords in the deployment file(source code).

The approach we followed.

added a script in the build/deployment pipeline, where it pulls client-secret from vault and creates a kubernetes secret which is referred from oauth2-proxy deployment file.

That way  we dont hardcode client-secret in oauth2-proxy deployment file.

**Comment by NickMeves** [comment]
> added a script in the build/deployment pipeline, where it pulls client-secret from vault and creates a kubernetes secret which is referred from oauth2-proxy deployment file.
> 
> That way we dont hardcode client-secret in oauth2-proxy deployment file.

This is the best practice in the current style configs. 👍 

If we don't have this pattern documented, maybe we should. Even with everything else from config or flags, at least `client-secret` (& likely `cookie-secret`) should be set with an `OAUTH2_PROXY_*` style envvar and set on the container from a Secret from Kubernetes (or mounting the secret to a volume if you want to go the secret file route).
