### ISSUE TITLE
--allowed-group docs.. Role/Group Based Access with keycloack

### ISSUE THREAD

**Issue by LordEvron** [oauth2-proxy/oauth2-proxy#1078]
Hi, 
I have configured keycloak with two roles:  "admin" and "user". I have also two upstreams "/admin" and "/user". I would like to setup oauth2 to allow "admin" role to access both the upstreams, while user role should only access "/user" 
I notice that there is an already PR  https://github.com/oauth2-proxy/oauth2-proxy/pull/767  asking this. Is there any timeline, when this feature will be available? 

I also notice that there is a parameter called **--allowed-group** . Can I set up oauth2 to use keycloak groups instead of roles to achieve the same behavior? If yes, there is any example on how to configure this simple case?

**Comment by JoelSpeed** [comment]
We were talking about integration OPA into the proxy to allow complex Authz rules such as this, but for the moment, we don't really have anything that would support this. We also don't have a timeline for integrating this as we haven't had much chance to look into new features like this. For now you can only have one set of authz rules for all users.

**Comment by kfox1111** [comment]
OPA would be really flexible for this use case, yeah.
