### ISSUE TITLE
Add ability to search on the Docs site.

### ISSUE THREAD

**Issue by MNF** [oauth2-proxy/oauth2-proxy#1081]
It will be good if on https://oauth2-proxy.github.io/oauth2-proxy/docs/  ability to search the Docs site will be available

**Comment by JoelSpeed** [comment]
Looks like we can do this (https://v2.docusaurus.io/docs/search) but will need myself or @NickMeves to set up an algolia index. Will try and get this set up over the next week or so

**Comment by MNF** [comment]
Alternatively you can utilise google search, e.g. similar to https://nsubstitute.github.io/help/search/

**Comment by michael-freidgeim-webjet** [comment]
re-activate the issue.

**Comment by MNF** [comment]
re-activate the issue

**Comment by michael-freidgeim-webjet** [comment]
re-activate the issue.

**Comment by MNF** [comment]
re-activate the issue

**Comment by michael-freidgeim-webjet** [comment]
the issue is still relevant

**Comment by MNF** [comment]
the issue is still relevant

**Comment by michael-freidgeim-webjet** [comment]
@JoelSpeed , the issue is not completed,
 github-actions bot should not close this as [completed](https://github.com/oauth2-proxy/oauth2-proxy/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted)

**Comment by MNF** [comment]
@JoelSpeed , you should change github-actions bot message, as  the issue is  not [completed](https://github.com/oauth2-proxy/oauth2-proxy/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted).
 Better to describe the reason as inactive.

**Comment by michael-freidgeim-webjet** [comment]
@JoelSpeed see input option https://github.com/actions/stale#close-issue-message
