### ISSUE TITLE
Doesn't build from source

### ISSUE THREAD

**Issue by realindiahotel** [oauth2-proxy/oauth2-proxy#1082]
## Expected Behavior

Using command `go get github.com/oauth2-proxy/oauth2-proxy/v7`

## Current Behavior

Errors with message: `
GO111MODULE=on CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags="-X main.VERSION=v7.0.1-31-g220b370-dirty" -o oauth2-proxy github.com/oauth2-proxy/oauth2-proxy/v7
pkg/app/pagewriter/sign_in_page.go:5:2: package embed is not in GOROOT (/usr/local/go/src/embed)
`

## Steps to Reproduce (for bugs)

Run command in expected behavior which is from the v7 documentation

## Context

Can no longer build from source (`make oauth2-proxy` now also gives same error message).

## Your Environment

Ubuntu Server 20.04

- Version used: v7.0.1 (master branch)

**Comment by realindiahotel** [comment]
I fixed it by setting my goroot and gohome env variables, make oauth2-proxy still doesn't work but the go get seems to work

**Comment by JoelSpeed** [comment]
You will need to be on Go 1.16 to use the latest code in master, that's why the embed warning is coming up when you try to go get

**Comment by realindiahotel** [comment]
> You will need to be on Go 1.16 to use the latest code in master, that's why the embed warning is coming up when you try to go get

Setting `go env -w GO111MODULE=on` seems to fix it I didn't update my go but it works after doing that

**Comment by realindiahotel** [comment]
@JoelSpeed so it's really strange, setting `go env -w GO111MODULE=on` allows me to get it to build using go get with go 1.15 installed, but `make oauth2-proxy` still failed. Updating to go 1.16 fixes `make oauth2-proxy` for me and now both work go get and make.

Thanks
