### ISSUE TITLE
X-Forwarded-Groups not passed to upstream headers

### ISSUE THREAD

**Issue by opteemister** [oauth2-proxy/oauth2-proxy#1085]
We need to get group names assigned to the Google user logged via Oauth proxy. 

## Expected Behavior

Upstream will have headers set:
`X-Forwarded-User`
`X-Forwarded-Email`
`X-Forwarded-Group`

## Current Behavior

Upstream have only headers:
`X-Forwarded-User`
`X-Forwarded-Email`

## Steps to Reproduce (for bugs)

We use Google as an OAuth provider and set parameters:
"--pass-user-headers=true"
"--pass-basic-auth=true"

## Context
From [current doc](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/) there is a note about that X-Forwarded-Groups should be passed if we set --pass-user-headers, and from [RELEASE NOTES](https://github.com/oauth2-proxy/oauth2-proxy/blob/220b3708fc4e1de5e30135b48c8d8a2ef7efd518/CHANGELOG.md#important-notes-2) also was added related to [that case](https://github.com/oauth2-proxy/oauth2-proxy/pull/797)

Also in a code I can see that this header can be set https://github.com/oauth2-proxy/oauth2-proxy/blob/220b3708fc4e1de5e30135b48c8d8a2ef7efd518/pkg/apis/options/legacy_options.go#L257

But in help description [here ](https://github.com/oauth2-proxy/oauth2-proxy/blob/220b3708fc4e1de5e30135b48c8d8a2ef7efd518/pkg/apis/options/legacy_options.go#L163) and directly from --help command we can see that pass-user-headers pass only X-Forwarded-User and X-Forwarded-Email information to upstream

And in fact it returns only X-Forwarded-User and X-Forwarded-Email headers

- Version used: v7.0.1 (quay.io/oauth2-proxy/oauth2-proxy:latest)

Could you please clarify what we doing wrong? Or there is a bug in a code? Thank you

**Comment by arnoldfranz** [comment]
I have the same issue. I can't get the Tokens from Azure in the headers. There are several bug reports related to similar problems, but I have not managed to make it working (yet :-))

**Comment by NickMeves** [comment]
`X-Forwarded-Groups` is new and will only be sent for Providers that have implemented the functionality.

Azure might happen in this PR: https://github.com/oauth2-proxy/oauth2-proxy/pull/1061

Google is special with groups: we don't get groups automatically, it only queries for them to do an authorization check (and then include in X-Forwarded-Group) if you use the `--google-group` flow (or the new `allowed-group` flag). And it will only list off Groups we query for, it doesn't pull all the user groups.

The Google provider is quite old and the Groups implementation needs an overhaul to be honest 😅

**Comment by opteemister** [comment]
That makes sense. Thank you for clarification
