### ISSUE TITLE
Does Oauth2-Proxy pass group filed in the headers with X-Forwarded-Groups or X-Auth-Forwarded-Groups ?

### ISSUE THREAD

**Issue by chandu412** [oauth2-proxy/oauth2-proxy#1088]
Does Oauth2-Proxy pass group filed in the headers with X-Forwarded-Groups or X-Auth-Forwaded-Groups ?

## Expected Behavior

Oauth-2 Should sent the group values as a header 
Ex:  X-auth-Forwarded-Groups: [/group1,/group2,/group3...]

## Current Behavior

X-Auth- Forwarded-group is not begin set 

Can anyone please is there any possible way to get the values in headers to pass it to nginx ingress ?

If this does not support this mechanism, is there any other way to get these values ?

Thanks in Advance !!!!

**Comment by JoelSpeed** [comment]
You should be able to get an `X-Forwarded-Groups` header back when using the `--pass-user-headers` option, however, you'll need to be using a provider that supports groups. Which provider are you using currently?

**Comment by chandu412** [comment]
@JoelSpeed, Thanks for your response Joel.

We are using keycloak provider.

please find our configuration that we are using..
-----------------------------------------------------------
  - --http-address=0.0.0.0:4180
    - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
    - --client-id=test
    - --client-secret=<secret>
    - --login-url=https://xxx/auth/realms/realm-name/protocol/openid-connect/auth
    - --provider=keycloak
    - --provider-display-name=Login
    - --redeem-url=https://xxx/auth/realms/realm-name/protocol/openid-connect/token
    - --set-xauthrequest=true
    - --email-domain=*
    - --cookie-secure=false
    - --validate-url=https://xxx/auth/realms/realm-name/protocol/openid-connect/userinfo
    - --keycloak-group=/nexus
    - --keycloak-group=/jenkins
    - --keycloak-group=/sonar
    - --redirect-url=https://xxx/oauth2/callback
    - --oidc-issuer-url=https://xxx/auth/realms/realm-name
    - --insecure-oidc-allow-unverified-email=true
    - --email-domain=example.com
    - --pass-user-headers=true
    - --cookie-name=testcookie
    - --cookie-secret=testcookiesecretkey
    - --pass-access-token=true
    - --pass-user-headers=true
    - --pass-authorization-header=true

**Comment by JoelSpeed** [comment]
This should work with the keycloak provider, however, I might suggest you try the OIDC provider instead. Keycloak is OIDC compatible and our OIDC provider works a lot better than the keycloak provider. I'd be interested to see if it works if you just switch provider?

Otherwise, if you have some time to check, we get group information from the userinfo endpoint, could you check what the structure of this is and check for the `groups` key?

**Comment by chandu412** [comment]
Hi Joel @JoelSpeed Thanks for the response and info, we are testing few scenarios, will come back to you soon with the updates

**Comment by chandu412** [comment]
@JoelSpeed We tested with oidc provider but its still didn't worked out.   It is not populating the group field in the headers

We tried hitting /userinfo end point it is not giving the group details, it is only providing email and user name

**Comment by arkadijs** [comment]
No Groups header for me too.
We're running the proxy with OIDC provider against Dex which in turn is running with Microsoft provider that supports and configured to read groups.

**Comment by arkadijs** [comment]
It looks like `X-Forwarded-Groups` is conditioned either on `--allowed-group` flag presence or setting `--scope=openid profile email groups` explicitly.

**Comment by JoelSpeed** [comment]
If you do not have `groups` in the scope parameter, then Dex won't include groups (most IDP providers won't), so yes, this is a necessity for using the groups headers, we can only populate them if the IDP send them to us

**Comment by arkadijs** [comment]
I would be nice to have a bit of documentation for this. By browsing the issue tracker it looks to me like not an uncommon issue.

**Comment by zfrhv** [comment]
could anyone make it work?
my provider is openshift

**Comment by zfrhv** [comment]
my bad, its a different repo.
openshift is not supported in this repo,
i have opened a new issue [here](https://github.com/openshift/oauth-proxy/issues/256)
