### ISSUE TITLE
Token/Session refresh in server side upstream call with cookies fails

### ISSUE THREAD

**Issue by ChrisHubinger** [oauth2-proxy/oauth2-proxy#1089]
Hi,

Using Keycloak configured as `oidc` provider, we deploy the proxy as a sidecar container in our frontend web server and as sidecar in the backend API. We use a `redis` server as session store. Both proxies are configured to use the same `client` in keycloak and share the same session secret.

After login everything works as expected. The Browser sends the request to the frontend application, which then sends requests, with the `cookies` from the request to the backend `api`

Schema:
Browser --- (cookie) ---> web server ---- (cookie) ----> API

This works as expected and the API proxy reads the access token from the session and passes it to the backend API where the token gets checked again (a Hasura Instance).

The problem that occurs is when the Session/Token expired, the first proxy seems to refresh the session/token with the Keycloak sever (using `refresh_token`?), no new manual login flow happens, but the proxy in front of the API does not, it sends an expired token to the backend API.

## Expected Behavior

Session and Token Refresh works on both proxies

## Current Behavior

The Second proxy in the chain passes the expired token in the request headers.

## Your Environment

Openshift 4.6

- Version used: v7.0.1 (quay.io/oauth2-proxy/oauth2-proxy:latest)

**Comment by NickMeves** [comment]
We have some issues around refreshing we hope to address that are covered in this issue: https://github.com/oauth2-proxy/oauth2-proxy/issues/856

At the moment, the best recommendation we have is to set your `--cookie-refresh` timer to the exact same duration as your Access or ID Token TTL.
