### ISSUE TITLE
Are azure b2c user flows planned?

### ISSUE THREAD

**Issue by ArtruneTranspara** [oauth2-proxy/oauth2-proxy#1090]
Upon reading the documentation and playing with the project a bit it seems to be availability to authenticate against azure. 
I've set it up successfully but i was wondering if it was possible or if it was on the roadmap to use Azure B2C user flows for login.

**Comment by NickMeves** [comment]
None of the maintainers are Azure users -- so we have no plans to add any Azure functionality ourselves.

Community contributions welcomed 😄
