### ISSUE TITLE
Issues with Keycloak integration

### ISSUE THREAD

**Issue by anthonyvk** [oauth2-proxy/oauth2-proxy#1093]
Integrating oauth2-proxy with Keycloak is not worknig. When I inspected the logs, it says Invalid parameter value for: scope

## Expected Behavior

Must be able to login to the respective service using keycloak credential.

## Current Behavior

After running keycloak container with following arguments. 
```
  provider: keycloak
  set-xauthrequest: true
  provider-display-name: Keycloak Login
  client-id: "XXX" # Change XXX to your client_id
  client-secret: "XXX" # Change XXX to your client_secret
  login-url: "https://localhost:8443/auth/realms/local/protocol/openid-connect/auth" # Change REALM_NAME to your realm
  redeem-url: "https://localhost:8443/auth/realms/local/protocol/openid-connect/token" # Change REALM_NAME to your realm
  validate-url: "https://localhost:8443/auth/realms/local/protocol/openid-connect/userinfo" # Change REALM_NAME to your realm
  keycloak-group: "myapp" 
```
When accessing the protected services, keycloak login page is displayed.
After login success, it says internal server error.
When I looked at the keycloak logs, I could see the following.
```
16:39:54,885 WARN [org.keycloak.services] (default task-13) KC-SERVICES0091: Request is missing scope 'openid' so it's not treated as OIDC, but just pure OAuth2 request.
16:39:54,887 ERROR [org.keycloak.services] (default task-13) KC-SERVICES0093: Invalid parameter value for: scope
16:39:54,894 WARN [org.keycloak.events] (default task-13) type=LOGIN_ERROR, realmId=local, clientId=gatekeeper, userId=null, ipAddress=172.17.0.1, error=invalid_request, response_type=code, redirect_uri=https://echo2.example.com/oauth2/callback, response_mode=query
```

## Steps to Reproduce (for bugs)

1.  Install NGINX ingress controller.
2.  Create cert manager : https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes
3.  Install OAuth2 proxy with the above mentioned arguments, and create a ingress for the service.
4.  Create realms and user in KeyCloak.
5. Protect the endpoint using the following annotations : 
```
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
```

## Context
Trying to achieve Keycloak Oauth2 authentication with NGINX ingress controller.

## Your Environment
Kubernetes cluster running in Docker Desktop.

- Version used:
Keycloak : 12.0.4
Oauth proxy : quay.io/pusher/oauth2_proxy:v6.1.1

**Comment by NickMeves** [comment]
To be blunt - the `keycloak` provider sucks and needs some love: https://github.com/oauth2-proxy/oauth2-proxy/issues/956

I recommend you hook into your Keycloak instance using the `oidc` provider. The `Keycloak` provider is barebones Oauth2, and there's been recent issues popping up maybe finding that the `api` default scope it uses isn't even correct anymore.

**Comment by hwaastad** [comment]
Hi,
The integration bd use client scope «api» so either add a api client scope to your keycloak instance (and client) or use a scope that usually exists, ex email.
