### ISSUE TITLE
Configuring trusted proxy IP's

### ISSUE THREAD

**Issue by fibbers** [oauth2-proxy/oauth2-proxy#1095]
I see that the security implications of setting up trust based on request headers have been discussed before (https://github.com/oauth2-proxy/oauth2-proxy/issues/871#issuecomment-717368395, https://github.com/oauth2-proxy/oauth2-proxy/pull/451#issuecomment-772931631).

I think that when you use both `--reverse-proxy` and `--trusted-ip` the security implications might be addressed if it's possible to configure "trusted" proxy IP's from which the `X-Forwarded-*` headers are taken into account/"trusted" (or whatever is specified in `--real-client-ip-header`) and don't take these headers into account from other IP's.

This is how Tomcat can be configured as well (configuring `internalProxies` in [`RemoteIpValve`](https://tomcat.apache.org/tomcat-9.0-doc/api/org/apache/catalina/valves/RemoteIpValve.html)).

My use-case is actually a bit different, but it would be solved as well by specifying a list of trusted proxy IP's:
I have a dashboard configured in Grafana which polls a Prometheus endpoint. My Prometheus deployment is protected by oauth2-proxy, but I'd like to add an exception so Grafana can scrape it without authentication.

However, if my browser requests the Grafana dashboard, Grafana sends a request to Prometheus with these headers (this is `ngrep` output, my workstation is `10.1.2.3`, Grafana is `10.0.0.2` and Prometheus is `10.0.0.3`):
```
T 10.0.0.2:58884 -> 10.0.0.3:80 [AP] #151            ## Grafana -> Prometheus
GET /api/v1/query?... HTTP/1.1.
Host: my-internal-prometheus-deployment.
User-Agent: Grafana/...
X-Dashboard-Id: 123.
X-Forwarded-For: 10.1.2.3, 10.1.2.3.                 ## Grafana forwards my browser's IP
X-Grafana-Org-Id: 456.
X-Panel-Id: 789.
```

oauth2-proxy is configured with `--reverse-proxy --trusted-ip=10.0.0.2 --real-client-ip-header=X-Forwarded-For`, however it requires this Grafana request to authenticate since it allows Grafana to act as a reverse proxy, reading `X-Forwarded-For`, and so it thinks my browser is doing the request instead of Grafana.

Say my actual internal nginx reverse proxy is `10.10.10.10`/`10.10.10.11` and I could configure something like `--internal-proxy=10.10.10.10 --internal-proxy=10.10.10.11` (shamelessly copying Tomcat naming:)), it would both help adding trust in the `X-Forwarded-*` headers and it would prevent parsing these headers when not desired.

## Expected Behavior

`X-Forwarded-*` headers aren't blindly accepted from all IP addresses when both `--reverse-proxy` and  `--trusted-ip` is configured.

## Current Behavior

`X-Forwarded-*` headers are always accepted/parsed when both `--reverse-proxy` and  `--trusted-ip` is configured.

## Possible Solution

Only parsing the `X-Forwarded-*` headers when a request comes from one of the IP addresses that is configured with a new flag which points to the "trusted" proxy IP's, which might have a default value (as with Tomcat) like: 10/8, 192.168/16, 169.254/16, 127/8, 172.16/12, ::1 (not sure about ipv6? 🤷 ). 

Implementation detail: I think being able to specify a subnet would be desirable when your reverse proxy is running in Kubernetes and might have dynamic IP's (when the pod is restarted) in a specific subnet.

It would be nice if oauth2-proxy can be ran with something like:
```
--reverse-proxy --trusted-ip=10.0.0.2 --real-client-ip-header=X-Forwarded-For --internal-proxy=10.233.0.0/16
```
`10.233.0.0/16` is Kubernetes internal IP subnet, so reverse proxies deployed in Kubernetes are allowed to read these headers from. I realise this might introduce the same problem for me if Grafana is deployed in Kubernetes as well, so there might be more to it 😄 

## Steps to Reproduce (for bugs)

1.  run Prometheus behind oauth2-proxy with `--reverse-proxy --trusted-ip=<Grafana-IP> --real-client-ip-header=X-Forwarded-For`
2.  configure Grafana dashboard that scrapes from Prometheus
3.  see the Prometheus dashboard failing since oauth2-proxy still requires the request from Grafana to be authenticated

## Your Environment

- Version used: `quay.io/oauth2-proxy/oauth2-proxy:v7.0.1` in Kubernetes v1.19.2

**Comment by NickMeves** [comment]
I'm not sure if this provides good enough protection from the attack scenario around this?

(Please correct me if I'm wrong, I'm fuzzy on the details 😅 ) `X-Forwarded-For` is spoofable, and each intermediate proxy adds the client IP it sees on the right side of the list -- while the originating client (used in the trusted-ip allowlist logic) is pulled from the leftmost entry.

So I can send an original request with the trusted IP I want to spoof in a `X-Forwarded-For` sent by me the client. Then my real IP will be the second IP in the `X-Forwarded-For` list (added by the proxy). OAuth2 will be next and will add the proxy ahead of it in the `X-Forwarded-For` -- so you allowlisting your single proxy IP will be no good, it will be in the chain.

I think to adequately protect against that attack -- anything we implement would need to be list based -- where the whole chain of `X-Forwarded-For` IPs needs to be in the revery proxy allowlist (excluding the leftmost client IP). Any additions in the middle, we'd consider the request spoofed (or we take the first IP that wasn't trusted as the client IP).

**Comment by NickMeves** [comment]
We also support htpasswd defined static user/pass pairs for basic auth. That might be a better way for Grafana to get authenticated if it can do basic auth.

If you can somehow get it a bearer token, I recommend that the most. Here's a writeup I did on how to do that: https://medium.com/in-the-weeds/service-to-service-authentication-on-kubernetes-94dcb8216cdc

As you saw in those previous issues -- I'm really not a fan of IP allowlisting 😄  -- I strongly recommend you get some form of authentication instead.

**Comment by fibbers** [comment]
Ok, I've given it a bit more thought and after drawing the different scenarios, I think most responsibility lies at the first reverse proxy (the one in front of oauth2-proxy), which might've been stated in the docs already, so that's where I currently configured things now. And authn is on the todo list, so thanks for the ideas, I'll look into those 👍 

There might still be some security benefits for configuring something like `--internal-proxy`, even though in unlikely scenarios: if oauth2-proxy can receive requests from both an internal reverse proxy _and_ directly.

Let me try to illustrate it a bit with some ascii kind of art 😀

Regular request via reverse proxy:
```
                                            "X-Forwarded-For: 4.3.2.1"
browser  ------------------>   reverse proxy   ------------------->   oauth2-proxy reads 4.3.2.1 as client IP
4.3.2.1                         10.10.10.10
```
Malicious request directly:
```
     "X-Forwarded-For: 10.0.0.1"
hacker   ------------------>   oauth2-proxy reads 10.0.0.1 as client IP
5.4.3.2
```
---
Now, when running oauth2-proxy with something like `--internal-proxy 10.10.10.10` it will only read IP's from `X-Forwarded-For` for requests originating from `10.10.10.10`, so the first regular request stays the same, but the malicious request now won't read 10.0.0.1 as client IP, but 5.4.3.2.

I don't know if this scenario (oauth2-proxy available both directly and via reverse proxy) is common though, but thought I'd share it anyway :)

And... even with this new flag, as you pointed out, this malicious request stays possible:
```
     "X-Forwarded-For: 10.0.0.1"            "X-Forwarded-For: 10.0.0.1, 5.4.3.2" 
hacker   ------------------>   reverse proxy   ---------------------------->   oauth2-proxy reads 10.0.0.1 as client IP
5.4.3.2                         10.10.10.10
```

I'll close the issue now, since my use-case won't be fixed by this :) Thanks for taking the time for this though 👍
