### ISSUE TITLE
Support configuration parameter names with dash/underscore aliases.

### ISSUE THREAD

**Issue by MNF** [oauth2-proxy/oauth2-proxy#1096]
## Current Behavior
From https://github.com/oauth2-proxy/oauth2-proxy/issues/702#issuecomment-665945115

From the [docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#config-file):
> 
> Every command line argument can be specified in a config file by replacing hyphens (-) with underscores (_). If the argument can be specified multiple times, the config option should be plural (trailing s).

> Additionally, the flag name is different from the cfg name, which is just confusing.

I am using .CFG file for local testing and pass parameters in kubernetes deployment, I have to copy and paste from one file to another  and keep changing hyphens (-) with underscores (_) and back is very annoying.
Is any technical reason for such rule , e.g. config file doesn’t allow hyphens (-)?

## Possible Solution

 Could you consider to support aliases with both hyphens (-) with underscores (_) in cfg file?
I.e. support both keys and e.g. if “client_id“ not found, try to find “client-id” in cfg file.

I’ve seen your  [RFC Introduce structural configuration ](https://github.com/oauth2-proxy/oauth2-proxy/issues/532), but it may take more time.
 Introducing aliases should be a quick win and will be backward compatible. It could be done consistently for all keys that are reading from .cfg.

**Comment by NickMeves** [comment]
All of this will be going away very soon in our next major release (v8): https://github.com/oauth2-proxy/oauth2-proxy/issues/532

Everything will be moving to structured configs and we will be moving away from the bazillion flat config flags.

You can start experimenting with this using the alpha config option I believe to start getting new features only available in v8 structured configs.

**Comment by michael-freidgeim-webjet** [comment]
@NickMeves  I know that you are planning to create new structural config, but I strongly discourage https://github.com/oauth2-proxy/oauth2-proxy/issues/532#issuecomment-797008459 to disable an existing configuration in the nearest future even after structural config will be implemented. 
This suggestion is an improvement (relatively simple) of the current functionality and can be done before the next major release.

**Comment by NickMeves** [comment]
PRs welcome 😄 

Since it will soon be deprecated, @JoelSpeed & I won't be volunteering to do it ourselves though. We have enough on our plate we have planned out to get us to the next milestones we want to hit in the next few minor versions & v8 major itself.

We are aware structured configs are a major change, that's why they won't fully go into place until a major release. As we unlock them in minor releases until then, you can start preparing for the migration by moving to the alpha-configs to prepare yourself.

**Comment by MNF** [comment]
re-activate the issue

**Comment by JoelSpeed** [comment]
I'm hesitant to support this for a couple of reasons. 

Firstly we are trying to remove this configuration style.

Secondly I see having two separate formats within the config just leading to more confusion. My suggestion would be that we come up with a way to improve the docs so that the env and config values are more obvious

**Comment by michael-freidgeim-webjet** [comment]
@JoelSpeed ,
My suggestion was to implement support of the same config and parameter keys as a quick win before new structural config will be implemented.
 If structural config replacement will be ready soon, there is no point to spend time for this.

However I do not understand your concern “having two separate formats within the config just leading to more confusion.”
If the proposal would be implemented, the only change in documentation could be

> Config keys are normally the same as command line arguments.
>  However if the argument can be specified multiple times, the config option should be plural (trailing s).
> Also command line argument can be specified in a config file by replacing hyphens (-) with underscores (_)

My concern was not about documentation, but about annoyance to change - to _ and back when copy and paste from one file to another.
