### ISSUE TITLE
skip-auth-route with nginx auth_request

### ISSUE THREAD

**Issue by foosinn** [oauth2-proxy/oauth2-proxy#1099]
Hey, we are using skip-auth-route with nginx auth_request. 

## Expected Behavior

Allow allow-listed urls in `skip-auth-route` when using nginx's auth_request mode. 

## Current Behavior

Traffic is still blocked

## Possible Solution

I assume that currently only the URL is matched for auth_request, not `X-Auth-Request-Redirect`.

## Steps to Reproduce (for bugs)

1. Setup oauth2-proxy and Nginx with auth_request (explained in your docs)
2. Allowlist a route via `skip-auth-route`
3. Still be unable to access it

## Context

One way to solve this would be to use nginx, that adds quite a bit of complication. I would prefer having the allowlist option.

## Your Environment

oauth2-proxy V7.0.1
nginx 1.18

Thanks so much!

**Comment by NickMeves** [comment]
I think you'll need to manage this at the nginx layer.

When you use the  seubrequest architecture -- OAuth2 Proxy gets requests to `/oauth2/auth` -- we don't see your original request path.

**Comment by NickMeves** [comment]
I believe  subrequests reuse/copy over the original request headers (so Authorization, cookie etc would factor into an auth decision).

But the `GET /oauth2/auth HTTP/1.1` first line will be the OAuth2 Auth endpoint and the original path will be lost from our view.

**Comment by NickMeves** [comment]
Not marking as an enhancement request since I don't think this is feasible -- please correct me if I'm understanding incorrectly and I'll re-classify the issue.

**Comment by JoelSpeed** [comment]
You are much better off using Nginx to perform the decisions here rather than relying on OAuth2 Proxy. If you have particular routes that can have auth skipped, Nginxs config is much richer and allows you to set this up to be much more efficient than relying on OAuth2 Proxy

**Comment by foosinn** [comment]
Hey,

thanks for letting me know. I'm aware of that, but we use oauth2-proxy as a drop-in for our staging environments.

I'll sick with configuring that via nginx or using it as a sidecar.

Thanks for your replies!
