### ISSUE TITLE
OIDC: Support for additional id_token signing algorithms (RS512, etc.)

### ISSUE THREAD

**Issue by iveshenry18** [oauth2-proxy/oauth2-proxy#1100]
I am attempting to authenticate against an internal enterprise Identity Provider that currently only includes RS512 in their id_token_signing_alg_values_supported. I understand that this fails to comply with the [OIDC specification](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) ("The algorithm RS256 MUST be included"), but it would be nice if this case could be handled.

Also, the error message returned in this case is a bit unclear.

## Expected Behavior

ID tokens are verified successfully for a larger set of signing algorithms (RS384, RS512, etc.). Alternately, the error message when no supported algorithm is available could be a bit more informative.

## Current Behavior

If the provider doesn't provide a key signed with RS256, the server returns a 500 error and logs a message similar to the following:
`Error redeeming code during OAuth2 callback: could not verify id_token: oidc: id token signed with unsupported algorithm, expected ["RS512"] got "RS256"`

If I am correct about the root cause of the problem (and I may be incorrect), this error message also seems to be counterintuitive.

## Possible Solution

On a high level it seems straightforward enough to implement more signing algorithms that could be attempted if RS256 fails. Additionally, the supported algorithms could be checked against the id_token_signing_alg_values_supported earlier in the flow, allowing for a more helpful error message. I am not familiar enough with the codebase to discern what the technical challenges to this might be.

## Steps to Reproduce (for bugs)

1.  Config (some info removed for security reasons; nothing that I believe is related to this issue): 
  ```
    provider = "oidc"
    provider_display_name = "REDACTED"

    http_address = "0.0.0.0:4180"
    https_address = "0.0.0.0:443"

    client_id = {{ .Values.oauth2.clientID | quote }}
    oidc_issuer_url = "https://{{ .Values.oauth2.idpHost }}/nidp/oauth/nam"
    redirect_url = "https://{{ .Values.ingress.host }}/oauth2/callback"

    email_domains = ['REDACTED']
    scope = 'openid read_user email'
    cookie_secure = false
    pass_access_token = true
    cookie_domains = ['REDACTED']

    reverse_proxy = true
    

    upstreams = ['http://0.0.0.0:8000/']
  ```

2.  Provider `/.well-known/openid-configuration`:
`...,"id_token_signing_alg_values_supported":["RS512"],...`
3. Provider  `/keys`:
`{"keys":[{"kty":"RSA","use":"sig","alg":"RS512",...` (this is the only key in the list)

## Context

I am attempting to secure a Kubernetes web application using the oauth2-proxy:v7.0.1 image running in a sidecar container. This is an internal tool, and users must authenticate against the enterprise SSO which, as described, doesn't seem to fully comply with the OIDC specification

## Your Environment

Kubernetes cluster:
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

- Version used: v7.0.1

__Note:__ I could be wrong about what the error is. Let me know if you think there may be something else going on than what I've described, or if there is already an available workaround.

**Comment by NickMeves** [comment]
I just did some quick research -- it looks like we'd need to use the `oidc.Config.SupportedSigningAlgs` when we setup an `oidc.IDTokenVerifier` in our OIDC Provider explicitly maybe?

It defaults to `RS256` if nothing is set -- but I've definitely used this with `ES256` OIDC configurations that have no `RS256` before, so I'm pretty sure the library constructs that list from the OIDC discovery document signing algorithms list 🤔

**Comment by NickMeves** [comment]
FYI - I'm pretty sure you are erroring here: https://github.com/oauth2-proxy/oauth2-proxy/blob/f3209a40e16defdab442ef87765e837d90ec4f9a/providers/provider_data.go#L137

Which is why I'm honing in on the `go-oidc` external library that does this.

**Comment by NickMeves** [comment]
Oh - just looked more closely at your error... So the library did see you want to use `RS512` as the allowed algorithm, but the IDToken it gave back was signed with `RS256`?

`id token signed with unsupported algorithm, expected ["RS512"] got "RS256"`

You might want to take a closer look at the IDTokens you are getting back from your IdP - something seems amiss there.

**Comment by travisofthenorth** [comment]
I am actually having a similar issue. My IdP only supports ES512. I'm getting the following error:
```
Error redeeming code during OAuth2 callback: could not verify id_token: oidc: id token signed with unsupported algorithm, expected ["RS256"] got "ES512"
```

The response from the discovery endpoint includes `"id_token_signing_alg_values_supported":["ES512"]`

I fetched the binary using `go get github.com/oauth2-proxy/oauth2-proxy/v7`

**Comment by travisofthenorth** [comment]
@NickMeves any idea? The original issue description is pretty much identically my issue.

**Comment by travisofthenorth** [comment]
Note to future person experiencing this issue: in my case, it seems to be that I'm using the "skip issuer check" flag (because the issuer and hostname don't actually match). Seems like go-oidc doesn't parse/use the discovery algorithms in that case.

**Comment by alank976** [comment]
> Note to future person experiencing this issue: in my case, it seems to be that I'm using the "skip issuer check" flag (because the issuer and hostname don't actually match). Seems like go-oidc doesn't parse/use the discovery algorithms in that case.

@travisofthenorth May I know how did you get around this then? I am in the same boat and using `--skip-oidc-discovery=true` as well for the same reason...
Is there an alternative I can configure the algorithm to ES512?
My `oidc-jwks-url` response is like this:
```json
{
  "keys" : [
    {
      "alg" : "ES512",
      "crv" : "P-521",
      "kid" : "XzdHuAU2ndBynboG3Ki-XanX1wk",
      "kty" : "EC",
      "use" : "sig",
      "x" : "AdFhBw5sWnRB75WGbTnibyZllv0xntc1KV3Tz9h0LQxtC0ycC4uUnxLB3tuNBSxp4FvOdL7vklKtCPOcRk64KbOC",
      "x5c" : [
        "MIIBwzCCASWgAwIBAQIQQSUzKz/CSFG3Ziq6eSHhBzAKBggqhkjOPQQDBDAgMR4wHAYDVQQDExVodHRwOi8vYXV0aC5hYXphaS5jb20wHhcNMjMwNDI2MTQxNDUxWhcNMzMwNDI2MTQxNDUxWjAgMR4wHAYDVQQDExVodHRwOi8vYXV0aC5hYXphaS5jb20wgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAHRYQcObFp0Qe+Vhm054m8mZZb9MZ7XNSld08/YdC0MbQtMnAuLlJ8Swd7bjQUsaeBbznS+75JSrQjznEZOuCmzggCM2rYtxuPwq3r5wuoXRiT/nZvWJZhq/Lpkn1CMejEjCLkthlzmnsBPZXoL46KD2tKxETBF3THnDQHMjOprVp7psjAKBggqhkjOPQQDBAOBiwAwgYcCQTGy35/dKxk0huMqK9c4TpsTas2CALyOGcXgJC3eZvvNeQ0KjfG784qo5X+8ChswMZNaGV5e/0VkYt+0qj3oJgUpAkIBTiK4Y6Mmjx6Ce02wIrp6aw2rMl57tnMDKZLzxZUA5ZHS3w86MzLKkKIH/WaKyNlI3MtimBa4jxPFVaEZ3DYgMaA="
      ],
      "x5t" : "XzdHuAU2ndBynboG3Ki-XanX1wk",
      "x5t#S256" : "Gx5bbNBkCv8kSfGplPcvtCKfMllBTpx_vyjhKUCvluk",
      "y" : "AIzati3G4_CrevnC6hdGJP-dm9YlmGr8umSfUIx6MSMIuS2GXOaewE9legvjooPa0rERMEXdMecNAcyM6mtWnumy"
    },
    {
      "alg" : "ES512",
      "crv" : "P-521",
      "kid" : "QuH9FcETVYTjqBKv1nPgho7lh0s",
      "kty" : "EC",
      "use" : "sig",
      "x" : "AP_kvJKL0hpvWnJEA7MwjkZ3TIuraKm0IiQeIdCgrSkZombsVgscO2RbQe9FmsjsROAly6yMHqrT7bBJj657ZtIE",
      "x5c" : [
        "MIIBxTCCASagAwIBAQIRAN+zWE+lx0cvjprA/hyNc2kwCgYIKoZIzj0EAwQwIDEeMBwGA1UEAxMVaHR0cDovL2F1dGguYWF6YWkuY29tMB4XDTIzMDQyNjE0MTQ1MVoXDTMzMDQyNjE0MTQ1MVowIDEeMBwGA1UEAxMVaHR0cDovL2F1dGguYWF6YWkuY29tMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQA/+S8kovSGm9ackQDszCORndMi6toqbQiJB4h0KCtKRmiZuxWCxw7ZFtB70WayOxE4CXLrIweqtPtsEmPrntm0gQBHZwD5bCQCk7XLWjwUsvCqT7MTAPzGNITlfGGtu0unQM3livZxVqpaF+YP3t4HzyVox5K+R1DvldUgwTJ8RjfAFYwCgYIKoZIzj0EAwQDgYwAMIGIAkIBaZRSvOvNtpQOZ0tQRrwp6XPz+Y+6o9iEtSPnN6D3AvQHALYo+vhs4RVnHdUZ8BwmcCWxS+yFo4a6RAw4vFHwt80CQgDrWAiGpZS9+FyPagqyKCoc+qlCceCssjFs1Cf16ati/9WFL4qzBqvjburxtNZZ4D3Ly5+yyGb9i52hKLQmccEYjw=="
      ],
      "x5t" : "QuH9FcETVYTjqBKv1nPgho7lh0s",
      "x5t#S256" : "btbIoe40c67OEum69mVxLnL4xsWiCAzrwwP7eQx7h34",
      "y" : "AR2cA-WwkApO1y1o8FLLwqk-zEwD8xjSE5XxhrbtLp0DN5Yr2cVaqWhfmD97eB88laMeSvkdQ75XVIMEyfEY3wBW"
    }
  ]
}
```
