### ISSUE TITLE
Describe Local development at the top level of documentation (or readme.md)

### ISSUE THREAD

**Issue by MNF** [oauth2-proxy/oauth2-proxy#1109]
## Expected Behavior

It will be good to have separate section ## Local Development/Testing in documentation (or readme.md)

## Current Behavior
The current link in https://github.com/oauth2-proxy/oauth2-proxy/blob/7def4bf3600ee29a843cf3375998aa5fd0428b0f/docs/versioned_docs/version-7.0.x/configuration/auth.md is hard to find.

`See also [our local testing environment](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment) for a self-contained example using Docker and etcd as storage for Dex.`

## Context

The issue is about discoverability of “local testing environment” documentation, however any more details about  “local  environment” in the documentation will be appreciated.
E.g. reference to [Kubernetes example](https://github.com/oauth2-proxy/oauth2-proxy/blob/8be97f25e7276d2d46f002199f9eda345fc0800d/contrib/local-environment/kubernetes/README.md) as well.

## Your Environment

NA

**Comment by JoelSpeed** [comment]
Totally agreed! We really should document this better and explain that they can be used. If anyone has time to pick this up, then please feel free

**Comment by michael-freidgeim-webjet** [comment]
Reactivate

**Comment by MNF** [comment]
the issue is still relevant

**Comment by MNF** [comment]
the issue is still relevant

**Comment by michael-freidgeim-webjet** [comment]
the issue is still relevant

**Comment by michael-freidgeim-webjet** [comment]
the issue is still relevant
