### ISSUE TITLE
How can I create valid user/password for local Dex?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [oauth2-proxy/oauth2-proxy#1110]
## Expected Behavior

https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/docker-compose.yaml has good instructions (BTW should they be in docs, rather than in the comments?) how to build an example instance 
I can run http://localhost:4180/ and see a form

> Authenticate using @example.com
> Sign in with OpenID Connect

However I couldn't find how I can create local account to  test Sign in button.
Could you please provide instructions how to save details of a new user?

## Current Behavior
No instructions how a new user/password can be created?

## Possible Solution
Add documentation to Local development section (suggested in https://github.com/oauth2-proxy/oauth2-proxy/issues/1109)

## Steps to Reproduce (for bugs)
In local copy of https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/
1. run make up
2. open http://localhost:4180/

## Your Environment
Local environment forked from master 5/03/2021

**Comment by JoelSpeed** [comment]
Users are defined in the dex configuration here 
https://github.com/oauth2-proxy/oauth2-proxy/blob/4d9de06b1dbad8d27965afa2586df29667eeb50c/contrib/local-environment/dex.yaml#L27-L32

We should add this to the documentation that exists in the docker-compose files and yes, it would be good to also copy this information into the docs at some point, haven't had a chance to do that just yet though. If anyone has the time to pick this up, then I should be able to find time to review, else I'll try and get to this in the not too distant future

**Comment by MNF** [comment]
Reopen please to add to documentation
