### ISSUE TITLE
Upstream path error when path end with ? character

### ISSUE THREAD

**Issue by gaveezy** [oauth2-proxy/oauth2-proxy#1112]
The proxy send request to upstream server with wrong path when path end withs `?`
For example, the original request `https://proxy-domain.url/file/count?`
The request sent to upstream by oauth2-proxy is `http://upstream-server/file/count??`

## Expected Behavior

The path should be `file/count?` instead of `file/count??`

## Current Behavior

The path is `file/count??`

- Version used: `7.0.1`

**Comment by JoelSpeed** [comment]
Not sure where this has come from, will see if I can find some time to look into it over the next week or so. Do you know does this only happen with HTTP upstreams or does this affect file based upstreams as well?

**Comment by gaveezy** [comment]
I'm not sure about the file based upstreams part. Didn't try it before. Any idea how to use it, so I can check if the problem existed with file based upstreams (can't find how to use file based upstreams on config file https://github.com/bitly/oauth2_proxy/blob/master/contrib/oauth2_proxy.cfg.example)?

**Comment by JoelSpeed** [comment]
Don't worry about the file upstream part, I found the part that was broken and have raised a PR to fix this in #1115. It doesn't affect the file based updstreams
