### ISSUE TITLE
Document oauth2/sign_in vs /oauth2/start 

### ISSUE THREAD

**Issue by MNF** [oauth2-proxy/oauth2-proxy#1114]
In https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints the endpoints described as
- /oauth2/sign_in - the login page, which also doubles as a sign out page (it clears cookies)
/oauth2/start - a URL that will redirect to start the OAuth cycle

It is not very clear what is the difference between them, it will be good to elaborate.

Could you please also  document parameter rd ? 
Will the value of rd be saved in state parameter and later
callback will retrieve from the state the original (protected by the proxy) url and redirects browser to it?
Is  parameter rd  supported in both endpoints or only on sign-in?

## Expected Behavior
More clear documentation.

## Current Behavior

Not enough details.

## Context

Reference in an example 
```
# If the auth_request denies the request (401), redirect to the sign_in page |  
# and include the final rd URL back to the user's original request. |  
error_page 401 = http://oauth2-proxy.oauth2-proxy.localhost/oauth2/sign_in?rd=$scheme://$host$request_uri
```

## Your Environment
Current online documentation.

**Comment by JoelSpeed** [comment]
The difference between them is that `start` starts the flow without user interaction (same as if `skip-provider-button` is provided) and `sign_in` will show the button and prompt users to click before they actually get logged in.

> Will the value of rd be saved in state parameter and later
callback will retrieve from the state the original (protected by the proxy) url and redirects browser to it?
Is parameter rd supported in both endpoints or only on sign-in?

You've got the gist of it yes! It's supported on both endpoints

I agree the documentation here is a bit lacking, we could use some updates!

**Comment by michael-freidgeim-webjet** [comment]
re-activate

**Comment by MNF** [comment]
the issue is still relevant
