### ISSUE TITLE
Auth with "Authorization: Bearer" and curl unclearness

### ISSUE THREAD

**Issue by bobykus31** [oauth2-proxy/oauth2-proxy#1118]
Can not get auth to work with curl and   ' -H "Authorization: Bearer ${TOKEN}"

`curl -L -v  --cookie "_myauth=secret"  -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" https://auth1.my.site:443/
`

The error is 

`Mar 22 16:54:48 auth1 oauth2-proxy[11621]: [2021/03/22 16:54:48] [stored_session.go:76] Error loading cookied session: cookie signature not valid, removing session`

The  config  is 

```
https_address = ":443"
     
## TLS Settings
tls_cert_file = "/etc/my.site/ssl/wildcard.crt"
tls_key_file = "/etc/my.site/ssl/wildcard.key"

# the OAuth Redirect URL.
redirect_url = "https://redirect.my.site/oauth2/callback"

# the http url of the upstream endpoint
upstreams = ["https://upstream.my.site:8443"]

## The OAuth Client ID, Secret
client_id = "my"
client_secret = "...-353ca8644b06"
cookie_name = "_myauth"
cookie_secret = "xBl4h438678r95GoQqPsw=="
cookie_secure = "true"

oidc_issuer_url = "https://auth.my.site/auth/realms/Internal"
provider = "MyAuth"
provider_display_name = "Keycloak"
```

We run oauth proxy as 

`/usr/bin/oauth2-proxy --config=/etc/oauth2_proxy/oauth2_proxy.cfg --login-url=https://auth.my.site/auth/realms/Internal/protocol/openid-connect/auth --redeem-url=https://auth.my.site/auth/realms/Internal/protocol/openid-connect/token --validate-url=https://auth.my.site/auth/realms/Internal/protocol/openid-connect/userinfo --provider=keycloak --redirect-url=https://redirect.my.site/oauth2/callback --skip-provider-button=true --prefer-email-to-user=true --pass-basic-auth=true --pass-user-headers=true --metrics-address my_ip:9153
`

With browser all works well.

We use Keycloak as auth service, but it must be something very local I can not find why does not work...
We use master repo build because of prometheus metrics.

**Comment by JoelSpeed** [comment]
I think you are missing the `--skip-jwt-bearer-tokens` option, this tells the proxy to accept JWT tokens as valid sessions, otherwise it will ignore the Authorization headers that you are passing

**Comment by bobykus31** [comment]
Added --skip-jwt-bearer-tokens, but  now new error appears 

Error retrieving session from token in Authorization header: [unable to verify bearer token, oidc: expected audience "my" got ["account"]

I might get token wrong or what...

**Comment by JoelSpeed** [comment]
I think this is a known issue, at the moment if you have multiple audiences from the same issuer, we can't validate them I don't think. @NickMeves were you aware of this? I think you were involved in some conversations around this but I can't recall if we had a workaround or not yet

**Comment by NickMeves** [comment]
`go-oidc` should handle array `aud` claims just fine. All the Kubernetes projected tokens are the format `aud: [ "example" ]` and they've worked no problem for me.

Or does this token actually have multiple audiences in the array claim? If you have a sample that would be great to see!
