### ISSUE TITLE
Creating JWT session with unverified email

### ISSUE THREAD

**Issue by shivknight** [oauth2-proxy/oauth2-proxy#1120]
## Expected Behavior
Able to create a new JWT session when `email_verified: false`

## Current Behavior
Creating a session from JWT when `email_verified: false` still checks for valid email, resulting in
```
[oauth2-proxy] [2021/03/23 00:55:57] [oauthproxy.go:922] Error retrieving session from token in Authorization header: email in id_token (<redacted>) isn't verified
```

## Possible Solution
If I understand correctly, https://github.com/oauth2-proxy/oauth2-proxy/blob/5788bebfeebaa1155536eee634fa15c7d4c7e5de/pkg/apis/middleware/session.go#L42 needs a check similar to https://github.com/oauth2-proxy/oauth2-proxy/blob/5788bebfeebaa1155536eee634fa15c7d4c7e5de/providers/provider_data.go#L165-L166

## Steps to Reproduce (for bugs)
1. Retrieve a JWT using the OIDC provider (or others I suppose) with `email_verified: false`
2. Send another request with a `Authorization: Bearer <jwt>` header

## Your Environment

- Version used:
v6.0.0

**Comment by NickMeves** [comment]
What options are you using?

You are correct - for any supplemental bearer token verifiers, the options are barebones via `--extra-jwt-issuers` (we are looking to resolve this in v8 with structured configs allowing a rich list of bearer providers with all the options).

But for Bearer tokens, the first verifier in the chain is your main provider. For instance, if you use OIDC - it will use this function: https://github.com/oauth2-proxy/oauth2-proxy/blob/5788bebfeebaa1155536eee634fa15c7d4c7e5de/providers/oidc.go#L181 which will honor any email verified settings you use for the provider.

**Comment by shivknight** [comment]
Thanks, you got me on the right track. I was falling through to the default verifier due to a mismatched `aud` claim in the JWT verifier. I'm still trying to resolve that issue btw, do you know if `oauth2-proxy` would set the `aud` to a value of `account` for any reason? Or is that from my OIDC provider? Closing the issue at any rate.

**Comment by NickMeves** [comment]
> Thanks, you got me on the right track. I was falling through to the default verifier due to a mismatched `aud` claim in the JWT verifier. I'm still trying to resolve that issue btw, do you know if `oauth2-proxy` would set the `aud` to a value of `account` for any reason? Or is that from my OIDC provider? Closing the issue at any rate.

We don't mess with the token `aud` in any way (or any other claim). Probably something to check on with your OIDC provider.
