### ISSUE TITLE
Customization of error page

### ISSUE THREAD

**Issue by cabrinoob** [oauth2-proxy/oauth2-proxy#1121]
Hi,
I see it was possible to override the error and sign_in templates. So, I checkout those from the v7.0.1 (those with bulma CSS).
I'am running OAuth2-proxy under K8S so I mounted those templates into the pod through a configMap and correctly setup the `--custom-templates-dir`.

This step worked: Template are correctly mounted into the pod. 

But, when I log in using my Auth0 IDP and intentionaly cause an error, Auth0 redirects to this url : 

    /oauth2/callback?error=unauthorized&error_description=some%20description&state=ed628ebc41e4562bee2ee9d764aee9a9%3A%2F

And the page is blank. So, if I look into the Oauth2-proxy logs I have this : 

```[2021/03/23 13:58:08] [oauthproxy.go:746] Error while parsing OAuth2 callback: unauthorized
2021/03/23 13:58:08 http: superfluous response.WriteHeader call from main.(*responseLogger).WriteHeader (logging_handler.go:69)
[2021/03/23 13:58:08] [oauthproxy.go:526] Error rendering error.html template: template: error.html:7:11: executing "error.html" at <.StatusCode>: can't evaluate field StatusCode in type struct { Title string; Message string; ProxyPrefix string }
```

It seems there's some missing fields in the go struct

Thank you for your help

**Comment by JoelSpeed** [comment]
The updated templates are actually only available from v7.1.0. So you will either need to use the master branch for now or wait until the v7.1.0 release is created, hopefully that should be some time this week

**Comment by cabrinoob** [comment]
Oh yes, I forgot to say that I also deployed the v7.1.0 of the docker image.

**Comment by JoelSpeed** [comment]
New release is out, you should be able to get this to work now, if you have any further issues, feel free to reopen

**Comment by cabrinoob** [comment]
Yes, I got it, and it works! 
It would be nice to populate a new variable in the error template with the content of the "error_descrition" sent by the IDP (in addition of the error).

But thank you

**Comment by JoelSpeed** [comment]
I think if you try the `--show-debug-on-error` option, it will give a more detailed error message, though I would suggest only using this while setting up the proxy and not continually as it may contain sensitive information
