### ISSUE TITLE
Recommended usage with CLI client?

### ISSUE THREAD

**Issue by shivknight** [oauth2-proxy/oauth2-proxy#1126]
Not an issue as much as a usage recommendation. How is `oauth2-proxy` meant to be used with a CLI client? My architecture is identical to the one described in https://github.com/oauth2-proxy/oauth2-proxy/issues/809, but it's not clear what options I need to set and what URLs I should use. 

## Expected Behavior
CLI app attempts to auth against OIDC provider via `oauth2-proxy`. `oauth2-proxy` returns a token to the CLI somehow. 

## Possible Solution
Here's my rough understanding of how this could work
1. CLI starts local http server on <redirect_url>
2. CLI opens browser page with oauth2-proxy auth URL, specifying redirect URL as query parameter (or `X-Auth-Request-Redirect` header)
3. Complete flow and oauth2-proxy calls back to <redirect_url> with token set in `X-Auth-Request-Access-Token` or somewhere else
4. CLI retrieves token and closes http server

I'm obviously missing something though because the flow completes and there's no token in the callback. The session cookie is in the response, which according to https://github.com/oauth2-proxy/oauth2-proxy/issues/950 *could* be used along with the `client-secret` to decrypt the token, but as noted, that's not the intended use of the cookie.

## Steps to Reproduce (for bugs)

N/A

## Context
I want an OAuth experience like, e.g. `heroku login`, that doesn't require copying a token from browser to a config file or something

## Your Environment
`oauth2-proxy` configuration with some irrelevant fields redacted or removed
```
oauth2-proxy
--provider=oidc
--oidc-issuer-url={{ .Values.global.oidc.issuer }}
--redirect-url={{ .Values.global.oidc.redirect }}
--email-domain=<redacted>
--upstream=http://127.0.0.1:{{ .Values.service.port }}
--http-address=0.0.0.0:{{ .Values.oauth2Proxy.port }}
--insecure-oidc-allow-unverified-email=true
--insecure-oidc-skip-issuer-verification=true
--use-oidc-implicit-flow=false
--cookie-secure={{ .Values.oauth2Proxy.cookieSecure }}
--pass-authorization-header=true
--pass-user-headers=true
--pass-access-token=true
--set-xauthrequest=true
--set-authorization-header=true
--skip-jwt-bearer-tokens=true
--extra-jwt-issuers=<redacted>
--whitelist-domain=localhost:*
```

- Version used:
v6.0.0

**Comment by JoelSpeed** [comment]
Typically, this kind of thing would be achieved by implementing OIDC in your command line tool. OAuth proxy wasn't really meant for this use case to be honest.

If you can get the cookie into your application, you can call `<Oauth2-proxy>/oauth2/auth`, and provided you've set the correct config for the headers, it will populate the response with information about the authenticated user. Does that work for you at all?

**Comment by shivknight** [comment]
It did work for me, thanks for the tip.

**Comment by satyamsundaram** [comment]
@shivknight can you explain how you are getting the cookie in your response because I'm only able to get the access-token and not the cookie?

**Comment by satyamsundaram** [comment]
Is the cookie that you are referring to the oauth2_proxy cookie? If yes, how will the OIDC provide this?
If not which cookie can be used to call <Oauth2-proxy>/oauth2/auth?
