### ISSUE TITLE
Metrics Server Requires TLS?

### ISSUE THREAD

**Issue by Fox32** [oauth2-proxy/oauth2-proxy#1132]
The metrics server claims that it requires a TLS configuration.

## Expected Behavior

Metrics server is listening on port 9100.

## Current Behavior

Startup fails with:

```
ERROR: Failed to initialise OAuth2 Proxy: error setting up server: could not
 build metrics server: error setting up TLS listener: no TLS config provided
```

## Possible Solution

Make TLS optional.

## Steps to Reproduce (for bugs)

1.  Use version 7.1.0
2.  Start the server with `--metrics-address=:9100` and without TLS configuration.

## Context

As I don't publish that port externally and just register it in a service monitor, I would expect to be able to use it without TLS.

## Your Environment

- Version used: 7.1.0

**Comment by JoelSpeed** [comment]
Damn, a typo is breaking this right now, would you be able to build an image from #1133 and check that it resolves the issue?

**Comment by Fox32** [comment]
@JoelSpeed I can't get it to build (but not because it is wrong, but because my device isn't setup properly). But thanks for the quick fix!

**Comment by Fox32** [comment]
@JoelSpeed still running into the issue with 7.1.1. But looks like there is already a PR #1141
