### ISSUE TITLE
When I add the path in my route like this: http://a.s.com/path, I login with Keycloak and it will show the page 503 - not available.

### ISSUE THREAD

**Issue by hanleirx** [oauth2-proxy/oauth2-proxy#1143]
When I add the path in my route like this: http://a.s.com/path, I login with Keycloak and it will show the page 503 - not available.
But I remove the path - http://a.s.com/, it can show page normally. 
But I need the path.
I don't know how to config the path.
I tried upstreams/ redirect-url/proxy-prefix/cookie-path, but they are faled. And I don't know how to config it.

my configmap is like this:

   provider="keycloak"
    provider_display_name="Keycloak"
    login_url="https://XX/auth"
    redeem_url="https://XX/token"
    validate_url="https://XX/userinfo"
    ssl_insecure_skip_verify=true
    client_id="XX"
    client_secret="XX"
    cookie_secret="XX"
    cookie_secure="false"
    http_address="0.0.0.0:3000"
    upstreams="http://127.0.0.1:80/"
    skip_auth_routes=["/health.*"]
    skip_provider_button="true"
    reverse_proxy="true"
    email_domains=["*"]
    cookie_domains=[".cloud"]
    whitelist_domains=[".cloud:*"]

Need your help,thanks!

**Comment by JoelSpeed** [comment]
Can you share any logs from OAuth2 Proxy during the requests to show the difference between making a request with the path and without the path? 

Please sanitize the logs before posting
