### ISSUE TITLE
Missing cookie _oauth2_proxy (oidc provider)

### ISSUE THREAD

**Issue by evilfer** [oauth2-proxy/oauth2-proxy#1146]
I'm trying to configure oauth2-proxy with Keycloak, using the oidc provider, in order to have support for token refresh. However, redirects back from keycloak to oauth2-proxy fail with 500 Internal Server Error.

## Expected Behavior

After being redirected to keycloak, and a successful login on keycloak, the system should proxy requests to the final backend system. The cookie with default name `_oauth2_proxy` should be set.

## Current Behavior

Immediately after successful keycloak login, the user is redirected to http://khub.localtest.me/oauth2/callback?state=..., which responds with 500 Internal Server Error.

The oauth2-proxy log contains:

```
[2021/04/03 11:37:26] [proxy.go:70] mapping path "/" => upstream "http://apache/"
[2021/04/03 11:37:26] [oauthproxy.go:149] OAuthProxy configured for OpenID Connect Client ID: khub-web-openidc
[2021/04/03 11:37:26] [oauthproxy.go:155] Cookie settings: name:_oauth2_proxy secure(https):false httponly:false expiry:1h0m0s domains:khub.localtest.me path:/ samesite: refresh:after 1m0s
[2021/04/03 11:37:43] [stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
172.19.0.6:38808 - 9580d76e-1422-4dad-b017-330c0e7521fc - - [2021/04/03 11:37:43] oauth2-proxy:4180 GET - "/" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36" 403 8077 0.001
172.19.0.6:38810 - ec18247e-d225-40d7-b8f6-96f163bcc128 - - [2021/04/03 11:37:46] oauth2-proxy:4180 GET - "/oauth2/start?rd=%2F" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36" 302 310 0.000
[2021/04/03 11:37:49] [oauthproxy.go:787] Error redeeming code during OAuth2 callback: token response did not contain an id_token
172.19.0.6:38854 - 849742a6-996d-4f78-9358-536221215147 - - [2021/04/03 11:37:49] oauth2-proxy:4180 GET - "/oauth2/callback?state=28579f53a8447efef301c81654902514%3A%2F&session_state=56768206-05e2-4b4e-ac4a-1eab78565f86&code=8be856ee-33b0-4bf2-a66b-7ab21dd4ca3b.56768206-05e2-4b4e-ac4a-1eab78565f86.7fe11c47-40c6-4c5f-9df8-c1f8288f18f9" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36" 500 2841 0.027
```

In the browser, I can see cookie `_oauth2_proxy_csrf`, but not `_oauth2_proxy`.

I've tried setting up the cookie name. However, whatever the cookie name is configured to, the actual cookie created is `[configured name]_csrf`.

## Steps to Reproduce (for bugs)

1.  This is a very basic set up, with nginx as public server, oauth2-proxy, keycloak, and apache as backend (apache is never reached)
2.  oauth2-proxy is configured through environment variables, see below.
3.  keycloak is configured with an openid client.
4. The error occurs as soon as a successful login is completed in keycloak, and the user is redirected back to /oauth2/callback

## Context

Trying to secure a web application with oauth2-proxy + keycloak using OpenId connect.

## Your Environment

- Version used:
  - quay.io/oauth2-proxy/oauth2-proxy:v7.1.2
  - jboss/keycloak:12.0.4

- SSL: this is a test local server, without any SSL certificates. `OAUTH2_PROXY_COOKIE_SECURE=false` is configured to support this.

- oauth2-proxy environment:

```
      - "OAUTH2_PROXY_PROVIDER=oidc"
      - "OAUTH2_PROXY_COOKIE_SECRET=[cookie secret]"
      - "OAUTH2_PROXY_CLIENT_ID=khub-web-openidc"
      - "OAUTH2_PROXY_CLIENT_SECRET=[client secret]"
      - "OAUTH2_PROXY_OIDC_ISSUER_URL=http://khub.localtest.me/auth/realms/khub"
      - "OAUTH2_PROXY_EMAIL_DOMAINS=*"
      - "OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180"
      - "OAUTH2_PROXY_REDIRECT_URL=http://khub.localtest.me/oauth2/callback"
      - "OAUTH2_PROXY_SCOPE=email profile"
      - "OAUTH2_PROXY_COOKIE_DOMAINS=khub.localtest.me"
      - "OAUTH2_PROXY_COOKIE_DOMAIN=khub.localtest.me"
      - "OAUTH2_PROXY_COOKIE_EXPIRE=1h0m0s"
      - "OAUTH2_PROXY_COOKIE_REFRESH=0h1m0s"
      - "OAUTH2_PROXY_COOKIE_SECURE=false"
      - "OAUTH2_PROXY_COOKIE_HTTPONLY=false"
      - "OAUTH2_PROXY_UPSTREAMS=http://apache/"
      - "OAUTH2_PROXY_PASS_ACCESS_TOKEN=true"
```

**Comment by MNF** [comment]
The message “Error loading cookied session: cookie "_oauth2_proxy" not present, removing session” is misleading. It is a normal behavior for the first time, when cookie has not been created yet. The message should be changed to be Info.

You should concentrate on investigation of the second message
 “Error redeeming code during OAuth2 callback: token response did not contain an id_token”
Verify your “response_code” and claims parameters

**Comment by evilfer** [comment]
Thank you Michael. 

You're right. Turns out I was missing the "openid" scope, and the keycloak log warned about this. All working now :).
