### ISSUE TITLE
Specify extra claims to fields stored in session-cookie-minimal

### ISSUE THREAD

**Issue by MNF** [oauth2-proxy/oauth2-proxy#1148]
## Current Behavior
You recently introduced session-cookie-minimal ( in
[Add option to remove tokens from cookie sessions #673](https://github.com/oauth2-proxy/oauth2-proxy/pull/673) )

Btw, It **should be mentioned in the documentation**, especially if you consider to make it as a default.

When this flag is specified, currently  it’s not possible to include in the session any claims normally available in id_token.

Existing hardcoded fields (Email: User: Groups:[] PreferredUsername) in  SessionState often  not sufficient and not extendable.

## Expected Behavior

It will be good to include in configuration   session-cookie-minimal-extra-claims=“claim1name,claim2name” that will allow to specify extra claims, stored within a session.
That should add to the SessionState ExtraClaims field as a collection of claims copied from id_token.

## Possible Solution

The extra claims will be included as header(s) to upstreams.
Not sure will it be better to have one header “extra-claims” passing collection or pass separate header for each claim
## Context

I want to pass as header a couple of proprietary claims, but don’t want to to keep in cookie the whole big id_token
## Your Environment

Fork of oaut2proxy v7, March 2021, Azure AD B2C

**Comment by NickMeves** [comment]
> Btw, It should be mentioned in the documentation, especially if you consider to make it as a default.

It isn't the default setting right?

This was only intended as a shim for Azure uses who couldn't/wouldn't use the Redis session store to fix the 8K session size problem until we refactored session encoding & compression here: https://github.com/oauth2-proxy/oauth2-proxy/pull/632

I think that fixed the issue for most Azure users, but some might still have large sessions.

**Comment by NickMeves** [comment]
We have our eye on dynamic claims -> sessions in the near future. This would be a good spot to support that as well 👍

**Comment by michael-freidgeim-webjet** [comment]
re-activate the issue.

**Comment by acobaugh** [comment]
Shall we use this issue to handle the extra claims feature? We've been maintaining our own fork (https://github.com/PennState/oauth2-proxy/tree/azure_testing) of oauth2-proxy that adds a `--pass-extra-claims` flag, which passes additional claims to backends via `x-auth-request-$claim` headers. We need this as there are two claims our apps need in order to authenticate users. It would be nice if similar functionality could be incorporated upstream so we don't have to keep maintaining our own branch. I only added extra claims support to the azure provider, so my fork isn't appropriate as-is.

**Comment by JoelSpeed** [comment]
I'm working on a prototype for generic claim extraction at the moment, that will be a gateway to allowing us to store additional claims across providers. I'll link back here when I get the PR up for that

**Comment by acobaugh** [comment]
Excellent, thank you. I'm looking forward to it.

**Comment by MNF** [comment]
re-activate the issue.

**Comment by MNF** [comment]
the issue is still relevant

**Comment by JoelSpeed** [comment]
We are making baby steps towards this feature, it is on the roadmap, but I don't have a timeline for it right now

**Comment by michael-freidgeim-webjet** [comment]
the issue is still relevant

**Comment by MNF** [comment]
[github-actions](https://github.com/apps/github-actions) bot closed this as [completed](https://github.com/oauth2-proxy/oauth2-proxy/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [22 hours ago](https://github.com/oauth2-proxy/oauth2-proxy/issues/1148#event-6965677466) 
has  incorrect text. If you want to close it automatically, the text should be 
“ bot closed this as inactive”

**Comment by dlouzan** [comment]
This probably needs to be reopened? At least I do not see any reference to a PR solving it.

**Comment by dlouzan** [comment]
This is still an issue
