### ISSUE TITLE
Can oauth2-proxy be used to just validate oauth jwt tokens ?

### ISSUE THREAD

**Issue by ovidiubuligan** [oauth2-proxy/oauth2-proxy#1150]
I have searched through all the documentation,  and it is given that there will be a session cookie . For my use case I don't think I need the session cookie  and it is a lot simpler. It is a basic kubernetes ingress setup and I just want to protect some paths/subdomains.

To test what I want to do :
1. I login via the browser in an angular app that follows `Authorization Code with PKCE` for an openId Connect provider. (this is not connected at all with oauth2-proxy)
2. take the connect token return from openId connect provider 
3. do a `curl` to a secured subdomain  with just a `  curl -H "Authorization: Bearer <token>"  https://api.mycluster.com` or  `curl -H "Authorization: Bearer <token>"  https://mycluster.com/api`
4. if the validation passes for that token let the request through.

I do not see why I need the cookie for this.
Can this be achieved ?

**Comment by NickMeves** [comment]
Yup!

Check out the end of this article I wrote: https://medium.com/in-the-weeds/service-to-service-authentication-on-kubernetes-94dcb8216cdc

It goes into how to do it for service-to-service auth.  I've used the exact same architecture with CLI tools that use PKSE to get an OIDC ID Token to authenticate via Bearer headers with APIs.

**Comment by ovidiubuligan** [comment]
@NickMeves  I have forked an existing jwt validator project for now .I added JWKS endpoint support (it used hardcoded certs in config) and regex validation for claims . I can then set different claim rules on the k8s ingresses .For now it might be enough .

I have read the whole article . Thank you , it was very insightful. I have a small question about the article . Isn't everything from your article covered by Istio ? (I cannot use istio since we also have windows containers)

**Comment by NickMeves** [comment]
Istio can potentially do it all if you only care about machine-to-machine I think (I need to dig into Istio more)

The big advantage of OAuth2 Proxy for us was it could be the 1 sidecar to handle human SSO flows, machines & human CLI apps all in 1 -- while providing a common subject (either actual JWT or `X-Forwarded-User` header) to backend applications to perform universal authorization logic across machines & humans.

We also already had AWS IRSA support for our application servers, so it was easy to continue the paradigm in our case.
