### ISSUE TITLE
Allow to set custom public port to form the redirectURL

### ISSUE THREAD

**Issue by truong-hua** [oauth2-proxy/oauth2-proxy#1153]
The auto generated redirectURL here does not work in case that the public port is not a default one (80 or 443)

## Expected Behavior

Public port should be configurable via an parameter or env, ex: --public-port=1443

- Version used: oauth2-proxy  (built with go1.15.5)

**Comment by NickMeves** [comment]
Which redirect URL -- the redirect in the OAuth flow to the callback endpoint or the final redirect to the original URL?

If its the OAuth callback URL -- that can be set explicitly with `--redirect-url`

**Comment by JoelSpeed** [comment]
> If its the OAuth callback URL -- that can be set explicitly with --redirect-url

I just wanted to add that this _should_ be set explicitly. In a future version we may require that it be set and remove the defaulting that we do today (it is a convenience after all)

**Comment by truong-hua** [comment]
> Which redirect URL -- the redirect in the OAuth flow to the callback endpoint or the final redirect to the original URL?
> 
> If its the OAuth callback URL -- that can be set explicitly with `--redirect-url`

I think it would be better for both. The --redirect-url is my current solution but it's likely a long way to reach the end result with a lot of risks and efforts.

In order to make a static --redirect-url to work with multiple domains we have to understand nginx config and adjust X-Auth-Request-Redirect. Then, we have to config a static final redirect url without using ENV or dynamic config elsewhere (because nginx does not support ENV and we may have different url/port on different environment), and it's really hard to make it sync with --redirect-url without knowledge about the HTTP Referer header. Unfortunately if someone using a strict Referer-Policy (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy), it will be again won't work. In reality, I have to update the example in README to remove the rd param because it will override the redirect header (we use the sign in page). These all are quite take time to resolve.

With just public port config the default oauth2-proxy will be worked easily and will be multiple environment friendly via ENV. Or if it can be detected automatically from the sign in page, it would be great.

Another point worth talking is that when I have multiple services which are authorizing via oauth2-proxy. If I config a static --redirect-url (to service A for example), it would mean that all other services will be depended on the service A for working. That why a dynamic redirect url is prefer (of course with non default public port allowed).

And may be more but I'm not remember now :D

**Comment by JoelSpeed** [comment]
Perhaps I'm not following quite how you're trying to use OAuth2 Proxy, but we should be compatible with everything you are trying to achieve already.

When you configure your identity provider, you have to give them a URL or URLs which are allowed for the redirection when you've finished authentication with them. This is what we call the OAuth callback URL or `redirect-url`. This typically has to be static with the IDP, hence why we encourage users to set this statically in the proxy as well.

To use OAuth2 Proxy with multiple domains, it is recommended to have OAuth2 Proxy on its own domain. So you'd set  the IDP redirect to something like `oauth2-proxy.my-domain.tld/oauth2/callback`.

When you access your application, `app1.my-domain.tld`, you would then have nginx set up the auth request module to check if the user is authenticated, and if not, redirect to `oauth2-proxy.my-domain.tld/oauth2/sign_in?rd=$scheme://$host$requesturi` (nginx will substitute these).

In all of these, you can include the port whereever you like and it should work.

The only final caveat of this setup is that you need to register the redirects (ie your application URLs) with OAuth2 Proxy using the whitelist domains option (which also supports non standard ports)
