### ISSUE TITLE
Proper syntax of using --skip-auth-route

### ISSUE THREAD

**Issue by mark-nexplore** [oauth2-proxy/oauth2-proxy#1154]
Hi,

I am trying to get `--skip-auth-route` working but hitting some bumps so hoping can get some advice.

The issue I am facing is there I have a routes:
- ^\/test\/?(.*)  in my ingress that needs to be authenticated ; but
- I do not want request going ^/test/no_auth\/?(.*) pass through authentication

So I tried to use `--skip-auth-route` with `^/test/no_auth\/.*` but it is different direct to the authentication server. Surprisingly I searched for quite some time to look for examples on how to do this properly but did not really get some real examples on this.

## Expected Behavior
Routes under ^/test/no_auth\/?(.*) should not pass through authentication

## Current Behavior
Routes under ^/test/no_auth\/?(.*)i is going through to authentication server and ignoring the regex defined in --skip-auth-regex

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
See above

## Your Environment
Oauth2 Proxy via Docker: quay.io/oauth2-proxy/oauth2-proxy:latest
AKS with Kubernetes 1.19.7

**Comment by NickMeves** [comment]
Implementation wise, it's just an array of regexes where if any match the path in the request, auth is skipped.  Here's the implementation if that helps you debug:

https://github.com/oauth2-proxy/oauth2-proxy/blob/42475c28f7f235c08777a24027fe8ec170763482/oauthproxy.go#L386

**Comment by Biboba** [comment]
I think it's because the documentation contains a typo:
"skip_auth_routes" should be used instead of "skip_auth_route":
[doc](https://github.com/oauth2-proxy/oauth2-proxy/blob/4f5efd4074098223aeee244b963dafa9cfd4924b/docs/docs/configuration/overview.md?plain=1#L183) VS [example](https://github.com/oauth2-proxy/oauth2-proxy/blob/6cc7da8993cf81dc0aae475edfd1632fd74d7818/contrib/oauth2-proxy.cfg.example#L67)

**Comment by jkjha** [comment]
> I think it's because the documentation contains a typo: "skip_auth_routes" should be used instead of "skip_auth_route": [doc](https://github.com/oauth2-proxy/oauth2-proxy/blob/4f5efd4074098223aeee244b963dafa9cfd4924b/docs/docs/configuration/overview.md?plain=1#L183) VS [example](https://github.com/oauth2-proxy/oauth2-proxy/blob/6cc7da8993cf81dc0aae475edfd1632fd74d7818/contrib/oauth2-proxy.cfg.example#L67)

@biboba , you saved my day. Thanks.
