### ISSUE TITLE
Provide darwin-amd64 docker images

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/oauth2-proxy#1155]
Please provide docker images for "darwin-amd64" as used on Apple MacBooks.

Currently https://quay.io/repository/oauth2-proxy/oauth2-proxy?tag=latest&tab=tags ony lists "linux-amd64" and some ARM variants.

It would be handy for testing the image locally using "docker-compose".

**Comment by JoelSpeed** [comment]
AFAIK docker for mac uses a linux VM under the hood (I do most of my dev on mac), so it should be fine to use the linux-amd64 images on mac

**Comment by lathspell** [comment]
Oh, indeed. I didn't even try because it seemed to impossible :-)
