### ISSUE TITLE
Setting `--htpasswd-user-group=<groupname>` doesn’t work when using GitLab as provider

### ISSUE THREAD

**Issue by johanfleury** [oauth2-proxy/oauth2-proxy#1157]
## Current Behavior

In version 7, I found myself unable to use htpasswd authentication when also using GitLab and restricting access to members of specific groups (with the `--gitlab-group` flags). oauth2-proxy raises the following errors:

```
[SNIPPED]:41840 - b4dd7fc9130fe002d2b7c660e1c9a279 - foo [2021/04/13 17:52:08] [AuthSuccess] Authenticated via basic auth and HTpasswd File
[SNIPPED]:41840 - b4dd7fc9130fe002d2b7c660e1c9a279 - - [2021/04/13 17:52:08] [AuthFailure] Invalid authorization via session: removing session Session{email: user:foo PreferredUsername:}
```

The `--htpasswd-user-group` flag seemed to be what I was looking for, but setting it as `--htpasswd-user-group=<groupname>` didn’t work and I had to prefix the group name with `group:` (i.e. `--htpasswd-user-group=group:<groupname>`).

This is an undocumented behavior.

## Expected Behavior

One should be able to set a list of group names in `--htpasswd-user-group` without prefixing them with `group:` or `project:`.

## Possible Solution

One solution would be to internally prepend `group:` to the group names passed to `--htpasswd-user-group` when provider is `gitlab`.

Another solution would be to do nothing but have a statement regarding this behavior in the documentation.

## Steps to Reproduce (for bugs)

* Deploy oauth2-proxy with `--provider=gitlab`, `--gitlab-group=<groupname>`, `--htpasswd-file=<path>` `--htpasswd-user-group=<groupname>`
* Notice that connecting using basic auth doesn’t work
* Change `--htpasswd-user-group=<groupname>` to `--htpasswd-user-group=group:<groupname>`
* Notice that it now works

## Context

I’m using oauth2-proxy to limit access to some pages that needs to be accessed by both OAuth2 capable client (humans) and robots.

## Your Environment

- Version used: Docker image from bitnami: `bitnami/oauth2-proxy:7`

**Comment by NickMeves** [comment]
Good catch!

I intend to migrate the GitLab provider to be based on OIDC and remove its custom behavior where groups is prefixed by `groups:` and standardize that any role-like structure actually called groups doesn't get the prefix (e.g. project, role, etc)

**Comment by NickMeves** [comment]
CC: @JoelSpeed Any objections to changing this convention where things with multiple group-like structures only prefix with their specialized name? While `group` actually just goes in `session.Groups` without a prefix?

Makes inheriting from the OIDC provider much more standard and clean in the future (and rides its functionality that doesn't prefix group claims).

Gitlab was the only provider we made the switch so far to prefix everything (even group with conflicts).

**Comment by JoelSpeed** [comment]
What is the intention here? So that a project would prefix but a group wouldn't? I think that possibly makes it confusing when you are using that particular provider does it not?

**Comment by johanfleury** [comment]
I hate those bots

**Comment by NickMeves** [comment]
I forgot about this -- but coincidentally, this refactor PR will fix this: https://github.com/oauth2-proxy/oauth2-proxy/pull/1239
