### ISSUE TITLE
One Oauth2 proxy for multiple site

### ISSUE THREAD

**Issue by breedjaram** [oauth2-proxy/oauth2-proxy#1158]
I have a working oauth2-proxy connected to keycloak. Authentication works without a problem but does not behave as expected. 

## Current Behavior

Is it possible using one Oauth2-proxy for two separate website (two nginx ingress)? 
Currently if I log in to site1.example.com so  I have pass access to site2.example.com too!

## Expected Behavior

Is it possible to split access to site1.example.com and site2.example.com? (for example, based on user groups?)
Is it possible those groups was define in ingresses?

target:
GroupA has access to site1.example.com only
GroupB has access to site2.example.com only

## Your Environment

Oauth2 Proxy via: quay.io/oauth2-proxy/oauth2-proxy:latest
Keycloak:latest

**Comment by NickMeves** [comment]
You can give this a shot: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#upstreams-configuration

Another architecture is using the subrequest auth pattern in nginx. Here's an tutorial on doing that in kubernetes: https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

I use this in my company to protect all our internal applications with a single central access proxy based on OAuth2 Proxy. If you want to do per-site authorization rules, I added this PR which should cover that: https://github.com/oauth2-proxy/oauth2-proxy/pull/849

**Comment by breedjaram** [comment]
Restrict via nginx ingress works fine but how to define correctly allowed_groups parameter for nginx ingress?
Allowed groups should be defined in ingress?

When I define the ,,--allowed-group=group1,, parameter in central Oauth2-proxy so this configuration is valid for all nginx ingress. (which I don't want)

The solution of this problem is to define allowed_groups in ingress? For site1 site2 siteX ingress with another allowed_groups.

My actual configuration of ingress
```
annotations:
nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.example.com/oauth2/auth"
nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.example.com/oauth2/start?rd=$scheme://$best_http_host$request_uri"
nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
```

Oauth2-proxy config
```
        - --provider=keycloak
        - --client-id=keycloak
        - --client-secret=XXXXXXXXX
        - --cookie-secret=XXXXXXXXXX
        - --login-url=https://keycloak-example.com/auth/realms/local/protocol/openid-connect/auth
        - --redeem-url=https://keycloak-example.com/auth/realms/local/protocol/openid-connect/token
        - --profile-url=https://keycloak-example.com/auth/realms/local/protocol/openid-connect/userinfo
        - --validate-url=https://keycloak-example.com/auth/realms/local/protocol/openid-connect/userinfo
        - --email-domain=*
        - --scope=openid profile email users
        - --http-address=0.0.0.0:8091
```

**Comment by NickMeves** [comment]
For the `auth-url` annotation, its an optional querystring parameter:

```
- [#849](https://github.com/oauth2-proxy/oauth2-proxy/pull/849) `/oauth2/auth` `allowed_groups` querystring parameter can be paired with the `allowed-groups` configuration option.
  - The `allowed_groups` querystring parameter can specify multiple comma delimited groups.
  - In this scenario, the user must have a group (from their multiple groups) present in both lists to not get a 401 or 403 response code.
  - Example:
    - OAuth2-Proxy globally sets the `allowed_groups` as `engineering`.
    - An application using Kubernetes ingress uses the `/oauth2/auth` endpoint with `allowed_groups` querystring set to `backend`.
    - A user must have a session with the groups `["engineering", "backend"]` to pass authorization.
    - Another user with the groups `["engineering", "frontend"]` would fail the querystring authorization portion.
```

**Comment by breedjaram** [comment]
Great this parameter in ingress works. That's exactly what I need.

Many thanks @NickMeves
