### ISSUE TITLE
Feature request: Support for OpenTracing

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/oauth2-proxy#1160]
## Expected Behavior

Please add support for OpenTracing. 

Also see previously closed tickets #1076 and #237 

## Current Behavior

No support.

## Possible Solution

Please note that supporting the creation and forwarding of the uber-trace-id alone would be beneficial.
That should be very simple to implement. The export of the trace or generating own spans would be nice to have but not necessary.
There is an existing library that could be used https://github.com/opentracing/opentracing-go

* Support "uber-trace-id" HTTP Header
** Forward existing "uber-trace-id" HTTP Header to upstream
** Create "uber-trace-id" HTTP Header according to spec if non-existing
** Log "uber-trace-id" as Request-Id

* Support OpenTracing export
** Export trace information via UDP to collector (e.g. a Jaeger Server)

* Support Spans
** Requests to the OAuth2 Server could be enhanced with a uber-trace-id that contains a random Span-Id so that e.g. Token Renewal Requests can be correlated with the incoming customer requests that caused them

* Support Metrics
** Number of Trace-Ids and Spans created
** Number of Traces exported successfully and with errors

**Comment by lathspell** [comment]
I got something working that does the trick for me. It's not meant as a merge request as I'm no real Go programmer but just hacked something together but it creates an OpenTracing Id for Request-Id, inserts it into the upstream header and even reports it to the Jaeger Server.

It's a diff and not a Github clone, sorry for that but it's only 135 lines long:

```
diff --git a/go.mod b/go.mod
index 9cb43c08..8da0e19e 100644
--- a/go.mod
+++ b/go.mod
@@ -20,12 +20,15 @@ require (
 	github.com/oauth2-proxy/tools/reference-gen v0.0.0-20210118095127-56ffd7384404
 	github.com/onsi/ginkgo v1.14.1
 	github.com/onsi/gomega v1.10.2
+	github.com/opentracing/opentracing-go v1.1.0
 	github.com/pierrec/lz4 v2.5.2+incompatible
 	github.com/pquerna/cachecontrol v0.0.0-20180517163645-1555304b9b35 // indirect
 	github.com/prometheus/client_golang v1.9.0
 	github.com/spf13/pflag v1.0.5
 	github.com/spf13/viper v1.6.3
 	github.com/stretchr/testify v1.6.1
+	github.com/uber/jaeger-client-go v2.17.0+incompatible
+	github.com/uber/jaeger-lib v2.4.1+incompatible // indirect
 	github.com/vmihailenco/msgpack/v4 v4.3.11
 	github.com/yhat/wsutil v0.0.0-20170731153501-1d66fa95c997
 	golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
diff --git a/main.go b/main.go
index 97f2c5a0..0e70e3db 100644
--- a/main.go
+++ b/main.go
@@ -11,7 +11,9 @@ import (
 	"github.com/oauth2-proxy/oauth2-proxy/v7/pkg/apis/options"
 	"github.com/oauth2-proxy/oauth2-proxy/v7/pkg/logger"
 	"github.com/oauth2-proxy/oauth2-proxy/v7/pkg/validation"
+	"github.com/opentracing/opentracing-go"
 	"github.com/spf13/pflag"
+	jaegercfg "github.com/uber/jaeger-client-go/config"
 )
 
 func main() {
@@ -62,11 +64,54 @@ func main() {
 
 	rand.Seed(time.Now().UnixNano())
 
+	initOpenTracing()
+
 	if err := oauthproxy.Start(); err != nil {
 		logger.Fatalf("ERROR: Failed to start OAuth2 Proxy: %v", err)
 	}
 }
 
+// OpenTracing initialization
+func initOpenTracing() {
+	cfg, err := jaegercfg.FromEnv()
+	if err != nil {
+		// parsing errors might happen here, such as when we get a string where we expect a number
+		logger.Printf("Could not parse Jaeger env vars: %s", err.Error())
+		return
+	}
+	// cfg.ServiceName = "oauth2-proxy"
+	// cfg.Sampler.Type = "const"
+	// cfg.Sampler.Param = 1
+	// cfg.Reporter.LogSpans = true
+	// cfg.Reporter.QueueSize = 10
+	// cfg.Reporter.BufferFlushInterval = 1 * time.Second
+	// cfg.Reporter.LocalAgentHostPort = "localhost:6831"
+
+	jaegerLogger := JaegerLoggerAdapter{} // oder jaeger.StdLogger
+	tracer, _, err := cfg.NewTracer(jaegercfg.Logger(jaegerLogger))
+	if err != nil {
+		logger.Printf("Could not initialize jaeger tracer: %s", err.Error())
+		return
+	}
+	// defer closer.Close() - better not as it would be closed at the end of this method?
+
+	opentracing.SetGlobalTracer(tracer)
+
+	parent := opentracing.GlobalTracer().StartSpan("init")
+	parent.Finish()
+}
+
+type JaegerLoggerAdapter struct {
+}
+
+func (j JaegerLoggerAdapter) Error(msg string) {
+	logger.Error(msg)
+}
+
+func (j JaegerLoggerAdapter) Infof(msg string, args ...interface{}) {
+	logger.Printf(msg, args...)
+}
+
 // loadConfiguration will load in the user's configuration.
 // It will either load the alpha configuration (if alphaConfig is given)
 // or the legacy configuration.
diff --git a/oauthproxy.go b/oauthproxy.go
index 9c307368..68acd929 100644
--- a/oauthproxy.go
+++ b/oauthproxy.go
@@ -274,7 +274,9 @@ func (p *OAuthProxy) setupServer(opts *options.Options) error {
 // the OAuth2 Proxy authentication logic kicks in.
 // For example forcing HTTPS or health checks.
 func buildPreAuthChain(opts *options.Options) (alice.Chain, error) {
-	chain := alice.New(middleware.NewScope(opts.ReverseProxy, opts.Logging.RequestIDHeader))
+	chain := alice.New(middleware.NewOpenTracing())
+
+	chain = chain.Append(middleware.NewScope(opts.ReverseProxy, opts.Logging.RequestIDHeader))
 
 	if opts.ForceHTTPS {
 		_, httpsPort, err := net.SplitHostPort(opts.Server.SecureBindAddress)
diff --git a/pkg/middleware/open_tracing.go b/pkg/middleware/open_tracing.go
new file mode 100644
index 00000000..e327be5b
--- /dev/null
+++ b/pkg/middleware/open_tracing.go
@@ -0,0 +1,25 @@
+package middleware
+
+import (
+	"net/http"
+
+	"github.com/justinas/alice"
+	"github.com/oauth2-proxy/oauth2-proxy/v7/pkg/logger"
+	"github.com/opentracing/opentracing-go"
+)
+
+func NewOpenTracing() alice.Constructor {
+	return func(next http.Handler) http.Handler {
+		return http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
+			span := opentracing.GlobalTracer().StartSpan("request")
+			carrier := opentracing.HTTPHeadersCarrier(req.Header)
+			err := span.Tracer().Inject(span.Context(), opentracing.HTTPHeaders, carrier)
+			if err != nil {
+				logger.Errorf("Error injecting OpenTracing Header: %v", err)
+			}
+			defer span.Finish()
+
+			next.ServeHTTP(rw, req)
+		})
+	}
+}
```

**Comment by NickMeves** [comment]
Yes! +1

@JoelSpeed and I definitely want support for tracing in the project at some point.

Neither of us has subject matter expertise in the space though, so we were looking for someone in the community with expertise on OpenTelemetry to guide the way as far as implementation & instrumentation best practices.

OpenTracing has merged into OpenTelemetry now, right?

**Comment by frittentheke** [comment]
@NickMeves Thanks for considering to add tracing. With oauth2-proxy being a vital part a of request flow for one's own application, being able to facilitate tracing would great!

Yes, OpenTelemetry (https://github.com/open-telemetry/opentelemetry-go) is the way forward, since, as you have mentioned yourself, the projects OpenCensus and OpenTracing have merged or are actually still in the very active process of doing so.
By making use of their SDK the instrumentation within your code will then be quite agnostic to the actual tracers. You can also make use of the existing instrumentation that are available for various libraries, especially for the HTTP, REST, gRPC communication (https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation)
You are then able to support different exporters, such as Jaeger or Zipkin (see: https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters) or even switch to OLTP (https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp) which intends to also standardize the span export / transport. Also support for the different header formats (Zipkin B3, Jaeger or the standardized W3C format) is available.

In any case, don't go all out on supporting tracing initially, but be a "good citizen" in handling HTTP requests and support propagation of the correlation headers and export a single span for the request going through oauth2-proxy. Tracing of i.e. the upstream requests to auth providers or adding more baggage to the spans can follow. But without propagation of the headers oauth2-proxy is kind of a blackhole to tracing attempts.

**Comment by lathspell** [comment]
hands off, github-actions bot!
