### ISSUE TITLE
Can't find data in Redis, Even after providing config, Browser Cookie is used for session store

### ISSUE THREAD

**Issue by Rahul1804** [oauth2-proxy/oauth2-proxy#1161]
I'm using "quay.io/oauth2-proxy/oauth2-proxy:latest" image in kubernetes 1.8.6 along with Istio-1.9.2. Keycloak is OIDC provider. I've used redis session store type , still I see session is getting stored in browser cookie, in redis I can't see any data. Please help me to fix this. Below is my Oauth2-Proxy setup. 

apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
  - name: http
    port: 4180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        args:
        - --session-store-type=redis
        - --redis-connection-url=redis://redis-master.redis.svc.cluster.local:6379
        - --provider=keycloak
        - --cookie-samesite=lax
        - --cookie-refresh=1h
        - --cookie-expire=4h
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --set-authorization-header=true
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --upstream=static://200
        - --skip-provider-button=true
        - --whitelist-domain=.hpecorp.net
        - --oidc-issuer-url=http://keycloak-url:10003/auth/realms/testrealm
        - --login-url=http://keycloak-url:10003/auth/realms/testrealm/protocol/openid-connect/auth
        - --redeem-url=http://keycloak-url:10003/auth/realms/testrealm/protocol/openid-connect/token
        - --validate-url=http://keycloak-url:10003/auth/realms/testrealm/protocol/openid-connect/userinfo
        - --profile-url=http://keycloak-url:10003/auth/realms/testrealm/protocol/openid-connect/userinfo
        - --standard-logging=true
        - --auth-logging=true
        - --request-logging=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: testclient
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: a64bc82a-8d8b-4f09-930c-ce4cd1463661
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: 892c869573095108535811657f0408ea
        ports:
        - containerPort: 4180
          protocol: TCP

**Comment by Rahul1804** [comment]
@NickMeves : Hey Nick, could you please help me out or redirect me somewhere, I could not find much why this is not working.

**Comment by JoelSpeed** [comment]
Hey @Rahul1804, when you see the sessions still being created as cookies, could you confirm their approximate size? 
Even with Redis storage, we still use a cookie to track the session, but instead of storing the session data, we just store the id of the session ticket. So if you were to switch from cookies to redis for the storage, you will still see cookies, but the size would drop from ~1000-4000kb to ~100kb

**Comment by Rahul1804** [comment]
Hey @JoelSpeed, thank you for reply. It's same data in cookie even after using redis, the cookie data has not changed. If I do SCAN 0 or KEYS * in redis-cli I can't see any data.

**Comment by Rahul1804** [comment]
And I verified the cookie remains same. My redis service is reachable to oauth2-proxy pod.

**Comment by JoelSpeed** [comment]
I haven't tried out the redis storage or any of this logic recently, and we don't have a local testing environment for redis either (that's going on my TODO list), so I can't easily check.

Is there anything in the logging of OAuth2 Proxy that my suggest whether it is even attempting to connect to redis?

**Comment by Rahul1804** [comment]
Only thing which I tested if I pass wrong redis url, the pod doesn't start and gives me error. If the url is fine below is the log

# kubectl logs oauth2-proxy-565cf8dff-w9k57 -n oauth2-proxy
[2021/04/20 16:54:06] [proxy.go:58] mapping path "/" => static response 200
[2021/04/20 16:54:06] [oauthproxy.go:149] OAuthProxy configured for Keycloak Client ID: testclient
[2021/04/20 16:54:06] [oauthproxy.go:155] Cookie settings: name:_oauth2_proxy_istio_ingressgateway secure(https):true httponly:true expiry:4h0m0s domains:.hpecorp.net path:/ samesite:lax refresh:after 1h0m0s

**Comment by NickMeves** [comment]
> ~1000-4000kb to ~100kb

He means bytes, not KB 😄 

4,000 KB would be one crazy cookie. If you are truly getting cookie session stores, they are larger, about 1-4KB like @JoelSpeed mentioned.

If you have a Redis session, the cookie is set to `<16 byte ID>.<32? byte Base64 secret>|timestamp|<sha256 of this cookie payload>`

**Comment by NickMeves** [comment]
Oh - you might want to try adding the redis DB number explicitly to your URL? Maybe that's what's missing:

`- --redis-connection-url=redis://redis-master.redis.svc.cluster.local:6379/0`

I don't know if that is mandatory of it that already defaults to DB 0.

**Comment by Rahul1804** [comment]
@NickMeves And redis will store the actual session data and browser cookie will have {CookieName}-{ticketID}.{secret} this thing only.

**Comment by NickMeves** [comment]
> @NickMeves And redis will store the actual session data and browser cookie will have {CookieName}-{ticketID}.{secret} this thing only.

Yeah - Redis will store the `SessionState` - encrypted in Redis with the `{secret}` part of the cookie. It will be stored in `{ticketID}` (likely with some prefix I can't recall) as the KEY in Redis.

**Comment by Rahul1804** [comment]
I tried DB number as well. By default it will be consider 0.

**Comment by NickMeves** [comment]
And no errors emitted from Oauth2-Proxy but you get a valid Redis type session cookie? But I take it sessions aren't working, or they are?

And no auth on Redis?

**Comment by Rahul1804** [comment]
> And no errors emitted from Oauth2-Proxy but you get a valid Redis type session cookie? But I take it sessions aren't working, or they are?
> 
> And no auth on Redis?

Yes, while testing [stored_session.go:76] Error loading cookied session: http: named cookie not present, removing session I saw this but there is a thread where you have mention that it's default behavior?
Yes, no auth on redis.

**Comment by Rahul1804** [comment]
This one https://github.com/oauth2-proxy/oauth2-proxy/issues/998

**Comment by Rahul1804** [comment]
> And no errors emitted from Oauth2-Proxy but you get a valid Redis type session cookie? But I take it sessions aren't working, or they are?
> 
> And no auth on Redis?

I can see actual session data in browser only, even if I use redis storage. Is there any limit on size of session if it's greater than x byte otherwise store in browser client. I could not find this in code though.

**Comment by NickMeves** [comment]
No - if you say type: Redis (and it seems like you do if you get errors if you try an invalid URL). We use Redis, we don't fallback to cookie sessions (cookie sessions have more limitations because web servers cap out at 8KB request headers).

It seems like you need to `tcpdump` that proxy:redis interaction to see what is going wrong if nothing is emitted from the logs.

**Comment by Rahul1804** [comment]
> No - if you say type: Redis (and it seems like you do if you get errors if you try an invalid URL). We use Redis, we don't fallback to cookie sessions (cookie sessions have more limitations because web servers cap out at 8KB request headers).
> 
> It seems like you need to `tcpdump` that proxy:redis interaction to see what is going wrong if nothing is emitted from the logs.

Yes, from logs, I could not find anything.

This is only error in oauth2-proxy pod - Is it removing the data from redis.?
[stored_session.go:76] Error loading cookied session: http: named cookie not present, removing session

**Comment by NickMeves** [comment]
It looks like in your configuration you are doing HTTP and not HTTPS from the details you sent above?

You have `secure` cookies set:
```
[2021/04/20 16:54:06] [oauthproxy.go:155] Cookie settings: name:_oauth2_proxy_istio_ingressgateway secure(https):true httponly:true expiry:4h0m0s domains:.hpecorp.net path:/ samesite:lax refresh:after 1h0m0s
```

Hence no session cookies sent with your requests (`http: named cookie not preset` part of the error) if that is the case.

This would also likely make the CSRF cookies during the initial signon flow fail (so you never get to the point where a session would be created in redis).

**Comment by Rahul1804** [comment]
Hey @NickMeves @JoelSpeed do you guys have any oauth2-proxy design document or any document which can help me to understand it more.

**Comment by Rahul1804** [comment]
Thank you Nick and Joel, I was able to solve the issue. But I want understand one more thing. If I want to get Authorization header(JWT Token) to application container. How should I do that.
Keycloak -> Oauth2-Proxy(JWT Token) -> Envoy(JWT Token) -> Application(It has JWT token in request header).

PS: I'm using OIDC provider(- --provider=oidc) now instead of Keycloak.

I'm sorry for too many questions, if you want I can open a new thread. Please let me know.

CC: @JoelSpeed @NickMeves

**Comment by NickMeves** [comment]
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/

`--pass-authorization-header` is likely what you want.

**Comment by mnsaybi** [comment]
> Thank you Nick and Joel, I was able to solve the issue. But I want understand one more thing. If I want to get Authorization header(JWT Token) to application container. How should I do that. Keycloak -> Oauth2-Proxy(JWT Token) -> Envoy(JWT Token) -> Application(It has JWT token in request header).
> 
> PS: I'm using OIDC provider(- --provider=oidc) now instead of Keycloak.
> 
> I'm sorry for too many questions, if you want I can open a new thread. Please let me know.
> 
> CC: @JoelSpeed @NickMeves

@Rahul1804 Could you please explain how did you resolved this issue. I got the same problem when using redis storage session
checking redis KEYS I did'nt find my oauth2 proxy key ! seems key not stored in redis
any help is appreciated 
Thanks
