### ISSUE TITLE
Metric server startup just on HTTP complains about lack of TLS Config

### ISSUE THREAD

**Issue by puneetbabbar26** [oauth2-proxy/oauth2-proxy#1163]
I have tried this on release 7.1.2, using docker, bypassing in the configuration as environment variables.

## Expected Behavior

Going by the configuration, the Metrics server should start as configured just by specifying the following configuration- 
OAUTH2_PROXY_METRICS_ADDRESS=":4280"

## Current Behavior

**The start of the OAUTH2_PROXY fails with the following error -** 
[2021/04/21 04:18:44] [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error setting up server: could not build metrics server: error setting up TLS listener: no TLS config provided

## Possible Solution

I figured out a workaround, I could get to work by specifying the following Configuration flag - 

OAUTH2_PROXY_HTTPS_ADDRESS="-"
OAUTH2_PROXY_METRICS_SECURE_ADDRESS="-"

Yes, you need to specify **both** somehow, specifying only OAUTH2_PROXY_METRICS_SECURE_ADDRESS didn't work.

Also, the documentation needs to be spruced up on how to specify values, when you don't want TLS 

The actual solution would be to get the metrics server to startup on HTTP with just OAUTH2_PROXY_METRICS_ADDRESS=":4280"

## Steps to Reproduce (for bugs)

1.  Just specify the configuration to start the Metrics server -> OAUTH2_PROXY_METRICS_ADDRESS=":4280"
2.  Start the OAUTH2 PROXY

## Context

Trying to get the Metrics server to run, so that I can make Prometheus scrape the metrics.

## Your Environment

- Version used: 7.1.2

**Comment by NickMeves** [comment]
Interesting - you are failing here: https://github.com/oauth2-proxy/oauth2-proxy/blob/7eeaea0b3f563c7e14f213e47dfda82b40f3fca1/pkg/http/server.go#L88

I thought those settings where set to `""` by default, equivalent to the `"-"` you are manually settings. @JoelSpeed & I will dig in.

**Comment by puneetbabbar26** [comment]
> Interesting - you are failing here:
> 
> https://github.com/oauth2-proxy/oauth2-proxy/blob/7eeaea0b3f563c7e14f213e47dfda82b40f3fca1/pkg/http/server.go#L88
> 
> I thought those settings where set to `""` by default, equivalent to the `"-"` you are manually settings. @JoelSpeed & I will dig in.

I looked at the code too, and thought it shouldn't happen, but I guess something else is happening while the configuration is mapped

**Comment by NickMeves** [comment]
@JoelSpeed spotted this issue -- we have a typo in the `cfg` variant of the flag.

https://github.com/oauth2-proxy/oauth2-proxy/blob/7eeaea0b3f563c7e14f213e47dfda82b40f3fca1/pkg/apis/options/legacy_options.go#L445

Environment variable configs are generated from the `cfg` name.
