### ISSUE TITLE
auth_request settings confusion

### ISSUE THREAD

**Issue by scarolac** [oauth2-proxy/oauth2-proxy#1164]
Our company is testing oauth2-proxy and we are trying to set it up to work with keycloak and pass the jwt along to the upstreams. Currently we have a frontend and backend running separately. When using oauth2-proxy in proxy mode, we can log in, get redirected correctly, and the backend has access to the bearer token to pull user data from, and log out with the keycloak signout address.

We wanted to be able to split auth to allow some pages to not need auth, one of them being "/", trying to do it in proxy mode didnt work since it would just allow everything through and negations didnt work, so we moved to auth_request within nginx.
Right now, setting up auth_request we can log in and get directed to the api correctly, but the authorization header is not coming through as our backend api throws a null pointer indicating that it is missing. Are there any working examples that people have been able to use, since everything we find is not giving enough information on how to setup nginx and oauth2-proxy in this way.
We have `set_authorization_header="true"` in the oauth config and tried variations of:
```
auth_request_set $token $upstream_http_authorization;
proxy_set_header Authorization $token;
```
within nginx.conf but can't seem to get the bearer token to come through. Any ideas?

**Comment by NickMeves** [comment]
The Keycloak provider is rather old and we are working on replacing it: https://github.com/oauth2-proxy/oauth2-proxy/issues/956

It only supports OAuth2 (not OIDC). So there's no IDToken to return in your `Authorization` header. That is my guess why you aren't getting a token back.

Until I find time to wrap up this PR (https://github.com/oauth2-proxy/oauth2-proxy/pull/1107), you should connect to your Keycloak instance with the OIDC provider.

**Comment by scarolac** [comment]
We didn't use the keycloak provider. We have it on oidc. This isn't a provider issue, this is a JWT passes in proxy mode, but not in nginx auth_request mode issue. We're trying to prevent "/" from being intercepted by the auth but still have something like "/admin" get picked up. If you skip "/" in proxy mode, it skips everything, so we did it in auth_request mode. It works, but now there is no JWT and we can't figure out how to get it to give the JWT again.

**Comment by scarolac** [comment]
Here are the configs we were trying. In the nginx.conf and oauth2-proxy.cfg you can see the commented out items that were turned on and off trying to get the token to come through in this way. When Oauth2-proxy is on top feeding into nginx it works with the JWT, when reversed with nginx on top feeding into oauth2-proxy as auth_request, no JWT :(

docker-compose.yml
```
version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 5000:5000
    volumes:
      - "/portainer/appdata/nginx-oauth2:/etc/nginx"
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command: --config /oauth2-proxy.cfg
    ports:
      - 4180:4180
    volumes:
      - "/portainer/appdata/nginx-oauth2/nginx-oauth2.cfg:/oauth2-proxy.cfg"

```
nginx.conf
```
    server {
        listen      5000;
        server_name localhost;

        location /oauth2/ {
            proxy_pass       http://oauth2-proxy:4180;
            proxy_set_header Host                    $host;
            proxy_set_header X-Real-IP               $remote_addr;
            proxy_set_header X-Scheme                $scheme;
            proxy_set_header X-Auth-Request-Redirect $request_uri;
            # proxy_set_header  Authorization    $http_authorization;
            # proxy_pass_header Authorization;
            # proxy_pass_header X-Access-Token;
            # proxy_set_header X-Auth-Request-Redirect $scheme://$host:$server_port$request_uri;
        }

        location = /oauth2/auth {
            proxy_pass              http://oauth2-proxy:4180;
            proxy_set_header        Host           $host;
            proxy_set_header        X-Real-IP      $remote_addr;
            proxy_set_header        X-Scheme       $scheme;
            # proxy_pass_header       Authorization;
            # proxy_set_header        Authorization  $http_authorization;
            # nginx auth_request includes headers but not body
            proxy_set_header        Content-Length "";
            proxy_pass_request_body off;
        }

        location /admin/ {
            auth_request     /oauth2/auth;
            error_page 401 = /oauth2/sign_in;

            # pass information via X-User and X-Email headers to backend,
            # requires running with --set-xauthrequest flag
            auth_request_set $user   $upstream_http_x_auth_request_user;
            auth_request_set $email  $upstream_http_x_auth_request_email;
            proxy_set_header X-User  $user;
            proxy_set_header X-Email $email;

            # # if you enabled --pass-access-token, this will pass the token to the backend
            # auth_request_set $token  $upstream_http_x_auth_request_access_token;
            # proxy_set_header X-Access-Token $token;

            auth_request_set $token $upstream_http_authorization;
            proxy_set_header Authorization $token;

            # if you enabled --cookie-refresh, this is needed for it to work with auth_request
            auth_request_set $auth_cookie $upstream_http_set_cookie;
            add_header Set-Cookie $auth_cookie;

            # When using the --set-authorization-header flag, some provider's cookies can exceed the 4kb
            # limit and so the OAuth2 Proxy splits these into multiple parts.
            # Nginx normally only copies the first `Set-Cookie` header from the auth_request to the response,
            # so if your cookies are larger than 4kb, you will need to extract additional cookies manually.
            auth_request_set $auth_cookie_name_upstream_1 $upstream_cookie_auth_cookie_name_1;

            # Extract the Cookie attributes from the first Set-Cookie header and append them
            # to the second part ($upstream_cookie_* variables only contain the raw cookie content)
            if ($auth_cookie ~* "(; .*)") {
                set $auth_cookie_name_0 $auth_cookie;
                set $auth_cookie_name_1 "auth_cookie_name_1=$auth_cookie_name_upstream_1$1";
            }

            # Send both Set-Cookie headers now if there was a second part
            if ($auth_cookie_name_upstream_1) {
                add_header Set-Cookie $auth_cookie_name_0;
                add_header Set-Cookie $auth_cookie_name_1;
            }
            
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host            $http_host;
            proxy_pass       http://192.168.1.48:3000/;
        }       
        
        location /api/ {
            proxy_pass        http://192.168.1.48:8080/;
            proxy_set_header  Host               $host;
            proxy_set_header  X-Real-IP          $remote_addr;
            proxy_set_header  X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header  X-Forwarded-Host   $host;
            proxy_set_header  X-Forwarded-Server $host;
            proxy_set_header  X-Forwarded-Port   $server_port;
            proxy_set_header  X-Forwarded-Proto  $scheme;
            proxy_set_header Authorization $token;
        }

        location / {
            proxy_pass       http://192.168.1.48:3000/;
            proxy_set_header Host               $host;
            proxy_set_header X-Real-IP          $remote_addr;
            proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host   $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-Port   $server_port;
            proxy_set_header X-Forwarded-Proto  $scheme;
            proxy_set_header Authorization $token;
        }
```
oauth2-proxy.cfg
```
http_address="0.0.0.0:4180"
upstreams=[
    "http://nginx:5000"
]
redirect_url="http://localhost:5000/oauth2/callback"
# Generate cookie secret
# python3 -c 'import os,base64; print(base64.urlsafe_b64encode(os.urandom(32)).decode())'
cookie_secret="OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
cookie_secure="false"
email_domains=[
    "*"
] 
whitelist_domains=[
    "*"
]
# cookie_domains=[
#     "*"
# ]

reverse_proxy="true"
set_xauthrequest="true"
set_authorization_header="true"
pass_access_token="true"
pass_authorization_header="true"

# keycloak provider
provider="oidc"
provider_display_name="Keycloak"
oidc_issuer_url="http://192.168.1.48:9090/auth/realms/platform-two"
client_id="platform-two"
client_secret="1360c2a9-4ac2-40c6-b0e9-77e1daf59473"
skip_provider_button="true"

# TODO: remove if prod
insecure_oidc_allow_unverified_email="true"
```

Don't worry about the "secrets" this is all a test environment.

**Comment by scarolac** [comment]
After logging in, hitting /oauth2/auth shows the full bearer token with the correct data inside. I figured it was an nginx setting anyway since I have no idea what it would be, you can see all my commented out items. That was me turning things on and off in various places to see what happened.

**Comment by JoelSpeed** [comment]
Have you got other headers working, eg the `X-Email` and `X-User` ones that you've set?

I wonder if there's a problem here with the Authorization token being too big to fit in a header, and therefore being dropped by nginx? (It is quite strict with the 4kb limit)

**Comment by scarolac** [comment]
I'm not sure, we only check for the bearer token, I just copied over the settings listed in the docs. We don't usually use nginx so we couldn't figure out how to grab a header from one endpoint and bring it to the others. I tried proxy_pass in different places but I'm not sure if I used it correctly. If I wanted that header in the /admin and /api paths, how do I get it there from the /oauth/auth path? I figured there is something we're missing in that process, just grab the header from one endpoint and carry it to the others.

**Comment by sedghi** [comment]
@scarolac I'm experiencing the same issue. Do you recall if you solved this problem three years ago?

**Comment by scarolac** [comment]
no i never figured out how to split the paths, it seemed to be all or nothing. maybe if you break the app in half and have a login half going through oauth proxy and the rest just hosted normally.

**Comment by chlinwei** [comment]
the same ,    auth_request /oauth2/auth;  affect all the location block in nginx.conf  even if auth_request just in one location block.
