### ISSUE TITLE
Sending Basic Auth to Upstream

### ISSUE THREAD

**Issue by knightian** [oauth2-proxy/oauth2-proxy#1166]
Hello,

From the documentation it is not obvious how to send the basic http auth credentials to upstream.

I can see the `--basic-auth-password` that says it takes a string, but what sort of string? Base64 encoded string?

Also I can't seem to find anywhere to put the username. So for e.g. if I would normally access by https://user:password@mydomain.com then how do I do this in oauth2-proxy?

**Comment by ianroberts** [comment]
> I can see the --basic-auth-password that says it takes a string, but what sort of string?

A plain string with the password that will be used for every user in the faked BASIC `Authorization` header.  I just use the word "password".

> Also I can't seem to find anywhere to put the username. So for e.g. if I would normally access by https://user:password@mydomain.com then how do I do this in oauth2-proxy?

The way the "fake basic auth" mechanism works is to send a basic auth header with the username returned by the identity provider (i.e. the same value as in the `X-Forwarded-User` header), but with the same (fixed) password for all users.

**Comment by JoelSpeed** [comment]
If you want to send a fixed header value for every authenticated user, you can do this using our alpha config which allows you to inject headers in a more flexible manner.

My advice would be to generate your static value:

```
$ USERPASS=$(echo -n "user:password" | base64)
$ echo -n "Basic $USERPASS" | base64
<base64 encoded string for the header>
```

And then use the alpha config:

```
injectRequestHeaders:
- name: Authorization
  values:
  - value: <base64 encoded string for the header>
```
This will then inject the header into every authenticated request
