### ISSUE TITLE
Add possibility to configure the browser redirect auth URL

### ISSUE THREAD

**Issue by jmarginier** [oauth2-proxy/oauth2-proxy#1167]
When I use Kubernetes, I want to do that : 

- INGRESS (example.com) -> oauth2proxy-svc -> webapp-svc (the upstream)
- INGRESS (auth.example.com)-> keycloak-svc 

*-svc => ClusterIp service
All components are inside the same Kubernetes cluster (same namespace too in fact).

My config map  (with alpha for inject headers) for the oauth2proxy : 
```
  oauth2.cfg: |- 
    ...
    reverse_proxy = "true"
    redirect_url = "http://example.com/oauth2/callback"
    client_secret="xxxx"
    client_id="xxxx"
    oidc_issuer_url="http://auth.example.com/auth/realms/master" //here we have the INGRESS URL
    provider="oidc"
    ....
```
```

oauth2-alpha.yaml: |-
    upstreams:
      - id: webapp
        path: /
        uri: 'http://webapp-svc'
...
```

The "oidc_issuer_url" cause a problem because the POD for oauth2proxy will call endpoint base on this URL but it's a INGRESS so it's not accessible ! 
But, if you use the ClusterIP (the keycloak service), it's not accessible from outside the cluster...

So may be it's necessary to distinct PUBLIC URL (use by the client browser) and the PRIVATE URL (use by oauth2proxy software) ?

Thanks

**Comment by TheAnachronism** [comment]
Why did you close this?
I'm currently facing the same issue, that it calls the IP directly but I have my identity provider running behind a reverse proxy.
