### ISSUE TITLE
JWT Token is not coming to Backend app only Encrypted Cookie I can see

### ISSUE THREAD

**Issue by Rahul1804** [oauth2-proxy/oauth2-proxy#1173]
Hi @JoelSpeed ,

I trying to use Oauth2-Proxy and KEYCLOAK OIDC with Istio+Kubernetes to provide AuthN/AuthZ to backend app. Now backend app expect Authorization header(JWT Token) , and backend app is not getting that.

Below is my config for Oauth2-Proxy deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        args:
        - --session-store-type=redis
        - --redis-connection-url=redis://redis-master.redis.svc.cluster.local:6379
        - --provider=oidc
        - --cookie-samesite=lax
        - --cookie-refresh=1h
        - --cookie-expire=4h
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --upstream=static://200
        - --skip-provider-button=true
        - --whitelist-domain=.xyz.net
        - --oidc-issuer-url=http://keycloak-service:10003/auth/realms/testrealm
        - --login-url=http://keycloak-service:10003/auth/realms/testrealm/protocol/openid-connect/auth
        - --redeem-url=http://keycloak-service:10003/auth/realms/testrealm/protocol/openid-connect/token
        - --validate-url=http://keycloak-service:10003/auth/realms/testrealm/protocol/openid-connect/userinfo
        - --profile-url=http://keycloak-service:10003/auth/realms/testrealm/protocol/openid-connect/userinfo
        - --standard-logging=true
        - --auth-logging=true
        - --request-logging=true
        - --cookie-secure=false
        - --cookie-name=_oauth2_proxy_istio_ingressgateway
        - --cookie-httponly=true
        - --cookie-domain=.xyz.net
        - --insecure-oidc-allow-unverified-email=true
        - --set-xauthrequest=true
        - --set-authorization-header=true
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --scope=openid
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: testclient
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: a64bc82a-8d8b-4f09-930c-ce4cd1463661
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: 892c869573095108535811657f0408ea
        ports:
        - containerPort: 4180
          protocol: TCP

-------------------------------------------------------------------
Below is Oauth2-Proxy pod logs

[2021/04/28 17:48:45] [options.go:169] WARNING: no explicit redirect URL: redirects will default to insecure HTTP
[2021/04/28 17:48:45] [proxy.go:58] mapping path "/" => static response 200
[2021/04/28 17:48:45] [oauthproxy.go:143] OAuthProxy configured for OpenID Connect Client ID: testclient
[2021/04/28 17:48:45] [oauthproxy.go:149] Cookie settings: name:_oauth2_proxy_istio_ingressgateway secure(https):false httponly:true expiry:4h0m0s domains:.xyz.net path:/ samesite:lax refresh:after 1h0m0s

[2021/04/28 17:49:22] [cookies.go:21] Warning: request host "backend-service:10009" did not match any of the specific cookie domains of ".xyz.net"
127.0.0.1:47496 - 1731cc09-04f3-4958-be98-7520acf64996 - - [2021/04/28 17:49:22] backend-service:10009 GET - "/" HTTP/1.1 "" 302 365 0.001
[2021/04/28 17:49:32] [cookies.go:21] Warning: request host "backend-service:10009" did not match any of the specific cookie domains of ".xyz.net"
127.0.0.1:47496 - 7d9dfdc2-499f-4862-b8f7-fb1c1a765272 - dev1@xyz.com [2021/04/28 17:49:32] [AuthSuccess] Authenticated via OAuth2: Session{email:dev1@xyz.com user:68601644-5c35-485c-9c72-c7ebeab54dc9 PreferredUsername:dev1 token:true id_token:true created:2021-04-28 17:49:32.210976433 +0000 UTC m=+46.933721912 expires:2021-04-28 17:54:32.205547518 +0000 UTC m=+346.928292998 refresh_token:true}

Could you please help me.

**Comment by Rahul1804** [comment]
If I just test Oauth2-Proxy and Keycloak, I'm getting authorization header in response header. Not sure why it's not reaching to backend application pod(app container + envoy sidecar container). Could you please help me to point me somewhere to debug it. Thank you !!

CC : @JoelSpeed @NickMeves

**Comment by holyjak** [comment]
Ok, so it seems the problem is not in oauth2-proxy but in your environment, right? I would suspect that something that sits between the proxy and your pod drops the headers and needs to be configured to pass them along. What, I have no idea.

**Comment by Rahul1804** [comment]
> Ok, so it seems the problem is not in oauth2-proxy but in your environment, right? I would suspect that something that sits between the proxy and your pod drops the headers and needs to be configured to pass them along. What, I have no idea.

Yes, EnvoyFilter and we can configure which headers it should pass to backend app (app container in my case).  I've mentioned authorization header in the config to be passed to the backend app. I've invested couple of days now, still it's not working :(

**Comment by Rahul1804** [comment]
> Ok, so it seems the problem is not in oauth2-proxy but in your environment, right? I would suspect that something that sits between the proxy and your pod drops the headers and needs to be configured to pass them along. What, I have no idea.

Hey @holyjak  How can I make sure that Oauth2-Proxy is send authorization header to envoy proxy before it reaches to actual  backend app.??

**Comment by NickMeves** [comment]
Last time I did this with a K8s Ingress via Nginx subrequests to `/oauth2/auth` I had no issues getting response headers and forwarding them to the backend as X-Auth-Request-* headers. It's admittedly been a while though (I think 6.1.1) since I last tried.

I recommend you play with local environments using the `contrib` part of the project to stand up some toy infrastructure. Remove `Envoy` from the equation and send requests to `httpbin` as a backend and confirm you get the headers you expect there.

**Comment by Rahul1804** [comment]
> Last time I did this with a K8s Ingress via Nginx subrequests to `/oauth2/auth` I had no issues getting response headers and forwarding them to the backend as X-Auth-Request-* headers. It's admittedly been a while though (I think 6.1.1) since I last tried.
> 
> I recommend you play with local environments using the `contrib` part of the project to stand up some toy infrastructure. Remove `Envoy` from the equation and send requests to `httpbin` as a backend and confirm you get the headers you expect there.

Hey @NickMeves - Yes in my browser, if I hit http://base-rul/oauth2/auth. I can see authorization header with JWT token. But not sure why it's not coming for just http://base-url.

**Comment by Rahul1804** [comment]
Hey @NickMeves I did try local setup

`curl -X GET "http://localhost:4180/get" -H "accept: application/json"`

response has not jwt token

```
{
  "args": {},
  "headers": {
    "Accept": "application/json",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-GB,en;q=0.9,hi-IN;q=0.8,hi;q=0.7,en-US;q=0.6",
    "Cookie": "_oauth2_proxy=9555bPEpOwcJwuHrqODAyISy_6sB_UXUeQUfZTPz6ywSb1TqOaULOz8wgSnSkLjffubzYM-Zk5N3OkZxskHua4XXDUEwEbSWy72GjyzCTTY-Tn5L0PVyyJGzZdeF8BNjCE_mFGyL6n630MJHVRkGZ2hN4tbXNCjV0Rcaa5tKcst_JJRvfFST845R3zDm4iHHR_hpRtCw_srw5da08Vl3VkhHcPwk3XRXGANyef0sODrQOE-hObQSNyG71VkplTS_SYSz6prtXhYTtsG6LaGiPtYl3caPOOhBIxrJP2YqYUAw5phvDFBGjSE7L3MKMom1LwtEISl-B1Lg0qkEqbxYXGXjNhFnrtMuj8kawpc_pSMdzXaC0E-gnLdUv3WMuUZNxSLY6fpvDj7AoEyyC9FQEbRLI0vtqmpnheaXGbD2nuqjhhINVOv4Srf3gXR-WonGobcSMie8zYeFzFRrw1vGvUJY2iv-OGPINBQMuJG80DuR2JkHewfV_JOidCejTYHesiXJnB6IXUJtjW-EtNNbAA80L4KhdesGg9Ugc0rm0oYd7rX10Vlg6n44dyZRhdTyR3xKnlVgf1sq7oeogUSqrs-CAdXE4vI0rInMegeocw1K4XGRJoK5_-WLSq6U-jeiwH5elbn2uqJ3uf4oRnh-5kbUhjniODZ-rJHrazgsQzH3vE9oVLcSctUNGoXLZva3b-PwAdetMwzr7agknaQR12aWCEurKSbZ32G_w3F_42oG2Px_AGTWL2uBx2zqyNhSGONKQE83YrjSPKHxbmq2NmyksFJxMdFBIN0Wf-JjY_avSG3LwwNXemRISz_jfgDDt4DDHDX_HbpZ2pqCwwBAavzbAr5ydd8qlp3ZPiPwtubDyPLSinWM2aWj1iTycWVixqnOD7ZlW9eDNJxBaTGJEeK6C3qcKUOtIBmmDlA4V7NBNMhOJ7hEnwae5xwEPIVpu7t44oUrQvemfD_gzLVTctb0714Ds_vZLsPqDofwcqnJWbGC_IErUkmuY1fRBvc3cswpkz3Hv9FwQnlf9qds98zDRGdJyZgRYYr0VJEJJDPYt1PcS4cc-jsHcmWLoLyJ2koIpafU0ITv4m9au8gDzCR4P52OtksLR43pxAarjJOF-Z_VFQXyypkUpDxODUbRfWl1YawViuQh9EktNKnrLDrloqhUcxf6XTMWC4AokpHUXt_9qYfF-WXfVIMbeeHsKNmnkOwcCeoosaCzdGJxOkpOI1YTaA_1ky1X8sikUpGYaaABEvO0lLH-73bIddcwsNbOsxsoc52pCIxeogLQukyguGyrVeZe0udQ1UXFB5SSdUmz8_tL0BJJSV5jctuGaesS1aH_wD3ueKGV_sJVx9YP_c270qLUBsGF_X_uS5YzeT7faTBPlbti0rXREEMGIUvxe3WEZXDS21upxZQ45LQhiTxwCZvvwvmBQMvnBsDxYAEQPROVglaNswqv9g5nAd5_-DysPwkBgDiF5JBOgRSMzsZmT98rMtOSi3U-bzwtOOxu97Xuhwjjk0INQnMRvqB1PfGkjUwV1UYakassqq4x6903n3a4CAoHH6fTXNw3kD6SQ33APGz1xMvQ0XJhJ_VLWV-m4HQD24oQJ10bUaHPwmzhwsvYf4T9aaLHjKHi5JHReHiXQmMiUe7ABSQsUkZsqJknxO0LkYFOkXiJq7K8lgnN-wAzmvzFZZK4aMZPYYsDv_tf9eN1qNnS93EP_LopClDvQ9Io3YwW1hgq0kJAJhCea1iOGbtZX2Pwee4RKPxdBITvg3nOO3Tw_YpIGdbBk-u9C9JnNVRZiyDk7lFi|1620277531|SB-ypo2xnfoAQr_blVF-bYnpbkwNhNiBjjUCsR9TxnM=",
    "Host": "localhost:4180",
    "Referer": "http://localhost:4180/",
    "Sec-Ch-Ua": "\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"",
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36",
    "X-Forwarded-Email": "admin@example.com",
    "X-Forwarded-User": "CiQwOGE4Njg0Yi1kYjg4LTRiNzMtOTBhOS0zY2QxNjYxZjU0NjYSBWxvY2Fs"
  },
  "origin": "172.20.0.1",
  "url": "http://localhost:4180/get"
}

```

**Comment by Rahul1804** [comment]
Hi @NickMeves , I wrote a LUA filter in envoy to check if authorization header is coming to envoy proxy. But it seems it is not send by oauth2-proxy. Output in headers- "no authorization found"
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
         inlineCode: |
            function envoy_on_response(response_handle)
                response_handle:logInfo(" ========= XXXXX ========== ")
                response_handle:headers():add("X-User-Header", "worked")
                local originalHeader = response_handle:headers():get("authorization")
                if originalHeader then
                  response_handle:headers():add("x-authorization", originalHeader)
                else
                  response_handle:headers():add("x-authorization", "no authorization found")
                end
            end
```

**Comment by Rahul1804** [comment]
@NickMeves @JoelSpeed  : Thank you guys, it worked for. I'm thinking to write a blog now Oauth2-Proxy with Istio or Envoy.
