### ISSUE TITLE
Add ability to connect to oidc provider with mTLS

### ISSUE THREAD

**Issue by iTaybb** [oauth2-proxy/oauth2-proxy#1174]
Currently, when trying to use an oidc provider which is enforcing mTLS, oauth2-proxy crashes.

## Expected Behavior

oauth2-proxy should authenticate with the provider with TLS certificates, if provided.

## Current Behavior

oauth2-proxy does not authenticate with the provider with TLS certificates.

## Possible Solution

add --provider-tls-cert and --provider-tls-key flags

## Your Environment

- Version used:
 7.1.3

**Comment by NickMeves** [comment]
Can you provide more details on which OIDC vendor you are using and link to their documentation for this feature?

**Comment by iTaybb** [comment]
It is basically Keycloak with an NGINX in front of him that is enforcing mTLS.
I just figured this might not be a very common case. We're doing it since we're bound to some regulations of our clients.
If you believe this is not common, please feel free to close the issue.

10x

**Comment by JoelSpeed** [comment]
I think this is definitely a legitimate use case, though I'm not sure how common of a request it would be.

In the Kubernetes world for example, people often implement mTLS using service meshes which tend to handle the mTLS without the application needing to be aware.

Do we know how easy it is for the Go client to add certificates for authentication?
