### ISSUE TITLE
ENV OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR is not working

### ISSUE THREAD

**Issue by iTaybb** [oauth2-proxy/oauth2-proxy#1178]
The environment variable `OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR` is not working.

## Expected Behavior

The environment variable `OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR` should affect whether a detailed error is showed on the error page or not.

## Current Behavior

The environment variable `OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR` has no effect, while the `--show-debug-on-error` command-line argument works as expected.

## Possible Solution

Golang isn't really my specialty, but the issue might be [here](https://github.com/oauth2-proxy/oauth2-proxy/blob/42475c28f7f235c08777a24027fe8ec170763482/pkg/apis/options/app.go#L36), perhaps the cfg value should be with underscores instead of dashes.

## Your Environment

- Version used: 7.1.3

**Comment by NickMeves** [comment]
Yup! That's definitely the error -- good catch. Do you want to open a PR with a fix?

**Comment by iTaybb** [comment]
I did. Thanks
