### ISSUE TITLE
Use Oauth2-proxy with mobile apps

### ISSUE THREAD

**Issue by LordEvron** [oauth2-proxy/oauth2-proxy#1182]
Hi, 

I Protected some upstream routes using: 
  oauth2-proxy --> Keycloak --> Google

Everything works fine in the browser and I am able to login and access the upstream routes. 
Now i want to do the same with Ionic App. 
What is the suggested way to do that? There is any API in Oauth2-proxy that allows me to fetch the Access token that i can then pass along? In which Header should put it?  In the issue https://github.com/bitly/oauth2_proxy/issues/571 they mentions a /token endpoint, but it does not seems to be in the documentation. 

If i create a new public client and fetch the token, can i then use it towards oauth2proxy and access the upstreams?
 
I would really appreciate some inputs on how this is normally solved. 

Thanks!

**Comment by zizitop13** [comment]
@LordEvron Hello! Could you please tell me how you dealt with your problem?

**Comment by deskoh** [comment]
@zizitop13 assuming your mobile as obtained the access token (e.g. via auth code flow), it can be provided to oauth2-proxy with `--skip-jwt-bearer-tokens` set and the request will be proxied to upstream.
