### ISSUE TITLE
--skip-jwt-bearer-tokens should be called --pass-jwt-bearer-tokens

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/oauth2-proxy#1185]
I found the name of this option rather confusing. It sounds like if OAuth2-Proxy should skip i.e. drop incoming requests with an "Authorization: Bearer ..." header while it actually means that OAuth2-Proxy validates this token, creates a new Session for it and then gladly passes it on to the backend. It's exactly the one option one must enable if applications, that somehow got an e.g. client credentials token for themselves, wants to pass requests through the proxy.

So shouldn't it be called "--pass-jwt-bearer-tokens" instead?

**Comment by NickMeves** [comment]
It doesn't actually pass the JWT to the backend (that is done with `pass-authorization-header`).

What this one does is set secondary OIDC issuer/audience pairs that are also valid to verify a bearer token (primary use case is primary provider is human facing SSO while machine accounts/PCKE CLI apps use bearer headers with this flag).

Admittedly, a lot of our flag names sucks 😅 -- But we won't change any of them unless they are especially egregious to not break backwards compatibility.

We are moving to structured configs in V8 -- so settings names are getting an overhaul then.

**Comment by NickMeves** [comment]
Here's an article I wrote on where this flag comes in handy: https://medium.com/in-the-weeds/service-to-service-authentication-on-kubernetes-94dcb8216cdc

**Comment by Brzhk** [comment]
May i suggest allow, as in 'allow-valid-token-bearing-requests' ?
