### ISSUE TITLE
Provider button not working with OIDC

### ISSUE THREAD

**Issue by Peperud** [oauth2-proxy/oauth2-proxy#1193]
When set with **_--skip-provider-button=false_** a screen with "Sign in with "OpenID connect" button is displayed, however clicking on the button has no effect.

## Expected Behavior
To properly continue the authentication flow after clicking the button

## Current Behavior
Authentication flow does not continue after pressing the button. Page bounces back to itself.

## Steps to Reproduce (for bugs)
Set oauth2_proxy for **oidc** and have **_--skip-provider-button=false_**

## Your Environment

- Version used:
quay.io/oauth2-proxy/oauth2-proxy:latest 
I believe it is 7.1.3 atm

**Comment by JoelSpeed** [comment]
I have just tried this on our local testing environment and have been unable to reproduce the issue, can you try the environment too and see if it works for you as expected?

You'll need docker and docker-compose, then from the root of this repo `make local-env-up`, once it's started, in a browser, `http://localhost:4180` should get you to a login page, try there and see if it works? If it does, you can start modifying the configuration until it matches/is more similar to yours and hopefully identify what breaks

To recreate once you change the config, delete the OAuth2 Proxy container and `make local-env-up` again.
To tear it down, `make local-env-down`.

**Comment by Peperud** [comment]
Apologies. I should have stated my full environment. It the one here https://github.com/oauth2-proxy/oauth2-proxy/issues/1194
