### ISSUE TITLE
Oauth2-proxy response /sign_in page when the upstream response 401 Unauthorized

### ISSUE THREAD

**Issue by truong-hua** [oauth2-proxy/oauth2-proxy#1195]
I'm not sure it's a bug or an expected behavior but in my case, the upstream will response 401 error if the client session is invalid or haven't been logged in. And it causes oauth2-proxy to response /sign_in page which will do set _oauth2_proxy cookie back to empty.

## Expected Behavior

Oauth2-proxy should respect the upstream response

## Current Behavior

Oauth2-proxy replace upstream response 401 with /sign_in

## Possible Solution

We try to block the request to upstream that cause 401 and by pass oauth2-proxy on these paths

## Steps to Reproduce (for bugs)

- Set up a nginx server that will response 401 on every request and make it upstream of the oauth2-proxy
- Go to http://oauth2-proxy/test-url
- Do login
- After redirect back to configured --redirect-uri, _oauth2_proxy cookie will be remove and the session is invalidate (some time it doesn't).

- Version used: oauth2-proxy  (built with go1.15.5)
- Docker Image: quay.io/pusher/oauth2_proxy:latest@sha256:5b1152e6caada09a5d3bf91fcba0f9b6ba04479ce3ab7438e57e629c3baa895d

**Comment by JoelSpeed** [comment]
Initially this seems like a valid behaviour. A 401 from the upstream implies that the user currently isn't valid, but if they were logged in as a different user, would be valid. It seems reasonable in this case for OAuth2 Proxy to attempt to get the user to sign in as a different user.

In the case that a user is logged in, but not allowed to access a resource, I would expect a 403 response from the upstream service, not a 401.

**Comment by truong-hua** [comment]
@JoelSpeed is there any way to disable that behavior? Our upstream has it's owned authorization but is not safe enough and we would like to place the OAuth2 Proxy in front of it :)

**Comment by JoelSpeed** [comment]
If you are trying to replace the authorization of your existing service, can you not turn it off?

As to whether this can be turned off, I'm not actually sure right now where this logic is coming from, so until we can work out why (where in the code) this is happening, I couldn't say whether there is a workaround or not

**Comment by truong-hua** [comment]
Actually, I just would like to keep both authorization (so a user have to authorize 2 times) and totally separated. You have any suggestion for me, @JoelSpeed ?

**Comment by truong-hua** [comment]
I found out the issue, it's not about Oauth2-proxy but Nginx
