### ISSUE TITLE
Cannot Connect to HTTPS Upstream 

### ISSUE THREAD

**Issue by eliavem** [oauth2-proxy/oauth2-proxy#1196]
I have a set up with Istio, oauth2-proxy and an external Authentication Server. This is an OpenID Connect Provider. The set up is a simple scenario. I have an app for which access is required. This app does not include log in or logout, I just want to be able to access the content ( not static ), and I'm using redis session store. I have expose the app and auth2-proxy on different domains, lets say: app.istio.domain and auth.proxy.domain. On a request, a matched SNI for my app domain, Istio ingress gateway will forward the request to oauth2-proxy. Since initially the user is not authenticated, the proxy will start the OIDC flow with the authentication provided. I'm using Authorization Code Flow. My redirect url in my provider is set to https://auth.proxy.domain/oauth2/callback. My issue is as follows:

If I set --upstream=https://app.istio.domain I get the issue "Error proxying to upstream server: x509: certificate signed by unknown authority" even tough this is not a self-sign cert. I then add --ssl-upstream-insecure-skip-verify=true. I then get "Access to app.istio.domain was denied". If I check the proxy logs I see this issue: "Error retrieving session from token in Authorization header: invalid authorization header: "Bearer eyJraWQiOiJORGF ... ". This shows multiple times in the logs. 

If I set  --upstream=http://app.appnamespace.svc.cluster.local:9080 it works but content is served in proxy url not in the original URL for my app. Is this a bug or some problem with my set up? 

## Expected Behavior

The application content should be served in the original application URL. 
Here is my configuration 

      - args:
        - --provider=oidc
        - --provider-display-name="OIDC Provider"
        - --email-domain=*
        - --set-xauthrequest=true
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --set-authorization-header=true
        - --upstream=https://app.istio.domain #modified domain also tried upstream=http://app.appnamespace.svc.cluster.local:9080
        - --oidc-issuer-url=https://mytenant.somedomain.com #all needed information exposed at /.well-known/openid-configuration
        - --standard-logging=true
        - --auth-logging=true
        - --request-logging=true
        - --skip-provider-button=true 
        - --redirect-url=https://auth.proxy.domain/oauth2/callback # modified domain
        - --skip-auth-strip-headers=false
        - --skip-jwt-bearer-tokens=true  
        - --session-store-type=redis
        - --redis-connection-url=redis://redis-release-master.redis.svc.cluster.local:6379
        - --redis-password=mypassword
        - --ssl-upstream-insecure-skip-verify=true
        - --cookie-domain=.istio.domain
        - --cookie-refresh=0 
        - --cookie-secure=true

ENV: OAUTH2_PROXY_CLIENT_ID OAUTH2_PROXY_CLIENT_SECRET OAUTH2_PROXY_COOKIE_SECRET are also set 

- Version used:
- oauth2-proxy:v7.1.2

**Comment by JoelSpeed** [comment]
Does your application support the ability to set the URL it expects to be served on? For example applications like wordpress allow this so that you can host them behind proxies in this way.

**Comment by eliavem** [comment]
It is a test app ( bookinfo ) provided by Istio. I cannot modify the application itself but create the necessary istio CRDs to expose the application (Gateway and Virtual Services). The application can then be accessed at APP_DOMAIN/productpage where APP_DOMAIN is just mapping to istio ingress url. There are other endpoints but not interested in those for now. The integration with Authentications services is for testing purposes, and the idea is to have Istio validate access token as well as offloading AuthZ and AuthN from the application. Basically, the application should not handle any OIDC logic or manage any tokens. Below is an example of the istio CRDs I have in place. Do you see any problems with what I'm trying to achieve? 

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: bookinfo
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 443
      name: https-istio-bookinfo
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istiotls 
    hosts:
    - bookinfo.istio.[domain]
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
  namespace: bookinfo
spec:
  hosts:
  - "bookinfo.istio.[domain]"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080

**Comment by JoelSpeed** [comment]
When using something like Istio, I would suggest looking into using the ext_authz functionality (there are many issues around users who've done this) so that OAuth2 Proxy doesn't actually act as a proxy, but more of an authentication side car
