### ISSUE TITLE
Kubernetes: per ingress group requirements

### ISSUE THREAD

**Issue by etfeet** [oauth2-proxy/oauth2-proxy#1197]
is it possible to use Kubernetes ingress annotations to enforce different group requirements on different ingresses?

ie ingress1:
  annotations: oauth2.groups.require: group1
  
  ie ingress2:
  annotations: oauth2.groups.require: some_other_group2
  
  looking at the current docs it looks like its a global flag for the oauth ingress instance itself.

**Comment by NickMeves** [comment]
Yup! https://github.com/oauth2-proxy/oauth2-proxy/pull/849

You can add the `allowed_groups` querystring parameter on the `/oauth2/auth` endpoint you set in the `nginx.ingress.kubernetes.io/auth-url` annotation in your ingress.

The CHANGELOG has detailed examples of using this new querystring field.

I used this pattern to hook in a bunch of internal applications with different ingresses with different authz rules into a central OAuth2 Proxy deployment.

**Comment by samhine** [comment]
> [@samhine](https://github.com/samhine) I think the issue is the @ symbol. Can you try without the add? Won't work for your role but this way you can check if the validation doesn't complain anymore. You might need to escape it somehow but that is a question towards nginx and the helm chart not oauth2-proxy

It does indeed work - I've had to turn off the `controller.enableAnnotationValidations` within my [`ingress-nginx` Helm chart](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L24C3-L24C30) which has resolved the issue! 

Bit annoying - not sure if you can modify those validation rules but I'm all set for now.
