### ISSUE TITLE
Oauth Proxy allowed_group dont work with Oracle IDP

### ISSUE THREAD

**Issue by sosiskin2000** [oauth2-proxy/oauth2-proxy#1198]
## Expected Behavior

Provided oidc, can parse groups returned from Oracle IDP

## Current Behavior
When i'm using run options --allowed-group=cheftest, its starts but say errors forbidden - but group exist:
```
10.244.1.4:47134 - 62b9bd56f1c7e4b43ea6b2331c0a24aa - anton.guts@oracle.com [2021/05/15 17:12:14] [AuthFailure] Invalid authentication via OAuth2: CSRF token mismatch, potential attack
10.244.1.4:47134 - 62b9bd56f1c7e4b43ea6b2331c0a24aa - - [2021/05/15 17:12:13] kibana-fra-k8s.ofscdev.oci.oc-test.com:443 GET - "/oauth2/callback?code=AgAgYmNkNTdiNDkxMzUxNDMxNjgxMDVlMzgzOTdhYmNjMTkIABCd8ijZ1MOe0pDa4Tm3-sIfAAAAMM-aSaNrUEhJzLz2OeZ9qJ66xm3NjEu72D1ud6Kt6dhyWiVxV9xD_9cPwSVpkTWAAQ==&state=npnXv0hiPgEjqFjCWfmJeWAtfOXKByb7GioQLq3lk8k%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 403 2767 0.558
10.244.3.134:54148 - xxxxxxxxxxxxxxxxxxxxxxx - anton.guts@oracle.com [2021/05/15 17:12:14] [AuthFailure] Invalid authentication via OAuth2: unauthorized
10.244.3.134:54148 - xxxxxxxxxxxxxxxxxxxxxxx - - [2021/05/15 17:12:13] kibana-fra-k8s.ofscdev.oci.oc-test.com:443 GET - "/oauth2/callback?code=AgAgYmNkNTdiNDkxMzUxNDMxNjgxMDVlMzgzOTdhYmNjMTkIABD182c7Md62O5uQeSAQIg5_AAAAMKFBEbzD07Kf0BoFoISXuob4IQgwFAR7W41qOdaZNhVRsRcSpDUaUedSlKjxaApeWQ==&state=CzJqIxp4_rGJ8802Jl1fpdjooUkF1IG_DVlG420xCjQ%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 403 2759 0.721
```

When i'm using config file.
```
[2021/05/15 17:07:28] [main.go:43] ERROR: failed to load config: error unmarshalling config: 1 error(s) decoding:

* '' has invalid keys: allowed_group
```
However group list have this name:

groups:[{"$ref":"http://admin:9246/admin/v1/Groups/93c2024166a04f73853f47d8373ed4e9","id":"93c2024166a04f73853f47d8373ed4e9","name":"OFSCPROD_SYSOps"} {"$ref":"http://admin:9246/admin/v1/Groups/f9df235c0e6043b68d5401cfae4510d9","id":"f9df235c0e6043b68d5401cfae4510d9","name":"**cheftest**"}]} 

## Possible Solution
Maybe format i need to change something in format of groups, to parse this correctly
## Steps to Reproduce (for bugs)

1.  Configuration file content:
```
http_address = "0.0.0.0:4180"
redirect_url = "https://<myURL>/oauth2/callback"
upstreams = ["file:///dev/null"]
pass_basic_auth = true
pass_user_headers = true
pass_host_header = true
pass_authorization_header = true
email_domains = ["oracle.com"]
provider = "oidc"
provider_display_name = "Oracle IDCS"
oidc_issuer_url="https://idcs-9dc693e80d9b469480d7afe00e743931.identity.oraclecloud.com/"
insecure_oidc_skip_issuer_verification = true
client_id = "<MYID>"
user_id_claim = "email"
oidc_email_claim = "email"
oidc_groups_claim = "groups"
scope = "openid profile email groups"
pass_access_token = false
set_xauthrequest = true
ssl_insecure_skip_verify = true 
cookie_secret = "<SECRET>"
cookie_secure = false 
cookie_httponly = true

```

2.  

   - --show-debug-on-error
   - --allowed-group=cheftest
   - --config=/opt/ofsc/oauth2-proxy/config/oauth-proxy.cfg
   - --client-secret-file=/opt/ofsc/oauth2-proxy/secret/oauth-token.cfg

3.  
Login to https://<myURL>
4.  
Page Shows 403 and write in logs

```
[2021/05/15 17:11:39] [oauthproxy.go:149] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
10.244.3.6:52708 - 527c8f2fe29a63d5fbe7644a5f6da3ad - anton.guts@oracle.com [2021/05/15 17:12:12] [AuthFailure] Invalid authorization via session: removing session Session{email:anton.guts@oracle.com user:ANTON.GUTS@ORACLE.COM PreferredUsername: token:true id_token:true created:2021-05-15 16:59:52.000503898 +0000 UTC expires:2021-05-15 17:59:51.873141582 +0000 UTC groups:[{"$ref":"http://admin:9246/admin/v1/Groups/aa52135cea994c03a2fce26ee4637f12","id":"aa52135cea994c03a2fce26ee4637f12","name":"OFSC-DEV-ASHOCI_SYSOps"} {"$ref":"http://admin:9246/admin/v1/Groups/df6b89b65cbd45728521700b18b19a02","id":"df6b89b65cbd45728521700b18b19a02","name":"PEOCONFL-dev-users"} {"$ref":"http://admin:9246/admin/v1/Groups/c72ee8247df443949f0e27a5dfdfc957","id":"c72ee8247df443949f0e27a5dfdfc957","name":"OFSC-PREPROD-OCI_SYSOps"} {"$ref":"http://admin:9246/admin/v1/Groups/9bcf93eebac9403da745ec2b06a23403","id":"9bcf93eebac9403da745ec2b06a23403","name":"all_employees"} {"$ref":"http://admin:9246/admin/v1/Groups/d4360717f5dc4ac9b5c17a6f60b5f71c","id":"d4360717f5dc4ac9b5c17a6f60b5f71c","name":"PEOOCCNJIRA-jira-users"} {"$ref":"http://admin:9246/admin/v1/Groups/93c2024166a04f73853f47d8373ed4e9","id":"93c2024166a04f73853f47d8373ed4e9","name":"OFSCPROD_SYSOps"} {"$ref":"http://admin:9246/admin/v1/Groups/f9df235c0e6043b68d5401cfae4510d9","id":"f9df235c0e6043b68d5401cfae4510d9","name":"cheftest"}]}
10.244.3.6:52708 - 527c8f2fe29a63d5fbe7644a5f6da3ad - anton.guts@oracle.com [2021/05/15 17:12:12] kibana-fra-k8s.ofscdev.oci.oc-test.com:443 GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 401 13 0.000
10.244.3.134:54148 - 3dd01cfe56594122f859ab9ffe970524 - - [2021/05/15 17:12:12] kibana-fra-k8s.ofscdev.oci.oc-test.com:443 GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 302 393 0.000
10.244.1.4:47134 - 7a81ba44d3598a7382a367bee21f2647 - - [2021/05/15 17:12:13] kibana-fra-k8s.ofscdev.oci.oc-test.com:443 GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 302 393 0.000
10.244.1.4:47134 - 62b9bd56f1c7e4b43ea6b2331c0a24aa - anton.guts@oracle.com [2021/05/15 17:12:14] [AuthFailure] Invalid authentication via OAuth2: CSRF token mismatch, potential attack
10.244.1.4:47134 - 62b9bd56f1c7e4b43ea6b2331c0a24aa - - [2021/05/15 17:12:13] kibana-fra-k8s.ofscdev.oci.oc-test.com:443 GET - "/oauth2/callback?code=AgAgYmNkNTdiNDkxMzUxNDMxNjgxMDVlMzgzOTdhYmNjMTkIABCd8ijZ1MOe0pDa4Tm3-sIfAAAAMM-aSaNrUEhJzLz2OeZ9qJ66xm3NjEu72D1ud6Kt6dhyWiVxV9xD_9cPwSVpkTWAAQ==&state=npnXv0hiPgEjqFjCWfmJeWAtfOXKByb7GioQLq3lk8k%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 403 2767 0.558
10.244.3.134:54148 - c8603c66c33e7ec780350f939c783b49 - anton.guts@oracle.com [2021/05/15 17:12:14] [AuthFailure] Invalid authentication via OAuth2: unauthorized
10.244.3.134:54148 - c8603c66c33e7ec780350f939c783b49 - - [2021/05/15 17:12:13] kibana-fra-k8s.ofscdev.oci.oc-test.com:443 GET - "/oauth2/callback?code=AgAgYmNkNTdiNDkxMzUxNDMxNjgxMDVlMzgzOTdhYmNjMTkIABD182c7Md62O5uQeSAQIg5_AAAAMKFBEbzD07Kf0BoFoISXuob4IQgwFAR7W41qOdaZNhVRsRcSpDUaUedSlKjxaApeWQ==&state=CzJqIxp4_rGJ8802Jl1fpdjooUkF1IG_DVlG420xCjQ%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 403 2759 0.721

```

## Context

Without allowed_group i can login successful, without mentioned errors, but  i need allowed group list to use this tool.

## Your Environment

Im running thin on Oracle linux 7.8, but same result for any OS.  

- Version used:

oauth2-proxy v7.1.3 (built with go1.16)

**Comment by NickMeves** [comment]
So we expect the groups claim in the OIDC IDToken to have this form:

`"groups": ["group0", "group1, "group2"]`

This PR added support for complex data structures in the claim: https://github.com/oauth2-proxy/oauth2-proxy/pull/839

So they would get parsed and passed to the backend in the `X-Forwarded-Groups` header.

But as far as the native `allowed_groups` authorization, you might have challenges. I believe we marshal the whole structure into a JSON string, so you'd need to match that whole complex format in your sample above.

**Comment by sosiskin2000** [comment]
Line in Configuration not working, for the same reasons?
If format will be updated from Oracle side, how i can provide list with group in configuration?
allowed_group = "group1, group2"  ??

or
allowed_group= ["group1, group2"]

in configuration it always says 
* '' has invalid keys: allowed_group

**Comment by JoelSpeed** [comment]
The configuration option is called `allowed_groups`, with an `s` on the end, which you've missed in your example

**Comment by sosiskin2000** [comment]
Do you have information how to configure this used mentioned setting, there is no example and description in documentation.

I have groups like this:

`groups:[{"$ref":"http://admin:9246/admin/v1/Groups/aa52135cea994c03a2fce26ee4637f12","id":"aa52135cea994c03a2fce26ee4637f12","name":"OFSC-DEV-ASHOCI_SYSOps"} {"$ref":"http://admin:9246/admin/v1/Groups/df6b89b65cbd45728521700b18b19a02","id":"df6b89b65cbd45728521700b18b19a02","name":"PEOCONFL-dev-users"} {"$ref":"http://admin:9246/admin/v1/Groups/c72ee8247df443949f0e27a5dfdfc957","id":"c72ee8247df443949f0e27a5dfdfc957","name":"OFSC-PREPROD-OCI_SYSOps"} {"$ref":"http://admin:9246/admin/v1/Groups/9bcf93eebac9403da745ec2b06a23403","id":"9bcf93eebac9403da745ec2b06a23403","name":"all_employees"} {"$ref":"http://admin:9246/admin/v1/Groups/d4360717f5dc4ac9b5c17a6f60b5f71c","id":"d4360717f5dc4ac9b5c17a6f60b5f71c","name":"PEOOCCNJIRA-jira-users"} {"$ref":"http://admin:9246/admin/v1/Groups/93c2024166a04f73853f47d8373ed4e9","id":"93c2024166a04f73853f47d8373ed4e9","name":"OFSCPROD_SYSOps"} {"$ref":"http://admin:9246/admin/v1/Groups/f9df235c0e6043b68d5401cfae4510d9","id":"f9df235c0e6043b68d5401cfae4510d9","name":"cheftest"}]}
`
You mentioned https://github.com/oauth2-proxy/oauth2-proxy/pull/839 but there is no description how it can help me, and how i can parse my complex groups. For example its not a list that you mentioned, each group it separate json as i see.

I have tryed all parts of my groups like id/name/ref -

`allowed_groups = ["cheftest", "93c2024166a04f73853f47d8373ed4e9", "OFSCPROD_SYSOps"]`
so no luck.
My only option to ask Oracle to change group format, or i can parse groups somehow?

**Comment by JoelSpeed** [comment]
Looking at the PR, it looks like you would need to set your `allowed_groups` to contain the full json structure of the group as it comes from your IDP. So in this case something like:

```
allowed_groups=['{"$ref":"http://admin:9246/admin/v1/Groups/f9df235c0e6043b68d5401cfae4510d9","id":"f9df235c0e6043b68d5401cfae4510d9","name":"cheftest"}']
```

@Bibob7 Do you have any extra context you could add here as to how this feature is meant to be used?

**Comment by sosiskin2000** [comment]
@JoelSpeed Thanks you are the best, its working.
Final question from my side.  My Oauth2 working well, but i need possibility to have couple of API users with internal auth via basic authorization. Is that possible?

**Comment by JoelSpeed** [comment]
Yes, we have some options for this, look for htpasswd in the docs and you should find this. You can also assign groups to users that are basic auth'd through a separate option should you wish to do so as well

**Comment by sosiskin2000** [comment]
Working, thank you
