### ISSUE TITLE
AzureAD: jwt not passed upstream after refresh

### ISSUE THREAD

**Issue by Christoph-Raab** [oauth2-proxy/oauth2-proxy#1201]
When using the new refresh mechanism for azure I observe the following behavior:
- After initial login by user his jwt is passed upstream to the application pod
- After the refresh the jwt is not passed upstream anymore

I have a keep alive mechanism that calls the app every 60 seconds. I have logged the requests on the app side and compared them to the logs of oauth2-proxy. I see the log message ``[azure.go:256] refreshed id token Session``. From that moment on the jwt does not appear in the application logs anymore.

## Expected Behavior

JWT should be passed upstream after token refresh.

## Current Behavior

JWT is not passed upstream after token refresh.

## Steps to Reproduce (for bugs)

Configure with azure:
```yaml
        args:
          - --provider=azure
          - --provider-display-name="Azure AD"
          - --client-id=
          - --client-secret=
          - --azure-tenant=
          - --email-domain=
          - --set-authorization-header=true
          - --pass-access-token=true
          - --skip-provider-button=true
          - --skip-auth-preflight=true
          - --skip-auth-strip-headers=true
          - --skip-auth-route=/api/headers
          - --session-store-type=redis
          - --redis-connection-url=
          - --http-address=0.0.0.0:4180
          - --upstream=static://
          - --reverse-proxy=true
          - --cookie-secret=
          - --cookie-refresh=60m
```

## Your Environment
I use oauth2-proxy combined with kubernetes 1.20.x and istio 1.9.x

- Version used:
v7.1.3

**Comment by JoelSpeed** [comment]
Looking at the code, we don't check whether the tokens returned are non-empty before storing them. I was under the impression that Azure should return a token always but that said, I think this will depend on exactly which type of azure you are using.

We certainly used to only update if they'd actually been refreshed, but that may be other providers that have similar implementations. I know @NickMeves was looking at some parts of the codebase around this area so he may have some additional context on changes there recently

**Comment by Christoph-Raab** [comment]
So I have revisited docs and the changelog.

I had the ``- --cookie-refresh=55min`` configured, because a token is only 1h min active. The changelog states:

> Please note that --cookie-refresh must be 0 (the default) or equal to the token lifespan configured in Azure AD to make Azure token refresh reliable. Setting this value to 0 means that it relies on the provider implementation to decide if a refresh is required.

So I have removed the ``--cookie-refresh``, but now the token is not refreshed at all. Even after 1 h 15 min, I still receive the expired token. Changed it to ``- --cookie-refresh=0`` just to be sure, still same effect.

Furthermore I simulated the flow with postman and observed, that the id_token is not refreshed. The response to the token refresh request does not have a id_token. Maybe that has something to do with it?

Note:
I updated the args above to reflect my current setup.

**Comment by Christoph-Raab** [comment]
So after a day of debugging the oauth2-proxy on my local machine I can say that:

1) With ``--cookie-refresh=0`` the refresh wont be triggered at all. Changelog is definitive false here

2) With ``--cookie-refresh=60m`` (my token lifetime) the refresh works as expected Bug.
But after the refresh, the ``Authorization`` header is not passed to upstream anymore. I havn't figured out, by whom the header is added to the response, but this is definitively a bug.

Any help/hint is appreciated.

**Comment by Christoph-Raab** [comment]
After some thinking I figured the empty idToken might be the problem. And indeed!

Changing the lines in the [azure.go](https://github.com/oauth2-proxy/oauth2-proxy/blob/06808704a3762de73bed1cc92b077420eb93d735/providers/azure.go#L286) from

```
	now := time.Now()
	expires := time.Unix(jsonResponse.ExpiresOn, 0)
	s.AccessToken = jsonResponse.AccessToken
	s.IDToken = jsonResponse.IDToken
	s.RefreshToken = jsonResponse.RefreshToken
	s.CreatedAt = &now
	s.ExpiresOn = &expires
```

to 

```
	now := time.Now()
	expires := time.Unix(jsonResponse.ExpiresOn, 0)
	s.AccessToken = jsonResponse.AccessToken
	if jsonResponse.IDToken == "" {
		logger.Printf("unable to refresh id_token, setting access_token as id_token instead")
		s.IDToken = jsonResponse.AccessToken
	} else {
		s.IDToken = jsonResponse.IDToken
	}
	s.RefreshToken = jsonResponse.RefreshToken
	s.CreatedAt = &now
	s.ExpiresOn = &expires
```

seams to be solving the problem. The session is refreshed and the token is passed upstream afterwards. 

I have build my locally modified version and will deploy and test it tomorrow in our QA stage. 

If this works I can create a pull request. Otherwise someone has to tackle the issue, because at the moment, the azure provider is broken, because of the missing refresh mechanism.

**Comment by Christoph-Raab** [comment]
Ok, that's not working. Some help would be appreciated, because, as I said, Azure Provider is broken, if upstream depends on the Authorization header.

**Comment by JoelSpeed** [comment]
So I can confirm that the changelog entry there is incorrect, if the refresh period is set to 0, we don't ever refresh.

What I can't really help with though is the Azure specific parts of this, I'm not an azure user and neither are any of the other maintainers. I don't really understand why they don't return a new ID Token when you refresh. Perhaps there's some extra option needed in the scope that allows a new ID Token to be returned, I think this will need some research.

What was the behaviour like when you had the 55m option? Still no luck?

**Comment by Christoph-Raab** [comment]
I think the problem is that you're using the old api.

The [current docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) point to the ``v2.0``.

So it's ``login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize`` instead of ``login.microsoftonline.com/{tenant}/oauth2/authorize`` and so on.

This page specifies the [refresh process](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#refresh-the-access-token). It states:

> id_token | An unsigned JSON Web Token (JWT). The app can decode the segments of this token to request information about the user who signed in. The app can cache the values and display them, but it should not rely on them for any authorization or security boundaries. For more information about id_tokens, see the id_token reference. **Note: Only provided if openid scope was requested.**

Your azure provider doesn't have a scope set, when requesting the refresh_token (line 260). Propably because that wasn't necessary with v1?

What bugs me is, that I set ``--pass-access-token=true`` so the Authorization Header is added upstream. That works till the refresh. But the id_token should bother here, because I pass the **access_token**, which contains all information that I need (email, name, groups, ...)

**Comment by JoelSpeed** [comment]
Have you tried setting the `--scope` flag? AFAIK our Azure implementation and our OIDC implementation can be used with Azure if you set them up correctly, there's just a few more flags/options you need to set up

**Comment by Christoph-Raab** [comment]
I switched projects so I will not be able to work on this anymore. My old team is still using it and I recommended using the OIDC issuer.

Azure Provider still needs rework. 

Regarding this ticket: You can close it or leave it open, I'll leave that up to you.
