### ISSUE TITLE
Use ingress routing for upstreams

### ISSUE THREAD

**Issue by danielhstahl** [oauth2-proxy/oauth2-proxy#1202]
I'm using an nginx ingress with oauth2-proxy.  I'm approaching this in two ways:
* A single oauth2-proxy deployment with 2 ingresses.  One ingress routes to my various services, while the other ingress routes only to the oauth2-proxy deployment for authentication.
* oauth2-proxy as a sidecar per service.  Only one ingress, but each oauth2-proxy has a different redirect url.  Significantly more boilerplate, however scaling happens automatically and I don't have to redo routing within oauth2-proxy: my "upstream" is simply localhost.  

Obviously the first approach is simpler overall, but currently I have to add upstreams to the oauth2-proxy deployment to point to each service.  This is duplicative since I've already listed these routes in my ingress.  

Would it make sense, or is it even possible, for oauth2-proxy to automatically extract the upstreams from the ingress?

**Comment by JoelSpeed** [comment]
If you are using nginx ingress, you can set the `auth-signin` and `auth-url` annotations to point to OAuth2 Proxy, and then it will just use the proxy for authentication checks, it doesn't actually proxy the requests via the OAuth2 Proxy instance.

We have this documented to some degree in our docs https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#configuring-for-use-with-the-nginx-auth_request-directive

You will need to make sure that your OAuth2 Proxy and other services all share the same base domain and that your cookie domain and whitelist domain options are also set correctly

**Comment by danielhstahl** [comment]
This worked! thanks!
