### ISSUE TITLE
Fragment is lost after redirects

### ISSUE THREAD

**Issue by tarvip** [oauth2-proxy/oauth2-proxy#1205]
After upgrading oauth2-proxy from version 7.0.1 to 7.1.3 URI fragments are lost after redirects.

## Expected Behavior

oauth2-proxy will keep the fragment after redirects.

## Current Behavior

Fragment is lost after successful authentication.

## Possible Solution

I played `sign_in.html` template, it seems to be affected by `<script>` location, in `v7.0.1` it was in `head`, when I moved script from `head` to `body`, then it started working again. So, my fix was following:

```
diff --git a/pkg/app/pagewriter/sign_in.html b/pkg/app/pagewriter/sign_in.html
index 652b674..fc7ab3f 100644
--- a/pkg/app/pagewriter/sign_in.html
+++ b/pkg/app/pagewriter/sign_in.html
@@ -22,23 +22,6 @@
         text-decoration: underline;
       }
     </style>
-
-    <script>
-      if (window.location.hash) {
-        (function() {
-          var inputs = document.getElementsByName('rd');
-          for (var i = 0; i < inputs.length; i++) {
-            // Add hash, but make sure it is only added once
-            var idx = inputs[i].value.indexOf('#');
-            if (idx >= 0) {
-              // Remove existing hash from URL
-              inputs[i].value = inputs[i].value.substr(0, idx);
-            }
-            inputs[i].value += window.location.hash;
-          }
-        })();
-      }
-    </script>
   </head>
   <body class="has-background-light">
   <section class="section">
@@ -82,6 +65,23 @@
     </div>
   </section>

+  <script>
+    if (window.location.hash) {
+      (function() {
+        var inputs = document.getElementsByName('rd');
+        for (var i = 0; i < inputs.length; i++) {
+          // Add hash, but make sure it is only added once
+          var idx = inputs[i].value.indexOf('#');
+          if (idx >= 0) {
+            // Remove existing hash from URL
+            inputs[i].value = inputs[i].value.substr(0, idx);
+          }
+          inputs[i].value += window.location.hash;
+        }
+      })();
+    }
+  </script>
+
   <footer class="footer has-text-grey has-background-light is-size-7">
     <div class="content has-text-centered">
        {{ if eq .Footer "-" }}
```

I am not a web developer, not sure it is correct fix.

## Steps to Reproduce (for bugs)

Setup latest oauth2-proxy, access a page that is protected by oauth-proxy and have fragment also in URL. After successful login when you are redirected to page fragment is gone.

In our case we are using Traefik with `forwardAuth` middleware and using approach described [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#forwardauth-with-static-upstreams-configuration)

## Context

It affected with Kibana urls, in kibana the query is in fragment, so whenever you had to login this query was gone.

## Your Environment

I was using versions 7.0.1 and 7.1.3

**Comment by JoelSpeed** [comment]
Seems like a regression, would you be able to create a PR with the fix you've mentioned here?
