### ISSUE TITLE
Jwt token passed to upstream does not contain aud in claims

### ISSUE THREAD

**Issue by rishi1111** [oauth2-proxy/oauth2-proxy#1206]
Cannot use the access token passed to upstream application, to authenticate as it does not contain aud in claims.
## Expected Behavior

aud should be present in claims
## Current Behavior

aud is missing from jwt token, and i get this error

Error retrieving session from token in Authorization header: [unable to verify bearer token, oidc: expected audience "custom-gatekeeper" got []]

## Steps to Reproduce (for bugs)
1. Add this to your config 
pass_access_token="true"
skip_jwt_bearer_tokens="true"

2. From the upstream application , print out the request headers. Copy the access token
3. Fire an API call, with the header "Authorization":"Bearer $access_token"
4. Error occurs

## Context

In some cases backend application needs this access token to access apis protected by oauth2proxy.

## Your Environment

- Version used:
Latest

**Comment by speedythesnailnpg** [comment]
I have this exact same issue when trying to verify token via k8s api server issued by oauth2-proxy.
