### ISSUE TITLE
Refresh-session not working for multiple session cookies

### ISSUE THREAD

**Issue by prince-melvin** [oauth2-proxy/oauth2-proxy#1209]
Multiple session-cookies not getting refreshed properly since the headers are getting flattened before adding it to response

## Expected Behavior

Session Cookies if span to more than one, it should get refreshed/set-newly
Allow multiple Set-Cookie headers in the response
```
Set-Cookie: cookie1=value
Set-Cookie: cookie2=value
```
## Current Behavior
If my session-state spans to two cookies and while refreshing session the Set-Cookie headers are getting flattened and becomes invalid like this
```
Set-Cookie: cookie1=value,cookie2=value
```
At pkg/middleware/headers.go
```
func flattenHeaders(headers http.Header) {
	for name, values := range headers {
		if len(values) > 1 {
			headers.Set(name, strings.Join(values, ","))
		}
	}
}
```
## Possible Solution
I am not sure about the use-case for flattening.
Shall we copy "Set-Cookie" headers without flattening or a configuration to allow such headers which can be repeated? 

## Context

Was trying to add introspection support for which I have raised a PR already https://github.com/oauth2-proxy/oauth2-proxy/pull/1189 and because of this my session-state becomes bigger
After that the refresh functionality was not working since the cookie is not set properly.

**Comment by JoelSpeed** [comment]
I'm not sure why flattening the set-cookie header in particular causes issues, as far as I'm aware, according to the HTTP spec, separate and comma separated headers should be syntactically identical

**Comment by prince-melvin** [comment]
Attached the screenshot (sorry for the bad quality), of set-cookie header with two cookies where you can see a warning symbol at the end which when hover says "this set cookie has invalid syntax" (Google chrome)

![invalid-set-cookie](https://user-images.githubusercontent.com/81223599/119263579-3b3e7100-bbfd-11eb-8769-17be43cfd5b4.jpg)

And also I tried to browse some docs,  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by JoelSpeed** [comment]
Right ok, I think we need to have an exlcusion on the flattening just for the set-cookie headers then. CC @NickMeves, just fyi, looks like this breaks split cookies.

In the mean time @prince-melvin, could I recommend using a server side session store, at the moment we have redis as the only available implementation but we are planning to add more as and when users desire them

**Comment by prince-melvin** [comment]
Yeah, I can proceed with redis for now :+1:

**Comment by rishi1111** [comment]
```
func flattenHeaders(headers http.Header) {
	for name, values := range headers {
		if len(values) > 1 {
                        // Do not perform logic for set-cookie header
                        if name == "Set-Cookie" {
                               
			}else if name=="Cookie"{
                              headers.Set(name, strings.Join(values, ";"))

                       }else{
                             headers.Set(name, strings.Join(values, ","))

			
		}
	}
}
```

Can I open a PR for the above fix?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie
The Separator for multiple Cookies in a header is ;

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
Multiple Set-Cookie Headers should be set instead of flattening.

**Comment by JoelSpeed** [comment]
We would never set the `Cookie` header as this is set by browsers as a response to the `Set-Cookie` header. But otherwise yes, we need a PR for this still as far as I know, so if you could look into adding a PR and making sure to include appropriate tests, that would be greatly appreciated

**Comment by rishi1111** [comment]
@JoelSpeed, This may be a bit off-topic for the thread,

In my case, the applications protected by oauth2proxy need the access_token in a particular Cookie named "kc-access"
With the above code-snippet and the below alpha-config, I have achieved the functionality.

Is there an alternate approach to achieve the functionality?

![image](https://user-images.githubusercontent.com/17124299/120895862-86fd0b80-c63c-11eb-8064-3314ad168bfd.png)
