### ISSUE TITLE
No "Set-Cookie" response for XHR / AJAX requests that trigger token refresh

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/oauth2-proxy#1211]
## Expected Behavior

When an incoming XHR request contains a session cookie whose lifetime exceeds `--cookie-refresh`, the outgoing HTTP response should contain a `Set-Cookie` header that refreshes the `_oauth2_proxy` cookie in the browser.

## Current Behavior

Everything works well for "normal" GET requests that return full HTML pages. But there are single page apps that make such a full page request only once and then do everything with AJAX i.e. small XHR requests.

The experienced behaviour is that using a Redis Session Storage and `--cookie-refresh=4m` and `--cookie-expire=5m`,  polling for new notifications as well as user interfactions like pressing a button works within the first 5 minutes but then stops working as the XHR requests start getting 401 answers.

Apparently none of the XHR requests, especially those between 4-5 minutes contain a Set-Cookie although they might or might not have refreshed the actual OAauth2 acces token. Therefore after 5 minutes the browser discards the now expired  `_oauth2_proxy` cookie and stops sending it which, of course, explains the 401 responses. 

## Possible Solution

Respond with Set-Cookie if an XHR request triggers a cookie refresh.

(Gatekeeper, btw, works like this)

## Steps to Reproduce (for bugs)

Configure Oauth2-Proxy with Redis Store and cookie-refresh=4m, cookie-expire=5m and repeat sending XHR requests every 10s.

## Your Environment

Version "master as of 2021-04-03". Running on Kubernetes.

**Comment by lathspell** [comment]
Please ignore, our patch from https://github.com/oauth2-proxy/oauth2-proxy/issues/856 caused this if used with the wrong --cookie-expire and --cookie-refresh values.

**Comment by lollo25** [comment]
@lathspell what are the correct values to use? I still don’t see set-cookie header when session is refreshed, therefore Ajax calls work only until the cookie expires.

**Comment by lathspell** [comment]
We use this:

  ## Cookies und Session
  cookie-expire: "4h"
  cookie-refresh: "270s"
  cookie-secure: "true"
  cookie-httponly: "true"
  cookie-samesite: "strict"

  ## Refresh access token before expiration with given duration offset; disabled by default
  refresh-token-offset: "30s"
