### ISSUE TITLE
expires_in value provided by oidc provider is not respected . 

### ISSUE THREAD

**Issue by parth30** [oauth2-proxy/oauth2-proxy#1212]
## Expected Behavior

The expires_in value should be respected from the oidc provider and after the expiry the token should not be considered valid .

## Current Behavior

The oauth2-proxy does not take in account the expires_in value provided by the oidc provider (in this case IBM APP ID) . 

## Steps to Reproduce (for bugs)
 1. set the token expiry in provider for 5 mins 
 2. login with valid credentials , after 5 mins you will see the user is still able to perform valid operations . 

## Your Environment

- Version used: oauth2-proxy 7.1.3

**Comment by JoelSpeed** [comment]
Have you set up token refreshing? You can also set up the `cookie-expire` to match the duration of the token. In some cases, users do not care about how long their access tokens live for, and therefore having their session tied to this time doesn't matter. To support multiple use cases we provider options for tweaking this.
