### ISSUE TITLE
Can't use allowed_groups query string with nginx to manage multiple authorizations 

### ISSUE THREAD

**Issue by oxenit** [oauth2-proxy/oauth2-proxy#1215]
## Expected Behavior

When using the allowed_groups query string on the auth endpoint I should be able to leverage authorizations mechanisms using the groups and redirect to specific upstreams using nginx. 

## Current Behavior

Cannot find the right config in nginx to pass the query strings to the auth endpoint, I always get 500 error. It seems to be doable using nginx ingress annotation for a K8S environment on all your docs but cannot find the way in a "traditional" nginx. 

## Possible Solution

Either nginx auth_request module does not support query strings (see https://trac.nginx.org/nginx/ticket/761) or I'm doing it the wrong way. 

## Steps to Reproduce (for bugs)

oauth2-proxy conf
```
email_domain="*"
cookie_secret="secret" 
provider=keycloak 
client_id=aa 
client_secret=bb
login_url="https://xx/auth/realms/yy/protocol/openid-connect/auth" 
redeem_url="https://xx/auth/realms/yy/protocol/openid-connect/token" 
profile_url="https://xx/auth/realms/yy/protocol/openid-connect/userinfo" 
validate_url="https://xx/auth/realms/yy/protocol/openid-connect/userinfo" 
scope="profile email" 
set_xauthrequest=true 
pass_access-token=true 
```

nginx conf
```
server {
  (...)

  location /oauth2/ {
    proxy_pass       http://127.0.0.1:4180;
    proxy_set_header Host                    $host;
    proxy_set_header X-Real-IP               $remote_addr;
    proxy_set_header X-Scheme                $scheme;
    proxy_set_header X-Auth-Request-Redirect $request_uri;
    # or, if you are handling multiple domains:
    # proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
  }

  location = /oauth2/auth {
    proxy_pass       http://127.0.0.1:4180;
    proxy_set_header Host             $host;
    proxy_set_header X-Real-IP        $remote_addr;
    proxy_set_header X-Scheme         $scheme;
    # nginx auth_request includes headers but not body
    proxy_set_header Content-Length   "";
    proxy_pass_request_body           off;
  }

  location / {
    auth_request /oauth2/auth?allowed_groups=example;
    error_page 401 = /oauth2/sign_in;

    # pass information via X-User and X-Email headers to backend,
    # requires running with --set-xauthrequest flag
    auth_request_set $user   $upstream_http_x_auth_request_user;
    auth_request_set $email  $upstream_http_x_auth_request_email;
    proxy_set_header X-User  $user;
    proxy_set_header X-Email $email;
    proxy_pass https://localhost:4443/;
  }
}
```

## Context

I wanna leverage groups mechanisms of keycloak to manage a unique oauth2-proxy with nginx with multiple upstreams and users having different roles (based on group) to access or not these upstreams. 

## Your Environment

Oauth2-proxy last version and Keycloak as IDP using keycloak provider.
Everything works, even allowed_groups in oauth2-proxy config but not at auth endpoint level.

**Comment by NickMeves** [comment]
`keycloak` is an old provider (just OAuth2 `api` scope). It doesn't support any group/role based authorization that was introduced to the project in v7. We are looking to deprecate & replace it here: https://github.com/oauth2-proxy/oauth2-proxy/pull/1210

In the meantime you can use the generic `oidc` provider with your Keycloak installation. `oidc` supports `allowed_groups`.
