### ISSUE TITLE
OAuth 2.0 Access Token Size for Google Cloud Platform Customers

### ISSUE THREAD

**Issue by idntfy** [oauth2-proxy/oauth2-proxy#1218]
We've received the following email from Google, TLDR: they increase oauth2 token size length and some other changes.

I would like to get an official answer that oauth2-proxy won't be affected by this change.

Making it a separate issue would also help other oauth2-proxy users to save their time and not research the code to understand whether they are affected. Thank you very much.

Full email body:

>_Google Cloud Platform will roll out security and reliability improvements that will increase the sizes of OAuth 2.0 tokens. Please follow the instructions below to use the documented token size limits of 2048 bytes and to remove any logic in your services/code that restricts its ability to process access tokens of certain sizes before August 23, 2021._
>
>Hello Google Cloud Customer,
>
>We’re writing to let you know that on **August 23, 2021**, we will roll out security and reliability improvements that will increase the sizes of OAuth 2.0 access tokens that your services may be using to call Google Cloud Platform APIs.
>
>The access token size increase will **only impact services that don’t conform to the access token size limits of 2048 bytes established on Google’s Developer guide and RFC 6749**. If your service falls into this category, please continue reading and take action as outlined below.
>
>**What do I need to know?**
>
>**The enhancement described above will increase the access token size issued to your services that authorize to Google Cloud APIs. Please consider that:**
>* The overall access token size will continue to remain within the 2048 bytes limit documented in Google’s Developer guide and public documentation.
>* Google’s OAuth 2.0 access tokens will also continue to conform to the standards defined in The OAuth 2.0 Authorization framework RFC 6749.
>
>**Verification Phase**
>
>To be able to identify services that may be impacted, we are launching a verification phase. In this phase we will serve projects with access tokens that have been artificially inflated with extra padding and monitor the size of the token that we receive back from these projects.
>
>The purpose of this phase is to identify the projects that will be affected once the enhancement described above takes place. Even if your services end up trimming this extra padding in the token to limit its size, the token will remain valid and calls to Google Cloud APIs should succeed while allowing us to pinpoint these services that do trim tokens. **We will notify the project owner(s) accordingly to make the recommended changes to these services before August 23, 2021, rollout and avoid potential outage of these services.**
>
>**On August 23, 2021**, we will roll out security and reliability improvements that will increase the sizes of OAuth 2.0 access tokens for all projects.
>
>* Unlike the specially padded tokens that were sent during the verification phase, these tokens will not have a padding and the token itself will be larger compared to current tokens.
>* We will also remove all projects from the exception-list and begin issuing the larger access tokens to all Google Cloud Platform (GCP) projects.
>**After this time, if your services continue to trim the access tokens size, then their calls to Google Cloud APIs will fail.**
>
>**What do I need to do?**
>
>**We strongly recommend that you use the documented token size limits of 2048 bytes and to remove any logic in your services/code that restricts its ability to process access tokens of certain sizes.**
>
>Please consider that:
>* If you haven’t built your Google Cloud APIs services’ frameworks based on access token size limits, no action is required from your part.
>* If your services expect access tokens to meet certain size limits then these services may be impacted and their calls to Google Cloud APIs may fail.
>* If we detect that the token sizes are being trimmed by services in this project, we will notify you by July 30, 2021, and automatically enroll the impacted projects into an exception-list. Projects in this exception-list will revert to receiving the currently available smaller access tokens until August 23, 2021. This verification phase will give you enough time to make the recommended changes to your service/code. Please use this form to enroll specific projects by June 7, 2021.
>
>For us to do the verification, we require you to follow these steps below in the specified timeline:
>* From now and until June 7, 2021: You can opt-in to enroll specific projects to receive the specially padded longer access tokens that could be up to 2048 bytes in size. We will monitor the access token size we send and receive back from these projects.
>* On June 21, 2021: We will automatically enroll all GCP projects to receive the specially padded larger tokens. You can opt-out your projects from this phase by filling this form by June 7, 2021.
If we don’t hear from you by June 7, 2021, we will send these projects the padded access tokens and monitor the token size we receive back from them.
>
>If you have any questions or require assistance, please reply to this email to contact Google Cloud Support.
>
>Thanks for choosing Google Cloud.

**Comment by JoelSpeed** [comment]
We don't have anything that depends on the size of the Google access token, so I believe we are unaffected by this change
