### ISSUE TITLE
Why is the "rd" option required for the sign_out option?

### ISSUE THREAD

**Issue by iTaybb** [oauth2-proxy/oauth2-proxy#1219]
Currently, the `/oauth2/sign_out` endpoint only clears oauth2 cookies. The OIDC cookies still exist, and will auto-login after the application is accessed.
In order to delete the oidc cookies, one must provide the oidc sign_out url via the `rd` option, and allow the oidc domain in the ` --whitelist-domain` option.

Isn't it redundant, since the oidc sign_out url's already provided in the oidc params? Also, it might as well be automatically inserted to the whitelist domain list.

I'll be happy to help with the implementation.

**Comment by rishi1111** [comment]
I currently face the same issue, but going through the previous open/closed issues in this repo, the reasoning seems to be that oauth2proxy supports many more providers like GitHub, google etc.. so a solution should cater to all the providers.

I have forked the repo and made my changes in the signout method.

**Comment by JoelSpeed** [comment]
As @rishi1111 says, we don't just support OIDC providers, and not all OIDC providers support single sign out. So in the past we have opted not to implement single sign out functionality.

That said, if we could come up with some way to support most providers, I think we could look at getting that added in!
