### ISSUE TITLE
Google Auth returns weirdly formatted token, oauth2-proxy can't recognize cookie

### ISSUE THREAD

**Issue by IDlOT** [oauth2-proxy/oauth2-proxy#1220]
## Current Behavior

I'm using Google as a provider and trying to receive an id_token to extract my email address. I provide the email, profile, and openid scopes and am successfully able to auth in, but the token I'm receiving is not formatted like a JWT at all. It's more than double the length and contains no periods. I used to receive correctly formatted JWT's before adding the new scopes, but even after removing them, the new token format persists. Regardless, this weird token is being set in my browser as an "_oauth2_proxy" cookie. 

If it helps, while I can't decode it on jwt.io, if I add a random string and a "." before this token, I can see the beginnings of a json blob with AccessToken, IDToken, etc, and some unreadable characters at the end. If this is the JSON array described [here](https://developers.google.com/identity/protocols/oauth2/openid-connect), how do I decode it to properly access the id_token?

Another possibly related symptom is this: my oauth2-proxy container is logging this combination of messages every second, even though my browser has the (albeit undecodable ) cookie set:

[2021/05/31 23:30:38] [oauthproxy.go:912] Error loading cookied session: cookie "_oauth2_proxy" not present
127.0.0.1:34370 - - [2021/05/31 23:30:38] <my-url> GET - "/oauth2/auth" HTTP/1.0 "node-XMLHttpRequest" 401 21 0.000
127.0.0.1:34372 - - [2021/05/31 23:30:38] <my-url> GET - "/oauth2/sign_in" HTTP/1.0 "node-XMLHttpRequest" 200 2681 0.000
[2021/05/31 23:30:43] [oauthproxy.go:912] Error loading cookied session: cookie "_oauth2_proxy" not present
127.0.0.1:34398 - - [2021/05/31 23:30:43] <my-url> GET - "/oauth2/auth" HTTP/1.0 "node-XMLHttpRequest" 401 21 0.000
127.0.0.1:34400 - - [2021/05/31 23:30:43] <my-url> GET - "/oauth2/sign_in" HTTP/1.0 "node-XMLHttpRequest" 200 2681 0.000
[2021/05/31 23:30:48] [oauthproxy.go:912] Error loading cookied session: cookie "_oauth2_proxy" not present
127.0.0.1:34418 - - [2021/05/31 23:30:48] <my-url> GET - "/oauth2/auth" HTTP/1.0 "node-XMLHttpRequest" 401 21 0.000
127.0.0.1:34420 - - [2021/05/31 23:30:48] <my-url> GET - "/oauth2/sign_in" HTTP/1.0 "node-XMLHttpRequest" 200 2681 0.000

Is this because of the formatting issue I mentioned above? Why is that port changing every time?

## Expected Behavior

Should receive correctly formatted JWT token after auth, that gets set in my browsers' cookies, and can be recognized by the oauth2-proxy container. 

## Your Environment

Kubernetes pod including one oauth2-proxy container and one nginx container following a similar setup to what is described [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#configuring-for-use-with-the-nginx-auth_request-directive).

**Comment by JoelSpeed** [comment]
The cookie format is considered to be internal to OAuth2 Proxy. It is not a JWT.

If you want to access the JWT token that Google provides, you should try using `set-authorization-header`. This option will add an `Authorization` header to responses, this is fetched from the session stored in the cookie.

Nginx can then use the Auth request mode to copy this header to a new header to provide to your application. I think it's called `auth_request_set`, you can see an example in our configuration docs.
