### ISSUE TITLE
infinite loop "[stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session"

### ISSUE THREAD

**Issue by davidy718** [oauth2-proxy/oauth2-proxy#1225]
trying to use oauth2 with okta 
## Expected Behavior

getting a infinite loop when trying to access the url  

## Context

provider = "oidc"
redirect_url = "https://redirect-url.com/authorization-code/callback"
oidc_issuer_url = "https://domain.okta.com"
upstreams = [
    "https://my-app:8080"
]
email_domains = [
    "*"
    ]
client_id = "client-id"
client_secret = "client-secret"
cookie_secret = "1234567891011121"
http_address = "0.0.0.0:4180"
skip_provider_button = true
## Your Environment

running oauth2 docker image V7.1.3 
- Version used:
thanks

**Comment by JoelSpeed** [comment]
Hi, could you please add some more detail about your set up. 

Are you hosting OAuth2 Proxy on a different domain to your application? 

Typically redirect loops like this are due to misconfiguration of the cookie settings. I would suggest using your browser's developer tools to inspect the calls and see if you can find the set-cookie response once Okta redirects back to OAuth2 Proxy

Another test you can try is to access `/oauth2/auth` (or your proxy prefix) to see if you are logged in there or not. If you are logged in it will show a blank page, you can then inspect the cookie again using developer tools in your browser

**Comment by davidy718** [comment]
its two separate domains
I see a cookie named `_oauth2_proxy_csrf` but ones I login it keeps disappearing when ever there is a request to `oidc-issuer-url`

**Comment by vetinari** [comment]
Similar issue here with dex as oauth2 provider:
```
http_address = "127.0.0.1:4180"
proxy_prefix = "/docs"
upstreams = [
     "http://127.0.0.1:8001/"
]
pass_basic_auth = true
pass_user_headers = true
pass_host_header = true
email_domains = [
     "mydomain.here"
]
provider = "oidc"
oidc_issuer_url="https://auth.mydomain.here/"
client_id = "oauth2-proxy"
client_secret = "client_secret"
cookie_secret = "cookie_secret"
cookie_domains = "server.mydomain.here"
cookie_secure = false
```
nginx as proxy is just:
```
       location /docs/ {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://127.0.0.1:4180/;
        }
```

Any response from the oauth2-proxy never sets a Cookie, i.e. response is

```
HTTP/1.0 403 Forbidden
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Expires: Thu, 01 Jan 1970 01:00:00 CET
X-Accel-Expires: 0
Date: Sun, 06 Jun 2021 11:51:32 GMT
Content-Type: text/html; charset=utf-8


<!DOCTYPE html>
... rest of response skipped...
```

**Comment by JoelSpeed** [comment]
> I think my issue was I wasn't using a Authorization Server in okta

@davidy718 Did you manage to get this working then?

@vetinari I think your issue is probably separate as you are using a single domain, when Dex redirects to the callback, do you see errors in the logs or can you inspect the response from that exact call?

**Comment by davidy718** [comment]
@JoelSpeed yes it works for me now 
Thanks for the help 👍

**Comment by vetinari** [comment]
```
[2021/06/09 16:16:39] [oauthproxy.go:155] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains:server.mydomain.here path:/ samesite: refresh:disabled
[2021/06/09 16:16:48] [stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
```
This is everything in the logs for a request - if I force a `_oauth2_proxy` to be present the message changes to `[stored_session.go:76] Error loading cookied session: cookie signature not valid, removing session` but nothing else changes.

The HTTP response in my [previous comment](https://github.com/oauth2-proxy/oauth2-proxy/issues/1225#issuecomment-855387438) was obtained by running tcpdump on the connection between nginx and the oauth2-proxy to check if nginx swallows something...
