### ISSUE TITLE
Proxy as a library (feature request)

### ISSUE THREAD

**Issue by srs** [oauth2-proxy/oauth2-proxy#1228]
I would like to customize OAuth2 proxy with adding more behaviour. Using this project as a library would be perfect. 

## Expected Behavior

Import `github.com/oauth2-proxy/oauth2-proxy/pkg/proxy` in my code and use this to construct the server.

## Current Behavior

No way to import the "proxy" to use as a library. Since most of the code is in the "main" package then the only way to do this now is to copy code.

## Possible Solution

Move the following files to an exported package (for example `pkg/proxy`):

* oauthproxy.go
* oauthproxy_test.go
* validator.go
* validator_test.go
* watcher.go
* watcher_unsupported.go

I also see that `VERSION` is used in `oauthproxy.go`. This would be an issue, but could be a configuration variable or move the `version.go` into the `proxy` package.

The remaining main package would use the exported package. This allows users to be able to create a new OAuthProxy by using the exported package (`proxy.NewOAuthProxy(...)`).

In my case I woud then use this in my own http server instance to add a couple of more routes.

**Comment by JoelSpeed** [comment]
We are actually refactoring the code out of the main package as a bit of a priority for myself and the other maintainers. In the process of doing this we are adding interfaces and segregating the code into smaller more manageable pieces. Eventually the aim is to migrate the main package as well into its own package as you've suggested here.

That said we weren't planning to allow this to be a generally consumed library. Perhaps you could talk a bit more about the use case you are trying to integrate with so we can understand the needs of your request a bit better?

**Comment by J3m5** [comment]
I see a use case for a library.
It could be used to make a plugin for another server like caddy for example.
A bit like caddy-auth-portal
https://github.com/greenpau/caddy-auth-portal
So it could be directly integrated in a file or reverse proxy server.

**Comment by tomberek** [comment]
Usage as a Go library allows for simpler deployment of self-contained applications and minimizes the amount of configuration to orchestrate or to get wrong.
