### ISSUE TITLE
Using basic authentication doesn't show the login failed message

### ISSUE THREAD

**Issue by morarucostel** [oauth2-proxy/oauth2-proxy#1232]
Running the oauth2-proxy with the "--display-htpasswd-form" and "--htpasswd-file" set to true, using a set of incorrect credentials doesn't show anything to the end user.
The end-user needs to know that his/her attempt failed (due to incorrect username/password) otherwise they don't even know that the attempt was done. For them the experience is that the two input fields were cleared with no message whatsoever.

## Expected Behavior

During the failed attempt, the end-user should see a message that the login attempt failed due to incorrect username/password credentials.

## Current Behavior

No message shown to the user during the failed login attempt. The user experience is strange, since the only information they get is a removal of their input. 

## Steps to Reproduce (for bugs)

1.  Create a file holding the basic auth credentials
```
htpasswd -cbs testpasswd admin@example.com password
```
2.  Update the oauth2-proxy.cfg file, adding
```
display_htpasswd_form="true"
htpasswd_file="/testpasswd"
```
3.  Update the docker-compose.yaml file, adding an additional volume `./testpasswd:/testpasswd` to the oauth2-proxy service, like: 
```
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
      - "./testpasswd:/testpasswd"
```
4.  Run `docker-compose -f docker-compose.yaml up`
5.  Wait for the images to start and then open in your browser the url: http://localhost:4180/
6.  Use an incorrect username/password. There is no message shown that the login attempt failed.

## Your Environment

This behaviour is not dependant on a specific environment. It can be produced locally using docker-compose or in a k8s cluster.

- Version used: any

**Comment by morarucostel** [comment]
Just uploading the full oauth2-proxy config file to have the full picture.
```
http_address="0.0.0.0:4180"
cookie_secret="OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
provider="oidc"
email_domains="example.com"
oidc_issuer_url="http://dex.localhost:4190/dex"
client_secret="b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK"
client_id="oauth2-proxy"
cookie_secure="false"
display_htpasswd_form="true"
htpasswd_file="/testpasswd"

redirect_url="http://localhost:4180/oauth2/callback"
upstreams="http://httpbin"
```

**Comment by JoelSpeed** [comment]
This should be easily reproducible using any of our local testing environments and a small modification to allow an `htpasswd_file`.

This is definitely something we should improve, I am imagining some kind of pop up banner saying invalid username/password combination

**Comment by rishi1111** [comment]
![invalid-user](https://user-images.githubusercontent.com/17124299/126861109-f8ec3ce0-786b-494c-9b46-d030f290c91c.png)

Are we looking for something like this? Saw something similar in Keycloak.

**Comment by morarucostel** [comment]
Looks good to me, yes.

**Comment by JoelSpeed** [comment]
That looks great, if we can get a PR for something like that, would be appreciated 😄

**Comment by morarucostel** [comment]
Just bringing it back to the attention.

**Comment by morarucostel** [comment]
Just bringing it back to the attention and asking for help on this.

**Comment by tlawrie** [comment]
Hi @costelmoraru @rishi1111 @JoelSpeed were we able to get a PR for this or was this ever updated by the community?

**Comment by JoelSpeed** [comment]
I don't think this was ever updated. A PR would certainly be welcomed though
