### ISSUE TITLE
Even after the Github authentication is successful k8's dashboard doesn't login and the login page is show to enter the token

### ISSUE THREAD

**Issue by Sandy1438** [oauth2-proxy/oauth2-proxy#1235]
Hi,

I have configured to secure  k8s dashboard using oauth2_proxy,dex and github.
Using the k8s dashboard endpoint it redirects to oauth2_proxy,dex and github signing page. 
After inputting the creds it keep on getting Reauthorization required page and not getting redirected back to k8s dashboard.

![image](https://user-images.githubusercontent.com/71320072/121522717-0448c780-ca13-11eb-8011-c18ddc610e71.png)

When I directly login to https://oauth2proxy.oidcdex.ga/oauth2/auth I get a blank page but I can verify that the ID token is generated as a bearer .

      - args:
        - "--http-address=0.0.0.0:4180"
        - "--cookie-secure=false"
        - "--client-id=<client id>"
        - "--client-secret=<client secret>"
        - "--provider=oidc"
        - "--oidc-issuer-url=https://dex.oidcdex.ga/"
        - "--upstream=https://k8ui.oidcdex.ga" ---> k8 dashboard url, I have also tried with /dev/null and FQDN of dash board service
        - "--email-domain=*"
        - "--set-authorization-header=true"
        - "--redirect-url=https://oauth2proxy.oidcdex.ga/oauth2/callback"
        - "--whitelist-domain=.oidcdex.ga"
        - "--set-xauthrequest=true"
        - "--scope=openid email profile groups"
        - "--pass-basic-auth=false"
        - "--pass-access-token=false"
        - "--show-debug-on-error=true"
        - "--ssl-upstream-insecure-skip-verify=true"
        - "--pass-authorization-header=true"
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie-secret
              name: oauth2-proxy
    
 K8 dashboard Ingress:
 
 apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2proxy.oidcdex.ga/oauth2/start?rd=https://$host$request_uri$is_args$args
    nginx.ingress.kubernetes.io/auth-url: https://oauth2proxy.oidcdex.ga/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    #nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-issuer"
  name: dashboard-ingress
  namespace: k8-ui
spec:
  ingressClassName : nginx
  tls:
  - hosts:
    - k8ui.oidcdex.ga
    secretName: ui-sso-tls
  rules:
  - host: k8ui.oidcdex.ga
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: k8-dashboard
            port:
              number: 80
                        
I would be thankful to you all if any suggestion or help on this to fix.

Thanks.

**Comment by Sandy1438** [comment]
I have resolved the infinite re-authorize loop now but after github authentication k8 dashboard still ask needs the token to be provided.
Where Am I doing wrong?

**Comment by Sandy1438** [comment]
Resolved the issue by whitelisting the cookies domian

**Comment by imranrazakhan** [comment]
For me following changes helped me

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: >-
      X-Auth-Request-Email,X-Auth-Request-Preferred-,X-Auth-Request-Access-Token,
      X-Auth-Request-Roles,X-Auth-Request-User,X-Auth-Request-Groups,X-Forwarded-Groups,
      Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/auth-cache-key: $remote_user$http_authorization
    ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
      proxy_pass_header Authorization;
  name: external-auth-oauth2
  namespace: kubernetes-dashboard
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
```
