### ISSUE TITLE
Check against excluded paths (--skip-auth-regex|--skip-auth-route) before returning 401 Unauthorized in /auth end-point

### ISSUE THREAD

**Issue by dkekel** [oauth2-proxy/oauth2-proxy#1245]
It is not possible to configure `--skip-auth-regex` or `--skip-auth-route` when using OAuth2 with Traefik ForwardAuth Middleware. Every request is passing the authentication check and results in `401` even if the request path should be skipped.

## Current Behavior
In our K8s cluster, we have OAuth2 proxy set-up with [Traefik ForwardAuth Middleware](https://doc.traefik.io/traefik/middlewares/forwardauth/) as described in the [documentation](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#configuring-for-use-with-the-traefik-v2-forwardauth-middleware). As the result, every request to ingress is forwarded to `/auth` end-point in order to decide whether the user is authorized or not _(and should be redirected to sign-in)_.

When `--skip-auth-regex` or `--skip-auth-route` are configured, one would expect that accessing the URLs matching the pattern would result in 202 with or without a valid AOuth2 session and the request will reach the service.

This is not the case since the function never checks against the stored regex paths, but directly returns error if there's no session for the given request:
```
// AuthOnly checks whether the user is currently logged in (both authentication
// and optional authorization).
func (p *OAuthProxy) AuthOnly(rw http.ResponseWriter, req *http.Request) {
	session, err := p.getAuthenticatedSession(rw, req)
	if err != nil {
		http.Error(rw, http.StatusText(http.StatusUnauthorized), http.StatusUnauthorized)
		return
	}

	// Unauthorized cases need to return 403 to prevent infinite redirects with
	// subrequest architectures
	if !authOnlyAuthorize(req, session) {
		http.Error(rw, http.StatusText(http.StatusForbidden), http.StatusForbidden)
		return
	}

	// we are authenticated
	p.addHeadersForProxying(rw, session)
	p.headersChain.Then(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		rw.WriteHeader(http.StatusAccepted)
	})).ServeHTTP(rw, req)
}
```
## Possible Solution

In case of an error when obtaining authenticated session (e.g. when the session cookie is not present in the request), the code should check for the path against stored skip regex matchers.

I.e.
```
session, err := p.getAuthenticatedSession(rw, req)
if err != nil && !p.IsAllowedRequest(req) {
   http.Error(rw, http.StatusText(http.StatusUnauthorized), http.StatusUnauthorized)
   return
}
```

## Context

The issue affects Alfresco tool that is deployed in K8s. The tool contains a service that is an aggregation of API end-points and a small web interface for administration needs. Most of those end-points and the interface should be behind the proxy in order to use SSO. However we would like to expose certain API end-points to other services within our group under basic authentication. This requires to by-pass OAuth2 proxy for those URLs.

## Your Environment

ArgoCD, K8s

- Version used: latest image

**Comment by NickMeves** [comment]
You'll need to remind me since I really only know the basics of Traefik from reviewing Traefik related PRs here 😅 

How does it transmit the original URI to OAuth2-Proxy (since it is calling `/oauth2/auth` endpoint)?

Will it be sent in the `X-Forwarded-Uri`?

I'd need to think very hard about doing any authentication bypasses based on that since the header is very spoofable 😨 

Does Traefik have no ways to configure skipping auth middleware itself in its config similar to nginx subrequests? (these --skip-auth-regex flags only work in inline proxying architectures, not in subrequest architecture like Traefik, nginx/k8s ingress).

**Comment by dkekel** [comment]
Hi @NickMeves , yes the original request information is passed via X-Forwarded headers (see https://doc.traefik.io/traefik/middlewares/forwardauth/#forward-request-headers).

I'll need to dig a bit more to see if there's a way to skip auth middleware. At the time I wasn't able to configure this actually except having two ingress configs for separate end-points.

Coming back to the original request, I see the potential risk there that you mentioned. In fact for my use case I've decided to use JWT tokens instead of Basic Auth since it is well supported with the current Traefik/OAuth proxy architecture. But it might be still useful in general to have `--skip-auth-regex` working with forwarded requests as well (not only for inline proxy).

**Comment by JoelSpeed** [comment]
In other proxies that use external auth servers, the idea is that you configure your skip auth at the proxy level rather than the OAuth2 Proxy level. Is this not possible in Traefik?

**Comment by dkekel** [comment]
In case someone else faces the same problem, in Traefik it is possible to exclude certain paths from ForwardAuth by creating additional routes [1] with rules matching the required URL paths.

[1] https://doc.traefik.io/traefik/v2.2/routing/routers/

**Comment by dkekel** [comment]
In case someone else faces the same problem, in Traefik it is possible to exclude certain paths from ForwardAuth by creating additional routers [1] with rules matching the required URL paths.

[1] https://doc.traefik.io/traefik/v2.2/routing/routers/
