### ISSUE TITLE
oauth2proxy does not forward  authorization header with id token

### ISSUE THREAD

**Issue by beatrausch** [oauth2-proxy/oauth2-proxy#1246]
Running oauth2proxy does not forward Authorization header on my local test setup. The local test setup consist of a running oauth2proxy plus a simple http server on localhost. 

## Expected Behavior

Based on the configuration below I would expect that the authorization header is set in the upstream request to the simple web server: ``Authorization: Bearer <id-token>``

## Current Behavior

The forwarded headers are:

````
Cookie: _oauth2_proxy=***
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
X-Forwarded-For: 127.0.0.1
Host: localhost:4180
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Dnt: 1
X-Forwarded-Email: ***
````

## Your Environment

oauth2proxy running on localhost at port 4180
webserver running on localhost at port 8080

Running oauth2proxy (v7.1.3) with the following flags:
````
oauth2-proxy \
  --provider=keycloak \
  --provider-display-name="Keycloak" \
  --oidc-issuer-url=*** \
  --login-url=***\
  --redeem-url=*** \
  --validate-url=*** \
  --pass-authorization-header=true \
  --set-authorization-header=true \
  --http-address=0.0.0.0:4180 \
  --cookie-expire=0h1m0s \
  --whitelist-domain="*" \
  --cookie-domain=* \
  --standard-logging=true \
  --auth-logging=true \
  --request-logging=true \
  --skip-provider-button=true \
  --upstream=http://localhost:8080 \
  --email-domain=* \
  --client-id="test-client" \
  --client-secret=*** \
  --redirect-url="http://localhost:4180/oauth2/callback" \
  --cookie-secret=*********** \
  --cookie-secure=false \
  --set-xauthrequest=true
````

- Version used:
oauth2proxy v7.1.3

**Comment by NickMeves** [comment]
You'll need to use the `oidc` provider. We only forward IDTokens in the `Authorization` header, which the `keycloak` provider doesn't have since it is only OAuth2 compatible, not OIDC compatible (it has scope: `api`, not `openid ...`).

This issue touches on plans to replace the current Keycloak provider with an OIDC version: https://github.com/oauth2-proxy/oauth2-proxy/issues/956

And there's a PR that's wrapping up.

**Comment by beatrausch** [comment]
Thx for clarification. I 'll will close the ticket.
