### ISSUE TITLE
Add ability to provide audience to auth0 during redemption

### ISSUE THREAD

**Issue by utkuturunc** [oauth2-proxy/oauth2-proxy#1250]
Some oidc providers utilize extra query parameters in the redeem request.

Examples:

Azure: uses `resource` param. This one is already handled by special implementation.

auth0: if a valid `audience` param is present in the requests, the returned token will be in JWT form, otherwise it will be a short opaque string. See: https://community.auth0.com/t/why-is-my-access-token-not-a-jwt-opaque-token/31028

Since it is impossible to define an audience in oauth2 proxy, the token received will be opaque, which makes it impossible to verify the token with jwks.

## Expected Behavior

Be able to define custom query parameters in the oidc provider so that we have more flexibility

## Current Behavior

Some options of oidc providers are not accessible

## Possible Solution

- Add `audience` field to the config
- Add more generic `extra-query-params` to the config
- Create auth0 provider that supports audience

## Context

I'm trying to give an audience to auth0 so that I can receive a JWT token which can be verified using jwks.

**Comment by JoelSpeed** [comment]
Have you tried adding the parameter to the `redeem-url` option? I think this works already

Eg `--redeem-url=https://auth0.domain.com/auth/redeem?audience=foo`

**Comment by utkuturunc** [comment]
@JoelSpeed thanks for the support, the following configuration worked for me


```
    - name: OAUTH2_PROXY_OIDC_ISSUER_URL
      value: https://mydomain.eu.auth0.com/
    - name: OAUTH2_PROXY_OIDC_JWKS_URL
      value: https://mydomain.eu.auth0.com/.well-known/jwks.json
    - name: OAUTH2_PROXY_LOGIN_URL
      value: https://mydomain.eu.auth0.com/authorize?audience=https://api.mydomain.com/
    - name: OAUTH2_PROXY_REDEEM_URL
      value: https://mydomain.eu.auth0.com/oauth/token
    - name: OAUTH2_PROXY_SKIP_OIDC_DISCOVERY
      value: "true"      
```
