### ISSUE TITLE
How do I selectively bypass auth based on URI?

### ISSUE THREAD

**Issue by IDlOT** [oauth2-proxy/oauth2-proxy#1254]
Sorry if this is a stupid question. I have a setup with Nginx roughly equivalent to what's outlined [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#configuring-for-use-with-the-nginx-auth_request-directive). How can I bypass the oauth2-proxy auth request on, for example, '/public/*'? I tried setting up a separate location block, but it always seems to run some aspect of the '/' block as well, namely attempting to redirect me to the sign-in button. Also tried the suggestions [here](https://stackoverflow.com/questions/7878334/nginx-conditional-proxy-pass).

I have Nginx and oauth2-proxy running on containers in a Kubernetes pod, if that's relevant. 

Thanks for any and all help!

**Comment by JoelSpeed** [comment]
This all depends on your nginx config, you just need to have a separate location block that doesn't have the auth attached.

Are you running this via nginx-ingress or just raw nginx config?

**Comment by IDlOT** [comment]
Just raw nginx config. Currently all of this is on a simple pod, not even a deployment. This is my config:

`client_max_body_size 1000M;
map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
}

server {
        listen [::]:80;
        listen 80;
        server_name $HOSTNAME;
        rewrite ^/(.*) https://$server_name/$1 permanent;
}

server {
        listen [::]:443 ssl;
        listen 443 ssl;
        server_name $HOSTNAME;
        ssl_certificate /etc/nginx/conf.d/live/$HOSTNAME/certificate.crt;
        ssl_certificate_key /etc/nginx/conf.d/live/$HOSTNAME/certificate.key;
        charset utf-8;

        location /oauth2/ {
                proxy_pass       $OAUTH2_PROXY_URI;
                proxy_set_header Host                    $host;
                proxy_set_header X-Real-IP               $remote_addr;
                proxy_set_header X-Scheme                $scheme;
                proxy_set_header X-Auth-Request-Redirect $request_uri;
        }
        location = /oauth2/auth {
                proxy_pass       $OAUTH2_PROXY_URI;
                proxy_set_header Host             $host;
                proxy_set_header X-Real-IP        $remote_addr;
                proxy_set_header X-Scheme         $scheme;
                proxy_set_header Content-Length   "";
                proxy_pass_request_body           off;
        }
        location /uploads {
        }
        location / {
                if ($http_user_agent ~* "facebookexternalhit/|Facebot|Tumblr|Slackbot-LinkExpanding|Googlebot|YandexBot|Discordbot") {
                        rewrite ^ /noauth$uri last;
                }
                auth_request /oauth2/auth;
                error_page 401 = /oauth2/sign_in;

                auth_request_set $user   $upstream_http_x_auth_request_user;
                auth_request_set $email  $upstream_http_x_auth_request_email;

                access_by_lua_file '/etc/nginx/conf.d/authorize.lua';

                auth_request_set $auth_cookie $upstream_http_set_cookie;
                add_header Set-Cookie $auth_cookie;

                proxy_pass       $REACT_APP_URI;
                proxy_set_header HTTP_REMOTE_USER  $user;
                proxy_set_header HTTP_REMOTE_EMAIL $email;
                proxy_set_header Host                    $host;
                proxy_set_header X-Real-IP               $remote_addr;
                proxy_set_header X-Scheme                $scheme;
                proxy_set_header X-Auth-Request-Redirect $request_uri;
                proxy_set_header Authorization $http_authorization;
                proxy_pass_header Authorization;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                
        }
        location /api/public {
                proxy_pass       $REACT_APP_URI;
                proxy_set_header HTTP_REMOTE_USER  $user;
                proxy_set_header HTTP_REMOTE_EMAIL $email;
                proxy_set_header Host                    $host;
                proxy_set_header X-Real-IP               $remote_addr;
                proxy_set_header X-Scheme                $scheme;
                proxy_set_header X-Auth-Request-Redirect $request_uri;
        }
        location /noauth {
                internal;
                rewrite ^/noauth(?<realuri>/.*)$ $realuri break;
                proxy_pass       $REACT_APP_URI;
                proxy_set_header HTTP_REMOTE_USER  $user;
                proxy_set_header HTTP_REMOTE_EMAIL $email;
                proxy_set_header Host                    $host;
                proxy_set_header X-Real-IP               $remote_addr;
                proxy_set_header X-Scheme                $scheme;
                proxy_set_header X-Auth-Request-Redirect $request_uri;
        }


        location /v1/graphql {
                proxy_pass $GRAPHQL_URI;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header X-Real-IP               $remote_addr;
                proxy_set_header X-Scheme                $scheme;
                proxy_read_timeout 86400;
        }
}
`

**Comment by IDlOT** [comment]
Update: My specific issue was that Next.js was serving static chunks under a different url, so the public location block wasn't catching them and as a result they were going through the proxy.
