### ISSUE TITLE
How to load user groups via userInfo endpoint?

### ISSUE THREAD

**Issue by adombrovsky** [oauth2-proxy/oauth2-proxy#1257]
Hello, in order to know which roles the current user has, I want to call the `UserInfo` endpoint. 
As I see from the code, this endpoint only works with the session data. The only way I found is to rely on the method [enrichSessionState](https://github.com/oauth2-proxy/oauth2-proxy/blob/d359ab75e1e35fca19521241b2495cbabc9742d7/oauthproxy.go#L801). It looks like all this enrichment will work only if the current session doesn't have any groups.

Is it possible to somehow force an enrichment, so that the groups from the current session will be ignored? Or maybe somehow configure oauth2-proxy to ignore groups when the user session is created.

**Comment by JoelSpeed** [comment]
If you need additional groups from the IDP userinfo endpoint, you should be able to get the access token and call this directly. Would that work for your use case?
