### ISSUE TITLE
Config parameter --https-address does not have effect

### ISSUE THREAD

**Issue by wolfram-laube** [oauth2-proxy/oauth2-proxy#1258]
## Expected Behavior

Our use case is consumption of backend services hosted on Kubernetes with communication authenticated by Keycloak (as a service) and secured by TLS. TLS needs to be propagated to the backend, so no SSL termination at the Load Balancer takes place. The expected communication flow is as follows:
* Client issues request at `https://mydomain.com/myservice`
* NGINX Ingress rule delegates to K8S service without terminating SSL (`nginx.ingress.kubernetes.io/backend-protocol: "HTTPS`)
* K8S service delegates to oauth2-proxy sidecar, using the port configured for HTTPS protocol (`--https-address: 0.0.0.0:443`)
* oauth2-proxy delegates authentication flow to Keycloak and after success redirects to backend main container

## Current Behavior

The NGINX logs indicate that connectivity with oauth2-proxy on configured HTTPS port cannot be established:
```
2021/06/30 10:25:36 [error] 35#35: *75356 connect() failed (111: Connection refused) while connecting to upstream, client: 10.128.15.204, server: 27642801-review-wla-nojira-rp1101..., request: "GET /favicon.ico HTTP/2.0", upstream: "https://10.20.2.13:8443/favicon.ico", host: "27642801-review-wla-nojira-rp1101...", referrer: "https://27642801-review-wla-nojira-rp1101.../"
```
When diagnostically changing the service to forward to the HTTP port, connection is established but uses wrong protocol, as expected:
```
2021/06/30 10:04:09 [error] 34#34: *67028 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 10.20.1.1, server: 27642801-review-wla-nojira-rp1101.dev.gke.blauweiss-edv.de, request: "GET /favicon.ico HTTP/2.0", upstream: "https://10.20.2.13:4180/favicon.ico", host: "27642801-review-wla-nojira-rp1101.dev.gke.blauweiss-edv.de", referrer: "https://27642801-review-wla-nojira-rp1101.dev.gke.blauweiss-edv.de/"
10.20.1.1 - - [30/Jun/2021:10:04:09 +0000] "GET /favicon.ico HTTP/2.0" 502 560 "https://27642801-review-wla-nojira-rp1101.dev.gke.blauweiss-edv.de/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36" 158 0.002 [common-modules-prototype-27642801-review-wla-nojira-rp1101-production-common-module-8002] [] 10.20.2.13:4180, 10.20.2.13:4180, 10.20.2.13:4180 0, 0, 0 0.000, 0.000, 0.001 502, 502, 502 c5609dc999cb07def797b2730f95c57d
```
It seems that - although possible to configure - the option `--https-address` does not have any effect.
I tried to verify this using standalone docker images `quay.io/pusher/oauth2_proxy:v6.1.1` and `bitnami/oauth2-proxy:7`
(see steps to reproduce below). Both of them are not responding to HTTPS requests on the configured port.

## Possible Solution
If HTTPS comm with oauth2-proxy is not an option, we will have to disable server.ssl in our backend services and rely on TLS for external communication only. But ideally, I'm simply missing something here J

## Steps to Reproduce (for bugs)

1.  
Fire up a docker container with a dummy config, only heeding the ports:
```
docker run -p 4180:4180 -p 8443:8443 bitnami/oauth2-proxy:7 \
    --cookie-secure=false \
    --upstream="file:///dev/null" \
    --http-address="0.0.0.0:4180" \
    --https-address="0.0.0.0:8443" \
    --redirect-url="http://internal.website.com/oauth2/callback" \
    --cookie-secret="NXA4K2lMUGsrSnFLYnprWnZESE5GUDNINzIrc2NHUnQ=" \
    --client-id=changeme \
    --client-secret=changeme \
    --email-domain=*

```
2.  
Connect to HTTP port:

```
> curl localhost:4180

<!DOCTYPE html>
<html lang="en" charset="utf-8">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Sign In</title>
 ...
```
Corresponds to issued from inside the oauth2-proxy sidecar on the cluster:
```
platform@production-6d4648464b-hqrd7:~$ curl localhost:4180
<a href="https://lemur-3.cloud-iam.com/auth/realms/blauweiss-iam/protocol/openid-connect/auth?approval_prompt=force&amp;client_id=hexenwawi1&amp;redirect_uri=https%3A%2F%2Flocalhost%3A4180%2Foauth2%2Fcallback&amp;response_type=code&amp;scope=api&amp;state=bb6af75de08cdc794feeaa253c997b49%3A%2F">Found</a>.
```
3.  
Connect to HTTPS port:
```
> curl localhost:8443

curl: (56) Recv failure: Connection reset by peer
```
Corresponds to issued from inside the oauth2-proxy sidecar on the cluster:
```
platform@production-6d4648464b-hqrd7:~$ curl localhost:8443
curl: (7) Failed to connect to localhost port 8443: Connection refused
```
(Connection `reset by peer` on a local machine as opposed to `refused` inside the K8S stemming from the Docker port forwarding on the local machine)

## Context

We want to offer backend service functionality for authenticated users over a secure line, to the internet as well as inside the K8S cluster. So we do not terminate SSL at front load balancer but propagate to the backend services, each of which has SSL enabled.

## Your Environment

GKE with NGINX ingress controller

- Version used:
Docker images `quay.io/pusher/oauth2_proxy:v6.1.1` and `bitnami/oauth2-proxy:7`

**Comment by JoelSpeed** [comment]
I think the issue is that you haven't set a TLS key or TLS certificate to use. Are there any warnings in the log that suggest it's not using HTTPs because these are missing? Maybe that's something we should add.

Normally, the HTTP server is disabled when the HTTPS server is enabled, which implies to me we are not even trying to start it, hence my thinking it's the TLS configuration
