### ISSUE TITLE
User headers are not getting sent with keycloak using nginx 

### ISSUE THREAD

**Issue by wcom939** [oauth2-proxy/oauth2-proxy#1259]
I am testing my keycloak/nginx/oauth integration using spring boot as the end application, all my settings are specified so as to pass both user/email headers, however both are not getting sent to the proxied application

## Expected Behavior

I should see X-User and X-Email headers in the headers list

## Current Behavior

The headers are missing

## Steps to Reproduce (for bugs)

1.  Setup a default keycloak instance
2.  Setup a default oauth2-proxy instance on windows (using the config for keycloak)
3.  setup nginx on windows using the config file suggested for auth_request in oauth2-proxy docs
4.  setup a simple spring boot also on windows, with one root controller to get the headers being received

- Version used: 7.1.3

NGINX config:
![image](https://user-images.githubusercontent.com/16446451/123991506-c8ad7780-d998-11eb-8384-e8896f7821e8.png)

oauth2-proxy config:
![image](https://user-images.githubusercontent.com/16446451/123992070-47a2b000-d999-11eb-8f47-844bbfb4397e.png)

Resulting headers coming in from spring boot:
![image](https://user-images.githubusercontent.com/16446451/123992641-cc8dc980-d999-11eb-8a3f-598231c89420.png)

**Comment by JoelSpeed** [comment]
Once you've authenticated, could you try accessing your OAuth2 Proxy instance at `/oauth2/auth` and record the response headers? It would be good to identify if the error is OAuth2 Proxy not sending the headers back or some other misconfiguration
