### ISSUE TITLE
List of options when basic auth used with htpasswd file

### ISSUE THREAD

**Issue by sanchesfrolov** [oauth2-proxy/oauth2-proxy#1261]
I am trying to set up simple basic auth with htpasswd file(--htpasswd-file).
But I could not find any example and just try to choose something based on my gut feeling :)
And all the time get different exceptions such us:
 invalid configuration
 oidc provider requires an oidc issuer URL
unknown flag: --display_htpasswd_form
 
## Expected Behavior
It would be better to have certain list of parameters which are demanded for using htpasswd-file

## Current Behavior

Lack of documentation for htpasswd feature.

## Possible Solution

Add example for described case to repository and documentation

## Your Environment

Kubernetes,
Oauth proxy is used as sidecar k8s container

- Version used:
7.1.3

**Comment by JoelSpeed** [comment]
As far as I know, the HTPASSWD feature is meant to be used as additional auth when using a real provider. Can you confirm this is what you are trying to do? 

If you just want basic auth protection this is better handled by something like Nginx which can do this built in and is probably more performant than OAuth2 Proxy

**Comment by sanchesfrolov** [comment]
Thank you for explanation
