### ISSUE TITLE
Keycloak as oidc provider and nginx auth_request gives back 403 with allowed_groups query string

### ISSUE THREAD

**Issue by TheAnachronism** [oauth2-proxy/oauth2-proxy#1263]
I currently have nginx and keycloak running and nginx uses the auth_request module to talk to OAuth2-Proxy which has oidc configurations for keycloak. In nginx I'm using the ?allowed_groups query string to specify that only a specific group can access this site. I have the same group specified with `OAUTH2_PROXY_ALLOWED_GROUPS`.
Now when I actually login I get the 403 Forbidden response from the proxy.

## Expected Behavior

It says by specifying the group in the configuration and in nginx it should allow the user with such a group to access the site. But I still get the unauthorized result.

## Steps to Reproduce (for bugs)

These are my environment variables for the proxy:

- OAUTH2_PROXY_HTTP_ADDRESS=http://XXXX
- OAUTH2_PROXY_REVERSE_PROXY=true
- OAUTH2_PROXY_WHITELIST_DOMAIN=.
- OAUTH2_PROXY_PASS_HOST_HEADER=true
- OAUTH2_PROXY_COOKIE_SECRET=XXXX
- OAUTH2_PROXY_COOKIE_SECURE=false
- OAUTH2_PROXY_EMAIL_DOMAINS=*
- OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
- OAUTH2_PROXY_PROVIDER=oidc
- OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=Keycloak
- OAUTH2_PROXY_OIDC_ISSUER_URL=https://XXX/auth/realms/OAuth2Proxy
- OAUTH2_PROXY_CLIENT_ID=OAuth2Proxy
- OAUTH2_PROXY_CLIENT_SECRET=XXXX
- OAUTH2_PROXY_ALLOWED_GROUPS=OAuth2Proxy
- OAUTH2_PROXY_SCOPE=openid
 
This is my nginx configuration:

```
server {
    listen						443 ssl;
    server_name					XXX;

    location / {
        auth_request                            /oauth2/auth;
        proxy_pass                              http://XXX;
        proxy_buffer_size                       8k;
        error_page 401 =                        /oauth2/sign_in;
        auth_request_set                        $user   $upstream_http_x_auth_request_user;
        auth_request_set                        $email  $upstream_http_x_auth_request_email;
        proxy_set_header                        X-User  $user;
        proxy_set_header                        X-Email $email;
        proxy_set_header                        X-Forwarded-Host $http_host;
        proxy_set_header                        X-Real-IP $remote_addr;
        proxy_set_header                        X-Forwarded-Proto $scheme;
        proxy_set_header X-Auth-Request-Redirect $request_uri;
        auth_request_set                        $auth_cookie $upstream_http_set_cookie;
    }
    location /oauth2 {
        proxy_set_header Host                       $host;
        proxy_set_header X-Real-IP                  $remote_addr;
        proxy_set_header X-Scheme                   $scheme;
        proxy_set_header X-Auth-Request-Redirect    $request_uri;
        proxy_buffer_size                           8k;
        proxy_pass http://authProxy/oauth2;
    }
    location = /oauth2/auth {
        proxy_pass                              http://authProxy/oauth2/auth?allowed_groups=OAuth2Proxy;
        proxy_buffer_size                       8k;
        proxy_set_header                        Host             $host;
        proxy_set_header                        X-Real-IP        $remote_addr;
        proxy_set_header                        X-Scheme         $scheme;
        proxy_set_header                        Content-Length   "";
        proxy_set_header X-Auth-Request-Redirect $request_uri;
        proxy_pass_request_body                 off;
    }
}
```

## Your Environment

Without the `allowed_groups` query string it works fine.

**Comment by J3m5** [comment]
I'm also interested, this is a requirement for us.
I saw this issue https://github.com/oauth2-proxy/oauth2-proxy/issues/1215 but @oxenit was using the keycloak provider and not the oidc one like you are.

**Comment by J3m5** [comment]
For information

Related issues: 
https://github.com/oauth2-proxy/oauth2-proxy/issues/831
https://github.com/oauth2-proxy/oauth2-proxy/issues/854
https://github.com/oauth2-proxy/oauth2-proxy/issues/1158
https://github.com/oauth2-proxy/oauth2-proxy/issues/1197

Related PR:
https://github.com/oauth2-proxy/oauth2-proxy/pull/849

**Comment by TheAnachronism** [comment]
> using the keycloak provider and not the oidc one like you are

I was using the oidc because in some other issue it was mentioned to just use that one instead of keycloak, because keycloak was kind of outdated or quite messy.
Apperantly it should get reworked at some point.

**Comment by snoopyCode** [comment]
If your group is called `OAuth2Proxy` in Keycloak try '/OAuth2Proxy' with `/` as prefix in `OAUTH2_PROXY_ALLOWED_GROUPS`

**Comment by TheAnachronism** [comment]
I've tried it with this / prefix but there doesn't seem to be any change in behavior. I still get a 403 after successful login with a user that is part of that group.

**Comment by jali-clarke** [comment]
> If your group is called `OAuth2Proxy` in Keycloak try `/OAuth2Proxy` with `/` as prefix in `OAUTH2_PROXY_ALLOWED_GROUPS`

partial necro to confirm that this _does_ work in my situation

**Comment by TheAnachronism** [comment]
OK, so I've come back to this issue as now I really have the use case, where I have one instance of oauth2-proxy running which is used by nginx with the auth request module. But I don't want all the websites which nginx handles restricted to a certain group. That's why I'd like to do that over the `allowed_groups` query-string, is possible.
As I understand it, using the environment variable will restrict the entire proxy to those groups.

Any idea if / how this is done?

**Comment by JoelSpeed** [comment]
Perhaps #1546 can help you @TheAnachronism

**Comment by TheAnachronism** [comment]
> Perhaps https://github.com/oauth2-proxy/oauth2-proxy/pull/1546 can help you @TheAnachronism

Actually, it wasn't this, but rather that it needs a `/` infront of the group because that's how the groups are returned from keycloak.
I have no idea why, but using `/Groupname` works.
