### ISSUE TITLE
Curl with Bearer token from Azure app not works

### ISSUE THREAD

**Issue by aleksandrovpa** [oauth2-proxy/oauth2-proxy#1270]
Couldn't authenticate with Azure Enterprise Application

## Expected Behavior

Request should proxy to service without redirect to auth page, if token not expired

## Current Behavior

Proxy get token without email (its normal for app, not user) and redirect to login Microsoft page

## Possible Solution

I'm not sure, but for my situation, think we could add condition [here](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/provider_data.go#L156) to set `temp@temp.com`. But this is not production solution

## Steps to Reproduce (for bugs)

At first, get a token with command:

```sh
1. TOKEN=$(curl -X POST -d 'grant_type=client_credentials&client_id=<>&client_secret=<>resource=<>>' https://login.microsoftonline.com/<>/oauth2/token | jq -r '.access_token')
2. curl -X GET -H "Authorization: Bearer ${TOKEN}" "https://$host/api/something" -H "accept: application/json"
```

## Context

We have a service, behind the oauth-proxy, and via browser everything works fine, but we have to send PUT request to the API of this service, just via `curl` and this is not working now

## Your Environment

k8s version = 1.19
nginx-ingress version = v0.35.0
oauth2_proxy version = quay.io/pusher/oauth2_proxy:v4.1.0

**Comment by grzesuav** [comment]
I have similar impression, does oauth2-proxy validates `Authorization` header from the request ? It it requires user to validate via proxy and use its own session cookie to verify if request is validated ?

It would be quite nice to see the first option.

**Comment by JoelSpeed** [comment]
How have you configured OAuth2 Proxy? We have an option to allow accepting headers in this manner `skip-jwt-bearer-tokens`, though you may want to use a newer version than version 4 for this

**Comment by E-gy** [comment]
@JoelSpeed doesn't `skip-jwt-bearer-tokens` still verify `email` claim of the bearer? And since not all OAuth flows include email addresses...

For example, to make Client Credential Flow with Keycloak work, one has to
1. Add a mapper to the client that adds a hardcoded `email` claim for an address with the trusted domain
2. Disable email verification in OAuth2 Proxy (since email won't ever be verified since service accounts don't have any)

(or at the very least i failed to find another way to use OAuth2 proxy OIDC provider to assert M2M authentication done with client credential flow).

**Comment by JoelSpeed** [comment]
Right yes, I see that the email verification can be an issue as this is required for now.

We plan in the future to make the Authz stuff completely seperate and not require it globally. The idea is that it's there if people want it, but can be ignored for those who don't

Something which I hadn't considered before is that as we introduce multiple providers, we probably want to have the ability to set the Authz on a per provider level, which I don't think we had planned for before (CC @NickMeves)

**Comment by NickMeves** [comment]
I just started musing through the future of authz & multiple providers in this PR too 😄 

https://github.com/oauth2-proxy/oauth2-proxy/pull/1340#issuecomment-913184576

Agreed! I think we will likely need to extend our session construct potentially so if we use a central provider engine, the provider/IdP can be an attributed used in ABAC style Authz rules.

**Comment by ksaadDE** [comment]
#2966
