### ISSUE TITLE
Is it possible to use certificate as client credential?

### ISSUE THREAD

**Issue by SleepyBag** [oauth2-proxy/oauth2-proxy#1272]
As RFC 6749 doesn't force the manner of client authentication, it seems that oauth2-proxy only support [client password](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1) now. However, I notice that Azure Active Directory also support certificate as client authentication. Is it possible to support this in the implementation of oauth2-proxy?

**Comment by JoelSpeed** [comment]
This is not something I've tried or tested, so at the moment I wouldn't be able to say if this is something that works or not.

Have you tried setting the client secret to a certificate? Are there additional requirements for the certificate client authentication that we would need to support?

**Comment by SleepyBag** [comment]
It shouldn't work because the process of using credentials is different from the process of using secret.

Specifically, to redeem a access token, we should sign a JWT with private key, not just pass the secret to Azure AD, as said here [https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token-with-a-certificate-credential](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token-with-a-certificate-credential). I notice that this process is implemented in the provider of logingov.

**Comment by trettstadtnlb** [comment]
Our company policy does not allow passwords as client credentials in production, so we need to use certificates. Is there still a chance that this gets implemented?

**Comment by JoelSpeed** [comment]
This is unlikely to be implemented by maintainers at the moment, but if a community member has time to take it on, we will try to put some time aside to review the changes

**Comment by nemobis** [comment]
A bit confusing that this was closed as completed after https://github.com/oauth2-proxy/oauth2-proxy/issues/1339 but in https://github.com/oauth2-proxy/oauth2-proxy/issues/1486 it was not considered completed.
