### ISSUE TITLE
Can we use oauth2-proxy for Single page applications?

### ISSUE THREAD

**Issue by r-kotagudem** [oauth2-proxy/oauth2-proxy#1277]
We are currently using oauth2-proxy for server side UI applications. can we use oauth2-proxy for angular applications.

My understanding is that SPA loads into the browser initially and the request wont go cross oauth2-proxy in further requests. how do we validate and maintain session. (is hitting the SPA again every 1 hr (for token refresh) the way to go?)

The api to fill the data in SPA will be different domain.
is silent refresh of token possible?

**Comment by JoelSpeed** [comment]
If your SPA can make a request to the `/oauth2/auth` endpoint periodically, it will refresh the session and set the new cookie in the response. I don't know if this is something you can do with an SPA as I don't know if you'd be able to update the browser cookie store from the SPA

**Comment by knabben** [comment]
For different domains, this can be set by the `--cookie-domain` parameter. And the `--cookie-httponly` set to false, so the SPA will be able to access `document.cookie`, this widens the surface attack though. Alternatives?

**Comment by knabben** [comment]
I have seen some similar approaches in libraries like `mozilla-oidc-django` - https://mozilla-django-oidc.readthedocs.io/en/stable/xhr.html

About setting the new cookie it can work with `--cookie-httponly` set to false and the SPA will be able to access it on `document.cookie`, this widens the surface attack though. Any other alternatives more secure?

**Comment by J3m5** [comment]
Is it possible to have the same cookie/token for the two endpoints ?

**Comment by knabben** [comment]
> Is it possible to have the same cookie/token for the two endpoints ?

If they are on different domains I don't think so, otherwise for subdomain you can forward the token from frontend to the backend using withCredentials 

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by r-kotagudem** [comment]
> If your SPA can make a request to the `/oauth2/auth` endpoint periodically, it will refresh the session and set the new cookie in the response. I don't know if this is something you can do with an SPA as I don't know if you'd be able to update the browser cookie store from the SPA

in that case, the token needs to be included with in the cookie? we have a problem with this. our user tokens are larger . so we are using redis. also as @knabben mentioned it is not so secure.

thanks for replying.

**Comment by JoelSpeed** [comment]
If your app can make a request to `/oauth2/auth`, that should also be able to return things like the tokens as separate headers, which you can then copy to the request to the backend application if you need to send the token specifically

**Comment by r-kotagudem** [comment]
> If your app can make a request to `/oauth2/auth`, that should also be able to return things like the tokens as separate headers, which you can then copy to the request to the backend application if you need to send the token specifically

ok thanks, will try.

**Comment by WestFarmer** [comment]
@JoelSpeed 
> make a request to the `/oauth2/auth` endpoint periodically

will this make the idle counting invalid ?
