### ISSUE TITLE
Issues migrating from https://sts.windows.net/{tenant-id}/ to https://login.microsoftonline.com/{tenant-id}/v2.0

### ISSUE THREAD

**Issue by avodaqstephan** [oauth2-proxy/oauth2-proxy#1279]
Hi, 

currently we're running oauth2-proxy together with the ingress-nginx-controller.
When we started to use oauth2-proxy we accidentally went with an outdated oidc-url "https://sts.windows.net/{tenant-id}/" but it worked!

Since we found out, that the [common Endpoint](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints) is only supported for the oidc-url "https://login.microsoftonline.com/{tenant-id}/v2.0"  we wanted to migrate.

At first we tried without the "common" endpoint. It doesn't work. So I'm asking for some support here ;)

My configuration:

```
- args:
  - --provider=oidc
  - --email-domain=domain.com
  - --upstream=file:///dev/null
  - --http-address=0.0.0.0:4180
  - --set-authorization-header=true
  - --pass-authorization-header=true
  - --pass-access-token=true
  - --pass-user-headers=true
  - --scope=openid,profile,email
  - --set-xauthrequest=true
  # old working url - --oidc-issuer-url=https://sts.windows.net/{client-id}/
  - --oidc-issuer-url=https://login.microsoftonline.com/{tenant-id}/v2.0
  - --whitelist-domain=.domain.de
  - --cookie-domain=.domain.de
```

I always get the response: `The application 'Foo' asked for scope 'openid,profile,email' that doesn't exist on the resource 'BAR'. Contact the app vendor.` 

The question is, why does it break? It works with the old endpoints.

Further is their an option to set the "common" endpoint to actually be able to allow users out of our organisation to login?

Kind regards, 
Stephan

**Comment by avodaqstephan** [comment]
Actually the setup of our Azure tenant was just wrong.

**Comment by ldynia** [comment]
@avodaqstephan  Could you share the configuration of oauth2_proxy that worked for you ? What was wrong with Azure tenant setup that you mentioned ? Much oblige!
