### ISSUE TITLE
Force Enrichment of Groups provided by Userinfo / Profilinfo Endpoint

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#1281]
## Expected Behavior

Groups contained in the ID Token AND provided by the userinfo / profilinfo endpoint are available in session data.

## Current Behavior

The userinfo/profile endpoint of our IDP returns all groups with roles of the user. Unfortunately, however, these groups are not stored in the session data because the Id token already contains a groups claim. But these are not all groups that are needed.
Unfortunately we can't disable that the Id token already contains the groups claim in the IDP.
Because of this not all needed groups end up in the session data.

## Possible Solution

Make oauth2 proxy configurable or append groups from userinfo / profileinfo always to the session data.

## Context

We want to pass all user groups with roles to upstream services for checking permissions.

- Version used: v.7.1.3

**Comment by JoelSpeed** [comment]
Is there any way to force your provider to store all the groups in the ID Token?
Is there any reason they don't do this by default that you are aware of?

Can we think of any scenarios where merging the two lists of groups could be problematic?

**Comment by Bibob7** [comment]
> Is there any way to force your provider to store all the groups in the ID Token?
> Is there any reason they don't do this by default that you are aware of?

We already ask for it. It is not possible to put all groups in the token. They just mentioned, that is not easily possible to change the implementation.

> Can we think of any scenarios where merging the two lists of groups could be problematic?

If we just append and override, i don‘t see any problems. The provided groups should not differ. Event if there is an overlap.
