### ISSUE TITLE
Enrich OIDC provider with custom Assertion Attributes from IdP?

### ISSUE THREAD

**Issue by sTb1337** [oauth2-proxy/oauth2-proxy#1282]
I am sry to open an issue for this but I am not able to join the Slack Server, because my mail address is not registered there? How can I be added/allowed into this Slack Space?

Our IdP is sending some additional custom flat Assertion Attributes (like Country / ZIP Code ect..) within the JWT .

How can i map and forward this information to the web application upstream?

I am currently in the process of writing an new provider which is a copy of OICD. The OICD provider is working fine, but doesn't parse, map and forward the custom Assertion Attributes the the web application upstream.

Question:
1. Am i on the right track to copy the existing OICD provider and add the custom mapping within https://github.com/oauth2-proxy/oauth2-proxy/blob/0b4bc36554b218eb34a0b47b18791695323b2004/providers/oidc.go#L71 ?
2. Is it already configurable via custom claims? If yes, may you provide an example, because for me https://github.com/oauth2-proxy/oauth2-proxy/issues/772 is an dead end.  Maybe https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config#using-alpha-configuration ?

**Comment by JoelSpeed** [comment]
> I am sry to open an issue for this but I am not able to join the Slack Server, because my mail address is not registered there? How can I be added/allowed into this Slack Space?

I think you can sign up from https://invite.slack.golangbridge.org/

> How can i map and forward this information to the web application upstream?

I am working on a feature to allow you to map and forward arbitrary claims at the moment, I expect this will be done within the next few months.

**Comment by sTb1337** [comment]
Thanks a lot! 

Iam really keen on using OAuth2Proxy within our new k8s enterprise product (~70k users). For that we really need forwarding custom assertion attributes from the JWToken. 

In the meantime can we achive this by implementing our own provider?

**Comment by JoelSpeed** [comment]
Yeah you may be able to do so by implementing your own provider based on the existing OIDC provider
