### ISSUE TITLE
"Login Failed: Unable to find a valid CSRF token." when Using GKE Ingress Load Balancer

### ISSUE THREAD

**Issue by kmcentush** [oauth2-proxy/oauth2-proxy#1284]
## Expected Behavior

I've set up a Docker container with an app and OAuth2-Proxy. Inside the container, I use NGINX to force authentication. This is working when testing locally.

I then deployed the container to Google Kubernetes Engine (GKE). The pods are live, etc. I can go to my site and go through the Google OAuth process, and then I run into a 403 error during the callback: Login Failed: Unable to find a valid CSRF token.

## Current Behavior

I checked the logs for my GKE ingress, and the callback URL is correct. However, I did noticed in the network traceback in Chrome developer tools that there do not appear to be any cookie headers being passed back to the app.

## Possible Solution

Is this the kind of issue that the [docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#configuring-for-use-with-the-nginx-auth_request-directive) address with the subsection about kubernetes and ingress NGINX?

I'm trying to determine if switching to Traefik instead of NGINX (again, inside the container) may fix the issue, or if that likely will have the same result since all of that is abstracted behind the GKE ingress load balancer.

## Steps to Reproduce (for bugs)

If a reproducible example is necessary, I can try my best to abstract away a simple example. But again, at the heart of my implementation is a Docker container w/ NGINX (inside the container) forcing authentication for my app. This works by itself locally, so I imagine the actual issue is somehow related to the GKE ingress load balancer.

## Your Environment

- Version used:
v7.1.3

**Comment by ShyLionTjmn** [comment]
try --cookie-secure=false

**Comment by kmcentush** [comment]
@ShyLionTjmn Wow, that actually did the trick!

Would you be able to explain what the issue is, and how I can work to be able to use `--cookie-secure=true` again?

**Comment by kmcentush** [comment]
Update: I found the source of my issue. I had set my host to use `http` and not `https` in the OAuth2-Proxy config. Once I defined my host with `https`, I was able to re-enable `--cookie-secure=true` without issues.

Case closed!
