### ISSUE TITLE
Ability to check if user is a collaborator on GitHub repo(s)

### ISSUE THREAD

**Issue by michaelbayles** [oauth2-proxy/oauth2-proxy#129]
The GitHub provider allows us to check if an authenticating user is part of the Organization or a particular team within the Organization. However, I need to authenticate users that are not part of the Organization, but are given read-only access to a single private repository. As the owner of the repo, I can give the user collaboration access to repo, and so I'd like a way to cascade that to my documentation site (authenticated via GitHub provider).

## Expected Behavior

New GitHub Provider option to specify which repo(s) to look at to find collaborators. 

## Current Behavior

The major difference here is that when configuring the reverse proxy, I'd also need to provide a token that can check the collaborators on a repo. https://developer.github.com/v3/repos/collaborators/#check-if-a-user-is-a-collaborator

## Possible Solution

New GitHub Provider option to specify which repo(s) to look at to find collaborators. During authentication, check if the user is a collaborator via 
https://developer.github.com/v3/repos/collaborators/#check-if-a-user-is-a-collaborator

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by mdgreenwald** [comment]
I'm impacted by this as well.

**Comment by mdgreenwald** [comment]
Is there still interest in resolving this?

**Comment by jsclayton** [comment]
I'm working on a PR now to add this. 🤚

**Comment by JoelSpeed** [comment]
This was implemented, closing
