### ISSUE TITLE
Traverse Github for list of sub-teams when specifying -github-team=""

### ISSUE THREAD

**Issue by Rakhmanov** [oauth2-proxy/oauth2-proxy#1295]
## Expected Behavior
Github allows to nest teams. I propose to traverse the teams list nested under the parent and grant them access allowed to the parent team.

## Current Behavior
When using Github auth provider with team based security as described:
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#github-auth-provider
The provider only looks at the top level for providing the access. And any sub teams that need the access have to be explicitly listed in the argument.

## Possible Solution
1) Modify behavior of current `-github-team=` parameter
    When doing the traversal in: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/github.go#L266
Issue the request to fetch subteams and add them to the presentTeams list. 
Drawback: need to account for duplicates. During last step list need to be checked for duplicate. Or convert to use map structure.

2) Introduce new parameter in form `-github-team-expanded=` and perform necessary team expansion requests to build complete list of teams.

3) Introduce flag modifying behavior of -github-team
     `-expand-github-teams`  This would trigger logic performing necessary team expansion requests to build complete list of teams.

## Context

Nested groups are often used to share similar configuration of access patterns for user across different teams.

- Version used:
Any

**Comment by JoelSpeed** [comment]
Just a few things that have come to mind while reading this:
* Are new permissions needed to allow the group traversal do you think?
* What is the impact in the number of API calls we have to make here?
* Is there a possibility for a circular group membership?

Have you had a go at implementing one of the solutions?
