### ISSUE TITLE
Forwarded token-id

### ISSUE THREAD

**Issue by brackend** [oauth2-proxy/oauth2-proxy#1298]
Configuration used is: ForwardAuth with 401 errors middleware using traefik.  The token is not sent to the upstream application.  Just the _oauth2-proxy cookie is sent.

## Expected Behavior

The proxy should allow token ids to reach upstream applications.  The applications may use the token id to either carry out user info introspection or accept the claims.  The applications access control has not information it can use.

Isn't this existing funtionality?

## Current Behavior
With the following config, the upstream is not receiving the token. 
      email_domains = [ "*" ]
      upstreams = [ "file:///dev/null" ]
      http_address = "xxxxx"
      scope= "openid email groups"
      oidc_groups_claim = "groups"
      oidc_email_claim = "email"
      oidc_jwks_url = "https://xxxxxx"
      provider = "oidc"
      oidc_issuer_url = "https://xxxxx"
      provider_display_name = "xxxxxx)"
      set_xauthrequest = true
      set_authorization_header = true
      pass_authorization_header = true
      pass_access_token = true

## Possible Solution

Assuming this is a config issue.

## Steps to Reproduce (for bugs)
1.  Redirects to provider on accessing the url
2. Authenticate on provider
3. Callback with auth code 
4. Oauth2-proxy forwards the request to the application
5. Result: no forwarded headers or cookies.   Just the oauth2-proxy cookie.

## Context

Applications sitting behind the proxy and traefik ingress should recieve token ids and other information forwarded from the idp.

## Your Environment

Kubernetest - traefik ingress, oauth2-proxy, various applications hosted on k8s.  

- Version used:OAuth2 Proxy version v7.1.3

**Comment by ianroberts** [comment]
When you're using the `/oauth2/auth` mode the `set_*` configuration options to oauth2-proxy add additional headers to the response that oauth2-proxy sends back to traefik, but you then have to add [extra configuration at the traefik side](https://doc.traefik.io/traefik/middlewares/forwardauth/#authresponseheaders) to take those response headers and copy them to the upstream request.
