### ISSUE TITLE
Feature request: ability to pass through /oauth2/start query parameters to the IdP

### ISSUE THREAD

**Issue by ianroberts** [oauth2-proxy/oauth2-proxy#1314]
It is possible to set the `prompt` parameter value passed to the OAuth2 login page via configuration, but oauth2-proxy will always pass the same value in all cases.  I have a use case where I would like to be able to pass a different `prompt` value _for specific requests only_.

In my case I'm using the `oidc` provider configured with Azure AD as the issuer.  The default behaviour of AAD without a `prompt` parameter is:

- if the user is not logged in to Azure, prompt for their email address and then authenticate them as normal
- if the user is logged in to _exactly one_ Azure account, and that account has already authorised the app (either the user has consented or the admin has pre-consented the app for all that tenant's users) then redirect back immediately to the callback URL
- if the user is logged in to _more than one_ Azure account, prompt the user to select the account they want to use, or log in as a different one

This is fine for my app in most cases, but I want to be able to offer an option in my app to "sign in as a different user", which should pass `prompt=select_account` to Azure to force it to display the account chooser (which always includes the "sign in as another account" option) even if the user is only signed in to one Azure account at the time.

This could be implemented as an additional query parameter to the `/oauth2/start` endpoint allowing the caller to specify a different `prompt` value which it passes through to the login URL.  I'm happy to start on a PR for this but wanted to check a few principles first:

- is this a feature you would be prepared to merge in?
- should this be a special case for the `prompt` parameter specifically
  - and if so should we verify that the value passed in is a valid OIDC `prompt` value per spec
- or should it be a more general feature where _any_ query parameters passed to `/oauth2/start` automatically feed through to the login URL (so it would be applicable to all providers, not just `oidc`)
  - perhaps with certain parameter names block-listed so a malicious caller can't manipulate the standard parameters like the callback URL, client ID, etc. etc

**Comment by Xwaffle1** [comment]
I'm also in need of a very similar change. In general when we provide parameters to `/oauth2/start` It would be great to have the parameters passed to the provider as well.

In my scenario I'm using Keycloak, and keycloak lets you pass in `login_hint` as a parameter.
When you use this parameter directly it fills out the email for you for a user.

In my setup, I require a user to enter their Email before they are sent to keycloak.


Unfortunately this parameter needs to be dynamically passed in per user to the URL, when you pass it to `/oauth2/start` in my case `/oauth2/start` redirects to my oidc-url: `dev-keycloak.company.com/auth/realms/SomeRealm`


Unfortunately during the redirect my parameter passed to `/oauth2/start` gets removed from your query :-/ and the users provided auth email gets removed

**Comment by JoelSpeed** [comment]
> is this a feature you would be prepared to merge in?

Initially I don't have objections to the feature, what I'd like to see more of is some context/discussion about possible ways this could be abused (or rather why it can't) to allow users to be directed to the wrong place or for the credentials to be stolen

> should this be a special case for the prompt parameter specifically
and if so should we verify that the value passed in is a valid OIDC prompt value per spec

Making it wider does sound interesting initially, but it also widens the scope for possible security holes, so I'd suggest keeping the scope to just prompt initially

CC @NickMeves WDYT of this feature request, any initial concerns?

**Comment by NickMeves** [comment]
This seems fine to me!

I think if this were really extensible (to support all the providers people have mentioned this may apply), we should have an `allowlist` on which dynamic queryparams we respect if added to `/oauth2/start`.

The one tough area architecturally -- this seems very provider specific, but the `/oauth2/start` layer is global.

**Comment by ianroberts** [comment]
I like the allowlist idea, I'm thinking an allowlist where each item is either just a plain query parameter name (in which case any value of that parameter will pass through to the login URL) or a `name=value` pair which allows through only that specific value for the parameter (e.g. `prompt=select_account`).  If you want to allow several different values you can put them all in the allowlist, e.g. `["prompt=select_account", "prompt=consent"]`).

Regarding `prompt` specifically, the current behaviour of `providers.makeLoginURL` seems to be that

- it will send a `prompt` value if one has been specified in the config file
- if no `prompt` has been set it'll send the configured value of `approval_prompt`
- if neither `prompt` nor `approval_prompt` has been set in the config it will default to `approval_prompt=force`

Is this third step actually desired behaviour?  There seems to be no way to send _neither_ `prompt` _nor_ `approval_prompt` - if `approval_prompt` were explicitly set to the empty string in config then oauth2-proxy would still send `approval_prompt=` with an empty value.  And if it is desired behaviour then I guess we'd need to make a special case to preserve this where we're feeding through `prompt` from the `/oauth2/start` URL (i.e. if there's a `prompt` on the `start` URL then use that, if there isn't then fall back to the usual three step process above).

**Comment by ianroberts** [comment]
Also do we need to distinguish between actual calls to `/oauth2/start` and calls to other endpoints that internally delegate to `OAuthStart`?  In fact it looks like any `Proxy` call has a code path that could end up calling `p.OAuthStart(rw, req)` if we have configured to skip the provider button, and my guess is we don't want to automatically interpret `/my/app/doSomething?prompt=none` as trying to set a prompt value on the login URL if it happens to redirect that far...

**Comment by JoelSpeed** [comment]
> Also do we need to distinguish between actual calls to /oauth2/start and calls to other endpoints that internally delegate to OAuthStart? 

Yes, I think it would be good if we could have something in the scope that marks the request as having originated at the start endpoint, and then from there we can either ignore the query params or observe them. Is it enough to look at the request path? Do we want to handle `sign_in` as well when skip provider button is enabled?

**Comment by ianroberts** [comment]
Any movement on this?  I've just rebased my PR, if you would like me to make changes to the config format just say so over there.

**Comment by ianroberts** [comment]
Oh, I thought commenting on this should have "un-staled" it...

**Comment by JoelSpeed** [comment]
I just had a look through the PR. There was a comment recently about making this a provider specific option, I think that makes sense and have commented on the PR as to that effect. Let's try to continue that conversation there.

In general, I think this is a good feature request and we should try and get the PR through once we get the design agreed upon
