### ISSUE TITLE
Make the /oauth2/auth endpoint status codes configureable to facilitate optional Authorization header via auth_request

### ISSUE THREAD

**Issue by jord1e** [oauth2-proxy/oauth2-proxy#1319]
## Expected Behavior

I would like the status codes of the `/oauth2/auth` endpoint to be configurable to support **optionally** passing the Authorization header to backend/upstream services to facilitate anonymous (unauthenticated) users. Making the status codes configurable is the only way I know of to make this work effectually with NGINX.

The desired result would look something like the following:

![Desired result](https://user-images.githubusercontent.com/30464310/129215842-5b392291-c67f-4738-919f-5129d130f720.png)

The cookie would be set via the normal route if a user explicitly decides to sign-in (via `/oauth2/sign_in`).

## Current Behavior

The status codes [are hardcoded](https://github.com/oauth2-proxy/oauth2-proxy/blob/42c16efa38b3e88f4ccb951fd5ed49a555e716fa/oauthproxy.go#L817):

<table>
<thead>
  <tr>
    <th>Condition</th>
    <th>Status Code</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>Error retrieving session</td>
    <td>401 Unauthorized</td>
  </tr>
  <tr>
    <td>authOnlyAuthorize logic (check groups)</td>
    <td>403 Forbidden</td>
  </tr>
  <tr>
    <td>Success</td>
    <td>202 Accepted</td>
  </tr>
</tbody>
</table>

## Possible Solution

Make the status codes configurable for the `/oauth2/auth` endpoint. I propose the following:

<table>
<thead>
  <tr>
    <th>CMD</th>
    <th>Config file</th>
    <th>Type</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>--auth-endpoint-unauthenticated-status</td>
    <td>auth_endpoint_unauthenticated_status</td>
    <td>int</td>
  </tr>
  <tr>
    <td>--auth-endpoint-unauthorized-status</td>
    <td>auth_endpoint_unauthorized_status</td>
    <td>int</td>
  </tr>
  <tr>
    <td>--auth-endpoint-success-status</td>
    <td>auth_endpoint_success_status</td>
    <td>int</td>
  </tr>
</tbody>
</table>

The terminology `unauthenticated` and `unauthorized` is a bit confusing, maybe a maintainer can comment on good alternatives taking in to account the current situation.

We then check if the code is supported by calling [`http#StatusText`](https://pkg.go.dev/net/http#StatusText), if the code is valid the method will return a non-empty string. When the code is *invalid* the proxy should fail to start.

The current setup using `http.Error` will continue to work, [every status code has a StatusText](https://cs.opensource.google/go/go/+/master:src/net/http/status.go) (open in a Chrome browser 🙄).

## Steps to Reproduce (for bugs)

N/A

## Context

I would like to support anonymous (unauthorized) users via NGINX + oauth2-proxy whilst still using the Authorization header "token relay" feature of oauth2-proxy for users that explicitly sign-in (and thus have a `_oauth2_proxy` cookie).

## Your Environment

N/A

## Contributing the feature

**I would like to contribute this feature in the form of a pull request**, if no other method exists for achieving my goal, using only NGINX (and something like oauth2-proxy, of course).

**Comment by JoelSpeed** [comment]
Can Nginx not be configured to allow the traffic to the backend even when a 403 or 401 is returned?
I know the sign in logic works via overriding the error_page directive, maybe leaving this out or using it in some special way makes this work without needing to modify OAuth2 Proxy?

**Comment by jord1e** [comment]
http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page

The following was bothering me:
> This causes an internal redirect to the specified uri with the client request method changed to “GET” (for all methods other than “GET” and “HEAD”).

But i overlooked this:
> If there is no need to change URI and method during internal redirection it is possible to pass error processing into a named location:
location / {
    error_page 404 = @fallback;
}
location @fallback {
    proxy_pass http://backend;
}
If uri processing leads to an error, the status code of the last occurred error is returned to the client.

I will try using this and get back tomorrow, if anyone else knows how to do this with nginx-ingress i would like to know :)

**Comment by jord1e** [comment]
nginx-ingress doesn't offer a simple way to edit the error_page because of two things:

The location isn't named, so you can't proxy the request whilst keeping the original method etc.:

- [The location directive](https://github.com/kubernetes/ingress-nginx/blob/9a9ad4785704ef7ec0f6428e5cfb2a32d9af5cf3/rootfs/etc/nginx/template/nginx.tmpl#L1090)
- [Function responsible for generating the location](https://github.com/kubernetes/ingress-nginx/blob/b591adac48d213102991f83a1bdfc21d78d0e733/internal/ingress/controller/template/template.go#L510)

And secondly, the auth_request directive is buried somewhere in the middle of the configuration:
https://github.com/kubernetes/ingress-nginx/blob/9a9ad4785704ef7ec0f6428e5cfb2a32d9af5cf3/rootfs/etc/nginx/template/nginx.tmpl#L1178 (error_page directive on line 1188).

Forking ingress-nginx or copying the entire configuration would not be preferred 🤐.

I could also add yet another service between oauth2-proxy and the ingress like so:

![Untitled Diagram(1)](https://user-images.githubusercontent.com/30464310/129372621-d83cd65d-7d27-4609-bc3d-17caef34ac6b.png)

But that would be inefficient, for obvious reasons.

**Comment by jord1e** [comment]
ugh, reactivate

**Comment by miklezzzz** [comment]
any chance this feature gets implemented? Could come in handy when the oauth-proxy is used as a middleware with envoy gateway (it seems EG respects only 200, not 202)
p.s. reactivate

**Comment by jord1e** [comment]
> any chance this feature gets implemented? Could come in handy when the oauth-proxy is used as a middleware with envoy gateway (it seems EG respects only 200, not 202) p.s. reactivate

The change was relatively simple, but it was never merged
https://github.com/oauth2-proxy/oauth2-proxy/pull/1332

I think back than I abandoned the hobby project.

You can try basing it off the PR, no idea how much changed to the project in 3 years, but feel free to
