### ISSUE TITLE
Need to allow oauth2-proxy to allow watching the changes in the content behind htpasswd-file

### ISSUE THREAD

**Issue by morarucostel** [oauth2-proxy/oauth2-proxy#1320]
We want to be able to make oauth2-proxy watch the values from the `htpasswd-file` and dynamically allow them new entries to be picked-up/removed. Similar to what `authenticated-emails-file` flag is doing. 

## Expected Behavior

Adding a new user/password entry in the storage (secret) behind the `htpasswd-file` will allow the new user to login. Removing an entry from storage will deny that user a successful login.

## Current Behavior

Currently the updates in the content of `htpasswd-file` and not picked-up by oauth2-proxy authentication mechanism.

## Possible Solution

Similar implementation with what is behind the `authenticated-emails-file` flag.

## Steps to Reproduce (for bugs)

1. Start oauth2-proxy with `display-htpasswd-form` and `htpasswd-file`
2. Add a new entry in the secret holding the list of existing users/passwords
3. Attempt a login with the newly introduced credentials
4. Login fails

## Context

There are some scenarios (PoCs, local installs, ...) where we use the `htpasswd-file` to authenticate users and our solution needs a dynamic way in adding new users that can access the solution.

## Your Environment

Not relevant, 

- Version used: v7.1.3

**Comment by morarucostel** [comment]
@NickMeves, I can push a PR refactoring the htpasswd.go in the same way you did the validator.go with the `WatchForUpdates`. 
In order to reuse the `WatchForUpdates` I believe we need to move it in a package under pkg. Any thoughts were to move it?

**Comment by JoelSpeed** [comment]
This was on my radar to work on at some point in the future as well, thanks for picking it up, will take a look at the PR shortly!

**Comment by morarucostel** [comment]
Just reopening the issue, since the fix is in progress.

**Comment by matheusMoreno** [comment]
Hey, did this issue ever get resolved? I'm facing the exact same problem: I'm updating a Kubernetes Secret with new passwords, but the changes are not being reflected on the container.

**Comment by tlawrie** [comment]
Hi @matheusMoreno @costelmoraru @JoelSpeed @aiciobanu were we ever able to get the PR merged in, this would be a great fix if so for those of us that use Basic Auth in dev environments or locally.

I see that the PR was closed after inactivity, but was close to being able to be merged in and maybe needed some help from the maintainers to get across the line.

**Comment by aiciobanu** [comment]
Hello @morarucostel @tlawrie @JoelSpeed I agree, this issue should be resolved. Instead of reopening the PR created last year, we should start anew from the latest version of the code to skip the merge & refactor hell.

**Comment by JoelSpeed** [comment]
Does anyone have time to take that on? I'm open to reviewing a PR but am unlikely to have time to implement it myself

**Comment by aiciobanu** [comment]
I can take this task

**Comment by aiciobanu** [comment]
@JoelSpeed @tlawrie @costelmoraru I've pushed a PR(https://github.com/oauth2-proxy/oauth2-proxy/pull/1701) that implements this feature

**Comment by tlawrie** [comment]
Hey @aiciobanu that is very exciting!

Hopefully the community is able to review and merge it in. Itd be fantastic to get that functionality included.
