### ISSUE TITLE
Traefik forward auth using error pages provides white page with "Found." link

### ISSUE THREAD

**Issue by NegativeFeedback** [oauth2-proxy/oauth2-proxy#1322]
When I use the parameter -skip-provider-button or false, I am only presented a white page with a single link named "Found" instead.

Expected Behavior

I would have expected to be redirected to the login site of the provider directly. 

Current Behavior

Show white page with "Found" link instead of being redirected to provider.
Steps to Reproduce (for bugs)

I have a nomad cluster with the following settings
```

job "oauth-proxy" {
  region      = "us"
  datacenters = ["dc1"]
  type        = "service"

  group "oauth-proxy" {
    count = 1

    task "oauth-proxy" {
      vault {
        policies = ["superuser"]
      }
      driver = "docker"
      env {
      }
      config {
        image        = "quay.io/pusher/oauth2_proxy:latest"
        args = [
          "--set-xauthrequest", "true",
          "--pass-access-token", "true",
          "--pass-authorization-header", "true",
          "--skip-provider-button", "true"
        ]
        port_map = {
          http = 4180
        }
      }

template {
  data = <<EOH

OAUTH2_PROXY_CLIENT_ID=''
OAUTH2_PROXY_CLIENT_SECRET=''
OAUTH2_PROXY_COOKIE_DOMAIN='..io'
OAUTH2_PROXY_COOKIE_REFRESH='1h'
OAUTH2_PROXY_COOKIE_SECURE='true'
OAUTH2_PROXY_COOKIE_SECRET=''
OAUTH2_PROXY_EMAIL_DOMAINS=*
OAUTH2_PROXY_FOOTER='-'
OAUTH2_PROXY_HTTP_ADDRESS='0.0.0.0:4180'
OAUTH2_PROXY_PASS_BASIC_AUTH='false'
OAUTH2_PROXY_PASS_USER_HEADERS='true'
OAUTH2_PROXY_PROVIDER='keycloak'
OAUTH2_PROXY_REVERSE_PROXY='true'
OAUTH2_PROXY_SET_AUTHORIZATION_HEADER='true'
OAUTH2_PROXY_SET_XAUTHREQUEST='true'
OAUTH2_PROXY_WHITELIST_DOMAIN='..io'
OAUTH2_PROXY_LOGIN_URL="https:///protocol/openid-connect/auth"
OAUTH2_PROXY_REDEEM_URL="https:///protocol/openid-connect/token"
OAUTH2_PROXY_PROFILE_URL="https:///protocol/openid-connect/userinfo"
OAUTH2_PROXY_VALIDATE_URL="https:///protocol/openid-connect/userinfo"
OAUTH2_PROXY_SCOPE=email

EOH

  destination = "secrets/file.env"
  env         = true
}
      resources {
        cpu    = 100
        memory = 128
        network {
          port "https" {
            static = 4180
          }
        }
      }

      service {
        port = "https"
        name = "oauth-proxy"
        tags = [
          "traefik.enable=true",
          "traefik.http.middlewares.oauth-verify.forwardAuth.address=http://oauth-proxy.service.consul:4180/oauth2/auth",
          "traefik.http.middlewares.oauth-verify.forwardAuth.trustForwardHeader=true",
          "traefik.http.middlewares.oauth-verify.forwardAuth.authResponseHeaders=X-Auth-Request-User,X-Auth-Request-Email,Authorization,Set-Cookie",
          "traefik.http.middlewares.oauth-signin.errors.service=oauth-proxy@consulcatalog",
          "traefik.http.middlewares.oauth-signin.errors.status=401",
          "traefik.http.middlewares.oauth-signin.errors.query=/oauth2/sign_in",
          "traefik.http.routers.oauth.rule=Host(`auth.`) || PathPrefix(`/oauth2`)",
          "traefik.http.routers.oauth-proxy.entryPoints=https",
          "traefik.http.routers.oauth.tls.certResolver='le'",
#          "traefik.http.services.oauth.loadbalancer.server.port='4180'",
          "traefik.http.routers.oauth.service=oauth-proxy@consulcatalog",
        ]
      }
    }
  }
}
```

**Comment by JoelSpeed** [comment]
The found page you refer to is OAuth2 Proxy responding with a redirect. When using Traefik you don't need to use the skip provider button option, instead just set the errors.query to `/oauth2/start`, you have `/oauth2/sign_in` at the moment

**Comment by atbentley** [comment]
Hi @JoelSpeed, I'm also seeing this issue. I'm using `/oauth2/start` as you suggest.

Maybe worth noting that oauth2 proxy is responding with a 401 status code and a location header. Seems to me that this should be a 301 status code?

Also the links are correct, both the link in the html response and the link in the location header. So everything works, just an extra click is needed right now.

<img width="916" alt="Screen Shot 2021-08-23 at 6 28 52 pm" src="https://user-images.githubusercontent.com/5869437/130483586-4930f60d-b87c-42a0-93bf-ae554af472fd.png">

**Comment by JoelSpeed** [comment]
Yeah you're right, does look like this should be a 301, can you double check the logs of OAuth2 proxy to find that request, it should say what the response is there. I have a suspicion that there's some config error in the traefik configuration that is not liking the 301 response and so is returning a 401 because it thinks you're unauthorised

**Comment by aplovich** [comment]
Traefik forwardAuth returns the response from the auth server it's checking (if not 2xx).  So it'll return the 401 response issued by the /oauth2/auth endpoint.  Perhaps oauth2-proxy could allow for setting the status code to 301?

https://doc.traefik.io/traefik/v2.0/middlewares/forwardauth/

**Comment by atze234** [comment]
Hi, im at the same stage with this problem: location header with a 401 response. 
The Logs of oauth2-proxy show:

`[2021/09/21 12:03:53] [stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.20.36.51 - 336afc15-ab6f-4a40-8311-7ce0d5e83bb7 - - [2021/09/21 12:03:53] whoami-sand.example.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36" 401 13 0.000
10.20.36.51 - 182d5c42-3b28-4290-8f43-d68f8aadfa73 - - [2021/09/21 12:03:53] whoami-sand.example.com GET - "/oauth2/start" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36" 302 368 0.000`

But the Traefik Logs show 401 for this request:
`
time="2021-09-21T12:09:39Z" level=debug msg="Remote error http://authproxy2-oauth2-proxy.ex.svc.cluster.local/oauth2/auth. StatusCode: 401" middlewareType=ForwardedAuthType middlewareName=ex-oauth2@kubernetescrd
time="2021-09-21T12:09:39Z" level=debug msg="Caught HTTP Status Code 401, returning error page" middlewareType=customError middlewareName=ex-oauth2start@kubernetescrd
[...]
10.200.4.61 - - [21/Sep/2021:12:09:39 +0000] "GET / HTTP/1.1" 401 368 "-" "-" 1645 "whoami-internal-ex-whoami-sand-ex@kubernetes" "http://100.106.187.59:4180" 4ms`

So maybe traefik just keeps the 401 it got before the Error page

Im using oauth-proxy v7.1.3 and traefik 2.4.8 and dont have an idea how to fix this atm. 

I also tried to use the provider Button Page with /oauth2/sign_in at the error Middleware. 
But there the Provider Button always points to the same location where i want to login:
mypage.example.com/oauth2/start as the "button action", which will respond with a 401 bringing me back to the sign_in page with the provider button...loop
The form action have to be static linked to oauth2-proxy ingress for this case - which isnt possible

**Comment by JoelSpeed** [comment]
I'd recommend taking a look through the other issues on this repo that relate to Traefik. I know others have had this working and the responses from OAuth2 Proxy are correct. I suspect this is a Traefik misconfiguration somewhere
