### ISSUE TITLE
Include  Request details in  error logs

### ISSUE THREAD

**Issue by MNF** [oauth2-proxy/oauth2-proxy#1324]
## Current Behavior
If in configuration we set request-logging=true, logs include detailed info like 
`log:"10.244.6.249:52822 - - [2021/08/11 00:14:34] siteUrl GET - "/oauth2/callback?error=server_error&error_description=AADB2C90047%3a+The+resource+%27https%3a%2f%2fstatic.siteUrl%2fweb%2fui%2fb2c%2flogin-siteUrl.html%27+contains+script+errors+preventing+it+from+being+loaded.%0d%0aCorrelation+ID%3a+d075fa72-3e37-4170-8c02-b7414205e777%0d%0aTimestamp%3a+2021-08-10+12%3a25%3a53Z%0d%0a&state=6421bf92335d940cca3ea5974eb5%3ahttps%3a%2f%2siteUrl%%2fSignIn%2fSignInSucceeded" HTTP/1.0 "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/170.0.386351093 Mobile/18F72 Safari/604.1" 403 2664 0.000",`
But in production we generally prefer to suppress them.

Unfortunately In case of errors the logged information is minimal
"[oauthproxy.go:729] Error while parsing OAuth2 callback: server_error"

## Expected Behavior

Ideally I want to see detailed information similar to  logger.PrintReq as a part of the error log.

## Possible Solution

E.g. in func (p *OAuthProxy) OAuthCallback(rw http.ResponseWriter, req *http.Request)
It will be good  to create responseLogger := &responseLogger{rw : rw} and pass it to method similar to logger.PrintReq(responseLogger.authInfo, responseLogger.upstream, req, url, t, responseLogger.Status(), responseLogger.Size())  (but without if!l.reqEnabled ) to
generate details and then include the details in logger.Errorf.

Do you see any issues with such error logging improvement?

## Steps to Reproduce (for bugs)

Set request-logging=false and view logs in case of errors.

## Context

How has this issue affected you? What are you trying to accomplish? 
We want to quickly understand the details of production errors, but do not log too many noise logs.

## Your Environment

- Version used:
- Fork of oauth_proxy as on March 2021 (v7.0)

**Comment by JoelSpeed** [comment]
We have several open issues talking about the logging not being paritcularly great throughout OAuth2 Proxy. It's on the list of things we want to get to. We need to identify a way to introduce levelled logging to allow users to define exactly how much logging they want. I have some sketches of this lying around somewhere but haven't had the time to take them all the way through to a PR

**Comment by MNF** [comment]
The example how it was done in our private forks is available in [Support MinimalLogLevel and adding request to error logs. #1353](https://github.com/oauth2-proxy/oauth2-proxy/pull/1353)

**Comment by JoelSpeed** [comment]
Would it be preferable to, when a request returns an error, have the request printed even if request logging is disabled? Using the newly added request IDs you could then track the request details from the separate request line

**Comment by michael-freidgeim-webjet** [comment]
@JoelSpeed , can you point to some document/code describing “newly added request IDs”? 
It will be ok  if in case of error an error log entry will have  request ID for reference and request will be logged separately.

**Comment by JoelSpeed** [comment]
Take a look at #1087 where this was implemented. IIRC, if a request ID is forwarded in a header, we use that, else we generate a request ID and log that in relevant logs
