### ISSUE TITLE
Is it possible to configure the oauth2-proxy as a public client ?

### ISSUE THREAD

**Issue by fcomte** [oauth2-proxy/oauth2-proxy#1327]
I would like to run this proxy in an unsafe context. I wonder if it's possible tu run it as a public client.
If not, is it just because it's not implemented or does it make no sens to do that ?

**Comment by JoelSpeed** [comment]
I don't think this project is particularly suitable for running as a public client. Typically public clients are flows implemented in shortly lived application sessions, eg if you implemented it in a mobile app that you then share via an app store.

This app is more intended to be managed as part of your application stack.

What is the use case you are trying to solve here?

**Comment by fcomte** [comment]
I develop an application that run some web application ( like jupyter , rstudio ) [](https://github.com/InseeFrLab/onyxia-web)
This apps are helm package deployed in a user namespace. I would like to run oauth2-proxy in front of each apps. 
Those apps are running in a kubernetes namespace where the user is admin so configuring each oauth2-proxy as a public client would fit to my usecase

**Comment by JoelSpeed** [comment]
In this scenario I would expect the end user to set up their own instance of the OAuth2 Proxy no? It's pretty standard when deploying apps like this that a user has to go configure the secrets and what not to deploy the app themselves
