### ISSUE TITLE
Azure: support upn claim as header

### ISSUE THREAD

**Issue by mblaschke** [oauth2-proxy/oauth2-proxy#1328]
## Expected Behavior

Header `x-auth-request-preferred-username` or `x-auth-request-upn` is added

## Current Behavior

Only `x-auth-request-email` exists

## Possible Solution

allow to add more claims as headers

## Context

in some AzureADs the email is not suitable so we need the UPN claim asheader.

## Your Environment

- Version used: 7.1.3

**Comment by ianroberts** [comment]
If you switch to alpha configuration you can map any claim in the token to any header name.

**Comment by mblaschke** [comment]
is there any timeline when this will be stable?
