### ISSUE TITLE
Feature request: Support htpasswd plain passwords

### ISSUE THREAD

**Issue by mkilchhofer** [oauth2-proxy/oauth2-proxy#1331]
I use oauth2-proxy with the helm chart in several kubernetes environments.
There are multiple scenarios, where I need basic auth besides oauth2/OIDC (eg. oauth2-proxy in front of Prometheus and Grafana uses basic auth to reach Prometheus) 

Since I use terraform to deploy the helm chart, I also use the bcyrpt() function of terraform to generate the hash for the htpasswd config file. Unfortunately bcrypt is not a idempotent function and therefore it triggers a helm upgrade every time my terraform code executes.

It seems that the code also supports SHA1 hashes (although the docs says only bcrypt is supported):
https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/authentication/basic/htpasswd.go#L68-L74

What about supporting plain passwords if there is no prefix?

**Comment by JoelSpeed** [comment]
> Since I use terraform to deploy the helm chart, I also use the bcyrpt() function of terraform to generate the hash for the htpasswd config file. Unfortunately bcrypt is not a idempotent function and therefore it triggers a helm upgrade every time my terraform code executes.

I think this is a terraform issue more than an issue for us. AFAIK terraform should be able to keep track of the inputs and determine if it actually needs to update the output based on whether the input changed or not. I fixed a bug in the AWS terraform provider that had similar behaviour in the past, KMS is also not idempotent, but the KMS provider does now produce a stable output.

Have you raised an issue on the terraform provider side?

**Comment by mkilchhofer** [comment]
This might be true, yes. I thought that this implementing this feature here would be trivial, but I already found a way to solve this.
The solution was to adapt your helm chart and "move the problem" to the helm component:
https://github.com/oauth2-proxy/manifests/pull/55 WDYT?

**Comment by JoelSpeed** [comment]
I left a comment on the other PR. For now I'm going to close this issue as I don't think this is something we want to support directly in the product. Storing plaintext passwords has obvious security issues, I would rather we didn't encourage it
