### ISSUE TITLE
Is it possible to pass the user email to upstream on header?

### ISSUE THREAD

**Issue by rubasace** [oauth2-proxy/oauth2-proxy#1334]
First of all, sorry if the answer to this is obvious as I'm a complete noob regarding this project, I just use it but I'm not too savvy regarding reverse proxies.

I'm using oauth2-proxy with nginx ingress controller to secure access to a media server I have running using k8s. One of the apps I'm hosting is [calibre-web](https://github.com/janeczku/calibre-web). It allows me to use my reverse-proxy authentication if I indicate which header contains the email, so I don't have to manage usernames and passwords. 

Reading the old version of oauth2-proxy README I saw something about `X-Email` header. I have the feeling this has now been replaced by explicit calls to the `/oauth2/userinfo` endpoint. I was just wondering if there's any way I can enable the propagation of the user email via a header so I can use it on calibre-web. Not sure if, otherwise, this is something that can be achieved via nginx itself. Thanks a lot, any help on the topic would be really appreciated.

**Comment by JoelSpeed** [comment]
If you use the `set-xauthrequest` option, it will then return some extra headers when nginx calls the `/oauth2/auth` endpoint, IIRC `X-Auth-Request-Email`. You can then use the nginx ingress controller annotations (one to do with auth-request headers?), to copy that over to the request to your backend application. This is definitely possible and a lot of examples can be found throughout our issues and docs.
