### ISSUE TITLE
Username field type is email when htpasswd is enabled

### ISSUE THREAD

**Issue by pburgisser** [oauth2-proxy/oauth2-proxy#1336]
When the htpasswd file is provided, the username+password fields are shown but the username is checking for a an email.

## Expected Behavior

When the htpassword file is provided, I should be able to login with a account which doesn't contains an '@'

## Current Behavior

The GUI is complaining that username doesn't contain an '@' and doesn't let the user in

## Possible Solution

Remove type="email" in HTML

## Steps to Reproduce (for bugs)

- Version used: 7.1.3

**Comment by JoelSpeed** [comment]
This makes sense, though I was under the impression I had tested this before and it worked with non-email logins. Perhaps we have regressed in some way 🤔 

Have you tried taking the existing template, modifying it and then setting it up as a custom template?

**Comment by pburgisser** [comment]
I have tested it with a custom template using a standard text field which works.
I have a commit ready to push the update.

**Comment by JoelSpeed** [comment]
Cool, if you could create a PR I'll try and find some time to take it for a test drive and verify that I can (and then can't) reproduce the issue

**Comment by pburgisser** [comment]
OK thanks. I have created the PR (not sure that the description is 100% accurate though)
