### ISSUE TITLE
Ability to config oidc provider to use mTLS (e.g. Client Certs/Users Certs)

### ISSUE THREAD

**Issue by bgoldiing** [oauth2-proxy/oauth2-proxy#1339]
Currently, when oidc provider required user to authenticate using the client/user certificate and the oauth2-proxy is return a 500 error.  

## Expected Behavior

oauth2-proxy redirect user to idam. IDAM prompts user to user cert and issues JWT token after authorizing user. oauth2-proxy callback redirect user to the originally required URL.

## Current Behavior

Oauth2-proxy redirect user to idam, user is prompted for certs,  idam issue a token and it's added to header. Browser is then redirect back to `oauth2/callback` URL where OAuth2-proxy returns a 500 error. It looks like oauth2-proxy is trying to call idam directly (without a cert). In the oauth2-proxy see the following in the logs:

```
[2021/08/23 15:59:24] [oauthproxy.go:748] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 400 Bad Request
Response: <html>
<head><title>400 No required SSL certificate was sent</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>No required SSL certificate was sent</center>
<hr><center>nginx</center>
</body>
</html>
```

Below is the arguments where passing to oauth2-proxy:

```
   --http-address=0.0.0.0:4180
   --metrics-address=0.0.0.0:44180
   --cookie-domain=.xyz-mda.io
   --cookie-expire=24h0m0s
   --insecure-oidc-allow-unverified-email=true
   --login-url=https://idam-staging.xyz.io/auth/realms/luna/protocol/openid-connect/auth
   --oidc-issuer-url=https://idam-staging.xyz.io/auth/realms/luna
   --oidc-jwks-url=https://idam-staging.xyz.io/auth/realms/luna/protocol/openid-connect/certs
   --pass-access-token=true
   --pass-authorization-header=true
   --pass-user-headers=true
   --provider=oidc
   --provider-display-name=Staging IDAM
   --redeem-url=https://idam-staging.xyz.io/auth/realms/luna/protocol/openid-connect/token
   --redirect-url=https://staging.xyz.io/oauth2/callback
   --reverse-proxy=true
   --scope=openid
   --set-authorization-header=true
    --set-xauthrequest=true
     --skip-jwt-bearer-tokens=false
     --skip-oidc-discovery=true
     --ssl-insecure-skip-verify=true
     --validate-url=https://idam-staging.xyz.io/auth/realms/luna/protocol/openid-connect/userinfo
     --whitelist-domain=.xyz.io
    --config=/etc/oauth2_proxy/oauth2_proxy.cfg
```

## Possible Solution

* Maybe, update oauth2-proxy to pass on the user cert over to the idam (would required oauth2-proxy tls setting to be configured with `nginx.ingress.kubernetes.io/auth-tls-verify-client: On ` 

## Steps to Reproduce (for bugs)

1. Setup keycloak with oidc cliednt configured to required user cert. 
2. Configure oauth2-proxy to use oidc provide. 

## Your Environment & Version

Running oauth2-proxy v7.1.3 in k8s with ingress-nginx (v0.47.0)

**Comment by JoelSpeed** [comment]
Is this similar to #1272 ?
