### ISSUE TITLE
Error loading cookied session: PF named cookie not present, removing session

### ISSUE THREAD

**Issue by pancudaniel7** [oauth2-proxy/oauth2-proxy#1342]
I receive error log message in oauth2-proxy service: **"Error loading cookied session: PF named cookie not present, removing session"** when I try to authenticate using Istio Oauth2-proxy and Envoy.
## Expected Behavior

Successfully store the session cookie in order to finish the Authentication

## Current Behavior

The first log error I receive when I get the first **pingIdentity redirect login page**, the login page is displayed but after I login successfully and receive **Auth code** oauth2-proxy **fails** to retrieve token using **Auth Code** and enters in a **redirect infinite loop** where the oauth2-proxy **resends the same authentication redirect url** containing the **Auth code**. (In my opinion this is because the cookie was not stored and the sessions was removed)

## Steps to Reproduce (for bugs)

1.  Accessing service external url
2.  Get redirected to PinkIdentity idp login page
3.  Add credentials and press submit (After submit the browser will enter in **a infinite redirect loop**, receiving wrong redirect url for geting the Oauth2 token after he receive the Auth code)

Session cookie properties, this cookie is generated by ping identity idp and is called PF:
![IMG_20210824_113313__01](https://user-images.githubusercontent.com/9675142/130584768-9ad57f3e-0c1a-4d91-8263-6d265ff9f3a9.jpg)

Oauth2-proxy flags config: 
```console
          - --provider=oidc
          - --provider-display-name="ping"
          - --provider-ca-file=/etc/ssl/certs/rtrust-ca-cert.pem
          - --cookie-refresh=1h
          - --cookie-expire=4h
          - --cookie-samesite=none
          - --cookie-secured=true
          - --cookie-path=/
          - --cookie-name=PF
          - --cookie-domain=idp-d.rbinternational.com
          - --skip-oidc-discovery=true
          - --oidc-issuer-url={{ .Values.serviceMesh.auth.issuerUrl }}
          - --login-url={{ .Values.serviceMesh.auth.issuerUrl }}/as/authorization.oauth2
          - --redeem-url={{ .Values.serviceMesh.auth.issuerUrl }}/as/token.oauth2
          - --oidc-jwks-url={{ .Values.serviceMesh.auth.issuerUrl }}/pf/JWKS
          - --validate-url={{ .Values.serviceMesh.auth.issuerUrl }}/as/token.oauth2
          - --redirect-url=https://{{ .Values.namespace }}.neuron-{{ .Values.namePrefix }}.{{ .Values.dnsEnvSuffix }}.{{ .Values.dnsSuffix }}.internal.cluster.cloud/
          - --whitelist-domain={{ .Values.namespace }}.neuron-{{ .Values.namePrefix }}.{{ .Values.dnsEnvSuffix }}.{{ .Values.dnsSuffix }}.internal.cluster.cloud
          - --skip-provider-button=true
          - --http-address=0.0.0.0:4180
          - --upstream=static://200
          - --email-domain=*
```

## Context

I am blocked to finish delivering Authentication and Authorization for a urgent product in a decoupled way.

## Your Environment

Cluster: Openshift4
ServiceMesh: Istio 2.0
Oauth2-proxy: 7.1.3
Envoy for Istio 2.0

**Comment by JoelSpeed** [comment]
This sort of thing normally happens because the cookie isn't being set to the correct domain. The domain setting for the cookie needs to allow OAuth2 Proxy to access it, looking at your value, this would mean that OAuth2 Proxy is hosted on `idp-d.rbinternational.com`, is that correct?

**Comment by pancudaniel7** [comment]
Your right, thanks I will close the issue

**Comment by pancudaniel7** [comment]
Cookie domain misconfigured
