### ISSUE TITLE
Different instances at different versions share the same session via redis

### ISSUE THREAD

**Issue by pettermk** [oauth2-proxy/oauth2-proxy#1346]
Hi,
I just realized that we use oauth2-proxy in my organization in a possibly strange way, I would like to clarify with developers if we need to take action.

There are multiple apps served in subpaths on the same domain. We use azure application gateway to proxy requests to  subfolders. Apps in the subfolders are served as individual applications (proxied to a different domain which is protected by its own oauth2 proxy), but they all share the same session store in redis.

Now deployment of these apps are not necessarily synced, and they all pull the latest version of the oauth2 proxy when they are built. So the question is, do we need to make sure that all are using the same oauth2 proxy version, or does the session conform to some interface which can be safely used between minor/patch versions?

I have seen weird internal server errors and 403 forbidden lately, which are resolved by clearing the cookies, which is what has prompted my question.

**Comment by JoelSpeed** [comment]
We tend to treat the session storage as an internal interface, and while we provide backwards compatibility, we don't provide forwards compatibility. I would recommend making sure that all of your OAuth2 Proxys are on the same major.minor version at all times to prevent possible issues with the sessions not being serialised correctly by older instances

**Comment by pettermk** [comment]
Thanks a lot for the clarification, and sticking to the same major.minor version sounds like a good idea :+1:
