### ISSUE TITLE
JWT access tokens with from OKTA with skip_jwt_bearer_tokens = true

### ISSUE THREAD

**Issue by imduffy15** [oauth2-proxy/oauth2-proxy#1350]
## Expected Behavior

When using JWT tokens from OKTA with skip_jwt_bearer_tokens = true it is expected that submitting them as a `Authorization: Bearer <access_token>` header will work.

## Current Behavior

Currently this does not work as the AUD in the access token is not the client id but rather the issuer url so https://corp.okta.com

As a result, oauth2-proxy doesn't find any matching jwks validators.

As a workaround I tried to use `extra_jwt_issuers` where the issuer is https://corp.okta.com and the aud also happens to be this as that is what is present within the access tokens so `extra_jwt_issuers = https://corp.okta.com=https://corp.okta.com` however this too fails and I was unable to determine why.

## Steps to Reproduce (for bugs)

 1. Configure Oauth2-proxy against an OKTA OIDC application with skip_jwt_bearer_tokens = true.
 2. Generate a OKTA access token and submit it as an authorization: bearer header and it will fail

Alternatively, repeat step 2 using an ID token and it will pass as OKTA set the AUD in the ID token to the client ID

## Your Environment

- Version used: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3

**Comment by imduffy15** [comment]
Wont Fix: not designed to work with access tokens 👍

**Comment by JoelSpeed** [comment]
Yeah you got it, this mechanism is supposed to be for ID Tokens, and I have used this with Okta ID Tokens in the past so it should work if you set that up
