### ISSUE TITLE
Not getting x-auth-request-user, only x-auth-request-email

### ISSUE THREAD

**Issue by hstridh** [oauth2-proxy/oauth2-proxy#1351]
I'm using oauth2_proxy with Azure provider and with the following settings:
          
- name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
value: "true"
- name: OAUTH2_PROXY_PASS_ACCESS_TOKEN
 value: "true"
- name: OAUTH2_PROXY_PASS_USER_HEADERS
 value: "true"
- name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
value: "true"
- name: OAUTH2_PROXY_SET_XAUTHREQUEST

Login process works perfect, however when I browse to /oauth2/auth
I can only see "x-auth-request-email" header but not "x-auth-request-user".
Any ideas why?

## Expected Behavior
Both x-auth-request-user and x-auth-request-email available

## Current Behavior
Only x-auth-request-email available

- Version used:
oauth2-proxy:v7.1.1

**Comment by JoelSpeed** [comment]
Please check the auth logs from the users login, it may be that the user isn't being set. The logs should let you know which fields were set. If the user isn't set, the header won't be created.
