### ISSUE TITLE
JWT Middleware doesn't have enriched sessions

### ISSUE THREAD

**Issue by imduffy15** [oauth2-proxy/oauth2-proxy#1352]
## Expected Behavior

EnrichSession is called after Redeeming a token, when ProfileURL is set, oauth2-proxy will fetch an external endpoint and add additional claims such as groups and email. 

This works great as the ?group=some-group query argument can be appended to limit access to an application to a specific set of users.

However, should the user generate the JWT themselves and pass it in and get verified by the JWT middleware the token is not enriched as a result group information may be list

## Current Behavior

JWT tokens are not enriched and do not contain additional claims available in the ProfileURL

## Possible Solution

Fetch ProfileURL for JWT tokens

## Steps to Reproduce (for bugs)

1. Configure a OIDC server and generate a token, for ease this can be done with https://github.com/imduffy15/token-cli example:

```
$ token-cli target create  okta --openid-configuration-url https://corp.okta.com/.well-known/openid-configuration
$ token-cli target set okta
$ token-cli token get client_id --client_secret client_secret --scope "openid email groups profile"
```

2. Query /oauth2/userinfo on oauth2 proxy with the auth header set:

```
$ curl -H "Authorization: Bearer $(token-cli token get client_id --client_secret client_secret --scope "openid email groups profile" | jq -r ".id_token") https://oauth2-proxy/oauth2/userinfo
```

No ProfileURL claims will be present

## Context

Can't use group filtering on JWT tokens :(

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
This is expected, we only enrich sessions that we create. If you want the group filtering on tokens created externally, you need to include them within the token that you are sending to OAuth2 Proxy.

When sending the token in the header, we don't necessarily have the ability to fetch the extra information, for example you have to use the access token with some providers. Additionally, when we enrich sessions, we do that once and store it within the session, if we did it for JWT tokens, we would have to enrich every time which would increase the load on the IDP significantly and increase individual request times
