### ISSUE TITLE
Refresh cookie allowed for not existing user, OIDC + Dex

### ISSUE THREAD

**Issue by tdowgielewicz** [oauth2-proxy/oauth2-proxy#1354]
Hi all,

We are using K8s cluster with Oauth2-proxy + OIDC (DEX)  + OpenLDAP as Backend
I'm dealing with station, that removed user can perform actions even after refreshing cookie. 

For me it is a no go, but I would like to keep existing stack.

## How to reproduce:

- Login as a user
- On the other thread remove this user from LDAP
- Wait for cookie_refresh timeout
- Reload Page

## Expected Behavior
1. OAuth2Proxy try to login/refresh token from Dex
2. Cookie not validated, returns to the login page

## Actual behavior
Cookie refreshed successfully

## Your Environment
```
  oauth2_proxy.cfg: |-
    http_address="myapp-dex:5556"
    cookie_secret="secret"
    provider="oidc"
    oidc-email-claim="sub"
    email_domains="*"
    oidc_issuer_url="https://<CLUSTER_IP>/dex"
    client_secret="myapp-secret"
    client_id="myapp"
    redirect_url="https://<CLUSTER_IP>/oauth2/callback"
    upstreams="https://<CLUSTER_IP>"
    pass_authorization_header=false
    set_xauthrequest=true
    set_authorization_header=false
    session_cookie_minimal=true
    ssl_insecure_skip_verify=true
    cookie_secure=false
    skip_provider_button=true
    cookie_expire="7h0m10s" 
    cookie_refresh="0h0m5s"
```

Logs
```
│ [2021/09/06 13:16:25] [stored_session.go:122] Refreshing 46.921057012s old session cookie for Session{email:void@gmail.com user:CiNjbj12b2lkQGdtYWlsLmNvbSxkYsa1leGFtcGxlLGRjPW9yZxIEb │
│ GRhcA PreferredUsername:void@gmail.com token:true id_token:true created:2021-09-06 13:15:38.078942988 +0000 UTC expires:2021-09-07 13:15:37.078426091 +0000 UTC} (refresh after 5s)   │
│ <IP> - d02b34f7ae3e4e23a2f85b6edbfebd77 - void@gmail.com [2021/09/06 13:16:25] <IP> GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.1 │
│ 5; rv:91.0) Gecko/20100101 Firefox/91.0" 202 0 0.001

- Version used: 
- bitnami/oauth2-proxy:latest (7.1.3)


Is there a way to force Oauth2Proxy to force verify user after refresh_cookie. Is there any other way to logout/stop not existing user?

**Comment by JoelSpeed** [comment]
ID Tokens are valid for as long as they are issued, typically this is set by the identity provider, so Dex in your case. If you want to ensure that a removed user cannot access the system, you must set your token lifetime short on the Dex side.

When we refresh, we do validate that the token is still valid, but that's only done by looking at the expiry, as per the OIDC spec.

**Comment by JoelSpeed** [comment]
Are there any logs in Dex that explain why the refresh failed?

**Comment by JoelSpeed** [comment]
It looks to me like you haven't quite configured the refreshing properly. You should see `refresh:true` in the OAuth2 Proxy auth log but it's not there. You need to set the `scope` configuration to include `offline_access` to ensure that Dex returns a refresh token.
