### ISSUE TITLE
Include PKCE - Code Challenge in Proxy (2nd try)

### ISSUE THREAD

**Issue by aberhallo** [oauth2-proxy/oauth2-proxy#1361]
## Expected Behavior

For security reasons It would be nice if the PKCE extension would be included in the proxy.
https://www.oauth.com/oauth2-servers/pkce/. 

This was already requested in https://github.com/oauth2-proxy/oauth2-proxy/issues/756 but I think the discussion was not considering the latest OAuth2 spec (see https://oauth.net/2.1/): _PKCE is required for all OAuth clients using the authorization code flow_. 
That means also for confidential clients and not only for mobile and SPA clients as @etca2z stated before. So using PKCE is state of the art for me and I want to use PKCE.

```
https://YOUR_DOMAIN/authorize?
    response_type=code&
    code_challenge=CODE_CHALLENGE&
    code_challenge_method=S256&
    client_id=YOUR_CLIENT_ID&
    redirect_uri=YOUR_CALLBACK_URL&
    scope=SCOPE&
    state=STATE
```
In contrast to the code flow without PKCE  a code_challenge has to be submitted. I think this is not done currently in the code, see https://github.com/oauth2-proxy/oauth2-proxy/blob/06808704a3762de73bed1cc92b077420eb93d735/providers/util.go#L38

To follow the 2.1 spec regarding PKCE I think oauth2-proxy should handle the PKCE flow.

PS:  since I can see different abbreviations in  #756: I'm talking about PKCE - Proof Key for Code Exchange, see https://auth0.com/docs/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce. It's not related to PKCS or PKSE (?) in this context.

## Current Behavior

PKCE cannot be used for the authorization and callback request

## Possible Solution

It would be good if it could be enabled by a property.

**Comment by braunsonm** [comment]
I'd be interested in implementing this if approved. The extra query params should be ignored by any platforms that don't support PKCE yet.

**Comment by andrehaland** [comment]
Are there any updates on this? I am also interrested in using the PKCE flow since it is required by the new OAuth 2.1 spec

**Comment by JoelSpeed** [comment]
Has anyone looked at how/where this might be integrated? I'm supportive of this being done if we can find a way to do this that fits nicely and doesn't add extra complexity to our individual providers (which we are currently trying to deduplicate)

**Comment by braunsonm** [comment]
It partially could be integrated in a non-provider specific way. The first step where the challenge is initially presented in the authorization code flow can be handled in all providers here: https://github.com/oauth2-proxy/oauth2-proxy/blob/fd5e23e1c55ec99f552321a317770015a4b788e1/providers/util.go#L38

The token exchange would have to be provider specific in the current codebase it seems. If you're interested in splitting this out to not be provider specific then we could consider moving some of the auth code exchange into util?

**Comment by braunsonm** [comment]
Bump

**Comment by 59977** [comment]
Hi! Is there any progress on this? 

We are also looking into this and are willing to help with implementing something along the lines @braunsonm is suggesting.

**Comment by JoelSpeed** [comment]
I don't think the maintainers have any time to work on this at the moment, so if you have the time to investigate further and put together a PR that would be appreciated

**Comment by ishchatul** [comment]
Would be amazing to have this feature

**Comment by phllpmcphrsn** [comment]
Where in the code does the proxy send the access token request? I'm trying to see where I could possibly place some code for the portion of PKCE Flow where the code verifier is sent to the authz server (i.e. keycloak) with the authorization code

**Comment by phllpmcphrsn** [comment]
Hey so I've done something like this thus far (using an adapted version of this [code](https://github.com/nirasan/go-oauth-pkce-code-verifier - I just placed it under pkg/util) for the verifier :
```go
func makeLoginURL(p *ProviderData, redirectURI, state string, extraParams url.Values) url.URL {
	a := *p.LoginURL
	params, _ := url.ParseQuery(a.RawQuery)
	params.Set("redirect_uri", redirectURI)
	if p.AcrValues != "" {
		params.Add("acr_values", p.AcrValues)
	}
	if p.Prompt != "" {
		params.Set("prompt", p.Prompt)
	} else { // Legacy variant of the prompt param:
		params.Set("approval_prompt", p.ApprovalPrompt)
	}
	params.Add("scope", p.Scope)
	params.Set("client_id", p.ClientID)
	params.Set("response_type", "code")

	// initialize the code verifier
	codeVerifier, _ := verifier.CreateCodeVerifier()

	// create code_challenge with S256 method
	codeChallenge := codeVerifier.CodeChallengeS256()

	params.Set("code_challenge", codeChallenge)
	params.Set("code_challenge_method", "S256")
	params.Add("state", state)
	for n, p := range extraParams {
		for _, v := range p {
			params.Add(n, v)
		}
	}
	a.RawQuery = params.Encode()
	return a
}
```
I see where in each provider they implement Redeem which seems to perform the Access Token Request, and I assume this is where we'd need to also send along the (PKCE) code-verifier to the provider. I will say that after looking into this more, I'm thinking the code-verifier actually needs to be moved out to oauthproxy.go so that it can be provided to authorization code redemption functions. For instance, maybe the verifier is created in OAuthStart and provided in the provider's GetLoginURL; then later on oauthproxy.go can use that verifier in the redeemCode method. The latter portion would require the Provider interface to be updated to handle the code-verifier, I would assume.

Does that sound at all viable?

**Comment by braunsonm** [comment]
Just a heads up @phllpmcphrsn that my PR addresses this issue

**Comment by heiniham** [comment]
is it still required to send client-secret even after pkce is enabled?

**Comment by braunsonm** [comment]
> is it still required to send client-secret even after pkce is enabled?

For confidential clients yes.

**Comment by heiniham** [comment]
here while deploying oauth2-proxy docker image it is mandated to pass client-id, client-secret and email domains setting so will it differentiate if PKCE is enabled and ignore client-secret?
