### ISSUE TITLE
Restrict groups - oidc provider azure

### ISSUE THREAD

**Issue by imarkvisser** [oauth2-proxy/oauth2-proxy#1363]
Hello, I don't have an issue but do have a question;

We are using the oauth2-proxy oidc provider to authenticate against Azure.
Is it possible to restrict logins to specific azure groups? It doesn't seem so, but just would like confirmation.

Thanks for your time.

**Comment by avwsolutions** [comment]
Indeed. Same here. Suppose --oidc-groups-claim  could be used ? We tried that without succes ;( 

Would be  great to have answer. or an example that works

**Comment by avwsolutions** [comment]
Can help out here @JoelSpeed ?

**Comment by JoelSpeed** [comment]
The Azure provider doesn't presently have group restrictions implemented. But the OIDC provider does and I think it works with Azure as well

**Comment by avwsolutions** [comment]
Hi @JoelSpeed  thanks for your quick response. We are using oauth2-proxy within our AKS clusters. Currently we use the config below that works well for user authentication of our tools through Azure(AD) with oidc.  But we also want to add / use the group validation. For example members of group "admin" are only allowed. We tried things here (like the var OAUTH2_PROXY_ALLOWED_GROUPS mentioned here #807 ) , but without succes. 

Looks like we oversee something how to configure it correctly ?
We tried --allowed-group and --oidc-groups-claim , which  we think the last one is correct ?

Could you give us a hint how to configure this from oauth2-proxy perspective ?

Below our deployment manifest snippet (container start config) .

`      containers:
      - env:
        - name: OAUTH2_PROXY_PROVIDER
          value: oidc
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: https://login.microsoftonline.com/a6b169f1-xxxx-0000-8f33-8db8903003c7/v2.0
        - name: OAUTH2_PROXY_SESSION_COOKIE_MINIMAL
          value: "true"
        - name: OAUTH2_PROXY_AZURE_TENANT
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-azure-tenant
              key: oauth2_proxy_azure_tenant
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-azure-client-id
              key: oauth2_proxy_client_id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-azure-client-secret
              key: oauth2_proxy_azure_client_secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-cookie-secret
              key: oauth2_proxy_cookie_secret
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: '*'
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: 0.0.0.0:4180
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
`
We use the following annotations our protected ingress.

`
nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
`

**Comment by Purneau** [comment]
Did you guys manage to make any progress on this? If yes, I’d be very interested to know how.

**Comment by avwsolutions** [comment]
Not yet  :/ . Really open for suggestions on this topic.

**Comment by Purneau** [comment]
So, based on all kinds of posts and StackOverflow articles, I'm now at a point where my setup is working, sometimes.
However, I'm not sure yet whether the failures are due to my setup or the application that I'm trying to expose (it does some weird XHRStream/HTTP long poll things). So here is what I have so far, based on other comments on this forum:

```
/usr/local/bin/oauth2-proxy --config=/etc/oauth2-proxy.cfg --azure-tenant=<tenant_id> --provider=oidc --oidc-issuer-url=https://sts.windows.net/<tenant_id>/ --logging-filename=/tmp/oauth_log_test --show-debug-on-error=true --errors-to-info-log --allowed-group="<group_object_uuid>" --skip-oidc-discovery=true --login-url=https://login.windows.net/<tenant_id>/oauth2/authorize?resource=https%3A%2F%2Fgraph.microsoft.com --redeem-url=https://login.windows.net/<tenant_id>/oauth2/token --oidc-jwks-url=https://login.windows.net/common/discovery/keys --profile-url=https://graph.microsoft.com/v1.0/me --user-id-claim=userPrincipalName --scope="openid profile email groups" --standard-logging --auth-logging --request-logging
```

/etc/oauth2-proxy.cfg
```
## OAuth2 Proxy Config File
## https://github.com/oauth2-proxy/oauth2-proxy

## <addr>:<port> to listen on for HTTP/HTTPS clients
http_address = ":4180"
# https_address = ":443"

## Are we running behind a reverse proxy? Will not accept headers like X-Real-Ip unless this is set.
# reverse_proxy = true

## TLS Settings
# tls_cert_file = ""
# tls_key_file = ""

## the OAuth Redirect URL.
# defaults to the "https://" + requested host header + "/oauth2/callback"
redirect_url = "https://<app_domain>/oauth2/callback"

## the http url(s) of the upstream endpoint. If multiple, routing is based on path
upstreams = [
    "http://127.0.0.1:8888/"
]

## Logging configuration
#logging_filename = ""
#logging_max_size = 100
#logging_max_age = 7
#logging_local_time = true
#logging_compress = false
#standard_logging = true
#standard_logging_format = "[{{.Timestamp}}] [{{.File}}] {{.Message}}"
#request_logging = true
#request_logging_format = "{{.Client}} - {{.Username}} [{{.Timestamp}}] {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}"
#auth_logging = true
#auth_logging_format = "{{.Client}} - {{.Username}} [{{.Timestamp}}] [{{.Status}}] {{.Message}}"

## pass HTTP Basic Auth, X-Forwarded-User and X-Forwarded-Email information to upstream
# pass_basic_auth = true
# pass_user_headers = true
## pass the request Host Header to upstream
## when disabled the upstream Host is used as the Host Header
# pass_host_header = true

## Email Domains to allow authentication for (this authorizes any email on this domain)
## for more granular authorization use `authenticated_emails_file`
## To authorize any email addresses use "*"
email_domains = [
    "<company_domain>"
]

## The OAuth Client ID, Secret
client_id = "<client_id>"
client_secret = "<client_secret>"

## Pass OAuth Access token to upstream via "X-Forwarded-Access-Token"
# pass_access_token = false

## Authenticated Email Addresses File (one email per line)
# authenticated_emails_file = ""

## Htpasswd File (optional)
## Additionally authenticate against a htpasswd file. Entries must be created with "htpasswd -B" for bcrypt encryption
## enabling exposes a username/login signin form
# htpasswd_file = ""

## bypass authentication for requests that match the method & path. Format: method=path_regex OR path_regex alone for all methods
# skip_auth_routes = [
#   "GET=^/probe",
#   "^/metrics"
# ]

## Templates
## optional directory with custom sign_in.html and error.html
# custom_templates_dir = ""

## skip SSL checking for HTTPS requests
# ssl_insecure_skip_verify = false


## Cookie Settings
## Name     - the cookie name
## Secret   - the seed string for secure cookies; should be 16, 24, or 32 bytes
##            for use with an AES cipher when cookie_refresh or pass_access_token
##            is set
## Domain   - (optional) cookie domain to force cookies to (ie: .yourcompany.com)
## Expire   - (duration) expire timeframe for cookie
## Refresh  - (duration) refresh the cookie when duration has elapsed after cookie was initially set.
##            Should be less than cookie_expire; set to 0 to disable.
##            On refresh, OAuth token is re-validated.
##            (ie: 1h means tokens are refreshed on request 1hr+ after it was set)
## Secure   - secure cookies are only sent by the browser of a HTTPS connection (recommended)
## HttpOnly - httponly cookies are not readable by javascript (recommended)
cookie_name = "_oauth2_proxy"
cookie_secret = "<something nice>"
# cookie_domains = ""
# cookie_expire = "168h"
# cookie_refresh = ""
# cookie_secure = true
# cookie_httponly = true
```

Based on the logging all looks fine (authorized messages); I do however see some warnings related to the cookie size (too big), it's probably due to the fact that our users are part of too many groups.

**Comment by avwsolutions** [comment]
@Purneau how did you configured your app-registrations for this ?

**Comment by Purneau** [comment]
I think the important parts are: 
```
	"accessTokenAcceptedVersion": 2,
```

and Application permissions and delegated permissions for:
```
Microsoft Graph:
- Directory.Read.All
```

**Comment by thomastvedt** [comment]
> Just got this working with Azure using the OIDC provider (not azure provider), using the command line --allowed-group="test" instead of allowed_group="test" in the cfg

What does your setup look like? args to oauth2?

**Comment by benedikt-mue** [comment]
I got it to work as well (with the help of @RichardTheHouse), with
cfg file:
```
email_domains = [ "*" ]
upstreams = [ "file:///dev/null" ]
oidc_groups_claim = "my_custom_group"
```

runtime args to oath2:
```
  --oidc-email-claim: "mail"
  --oidc-email-claim: email
  --allowed-group: "admin"
  --scope: "openid my_custom_group"
  --whitelist-domain: .service.myapp.net
  --cookie-domain: service.myapp.net
```

version `v7.3.0`

**Comment by bmgante** [comment]
Hi @benedikt-mue 

need some guidance on how to limit oauth2-proxy (v7.3.0) to specific azure ad groups:

This is my spec:
    spec:
      containers:
      - args:
        - --provider=oidc
        - --user-id-claim=oid
        - --cookie-expire=12h
        - --azure-tenant=xxxxx
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --oidc-issuer-url=https://login.microsoftonline.com/xxxxxx/v2.0 # replace with your tenant id
        - --allowed-group="Observability Admin"
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: xxx
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: xxx
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: xxx
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

In azure ad application i´ve added that group to Users and Groups as per snapshot below and also added the entry below in the app manifest, however keep getting 403 forbidden when trying to login. Can someone please provide some guidance on how to achieve the expected result?


"groupMembershipClaims": null,  ---> "groupMembershipClaims": "ApplicationGroup, SecurityGroup"

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/27358817/39669b19-b8c2-4962-96ae-54c509a55e92)

Many thanks

**Comment by bmgante** [comment]
@benedikt-mue could you please provide some further details on your setup?
What is exactly my_custom_group? How did you configured your application in azure ad?
Thanks

**Comment by Alexander-ac** [comment]
You can make it with roles concept:

oidc_groups_claim = "roles"
allowed_groups = ["list", "of", "allowed", "roles"]

**Comment by danieldietrichriverty** [comment]
Thanks everybody for you information, it helped me to get it working with the use of only one AppRegistration and Application Roles.

The settings i use are:
`        provider = "oidc" 
        skip_oidc_discovery = "true" 
        oidc_issuer_url = "https://login.microsoftonline.com/<tenant-id>/v2.0" 
        login_url = "https://login.windows.net/<tenant-id>/oauth2/authorize?resource=https%3A%2F%2Fgraph.microsoft.com" 
        redeem_url = "https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token" 
        oidc_jwks_url = "https://login.microsoftonline.com/<tenant-id>/discovery/v2.0/keys" 
        profile_url = "https://graph.microsoft.com/v1.0/me"
        user_id_claim = "userPrincipalName" 
        scope = "openid profile email" 
        allowed_groups = [ "<app role name>" ]
        oidc_groups_claim = "roles"`

with this setup you can map different User Groups to the checked AppRole in the azure enterprise application configuration and so you are very flexible. And there also no size problems of the token if a user is in many groups.

**Comment by satyamkapoor** [comment]
@danieldietrichriverty is there an option to use it without app roles?

**Comment by danieldietrichriverty** [comment]
@satyamkapoor sorry, i don't know. 
should be possible to map groups to the token (https://learn.microsoft.com/en-us/security/zero-trust/develop/configure-tokens-group-claims-app-roles) and then oauth proxy could check on that as "oidc_groups_claim". But i never tried this, because app roles are the better solution in my use case.

**Comment by danny-sevaro** [comment]
I successfully configured OAuth2 Proxy using Azure as the provider with allowed groups working. 

## 1. Add Group Claims in the Azure Application  
To get started, you need to configure your Azure application to include group claims in the token:  

- Navigate to your Azure application settings.  
- Go to **Token Configuration** and add the **Groups** claim.  
- Ensure the following API permissions are enabled and also consent is granted org wide:  
  - **Group.Read.All** (Application type)
  - **User.Read** (Delegated type)  

## 2. Configure Environment Variables  
Next, set up the required environment variables for OAuth2 Proxy in your application:  

```
OAUTH2_PROXY_PROVIDER=azure  
OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/<tenant-id>/v2.0  
OAUTH2_PROXY_OIDC_GROUPS_CLAIM=groups  
OAUTH2_PROXY_ALLOWED_GROUPS=<group-id>  # Example comma seperated ids: 7c28ace6-e537-4d13-867d-ce822422fa7f,7c28ace6-e537-4d13-867d-ce822422fa90  
OAUTH2_PROXY_AZURE_GRAPH_GROUP_FIELD=id  # id is the default
```
Replace <tenant-id> with your Azure AD tenant ID and <group-id> with the desired Azure AD group ID.

If you'd prefer to use group names rather than group IDs, update the following environment variables:
```
OAUTH2_PROXY_AZURE_GRAPH_GROUP_FIELD=displayName
OAUTH2_PROXY_ALLOWED_GROUPS="External Developer"
```

I was able to retrieve all the configuration variables running the below command.
`docker run --rm quay.io/oauth2-proxy/oauth2-proxy:v7.7.1 --help`
