### ISSUE TITLE
kubernetes samples are broken

### ISSUE THREAD

**Issue by mr-ma** [oauth2-proxy/oauth2-proxy#1365]
I am trying to follow the instructions provided (here)[https://github.com/oauth2-proxy/oauth2-proxy/tree/master/contrib/local-environment/kubernetes] to run the kubernetes example. 

I ran into a problem while attempting to run the sample.
The dex pod kept crashing. 

## Expected Behavior

The example should work with no problem whatsoever.

## Current Behavior

The dex controller keeps crashing.

## Possible Solution

Turned out that for newer versions of kubernetes one has to set the `env` section in the deployment file as below:
```bash
--- a/contrib/local-environment/kubernetes/oauth2-proxy-example-full.yaml
+++ b/contrib/local-environment/kubernetes/oauth2-proxy-example-full.yaml
@@ -294,7 +294,10 @@ spec:
           timeoutSeconds: 1
           failureThreshold: 1
         env:
-          []
+          - name: KUBERNETES_POD_NAMESPACE
+            valueFrom:
+              fieldRef:
+                fieldPath: metadata.namespace
         volumeMounts:
         - mountPath: /etc/dex/cfg
           name: config
```
## Steps to Reproduce (for bugs)
```bash
git clone https://github.com/oauth2-proxy/oauth2-proxy.git
cd contrib/local-environment/kubernetes
make create-cluster
make deploy

```

### Version used: 
- MacOS Big Sur 11.4
- kind v0.11.1 go1.16.4 darwin/amd64

**Comment by JoelSpeed** [comment]
Have you got Dex logs that explain why it was crashing? Would be good to verify why exactly we need this extra environment variable setting

I was under the impression this was always injected into pods, maybe they've removed that in later versions 🤔

**Comment by mr-ma** [comment]
here is the error:
```
time="2021-09-15T22:03:13Z" level=info msg="config using log level: debug"
time="2021-09-15T22:03:13Z" level=info msg="config issuer: http://dex.localtest.me"
failed to initialize storage: failed to inspect service account token: jwt claim "kubernetes.io/serviceaccount/namespace" not found
```
Here is a relevant [issue](https://github.com/kubeflow/manifests/issues/1882)

**Comment by JoelSpeed** [comment]
[This thread](https://github.com/dexidp/dex/issues/2082#issuecomment-818124478) on Dex's repo has an explanation of the issue, it's because of a new feature `BoundServiceAccountTokenVolume`. I think we can apply the workaround as you've suggested in the description of this issue, thanks for bringing this to our attention
