### ISSUE TITLE
Tokens are not getting refreshed after session expiry

### ISSUE THREAD

**Issue by puneetbabbar26** [oauth2-proxy/oauth2-proxy#1366]
## Expected Behavior
We use oauth2_proxy configured with OKTA and were trying to upgrade from version `5.1.0` to the latest `7.1.3`

On 5.1.0 when the access_token expires, the proxy is able to use the refresh_token to get another access_token

the following excerpt from the logs should clarify the behaviour

> [2021/09/15 06:21:42] [oauthproxy.go:888] Removing session: token expired Session{email:blah@blah user:00u6os9oxnNZ4GJa52p7 PreferredUsername:blah@blah.org token:true id_token:true created:2021-09-15 06:10:27.527610335 +0000 UTC expires:2021-09-15 06:15:27.527395258 +0000 UTC}
172.17.0.1 - - [2021/09/15 06:21:42] localhost:4180 GET - "/whoIs" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" 302 331 0.000
172.17.0.1 - blah@blah [2021/09/15 06:21:43] [AuthSuccess] Authenticated via OAuth2: Session{email:blah@blah user:00u6os9oxnNZ4GJa52p7 PreferredUsername:blah@blah.org token:true id_token:true created:2021-09-15 06:21:43.856359961 +0000 UTC m=+11.122179418 expires:2021-09-15 06:26:43.522326926 +0000 UTC m=+310.788146397}
172.17.0.1 - - [2021/09/15 06:21:43] localhost:4180 GET - "/oauth2/callback?code=NHiy4gQgFlVw_ADfRbEsZhwdUbtCbi_DzAv3raoBLZ8&state=bcdb92bdb2f5cb56b5d6c6e505028c05%3A%2FwhoIs" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" 302 29 0.732

## Current Behavior

With `7.1.3` when the session expires, the proxy doesn't validate the token and simply passes it upstream to be handled by the upstream API, which can call the token as expired and return 401, but the token just doesn't get refreshed since the proxy doesn't care about the expiry or the 401 return.

> 172.17.0.1 - 6de7027c-d016-4467-a8b3-e0f747ace9f5 - blah@blah [2021/09/15 05:33:35] localhost:4180 GET / "/whoIs" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" 401 0 0.045

## Possible Solution

Not sure if this is an intended behaviour change to the proxy with the major version change (not sure why would this useful feature be ignored).
I would request you to either suggest the right configuration that I need to do ( I am still scratching my head on how to getthe refresh behavior to work) or possibly add back the functionality as it worked in `5.1.0`

## Steps to Reproduce (for bugs)

Use the docker image for `7.1.3`
Set a short TTL for `access_token` on OKTA, say 5 mins.
Login for an APP and try to access the app again after 5 mins.

## Context

Caused a widespread outage in production after the upgrade. As soon as the `access_token` for logged in users got expired, they couldn't use the app anymore.

## Your Environment
OAuth provider OKTA
We are using oauth2-proxy with redis

Here's how we configure the proxy to run on k8s
> OAUTH2_PROXY_EMAIL_DOMAINS: "*"
OAUTH2_PROXY_COOKIE_SECURE: "false"
OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
OAUTH2_PROXY_PASS_BASIC_AUTH: "false"
OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
OAUTH2_PROXY_PASS_HOST_HEADER: "true"
OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
OAUTH2_PROXY_HTTPS_ADDRESS: "0.0.0.0:443"
OAUTH2_PROXY_REVERSE_PROXY: "true"
OAUTH2_PROXY_REAL_CLIENT_IP_HEADER: "X-Forwarded-For"
OAUTH2_PROXY_PASS_USER_HEADERS: "false"
OAUTH2_PROXY_PASS_BASIC_AUTH: "false"
OAUTH2_PROXY_SESSION_STORE_TYPE: "redis"
OAUTH2_PROXY_REDIS_CONNECTION_URL: "redis://{{ template "oauth2-proxy.fullname" . }}-redis:6379"
OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY: "true"
OAUTH2_PROXY_PROVIDER: "oidc"
OAUTH2_PROXY_OIDC_ISSUER_URL: "{{ .Values.configuration.oauth.issuer | quote }}"
OAUTH2_PROXY_SCOPE: "openid offline_access email profile"
OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.configuration.proxy.cookieSecret | quote }}
OAUTH2_PROXY_REDIRECT_URL: "https://{{ .Release.Namespace }}.blah/oauth2/callback"
OAUTH2_PROXY_UPSTREAMS: {{ required ".Values.configuration.proxy.upstream to be set" .Values.configuration.proxy.upstream | quote }}
OAUTH2_PROXY_CLIENT_ID: blah
OAUTH2_PROXY_CLIENT_SECRET: blah
- Version used: 7.1.3 (Docker image)

**Comment by JoelSpeed** [comment]
Have you tried setting the cookie-refresh option? Looks to me from the previous logs that in fact we aren't doing a refresh but in fact, just a full new login (by hitting the callback). I think we made some changes that mean the session can be allowed to live forever even with an invalid token, and it's up to the user to determine whether this is appropriate or not. For this use case, I suspect the issue is you haven't got cookie refresh configured, if you set this to the same as your token lifetime, it should attempt to refresh after a few minutes and you should be good to go again
