### ISSUE TITLE
Automatic redirect to IdP from sign_out endpoint

### ISSUE THREAD

**Issue by sgrimm** [oauth2-proxy/oauth2-proxy#1368]
## Expected Behavior

Clients should be able to sign out of a web app without knowing the details of the IdP's URL structure, similar to the way they log in by just trying to fetch an app URL and OAuth2 Proxy automatically redirects them to the right place.

## Current Behavior

The sign out URL has to be explicitly constructed (either on the client side or in server-side application code) with appropriate query string parameters. This can end up looking pretty hairy if you want the user to end up back on a "you're logged out" page on the app domain (leaving out the URL encoding here for clarity, and using Keycloak for the IdP):

`https://app.example.com/oauth2/sign_out?rd=https://idp.example.com/auth/realms/example_app/openid-connect/logout?redirect_uri=https://app.example.com/static/logged_out.html`

## Possible Solution

Add a configuration option to set the default redirect URL for the `/oauth2/sign_out` endpoint.

A basic implementation (which would solve the problem) would give you a way to specify the whole URL, something like

```shell
oauth2-proxy --logout-redirect-url \
  'https://idp.example.com/auth/realms/example_app/openid-connect/logout?redirect_uri=https://app.example.com/static/logged_out.html'
```

A nicer variant for OIDC-style IdPs would be to take advantage of the fact that the discovery document already has the IdP logout URL and that OAuth2 Proxy already knows the web app's scheme+hostname, so you could do

```shell
oauth2-proxy --oidc-logout-redirect-url /static/logged_out.html
```

to get the same end result as above. With this in place, clients just need to navigate to `https://app.example.com/oauth2/sign_out`, and the details of the signout process are taken care of by the proxy.

## Context

Our front end team came to me and said, "We're adding the 'log out' button. What URL should it fetch?" and I realized that constructing the URL would require the application code to know how to construct a Keycloak logout URL. Thanks to OAuth2 Proxy, the application is otherwise unaware of the fact that Keycloak even exists in our infrastructure; all the mechanics of logging in are abstracted away nicely.

## Your Environment

- Version used: 7.1.3

**Comment by gboor** [comment]
I am also very interested in this. I currently have a deployment that I deploy with oauth2-proxy as a sidecar in 2 different contexts with 2 different IdP's. While the config works just fine, making the logout work is tricky. It would be a lot nicer if that can be in the configuration as well, so I can change it per deployment instead of pulling all kinds of tricks in the front-end.

**Comment by JoelSpeed** [comment]
Could you take a look at #1224 please, I think this may be covered already under that issue

**Comment by alexisgaziello** [comment]
See my answer in https://github.com/oauth2-proxy/oauth2-proxy/issues/1224#issuecomment-1034123738

Solves the q.
