### ISSUE TITLE
email-domain validation failing

### ISSUE THREAD

**Issue by korporationcl** [oauth2-proxy/oauth2-proxy#1374]
Hi, I am using oauth2-proxy (7.1.3) running in Kubernetes (helm chart) and I just made a change on the `email-domain' field from "*" to:

```
email-domain:
  - "domain1.com"
  - "domain2.com"
```

this broke my current setup, unexpectedly of course, but my understanding is this shouldn't have caused an error:

```
[AuthFailure] Invalid authentication via OAuth2: unauthorized
```

To make sure, my user is valid and belongs to the `domain1.com` organisation (domain).  The helm chart rendered the following configuration:

```
--email-domain=[domain1.com domain2.com] 
```

Note: I edited the values to avoid issues.

## Expected Behavior

I would expect users that belong to both domains get access to the service behind since they are valid users. 

## Current Behavior

Instead am getting the error:

```
[AuthFailure] Invalid authentication via OAuth2: unauthorized
```

Visually you get the following error on the browser:

```
You do not have permission to access this resource.
Request ID: aasdasdsadsad
```
## Possible Solution

Clarify if this issue is a bug or just a lack of understanding about how to properly setup this value.

## Steps to Reproduce (for bugs)

I use Okta to validate my users but I belong to the `domain1.com` Organisation and the way of reproducing this is changing the `email-domain: *` to `email-domain: [domain1.com domain2.com]`

## Context

We are rolling out an identity provider solution and not everyone belongs to the company. We want to add an extra layer of control on the oauth2-proxy level.

## Your Environment

oauth2-proxy 7.1.3, running in kubernetes (using the helm chart).

**Comment by JoelSpeed** [comment]
Could you try manually editing the rendered config to try `--email-domain=domain1.com --email-domain=domain2.com`, I think the issue is that these should be rendered separately

**Comment by korporationcl** [comment]
Sorry I just had some time to test this, I added in the helm chart:

```
extraArgs:
    email-domain: "domain1com"
    email-domain: "domain2.com"
```

but this only rendered one entry:

```
--http-address=0.0.0.0:4180 --metrics-address=0.0.0.0:44180 --cookie-domain=.xxx --email-domain=domain1.com --oidc-issuer-url=xxxxxx --pass-access-token=true --provider=oidc --provider-display-name=Okta --redirect-url=xxxx --set-authorization-header=true --set-xauthrequest=true --skip-provider-button=true --whitelist-domain=.internal --config=/etc/oauth2_proxy/oauth2_proxy.cfg
```

I had to actually disable one rule in my linter to make this happen otherwise won't pass the validation for yaml.

**Comment by JoelSpeed** [comment]
Sorry, my suggestion was actually to edit the rendered output to put the two emails in separately. I don't maintain or use helm so I can't really help you with that aspect (but others can), but I think the issue is that the flag needs to be rendered twice, separately. If you can verify that they need to be rendered separately and this works for your use case, I'd suggest raising an issue against the helm chart directly
