### ISSUE TITLE
incorrect docs: OAUTH2_PROXY_UPSTREAM	vs OAUTH2_PROXY_UPSTREAMS

### ISSUE THREAD

**Issue by Ashtonian** [oauth2-proxy/oauth2-proxy#1377]
## Expected Behavior

The docs to be accurate. 

## Current Behavior

The docs say args can be passed as env variables by adding `OAUTH2_PROXY_` prefix. The [table](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview) listing all the config flags lists `--upstream` and makes no mention of `--upstreams`. This implies that the correct env variable is `OAUTH2_PROXY_UPSTREAM` but this does not work and should be `OAUTH2_PROXY_UPSTREAMS`

**Comment by JoelSpeed** [comment]
To quote the docs:

> Every command line argument can be specified as an environment variable by prefixing it with OAUTH2_PROXY_, capitalising it, and replacing hyphens (-) with underscores (_). **If the argument can be specified multiple times, the environment variable should be plural (trailing S).**

The second sentence here is important and explains that the `--upstream`argument would turn into `OAUTH2_PROXY_UPSTREAMS`.

I appreciate this is an annoying convention but it's a convention that predates all of the current maintainers. We plan to resolve it at some point with our new structured configuration.

**Comment by Ashtonian** [comment]
Missed that, thanks. I don't the convention is the worst, I just think this should be more explicitly stated and clear. Alternatively a clearer behavior when there is no upstream configured. Right now its just a 404 and with no logs. Maybe the default 404 could be more informative "404 no upstream provided". Or a log "no upstream provided" - I'm using the helm chart for this which looks to have a default set.

**Comment by JoelSpeed** [comment]
> Alternatively a clearer behavior when there is no upstream configured. 

I was under the impression we required there to be at least one upstream, but maybe we broke that 🤔 

> I don't the convention is the worst, I just think this should be more explicitly stated and clear.

I'll have a think about how we can make this more obvious, we have the ability to create big bright warning boxes on the docs pages, perhaps highlighting it in one of those could make it more obvious

**Comment by Ashtonian** [comment]
I'm using the [helm](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml#L25) chart which looks to be setting upstream to file null.

> we have the ability to create big bright warning boxes on the docs pages, perhaps highlighting it in one of those could make it more obvious
I like big bright warnings :)
