### ISSUE TITLE
Feature Request - Allow requests with bearer tokens in addition to session cookies

### ISSUE THREAD

**Issue by mattharrigan** [oauth2-proxy/oauth2-proxy#1380]
## Expected Behavior

If an incoming request has a valid JWT auth bearer token, but no session cookie, have an optional configuration setting that will allow the request to pass.

## Current Behavior

Session cookies are strictly required

## Context

Sometimes an app needs to be used other than from a single web application. Perhaps there is a need to obtain a JWT using a client credentials grant and use it in requests. Perhaps app A needs to make requests to app B, where each is nominally secured by a different oauth2-proxy instance (different secrets, client IDs, etc), and app A attaches a valid JWT to the requests to app B.

Thank you

**Comment by JoelSpeed** [comment]
This is already available! Checkout the `--skip-jwt-bearer-tokens` and `--extra-jwt-issuers` options from our docs. We expect an authorization header with the JWT present, and from there we can allow the request through

**Comment by mattharrigan** [comment]
I missed that option. Sorry for the bad issue. Thanks for already having that feature.
