### ISSUE TITLE
Browser Back-Button shows 403 after successfull login  

### ISSUE THREAD

**Issue by hakimsabery** [oauth2-proxy/oauth2-proxy#1387]
# After Successful login user clicks the Back-Button in the browser but oauth2-proxy shows 403 Forbidden. I looking for a better solution or one of following.

1. redirect back to last page 
2. show login page again

![image](https://user-images.githubusercontent.com/55178187/135439855-ec564f59-7627-465d-bfda-5ccfdc2e2a47.png)

**Comment by JoelSpeed** [comment]
By clicking the back button, you are sending the user back to the OAuth2 Proxy callback endpoint, when you hit this without providing the right information, it's right that it returns a 403.

Why is your user hitting back?

What are you expecting the behaviour to be?

**Comment by hakimsabery** [comment]
> Why is your user hitting back?

Because it is foreseen scenario. A user would go back to comming page or last Browser history.

> 
> What are you expecting the behaviour to be?

I am expecting something like "You are already signed in" etc.
