### ISSUE TITLE
Feature request: access token verification with mandatory scopes

### ISSUE THREAD

**Issue by irizzant** [oauth2-proxy/oauth2-proxy#1389]
## Expected Behavior

Currently you can use `skip_jwt_bearer_tokens` to **enable** access token verfication and specify a list of `extra_jwt_issuers` to verify ID tokens.
There should be a flag `required-scopes` that one could supply in order to specify a list of mandatory scopes that should be available in the access token.

## Current Behavior

Currently, only `--scope` is available to request some specific scopes from the provider but there is no way to specify which scopes are mandatory.

**Comment by JoelSpeed** [comment]
> Maybe it works and it shouldn't, in any case access token validation should be used instead of ID tokens for service-to-service communications so it's still worth it as a feature.

Could you elaborate on this for me please, why should access token validation be used for M2M calls over an ID Token?

**Comment by irizzant** [comment]
For a number of reasons. 
ID tokens are meant for authentication, access token are meant for authorization.

In service-to-service communications, e.g when you want to consume an API from a service, you want to **authorize** a service to consume the API, you don't care about profiles, email addresses, or identity concerns.
If your API accepts an ID token as an authorization token, to begin with, you are ignoring the intended recipient stated by the audience claim. That claim says that it is meant for your client application, not for the resource server (i.e., the API).
On the contrary an access token's `aud` claim states it's intended for a resource server.
You may think this is just a formality, but there are security implications here.

First of all, among other validation checks, your API shouldn’t accept a token that is not meant for it. If it does, its security is at risk. In fact, if your API doesn't care if a token is meant for it, an ID token stolen from any client application can be used to access your API. 

In addition, your ID token will not have granted scopes, which is what prevents unauthorized access to resources.

**Comment by JoelSpeed** [comment]
I think using ID Tokens for service to service communication is still valid. An ID token is used to identify something, that could be a person or a thing. The ID Token does not contain any authorization information as you have said.

It is up to some other service to map the user to to the authorization that they have.

This is a different model to what you are proposing, but I believe an entirely valid way to have your authentication and authorization implemented in different services. For example, Kubernetes is a well known system that implements this. Service accounts for pods have signed ID Tokens, these identify the workload to the API server while the RBAC system sets the authorization.

Our project primarily focuses on the Authentication part of this dance and as such, our extra issuers configuration is intended to be used for ID Tokens and not access tokens. Having a required scopes options wouldn't make sense when validating ID Tokens so I wouldn't want to add that in to that part of the proxy.

**Comment by irizzant** [comment]
You said it yourself, ID tokens are not enough for service to service communication unless you use some other service to perform the authorization part.

First of all this means basically doubling the steps needed for an API call.
I as an API owner have to check that you have been authenticated to understand which authorization policy I have to apply to you and you as an API consumer have to first authenticate, store the ID token somewhere safe, then perform the real API call.
Moreover, you have to manage the ID token expiration/renewal and if you don't adding the ID token in this scenario doesn't really pay you anything back.
This is not reasonable and also not always feasible.

In addition, using the ID token this way adds the security problems I have already described: a stolen ID token would not only allow any client to gain the defined access policy and invoke API they don't have access to, but could also be used to act as an authenticated user for a website that accepts ID tokens for logins. 
OAuth2 access tokens are not subject to this issue.

The Kubernetes example you provided doesn't really fit a general service to service communication.
Kubernetes manages ID tokens associated to Service Accounts by mounting volumes into Pods and it does all the orchestration needed to manage this itself.
It's a kind of internally manged process that requires no additional steps for Pods to be able to consume Kubernetes API.
This is why Service Accounts are meant to be used as an authentication mechanism internal to the cluster and their associated should never leave the cluster realm.

That being said, I still don't agree that ID tokens can replace access tokens for service to service communications, but if Oauth2 Proxy is not meant to support access token verification at the moment it's ok for me, that is still a nice to have feature request

**Comment by irizzant** [comment]
activity
