### ISSUE TITLE
500 Internal Server error after auth with Azure (coming from nginx 1.19 ingress controller?)

### ISSUE THREAD

**Issue by robertocamp** [oauth2-proxy/oauth2-proxy#1390]
## Summary:
I am trying to get a k8s application working behind an Oauth2 proxy. The provider is Azure and the k8s is an interal (non-cloud) data center cluster.

## Expected Behavior
1. client connects to URL in browser
2. Oauth2 splash page with "Sign in with Azure" message
3. Authenticate via MFA with Azure
4. get re-directed to the app page 

## Current Behavior
1. client connects to URL in browser-OK
2. Oauth2 splash page with "Sign in with Azure" message-OK
3. Authenticate via MFA with Azure-OK (I see the auth request and I use my phone to authenticate)
4. get re-directed to the app page-500 Internal Server Error, with debug enabled:  (see below [2021/10/03 18:21:38] timestamp)
5. seems like authentication is fine but the the oauth2 is not redirecting to the actual requested page?

This is what I am seeing in the  oauth2 container logs (and the debug on the 500 Internal web page):
[2021/10/03 18:21:38] [oauthproxy.go:748] Error redeeming code during OAuth2 callback: unexpected status "401": {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 9c36a6d9-236e-4de0-8d86-"error_uri":"https://login.microsoftonline.com/error?[2021/10/03 18:21:38] application.internal.com GET - "/oauth2/callback?code=<REDACTED> HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" 500 3362 0.542

## configuration:
interal app and oauth2 are separate containers in the same POD

```
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app: demo-app

name: demo-app
namespace: demo-namespace
spec:
progressDeadlineSeconds: 600
replicas: 1
revisionHistoryLimit: 10
selector:
matchLabels:
app: demo-app
strategy:
rollingUpdate:
maxSurge: 50%
maxUnavailable: 50%
type: RollingUpdate
template:
metadata:
labels:
app: demo-app
annotations:
Vault stuff

spec:
automountServiceAccountToken: true
containers:
- name: demo-app
image: registry.internal.com/path/image:latest
imagePullPolicy: Always
name: demo-app
args: ["sh", "-c", ". /vault/secrets/demo && ./gunicorn.sh"]
ports:
- containerPort: 8000
protocol: TCP
env:
- name: YOUNG_NODE_GRACE_PERIOD

value: "1200"
- name: DEMO_FILE
value: /app/config/awsconfig
- name: TFE_URL
value: https://tfe.internal.com
resources:
limits:
cpu: 8
memory: 2Gi
requests:
cpu: 500m
memory: 256m

- name: oauth2-proxy
image: registry.internal.path/image:v7.1.3
imagePullPolicy: IfNotPresent
command: ["/bin/sh", "-c"]
# args: ["source /vault/secrets/app && /bin/oauth2-proxy --provider=azure --email-domain=internal.com --http-address=0.0.0.0:4180 --

upstream=http://localhost:8000  --show-debug-
on-error=true --cookie-domain=.internal.com --cookie-secure=false --azure-tenant=123456789"]

args: ["source /vault/secrets/demo && /bin/oauth2-proxy --provider=azure --email-domain=internal.com --http-address=0.0.0.0:4180 --
upstream=http://localhost:8000 --show-debug-on-error=true --azure-tenant=123456789"]
ports:
- containerPort: 4180
protocol: TCP
dnsPolicy: ClusterFirst
imagePullSecrets:
- name: pcas-image-pull-k8s-git
restartPolicy: Always
schedulerName: default-scheduler
securityContext:
runAsUser: 1000
serviceAccount: service-vault-auth-delegator
serviceAccountName: service-vault-auth-delegator
shareProcessNamespace: false
terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
labels:
app: demo-app
name: demo-app-oauth2-proxy
namespace: demo-namespace
spec:
ports:
- name: http
port: 4180
protocol: TCP
targetPort: 4180
selector:
app: demo-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: demo-app-oauth2-proxy
namespace: pcas-inf
annotations:
nginx.ingress.kubernetes.io/proxy-buffer-size: 16k

spec:
rules:
- host: demo-app-demo-namespace
http:
paths:
- backend:
serviceName: demo-app-oauth2-proxy
servicePort: 4180
path: /
```

## versions
kubernetes v1.21
nginx controller v1.19
oauth2: v7.1.3

**Comment by robertocamp** [comment]
A follow up question I have is that I am not using any annotations for nginx with regard to `auth-url` or `auth-signin`.
so,
1. are these strictly necessary ?
2. could this be where my issue is?

**Comment by rcampbell-LI** [comment]
I had an issue with my secret, pulling the secret id and not the actual secret "value" , from vault. I will mark the issue resolved.
