### ISSUE TITLE
Oauth2-proxy is returning status 302 instead of 401 for AJAX requests when the cookie is expired

### ISSUE THREAD

**Issue by l-lafin** [oauth2-proxy/oauth2-proxy#1393]
I'm not sure if this is a bug or misconfiguration, but the oauth2-proxy is returning the status code 302 instead of 401 for AJAX requests when the cookie is expired, which triggers an unwanted redirect in the browser. This question/bug is based on these discussions #551 and #461.

## Expected Behavior

- Given the oauth2-proxy received incoming AJAX requests
- And the cookie/access token is expired
- Then it should respond with the status code 401 (unauthorized) instead of 302 (found/redirect)

## Current Behavior

- Given the oauth2-proxy received incoming AJAX requests 
- And the cookie/access token is expired
- Then it is always responding as 302

## Steps to Reproduce (for bugs)

1.  Authenticated the user and gets fresh cookie/session.
2.  Wait until the cookie got expired.
3.  Trigger an Ajax call explicitly using the header `Accept: application/json`.

**Log example:**
```
172.20.0.10:37666 - ade7a6fc-4078-49a6-a753-3a24146efccf - - [2021/10/06 20:35:30] dev.local.com POST - "/cco/api/form-interpreter/api/v1/Interpret/InCharge-allergies" HTTP/1.1 "" 302 0 0.000
[2021/10/06 20:35:30] [stored_session.go:76] Error loading cookied session: http: named cookie not present, removing session
```

**Request executed:**
```
Request URL: https://dev.local.com/cco/api/form-interpreter/api/v1/Interpret/InCharge-allergies
Request Method: POST
Status Code: 302 Found
Remote Address: 127.0.0.1:443
Referrer Policy: strict-origin-when-cross-origin

// Headers:
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 155
Content-Type: application/json;charset=UTF-8
Cookie: cookie_session_name_csrf=<cookie_value>
```

## Context

We are using oauth2-proxy to handle the authentication from both `Ajax requests` (explicitly contains the header `Accept: application/json`) and regular requests from a SPA application. Since we are a SPA application we load the application once at the start and then after that we just perform AJAX calls, so we need to receive an actual 401 when the cookie get expired to handle it properly in the SPA and avoid possible errors from unwanted automatic redirects.

## Your Environment

- Version used: `quay.io/oauth2-proxy/oauth2-proxy:v7.1.3`

```
OAUTH2_PROXY_COOKIE_DOMAINS=*
OAUTH2_PROXY_COOKIE_EXPIRE=0h29m0s
OAUTH2_PROXY_COOKIE_REFRESH=0
OAUTH2_PROXY_COOKIE_NAME=cookie_session_name
OAUTH2_PROXY_COOKIE_SECRET=SomeRandomSecret
OAUTH2_PROXY_COOKIE_SECURE=true
OAUTH2_PROXY_EMAIL_DOMAINS=*
OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:8080
OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=true
OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION=true
OAUTH2_PROXY_PROVIDER=oidc
OAUTH2_PROXY_LOGIN_URL=https://my.oidc.provider.com/authorize/oauth2/authorize
OAUTH2_PROXY_OIDC_ISSUER_URL=https://my.oidc.provider.com/oauth2/access_token
OAUTH2_PROXY_OIDC_JWKS_URL=https://my.oidc.provider.com/authorize/oauth2/jwks?api-version=1
OAUTH2_PROXY_REDEEM_URL=https://my.oidc.provider.com/authorize/oauth2/token
OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true
OAUTH2_PROXY_PASS_BASIC_AUTH=true
OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://my.redis.app:6379
OAUTH2_PROXY_SESSION_STORE_TYPE=redis
OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
OAUTH2_PROXY_SET_INTROSPECTION_VALUE=true
OAUTH2_PROXY_SET_XAUTHREQUEST=true
OAUTH2_PROXY_SKIP_OIDC_DISCOVERY=true
OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY=true
OAUTH2_PROXY_UPSTREAMS=static://
OAUTH2_PROXY_WHITELIST_DOMAINS=*
```

**Note: We are not using the cookie refresh option, but we have tested using it with the value `OAUTH2_PROXY_COOKIE_REFRESH=0h28m0s`.**

Not sure if it's relevant or not, but the oauth2-proxy is behind an instance of envoy reverse proxy that will only proxy the request URL in the right direction/network and it does not touch in the headers at all.

**Comment by phllpmcphrsn** [comment]
@ricosega were/are you using Istio; if so, what version? Trying to figure out when `includeRequestsHeadersInCheck` was added to see if I need to convert to it (from `includeHeadersInCheck`)
