### ISSUE TITLE
Feat: allow to disable the behavior to log user out when receiving HTTP 401 from upstream

### ISSUE THREAD

**Issue by truong-hua** [oauth2-proxy/oauth2-proxy#1395]
I believe that many people is deploying OAuth2 Proxy as a convenience layer to secure other services like how the Basic Auth is working. In that scenario, people like me won't expect that OAuth2 Proxy will act anything while receiving 401 from the upstream (like the upstream service may have their owned Basic Auth). So, Oauth2 Proxy will look like a firewall in my scenario.

## Expected Behavior

OAuth2 Proxy just passthrough the HTTP 401 from the upstream without altering their response.

## Current Behavior

If the upstream response 401, OAuth2 proxy will handle the upstream response and override the output (clean cookie & redirect user to OAuth2 login page), which is not expected.

## Possible Solution

Deploy a middleware reverse proxy nginx that rewrite HTTP 401 with another HTTP code but the client will wrongly handle the response.

## Steps to Reproduce (for bugs)

1.  Deploy a NGINX which always response 401 Unauthorized
2.  Place an OAuth2 Proxy in front of the NGINX.
3.  After authorized to OAuth2 Proxy, user will be redirected to login page

## Your Environment

Docker Swarm

- Version used: quay.io/pusher/oauth2_proxy:latest@sha256:5b1152e6caada09a5d3bf91fcba0f9b6ba04479ce3ab7438e57e629c3baa895d

**Comment by JoelSpeed** [comment]
This will need some investigation to work out exactly why this is happening, as far as I know there's nothing explicitly written in our code to cause this behaviour deliberately. We don't inspect the responses from upstream servers so I'm not sure why this would be happening

**Comment by JoelSpeed** [comment]
I just tried to reproduce this with our local test environment and could not reproduce the issue.

1. `make local-env-up`
2. In a browser, access `http://localhost:4180`
3. Perform the login using the admin@example.com user and password as password
4. Access `http://localhost:4180/status/401` to generate a 401, OAuth2 Proxy transparently proxied this without doing anything to the reponse

Perhaps some other proxy is observing the 401 and causing this behaviour?

**Comment by GilbertYoder** [comment]
I want to reoopen this discussion.

I'm using oauth2-proxy with traefik forward-auth to protect a wide variety of backend-services. I use traefik middleware to catch 401 errors and redirect to the oauth2-proxy sign in page. This middleware is applied to all backend services. This is per docs: [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#configuring-for-use-with-the-traefik-v2-forwardauth-middlewarel)

Some backend services throw 401's for various reasons, possibly no good reason, but that will result in the user being redirected to oauth2/sign_in?etc and logged out.

I can remove the redirect to fix this issue, but then users lose that convenience.

Any ideas on this?
