### ISSUE TITLE
Result of provider.ValidateSession() is ignored during session creation

### ISSUE THREAD

**Issue by stippi2** [oauth2-proxy/oauth2-proxy#1396]
## Expected Behavior

Authentication fails if the JWT validation fails.

## Current Behavior

The result of the JWT validation does not have any effect, as the return value of the function [is ignored](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L756).

## Possible Solution

Look at the return value and fail authentication if necessary.

## Steps to Reproduce (for bugs)

For debugging purposes, I have configured a really short token expiry time in the OIDC issuer (1 minute). I have stepped through the code for authentication flow after the oauth2/callback endpoint is called, i.e. when initiating the fresh session. This caused enough of a delay that the token was already expired before it was being validated. The validation failed as expected [here](https://github.com/coreos/go-oidc/blob/v3/oidc/verify.go#L271). But then I realized that the result of `ValidateSession()` is actually ignored. I assume token expiry is not the only reason why validation can fail.

## Your Environment

- Version used:

https://github.com/oauth2-proxy/oauth2-proxy/commit/fd5e23e1c55ec99f552321a317770015a4b788e1

**Comment by JoelSpeed** [comment]
@NickMeves I think this was introduced when you adding nonce checks for ID Tokens, do you recall if there was a particular reason for ignoring the return value of `ValidateSession`?

Since this is only happening on login, how much of a real world issue is this? IIUC we still validate the session correctly on subsequent calls and refreshes

**Comment by NickMeves** [comment]
Looks like a bug to me; good catch!

The intent was to validate the session after Redeem & Refresh. Without this validated, this is only happening on the Refresh process.

OIDC is the most effective user of this checking the Nonce claim in the returned ID token.

Other providers just hit the Profile URL with the Access Token if I recall.

@stippi2 Are you comfortable making a PR with the fix?

**Comment by stippi2** [comment]
PR to fix the issue is easy. Not yet sure how easy it will be to also provide test coverage, but I'll see.

**Comment by stippi2** [comment]
Not sure if you got a notification, I've opened the [PR 1433](https://github.com/oauth2-proxy/oauth2-proxy/pull/1433) to provide a fix including test coverage.
