### ISSUE TITLE
oauth2-proxy behind a ingress redirect to root path, not oauth-proxy

### ISSUE THREAD

**Issue by szediktam** [oauth2-proxy/oauth2-proxy#1400]
I deploy oauth2-proxy as a sidecar container with my component. And expose it as a path in my vip,(https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy)
oauth-proxy config:
      containers:
      - args:
        - --https-address=:4180
        - --upstream=http://localhost:8080
        - --provider=oidc
        - --provider-display-name="HHHHHHHH"
        - --oidc-issuer-url=https://xxx.xxx.xxx.xxx/dex
        - --client-id=oauth2-proxy
        - --client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
        - --scope=openid+profile+email+groups+ext
        - --redirect-url=https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy/oauth2/callback
        - --login-url=https://xxx.xxx.xxx.xxxx/aaa/bbb/oauth2-proxy
        - --email-domain=*
        - --ssl-insecure-skip-verify=true
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-key-file=/etc/tls/private/tls.key
        - --cookie-secure=false
        - --cookie-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
        - --cookie-expire=0h20m0s
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
## Expected Behavior
when i view https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy，it will jump to my dex and then to my componet.

## Current Behavior
when i view https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy，it jumps to https://xxx.xxx.xxx.xxx/oauth2/start，not https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy/oauth2/start. I cant jump to dex to login in

When I add a option
--proxy-prefix=/aaa/bbb
it jumps to https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy/oauth2/start. But not oauth-proxy is working at /aaa/bbb/oauth2/start

## Your Environment
Kubernetes v1.21.2
oauth2-proxy v7.1.3 as a sidecar container with my component in a pod.
expose oauth-proxy to https://xxx.xxx.xxx.xxx/aaa/bbb/oauth-proxy

**Comment by mteodor** [comment]
it is hard to tell from this config without the whole setup but the flow is like this( judging from your configuration and having oidc flow in mind)

* you access `http://whereveryourproxyis:4180` , 
* `oauth2-proxy` redirects  https://xxx.xxx.xxx.xxx/oauth2/start checks if there is authenticated session and if not 
* redirects further to login-url  https://xxx.xxx.xxx.xxx/dex/auth
* then Dex should authenticate user ( prompt with form to enter username and password )
* after successful authentication on Dex will send data to `/oauth2/callback` so that `oauth2-proxy` can retrieve token from Dex ( this actually happens through the browser but never mind)
* when `ouath2-proxy` successfully retrieves token it should present content from `upstream` localhost:8080

ok, but your ingress controller of choice must have something similar to
```
 nginx.ingress.kubernetes.io/auth-signin: http://oauth2-proxy.localtest.me/oauth2/start
 nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy-example-oauth2-proxy-sample.default.svc.cluster.local/oauth2/auth
```

**Comment by JoelSpeed** [comment]
> When I add a option
--proxy-prefix=/aaa/bbb
it jumps to https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy/oauth2/start. But not oauth-proxy is working at /aaa/bbb/oauth2/start

I think you need to set the proxy prefix to `--proxy-prefix=/aaa/bbb/oauth2-proxy/oauth2` based on what you've said so far, it seems it's working for you, based on the original comment, you just haven't put quite the right value

**Comment by JoelSpeed** [comment]
The redirect URL is constructed here which does include the proxy prefix https://github.com/oauth2-proxy/oauth2-proxy/blob/543a71efada7c2ce3fe2451e4625ba7c893be313/oauthproxy.go#L143-L146

Have you explicitly set the `redirect-url` in your configuration?

**Comment by szediktam** [comment]
@JoelSpeed I set `redirect-url` to `at https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy/oauth2/callback`
Here is my new configuration:
```
  - args:
    - --https-address=:4180
    - --http-address=:4180
    - --upstream=http://localhost:8080
    - --provider=oidc
    - --oidc-issuer-url=https://xxx.xxx.xxx.xxx/dex
    - --client-id=oauth2-proxy
    - --client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
    - --scope=openid+profile+email+groups+ext
    - --skip-provider-button=true
    - --redirect-url=https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy/oauth2/callback
    - --email-domain=*
    - --ssl-insecure-skip-verify=true
    - --cookie-secure=false
    - --cookie-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
```

oauth-proxy ingress configuration:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: oauth2-proxy
  namespace: kube-system
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
        path: /aaa/bbb/oauth2-proxy($|/)(.*)
        pathType: ImplementationSpecific
```

With this configuration, when i access  `https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy/`,
it skip provider login page, and login in with dex.
But after callback, it redirect to `https://xxx.xxx.xxx.xxx/` , not `https://xxx.xxx.xxx.xxx/aaa/bbb/oauth2-proxy/`. How to fix this.
