### ISSUE TITLE
Authorizing against Github - Passing access_token in Authorization header

### ISSUE THREAD

**Issue by dineshsbm** [oauth2-proxy/oauth2-proxy#1402]
Recently there was a changed made by Github in Authorizing oAuth Apps that the **Access Token** should be passed in header and not as a query parameter. I went through the documents which were pointed out (see below)

- https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
- https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps

I have a Kibana instance running on AWS for which the users are authorized against GitHub using oauth2-proxy. The authorization happens via command line which is configured as below
`./oauth2_proxy --email-domain=* --upstream=http://kibana:<KIBANA_PORT> --http-address=http://:<KIBANA_AUTH_PORT> --redirect-url=https://<URL>/oauth2/callback --cookie-domain=<URL> --cookie-secure=true --cookie-httponly=false --cookie-expire=12h0m0s --provider=github --github-org=FlukeNetworks --github-team=kibana-insights`

Currently, I am running into an error and not able to login to Kibana instance. I am trying to follow the document to make the change but couldn't understand how to pass the token in the header through command line, as I can see all the documents refer to make the CURL request.

## Expected Behavior

The `access_token` is passed in Authorization and the user are authorized against Github.

## Current Behavior

Currently, the `access_token` is passed in header due to which Github reports an error and doesn't authorizes the users to login to Kibana. 

Adding logs below for reference
`error redeeming code got 400 from "https://api.github.com/user/teams?access_token=<TOKEN>...&limit=100" {"message":"Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param","documentation_url":"https://docs.github.com/v3/#oauth2-token-sent-in-a-header"}
ErrorPage 500 Internal Error Internal Error... <INTERNAL URL> GET - "/oauth2/callback?code=<CODE>&state=<STATE>" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0" 500 331 0.290`

## Context

I am trying to pass the `access_token` via Authorization header to authenticate user against Github. Currently, I am unable to login to Kibana instances (Dev & Production) to get user analytics.

## Your Environment

1. Kibana is hosted on AWS cloud and running in ECS container.
2. oauth2_proxy is an executable file downloaded from https://github.com/bitly/oauth2_proxy/releases/download/v2.2/oauth2_proxy-2.2.0.linux-amd64.go1.8.1.tar.gz

- Version used: oauth2_proxy-2.2.0.linux-amd64.go1.8.1

**Comment by JoelSpeed** [comment]
> Version used: oauth2_proxy-2.2.0.linux-amd64.go1.8.1

Please upgrade to a newer version of OAuth2 Proxy, this issue is already resolved in newer versions

**Comment by dineshsbm** [comment]
Thank you, @JoelSpeed. Upgrading works like a charm without additional changes :)
