### ISSUE TITLE
Auth0 expect 'audience' parameter with the authorize request

### ISSUE THREAD

**Issue by Mariappan** [oauth2-proxy/oauth2-proxy#1406]
## Expected Behavior

Support to send `audience` parameter along with authorize request

## Current Behavior

We are trying to integrate oauth2-proxy with our app, which uses auth0 as an OIDC provider. 

There is one minor problem we are facing. Auth0 currently expects a parameter `audience` in the authorize request to send valid JWT access tokens. If not, auth0 sends opaque access tokens which can be only verified by calling the auth0 server again.
_Ref:_
https://community.auth0.com/t/getting-jwt-access-token-instead-of-opaque-token-from-oauth-token-with-authorization-code-flow/48395
https://auth0.com/docs/authorization/flows/call-your-api-using-the-authorization-code-flow

Oauth2-proxy does not support adding extra parameters with authorize request.

## Possible Solution

1. The parameter `audience` is not part of the OIDC spec, but the spec does not seem to restrict sending other parameters.
    Add an optional config `audience`, which can be added to the authorize request if configured.
    I have quickly made some changes and verified working for my case. 
    I could raise a PR if this proposal looks fine.

2. Another possible solution is to have a config which can take key value pair. This kv pairs can be added to the authorize request. This solution may enable users to use oauth2proxy with some other id providers, which need other custom params.

## Context

Our cluster uses ambassador as ingress controller and configured oauth2-proxy as extAuth service.
oauth2-proxy has `--pass-access-token` config set and it forwards the access-token to ambassador as expected.
Our app then verifies this JWT access token before proceeding.

## Your Environment

- Version used:
v7.1.3-amd64

**Comment by JoelSpeed** [comment]
The audience is a static parameter right? If you manually configure the OIDC endpoints rather than using the discovery mechanism, you should be able to add additional query string parameters to the URLs which will then be passed along. People have used this technique before to add additional parameters such as the google hosted domain parameter

**Comment by JinruiDuan** [comment]
Hi @Mariappan ! I'm having a similar question for setting it up for auth0. Would you mind share your config?

**Comment by sudoduan** [comment]
Hi @Mariappan ! I have a similar issue when setting it up for auth0. Do you mind share your config?

**Comment by Mariappan** [comment]
@sudoduan Yep sure,

```ini
# Server configuration
http_address="0.0.0.0:4180"
upstreams="static://200"

# OIDC provider configuration
provider="oidc"
oidc_issuer_url="Auth0 subdomain https://dev.auth0.com/"
client_secret="SECRET"
client_id="CLIENT_ID"
redirect_url="/oauth2/callback"
audience="API audience"

email_domains="*"
set_xauthrequest="true"
pass_access_token="true"

# Cookie storage configuration
# https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#generating-a-cookie-secret
cookie_secret="RANDOM_URLSAFE_BASE64_ENCODED_SECRET"
cookie_secure="true"
```

**Comment by matzegebbe** [comment]
hello! That config above works for you? I thought `audience` isn't supported and you had to use `skip-oidc-discovery`

**Comment by matzegebbe** [comment]
https://github.com/oauth2-proxy/oauth2-proxy/issues/1250 that answers my question
