### ISSUE TITLE
Provider OIDC with keycloak : refresh_token not replace during re code flow ==> Error 500

### ISSUE THREAD

**Issue by GFlo69** [oauth2-proxy/oauth2-proxy#1409]
During the re init of the second session, the value of the lifetime of the refresh token is never updated

## Current Behavior

My keycloak realm is configured to

- not allow mutilple use of the same refresh_token.
- refresh token's lifespan is 3 min
- access token's lifespan is 1 min 

My oatuh2-proxy is configured to 
- execute a refresh cookie every minute

I can see the correct execution of the refresh_token on my keycloak instance every minute. I also see it in the logs.
However, the first alert is logged on the expiration of the refresh token. When its lifespan is exceeded, the flow code is restarted but generates an error 500. I see in the logs always the same value of the lifespan of the refresh token

Note : To return after the 500 error to an acceptable state, I have to delete my keycloak user session

## Possible Solution

Verify value expiration of refresh_token in cookie ?

## Steps to Reproduce (for bugs)

1.  Configure keycloak client with lifespan token at 1m and Client Session Max at 3m
2.  Configure proxy with refresh cookie at 1m
3.  Connected on proxy and show logs
4. No problem before 1m
5. At +1min refresh cookie (refresh token) is execute
6. At +2min refresh cookie (refresh token) is execute
7. At +3min Error 500. 
Log show : 

 ```
./oauth2-proxy --config configv2.file
[2021/10/16 23:14:40] [proxy.go:70] mapping path "/" => upstream "http://127.0.0.1:8080/"
[2021/10/16 23:14:40] [oauthproxy.go:143] OAuthProxy configured for OpenID Connect Client ID: oauth2-proxy
[2021/10/16 23:14:40] [oauthproxy.go:149] Cookie settings: name:_oauth2_proxy secure(https):false httponly:false expiry:2m0s domains: path:/ samesite: refresh:after 1m0s


127.0.0.1:42656 - fbfca142-309e-4f8a-aed7-280da0344530 - MAIL [2021/10/16 23:15:27] monsitesecure.DOMAINE:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 404 19 0.000
[2021/10/16 23:15:49] [stored_session.go:122] Refreshing 1m16.665170101s old session cookie for Session{email:MAIL user:IDUSER PreferredUsername:USER token:true id_token:true created:2021-10-16 23:14:32.334829899 +0200 CEST expires:2021-10-16 23:15:32.325781796 +0200 CEST refresh_token:true} (refresh after 1m0s)
[2021/10/16 23:15:49] [oidc.go:158] refreshed session: Session{email:MAIL user:IDUSER PreferredUsername:USER token:true id_token:true created:2021-10-16 23:15:49.882520819 +0200 CEST m=+69.233994635 expires:2021-10-16 23:16:49.866585362 +0200 CEST m=+129.218059178 refresh_token:true}
[2021/10/16 23:15:49] [cookies.go:84] Warning: request host is "monsitesecure.DOMAINE" but using configured cookie domain of "DOMAINE:4180"
127.0.0.1:42656 - 4ac608b7-b493-4b51-9475-325d6ac37533 - MAIL [2021/10/16 23:15:49] monsitesecure.DOMAINE:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 404 19 0.056


127.0.0.1:42656 - efd0af57-b0cf-4b13-a234-ba76af6fa885 - MAIL [2021/10/16 23:16:49] monsitesecure.DOMAINE:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 404 19 0.000
[2021/10/16 23:16:56] [stored_session.go:122] Refreshing 1m6.117479181s old session cookie for Session{email:MAIL user:IDUSER PreferredUsername:USER token:true id_token:true created:2021-10-16 23:15:49.882520819 +0200 CEST expires:2021-10-16 23:16:49.866585362 +0200 CEST refresh_token:true} (refresh after 1m0s)
[2021/10/16 23:16:56] [oidc.go:158] refreshed session: Session{email:MAIL user:IDUSER PreferredUsername:USER token:true id_token:true created:2021-10-16 23:16:56.70730767 +0200 CEST m=+136.058781486 expires:2021-10-16 23:17:32.706985363 +0200 CEST m=+172.058459079 refresh_token:true}
[2021/10/16 23:16:56] [cookies.go:84] Warning: request host is "monsitesecure.DOMAINE" but using configured cookie domain of "DOMAINE:4180"
127.0.0.1:42656 - d123c070-024d-4c2f-addf-3c203fc94881 - MAIL [2021/10/16 23:16:56] monsitesecure.DOMAINE:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 404 19 0.041

127.0.0.1:42656 - befecc94-2edc-43c1-84c0-4d32ec710020 - MAIL [2021/10/16 23:17:52] monsitesecure.DOMAINE:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 404 19 0.001
[2021/10/16 23:18:06] [stored_session.go:122] Refreshing 1m9.29269233s old session cookie for Session{email:MAIL user:IDUSER PreferredUsername:USER token:true id_token:true created:2021-10-16 23:16:56.70730767 +0200 CEST expires:2021-10-16 23:17:32.706985363 +0200 CEST refresh_token:true} (refresh after 1m0s)
[2021/10/16 23:18:06] [stored_session.go:76] Error loading cookied session: error refreshing access token for session (Session{email:MAIL user:IDUSER PreferredUsername:USER token:true id_token:true created:2021-10-16 23:16:56.70730767 +0200 CEST expires:2021-10-16 23:17:32.706985363 +0200 CEST refresh_token:true}): error refreshing access token: unable to redeem refresh token: failed to get token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Token is not active"}, removing session
127.0.0.1:42656 - 87958b27-3706-40bf-949a-ef8bcace859a - - [2021/10/16 23:18:06] monsitesecure.DOMAINE:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 403 8069 0.032
127.0.0.1:42656 - bde4c1e8-b97b-4764-a56f-421ccabddf32 - - [2021/10/16 23:18:14] monsitesecure.DOMAINE:4180 GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 302 350 0.000
[2021/10/16 23:18:14] [oauthproxy.go:748] Error redeeming code during OAuth2 callback: could not verify id_token: oidc: token is expired (Token Expiry: 2021-10-16 23:17:32 +0200 CEST)
127.0.0.1:42656 - c8b67e9d-d079-4def-a91e-189a9c4d08c3 - - [2021/10/16 23:18:14] monsitesecure.DOMAINE:4180 GET - "/oauth2/callback?state=E7RCCS2wFE80x1ebMu81N6jBdGPnqLqrmiPOIk_roeQ%3A%2F&code=ca6e03e8-6927-43ea-b422-502c9cd7b127.e6ba9645-bde4-4f23-8cae-ed2d01cfb159.a74724de-e96a-4f47-b158-901173991f69" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 500 2841 0.032
```

Show the line : 
`[2021/10/16 23:18:14] [oauthproxy.go:748] Error redeeming code during OAuth2 callback: could not verify id_token: oidc: token is expired (Token Expiry: 2021-10-16 23:17:32 +0200 CEST)`

Token Expiry is the value of the before last refresh : 
`CEST expires:2021-10-16 23:17:32.706985363`

The code flow 

## Your Environment

http_address = "127.0.0.1:4180"
reverse_proxy = false
provider_display_name="RALALA"
redirect_url = "http://monsitesecure:4180/oauth2/callback"
upstreams = "http://127.0.0.1:8080/"
request_logging = true
auth_logging = true
email_domains = [
     "*"
]
provider = "oidc"
client_id = "oauth2-proxy"
client_secret = "f0e26e1e-XX"
oidc_issuer_url="https://KEYCLOAK/auth/realms/TEST"
cookie_secret=1234567891234567
scope="profile openid"
cookie_expire="60m"
cookie_refresh = "1m"
cookie_httponly=false
cookie_secure=false
skip_provider_button=false
ssl_insecure_skip_verify = false

- Version used: 7.1.3 (tested on 6 and 5)
- keycloak used: 12.04 (tests on keycloak 15)

**Comment by GFlo69** [comment]
I test with matser and provider oidc. I have the same result. What is the version of keycloak in your env ?
```
2021/10/17 21:46:43 oauthproxy.go:749: 127.0.0.1:52288 error redeeming code unable to update session: could not verify id_token: oidc: token is expired (Token Expiry: 2021-10-17 21:46:37 +0200 CEST)
2021/10/17 21:46:43 oauthproxy.go:532: ErrorPage 500 Internal Error Internal Error
127.0.0.1 - - [17/Oct/2021:21:46:43 +0200] monsitesecure:4180 GET - "/oauth2/callback?state=5062c8f58da6896a96dd3e0ab89d12d7%3A%2F&code=c7fe69c9-acd1-4862-8aba-6b8a5782d022.de0a907f-89fa-457c-9be6-80c48d40cc5a.a74724de-e96a-4f47-b158-901173991f69" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 500 331 0.038
```

When I tring use keycloak-oidc or keycloak provider, the log say "OAuthProxy configured for Google Client ID:"

**Comment by GFlo69** [comment]
### Keycloak Configuration : 
access_token ==> 1 min
refresh_token ==> 3 min
Limit 1 use refresh token

### oauth2 proxy Configuration
refresh cookie ==> 1 min
provider ==> oidc (version master and 7)


**Authentificate step : t=0 min (21:00:14)**
```
2021/10/18 21:00:14 oauthproxy.go:779: 127.0.0.1:44254 authentication complete Session{email:USER@domaine.com user: token:true id_token:true expires:2021-10-18 21:01:14.996461285 +0200 CEST m=+777.095077244 refresh_token:true}
127.0.0.1 - - [18/Oct/2021:21:00:14 +0200] monsitesecure.domaine.grp:4180 GET - "/oauth2/callback?state=35b9ecac6a270b4d335f5ee45041fe54%3A%2F&code=a3ef67af-316e-4b0d-aef8-f227b3c5fa57.15eada20-9743-4a4e-9f25-d466ae228720.a74724de-e96a-4f47-b158-901173991f69" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 302 24 0.167
```

**==> Keycloak generate access token with 1 min lifespan  and a refresh token for 3 min lifespan ==> access token expire at 21:00:14 + 1min ==> 21:01:14 ==> It's ok for me**

**After +1min (T=0 + >1min = 21:01:46)**
```
2021/10/18 21:01:46 oauthproxy.go:833: 127.0.0.1:44254 refreshing 1m32s old session cookie for Session{email:USER@domaine.com user:USER token:true id_token:true expires:2021-10-18 21:01:14.996461285 +0200 CEST refresh_token:true} (refresh after 1m0s)
refreshed id token Session{email:USER@domaine.com user:USER token:true id_token:true expires:2021-10-18 21:02:46.78464161 +0200 CEST m=+868.883257569 refresh_token:true} (expired on 2021-10-18 21:01:14.996461285 +0200 CEST)
127.0.0.1 - USER@domaine.com [18/Oct/2021:21:01:46 +0200] monsitesecure.domaine.grp:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 404 19 0.163
```
**==> A refresh cookie is execute
==> Keycloak generate one acces_token + 1 min lifespan (access_token lifespan at 21:01:46 + 1 min = 21:02:46) AND one new refresh_token + 3min lifespan (refresh token lifespan at 21:01:46 + 3 min). The value 2021-10-18 21:01:14.996461285 is the good expire time for generate 
access token at T=0**

**After + 1min (T=0 + > 2min = 21:03:25)**
```
2021/10/18 21:03:25 oauthproxy.go:833: 127.0.0.1:44254 refreshing 1m39s old session cookie for Session{email:USER@domaine.com user:USER token:true id_token:true expires:2021-10-18 21:02:46.78464161 +0200 CEST refresh_token:true} (refresh after 1m0s)
2021/10/18 21:03:25 oauthproxy.go:839: 127.0.0.1:44254 removing session. error refreshing access token unable to redeem refresh token: failed to get token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Token is not active"} Session{email:USER@domaine.com user:USER token:true id_token:true expires:2021-10-18 21:02:46.78464161 +0200 CEST refresh_token:true}
```

**==> A refresh cookie is execute
==> The value 2021-10-18 21:01:14.996461285 is the good expire time for generate access token at T0 +> 1min**
```
I see this log : removing session. error refreshing access token unable to redeem refresh token: failed to get token: oauth2: cannot fetch token: 400 Bad Request.
Note : My keycloak is configurate to accept one unique same refresh token.
Information : When I configure keycloak for accept 10 same refresh, the problem arises later. This test therefore makes it possible to confirm that oauth2 proxy does not overwrite its refresh token value..
```


In fact, refresh token expiration is present for maintenir user session. Keycloak sso lifespan is an another value for force in lifespan user re-authentification 

Maybe another problem. When I get to the refresh token expiration time, oauth2 raised a code 500. The log shows an old expiration time in the token.
The uniq solution for the unblocking situation is the logout user on the keycloak session ??? In this case, I have no explanation

**Comment by louisgls** [comment]
I believe I have the same issue, if i set refresh_token lifespan to 3 min, i have after 3 min :
```
[2021/11/02 19:49:01] [stored_session.go:124] Unable to refresh session: error refreshing tokens: unable to redeem refresh token: failed to get token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Token is not active"}
```
If I try again using the max reuse of refresh token option in keycloak :
```
[2021/11/02 19:57:36] [stored_session.go:124] Unable to refresh session: error refreshing tokens: unable to redeem refresh token: failed to get token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Maximum allowed refresh token reuse exceeded"}
```
I'm using keycloak-oidc and oauth2-proxy 7.2.0. The same issue occurs with 7.1.3 and oidc default provider.

I'm guessing the oidc provider is reusing the same refresh token because it didn't successfully retrieved the new refresh token as you said :

> Looking at this, it is suggesting that we aren't storing the new refresh tokens, I assume that keycloak is returning the new refresh token in the same way as normal OIDC providers would be, in which case, if this is correct, we have introduced a bug somewhere in our OIDC provider.

I could be doing something wrong since you made it work on your local testing environment but I can't find out what could be the issue here.

> I've just tested master with our local testing environment and can confirm this bug is not present in master, would you be able to build a container from the latest code and test in your environment?

**Comment by JoelSpeed** [comment]
> I'm guessing the oidc provider is reusing the same refresh token because it didn't successfully retrieved the new refresh token as

I agree, I think that's your problem, I don't think there's anything we can do to change that behaviour though. In this case, i'd expect the session to now fail validation in which case, the session is cleared and the user is asked to re-authenticate, is that not happening for you?

**Comment by torrybr** [comment]
I am getting this exact error with keycloak using the keycloak-oidc provider

**Comment by krishnakc1** [comment]
Does anyone can tell why this is happening? I have same issue at the moment. I initially thought the redis db has bad refresh token data. Restarting it from scratch did not make a difference.
