### ISSUE TITLE
No error message from failed token exchange

### ISSUE THREAD

**Issue by andreas-p** [oauth2-proxy/oauth2-proxy#1415]
I was stuck quite a while getting V7.1.3 to run with that dreaded "error loading cookied session" until I found out that proxy_prefix was configured wrong.

When there's an unexpected response from the auth server trying to exchange the token, there should be an error message logged.

**Comment by NickMeves** [comment]
I don't think there's anything we can do here.

We redirect you to your IdP and rely on your IdP redirecting you back to the Callback URL. Once you are back with us, we have descriptive & distinct error logs for every way you could potentially fail the Start + Callback sides of that sandwich around your IdP

**Comment by andreas-p** [comment]
I'm talking about the token exchange that oauth2proxy performs after the client comes back to him from successful auth with the IdP. While oauth2proxy was able to access the IdP (concerning firewalling etc), but the content wasn't correct some how until proxy_prefix was fixed.
