### ISSUE TITLE
Use --skip-auth-route allow / but deny any other path

### ISSUE THREAD

**Issue by mikeyGlitz** [oauth2-proxy/oauth2-proxy#1423]
I'm looking to create a landing page for my web application. I'm using oauth2-proxy as a way to secure my application and make it so that only authorized users can access past the landing page. I want `/` to be allowed, but anything else should get redirected to oauth2-proxy.

## Expected Behavior

I the following configuration in my `oauth2_proxy.cfg` file and I don't have to go through my auth provider.

```
skip_auth_routes = ["^/$"]
```

## Current Behavior

I have the following configuration in my `oauth2_proxy.cfg` and am redirected to a login screen for my auth provider

```
skip_auth_routes = ["^/$"]
```
![image](https://user-images.githubusercontent.com/606924/138992787-1fca66a2-d103-4f9e-aef0-498f85ee8e42.png)
![image](https://user-images.githubusercontent.com/606924/138992677-9fcbd42b-f53a-486a-b61b-ab775cbbc5bd.png)

## Full configuration that I'm using

```
            provider = "keycloak"
            login_url = "https://host.docker.internal/auth/realms/Localnet/protocol/openid-connect/auth"
            redeem_url = "https://host.docker.internal/auth/realms/Localnet/protocol/openid-connect/token"
            profile_url = "https://host.docker.internal/auth/realms/Localnet/protocol/openid-connect/userinfo"
            validate_url = "https://host.docker.internal/auth/realms/Localnet/protocol/openid-connect/userinfo"
            email_domains = ["*"]
            skip_auth_regex = ["^\\/?$"]
            scope = "profile"
            ssl_insecure_skip_verify = true
            set_authorization_header = true
```

**Comment by JoelSpeed** [comment]
Will you be proxying traffic directly through the OAuth2 Proxy (using the `upstream`/`upstreams` options), or will you be using something like nginx/istio/traefik with their external auth module equivalents?

If you are using external auth, it is recommended to handle this kind of separation at the proxy level rather than relying on OAuth2 Proxy, which in these scenarios, doesn't normally know what the upstream require URI is.

**Comment by spahrson** [comment]
We have a similar issue here and try to have something like that:
- path `/admin` should be authenticated and authorized.
- everything else skipped.

This is just impossible with just oauth2proxy. If we skip `/` we skip also `/admin`. The regex engine below oauth2proxy does not allow any (negative) lookarounds thus we cannot create something like skip `^\/?(?!admin)+.*$`.

**Comment by mikeyGlitz** [comment]
> Will you be proxying traffic directly through the OAuth2 Proxy (using the `upstream`/`upstreams` options), or will you be using something like nginx/istio/traefik with their external auth module equivalents?
> 
> If you are using external auth, it is recommended to handle this kind of separation at the proxy level rather than relying on OAuth2 Proxy, which in these scenarios, doesn't normally know what the upstream require URI is.

I'm using Kubernetes to host the oauth2-proxy service. The service is being proxied through ingress-nginx.
