### ISSUE TITLE
Changing port causes error in loading cookied session

### ISSUE THREAD

**Issue by avarf** [oauth2-proxy/oauth2-proxy#1424]
I have a set up with nginx + oauth2-proxy that redirects to our keycloak for SSO. Everything works as expected but yesterday I needed to run two Nginx+oauth2 on my machine (for development on Microk8s) and because of port conflict I changed the public port of the second Nginx to 9090. When I try to access the backend APIs behind the Nginx, it first redirects me to keycloak and after signing in it tries to redirect me to the backend but oauth2 blocks the traffic and in the browser I get "This site can’t be reached" and in the logs of the oauth2 I get:
```
[2021/10/27 07:27:30] [stored_session.go:77] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
192.168.1.9 - b29fda4c-1af7-4cbf-aef2-d9eb8b95b29e - - [2021/10/27 07:27:30] mywws.io GET - "/oauth2/auth" HTTP/1.0 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36" 401 13 0.000
192.168.1.9 - 543b1101-812b-4fea-a50c-34d3846ce7fe - - [2021/10/27 07:27:30] mywws.io GET - "/oauth2/sign_in" HTTP/1.0 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36" 302 400 0.000
```

I tested and changed the port of the public service of Nginx to 443 and then I was able to access the backend but https + any other port than 443 fails.

## Expected Behavior
The public port of Nginx should not affect the behavior of oauth2.

## Steps to Reproduce (for bugs)
1. Launch an Nginx + oauth2 + some backend API
2. Use a different public port for Nginx than 443
3. Try to access the backend

## Your Environment

Microk8s kubernetes:
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-34+7402e007632498", GitCommit:"7402e007632498c9b5b4f9da672aa2be7b382f2a", GitTreeState:"clean", BuildDate:"2021-09-28T12:34:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

List of services and their exposed ports (proxy is the Nginx):
```bash
$ kubectl -n test get svc
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
wwslogs                 ClusterIP      10.152.183.86    <none>        9080/TCP         40h
wwslogs-publicip        LoadBalancer   10.152.183.155   192.168.1.9   9080:31692/TCP   40h
proxy-public-internal   ClusterIP      10.152.183.172   <none>        443/TCP          18h
oauth2                  ClusterIP      10.152.183.32    <none>        4180/TCP         18h
proxy-public            LoadBalancer   10.152.183.177   192.168.1.9   9090:30463/TCP   18h
```

**Comment by NickMeves** [comment]
Unless you harcoded `cookie-domain`:



--cookie-domain | string \| list | Optional cookie domains to force cookies to (e.g. .yourcompany.com). The longest domain matching the request's host will be used (or the shortest cookie domain if there is no match).
-- | -- | --


We use the standard host headers nginx is passing along to set the cookie domain appropriately:

```
// GetCookieDomain returns the correct cookie domain given a list of domains
// by checking the X-Fowarded-Host and host header of an an http request
func GetCookieDomain(req *http.Request, cookieDomains []string) string {
	host := requestutil.GetRequestHost(req)
	for _, domain := range cookieDomains {
		if strings.HasSuffix(host, domain) {
			return domain
		}
	}
	return ""
}
```

**Comment by avarf** [comment]
No, I didn't add any `cookie-domain`.
I tried to add it but I am getting marshaling error:
```bash
$ kubectl -n test logs oauth2-55688558b4-xnrnz 
[2021/11/02 08:56:32] [main.go:43] ERROR: failed to load config: error unmarshalling config: 1 error(s) decoding:

* '' has invalid keys: cookie_domain
```
I tried different formats, with port, without port, as a string, as a list of strings, etc. But I was getting that error all the time.
```
cookie_domain = "mywws.io"
cookie_domain = ".mywws.io"
cookie_domain = ".mywws.io:1443"
cookie_domain = [".mywws.io"]
cookie_domain = [".mywws.io:1443"]
```

**Comment by JoelSpeed** [comment]
The option is able to be specified multiple times, so within the config the key is `cookie_domains = ["..."]`. Try setting it to the domain without the port and see how you get on

**Comment by avarf** [comment]
This is what I did as I mentioned in my previous message: `cookie_domain = [".mywws.io"]`

**Comment by JoelSpeed** [comment]
Note the `s` in `cookie_domains = ["..."]` which you didn't have in your examples. This option is a list and as such, within the config has a trailing `s` when compared with the flag option
