### ISSUE TITLE
Recommened handling of js frontend applications

### ISSUE THREAD

**Issue by foosinn** [oauth2-proxy/oauth2-proxy#1425]
Recently i came across multiple js frontend applications that cache the `index` page and use js routers. This leads to loading a working index site from cache, but the js, css or ajax resources are redirected to the oauth login site.

Is there a well known solution to this? Only thing that came to our mind is disabling the cache for the index page.

## Expected Behavior

Redirect to oauth site.

## Current Behavior

Especially resources are redirected to the oauth login site. This is not tranparent to the user and simply ships a broken site

## Possible Solution

Disabling the cache

## Steps to Reproduce (for bugs)

--

## Context

--
## Your Environment

--

- Version used: 7.1.3

**Comment by NickMeves** [comment]
I agree -- disabling the cache or setting it lower than the OAuth2-Proxy session duration is probably your best bet.

All the other resources you mentioned won't be a good experience for the user's auth redirect. Your initial landing/index page if your only spot.

**Comment by foosinn** [comment]
Thanks, i think this can be closed
