### ISSUE TITLE
Facing issue for the oauth2-proxy with error connection refused from nginix pod

### ISSUE THREAD

**Issue by jijilonline** [oauth2-proxy/oauth2-proxy#1427]
[error] 6#6: *5352511 auth request unexpected status: 502 while sending to client, client: IP, server: .., request: "GET / HTTP/1.1", host: "hostnamet"
2021/10/28 09:10:23 [error] 6#6: *5352512 connect() failed (111: Connection refused) while connecting to upstream, client: IP, server: .., request: , subrequest: "/oauth2/auth", upstream: 

For the K8s Dashboard, we are using dex and uses oauth2 proxy and nginx for authentication and getting the above error in the nginx pod and oauth2 prox is getting Crashloopbackoff error

**Comment by NickMeves** [comment]
If OAuth2-Proxy is Crash Looping, I can see why Nginx can't connect to it with auth subrequests 😄 

Do you have any OAuth2-Proxy pod logs, that's likely your issue.  Usually a configuration error causes something like this.

**Comment by jijilonline** [comment]
Thanks Nick. We dont see any logs getting generated for the proxy pods.

Below is what we can find using describe command


Events:
  Type     Reason     Age                   From                  Message
  ----     ------     ----                  ----                  -------
  Warning  Unhealthy  14m (x1169 over 23h)  kubelet, <**node**>  Liveness probe failed: Get https://<PodIP>:4180/ping: dial tcp PodIP:4180: connect: connection refused
  Warning  BackOff    2s (x4700 over 23h)   kubelet, <**node**>  Back-off restarting failed container

**Comment by JoelSpeed** [comment]
Have you tried starting the OAuth2 proxy container on your local machine with your given config? There's almost certainly some issue with the configuration that's causing it to exit straight away.

The only way we will be able to provide guidance is if you can provide the OAuth2 Proxy logs

**Comment by jijilonline** [comment]
Not familiar on how to set it up on local machine. There is no logs getting generate from the pods

**Comment by JoelSpeed** [comment]
If you have docker/docker compose, you could try reproducing the issue by modifying the configuration in our [local testing environment](https://github.com/oauth2-proxy/oauth2-proxy/tree/master/contrib/local-environment), or always just use a `docker run` command passing the appropriate configuration

**Comment by jijilonline** [comment]
Here is the error

main.go:120: Get https://dex.int.xxxx.net/dex/.well-known/openid-configuration: dial tcp <IP>:443: connect: connection timed out

how to check if the firewall is open or not ?

**Comment by JoelSpeed** [comment]
Unfortunately, that's beyond the scope of the support I can give as a project maintainer, you will need to address your own network issues and make sure that your dex instance is accessible from wherever your container is running
