### ISSUE TITLE
Options set in config file are not consistently respected

### ISSUE THREAD

**Issue by JackLThornton** [oauth2-proxy/oauth2-proxy#1429]
When trying to set command line options in a configuration file (referenced with --config=*filepath*), some of those options are accepted and successfully used (e.g. tls_cert_file, tls_key_file and redirect_url) while others are ignored (e.g. https_address, client_id and client_secret).

## Expected Behavior
All of the configuration items that I would pass over the command line (except, of course, the reference to the configuration file) should be able to be placed in the configuration file after changing the dashes in the option name into underscores

## Current Behavior

Only some of the options set in the configuration file are recognized and respected. Others are apparently ignored. For example, if I specify the client_id in the configuration file, then executing oauth2-proxy results in an immediate error (when provider is specified as adfs) telling me that I must specify the client id. However, when I include --client-id as a command line argument, oauth2-proxy runs. (and yes, I have "uncommented" the lines with the indicated settings in the config file)

## Steps to Reproduce (for bugs)

Set provider as adfs and point to a properly formatted config file. Set the client id and secret in the config file. oauth2-proxy will immediately error out telling you that you didn't specify a client id or secret.

## Context

Just trying to not have to pass every setting via the command line. This is not high priority; however, if the documentation says something is supposed to work, then it should work or the documentation should be updated. Note that I had this same bug in the latest 7.1.x version, and it still exists in 7.2.0.

## Your Environment

I am running in a VM based on Ubuntu version 20.04.

- Version used:
7.2.0

**Comment by NickMeves** [comment]
🤔 Weird, config options are provider agnostic

We've had alignment issues in the past with a typo in the flag setup, but this looks normal to me:

https://github.com/oauth2-proxy/oauth2-proxy/blob/6c379f74dbb9078cbed8d9f8b77ca761fdf72f5a/pkg/apis/options/legacy_options.go#L469

You get this in 7.1.X using OIDC with your ADFS IdP too? Or just 7.2 when explicitly using the new ADFS Provider?

**Comment by NickMeves** [comment]
You should also see you client ID printed in the logs on startup:

https://github.com/oauth2-proxy/oauth2-proxy/blob/6c379f74dbb9078cbed8d9f8b77ca761fdf72f5a/oauthproxy.go#L148

Does it look the same if you use both mechanisms?

**Comment by aplovich** [comment]
I've noticed this when trying to get oauth2-proxy to read secrets from a file (client_secret and cookie_secret).  I don't see any errors in the logs on startup.  However, when I try to authenticate, the call to get token fails on my IDP due to an incorrect client secret.

If I configure the secrets as command line options, it works correctly.

I'm on v7.1.3.

**Comment by aplovich** [comment]
After some investigation, it looks like the Helm chart has default values for various settings that will make their way into EnvVars, which then override settings in any supplied (--config) config files.

config:
  clientID: "XXXXXXX"
  clientSecret: "XXXXXXXX"
  cookieSecret: "XXXXXXXXXXXXXXXX"

Setting this switch to false disabled this behavior, and allowed me to pass my secrets via config file:

proxyVarsAsSecrets: false
