### ISSUE TITLE
Can't successfully authenticate to ADFS

### ISSUE THREAD

**Issue by JackLThornton** [oauth2-proxy/oauth2-proxy#1430]
I am trying to use OAuth2 Proxy to authenticate via ADFS as the identity provider. ADFS successfully presents the authentication screen, allows me to enter credentials, whines at me if I get the credentials wrong, and just plain "disappears" if I get the credentials correct (as I would expect). OAuth2 Proxy fails on getting the callback from ADFS.

## Expected Behavior

OAuth2 Proxy should send the claims through to the upstream server.

## Current Behavior

OAuth2 Proxy displays a "500" internal server error when getting the response from ADFS. ADFS is sending what looks an awful lot like a properly formatted JWT, but the data is unrecognizable. This leads me to suspect that the entire JWT is encrypted, but I don't see a way (i.e. no command-line option) to tell OAuth2 Proxy that the ADFS server's encryption certificate is XYZ.

Since this is all test setup with nothing sensitive, I'm putting the relevant log entry from OAuth2 Proxy here:
[2021/10/28 12:55:31] [oauthproxy.go:862] No valid authentication in request. Initiating login.
10.10.3.5:51650 - 52c369f3-05f3-4728-8048-8a20d525c174 - - [2021/10/28 12:55:31] ubuntu-a.arisia.net:4443 GET - "/" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0" 403 8098 0.000
10.10.3.5:51650 - 95dcecdf-b2fe-4e48-bb8e-6693e551c323 - - [2021/10/28 12:55:35] ubuntu-a.arisia.net:4443 GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0" 302 312 0.000
10.10.3.5:51668 - 6732efa3-9e07-44a7-8090-088b1d28b9f6 - - [2021/10/28 12:59:35] ubuntu-a.arisia.net:4443 GET - "/oauth2/callback?code=DZHxj6CrmU-gNp47Lo5DWQ.ffGlpzOa2QgHAFYNjdCkUf_Ka2I.MZwzzVgT22WcQriZzJ3ieGJuZsTpNlnX18SPWF8koeAQM1iXrrsMf0K0cjYq0onIig-LUcdj8tMwFyRgj5A4gUj59XjTMCqhu17NpH1ZGo4PXbFj4wMnPVtjiz3V-q4qGHMXtyFiVFmD7dYafKM0EL1Ffz6LQ3lml-hG-DIHuiZABcrP1aaQAkPXswCI4SRNM8gSfHRxqRyHemu8Bb7FReZkvTnRym5DTnBax8mVsD7aqjLGZJDC5jGkKxXsaQkuRda89t58D8gtu5Yzzmi0bI1Nn7kBzFn1FPGoP4DxBN9Gc2ibVdqH9W8UZyQx5fFZXWcj-zAthwpLjFkGsIPMew&state=e79mtEcjk5wneXC2wau6Do6Ib_e4Yenk5xfT_kweVlY%3A%2F" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0" 500 2844 0.000

In addition to the log, there is an error message sent to the console that is inexplicably not written to the log:
[2021/10/28 12:59:35] [oauthproxy.go:723] Error redeeming code during OAuth2 callback: token exchange failed: Post "": unsupported protocol scheme ""

command line:
./oauth2-proxy --config=/home/jack/oauth2-proxy/oauth2-proxy.cfg --provider=adfs --client-secret=AS7Au60aE03cbkek73f1zWklc-0zw0uKx2KXfr_D --client-id=82116eaa-c2b2-472e-b021-751234b8587b --cookie-secret=sodlwQGtxSxUYs8A6isAl6e6ukU65hTrKWS7ey2xLzQ= --https-address=:4443 --login-url=https://arisia.net/adfs/oauth2/authorize/ --upstream=http://ubuntu-c.arisia.net/kc-test/ --scope="openid" --logging-filename="/home/jack/oauth2-proxy/log.txt"

Config file attached

## Context

Trying to implement SSO using ADFS as an identity provider

## Your Environment

Ubuntu 20.04 in a VM (VMWare Workstation)

- Version used:
7.2.0
(however, had pretty much the same kind of error in 7.1.x using oidc as the provider)
[oauth2-proxy.cfg.txt](https://github.com/oauth2-proxy/oauth2-proxy/files/7436351/oauth2-proxy.cfg.txt)

**Comment by NickMeves** [comment]
I caught a bug looking at the ADFS code but didn't get my PR merged before 7.2: https://github.com/oauth2-proxy/oauth2-proxy/pull/1247

I don't use ADFS, so I can't comment on its behavior in practice. Maybe the original author of the Provider has ideas on what you are experiencing? If I recall this is a brand new provider in 7.2

**Comment by JackLThornton** [comment]
It appears that what ADFS is returning is not an access token, but an authorization code. ADFS is expecting to get a second call to the /token endpoint with the code it returned in order to provide the access token. I tried setting the "--redeem-url" to that endpoint, but ADFS then complains that it isn't getting a valid secret passed in. How do I make OAuth2 Proxy go back to ADFS to exchange the authorization code for an access token?

**Comment by JackLThornton** [comment]
And yes, this is a new provider in 7.2; however, I experience the same behavior in 7.1 using the generic "OpenID Connect" provider

**Comment by JoelSpeed** [comment]
I think the issue in the below line is that you haven't got a redeem URL set, so adding that is the right step.
```
[2021/10/28 12:59:35] [oauthproxy.go:723] Error redeeming code during OAuth2 callback: token exchange failed: Post "": unsupported protocol scheme ""
```
When you add this and you don't get a valid secret, that suggests that your client secret that you are passing to OAuth2 Proxy isn't valid for the client ID on ADFS, can you double check/generate a new token to use for this client? Can you post the additional errors you get when you set the redeem URL?

**Comment by afeedh** [comment]
@JoelSpeed I had faced a similar issue recently and it seems like after setting the redeem URL it does authenticate and posts the authenticated session details in the log. However I'm seeing a different error (status code: 502) when the `/oauth2/callback` call is made after authenticating. Is this an error from the ADFS?

**Comment by v01d-bak3r** [comment]
It kind of works now after increasing the proxy_buffer_size but now seeing a 500 Internal server error after getting redirected back to the original URL. Can still see in the logs that the session has been authenticated.

**Comment by JoelSpeed** [comment]
@gyurco If you haven't already, please make sure the oidc-issuer-url option is set, otherwise please raise an issue for the ADFS provider being broken and include some logs to help indicate what exactly isn't working

**Comment by will-freshworks** [comment]
Also getting this with `provider="azure"` on v7.3.0. Dropping to v7.2.1 fixes the issue. Here's my .cfg file:
```
http_address="http://0.0.0.0:80"
upstreams=["http://api"]
redirect_url="http://localhost:4300/oauth2/callback"
cookie_secret="secret"
cookie_secure="false"
email_domains="*"

provider="azure"
client_id=...
client_secret=...
oidc_issuer_url=...
```

**Comment by gyurco** [comment]
@JoelSpeed oidc-issuer-url is set. I'll try to collect some logs (but I don't manage the Windows side).
