### ISSUE TITLE
[Question] Does it support blacklist/whitelist specific users for specific domain?

### ISSUE THREAD

**Issue by yongzhang** [oauth2-proxy/oauth2-proxy#1431]
Hi

I’m using oidc provider, all users are granted access to the oidc connector at provider side, I’m not sure if I can limit user access at domain layer, for example, only allow user1@myemaildomain.com to access https://myservice.mydomain.com?

**Comment by NickMeves** [comment]
There's options to restrict access based on the group/role or more broadly based on the email domain, but not on the individual user.

**Comment by jboesh** [comment]
May I ask why you can't whitelist 1 user? but only an entire domain eg?

does this apply to all oath providers?

**Comment by JoelSpeed** [comment]
There is the authenticated emails file option, I've not used it myself but I think that allows you to limit to specific emails
