### ISSUE TITLE
Correction in documentation about openid integration

### ISSUE THREAD

**Issue by ThomasKalten** [oauth2-proxy/oauth2-proxy#1432]
A small irritating name exchange:
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#openid-connect-provider

## Current Behavior

The oidc_issuer_url is based on URL from your Authorization Server's Issuer field in step 2, or simply https://corp.okta.com . The client_id and client_secret are configured in the application settings. Generate a unique **client_secret** to encrypt the cookie.

## Possible Solution
The oidc_issuer_url is based on URL from your Authorization Server's Issuer field in step 2, or simply https://corp.okta.com . The client_id and client_secret are configured in the application settings. Generate a unique **cookie_secret** to encrypt the cookie.

**Comment by ThomasKalten** [comment]
If someone would give me write access, I could change it ... but giving write access would take longer then changing the this one word directly.

**Comment by JoelSpeed** [comment]
Anyone is able to update our docs, you just need to submit a PR for review, no need to have write access for that. If it is just one word that needs changing, this can even be done from GitHubs web UI

**Comment by ThomasKalten** [comment]
Done. PR created.
