### ISSUE TITLE
Final redirect after code redemption is not original page requested

### ISSUE THREAD

**Issue by krenaut62** [oauth2-proxy/oauth2-proxy#1435]
after code redemption, user is not redirected back to original page requested.  The observed behavior is:

1) unauthenticated user navigates to page: https://hostname/secure/index.html
2) user is redirected to OIDC provider and authenticates
3) user is redirected back to callback URL
4) code is redeemed
5) user is redirected to: https://hostname/

The expected behavior is:

1) unauthenticated user navigates to page: https://hostname/secure/index.html
2) user is redirected to OIDC provider and authenticates
3) user is redirected back to callback URL
4) code is redeemed
5) user is redirected to: https://hostname/secure/index.html

## Your Environment

- Version used: v7.2.0

**Comment by ianroberts** [comment]
Are you using oauth2-proxy as a reverse proxy, or as a "sidecar" via the nginx auth-request mechanism or similar?  Can you share your configuration (excluding any sensitive data like client secrets), including on the nginx side if you're using that mode?
