### ISSUE TITLE
Skip aud check in token on Authorization header in the request when aud claim is missing

### ISSUE THREAD

**Issue by torsrex** [oauth2-proxy/oauth2-proxy#1437]
We would like to skip checking the `aud` claim in a token sent in the Authorization header of a request to the oauth2-proxy using an optional runtime parameter.

## Expected Behavior
When `--skip-jwt-bearer-tokens` and `--skip-aud-check-when-missing` are set, a request containing a token in the Authorization header which is missing the `aud` claim should pass through the oauth2-proxy successfully.

## Current Behavior
Setting `--skip-jwt-bearer-tokens` only leads to the `aud` check in the oauth2-proxy to fail due to the missing `aud` claim in the token.

## Possible Solution
This PR in its initial form shows a possible solution by adding the `--skip-aud-check-when-missing` runtime parameter: https://github.com/oauth2-proxy/oauth2-proxy/pull/1204

## Context
We're using the oauth2-proxy together with Istio to provide cluster-wide authentication. An ext_authz Envoy filter is used to check each request against the oauth2-proxy to authenticate the user against Azure AD. The setup is similar to what is described here: https://www.jetstack.io/blog/istio-oidc/

We would also like to use system-to-system authentication where the request entering the cluster will have the Authorization header set. We're using the `--skip-jwt-bearer-tokens` flag to pass these tokens through the oauth2-proxy. However, this token does not have the `aud` claim set, which leads to the oauth2-proxy failing. We will be performing additional checks using Istio's `requestAuthentication` resource https://istio.io/latest/docs/reference/config/security/request_authentication/ which will check the signature of the token. The OpenPolicyAgent may also be used to check additional claims in the token.

This PR https://github.com/oauth2-proxy/oauth2-proxy/pull/1204 in its initial form added a flag `--skip-aud-check-when-missing` which fits our use case perfectly, however, this flag was removed due to review comments.

-> Would it be possible to add back the `--skip-aud-check-when-missing` flag?

## Your Environment

- Version used:
Oauth2-proxy: v7.2.0
OpenShift: v4.7.33
OpenShift Service Mesh: v2.0.8
Open Policy Agent: v0.32.1-envoy-1

**Comment by JoelSpeed** [comment]
Is it possible to add an `aud` claim to the token? Or possible there is some other token parameter that could be substituted? We are working to add support for multiple providers, and in doing so, will make the extra JWT issuers option just additional validate only providers, in which case, you'd be able to configure the user claim to some field other than the audience, which I think would resolve your issue

**Comment by JoelSpeed** [comment]
Just been looking through some of our other issues, and we seem to already be tracking this with #891, could you check that this is the same feature request and close out this issue. There is already a PR open to implement the request, which is being reviewed

**Comment by torsrex** [comment]
We solved this on our end by using Istio CUSTOM actions with the `AuthorizationPolicy` resource to only forward the request to the oauth2-proxy if an authorization header is not present on the request, or if it is malformed, thus bypassing the oauth2-proxy for system-to-system calls. Instead, we are validating the JWT signature using Istio's `RequestAuthentication` resource, and performing additional checks using OPA policies.

This seems to be similar to #891 so this issue can probably be closed.
