### ISSUE TITLE
Document/sketch OAuth2-Proxy authentication flow 

### ISSUE THREAD

**Issue by karlschriek** [oauth2-proxy/oauth2-proxy#1438]
My colleagues and I are currently trying to form a detailed view of how the OAuth2-Proxy authentication flow works, and in particular:
- Which endpoints are called when, and how this differs between NGINX and Istio
- Which requests/responses are sent when? What goes back to the browser, what gets sent between oauth2-proxy and the IdP? What gets sent between oauth2-proxy and Istio/NGINX? etc.

It would be very helpful to have a detailed diagrammatic representation of how this communication works.

## Expected Behavior

We would like a detailed diagram in the oauth2-proxy docs.

## Current Behavior

Currently there is only this, which is extremely simple and hides a lot of complexity:
![bd040b7a-0d6a-11e5-85b9-f8d953d04f39](https://user-images.githubusercontent.com/25316920/140295394-ceda1dbd-7b97-428e-b47e-b7341e40add4.png)

## Possible Solution

I have done some reverse-engineering to figure out the flow of requests between browser, nginx-ingress, oauth2-proxy and (google) IdP. I've done this in diagrams.net. The diagram is shared (and editable) here: https://drive.google.com/file/d/1LmTWZPwTW-NQaxCPVq5FsKd9ZjJsqZVO/view?usp=sharing

Here is a JPEG of the diagram at the time of opening this issue
![oauth2-proxy (2)](https://user-images.githubusercontent.com/25316920/140295874-caab93e9-e6db-4cae-8463-1428dd3941fd.jpg)

The above is my understanding of how the auth flow would work in combination with the NGINX auth_request directive. I think the differences will be minor (but important) without this directive, so I would like to first focus on this and get a clear picture. Note that I have never contributed to oauth2-proxy and my only experience with it is by implementing it in order to perform OIDC authentication in various Kubernetes setups. 

Could someone who has more indepth knownledge take up a review / improve the diagram?

**Comment by JoelSpeed** [comment]
I've just had a read through the diagram and to be honest, it looks really good! I don't think there's much if anything I would want to change/add. 

I think the login flow is accurately captured, and while there are other flows we might want to document (eg refresh flow), I think I'd probably leave this one as is.

I think we should try to embed this diagram within the product docs somewhere

**Comment by AndrewNiven1** [comment]
Thanks for this diagram - my team and I found it extremely helpful in understanding what's going on with our ingresses. Did this ever get merged in a different PR?

**Comment by JoelSpeed** [comment]
It would be good to include these kinds of flow diagrams into the documentation. This was originally written on draw.io, does anyone know, is there a way to export the diagram to some version controllable resource that we can then generate into an image?

**Comment by braunsonm** [comment]
> is there a way to export the diagram to some version controllable resource that we can then generate into an image?

Yes, on draw.io you can export the XML of the image for editing later which could be added to Git. @JoelSpeed

**Comment by JoelSpeed** [comment]
Sweet, that sounds good, we should definitely get this into the docs then
