### ISSUE TITLE
Unable to authenticate to Kibana with basic auth

### ISSUE THREAD

**Issue by gianlucapisati** [oauth2-proxy/oauth2-proxy#1440]
## Expected Behavior

Loggin in Kibana with Basic auth

## Current Behavior

I obtain a 401 and a subsequent redirect to oauth2_proxy login page.

## Context
This is not a bug for sure, I'm just asking help as I can't configure Oauth2_proxy with Kibana.
This is my configuration:

- oauth2_proxy running on port 4180
- nginx listening on 80/443 with a proxy pass to localhost:4180 (oauth2_proxy)
- oauth2_proxy that performs the SSO with localhost:8080 as upstream (nginx)
- nginx listening on 8080 with a proxy pass to localhost:5601 (kibana)

Here the conf file:

**oauth2_proxy launch string**
```
oauth2-proxy  
    --email-domain="example.com"  
    --upstream="http://127.0.0.1:8080/"  
    --approval-prompt="auto"  
    --redirect-url="https://example.com/oauth2/callback"  
    --cookie-secret=redacted
    --set-xauthrequest=true 
    --pass-user-headers=true 
    --pass-authorization-header=true
```

**oauth2_proxy.conf**
```
server {
    listen 443 ssl;
    server_name example.com;

    location / {
      proxy_pass http://127.0.0.1:4180;
    }

    [letsencrypt config omitted]
}
```

**kibana.conf**
```
server {
    listen 8080;

    location / {
      proxy_pass http://127.0.0.1:5601;

      set $auth_string  "${remote_user}:<my_strong-password>";
      set_encode_base64 $encoded_string $auth_string;

      proxy_set_header Authorization "Basic $encoded_string";

      #to manage logout redirect
      rewrite /login https://example.com/oauth2/sign_in redirect;
    }
}
```

`${remote_user}` is empty, how can I valorize it?

Do you see any obvious errors?

**Comment by JoelSpeed** [comment]
This is more an nginx question than OAuth2 Proxy, but you need to take the value of `X-Forwarded-User` (set by OAuth2 Proxy) and make that into the value of your variable, how you do that I don't know, I'd suggest checking the nginx docs
