### ISSUE TITLE
Multi-arch container image binary is built for the wrong architecture

### ISSUE THREAD

**Issue by devon-mar** [oauth2-proxy/oauth2-proxy#1442]
The binary in the `v7.2.0` multi-arch container image is compiled for the wrong architecture.
The `v7.2.0-armv6` tag has the correct architecture.

## Expected Behavior
The binary is built for armv6.

```
$ file oauth2-proxy
oauth2-proxy: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=0oyzJKEXcQ140CHG8nI2/a_PJ-5RgfNT14hi9TApV/7QScZzSD4FsTnnfsHRSF/FMCEBBO5LZl9kyAngJy4, not stripped
```

## Current Behavior

The binary in the `armv6` manifest is built for x86_64.
This bug occurs when pulling from the `v7.2.0` tag, but below I pulled using the sha256 just to be sure.
```
$ docker run -it --entrypoint sh -d  --rm quay.io/oauth2-proxy/oauth2-proxy@sha256:3ff0bf5feaf51d53fd0a9d616ae8efa3d857dd8f6641f6fdd4d5bac92e9ffc34
94ece642d486d951be629ab77e499ee4d6a628bbd0abddbd482cf2d1780be717
$ docker cp 94ece642d486d951be629ab77e499ee4d6a628bbd0abddbd482cf2d1780be717:/bin/oauth2-proxy ./
$ file oauth2-proxy
oauth2-proxy: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=Hs1VAqSM5Ck5mHkUfgmv/7FxoD16obuWPIbOUYaP8/zpskzI6etXPtFtk3sjRw/_L2y9XsB4GCxaTc56Fj-, not stripped
```

## Steps to Reproduce (for bugs)

1.  Pull and run the oauth2-proxy v7.2.0 container on an arm machine
2.  The following occurs
```
$ docker run --rm quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
standard_init_linux.go:228: exec user process caused: exec format error
```

## Context

I'm trying to run oauth2-proxy on an arm machine.

## Your Environment

- Version used: v7.2.0
- `Docker version 20.10.8, build 3967b7d`

**Comment by JoelSpeed** [comment]
Apologies for this, I did some work on the dockerfile recently and had thought I had tested it, but I guess my testing method gave me a false positive. I see there's a fix already raised, let's merge that once there's a changelog entry

**Comment by devon-mar** [comment]
@JoelSpeed Are you able to push a new image to quay.io?

**Comment by JoelSpeed** [comment]
I'm looking at doing a 7.2.1 release in the next week or so as we close out a few small bugs, I'll wait until that's done.

For now, you can use the arch tagged image `v7.2.0-armv6`

**Comment by alekc** [comment]
@JoelSpeed latest chart version is still referencing 7.2.0 requiring an override, you might want to bump those as well.

**Comment by JoelSpeed** [comment]
The helm chart is maintained by a separate group of folks, I expect they will get it updated in their own time
