### ISSUE TITLE
email-domain is not working in LinkedIn provider

### ISSUE THREAD

**Issue by jkandasa** [oauth2-proxy/oauth2-proxy#1443]
`email-domain` not working in LinkedIn provider.
##### root cause: 
wrong validation url, currently it is pointing to https://api.linkedin.com/v2/emailAddress 

##### error:
```
[2021/11/10 21:14:51] [internal_util.go:74] token validation request failed: status 404 - {"serviceErrorCode":0,"message":"Resource emailAddress does not exist","status":404}
[2021/11/10 21:14:51] [internal_util.go:69] 404 GET https://api.linkedin.com/v2/emailAddress {"serviceErrorCode":0,"message":"Resource emailAddress does not exist","status":404}
```

## Expected Behavior
validation stage should work as expected

## Current Behavior
failed on validation URL

## Possible Solution
Update validation url as https://api.linkedin.com/v2/me

## Steps to Reproduce (for bugs)
1.  setup a `email-domain` with a domain, example: gmail.com
2.  setup linkedIn provider

## Context
With this issue, can not use `email-domain` feature

## Your Environment
```bash
docker run --detach --name oauth2-proxy \
    --env  TZ="Asia/Kolkata" \
    --publish 9021:4180 \
    --restart unless-stopped \
    quay.io/oauth2-proxy/oauth2-proxy:v7.2.0 \
    --provider="linkedin" \
    --cookie-secure=false \
    --upstream="http://192.168.0.21:8080" \
    --http-address="0.0.0.0:4180" \
    --redirect-url="https://private-domain/oauth2/callback" \
    --cookie-secret="12345678" \
    --client-id="abcd" \
    --client-secret="abcd" \
    --email-domain="gmail.com"
```

- Version used: v7.2.0

**Comment by JoelSpeed** [comment]
Based on this issue, does the profile URL not also need updating? As it is pointing at the same email address endpoint?

**Comment by JoelSpeed** [comment]
This was recently updated by @wuurd, so I'm surprised it's not working. @wuurd can you weigh in here?

**Comment by jkandasa** [comment]
> Based on this issue, does the profile URL not also need updating? As it is pointing at the same email address endpoint?

@JoelSpeed Profile URL works ok. It returns email address
https://github.com/oauth2-proxy/oauth2-proxy/blob/7ed4e3c830f428f3a9d6028f11a5532c89a2927a/providers/linkedin.go#L79

##### LinkedIn endpoints
![image](https://user-images.githubusercontent.com/1004403/141651844-db7837dd-5fc1-462b-b501-b1fd08d9fdd2.png)

**Comment by JoelSpeed** [comment]
But if the profile URL is working, and we currently use the profile URL to validate, then it seems we don't need to update the provider right?

I don't understand right now where the error is coming from, perhaps you could explain why the `/emailaddress` path works for the profile URL but not the validate URL?

**Comment by jkandasa** [comment]
@JoelSpeed I do not understand, what is the issue with `/emailAddress`, in a quick view I see that we are passing some query parameters,
https://github.com/oauth2-proxy/oauth2-proxy/blob/7ed4e3c830f428f3a9d6028f11a5532c89a2927a/providers/linkedin.go#L79-L84

but in `validateToken` we do not pass those.
https://github.com/oauth2-proxy/oauth2-proxy/blob/7ed4e3c830f428f3a9d6028f11a5532c89a2927a/providers/internal_util.go#L53-L62

I didn't debug further it as the validation is working with `/me` url
