### ISSUE TITLE
How can I authenticate against my own gitlab instance?

### ISSUE THREAD

**Issue by 3e-maciej** [oauth2-proxy/oauth2-proxy#1449]
I am trying to configure oauth2_proxy to authenticate against my own gitlab instance.

in my config file I have:

```
provider = "gitlab"

login_url = "https://[my-gitlab-instance-domain]/oauth/authorize"
redeem_url = "https://[my-gitlab-instance-domain]/oauth/token"
validate_url = "https://[my-gitlab-instance-domain]/api/v4/user"
```

but it keeps redirecting me to https://gitlab.com (global one) not my own instance. I am using 7.2.0 version of oauth2_proxy in simple proxy scenario.
What is wrong with my config?

**Comment by jkandasa** [comment]
and if I am not wrong, I do not see the use of the following parameters in gitlab configuration
```
login_url = 
redeem_url = 
validate_url = 
```
