### ISSUE TITLE
Urgent help needed [AuthFailure] Invalid authentication via OAuth2: CSRF token mismatch, does having 2 oauth2-proxy pods without session stickiness  causes this issue?

### ISSUE THREAD

**Issue by r-kotagudem** [oauth2-proxy/oauth2-proxy#1450]
@NickMeves @JoelSpeed 
[AuthFailure] Invalid authentication via OAuth2: CSRF token mismatch, does having two oauth2-proxy pods without session stickiness  causes this issue?

does oauth2-proxy verify csrf cookie stored-in-memory?

**Comment by JoelSpeed** [comment]
@NickMeves is more of an expert on this than me, but as far as I remember, the CSRF token is stored in the state parameter and a cookie, so there shouldn't be an issue with having multiple pods running

**Comment by r-kotagudem** [comment]
thanks for clarifying this.
