### ISSUE TITLE
simultaneous ajax requests causing csrf cookie mismatch/not found in the middle of user activity in application due to expired refresh token

### ISSUE THREAD

**Issue by r-kotagudem** [oauth2-proxy/oauth2-proxy#1451]
@JoelSpeed @NickMeves 
currently with default cookie-expire for a week, this issue occurs. 

1. refresh token is valid for 24 hours
1. user login to application today and tomorrow before 23rd hour the application continue to be loggedin
2. at 24th hour, users clicks a tab in application which triggers multiple ajax requests, causes 403 forbidden error in browser(csrf cookie overwritten due to mulltiple login request at same time)

Would like to know how this is being addressed, 
Can we set oauth2_proxy cookie as session instead of persistent? this will help start a new session when user starts a new browser (instead of continuing about to expire session) and  login session will be active for next 24 hours.

We could not identify the issue  in testing and now some of production users are facing this issue. This is high priority for us to fix this issue. any help here is highly appreciated.

**Comment by r-kotagudem** [comment]
> @JoelSpeed @NickMeves currently with default cookie-expire for a week, this issue occurs.
> 
> 1. refresh token is valid for 24 hours
> 2. user login to application today and tomorrow before 23rd hour the application continue to be loggedin
> 3. at 24th hour, users clicks a tab in application which triggers multiple ajax requests, causes 403 forbidden error in browser(csrf cookie overwritten due to mulltiple login request at same time)
> 
> Would like to know how this is being addressed, Can we set oauth2_proxy cookie as session instead of persistent? this will help start a new session when user starts a new browser (instead of continuing about to expire session) and login session will be active for next 24 hours.
> 
> We could not identify the issue in testing and now some of production users are facing this issue. This is high priority for us to fix this issue. any help here is highly appreciated.

@JoelSpeed  could you pls provide your advise on this?

**Comment by r-kotagudem** [comment]
https://github.com/oauth2-proxy/oauth2-proxy/issues/1287

**Comment by yoavo-datricks** [comment]
Hi. This is kind of a big issue for us causing multiple APIs failures. It looks like the parallel API requests are corrupting the CSRF nonce. Any suggestions on why or how to workaround?

**Comment by r-kotagudem** [comment]
currently, we made oauth2_proxy cookie as session cookie (so cookie is not carried to next day and fail in middle of activity). 
since refresh token is valid for 24 hours

if browser is still open, Trigger  logout  from application before 24 hours is reached  
If browser is closed and reopened, it starts a new session valid for another 24 hours.
