### ISSUE TITLE
Accessing Multiple Resources?

### ISSUE THREAD

**Issue by davidcorrigan714** [oauth2-proxy/oauth2-proxy#1453]
We're using Azure AD and I've got oauth2-proxy setup in front of an app in k8s. Logging in works great but the access-token that's passed to the backend is only valid for Microsoft Graph, my app needs to access additional resources as well, say Outlook. To get a token for outlook I need to use the refresh token to then get a new access token that's valid for Outlook. From what I can tell there's currently no safe way to obtain a new access token for another resource through oauth2-proxy? I see a few ways to get the refresh token in some hacky ways through either decoding the cookie, or pulling it out of Redis but then it seems like I'd also hit the issue where a new refresh token can possibly be returned. Although with Azure AD I don't think it actually invalidate the old one so there might not be any race conditions, it still seems hacky to try and pull the refresh token directly from the cookie or Redis.

**Comment by JoelSpeed** [comment]
This is not something I'm experienced with, but just wanted to add that with our alpha options, there is a way now to get the refresh token out of the session via a header either injected for the upstream request or returned on the auth request depending on your setup
