### ISSUE TITLE
Google OIDC sign out

### ISSUE THREAD

**Issue by Mracobes9** [oauth2-proxy/oauth2-proxy#1456]
Hi. I try to implement log out function on my website by using /oauth2/sign_out  endpoint, But i compfused by rd parameter. Google oidc haven't end_session_endpoint in its openid metadata (https://accounts.google.com/.well-known/openid-configuration). What i should transfer as a rd parameter ?

**Comment by derekkite** [comment]
https://myaccount.google.com/permissions

The user would revoke permissions for the app. Not sure if that is what is needed.
