### ISSUE TITLE
Using --allowed-roles gives 403

### ISSUE THREAD

**Issue by MoatazAbdallh** [oauth2-proxy/oauth2-proxy#1457]
## Expected Behavior

I have the following configuration:
` "--provider=keycloak-oidc",

              "--client-id=xxxxx",

              "--client-secret=xxxx",

              "--upstream=xxxxx",
              "--oidc-issuer-url=xxxxxx",
              "--redeem-url=xxxxxx",
              "--redirect-url=xxxxxx",
              "--http-address=xxxxx",
              "--auth-logging=true",
              "--email-domain=*",
              "--cookie-secret=xxxx",
              "--standard-logging=true",
              "--auth-logging=true",
              "--request-logging=true",
              "--whitelist-domain=xxxxxxx",
              "--skip-provider-button=true",
              "--skip-jwt-bearer-tokens=true",
              "--pass-authorization-header=true",
              "--pass-access-token=true",
              "--pass-user-headers=true",
              "--allowed-role=realm-access-role",
              "--cookie-secure=false",
              "--scope=openid email profile",
              "--skip-auth-route=/health"`

## Current Behavior

Every time i try to hit endpoints got 403, and I am assured that my account has the realm access-role

**Comment by JoelSpeed** [comment]
Are there any logs or additional details you can add to tell us why this 403 might be being sent back? Do you mean you get 403 after being redirected back from keycloak?

**Comment by MoatazAbdallh** [comment]
Here is some logs extracted from oauth2_proxy server when i am trying to hit the endpoint, and i think this failure is thrown from oauth2_proxy

[AuthFailure] Invalid authorization via session: removing session Session{email:xxxxxuser:xxxxxx PreferredUsername:xxxxx token:true id_token:true created: expires:}

**Comment by JoelSpeed** [comment]
Can you provide a set of logs around this, there may be other log lines that detail what the errors are. This doesn't really give me much to go on right now

**Comment by MoatazAbdallh** [comment]
it seems that there is no --oidc-roles-claim or i don't know what i should use in the Token Claim Name in the User Realm Role Mapper in keycloak, i have made a workaround by using "groups" as Token claim name and used --allowed-group but i don't think this is a good idea

**Comment by priggad** [comment]
I'm also having the same issue. I'm running the proxy in a container - when the environment variable `OAUTH2_PROXY_ALLOWED_ROLES` is set to "" or is not defined at all then the proxy works as expected. If I add a client role to `OAUTH2_PROXY_ALLOWED_ROLES` in the format "client_id:role_name" as recommended by the documentation I get a 403 and the same log output as specified by @MoatazAbdallh .  I've inspected the access token provided by keycloak and can see this claim `'resource_access': {'client_id': {'roles': ['role_name']}}`.

I've had a look at the source code and the error message originates here: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L941. I'm not sure but I suspect the `authorize` variable is being set to false by `p.provider.Authorize(req.Context(), session)` (https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/provider_default.go#L113) because  `sessions.SessionState.Groups`  has not be set correctly . My reason for thinking this is because the log output is appended with data about the session but doesn't contain any data on groups as suggested by this: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/apis/sessions/session_state.go#L104 

Just for clarity, my log output:
`email@domain [2021/12/02 15:19:58] [AuthFailure] Invalid authorization via session: removing session Session{email:email@domain user:keycloakid PreferredUsername:username token:true id_token:true created:2021-12-02 15:19:58.876585694 +0000 UTC m=+4714.765634882 expires:2021-12-02 15:24:58 +0000 UTC}`

**Comment by juliohm1978** [comment]
Hi.

I'm having a similar issue. Interestingly, though, the Authorization Flow works fine in the browser, but I get that exact error using the Authoriztion header with a Bearer token.

`--skip-jwt-bearer-tokens` and `--extra-jwt-issuers` are configured as expected and they work with the plain oidc provider. But as soon as I switch to keycloak-oidc and add `--allowed-role=...`, this error shows up.

These are the online log messages that I get.

```
127.0.0.1 - 36fc6c30-4248-4cdd-8bcb-b1ad5e9469a4 - REDACTED [2021/12/03 05:03:34] [AuthFailure] Invalid authorization via session: removing session Session{email:REDACTED user:229e690f-7305-4d4e-9a60-459c155f8773 PreferredUsername:REDACTED token:true id_token:true created:2021-12-03 05:03:34.579524079 +0000 UTC m=+358.867853001 expires:2021-12-03 05:08:21 +0000 UTC groups:[REDACTED]}
127.0.0.1 - 36fc6c30-4248-4cdd-8bcb-b1ad5e9469a4 - REDACTED [2021/12/03 05:03:34] localhost:4180 GET - "/meuapp/api/users/" HTTP/1.1 "curl/7.80.0" 403 2808 0.001
```

**Comment by priggad** [comment]
I can confirm that I get the same behavior as @juliohm1978 - authorization flow via browser works as expected, sending a request with an Authorization: Bearer token (retrieved using client credentials flow) results in 403. I've looked at the log output and the issue definitely seems to be the `sessions.SesstionState.Groups` property - it gets populated with groups and roles during the authorization flow but only groups when using the Authorization: Bearer header in a direct request.
Authorization flow:
`[2021/12/03 08:34:52] [oauthproxy.go:862] No valid authentication in request. Initiating login.`
`domain@email [2021/12/03 08:35:04] [AuthSuccess] Authenticated via OAuth2: Session{email:domain@email user:keycloakid PreferredUsername:username token:true id_token:true created:2021-12-03 08:35:04.857903022 +0000 UTC m=+1944.540112235 expires:2021-12-03 08:40:04.857654082 +0000 UTC m=+2244.539863292 refresh_token:true groups:[/group_name role:client_id:role_name]}`

Authorization Bearer header: 
`email@domain [2021/12/03 08:34:35] [AuthFailure] Invalid authorization via session: removing session Session{email:email@domain user:keycloakid PreferredUsername:username token:true id_token:true created:2021-12-03 08:34:35.206153841 +0000 UTC m=+1914.888363053 expires:2021-12-03 08:39:35 +0000 UTC groups:[/group_name]}`

**Comment by r9labs** [comment]
Confirmed that this is still an issue with v7.2.0 using Client Roles, and Environment Variables.

**Comment by rekup** [comment]
This issue also seems to affect `v7.2.1`

**Comment by priggad** [comment]
Issue still relevant.

**Comment by dweber019** [comment]
I think this method https://github.com/oauth2-proxy/oauth2-proxy/blob/d34644e16072329ebe78cef362dbc2bce59edf5e/providers/oidc.go#L161 is missing in https://github.com/oauth2-proxy/oauth2-proxy/blob/d34644e16072329ebe78cef362dbc2bce59edf5e/providers/keycloak_oidc.go

**Comment by MrDeerly** [comment]
Can confirm the bug, what's the current status @JoelSpeed ?

**Comment by eformat** [comment]
this started working for me once i added in a client role mapper to my openid-connect client in keycloak
i added some debug into keycloak_oidc.go in a custom built image:
```
logger.Printf("getClientRoles: %s", clientRoles)
``` 
which returned null ... so was obvious what i was doing wrong. i added this:

![Screenshot from 2022-06-06 14-04-45](https://user-images.githubusercontent.com/712608/172092862-52334364-c0ed-4c5f-ab98-424a458b714f.png)

and used this as the argument to oauth2-proxy in my example.

```
- '--allowed-role=mlflow:admin'
```

**Comment by MrDeerly** [comment]
> this started working for me once i added in a client role mapper to my openid-connect client in keycloak i added some debug into keycloak_oidc.go in a custom built image:
> 
> ```
> logger.Printf("getClientRoles: %s", clientRoles)
> ```
> 
> which returned null ... so was obvious what i was doing wrong. i added this:
> 
> ![Screenshot from 2022-06-06 14-04-45](https://user-images.githubusercontent.com/712608/172092862-52334364-c0ed-4c5f-ab98-424a458b714f.png)
> 
> and used this as the argument to oauth2-proxy in my example.
> 
> ```
> - '--allowed-role=mlflow:admin'
> ```

Strange that this is fixing it for you. I have the mappers since day one and it doesn't work
![Screenshot from 2022-06-07 08-40-34](https://user-images.githubusercontent.com/33393789/172313109-1537b270-b375-43eb-a4e2-eb5c4a4a4fd5.png)

**Comment by priggad** [comment]
I also have always had a role mapper for the client in place and still get the same error.

**Comment by JoelSpeed** [comment]
Just as a heads up, I have very little time to work on this project at the moment. To get this bug resolved a keycloak user from the community will need to put some time in to work out what the issue is and then raise a PR to resolve the issue. Is anyone able to dedicate some time to it?

**Comment by JoelSpeed** [comment]
I don't have much insight, but my recommendation would be to try and intercept the ID Token data and profile URL data that we are fetching. If you can work out what data we are observing you'll have an easier time working out where exactly the code is broken I would expect. Maybe start from the providers package Keycloak provider and go from there

**Comment by MrDeerly** [comment]
Took me a while to debug this, above is the PR to fix the issue. :+1:
