### ISSUE TITLE
acess token verification fails

### ISSUE THREAD

**Issue by nbraun-wolf** [oauth2-proxy/oauth2-proxy#1458]
Hi, I am trying to send the token received from /oauth2/auth to a backend and verify it, but it's not working with the [recommended flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-tokens.) from azure.

I am able to do it with token acquired by the [msal](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview) library but not with tokens from the oauth2 proxy. I decoded both tokens and notices that they are different.

```bash
# msal header
{"typ":"JWT","alg":"RS256","kid":"redacted"}
# oauth2 proxy header
{"typ":"JWT","nonce":"redacted","alg":"RS256","x5t":"redacted","kid":"redacted"}
```
The payload is different as well. The one from the oauth2 proxy is missing the roles, for example.

Upon further investigation, I also notice that base64 reports invalid input when trying to decode the payload. When I do it with the msal token, it works.

```bash
$ echo $AD_TOKEN | cut -d . -f 2 | base64 -d
... base64: invalid input
```

**Comment by nbraun-wolf** [comment]
Using version 2 of the AD login provider also didn't help. It brought the same kind of unusable token,

```yaml
extraArgs:
  provider: oidc
  oidc-issuer-url: https://login.microsoftonline.com/<app-id>/v2.0
```

**Comment by JoelSpeed** [comment]
The tokens recieved by OAuth2 Proxy are ID Tokens typically, Microsoft has a different page for these and you should be able to validate these separately. If you need the roles, I think you may need to adjust the scope to request the roles to be injected into the ID Token, they may however already be there.

MS Docs: https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens

How are you getting the token out of OAuth2 Proxy? Depending on how you are getting it will determine whether you are currently using the access token or ID Token

**Comment by nbraun-wolf** [comment]
Hi, thanks for the response. I am asking for the token via endpoint `/oauth2/auth`. 

I think the roles are not there, but I am not sure, since base64 decoding failed. How would I change the scope? I guess this must happen somewhere at oauth2-proxy level.

**Comment by nbraun-wolf** [comment]
@JoelSpeed, is there another way of getting the access token other than /oauth2/auth and reading it from the header `x-auth-request-access-token`'? Based on the name it should be the access token though.

**Comment by bluebrown** [comment]
Is there no way to obtain the Access Token with this project? ID Token is not feasible.

**Comment by JoelSpeed** [comment]
If it's coming from the `x-auth-request-access-token` then yes, you've got the access token coming back, or at least, you should do

**Comment by bluebrown** [comment]
@JoelSpeed, 

> or at least, you should do

But its not the case. Any idea how to solve this?

**Comment by nbraun-wolf** [comment]
I think the issue is that oauth2proxy is indeed providing a real access token. But msal is using the id token in place of an access token. Hence the token from msal contains the roles but the access token from oauth2 proxy does not.

**Comment by bluebrown** [comment]
Closing this as it was solved by registering an api and use it as scope in extra args. Otherwise the token claims are modifed after signage which makes verification of the signature impossible.

https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis
