### ISSUE TITLE
Multi-tenancy proxy with Keycloak OIDC #2

### ISSUE THREAD

**Issue by awoimbee** [oauth2-proxy/oauth2-proxy#1462]
Hi,
Before anything, please read #739, it contains all the info needed, but got closed prematurely.
I have exactly the same use-case and issue as the OP of #739.
I too propose to implement the feature myself (but can't promise anything as I'm not proficient in Go).

My dream is to have a dedicated page like "Please enter tenant name:" and a shortcut like `https://internal-oauth2.example.com/oauth2/auth?tenant=weststainesmassiv` to fetch the tenant name before querying keycloak.
I have no idea if this is possible, I just know that it won't be easy since `ProviderData` (directly used by `OIDCProvider` in turn directly used by `KeycloakOIDCProvider`)  isn't multi-tenant friendly.

Are the maintainers OK to merge such a solution ?
Do you have any code snippet/partial implementation @a8m ?

PS:
I looked at completing the multi provider implementation but it's a totally different use-case (i.e. we don't want tenantA to have a big blue button "login with KeycloakTenantB")

**Comment by islam56naser** [comment]
Hi @awoimbee , I'm also facing the same issue and I'm thinking of implementing this myself but I'd like to know what the maintainers think

**Comment by JoelSpeed** [comment]
This isn't something we've considered and does make the keycloak logic spill outside of the normal bounds of the provider, so I'm a bit hesitant about suggesting we go ahead and implement this. Have you looked at all at the code or how this might be implemented to see how much we need to carry extra information around?

**Comment by awoimbee** [comment]
Hi @JoelSpeed,
I personally put this project on hold.
The big issue is that this project seems to have 2 distinct phases, a [configuration phase](https://github.com/oauth2-proxy/oauth2-proxy/blob/4f5efd4074098223aeee244b963dafa9cfd4924b/main.go#L57) then a [runtime phase](https://github.com/oauth2-proxy/oauth2-proxy/blob/4f5efd4074098223aeee244b963dafa9cfd4924b/main.go#L58). Calls to `/.well-known/` routes [are done in the configuration phase](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/validation/options.go). Multi-tenancy would require us to run these steps in the runtime phase.

Creating a new OIDC client on the spot, depending on the realm name, is no small feat.
But this feature would be absurdly cool.

**Comment by JoelSpeed** [comment]
That seems like a good analysis, I think we would need a major re-architecture of the project to be able to support this then.

This isn't something the maintainers of this project have a personal interest in (we are mainly just trying to make the project cleaner right now), so if anyone wants to experiment feel free, but otherwise, given the complexity, perhaps we say we won't do this?
