### ISSUE TITLE
OAuth2 Proxy client_credentials flow with AzureAD

### ISSUE THREAD

**Issue by gfrankel97** [oauth2-proxy/oauth2-proxy#1463]
## Expected Behavior
OAuth2 Proxy client_credentials flow should work whether or not the client App Registration has an associated Service Principal.

## Current Behavior
OAuth2 Proxy worked well with machine-to-machine using the [`client_credentials` auth flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) using an App Registration; however, upon creating a Service Principal tied to the same App Registration, `client_credentials` flow broke. The token generated by Azure at https://login.microsoftonline.com/getbeyond.com/oauth2/v2.0/token contains a `sub` key if the client App Registration has an associated Service Principal, which causes OAuth2 Proxy to start throwing 403s. I would expect the extra information provided in the token to be of no consequence to OAuth2 Proxy. 

## Possible Solution
Including an `--authenticated-emails-file=<PATH_TO_FILE>`, which contains the Object ID of the Service Principal tied to the client App Registration, fixes the problem. I was able to stumble across this solution courtesy of this [article](https://www.paraesthesia.com/archive/2020/09/03/setting-up-oauth2-proxy-with-istio/).

If this is the intended functionality, I feel it should be better documented. I am happy to provide more details. Barring this hiccup, this is a fantastic tool; much appreciation to the maintainers and developers.

## Your Environment

```
/bin/oauth2-proxy 
  --request-logging=true \
  --auth-logging=true \
  --standard-logging=true \
  --provider=oidc \
  --skip-jwt-bearer-tokens=true \
  --oidc-issuer-url=https://login.microsoftonline.com/<TENANT_ID>/v2.0 \
  --http-address=<LISTEN_HTTP> \
  --upstream=<UPSTREAM_HTTP> \
  --pass-access-token=true\
  --pass-authorization-header=true\
  --set-authorization-header=true \
  --authenticated-emails-file=/etc/emails/service-principals
```

```
OAUTH2_PROXY_CLIENT_ID
OAUTH2_PROXY_CLIENT_SECRET
OAUTH2_PROXY_COOKIE_SECRET
OAUTH2_PROXY_EXTRA_JWT_ISSUERS
```
environment variables are also set.

- Version used: v7.2.0

**Comment by JoelSpeed** [comment]
What is the content of the `sub` key when it is present, is it the user email?
The `sub` key, IIRC, is what we use for the user by default. You could change the `oidc-user-claim` as an alternate workaround I think
