### ISSUE TITLE
Question: Serviceaccount usage

### ISSUE THREAD

**Issue by gowrisankar22** [oauth2-proxy/oauth2-proxy#1464]
oauth2proxy is configured with serviceaccount in https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/deployment.yaml#L41. I'm trying to figure out what it's used for. can someone help ?

**Comment by JoelSpeed** [comment]
You'd be better asking this question over on the manifests repository, we are not responsible over here for how the code is deployed and the maintainers of the manifests will likely have a better answer for you
