### ISSUE TITLE
Mistake in a documention

### ISSUE THREAD

**Issue by dawidswiton** [oauth2-proxy/oauth2-proxy#1469]
## Expected Behavior
Documentation suggests that flag:
--allowed-group
should be used as enviroment variable:
OAUTH2_PROXY_ALLOWED_GROUP

But only OAUTH2_PROXY_ALLOWED_GROUPS is taken into account

## Current Behavior
Using OAUTH2_PROXY_ALLOWED_GROUP is **not** checking group restriction.
Using OAUTH2_PROXY_ALLOWED_GROUP**S** is checking group restriction.

## Possible Solution
Correcting documentation to keep it in sync with code or unifying flags with environment variables

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
Please read the section in the documentation about environment variables which explains how flags map to environment variables, it explains the behaviour that you are seeing

https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#environment-variables
