### ISSUE TITLE
[Question] Error creating session although the email is existing

### ISSUE THREAD

**Issue by forestm** [oauth2-proxy/oauth2-proxy#1470]
Hi

I was trying to secure our app by oauth2-proxy, and use our own oidc server.

From the oidc server's log, it shows the id_token generated successfully.
the payload in the id_token looks like 
`{
  "sub": "hello.world",
  "aud": "app1",
  "kid": "rsa1",
  "iss": "https://mycompany.com/iam",
  "name": "HelloWorld",
  "groups": [
    "group1",
    "group2"
  ],
  "exp": 1639127925,
  "iat": 1639041525,
  "email": "helloworld@mycompany.com",
  "jti": "4bdfe381-4d0d-42f5-a7ab-a472217edd6b"
}`

the whold token returned from oidc server is 
`{
    "access_token": "xxxxxxxxx",
    "token_type": "bearer",
    "refresh_token": "xxxxxxx",
    "expires_in": 75231,
    "scope": "app openid profile email groups",
    "jti": "286451ef-6ab4-4008-928c-25b02fe01fef",
    "id_token": "xxxxxxxxxxxx"
}`

But from oauth2-proxy pod's log, I got this error
`[2021/12/09 13:41:37] [oauthproxy.go:730] Error creating session during OAuth2 callback: neither the id_token nor the profileURL set an email
10.233.72.59:53890 - aa48a5bf7d793deed277a46c59e3b70c - - [2021/12/09 13:41:37] dev-gdsp-faas.gslb.dcnw GET - "/oauth2/callback?code=p7zbfsRzK7PrHx9fe8B5CDin&state=5OJbhfIW_OlL4yPW6QLklGrPuy9ICbTDZ9itJ9iDjVo:/?" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36" 500 2831 0.098`

I'm not sure how does the oauth2-proxy resolve the id_token?  
Or is there anything wrong with our own oidc server?

I was using the latest docker image (quay.io/oauth2-proxy/oauth2-proxy:latest)

Thanks

**Comment by JoelSpeed** [comment]
Could you share a sanitzed version of your configuration so that we can see what options might be affecting this?

**Comment by forestm** [comment]
I used these options as args in k8s deployment

- --provider=oidc
- --email-domain=domain.com
- --upstream=file:///dev/null
- --http-address=0.0.0.0:4180
- --auth-logging=true
- --silence-ping-logging
- --ssl-insecure-skip-verify=true
- --oidc-issuer-url=https://iamdomain/iam
- --client-id=oauth2-proxy
- --client-secret=oauth2-secret
- --cookie-secret=1234567891234567
- --cookie-samesite=none
- --cookie-path=/oauth2-proxy

By the way, the discovery endpoint of oidc (.../.well-known/openid-configuration) is opened.

**Comment by forestm** [comment]
I found the reason: 
1 I missed the email in the scope at the first time created the new oidc client
2 oidc server cached the token 
3 adding email into scope didnot work, because the oidc server still got the token from cache
4 then I cleared the cache, the issue fixed.
