### ISSUE TITLE
When the `aud` claim is wrong Bearer token authentication works but it does not interpret the groups field

### ISSUE THREAD

**Issue by jpc** [oauth2-proxy/oauth2-proxy#1472]
I am using Keycloak and I observe strange behavior when using Bearer tokens. The documentation mentions that you need to have `oauth2` in the `aud` claim but I initially missed it when updating the provider from `keycloak` to `keycloak-oidc`.

Without the proper `aud` claim oauth2-proxy still accepts the token as long as a group membership requirement is not specified.

When the `aud` claim does not contain `oauth2` the `groups` claim (and any other data encoded in the token) is silently dropped and never appears in the session object.

## Expected Behavior

As I understand it without a correct `aud` claim the authorization shouldn't work and the proxy should log a helpful error message.

## Current Behavior

The tokens are accepted even without a correct `aud` claim but they have limited functionality. 
The CreateSessionFromToken method (which should populate the session with data from the token) fails here:
https://github.com/oauth2-proxy/oauth2-proxy/blob/16a9893a19dfe832a1acc72af70b27d0150caa7f/providers/oidc.go#L210-L213 with an error: `oidc: expected audience "oauth2" got ["realm-management" "account"]` but this error message is hidden from the user which makes it very difficult to debug the issue.

## Possible Solution

If we made the error fatal it would be shown in the logs and the problem could be easily discovered.

## Context

I get the token for a CLI app using the Device Authorization flow (with scope 'offline_access'). The token I get (parsed on JWT.io) has a properly populated groups field.

## Your Environment

Keycloak
oauth2-proxy v7.1.3 (also tested on git master)
nginx which calls the `/oauth2/auth` endpoint

**Comment by jpc** [comment]
Ok, when cleaning up after my tests I've noticed I tested the `keycloak-oidc` provider on the master branch (it was not there in v7.1.3 yet). The same problem occurred in v7.1.3 but for the deprecated `keycloak` provider for which the whole code path copying things from access token claim to the session seems to be missing.

**Comment by JoelSpeed** [comment]
Just to clarify on your last comment there, are you saying that this isn't working for either the `keycloak` or `keycloak-oidc` providers?

How was it that you got the error out, was this from the logs? Have you tried `--show-debug-on-error` in this scenario?
