### ISSUE TITLE
Request to Enable Inject Request Header from Arbitrary Token Claim

### ISSUE THREAD

**Issue by jacky96623** [oauth2-proxy/oauth2-proxy#1475]
Hi there, may I ask if Oauth2 Proxy already supports injecting request header from arbitrary claim in token? If not, it would be greatly appreciated if this feature can be implemented.

## Expected Behavior

By using alpha config, I expect that Oauth2 Proxy will try to extract any claim from JWT and pass it to upstream if the claim exists. If the claim does not exist, then the header will not be injected.

## Current Behavior

By looking at https://github.com/oauth2-proxy/oauth2-proxy/blob/v7.2.0/pkg/apis/sessions/session_state.go#L127-L155, I think that the claims that user can extract are restricted to "access_token", "id_token", "created_at", "expires_on", "refresh_token", "email", "user" and "groups" only.

## Possible Solution

Maybe this can be implemented by looking at parsed tokens?

## Context

I was using Keycloak Gatekeeper (also known as Louketo Proxy) with Keycloak and there are some custom attributes which determine the accessibility of a user (not just forbidden or allowed, but more like distinguishing user's tier). Unluckily the stated proxy already sunset and the development team recommended its users to migrate to Oauth2 Proxy. So I really need this feature so that I could migrate from a deprecated project to a well-maintained one.

## Your Environment

- Version used: `oauth-proxy/oauth-proxy:v7.2.0`

**Comment by JoelSpeed** [comment]
We are working towards allowing this feature, though the maintainers currently have very little time to put towards the project so I can't suggest a possible timeline for this.

The upshot of the work to do here is:
- Add an option to allow additional claims to be extracted from the ID Token
- Using this new option, whenever a session is created within a provider, attempt to extract the required claims
- Store these extracted additional claims in a map within the session
- Teach the claim header injector to read from the additional map when the requested claim isn't on of the standard claims we have implemented

**Comment by JoelSpeed** [comment]
This is related to/dependent on #1148
