### ISSUE TITLE
Airgapped environment missing stylesheet.

### ISSUE THREAD

**Issue by CodeGlitcher** [oauth2-proxy/oauth2-proxy#1476]
We are using oauth2-proxy in a airgapped enviroment and the login page is missing its stylesheet.
We upgrade oauth proxy from version v7.1.3 to v.7.2.0
But the new version nolonger has its own stylesheet.
It is now downling this from cdn.jsdelivr.net. 
We cannot reach this domain from our server.
It is possible to include the stylesheet in the application itself rather then relaying on a 3rth party to supply the stylesheet

**Comment by JoelSpeed** [comment]
We can use golang embedding to embed the file, shouldn't be too difficult, worth a PR I reckon. Do you have time to help implement this?

**Comment by CodeGlitcher** [comment]
Never have done anything with go, but I have some time next weekend so I will give it a try
