### ISSUE TITLE
Integration of Openshift Provider

### ISSUE THREAD

**Issue by yeplaa** [oauth2-proxy/oauth2-proxy#1480]
Hello,

Indeed, i use currently https://github.com/openshift/oauth-proxy that is very integrated with Openshift but it has basic features with others providers.

I would like to know if it's planned to integrate Openshift as Provider.

Thanks

**Comment by JoelSpeed** [comment]
We don't have any active plans to integrate new providers at present and I'm not familiar enough with the authentication systems within openshift to suggest how we would integrate. Is there an identity provider running within openshift to integrate with? I would expect that to be keycloak if any?

**Comment by yeplaa** [comment]
@JoelSpeed by default on Openshift it's not keycloak used but historically Oauth provider embedded by Openshift. 

Bellow some specificities of openshift/oauth-proxy configuration with oauth provider embedded by Openshift : 
- the clientid option is the pod Serviceaccount name
- A client-secret-file option is used and setted with token SA content : /var/run/secrets/kubernetes.io/serviceaccount/token
- A openshift-sar option allow to manage access to GUI :
Ex : `- '-openshift-sar={"resource": "namespaces", "verb": "get", "resourceName": "<namespace>", "namespace": "<Namespace>"}'` So only the users with access to namespace are automatically authenticated on the GUI.

With openshift/oauth-proxy, we don't need to create/declare manually OIDC configuration for each GUI. No manual action is required when we deploy a new GUI to secure.
Do you known if this features are available in oauth2-proxy?

**Comment by JoelSpeed** [comment]
It sounds to me like what you're describing is more just a Kubernetes compatible authentication system. Kubernetes itself kind of acts as an identity provider, by generating service account tokens. You could set up Kubernetes service account tokens as an extra issuer with OAuth2 Proxy just validating the tokens based on the service account signing file, but Kubernetes is not an OIDC identity provider in and of itself.

There are existing projects, such as kube-rbac-proxy, that may be able to help with what you're looking for, though they don't handle the login element as there is no identity provider to log in against within Kube. If you want to have identity management you'll need something like Dex or Keycloak

**Comment by yeplaa** [comment]
@JoelSpeed The Oauth provider embedded by Openshift meets my needs. I would like used oauth2-proxy (because generic and usable with several OIDC) instead openshift/oauth-proxy as sidecar for using this Openshift features. But currently this specific features related to Oauth Openshift aren't available with oauth2-proxy.
