### ISSUE TITLE
feature request: support users without email addresses

### ISSUE THREAD

**Issue by bbigras** [oauth2-proxy/oauth2-proxy#1483]
## Expected Behavior

I'm using "login with Steam" to auth my users.
Steam doesn't provide the email addresses.
I would like to use oauth2-proxy.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by SpecialYang** [comment]
try to use `insecure-oidc-allow-unverified-email=true`.

**Comment by JoelSpeed** [comment]
We have an intention to overhaul the authorization mechanisms but haven't had the time to implement the changes just yet. When we do overhaul it, we will make all authorization optional so that emails will no longer be required

**Comment by bbigras** [comment]
> try to use `insecure-oidc-allow-unverified-email=true`.

Thanks, but I still got `Error creating session during OAuth2 callback: unable to extract email from userinfo endpoint: type assertion to string failed` with that.

**Comment by aslafy-z** [comment]
@JoelSpeed Can you please re-open this issue **and remove the `Stale` tag**? :see_no_evil:

**Comment by aslafy-z** [comment]
No stale please

**Comment by Sissi44** [comment]
Hello, any update for this issue ?

**Comment by JoelSpeed** [comment]
Apologies, no update, this will need some investment from an interested community member to drive it forward, it's unlikely to be prioritised by the maintainers

**Comment by aslafy-z** [comment]
Not stale

**Comment by mkjpryor** [comment]
I am also seeing this. In my case, it is with Keycloak.

**Comment by ebcFlagman** [comment]
We have the same issue here

**Comment by k-k-k-k-k-k-k-k** [comment]
To allow users who don't have an email address to sign in, I'm using `--user-id-claim=preferred_username`. 

`oauth2-proxy -h` says `--user-id-claim oidc-email-claim             (DEPRECATED for oidc-email-claim) which claim contains the user ID (default "email")`.

Hope that helps.
