### ISSUE TITLE
Redirecting with Keycloak OIDC not working

### ISSUE THREAD

**Issue by pbitante** [oauth2-proxy/oauth2-proxy#1484]
## Expected Behavior

I am using oauth2-proxy in front of an R application using Shiny and authenticating with Keycloak OIDC. I would expect by navigating to the app url that I am redirected to Oauth2's page, login with Keycloak, then redirect back to the app I am trying to reach.

## Current Behavior

I am able to get through the process up until being redirected back to my app. After logging in through Keycloak, I am brought back to a "404 Not Found" page. I can verify that I am authenciated through the oauth-proxy container's logs, and I have the _oauth_ cookies in my broswer. I am not sure what is configured wrong and preventing the app from being accessed. 

## Steps to Reproduce (for bugs)

A client and secret will need to be generated for the rocker image. In the docker compose images below, I have called the client "rocker"

1. navigate to localhost:12001
2.  authenticate using keycloak

## Context

The following can be placed in a docker compose file and brought up that way.

### Oauth2 Image ###

  oauth:
    image: quay.io/oauth2-proxy/oauth2-proxy
    ports:
      - "12001:12001"
    environment:
      - OAUTH2_PROXY_PROVIDER=keycloak-oidc
      - OAUTH2_PROXY_CLIENT_ID=rocker
      - OAUTH2_PROXY_CLIENT_SECRET=<keycloak-secret>
      - OAUTH2_PROXY_COOKIE_SECRET=<cookie-secret>
      - OAUTH2_PROXY_REDIRECT_URL=https://rocker/oauth2/callback
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://keycloak/auth/realms/master
      - OAUTH2_PROXY_REQUEST_LOGGING=true
      - OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR=true
      - OAUTH2_PROXY_ERRORS_TO_INFO_LOG=true
      - OAUTH2_PROXY_EMAIL_DOMAINS=<subdomain>
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:12001
      - OAUTH2_PROXY_UPSTREAM=http://rocker:12001
      - OAUTH2_PROXY_LOGIN_URL=https://keycloak/auth/realms/master/protocol/openid-connect/auth
      - OAUTH2_PROXY_REDEEM_URL=https://keycloak/auth/realms/master/protocol/openid-connect/token
      - OAUTH2_PROXY_PROFILE_URL=https://keycloak/auth/realms/master/protocol/openid-connect/userinfo
      - OAUTH2_PROXY_VALIDATE_URL=https://keycloak/auth/realms/master/protocol/openid-connect/userinfo

####################

### Shiny Server Image ###

  rocker:
    image: rocker/shiny-verse:latest
    ports:
      - 3838:3838

##########################

### Keycloak Image ###
  keycloak:
    image: jboss/keycloak:11.0.3
    ports:
      - 5005:5005
    environment:
      - KEYCLOAK_USER=user
      - KEYCLOAK_PASSWORD=password

######################

## Your Environment

Docker version: 4.0.1
Oauth2-proxy Version used: v7.2.0
Keycloak version used: 11.0.3

**Comment by kfox1111** [comment]
Not that it helps solve this issue, but maybe consider shinyproxy (https://www.shinyproxy.io/). It supports oidc directly, and dynamically runs shiny app instances. Has worked around the pesky R scalability problem on our servers too.

**Comment by pbitante** [comment]
Thank you for taking the time to look at our issue. We looked at shinyproxy before deciding on using oauth2-proxy for authenticating.

**Comment by JoelSpeed** [comment]
Once you've authenticated, it looks like OAuth2 Proxy is returning a 404 right? Can you see any logs inside the the upstream application that suggest whether it has been accessed or not?

I suspect your issue is that `OAUTH2_PROXY_UPSTREAM=http://rocker:12001` should be `OAUTH2_PROXY_UPSTREAMS=http://rocker:12001`. This option can be specified multiple times so gains a trailing S and becomes a comma separated list in the env

**Comment by pbitante** [comment]
Thank you, <a href="https://github.com/joelspeed">@JoelSpeed</a>!

By adding the "S" to my variable, I was able to authenticate and I was redirected to oauth2 with a 502 error. While it isn't the final result I was looking for, it certainly is a step in the right direction. Once again, thank you.
