### ISSUE TITLE
whitelist error messages in log when issue is actually nginx proxy_buffer_size setting 

### ISSUE THREAD

**Issue by scyto** [oauth2-proxy/oauth2-proxy#1485]
--edit--
Seems this was nothing to do with the whitelist despite the white list errors
https://github.com/oauth2-proxy/oauth2-proxy/issues/1485#issuecomment-999169916
---edit---

I am upgrading from v5 to 7.20, v5 works fine.

Seems there is a new whitelist feature (great idea!)

With 7.20 I am getting the following in the oauth docker container log

```
172.17.0.1:57202 - f8277041-81d5-4de8-8244-b10067f092e8 - - [2021/12/21 23:19:22] host.mydomain.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62" 401 13 0.000
[2021/12/21 23:19:22] [validator.go:77] Rejecting invalid redirect "https://host.mydomain.com/favicon.ico": domain / port not in whitelist
[2021/12/21 23:19:22] [director.go:85] Invalid redirect provided in X-Auth-Request-Redirect header: https://host.mydomain.com/favicon.ico
```
Which i think then is causing a 502 to be returned to the client by the nginx proxy.

I have tried various combinations of OAUTH2_PROXY_WHITELIST_DOMAIN as a docker env var
```
OAUTH2_PROXY_WHITELIST_DOMAIN = .
OAUTH2_PROXY_WHITELIST_DOMAIN = .mydomain.com
OAUTH2_PROXY_WHITELIST_DOMAIN = .mydomain.com:*
```

OAUTH2_PROXY_WHITELIST_DOMAIN appears not to work or i am mis-interpreting the documentation / other github issues i have read.

### auth params i use - this is an include file
```
auth_request /oauth2/auth;
error_page 401 = /oauth2/sign_in;

# pass information via X-User and X-Email headers to backend,
# requires running with --set-xauthrequest flag
auth_request_set $user   $upstream_http_x_auth_request_user;
auth_request_set $email  $upstream_http_x_auth_request_email;
proxy_set_header X-User  $user;
proxy_set_header X-Email $email;

# if you enabled --pass-access-token, this will pass the token to the backend
auth_request_set $token  $upstream_http_x_auth_request_access_token;
proxy_set_header X-Access-Token $token;

# if you enabled --cookie-refresh, this is needed for it to work with auth_request
auth_request_set $auth_cookie $upstream_http_set_cookie;
add_header Set-Cookie $auth_cookie;

# When using the --set-authorization-header flag, some provider's cookies can exceed the 4kb
# limit and so the OAuth2 Proxy splits these into multiple parts.
# Nginx normally only copies the first `Set-Cookie` header from the auth_request to the response,
# so if your cookies are larger than 4kb, you will need to extract additional cookies manually.
auth_request_set $auth_cookie_name_upstream_1 $upstream_cookie_auth_cookie_name_1;

# Extract the Cookie attributes from the first Set-Cookie header and append them
# to the second part ($upstream_cookie_* variables only contain the raw cookie content)
if ($auth_cookie ~* "(; .*)") {
    set $auth_cookie_name_0 $auth_cookie;
    set $auth_cookie_name_1 "auth_cookie_name_1=$auth_cookie_name_upstream_1$1";
}

# Send both Set-Cookie headers now if there was a second part
if ($auth_cookie_name_upstream_1) {
    add_header Set-Cookie $auth_cookie_name_0;
    add_header Set-Cookie $auth_cookie_name_1;
}

# proxy_pass http://192.168.1.38:8090; handled in each of the relevant sites enabled files by inclusion of this finclude file
# or "root /path/to/site;" or "fastcgi_pass ..." etc

```

### oauth locations
```
			  location /oauth2/ {
				proxy_pass       http://192.168.1.31:4180;
				proxy_set_header Host                    $host;
				proxy_set_header X-Real-IP               $remote_addr;
				proxy_set_header X-Scheme                $scheme;
				#proxy_set_header X-Auth-Request-Redirect $request_uri;
				# or, if you are handling multiple domains:
				proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
			  }


			  location = /oauth2/auth {
				proxy_pass       http://192.168.1.31:4180;
				proxy_set_header Host             $host;
				proxy_set_header X-Real-IP        $remote_addr;
				proxy_set_header X-Scheme         $scheme;
				# nginx auth_request includes headers but not body
				proxy_set_header Content-Length   "";
				proxy_pass_request_body           off;
			  }
```

## Context
I am new to version 7, so apologies if i have missed an env var I should have  used
I am using the azure provider, it has worked well on v5, now with the shift to v7 i am hitting this (which is expected)

## Your Environment

- Version used: 7.2.0
- Synology DSM 7.0 docker host
- nginx container as reverse proxy configured as per documentation
- not discounting i am an idiot and maybe didn't read something i should have?

![image](https://user-images.githubusercontent.com/11369180/147011301-a63fa2b4-5e73-4dbb-ad0f-7b2718e97247.png)

**Comment by scyto** [comment]
well dagnabit it was ```proxy_buffer_size``` that was the issue, upped the size in nginx and it solved it (i didn't spot the error in the log)

very confusing error messages though, throwing a whitelist error when it isn't a whitelist error?

**Comment by timyong80** [comment]
Hi @scyto 

May I know where did you set the proxy_buffer_size value? Is it a variable that you added to my_vhost.conf? I'm using bitnami/nginx 1.21.3. Currently, I'm getting a warning error in the pod log and according to the documentation here, it says increasing the proxy_buffer_size in nginx should resolve this.

[2021/12/23 00:50:31] [session_store.go:163] WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.

Thank you.

**Comment by JoelSpeed** [comment]
Just wanted to add a note that `OAUTH2_PROXY_WHITELIST_DOMAIN` is incorrect, it should have a trailing S, `OAUTH2_PROXY_WHITELIST_DOMAINS`, as it can be specified multiple times via the CLI

**Comment by scyto** [comment]
@timyong80 in the http section

```
http {

# standard http settings i picked up...
    default_type                            application/octet-stream;
    server_names_hash_bucket_size           128;
    resolver                                192.168.1.35 ipv6=off;
    sendfile                                on;
    server_tokens							off;
	tcp_nopush                              on;
    tcp_nodelay								on;
	underscores_in_headers                  on;
    client_body_buffer_size                 16K;
    client_header_buffer_size               1k;
    proxy_buffer_size						12k; 
#   client_max_body_size                   1m; #default
    client_max_body_size                    1024m; #might be needed for plex and emby
    large_client_header_buffers             4 4k;
    client_body_timeout                     120s;
    client_header_timeout                   120s;
    keepalive_timeout                       75s 20s;
    send_timeout                          	120s;

etc etc etc

}

**Comment by JoelBirlingmairBeastCode** [comment]
BTW the docs for command line options here 
https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#command-line-options

do not state that the command line argument `--whitelist-domain` can be specified multiple times.

Until reading your comment here
https://github.com/oauth2-proxy/oauth2-proxy/issues/1485#issuecomment-1000439179

> Just wanted to add a note that `OAUTH2_PROXY_WHITELIST_DOMAIN` is incorrect, it should have a trailing S, `OAUTH2_PROXY_WHITELIST_DOMAINS`, as it can be specified multiple times via the CLI

I did not know that I needed an 'S' on the end
