### ISSUE TITLE
Azure: Is it possible to use certificate as client credential?

### ISSUE THREAD

**Issue by kasbst** [oauth2-proxy/oauth2-proxy#1486]
Is there any chance this will be implemented? We are not allowed to use SPN secret credential due to internal company policies. We can use only SPN certificate credential.

[Previous issue was sclosed](https://github.com/oauth2-proxy/oauth2-proxy/issues/1272)
[PR was closed but not merged](https://github.com/oauth2-proxy/oauth2-proxy/pull/1293)

Thank you.

**Comment by JoelSpeed** [comment]
At the moment we have no intention of implementing this. The maintainers of this project are no longer running this application within our day to day jobs so our appetite to implement new features is relatively minimal at the moment.

If someone is willing to pick the PR back up, we should be able to find some time to review
