### ISSUE TITLE
Authentication with bearer tokens using GitHub provider

### ISSUE THREAD

**Issue by jacek-jablonski** [oauth2-proxy/oauth2-proxy#1499]
Hi,
I've set up some API behind oauth2_proxy, everything is working fine. But now I would like to create some browser-only application to use this API behind oauth2_proxy. I've seen the medium article about service-to-service authentication, but it was set up using oidc provider. As far as I know, Github isn't OIDC compatible.

So is it possible to set up a browser-only application with an authentication to oauth2_proxy with GitHub provider?

**Comment by StephenOTT** [comment]
Was researching a similar scenario -!: came across this issue that I think discusses a similar scenario? https://github.com/oauth2-proxy/oauth2-proxy/issues/962#issuecomment-750674340

**Comment by jacek-jablonski** [comment]
@StephenOTT thanks, it seems that related issue explains a lot.

**Comment by StephenOTT** [comment]
If you get it working please let me know!  Have a similar need to have openid login with GitHub idp

**Comment by jacek-jablonski** [comment]
@StephenOTT as far as I understand above issue it is currently not possible with GitHub, so I will not try anymore.

**Comment by StephenOTT** [comment]
@jacek-jablonski  the note reads:

>Coming up in v7, regardless of your provider, if you set the appropriate oidc-issuer related flags, there's a default implementation of CreateSessionFromToken if you happen to have a valid ID Token to use.

this would seem to suggest hat v7 ~would have had the features needed to make it ~work ?

**Comment by jacek-jablonski** [comment]
For me, it means that using OIDC related flags, you may configure another provider and make bearer tokens work. You still need valid ID token from OIDC issuer, GitHub doesn't provide ID Tokens.

**Comment by JoelSpeed** [comment]
GitHub isn't an OIDC compatible provider and, as you've said, doesn't provide ID Tokens. So at the moment I don't think we have any way for this to be implemented using GitHub as an identity provider

**Comment by brumhard** [comment]
Would it be possible to implement `CreateSessionFromToken` for the github provider using the `https://api.github.com/user` endpoint and caching the response for a given token somehow to not run into github API rate limits?

**Comment by JoelSpeed** [comment]
We typically don't create a session from the tokens as it's more of a machine to machine style communication, the expectation is that if we created a session, that would be tracked via a cookie.

We could in theory store the sessions locally, but then how would this work with HA? Do we need a distributed store for this? Not everyone wants to set one up

I'm not sure this can be done in an efficient way so that we don't keep hitting GitHub for the information
