### ISSUE TITLE
multiple upstreams? - oauth2-proxy as a central service for authentication in Kubernetes

### ISSUE THREAD

**Issue by masshysteria1** [oauth2-proxy/oauth2-proxy#1501]
Hey,

We'd like to use oauth2-proxy as a central service in our Kubernetes cluster to protect a few applications. Preferably have one pod of oauth2-proxy instead of one per namespace. 
I have seen some threads talking about path-based routing. What is the easiest way of doing this without path-based routing? is that the only way? 
We use NGINX-Ingress Controller on top to route the traffic to the relevant service.

Thank you!

**Comment by ckwalsh** [comment]
Take a look at https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/ . You can do this with the auth-url and auth-signin annotations, and taking advantage of shared cookies.

In my homelab, all my systems are given subdomains under "dev.foo.com", such as "mysite.dev.foo.com", and "project.dev.foo.com". I have configured kubernetes to serve oauth2-proxy under "oauth.dev.foo.com", and configured oauth2-proxy to use "dev.foo.com" as it's cookie domain.

In the ingresses I want to protect, I use the following:
```
    nginx.ingress.kubernetes.io/auth-url: "https://oauth.dev.foo.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth.dev.foo.com/oauth2/start?rd=https%3A%2F%2F$host$escaped_request_uri"
```

Note that unlike the example, I have hardcoded the domain. This is deliberate.

When a request is sent to "project.dev.foo.com", the headers are sent to my oauth2-proxy instance and authenticated. If auth fails, I am redirected to oauth.dev.foo.com for login, then back when it is complete. If auto succeeds, the request is appropriately forwarded

**Comment by masshysteria1** [comment]
@ckwalsh Thanks a lot!
But what about the oauth2-proxy config file - if several systems need to be redirected to their relevant upstream, what do you configure there?

**Comment by hevans-dglcom** [comment]
@masshysteria1 nothing - it passes the redirect url through the redirect flow automatically when you include the ?rd=https%3A%2F%2F$host$escaped_request_uri in the auth-signin snippet
