### ISSUE TITLE
How to test the proxy server locally

### ISSUE THREAD

**Issue by rusakov92** [oauth2-proxy/oauth2-proxy#1506]
Hello, I'm trying to setup and test this application locally on my Mac with docker but I can't figure out what exactly I do wrong in order to access the server. I'm running this command:
```
docker run -p 4180:4180 quay.io/oauth2-proxy/oauth2-proxy \
    --cookie-secure=false \
    --upstream="127.0.0.1:8181" \
    --http-address="127.0.0.1:4180" \
    --redirect-url="127:0.0.1:8181/oauth2/callback" \
    --cookie-secret=secret \
    --client-id=secret \
    --client-secret=secret \
    --email-domain="*" \
    --provider=facebook
```
But when I try to ping the proxy I don't get any response from the server on 127.0.0.1:4180. Any idea what I'm doing wrong?

**Comment by JoelSpeed** [comment]
Have you tried binding to all interfaces? I suspect the fact that you're binding to localhost is causing you issues here as you have to bear in mind that when running the application in Docker, the application has a separate network namespace.

Try setting `--http-address=":4180"` to bind to all interfaces

**Comment by rusakov92** [comment]
Hello, yes that worked, it is added as an example in how to setup [OKTA-localhost](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#okta---localhost) to use --http-address="0.0.0.0:4180". That solved my issue, I can now connect to the container and it looks like the server managed to create the access token as the cookie is now present.

Now I'm facing another issue, it looks like it does not send a request to the OKTA's API. Is there some way to debug this? Is it possible to see how the proxy is forwarding my requests?

This is what I run now to test this:
```shell
docker run -p 4180:4180 quay.io/oauth2-proxy/oauth2-proxy \
--provider="oidc" \
--redirect-url="http://localhost:4180/oauth2/callback" \
--oidc-issuer-url="https://dev-04314823.okta.com/oauth2/default" \
--upstream="https://dev-04314823.okta.com/" \
--email-domain="*" \
--client-id="secret" \
--client-secret="secret" \
--pass-access-token=true \
--cookie-secret="secret" \
--cookie-secure=false \
--skip-provider-button=true \
--http-address="0.0.0.0:4180"
```

**Comment by JoelSpeed** [comment]
How is the Okta API expecting to receive credentials? Is it expecting to receive the access token as authentication or the ID Token? You might need to use `--pass-authorization-header` to send the ID Token instead
