### ISSUE TITLE
Documentation lacks information on how to use custom templates

### ISSUE THREAD

**Issue by tareco** [oauth2-proxy/oauth2-proxy#1507]
## Expected Behavior

Documentation should state how to use the custom templates.

## Current Behavior

There is no information on how to actually use templates to customize the sign in page.

## Steps to Reproduce (for bugs)

No specific steps, information is just missing in the documentation pages.

## Context

I would like to be able to customize the look and feel of the sign in page to better match my application style.

## Your Environment

- Version used: v7.2.0

**Comment by tareco** [comment]
In the meanwhile.. I appreciate any help about templates. Thank you!

**Comment by JoelSpeed** [comment]
I would recommend taking a look at the html files in https://github.com/oauth2-proxy/oauth2-proxy/tree/master/pkg/app/pagewriter, there is one for the error page and one for the sign in page.
You should be able to customise these to fit with the style of your own application.

After that, you need to place them in a directory accessible by the oauth2 proxy application and pass the location as `--custom-templates-dir`, the names of the files should match those within the directory I linked above, `error.html` and `sign_in.html`

**Comment by JoelSpeed** [comment]
@cynthia-rempel This is a great suggestion, would you be interested in making a PR to the docs to add a new section about configuring these?

**Comment by ladislavrolnik** [comment]
We are using oauth2-proxy at the corp level I have figured out that there is no possibility to include <img src=""> into error.html because of redirection. CustomLogo is applicable only for sign_in.html....any way how to include custom-sign-in-logo for custom-error-logo???
Or coud someone lead me to some workaround?

**Comment by regmicmahesh** [comment]
@ladislavrolnik  we're storing image in s3 buckets to avoid this behaviour.
