### ISSUE TITLE
Redirecting to 404 after successfull authentication

### ISSUE THREAD

**Issue by oauth222** [oauth2-proxy/oauth2-proxy#1510]
Im using OAuth2-Proxy + Keycloak to manage access for an application on a local network for a project.
Unfourtunately OAuth2-Proxy is not redirecting me to my upstream but gives me a "404 page not found" from OAuth2-Proxy after successfully authenticating with keycloak.

I would greatly appreciate any help in solving this issue, as getting this working is crucial for my final university project!

## Expected Behavior

1. Visiting 192.168.0.7:4180 (OAuth2-Proxy) and clicking "Sign In" Button
2. Redirect to (192.168.0.7:8000) Keycloak login page, entering username and password correctly
3. (Authenticating with OAuth2-Proxy)
4. Redirect to upstream Application 192.168.0.7:8080

## Current Behavior

1. Visiting 192.168.0.7:4180 (OAuth2-Proxy) and clicking "Sign In" Button
<img width="614" alt="404_1" src="https://user-images.githubusercontent.com/97355893/148654207-9da5f06e-5296-450c-a2a6-c5ff64872119.png">
2. Redirect to (192.168.0.7:8000) Keycloak login page, entering username and password correctly
<img width="874" alt="404_2" src="https://user-images.githubusercontent.com/97355893/148654225-86828fc5-48a6-4f61-a0ef-b4e1c641b841.png">
3. (Authenticating with OAuth2-Proxy)

4. Redirect to 192.168.0.7:4180 with "404 page not found"
<img width="203" alt="404" src="https://user-images.githubusercontent.com/97355893/148654246-3e17fa7a-0a27-4b9f-bebf-bb26204920a5.png">

I can also see in Keycloak Admin Portal that the user "oauth2" is now signed in and the OAuth2 Logs also show that the authentication was successfull.

The Valid Redirect URL in Keycloak Admin Portal is: http://192.168.0.7:4180/oauth2/callback/*   , as i need to callback with OAuth2 correct?
So i'd like to know where is the problem and why i'm not being redirected to my upstream by OAuth2?

**OAuth2-Proxy Logs:**
`[2022/01/08 17:03:04] [oauthproxy.go:866] No valid authentication in request. Initiating login.
192.168.0.8:51356 - 8248df39-5e40-4ea5-9b58-07e92119df9b - - [2022/01/08 17:03:04] 192.168.0.7:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 403 8027 0.001
192.168.0.8:51356 - c7ea7fe9-07f5-4c85-8649-6784b23f5e81 - - [2022/01/08 17:03:05] 192.168.0.7:4180 GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 302 332 0.001
192.168.0.8:51356 - 31c4f7e7-437f-441e-8aeb-d36ed573e5c4 - oauth2@gmail.com [2022/01/08 17:03:10] [AuthSuccess] Authenticated via OAuth2: Session{email:oauth2@gmail.com user:656d90b3-c73e-445e-8d6b-7dc579be9b1e PreferredUsername:oauth2 token:true id_token:true created:2022-01-08 17:03:10.615787303 +0000 UTC m=+803.656461676 expires:2022-01-08 17:08:10.614940443 +0000 UTC m=+1103.655614761 refresh_token:true groups:[/oauth2]}
192.168.0.8:51356 - 31c4f7e7-437f-441e-8aeb-d36ed573e5c4 - - [2022/01/08 17:03:10] 192.168.0.7:4180 GET - "/oauth2/callback?state=RnOjR0AKVzHWtm5Ptcfb-bzLWc5L0vJMPLBjxB5yorE%3A%2F&session_state=74ed9ac3-b16f-4c29-b1e9-33921abb40b7&code=c9a15e05-5ccb-4a62-a926-d6f634b274a6.74ed9ac3-b16f-4c29-b1e9-33921abb40b7.da71a57c-37ca-4470-b78d-6a6bfbe38829" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 302 24 0.047
192.168.0.8:51356 - 4fbb8782-9112-4672-bc92-5c5d28d353fb - oauth2@gmail.com [2022/01/08 17:03:10] 192.168.0.7:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" 404 19 0.001`

### **OAuth2**

**OAuth2-Proxy Version:**
v7.2.1-arm64
**Image:**
quay.io/oauth2-proxy/oauth2-proxy:latest-arm64
**Ports:**
4180:4180
**Environment:**
-OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180 \
OAUTH2_PROXY_PROVIDER=oidc \
OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=Keycloak \
OAUTH2_PROXY_OIDC_ISSUER_URL=http://192.168.0.7:8000/auth/realms/oauth2-proxy \
OAUTH2_PROXY_CLIENT_ID=oauth2-proxy \
OAUTH2_PROXY_CLIENT_SECRET=*client-secret-placeholder* \
OAUTH2_PROXY_COOKIE_SECRET=OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w= \
OAUTH2_PROXY_COOKIE_SECURE=false \
OAUTH2_PROXY_EMAIL_DOMAINS=* \
-OAUTH2_PROXY_WHITELIST_DOMAINS=192.168.0.7:* \
-OAUTH2_PROXY_UPSTREAMS=http://192.168.0.7:8080/ \
-OAUTH2_PROXY_REDIRECT_URL=http://192.168.0.7:4180/oauth2/callback \

### **Keycloak**

**Keycloak Version:**
15.0.1
**Image:**
docker.io/mihaibob/keycloak:15.0.1
**Ports:**
8000:8080
**Environment:**
KEYCLOAK_USER=admin
KEYCLOAK_PASSWORD=admin 

Valid Redirect URL in Keycloak Admin Portal:
http://192.168.0.7:4180/oauth2/callback/*

### **Application**
**Ports:**
8080:8080

**Comment by JoelSpeed** [comment]
This looks to me as if the 404 may actually be coming from your upstream application, have you checked the logs of the application that's running on port 8080?

**Comment by yousri-meftah** [comment]
i have to same issue it gives me 404 and my url in upstream works fine

**Comment by tyriis** [comment]
i have the same behaviour after 1st login, i get redirected to oauth2-proxy / instead of the initial requested URL. After reloading/retry it is working as expected.
