### ISSUE TITLE
Cookie doesn't expire after time set?

### ISSUE THREAD

**Issue by masshysteria1** [oauth2-proxy/oauth2-proxy#1513]
Hey,

We have oauth2-proxy v7.2.0 on our K8S cluster. For some reason, even after setting `**cookie_expire = "12h"**, I never get redirected to authenticate again, as if the cookie doesn't expire. Full config:

  configFile: |-
    email_domains = "*"
    upstreams = [ "http://jaeger-query.jaeger.svc.cluster.local" ]
    provider = "azure"
    https_address = "0.0.0.0:4180"
    oidc_issuer_url= "https://sts.windows.net/82cb6975-449f-42bb-8f38-6eff0b821640/"
    redirect_url = "https://oauth2proxy.domain.com/oauth2/callback"
    cookie_domains = ".domain.com"
    whitelist_domains = ".domain.com"
    oidc_groups_claim = "groups"
    user_id_claim = "preferred_username"
    skip_provider_button = "true"
    set_authorization_header = "true"
    set_xauthrequest = "true"
    cookie_secure = "false"
    cookie_expire = "12h"

Any idea why?

**Comment by JoelSpeed** [comment]
Can you use the developer tools within your browser to see how long the cookie is valid for?

Also, I think the cookie expire settings are logged when OAuth2 Proxy starts, could you take a look at the first few log lines to see what it reckons the expire setting is?
