### ISSUE TITLE
Hash appended to URL when no hash is needed

### ISSUE THREAD

**Issue by omBratteng** [oauth2-proxy/oauth2-proxy#1515]
When I go to https://example.com/ and I'm presented with a login page, and after login, a hash is appended to the URL, making the URL after login: `https://example.com/#`

## Expected Behavior

No `#` is appended to the URL when not needed

## Current Behavior

A `#` is appended after login

## Your Environment

- Version used: 7.2.1

**Comment by JoelSpeed** [comment]
Can you provide more detail about your setup? 

What exactly is providing the redirect information for you? 

Do you have some other proxy in front?

Are you using the sign in button or skipping that and going straight to the identity provider?

**Comment by omBratteng** [comment]
It's behind an nginx proxy, which is begind a Azure Application Gateway ingress in k8s.
I'll see if I can extract the setup to a minimal where it still occurs, and share it.

**Comment by tareco** [comment]
I noticed this too and it breaks common php-fpm nginx configurations because the file cannot be found:
`https://example.com/test.php#`
> File not found.

**Comment by tareco** [comment]
It might had to do with the `location` groups I had in my case.

Currently it is not happening anymore, `rd` is filled with the `/` and after login I get redirect **without** the `#` route.

```
<form method="GET" action="/oauth2/start">
<input type="hidden" name="rd" value="/">
<p class="block">Authenticate using example.com</p>
<button type="submit" class="button block is-primary">Sign in with Google</button>
</form>
```

**Comment by omBratteng** [comment]
Oh, I've noticed it's not happening here either anymore. I could've sworn it was happing on `7.2.1`
