### ISSUE TITLE
Nginx Ingress controller and oauth2-proxy proxy mode, headers not passsed upstream

### ISSUE THREAD

**Issue by gkasturik** [oauth2-proxy/oauth2-proxy#1517]
Not seeing auth-response-headers in proxied requests.

Nginx config below
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-Email, X-Auth-Request-User, X-Forwarded-Access-Token"

Oauth-proxy config below

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=google
        - --upstream=XXXXX
        - --http-address=0.0.0.0:4180
        - --client-id=XXXXX
        - --client-secret=XXXXX
        - --cookie-domain=XXXXXX
        - --cookie-refresh=1h
        - --cookie-secret=XXXXXX
        - --email-domain=*
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --pass-user-headers=true
        - --ssl-insecure-skip-verify=true 
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy

**Comment by Aishwarya-Murahari** [comment]
Updating proxy-buffer-size: 16k in ingress config map worked for me.
data:
 proxy-buffer-size: 16k
