### ISSUE TITLE
Can anybody help? Something wrong, but I can't tell what...

### ISSUE THREAD

**Issue by xyzroller** [oauth2-proxy/oauth2-proxy#1523]
I am banging my head against the wall and hope someone can help. I am trying to use oauth2-proxy to provide login in front of an nginx webserver on the same host as oauth2-proxy and using GitHub as OAuth2 provider. The container with oauth2-proxy and nginx is sitting behind HAProxy doing TLS and forwarding to port 80 on my oauth2-proxy/nginx container.

## Current Behavior

The login flow seems to work,I log in to GitHub and authorize the application but then after logging in I get a "500 Internal Server Error" from oauth2-proxy.

The log says (Client ID redacted and domain name swapped for "example.com"):
```
[2022/01/25 19:46:22] [proxy.go:89] mapping path "/" => upstream "http://127.0.0.1:8080/"
[2022/01/25 19:46:22] [oauthproxy.go:148] OAuthProxy configured for GitHub Client ID: <REDACTED>
[2022/01/25 19:46:22] [oauthproxy.go:154] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:6h0m0s domains: path:/ samesite:none refresh:disabled
95.117.23.51 - 0a3951d0-aa37-42bd-bd88-1916d63ebec3 - - [2022/01/25 19:46:41] example.com GET - "/oauth2/sign_in?rd=%2F" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" 200 8030 0.003
95.117.23.51 - 6cc0fc5b-d1c0-4591-8d25-b6af28f184b0 - - [2022/01/25 19:46:43] example.com GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" 302 293 0.002
95.117.23.51 - 3d877c51-9303-42b4-8194-9451c0efafc8 - - [2022/01/25 19:46:43] example.com GET - "/oauth2/callback?code=19d0085d63f70785ee24&state=3lKJi4tchl0bD_g4Oq1IXT3WX5mSKOV_BPffVR8f3R4%3A%2F" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0" 500 2841 0.450
```

...so we see the 500 error there too.

This is my oauth2-proxy configuration (Secrets redacted and domain name swapped for "example.com"):

```
http_address = "0.0.0.0:80"
reverse_proxy = true
real_client_ip_header = "X-Forwarded-For"

provider = "github"
provider_display_name = "GitHub TEST"
redirect_url = "https://examle.com/oauth2/callback"
login_url = "https://github.com/login/oauth/authorize"
redeem_url = "https://github.com/login/oauth/access_token"
validate_url = "https://api.github.com/user"
client_id = "<REDACTED>"
client_secret = "<REDACTED>"

request_logging = true
auth_logging = true
standard_logging = true
logging_filename = "/tmp/oa2p.log"

upstreams = [
  "http://127.0.0.1:8080/" 
]

pass_access_token = false
pass_authorization_header = false
pass_basic_auth = false
pass_host_header = false
pass_user_headers = false

session_store_type = "cookie"
cookie_name = "_oauth2_proxy"
cookie_secret = "<REDACTED>"
cookie_samesite = "none"
cookie_secure = true
cookie_httponly = true
cookie_domains = ""
cookie_expire = "6h"
cookie_refresh = 0

```

I have toggled every variable (e.g. `pass_access_token`, `cookie_secure`, ...) in various combinations, always with the same result.

I have checked `curl http://127.0.0.1:8080" from the CLI on the machine and the website is returned. I have also added the following to the configuration to bypass the authorization flow and then the website works fine:

```
skip_auth_routes = [
  "^/"
]
```

This makes me conclude that nginx is set up properly.

I just can't see what is wrong. Can anyone give me a helping hand?

## Your Environment

- Version used: 7.2.1

**Comment by xyzroller** [comment]
More information...
If I set `show_debug_on_error = true` in oauth2-proxy.cfg, then I see the following under "More Info" on the error page:

```
unexpected status "404": {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Request ID: 4f752ad7-9db8-4c81-8553-0ba6777ebf09
```
So it looks like I get the error from some 404 response from GitHub.

**Comment by JoelSpeed** [comment]
One of your login/validate/redeem URLs is likely causing an issue here. I would suggest to double check those, I think it may be the validate as it doesn't have the API version in it which IIRC is normally a part of GitHubs URL scheme

**Comment by xyzroller** [comment]
That's it...
All I had to do was change `validate_url` to

```
validate_url = "https://api.github.com"
```
and now it works.
Thanks for the tip!

**Comment by xyzroller** [comment]
Just in case anybody finds this while searching for a solution to the same problem, a few other things to note to make the setup work properly:

- `pass_host_header = false` prevented relative links on the protected website from working properly, so it needs to be `pass_host_header = true`

- Using port 80 for the oauth2-proxy listening address and 8080 for upstream nginx on localhost also broke relative links on the webpage, so I had to change to port 4180 (the default) for oauth2-proxy and 80 for the upstream nginx. That is: 
    ```
    http_address = "0.0.0.0:4180"
    ...
    upstreams = [
      "http://127.0.0.1/" 
    ]
    ```
    (and the appropriate change to the backend definition in HAProxy to send traffic to 4180)

**Comment by xyzroller** [comment]
Closing again after adding the above comment.
