### ISSUE TITLE
Graphql Websocket Authentication

### ISSUE THREAD

**Issue by mjmonroe** [oauth2-proxy/oauth2-proxy#1524]
## Expected Behavior
We have a Graphql service behind oauth2-proxy v7.2.1. The normal HTTPS Graphql endpoints work as expected. Our Graphql service exposes a Graphql websocket endpoint. According to the oauth2-proxy documentation, after setting _--proxy-websockets_ to true, Graphql websockets should be reachable, assuming we pass the ___oauth2_proxy_ cookies.

When we bypass the oauth2-proxy and go directly to the service, websockets work as expected.

## Current Behavior
When we try and reach the websocket without setting the ___oauth2_proxy_ cookie, we receive a **200**, and a redirect to login to our IdP as expected. When we set a valid ___oauth2_proxy_ cookie, the proxy correctly validates the request, but we receive a **400 Bad Request**. The Graphql service does not log any errors. It appears that something other than the Graphql service is returning the 400.

Headers we passed in:
<img width="713" alt="Screen Shot 2022-01-25 at 3 01 30 PM" src="https://user-images.githubusercontent.com/9063378/151068507-a29cf4f6-2b47-4d03-a807-9bde4170c812.png">

## Possible Solution
Does oauth2-proxy look at _Sec-WebSocket-Protocol_ header? Graphql websockets use the _graphql-ws_ protocol, not the standard _ws_ protocol. 

## Your Environment
The Graphql service uses [Ariadne](https://ariadnegraphql.org/ ) and runs on a kubernetes cluster configured with a ngnix proxy.  

- Version used:
oauth2-proxy v7.2.1

**Comment by JoelSpeed** [comment]
>  Sec-WebSocket-Protocol

I don't think it does look at this no. I think we only support the standard `ws` protocol (and `wss`), so perhaps the 400 is because it can't identify the protocol, the code for this is all in pkg/upstream if you want to try and work it out from the code
