### ISSUE TITLE
documented defaults are overwritten when configuring other non-default provider options

### ISSUE THREAD

**Issue by cruwe** [oauth2-proxy/oauth2-proxy#1526]
First, thanks for developing `oauth2-proxy` and making your work available to the general public.

https://github.com/oauth2-proxy/oauth2-proxy/blob/4f5efd4074098223aeee244b963dafa9cfd4924b/pkg/apis/options/alpha_options.go#L56

Any defaults documented, such as _e.g._ `emailClaim`, are overwritten when other non-default options have been passed.
I suggest explicitly stating so, PR will follow.

Thanks for your work, cheers! Christopher

**Comment by JoelSpeed** [comment]
Well that's certainly not intended! Sounds like a bug in how we are implementing the defaulting there. Have you looked into the code at all to see why this is the behaviour?

**Comment by cruwe** [comment]
Sorry to be late replying. Please don't take it as lack of interest, but rather lack of time the last two weeks.

I did'nt get at first that this was a bug, although I should have thought about the possibility.

I stumbled on this behaviour when upgrading from 7.1.1 to 7.2.1 and, considering I use alpha-features, thought it fair that things may change in unpredictable ways and that perhaps implementations may be "incomplete". After all, it's _flagged_ alpha.

I've looked at the code and noticed fields being overwritten where I'd have thought of a deep-merge in left,right precedence, so to speak. Knowing now that you consider that to be bug, I'd be willing to pick that up and to the fix properly as you suggested.

Thanks for your comment!

**Comment by JoelSpeed** [comment]
> I've looked at the code and noticed fields being overwritten where I'd have thought of a deep-merge in left,right precedence, so to speak.

This sounds like what I had in mind before, seems like a good UX to me at least

If you have the time to look into how we can fix this, then that would be great, though i'm not sure how simple it would be :thinking: 

I have thought in the past about a `Default()` function that we could call on each structure in the options, once it's been loaded to set the defaults if they haven't already been set by the user. Not sure if there is a better way to do it though
