### ISSUE TITLE
Can't use oauth2-proxy windows prebuilt as binary service

### ISSUE THREAD

**Issue by MoatazAbdallh** [oauth2-proxy/oauth2-proxy#1530]
## Expected Behavior

I am trying to run oauth2-proxy as windows service by creating new service using sc.exe through the following command
` sc.exe create Oauth2 Proxy binpath= "\"xxx.oauth2-proxy.exe\" --config= \"xxx.config.cfg\"" `

and when i try to run it gives the following error

`Error: 1053 the service did not respond in a timely fashion service `

## Current Behavior

`Error: 1053 the service did not respond in a timely fashion service `

## Your Environment

Windows

- Version used:

7.2.1

**Comment by JoelSpeed** [comment]
You have to include special logic within Go binaries to enable them to run as windows services, we don't yet support this, but if you want to add it I'll happily review a PR for this
