### ISSUE TITLE
Special Okta workarounds welcome in `oauth2-proxy`?

### ISSUE THREAD

**Issue by askreet** [oauth2-proxy/oauth2-proxy#1532]
We're using `oauth2-proxy` with Okta in OIDC mode, based on the existing documentation. Works great.

We had some interest in getting group data as a header which y'all support natively. However, Okta is weird about it:

> If you make a request to the Org Authorization Server for both the ID token and the access token, that is considered a [thin ID token](https://developer.okta.com/docs/concepts/api-access-management/#tokens-and-scopes) and contains only base claims. Profile attributes and Groups aren’t returned, even if those scopes are included in the request. You can use the access token to get the Groups claim from the /userinfo [endpoint](https://developer.okta.com/docs/reference/api/oidc/#userinfo).

(From https://developer.okta.com/docs/guides/customize-tokens-groups-claim/main/#add-a-groups-claim-for-the-org-authorization-server).

We could work around this in our app, but it seems easier for us if `oauth2-proxy` handled this case and we didn't have to implement a caching strategy or anything. My thought is adding a special flag `--fetch-okta-userinfo` that would populate `X-Forwarded-Groups` based on an API call to the `/userinfo` endpoint during the OIDC flow. I'd be happy to work on this patch.

**Comment by askreet** [comment]
After starting to look at the code to understand where this might live, it seems `--profile-url` is exactly for this purpose, though I can't seem to make it work with Okta's `/userinfo` endpoint.

**Comment by subramad** [comment]
@askreet I am having same issue, I dont see the groups even if I see the scope has groups in access token. Can you help how you resolved this?
