### ISSUE TITLE
Docker release tags without "v" prefix

### ISSUE THREAD

**Issue by iFrozenPhoenix** [oauth2-proxy/oauth2-proxy#1542]
Currently the docker images are published with a v prefix which is not semver conform.

Would it be possible to publish the images without the "v" prefix, so that they are semver conform?
This would enable automation tools to parse the version in a standard way so that they can e.g. load the latest image by the version no instead of the latest tag.

**Comment by JoelSpeed** [comment]
We have historically always published releases with a v prefix, which is then interpreted into the version strings in the tags. I don't think we want to change the way we are doing this, but maybe we can update the Makefile to detect a `v` prefix and publish the version twice stripping the `v` prefix.

Eg the [docker-all](https://github.com/oauth2-proxy/oauth2-proxy/blob/c5a98c6d03781476021107772a150ba2acb39206/Makefile#L54) target could call itself again while setting `VERSION=...`
