### ISSUE TITLE
Bypass auth methods cause a panic on /auth?allowed_groups=... usage

### ISSUE THREAD

**Issue by andytson-inviqa** [oauth2-proxy/oauth2-proxy#1544]
We are trying to use the auth-only endpoint to specify multiple different group checks on different web entrypoints, whilst allowing fallback to trusted ips

If we visit using the trusted ip, then we get a panic on /go/src/github.com/oauth2-proxy/oauth2-proxy/oauthproxy.go:995

## Expected Behavior

site-a.com should allow either:
* group team-a
* traffic from 1.2.3.4

site-b.com should allow either:
* group team-b
* traffic from 1.2.3.4

## Current Behavior

traffic from 1.2.3.4 gets a panic from trying to resolve a nil pointer

```
http: panic serving 10.244.4.26:47612: runtime error: invalid memory address or nil pointer dereference
goroutine 2668 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0xbccae0, 0x133f7d0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
main.checkAllowedGroups(0xc000224180, 0x0)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/oauthproxy.go:995 +0x3b
main.authOnlyAuthorize(...)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/oauthproxy.go:982
main.(*OAuthProxy).AuthOnly(0xc000224180, {0x7f72d7954a48, 0xc0004eeb40}, 0xb8f0e0)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/oauthproxy.go:836 +0x4d
net/http.HandlerFunc.ServeHTTP(0xda93c0, {0x7f72d7954a48, 0xc0004eeb40}, 0xc00009eb80)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/middleware.(*storedSessionLoader).loadSession.func1({0x7f72d7954a48, 0xc0004eeb40}, 0x4bcbf7)
	/go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/middleware/stored_session.go:86 +0x1b2
net/http.HandlerFunc.ServeHTTP(0x203000, {0x7f72d7954a48, 0xc0004eeb40}, 0x7f72d79fe190)
```

## Possible Solution

avoid doing the checkAllowedGroups on authOnlyAuthorize if p.IsAllowedRequest(req)

## Steps to Reproduce (for bugs)

* site-a.com uses .../auth?allowed_groups=team-a
* site-b.com .../auth?allowed_groups=team-b
* trusted_ips=1.2.3.4
* visit from 1.2.3.4

## Context

Being able to limit different hosts by different groups from one oauth2-proxy environment, whilst also using bypass mechanisms like trusted ips, skip preflight checks etc.

## Your Environment

- Version used: 7.2.1
- Kubernetes
- ingress-nginx with ingresses using nginx.ingress.kubernetes.io/auth-* annotations

**Comment by andytson-inviqa** [comment]
sorry, accidentially submitted before I'd finished

**Comment by JoelSpeed** [comment]
This is definitely a bug, are you able to raise a PR to fix the issue? I think we just need to check for nil in authOnlyAuthorize and skip if that's the case

**Comment by andytson** [comment]
I think that using the session != nil check would have odd behaviour if the user has already got a cookie session, then the groups would be checked as well regardless of whether they were allowed via the bypass methods.

**Comment by andytson** [comment]
so possibly the `p.IsAllowedRequest(req)` should be re-run in this case, either in AuthOnly or with p passed in to authOnlyAuthorize

**Comment by JoelSpeed** [comment]
It does raise a question which has come up before, if the user has a session and is also authorized by the skip auth checks, should their existing session still be checked?

I lean towards yes in this case because if the information is stale or expired and we pass it to an upstream, that could cause issues right? Whereas if we cleared the expired session we wouldn't send the information to the upstream

I think it's important that we at least clear the session if the session doesn't match the auth rules, or are there other use cases I'm not considering at the moment?

**Comment by andytson** [comment]
ok I'll do the session != nil way then, and that can be answered separately if at all.
