### ISSUE TITLE
Send `X-Forwarded-Proto: https` to upstream when listening on TLS

### ISSUE THREAD

**Issue by candlerb** [oauth2-proxy/oauth2-proxy#1547]
## Expected Behavior

When oauth2-proxy is listening on https but forwarding to a http upstream, I expect `X-Forwarded-Proto: https` to be present in the forwarded request.  This tells the upstream that any absolute links it generates should be https, not http.

## Current Behavior

I can use tcpdump to see the traffic to upstream:

```
X-Forwarded-Email: brian@...
X-Forwarded-For: 2001:db8:...
X-Forwarded-Preferred-Username: brian
X-Forwarded-User: subclaim...
```

There's no `X-Forwarded-Proto` present.  I can't find any config option which would add this, in the documentation or in the source code.

## Possible Solution

Automatically add `X-Forwarded-Proto: https` in upstream proxied requests when listening on TLS.

Alternatively: have a way to add any arbitrary, static headers to the upstream.

## Steps to Reproduce (for bugs)

```
https_address = ":443"

tls_cert_file = "..."
tls_key_file = "..."

upstreams = [
    "http://127.0.0.1:8888/"
]

provider ... etc
```

Run another server listening on localhost:8888

Run `tcpdump -i lo -nn -s0 -A tcp port 8888` to see the traffic to the server.

(Note: I have not set `reverse_proxy = true`.  This is because I'm not talking about trusting X-Forwarded-Proto from the client; there is no proxy between the client and oauth2-proxy. Rather I'm talking about inserting X-Forwarded-Proto towards the upstream server)

## Context

Use case: I am trying to put oauth2-proxy in front of an application (oxidized) running on `http://127.0.0.1:8888`.  When it receives a request to `/` it issues a redirect to `/nodes`.  However it is generating a http rather than https redirect.

## Your Environment

- Version used: `oauth2-proxy-v7.2.1.linux-amd64.tar.gz` (official release binary)

**Comment by candlerb** [comment]
Aha, it looks like the "alpha" configuration should allow me to do this:

```
injectRequestHeaders:
- name: X-Forwarded-Proto
  values:
  - value: https
```

I'm just having some problems with the auto conversion of the config to this new format: the new config is missing `cookie-secret` and `email-domain(s)`. But I'll work through this.

**Comment by candlerb** [comment]
OK, I had to add `--cookie-secret "..."` and `--email-domain "*"` as command-line options, but now it works, yay :-)

Feedback: the alpha config parser isn't very friendly - it doesn't tell you where you made a mistake. Here are a couple of errors I got:

```
Feb 09 17:05:28 oxidized oauth2-proxy[15024]: [2022/02/09 17:05:28] [main.go:43] ERROR: failed to load alpha options: error unmarshalling config: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type options.AlphaOptions
```

```
Feb 09 17:17:12 oxidized oauth2-proxy[15592]: [2022/02/09 17:17:12] [main.go:43] ERROR: failed to load alpha options: error unmarshalling config: error unmarshaling JSON: while decoding JSON: illegal base64 data at input byte 4
```

Basically "you have an error somewhere.  Do a binary chop if you want to find it" :-)

**Comment by JoelSpeed** [comment]
All we do for the config is a yaml unmarshal, so this is all coming from the underlying libraries, not sure what we can do to improve this right now but thanks for the feedback, will have a think about it :thinking:

**Comment by candlerb** [comment]
I've seen better errors from Go YAML decoding, using `gopkg.in/yaml.v2` or `gopkg.in/yaml.v3` directly.  It looks like the [library](https://github.com/ghodss/yaml) you're using does another layer of decoding via JSON, and loses the context.

Anyway, happy to close this now since I have a solution to the original problem. Cheers!
