### ISSUE TITLE
skip-auth-preflight doesn't work with auth_request/forwardAuth sub-requests

### ISSUE THREAD

**Issue by andytson** [oauth2-proxy/oauth2-proxy#1549]
## Expected Behavior

When using skip-auth-preflight with oauth2-proxy behind Nginx or Traefik and auth_request/forwardAuth sub-requests are used, OPTIONS requests to the ingress should be allowed

## Current Behavior

It's blocked because the check in oauth2-proxy just checks it's own request (which is a sub-request) method

## Possible Solution

oauth2-proxy should use X-Original-Method/X-Forwarded-Method for the preflight check when in reverse proxy mode.

## Steps to Reproduce (for bugs)

1.  Implement config with skip-auth-preflight and reverse-proxy set
2.  Implement a k8s ingress that has the annotations/middleware for an auth request to oauth2-proxy
3.  curl -X OPTIONS http://the-ingress-host
4.  Receive a unexpected 401 or 302 depending on oauth2-proxy endpoint used and middleware usage

## Context

This prevents the OPTIONS request succeeding, which doesn't receive cookie credentials.

## Your Environment

- Version used: 7.2.1
- Kubernetes
- Nginx or Traefik ingress controller
- Ingress with annotations/middleware for the auth request

**Comment by andytson** [comment]
I assume this is also an issue by the looks of things for the allowed routes functionality as well, as it seems to refer to the own request as well. 

The TrustedIps I've not had this problem with

**Comment by andytson** [comment]
I'm wondering about the implementation for the fix.

Though I could just do a check for X-Fowarded-Method and use if there, there's a security reason to do more, as it should only be used when absolutely sure it was a reverse-proxy request, otherwise could be faked.

**Comment by andytson** [comment]
Just to update, Nginx X-Original-Method. It seems dangerous to choose one or the other without knowledge of which is correct, if a client can fake the other header and bypass on other methods

**Comment by JoelSpeed** [comment]
> It seems dangerous to choose one or the other without knowledge of which is correct, if a client can fake the other header and bypass on other methods

In general, we have left the `reverse-proxy` as a more insecure option where we recommend that users filter out headers before making the subrequest (Nginx may already do some of this by default), so I think working on both could be allowed based on the `reverse-proxy` flag, but the alternative is to have configuration for this to allow users to choose which value to use

**Comment by andytson-inviqa** [comment]
I'm currently solving this issue targeting the specific ingress that needs preflight in k8s via:

```
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-snippet: |
      if ($request_method = OPTIONS) {
        return 200;
      }
 ```

**Comment by kartoch** [comment]
I can confirm this bug is still present in v7.4.0.
