### ISSUE TITLE
Issue using the prebuilt docker image of the proxy: connection refused

### ISSUE THREAD

**Issue by lgiommi** [oauth2-proxy/oauth2-proxy#1552]
## Expected Behavior

Use oauth2-proxy as proxy in front of a service that is running on port 8080. Everything is tested locally. I registered my application with the `https://cms-auth.web.cern.ch/` provider using `http://localhost:4180/oauth2/callback` as Redirect URI. I want to use the prebuilt docker image of oauth2-proxy. I run the proxy with 
```
docker run -p 4180:4180 -p 8080:8080 -v /MY_PATH/:/etc quay.io/oauth2-proxy/oauth2-proxy --config /etc/example_config.cfg
```
where `example_config.cfg` is:
```
provider = "oidc"
redirect_url = "http://localhost:4180/oauth2/callback"
oidc_issuer_url = "https://cms-auth.web.cern.ch/"
upstreams = [
    "http://0.0.0.0:8080"
]
email_domains = [
    "*"
]
client_id = "MY_CLIENT_ID"
client_secret = "MY_CLIENT_SECRET"
pass_access_token = true
cookie_secret = "MY_COOKIE_SECRET"
cookie_secure = false
skip_provider_button = true
ssl_insecure_skip_verify = true
http_address = "0.0.0.0:4180"
```
The local service running on port 8080 has an API that prints "Hello world". The expected behavior is that opening a (Firefox) browser, going to `http://localhost:4180/hello`, it verifies my certificate and it redirect me to `https://cms-auth.web.cern.ch/login` where I can sign in with my x509 certificate or CERN SSO. After that I see on the web page "Hello world".

## Current Behavior

After signing with my x509 certificate or CERN SSO the page is redirected to the message `502 Bad Gateway There was a problem connecting to the upstream server.`  In the terminal where the proxy is running the output is
```
$ docker run -p 4180:4180 -p 8080:8080 -v /MY_PATH/:/etc quay.io/oauth2-proxy/oauth2-proxy --config /etc/example_config.cfg 
[2022/02/11 13:16:46] [proxy.go:89] mapping path "/" => upstream "http://0.0.0.0:8080"
[2022/02/11 13:16:46] [oauthproxy.go:148] OAuthProxy configured for OpenID Connect Client ID: MY_CLIENT_ID
[2022/02/11 13:16:46] [oauthproxy.go:154] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
[2022/02/11 13:16:59] [oauthproxy.go:866] No valid authentication in request. Initiating login.
172.17.0.1:64788 - 77d887a7-cdf4-463f-b96f-7879892353e7 - - [2022/02/11 13:16:59] localhost:4180 GET - "/hello" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0" 302 320 0.001
172.17.0.1:64788 - 6eb97fc5-22d1-4bf9-b93c-fc4ff4d2fe37 -MY_MAIL@cern.ch [2022/02/11 13:17:08] [AuthSuccess] Authenticated via OAuth2: Session{MY_INFO token:true id_token:true created:2022-02-11 13:17:08.8678187 +0000 UTC m=+22.831653101 expires:2022-02-11 14:17:07.8536012 +0000 UTC m=+3621.817436801}
172.17.0.1:64788 - 6eb97fc5-22d1-4bf9-b93c-fc4ff4d2fe37 - - [2022/02/11 13:17:08] localhost:4180 GET - "/oauth2/callback?code=RiTMDCzEO1fGCasHtlBHZq&state=AOgcs_1nBpZiWo0R_5dFUqQ9Z3G8vAtVevr35ar2ZZg:/hello" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0" 302 29 0.667
[2022/02/11 13:17:08] [error_page.go:93] Error proxying to upstream server: dial tcp 0.0.0.0:8080: connect: connection refused
172.17.0.1:64788 - 33d307b8-7f2e-483a-8187-fa221db5aab2 - luca.giommi@cern.ch [2022/02/11 13:17:08] localhost:4180 GET / "/hello" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0" 502 2309 0.003
[2022/02/11 13:17:09] [error_page.go:93] Error proxying to upstream server: dial tcp 0.0.0.0:8080: connect: connection refused
172.17.0.1:64788 - be5b7104-5bd7-4b64-8196-17eafb82c7cf - MY_MAIL@cern.ch [2022/02/11 13:17:09] localhost:4180 GET / "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0" 502 2309 0.003
```

## Possible Solution

Since I am using a macOS I installed oauth2-proxy with brew and removing from the `example_config.cfg` the line `http_address = "0.0.0.0:4180"` and running the proxy with `oauth2-proxy --config ./example_config.cfg` everything works correctly and at the end `http://localhost:4180/hello` shows me "Hello world". I obtained the same output also using the prebuilt binary `oauth2-proxy-v7.2.1.darwin-amd64.tar.gz`. But I would like to use the docker image for the proxy, and I would like to solve the issue with it. Am I running the container in the wrong way?

## Your Environment

- Version used: quay.io/oauth2-proxy/oauth2-proxy:latest
- macOS Monterey 12.1

**Comment by braunsonm** [comment]
> The local service running on port 8080 has an API that prints "Hello world".

Is this service running in a container or on your machine? If it's running on your machine outside of a container you need to use your docker host as the upstream. It sounds like you're telling `oauth2-proxy` to reverse proxy port 8080 inside the container it's running, of which there is no service on port 8080.

You can reference the host machine inside a container with `host.docker.internal`, so upstream set to `http://host.docker.internal:8080` would be what you want.

**Comment by lgiommi** [comment]
My service is running on my machine, so outside a container. I tried to use `http://host.docker.internal:8080` as upstream but I got a "Connection failed" error when I try to browse `http://localhost:4180/hello` with no answer from the `oauth2-proxy` container. In the meanwhile, I tried the image in an ubuntu environment using the same config file (shown in the first post without the `http_address = "0.0.0.0:4180"` line) and it worked correctly. Maybe is something wrong with how docker works in a macOS?

**Comment by JoelSpeed** [comment]
Have you tried using the [local testing environments](https://github.com/oauth2-proxy/oauth2-proxy/tree/master/contrib/local-environment) at all, I know they work on my Mac at least. Perhaps that will give you some inspiration for running this all in docker for mac?

**Comment by lgiommi** [comment]
I took inspiration from what @JoelSpeed suggested to me but basically, all the information contained in the configs are the same I used. Maybe is a particular way to run the container?

**Comment by lgiommi** [comment]
Issue still remains

**Comment by braunsonm** [comment]
@lgiommi this is something wrong with your configuration. I don't see anything here that has to do with oauth proxy's code.

**Comment by BenjaminHae** [comment]
The Problem is, that in the Dockerfile at bitnami, the command is specified to contain the upsteam parameter:
https://github.com/bitnami/containers/blob/1930b4f9705d88ce84299e729fe333e88dd6bb5e/bitnami/oauth2-proxy/7/debian-11/Dockerfile#L50

As a result the value in the config file (or the environment variable) is ignored.

It can be fixed by ovverriding the command to be "oauth2-proxy" without the parameters specified in the Dockerfile.
