### ISSUE TITLE
Getting all profile details of a user

### ISSUE THREAD

**Issue by tareco** [oauth2-proxy/oauth2-proxy#1557]
Hi,

Apologies in advance if I am looking the wrong way; I have searched for similar topics but couldn't really find any relevant documentation on this.

## Expected Behavior

Document all the `X-Auth-*` headers relating to the guest profile.

## Current Behavior

I am trying to find documentation how to get the user profile picture and real name, but cannot find it anywhere.

## Possible Solution

Updating the documentation with all the X-Auth headers relevant for the user profile.

## Steps to Reproduce (for bugs)

1. I am using Google as provider and `set_xauthrequest = true`;
2. I can get `$upstream_http_x_auth_request_user`, `$upstream_http_x_auth_request_email` and `$upstream_http_x_auth_request_groups`;
3. I can't get data for `$upstream_http_x_auth_request_preferred_username`;
4. I can't find the headers for the profile picture url.

## Context

I am using OAuth2-Proxy as an authenticator for an internal application. Authentication is working fine and I can get the user email and groups.

I would like to improve the application menu adding to it a profile element, showing the user first/last name and the profile picture.

## Your Environment

Debian 9.1
Nginx 1.10.3
PHP 7.0
Google Workspace
oauth2-proxy-v7.2.1.linux-amd64.tar.gz

**Comment by JoelSpeed** [comment]
At the moment we only support a very small subset of the profile claims, eg User, Email and Preferred Username. In the future we hope to be able to extract more of these, eg the Real Name, but before we can do that we need to do some work around our providers, eg #1394

**Comment by tareco** [comment]
Hi @JoelSpeed, if I understood correctly the "Preferred Username" is already supported.
If so, how can I capture it? This is what I am using but it comes out empty:
`auth_request_set $name $upstream_http_x_auth_request_preferred_username;`

**Comment by JoelSpeed** [comment]
I thought what you have there should work, you may want to check your logs to see if the preferred username is being captured during the login cycle, if it isn't, that would explain why the header is empty

**Comment by tareco** [comment]
Are you referring to these log entries? If you are, I can't find an entry for the name here.. how could I get that from Google?

```
200 GET https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=<<<redacted>>>
{
  "issued_to": "<<<redacted>>>",
  "audience": "<<<redacted>>>",
  "user_id": "<<<redacted>>>",
  "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email openid",
  "expires_in": 3599,
  "email": "<<<redacted>>>",
  "verified_email": true,
  "access_type": "offline"
}
```

**Comment by JoelSpeed** [comment]
Normally there is a log line that details what was created in the session, it will start with `Authenticated via OAuth2:` and then have the details of the session

**Comment by tareco** [comment]
Ok, sorry for overlooking.. it's there, but empty unfortunately.. what could be wrong? :(
`Authenticated via OAuth2: Session{email:<<<redacted>>> user:<<<redacted>>> PreferredUsername: token:true id_token:true created:2022-02-16 15:25:40.582183863 +0000 UTC m=+79725.032087823 expires:2022-02-16 16:25:39.582183863 +0000 UTC m=+83324.032087823 refresh_token:true groups:[<<<redacted>>>]}`

**Comment by JoelSpeed** [comment]
Based on your previous message, you are using the google provider right? Have you tried using the OIDC connector with Google instead? The google provider is old and out of date, and it looks like it doesn't set the preferred username at all

**Comment by tareco** [comment]
Yes, I have Google Workspace so I am using the default..

I see in the docs examples of OIDC for Okta and others, but not for Google. Is there a sample config for that?

**Comment by JoelSpeed** [comment]
I don't have one handy, but the issuer for google is `https://accounts.google.com/` if that helps at all

**Comment by tareco** [comment]
I'll give it a try  - thank you.

**Comment by tareco** [comment]
I am unable to put this to work.
While trying OIDC with Google I got stuck in restricting to users that belong to certain groups only.
Also don't understand why, but I don't get the real user name as well (first / family).
I would really appreciate a working example (or as close as possible).
Thank you.

**Comment by tareco** [comment]
Hi @JoelSpeed,

I would really appreciate it if you could provide a working example of to access real name and profile picture using google.

Thank you so much.

**Comment by JoelSpeed** [comment]
Apologies, this is not something I'm going to have the time to do.

Please remember that this project is run by myself and another couple of maintainers purely in our spare time. While we have an interest in keeping the project going for its users, we really need community members to help solve issues like yours and then provide the feedback to others on how to solve the issues. This kind of particular case is not something we typically investigate in our time working on the project

**Comment by krin-wang** [comment]
@tareco, I met same issue as you (cannot get user profile information by google provider). 
Finally, I found that specifying `OAUTH2_PROXY_OIDC_ISSUER_URL` works.
Could you please also have a try?

oauth2-proxy image: `quay.io/oauth2-proxy/oauth2-proxy:v7.2.0`.


With following environment settings, the return JWT token doesn't contains profile information, and the `iss` would be `accounts.google.com`
```
- name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
  value: "true"
- name: OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS
  value: "true"
- name: OAUTH2_PROXY_SCOPE
  value: "openid email profile"
```

But after I specified  `OAUTH2_PROXY_OIDC_ISSUER_URL` explicitly, it works and the `iss` in JWT token changed to `https://accounts.google.com`.
```
- name: OAUTH2_PROXY_OIDC_ISSUER_URL
  value: "https://accounts.google.com"
```

**Comment by tareco** [comment]
Hi @krin-wang and thank you for your message.

I have tried adding the parameters you mention to my conf file, but the token still doesn't come with user name and pic url.

My relevant conf information:

```
google_admin_email = "<email>"
google_service_account_json = "<json file>"
google_group = [ "<group_email_1>", "<group_email_2>" ]

pass_authorization_header = true
skip_jwt_bearer_tokens = true
scope = "openid email profile"
oidc_issuer_url = "https://accounts.google.com"
```

In the logs I only see this:

```
GET https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=[XXXXX]… {
  "issued_to": “XXXXX.apps.googleusercontent.com",
  "audience": “XXXXX.apps.googleusercontent.com",
  "user_id": “XXXXX”,
  "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email openid",
  "expires_in": 3598,
  "email": “XXXXX”,
  "verified_email": true,
  "access_type": "offline"
}
```

**Comment by krin-wang** [comment]
Hi @tareco, let me share more information here in case it would be helpful. Though I also have no idea on the root cause.
My log is same with yours.
```
[internal_util.go:69] 200 GET https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=XXX... {
  "issued_to": "<<redacted>>.apps.googleusercontent.com",
  "audience": "<<redacted>>.apps.googleusercontent.com",
  "user_id": "<<redacted>>",
  "scope": "openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile",
  "expires_in": 3599,
  "email": "<<redacted>>",
  "verified_email": true,
  "access_type": "offline"
}

<<redacted>> [2022/08/29 11:23:10] [AuthSuccess] Authenticated via OAuth2: Session{email:<<redacted>> user:<<redacted>> PreferredUsername: token:true id_token:true created:2022-08-29 11:23:10.519797883 +0000 UTC m=+26685.869868779 expires:2022-08-29 12:23:09 +0000 UTC}
```

I checked passed jwt token in Authorization header.
Before I explicitly specified `oidc_issuer_url="https://accounts.google.com"`, the jwt token looks like this (only payload part).
```
{
  "iss": "accounts.google.com",
  "azp": "<<redacted>>.apps.googleusercontent.com",
  "aud": "<<redacted>>.apps.googleusercontent.com",
  "sub": "<<redacted>>",
  "hd": "<<redacted>>[company domain]",
  "email": "<<redacted>>",
  "email_verified": true,
  "at_hash": "<<redacted>>",
  "iat": 1661772789,
  "exp": 1661776389
}
```

After I set `OAUTH2_PROXY_OIDC_ISSUER_URL="https://accounts.google.com"`, the jwt token looks like (only payload part).
```
{
  "iss": "https://accounts.google.com",
  "azp": "<<redacted>>.apps.googleusercontent.com",
  "aud": "<<redacted>>.apps.googleusercontent.com",
  "sub": "<<redacted>>",
  "hd": "<<redacted>>[company domain]",
  "email": "<<redacted>>",
  "email_verified": true,
  "at_hash": "<<redacted>>",
  "name": "<<redacted>>",
  "picture": "<<redacted>>",
  "given_name": "<<redacted>>",
  "family_name": "<<redacted>>",
  "locale": "en",
  "iat": 1661772190,
  "exp": 1661775790
}
```

**Comment by tareco** [comment]
Hi @krin-wang, it seems no matter my conf I never get those details.
I am not sure where to get the jwt payload, can you help me with that so I can debug better?

**Comment by krin-wang** [comment]
With `OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER` enabled, oauth2-proxy will pass jwt token in `Authorization` header when forward the request to upstreams. 

You can print/log the forwarded request headers in upstream service code.

**Comment by tareco** [comment]
Thank you @krin-wang.

After adding `set_authorization_header` I was able to forward the token to my upstream wsgi and decode it.

Unfortunately, it never carries the extra info :/

```
{
  "iss": "accounts.google.com",
  "azp": "<<redacted>>.apps.googleusercontent.com",
  "aud": "<<redacted>>.apps.googleusercontent.com",
  "sub": "<<redacted>>[my domain]",
  "hd": "<<redacted>>",
  "email": "<<redacted>>",
  "email_verified": true,
  "at_hash": "<<redacted>>",
  "iat": 1661784077,
  "exp": 1661787677
}
```

**Comment by tareco** [comment]
Hi again, @krin-wang!

It is working finally, although I don't know exactly why...

I made some changes to my config, this is what I have for Google:

```
pass_authorization_header = true
set_authorization_header = true
skip_jwt_bearer_tokens = true
scope = "openid email profile"
oidc_issuer_url = "https://accounts.google.com"
profile_url = "https://accounts.google.com"
set_xauthrequest = true
pass_access_token = true
```

I am not sure if it was related or not, but I noticed that my server was giving some buffer errors on uWSGI: `invalid request block size: 4531 (max 4096)...skip`. I have increased its `buffer-size` from the default to 32768 and I started getting the extra info in the JWT payload:

```
{
  "iss": "https://accounts.google.com",
  "azp": "<<redacted>>.apps.googleusercontent.com",
  "aud": "<<redacted>>.apps.googleusercontent.com",
  "sub": "<<redacted>>",
  "hd": "<<redacted>>",
  "email": "<<redacted>>",
  "email_verified": true,
  "at_hash": "<<redacted>>",
  "name": "<<redacted>>",
  "picture": "https://lh3.googleusercontent.com/a/<<redacted>>",
  "given_name": "<<redacted>>",
  "family_name": "<<redacted>>",
  "locale": "en-GB",
  "iat": 1661790240,
  "exp": 1661793840
}
```

Thank you for the tips! They definitely helped getting there :)))

**Comment by tareco** [comment]
Well.. I thought I had nailed it, but `name`, `given_name`, `family_name` and `picture` are not visible in `/userinfo` of oauth2-proxy and I can't get them in upstream variables such as `$upstream_http_x_auth_request_picture`.. Any idea?

**Comment by gysel** [comment]
I was only able to get it working once I added the following two settings:

```
OAUTH2_PROXY_LOGIN_URL=https://accounts.google.com/o/oauth2/v2/auth?access_type=offline
OAUTH2_PROXY_REDEEM_URL=https://oauth2.googleapis.com/token
```

The reason seems to be that the Google provider uses hardcoded legacy endpoints from Google.

https://github.com/oauth2-proxy/oauth2-proxy/blob/01386bf30348f75590df61a3408187696fef6d4b/providers/google.go#L57-L81

**Comment by joelsdc** [comment]
Hey guys, I'm having a really hard time getting the profile details to work in my setup.

I can't get the `first name`, `last name`, `profile picture` or the `preferred username`...

@tareco / @gysel / @krin-wang : when you say "get it working" do you mean the authentication works, or do you mean the getting profile details work? if the later, with the OIDC or the Google provider?

Can you guys post your settings? 

I'm not having issues with auth, only getting the profile details...

**Comment by roshanlasantha** [comment]
Hi @joelsdc,
Just wondering if you have found a way to receive firstName and lastName from the OIDC. I'm facing a similar issue with the Keycloak.
