### ISSUE TITLE
For X-Forwarded-Groups, use roleName instead of role:clientName:roleName

### ISSUE THREAD

**Issue by lolllpop** [oauth2-proxy/oauth2-proxy#1569]
I use oauth2-proxy in combination with keycloak and the new keycloak-oidc provider. The access control within oauth2-proxy based on client roles does work using the syntax clientName:roleName for allowed-roles. For fine grained access control within upstream itself, however, I forward the roles using the X-Forwarded-Groups.

## Expected Behavior

X-Forwarded-Groups contains the original roleName as configured in keycloak and understood by upstream.

## Current Behavior

oauth2-proxy prepends roleName with the prefix role:clientName:, resulting in the X-Forwarded-Groups being set to role:clientName:roleName. For upstream, this is an unknown role.

## Possible Solution

If the differentiation between client roles, (global/realm) roles, and groups is required, maybe store them in different variables and allow for the configuration which of them and how they are forwarded to upstream. There should at least be an option to forward them unmodified.

## Steps to Reproduce (for bugs)

oauth2-proxy.conf (extract):

````
provider = "keycloak-oidc"
provider_ca_files = "/ssl/CA.crt"
oidc_issuer_url = "https://keycloak:8443/auth/realms/realm"
client_id = "client"
client_secret = "xxx"
scope = "openid profile email"
email_domains = "*"
allowed_roles = [ "clientName:roleName" ]
whitelist_domains = [ "keycloak:8443" ]
redirect_url = "https://client:8443/oauth2/callback"
````

keycloak configured according to your docu:
````
Mapper Client Roles
  Mapper Type: User Client Role
  Client ID: clientName
  Token Claim Name: resource_access.${client_id}.roles
  Add to access token: on
````

## Your Environment

oauth2-proxy: 7.2.1
keycloak: 17.0.0

**Comment by JoelSpeed** [comment]
> If the differentiation between client roles, (global/realm) roles, and groups is required, maybe store them in different variables and allow for the configuration which of them and how they are forwarded to upstream. There should at least be an option to forward them unmodified.

I think this may be possible once we add an extra parameters option for the session state, allowing you to add arbitrary claims to your session. That said, I don't know when exactly we are planning to add that. I've done a bunch of the prerequisite work now so it should be possible soon

**Comment by lolllpop** [comment]
I have seen your work on the extraction of claims, and with alpha-config the forwarding of such claims should already be possible. Very promising!

But even then, I would miss a part in between: the formatting of claims being forwarded. For example, the values of a multi-value claim (e.g. multiple roles) might be required to be joined either using spaces or using commas depending on upstream.

**Comment by JoelSpeed** [comment]
At the moment, for multi value headers, we use comma separation. Which, IIRC, we had a big discussion about at the time and concluded that the HTTP spec specifies comma separated values for headers with multiple values.
If your upstream doesn't support comma separated values, then it isn't HTTP spec compliant was the conclusion we made at the time

**Comment by arnouthoebreckx** [comment]
I was wondering if there was any update regarding the adding of arbitrary claims? I'm looking for something similar where I can forward both the groups and roles to the upstream and this does not seem to be currently supported.

**Comment by JoelSpeed** [comment]
No progress just yet, we need to do a bunch of work to refactor the providers to unblock this. It's on my radar but I don't have much time to support this project right now

**Comment by CMarcher-Ahuora** [comment]
Any updates?
