### ISSUE TITLE
Redirect loses query params from original url ​

### ISSUE THREAD

**Issue by JasperWoo** [oauth2-proxy/oauth2-proxy#1570]
Action: 
1. Click on this link - https://application.com/account/someid/history?page=2
2. Authenticate
3. end up at this location - 
Expectation - At step 3, I'd end up at the location specified originally in step 1.

## Expected Behavior
Redirected back to https://application.com/account/someid/history?page=2

## Current Behavior
Redirected to https://application.com/account/someid/history, missing the query param `?page=2`

## Context
We are trying to improve the user experience. Part of it is about being able to share every page that we have. This redirection behavior compromises the goal.

## Your Environment
Setup is using oauth2-proxy sidecar with /oauth2/callback as redirect_url

### Version used:
- v6.0.0

**Comment by JoelSpeed** [comment]
Could you please share more details about your setup, including how you have OAuth2 Proxy as a sidecar? Do you mean that OAuth2 Proxy is proxying straight through to the application once authenticated? Or do you mean you have OAuth2 Proxy as an auth sidecar to some other proxy?

Do you see the OAuth2 Proxy login page or are you skipping that?

**Comment by JasperWoo** [comment]
Yes. The OAuth2 Proxy is a sidecar, the port of which is where the traffic is routed to in the first place:
```
    route:
    - destination:
        host: service.ns.svc.cluster.local
        port:
          # OIDC port for auth
          number: 9443
```
As user logs in, proxy talks to an oidc server than tells us if the user is legitimate, if so, the proxy redirects back to the corresponding application container (with the upstream parameter).
Sidecar configuration:
```
- name: oauth2-proxy
          args:
            - oauth2-proxy
            - --provider=oidc
            - --oidc-issuer-url=oidc_server_endpoint
            # upstream point to the ui application container port
            - --upstream=http://127.0.0.1:{{ .Values.application.container_port }}
            - --http-address=0.0.0.0:9443
            - --redirect-url=...../oauth2/callback
            - --cookie-secure={{ .Values.oauth2_proxy.cookieSecure }}
            - --insecure-oidc-allow-unverified-email=true
            - --cookie-expire={{ .Values.oauth2_proxy.cookieExpire }}
            - --insecure-oidc-skip-issuer-verification=false
            - --sfdc-k4a-enabled=true
            - --skip-provider-button=true
            - --use-oidc-implicit-flow=false
            - --sfdc-oidc-client-id-path=somevault
            - --sfdc-oidc-client-secret-path=somevault
            - --sfdc-oidc-cookie-secret-path=somevault
            - --skip-auth-regex="/status"
```

**Comment by JoelSpeed** [comment]
It looks to me from your config that you aren't using it as an auth sidecar but it is actually proxying to the upstream directly. In which case, this is likely an issue with how we are constructing the URL in the sign in page logic.

If I've understood correctly, the redirect in your case boils down to the output of this function
https://github.com/oauth2-proxy/oauth2-proxy/blob/45ef848b0acece35c43a0afaa237783e27d42e16/pkg/requests/util/util.go#L37-L44

Which I'm guessing doesn't return the query parameters :thinking: Looking at the tests we don't have an example which includes and query params

**Comment by braunsonm** [comment]
Cannot reproduce using the latest builds. With httpbin as my upstream I can hit `http://localhost:4180/redirect-to?url=https%3A%2F%2Fgoogle.com`, authenticate, and be redirected to google proving the query params are passed.

Can you try upgrading from v6?

**Comment by JoelSpeed** [comment]
That's curious, I wonder why that is, do you have enough experience to be able to debug this?

**Comment by Thesola10** [comment]
In all likelihood, that may be due to the `&` and `?` not being sanitized. The `?` is preserved as a parameter body since you can't start a parameter list twice in an URL, but `&` is passed as extra parameters.

**Comment by mtneug** [comment]
You can URL-encode the return address to preserve the `&` etc. After the login, the user is redirected to the decoded URL.

**Comment by n3xem** [comment]
Is anyone working on fundamentally solving this problem?

**Comment by sbharadwaj1** [comment]
This is still relevant. Do we have a fix for it?

**Comment by Adoliin** [comment]
Any updates on this?

**Comment by anuragverma65** [comment]
This is still a relevant issue and there is an open [PR](https://github.com/CallumWayve/oauth2-proxy/pull/1) which solves this issue.
