### ISSUE TITLE
Allow passing contents of google-service-account-json as environment variable

### ISSUE THREAD

**Issue by alasdairnicol** [oauth2-proxy/oauth2-proxy#1571]
I'm following the instructions at https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#restrict-auth-to-specific-google-groups-on-your-domain-optional to restrict auth to google groups.

I am using environment variables for all secrets, e.g. OAUTH2_PROXY_CLIENT_SECRET. However I can't pass the json file as an environment variable. I can set OAUTH2_PROXY_GOOGLE_SERVICE_ACCOUNT_JSON, but that only determines the location of the file.

## Expected Behavior

Enable another flag, e.g. --google-service-account-json-contents and associated environment variable OAUTH2_PROXY_GOOGLE_SERVICE_ACCOUNT_JSON_CONTENTS, which allows me to pass the contents of the file.

## Current Behavior

I need to use --google-service-account-json-contents, which means I need to create the json file when the container starts.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Context

I'm running on ECS, so I don't think there's a good way to take a secret from SSM and create a file. I think I'll need to build another container based on quay.io/oauth2-proxy/oauth2-proxy, and in the entrypoint create the json file before starting oauth2-proxy.

## Your Environment

AWS ECS, ideally I'd store the json file in AWS secrets manager

- Version used:

oauth2-proxy 7.2.1

**Comment by alasdairnicol** [comment]
I found a better workaround. By setting `entryPoint` for my ECS task, I can create the file from the environment variable before starting the oauth2-proxy binary.

```
                "entryPoint": [
                    "sh",
                    "-c",
                    "echo $OAUTH2_PROXY_GOOGLE_SERVICE_ACCOUNT_JSON_CONTENTS > /dev/shm/google-account.json && exec /bin/oauth2-proxy \"$@\""
                ],
```

This means I don't need to build a new container for each oauth2-proxy release. Therefore this feature request is not as important. I'd be happy for it to be closed, unless it would be helpful to other users.

**Comment by RichardSieg** [comment]
For people stumbling over this in the future: I encoded my json file as base64 since I could not figure out how to properly escape the line breaks in the service account json. Here's how my entrypoint in CDK looks like:
```
entryPoint: [
                "/bin/bash",
                "-c",
                `echo $OAUTH2_PROXY_GOOGLE_SERVICE_ACCOUNT_JSON_CONTENTS | base64 --decode > google-account.json && exec oauth2-proxy \
                YOUR OPTIONS`,
            ],
```
