### ISSUE TITLE
add support for memory-based session storage

### ISSUE THREAD

**Issue by UiP9AV6Y** [oauth2-proxy/oauth2-proxy#1575]
add support for session storage in
the oauth2-proxy process memory
using a map or tree structure.

## Current Behavior

session information can stored
in two ways:

* cookie, which is sent to the client
  and stored in the browser. is subject
  to browser limitations, e.g. storage
  size
* redis, which requires the deployment
  of a dedicated K/V storage solution

## Expected Behavior

we would like to support users whose
information set is too large for cookie
storage, without having to deploy a
dedicated storage solution.

## Possible Solution

i do not think this feature needs a
special data structure; a simple `map`
would probably suffice. together with
an internal cleanup routine, this could
behave pretty much identical to redis,
except it would store the data within
the memory bounds of the oauth2-proxy
process.

## Context

we have a bunch of self-service 
applications, where users mostly spend
a few minutes using it. we therefor do
*not* have any requirement for long-term
session persistence. however, some of
our users are members of many groups,
causing the JWT and therefor the cookie
to grow above the limit accepted by
browsers. given that the services are
rather small, we would like to avoid
having to deploy a redis store alongside
each of them.

## Your Environment

- Version used: `7.2.1`

**Comment by UiP9AV6Y** [comment]
i can come up with a PR if needed

**Comment by JoelSpeed** [comment]
Initially, I'm hesitant to say we would want an in-memory store, as this doesn't scale horizontally at all, and, if the application restarts, every user then needs to re-authenticate. Are there alternative stores that would be easier for you to use that might have a wider appplication?

For example, perhaps some cloud provider key/value store or maybe even just a filesystem based session store (I know a lot of older PHP apps used to do this).

This would at least allow sessions to persist across OAuth2 Proxy restarts
