### ISSUE TITLE
Getting lint errors when building thanks to go encryption lib changes (deprecated method)

### ISSUE THREAD

**Issue by purejgleason** [oauth2-proxy/oauth2-proxy#1576]
## Expected Behavior

I can build the project using `make` on my macbook.

## Current Behavior

```
pkg/util/util_test.go:86:10: SA1019: certPool.Subjects is deprecated: if s was returned by SystemCertPool, Subjects will not include the system roots. (staticcheck)
	subj := certPool.Subjects()
```

## Possible Solution

This is a workaround but it seems to let it compile locally

```
-       subj := certPool.Subjects()
+       subj := certPool.Subjects() //nolint
```

## Steps to Reproduce (for bugs)

1.  run `make`

## Your Environment

Macbook

- Version used:

go version devel go1.18-b37a5391f9 Tue Dec 7 20:14:56 2021 +0000 darwin/amd64

**Comment by JoelSpeed** [comment]
This looks to be a new deprecation with Go 1.18. This project only currently supports 1.17 but it is good to catch the deprecations so thanks for posting.

Is there a recommended alternative in the release notes/godoc that suggests how to handle the deprecation?

**Comment by JoelSpeed** [comment]
This looks to be a new deprecation with Go 1.18. This project only currently supports 1.17 but it is good to catch the deprecations so thanks for posting.

Is there a recommended alternative in the release notes/godoc that suggests how to handle the deprecation?

**Comment by t-katsumura** [comment]
I have the same problem.
I think there is no other way better than using `nolint`.

CertPool.Subjects() was deprecated in this (https://github.com/golang/go/commit/3544082f75fd3d2df7af237ed9aef3ddd499ab9c) commit.

This deprication was discussed at https://github.com/golang/go/issues/46287
According to the discussion, CertPool was changed to be fully opaque.
So I think there is no good alternative way for `TestGetCertPool()`.

I could not found other way to fix this issue except for using `nolint`. 
Actually, many other OSS fix this in the same way.
