### ISSUE TITLE
Question: restrict multiple sites by different github teams with one oauth_proxy

### ISSUE THREAD

**Issue by dguendisch** [oauth2-proxy/oauth2-proxy#158]
I have successfully setup a central oauth_proxy (with github provider) protecting some other sites on the same parent domain using the nginx ingress controller (thanks to the hints from @JoelSpeed in https://github.com/bitly/oauth2_proxy/issues/550).
I wanted to have one central oauth_proxy instead of a dedicated one for every site because I only want to maintain one github oauth application (and you can only specify one redirect/callback URI per app).

I'm wondering now whether it would be possible to do different authorizations on the protected sites.
I see that I can restrict authorization on oauth_proxy e.g. with `-github-team` but that would then apply to all my protected sites.
Is it somehow possible to achieve that with (one) oauth_proxy?

**Comment by ploxiln** [comment]
That is not currently possible. You currently need multiple instances of oauth2_proxy to apply different team restrictions to different upstreams.

**Comment by dguendisch** [comment]
I see, thanks.
Actually multiple oauth2_proxy instances is ok as long as I could still go with having only one "master" oauth2_proxy registered on github.
But I guess it's not possible to kind of "cascade" the oauth2_proxies?

Another idea (to allow having only one oauth app registered at github) would be to use e.g. dex as the one github oauth app and then use multiple oauth2_proxy instances with provider `oidc` pointing to that  one dex installation. However when using `oidc` I cannot restrict to github teams, that option seems only available for `github` provider.
So the only authz option I see in that case is to maintain a list of email addresses and use `--authenticated-emails-file`.
Or does someone see other options to authz?

**Comment by kskewes** [comment]
Multiple `oauth2_proxy`'s with different group configuration works fine for us using nginx-ingress providing each proxy is protecting different subdomains or you run ~<3 different `oauth2_proxy` configs per subdomain.

For example:
- app1.sub1.example.com protected by oauth2-proxy.sub1.faceme.com allowing group1
- app2.sub1.example.com protected by oauth2-proxy.sub1.faceme.com allowing group2
- app3.sub1.example.com protected by oauth2-proxy.sub1.faceme.com allowing group3
- app4.sub2.example.com protected by oauth2-proxy.sub2.faceme.com allowing group4

The reason for this is each `oauth2_proxy` cookie is about 2.5K and Chrome (maybe others) will submit all cookies for the full domain (eg: `sub1.example.com`) to the load balancer in front of `oauth2_proxy`.
For us this is nginx-ingress which has a hard limit around 8K cookie size before denying user GET's.
This means ~3 different `oauth2_proxy` per domain.
I haven't been able to get around this with the lua script example in the docs and may have misinterpreted its purpose.

If cascade proxies then the secondary `oauth2_proxy` will validate email (see archived bitly repo issue/pr implementing this) but won't check google groups membership.

**Comment by dguendisch** [comment]
How do you achieve this example?

> For example:
> app1.sub1.example.com protected by oauth2-proxy.sub1.example.com allowing group1
> app2.sub1.example.com protected by oauth2-proxy.sub1.example.com allowing group2
> app3.sub1.example.com protected by oauth2-proxy.sub1.example.com allowing group3

It looks like **one** oauth2-proxy at `oauth2-proxy.sub1.example.com` protecting 3 different apps (that's clear) with 3 **different** group permissions (that's what I don't understand).
Or are you just allowing all 3 groups with this one oauth2-proxy?

**Comment by kskewes** [comment]
Sorry, that would have been confusing. It was a typo. :)

**Comment by dguendisch** [comment]
Then it matches what I'm currently doing: having one oauth2-proxy instance per team/group configuration.
Btw. thanks for that pointer regarding the cookie size, will keep that in mind.

**Comment by kskewes** [comment]
Indeed. I missed your comment about Github supporting only a single call back URL per app.
Good luck. We'll be circling back around to this again soon. Maybe per Redis PR #140...

**Comment by gogovan-vincentngai** [comment]
Do Github or Oauth2 will give me the github team in header after i success login?
so i can do something like 
if (header find team a)
   then USER A
if (header find team b)
   then USER B
