### ISSUE TITLE
Should roles be case-sensitive?

### ISSUE THREAD

**Issue by Nold360** [oauth2-proxy/oauth2-proxy#1581]
Since I'm to stupid to join your slack, I'll ask here. 

We are auto generating roles from LDAP, which have stupid cases e.g `MyRole`. In oauth-proxy I would like to just allow `myrole` but it wouldn't work because of the comparision.

Question: Could we convert all roles to lower case before comparision, or do i need to find another workaround?

## Expected Behavior

roles are case insensitive.

## Current Behavior

roles are case sensitive

## Possible Solution

Convert all roles to lower case before comparision

## Steps to Reproduce (for bugs)

1. create role `MyRole` in OIDC Provider
2. Allow role `myrole` in oauth-proxy
3. Access gets denied

1.  
4.  
5.  
6.  

## Your Environment

- Version used: latest

**Comment by JoelSpeed** [comment]
If an identity provider is case sensitive for something like this then I expect we need to be congruent to that. So I don't think we would want to modify those at all, and let end user applications handle the case sensitivity

**Comment by braunsonm** [comment]
Although LDAP attributes are case-insensitive, not all IdP have case insensitive roles. You should make the specific match as Joel mentioned. 
Feel free to chat on Slack for additional help
