### ISSUE TITLE
How to use one oauth2-proxy server to support multiple applications?

### ISSUE THREAD

**Issue by forestm** [oauth2-proxy/oauth2-proxy#1591]
## Expected Behavior

we have a large number of applications grouped by namespace, and their url looks like `http://common_domain/namespace/app_name`
we want to restrict the access permission based on the namespace.

## Current Behavior

Our oidc server can create token based on namespace, then return it to oauth2-proxy. If the user has no permission to the namespace, then return 401.
oauth2-proxy performs normally if the user has access permission.

The question is:
if user can access app1, he can open it normally.
Now he wants to open app2 which he has no permission, but because there's a cookie in the browser, so he can access app2.
if delete the cookie, then user cannot access app2.

## Possible Solution

Can we define the cookie name dynamically base on the subpath? here the subpath is namespace

or do we have some other methods?

## Your Environment

all of our apps and oauth2-proxy are based on kubernetes.

- Version used:
oauth2-proxy: latest

**Comment by braunsonm** [comment]
We support this by modifying the request to the `/oauth2/auth` endpoint. In there you can add the query string `allowed_groups` to the request and only those groups will be allowed through. See this PR: https://github.com/oauth2-proxy/oauth2-proxy/pull/849/files

You would probably use this with nginx's request auth.

**Comment by forestm** [comment]
Thank you @braunsonm for your comments.
But we should set up `allowed_groups` before starting up oauth2-proxy, and  it won't be changed in the runtime.
For different applications, user might  have different access permissions, and all these permissions can be controlled by our auth server. 

So can I use one oauth2-proxy for the authentication/authorization for different applications?
