### ISSUE TITLE
Container image arm64 v8 architecture missing

### ISSUE THREAD

**Issue by Legion2** [oauth2-proxy/oauth2-proxy#1593]
I'm trying to build a container image with oauth2-proxy as base image for the `linux/arm64/v8` platform.

## Expected Behavior

The build is successful

## Current Behavior

The build failes with `error building image: no child with platform linux/arm64/v8 in index quay.io/oauth2-proxy/oauth2-proxy:v7.2.1`

## Possible Solution

The `arm64` entry in the image index is missing the `v8` variant.

## Steps to Reproduce (for bugs)

1.  `docker run mplatform/manifest-tool inspect quay.io/oauth2-proxy/oauth2-proxy:v7.2.1` shows the missing variant

## Context

I'm building container images with kaniko

## Your Environment

- Architecture: arm64/v8 (aws graviton)
- Version used: 7.2.1

**Comment by Legion2** [comment]
Possibly this is "only" a kaniko issue, because kaniko is more strict about the presence of the variant option for the arm64 architecture. Docker itself can pull the arm64 image without the variant property.

**Comment by jerryhopper** [comment]
there is multiple things wrong imho.
But im quite sure that  test-reporter-latest-linux-amd64 dependency wont work on armv8 (https://github.com/oauth2-proxy/oauth2-proxy/blob/master/.github/workflows/ci.yaml)

Have a look how i do a multiarch build in github actions : https://github.com/jerryhopper/fusionauth-app-multiarch/blob/master/.github/workflows/main.yml
and the dockerfile (where arch specific dependencies are handled) : https://github.com/jerryhopper/fusionauth-app-multiarch/blob/master/Dockerfile

i hope that helps you further!

**Comment by Legion2** [comment]
I think the test-reporter is only used in ci and not bundled into the container image, so it must be amd64 because it must run in GitHub actions.
