### ISSUE TITLE
Documentation or pointers on how to configure Okta with oauth2-proxy to send the groups

### ISSUE THREAD

**Issue by rosskusler** [oauth2-proxy/oauth2-proxy#1596]
Do you have any documentation or can you point me to any resources that explain how to configure Okta and oauth2-proxy together so that the 'groups' claim gets sent to the upstream in the X-Forwarded-Groups header?

I have tried setting the pass-user-headers and setting the oidc-groups-claim to "groups". I'm not sure whether oauth2_proxy is actually getting a token from Okta that contains this claim.

**Comment by JoelSpeed** [comment]
Unfortunately this isn't something we are likely to be documenting any time soon as it's not a feature any of the maintainers use. If you do find some documentation I'm happy to review an addition to our docs
