### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by NikitaIvankov1992** [oauth2-proxy/oauth2-proxy#1600]
## Expected Behavior

We can set up callback URL dynamicly

## Current Behavior

You can set it over configuration file and "-redirect-url" directive or it will be '"https://" + requested host header + "/oauth2/callback"'

## Context

Hey there :)

Not sure why [redirect URL](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/app/redirect/director.go#L43-L52) which is used to redirect user to once authenticated with the OAuthProxy gotten from "X-Forwarded-Host" header, but ["callback" redirect URL](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/oauth2-proxy.cfg.example#L16)(haven't found in the code) which is used to redirect user back to oauth2-proxy once the Idp part is done gotten from "Host" header

Is there any way to dynamically form this callback URL? We need
X-Forwarded-Proto + X-Forwarded-Host + Original-path + "/oauth2/callback"

**Comment by JoelSpeed** [comment]
Typically your identity provider will need to know ahead of time where the callback URL is for OAuth2 Proxy, this is part of the security requirements of OAuth2.

Does you IDP allow dynamic callback URLs? Is there any reason you need to host the same OAuth2 Proxy under multiple domains and can't share it in a centralised fashion under its own domain?
