### ISSUE TITLE
Multiple GitHub organizations support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [oauth2-proxy/oauth2-proxy#1602]
## Expected Behavior

```go
type GitHubProvider struct {
	*ProviderData
	Orgs  []string
	Team  string
	Repo  string
	Token string
	Users []string
}
```

## Current Behavior

```go
type GitHubProvider struct {
	*ProviderData
	Org   string
	Team  string
	Repo  string
	Token string
	Users []string
}
```

## Possible Solution

- `config.github_org` can be comma separated list of allowed organizations
- `config.github_org` can be deprecated and `config.github_orgs/config.github_organizations` used instead

## Context

I need to setup ui access to multiple organizations members

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
If this can be done in a  backwards compatible way I don't see a reason not to
