### ISSUE TITLE
Invalid scope when specifying allowed groups

### ISSUE THREAD

**Issue by ampc** [oauth2-proxy/oauth2-proxy#1604]
Invalid scope when specifying allowed groups

## Context

Using Keycloak and oauth2-proxy, I'm trying to restrict access to specific groups.
I'm using the following configuration:
```
providers:
  - approvalPrompt: force
    clientID: AuthProvider
    clientSecret: xxxxxx
    allowedGroups: ["bananas"]
    id: keycloak-oidc=AuthProvider
    oidcConfig:
      emailClaim: email
      groupsClaim: groups
      insecureSkipNonce: true
      issuerURL: https://xxxxx/auth/realms/kubernetes
      userIDClaim: email
      insecureAllowUnverifiedEmail: true
    provider: keycloak-oidc
 ```
 I get this error
 **Login Failed: The upstream identity provider returned an error: invalid_scope**
 
 Logs:
 ```
 [2022/03/25 19:33:32] [oauthproxy.go:714] Error while parsing OAuth2 callback: invalid_scope
10.92.142.166 - 029927d7d734cd842740e61e2d51a27a - - [2022/03/25 19:33:32] argocd-customer.apps.domain.azure.cloud.example GET - "/oauth2/callback?error=invalid_scope&error_description=Invalid+scopes%3A+openid+email+profile+groups&state=NF9RFeZk44HwCdTDH9cavXrhaU1wprJ5ZZqxhAWwE1E%3Ahttps%3A%2F%2Fargocd-customer.apps.domain.azure.cloud.example%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36" 403 2801 0.000
10.244.2.145 - fe4209c66b6e6abe268710d60219cc2a - - [2022/03/25 19:33:32] argocd-customer.apps.domain.azure.cloud.example GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36" 401 13 0.000
10.92.142.166 - 17388fa65b8041834c133c1eef6ef370 - - [2022/03/25 19:33:33] argocd-customer.apps.domain.azure.cloud.example GET - "/oauth2/start?rd=https://argocd-customer.apps.domain.azure.cloud.example%2Ffavicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36" 302 524 0.000
10.92.142.166 - 92748bce8450cf77555c1fbc4a27411a - - [2022/03/25 19:33:33] argocd-customer.apps.domain.azure.cloud.example GET - "/oauth2/callback?error=invalid_scope&error_description=Invalid+scopes%3A+openid+email+profile+groups&state=GSJPPvtLJF28mryHUPP9oBcfNGGn0xlTo1WPB1BKFHY%3Ahttps%3A%2F%2Fargocd-customer.apps.domain.azure.cloud.example%2Ffavicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36" 403 2801 0.000
[2022/03/25 19:33:33] [oauthproxy.go:714] Error while parsing OAuth2 callback: invalid_scope
```
 

## Your Environment

- Version used:
oauth2-proxy: 7.2.0
keycloak:  15.0.2

**Comment by braunsonm** [comment]
As it state you need to provide a scope, it looks like you aren't providing any. The scope you need to provide depends on your keycloak installation so unfortunately we can't be much help on that front;.

**Comment by ampc** [comment]
This only happens when I added the "allowedGroups" option. Is it possible to know which changes are done after enabling this option?

**Comment by ampc** [comment]
Found the problem. Somehow after enabling **allowedGroups** option the default scope is overridden.
Fixed by adding
    scope: openid email profile

**Comment by braunsonm** [comment]
Ah yes I see the confusion, you can see here we add `groups` to the scopes if you have `allowedGroups` set
https://github.com/oauth2-proxy/oauth2-proxy/blob/ce750e9b301ac66b3b8cbdbd0bc8ac7415bfed79/providers/providers.go#L159

I'm not sure if this is a great default behaviour to be honest. That scope may not be defined for all providers. `groups` is not like `openid email profile` which are agreed upon in the standard.

Thoughts? @JoelSpeed

**Comment by willhargan** [comment]
Not sure if this should be in a separate issue but I've had the same issue of an invalid scope using the github provider set to specific teams. It sends a scope of `openid email profile read:org` which doesn't include the user:email that github is expecting and thus errors out. 

I followed the suggestion here to set a scope manually and got it working but I feel like the scope shouldn't need to be manually set.

**Comment by JoelSpeed** [comment]
> I'm not sure if this is a great default behaviour to be honest. That scope may not be defined for all providers. groups is not like openid email profile which are agreed upon in the standard.

Yeah this is not great behaviour, IIRC we only do this if the scope hasn't been modified (or we had intended that to be the case). Does setting scope explicitly prevent this from happening? We should make sure it's only the default value that gets this magic treatment

**Comment by JoelSpeed** [comment]
> I followed the suggestion here to set a scope manually and got it working but I feel like the scope shouldn't need to be manually set.

In general I lean towards making more of these things user configurable rather than implicit, it makes the user experience more predictable and leads to fewer confusing issues such as this one

**Comment by CAR6807** [comment]
Bump, this is a bad user experience since it is not documented well in the options section for either scope or Allow groups.
Especially since there is a usually an upstream that handles the authorization based on login response from the proxy. 
FYI if running in containers/kube.
`--scope=openid profile email groups`
Other work around is specify Allow Groups but with a widely populated group.
`--allowed-groups=EVERYUSER`

**Comment by JoelSpeed** [comment]
Has any one got time to look into getting a fix up for this?

**Comment by tuunit** [comment]
I repurposed @jjlakis PR #2392 and implemented a new flag to be able to disable the implicit groups scope additions. With this flag we stay backwards compatible and have no breaking change.

**Comment by tuunit** [comment]
> > I followed the suggestion here to set a scope manually and got it working but I feel like the scope shouldn't need to be manually set.
> 
> In general I lean towards making more of these things user configurable rather than implicit, it makes the user experience more predictable and leads to fewer confusing issues such as this one

Hi @JoelSpeed,

would you prefer the approach I implemented in JJs PR or his original solution of just removing the implicit logic:
https://github.com/oauth2-proxy/oauth2-proxy/commit/d473f496821d136f5bba03c3876893a315314197

**Comment by JoelSpeed** [comment]
In an ideal world, users are setting their scope explicitly. And in that same world, we should never modify their scope. If they are not setting their scope explicitly, then us adding the groups scope for them is also reasonable IMO.

I would rather we didn't add a flag for disabling the implicit behaviour, but to avoid this being a majorly breaking change, is it possible to retain the implicit behaviour for now when the scope is not the default?

**Comment by tuunit** [comment]
> is it possible to retain the implicit behaviour for now when the scope is not the default

@JoelSpeed sorry but I don't really get what you expect.

Please clarify:

1. Only add the `groups` scope for people who DON'T explicitly set the scope at all (using the default scopes + groups in case of `allowed_groups`)?
2. Only add the `groups` scope for people who DO explicitly set the scope (in case of `allowed_groups` being used) and DON'T set the `groups` for people who use the default by NOT setting the scope explicitly (this scenario doesn't sound like it makes a lot sense)

**Comment by JoelSpeed** [comment]
I had meant option 1.

If you have an opinion about scope, we should not mess with that.

If you have no opinion about scope, we can choose your default scope based on the other options you provided

**Comment by tuunit** [comment]
@JoelSpeed the behaviour is already like in option 1. Result of a bugfix I merged last year in december:

https://github.com/oauth2-proxy/oauth2-proxy/pull/2197

**Comment by tuunit** [comment]
I therefore see this issue as closed. I extended the test cases and documentation in PR#2392

**Comment by JoelSpeed** [comment]
Then I think we are ok, but should document this. If you haven't specified an opinion, and we think that for the majority of people, we can choose a sensible default, and that default is not ok for you, then, specify an opinion! 😅 

Something we use a lot at work when designing APIs (to configure operators and applications so similar in a way)
```
When omitted, this means no opinion, and the platform is left to choose a reasonable default, subject to change over time.
```
I think we can also embody that mantra.

**Comment by tuunit** [comment]
Sounds good to me!
