### ISSUE TITLE
Dockerfile requires --platform support in docker build, this is not documented.

### ISSUE THREAD

**Issue by eigood** [oauth2-proxy/oauth2-proxy#1605]
In the makefile, there is a "docker buildx", but that is not a valid command.  And "docker build --platform" requires turning on experimental flags.

I was attempting to compile against master, to fix the keycloak-oidc, which is broken for me as well.

**Comment by JoelSpeed** [comment]
Docker buildx is an extension to the normal docker build chain that allows us to build cross compiled images from our local machines, please follow these instructions if you wish to use it (though it is installed by default on most docker installs now from what I can tell)

https://docs.docker.com/buildx/working-with-buildx/
