### ISSUE TITLE
Add support for adding custom headers to requests to the OIDC server?

### ISSUE THREAD

**Issue by sindre-nistad** [oauth2-proxy/oauth2-proxy#1609]
## Expected Behavior

Be able to add a header to all reqests that `oauth2-proxy` sends to the designated OpenID Connect server / endpoint.

## Current Behavior

It doesn't support this.

## Possible Solution

I'm currenly experimenting with [mitmproxy](https://mitmproxy.org/) to add the headers when necessary.
This should work, but requires a non-trivial amount of extra work, and configuration.

## Context

I am using [Azure API Management ](https://azure.microsoft.com/services/api-management/#overview) to access a KeyCloak server, which runs on-prem.
This requires using a "[subscription key](https://docs.microsoft.com/en-us/azure/api-management/api-management-subscriptions)", which is added to a header (`Ocp-Apim-Subscription-Key` by default).
I'd like to add this to the configuration / command line argument, preferably as something similar to `--additional-request-headers=Ocp-Apim-Subscription-Key=<secret key goes here>`

## Your Environment

I'm using it as a container with an API, a single page application, and a NginX proxy

- Version used: 7.2.1

**Comment by braunsonm** [comment]
Adding arbitrary headers to requests to upstreams is probably out of scope for oauth2-proxy. Your LB/Ingress should be doing this instead

**Comment by sindre-nistad** [comment]
How would that work when `oauth2-proxy` is making a TLS request to the OpenId-connect provider?

I may have been unclear in my description. Sorry for that.

**Comment by sindre-nistad** [comment]
Thanks for the update :)

Update: For my use case, it wasn't enough to add the header; I tried adding it with [mitmproxy](https://mitmproxy.org). That worked as expected, but it there where additional issues.

**Comment by savitha-qs** [comment]
What's the status of this ticket? I'm interested in it as well. I'd like to use `oauth2-proxy` with `PKCE` using an Azure App Registration for a SPA. However, it fails with this error:

```
Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests
```

Apparently, the Azure token endpoint requires an `Origin` header. I need to be able to configure`oauth2-proxy` to send it. 

Any idea on workarounds?
