### ISSUE TITLE
How to create and use tokens with oauth2_proxy

### ISSUE THREAD

**Issue by pedreen** [oauth2-proxy/oauth2-proxy#161]
Hello guys!
I configured my endpoint with oauth2_proxy using google as provider on kubernetes in GCP. For use via browser it worked normally however to make a request by code I need a token to validate the request. I would like to know if with the pusher / oauth2_proxy container it is possible to generate this token for my request. I will pass the configuration I made of my oauth2_proxy.yml and pass my endpoint (I put it to return the _oauth_proxy which is the cookie, to do a test only).

Oauth2_proxy.yml:
[oauth2_proxy.zip](https://github.com/pusher/oauth2_proxy/files/3213913/oauth2_proxy.zip)

This is my API: https://pedro.4intelligence.com.br

This is my ingress:
[ingress.zip](https://github.com/pusher/oauth2_proxy/files/3213919/ingress.zip)

**Comment by tbrandsma-rw** [comment]
I am interested in this too!

**Comment by xynova** [comment]
It would be nice to generate tokens that could be used by CLIs for sure and not have to rely on a different tool for the job. +1

**Comment by davidholsgrove** [comment]
Hi @JoelSpeed, I too would like to know if this is possible and if it is, we can have an example in curl / postman to show the steps in the Readme perhaps?

**Comment by sitsofe** [comment]
@pedreen do you mean cookie rather than token?

**Comment by 5331k** [comment]
Hi @pedreen , Are you able to achieve, what you are trying to do, i am also looking for solution
