### ISSUE TITLE
Option `--insecure-oidc-allow-unverified-email` doesn't work when email property is absent in token

### ISSUE THREAD

**Issue by artur-ptaszek-mck** [oauth2-proxy/oauth2-proxy#1612]
While using M2M communication we use `--skip-jwt-bearer-tokens` to allow our api consumers to pass `Authorization: Bearer` headers. It works for regular tokens retrieved via authorization flow, but doesn't if we provide token generated for M2M authentication. The flag `--insecure-oidc-allow-unverified-email` proves to be working with tokens with fields: `scope: email, email: email@example.com, email_verified: false`, but doesn't work when it's lacking an email, but has `scope: email, email_verified: false`.

## Expected Behavior

Option `--insecure-oidc-allow-unverified-email` to be respected even if `email` property is absent.

## Current Behavior

Option `--insecure-oidc-allow-unverified-email` doesn't work when _email_ field is absent.

## Steps to Reproduce (for bugs)

1. Retrieve token from IdP with the following contents:
```json
{
  "exp": 1649332359,
  "iat": 1649328759,
  "jti": "jti",
  "iss": "<issuer_url>",
  "aud": "<audience_url>",
  "sub": "<subject_id>",
  "typ": "Bearer",
  "azp": "<client_b_id>",
  "acr": "1",
  "scope": "profile email",
  "email_verified": false,
  "clientId": "<client_b_id>",
  "preferred_username": "service-account-<client_b_id>"
}
```
2. `curl -XGET http://localhost:4180/oauth2/auth -H 'Authorization: Bearer <token_from_previous_step>'`
3.  I get the following error
```
172.18.0.1 - 3a99938a-3e49-46bf-a763-40a9eb3d59d1 - - [2022/04/08 06:17:16] localhost:8088 GET - "/oauth2/auth" HTTP/1.1 "curl/7.77.0" 401 13 0.000
[2022/04/08 06:17:16] [jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, oidc: expected audience "<client_id_a>" got ["<audience_url>"], email in id_token (<subject_id>) isn't verified]
```

## Context

Our IdP has set by default the following scope: `profile email` which we cannot override by defining parameter _scope_ while issuing M2M tokens. So for these if email is not defined (M2M users don't have an email), then we get absent `email` property, but present `email_verified: false`.

## Your Environment

- Version used: 7.2.1
- Command line options:
```
--http-address=:4180
--provider=oidc
--cookie-secret=<cookie_secret>
--skip-jwt-bearer-tokens
--extra-jwt-issuers=<issuer_url>=<audience_url>
--insecure-oidc-allow-unverified-email
--client-id=<client_id_a>
--client-secret=<client_secret_a>
--redirect-url=http://localhost:8088/oauth2/callback
--oidc-issuer-url=<issuer_url>
--email-domain=*
--upstream=static://202
--reverse-proxy=true
```

**Comment by JoelSpeed** [comment]
This is a limitation of the legacy authorization layer we have implemented. We are intending to change this in a future release, but for now, authz requires having an email address. For now the workaround is to have a dummy email address field or set the email claim to some other value, perhaps `--oidc-email-claim=sub` might work for you?

**Comment by artur-ptaszek-mck** [comment]
Thanks for a response. I tried proposed solution, but issue persists. I get the same error.

Do you have any timeframe on this refactor? I'm eager to use `oauth2-proxy` :)

**Comment by JoelSpeed** [comment]
Apologies, no specific timeline. This project is a passion project and myself and the other maintainers only work on it during our spare time, so projects like this can be slow

**Comment by AlexanderWells-diamond** [comment]
I encountered the same problem. The workaround I used was to use these lines in the config file:
```
oidc_email_claim="id"
email_domains = [ "*" ]
```
The `id` field in my IdP provides the username, and by explicitly allowing all "email" domains `oauth2-proxy` won't attempt to validate the contents of the `id` field. Not perfect, as we cannot filter using the `email_domains` option, but we didn't have a proper email address returned anyway so its no real loss.

**Comment by artur-ptaszek-mck** [comment]
Sorry for asking for timeframe... Too much time spent in client projects :D 

Good news is with new version of _oauth2-proxy_ I could use the following parameter:

```
--oidc-extra-audience=<audience_url>
```

It solved the issue I had!

**Comment by ajarmada** [comment]
@JoelSpeed Is this issue fixed in latest versions of OAuth2-Proxy?
