### ISSUE TITLE
Feature idea: Provide a Traefik plugin

### ISSUE THREAD

**Issue by piotrgwiazda** [oauth2-proxy/oauth2-proxy#1613]
Using oauth2-proxy with ForwardAuth in Traefik is one of the most powerful options. It would be fantastic of Oauth2 proxy was available as a Traefik plugin (if possible(.

## Expected Behavior

Provide all Oauth2 proxy features in Traefik as a plugin avoiding running two separage processes/pods and forwarding requests. Traefik has new plugin feature.

## Current Behavior

Oauth2 proxy runs side by side with Traefik and requires forwarding requests.

## Possible Solution

Traefik provides plugin features. Not sure if it is possible to run Oauth2 proxy as a plugin.

## Steps to Reproduce (for bugs)

N/A

## Context

This will simplify setting up oauth2-proxy with Traefik ingress protecting access to certain paths and still handling SSL/TLS and edge routing with Traefik. Compared to ForwardAuth this could reduce the latency.

## Your Environment

Kubernetes

**Comment by JoelSpeed** [comment]
Do you have links for any documentation or an understanding of what might be involved to achieve this? While it sounds interesting I think it would likely mean we have to make big architectural changes which do not align with the rest of the project goals at the moment

**Comment by piotrgwiazda** [comment]
Here is the documentaton https://doc.traefik.io/traefik-pilot/plugins/plugin-dev/. It is basically implementing one function that has access to both request and response object. 
Plugins are however executed by Yaegi interpreter rather than precompiled. This might be a limitation.

**Comment by JoelSpeed** [comment]
Thanks for the link, I've had a read through and it does look interesting. This looks like something we may be able to support in the future, but the issue to me currently is that the configuration for OAuth2 Proxy is very complicated and unlikely to be compatible with the way Traefik expects to run. We may be able to create a plugin once we have refactored a bit more of the code, but for now, I think there's a lot of work ahead
