### ISSUE TITLE
Request a troubleshooting guide

### ISSUE THREAD

**Issue by lknite** [oauth2-proxy/oauth2-proxy#1618]
I wonder if it might be appropriate to add a general troubleshooting guide to the website?

I've followed a guide provided at the nginx-ingress website which references this oauth2-proxy:
https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

Afterwards, I began troubleshooting issue after issue searching past issues here on github looking for answers.

At the moment I have an azure identity server setup which gives 500 by default, 403 if I refresh the screen, and 502 if I provide "--upstream" server, where as in another environment I'm trying to use keycloak I end up on the target site but without a bearer token having been passed.  In my oauth2-proxy log I can see the return values 500, 403, 502, 302, ... but no errors, nor any errors in the nginx-ingress log.

This product seems really well-made and refined, with lots of configuration options, but I don't know which ones I should be using.

It's like I'm always so close, yet so far way ...
```
[AuthSuccess] Authenticated via OAuth2: Session{
```

**Comment by JoelSpeed** [comment]
I would love to have a troubleshooting guide, but this project is so complex, and we have so little time to spend on it, I don't know if I could do it justice with my current commitments already.

If anyone happens to have time to start making notes, that is definitely appreciated

**Comment by lknite** [comment]
# Welcome
Welcome to the oauth2-proxy troubleshooting / deep dive guide.

# What is oauth2-proxy?
oauth2-proxy is an implementation of an Authorization Proxy.  An authorization proxy has two use cases (not specific to identity server providers):
- protect a website (or webapi) without any security by adding a layer in front of it to handle authentication (credential gathering) and authorization (such as via the use of a groups claim)
- gather up credentials and generate a bearer token which can then be passed along to a website (or webapi) which implements security using a bearer token (such as the [kubernetes dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/))

# Summary
In this guide we will walk through the workflow of oauth2-proxy with references to log files so that you can turn on debugging and follow along in your own setup.  We will present the workflows of the two use cases listed above.

The steps given in this guide should be followed if you are running into any difficulties getting things to work.  It can also just be fun to watch and understand better how OIDC works, as well as more directly understand the way oauth2-proxy securely protects its backend-sites.

# Diagram
typical odic workflow diagram goes here

# Why is oauth2-proxy needed?
OIDC is a modern standard allowing web applications to removing a layer of complexity allowing an Identity Service Provider to handle the gathering of credentials, password resets via email, account management etc.  Modern apps often have OIDC settings integrated into them, but it is common for an app to not yet have OIDC integrated for many reasons, this is where oauth2-proxy shines.
