### ISSUE TITLE
Question: oauth2-proxy with Forward proxy

### ISSUE THREAD

**Issue by rohrit** [oauth2-proxy/oauth2-proxy#1619]
Would oauth2-proxy be able to act as an authentication service in a forward proxy scenario where requests might be sent to any arbitrary domain (e.g. google.com, facebook.com etc.)?

The flow would be 

browser --> forward proxy --> oauth2-proxy --> proxy connect to eventual domain

From what I have seen, there does not seem to be a way to do this with oauth since cookie domains are set for a particular domain and the callback URLs cannot be set per domain since it would not be scalable. Please let me know if I have missed some way of deploying this which would make this feasible.

**Comment by JoelSpeed** [comment]
I don't think this would be possible as you say, the cookies must be accessible to OAuth2 Proxy and so must be on a domain with the request path (it can be a similar domain if the cookie is shared across subdomains).

**Comment by rohrit** [comment]
@JoelSpeed , thanks for the quick response and confirmation. we do use oauth2-proxy for other use cases and love the work you guys are doing!
