### ISSUE TITLE
Question: Is it possible to override the header key x-forwarded-access-token?

### ISSUE THREAD

**Issue by theanhdh** [oauth2-proxy/oauth2-proxy#1620]
I was able to get the Oauth2 Proxy to forward the access token to the back-end APIs, but was looking for way to override the default header key generated by Oauth2 Proxy which is "x-forwarded-access-token", is it even possible?

**Comment by JoelSpeed** [comment]
If you use our alpha configuration, you can customise this, have a search through previous issues for header examples where other users have done this

**Comment by theanhdh** [comment]
Thank you very much @JoelSpeed
