### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by kschu91** [oauth2-proxy/oauth2-proxy#1624]
Hi folks,

When did you plan the next relase of oauth2-proxy? There are a couple of issues that are going to be fixed in the next relase.
Would be awesome to see a new release soon :)

I am especially waiting for #1204 

Let me know if I can support with anything.

Cheers!

**Comment by JoelSpeed** [comment]
Hi, I want to get #1502 and #1578 merged before we cut a release, I have just poked both PRs and if there's no response soon and I manage to get through my backlog of OAuth2 Proxy stuff, I will fix them up myself. Alternatively if you are able you could take a look and try to help move them along

**Comment by JoelSpeed** [comment]
7.3.0 is now available, docker images will be pushed shortly
