### ISSUE TITLE
unmarshalling data to session state fails

### ISSUE THREAD

**Issue by salmanisd** [oauth2-proxy/oauth2-proxy#1627]
I am running oauth2-proxy v7.2.1 and running into the following error when I try to sign in.
The authentication is successful as seen in the oauth2-proxy logs but immediately comes the error 
`[stored_session.go:77] Error loading cookied session: error unmarshalling data to session state: msgpack: invalid code=d7 decoding bytes length, removing session
`
I have tried with both redis and cookie storage.
On wireshark, I see oauth2-proxy setting the `_oauth2_proxy_` cookie (to the browser) on authentication but afterwards its processing fails. And since the cookie is encrypted, I really cant say whats going on.

Any ideas whats going on or how I can further debug this issue?

**Comment by JoelSpeed** [comment]
It looks to me like your session is somehow being corrupted, resulting in an unfinished session being loaded.

Can you share more information about your setup so that we can suggest possible avenues to investigate?

**Comment by bparquet** [comment]
I've run into the exact same problem. I think there is something in my session state that msgpack can't handle correctly. I was able to get past this problem by rebuilding oauth2-proxy using `github.com/vmihailenco/msgpack/v5 v5.3.5` instead of v4 and update session_state.go and csrf.go.

**Comment by JoelSpeed** [comment]
If you believe this to be a bug, would you have time to open a PR with the changes you've made?
