### ISSUE TITLE
Add provider tls capability

### ISSUE THREAD

**Issue by bputt-e** [oauth2-proxy/oauth2-proxy#1628]
We're looking to add tls cert/key to the provider when it reaches out to talk to one of the supported providers (gitlab in our case) in a PKI environment.

## Expected Behavior

It would be great if we could get the following cli arguments:

```
--provider-tls-cert-file
--provider-tls-key-file
```

Those would compliment ```--provider-ca-file``` which would enable us to talk to the provider using our certs.

## Current Behavior

Since we can't specify a cert/key when talking to the provider, we get an error where it expects a valid cert to talk to the provider. 

## Possible Solution

Adding the ability to attach a cert/key to the code that talks outbound to the various providers

## Context

We are in a PKI environment and need certs to talk to any website.

- Version used: 7.2.1

**Comment by JoelSpeed** [comment]
This seems like a reasonable feature request. While we aren't likely to implement this ourselves due to time constraints, we are happy to work with someone reviewing designs and pull requests if you have the time to work on an implementation

**Comment by marcindulak** [comment]
[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by JoelSpeed** [comment]
If you believe this issue should be maintained and kept alive, I'm happy to reopen. We use the stale bot on this repo because, quite often, issues get answered and then never closed, the timeout allows us to close out those issues no one else is interested in.
