### ISSUE TITLE
cli or app client authentication 

### ISSUE THREAD

**Issue by jchenship** [oauth2-proxy/oauth2-proxy#1629]
oauth2-proxy works great for human access, but we also want to use cli to interact with the upstream website with authentication. 

## Current Behavior

related to https://github.com/oauth2-proxy/oauth2-proxy/issues/1126 but that ticket is closed without giving an ideal solution 

There's 1 possible solution at the moment which is using the id token in the `Authorization` header and configure `--skip-jwt-bearer-tokens` and `--extra-jwt-issuers`. But there are 2 issues with it

1. the google groups check won't work because the id token we got from google doesn't have the groups claim, so the session data won't have the groups information, so the session check always failed. If it's human access, the groups information is added at the callback stage, where the code calls google api to enrich the session before it returns to the user
2. we need to manage the logic to refresh the id token at the cli side, which kind of duplicates the logic that oauth2-proxy is doing

Another way is somehow we need to get the `_oauth2_cookie` but there's no ideal way to do that via cli at the moment.

## Possible Solution

oauth2-proxy can support more than 1 callback url, this issue might be related https://github.com/oauth2-proxy/oauth2-proxy/issues/1600 . So the flow will become

1. the cli generates the google oauth2 login start url, set the callback url with something like `localhost:8080` (temp server started by cli), and display the url to the user
2. user clicks the url, finishes google auth flow in browser and google redirects the authorization code to `localhost:8080`
3. the cli calls oauth2-proxy `oauth2/callback` with the code and all other information (client id, state, scope etc) redirected from google
4. oauth2-proxy redeems the code, set the auth cookie `_oauth2_proxy` and `session` and can be used by the cli later

this way we might also need to handle the csrf cookie

**Comment by jchenship** [comment]
also see this maybe can use as a reference https://www.pomerium.com/docs/topics/programmatic-access.html

**Comment by JoelSpeed** [comment]
I'm not sure this is something we are likely to support any time soon. Our priorities as maintainers at the moment is to try and refactor the code and make it easier to maintain, and to make the project easier for users.
This seems like a major new feature so i would suggest we wait to start on this until our other projects are concluded

**Comment by jonathandavis805** [comment]
Any progress on this? It's been a few years and I feel like some other issues have been resolved related to this use case but I can't figure out how to put it all together.
