### ISSUE TITLE
Error loading cookied session: failed to load the session state with the ticket: error loading redis session: dial tcp: i/o timeout, removing session

### ISSUE THREAD

**Issue by r-kotagudem** [oauth2-proxy/oauth2-proxy#1630]
@JoelSpeed @NickMeves 
When oauth2-proxy hits redis for session data, we are seeing below error occasionally causing request retrigger login flow.

GMT [2022/04/27 06:29:58] [logger.go:508] Error loading cookied session: failed to load the session state with the ticket: error loading redis session: dial tcp: i/o timeout, removing session

both oauth2-proxy and redis are running as pods in eks cluster.

using istio sidecar and ext_authz filter to redirect to oauth2-proxy

Could this be due to resource limit hit by redis or any other cause? Any insight into this issue is highly appreciated.

** there is no restart of pods at the time we saw this error

**Comment by r-kotagudem** [comment]
Is there a way we set the timeout for outgoing connections from oauth2-proxy 
timeout for connecting to IDP
timeout for connecting to redis

We see this errors in productions and would appreciate any insight into this issue

**Comment by JoelSpeed** [comment]
Currently no, but this is definitely something we should look into. I'd welcome a PR to solve the issue if you have thoughts on how best to achieve this.

**Comment by Dimss** [comment]
might be related to this #1691
