### ISSUE TITLE
Question: Availability of prebuilt docker image from quay.io

### ISSUE THREAD

**Issue by lukemaslany-next** [oauth2-proxy/oauth2-proxy#1633]
More of a general question than an issue.

While on quay.io earlier today I spotted a notice stating:

> On June 1 2022, Repository Signing and App Registry will be removed from quay.io. Users should migrate to use alternatives which are now natively supported (Cosign & Helm respectively)

I was curious as to whether the prebuilt docker image will still be accessible from quay.io/oauth2-proxy after June 1, 2022?

If not, will it be hosted elsewhere?  Or do we need to start looking at building our own image?

Much appreciated,

**Comment by JoelSpeed** [comment]
The changes on Quay will not affect this project, the image hosting is not changing, we do not use repository signing, nor do we use the app registry
