### ISSUE TITLE
Docs: link in cookie-secure description (set secure (HTTPS only) cookie flag) is dead

### ISSUE THREAD

**Issue by jwaffe75** [oauth2-proxy/oauth2-proxy#1637]
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#command-line-options

This link is dead (404) https://owasp.org/www-community/controls/SecureFlag

It's also dead in the "next" version of the docs page too https://oauth2-proxy.github.io/oauth2-proxy/docs/next/configuration/overview#command-line-options , and in [master](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/docs/configuration/overview.md#command-line-options)

Maybe this is the right link? https://owasp.org/www-community/controls/SecureCookieAttribute

**Comment by JoelSpeed** [comment]
I think you're right, do you have time to put up a PR to fix the link in the current and next versions of the docs?

**Comment by jwaffe75** [comment]
Hello, 

Sorry, not at the moment.
