### ISSUE TITLE
grafana dashboard

### ISSUE THREAD

**Issue by tirelibirefe** [oauth2-proxy/oauth2-proxy#1644]
Hello,
I see my oauth2-proxy can send metrics to Prometheus.
![image](https://user-images.githubusercontent.com/45227339/167611440-99dbfdd2-fca4-4f8c-931e-501eef0d5d81.png)

I searched but couldn't have found, is there any Grafana dashboards can be used?

Thanks & Regards

**Comment by JoelSpeed** [comment]
We don't have any dashboards that are officially maintained but you may find some community contributions on the grafana hub
