### ISSUE TITLE
[Question] Cookie Expiration Behaviour

### ISSUE THREAD

**Issue by dmitriypavlov** [oauth2-proxy/oauth2-proxy#1645]
Greetings! Sorry if it is wrong place to post a questions.
While using cookies as a storage backend:

1. Does --cookie-expire only affects standard way of cookies expiration time?
2. Does OAuth2 Proxy stores expiration timestamp in the cookie body itself (besides the standard way)?
3. Is cookie expiration date signed/checksummed anyhow in the cookie body?

The questions I'm asking are for understanding whether I can leave 24h expiration time set in the config, take a cookie from my browser and use it in the third-party automation testing service and set the cookie to expire never there? The testing service needs a cookie to bypass OAuth Proxy with no expiration date. But all the rest (users, etc) need the limited timeframe.

The general question: can I safely change the expiration date on client side without consequences?
Thank you.

**Comment by JoelSpeed** [comment]
> Does --cookie-expire only affects standard way of cookies expiration time?

Yep

> Does OAuth2 Proxy stores expiration timestamp in the cookie body itself (besides the standard way)?

Yep

> Is cookie expiration date signed/checksummed anyhow in the cookie body?

The entire cookie body is signed and encrypted, and we check that signature before we read any information from the cookie

You won't be able to extend the time of the cookie without invalidating the cookie itself. If you need this kind of behaviour, you need to look into issuing a token from your identity provider and passing this via an authorization header to OAuth2 Proxy. Search the issues for M2M for hints on how to achieve this

**Comment by dmitriypavlov** [comment]
Got it, thanks.


Sent from my Apple Watch

**Comment by zohiba** [comment]
hi @JoelSpeed  how is the cookie encrypted? I see it is only base64 encoded. And the username is easily decoded. Is there any way to prevent this?

**Comment by JoelSpeed** [comment]
Which version are you running? The data within the cookies goes through some encryption based on the value of the cookie secret, so you shouldn't be able to review any of it within plaintext just by base64 decoding it. That may not have always been the case though
