### ISSUE TITLE
Go vet issue

### ISSUE THREAD

**Issue by joeybdub** [oauth2-proxy/oauth2-proxy#1646]
go vet ./... returns an issue when running
## Expected Behavior

Pass go vet ./...

go vet ./... 
# github.com/oauth2-proxy/oauth2-proxy/v7/pkg/requests
pkg/requests/result.go:18:2: method UnmarshalJSON() (*simplejson.Json, error) should have signature UnmarshalJSON([]byte) error
pkg/requests/result.go:72:18: method UnmarshalJSON() (*simplejson.Json, error) should have signature UnmarshalJSON([]byte) error

## Steps to Reproduce (for bugs)

1.  
go vet ./... 
# github.com/oauth2-proxy/oauth2-proxy/v7/pkg/requests
pkg/requests/result.go:18:2: method UnmarshalJSON() (*simplejson.Json, error) should have signature UnmarshalJSON([]byte) error
pkg/requests/result.go:72:18: method UnmarshalJSON() (*simplejson.Json, error) should have signature UnmarshalJSON([]byte) error
3.  
4.  
5.  

## Your Environment

- Version used:
- go 1.1.7 1.18

**Comment by JoelSpeed** [comment]
Hmm, looking at this, I guess we need to rename that function in the request builder to avoid the clash, perhaps `SimpleJSON()` or `UnmarshalSimpleJSON()` would work

**Comment by joeybdub** [comment]
yeah would be good if all references are changed also.
