### ISSUE TITLE
Azure ID: The redirect URI provided by oauth2-proxy always http (not https) till explicitly configured in oauth2-proxy.cfg file

### ISSUE THREAD

**Issue by romanstech** [oauth2-proxy/oauth2-proxy#1647]
Azure ID: The redirect URI provided by oauth2-proxy always http (not https) till explicitly configured in oauth2-proxy.cfg file

## Expected Behavior

As I see in https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/oauth2-proxy.cfg.example file redirect_url must be:
```
## the OAuth Redirect URL.
# defaults to the "https://" + requested host header + "/oauth2/callback"
```

## Current Behavior

Azure ID works only with https redirect URI. I receive the same error from Azure ID all the time (**pay attention on http:// scheme not https://**):
` AADSTS50011: The redirect URI 'http://<domain>/oauth2/callback' specified in the request does not match the redirect URIs configured for the application 'xxxxx'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.`

It means that oauth2-proxy always returns http URI. 
I tried different ways to solve this:
1. Add rd to the error_page 401: 
`error_page 401 = /oauth2/start?rd=$scheme://$host$request_uri; `
but in this case I receive an error 
`Rejecting invalid redirect "https://<domain>/": domain / port not in whitelist.` 
When I try to add the domain in oauth2-proxy.cfg file:
`whitelist_domain = "<domain>"`
oauth2-proxy fails.
2. I tried the latest version 7.2.1, v.7.2.0, v.7.1.3 — the same behavior.

## Possible Solution

I can solve the issue by explicitly providing **redirect_url** value inside **oauth2-proxy.cfg** file:
`redirect_url = "https://<domain>/oauth2/callback"`
With this definition Azure ID authentication starts working as requested.
But in this case I can't use a single oauth2-proxy process in my multi-subdomain environment. 
Also I tried to use:
`redirect_url = "https://{{.Host}}/oauth2/callback"`
but it didn't work as well.

_My purpose is to use a **single oauth2-proxy process** to authenticate all my Nginx instances for 15–20 subdomains._

## Steps to Reproduce (for bugs)

**oauth2-proxy.cfg:**
```
http_address = "127.0.0.1:4180"
reverse_proxy = true
email_domains = [
     "domain"
]
provider = "azure"
oidc_issuer_url = "https://sts.windows.net/id/"
custom_sign_in_logo = "/usr/local/share/azure_logo.png"
footer = '-'
client_id = "id"
client_secret = "secret"
skip_auth_routes = [
  "GET=^/probe",
  "^/metrics"
]
pass_user_headers = true
pass_host_header = true
set_xauthrequest = true
cookie_name = "_oauth2_proxy"
cookie_secret = "secret"
cookie_expire = "168h"
cookie_secure = false
session_store_type = "redis"
redis_connection_url = "redis://127.0.0.1:6379"
logging_filename = "/var/log/nginx-oauth2-proxy/auth.log"
logging_max_size = 100
logging_max_age = 30
logging_local_time = true
logging_compress = true
errors_to_info_log = true
standard_logging = true
request_logging = true
request_logging_format = "{{.Client}} - {{.Username}} [{{.Timestamp}}] {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}"
auth_logging = true
silence_ping_logging = true
real_client_ip_header = "X-Forwarded-For"
```

**nginx.conf (relevant part)**:
```
location /oauth2 {
        internal; # Ensure external users can't access this path
        proxy_pass http://localhost:4180;
        proxy_set_header Host                           $host;
        proxy_set_header X-Real-IP                      $remote_addr;
        proxy_set_header X-Scheme                       $scheme;
        proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
}
location = /oauth2/auth {
        internal; # Ensure external users can't access this path
        proxy_pass http://localhost:4180;
        proxy_set_header Host             $host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme         $scheme;
        proxy_set_header Content-Length   "";
        proxy_pass_request_body           off;
}
location / {
         auth_request /oauth2/auth;
         error_page 401 = /oauth2/start?rd=$scheme://$host$request_uri;
         auth_request_set $user   $upstream_http_x_auth_request_user;
         auth_request_set $email  $upstream_http_x_auth_request_email;
         proxy_set_header X-Auth-Request-User  $user;
         proxy_set_header X-Email $email;
         index  index_auth.html;
         try_files $uri $uri/ /index_auth.html ;
}
```

## Your Environment
RHEL 8.6
Nginx 1.20.2

- Version used:
- v7.2.1, 7.2.0, 7.1.3

**Comment by r-kotagudem** [comment]
Use cookie-secure=true to use https url for redirect url.. It should fix this issue

**Comment by romanstech** [comment]
> Use cookie-secure=true to use https url for redirect url.. It should fix this issue

Your are absolutely correct.
`cookie-secure=true`
solved the issue.
