### ISSUE TITLE
Can I use this repo to work with Tiktok?

### ISSUE THREAD

**Issue by zydjohnHotmail** [oauth2-proxy/oauth2-proxy#1652]
Hello:
I have Tiktok API key, but since I don't own any internet domain, I can't use Oauth2 to get access tokens from Tiktok.
I believe the Oauth2 in Tiktok is the same as Google Oauth2, so I want to know if I can use this repo to get access tokens from Tiktok.
You know that for all the people who don't own their own internet domains, it is nearly impossible to use Oauth2 in Tiktok directly.
Please advise,
Thanks,

**Comment by JoelSpeed** [comment]
This isn't something we have tried but you could try setting up OAuth2 Proxy on your local machine and using it to authenticate with TikTok. I can't promise this will work though as it's not something we have ever tried
