### ISSUE TITLE
Inject response headers not used while login flow

### ISSUE THREAD

**Issue by albert0815** [oauth2-proxy/oauth2-proxy#1653]
We planned to use the alpha feature which allows injecting response headers to add certain security relevant headers such as HSTS (strict-security-transport) or CSP (content-security-policy). Basically it works fine. But the very first request which forwards the user to the login form of the OIDC provider (we are using Keycloak and have skip_provider_button enabled) with a http 302 redirect does not contain those headers.

## Expected Behavior

The to be injected response headers should also be considered when a redirect to the login form is done.

## Current Behavior

Those headers are only considered after the login.

## Steps to Reproduce (for bugs)

Add a response header using alpha config inject response header and enable skip_provider_button. Request the page and observe headers.

## Your Environment

oauth2-proxy is deployed in Kubernetes using helm

- Version used: v7.2.1

**Comment by yanzv** [comment]
I am seeing the same issue using oauth2-proxy v7.4.0. Not sure if I should open a new issue or can get this issue  re-open. 
I am seeing that all oauth2-proxy endpoints do not response with injected response headers.  For example, `/oauth2/sign_out` and `callback?session_code=...` 
Is that something that can be enabled using configuration or would need code changes?

Thanks!

**Comment by JoelSpeed** [comment]
Hmm, it was never intended that the headers should be inject on unauthenticated requests, this would be a change in behaviour for existing users were we to change it now.

So the intention here is to make sure that, at least during the auth flow, you can set headers such as HSTS?  I suspect we will want a separate configuration for global headers to be added.

My typical response in this case is that you really should have something like nginx in front of OAuth2 Proxy to handle TLS termination and the additional configuration like this, do you have a proxy in front? Can you configure these headers there instead?
