### ISSUE TITLE
/tmp/ folder looks empty but in reality oauth2-pr seems to be fulling it

### ISSUE THREAD

**Issue by raz3r** [oauth2-proxy/oauth2-proxy#1654]
Hi,

I am using oauth2-proxy (latest version) with Nginx (latest version) on Debian 11. Yesterday we noticed Nginx was refusing a lot of connections and we realized the issue was the /tmp/ folder full. In reality the folder was completely empty but I've noticed the following with a lsof /tmp ->

oauth2-pr    506 root    1u   REG  254,3 37318952   11 /tmp/#11 (deleted)
oauth2-pr    506 root    2u   REG  254,3 37318952   11 /tmp/#11 (deleted)

Could it be that oauth2-proxy is doing something wrong in the background? A reboot fixed the error but now I've noticed with df-h that it started to grow again (yesterday it was 3%, now 6%). The VM is brand new, less than a month and the only software installed are Nginx and oauth2-proxy.

EDIT: today /tmp/ was at 11%, I killed oauth2-proxy and /tmp/ immediately got back at 3%.

**Comment by JoelSpeed** [comment]
This is weird, as far as I'm aware we don't use the tmp directory for anything while running. To be honest, I haven't a clue what this could be, have you done any deeper investigation?

**Comment by raz3r** [comment]
I believe I've found the issue, oauth2-proxy had logging to file disabled, once enabled the problem disappeared.

**Comment by JoelSpeed** [comment]
Well that's even weirder :sweat_smile: Ok, well at least we have some direction to look into. Not sure why logging to file changes this behaviour but we can take a look at the logger code and see if there's anything obvious there
