### ISSUE TITLE
Support X-Auth-Request-Groups for github provider

### ISSUE THREAD

**Issue by lotooo** [oauth2-proxy/oauth2-proxy#1655]
I am not able to get the X-Auth-Request-Groups header when using nginx auth-requests with Github provider.

## Expected Behavior

Usable `$upstream_http_x_auth_request_groups` variable (the same way as `$upstream_http_x_auth_request_user` and `$upstream_http_x_auth_request_email`). Currently the variable is empty.

## Current Behavior

Currently the header is empty so I can't get the list of teams that our users belong to (which would be really helpful for finer ACLs).
Hard to sniff the traffic between nginx and our auth-proxy instance as it is full HTTPS but my tests with nginx lead me to an empty header.

## Possible Solution

I am not sure I can help here ^^ 

## Steps to Reproduce (for bugs)

1. Use oauth-proxy with github provider  (with `--set-xauthrequest --reverse-proxy` flags).
2. Use nginx
3. Grab The X-Auth-Requests-Groups header and send it to the backend app (with `auth_request_set $groups  $upstream_http_x_auth_request_groups;` + `proxy_set_header   X-Forwarded-Groups $groups;`
4. Sniff the traffic between nginx and the app, the header is not set (because `$groups` is empty)

## Context

I am trying to make rundeck ACL work with github teams instead of users for dynamic ACLs.

I am not sure it is supposed to be supported, but the doc doesn't mention it is not supposed to work.
https://github.com/oauth2-proxy/oauth2-proxy/issues/845 makes me think it is a known issue but https://github.com/oauth2-proxy/oauth2-proxy/pull/1020 implies the opposite

## Your Environment

- Version used: 7.2.1

**Comment by alexisdondon** [comment]
Should it be possible to add some conf to put maybe  --github-repo --github-team or --github-org populate the X-Auth-Request-Groups?

**Comment by igorcezar** [comment]
Is there any update on this? I've tried to make it work by setting --github-team and --github-org, but still got the same problem. 
It seems is not getting any groups from the session:

https://github.com/supracarol/oauth2-proxy/blob/8abc4e6d876b2e4a5c348e05927b2c472fdfef9b/oauthproxy.go#L1034-L1040

**Comment by JoelSpeed** [comment]
> Should it be possible to add some conf to put maybe --github-repo --github-team or --github-org populate the X-Auth-Request-Groups?

Yes I believe this is the intention, but someone may need to dig through the GitHub provider code to work this out as GitHub is a bit of a special case

**Comment by josh-freeman-tradeweb** [comment]
This is still a missing feature today....
