### ISSUE TITLE
Automatically use end_session_endpoint for sign out via OIDC

### ISSUE THREAD

**Issue by jstsddg** [oauth2-proxy/oauth2-proxy#1656]
Use the `end_session_endpoint` setting of the `.well-known/openid-configuration` file for sign out in OIDC setups, if it is set and no other redirect URL is given.

## Expected Behavior

The `end_session_endpoint` setting should be honored automatically.

## Current Behavior

The `end_session_endpoint` setting is ignored and has to be setup automatically.

## Possible Solution

The application already accesses the OIDC endpoint `.well-known/openid-configuration` on startup and could (maybe depending on a setting to not break current setups) save the `end_session_endpoint` setting if it is set.
If the `/oauth2/sign_out` endpoint is called, the saved URL could be used to redirect.

## Steps to Reproduce (for bugs)

1.  Setup oauth2-proxy with OIDC
2.  Open /oauth2/sign_out
3.  Infinite redirect, even though `end_session_endpoint` is correctly set.

## Context

Create an (as simple as possible) configuration for multiple company internal products, which should just be copy-and-pastable. Hence automatic configuration would be incredibly useful.

## Your Environment

A docker-compose based setup with a nginx reverse proxy.

- Version used: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0

Thank you for your time!

**Comment by bradyfontenot** [comment]
Chiming in that this would be extremely helpful for our use case well in case this can be reopened.

**Comment by 0anton** [comment]
+1

**Comment by jstsddg** [comment]
unstale

**Comment by 0anton** [comment]
still relevant

**Comment by allanian** [comment]
+1

**Comment by jstsddg** [comment]
unstale

**Comment by JoelSpeed** [comment]
Has anyone explored what would be involved in implementing this? Maintainers will not have time to implement this in the near future, this would need to be a community contribution

**Comment by andrebreitenfeld** [comment]
+1

**Comment by jstsddg** [comment]
We moved to a native oAuth2 implementation in our services. Sadly, I wont have time to work on this as well.
