### ISSUE TITLE
Remove Unnecessary(?) check of Connection header when upgrading Websocket that can prevent websocket from being served from modern browsers

### ISSUE THREAD

**Issue by WareJosephB** [oauth2-proxy/oauth2-proxy#1659]
## Expected Behavior

When making a request with headers "Connection: keep-alive, Upgrade; Upgrade: websocket", the keep-alive should be ignored when checking if the request should be served by a Websocket, per [IETF protocol document](https://datatracker.ietf.org/doc/html/draft-ietf-hybi-thewebsocketprotocol-17#section-4), the Connection header must include Upgrade, but is not limited to exactly matching it. 

## Current Behavior

As removing the keep-alive headers from a request in Firefox and Chrome is not possible and I am limited in my browser choices at my workplace where I have access to the oauth2-proxy instance, I have not tested to ensure this is the specific behaviour, but it is a reasoned guess and warrants more testing:

Request with headers "Connection: keep-alive, Upgrade; Upgrade: websocket" fail [the test to check if they should be served on a Websocket](https://github.com/oauth2-proxy/oauth2-proxy/blame/ac188b129fcb6a0c9df6adbb88b7a90660e68423/pkg/upstream/http.go#L90)- this behaviour differs from [the tested behaviour](https://github.com/oauth2-proxy/oauth2-proxy/blame/ac188b129fcb6a0c9df6adbb88b7a90660e68423/pkg/upstream/upstream_suite_test.go#L94) which does not check the Connection header at all.

May not be the issue at all, as [this similar issue about GraphQL](https://github.com/oauth2-proxy/oauth2-proxy/issues/1524) may be related to my bug?

## Possible Solution 

(I am happy to make a merge request with these changes)
Adjust the two lines linked above to:
	if h.wsHandler != nil && strings.Contains(strings.ToLower(req.Header.Get("Connection")), "upgrade") && req.Header.Get("Upgrade") == "websocket" {

OR

	if h.wsHandler != nil && req.Header.Get("Upgrade") == "websocket" {

as @braunsonm (re: the Slack channel) can't think of a reason the check exists (as the IETF protocol document defines with the Connection: Upgrade, I think that should be still kept).

## Steps to Reproduce (for bugs)

I can probably wrangle the container images and charts onto our public repos if required, or else knock up a minimal reproduction.
oauth2-proxy running from the Helm chart within Kubernetes, with upstream of an ApolloGateway node server serving subscriptions over graphql-ws. Making requests through the oauth2-proxy with altair-graphql, served from the node server, on Firefox 91.5 on RHEL7, the request headers contain "Connection: keep-alive, Upgrade" and the request returns 400: Bad Request.

## Context

Trying to serve GraphQL subscriptions over graphql-ws through the oauth2-proxy when logged in.

## Your Environment

oauth2-proxy 7.2.1 running from the Helm chart, upstream an ApolloGateway supporting GraphQL subscriptions over graphql-ws.
Hitting the oauth2-proxy with a subscription effect from altair-graphql from Firefox 91.5 on RHEL 7, the query returns 400: Bad Request.

- Version used:

oauth2-proxy 7.2.1 from Helm chart 6.2.1, Firefox 91.5, RHEL 7.

**Comment by WareJosephB** [comment]
Found my issue was not caused by this, so I presume the keep-alive is being stripped out elsewhere- I can't find where so someone with more Go experience may want to take a look. May be an issue still

**Comment by braunsonm** [comment]
Still would be open to having a PR for this if you have time!

**Comment by braunsonm** [comment]
Still relevant

**Comment by braunsonm** [comment]
Keeping this active

**Comment by braunsonm** [comment]
Activity
