### ISSUE TITLE
cant use rbac on groups claim for k8s-dasboard

### ISSUE THREAD

**Issue by It-Prooffice** [oauth2-proxy/oauth2-proxy#1660]
## Expected Behavior

i want to define rbac by groups insted of single user, since we got a hell loads of users

i can allow groups in the oauth2-proxy, but it seems the group istn passed or i cant figure out what it calls it 

i can do rbac for a single user with

user
rof@email.dk

but if i try

group
k8sadmin

nothing happends 

this is the oauth2 log

172.16.69.224:60250 - 3f205f1eff5577e2e4890c4eac680a11 - rof@email.dk [2022/05/25 12:13:47] [AuthSuccess] Authenticated via OAuth2: Session{email:rof@email.dk user:CgNyb2YSBGxkYXA PreferredUsername: token:true id_token:true created:2022-05-25 12:13:47.697000864 +0000 UTC m=+795.167246960 expires:2022-05-25 20:13:46.696719965 +0000 UTC m=+29594.166966056 groups:[k8sadmin]}
172.16.69.224:60250 - 3f205f1eff5577e2e4890c4eac680a11 - - [2022/05/25 12:13:47] dashboard.domain.dk GET - "/oauth2/callback?code=g5udc233pjtzz6ndcmmhfp7ge&state=6xKclTqpwbj1wU3dDYyTGYsf87KloyfinBIW4aKM180%3Ahttps%3A%2F%2Fdashboard.domain.dk%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36" 302 58 0.018

## Your Environment

k8s 1.24
latest dashbord and oauth2-proxy versions using dex

- Version used:
Latest

**Comment by JoelSpeed** [comment]
Are you passing the authentication to the k8s dashboard using the authorization header and OIDC token? 

If so, please check the ID Token payload to ensure groups are present and then ensure you have set the oidc group's claim in the Kube API server configuration.

I know this should work, it's just a case of getting it configured correctly
