### ISSUE TITLE
allow use local css

### ISSUE THREAD

**Issue by K7cl** [oauth2-proxy/oauth2-proxy#1664]
## Expected Behavior

load page faster

## Current Behavior

load page very slow, because the html refer a css with src to a cdn link. that cdn usually not accessible in some location

## Possible Solution

allow user to store all necessary static assets locally, maybe by give a option to choice cdn or local path

## Context

Even I can solve this problem by compile a custom version, but i think is nice to have an option in official branch.

- Version used: 7.2.1

**Comment by JoelSpeed** [comment]
My recommendation would be to copy the templates from the [source](https://github.com/oauth2-proxy/oauth2-proxy/tree/master/pkg/app/pagewriter) (error.html and sign_in.html) and make the necessary changes and then provide them to OAuth2 Proxy using the `--custom-templates-dir` option. This kind of change is unlikely to be accepted as a core feature as there is already an easy workaround for users

**Comment by K7cl** [comment]
Thanks for reminder this. I'll try at next update.
