### ISSUE TITLE
v7.3.0 breaks azure provider

### ISSUE THREAD

**Issue by jeroenlandheer** [oauth2-proxy/oauth2-proxy#1666]
After installing v7.3.0 the `azure` provider breaks. Our configuration works with v7.2.1 but once I install v7.3.0 we get the following in the log file:

```
[2022/05/30 09:45:12] [azure.go:227] unable to get claims from token: could not get claim "groups": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "400":
```

I haven't seen any breaking changes in the change logs that should point to this, any ideas?

**Comment by knightian** [comment]
SAME!!!! `[2022/05/31 02:44:27] [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: invalid provider verifier options: missing required setting: issuer-url`

**Comment by erikgb** [comment]
Issues with Azure provider here also. Definitely a breaking change to make the `oidc-issuer-url` mandatory. 😞 

I wonder if the following comment might be relevant: https://github.com/oauth2-proxy/oauth2-proxy/pull/1135#issuecomment-812984657 (including responses)?

**Comment by erikgb** [comment]
And I think the breaking change in flag validations were introduced in https://github.com/oauth2-proxy/oauth2-proxy/pull/1559. Was that intentional @JoelSpeed - i.e. some kind of bugfix?

**Comment by knightian** [comment]
Looks like GitHub auth is also having issues. Is there any pertinent security issues that are addressed in this or is it fine to roll back and live on 7.2.1?

**Comment by knightian** [comment]
> > Looks like GitHub auth is also having issues. Is there any pertinent security issues that are addressed in this or is it fine to roll back and live on 7.2.1?
> 
> There has been a very long time since the 7.2.1 release, so my main concern is security vulnerabilities in the container images, some of them critical. I would prefer an urgent bugfix to the borked 7.3.0 release.

Yea that’s how I feel about it too, dependbot was screaming in my fork about vulnerabilities in dependencies, thus I figured it was probably important to update and made it a priority.

**Comment by erikgb** [comment]
I can confirm this issue here also, after working around the breaking config issue. Works with version 7.2.1.

**Comment by franktore** [comment]
Can confirm that oauth2-proxy with azure using oidc provider is broken. unable to get claims from token at callback url.

**Comment by AureaMohammadAlavi** [comment]
I had to change the provider type to `oidc` and add `oidc-issuer-url` argument to make it work with version `7.3.0`.

**7.2.1**
```
- --provider=azure
- --email-domain=example.com
- --upstream=file:///dev/null
- --http-address=0.0.0.0:1234
- --pass-user-headers
```


**7.3.0**
```
- --provider=oidc
- --email-domain=example.com
- --upstream=file:///dev/null
- --http-address=0.0.0.0:1234
- --pass-user-headers
- --oidc-issuer-url=https://login.microsoftonline.com/{TENANT_ID}/v2.0
```

**Comment by JoelSpeed** [comment]
OK, so we clearly have a couple of issues here which were not intentional breakages. Please note that none of the maintainers have easy access to Azure to test changes so we do rely on community feedback for this (and many other providers).

Let's start with the new requirement of having an `oidc-issuer-url` set. I believe this was a result of #1555 in which we moved the verifier initialisation into the providers package. Looking at the code, in the validation package, the old code would only initialise the verifier if the OIDC issuer URL was set. In the new code, we now have it so that we initialise the verifier if the provider expects to use one. If you look at [the azure code](https://github.com/oauth2-proxy/oauth2-proxy/blob/db74661e1099f27b07f7fb94469c94afcaf037bc/providers/azure.go#L219) you can see that it optionally skipped the verification of the token if the verifier wasn't initialised. 

Given this is insecure and the new behaviour is more secure, I'm tempted to call that a bug fix and require that users now set their Issuer URL whenever they use Azure, meaning their tokens are actually veriifed rather than being blindly trusted. Unless there are serious objections from the Azure users on this thread, I will retrospectively add a breaking change note to the changelog saying that users are now required to set their OIDC Issuer URL to provide a more secure default.

For the second issue, it looks like we are trying to make a request to the Azure profile URL to gather more information because either the email or groups are not included in the ID Token. This one is confusing me a bit because the 400 implies we aren't setting the correct header for authentication to Azure to fetch the profile URL, however, [this](https://github.com/oauth2-proxy/oauth2-proxy/blob/db74661e1099f27b07f7fb94469c94afcaf037bc/providers/azure.go#L346-L350) is the request we have been making historically, [this](https://github.com/oauth2-proxy/oauth2-proxy/blob/db74661e1099f27b07f7fb94469c94afcaf037bc/pkg/providers/util/claim_extractor.go#L97-L101) is the new request which should be identical.

Does anyone with access to azure have the ability to build a test image with some debug logging around these code areas to try and work out exactly what the issue is here?
I'm wondering if it is because the default profile URL is for v1 tokens and the users seeing this issue are using the v2 issuer URL? 

Could all in the thread please confirm if they are setting an issuer URL, what that is (obscured) and likewise with profile URL please?

**Comment by rouke-broersma** [comment]
@JoelSpeed fyi an azure tenant can be created for free, at which point you will have access to all features you need to test authentication. They are free features and as far as I know don't even require a credit card attached. If necessary I can create a tenant for you and hand it over to you, if interested.

**Comment by JoelSpeed** [comment]
@rouke-broersma Thanks for the heads up, I can look into that. The other issue really is time. I'm pretty short on it these days given this is now a hobby project and not something my employer grants me time to work on. Realistically we need to find engaged maintainers for each provider who can put in the time to make sure their providers are still working as we make changes

**Comment by erikgb** [comment]
> Given this is insecure and the new behaviour is more secure, I'm tempted to call that a bug fix and require that users now set their Issuer URL whenever they use Azure, meaning their tokens are actually veriifed rather than being blindly trusted. Unless there are serious objections from the Azure users on this thread, I will retrospectively add a breaking change note to the changelog saying that users are now required to set their OIDC Issuer URL to provide a more secure default.

@JoelSpeed I agree with your suggestion. This is a breaking change for the azure-provider, but should be ok with a mark in the release notes.

I am atually testing out the from @AureaMohammadAlavi in https://github.com/oauth2-proxy/oauth2-proxy/issues/1666#issuecomment-1145838016 now. I can say that the Azure v1 OIDC endpoint config (sts.windows.net) does not work with version 7.3.0. Hoping this will work with the oidc-provider and Azure v2 OIDC endpoint config (login.microsoftonline.com).

**Comment by franktore** [comment]
Thanks for looking into this @JoelSpeed. We are using `OIDC_ISSUER_URL="https://login.microsoftonline.com/<tenant-id>/v2.0"`
We do not have any `PROFILE_URL` specified in our config. On a different topic ( I should start separate thread for that ), long running requests are now suddenly giving 502 timeouts. Setting the `UPSTREAM_TIMEOUT` parameter seems to remedy this though, but I wonder why the timeout hasn't occurred for us previously.

**Comment by knightian** [comment]
@JoelSpeed --oidc-issuer-url="https://sts.windows.net/{tenant-id-here}/ but I wasn't using --oidc-issuer-url in 7.2.1 so I just added it as per the documentation I think

**Comment by knightian** [comment]
> Unless there are serious objections from the Azure users on this thread, I will retrospectively add a breaking change note to the changelog saying that users are now required to set their OIDC Issuer URL to provide a more secure default.

I see no reasonable objection, it's not hard to add the issuer once it's documented as a breaking change, and sounds like a security benefit obtained in comparing expected issuer against actual.

**Comment by erikgb** [comment]
I can confirm that the suggestion from @AureaMohammadAlavi in https://github.com/oauth2-proxy/oauth2-proxy/issues/1666#issuecomment-1145838016 works for me/us! Thanks! I am not sure if there are any downsides using the standard oidc-provider with Azure? Maybe the azure-provider should be deprecated and eventually removed?

**Comment by haydn-j-evans** [comment]
@erikgb havent looked too deeply in the code yet, but it seems in my case testing a user without a email address, the Azure provider populates the email field with the azure UPN, where the OIDC provider just fails.

In our case, our Azure tenant is literally just for our small department, and email fields are not required as our "main tenant" is the one that handles our contact info - so this would be a major regression for us without some tweaking of the OIDC provider to handle this situation.

**Comment by franktore** [comment]
In our case the OIDC provider fails to retrieve the group, email and preferred_username fields. perhaps others as well. It then attempts to fetch information from PROFILE_URL, but fails at that as it provides the wrong authentication. Failure mode is Invalid Audience.

**Comment by Silvenga** [comment]
Same for us, a 500 error is returned by oauth2-proxy upon failing to fetch from the profile endpoint.

**Comment by hevans-dglcom** [comment]
Hello @JoelSpeed, I have found the issue.

In this func, you had the azure provider set to true.

```
func providerRequiresOIDCProviderVerifier(providerType options.ProviderType) (bool, error) {
	switch providerType {
	case options.BitbucketProvider, options.DigitalOceanProvider, options.FacebookProvider, options.GitHubProvider,
		options.GoogleProvider, options.KeycloakProvider, options.LinkedInProvider, options.LoginGovProvider, options.NextCloudProvider:
		return false, nil
	case options.ADFSProvider, options.GitLabProvider, options.KeycloakOIDCProvider, options.OIDCProvider, options.AzureProvider:
		return true, nil
	default:
		return false, fmt.Errorf("unknown provider type: %s", providerType)
	}
}
```

This then causes the Azure provider to move through the oidc setup, which causes both problems:

1st problem is that the issuerURL must be set.
2nd Problem is that the graph api returns a 400.

What is actually happening is the provider setup is reaching out to the issuerURL and populating the profile URL from here, (which is actually )
```
https://login.windows.net/{tenant}/openid/userinfo
```
from there everything is set, and the Azure init (which relies on empty values to set the azure defaults) fails.

Add Azure into the false case, and it is unbroken.

**Comment by JoelSpeed** [comment]
If we add Azure to the false case, does that not mean that we then aren't setting up a provider verifier and as such, aren't doing any token validation on the tokens we are getting from Azure?

**Comment by hevans-dglcom** [comment]
Azure package has these lines:

```
if p.ValidateURL == nil || p.ValidateURL.String() == "" {
	p.ValidateURL = p.ProfileURL
}
```

So validationURL is actually set - we do not validate against the sts.windows.net URL but instead the graph api validates the token for us.

**Comment by ngrigoriev** [comment]
My quick guess. I see that when calling AAD OIDC auth endpoint you pass resource=https://graph.microsoft.com. You will be certainly getting the tokens with the audience set to that. I do not know if you really are calling Graph API after that or not.

My guess: something got changed. Was this parameter there before? Either its need shold be reviewed or instead you should set the value of audienceClaims to "appid" instead. In "appid" you will certainly have your client ID.

**Comment by jmahlik** [comment]
I can confirm the oidc provider works when hitting the v2 endpoints. To add to @AureaMohammadAlavi's solution, there were a couple other params needed. Mainly around the profile url and scope.

```
--provider=oidc \
--cookie-domain=https://login.microsoftonline.com/v2.0,{APP}
--email-domain={COMPANY} \
--oidc-issuer-url=https://login.microsoftonline.com/{AZURE_TENENT}/v2.0 \
--login-url=https://login.microsoftonline.com/{AZURE_TENENT}/v2.0/oauth2/authorize \
--redeem-url=https://login.microsoftonline.com/{AZURE_TENENT}/v2.0/oauth2/token \
--oidc-jwks-url=https://login.microsoftonline.com/common/discovery/keys \
--profile-url=https://graph.microsoft.com/v1.0/me \
--scope='openid email profile offline_access' \
```

**Comment by neiser** [comment]
I can confirm that switching to the `oidc` provider as suggested by @jmahlik and @AureaMohammadAlavi makes it work for us, too. We weren't able to get it running with the `azure` provider, but that's fine for us.

Here's our working snippet (based on the oauth2-provider helm chart), if somebody wants to fix it quickly by copy&pasting:
```
  extraArgs:
    ## Use Azure AD via OIDC provider, replace $AZURE_TENANT_ID with your own
    provider: oidc
    oidc-issuer-url: https://login.microsoftonline.com/$AZURE_TENANT_ID/v2.0
    login-url: https://login.microsoftonline.com/$AZURE_TENANT_ID/v2.0/oauth2/authorize
    redeem-url: https://login.microsoftonline.com/$AZURE_TENANT_ID/v2.0/oauth2/token
    oidc-jwks-url: https://login.microsoftonline.com/common/discovery/keys
    profile-url: https://graph.microsoft.com/v1.0/me
    scope: 'openid email profile offline_access'
```

**Comment by jmahlik** [comment]
Would it be helpful to add some of these examples to the azure provider docs? I feel like I spent a solid day or two trying to debug that before switching over. Would be really helpful to have the info like "if the provider doesn't work, try xyz".

**Comment by rouke-broersma** [comment]
@knightian it does, but you need to use the group IDs instead of the group names because group names are not returned for oidc.

**Comment by andreb89** [comment]
That workaround/solution does not really work for us. We have already used the OIDC provider initially with Azure AD, but now with v7.3.0 it no longer works. I also tried out the above mentioned workaround, but it did not help. 

We keep getting the following error:
`[2022/08/04 11:05:55] [oauthproxy.go:768] Error redeeming code during OAuth2 callback: could not get claim "groups": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "401": {"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience."`

**Comment by knightian** [comment]
> 

Are you definitely using the v2 endpoint to fetch tokens not the sts.windows one or whatever it was?

**Comment by andreb89** [comment]
@knightian 
yes, I am using:
```
oidc_issuer_url = "https://login.microsoftonline.com/<tenant-id>/v2.0"
profile_url = "https://graph.microsoft.com/v1.0/me"
login_url = "https://login.microsoftonline.com/<tenant-id>/v2.0/oauth2/authorize"
redeem_url = "https://login.microsoftonline.com/<tenant-id>/v2.0/oauth2/token"
oidc_jwks_url = "https://login.microsoftonline.com/common/discovery/keys"
```

The Azure AD app is configured for v2 in the manifest:
`"accessTokenAcceptedVersion": 2`

**Comment by JoJ123** [comment]
Hi, 
we also face issues with Azure AD. The different solutions here didn't helped. 
When I take:
I've changed also in the app manifest:
`"accessTokenAcceptedVersion": 2`
```
extraArgs:
  provider: oidc
  redirect-url: https://oauth.***.com/oauth2/callback
  oidc-issuer-url: https://login.microsoftonline.com/***/v2.0
  login-url: https://login.microsoftonline.com/***/oauth2/authorize
  redeem-url: https://login.microsoftonline.com/***/v2.0/oauth2/token
  oidc-jwks-url: https://login.microsoftonline.com/common/discovery/keys
  profile-url: https://graph.microsoft.com/v1.0/me
  scope: 'openid email profile offline_access'
  pass-user-headers: 
  upstream: file:///dev/null
  email-domain: ***.com
  provider-display-name: "*********"
  whitelist-domain: .***.com
  cookie-domain: .***.com
```
After the login I see 403 Forbidden
![image](https://user-images.githubusercontent.com/38938791/184926211-b137e1b3-f0e3-4f13-9fff-4b7f919b9f3a.png)

Logs:
![image](https://user-images.githubusercontent.com/38938791/184925892-22aa6867-5fea-4172-81a7-b81af6658f38.png)

**Comment by hereCOMESlappy** [comment]
Project ded rip

**Comment by JoelSpeed** [comment]
This was an unfortunate and unintended breaking change, that said, I maintain that it's progress towards a more secure Azure provider. I agree, updating the docs is the correct thing to do here. Anyone got time to put up a PR?

**Comment by dulakm** [comment]
@JoelSpeed already did, 6 days ago: https://github.com/oauth2-proxy/oauth2-proxy/pull/1771

**Comment by henriknil** [comment]
> @JoelSpeed already did, 6 days ago: #1771

That's not really updating the documentation. The azure provider is broken and the instructions found here:  https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/docs/configuration/auth.md#azure-auth-provider are no longer working.

**Comment by JoelSpeed** [comment]
I would hope to get the docs updated as @henriknil has noted. Updating the changelog is also valuable though, it might be best to explain the workaround in the changelog as it's relatively straight forward

**Comment by ramkrivas** [comment]
I also get the same error : 401 in version v7.3.0

`Error redeeming code during OAuth2 callback: could not get claim "groups": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "401": Unauthorized`

**Comment by erikgb** [comment]
Release 7.4.0 is out: https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.4.0. Can you retest so we eventually can close this issue?

**Comment by atringle** [comment]
I may have spoken to soon seems i was missing the group permission on my azure app and i no longer see the groups claim failing. I now see email claims failing but maybe that is a config issue on my part.

**Comment by henriknil** [comment]
I added Group.Read.All permission and could upgrade to 7.4.0 without issues. However maybe #1868 might be the correct permission?

**Comment by reespozzi** [comment]
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.4.0

**Comment by DJMogens** [comment]
> I may have spoken to soon seems i was missing the group permission on my azure app and i no longer see the groups claim failing. I now see email claims failing but maybe that is a config issue on my part.

Did you find a way to fix the email issue? I seem to still have this problem

**Comment by atringle** [comment]
> > I may have spoken to soon seems i was missing the group permission on my azure app and i no longer see the groups claim failing. I now see email claims failing but maybe that is a config issue on my part.
> 
> Did you find a way to fix the email issue? I seem to still have this problem

I was able to bypass the issue by adding the config
`insecure_oidc_allow_unverified_email = "true"`

Currently i am getting a 403 due to csrf when redirecting from a page but if i go to my oauth2proxy page directly than i can get the valid token and access my other page just fine. Hopefully will get some time to look into it further this week i saw a new release came out so ill probably give that a try and see if it helps at all.

**Comment by Rojax** [comment]
I'm getting the same error as @atringle regarding CSRF when using the v1 azure auth url.

If I switch to v2 it works even without altering the apps manifest file - ist this intended? The docs state explicitly to set `"accessTokenAcceptedVersion": 2` in step 4 in <https://github.com/oauth2-proxy/oauth2-proxy/blob/fd2807c091686a2a23f41123e3470a1076e877a0/docs/docs/configuration/auth.md>

**Comment by vittoriocanilli** [comment]
On my AKS cluster I use OAuth2-Proxy with Azure provider to authenticate the users and to authorise them to access the Kubernetes namespaces according to the AAD groups, they belong to. OAuth2-Proxy is installed with its Helm chart (version 6.8.0) and here are the extraArgs:
```
provider: "azure"
resource: "6dae42f8-4368-4678-94ff-3960e28e3630"
oidc-issuer-url: "https://sts.windows.net/{REDACTED_TENANT_ID}/"
azure-tenant: "{REDACTED_TENANT_ID}"
pass-access-token: "true"
pass-user-headers: "true"
set-xauthrequest: "true"
oidc-email-claim: sub
cookie-refresh: 59m
cookie-expire: 1h
```
After updating OAuth2-Proxy to 7.4.0 I get the same error in the logs, that is reported at the beginning of this thread: https://github.com/oauth2-proxy/oauth2-proxy/issues/1666#issue-1252488741

So I have switched to the Azure Auth V2 endpoint, as many have done in this thread by using the following extraArgs:
```
provider: "azure"
oidc-issuer-url: "https://login.microsoftonline.com/{REDACTED_TENANT_ID}/v2.0"
azure-tenant: "{REDACTED_TENANT_ID}"
pass-access-token: "true"
pass-user-headers: "true"
set-xauthrequest: "true"
oidc-email-claim: sub
cookie-refresh: 59m
cookie-expire: 1h
azure-graph-group-field: "id"
```
This lets the user authenticate to the AKS cluster, but it does not authorise them to access the Kubernetes namespaces, which require the AAD groups. I have checked the OAuth2-Proxy and it seems that the groups are acquired though:
```
[2023/01/24 14:46:16] [internal_util.go:69] 200 GET https://graph.microsoft.com/oidc/userinfo {"sub":"{REDACTED_SUB}","name":"{REDACTED_NAME}","family_name":"{REDACTED_FAMILYNAME}","given_name":"{REDACTED_GIVENNAME}","picture":"https://graph.microsoft.com/v1.0/me/photo/$value","email":"{REDACTED_EMAIL}"}
10.1.193.195:37276 - ca0bb03108a8692659f4424a5e74d8f9 - {REDACTED_SUB} [2023/01/24 14:46:16] [AuthSuccess] Authenticated via OAuth2: Session{email:{REDACTED_SUB} user: PreferredUsername: token:true id_token:true created:2023-01-24 14:46:15.464418172 +0000 UTC m=+385.805287758 expires:1970-01-01 00:00:00 +0000 UTC groups:[{REDACTED_GROUP1} {REDACTED_GROUP2} ... {REDACTED_GROUPN}]}
```

As you can see the session's expiration is set to `1970-01-01 00:00:00 +0000 UTC`: do you know what the issue could be? It is strange that the Azure Auth V2 endpoint returns me an expired session.

**Comment by pierluigilenoci** [comment]
@JoelSpeed, this is still an issue.

**Comment by gannaramu** [comment]
seeing a similar issue as @vittoriocanilli

**Comment by pierluigilenoci** [comment]
About a year has passed since several users had problems running the Azure provider.
Judging by the comments here, the problem has been fairly cleared up.
It may be time to find someone to handle and resolve the situation. What do you think?
@JoelSpeed @steakunderscore @NickMeves 

For completeness, I also add all the provider's contributors (maybe someone driven by a positive spirit takes charge of the situation). @adriananeci @ianroberts @weinong @codablock @johejo @wonderhoss @theonewolf @pasha-r @leyshon @MisterWil @jehiah @eelcocramer 

Thank you all for the effort invested in the project so far and for what you will invest in the future.

**Comment by pierluigilenoci** [comment]
Probably related issues:
* https://github.com/oauth2-proxy/oauth2-proxy/issues/1715 @bluebrown
* https://github.com/oauth2-proxy/oauth2-proxy/issues/2095 and https://github.com/oauth2-proxy/oauth2-proxy/pull/2096 @nhahn1312 
* https://github.com/oauth2-proxy/oauth2-proxy/issues/2089 @uvaisibrahim
* https://github.com/oauth2-proxy/oauth2-proxy/issues/1987 @syst0m 
* https://github.com/oauth2-proxy/oauth2-proxy/issues/1505 (by me)
* https://github.com/oauth2-proxy/oauth2-proxy/issues/1231 @mvalenzisi

**Comment by Rojax** [comment]
I guess  what @gannaramu described is a different issue. The original issue that azure was not working at all  (`unable to get claims from token: could not get claim "groups": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "400":`) was resolved months ago with v7.4.0. At least for us it's working by just following the steps mentioned in the azure setup documentation. But when calling `https://audit-hub.usd.de/oauth2/userinfo` I also get 
```
{"user":"","email":"User@contoso.com","groups":["GID_1",...,"GID_N]}
```

so the user field is empty, but besides that authentication works.

**Comment by uvaisibrahim** [comment]
In my case, I have configured oauth2-proxy for my prometheus deployment with oauth2-proxy version 7.4.0 and working fine.  I followed the oauth2-proxy documentation to set up the Azure service Principal and also for the oauth2-proxy deployment. So when I load prometheus, it redirecting me to the Microsoft authentication page, and on successful authentication, it revert to the prometheus page.

But the problem is , when I add this prometheus end point as a datasource in Grafana, I am getting a CORS error in browser saying `Access-Control-Allow-Origin Missing Header` to `https://login.microsoftonline.com/blahblahblah/oauth2/v2.0/authorize?approval_prompt=force...`

**Comment by pierluigilenoci** [comment]
@JoelSpeed @steakunderscore @NickMeves, any news around this?

**Comment by imranrazakhan** [comment]
@pierluigilenoci and others, I am also using Azure AD with AKS and following are my findings

- `X-Auth-Request-Access-Token` token has groups info in payload but `Authorization `token doesn't contain groups info in payload.

- While I was able to successfully log in to the Kubernetes Dashboard, I encountered issues with the authorization process as per RBAC (Role-Based Access Control). In order to investigate further, I performed manual testing by obtaining the token and testing it with the Kubernetes API. `SelfSubjectReview `( its purpose is to find out how Kubernetes cluster maps authentication information to identify me as a client.)

    1. I found that using the token obtained via kubelogin and including it in the Authorization header allowed me to access all the resources in the Kubernetes dashboard.
      
    2. I encountered an issue where the token returned by oauth2_proxy was resulting in an "unauthorized" error.
      
    3. Upon decoding both tokens, I discovered a difference in the "aud" (audience) value. The token obtained through kubelogin had the "aud" value set to "6dae42f8-4368-4678-94ff-3960e28e3630", while the token acquired via oauth2 had the "aud" value set to "https://graph.microsoft.com/".
      
    4. I attempted to update the "aud" value in oauth2_proxy by setting the resource value to "6dae42f8-4368-4678-94ff-3960e28e3630", but encountered an error.
`[azure.go:105] WARNING:  --resource option has no effect when using the Azure OAuth V2 endpoint.`

To verify this further, I conducted testing using the following two commands:
`az account get-access-token --resource https://management.azure.com  `                   --> **unauthorize**
`az account get-access-token --resource 6dae42f8-4368-4678-94ff-3960e28e3630`     --> **authorize**

Is there any way we can add resource in v2 ?

**Comment by abdullahkhawer** [comment]
I had oauth2-proxy running on my Kubernetes cluster which I deployed using Helm via [this chart](https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy). I just upgraded oauth2-proxy from `v7.1.3` with chart `4.2.2` to `v7.4.0` with chart `6.16.1` and started seeing the following error: `[main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: invalid provider verifier options: missing required setting: issuer-url`

I made it work by adding `azure_tenant` and  `oidc_issuer_url` in the config file in the default values file as follows:

Before:

```yaml
# Oauth client configuration specifics
config:
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]
    http_address = "0.0.0.0:4180"
    provider = "azure"
```

After:

```yaml
# Oauth client configuration specifics
config:
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]
    http_address = "0.0.0.0:4180"
    provider = "azure"
    azure_tenant = "${azure_tenant_id}"
    oidc_issuer_url = "https://sts.windows.net/${azure_tenant_id}/"
```

**Comment by jryberg** [comment]
> In my case, I have configured oauth2-proxy for my prometheus deployment with oauth2-proxy version 7.4.0 and working fine. I followed the oauth2-proxy documentation to set up the Azure service Principal and also for the oauth2-proxy deployment. So when I load prometheus, it redirecting me to the Microsoft authentication page, and on successful authentication, it revert to the prometheus page.
> 
> But the problem is , when I add this prometheus end point as a datasource in Grafana, I am getting a CORS error in browser saying `Access-Control-Allow-Origin Missing Header` to `https://login.microsoftonline.com/blahblahblah/oauth2/v2.0/authorize?approval_prompt=force...`

Did you find a solution for this?

I got the following errors in oauth2-proxy when the above message in Grafana is shown
```
[2023/10/16 13:35:35] [stored_session.go:94] Error loading cookied session: session ticket cookie failed validation: <nil>, removing session
[2023/10/16 13:35:35] [stored_session.go:97] Error removing session: error decoding ticket to clear session: session ticket cookie failed validation: <nil>
```

**Comment by mvalenzisi** [comment]
I got it working with `v7.5.1`, in my case I don't need the proxy to fetch the groups, because this is done by AKS managed identity.
Here's my configuration:
```
provider: oidc
oidc-issuer-url: https://login.microsoftonline.com/[REDACTED]/v2.0
login-url: https://login.microsoftonline.com/[REDACTED]/oauth2/v2.0/authorize
redeem-url: https://login.microsoftonline.com/[REDACTED]/oauth2/v2.0/token
oidc-jwks-url: https://login.microsoftonline.com/[REDACTED]/discovery/v2.0/keys
skip-oidc-discovery: true
user-id-claim: email
oidc-email-claim: sub
oidc-audience-claim: aud
scope: openid 6dae42f8-4368-4678-94ff-3960e28e3630/.default
pass-access-token: true
pass-user-headers: true
set-xauthrequest: true
```

The scope `openid` is required when authenticating using `oidc`,
`6dae42f8-4368-4678-94ff-3960e28e3630/.default` is the scope for `Azure Kubernetes Service AAD Server`.

Related issue: https://github.com/oauth2-proxy/oauth2-proxy/issues/2314

**Comment by nilsgstrabo** [comment]
Would be useful if there was an option to skip request to ProfileURL in the ClaimsExtractor, ref https://github.com/oauth2-proxy/oauth2-proxy/issues/2314#issuecomment-1810367324

**Comment by pierluigilenoci** [comment]
Considering that the Azure provider is practically deprecated and the problem seems to be solved with the generic OIDC provider, it might make sense to close this issue.

@jeroenlandheer, are you still having problems?

**Comment by jeroenlandheer** [comment]
@pierluigilenoci No, this is no longer relevant. I've closed this issue.

**Comment by simaotwx** [comment]
The solution is indeed to switch to the "https://login.microsoftonline.com/<tenant id>/v2.0" endpoint and use "oidc" as provider

**Comment by peckloris** [comment]
> Issues with Azure provider here also. Definitely a breaking change to make the `oidc-issuer-url` mandatory. 😞
> 
> I wonder if the following comment might be relevant: [#1135 (comment)](https://github.com/oauth2-proxy/oauth2-proxy/pull/1135#issuecomment-812984657) (including responses)?





+1
