### ISSUE TITLE
Inconsistent code-challenge-method CLI flag and config file naming

### ISSUE THREAD

**Issue by ChrisEke** [oauth2-proxy/oauth2-proxy#1667]
## Expected Behavior
Adding `code_challenge_method = "S256"` to the config file should enable PKCE code challenge within the app.

## Current Behavior
oauth2-proxy fails to start with error: 
```
[2022/05/30 11:47:15] [main.go:43] ERROR: failed to load config: error unmarshalling config: 1 error(s) decoding:

* '' has invalid keys: code_challenge_method
```

## Possible Solution
Starting oauth2-proxy with argument `--code-challenge-method=S256`works as intended. 

## Steps to Reproduce (for bugs)

1.   Add line: `code_challenge_method = "S256"` in config file (e.g. /etc/oauth2-proxy.cfg)
2.  Start oauth2-proxy with argument `--config=/etc/oauth2-proxy.cfg`

## Your Environment
- k8s deployment (k3s v1.23.6+k3s1)
- Running amd64 version of quay.io/oauth2-proxy/oauth2-proxy:v7.3.0

 
- Version used: v7.3.0

**Comment by braunsonm** [comment]
There is a bit of inconsistency here with the naming between us deciding not to enable this feature by default. In configuration files it is actually `force_code_challenge_method`. See the docs here: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config

I agree the difference is not ideal. Will look at changing this in the next release.
