### ISSUE TITLE
Documentation fix for whitelist_domains

### ISSUE THREAD

**Issue by romanstech** [oauth2-proxy/oauth2-proxy#1668]
On page https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#command-line-options there is a small mistake.
Instead of:
`--whitelist-domains`
we see
`--whitelist-domain`

To fix just need to add letter **s** to word **domain**.

**Comment by matzegebbe** [comment]
It really looks like it is a difference between the CMD parameter and the config parameter.

https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/apis/options/options.go#L32
![image](https://user-images.githubusercontent.com/3482021/171802587-20066f7e-8b8f-49f9-97f8-a047eec9aff1.png)

**Comment by JoelSpeed** [comment]
Yes, this is a historic issue that's come up many times. Any flag that can be specified multiple times on the command line, is singular as a flag, but plural as a config or environment parameter. This is something we are looking to resolve in the future but it will be a breaking change as part of our new structured configuration project.
