### ISSUE TITLE
Add FusionAuth as a provider

### ISSUE THREAD

**Issue by khushbooag4** [oauth2-proxy/oauth2-proxy#1670]
In the provider part, we can add [FusionAuth](https://fusionauth.io/) as provider. The goal is to add FusionAuth as a provider that will enable all tech products to not include authentication-related code inside microservices, enabling the creation and management of ACL outside of a microservice in a reusable way.

Kindly review it @tomtaylor @dhowden @jonas @thiagocaiubi @drewolson

**Comment by JoelSpeed** [comment]
Hi, welcome to the project. Having a quick look at the documentation for fusion Auth, it seems to be an OIDC compatible identity provider. In which case, are there any reasons it cannot be hooked up straight to our generic OIDC provider?

**Comment by khushbooag4** [comment]
No, I don't think so. We can add the confirguration of FusionAuth to the OIDC provider.

**Comment by khushbooag4** [comment]
my docker.compose.yml
version: "3"

networks:   
  cac:     
    driver: bridge

services:
#Oauth2 proxy
  oauth2-proxy:
    container_name: oauth2-fa-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
    command: --config /oauth2-proxy.cfg
    ports:
      - 4180:4180/tcp
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    networks:
      - cac
    depends_on:
      # - fa-search
      # - fa-db
      - fusionauth
# Fusion Auth
  fa-search:
    container_name: fa-search
    networks:
      - cac
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - cluster.name=fusionauth
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - discovery.type=single-node
    restart: unless-stopped
    # ulimits: # Don't work with Gitpod
    #   memlock:
    #     soft: -1
    #     hard: -1
    volumes:
      - fa-es-data:/usr/share/elasticsearch/data

  fusionauth:
    container_name: fusionauth
    networks:
      - cac
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - fa-search
    environment:
      DATABASE_URL: jdbc:postgresql://fa-db:${FUSIONAUTH_POSTGRES_PORT}/fusionauth
      DATABASE_ROOT_USERNAME: ${FUSIONAUTH_POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${FUSIONAUTH_POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${FUSIONAUTH_DATABASE_USER}
      DATABASE_PASSWORD: ${FUSIONAUTH_DATABASE_USERNAME}
      FUSIONAUTH_SEARCH_ENGINE_TYPE: elasticsearch
      FUSIONAUTH_SEARCH_SERVERS: http://fa-search:9200
      FUSIONAUTH_URL: http://fusionauth:9011
      FUSIONAUTH_API_KEY: ${FUSIONAUTH_API_KEY}
      FUSIONAUTH_APP_KICKSTART_FILE: ${FUSIONAUTH_APP_KICKSTART_FILE}
      FUSIONAUTH_ADMIN_EMAIL: ${FUSIONAUTH_ADMIN_EMAIL}
      FUSIONAUTH_ADMIN_PASSWORD: ${FUSIONAUTH_ADMIN_PASSWORD}
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa-config:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart

  fa-db:
    container_name: fa-db
    networks:
      - cac
    image: postgres:12
    environment:
      - POSTGRES_USER=${FUSIONAUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FUSIONAUTH_POSTGRES_PASSWORD}
    ports:
      - "5436:${FUSIONAUTH_POSTGRES_PORT}"
    volumes:
      - ./pgdata-fa-db:/var/lib/postgresql/data

volumes:
  fa-es-data:
  fa-config:

**Comment by khushbooag4** [comment]
` /oauth2-proxy.cfg ` in this I have added the confirguration

**Comment by JoelSpeed** [comment]
What have you set as the OIDC Issuer URL for OAuth2 Proxy, you haven't shared the config that I can see

This is a docker issue not a fusion auth or OAuth2 Proxy issue. You'll need to access the fusion auth provider over some network via a name, individual containers do not share a network namespace normally so localhost won't work
