### ISSUE TITLE
Keycloak/oauth2-proxy - throwing in 500 error to redirect to Keycloak

### ISSUE THREAD

**Issue by dsantanu** [oauth2-proxy/oauth2-proxy#1671]
I have a web-ui, oauth2-proxy and Keycloak running a as Kubernetes apps; web-ui and oauth2 are behind the ingress-nginx and keycloak is exposed through NodePort.

These are my currentendpoints:
-  web-ui: `https://ui.mydomain.uk.local`
- oauth2: `https://ingress.mydomain.uk.local/oauth2`
-  keycloak: `http://ingress.mydomain.uk.local:8080`

If I use `https://ingress.mydomain.uk.local/oauth2/start` I get the keycloak login page but ends up with **500** error if I target the UI endpoint. I followed the official documentation [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#keycloak-auth-provider) to setup my services. 
I cannot copy (and paste) from the environment I'm running the actual code, but here is the screenshots of my configs:

**OA deployment args:**
![image](https://user-images.githubusercontent.com/4650237/171406766-89c724e2-181e-4034-bcd1-b564999cd46e.png)

**OA Ingress Rules:**
![image](https://user-images.githubusercontent.com/4650237/171404079-2a8858e0-f4ea-44b3-8cc6-cb216564bb58.png)

**UI Ingress Rules**
![image](https://user-images.githubusercontent.com/4650237/171404180-a9b65812-76e7-47f4-a240-5e5c4cbea5d4.png)

## Expected Behavior
It should redirect to Keycloak login page

## Current Behavior
It seems redirecting to aouth2-proxy (returning 302) and then getting a 500.

**OA Ingress log:**
![image](https://user-images.githubusercontent.com/4650237/171405061-c11916d6-33b4-4323-82d0-77a2495c86ba.png)

**UI Ingress log:** 
![image](https://user-images.githubusercontent.com/4650237/171405185-f9cd28c9-4d6c-455a-9ac0-44529bea6a3a.png)

So far I've tried as many as pages I could find form the net but nothing worked out for me. Is there any one can spot any wrong-doing  or  misreconfiguration there? I got stuck really bad and would appreciate some help. thanks in advance!!

**Comment by dsantanu** [comment]
after looking in the ingress-nginx log, I also see this: 
`auth request unexpected status: 302 while sending to client`  - looks like nginx ingress not liking the 302 response from oauth2?

**Comment by JoelSpeed** [comment]
I think your auth-url annotation is wrong, it should be `/oauth2/auth` not just `/auth` at the end

**Comment by dsantanu** [comment]
if look at the entire configuration, then you will see I have used `--proxy-prefix=/`, which makes oauth2-proxy to be served as root when called locally, hence `/auth`. When it accessed via ingress-controller, then it goes via `/oauth2` sub-path.

**Comment by JoelSpeed** [comment]
Right I see the rewrite now, that confused things a little as you are accessing it via /OAuth2/ publicly, you can probably remove the rewrite with no ill effect

Have you tried hitting that endpoint manually? Eg if you access `/auth` on OAuth2 proxy directly, do you get the same 302? 

If the proxy prefix is working as expected that endpoint should never return a 302 so I suspect that's the root of your issue

**Comment by dsantanu** [comment]
prefix is working as expected, I assume otherwise `auth-url` wouldn't work. If I go through ingress-controller and hit `https://ingress.mydomain.uk.local/oauth2/auth` I get redirected to `http://ingress.mydomain.uk.local:8080/auth/relame/master/....`, which is the KC endpoint.

**Comment by JoelSpeed** [comment]
> assume otherwise auth-url wouldn't work.

The 500 error you are getting is because OAuth2 Proxy is returning an invalid code when Nginx is attempting to request the auth-url

> https://ingress.mydomain.uk.local/oauth2/auth I get redirected to http://ingress.mydomain.uk.local:8080/auth/relame/master/...., which is the KC endpoint.

Yep, that's not the correct behaviour, so your prefix isn't working as expected. If it were working as expected then you wouldn't be seeing that redirect, you would see either a 401 or 202 reponse. The behaviour you are seeing is what happens when you hit an unknown endpoint (one not internal to OAuth2 Proxy) and you aren't logged in and you have skip-provider-button=true as you do.

I would suggest removing the proxy prefix and rewrite options on OAuth2 Proxy as you aren't achieving anything by adding them in

**Comment by dsantanu** [comment]
I think, oauth2-proxy is not exactly doing what it supposed to do with `--proxy-prefix`.  At least that was the case for me. As it wasn't properly setting the _url root path that this proxy should be nested under_, was making the `auth-url` invalid, resulting  500 error. 
I had to remove the `proxy-prefix` parameter, create a dedicated DNS record, pointing to the ingress-controller's NLB, use the new DNS name as _host_ and `/` as the _path_ in the ingress rule.  It started working after that. Thanks to @JoelSpeed for pointing that out.

I still think, if `proxy-prefix` ia actually doing what it supposed to do, the oauth2-proxy SHOULD work that way I was doing. What I did now it's work around than a fix, IMO.

**Comment by SSAR13** [comment]
@dsantanu I am facing with exact same issue with the almost similar implementation. Working on it for 1 week now.  
` create a dedicated DNS record, pointing to the ingress-controller's NLB`  Need more info regarding this. like what will be the DNS record type? A record etc.  

FYI I am using Ingress Controller Version: 0.48.

**Comment by SSAR13** [comment]
Finally, I figured it out after 7 days of struggle that there aren number of ways for it to work depending on the type of configuration you are using, and I will post here what worked for me and what didn't 

Worked for me: 
Oauth2 service type Nodepart then using external Ip with port number( nodeport of oauth2 service )
i.e., instead of this 
nginx.ingress.kubernetes.io/auth-url: http://{{oauth2proxyname}}.{{oauthnamespace}}.svc.cluster.local/oauth2/auth
I used this 
nginx.ingress.kubernetes.io/auth-url: http://137.xx.xx.x:31722/oauth2/auth

I read nearly a hundred articles over the past 7 days and tried as many approaches as I tried @dsantanu solution which dint work for me.

If anyone need help with SSO implementation for Kubernetes Ingress using Keycloak plz post here. I will support in the way I can. I will post in future more possible solutions for this. Cheers!

**Comment by haglo** [comment]
hello,

i have the same problem and i work on it also one week.
can you help me

**Comment by haglo** [comment]
I have set up following Demoproject:


===================================
1) Keycloak-Server 
Run in k3s Cluster
FQDN: https://keycloak.informatik.uni-ulm.de
REALM: ertis
Client_id: ertis_app
ClientSecret: OOfrC9ldwJB61XvQD4WRSjMFxanOsgqz # I have changed it
Valid Redirect URIs: https://app.informatik.uni-ulm.de/oauth2/callback



===================================
2) Application-Server
My Application which i want protect
Runs in k3s Cluster
FQDN: https://app.informatik.uni-ulm.de



===================================
3) On my Application Server i have installed
k3s without traefic
Helm
MetallB
ingress-nginx
  => get Connect to Internet is working
cert-manager
  => cert-manager with letsencrypt is working



===================================
4) This are the yml-Files on Application-Server
(wrong formated here)

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: ertis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "oauth2-proxy"
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: "quay.io/oauth2-proxy/oauth2-proxy:v7.3.0"
        args:
          - --provider=keycloak-oidc
          - --client-id=ertis_app
          - --client-secret=OOfrC9ldwJB61XvQD4WRSjMFxUmOsgqz
          - --oidc-issuer-url=https://keycloak.informatik.uni-ulm.de/realms/ertis  
          - --redirect-url=https://app.informatik.uni-ulm.de/oauth2/callback
          - --login-url=https://keycloak.informatik.uni-ulm.de/realms/ertis/protocol/openid-connect/auth
          - --redeem-url=https://keycloak.informatik.uni-ulm.de/realms/ertis/protocol/openid-connect/token
          - --validate-url=https://keycloak.informatik.uni-ulm.de/realms/ertis/protocol/openid-connect/userinfo
          - --cookie-secure=false
          - --cookie-name=_oauth2_proxy
          - --cookie-secret=Q3Vta1EwY2tWVmtQaUgwRER1V0R4eTNTUnVOLzhueUw=
          - --cookie-domain=.informatik.uni-ulm.de
          - --whitelist-domain=.informatik.uni-ulm.de
          - --email-domain=*  
          - --upstream=file:///dev/null
          - --http-address=0.0.0.0:4180
          - --set-authorization-header=true
          - --skip-provider-button=true
          - --set-xauthrequest=true
          - --skip-auth-preflight=false
          - --auth-logging=true
          - --insecure-oidc-allow-unverified-email
          - --pass-access-token=true
          - --pass-user-headers=true
          - --reverse-proxy=true
          #- --real-client-ip-header=X-Forwarded-For
          #- --ssl-insecure-skip-verify=true
          #- --ssl-upstream-insecure-skip-verify=true
          #- --scope=openid email profile offline_access

---

apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-svc
  namespace: ertis
spec:
  type: ClusterIP
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
      name: web
  selector:
    app: "oauth2-proxy"
    
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ertis-main-ing
  namespace: ertis
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: '/oauth2'
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    
    nginx.ingress.kubernetes.io/auth-url: "https://app.informatik.uni-ulm.de/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://app.informatik.uni-ulm.de/oauth2/start?rd=$scheme://$best_http_host$request_uri"
    
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  rules:
    - host: app.informatik.uni-ulm.de
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: whoami-svc
                port:
                  number: 80

  tls:
  - hosts:
    - app.informatik.uni-ulm.de
    secretName: app.informatik.uni-ulm.de-cert
    
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ertis-oauth2-ing
  namespace: ertis
  annotations:
     cert-manager.io/cluster-issuer: letsencrypt
     kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app.informatik.uni-ulm.de
      http:
        paths:
          - path: '/oauth2'
            pathType: ImplementationSpecific
            backend:
              service:
                name: oauth2-proxy-svc
                port:
                  number: 4180

  tls:
  - hosts:
    - app.informatik.uni-ulm.de
    secretName: app.informatik.uni-ulm.de-cert

**Comment by SSAR13** [comment]
Please also post me the error 

> I have set up following Demoproject:
> 
> ===================================
> 
> 1. Keycloak-Server
>    Run in k3s Cluster
>    FQDN: https://keycloak.informatik.uni-ulm.de
>    REALM: ertis
>    Client_id: ertis_app
>    ClientSecret: OOfrC9ldwJB61XvQD4WRSjMFxanOsgqz # I have changed it
>    Valid Redirect URIs: https://app.informatik.uni-ulm.de/oauth2/callback
> 
> =================================== 2) Application-Server My Application which i want protect Runs in k3s Cluster FQDN: https://app.informatik.uni-ulm.de
> 
> =================================== 3) On my Application Server i have installed k3s without traefic Helm MetallB ingress-nginx => get Connect to Internet is working cert-manager => cert-manager with letsencrypt is working
> 
> =================================== 4) This are the yml-Files on Application-Server (wrong formated here)
> 
> apiVersion: apps/v1 kind: Deployment metadata: labels: app: oauth2-proxy name: oauth2-proxy namespace: ertis spec: replicas: 1 selector: matchLabels: app: "oauth2-proxy" template: metadata: labels: app: oauth2-proxy spec: containers: - name: oauth2-proxy image: "quay.io/oauth2-proxy/oauth2-proxy:v7.3.0" args: - --provider=keycloak-oidc - --client-id=ertis_app - --client-secret=OOfrC9ldwJB61XvQD4WRSjMFxUmOsgqz - --oidc-issuer-url=https://keycloak.informatik.uni-ulm.de/realms/ertis - --redirect-url=https://app.informatik.uni-ulm.de/oauth2/callback - --login-url=https://keycloak.informatik.uni-ulm.de/realms/ertis/protocol/openid-connect/auth - --redeem-url=https://keycloak.informatik.uni-ulm.de/realms/ertis/protocol/openid-connect/token - --validate-url=https://keycloak.informatik.uni-ulm.de/realms/ertis/protocol/openid-connect/userinfo - --cookie-secure=false - --cookie-name=_oauth2_proxy - --cookie-secret=Q3Vta1EwY2tWVmtQaUgwRER1V0R4eTNTUnVOLzhueUw= - --cookie-domain=.informatik.uni-ulm.de - --whitelist-domain=.informatik.uni-ulm.de - --email-domain=* - --upstream=file:///dev/null - --http-address=0.0.0.0:4180 - --set-authorization-header=true - --skip-provider-button=true - --set-xauthrequest=true - --skip-auth-preflight=false - --auth-logging=true - --insecure-oidc-allow-unverified-email - --pass-access-token=true - --pass-user-headers=true - --reverse-proxy=true #- --real-client-ip-header=X-Forwarded-For #- --ssl-insecure-skip-verify=true #- --ssl-upstream-insecure-skip-verify=true #- --scope=openid email profile offline_access
> 
> apiVersion: v1 kind: Service metadata: name: oauth2-proxy-svc namespace: ertis spec: type: ClusterIP ports: - port: 4180 targetPort: 4180 protocol: TCP name: web selector: app: "oauth2-proxy"
> 
> apiVersion: networking.k8s.io/v1 kind: Ingress metadata: name: ertis-main-ing namespace: ertis annotations: cert-manager.io/cluster-issuer: letsencrypt acme.cert-manager.io/http01-edit-in-place: "true" kubernetes.io/ingress.class: nginx nginx.ingress.kubernetes.io/rewrite-target: '/oauth2' nginx.ingress.kubernetes.io/backend-protocol: HTTPS
> 
> ```
> nginx.ingress.kubernetes.io/auth-url: "https://app.informatik.uni-ulm.de/oauth2/auth"
> nginx.ingress.kubernetes.io/auth-signin: "https://app.informatik.uni-ulm.de/oauth2/start?rd=$scheme://$best_http_host$request_uri"
> 
> nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
> nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
> ```
> 
> spec: rules: - host: app.informatik.uni-ulm.de http: paths: - path: '/' pathType: Prefix backend: service: name: whoami-svc port: number: 80
> 
> tls:
> 
> * hosts:
>   
>   * app.informatik.uni-ulm.de
>     secretName: app.informatik.uni-ulm.de-cert
> 
> apiVersion: networking.k8s.io/v1 kind: Ingress metadata: name: ertis-oauth2-ing namespace: ertis annotations: cert-manager.io/cluster-issuer: letsencrypt kubernetes.io/ingress.class: nginx spec: rules: - host: app.informatik.uni-ulm.de http: paths: - path: '/oauth2' pathType: ImplementationSpecific backend: service: name: oauth2-proxy-svc port: number: 4180
> 
> tls:
> 
> * hosts:
>   
>   * app.informatik.uni-ulm.de
>     secretName: app.informatik.uni-ulm.de-cert

Please also post me the error ?

**Comment by dineshkoppa** [comment]
re-activate

**Comment by saashqdev** [comment]
I'm currently battling this behind a Hetzner loadbalncer. I've used your settings from above. I constantly get 503 when I go to: `https://my-domain/oauth2/auth` as well. Has anyone nailed this down yet?

**Comment by mylchenko-alexander** [comment]
re-activate
