### ISSUE TITLE
Trusted ips not working with AWS NLB + ingress-nginx

### ISSUE THREAD

**Issue by zetaab** [oauth2-proxy/oauth2-proxy#1675]
## Expected Behavior

Expected behaviour is that we could use trusted ips feature. 

## Current Behavior

I added debug information to client ip function

```
[2022/06/03 13:56:20] [oauthproxy.go:537] req &{Method:GET URL:/oauth2/auth Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[*/*] User-Agent:[curl/7.79.1] X-Auth-Request-Redirect:[/] X-Forwarded-For:[52.28.106.99] X-Forwarded-Host:[echoaws.csf.foo.com] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Scheme:[https] X-Original-Forwarded-For:[91.154.14.230] X-Original-Method:[GET] X-Original-Url:[https://echoaws.csf.foo.com/] X-Real-Ip:[52.28.106.99] X-Request-Id:[9f6849eb822cf4434e04fa6fc0aa76eb] X-Scheme:[https] X-Sent-From:[nginx-ingress-controller]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:echoaws.csf.foo.com Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:100.100.54.155:40256 RequestURI:/oauth2/auth TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc000251b90}
```

The problem is that client real ip is located in header called `X-Original-Forwarded-For`. That header is not allowed in oauth2-proxy. However, it is possible to get client real ip to X-Forwarded-For headers using https://github.com/kubernetes/ingress-nginx/issues/5970#issuecomment-879855750 BUT after that it is possible to send X-Forwarded-* headers through nginx-ingress and change your real ip address. Which is security risk.

example
`curl https://echoaws.csf.foo.com -v  -H 'X-Forwarded-For: 8.8.8.1'` will show the ip address as 8.8.8.1. (with those settings in comment)

## Possible Solution

I would like to see that `X-Original-Forwarded-For` header is going to be allowed because ingress-nginx is quite popular.

## Steps to Reproduce (for bugs)

1.  create kubernetes cluster (we have kops) to AWS
2.  install ingress-nginx with NLB in front of it
3.  use manifests https://gist.github.com/zetaab/915994ff20e30b22d2707db75dde0820
4.  you can see that trusted ips does not work

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
Have you tried using the `compute-full-forwarded-for` option on ingress-nginx? It was my understanding, and this may be out of date, that in an x-forward-for, there should be a chain of IP addresses, and then the end application should determine which of those it trusts. I believe that's the behaviour we have in OAuth2 Proxy today. 

I'm not against adding support for this, though, it does open a can of worms for how other proxies handle this in non-compliant ways. I'd certainly like to see if there is a workaround before we add it though

**Comment by zetaab** [comment]
@JoelSpeed yes I have tried it. However, if that setting is enabled it is possible to fake ip address by adding request header like `X-Forwarded-For: 8.8.8.8`

**Comment by zetaab** [comment]
![image](https://user-images.githubusercontent.com/22482503/172098752-944ba285-d7f2-4909-a195-9b319f44f9ad.png)

this is the architecture that I am using. The problem with this is, that its really ingress-nginx that is doing the request against oauth2 proxy /auth path - not the user. `compute-full-forwarded-for` does not help.

**Comment by hevans-dglcom** [comment]
Hi, I noticed that you have an open PR for this open.

You could also use this little workaround at the nginx level.

```
nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-For $http_x_original_forwarded_for;
```
This would set/overwrite the X-Forwarded-For header to the value of the X-original header, which the app can understand.

**Comment by JoelSpeed** [comment]
Does the workaround work or does that still allow spoofing?

**Comment by hevans-dglcom** [comment]
Using the the proxy_set_header will reset this header value, not append to it. This would mean regardless if the client is passing their own X-Forwarded-For it would be overwritten.

**Comment by hevans-dglcom** [comment]
@zetaab  actually it would be interesting to know where this X-Original-Forwarded-For header is actually coming from - is this an Nginx Ingress header? Afaik AWS NLB is just a network load balancer right? Its not actually injecting any headers?

In that case you could possibly just use the following snippet instead:

```
nginx.ingress.kubernetes.io/auth-snippet: |
  proxy_set_header X-Real-IP $remote_addr;

OR
nginx.ingress.kubernetes.io/auth-snippet: |
  proxy_set_header X-Forwarded-For $remote_addr;
```

This would reset the X-Real-IP (or X-Forwarded-For, depending which your would like to use) headers to the remote address (as AWS NLB preserves the source IP) - all you would need to make sure in this case, is that your Nginx-Ingress is using traffic-policy-local (otherwise your source IP would be lost).
