### ISSUE TITLE
Having upstream to multiple servers 

### ISSUE THREAD

**Issue by davidy718** [oauth2-proxy/oauth2-proxy#1678]
## Expected Behavior
Have it send the request to multiple servers 

## Current Behavior
getting an error saying that it cant sent to the same path 

## Possible Solution
allow oauth2 to work as a load balancer

## Steps to Reproduce (for bugs)
use oauth2 proxy with multiple upstreams in a config file with multiple servers 

upstreams = [
    "https://192.168.1.10:443",
    "https://192.168.1.11:443",
    "https://192.168.1.12:443"
]

## Your Environment

- Version used: V7.3.0

**Comment by JoelSpeed** [comment]
I think in this case I would recommend instead to use something that is more dedicated to handling traffic with multiple backends. For example, you could use OAuth2 Proxy as an auth_request sidecar to nginx which already has support for load balancing multiple backends.
