### ISSUE TITLE
v7.3.0 oidc with keycloak, user missing

### ISSUE THREAD

**Issue by marcojarjour** [oauth2-proxy/oauth2-proxy#1681]
After the update to v7.3.0 the user is missing in the /userinfo and /auth endpoint. It seems to be working until this commit https://github.com/oauth2-proxy/oauth2-proxy/commit/967051314e5d84cb389aa33ca8e0ff624b43c7eb. This seems to happen with the oidc provider as well.

## Expected Behavior

I would expect the user is set as in v7.2.1

## Current Behavior

User is missing

## Possible Solution

downgrade to v7.2.1

## Steps to Reproduce (for bugs)

I created a docker-compose example, see for a detailed instructions https://github.com/marcojarjour/keykloak_oauth2

**Comment by JoelSpeed** [comment]
Hi, we are quite short staffed at the moment so it's unlikely we are going to have time to look into this soon. Have you had an opportunity to dig into this to work out exactly why it's broken?

**Comment by marcojarjour** [comment]
Thanks for your feedback, unfortunately no, we are also short on time and I am more of a system engineer than a programmer and I have not worked with go therefore reading/debugging the code is not so easy for me.

**Comment by jacksgt** [comment]
Hello,
we are also affected by this and had to revert back to v7.2.0 after some of our users reported that the `X-Forwarded-User` header is missing when `prefer-email-to-user` is set to `true`.

I don't see any error messages in the logs that could explain why the header is missing now.

In case it helps, this is the full configuration we are using:
```
OAUTH2_PROXY_HTTP_ADDRESS = ':4180'
OAUTH2_PROXY_METRICS_ADDRESS = ':44180'
OAUTH2_PROXY_SILENCE_PING_LOGGING = 'true'
OAUTH2_PROXY_REDIRECT_URL = 'https://example.com/oauth2/callback'
OAUTH2_PROXY_WHITELIST_DOMAINS = 'example.com'
OAUTH2_PROXY_ALLOWED_GROUPS = 'default-role'
OAUTH2_PROXY_UPSTREAMS = 'http://example-app.my-ns.svc.cluster.local:80/'
OAUTH2_PROXY_PROXY_PREFIX = '/oauth2'
OAUTH2_PROXY_COOKIE_PATH = '/'
OAUTH2_PROXY_OIDC_GROUPS_CLAIM = 'roles'
OAUTH2_PROXY_PREFER_EMAIL_TO_USER = 'false'
OAUTH2_PROXY_EMAIL_DOMAINS = '*'
OAUTH2_PROXY_SCOPE = 'openid'
OAUTH2_PROXY_PROVIDER = 'oidc'
OAUTH2_PROXY_OIDC_ISSUER_URL = 'xxx'
OAUTH2_PROXY_CLIENT_ID = 'xxx'
OAUTH2_PROXY_CLIENT_SECRET = 'xxx'
OAUTH2_PROXY_COOKIE_SECRET = 'xxx'
OAUTH2_PROXY_COOKIE_SECURE = 'false'
OAUTH2_PROXY_SKIP_PROVIDER_BUTTON = 'true'
```

**Comment by JoelSpeed** [comment]
It's likely that the session isn't picking up the information from the token, that's what we are seeing in other reports. If you check the authentication logs it might show what was and what wasn't captured

**Comment by jacksgt** [comment]
The issue is still present.

**Comment by breedjaram32** [comment]
Hi,
problem is still in V7.4.0

**Comment by marcojarjour** [comment]
Thank you all, espacially to  @JoelSpeed and @babs i guess it was fixed by you with #1815, for me this issue is resolved with the 7.4.0 release.

**Comment by breedjaram32** [comment]
Hi, but I am using `--provider=keycloak-oidc` and does not works in 7.4.0
Older issue is https://github.com/oauth2-proxy/oauth2-proxy/issues/1813

/userinfo
{"user":"","email":"XXX@XXX.XX","groups":["group1","role:offline_access","role:uma_authorization"],"preferredUsername":"firstname.lastname"}

**Comment by marcojarjour** [comment]
If i am not missing something this should be fixed in master with #1874 so i guess you just need to be a bit more patient or using the master release in the meantime.

May i ask why you are using the keycloak-oidc? Maybe you could switch to oidc. We are using oidc with our keycloak without any issue.

**Comment by breedjaram32** [comment]
Because  `--provider=oidc` does not support the transmission of information about keycloak `role`
With `--provider=keycloak-oidc` I see user's assigned Keycloak roles in header.

**Comment by marcojarjour** [comment]
Yes then its not an option.
As mentionend i guess the master release would work then, but it seems you need to compile it on your own, but its quite straight forward.

**Comment by babs** [comment]
I've made a release on my fork that includes the fix. It would be nice to check if it resolves your issue.
If not, please tell me.

One note, I think, if I remember correctly but might be mistaken, in keycloak-oidc impl, group is "forced" as role and the cli option to change it is ignored, again might be wrong.

**Comment by breedjaram32** [comment]
unresolved
