### ISSUE TITLE
Trying to build container fails, make docker

### ISSUE THREAD

**Issue by japrogramer** [oauth2-proxy/oauth2-proxy#1682]
## Expected Behavior
build container and tag image, from my own branch .. with  no changes to makefile.

The build process works in one machine but not a different machine

## Current Behavior
This works on one machine but not on a different machine
````
moby/buildkit                                               buildx-stable-1         a2c9241854f2   4 weeks ago     142MB

▶ DOCKER_BUILD_PLATFORM=linux/amd64 make docker                                                  ∞
docker buildx build --build-arg RUNTIME_IMAGE=alpine:3.15 --build-arg VERSION=v7.3.0-1-g18fd60a3 --platform linux/amd64 -f Dockerfile -t quay.io/oauth2-proxy/oauth2-proxy:latest .
WARNING: No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
```

**Comment by JoelSpeed** [comment]
Can you raise a PR and I'll test this out. Unfortunately the behaviour seems to vary a lot depending on the system you're running on. Can you share any details about the systems the makefile is and isn't working on?
