### ISSUE TITLE
Is there a way to block or kill the session of users?

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#1684]
Is there currently a way to block specific users or log them out for example based on their user id?

# Use Case

The credentials of a user are stolen and we want to block the related account. Of course we can do this on IDP side, but the user or attacker still has a valid session until the access token expires.

I would also like to kill the user related session, if I block the user on IDP side.

**Comment by JoelSpeed** [comment]
In this case, you should rotate the cookie secret, this will log everyone out but means that the credentials of the stolen user can no longer be used. We don't have any plans to change this right now. My recommendation is to make sure you have short lived tokens coming from the identity provider and make sure to block the refresh token as soon as you are made aware of the breach.
