### ISSUE TITLE
Groups claim from auth0 is sometimes present

### ISSUE THREAD

**Issue by anthr76** [oauth2-proxy/oauth2-proxy#1686]
## Expected Behavior

`X-Auth-Request-Groups` header and `?allowed_groups` parameter to be fulfilled.

## Current Behavior

It appears to sporadily be fulfilled. 

## Possible Solution

?

## Steps to Reproduce (for bugs)

The configuration https://github.com/anthr76/infra/blob/main/k8s/base/networking/oauth2-proxy/helm-release.yaml

1.  
2.  
3.  
4.  

## Context

I would like to scope certain ingresses to `?allowed_groups` but this seems to only be fulfilled "sometimes" as a part of auth0. When the header is missing nginx gives a 401 and I can't get nginx or oauth proxy or nginx to tell me much more..

## Your Environment

- Version used:

Nginx is configured with the following annotations:

```
    nginx.ingress.kubernetes.io/auth-response-headers: x-auth-request-email, x-auth-request-groups
    nginx.ingress.kubernetes.io/auth-signin: https://auth.kutara.io/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth
```

**Comment by JoelSpeed** [comment]
Did you manage to investigate this at all? I'm unlikely to find time to look into this any time soon so I'll need someone from the community to help work out exactly what's broken here

**Comment by anthr76** [comment]
This is still an issue.

**Comment by anthr76** [comment]
This is still an issue
