### ISSUE TITLE
Ping endpoint should check Redis connection

### ISSUE THREAD

**Issue by amincheloh** [oauth2-proxy/oauth2-proxy#1687]
## Expected Behavior

ping endpoint should check Redis connection

## Current Behavior

ping endpoint always returns 'OK' message 

## Possible Solution
using something like validating Redis configuration on startup

## Context
when running oauth2-proxy on K8S environment with liveness/readiness probe, if Redis server down oauth2-proxy still in the ready state because of ping endpoint always returns 'OK'.

## Your Environment

- Version used: 7.3.0

**Comment by JoelSpeed** [comment]
I'm not opposed to the ping endpoint supporting this if someone wants to work on a PR for it. Is there any way we can make sure this is thoroughly tested if we do go ahead?

**Comment by t-katsumura** [comment]
Hi
I'm interested in this feature and thinking to implement experimental code.
As for testing, in my opinion, [miniredis](https://github.com/alicebob/miniredis) could be one candidate for redis moc server.

By the way, I have a question.
Does this feature should really be added to `/ping` endpoint ?
It's very common to use Liveness Probe (which correspond to current ping) and Readiness Probe at the same time on k8s.
So, I think this feature should be implemented as an another endpoint, `/readiness` for example.

**Comment by JoelSpeed** [comment]
> As for testing, in my opinion, [miniredis](https://github.com/alicebob/miniredis) could be one candidate for redis moc server.

Yep I think we could use that here.

> It's very common to use Liveness Probe (which correspond to current ping) and Readiness Probe at the same time on k8s.

Yes I would agree, I think this should be a separate more in depth health check. That would allow users to have the option of the dumb ping endpoint and the actual health checks
