### ISSUE TITLE
Redis 7.x cluster connection problem

### ISSUE THREAD

**Issue by gino-ats** [oauth2-proxy/oauth2-proxy#1692]
I'm not able to use Redis cluster v.7 as session storage while it works with Redis 6.x. 

## Expected Behavior
OAuth2-proxy should work with Redis 7, too.

## Current Behavior
Using Redis 7.0.1, oauth2-proxy 7.3.0 and docker I receive "unable to set a redis initialization key: got 4 elements in cluster info address, expected 2 or 3" error during startup. Using Redis 6.2.7 all is working well.

```
docker run -P --rm --name oauth2-proxy  quay.io/oauth2-proxy/oauth2-proxy:v7.3.0 \
    --cookie-secure=false \
    --upstream="http://internal.website.com/" \
    --http-address="127.0.0.1:4180" \
    --redirect-url="http://internal.website.com/oauth2/callback" \
    --cookie-secret=OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w= \
    --client-id=XXXXXXXXXXXXXXXXXXXXXXXXXXX \
    --client-secret=XXXXXXXXXXXXXXXXXXXXXXXXXXX \
    --email-domain=* \
    --session-store-type=redis \
    --redis-use-cluster=true \
    --redis-cluster-connection-urls=redis://redis-cluster-7:6379

[2022/06/15 09:31:41] [main.go:54] invalid configuration:
  unable to set a redis initialization key: got 4 elements in cluster info address, expected 2 or 3
  unable to delete the redis initialization key: got 4 elements in cluster info address, expected 2 or 3

```
Using Redis 6.2.7, oauth2-proxy 7.3.0 and docker:

```
docker run -P --rm --name oauth2-proxy  quay.io/oauth2-proxy/oauth2-proxy:v7.3.0 \
    --cookie-secure=false \
    --upstream="http://internal.website.com/" \
    --http-address="127.0.0.1:4180" \
    --redirect-url="http://internal.website.com/oauth2/callback" \
    --cookie-secret=OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w= \
    --client-id=XXXXXXXXXXXXXXXXXXXXXXXXXXX \
    --client-secret=XXXXXXXXXXXXXXXXXXXXXXXXXXX \
    --email-domain=* \
    --session-store-type=redis \
    --redis-use-cluster=true \
    --redis-cluster-connection-urls=redis://redis-cluster-6:6379

[2022/06/15 16:40:35] [proxy.go:89] mapping path "/" => upstream "http://internal.website.com/"
[2022/06/15 16:40:35] [oauthproxy.go:156] OAuthProxy configured for Google Client ID: XXXXXXXXXXXXXXXXXXXXXXXXXXX
[2022/06/15 16:40:35] [oauthproxy.go:162] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled

```

## Your Environment

- Version used: oauth2-proxy v7.3.0, Redis v7.0.1, Redis 6.2.7

**Comment by marcusvezz** [comment]
I have the same problem too.

**Comment by haydn-j-evans** [comment]
We are using go-redis v8, which only supports redis 6.x

By the looks, to support redis 7.x we have to upgrade this library to go-redis v9

[link to documentation](https://github.com/go-redis/redis#installation)

By the wording, it seems like its not back-compatible, so extra work would have to be done to support both libraries at the same time.

**Comment by pierluigilenoci** [comment]
@JoelSpeed can you please take a look?

**Comment by JoelSpeed** [comment]
If we want to update this it will need a community member to invest some time into doing the work, I won't have time for it.

Do we know if the v9 version of the library is incompatible with the v6 version of Redis? That would constitute a breaking change unless we add support for both within OAuth2 Proxy (which I think is possible now we are using go modules)

**Comment by pierluigilenoci** [comment]
So @gino-ats and @marcusvezz feel free to open a PR to implement this. 🚀

**Comment by mvalenzisi** [comment]
This is still an issue.

**Comment by JoelSpeed** [comment]
Version 7.4.0 includes the new redis library which claims to support redis 7, has it not resolved the issue?

**Comment by mvalenzisi** [comment]
@JoelSpeed we tried version 7.4.0, unfortunately we hit this other issue https://github.com/oauth2-proxy/oauth2-proxy/issues/1666

**Comment by braunsonm** [comment]
Not related to this issue, so closing.

**Comment by IgorGolivets** [comment]
I have a similar issue with Azure Redis ver 6.0 and oauth2 7.5.1:
```
[2023/11/28 13:03:15] [main.go:54] invalid configuration:
  unable to set a redis initialization key: i/o timeout
  unable to delete the redis initialization key: i/o timeout
```
with below config:
```
    - --upstream=http://127.0.0.1:9090
      - --http-address=0.0.0.0:8081
      - --provider=azure
      - --client-id=<clientId>
      - --client-secret=<secret>
      - --azure-tenant=tenantID
      - --oidc-issuer-url=https://login.microsoftonline.com/tenantID/v2.0
      - --email-domain=*
      - --cookie-secret=<cookiesecret>
      - --cookie-secure=true
      - --cookie-csrf-per-request=true
      - --cookie-csrf-expire=5m
      - --reverse-proxy=true
      - --session-store-type=redis
      - --redis-connection-url=redis://<hostname>.redis.cache.windows.net:6380/0
      - --redis-password=<redispass>
```

**Comment by uidmehdi** [comment]
@IgorGolivets, try adding `--redis-insecure-skip-tls-verify=true`. This should solve your issue.
