### ISSUE TITLE
Support PROXY Protocol

### ISSUE THREAD

**Issue by OOTS** [oauth2-proxy/oauth2-proxy#1696]
I propose to implement support for the PROXY protocol in OAuth2-Proxy. That would make it possible to run OAuth2-Proxy behind a L7 load balancer or reverse proxy, but without the requirement of having the LB/proxy decrypt the TLS connection.

## Current Behavior

When running OAuth2-Proxy behind a load balancer or reverse proxy, the LB/proxy needs to be able to terminate/decrypt the TLS connection to inject the `X-Forwarded-For` headers and thereby inform OAuth2-Proxy of the client's actual IP address. (Though I haven't tried it, the documentation suggests OAuth2-Proxy already supports this kind of setup.) Because of this requirement, the LB/proxy can see all traffic going to OAuth2-Proxy in plain text, which is a bit of a security risk.

## Expected Behavior

There is an alternative to injecting `X-Forwarded-For` and similar headers into the (otherwise encrypted) HTTP request: the [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt). Effectively, it works be prefixing a bit of information to the TCP datastream. (Depending on the version of the protocol, the information is prefixed either in plain ASCII text or in a binary format.)

It would be nice if OAuth2-Proxy supported this protocol. This way, one could run OAuth2-Proxy behind a load balancer or reverse proxy without giving the LB/proxy the necessary TLS keys (and thereby full access to the plaintext HTTP traffic). Of course, the load balancer needs to support the proxy protocol, too.

## Possible Solution

Googling for support of the PROXY protocol in Go came up with a number of implementations:
* https://inkel.github.io/posts/proxy-protocol/ / https://github.com/inkel/viaproxy
* https://github.com/sprucehealth/go-proxy-protocol
* https://github.com/armon/go-proxyproto
* https://github.com/pires/go-proxyproto

The first ones appear to be quite basic (but also short) implementations. The last one appears to be the most complete and actively maintained one.

## Context

My goal would be to set up OAuth2-Proxy:
* behind a load balancer
* in a way such that OAuth2-Proxy has the real client's IP address
* in a way such that the load balancer doesn't need to have the TLS keys to decrypt the incoming traffic.

## Your Environment

- Version used: 7.3.0
- load balancer
- Kubernetes

**Comment by JoelSpeed** [comment]
Have you looked at all into where within OAuth2 Proxy this would be implemented? I expect somewhere in the server code we need to change our TLS listener to a proxy protocol listener of some description?

Would you expect the proxy to use proxy protocol the whole way through (ie client side, sending onto upstream servers) or just on the server side from the load balancer?

**Comment by JoelSpeed** [comment]
Sounds like a reasonable approach, we can add these new types to new files in the server package we already have and handle it all where we set up the server already. I'd definitely make this opt in though

**Comment by OOTS** [comment]
I 100% agree on making this feature opt-in.

That would probably involve adding a new command line parameter (e.g. `--expect-proxy-protocol`) and a bit of additional logic when creating the listeners. And then probably a bit of documentation for this parameter.

And of course, some unit tests for the new code.

**Comment by JoelSpeed** [comment]
That sounds good. If we are adding proxy protocol options we need to make sure it's obvious if they are for the server or for the proxy code through to the upstreams.

I would recommend adding this just to the alpha config instead of adding a new flag, we have too many flags already!

If you can create a PR I'll try and find the time to review

**Comment by OOTS** [comment]
I'll see if/when I have a bit of time to implement this. (If someone else wants to pick it up in the mean time, please feel free to do so.)

What's the situation with the alpha config? I was trying to avoid it, since it sounds so... deprecated. Is it actually supposed to become a replacement to configuration via command line parameters?

**Comment by JoelSpeed** [comment]
The intention for the alpha config is that eventually it will replace the current mess of config we have right now. It needs to go through some evolution before that point though because there are parts that haven't migrated and parts that I want to change within it. I've learnt a lot about API design since starting the project so it needs a thorough UX review once we get closer to releasing it

**Comment by OOTS** [comment]
bump

**Comment by marcomusso** [comment]
pump up the vol^H^H^Hissue. ehm bump

**Comment by 303snowing** [comment]
Is it ready? 
I used oauth2-proxy and nginx auth_request with okta as a gateway to check user permission of this proxy(https://github.com/snail007/goproxy), but seems to not work.🙉

**Comment by OOTS** [comment]
I'm still interested in this

**Comment by JoelSpeed** [comment]
Does anyone have time to raise a PR to support proxy protocol?
