### ISSUE TITLE
Issue with %2f in upstream URL

### ISSUE THREAD

**Issue by raz3r** [oauth2-proxy/oauth2-proxy#1698]
Hi,

I am using oauth2-proxy (latest version) with Nginx (latest version) on Debian 11. It seems like this plugin automatically unescapes escaped paths/URLs, there are two similar issues closed, any help would be appreciated.

If you try to add an upstream URL with an escaped path such as http://127.0.0.1:8000/a%2Fb/ it will instead bind to the unescaped path /a/b/.

https://github.com/oauth2-proxy/oauth2-proxy/issues/844
https://github.com/oauth2-proxy/oauth2-proxy/issues/459

**Comment by alexdanilowicz** [comment]
Thanks for adding this! The option is `proxyRawPath` BTW @raz3r 

Hoping to make this non-alpha someday!
