### ISSUE TITLE
Docu: Azure Auth Provider docu unclear

### ISSUE THREAD

**Issue by justarandomsysadmin** [oauth2-proxy/oauth2-proxy#1702]
Third point:

> On the "Settings" / **"Required Permissions"** page of the app, click on "Windows Azure Active Directory" and then on "Access the directory as the signed in user". Hit "Save" and then then on "Grant permissions" (you might need another admin to do this).

There is no **Required Permissions** section anywhere to be found. Not sure what is meant here, there are SSO sections for enterprise apps, but registered apps can't be configured there it says.

> On the "Settings" / **"Reply URLs"** page of the app, add https://internal.yourcompanycom/oauth2/callback for each host that you want to protect by the oauth2 proxy. Click "Save".

There is no "Reply URLs" to be found. This has changed the left side setting "Authentication" and then "Redirect URLs". But I'm not sure if that is meant.

So can anyone clear this up for me? I'm not able to correctly configure it with the provided documentation and I'm stuck right now.

**Comment by hevans-dglcom** [comment]
yes - the callback URL is the "Redirect URL" in the azure app registration.

Just be warned, the azure provider is currently broken on the latest release, please use the 7.2.1 release instead
