### ISSUE TITLE
Single oauth2-proxy deployment serving multiple apps with dedicated "restricted_access" list per application.

### ISSUE THREAD

**Issue by mateuszkula1** [oauth2-proxy/oauth2-proxy#1703]
## Context
Hi,

I followed instructions described in this digitalocean [tutorial](https://www.digitalocean.com/community/tutorials/how-to-protect-private-kubernetes-services-behind-a-github-login-with-oauth2_proxy).

I'm having 2 dummy applications which are protected by sso with oauth2-proxy. The problem is that both ingresses instances are pointing to the same oauth2-proxy, so rules like list of users defined in restricted_access is common for both apps.

I would like to be able to define different list of users who have access to echo1.mydomain.com and different set of users with access to echo2.mydomain.com 

## Expected Behavior

It would be nice to be able to define in oauth2-proxy configuration something like this:
```
default:
  *@mydomain.com

echo-1-ingress:
  user1@mydomain.com
  user2@mydomain.com

echo-2-ingress:
  user3@mydomain.com
  user4@mydomain.com
```

## Current Behavior

There is single file "authenticated-emails-list" which will be common to all apps ingresses that are connecting to oauth2-proxy.

## Possible Solution

I understand that I could deploy two oauth2-proxy one for app1 and second one for app2, but is it the only option to achieve such functionality? 

## Summary

I searched through Internet and Documentation and I cannot find option to setup different access lists per application using single oauth2-proxy deployment. Am I right that such config doesn't exist? If yes - is there any plan to introduce such functionality?

**Comment by hevans-dglcom** [comment]
Hi,

This is already doable on the /auth endpoint.

The trick is for each ingress, you can add parameters into the auth request annotation: 

You can use the following parameters:

allowed_groups
allowed_emails
allowed_email_domains

So your ingress 1 would use the following auth-url

```
nginx.ingress.kubernetes.io/auth-url: "https://auth.int.your_domain/oauth2/auth?allowed_emails=user1@mydomain.com,user2@mydomain.com"
```

**Comment by mateuszkula1** [comment]
Hello @hevans-dglcom,

Thanks for your hint! It looks that it would address the problem that I am facing.
Unfortunately I tried this approach with my current configuration and it didn't work for me. I have 2 following questions:

1. Is it possible to not set any permissions when starting oauth2-proxy? It would be best to provide access using Ingress annotations as you suggested, but when I am not defining "domain" or users through file - service cannot start and asks me to define at least one of them. It's not very problematic as I could be the "default" single user which has access to all company applications, but it looks like some compromise and not perfect solution.
```
[2022/07/01 13:10:33] [main.go:54] invalid configuration:
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
```
2. I set single user (other than me) in an "authenticated-emails-list" file so that the oauth2-proxy could start and I tried to access application with Ingress annotation "oauth2/auth?allowed_emails=name.lastname@mydomain.com" and it failed with 403 error for my credentials. It seems like this endpoint is not interpreted correctly, or it's ignored because of the file which defines which users are having access? Is there some additional configuration needed so that annotation parameters are used by oauth2-proxy?

I tried to find solution on my own, but after some hours I felt hopeless so came back here to look for some additional advice.

I can add that I see in the logs of oauth2-proxy pod (I censored sensitive data):
```
IP:PORT - e48bc4a11477d28b6ec3ffb048b39af9 - - [2022/07/01 10:39:11] 
sso.mydomain.com GET - "/oauth2/auth?allowed_emails=name.lastname@mydomain.com" 
HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" 401 13 0.000
```
And then:
```
IP:PORT - c31941100d7558358b7b47bdaf0111aa - 
name.lastname@mydomain.com [2022/07/01 10:39:15] 
[AuthFailure] Invalid authentication via OAuth2: unauthorized
```

**Comment by hevans-dglcom** [comment]
Nothing else is needed - this should just work out of the box.

Let me double check on one of my ingresses.

**Comment by hevans-dglcom** [comment]
Only thing I can see is that your ingress annotation does not need quotes for the auth url.

Just to be clear, the ingress restrictions do not interact with the rest of the code in any way, they just compare the parameter definitions against what is in your session data, so the only thing it can be is a misconfiguration at the ingress level.

Maybe just confirm also that your email is as expected at the session info endpoint - /oauth2/userinfo

**Comment by mateuszkula1** [comment]
Hi,

I found out that this "allowed_emails" is very fresh functionality which seems to be introduced in version 7.3.0 of oauth2-proxy -> https://github.com/oauth2-proxy/oauth2-proxy/pull/1595

I was using https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy helm chart which currently is set to version 7.2.1 and that's why it didn't work for me.

It seems that solves my issue as I have defined "mydomain.com" in global config and those annotations are narrowing access policy, so only user defined in "allowed_emails" has access and others don't, even if they have e-mail addresses register in "mydomain.com" from global config. It's exactly what I was looking for.

Many thanks for your support!

**Comment by yongzhang** [comment]
> Hi,
> 
> This is already doable on the /auth endpoint.
> 
> The trick is for each ingress, you can add parameters into the auth request annotation:
> 
> You can use the following parameters:
> 
> allowed_groups allowed_emails allowed_email_domains
> 
> So your ingress 1 would use the following auth-url
> 
> ```
> nginx.ingress.kubernetes.io/auth-url: "https://auth.int.your_domain/oauth2/auth?allowed_emails=user1@mydomain.com,user2@mydomain.com"
> ```

Hi @hevans-dglcom , do you know how to do this in traefik, I posted my configs [here](https://github.com/oauth2-proxy/oauth2-proxy/issues/1614#issuecomment-1185173519).
