### ISSUE TITLE
Add a new endpoint to simplify optional authentication

### ISSUE THREAD

**Issue by robertmuth** [oauth2-proxy/oauth2-proxy#1705]
For apps where a login is optional the nginx setup can be quite complex.

I believe a new endpoint say  /oauth2/optional_auth  could be helpful here.

in the nginx configuration most urls would use the new 
   auth_request /oauth2/optional_auth;

only a special  explicit authentication url would use the traditional  
   auth_request /oauth2/auth;
   

/oauth2/optional_auth would behave as follows:
* if there has been a previous authentication (e.g. as witnessed by a cookie) just behave as
    /oauth2/auth
* if there is not such cookie, set authentication related cookies/header to dummy values (e.g. empty strings)
  and return 202
  
  So /oauth2/optional_auth always return 202 and never triggers a login sequence.

**Comment by aimichal** [comment]
I see a lot of value in this optional/passs-thru mode, and have been wanting it for a while.

* One use-case is that websites can choose to display anonymous content (with a "login" link), or personalized content (with a "logout" link).
* Another use-case is for APIs, where the server can consider an oauth2-proxy provided header for authorization (so authenticated web users can access the API naturally in the browser), or can implement its own mechanism such as looking up a bearer token (so applications can use the API simply).

If there's a way to do this without changing oauth2-proxy (maybe there's already a feature like this, or a combination of settings that make it work like this), I'd love to know.

**Comment by hevans-dglcom** [comment]
This is a really good idea actually - we are just starting to use the JWT tokens injected by our nginx + subauth setup downstream into our microservices for user identification, and some of our developers sometimes want to handle everything inside the application, without 401s and redirects at the ingress level. This is

The following code will return 202 without headers if you are not authenticated but will return headers if authenticated (so you would still have to setup which headers you would like to respond with. Feel free to create some tests and open a PR.

```
headersOnlyPath   = "/headers"


r.Path(proxyPrefix + headersOnlyPath).Handler(p.sessionChain.ThenFunc(p.HeadersOnly))


func (p *OAuthProxy) HeadersOnly(rw http.ResponseWriter, req *http.Request) {
	
       session, err := p.getAuthenticatedSession(rw, req)
	if err != nil {
		rw.WriteHeader(http.StatusAccepted)
		return
	}

	// we are authenticated
	p.addHeadersForProxying(rw, session)
	p.headersChain.Then(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		rw.WriteHeader(http.StatusAccepted)
	})).ServeHTTP(rw, req)
}
```

**Comment by robertmuth** [comment]
This worked like a charrm - thanks!

Now, I wonder what is the best way to configure a sign out rule in nginx.
This works reasonable well - it logs out an redirects to the "root page (/)":

```
        location /oauth2/sign_out {
                 proxy_pass http://127.0.0.1:4180;
                 proxy_set_header Host $host;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Scheme $scheme;
                 proxy_set_header X-Auth-Request-Redirect $host;
        }
```
But the last line setting X-Auth-Request-Redirect does not seem to have much effect.

The documentation suggest to redirect to the sign-out page of oauth2 provider (google in my case).

**Comment by hevans-dglcom** [comment]
Have you whitelisted the domain you are trying to redirect back to?

```
--whitelist-domain 
```
I believe this validation also applies to redirects after sign_out
