### ISSUE TITLE
InsecureOidcSkipNonce option ignored in GitLab provider

### ISSUE THREAD

**Issue by watterm** [oauth2-proxy/oauth2-proxy#1710]
The GitLab provider ignores the option to skip nonce checks for insecure OIDCs and is [set to false](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/gitlab.go#L42).

## Expected Behavior
Use the `InsecureSkipNonce` option in the GitLab provider.

## Current Behavior
Ignoring the option. Nonce verification fails:
```
[2022/06/14 12:53:34] [oidc.go:96] nonce verification failed: id_token nonce claim does not match the session nonce
```

## Possible Solution
Use the option from the OIDC provider.

## Steps to Reproduce (for bugs)

1.  Connect an insecure GitLab
2.  Nonce verification fails

The default setting for the InsecureSkipNonce option is true, so it doesn't have to be set explicitly. Doing so doesn't change anything.

## Context

We have a GitLab for staging in an internal network on a different port, for which we skip identification.

## Your Environment

- Version used:
7.3.0

**Comment by jenqaz** [comment]
We've the same issue with the ADFS provider. It works correctly if we change the `--provider` to OIDC. By the way, is there any reason to switch `--provider` back to ADFS if everything works with OIDC?

**Comment by jsmouret** [comment]
> We've the same issue with the ADFS provider. It works correctly if we change the `--provider` to OIDC. By the way, is there any reason to switch `--provider` back to ADFS if everything works with OIDC?

not everything works with OIDC: for example #1793 where the Gitlab provider gives back the right user.
