### ISSUE TITLE
Upstream Timeout does not work

### ISSUE THREAD

**Issue by SSvilen** [oauth2-proxy/oauth2-proxy#1716]
We use alpha config to set our upstream and in that config we've set timeout to 600s.
Oauth2 seems to ignore that options - the http calls to backend are being dropped after exactly 30s.

## Expected Behavior

The timeout configurations should work.

## Current Behavior

The calls are still being dropped after 30s.

## Steps to Reproduce (for bugs)

Define a upstream with alpha config and set the timeout property.

## Context

We have some http calls that can take long time to complete.

## Your Environment

- Kubernetes  - all components (oauth2 proxy and http backend run as containers)

- Version used: 7.3.0

**Comment by JoelSpeed** [comment]
Could you try to add some debug logging to see if that is the issue? When using alpha config I didn't think it merged in anything from the newer config that would overwrite the alpha config but there could be a bug there with individual options

**Comment by SSvilen** [comment]
btw we noticed, that setting the timeout to anything below 30s seems to be taking effect. 
Is 30s the maximum?

**Comment by t-katsumura** [comment]
Upstream timeout in alpha config works as expected for me even it's longer than 30s.
(v7.3.0 used)

@SSvilen 
Your problem could be caused by your environment.
For example, GKE has its loadbalancer 30s timeout in default.
https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#timeout

So, you should describe your environment and configuration in more detail.

**Comment by SSvilen** [comment]
We narrowed down the problem to the Open Shift ingress controller. 
Interesting fact  - the problem did not appear when the communication was going between ingress and pod directly - seems like keep-alive was working fine in that situation.

**Comment by jacksgt** [comment]
Aha, another fellow Openshift user! :-)

Thanks for the follow-up. You probably need to set the `haproxy.router.openshift.io/timeout` annotation on the route: https://docs.openshift.com/container-platform/4.9/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration

**Comment by SSvilen** [comment]
We increased it in the ingress controller settings.
