### ISSUE TITLE
Dynamically pass a parameter to oauth2-proxy login url

### ISSUE THREAD

**Issue by xelita** [oauth2-proxy/oauth2-proxy#1717]
I would like to dynamically pass a **kc_idp_hint** parameter to the oauth2-proxy login url. 
The goal is to use Keycloak Client-suggested Identity Provider feature to authenticate users with several external IDPs - https://www.keycloak.org/docs/latest/server_admin/index.html#_client_suggested_idp

## Expected Behavior

**kc_idp_hint** parameter is provided via our frontend nginx depending on the client connecting to the application. (several clients > several IDP).

eg. 
client1 login url: https://oauth2-domain/auth?kc_idp_hint=client1-idp"
client2 login url: https://oauth2-domain/auth?kc_idp_hint=client2-idp"
...

## Current Behavior

I do not know how to provide oauth2-proxy with this parameter (dynamically).

- Version used: 7.3.0

**Comment by xelita** [comment]
Thanks in advance team.

**Comment by haydn-j-evans** [comment]
Do you have some identifier that nginx can use to distinguish between client types? 

You could pass the additional parameters to the /oauth2/start endpoint using the new "loginURLParameters" option in the alpha struct, but to pass the *correct* parameter based on the client type you would have do this in the nginx block.

Maybe you could do something like this? Each useragent gets rewritten to a different domain (and therefore server block), with different /start parameters for each block's auth-login string ... just spitballing....

https://serverfault.com/questions/775463/nginx-redirect-based-on-user-agent

**Comment by xelita** [comment]
> Do you have some identifier that nginx can use to distinguish between client types?
> 
> You could pass the additional parameters to the /oauth2/start endpoint using the new "loginURLParameters" option in the alpha struct, but to pass the _correct_ parameter based on the client type you would have do this in the nginx block.
> 
> Maybe you could do something like this? Each useragent gets rewritten to a different domain (and therefore server block), with different /start parameters for each block's auth-login string ... just spitballing....
> 
> https://serverfault.com/questions/775463/nginx-redirect-based-on-user-agent

Thanks I am checking this solution now. Will keep you posted!

**Comment by xelita** [comment]
Thanks @haydn-j-evans - I have made some progress on this.

First, I have migrated my oauth2-proxy config to alpha config
Then, I have created a virtual host to handle my client1 requests (client1.mydomain.com). 
`
server {  
    listen 443 ssl;
    server_name client1.mydomain.com;

    ssl_certificate /config/nginx/ssl.crt;
    ssl_certificate_key /config/nginx/ssl.key;

    location / {
        proxy_set_header    X-Forwarded-Host    $host;
        proxy_set_header    X-Forwarded-Port    $server_port;
        proxy_set_header    X-Forwarded-Proto   $scheme;      

        set $args $args&kc_idp_hint=client1-idp;
        proxy_pass                      http://oauth2-proxy:4180/oauth2/start;
        proxy_pass_request_headers      on;   
    }     
}
`
I am properly redirected to the external KC IDP (client1-idp) from where I can authenticate successfully.

The problem I am facing now is that I am redirected to https://www.myappdomain.com url after the authentication. This behaviour is expected because it is the default redirect url I have defined in the oauth2-proxy config file.

As a result, I am getting the following 403 error:  **AuthFailure Invalid authentication via OAuth2: unable to obtain CSRF cookie**

Is there a way to dynamically redirect client1 to the **client1.mydomain.com** domain by using /oauth2/start endpoint?

**Comment by haydn-j-evans** [comment]
yes - just add the additional parameter to the /start request

rd=https://client1.mydomain.com

**Comment by xelita** [comment]
unfortunately, it does not seem to be taken into consideration
`
location / {
    proxy_set_header    X-Forwarded-Host    $host;
    proxy_set_header    X-Forwarded-Port    $server_port;
    proxy_set_header    X-Forwarded-Proto   $scheme;      

    set $args                                       $args&kc_idp_hint=client1-idp&rd=https://client1.mydomain.com/oauth2/callback;
    proxy_pass                                   http://oauth2-proxy:4180/oauth2/start;
    proxy_pass_request_headers      on;   
}     
`
Is there anything missing there?

**Comment by xelita** [comment]
I am closing this issue.

I finally implemented another solution using oauth2-proxy state request param.

**Comment by aXtionTim** [comment]
> unfortunately, it does not seem to be taken into consideration
> 
> ` server { listen 443 ssl; server_name client1.mydomain.com;
> 
> ```
> ssl_certificate /config/nginx/ssl.crt;
> ssl_certificate_key /config/nginx/ssl.key;
> 
> location / {
>     proxy_set_header    X-Forwarded-Host    $host;
>     proxy_set_header    X-Forwarded-Port    $server_port;
>     proxy_set_header    X-Forwarded-Proto   $scheme;      
> 
>     set $args $args&kc_idp_hint=client1-idp&rd=https://client1.mydomain.com/oauth2/callback;
>     proxy_pass                      http://oauth2-proxy:4180/oauth2/start;
>     proxy_pass_request_headers      on;   
> }     
> ```
> 
> } ` Is there anything missing there?

Possibly the rd parameter had to be URL escaped.
