### ISSUE TITLE
Proxy ROPC request from client to IdP

### ISSUE THREAD

**Issue by watsuwo** [oauth2-proxy/oauth2-proxy#1718]
I propse the proxy feature for ROPC request from client.
That would make it possible to issue access tokens to clients whose interfaces cannot be changed immediately.

## Current Behavior

The current behavor can be SSO by authorization code flow.

Oauth2Proxy is often adopted when switching IdP, but often a few clients are unable to respond immediately to the authorization code flow.
Token issuance by ROPC is effective for those clients.

Therefore, I would like to add an endpoint to proxy IdP and ROPC requests to Oauth2 Proxy.

This endpoint allows clients to respond to IdP switching as quickly as possible.

**Comment by JoelSpeed** [comment]
Perhaps you could expand on the details of what you mean here, this isn't something I'm familiar with.

As I understand it, you're suggesting that if you changed IDP, OAuth2 Proxy clients should remain logged in/ should be able to remain logged in using this new endpoint? 

If we were to support multiple providers, would that not allow the existing clients to remain authenticated while they make the transition to the new identity provider?
