### ISSUE TITLE
v7.3.0 with gitlab provider requires `issuer-url` while v7.2.1 does not

### ISSUE THREAD

**Issue by Jeinhaus** [oauth2-proxy/oauth2-proxy#1722]
## Expected Behavior

When upgrading from v7.2.1 to v7.3.0 I expected that no changes to my config are required, since nothing in the changelog mentions changes regarding `issuer-url` or other breaking changes.
Since the [documentation](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#gitlab-auth-provider) still says the `oidc-issuer-url` is only required when self-hosting Gitlab I expected it to work in my case with v7.3.0 without any `oidc-issuer-url`

## Current Behavior

The pod crashes with the following error:

```
[2022/07/13 14:15:46] [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: invalid provider verifier options: missing required setting: issuer-url
Stream closed EOF for system/oauth2-proxy-5c46b7d6cc-n7knm (oauth2-proxy)
```

## Steps to Reproduce (for bugs)

You might be able to reproduce this bug with my config.
This is the snippet from my `values.yaml`:

```yaml
      configFile: |-
        provider = "gitlab"
        gitlab_groups = [ "example" ]
        redirect_url = "https://example.com/oauth2/callback"
        whitelist_domains = [ ".example.com" ]
        email_domains = [ "*" ]
        upstreams = [ "static://202" ]
        silence_ping_logging = true
        cookie_domains = [ ".example.com" ]
        reverse_proxy = true
```

## Context

Is there anything I missed in the change log?

## Your Environment

* running oauth2-proxy in a k8s cluster
* installed using the Helm chart version 6.2.2
* using the [Traefik ForwardAuth with static upstreams](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#forwardauth-with-static-upstreams-configuration).
* using the `gitlab` provider with a group hosted on https://gitlab.com
- Version used: v7.3.0

**Comment by Jeinhaus** [comment]
Setting `oidc_issuer_url = "https://gitlab.com"` fixes this. So maybe just updating the docs is enough?

**Comment by JoelSpeed** [comment]
I think a PR into the 7.3.0 release broke a bunch of the defaulting for the providers so more options are being required this release than should have been. It's on my list to investigate the provider setup again and resolve this

**Comment by JuroOravec** [comment]
Came across this on v7.6.0, can confirm that adding `oidc_issuer_url` fixes it.
