### ISSUE TITLE
Show customized Forbidden page for unauthorized users instead of black default browser page

### ISSUE THREAD

**Issue by arshiamalek** [oauth2-proxy/oauth2-proxy#1734]
When using oauth2-proxy with Keycloak and Istio if a user does not have enough permissions to access a webpage the browser shows a default 403 page
<img width="1440" alt="Screen Shot 2022-07-19 at 2 05 54 PM" src="https://user-images.githubusercontent.com/80602936/179824463-17183fbf-d92d-4f53-89de-75f934cfec64.png">

## Expected Behavior

Allow users to customize the page above adding a custom page with.

## Current Behavior

If the user for instance does not have their email verified the page above is displayed and is not configurable. 

## Possible Solution

Allow users to provide a template directory or path for error messages.

- Version used:
- keycloak: 12.0.4
- istio-proxy: v2:1.10

**Comment by JoelSpeed** [comment]
This is weird, usually it should respond with an error page and in that case, you can customize how that looks as well. Do you happen to have logs that can show what is happening here?
