### ISSUE TITLE
Support multiple Client IDs on the same proxy instance

### ISSUE THREAD

**Issue by jleaniz** [oauth2-proxy/oauth2-proxy#1740]
Unable to provide more than one Client ID for authentication. I have a use case where I would like to authenticate a web application and a native application (each with their own Client ID) using the same oauth2-proxy instance.

## Expected Behavior

I can specify more than one client_id and client_secret in the configuration file and the oauth2-proxy instance will authenticate clients based on the right issuer/audience/client_id

## Current Behavior

Only one client_id can be specified in the configuration.

## Context

One use case for this feature is an API server that is a backend for a web UI and can be sent requests from command-line clients (or other native clients) that require OAuth2 authentication. Each client has its own client_id. The oauth2-proxy sits in front of the API server and authenticates incoming requests accordingly (requests could come from different client_ids)

## Your Environment

See above

- Version used: 7.3.0

**Comment by JoelSpeed** [comment]
There's some work in progress on implementing multiple providers, I think once that's done this should be possible

**Comment by andrew-gropyus** [comment]
@JoelSpeed Looks like the stale-bot got to this one. Since there is some work in progress (#1657) does it make sense to keep it open?

**Comment by andrew-gropyus** [comment]
bump for stale

**Comment by OmarHawk** [comment]
Will this then not be implemented? It seems, there is quite a large PR open which also got closed due to inactivity...

**Comment by adamaziz15** [comment]
For anyone still looking for a solution, I wrote a blog post that might be helpful (TLDR I sort of layered 2 proxies to accomplish this)
https://www.withcoherence.com/post/multi-client-authentication-with-auth0-and-oauth2-proxy

**Comment by meszolym** [comment]
@adamaziz15 , it leads to a 404.
