### ISSUE TITLE
[question] Why nonce value remains same in ID Token after cookie refresh call?

### ISSUE THREAD

**Issue by amanrao23** [oauth2-proxy/oauth2-proxy#1741]
On the successful cookie-refresh call, ID and Access Token are refreshed but nonce parameter in ID token value remains same as in the old ID token. Is this the expected behavior?

## Expected Behavior
New nonce value should be generated in the refreshed ID token on the cookie refresh call.

## Current Behavior
Nonce value remains same in old and refreshed ID token.

## Steps to Reproduce (for bugs)

1.  Create a new session on any application using Oauth2-proxy. 
2.  Save the nonce value in the generated ID token.
3.  Wait for the cookie-refresh call.
4.  Compare the value of nonce in old and refreshed ID token.

## Your Environment

- Version used:
7.3.0

**Comment by JoelSpeed** [comment]
Have you dug around in the code? It's quite possible that we aren't changing the nonce during a refresh flow. It was my understanding that the nonce was only used to protect the login flow and wasn't needed for the refresh but @NickMeves might know more

**Comment by NickMeves** [comment]
I think setting the nonce is only part of the Authentication Request: https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest

Backend IDPs even after refreshes preserve what we originally sent in the IDToken (so we can continue validating the nonce in the IDToken against what store we in our session that we sent in the original request.
