### ISSUE TITLE
[Question] Is validating claims (e.g. `exp`) possible with passing a JWT Token? 

### ISSUE THREAD

**Issue by sherifkayad** [oauth2-proxy/oauth2-proxy#1742]
If one would use the `oauth2-proxy` to receive and validate JWT tokens before passing a request through (e.g. by setting `--skip-jwt-bearer-token` and `--extra-jwt-issuers`), would there by any possibility to check on some of the claims of the token beyond decoding it? e.g. checking the expiry (`exp`) or even some other claims against some values?

## Expected Behavior
N.A.

## Current Behavior
N.A.

## Possible Solution
N.A.

## Steps to Reproduce (for bugs)
N.A.

## Context
I am basically trying to use `oauth2-proxy` also as an authenticator for service-2-service communication. A necessary check (aside from the token authenticity) is the token validity and its time of expiration. Potentially we could also check on some additional claims matching certain values, however, the most important thing for us at the moment is to find a way to validate the expiration time and that we don't route requests with expired tokens to our services. 

## Your Environment
N.A.

**Comment by JoelSpeed** [comment]
We intend in the future to have authorization as a configuration option to check contents of tokens in this way, but it's not something we've had the time to implement just yet

**Comment by sahmadinejad-varmour** [comment]
any update on this?

**Comment by JoelSpeed** [comment]
OAuth2 Proxy does basic authz, in that it makes sure you have the correct email domain and group membership for certain provider, though it's not completely extensive and customisable. You can do this in your own application if you need to
