### ISSUE TITLE
Cookies expire immediately upon login

### ISSUE THREAD

**Issue by LeeMartin77** [oauth2-proxy/oauth2-proxy#1745]
Hello!

I have been happily using oauth2 proxy in my K3S cluster for quite a while, however when some pods rolled recently causing an upgrade from v7.2.1 to v7.3.0 (I was using the 'latest' tag), on logging in, cookies aren't set, and the following two warnings appear in the console:

```
Cookie “_oauth2_proxy_0” has been rejected because it is already expired.
Cookie “_oauth2_proxy_1” has been rejected because it is already expired.
```

Something seems to have changed to cause this between v7.2.1 and v7.3.0, as pinning to v7.2.1 causes everything to function again, with cookies being set and being able to be used on requests.

## Expected Behavior

After logging in, cookies should be set with an appropriate expiry time, so they don't immediately expire.

## Current Behavior

The expiry on the cookies is in the past, so the browser immediately disposes of them as expired.

## Possible Solution

~~If I was a gambler, I'd put it down to the fact the date in the pod is in UTC, and I'm currently on BST~~ I'm moderately less convinced of this now - I had a skim over the code diff between the two versions, but I'm not a Go person, so nothing immediately sprang out.

## Steps to Reproduce (for bugs)

This is on a project I do in an open repo, so I'll drop some links:

Relevant bit of the helm chart:

https://github.com/LeeMartin77/PaceMe.js/blob/8c2bd23b3417741c44f8becc97e85b27f806488d/helm/templates/traefik-ingress.yml#L92

In order to reproduce, you can deploy this project somewhere switching out the oauth2-proxy tag for v7.2.1, alternatively, I've deployed the application with v7.3.0 at [https://app-test.paceme.info](https://app-test.paceme.info/) - the app on v7.2.1 is running on [https://app.paceme.info](https://app.paceme.info/)

If it works for people in other regions, it could be simply down to me being on BST.

## Context
I use oauth2 proxy as a traefik middleware on my cluster, so I can use an AWS cognito pool for authentication without having to actually deploy my application to the cloud - instead able to run my cluster on a few raspberry pis.

## Your Environment

a K3S cluster running on a trio of raspberry pi 4s - I'm using the new manifest images rather than the old specific-arch tagged ones.

- Version used:
Bug in v7.3.0, working fine in v.7.2.1

**Comment by pa5446530a** [comment]
I am running into the same issue, though downgrading to 7.2.1 or lower does not help in my case.

**Comment by JoelSpeed** [comment]
This looks like an interesting bug, have you tried setting the cookie expire to say 2 hours instead and seeing how that works? What time is your browser seeing vs the server?

**Comment by LeeMartin77** [comment]
So I checked out the server/client(s) time - they're all the same, synced to UTC with the timezone as BST, meaning +0100 right now for it being summer.

Tried setting `--cookie-expire=2h0m0s`, issue persisted.
Tried setting `--cookie-expire=24h0m0s`, issue persisted.

Checked out the docs - I'm using OIDC, so I can set a `--cookie-refresh`, which was unset before now, which the docs imply means it'd be disabled (I actually might enable this on the "live" 7.2.1 version, handy config!)

`--cookie-refresh=2h0m0s` , issue persisted.
`--cookie-refresh=24h0m0s`, issue persisted.

Just for luck I tried `--cookie-expire=48h0m0s --cookie-refresh=24h0m0s` together, still the issue persisted

**Comment by JoelSpeed** [comment]
This is very odd. Are you able to record the requests and responses using your browser developer tools and find the set-cookie header, we should be able to see the expiry from there

**Comment by LeeMartin77** [comment]
Here are the set cookie headers from logging in just now - I dug into it, and what I've noticed is that the inital request seems fine (and lets me load the page), but the next request to be sent has a new set of set-cookie headers set for the past with no actual cookie data. I'm wondering if the proxy is deciding the cookie I'm sending with the request (which looks right, or at least the same as the old v7.2.1 deployment) isn't valid and is then clearing it out?

Feel free to hit https://app.paceme.info  (v7.2.1) and https://app-test.paceme.info (v7.3.0) at your leisure  

### v7.2.1

```
_oauth2_proxy_csrf=; Path=/; Expires=Sat, 10 Sep 2022 09:40:01 GMT; HttpOnly; Secure

_oauth2_proxy_0=[REDACTED]; Path=/; Expires=Sat, 17 Sep 2022 10:40:01 GMT; HttpOnly; Secure

_oauth2_proxy_1=[REDACTED]; Path=/; Expires=Sat, 17 Sep 2022 10:40:01 GMT; HttpOnly; Secure
```

### v7.3.0

```
// initial login

_oauth2_proxy_csrf=; Path=/; Expires=Sat, 10 Sep 2022 09:40:47 GMT; HttpOnly; Secure

_oauth2_proxy_0=[REDACTED]; Path=/; Expires=Mon, 12 Sep 2022 10:40:47 GMT; HttpOnly; Secure

_oauth2_proxy_1=[REDACTED]; Path=/; Expires=Mon, 12 Sep 2022 10:40:47 GMT; HttpOnly; Secure

// On second request

_oauth2_proxy_0=; Path=/; Expires=Sat, 10 Sep 2022 09:40:48 GMT; HttpOnly; Secure

_oauth2_proxy_1=; Path=/; Expires=Sat, 10 Sep 2022 09:40:48 GMT; HttpOnly; Secure
```

**Comment by JoelSpeed** [comment]
Is there anything in the logs about why it's clearing the cookie? It looks like it's loading in, deciding the cookie is invalid and clearing it

**Comment by LeeMartin77** [comment]
Well now I feel like an idiot for missing this:

```
10.42.1.1 - 7106861e-ad1b-4fb3-9f87-84d78ce4b29f - lee@pliminus.co.uk [2022/09/10 10:54:35] [AuthSuccess] Authenticated via OAuth2: Session{email:lee@pliminus.co.uk user: PreferredUsername: token:true id_token:true created:2022-09-10 10:54:35.102058028 +0000 UTC m=+798481.392074608 expires:2022-09-10 11:54:34.869173356 +0000 UTC m=+802081.159189936 refresh_token:true}
[2022/09/10 10:54:35] [session_store.go:163] WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.
10.42.1.1 - 7106861e-ad1b-4fb3-9f87-84d78ce4b29f - - [2022/09/10 10:54:34] app-test.paceme.info GET - "/oauth2/callback?code=1e7c3bac-6b79-4f3b-aea6-f2e00ae076f7&state=vgc7MmcKWyE7LuAAbMcj3d53Le1JGX0QPZT6k58eKyM%3A%2F" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0" 302 24 0.619
```

Is there a reason this would have changed between v7.2.1 and v7.3.0?

**Comment by JoelSpeed** [comment]
I don't think it should have changed but tbh I don't really remember what the differences were there. I'd be interested to see if you switch to redis storage if that helps resolve the issue

I want to deprecate the split cookies eventually as they have been nothing but trouble

**Comment by LeeMartin77** [comment]
I'll try that out tonight for you and report back :smile:

**Comment by LeeMartin77** [comment]
Reporting back on switching to redis storage - works a treat in v7.2.1 (in fact, going to leave it enabled), however the issue of the cookie being immediately expired persists in v7.3.0. I can see that in both cases I only have the one cookie being set now.
