### ISSUE TITLE
how to the get the public key for validating the JWT?

### ISSUE THREAD

**Issue by odin-delrio** [oauth2-proxy/oauth2-proxy#1747]
Hello! I can see that with the `--pass-access-token` option I can forward the JWT to the upstream service.

What I would like to do, is to validate that JWT in the upstream service, for doing that, I need access to the public key there. So, my question is, is there a way to obtain the correspondent public key to the private one used to sign the JWT from the upstream service?

To give you context about my mental path, I'm used to use firebase as auth mechanism, and they expose the public keys in endpoints, for example: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
This way, the receivers of the JWT can fetch the public keys and use them to validate the tokens.

**Comment by hevans-dglcom** [comment]
Hi, the access tokens passed upstream by Oauth proxy are actually from the provider you are using.

So for example, if you use the azure provider, you would use the public jwt endpoint for your tenant.

```
https://login.microsoftonline.com/{{ tenant_id }}/discovery/keys
```

**Comment by hevans-dglcom** [comment]
You can see as an example the jwt keys from the common endpoint.

[https://login.microsoftonline.com/common/discovery/keys](url)
