### ISSUE TITLE
Can you configure to start authentication in a new tab once clicked "Sign In with Azure"?

### ISSUE THREAD

**Issue by jenswachtel** [oauth2-proxy/oauth2-proxy#1748]
Is it possible to configure, let's say the azure provider that a click on the SSO login button will actually open a new browser tab?

In my case, the oauth2-proxy login page is loaded in an iframe, thus the connection gets denied via a classic
`Refused to display 'https://login.microsoftonline.com/' in a frame because it set 'X-Frame-Options' to 'deny'.`

I was hoping to solve this via an external page load to execute login rather than redirect within the iframe

**Comment by JoelSpeed** [comment]
If you change the HTML that is served I think you could achieve this, have a look at the templates notes within the docs
