### ISSUE TITLE
Application doing AJAX requests gets 401 error after some time even though the cookie expires in one week

### ISSUE THREAD

**Issue by SSchwaiger** [oauth2-proxy/oauth2-proxy#1755]
We have put a Docker container serving static HTML/JS files and another Docker container serving a REST API behind OAuth Proxy. When we access the HTML pages, we get redirected to Keycloak, sign in and can now correctly access the app and the API. But after some time without reloading the page, when making an AJAX request the API (or better: OAuth Proxy) returns 401.

So my question is: what timeout must I check to fix this issue? And: does OAuth Proxy never refresh the Bearer token when it expires?

**Comment by JoelSpeed** [comment]
You should set the cookie-refresh to make sure that the token gets refreshed. Also check in the authentication logs that you are getting a refresh token, if that's not present, you won't get a refreshed token. 

Else, this will happen once your ID Token expires, so, this is configured in Keycloak.

**Comment by SSchwaiger** [comment]
Hmm, yes we're about to homogenize the settings, thanks a lot!
