### ISSUE TITLE
Configuration for upstream file start path

### ISSUE THREAD

**Issue by darox** [oauth2-proxy/oauth2-proxy#1757]
I'm having issues to serve a react application from file upstream. Index.html is loading but for some reason the JS files are not found. Therefore I'd like to configure the start path from /var/www/static to / However, I can't find an example on how to configure the path remapping. My files are all placed in /var/www/static and I'd like to access them via /. Thank you.

**Comment by JoelSpeed** [comment]
You might want to take a look at this PR which implemented rewriteTarget, but only via the alpha config, https://github.com/oauth2-proxy/oauth2-proxy/pull/1060
