### ISSUE TITLE
Configure "privateJwk" as client secret (RsaPrivateKeyJwtSecret)

### ISSUE THREAD

**Issue by Richard87** [oauth2-proxy/oauth2-proxy#1763]
When authenticating with the norwegian health department, they provide a RSA Private key in the format of a JWK to be used as `client_secret`

I tried to add the json encoded jwk as `clientSecret` and was not suprised when it failed. 

Can a jwk client secret be used? If so how?

## Expected Behavior

Documentation for using a jwk as client secret, alternative how to specify a RSA Private key as client secret

## Current Behavior

invalid_client error message when callback is triggered with auth code.

## Steps to Reproduce (for bugs)

An example private JWK I'm expected to use:
```json
{
    "d": "FeSca0VbvpQrOG8CNbGY-RzUwaUKIcE76rdkAMZCmq1C-qARL9-QJnX5CeaRwvt0uAn1MIo6f6quvcUZBKpxJX7BHVBT6XhzlwaAnQEIgfxyi1qmDQoxXO4Gh4-VASR06duheTuZ3uypbkGqio6kOdiX0xSUytDDgeQ5rpPoYyJK6I0OfYMx0kxPxSPqAk66AQimIK-WMgsfHaumsVrhV8lBiPoupNMo1ITtTlifFwCc8PbKHZceG7mx2tpTSy_myVGr2MgNZ8DB59LY209-rcB61Mz3C-PC8U3j-QqxG-QdUn9PBVphZnH9JoJx1ByQrVxLDPJps4BdbFIIXc7RSZpmBnfgLJqUcv8KUjCo2cazQB9UHzR3AhBC5nrH5_2fEPC67fx3Zk7LZ63E2cV8Fpj1nH5BLcT9g9rHWcW_THK3X_dyy0nGWlpA1i4yEgnm6fLbiqiKfFtTj89IE8Tehjz8YprAjsgr58zvGD9C7kNnLGE_WrCq2itmNSHvUsWihguI5qOZBxs9A7Kb4HLj6qKDwtrSMk6ekX6FMycwO--9_jKrEiiNk_noVGz85YkUDZ4dN-6A9Co5PZGgAGw0Qui8BGiZzokRkOoEzh0teg9eb8viyYC5mZcqHO2c8bdBZoufSu3CbPWXJliDtQAI6hDmVwrFRCgPpzCBP9gS2TE",
    "dp": "gYxWHUqO-eZLTp8X_p8vuC0tf4vkSV9EDmaCKQJZiW5fFrd0aZcqx4tyWwAhD_JXtHAbe9QHsTT77dUUEkvy5NlY6AD4r0BrptyOFm4zOwmYFa8yQ8R2c3eMoc6WyRJMTohkEgF_84BIJSBM4Tt2KBygrXlCv5KU-rNqn8_2djLr9j9XFpMSnnEOtltMhPSUONuEIBkr6oSbNo4b8kGsD0OGr5NkscizABJObcXelPcnFYs9bwpN29OGUj5xxzocUbG6sYlWvlDnZoHLudg_C2yuHd_0lLc2aZAJ99snClh4tC4gMUV5fN5LrHyOKVg0gt771uupjFkM8TcCdaseRw",
    "dq": "UDq7otYQ3GJxsiAi_UaDiZz9Ot4xKhxI3CGqAal9TtCiMdT_vZADEY5BdYlDk-5ZM6b8M8I4xKbzAHLDbCmpgZ6XPmFnffy6mXEcFSuyuV2jWToxIXTCDsH8RkZYH5gGYJZ_Zrh4ei7d8hjER8NF_HVOJGiZ-3DKnhEKlTkMcVbR31GC3unZ50xAI3kuQfauXq9dE_SOoVFqWu0x4ycgtyBljhqaTRVuDQ6Fs-VZyBzgm7OSVjeZk1kDeL97AEVWexkJSNeVdx9aiqIw_QAmyGCPHHo2w6PFwFWg9dJcHPxr7ui6IEgJFiTC7Z5M6uamRUwtqiekXBbrZ4aeF2MKAQ",
    "e": "AQAB",
    "kty": "RSA",
    "n": "wX_-VrfYFl5z0PxCT77FgVth0xxn8k5tt656SrhotgJV9l6Fm7KHD6TWdmfoTPZ-03O8APJUX-GQOZTc4VuoB3QyRSsGhKf23hDEOIoDNiIPQMZbnhi7yJn2CunjpVHcGvKvWIYQCZ3BVcMx9v7RlMt6CIHO4pqucOLhiuDbix-FvjHjtZ-D5qndCsuYx3CGxputUzqeYtrbZZA4yw8cgXzrz6fhTtAaOkTntEAglAgB_OIsaWlkqxjgtIA6vnqhaQFRUjMaVechZ8W-9gjWgosEJxMn58qnV9Mpfwn7mdlxgObz-UgUMN2iUUHH84QDy45b8oRSGLjOwc1pHzdzKTCPkWbn6masoLIEpBai1nAC3cLnlDAUa4XevxaoZctGm18gHSU7cPwRFuxxB0I_NsV2C83y_ZjSzn4cDa-ZsaaraomvLBoftR5XTTE3RM2R6Y0M80hcdHOTyUNySg_BmzAg8A8lHr4JVMExexPHuL6LPtSApoGwRb020b9vcjV208yaSeaPfT5eK4OBDS5v4ZQPp8WiLVuARjc9M9UdGmoKY7vcIROKvgPTmn56U--NL1tK4QYtlLXgqp-G4JjVLmzJjWrOXIju3o7yuns3rQVLJVEdGKqK_4j43Oh0UJcsURgWLG-7PVPwuSH_u-Rr4y60EwoL_d8xFLLhPKQkIEM",
    "p": "4OZl_OYTtaGuPNE04p_ulNP3irhvoN6EV1VHQtwtn3mEaWzofxQKiv2Xi1Ma3-1jyrKotEUqcFfdrb_77U-ZlLxCme8le0xC948HxXBX1uk6s1wjCeKf_zoYizpX5YiCejeHeOaFv0R7Uf7Vasz3fJIS9g0rtgMARe5kJ3wNQHA0QDo_JYyM0RQBfOeIRYCBpADf6kgVx4P39xyngAHxC_5G931y3MtVy4_9gUl9uUh1UiFX6FhaQnq9-5H7D53UxlpJ3skYCYuvhAveaqtXfyBx_z2xPy4ExAXNNSAWmvnbQ3IHmsDWaaoVu4Yy96ecomv2dwIO0u3ND5OGRGEpaw",
    "q": "3EIDv6zSjp6xSwA594XXrf1T_NzIfx1fUXFPTnNKuiTmoeD153YOFiXzr9CR0H4U9FWeJFvCTeUkzD5_TVokJzUdIuyArgd4WFGPgnxPUziWNSn6HprN75JOVHJBm6BSR7AK848XMSaxbQbClFPhHMZ2UvJBlmvRfTVIeYTSeHxCd8zkYUBwDiK9QHFvIgax_OMg-rLQ4MXJkcD-zXrk3xF3O7ZPWmuzgE5xRRgrCjHaLCQuxnSAdeeJdLUPGLYe468PdmaWdp1bu1UOv1Nt5173C8R-8o7bU1bVkg07iCfnEhDpcqPKGpJ032miwhjkVPWQthrsIvO5-lwHL15iiQ",
    "qi": "OihyUndzfI5zFLnXgUguhYlqxyGODczGhSIN3WZRr522vmtnT5jPq-AICTe7H8jQQhXGmYtJ3ftH2RIRzNOfThtCr0s8gvKWgNUoGrNvguX_39Rf8AyzGSQVy_UIh6zOyP5W0WC78k6yO0Kr1agNatcjEvOb4TMzDzZpZhewKwssLoTE7AnDJiwBweiHs9HNQnj4trz26qLefX7Ce3LqTDq27Qj5adf6M_LttMF-4G8ubeugVeVN6smy0rD3j00958M_MDvW1qw6v_QG1OeCL-LpCm4QB32qWjGPxNythq2H7IlpJRbG5T5NEt41TGUdyIJ8utl9A8gG4hWHzqXYxA"
}
```

## Your Environment

- Version used: 7.3.0 (using helm chart 6.2.2)
- Running on GKE v1.21.13
Config:
```
config:
  annotations: {}
  clientID: c0...59
  clientSecret: '{"d":"asdjklasjkd"...}'
  configFile: |-
    provider_display_name = "HelseID"
    provider = "oidc"
    skip_provider_button = "true"
    oidc_issuer_url = "https://helseid-sts.test.nhn.no"
    pass_access_token = "true"
    email_domains = "*"
    cookie_samesite = "lax"
  cookieName: ""
  cookieSecret: SD...SDA=
  google: {}
customLabels: {}
deploymentAnnotations: {}
extraArgs:
  code-challenge-method: S256
  scope: openid profile helseid://scopes/identity/pid helseid://scopes/hpr/hpr_number
  show-debug-on-error: true
```

**Comment by JoelSpeed** [comment]
I've not seen a JWK being used as a client secret for any of our providers so far, so I wouldn't expect this to work. Do you know how common this is? Normally the data is encoded in a way that it seems opaque (base64?) to the proxy. Have you tried base64 encoding this key?

**Comment by Richard87** [comment]
It seems to be popular in the auth-scene in Norway/Scandinavia. I see BankID is also using it (the de-facto standard way of authenticating between individuals and governemnt entities, banks and many more).

They have written a section about it here:
https://confluence.bankidnorge.no/confluence/pdoidcl/technical-documentation/core-concepts/client-authentication

(I'm still searching for any reasoning behind the dessicion, would be very interresting to hear!)

**Comment by Richard87** [comment]
So, after studying the topic some more, apparantly they want us to construct a access token (JWT), and sign it with my JWK (RSA key above).

For HelseID Provider, they write about requirements here: https://helseid.atlassian.net/wiki/spaces/HELSEID/pages/128352260/Security+profile+for+clients+using+HelseID

https://www.rfc-editor.org/rfc/rfc7521#section-4.2
https://www.rfc-editor.org/rfc/rfc7523#page-5

Some more information about client generated JWT (using JWK) here: https://kb.authlete.com/en/s/oauth-and-openid-connect/a/client-auth-private-key-jwt

**Comment by JoelSpeed** [comment]
This isn't an area I have expertise in so I doubt I'll be much help, where did you get to with this? Did you make any progress?

**Comment by Richard87** [comment]
I have made some progress, but not finished yet. 

The basic flow
- Generate private/public key pair
- Create a JWK from your public key and upload to authentication server
- On authentication:
   - Follow regular PKCE steps
   - When fetching access token authenticate with client_assertion and `client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer`
   - The client_assertion should be set to a special JWT signed with your private key

More information: https://curity.io/resources/learn/client-assertions-jwks-uri/
