### ISSUE TITLE
Parse SAML group mapping claim from Cognito as array, not string

### ISSUE THREAD

**Issue by therc** [oauth2-proxy/oauth2-proxy#1765]
## Steps to Reproduce (for bugs)

Set up SAML IdP Group Mappings with Cognito, as described at https://medium.com/geekculture/using-saml-idp-group-mappings-with-aws-cognito-34e297cf1aa8

Set up oauth2-proxy to talk to the Cognito user pool's app with the OIDC provider and restrict access only to users in group test-group-one

Log in as a some user that is in N groups, including test-group-one

## Expected Behavior

The user is authorized.

## Current Behavior

As seen at the end of the article, the claim in Cognito's JWT for federated groups looks like
`"custom:groups": "[test-group-two, test-group-one]"` (a string representing an array, not an actual array)

The authorization check will thus fail.

## Possible Solution

Two options:

1. Add a `--cognito-stupid-group-mapping` flag that parses the string and replaces it with an array
2. Automatically detect the "[X]" format for the groups claim and perform the replacement on the fly

## Context

I filed a support case with AWS, but I doubt they'll fix this. In a blog post of theirs, they describe using a Lambda function to rewrite the JWT on the fly (!).

## Your Environment

- Version used: master

**Comment by JoelSpeed** [comment]
Do you have an example of the ID Token payload that you are getting? In theory we could improve our claim coercion logic to recognise a list in a string without any need for additional options.

**Comment by JoelSpeed** [comment]
I expect the code is ending up here somewhere, https://github.com/oauth2-proxy/oauth2-proxy/blob/b82593b9cca1f030fa6b272ecb4dc56dae4aa9a0/pkg/providers/util/claim_extractor.go#L176-L196

Do you have logs that explain why the user isn't authorized?

**Comment by therc** [comment]
That is indeed the code that I had tweaked in the custom build we have been running. This is the diff (modulo tests):

```diff
diff --git a/pkg/providers/util/claim_extractor.go b/pkg/providers/util/claim_extractor.go
index 883cc64f..db00b544 100644
--- a/pkg/providers/util/claim_extractor.go
+++ b/pkg/providers/util/claim_extractor.go
@@ -178,6 +178,18 @@ func toStringSlice(value interface{}) ([]string, error) {
        switch v := value.(type) {
        case []interface{}:
                sliceValues = v
+       // Detect array passed as a single string, e.g. when federating
+       // users and groups in Cognito. See
+       // https://github.com/oauth2-proxy/oauth2-proxy/issues/1765
+       case string:
+               s := value.(string)
+               if strings.HasPrefix(s, "[") && strings.HasSuffix(s, "]") {
+                       l := strings.Split(s[1:len(s)-1], ", ")
+                       return l, nil
+
+               } else {
+                       sliceValues = []interface{}{v}
+               }
        case interface{}:
                sliceValues = []interface{}{v}
        default:
```

That also hardcodes ", " (comma space) as the separator. Personally, I like that there's no new option, but I'm also wondering if any directories out there might be have user fields like "[HUMAN RESOURCES]" that might trigger a false positive. Should I submit the PR?

**Comment by therc** [comment]
Also: AWS is aware of the issue and our support case has been added to an existing feature request, but there's no timeline yet when it will be addressed.

**Comment by JoelSpeed** [comment]
>  but I'm also wondering if any directories out there might be have user fields like "[HUMAN RESOURCES]" that might trigger a false positive

I have absolutely no idea, they very well could do. Makes me hesitant to say we should be doing this tbh, I just know as soon as we merge it, someone will come and complain we broke their groupings
