### ISSUE TITLE
request to /somepath is not routed to /somepath/ in upstream

### ISSUE THREAD

**Issue by osimosu** [oauth2-proxy/oauth2-proxy#1770]
oauth2-proxy doesn't route client request from https://myapp.com/somepath to http://localhost:8080/somepath/.   Note the trailing slash. 

We get a 404 page not found response.

 http://localhost:8080/somepath/ is a configured upstream endpoint.

## Expected Behavior

https://myapp.com/somepath should route to http://localhost:8080/somepath/

## Current Behavior

https://myapp.com/somepath doesn't route to http://localhost:8080/somepath/

We get a 404 page not found response.

## Your Environment

- Version used:

v7.3.0

**Comment by osimosu** [comment]
A workaround is basically including both http://localhost:8080/somepath/ and http://localhost:8080/somepath in the upstream.

**Comment by lknite** [comment]
Post your oauth2-proxy config & the ingress you have configured for your target app.

**Comment by osimosu** [comment]
My set up is a bit complicated but this should be easy to reproduce.

Send a client request to https://myapp.com/somepath but have http://localhost:8080/somepath/ in the upstream. Note the trailing slash which i expect to be insignificant... oauth2-proxy returns a 404 page not found.

OAUTH2_PROXY_UPSTREAMS: http://localhost:8080/somepath/

**Comment by JoelSpeed** [comment]
Have you tried changing your config to remove the trailing slash? Does that make a difference?

Note that I know other proxies (eg nginx) have semantic differences between a path with and without a trailing slash, so if this is a difference of behaviour we aren't the only people doing it, it will depend on the underlying mux implementation
