### ISSUE TITLE
Private Gitlab-instance stuck in a loop trying to redirect to secured app after successful login

### ISSUE THREAD

**Issue by davidberglund** [oauth2-proxy/oauth2-proxy#1772]
I think I've gone through every piece of documentation and issue on how to set this up on K8s with nginx ingress and using a private Gitlab-instance as IdP (which in turn uses OmniAuth/Azure AD). This is the first time I'm trying to set up OAuth2-Proxy btw but I've spend a few days on this now actually and gotten closer and closer so here's hoping some help can get me all the way there. <3

Nginx/OAuth2-Proxy correctly initiates login flow on gitlab.mydomain.tld and after successful authentication Gitlab gets stuck in a loop going through a bunch of callback-URI's. See detailed description below. 

## Expected Behavior

After successful authentication with Gitlab provider user is redirected to the secured app in kubernetes, as configured in ingress manifest.

## Current Behavior

User is correctly redirected to gitlab.mydomain.tld and login flow is successfully completed until Gitlab gets stuck in a loop trying to redirect to:
https://oauth2proxy.mydomain.tld/oauth2/callback?code=bLARGH123rU%3Ahttp%3A%2F%2Fmysecuredapp.mydomain.tld%2F
then
https://oauth2proxy.mydomain.tld/oauth2/callback?code=928gsgorU%3Ahttp%3A%2F%2Fmysecuredapp.mydomain.tld%2F
then
https://oauth2proxy.mydomain.tld/oauth2/callback?code=adjog9312oogsgorU%3Ahttp%3A%2F%2Fmysecuredapp.mydomain.tld%2F
and so on

Issuing a new code over and over and from that producing new redirect URI's.

Does the issue lie in the oauth2/start rd-parameter I'm using? See below. I've tried some different variants of it but.
Are those $variables actual variables that can be picked up or just placeholder values that you're suppose to replace with hard coded URL's?

## Your Environment

Kubernetes 2.21
ingress-nginx/controller:v1.3.0
oauth2-proxy:v7.3.0-amd64 (when using v7.2.1-amd64 image, the "mysecureapp.mydomain.tld" URI is lost and I get redirected to oauth2proxy.mydomain.tld resulting in a 404 with ingress-nginx)

Annotations for secured app ingress:
nginx.ingress.kubernetes.io/auth-url: "https://oauth2proxy.mydomain.tld/oauth2/auth"
nginx.ingress.kubernetes.io/auth-signin: "https://oauth2proxy.mydomain.tld/oauth2/start?rd=http://$host$request_uri" 

OAuth2-Proxy Deployment:
        containers:
        - args:
          - --provider=gitlab
          - --gitlab-group="mygroup"
          - --upstream=file:///dev/null
          - --http-address=0.0.0.0:4180
          - --session-store-type=redis
          - --redis-password=[REDACTED]
          - --redis-connection-url=redis://[REDACTED]:PORT
          - --whitelist-domain=*.mydomain.tld:*
          - --ssl-insecure-skip-verify
          - --ssl-upstream-insecure-skip-verify
          - --email-domain="*"
          - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
          - name: OAUTH2_PROXY_CLIENT_ID
            value: "[REDACTED]"
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: "[REDACTED]"
          - name: OAUTH2_PROXY_OIDC_ISSUER_URL
           value: "https://gitlab.mydomain.tld"
         - name: OAUTH2_PROXY_COOKIE_SECRET
           value: "[REDACTED]"
         - name: OAUTH2_PROXY_REDIRECT_URL
           value: "https://oauth2proxy.mydomain.tld/oauth2/callback"
         - name: OAUTH2_PROXY_REVERSE_PROXY
           value: "true"
         - name: OAUTH2_PROXY_EMAIL_DOMAINS
           value: "mydomain.tld"
         - name: OAUTH2_PROXY_COOKIE_DOMAIN
           value: "mydomain.tld"

- Version used:
v7.3.0

**Comment by lknite** [comment]
Not official support, but just happened to come across your ticket.  Have you tried:
```
nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.vc-prod.k.home.net/oauth2/start?rd=$escaped_request_uri"
```

**Comment by JoelSpeed** [comment]
```
- name: OAUTH2_PROXY_COOKIE_DOMAIN
value: "mydomain.tld"
```
I suspect that your issue is that your cookie isn't being set correctly, try using `.mydomain.tld` instead. The leading period means it can be accessed by subdomains as well as the root domain. If you application is being hosted on a subdomain (which it looks like it is) then this is required.

As a note, cookie domain and whitelist domain are normally the same value
