### ISSUE TITLE
Add option to use final IP in x-forwarded-for header

### ISSUE THREAD

**Issue by alasdairnicol** [oauth2-proxy/oauth2-proxy#1778]
When parsing a list of IPs in the x-forwarded-for header, oauth2-proxy is using the first IP in the list, e.g. in [this test case](https://github.com/oauth2-proxy/oauth2-proxy/blob/42475c28f7f235c08777a24027fe8ec170763482/pkg/ip/realclientip_test.go#L66), for the string `"192.168.10.50, 10.0.0.1, 1.2.3.4"` it returns `192.168.10.50`.

However, in our set up, we want to use the right-most IP, because we can only trust the IP set by the final proxy.

## Expected Behavior
For an x-forwarded-for header of "192.168.10.50, 10.0.0.1, 1.2.3.4", add an option so that the real IP is `1.2.3.4`

## Current Behavior

For an x-forwarded-for header of "192.168.10.50, 10.0.0.1, 1.2.3.4", the real IP is 192.168.10.50. That means that malicious users can spoof the IP in the header e.g. with `curl -H 'X-Forwarded-For:192.168.10.50' example.com`

## Possible Solution
We could add a new option to oauth2-proxy, which causes it to use the right-most IP.

Alternatively, (and more complex), could implement something like the [realip module](http://nginx.org/en/docs/http/ngx_http_realip_module.html) in nginx. This lets you provide a list of trusted IPs, which are removed from the end of the list, so it ends up using the final untrusted IP in the list.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Context

I am using oauth2-proxy behind an AWS application load balancer. It has three modes for handling x-forwarded-for headers ([docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html)), but none of them are suitable for working with Oauth2 proxy,

Consider a request from 1.2.3.4, where the user has spoofed X-Forwarded-For 5.6.7.8 (where 5.6.7.8 is a trusted IP)

In **append mode**, the ELB will pass 5.6.7.8,1.2.3.4, and Oauth2-proxy will currently use 5.6.7.8 and trust the request when we don't want it to be trusted
In 
In **replace** mode, the ELB will pass 5.6.7.8 and Oauth2-proxy will currently use 5.6.7.8 and trust the request when we don't want it to be trusted
In **remove** mode, the ELB won't pass an X-Forwarded-For header, so the --trusted-ip option in Oauth2-proxy won't work at all

ELB and Oauth2-proxy would work if ELB had a **replace** mode, but unfortunately this doesn't exist. Therefore I've created this issue to see if there's any appetite to address it in Oauth2-proxy. 

## Your Environment

Oauth2-proxy running as a sidecar container on AWS ECS, behind an application load balancer.

- Version used: v7.3.0

**Comment by JoelSpeed** [comment]
Perhaps take a read through https://github.com/oauth2-proxy/oauth2-proxy/issues/1675, I think it might be the same issue
