### ISSUE TITLE
Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401 Unauthorized

### ISSUE THREAD

**Issue by ferhatys** [oauth2-proxy/oauth2-proxy#1782]
I've configured `oauth2-proxy` version `7.3.0` to use PKCE with the `--code-challenge-method` flag to fetch the token without a client secret. I'm using Ping Federate as my identity provider. However, I keep getting the following error back from Ping Federate.

```
[oauthproxy.go:768] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error_description":"Invalid client or client credentials.","error":"invalid_client"}
```
Ping Federate states that you will also get this error if you send a client secret in your request even if it's empty. 

I'm using the following flags.

```
        - --http-address=0.0.0.0:4180
        - --metrics-address=0.0.0.0:44180
        - --code-challenge-method=S256
        - --cookie-domain=.xxx
        - --email-domain=*
        - --oidc-issuer-url=xxx
        - --pass-user-headers=true
        - --profile-url=https://xxx/idp/userinfo.openid
        - --provider=oidc
        - --reverse-proxy=true
        - --redirect-url=https://xxx/oauth2/callback
        - --client-id=xxx
        - --redeem-url=https://xxx/as/token.oauth2
        - --provider-display-name=PingID
        - --redis-connection-url=redis://oauth2-proxy-oauth-ping-redis-master
        - --scope=openid email profile
        - --session-store-type=redis
        - --set-xauthrequest=true
        - --whitelist-domain=.xxx
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
```

I've already tested the Client ID and the PKCE request in Postman manually and that works. So the Client ID is a valid Client ID. 

I do have to specify a client secret as an environment variable even if I'm not using it. The `oauth2-proxy` won't start if I don't specify a Client Secret using `OAUTH2_PROXY_CLIENT_SECRET`.

## Expected Behavior

I'm expecting the PKCE flow to work. 

## Current Behavior

Getting an error in the logs:

```
[oauthproxy.go:768] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error_description":"Invalid client or client credentials.","error":"invalid_client"}
```

## Possible Solution

Can you check whether the Client Secret is not sent within the token request at https://github.com/oauth2-proxy/oauth2-proxy/blob/037cb041d3e72e91aa4a845e660192ce5c1741e0/providers/oidc.go#L57 ?

## Steps to Reproduce (for bugs)

1.  Create an application in Ping Federate
2.  Deploy `oauth2-proxy` with a Helm chart using the above flags
3.  Configure Ingress to use `oauth2-proxy` instance with annotations
4.  Browse to the Ingress URL

## Context

Trying to get PKCE to work with `oauth2-proxy`.

## Your Environment

Dev environment on AWS

- Version used: 7.3.0

**Comment by JoelSpeed** [comment]
@braunsonm Maybe you can help here? I think you know this area better than I do

**Comment by braunsonm** [comment]
OAuth Proxy does not support public clients (those without client secrets). Although some providers treat PKCE as a replacement for client secrets it really is not the same thing.

There is already an issue here for supporting public clients so I encourage you to follow along on that one for updates https://github.com/oauth2-proxy/oauth2-proxy/issues/1714
