### ISSUE TITLE
[oauthproxy.go:768] Error redeeming code during OAuth2 callback: could not verify id_token: failed to verify token: failed to verify signature: failed to verify id token signature

### ISSUE THREAD

**Issue by ramkrivas** [oauth2-proxy/oauth2-proxy#1794]
## Current Behavior

We are using Oauth2 proxy to authenticate with auth0/OIDC provider and below is configuration setup.

- args:
        - --provider=oidc
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=http://0.0.0.0:4180
        - --proxy-prefix=/oauth2
        - --whitelist-domain=.cloudapp.azure.com
        - --cookie-domain=.westeurope.cloudapp.azure.com
        - --pass-access-token=true
        - --set-xauthrequest=true
        - --cookie-expire=0h15m0s
        - --cookie-secure=true
        - --redeem-url=https://<<auth0.com>>/oauth/token
        - --login-url=https://<<auth0.com>>/authorize
        - --oidc-issuer-url=https://<<auth0.com>>/
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: <<CLIENT_ID>>
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: <<CLIENT_SECRET>>

With above configuration when the user is login, we are getting 500 internal server error and below is the logs from Oauth2proxy container.

### ` [oauthproxy.go:768] Error redeeming code during OAuth2 callback: could not verify id_token: failed to verify token: failed to verify signature: failed to verify id token signature`

Below is the screenshot from browser network trace:
![image](https://user-images.githubusercontent.com/71707/190634551-c635bece-fc6b-494b-9c81-d7c8f075d36a.png)

- Version used:
Version: 7.3.x

**Comment by ramkrivas** [comment]
I verified the issue again. The problem was with our configuration. Sorry for the confusion, you can close the issue.

**Comment by C-Duv** [comment]
I have [a the same issue](https://stackoverflow.com/questions/75897820/oauth2-proxy-with-openid-connect-provider-provider-fails-with-error-redeeming-c) where I get a _500 Internal Server Error_ page with "Error redeeming code during OAuth2 callback: could not verify id_token: failed to verify token: failed to verify signature: failed to verify id token signature" when using the authorization server [LemonLDAP::NG](https://lemonldap-ng.org) as an OpenID Connect Provider.

Do you remember which configuration parameter/option was faulty?
