### ISSUE TITLE
SP-API auth code 

### ISSUE THREAD

**Issue by sofian-ysf** [oauth2-proxy/oauth2-proxy#1797]
I am attempting to implement the Amazon Selling Partner API website authorisation workflow using a ReactJS website (of which I am very new to). The documentation (https://developer-docs.amazon.com/sp-api/docs/website-authorization-workflow) has seemed fairly straightforward up till step 3. 

## Expected Behavior

In Step 3 of the instructions (https://developer-docs.amazon.com/sp-api/docs/website-authorization-workflow), my 
 application should receive query parameter: (selling_partner_id), when redirecting in the url and thus be available to use in a subsequent HTTP post request to exchange for a token.

## Current Behavior

The parameter is present in the url as a query parameter but then I am redirected back to my website without this parameter visible in the url. 

Inspecting chrome dev tools network tab I am able to see the url with the necessary query parameters. 

I need to use this parameter when making the subsequent HTTP post request to exchange it for a token to make calls to the API, but I am struggling to figure out how to retrieve it. 

## Possible Solution

I have attempted several different solutions:
1. Implementing the LWA javascript SDK (https://developer.amazon.com/docs/login-with-amazon/install-sdk-javascript.html)
    ---> The documentation is for an html website .
    ----> The first script mentioned in Step 3, I have incorporated in my index.html
    ----> For subsequent scripts, I have created React class components using componentDidMount and Render function
    ----> I thought perhaps the options object within the script would save the auth code in state, as the documentation suggests, but I haven't managed to retrieve it
2. I have tried to retrieve the query parameter from the network tab programmatically as seen in this thread (https://stackoverflow.com/questions/45649634/how-to-capture-query-string-parameters-from-network-tab-programmatically)
3. I've also tried some more simple solutions like using document.referrer to retrieve the previous page url, but this only retrieves the domain and not the query parameters. Using pageinit to retrieve the query parameter in the url.

## Context

Implement the SP-API website workflow to make calls to the SP-API. (Exchange SP-API auth code for token to make POST calls)

## Your Environment

ReactJS

- Version used:

**Comment by JoelSpeed** [comment]
Please provide details about how you've set up OAuth2 Proxy. Is it directly fronting your application or do you have something like NGINX in front of your project, with OAuth2 Proxy as an auth_request module. Depending on which of these you have, depends how you can inject the redirect
