### ISSUE TITLE
Question: How to support session freshness with only manual end user auth calls and no autologin?

### ISSUE THREAD

**Issue by krodyrobi** [oauth2-proxy/oauth2-proxy#1798]
Disclaimer:  I am very new to k8s, as such I apologies for the vague / probably misused terms used hereafter.

Can we configure oauth2-proxy to only trigger the auth flow when a user lands on the `/oauth2/start` endpoint, but still have sessions "if existing" be refreshed / validated, for all requests?

Use case:
 - A frontend may or may not need users authenticated
 - Several backends have public endpoints or payloads based on a principal existing in the first place.
 - If a user didn't login it is fine for endpoints requiring auth to fail with 401 / 403, be them ajax or otherwise.
 
If I read the docs correctly, I can control which services / request combos need auth by passing CUSTOM and oauth2-proxy in the `AuthenticationPolicy` but I cannot have a request of a service both authorized and public, and for those that are not authorized no cookie refresh happens as the lib is not called at all.

Have I missed something? can this use case be achieved?
If not, Is there in k8s / istio land some sort of package / tools that exist to allow such a use case, or documentation on how to write a custom provider ourselves? I find the docs quite lacking in this regard.

Thank you! for your time and patience :)

**Comment by t-katsumura** [comment]
@krodyrobi 
Sorry if I misunderstood your question.
You can possibly use `--force-json-errors` and `--skip-auth-route`

- `--skip-auth-route` can define which urls require authentication
-  `--force-json-errors` does not redirect users to `/oauth2/sign_in` even they don't have any valid session. 401 error is returned instead. Sessions are refreshed or validated if requests have any.
- You can trigger auth flow with `/oauth2/start` endpoint

**Comment by krodyrobi** [comment]
Sounds like what I need, thank you
