### ISSUE TITLE
OAuth2/OIDC Client Authentication: Send as Basic Auth Header

### ISSUE THREAD

**Issue by jbolus-nifc** [oauth2-proxy/oauth2-proxy#1799]
## [Basic auth pattern](https://datatracker.ietf.org/doc/html/rfc2617) of instead providing client credentials in the authorization header, per [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1)

I used https://oauthdebugger.com and Postman to narrow down my specific issue to our partner's provider OAuth2 implementation. Which seems to only issue access tokens if the client credentials are sent as: `Authorization: Basic <credentials>` 

With `<credentials>` being in the form of a base64 string.

E.g.  `echo -n $client_id:$client_secret | base64`

## Current Behavior

Although the logs shows that an authorization code is successfully being passed. This results in a 401 error while requesting the `--redeem-url`  `(/oauth/token)` endpoint. 

~Which leads me to believe that their implementation is not up to spec?~ [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1) I've tried other middleware projects with the same result. But I want to stick to oauth2-proxy because it's the most elegant solution. 

```
sso-oauth2-proxy-1  | 192.168.48.5:38862 - 309a5109-fc4e-4397-afaf-e5ba23a849ba - - [2022/09/20 22:43:28] sso.site.com GET - "/oauth2/start" 
sso-oauth2-proxy-1  | [oauthproxy.go:768] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401 
sso-oauth2-proxy-1  | Response: {"timestamp":"2022-09-20T22:43:45.175+00:00","status":401,"error":"Unauthorized","path":"/oauth/token"}
sso-oauth2-proxy-1  | 192.168.48.5:34574 - 252c0300-5db1-4de8-beac-2305b6cb474c - - [2022/09/20 22:43:44] sso.site.com GET - "/oauth2/callback?code=nENLTn&state=PC8ReJ-K_Euh..."
```

## Possible Solution

Edit: Perhaps appending something like

```go
EncodedAuth := base64.StdEncoding.EncodeToString([]byte(p.ClientID + ":" + clientSecret))
SetHeader("Authorization", "Basic "+EncodedAuth).
```
To `provider_default.go`: https://github.com/oauth2-proxy/oauth2-proxy/blob/ce750e9b301ac66b3b8cbdbd0bc8ac7415bfed79/providers/provider_default.go#L67-L72

## Context

> **RFC 6749**
> **[2.3.1.  Client Password](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1)**
> 
> The authorization server **_MUST_** support the HTTP Basic
>    authentication scheme for authenticating clients that were issued a
>    client password.
> 
>    Alternatively, the authorization server **_MAY_** support including the
>    client credentials in the request-body using the following
>    parameters:
> 
>    client_id
>          REQUIRED.  
> 
>    client_secret
>          REQUIRED. 

If there a configuration option that I'm missing? I'm also open to just creating my own custom provider but I don't have much experience with golang. 

Thanks,

## Your Environment

- Version used: oauth2-proxy:7.3.0

**Comment by jbolus-nifc** [comment]
I was able to resolve the issue by adding a new provider using `digitalocean.go` as an example and adding lines 1 and 7 To `/oauth2-proxy/providers/provider_default.go` and rebuilding the docker image.

```go=
1. EncodedAuth := base64.StdEncoding.EncodeToString([]byte(p.ClientID + ":" + clientSecret))
2. result := requests.New(p.RedeemURL.String()).
3. 	WithContext(ctx).
4. 	WithMethod("POST").
5. 	WithBody(bytes.NewBufferString(params.Encode())).
6. 	SetHeader("Content-Type", "application/x-www-form-urlencoded").
7. 	SetHeader("Authorization", "Basic "+EncodedAuth).
8. 	Do()
9. if result.Error() != nil {
10. 	return nil, result.Error()
11. }
```

**Comment by JoelSpeed** [comment]
I don't think this is something we allow to configure right now, but I'm hoping to rewrite our base provider to allow more configuration and customisation like this in the future. Any thoughts how you would integrate this into the existing providers in a configurable way?
