### ISSUE TITLE
Group-based authorization with JWT and Google Workspace

### ISSUE THREAD

**Issue by jwolski2** [oauth2-proxy/oauth2-proxy#1803]
Hi there, my goal is to have an OAuth2 Proxy instance that supports both:
* Authentication and group-based authorization for users
* Authentication for service accounts, ideally with groups too

Is this possible w/ Google as a provider?

## Current Behavior

I've specified `OAUTH2_PROXY_GOOGLE_ADMIN_EMAIL`, `OAUTH2_PROXY_GOOGLE_GROUP` and `OAUTH2_PROXY_GOOGLE_SERVICE_ACCOUNT` with the relevant details. Upon logging in to Google, if my user is part of the Google group, then my request is forwarded to the downstream service. If my user is not part of the group, then I see a fat ol' 403. Great! Works as expected. However, if I now want to let in service accounts through the same OAuth2 Proxy instance as an extra JWT issuer, I see the following error: 

```
[AuthFailure] Invalid authorization via session: removing session Session{email:SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com user:XXX PreferredUsername: token:true id_token:true expires:2022-09-26 18:55:53 +0000 UTC}
```

If I unset/remove the `GOOGLE_ADMIN_EMAIL`, `GOOGLE_GROUP` and `GOOGLE_SERVICE_ACCOUNT` env vars mentioned above and try to auth through the OAuth2 Proxy using service account credentials (an ID token as the `Bearer`), service account auth works as expected. 

I traced through the code and suspect when group-based auth is "enabled" and JWT ID tokens are provided, the OAuth2 Proxy tries to look at the groups claim in the token. And since Google doesn't add the group claim to the token, this simply won't work. 

## Possible Solution

If this is a correct read of the situation, my options using a single instance of OAuth2 Proxy and Google as the provider are:
1. Authentication and group-based authorization for users, but nothing for service accounts
2. Authentication for users AND service accounts, but no group-based authorization

And so I'm thinking of having 2 separate instances:
1. Authentication and group-based authorization for users
2. Authentication for service accounts

Is this the correct/best way to handle such a configuration?

Thanks!

- Version used: 7.3.0

**Comment by jeffisabelle** [comment]
@JoelSpeed - can you re-open this issue and hopefully review the relevant PR? We are still looking into solutions to this problem.

**Comment by RichardSieg** [comment]
Please re-open and merge the PR if possible.

**Comment by pfuhrmann** [comment]
We also badly need this!

@JoelSpeed would you kindly consider taking a look at the PR here: https://github.com/oauth2-proxy/oauth2-proxy/pull/1806 which could potentially solve this issue?

It seems like a missing basic functionality to be able to do machine-to-machine flow together with user credentials flow.

**Comment by grjones** [comment]
Adding onto the pile of people that could really use  #1806. It seems like a fairly straightforward change? I know there is some chatter that maintainers are low and there has not been a release in a long while, which is unfortunate. @JoelSpeed I'm sure this is not your main focus and your efforts with this project have been amazing, but could you let us know how maintenance is going and specifically that PR? I guess I am wondering if we should move to something else if dev has stalled. Thank you!
