### ISSUE TITLE
Ability to turn off OAuth2 Proxy session storage

### ISSUE THREAD

**Issue by jahveen** [oauth2-proxy/oauth2-proxy#1804]
OAuth2 Proxy provides two options for a session storage backend. I require a third option that omits a session altogether

## Expected Behavior

Ability to configure:
--session-store-type: none

In this mode, a session or ticket cookie is not checked, and a request can only pass if it has a verified JWT bearer token.

## Current Behavior

Configuration requires:
--session-store-type: cookie (default), or redis

An oauth2-proxy session cookie is stored in the browser following a request

## Context

I do not need this additional state in my application, since most of my application endpoints are RESTful and use a JWT token in the authentication header. Having this session in addition to the Keycloak (or other Authentication Server) session cookies in my workflows adds complexity to edge-case troubleshooting.

## Your Environment

OS: Ubuntu 20.04.2 LTS

- Version used:
bitnami/oauth2-proxy:7.2.1

**Comment by t-katsumura** [comment]
@jahveen 
Hi!
Maybe your requested feature has already been realized by `--skip-jwt-bearer-tokens` option.
Have you already checked if this option meets your needs?
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview

**Comment by jahveen** [comment]
I have already checked. Using this option includes the cookie responses from oauth2_proxy

**Comment by JoelSpeed** [comment]
This makes sense as a request, but has a wide impact. It would mean disabling all ability to log in, and large swathes of the code would be disabled in this mode. I don't know if we are in a position to be able to easily do this right now, you'd have to touch a large area to implement this.

Have you looked at trying to implement this at all?

**Comment by JoelSpeed** [comment]
@OmarHawk Are you willing to look into implementing this, if you are, i can re-open the issue
