### ISSUE TITLE
Support for GKE workload identities with Google auth

### ISSUE THREAD

**Issue by laughingman7743** [oauth2-proxy/oauth2-proxy#1808]
## Current Behavior

I have an authentication setup using Google Groups in GKE, but I get the following error.
```
[2022/10/03 09:26:47] [main.go:54] invalid configuration:
  missing setting: google-service-account-json
```
I would like to use GKE WorkloadIdntity to set up authentication for Google Groups without issuing JSON keys for service accounts, is this not supported?

## Possible Solution

It would be nice to support GKE workload identities and be able to start without the `google-service-account-json` flag.
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

## Your Environment

- Version used: 7.2.1

**Comment by JoelSpeed** [comment]
I don't think this is supported currently but if you can put together a PR to support this, I don't see why we couldn't include this as a feature

**Comment by bygui86** [comment]
@JoelSpeed I don't understand why this issue was closed but still the Google Workload Identity PR is open...

**Comment by JoelSpeed** [comment]
Workload identity now merged, will leave it closed
