### ISSUE TITLE
Keaycloak provider doesn't retain user nor prefered_username in session

### ISSUE THREAD

**Issue by babs** [oauth2-proxy/oauth2-proxy#1813]
## Expected Behavior

Retain the `user` and possibly `preferred-username` to be able to propoerly populate x-forwarded-user to the backend

## Current Behavior

None are saved in session, therefore headers are not provided to the backend

## Possible Solution

~A PR  is on it's way~ PR #1815 is here

- Version used: 7.3.0

**Comment by ooraini** [comment]
shameless plug: I faced a similar issue with OIDC provider, the username wasn't available in the session #1793. I ended up creating my own solution [https://github.com/ooraini/oidc-auth](https://github.com/ooraini/oidc-auth). See if it work for you.

**Comment by babs** [comment]
PR is available as #1815 
I also made a build on my fork as this patch was the only missing piece... At this time ;)
