### ISSUE TITLE
Paramter proxy_timeout needs unit on CLI but none in config file?

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/oauth2-proxy#1814]
Apparently the new proxy_timeout parameter needs a unit (like "s" for seconds) when given as CLI parameter but does not accept one when provided in the config file.

## Expected Behavior

Parameter name differes ("-" vs "_") but value is same.

## Current Behavior

When using "s" in config file:

    local-oauth2-proxy-1  | [2022/10/05 06:29:01] [main.go:45] ERROR: failed to load config: unable to load config file: While parsing config: (22, 23): unexpected token

When *not* using "s" in CLI parameter:

    local-oauth2-proxy-1  | invalid argument "200" for "--upstream-timeout" flag: time: missing unit in duration "200"

## Version used:

7.3.0

**Comment by t-katsumura** [comment]
@lathspell 
Hi.
Did you use single/double quotation propery ?
If you specified the value as string, it requires a unit.

In a config file,

```
upstream_timeout="60"    # fails
upstream_timeout="60s"   # works

upstream_timeout='60'    # fails
upstream_timeout='60s'   # works

upstream_timeout=60      # works
upstream_timeout=60s     # fails
```

**Comment by lathspell** [comment]
Thanks that does explain it.

Given that the config file looks very similar to YAML, one is inclined to use the same quoting rules and YAML would parse the value as String if it doesn't look like an Int. Is your parser some Go standard library or could it be made more tolerant?

**Comment by t-katsumura** [comment]
Oh... you are using alpha config.
I showed the older config above.

Yaml config is parsed in the following function. And I checked  using oauth2-proxy v7.3.0.
So, I think there is no difference in parser.

https://github.com/oauth2-proxy/oauth2-proxy/blob/965fab422d6cd30411a6ee85a34532b276284289/pkg/apis/options/load.go#L140

I also checkded for alpha config.
This config worked for me even `timeout` has the unit 's' .

```
upstreamConfig:
  upstreams:
  - id: mymocserver
    passHostHeader: true
    proxyWebSockets: true
    timeout: 60s
    path: /
    uri: http://mymocserver.localhost.com:8000/
```

Can you show us your configuration file and any logs if possible?

**Comment by t-katsumura** [comment]
I can really understand what you expect.
But the config file is based on the [TOML specification](https://github.com/toml-lang/toml.io/blob/main/specs/en/v1.0.0-rc.2.md#string).
So, we need to follow this specification and the using unclear more tolerant parser is not a good idea, I guess.
Maybe this should be described clearly  in the docs.

For your information, 

toml based config is parsed in this function.

https://github.com/oauth2-proxy/oauth2-proxy/blob/db74661e1099f27b07f7fb94469c94afcaf037bc/pkg/apis/options/load.go#L23

And, yaml based config file is parsed in this function.

https://github.com/oauth2-proxy/oauth2-proxy/blob/db74661e1099f27b07f7fb94469c94afcaf037bc/pkg/apis/options/load.go#L140

**Comment by lathspell** [comment]
If it's TOML, then maybe call the example files "config.toml" in https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview and "config.yml" in https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config?
That way the user would be reminded which syntactic rules apply.
