### ISSUE TITLE
Ambiguous AuthFailure in case of invalid email

### ISSUE THREAD

**Issue by PAStheLoD** [oauth2-proxy/oauth2-proxy#1822]
## Expected Behavior

In case of `invalidEmail` I would expect a message in the logs that informs the admin/operator that the email validation failed.

## Current Behavior

Unclear message about "[removing session](https://github.com/oauth2-proxy/oauth2-proxy/blob/965fab422d6cd30411a6ee85a34532b276284289/oauthproxy.go#L1056)".

## Possible Solution

```go
	invalidEmail := session.Email != "" && !p.Validator(session.Email)
	if (invalidEmail) {
		logger.Printf("invalid email: %s", session.Email)
	}

```

or 

Include the variable in the log line, something like:

```go
logger.PrintAuthf(session.Email, req, logger.AuthFailure, "Invalid authorization via session: removing session %s (is email valid? %s)", session, invalidEmail)
```

## Context

We're using the Google provider for humans and the JWT bearer tokens via the extra issuers for machines, and our first attempt led to auth failures when we simply set the JWT subject to "kubernetes", setting it to something like a real email address solved the issue.

Thanks for considering!

**Comment by JoelSpeed** [comment]
Improving the context around these errors is definitely on the todo list. If you want to raise a PR that would help!

I'm not sure whether we really want to log the email though, the more we littler the logs with identifying information the more we need to be careful about where our logs end up. So improving the logs yes, including the email probably not IMO

**Comment by PAStheLoD** [comment]
Hey, thanks for replying! Unfortunately my go skills are only underwhelmed by my time management ones :S

The email address is currently already logged as part of the whole Session struct.

**Comment by JoelSpeed** [comment]
Yep the email is, but only on the auth logger which can be disabled, we must make sure we only log PII to that logger and not the general logger. Then users can disable the logger which contains sensitive data

**Comment by omBratteng** [comment]
I have encountered this issue as well. 
Would something like this work better?
```go
cause := "unauthorized"
if invalidEmail {
	cause = "invalid email"
}
logger.PrintAuthf(session.Email, req, logger.AuthFailure, "Invalid authorization via session (%s): removing session %s", cause, session, invalidEmail)
```

**Comment by omBratteng** [comment]
I created https://github.com/oauth2-proxy/oauth2-proxy/pull/2010 to fix this
