### ISSUE TITLE
OIDC Azure only works when callback subpath is /oauth2/callback

### ISSUE THREAD

**Issue by adamchengtkc** [oauth2-proxy/oauth2-proxy#1826]
## Expected Behavior

The callback/redirect_url should be able to use any path or subpath

## Current Behavior

Only works when redirect_url is: https://www.example.com/oauth2/callback

For other subpath e.g. https://www.example.com/authproxy/oauth2/callback or https://www.example.com/oauth/callback

The following happens (These are the findings I got from MS Azure support after sending them my console and network logs)

1.	The user first goes to the application URL, and he is redirected to Azure AD for authentication (pay attention to the URL the application is redirecting to – visible in bottom right, in the HTTPS response):
2. After prompting the user for KMSI cookie (Keep Me Signed In), we are redirecting him to the [https://flo.example.com/authproxy/oauth/callback] URL, with an authorization code (as per OAuth2 Authorization code flow):
3.	The application or the OAuth2-proxy receives the response on the callback URL, and it immediately redirects to Azure AD for authentication, while somehow adding the authorization code to the request body 
4.	Azure AD receives this request and treats the additional characters as part of the “state” parameter, thus responds with a new authorization code each time, but please notice how the HTTP request grows in size:

Step 4 repeats 2 more times until the url query string is too long

So after step 2: Why is the Oauth2-proxy not accepting the authorization code received from Azure AD and sends immediately another request for authentication?

## Steps to Reproduce (for bugs)

Use Azure as OIDC provider with these example config
```
- name: OAUTH2_PROXY_AZURE_TENANT_STRING
  value: ""
- name: OAUTH2_PROXY_CLIENT_ID
  value: ""
- name: OAUTH2_PROXY_COOKIE_REFRESH
  value: "60m"
- name: OAUTH2_PROXY_EMAIL_DOMAINS
  value: "*"
- name: OAUTH2_PROXY_HTTP_ADDRESS
  value: "http://:8000"
- name: OAUTH2_PROXY_OIDC_ISSUER_URL
  value: "https://login.microsoftonline.com/<TENANT_ID>/v2.0"
- name: OAUTH2_PROXY_SET_XAUTHREQUEST
  value: "true"
- name: OAUTH2_PROXY_PASS_ACCESS_TOKEN
  value: "true"
- name: OAUTH2_PROXY_PASS_BASIC_AUTH
  value: "false"
- name: OAUTH2_PROXY_PASS_USER_HEADERS
  value: "false"
- name: OAUTH2_PROXY_PROVIDER
  value: "oidc"
- name: OAUTH2_PROXY_REDIRECT_URL
  value: "https://a.example.com/authproxy/oauth2/callback"
- name: OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS
  value: "true"
- name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
  value: "true"
- name: OAUTH2_PROXY_UPSTREAMS
  value: http://127.0.0.1:8080/
- name: OAUTH2_PROXY_SESSION_STORE_TYPE
  value: "redis"
- name: OAUTH2_PROXY_REDIS_CONNECTION_URL
  value: "redis://redis:6379"
```

## Your Environment

- Version used:
v7.2.1 and v7.3.0 in docker

**Comment by julian-barske** [comment]
What you're looking for is the proxy-prefix configuration.
When setting the redirect URL, you only change what is being sent to the provider and not what URL OAuth2 Proxy is expecting the callback to be at.
The path of the redirect URL always has to be [proxy-prefix]/callback

**Comment by adamchengtkc** [comment]
Thanks very much for pointing this. Much appreciated
