### ISSUE TITLE
Release of api_routes config

### ISSUE THREAD

**Issue by beezerk23** [oauth2-proxy/oauth2-proxy#1829]
Hey, is there a plan on when to release this in some patch version? Im using the docker image and not sure how to use the master branch directly. Any help is highly appreciated

_Originally posted by @beezerk23 in https://github.com/oauth2-proxy/oauth2-proxy/issues/1760#issuecomment-1277638607_

**Comment by JoelSpeed** [comment]
You should be able to build the docker file using a recent version of docker or some other container builder such as podman. I'm hoping to cut a new release soon but I'm struggling to find time to sit down and do it right now as I'm travelling at lot right now
