### ISSUE TITLE
How to use oauth2-proxy behind a rewrite proxy

### ISSUE THREAD

**Issue by PaleNeutron** [oauth2-proxy/oauth2-proxy#1831]
## Problem

I have several apps deployed behind an openshift router and can be accessed by `http://mydomain.com/app1/path`.

My route rewrite `/app1/path` to `/path`, so I the http request app1 got is `http://mydomain.com/path`.

The problem is if I put oauth2-proxy with app1, the current_path in redirect_url will be `/path` not `/app1/path` so after auth the oauth2-proxy will redirect me from `http://mydomain.com/app1/path` to `http://mydomain.com/path`.

Can anyone give me some suggestions ?

Here is a nginx conf to simulate my openshift route

```
    server {
        listen       9999;
        location /nssf {
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://localhost:4180;
            proxy_redirect     off;
            rewrite /nssf/(.*) /$1  break;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
```

- Version used: V7.3.0

**Comment by JoelSpeed** [comment]
You can set the `X-Auth-Request-Redirect` header to the path that the user path before it is rewritten and then OAuth2-Proxy will use that as the redirect path after a successful login
