### ISSUE TITLE
Need Recommendation to setup OPA to enable Authorization . 

### ISSUE THREAD

**Issue by anannaya** [oauth2-proxy/oauth2-proxy#1832]
Authorization has been a long pending feature list of oauth2-proxy.

**Comment by JoelSpeed** [comment]
We aren't looking into integrating OPA as it proved overly complex and the maintainers do not have the time to invest in maintaining an integration with OPA right now

**Comment by qdrddr** [comment]
OPA for AuthZ seams to be the right choice, hope oauth2-proxy will go this way
