### ISSUE TITLE
Support client_assertion in generic OIDC provider

### ISSUE THREAD

**Issue by PabloPie** [oauth2-proxy/oauth2-proxy#1834]
## Expected Behavior

When trying to configure the generic OIDC provider with Azure AD and their new [federated credential auth](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#third-case-access-token-request-with-a-federated-credential) I noticed that you need to provide a client_assertion and a client_assertion_type parameter instead of a client_secret, which the provider doesn't seem to support currently.

## Current Behavior

You cannot use jwt or certificates for a client credentials grant.

## Possible Solution

Add a new parameter mirroring client_secret for client_assertion.

## Context

In our case, this is useful for authenticating a Kubernetes pod to Azure without having to create and manage a static client secret.

## Your Environment

- Version used: 7.3.0

**Comment by prevostc** [comment]
This is something I need, is this something you would be interested in and I start working adding this to oauth2-proxy?
If yes, what would be the api for this? a new provider or adapt the existing oidc one with options?

**Comment by tuunit** [comment]
Hi @prevostc,

as you already worked on this internaly at your company. Are you willing to invest same time generalize your solution so you are able to contribute it to the community?

**Comment by prevostc** [comment]
> as you already worked on this internaly at your company. Are you willing to invest same time to generalize your solution, so you are able to contribute it to the community?

Hi sir, I am willing to work on this and I will do my best to contribute that back to the community.
