### ISSUE TITLE
Getting authenticated user data

### ISSUE THREAD

**Issue by aidevops1** [oauth2-proxy/oauth2-proxy#1842]
## Expected Behavior

I can't find it in the oauth2-proxy docs how to extract the user information (eg. username and email) in the flask app that's protected by oauth2-proxy. Please guide me where or how to find it :-)

## Your Environment

oauth2-proxy is running behind nginx protecting a simple python flask app.

- Version used: 7.3.0

**Comment by jkjha** [comment]
I am also looking for this information but in tomcat application. More info in this stackoverflow question: https://stackoverflow.com/questions/74114403/get-username-in-opengrok-from-oauth2-proxy

**Comment by beezerk23** [comment]
@aidevops1 Unfortunately i dont have any knowledge of Flask, but you can fetch /oauth2/userinfo to get at least the email and username. 

We need to get much more information about the user like the ID etc, so what we do is decode the jwt token part holding the information.

**Comment by aidevops1** [comment]
I thought so, however I assume you need to have such a token or something to query the /oauth2/userinfo URI. How to get that? Where is it?

**Comment by beezerk23** [comment]
Mhh no you don't need it. Once authenticated the token is saved in the cookie. Every request to that URL is using this cookie so the request is already authenticated.

**Comment by aidevops1** [comment]
I still don't get it. The app wants to know who the user is not only that he's authenticated. So I assume to figure it out, the app needs to call /oauth2/userinfo on the auth proxy. Can you guide me which cookie value to use?

**Comment by beezerk23** [comment]
Is the proxy and the app running on different domains? Otherwise it should work out of the box. The oauth proxy would save the cookie to your domain like myapp.com. Every request to that domain now includes the cookie, so if you would call myapp.com/oauth2/userinfo this request is authenticated and will return the information.

If your application is running on a separate domain than the oauth proxy like app.myapp.com and proxy.myapp.com then you would need the --pass-access-token option. This will sent the JWT in the header X-Forwarded-Access-Token to your app. The cookie still is saved on proxy.myapp.com but you get the JWT in your app.myapp.com. What you of course also can do here is to call proxy.myapp.com/oauth2/userinfo. 

Hope this makes it more clear, otherwise maybe you can share more about your exact setup.

**Comment by jkjha** [comment]
@beezerk23  , isn't it possible to pass the username from oauth2-proxy to the application server as header. I tried using the flag `--pass-basic-auth` based on documentation here: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview . But that doesn't seems to work.

**Comment by aidevops1** [comment]
The whole setup is running in a containerized environment. The proxy and the app are in 2 separate containers with an nginx container as the frontend. As jkjha mentioned, unfortunately the --pass-access-token doesn't seem to work.

I use the following relevant options for the proxy:

```
--pass-user-headers=true
--set-xauthrequest=true
--pass-access-token=true
--set-authorization-header=true
```

I have the following headers:

X-Forwarded-For, X-Forwarded-Host, X-Forwarded-Port, X-Forwarded-Proto, X-Forwarded-Server and X-Real-Ip

As well as the following cookies:

_oauth2_proxy_0
_oauth2_proxy_1

Probably I should use the cookies, but not sure how.

**Comment by beezerk23** [comment]
@jkjha This is configured to true by default and for me it works. I don't get the username but thats because my provider does not use usernames, so i get X-Forwarded-Email. Maybe check your request headers to see what is in there

**Comment by jkjha** [comment]
Thanks for your response. Where exactly I can see the request headers? Do you mean in oauth2-proxy?
I am debugging my upstream app, and its not receiving either X-Forwarded-User or X-Forwarded-Email.

However, /oauth2/userinfo returns following output:

`{"user":"","email":"myname@domain.com"}` (user is blank). I am fine if atleast email is received on header.

Only option currently I have is to make extra API call for /oauth2/userinfo from my upstream app to get the details which I am trying to avoid. (I just want to show "Welcome <user/email>" on upstream UI.

If you have any info or tip, please let me know.

**Comment by jkjha** [comment]
Finally got it working... here is the trick: https://github.com/oauth2-proxy/oauth2-proxy/issues/197#issuecomment-540158057
