### ISSUE TITLE
Question: Does oauth2 proxy support HTTP compression by itself ?

### ISSUE THREAD

**Issue by thisisfeature** [oauth2-proxy/oauth2-proxy#1844]
## Expected Behavior

Hi teams, I have a question that does oauth2 proxy support HTTP compression by itself ?

I'm investigating the way to config HTTP compression with oauth2 proxy, then all the request/response go through the proxy can improve transfer speed and bandwidth utilization.

## Your Environment

- Version used: v7.3.0

**Comment by JoelSpeed** [comment]
At the moment no it doesn't, how popular do you think this feature would be? Is there an easy way to implement this within go?

**Comment by thisisfeature** [comment]
I see some proxy like nginx, ha proxy, appache webserver which support Http compression. It would be great if Oauth2 proxy could support it.

**Comment by JoelSpeed** [comment]
It would be better to use something more fully fledged, like Nginx, and just use OAuth2 Proxy as an auth request sidecar IMO
