### ISSUE TITLE
Issues with OAUTH2_PROXY_CODE_CHALLENGE_METHOD

### ISSUE THREAD

**Issue by jkroepke** [oauth2-proxy/oauth2-proxy#1852]
## Expected Behavior

I cant enable PKCE support in oauth2-proxy through the env variable `OAUTH2_PROXY_CODE_CHALLENGE_METHOD`

## Current Behavior

If `OAUTH2_PROXY_CODE_CHALLENGE_METHOD` is set `S256`, the log message

```
[2022/10/23 17:47:19] [providers.go:145] Warning: Your provider supports PKCE methods ["S256" "plain"], but you have not enabled one with --code-challenge-method
```

I expect, that PKCE is still not enabled, if the message appears.

## Possible Solution

Using the CLI option `--code-challenge-method=S256` helps here.

## Steps to Reproduce (for bugs)

1.  Setup oauth-proxy with an OIDC endpoint that supports PKCE
2.  Set OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
3.  Look at the logs

## Context

Enabling PKCE in oauth2-proxy

## Your Environment

- Version used: oauth2-proxy v7.3.0 (built with go1.17.10)

**Comment by Wykiki** [comment]
Encountered that bug, may this originated from the property definition that is different, on the JSON side, for this ?
https://github.com/oauth2-proxy/oauth2-proxy/blob/1e21a56f99b1c6278d6a1ade781e4491a426f6a0/pkg/apis/options/providers.go#L80

All other properties have lowerCamelCase for JSON definition, so shouldn't it be like this ?
```go
CodeChallengeMethod string `json:"codeChallengeMethod,omitempty"`
```

**Comment by t-katsumura** [comment]
I don't know if it works but can you try depricated `--force-code-challenge-method` option just for workaround ? 

OAUTH2_PROXY_FORCE_CODE_CHALLENGE_METHOD="S256"

https://github.com/oauth2-proxy/oauth2-proxy/blob/1e21a56f99b1c6278d6a1ade781e4491a426f6a0/pkg/apis/options/legacy_options.go#L534

**Comment by Wykiki** [comment]
Tried that and it worked, thanks !

**Comment by jkroepke** [comment]
It's possible to implement the env variable for the non deprecated flag, too?

**Comment by segaura** [comment]
I am not able to have any of this working if Alpha Configuration is active:

--code-challenge-method=S256
--force-code-challenge-method=S256

also their property/env variants, like these etc.

code_challenge_method=S256
force_code_challenge_method=S256

Do them work for you?

NOTE: I have provider auto-discovery turned off
