### ISSUE TITLE
Is it possible to have the nginx location block provide the allowedGroup to oauth2-proxy?

### ISSUE THREAD

**Issue by wccropper** [oauth2-proxy/oauth2-proxy#1855]
Is it possible to have the nginx location block provide the allowedGroup to oauth2-proxy? I would like to run a single oauth2-proxy and have many locations, each with a unique allowedGroup. If the only option is to run multiple oauth2-proxy, what is the recommendation on how to best do that on a single server using redis? Any assistance is appreciated.

**Comment by ObjectivelyAj** [comment]
Also looking for a way to do this. As it stands it seems that there is noway to have multiple unique allowedGroup.

**Comment by JoelSpeed** [comment]
Can you not do this with the auth request path? If you add a query string `?allowed_groups=...` I believe this is already supported
