### ISSUE TITLE
Equivalent to nginx try_files when serving static files

### ISSUE THREAD

**Issue by cjalmeida** [oauth2-proxy/oauth2-proxy#1856]
When serving static files using `file://` URI scheme, when using a SPA router (like Angular's [PathLocationStrategy](https://angular.io/api/common/PathLocationStrategy#description)) the proxy _correctly_ tries to load a subpath as a file. Eg.

Requesting `http://foo/sub/path` on a mapping ` "/" => "file:///web/#/"` tries to load "/web/sub/path". In SPA using path location routing strategy the expected behavior from proxy would be to try to load `file:///web/index.html` instead regardless of the subpath. 

In Nginx, you can use `try_files` as in [this SO answer](https://stackoverflow.com/a/40050985) to try the base path before returning 404's.

Is this somehow achievable in oauth2-proxy?

**Comment by JoelSpeed** [comment]
No, this isn't something we have implemented, your best option is to use OAuth2 Proxy as an Nginx auth_request sidecar and use the existing Nginx behaviour
