### ISSUE TITLE
Azure V2 endpoint: isV2Endpoint not set when configured

### ISSUE THREAD

**Issue by kaarlov** [oauth2-proxy/oauth2-proxy#1857]
## Expected Behavior

Azure V2 endpoint should work with configuration described in documentation:

   --provider=azure
   --client-id=<application ID from step 3>
   --client-secret=<value from step 5>
   --azure-tenant={tenant-id}
   --oidc-issuer-url=https://login.microsoftonline.com/{tenant-id}/v2.0

## Current Behavior

Got an error "AADSTS901002: The 'resource' request parameter is not supported." at login

## Possible Solution

Looking at azure.go the resource parameter should not be present in request when isV2Endpoint is true. It looks like the code

```
isV2Endpoint := false
if strings.Contains(p.LoginURL.String(), "v2.0") {
	isV2Endpoint = true
```

Does not set it true with documented parameters. Works fine by setting isV2Endpoint := true

## Steps to Reproduce (for bugs)

Configuration file items related to Azure:

```
provider="azure"                                                                                                                     
client_id="redacted"                                                                                     
client_secret="redacted" 
oidc_issuer_url="https://login.microsoftonline.com/redacted/v2.0"  

```
1. Try to log in
## Your Environment

- Version used:

v7.3.0 / latest source

**Comment by kaarlov** [comment]
Looks like this is no longer an issue with 7.4.0 release.

**Comment by JoelSpeed** [comment]
Great, can we close this?

**Comment by kaarlov** [comment]
Yes, I think this can be closed.
