### ISSUE TITLE
Is this possible to send access token as query parameter to upstream 

### ISSUE THREAD

**Issue by dk198150** [oauth2-proxy/oauth2-proxy#1864]
Is this possible to setup Oauth2-proxy to send access token as query parameter to upstream uri?  ie:  https://<upstream uri>?access_token=<access token>
## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
Your only option for sending details from the session to the upstream is via headers, we don't support modifying the query string
