### ISSUE TITLE
Feature: support unix socket as upstream

### ISSUE THREAD

**Issue by babs** [oauth2-proxy/oauth2-proxy#1865]
## Expected Behavior

I'd like to be able to provide unix:///run/myapp/uvicorn.sock as the upstream server

~PR is coming~ see PR #1866 

## Your Environment

- Version used: 7.3.0

**Comment by JoelSpeed** [comment]
Seems like a reasonable feature request, all of the upstream proxying code is well maintained and in good form so this shouldn't be too hard. Will want to make sure we have decent tests for this please.

**Comment by babs** [comment]
I've submitted a PR, might need some help for the test part

**Comment by babs** [comment]
Still on it.

**Comment by babs** [comment]
Still on it but lack of time :/

**Comment by babs** [comment]
PR still open.

**Comment by babs** [comment]
Not stale

**Comment by JoelSpeed** [comment]
Still working on this
