### ISSUE TITLE
[doc] Azure AD permission incorrect?

### ISSUE THREAD

**Issue by caizixian** [oauth2-proxy/oauth2-proxy#1868]
## Expected Behavior
Setting the permission to fetch groups per the documentation, which should be `User.Read` for Delegated and `Directory.Read.All` for Application.

https://learn.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=http#permissions

## Current Behavior

`Group.Read.All` is listed.

https://github.com/oauth2-proxy/oauth2-proxy/blob/aafa96655048bc1ed26487e92410f5fe64968fa2/docs/docs/configuration/auth.md?plain=1#L82

## Context
https://learn.microsoft.com/en-us/graph/api/user-list-transitivememberof endpoint is used to fetch group membership.

https://github.com/oauth2-proxy/oauth2-proxy/blob/aafa96655048bc1ed26487e92410f5fe64968fa2/providers/azure.go#L137

**Comment by JoelSpeed** [comment]
Have you tried it with the other permissions? Does it work in those cases? I'm not an Azure user so I can't really help right now

**Comment by danbrad** [comment]
I've done a bit of testing on this and it does appear that User.Read for delegated is enough for it to work with 7.4.0 without Directory.Read.All for application being added.

In order for it to work consistently, admin consent does appear to be needed, although I have seen it work for some users without it.
