### ISSUE TITLE
[need help] Traefik forward auth with allowed_groups query param

### ISSUE THREAD

**Issue by yongzhang** [oauth2-proxy/oauth2-proxy#1870]
Hi, there

I tried hard with Traefik forward auth (static upstreams) with `allowed_groups` query param, I finally gave up, couldn't make it work.

Traefik config I used from this example:
 
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#forwardauth-with-static-upstreams-configuration

This works very well. But I don't know how and where to add the `allowed_groups` query args introduced in this [PR](https://github.com/oauth2-proxy/oauth2-proxy/pull/849). Please help if anyone has success examples, thanks.

**Comment by JoelSpeed** [comment]
It was my understanding that Traefik couldn't handle query strings and needed env vars for this kind of thing? You'd have to check with someone more familiar with Traefik though
