### ISSUE TITLE
Injecting request ID into upstream headers

### ISSUE THREAD

**Issue by ShivanKKP** [oauth2-proxy/oauth2-proxy#1871]
(https://github.com/oauth2-proxy/oauth2-proxy/pull/1087#issuecomment-797844247)

## Expected Behavior

Add the generated Request-ID/UUID as a upstream header when non is supplied.

## Current Behavior

When request-id is omitted a generated UUID is used in the logfiles. The UUID isn't propagated to the upstream.

## Possible Solution

add a new property gen-request-id
gen-request-id=true
if header(request-id-header) is omitted/empty then add this header with value UUID to the upstream.

## Context

- Version used: 7.3.0

**Comment by JoelSpeed** [comment]
I wonder if we can include this as a part of the current headers configuration. You'd need to expand the code [here](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/header/injector.go) to be able to gather data from the request context to then be able to be injected into the response or request. What do you think?
