### ISSUE TITLE
Some providers has uninitialized user claim

### ISSUE THREAD

**Issue by babs** [oauth2-proxy/oauth2-proxy#1874]
Keycloak OIDC (among others) doesn't call `setProviderDefaults` therefore UserClaim is never initialized with the default value (sub) and stay an empty string. This leads to an empty user.

Should be closed by PR #1873 

## Expected Behavior

`user` value present in the session.

## Current Behavior

When using Keycloak OIDC, `user` value is empty

## Your Environment

- Version used: 7.4.0

**Comment by breedjaram32** [comment]
If the problem will is solved, so similar issue for closing https://github.com/oauth2-proxy/oauth2-proxy/issues/1681

**Comment by babs** [comment]
I think so too, pr #1873 might also close #1681.

You can TEST a build from my fork to confirm it (not for long term use)
