### ISSUE TITLE
Validate URL call does not correctly honor already set URL parameters

### ISSUE THREAD

**Issue by fschaefer** [oauth2-proxy/oauth2-proxy#1878]
If the validate URL already contains URL parameters like in

`https://my.provider.de/2.0/users/me?with_permissions=true&with_roles=true`

`oauth2-proxy` doesn't honor this circumstance and appends a new query string marker (`?`) instead of a separator (`&`) and
the URL becomes

`https://my.provider.de/2.0/users/me?with_permissions=true&with_roles=true?access_token=eyJ0eXAiOiJKV1...`

which leads to problems depending on the upstream server implementation.

The code is here:
https://github.com/oauth2-proxy/oauth2-proxy/blob/aafa96655048bc1ed26487e92410f5fe64968fa2/providers/internal_util.go#L56

**Comment by JoelSpeed** [comment]
Yep, fair point, that's a bug! PR welcome

**Comment by miguelborges99** [comment]
@fschaefer Are you able to check if [pull request](https://github.com/oauth2-proxy/oauth2-proxy/pull/1951) is working fine?

**Comment by miguelborges99** [comment]
Pull request is still to be merged
