### ISSUE TITLE
Docs about email provider

### ISSUE THREAD

**Issue by guettli** [oauth2-proxy/oauth2-proxy#1881]
## Expected Behavior

If I read the docs about the email provider, I expect to understand how
an email provider can provide oauth2.

https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#email-authentication

## Current Behavior

The docs name some settings, but nothing about how this works.

## Possible Solution

Someone who knows how it works could update this part of the docs.

**Comment by JoelSpeed** [comment]
Yeah that part of the docs needs an update.

Basically, your options for email domain are, if all users come from a single domain, set that as an email domain, and only users with emails at that domain will be allowed to log in. If you don't care which domain the user email is from, set it to `*`

If you only want specific users to log in, use the authenticated emails file, then only users with those specific emails can log in
