### ISSUE TITLE
map JWT claim to Session Claim

### ISSUE THREAD

**Issue by itmwiw** [oauth2-proxy/oauth2-proxy#1885]
Hello
I have a token claim I need to map as a header. To do so, I used the oidc-email-claim option that allows me to choose the claim I consider to be the email (to be mapped to the session claim). Then, I mapped the session claim to my custom header. Everything works fine when connecting through my provider.
However, When trying to connect with a JWT using "skip-jwt-bearer-tokens: true", the session claim is not mapped to the correct JWT claims. Thus the header is not mapped correctly. 
Any help on this?
thanks in advance.
Regards,
Tarik

**Comment by JoelSpeed** [comment]
Yeah interesting point, I don't think we have a solution for this for the JWTs right now.

Once we have multi-provider support the additional JWT tokens will be supported through that mechanism and you'll be able to remap the session based on that, but right now, I don't think this is supported
