### ISSUE TITLE
Doc site root respond 404

### ISSUE THREAD

**Issue by babs** [oauth2-proxy/oauth2-proxy#1891]
http://oauth2-proxy.github.io/ respond 404

## Possible Solution

It would be nice to have a basic html that to redirect / to /oauth2-proxy/ where docs are currently exposed.

**Comment by JoelSpeed** [comment]
To do this, I think it's possible, but we'd need to create a repo for github to publish at the root URL (we use github pages to publish hence why it's under this subpath) and then add something in there, shouldn't be too hard to set up I don't think

**Comment by babs** [comment]
According to the documentation it might be possible to publish at root, maybe it's a new feature ?

**Comment by JoelSpeed** [comment]
> According to the documentation it might be possible to publish at root, maybe it's a new feature ?

Have you got a link for that? That definitely sounds new to me

**Comment by babs** [comment]
This is what I found:
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by JoelSpeed** [comment]
Reading through that, I don't see a way to publish to the org root of github.io. The `root` part they are talking about there is whether the docs are published from the repo root, or from the docs folder within the repo

**Comment by babs** [comment]
My bad.
That said there should be a way to push a proper page at the root to at lease redirect to the proper subfolder, no ?

**Comment by JoelSpeed** [comment]
I think there must be a way to do it yes, but you're right, it would just be a file that causes a redirect to the right docs site
