### ISSUE TITLE
[Question] How to log out a user from all his sessions?

### ISSUE THREAD

**Issue by tybulewicz** [oauth2-proxy/oauth2-proxy#1893]
One of requirements of our project is to be able to log out a user from all sessions that are currently active.

I know that cookie backend won't allow that, I hoped redis might help, but it seems only current session can be [removed](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/sessions/redis/redis_store.go#L61) .

I've come up with a band-aid solution idea, that would store a list of all `ticketID`s for a given user and when requested, all keys from redis would be removed. It doesn't seem too elegant, do you know of any other solutions?

**Comment by JoelSpeed** [comment]
If you change your cookie secret, you can invalidate all sessions for the entire org.

If you really want to log a user out though, your best bet is to try and invalidate their session on the IDP side, since then when they go to refresh the session, it won't work

**Comment by tybulewicz** [comment]
Thank you for that suggestion @JoelSpeed!
