### ISSUE TITLE
Advice: Accessing API behind proxy using Python or Curl

### ISSUE THREAD

**Issue by stevenayers** [oauth2-proxy/oauth2-proxy#1895]
Hi All,

This is more of a request for help than an issue.

I have a REST API deployed on Kubernetes behind the OAuth2-proxy, which is deployed using the official helm chat.

My OIDC Provider: Google
My API URL: `https://my-api.example.com`
My Kubernetes Nginx Config:
```
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
```

I'd like to access this API using either CURL or Python. Also:
- I'd rather not use the same client ID and client secret that I have issued for the oauth2-proxy
- This needs to be entirely programmatic with no human intervention (login screens etc)

Could someone please break down to me what steps I need to take to make this work? Preferably with curl/python code examples and an explanation of which URL paths I need to hit in my requests and if I need to set up anything additional in the Google developer console.

Thank you! 🙏

**Comment by JoelSpeed** [comment]
I expect you'll need to do some exploration of this yourself, the maintainers certainly don't have enough time right now to write up a guide of how to do this for you.

That said, you can use the `extra-jwt-issuers` option to provide additional client-ids configurations for providers that are not designed for interactive login, but designed just to accept tokens generated elsewhere

If you can set this up with your provider, and then generate the authentication JWT somehow (this will vary a lot depending on your stack and provider), then you should be able to achieve what you are looking to do

**Comment by umershaekoor** [comment]
@JoelSpeed could you please provide an example of a config using the extra jwt issuers property?

I'd like to get through to a rest api protected via oAuth2 Proxy by passing a token generated by a different client (and hence a different client-ID) where both the clients share the same key cloak provider.

The docs say that the property takes a list like issuer=audience but I'm not sure how that's supposed to work. Should it be <keycloak-issuer>=<client-one-id>, <keycloak-issuer>=<client-two-id>?

**Comment by nishafnaeem** [comment]
Was anyone able to find out how we can actually make the `curl` or `python` request to hit the API sitting behind `oauth2-proxy`?

**Comment by royxact** [comment]
You should be able to curl a first request, that will redirect to the logon provider (add -L to tell curl to redirect).
Include the logon data in that request (i.e. secret, client id). If you need to pass those in the URL you need to tell oauth2-proxy to pass on that url parameter to the identify provider by using this parameter: 
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config#loginurlparameter

You'll then receive back the cookie, which you should be able to use in the requests following the first one.

**Comment by royxact** [comment]
Sorry, we're not using the Google provider.

**Comment by nishafnaeem** [comment]
Alright. I couldn't find any possible example so not really sure on how to compile the URL with the parameters. Any help from any community member would be appreciated.
