### ISSUE TITLE
ASCII encoding is missing as defined by RFC

### ISSUE THREAD

**Issue by jflo93** [oauth2-proxy/oauth2-proxy#1897]
Hi together, 
sometimes we get an error on our IDP: 

> Transformed code verifier does not match code challenge.

I found that the generation of the code challenge does not match the RFC. Here the ASCII encoding is missing.
Please have a look at the RFC: 
https://www.rfc-editor.org/rfc/rfc7636#section-4.2
     ` code_challenge = BASE64URL-ENCODE(SHA256(ASCII(code_verifier)))
`
There is also a stackoverflow entry on the topic:
https://stackoverflow.com/questions/58687154/identityserver4-pkce-error-transformed-code-verifier-does-not-match-code-chall

https://github.com/oauth2-proxy/oauth2-proxy/blob/fd2807c091686a2a23f41123e3470a1076e877a0/pkg/encryption/utils.go#L89

Could you fix this?

**Comment by braunsonm** [comment]
Yes, completely my fault here, made an incorrect assumption about the string generation. PR should resolve this.

**Comment by braunsonm** [comment]
@jflo93 Maybe I misunderstood. I created PR which should address this more clearly but there should not be any non-ASCII characters in the code verifier as we pass the generated bytes into a base64 encoding before SHAing them.

What makes you certain this is the error? What code verifier is your IdP seeing?

**Comment by braunsonm** [comment]
What might actually be happening here is the generated bytes explodes the length during base64 encoding to >128 characters that the spec supports.

If your generated bytes get enough UTF-8 characters encoded in the bytes, the base64 string could go past the [46, 128] allowed range. My draft PR would still fix that since the base64 encoding has been removed

**Comment by jflo93** [comment]
unfortunately, I can't say exactly. 
We use the Duende framework and with it we get the error.
The changes look good and hopefully fix our random error
