### ISSUE TITLE
Can we make all files referenced in this repo self-contained in order to make this tool easier to use in private cloud environment where Internet cannot be accessed at will?

### ISSUE THREAD

**Issue by thuzhf** [oauth2-proxy/oauth2-proxy#1898]
For example, the following line contains a css file referenced in URL form, and this results that when Internet can not be accessed, this webpage will be in loading state for very long time before it times out, and in the end, it cannot show this css file at all.
https://github.com/oauth2-proxy/oauth2-proxy/blob/7a784a460dbccad2fff4837cdad5a9fb414f971c/pkg/app/pagewriter/sign_in.html#L8

But if we copy this css file directly into this repo, then we can use it at ease even if when we are in private cloud environment where Internet cannot be accessed at will.

This is only an example code line. There are several similiar code lines that have the same problem. I hope all these code lines can be changed so that we do not have this problem. Thanks!

**Comment by JoelSpeed** [comment]
This makes sense as a feature request for internet restricted environments, are you able to raise a PR for this?

In my mind this will work roughly by:
- Use go embed to embed the currently linked files
- Include scripts/make targets to make sure the embedded files are up to date
- Serve the files under `/<proxy-prefix>/static`

Open question: Do we want this to be the default behaviour? How many files do we link? If it's only a few small files we are probably ok doing this and not making it optional.

**Comment by VolJin** [comment]
Need this feature
