### ISSUE TITLE
Since 7.2.x, Behaviour changed, if --skip-auth-regex or --skip-auth-route is configured, after authentication, skipped URL gets additional header

### ISSUE THREAD

**Issue by RockRich** [oauth2-proxy/oauth2-proxy#1900]
Hello Everybody, 

I don't know if you have added a new Feature or not, but maybe you can tell me, if it should work like this or not. 

I used the provider = "oidc"

With the version 7.1.3, everything worked perfectly. I configured a --skip-auth-regex which worked fine. 
To reproduce: 
## How it was in Version 7.1.3:
- Configure everything with a valid --skip-auth-regex or route
- Call the route which should be ignored.  
- Check LOG: 172.21.119.33 - 764aa59c-b952-48cc-9977-4d66ccce5ec6 - - [2022/11/16 09:31:38] fancyurl.com GET / "/actuator/info" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" 200 299 0.006
- It works! 
- Authenticate Browser
- Call the route again.
- Check LOG: 172.21.119.33 - 67cfdcf1-621c-4f78-8570-df9e4e5ef22e - f:98888f3-5a58-4708-90ca-047777fe2401:user1 [2022/11/16 09:32:25] [AuthSuccess] Authenticated via OAuth2: Session{email:f:98888f3-5a58-4708-90ca-047777fe2401:user1 user:f:98888f3-5a58-4708-90ca-047777fe2401:user1 PreferredUsername: token:true id_token:true created:2022-11-16 09:32:25.167004503 +0100 CET m=+173.389325199 
.....
// How it was
172.21.119.33 - f80cc72e-2f63-47f0-ac93-81f3e64bdf69 - **-** [2022/11/16 09:32:28] fancyurl.com GET / "/actuator/info" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" 200 243 0.004
- It works! 

But in the newer Version, after Authenticate, the Proxy adds a custom header, despite ignoring it. 
## How it works with 7.2x or 7.3.x or 7.4.0
- Configure everything with a valid --skip-auth-regex or route
- Call the route which should be ignored.  
- Check LOG: 172.21.119.33 - 764aa59c-b952-48cc-9977-4d66ccce5ec6 - - [2022/11/16 09:31:38] fancyurl.com GET / "/actuator/info" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" 200 299 0.006
- It works! 
- Authenticate Browser
- Call the route again.
- Check LOG: 172.21.119.33 - 67cfdcf1-621c-4f78-8570-df9e4e5ef22e - f:98888f3-5a58-4708-90ca-047777fe2401:user1 [2022/11/16 09:32:25] [AuthSuccess] Authenticated via OAuth2: Session{email:f:98888f3-5a58-4708-90ca-047777fe2401:user1 user:f:98888f3-5a58-4708-90ca-047777fe2401:user1 PreferredUsername: token:true id_token:true created:2022-11-16 09:32:25.167004503 +0100 CET m=+173.389325199 
.....
// Different
172.21.119.33 - 94c15e01-fead-41d8-a93b-7e4d2e2c8517 - **f:98888f3-5a58-4708-90ca-047777fe2401:user1** [2022/11/16 09:52:49] fancyurl.com GET / "/actuator/info" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" 500 0 0.002

## Expected Behaviour
As it was in Version 7.1.3

Thanks a lot 🙏

Have a good Day / Evening / Night / Morning 

Cheers

**Comment by JoelSpeed** [comment]
Yeah this was a new feature, the intention was that if you have a valid user session, we would read from that to enhance the request, even on a skip-auth-route style request.

Users were complaining that this didn't work.

Is this causing you an issue now?

**Comment by RockRich** [comment]
For me, everything works fine now. Some spring-security-tools returned 401, because a token was sent. When I was reading the documentation (https://oauth2-proxy.github.io/oauth2-proxy/docs/behaviour), I thought that everything what includes the "--skip-auth-regex" will be ignored. Maybe a change of the behavior description will help. 

Thanks!
