### ISSUE TITLE
Provide option to skip group detail from Oauth cookie

### ISSUE THREAD

**Issue by bhavik-patel24** [oauth2-proxy/oauth2-proxy#1902]
## Expected Behavior

User login should work with higher number of group memberships.

## Current Behavior

User can't login with certain higher size of group memberships.

## Possible Solution

Introduce new option to skip group information from Oauth cookie

## Steps to Reproduce (for bugs)

1. Create a user who part of certain number of groups : In my case, User is part of 152 groups (groupname ~ 120 characters long so group array size ~18kb) on Azure AD application
2. Using session-store-type as cookie: Oauth2 cookie size created for this user is more than 8kb which fail in later part of session management. (jetty)

In case of session-store-type as redis: Oauth2 cookie size reduce to ~180bytes but still failing with error 431 : Request header field too large. (with pass_user_headers=false option and Redis key size is ~21kb)

## Context

This is not solve by cookie-minimal option as this issue is not related to Auth token but group information.

- Version used:
7.2.1

I created a patch to skip group information from oauth2 cookie which fix this issue in my environment. Is there any other suggestion? Should it good idea to main stream it if others are also face similar issue?
[oauth-reduce-cookie-size.txt](https://github.com/oauth2-proxy/oauth2-proxy/files/10027629/oauth-reduce-cookie-size.txt)

**Comment by bhavik-patel24** [comment]
One more thing I noticed here, 
"pass_user_headers=false" : Oauth2-proxy option doesn't work properly. Even with this option marked as false, Oauth2-proxy provide X-Forwarded-group information to upstream.

**Comment by ChevronTango** [comment]
> One more thing I noticed here, "pass_user_headers=false" : Oauth2-proxy option doesn't work properly. Even with this option marked as false, Oauth2-proxy provide X-Forwarded-group information to upstream.

Wanted to jump in and point out a fix for this I found whilst digging in the code. It looks like "pass_user_headers=false" only works if "pass_basic_auth=false" is also set. It seems the options are intrinsically linked which the documentation doesn't make clear.

**Comment by VF-mbrauer** [comment]
@bhavik-patel24, @ChevronTango: I create for the same behaviour: https://github.com/oauth2-proxy/oauth2-proxy/issues/2061

**Comment by fstaudt** [comment]
I encounter the same issue with some users having a large number of groups in Gitlab.

Could you consider reopening this issue ?
