### ISSUE TITLE
Bug: `setProviderDefaults` can't set scope properly

### ISSUE THREAD

**Issue by yuanqiuye** [oauth2-proxy/oauth2-proxy#1903]
## Expected Behavior
https://github.com/oauth2-proxy/oauth2-proxy/blob/fd2807c091686a2a23f41123e3470a1076e877a0/providers/github.go#L66-L74

The `githubDefaultScope` should be set properly, but it doesn't.

It affects all providers that use `setProviderDefaults` to initialize scope.

## Current Behavior
https://github.com/oauth2-proxy/oauth2-proxy/blob/fd2807c091686a2a23f41123e3470a1076e877a0/providers/providers.go#L34-L71
`newProviderDataFromConfig` is before providers' constructor, 
https://github.com/oauth2-proxy/oauth2-proxy/blob/fd2807c091686a2a23f41123e3470a1076e877a0/providers/providers.go#L155-L169
so if `p.Scope` is blank, `p.Scope` will automatically set to `"openid email profile"`.
It will cause the check of `p.Scope` is useless in
https://github.com/oauth2-proxy/oauth2-proxy/blob/fd2807c091686a2a23f41123e3470a1076e877a0/providers/provider_data.go#L190-L204

## Possible Solution

Maybe can make a function just like `defaultURL`
https://github.com/oauth2-proxy/oauth2-proxy/blob/fd2807c091686a2a23f41123e3470a1076e877a0/providers/provider_data.go#L207-L218
to set scope properly in `setProviderDefaults`

- Version used: 7.4.0

**Comment by yuanqiuye** [comment]
Maybe it is the reason of https://github.com/oauth2-proxy/oauth2-proxy/issues/1724

**Comment by tuunit** [comment]
Indeed this is the issue in #1724

**Comment by tuunit** [comment]
PR with fix: https://github.com/oauth2-proxy/oauth2-proxy/pull/1926

**Comment by yuanqiuye** [comment]
> PR with fix: https://github.com/oauth2-proxy/oauth2-proxy/pull/1927

Thanks for fixing this! Hope that the PR will soon be merged.

**Comment by tuunit** [comment]
Resolved by #1927 
Will be included in the next release
/close
