### ISSUE TITLE
Error with different app into the same domain

### ISSUE THREAD

**Issue by simone-reale-sdg** [oauth2-proxy/oauth2-proxy#1904]
Hi, I have the same app, with two different configuration (Azure App Registration). I have two env into the same domain:

https://myapp-dev.mydomain.com for DEV
https://myapp.mydomain.com for PROD

When I logged in dev and after I logged in prod when I try to return in DEV I have a 401 error.

Into the log I can see this error

11/17/2022, 4:56:41 PM
oauth2-proxy-7fc844c4bd-l7vw5
525621b6331889b3506dd7ce8a08bfefdbd0ea17b8d3a3947e96ccfd8347c1bd
[2022/11/17 15:56:41] [azure.go:162] unable to get email claim from id_token: <nil>
11/17/2022, 4:56:41 PM
oauth2-proxy-7fc844c4bd-l7vw5
525621b6331889b3506dd7ce8a08bfefdbd0ea17b8d3a3947e96ccfd8347c1bd
[2022/11/17 15:56:41] [azure.go:232] unable to verify token: oidc: expected audience "9daeb5a0-bb27-483a-a3c8-9003455e0b99" got ["https://graph.microsoft.com"]
11/17/2022, 4:56:41 PM
oauth2-proxy-7fc844c4bd-l7vw5
525621b6331889b3506dd7ce8a08bfefdbd0ea17b8d3a3947e96ccfd8347c1bd
[2022/11/17 15:56:41] [azure.go:170] unable to get email claim from access token: <nil>
11/17/2022, 4:56:41 PM
oauth2-proxy-7fc844c4bd-l7vw5
525621b6331889b3506dd7ce8a08bfefdbd0ea17b8d3a3947e96ccfd8347c1bd
10.243.225.10:53236 - 618809d35bb1b5808b8787f3f355aeb6 - xxxx@mydomain.com [2022/11/17 15:56:41] [AuthFailure] Invalid authentication via OAuth2: unable to obtain CSRF cookie

- Version used: v7.2.1

**Comment by JoelSpeed** [comment]
This suggests to me that you're using the same `--cookie-name` for both environments? And there's an overlap?

Can you check that you have either separate cookie domains or separate cookie names so there's no conflict between the instances
