### ISSUE TITLE
--cookie-path not working

### ISSUE THREAD

**Issue by RonanMorgan** [oauth2-proxy/oauth2-proxy#1905]
Hello,

I have an issue using nginx auth_request 

my nginx conf is very simple : 

> location /hapi/ {
>     auth_request /oauth2/auth;
>     error_page 401 = /oauth2/sign_in;

the authentication through /oauth2/sign_in is working : 

`10.0.0.2 - 61edfa53-ff1e-46a2-9d5e-f44b110e26b2 - ronan.sy@mycompany.com [2022/11/18 13:51:18] [AuthSuccess] Authenticated via OAuth2: Session{email:ronan.sy@mycompany.com user:578a1ed6-b1e9-41ee-b568-49500c70aa32 PreferredUsername:ronan token:true id_token:true created:2022-11-18 13:51:18.301206652 +0000 UTC m=+10409.766078023 expires:2022-11-18 13:56:18.300694089 +0000 UTC m=+10709.765565430 refresh_token:true}`

But the /oauth2/auth is still sending a 401 after redirection, so I am stucked with the sign_in page while the session has beend created in my oidc provider (ie keycloak here)

I have tried the configuration in the [documentation](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#configuring-for-use-with-the-nginx-auth_request-directive) but I have the same issue.

Any idea ? I don't have any error anywhere (keycloak, nginx, browser ...) 

My oauth2-proxy conf is : 

> services:
>   proxy:
>     image: quay.io/oauth2-proxy/oauth2-proxy:latest
>     ports:
>       - 4180:4180
>     environment:
>       OAUTH2_PROXY_PROVIDER: oidc
>       OAUTH2_PROXY_CLIENT_ID: Hapi-fhir
>       OAUTH2_PROXY_CLIENT_SECRET: ********************************
>       OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.mycompany.dev/realms/mycompany-broker
>       OAUTH2_PROXY_COOKIE_SECRET: azerty
>       OAUTH2_PROXY_EMAIL_DOMAINS: "*"
>       OAUTH2_PROXY_REDIRECT_URL: https://keycloak.mycompany.dev/oauth2/callback
>       OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
>       OAUTH2_PROXY_REVERSE_PROXY: "true"
>       OAUTH2_PROXY_COOKIE_SECURE: "false"
>     command:
>       - --upstream=http://hapi:8080/hapi/
>       - --whitelist-domain=[.mycompany.dev]
>       - --cookie-name=_oauth2_mycompany_proxy
>       - --cookie-path=mycompany
>     entrypoint:
>       - oauth2-proxy

**Comment by bhavik-patel24** [comment]
Hi @RonanMorgan ,

I think cookie-path need to correct in your case. Please check with hapi as cookie path.

**Comment by RonanMorgan** [comment]
nope, doesn't get any better :/

Thank you for your answer,

**Comment by RonanMorgan** [comment]
it seems that the 401 come from the fact I keycloak itself cannot access openid-connect/userinfo endpoint ...

**Comment by RonanMorgan** [comment]
ok it seems that the error was due to the following configuration : 
`--cookie-path=hapi`

The cookie was not saved in /hapi but in oauth2/ (which is even not the default value...)

So I will rename this issue and let it open since it could still be a bug in oauth2-proxy side
