### ISSUE TITLE
Need to ignore Id Token Signature Verification

### ISSUE THREAD

**Issue by triplebackslash** [oauth2-proxy/oauth2-proxy#1908]
## Expected Behavior

I would like to suggest a new flag in order to ignore id token signature verifications.
I have a scenario using azure ad provider which jwt tokens are generated by a azure ad endpoint wihtout a valid signature, and at the moment oauth2-proxy tool fails to accept the token because of it.

## Current Behavior

When I make a request to a server behind a oauth2-proxy server with a Authorization Header containing a invalid signature jwt token, a exceptions is returned.

```
[jwt_session.go:51] Error retrieving session from token Authorization header: [unable to verify bearer token, failed to verify token: failed to verify signature: failed to verify id token signature
```

## Possible Solution

A [recent commit ](https://github.com/coreos/go-oidc/commit/fb9e00951dc7a7d035e7664a5df116c3563afbd7)  on [go-oidc](https://github.com/coreos/go-oidc)  added the InsecureSkipSignatureCheck feature.

## Your Environment

- Version used: 7.4.0

**Comment by miguelborges99** [comment]
I've created this [pull request](https://github.com/oauth2-proxy/oauth2-proxy/pull/1956). The option is available if you use alpha config.

@JoelSpeed Should the insecureSkipSignatureCheck option be also available in the legacy ones?

**Comment by JoelSpeed** [comment]
I want to stop adding options to the legacy options so keeping it in alpha only is sensible, thanks for raising a PR @miguelborges99

**Comment by kr4sv** [comment]
> I've created this [pull request](https://github.com/oauth2-proxy/oauth2-proxy/pull/1956), do you want to test using your Azure configuration. The option is available if you use alpha config.

👍

**Comment by miguelborges99** [comment]
PR needs review...
