### ISSUE TITLE
Question: Is there a way to combine basic auth with SSO?

### ISSUE THREAD

**Issue by dene14** [oauth2-proxy/oauth2-proxy#1909]
Sorry if I'm asking a dumb question, but haven't found anything like that in documentation...

I need to protect certain prefixes in my website with auth, however I need to preserve basic auth for external users.
Is there any way to do so?

**Comment by JoelSpeed** [comment]
You can use the `skip-auth-route` configuration option to configure which paths do and don't require authentication
