### ISSUE TITLE
Error with oauth2-proxy.cfg file

### ISSUE THREAD

**Issue by komainu-ctrl** [oauth2-proxy/oauth2-proxy#1910]
Hey everyone,

When i try to put **allowed_group** and **allowed_role** in the cfg file i have an error. But when I'm executing it in command line everything work. 

` ERROR: failed to load config: error unmarshalling config: 1 error(s) decoding:

* '' has invalid keys: allowed_group`

or 

`ERROR: failed to load config: error unmarshalling config: 1 error(s) decoding:

* '' has invalid keys: allowed_role`

Config file oauth2-proxy.cfg: 

 allowed_group = [
       "test",
       "manager"
 ]

or 

 allowed_role = [
        "test",
        "manager"
 ]
 
How could i manage to put allowed_role or allowed_group in my .cfg file ?

Thanks in advance
 
 
 Environnement :
 Almalinux 8.6, Oauth2 version 7.4

**Comment by miguelborges99** [comment]
It is not "allowed_group" / "allowed_role" but "allowed_groups" / "allowed_roles".

See [documentation](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config).

**Comment by clement-igonet** [comment]
Maybe not (anymore): https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview
`--allowed-role` | `string | list` | `restrict logins to users with this role (may be given multiple times). Only works with the keycloak-oidc provider.`

**Comment by tuunit** [comment]
The documentation is lacking in this area. The flags are always in singular but some attributes can process multiple values like the groups or roles therefore in toml and in the new yaml format they are in plural form. Sorry for the inconvenience.
