### ISSUE TITLE
Error creating session during OAuth2 - Keycloak OIDC

### ISSUE THREAD

**Issue by shubhamdeodia** [oauth2-proxy/oauth2-proxy#1913]
I am relatively new to Keycloak and oauth2-proxy.

I am trying to make it work for one of my static app. However, I am getting below error

`[2022/11/27 12:09:40] [oauthproxy.go:830] Error creating session during OAuth2 callback: audience from claim aud with value [val1 val2] does not match with any of allowed audiences map[client-id:{}]`

Is there way to I can disable the audiences check from the claim or allow all the values to pass through with some wildcard ?

Appreciate any help you can provide.

```oauth2-proxy.cfg
## OAuth2 Proxy Config File
http_address="0.0.0.0:8080"
code_challenge_method="S256"
client_id="$CLIENT_ID"
ssl_insecure_skip_verify=true
pass_access_token=true
# set-xauthrequest=true
pass_authorization_header=true
ssl_upstream_insecure_skip_verify=true
client_secret="$CLIENT_SECRET"
redirect_url="$REDIRECT_URL"
oidc_issuer_url="$OIDC_ISSUER_URL"
upstreams=[
    "file:///var/www/static/#/"
]
whitelist_domains=[
    "*.myapp.com:*",
    "*.myapp.mobi:*"
]
provider="keycloak-oidc"
provider_display_name="kodics"
request_logging=true
set_authorization_header = true
email_domains= "*"
insecure_oidc_allow_unverified_email=true
cookie_secret="$COOKIE_SECRET"
cookie_secure=true
skip_provider_button=true
```

- Version used:
- 7.4.0

**Comment by Elektordi** [comment]
The audience in your token is supposed to include the client-id of your oauth2-proxy.
Currently there is a bug in Keycloak OIDC provider (see #1916 ) so roles configuration from keycloak is not enough, you have to manually create a mapper in your client scope to add a hardcoded claim, matching your client-id.
More information in keycloak documentation: https://www.keycloak.org/docs/latest/server_admin/#_audience_hardcoded

And there is no way to disable audience check in oidc, if would be a security hole, because any token for another service of your Keycloak would permit access to this backend!

**Comment by BenjaminHae** [comment]
According to the OpenID spec, the Access Token issued when using OpenID is inteded for usage at the `userinfo` endpoint of the Identity Provider.  
All information needed by OAuth2-Proxy to authenticate the user (when OpenID is used) is contained in the IdToken.
The Access Token should only come into play, when OAuth2-Proxy requires additional data that can be obtained from the userinfo-endpoint. And even in that case OAuth2-Proxy would not need to inspect the Access Token itsel.

**Comment by brsolomon-deloitte** [comment]
Please re-open. Not stale and still occurring with oauth2-proxy v7.4.0 and Keycloak 21.x.

oauth2-proxy fails with keycloak-oidc using the examples currently shown in the oauth2-proxy docs.

**Comment by celevra** [comment]
any news on that?

**Comment by sethlinnkuleuven** [comment]
I'm having this problem also. Anyone figure it out?

**Comment by christianmerges** [comment]
Same here so the issue is still there.

**Comment by sleidig** [comment]
It's a bit confusing what to do exactly, even with the answer [here in the second comment](https://github.com/oauth2-proxy/oauth2-proxy/issues/1913#issuecomment-1334087261). You need the following steps (as far as I understand and tested):

1. Edit the Keycloak Client you use for the oauth2-proxy
2. Go to "Client Scopes" and edit the dedicated scope
3. Add mapper (by configuration):
   - "Audience" mapper type and explicitly add the client ID as "included client audience"

We have documented it in the context of one of our systems for our admins here: https://github.com/Aam-Digital/aam-services/blob/main/docs/modules/export.md#oauth-proxy--keycloak-client
