### ISSUE TITLE
Post Login Redirect

### ISSUE THREAD

**Issue by shubhamdeodia** [oauth2-proxy/oauth2-proxy#1914]
## Expected Behavior

I have a requirement, where I need to redirect the user to a different sub-domain (in some cases a different domain). For example my app will be hosted on given sub-domain `docs.myapp.com`

and I want user to be able to redirect to `cloud.myapp.com` after they are authenticated.

## Current Behavior

I tried adding`rd=https://cloud.myapp.com` to the `redirect_url` parameter, however it doesn't work, `http://localhost:8080/oauth2/callback?rd="https://cloud.myapp.com"`

Is there any other solution to achieve the same as I am not using nginx in the front ?

Appreciate your help

- Version used:
7.4.0

**Comment by JoelSpeed** [comment]
What doesn't work about it? This issue is very light on details, if you can provide more background and context, maybe some example logs, we might be able to help dig into this further.

You look like you're on the right path with the `rd` query parameter though
