### ISSUE TITLE
Support arbitrary env var in alpha config

### ISSUE THREAD

**Issue by ledoyen** [oauth2-proxy/oauth2-proxy#1915]
Alpha config is already a great improvement as it allows fine configuration of upstreams (:hugs: url rewrite), and it will become even more interesting in the future, when _multiple providers_ will be released.

In opposition to the "legacy" configuration, there is no way to configure elements of the alpha config through environment variables.

However, I do see two use case for such late configuration:
* **sensitive information** (client id / secret, cookie secret, etc.), that you do not want to be left hardcoded in some file, that is solved today using the legacy configuration (but I assume it will disappear one day)
* **upstream uris**, that may be resolved/available at deploy time

## Expected Behavior

Either:
* read alpha configuration from env vars such as `OAUTH2_PROXY_UPSTREAM_CONFIG_UPSTREAMS_0_URI`
* allow to write configuration such as:
```yml
upstreamConfig:
  upstreams:
    - id: my_app
      path: ^/myapp/(.*)$
      rewriteTarget: /$1
      uri: ${env:MYAPP_URI}
```

## Current Behavior

No current equivalent.

## Possible Solution

Not being familiar with Go or even Viper, I am not sure what solution is best / simplest to implement.

Simply referring to opened thread https://github.com/spf13/viper/issues/339, it seems that enabling `.AutomaticEnv()` on the [viper instance parsing YAML](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/apis/options/load.go#L142-L146) could suffice.

It should allow to write an env var such as `OAUTH2_PROXY_ALPHA_UPSTREAM_CONFIG_UPSTREAMS='[{"id": "m_app", "path": "^/myapp/(.*)$", "rewriteTarget": "/$1", "uri": "https://???"}]'`.
This would allow to supply multiple upstreams with url rewriting in a dynamic way.

**Comment by hevans-dglcom** [comment]
Hi - I have covered this usecase in my upstream build (that uses multiple providers in production), but I don't have the time atm to write tests, add documentation etc to create a proper PR.

But here is the code for this particular change in /pkgs/options/load.go 

```
import (
  "github.com/drone/envsubst"
)

// LoadYAML will load a YAML based configuration file into the options interface provided.

func LoadYAML(configFileName string, into interface{}) error {
	v := viper.New()
	v.SetConfigFile(configFileName)
	v.SetConfigType("yaml")
	v.SetTypeByDefaultValue(true)

	if configFileName == "" {
		return errors.New("no configuration file provided")
	}

	data, err := ioutil.ReadFile(configFileName)
	if err != nil {
		return fmt.Errorf("unable to load config file: %w", err)
	}
        
        // We now parse over the yaml with env substring, and fill in the ENV's
	datastring, err := envsubst.EvalEnv(string(data))
	if err != nil {
		return fmt.Errorf("error in substituting env variables : %w", err)
	}

	data = []byte(datastring)

	// UnmarshalStrict will return an error if the config includes options that are
	// not mapped to felds of the into struct
	if err := yaml.UnmarshalStrict(data, into, yaml.DisallowUnknownFields); err != nil {
		return fmt.Errorf("error unmarshalling config: %w", err)
	}

	return nil
}
```

**Comment by hevans-dglcom** [comment]
tbh i think probably you can delete all the viper methods from the top of this function too, they are not actually used in the function

**Comment by hevans-dglcom** [comment]
actually don't even worry, had some time to implement :)

**Comment by ledoyen** [comment]
Still relevant, waiting for #1922 to be merged
