### ISSUE TITLE
Behavior change in v7.4.0: Redis Idle Timeout

### ISSUE THREAD

**Issue by adriankostrubiak-tomtom** [oauth2-proxy/oauth2-proxy#1917]
Using the same configuration, upgrading from v7.3.0 to v7.4.0 results in an unexpected change in behavior around Redis idle connection timeouts.  I believe this regression to have occurred with #1691 .

## Expected Behavior

If I do *not* specify `--redis-connection-idle-timeout`, I expect oauth2-proxy to use the default Redis configurations, which based on the [source code](https://github.com/go-redis/redis/blob/4bda6ec2fb4a836bbffc0032ad3a0f2f79528ccb/options.go#L107-L114) default the timeout to 30minutes

## Current Behavior

If I do *not* specify `--redis-connection-idle-timeout`, the Redis idle connection timeout is set to `0`, which based on the [source code](https://github.com/go-redis/redis/blob/4bda6ec2fb4a836bbffc0032ad3a0f2f79528ccb/options.go#L107-L114) means that connections will never be closed.

I believe this behavior to be a result of [this change](https://github.com/oauth2-proxy/oauth2-proxy/pull/1691/files#diff-12eb03d2e4162320c9a848db9eb444ca2bbf9fc19e11d5756f85aaf1a9e38d85)

## Possible Solution

I think there's a few options on the table for resolving this.

It would be possible to adjust the changes from #1691 to *only* configure the redis idle timeout if it has explicitly specified. This would likely mean using a pointer for the configuration, and adjusting how the redis client is instantiated.

It could also be decided that this is the desired behavior; in that case, I'd suggest an update to documentation.

## Steps to Reproduce (for bugs)

1.  Configure oauth2-proxy v7.3.0 to use redis. This results in a redis client with a default of 30min idle connection timeouts
2.  Upgrade oauth2-proxy to v7.4.0. This results in a redis client with no idle connection timeouts

## Context

This is an unexpected change for us, and has caused some amount of outage in our testing environments.  Previously, idle connections were getting timed out; now they remain forever.  However, there are other components - Azure Load Balancers, proxies, etc - that can close the connection.  Some components, notably Azure Load Balancers, may not "appropriately" close the TCP connection - no TCP RST is sent, by default. ([ref](https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset#tcp-reset)). Since the connection has been closed, but the redis client is un aware of it (due to lack of TCP RST), this results in errors such as:
```
[stored_session.go:97] Error removing session: error clearing the session from redis: write tcp 1.2.3.4:45430->2.3.4.5:6380: write: broken pipe

[stored_session.go:94] Error loading cookied session: failed to load the session state with the ticket: error loading redis session: write tcp 1.2.3.4:45430->2.3.4.5:6380: write: broken pipe, removing session
```
Ultimately leaving a client unable to authenticate.

We've resolved this for our deployments by explicitly setting `--redis-connection-idle-timeout=220`, which is a value less than the default Azure Load Balancer timeout, but I think this change in behavior in oauth2-proxy will be unexpected for many others in Azure environments.

## Your Environment

Deployed in Azure Kubernetes cluster in istio service mesh.

- Version used:
v7.4.0

Finally, I'd be happy to take on looking into a fix if that's what's decided as the right path forward here.

**Comment by JoelSpeed** [comment]
CC @Dimss I think you introduced this change

Yes, the expected behaviour you've described is correct, and I agree this is a bug, if you have time to work out how to resolve this, that would be great! PR definitely welcome for this

**Comment by Dimss** [comment]
@adriankostrubiak-tomtom @JoelSpeed 

Just to clarify,

Before the https://github.com/oauth2-proxy/oauth2-proxy/pull/1691 fix, the default idle timeout was [30 minutes](https://github.com/go-redis/redis/blob/4bda6ec2fb4a836bbffc0032ad3a0f2f79528ccb/options.go#L107-L114).
As a result, if on the Redis side, [Redis timeout option](https://redis.io/docs/reference/clients/#client-timeouts) was set to non zero value, the https://github.com/oauth2-proxy/oauth2-proxy/issues/1690 occurred.   

After the fix, the default timeout is set to `0`, meaning never close connection, and this actually what brakes the backward compatibility, right? 

If the above is correct, isn't it enough to set the default value for `--redis-connection-idle-timeout` to 30 minutes?

**Comment by JoelSpeed** [comment]
As far as I can tell, you're correct and we should restore the original behaviour, or, take the opportunity to set some other reasonable default timeout, since we already made a breaking change.

I'm ok with going for the default being 30m if you think that's the best path forward to restore the old behaviour
