### ISSUE TITLE
Question:How do I make a request to UpStream using the X-Forwarded-Host header?

### ISSUE THREAD

**Issue by matyuda** [oauth2-proxy/oauth2-proxy#1919]
Hi. I'm using OAuth2Proxy in CloudFornt-ALB-ECS configuration.

According to the documentation below, I understand that setting reverse_proxy=true will cause the request to UpStream with the X-Forwarded-{Proto,Host,Uri} header appended.
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#command-line-options

However, when I ran the container that displays the results of phpinfo with UpStream, X-forwarded-Proto was appended, but X-Forwarded-Host, X-Forwarded-Uri was not appended.

<img width="917" alt="phpinfo" src="https://user-images.githubusercontent.com/24763623/205605681-902d6599-1635-4299-971a-ea166bf0ebba.png">

How do I get attached?

Dockerfile
```
FROM quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
COPY oauth2-proxy.cfg /etc/
ENTRYPOINT ["/bin/oauth2-proxy", "--config=/etc/oauth2-proxy.cfg"]
```

oauth2-proxy.cfg
```
upstreams = [
     "http://localhost/"
]
email_domains="*"
oidc_email_claim="sub"
reverse_proxy=true
whitelist_domains=".XXXXXXXX.jp:*"
```

TaskDefinition Settings(Excerpt from the environment variable part only)
```
[
          {
            name  = "OAUTH2_PROXY_COOKIE_SECRET"
            value = "yyyyyyyyyyyyyyyyyyyy"
          },
          {
            name  = "OAUTH2_PROXY_COOKIE_SECURE"
            value = "false"
          },
          {
            name  = "OAUTH2_PROXY_COOKIE_NAME"
            value = "oauth2_proxy"
          },
          {
            name  = "OAUTH2_PROXY_PROVIDER"
            value = "keycloak-oidc"
          },
          {
            name  = "OAUTH2_PROXY_CLIENT_ID"
            value = "webApplication"
          },
          {
            name  = "OAUTH2_PROXY_CLIENT_SECRET"
            value = "xxxxxxxxxxxxxxxxxxx"
          },
          {
            name  = "OAUTH2_PROXY_OIDC_ISSUER_URL"
            value = "https://XXXXXXXXX/auth/realms/YYY"
          },
          {
            name  = "OAUTH2_PROXY_HTTP_ADDRESS"
            value = "8888"
          },
          {
            name  = "OAUTH2_PROXY_REDIRECT_URL"
            value = "https://XXXXXXXXX/oauth2/callback"
          },
          {
            name  = "OAUTH2_PROXY_SKIP_PROVIDER_BUTTON"
            value = "true"
          }
]
```

**Comment by JoelSpeed** [comment]
OAuth2 Proxy doesn't create the headers, it only passes them through, so you would need it coming from the ALB IIRC
