### ISSUE TITLE
oauth2-proxy Keycloak provider not working

### ISSUE THREAD

**Issue by iamaverrick** [oauth2-proxy/oauth2-proxy#1931]
we are deploying oauth2 proxy using helm packaged by bitnami and the service deployed and works as expected. issue comes in while configuring a provider which in our case is keycloak. we are following the example provided in the [docs ](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#keycloak-oidc-auth-provider), but the version of keycloak that we use doesn't have mapper. we are using keycloak version 19.0.3.
```
Create a mapper with Mapper Type 'Group Membership' and Token Claim Name 'groups'.
Create a mapper with Mapper Type 'Audience' and Included Client Audience and Included Custom Audience set to your client name.
```

## Expected Behavior

configure oauth2-proxy with keycloak recent versions or with out mappers.

## Current Behavior

unable to configure oauth2-proxy with keycloak recent version.

## Steps to Reproduce (for bugs)

deployment of oauth works fine is the configuration of keycloak the problem at the moment. either we need to update the docs to state the version it currently supports, our upgrade oauth2-proxy to support more recent versions. 

## Your Environment

Vmware Tanzu K8s bare metal

- Version used:
- oauth2-proxy v7.4.0
- keycloak v19.0.3.

**Comment by JoelSpeed** [comment]
You'll want to work with the keycloak user group for this probably, maintainers here aren't keycloak experts, apologies

**Comment by gitgabz** [comment]
@iamaverrick Keycloak has changed their default admin console theme to Admin2 in later versions, the layout of this console is a bit different than what is described in the documentation for Oauth2-proxy but the settings and features are still there.

I will try to add some context on how to configure it in the new console allthough this is a Keycloak specific task and not Oauth2-proxy

To configure the local client mappers in the Admin2 panel (*that I am guessing that you are using), navigate to:
	
	Clients -> {your client} -> Client scopes

In the Admin2 panel the "mappers pane" should be named {your client name}-dedicated under "Assigned client scope" and have a description of "Dedicated scope and mapper for this client"
Clicking the link should direct you to the "dedicated scopes" page for a given client.

Generating the mappers should be more or less similar to the current documentation.

1st. mapper

	Configure a new mapper -> Group Membership
		Name: client-group-mapper
		Token Claim Name: groups
		Full group path: If this is turned on there will be a / delimeter on the group names with a complete path for subgroups if any.

2nd. mapper

	Add mapper -> By configuration -> Audience
		Name: aud-mapper-client
		Include Client Audience: [select your client from the dropdown]
	
If you have a user and groups defined in you Keycloak instance you may evaluate and see what the access token will contain.

	Go to: 	clients -> {your client} -> client scopes -> Evaluate [Should be next to the setup tab]
		User: [select a known user in the realm]
			Click "Generate access token"
				Now a sample token structure should be displayed and you should be able to see that both [aud] and [groups] claims are set.

---

If you would like to see the difference in the console you could start up keycloak and oauth2-proxy locally.

# Old administrator web console on 19.0.2
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=development quay.io/keycloak/keycloak:19.0.2 start-dev --features-disabled=admin2

# New Admin2 web console as default on 19.0.2
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=development quay.io/keycloak/keycloak:19.0.2 start-dev		
		
http://localhost:8080

@JoelSpeed would you like a pr. on the documentation ?

**Comment by iamaverrick** [comment]
Hello @JoelSpeed,

I don't think this issue has anything to do with keycloak and its maintainers; as @gitgabz stated, this was an issue with the oauth2 proxy documentation. I was able to add the proper mappers to the configuration. I want to thank @gitgabz for his support on this matter. This should be reflected in the documentation, so other developers don't have this issue. I want to note that I still need help to implement this following the docs. Now I'm getting a 500 Internal Server Error when I successfully auth via the proxy auth service.

**Comment by miguelborges99** [comment]
@gitgabz,  I would say that it is a good idea to do a PR for the documentations.

**Comment by JoelSpeed** [comment]
if anyone can raise a PR to update the documentation, that would very much be appreciated, thanks

**Comment by gitgabz** [comment]
@JoelSpeed I have added a suggestion for the keycloak-oidc provider documentation in regard to the the new default Admin2 web console of Keycloak v19.0.0 and above. It should describe in some detail how to create a client, claims, user and realm roles/groups.
Made sure to add a comment that the user should consult the Keycloak documentation as this is only meant to kick-start a sample integration.

https://github.com/oauth2-proxy/oauth2-proxy/pull/1999
gitgabz:oauth2-proxy_keycloak-oidc_provider_documentation_#1931

**Comment by brsolomon-deloitte** [comment]
Please re-open. Not stale and still occurring with oauth2-proxy v7.4.0 and Keycloak 21.x.

oauth2-proxy fails with keycloak-oidc using the examples currently shown in the oauth2-proxy docs.

**Comment by bayerlse** [comment]
Having the same issue here! my generated service account tokens from keycloak wont work. it always states:

`Error retrieving session from token in Authorization header: [unable to verify bearer token, could not create session from token: audience from claim aud with value [MY_DEFAULT_CLIENT account] does not match with any of allowed audiences map[MY_DEFAULT_CLIENT:{}], audience from claim aud with value [MY_EXTRA_CLIENT account] does not match with any of allowed audiences map[MY_EXTRA_CLIENT account:{}]]`

**Comment by 3213-cmd** [comment]
@iamaverrick did you by any chance find a solution for the issue? https://github.com/oauth2-proxy/oauth2-proxy/issues/1931#issuecomment-1379362296

**Comment by WolfMa99** [comment]
In Keycloak you have to go to Clients->(client-id)->Client scopes->(client-id)-dedicated->Add mapper->By configuration->Audience

Name: (client-id)-audience
Included Custom Audience: (client-id)
Tick Add to ID token
Click Save

Switch to Scope
Untick Full scope allowed

Back to Clients->(client-id)->Client scopes->Evaluate->Users: (client-id)->Generated access token

Check aud

--

Did it work for you?

**Comment by vinzcoco** [comment]
Thank you @WolfMa99, your config worked for me!
