### ISSUE TITLE
Question: How to create custom provider auth UI : expected response format (cookie)

### ISSUE THREAD

**Issue by softyn** [oauth2-proxy/oauth2-proxy#1932]
I am implementing custom provider and I am currenlty using keycloak configuration providing own UI for auth.
Later I am redirecting back to aouth2-proxy redirect url providing prepared cookie.
However, I am getting error decoding _oauth2_proxy cookie. Initially I thought it's just 1 value expected in that cookie (token or code). 

I haven't found description of that cookie format and any other requirements of such custom auth UI.

Could you provide short example (could be javascript code) of composing that cookie together with sample encryption so it could be later properly handled by oauth2-proxy (especially line 2nd and 3rd of my example bellow) ?

Something like :
var restCallToCustomAuth_Result = Rest(https://..../auth , headers: OAUTH2_PROXY_CLIENT_ID/OAUTH2_PROXY_CLIENT_SECRET);
var oauth2-proxy_cookie_content = { field: restCallToCustomAuth_Result.field1, ... };
return Encrypt(EncMethod, OAUTH2_PROXY_COOKIE_SECRET, oauth2-proxy_cookie_content );

**Comment by JoelSpeed** [comment]
The OAuth2 Proxy cookie is considered internal to the project, you must create the cookie by going through the authentication flow and ending up back at the OAuth2 Proxy callback endpoint. We deliberately do not publish the cookie schema as this is subject to change over time.

If you want to customise the login, that is possible, you can even skip the OAuth2 Proxy login page should you so desire to do so
