### ISSUE TITLE
Notate broken/WIP issues in docs

### ISSUE THREAD

**Issue by sfxworks** [oauth2-proxy/oauth2-proxy#1938]
Hey all. I request these issues be noted in documentation as they are major hurdles for someone getting started. 
My story in a nutshell

https://github.com/oauth2-proxy/oauth2-proxy/issues/1724 (couldnt get scope issue working, moved to keycloak)
https://github.com/oauth2-proxy/oauth2-proxy/issues/1913 (still couldnt get keycloak working after this, moved to gittea)
https://github.com/oauth2-proxy/oauth2-proxy/issues/1636 (had to explicitly specify the arm image)

**Comment by tuunit** [comment]
Especially the issue with scope should be noted. I would fully support to note the issues in the documentation. Would you like to create a PR for it?

**Comment by sfxworks** [comment]
I'm on a bit of a break until January so if you wish to do so before me go ahead

**Comment by brsolomon-deloitte** [comment]
Please re-open. Not stale and still occurring with oauth2-proxy v7.4.0 and Keycloak 21.x.

oauth2-proxy fails with keycloak-oidc using the examples currently shown in the oauth2-proxy docs.

**Comment by tuunit** [comment]
Hi @brsolomon-deloitte I would love to help out and take another look at the issue. Can you share some more details about how you configured your oauth2-proxy. Which flags and/or config file settings you used would a great starting point.
