### ISSUE TITLE
Azure and Oauth2 JWT does not exist

### ISSUE THREAD

**Issue by LucaCre** [oauth2-proxy/oauth2-proxy#1939]
Azure and Oauth2 JWT does not exist

## Expected Behavior

Current setup:
AD Groups are mapped to roles in Azure App Registration and Enterprise App.
Oauth2-Proxy 7.3.0 with https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy helm chart version 6.5.0.
- provider: oidc (# v7.3.0 breaks azure provider #1666)

## Current Behavior

In the oauth2-proxy log we can see the group id which is sent from azure. In the backend Application does not appear any jwt token. I would expect to see at least a jwt token. Our goal is to have the roles in the jwt token. So we can validate permissions in the backend.

## Possible Solution
???

## Steps to Reproduce (for bugs)

config:
  configFile: |-
extraEnv:
  - name: OAUTH2_PROXY_HTTP_ADDRESS
    value: "0.0.0.0:4180"
  - name: OAUTH2_PROXY_EMAIL_DOMAINS
    value: "*"
  - name: OAUTH2_PROXY_COOKIE_SECURE
    value: "false"
  - name: OAUTH2_PROXY_COOKIE_SECRET
    value: "XXXX"
  - name: OAUTH2_PROXY_REDIRECT_URL
    value: "https://mydomain/oauth2/callback"
  - name: OAUTH2_PROXY_AUTH_LOGGING
    value: "true"
  - name: OAUTH2_PROXY_AUTH_LOGGING_FILENAME
    value: "/etc/oauth2_proxy/auth.log"
  - name: OAUTH2_PROXY_REQUEST_LOGGING_FILENAME
    value: "/etc/oauth2_proxy/request.log"
  - name: OAUTH2_PROXY_STANDARD_LOGGING_FILENAME
    value: "/etc/oauth2_proxy/standard.log"
  - name: OAUTH2_PROXY_ERRORS_TO_INFO_LOG
    value: "true"
  - name: OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR
    value: "true"
  - name: OAUTH2_PROXY_REQUEST_LOGGING
    value: "true"
  - name: OAUTH2_PROXY_STANDARD_LOGGING
    value: "true"
  - name: OAUTH2_PROXY_COOKIE_REFRESH
    value: "1h"
  - name: OAUTH2_PROXY_FOOTER
    value: "XXX"
  - name: OAUTH2_PROXY_REVERSE_PROXY
    value: "true"
  - name: OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR
    value: "true"
alphaConfig:
  enabled: true
  annotations: {}
  serverConfigData:
    SecureBindAddress: ''
    TLS: null
  metricsConfigData: 
    SecureBindAddress: ''
    TLS: null
  configData:
    injectRequestHeaders:
    - name: X-Forwarded-Groups
      values:
        - claim: groups
    - name: X-Forwarded-User
      values:
        - claim: user
    - name: X-Forwarded-Email
      values:
        - claim: email
    - name: X-Forwarded-Preferred-Username
      values:
        - claim: preferred_username
    - name: Authorization
      values:
        - claim: id_token
          prefix: 'Bearer '
    injectResponseHeaders:
    - name: X-Auth-Request-User
      values:
        - claim: user
    - name: X-Auth-Request-Email
      values:
        - claim: email
    - name: X-Auth-Request-Preferred-Username
      values:
        - claim: preferred_username
    - name: X-Auth-Request-Groups
      values:
        - claim: groups
    - name: Authorization
      values:
        - claim: id_token
          prefix: 'Bearer '
    providers:
    - provider: oidc
      clientSecret: XXX
      clientID: XXX
      oidcConfig:
        issuerURL: https://login.microsoftonline.com/XXX
        emailClaim: email
        userIDClaim: email
        groupsClaim: groups
        insecureSkipIssuerVerification: true
        insecureAllowUnverifiedEmail: true
        insecureSkipNonce: true
        audienceClaims:
        - aud
      force_code_challenge_method: S256
      id: azure
      name: azure
      scope: "openid email profile custom"
      azureConfig:
        tenant: XXX
    upstreamConfig:
      upstreams:
      - id: static://202
        path: /
        static: true
        staticCode: 202

## Context

Is there any bug which prevent oauth2-proxy from reading the values from azure. Or why we don't see any jwt token ?

**Comment by JoelSpeed** [comment]
Can you share a redacted version of the authentication logs from your login? It will say whether you are storing the `id_token` or not, if you aren't storing one, then the header will not be passed through. The Alpha config looks about right though

**Comment by LucaCre** [comment]
It was an ingress annotation error. With the following annotation it works and the jwt appears:
nginx.ingress.kubernetes.io/auth-response-headers: >-
      X-AUTH-REQUEST-EMAIL, X-AUTH-REQUEST-GROUPS, AUTHORIZATION

**Comment by gannaramu** [comment]
@JoelSpeed any plans of including id_token as part of the default config? this seems to be the only way to include appRoles from azure ad in the response header to the upstream app when using the auth_url approach on ingress-nginx
