### ISSUE TITLE
Cookie splitting status update?

### ISSUE THREAD

**Issue by benjaminmposnick** [oauth2-proxy/oauth2-proxy#1940]
## Expected Behavior
I'm getting the following error when I deploy an `oauth2-proxy` sidecar along with my Kubernetes application:
```
[2022/12/19 19:42:42] [session_store.go:163] WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.
```
My cookie is split into two smaller cookies: one that's 3918 bytes and one that's 400 bytes. I do not have the ability to use a Redis cache very easily for our use case. So I wanted to confirm: is this warning simply just a notification for the application developer, or is should this be treated as an error (implying we should switch to Redis if this warning appears)? I just want to ask whether proceeding with this warning present is safe, or if it will cause issues in the long run?

## Your Environment
- Version used: 7.2.0

**Comment by JoelSpeed** [comment]
My preference would be that you treat this as an error. I want to deprecate the splitting feature in the future as it has caused nothing but trouble!

My recommendation, if you can't set up redis (there is a redis operator for kubernetes that you could use?), would be to look at implementing a server side session store within OAuth2 Proxy. I think there is a possibility we could even create an implementation based on Kubernetes secrets, which would make it super easy to deploy to Kube

**Comment by benjaminmposnick** [comment]
> My preference would be that you treat this as an error. I want to deprecate the splitting feature in the future as it has caused nothing but trouble!
> 
> My recommendation, if you can't set up redis (there is a redis operator for kubernetes that you could use?), would be to look at implementing a server side session store within OAuth2 Proxy. I think there is a possibility we could even create an implementation based on Kubernetes secrets, which would make it super easy to deploy to Kube

Hi @JoelSpeed, thanks for your response! We don't have the ability to easily set-up Redis in our environment, since our company has an in-house software package that wraps Redis and does some additional things. Do you have any documentation or examples I could look at for setting up a server-side session store within `oauth2-proxy`? I'm happy to treat this warning as an error, any help and/or pointers you could provide to mitigate this would be greatly appreciated. Thank you!

**Comment by benjaminmposnick** [comment]
Hi @JoelSpeed, just following up on the above message. Thanks!

**Comment by r-kotagudem** [comment]
> My preference would be that you treat this as an error. I want to deprecate the splitting feature in the future as it has caused nothing but trouble!
> 
> My recommendation, if you can't set up redis (there is a redis operator for kubernetes that you could use?), would be to look at implementing a server side session store within OAuth2 Proxy. I think there is a possibility we could even create an implementation based on Kubernetes secrets, which would make it super easy to deploy to Kube

@JoelSpeed could you brief on what kind of trouble would it cause to use cookie as session store. since we want to use cookie in production instead of redis. as we have connectivity issues with redis and(additional overhead in using redis connection in each request)

**Comment by r-kotagudem** [comment]
> > My preference would be that you treat this as an error. I want to deprecate the splitting feature in the future as it has caused nothing but trouble!
> > My recommendation, if you can't set up redis (there is a redis operator for kubernetes that you could use?), would be to look at implementing a server side session store within OAuth2 Proxy. I think there is a possibility we could even create an implementation based on Kubernetes secrets, which would make it super easy to deploy to Kube
> 
> @JoelSpeed could you brief on what kind of trouble would it cause to use cookie as session store. since we want to use cookie in production instead of redis. as we have connectivity issues with redis and(additional overhead in using redis connection in each request?)

could you please reply on this? we want to clarify if cookie session store is continued in further versions of oauth2-proxy.or any plans to remove cookie session support from this app altogether

**Comment by JoelSpeed** [comment]
The cookie session store will never go away, but, if your session includes things like tokens, then you will bust the 4kb cookie capacity and it will currently split into multiple cookies, which is buggy and quite often causes issues.
To avoid this, you either need to use `session-cookie-minimal` which removes a number of features from the project (since we no longer store some of the tokens), or use a persistent session storage

I plan to deprecate the split cookies at some point in the future so if there's an alternate persistent session store you'd like to implement, I'm open to ideas for other key value stores

**Comment by benjaminmposnick** [comment]
I am seeing the following error after setting `session-cookie-minimal` to true. Could you provide some assistance @JoelSpeed?
```
Unable to connect to the server: failed to refresh token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Token is not active"}
```

**Comment by benjaminmposnick** [comment]
Is [this](https://github.com/oauth2-proxy/oauth2-proxy/issues/1940#issuecomment-1448561813) related to this issue? https://github.com/oauth2-proxy/oauth2-proxy/issues/1945

**Comment by JoelSpeed** [comment]
Seems like it might be related yes, if you have session cookie minimal I wouldn't expect refreshing to work, you'd have no refresh token/ID token to use for the refresh

**Comment by benjaminmposnick** [comment]
> Seems like it might be related yes, if you have session cookie minimal I wouldn't expect refreshing to work, you'd have no refresh token/ID token to use for the refresh

@JoelSpeed So is there a work around for our scenario then? Can we simply shutoff refresh somehow? If so, what are the implications of that?

**Comment by JoelSpeed** [comment]
> > Seems like it might be related yes, if you have session cookie minimal I wouldn't expect refreshing to work, you'd have no refresh token/ID token to use for the refresh
> 
> @JoelSpeed So is there a work around for our scenario then? Can we simply shutoff refresh somehow? If so, what are the implications of that?

You can set the refresh period to 0 to disable it, the implication is that users will have to re-authenticate more frequently. You'll need to set the cookie expire period to whatever duration you see fit as the maximal authentication period
