### ISSUE TITLE
Stop attempting to refresh access token for session if receiving "Session not active"

### ISSUE THREAD

**Issue by myspaghetti** [oauth2-proxy/oauth2-proxy#1945]
## Expected Behavior

Enhancement request: oauth2-proxy should stop attempting to refresh the session after receiving  `Response: {"error":"invalid_grant","error_description":"Session not active"}`

## Current Behavior

oauth2-proxy is configured with `cookie_refresh` and successfully refreshes the session cookie when the provider's session is active. When the session is not active, oauth2-proxy attempts to refresh the session about five times every two seconds and correctly gets the following error:
```
oauth2-proxy    | [2022/12/21 03:00:13] [stored_session.go:94] Error loading cookied session: error refreshing access token for session (Session{email:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx user:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx PreferredUsername:xxxx token:true id_token:true created:2022-12-21 02:54:44.27982877 +0000 UTC expires:2022-12-21 02:55:44.268840644 +0000 UTC refresh_token:true}): session is expired, removing session
oauth2-proxy    | [2022/12/21 03:00:13] [stored_session.go:193] Unable to refresh session: error refreshing tokens: unable to redeem refresh token: failed to get token: oauth2: cannot fetch token: 400 Bad Request
oauth2-proxy    | Response: {"error":"invalid_grant","error_description":"Session not active"}
```

## Possible Solution

Stop attempting to refresh the session after receiving  `Response: {"error":"invalid_grant","error_description":"Session not active"}` 

## Steps to Reproduce (for bugs)

1.  Set oauth2-proxy `cookie_refresh` to some value (mine is 5m)
2. Trigger provider session expiry
3. oauth2-proxy attempts to refresh cookie, gets provider response that the session expired
4. oauth2-proxy keeps attempting to refresh cookie for the expired session

## Context

The issue creates many unnecessary requests

## Your Environment

Docker internal network 

- Version used:
`Linux 5.4.0-135-generic` `Docker version 20.10.12` `nginx/1.22.1` `Keycloak 20.0.2` `oauth2-proxy:v7.4.0`

**Comment by JoelSpeed** [comment]
When the session is inactive on the cloud provider side, OAuth2 Proxy should invalidate the session and clear the cookie. This sounds like a bug to me.

PR welcome if anyone has time to work out how to fix this.

**Comment by myspaghetti** [comment]
Since oauth2_proxy returns `400 Bad Request` to `auth_request` the session is effectively invalidated and the protected resource cannot be accessed, so security-wise this is fine. If the webpage is reloaded, a login prompt appears as expected. However if the webpage is not reloaded, oauth2_proxy might keep making cookie refresh requests, as it does due to the content of my webpage.

I can see that session clearing is already implemented in [`stored_session.go` for `loadSession`](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/middleware/stored_session.go#L92) on another failure condition. Perhaps [`refreshSessionIfNeeded`](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/middleware/stored_session.go#L127) can be rate-limited, or it could look at [the resulting `err` from the provider](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/middleware/stored_session.go#L190) and give up if `Session not active` is part of the spec.

**Comment by myspaghetti** [comment]
Since oauth2_proxy returns `400 Bad Request` to `auth_request` the session is effectively invalidated and the protected resource cannot be accessed, so security-wise this is fine. If the webpage is reloaded, a login prompt appears as expected. However if the webpage is not reloaded, oauth2_proxy might keep making cookie refresh requests, as it does due to the content of my webpage.

I can see that session clearing is already implemented in [`stored_session.go` for `loadSession`](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/middleware/stored_session.go#L92) on another failure condition. Maybe [`refreshSessionIfNeeded`](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/middleware/stored_session.go#L127) can be rate-limited, or it could look at [the resulting `err` from the provider](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/middleware/stored_session.go#L190) and give up if `Session not active` is part of the spec.

At any rate, thanks for this great piece of software!

**Comment by myspaghetti** [comment]
`error_description` is [optional in the spec](https://www.ietf.org/rfc/rfc6749.txt) so oauth2-proxy definitely shouldn't rely on it. `invalid_grant` is part of the spec: "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client." So maybe when oauth2-proxy receives `invalid_grant` it should give up trying to refresh the cookie.

**Comment by akri16** [comment]
Are there any plans on this getting fixed?

**Comment by JoelSpeed** [comment]
We need someone to take the time to understand the issue and the code and put a PR forward for the fix

**Comment by davidfrickert** [comment]
Not sure if it helps but I ran into a similar situation while using OAuth2-proxy + Keycloak.
The error was "Token not active" and OAuth2-proxy was basically still keeping the session active while receiving this error which is not ideal.
The issue on my side was that I had a configuration on Keycloak:
Access Token lifespan: 5min
SSO Session Idle: 1min

This means that while the access token stated that it would expire in NOW() + 5min, the session itself on Keycloak would expire in NOW() + 1 min - assuming the scenario that the user doesn't refresh the token in the 1min idle time. 

Obviously these are quite extreme values but the same applies on higher values when Access token lifespan > SSO Session Idle.

In any case, I think that in these scenarios, the session should be invalidated if the error is of type `invalid_grant` as stated above. What is missing for the change to be implemented?

**Comment by abdutta** [comment]
To whoever visit this page for the issue mentioned above as by @davidfrickert . There is a setting in KeyCloak server to revoke refresh token. Enable it and KeyCloak will revoke the session.

**Comment by frhack** [comment]
I've been hitting this exact issue with Keycloak OIDC + Redis session store on v7.14.2.

When Keycloak invalidates a session (admin sign-out, logout from another app), OAuth2-Proxy detects the failure during `cookie-refresh` but silently continues serving the stale session. The user stays logged in indefinitely.

I wrote a patch that distinguishes between **fatal errors** (session actually revoked) and **transient errors** (network issues, KC temporarily down):

- Fatal: `invalid_grant`, `Session not active`, `Token is not active`, `invalid_client` → call `store.Clear()` to remove the Redis key + cookie, force re-authentication
- Transient: timeouts, DNS failures, 5xx → keep existing session (current behavior)

The change is ~30 lines in `pkg/middleware/stored_session.go` — adds an `isFatalRefreshError()` helper and calls `store.Clear()` in the existing error branch.

Tested in production with Keycloak 26 + Redis session store + `cookie-refresh=30s`. Cross-app SSO logout now works within 30 seconds.

Patch + Dockerfile for reproducible build: https://gist.github.com/frhack/f5664c652e9e0f65a48cae969c97ff56

Happy to open a PR if there's interest. Would the maintainers prefer this as a default behavior or behind a config flag?

**Comment by frhack** [comment]
> We need someone to take the time to understand the issue and the code and put a PR forward for the fix

I just released a working fix

Patch + Dockerfile for reproducible build: https://gist.github.com/frhack/f5664c652e9e0f65a48cae969c97ff56

**Comment by tuunit** [comment]
@frhack thank you for contributing but please don't respond with the same content to each and every comment written in this thread. My inbox got flooded with your responses.

**Comment by tuunit** [comment]
I would happily review a PR you open with your proposed change

**Comment by frhack** [comment]
> I would happily review a PR you open with your proposed change

Thanks! PR is up: #3333 

Checks only standard OAuth2 error codes (`invalid_grant`, `invalid_client`) per RFC 6749, not provider-specific `error_description` strings. Unit tests included.


Francesco
