### ISSUE TITLE
Azure provider in china

### ISSUE THREAD

**Issue by ebcFlagman** [oauth2-proxy/oauth2-proxy#1961]
I would use the newest version in our china envronment.

My actual configuration looks like:
```
--provider=azure
--email-domain=*
--upstream=http://localhost:8080/
--http-address=0.0.0.0:4180
--azure-tenant=<TENANT-ID>
--oidc-issuer-url=https://login.partner.microsoftonline.cn/<TENANT-ID>/v2.0
--login-url=https://login.chinacloudapi.cn/<PARTNER>/oauth2/authorize
--redeem-url=https://login.chinacloudapi.cn/<PARTNER>/oauth2/token
--resource=https://microsoftgraph.chinacloudapi.cn
--profile-url=https://microsoftgraph.chinacloudapi.cn/v1.0/me
```

Now when I would login i got the following error:
`invalid_resource. The resource principal named https://graph.microsoft.com was not found in the tenant named <TENANT-ID>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.`

I know that `graph.microsoft.com` must be `microsoftgraph.chinacloudapi.cn` but I have no clue how to configure.

**Comment by miguelborges99** [comment]
@ebcFlagman This seems to be an Azure missing configuration, not an oauth2-proxy issue. Maybe you should talk with your Azure administrator, or with Azure support if it is the case.

**Comment by erwen** [comment]
@ebcFlagman Have u find a way to fix this?

**Comment by ebcFlagman** [comment]
@erwen Unfortunately it's currently not our focus so the deep dive is on hold on my side

**Comment by erwen** [comment]
@ebcFlagman  Okay, thank u anyway

**Comment by erwen** [comment]
@ebcFlagman I found the root cause , the  azureV2Scope = "https://graph.microsoft.com/.default" hardcode in providers/azure.go, after changed it to china endpoint, it work as expect

**Comment by erwen** [comment]
@miguelborges99 Can we make it configurable as a external arg?
