### ISSUE TITLE
Keycloak needs to be exposed for login, otherwise 403 Forbitten

### ISSUE THREAD

**Issue by e36Alex** [oauth2-proxy/oauth2-proxy#1963]
Hi,

i want to run oauth2-proxy to use nginx auth-request against keycloak as IDP.
The actual problem is, that i have to expose (behind nginx) keycloak to login from outside my network, otherwise ii get redirected to the keycloak domain an get a 403 Forbidden error.
When i setup proxy_pass in nginx to keycloak host, i can login without problems.

## Expected Behavior
I expect, that oauth2-proxy will proxy the login form without exposing keycloak at the reverse-proxy

## Your Environment

nginx.conf for domain that should be protected:
`  location  /oauth2/ {
    proxy_pass       http://auth.domain.de:1080;
    proxy_set_header Host                    $host;
    proxy_set_header X-Real-IP               $remote_addr;
    proxy_set_header X-Scheme                $scheme;
    proxy_set_header X-Auth-Request-Redirect $request_uri;
    # or, if you are handling multiple domains:
    #proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
  }
  location  /oauth2/auth {
    proxy_pass       http://auth.domain.de:1080;
    proxy_set_header Host             $host;
    proxy_set_header X-Real-IP        $remote_addr;
    proxy_set_header X-Scheme         $scheme;
    # nginx auth_request includes headers but not body
    proxy_set_header Content-Length   "";
    proxy_pass_request_body           off;
    proxy_set_header X-Auth-Request-Redirect $request_uri;
    #set $args $args&allowed_groups=/ldap/gitlab;
  }

  location / {
    proxy_pass https://gitlab.domain.de;

    auth_request /oauth2/auth;
    error_page 401 = /oauth2/sign_in?rd=https://gitlab.domain.de/$request_uri;
    #error_page 401 = /oauth2/start;

    # pass information via X-User and X-Email headers to backend,
    # requires running with --set-xauthrequest flag
    auth_request_set $user   $upstream_http_x_auth_request_user;
    auth_request_set $email  $upstream_http_x_auth_request_email;
    proxy_set_header X-User  $user;
    proxy_set_header X-Email $email;

    # if you enabled --pass-access-token, this will pass the token to the backend
    auth_request_set $token  $upstream_http_x_auth_request_access_token;
    proxy_set_header X-Access-Token $token;

    # if you enabled --cookie-refresh, this is needed for it to work with auth_request
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $auth_cookie;
    # When using the --set-authorization-header flag, some provider's cookies can exceed the 4kb
    # limit and so the OAuth2 Proxy splits these into multiple parts.
    # Nginx normally only copies the first `Set-Cookie` header from the auth_request to the response,
    # so if your cookies are larger than 4kb, you will need to extract additional cookies manually.
    auth_request_set $auth_cookie_name_upstream_1 $upstream_cookie_auth_cookie_name_1;

    # Extract the Cookie attributes from the first Set-Cookie header and append them
    # to the second part ($upstream_cookie_* variables only contain the raw cookie content)
    if ($auth_cookie ~* "(; .*)") {
        set $auth_cookie_name_0 $auth_cookie;
        set $auth_cookie_name_1 "auth_cookie_name_1=$auth_cookie_name_upstream_1$1";
    }

    # Send both Set-Cookie headers now if there was a second part
    if ($auth_cookie_name_upstream_1) {
        add_header Set-Cookie $auth_cookie_name_0;
        add_header Set-Cookie $auth_cookie_name_1;
    }

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  }
}`

nginx.conf of oauth2-proxy:
`    set $oauth_proxy_hostname auth.domain.de; # Adjust as needed
    set $oauth_proxy_port 1080;
    set $oauth_proxy_proto http;

    location /oauth2/ {
        #include /config/nginx/resolver.conf;

        proxy_pass $oauth_proxy_proto://$oauth_proxy_hostname:$oauth_proxy_port;
        proxy_set_header Host                    $host;
        proxy_set_header X-Real-IP               $remote_addr;
        proxy_set_header X-Scheme                $scheme;
        proxy_set_header X-Auth-Request-Redirect $request_uri;
    }
    location /oauth2/auth {
        #include /config/nginx/resolver.conf;

        proxy_pass $oauth_proxy_proto://$oauth_proxy_hostname:$oauth_proxy_port;
        proxy_set_header Host             $host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Scheme         $scheme;
        # nginx auth_request includes headers but not body
        proxy_set_header Content-Length   "";
        proxy_pass_request_body           off;
    }
}`

nginx.conf of keycloak domain (just to get a ssl-cert with certbot)
`  location  / {
		deny all;
	}`

docker-compose.yml of oauth2-proxy:
`  oauth2-proxy:
      container_name: oauth2-proxy
      image: quay.io/oauth2-proxy/oauth2-proxy:latest
      ports:
      - "1080:1080"
      - "1443:1443"
      volumes:
      - /srv/docker-compose/oauth2-proxy/config/:/etc/oauth2-proxy/config
      environment:
        OAUTH2_PROXY_CONFIG: /etc/oauth2-proxy/config/oauth2-proxy.cfg
        OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
        OAUTH2_PROXY_EMAIL_DOMAINS: "*"
        OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
        OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
        OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
        OAUTH2_PROXY_OIDC_ISSUER_URL: "https://kc.domain.de/realms/private"
        OAUTH2_PROXY_COOKIE_DOMAINS: ".domain.de"
        OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:1080" # This assumes you're running in docker and public listening is OK. Adjust as needed
        OAUTH2_PROXY_HTTPs_ADDRESS: "0.0.0.0:1443" # This assumes you're running in docker and public listening is OK. Adjust as needed
        OAUTH2_PROXY_REVERSE_PROXY: "true"
        OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"
        OAUTH2_PROXY_LOGGING_FILENAME: "/dev/stdout"
        OAUTH2_PROXY_STANDARD_LOGGING: "true"
        OAUTH2_PROXY_STANDARD_LOGGING_FORMAT: "[{{.Timestamp}}] [{{.File}}] {{.Message}}"
        OAUTH2_PROXY_REQUEST_LOGGING: "true"
        OAUTH2_PROXY_REQUEST_LOGGING_FORMAT: "{{.Client}} - {{.Username}} [{{.Timestamp}}] {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}"
        OAUTH2_PROXY_AUTH_LOGGING: "true"
        OAUTH2_PROXY_AUTH_LOGGING_FORMAT: "{{.Client}} - {{.Username}} [{{.Timestamp}}] [{{.Status}}] {{.Message}}"
        OAUTH2_PROXY_PASS_HOST_HEADER: "false"
        OAUTH2_PROXY_SET_XAUTHREQUEST: "true" # Injects a bunch of user profile info. See link at top for more details.
        OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true" # Injects a signed token.
        OAUTH2_PROXY_WHITELIST_DOMAINS: ".domain.de"
        OAUTH2_PROXY_COOKIE_EXPIRE: "168h"
        OAUTH2_PROXY_COOKIE_SECURE: "true"
        OAUTH2_PROXY_COOKIE_HTTPONLY: "false"
        OAUTH2_PROXY_SESSION_STORE_TYPE: "redis"
        OAUTH2_PROXY_REDIS_CONNECTION_URL: "redis://10.0.0.10:6379"
        OAUTH2_PROXY_REDIS_PASSWORD: ${OAUTH2_PROXY_REDIS_PASSWORD}
        OAUTH2_PROXY_REDIRECT_URL: https://auth.domain.de/oauth2/callback
        OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
        OAUTH2_PROXY_LOGIN_URL: "https://kc.domain.de/realms/private/protocol/openid-connect/auth"
        
        OAUTH2_PROXY_UPSTREAM: "static://200"
        OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"`

- Version used:
latest docker image

**Comment by miguelborges99** [comment]
Don't you want to do a diagram explaining what you intend to do? Maybe someone in the community can help with some guidance. It is hard to look to all your config files, and give an answer.

**Comment by e36Alex** [comment]
I did my best to bring it in a diagram:

This is the way in should work in my expectation:
Oauth2-Proxy calls Keycloak (of course, there is firewall rule from "dmz" docker host to "internal" docker host.
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/26880334/212558844-b96bcb54-945f-47a8-9797-a0833340dea6.png">

But it acually just works, when i proxy_pass the keycloak url from nginx reverse proxy to the Keycloak container at the internel network. But this means, everyone from outside of my network can reach my keycloak container directly. This i would like to avoid.
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/26880334/212558982-6be76655-f5d8-4ed9-9ac6-788fcc274fd5.png">

**Comment by rafsaf** [comment]
Was looking in issues for something different, but couldn't help myself to answer, you prepared nice diagrams.

In short: Not possible to avoid keycloak exposition.

Long: Think about it, oauth2 proxy is just dummy redirect service, nothing more nothing less, it must use **something** to authenticate, may be some external service like github or self hosted keycloak. The only question is **who can access oauth2 proxy**, this part must also be able to access your auth provider (keycloak in this case). So if whole world should have access to oauth2 proxy, whole world should also have access to keycloak, if this is true only for some IP range, the same goes for keycloak.
At least access to non-admin part of keycloak.

**Comment by kfox1111** [comment]
To expand upon that slightly:
There's a million ways to authenticate. username/password, u2f keys, securid, the list goes on and on. One of the beauties of oidc is all that complexity gets stuck into one place, the security server (keycloak), so that all the web services don't have to have that logic anymore (oauth2-proxy and whats behind). But for that to work, it must be exposed.

**Comment by myspaghetti** [comment]
As others have said, oauth2-proxy only provides a way to use `auth_request` with nginx, it doesn't do the actual authentication. You don't have to expose all of Keycloak though, just the directories `realms`, `resources`, and `js`.  You can also remove users' ability to view their profile details, change passwords, etc. They'll still be able to see they're using Keycloak, but that's about it. You can put Keycloak on a subdirectory instead of a subdomain, too.

**Comment by e36Alex** [comment]
Thanks for your replies and your help.
 I think, i know what to do now! ;-)
