### ISSUE TITLE
Add option to alter variable values in logging format and redact some critical information

### ISSUE THREAD

**Issue by f-ld** [oauth2-proxy/oauth2-proxy#1965]
Add some options in log formats to get altered content from variable. For example instead of `{{.Username}}` be able to specify `{{.Username|function()}}` to get an altered version of username processed by `function()` and not `username@email.com`.

## Expected Behavior

Log formats can be customised using variables, for example `{{.Username}}` in format will be replaced by `username@email.com`.
But for security reasons, it could be interesting to alert the value, for example using `{{.Username|hash}}` to get a hashed version of the email address or `{{.Username|replace("@.*", "")}}` that would allow to replace parts of the value based on some regexp.

## Current Behavior

Current behaviour is only allowing to get full variable content (i.e. full username as `username@email.com`) or nothing. 

## Possible Solution

Add one or two functions to either:
- `hash()` that would hash the value based on some secret added in configuration. This would be the most secure version and OPS would have access to secret and be able to get back to original value from logs.
- `replace(regexp, replacement string)` that would search for `regexp` and  use `replacement` to replace the value. This would allow to remove domains or replace them with specific strings (but then we might want to apply more than one string regexp with different values so be able to pipe calls).

## Context

Full username is an email address reported as PII by security monitoring tools (and anyone having access to logs would then discover valid email addresses). But also in auth logging, the `{{.Message}}` may contain email addresses like in this log:

```
100.101.102.103:45678 - 0123456789abcdef0123456789abcdef - user.name@domain.com [2023/01/09 09:38:22] [AuthSuccess] Authenticated via OAuth2: Session{email:user.name@domain.com user: PreferredUsername:uname@domain.com token:true id_token:true created:2023-01-09 09:38:22.092367694 +0000 UTC m=+2312584.514006384 expires:2023-01-09 10:38:21.963297314 +0000 UTC m=+2316184.384936012}
```

## Your Environment

k8s cluster with helm chart 6.5.0 deploying version 7.3.0 of app.

**Comment by miguelborges99** [comment]
I think you can use a something, like {{.Username | printf "%.4s*******" }}
which will print the first 4 characters and the rest is filled with '*'  --> user*******

Is sufficient for you?

You have to change the standard logging, request loggin and auth-logging using the options:

	--standard-logging-format
	--request-logging-format
	--auth-logging-format

See the [logging configurations](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#logging-configuration) for more details.

Just as a curiosity, there is a library with template functions, named [Sprig](http://masterminds.github.io/sprig/), which could be added to the project. But, it is one more dependency and it could bring vulnerabilities. Maybe it is not worthy...
