### ISSUE TITLE
Option for per-route group authorization.

### ISSUE THREAD

**Issue by jonbonazza** [oauth2-proxy/oauth2-proxy#1966]
We are looking at migrating away from an in-house IAP solution to something open source, and this project is the most ideal candidate that we've found. It actually functions almost exactly like our own in-house solution. There is one missing feature that our devs rely on though and that's what we call "path-based authorization." Essentially, we require a way to provide something like a YAML file that defines a list of routes and allowed "scopes" (or in the case of this project, maybe "groups" makes the most sense) that are allowed to access that route. So if in the file we have `/foo` which allows the scopes `bar` and `baz`, then if a request comes in for route `/foo` and the provided JWT doesn't include either `bar` or `baz` in the list of scopes (or groups or w/e) then it will automatically be rejected with a `401 UNAUTHORIZED`. This allows upstream services to not have to care about inspecting the request's JWT for scopes/groups and can rely on the IAP to do the right thing for them. This reduces code complexity and makes local testing easier.

I've already started implementing this in a way I believe make sense, but I wanted to know whether a) such a feature would be accepted and b) if there were any requirements and/or implementation suggestions you had as maintainers of the project.

**NOTE: I didn't really follow the Issue Template with this issue because the template seems to be designed more for bugs, rather than feature requests. If you want me to change the format of this issue, please let me know and I'd be happy to oblige.**

**Comment by jonbonazza** [comment]
Ping.

**Comment by ibizaman** [comment]
@jonbonazza This is a feature I'm very much interested in too. Would you mind sharing what you already implemented?

**Comment by ibizaman** [comment]
Has been implemented in #2011

**Comment by ibizaman** [comment]
Mmh I guess I triggered closing this issue. It should still be open though.
