### ISSUE TITLE
Issuer verification in combination with keycloak-oidc backchannel

### ISSUE THREAD

**Issue by jwie-idirect** [oauth2-proxy/oauth2-proxy#1969]
Keycloak allows using a [backchannel](https://www.keycloak.org/server/hostname) (different url than the from which the frontend is accessed) to obtain a token. The tokens however still contain the valid issuer url (based on the frontend url). 

## Expected Behavior

Oauth2 proxy should be able to validate the issuer in the token, based on the issuer that is returned in the ".well-known/openid-configuration" endpoint. For example if the frontend-url is `http://127.0.0.1.nip.io:8080` and the following url is accessed: `http://localhost:8080/realms/master/.well-known/openid-configuration`, keycloak will return:
```json
{
    "issuer": "http://127.0.0.1.nip.io:8080/realms/master",
    "authorization_endpoint": "http://127.0.0.1.nip.io:8080/realms/master/protocol/openid-connect/auth",
    "token_endpoint": "http://localhost:8080/realms/master/protocol/openid-connect/token",
    "introspection_endpoint": "http://localhost:8080/realms/master/protocol/openid-connect/token/introspect",
    "userinfo_endpoint": "http://localhost:8080/realms/master/protocol/openid-connect/userinfo",
    "end_session_endpoint": "http://127.0.0.1.nip.io:8080/realms/master/protocol/openid-connect/logout",
   ....
}
```
The links useful for backchannel communication are adapted, but all others (including issuer) use the frontend url.

## Current Behavior

Currently it's only possible to make this scenario work by specifying the "--insecure-oidc-skip-issuer-verification=true", which seems to skip:
* matching the issuer in the ".well-known/openid-configuration" to the --oidc-issuer-url parameter (which is ok)
* matching the issuer in the token to the one returned by ".well-known/openid-configuration"  (which is not ok, since the issuer returned by this endpoint is the one that should be used in the token)

## Possible Solution

One possibility is to not skip issuer verification and use the issuer returned by the ".well-known/openid-configuration" endpoint.

## Your Environment

- Version used: 7.4.0

**Comment by miguelborges99** [comment]
In the https://www.rfc-editor.org/rfc/rfc8414.html#section-3.3, it seems that the issuer retrieved by discovery endpoint should be equal to the authorization server's issuer, but this keycloack backchannel breaks the RFC.
To make such a change does not seems to be easy, since parts of the code which deals with issuer urls and issuer validation seem to be generic, and used by other providers.

**Comment by jwie-idirect** [comment]
I indeed agree that it's not following the spec. 
I didn't dig in the code but I think using the issuer returned from the discovery endpoint doesn't break the providers that follow the spec (since it matches currently used url and this is also checked when insecure-oidc-skip-issuer-verification is set to false).

**Comment by miguelborges99** [comment]
To have the code clean, I would think in splitting the code in terms of checks, one for providers that follow the spec and a specific for keycloak oidc. Also storing the retrieved issuer in a variable, different from options, and probably have an option, we may think of a good name for that, to setup this backchannel configuration (e.g. --uses-backchannel=true/false), and only valid for keycloak oidc. It could work with less more effort in terms of code refactoring, but I think it is not the biggest issue.

If I think about it, how secure is the issuer verification check when backchannel is used? Any issuer can be retrieved if an attack occurs,  different from the one that is expected. So, in terms of concept, should I consider that issuer verification is secure (i.e. --insecure-oidc-skip-issuer-verification=false) when I only make partial checks, and ignore others?

**Comment by miguelborges99** [comment]
Maybe, we should do like we have in quarkus.
They have two issuers:

[quarkus.oidc.auth-server-url](https://quarkus.pro/guides/security-openid-connect-multitenancy.html#quarkus-oidc_quarkus.oidc.auth-server-url)

The base URL of the OpenID Connect (OIDC) server, for example, 'https://host:port/auth'. All the other OIDC server page and service URLs are derived from this URL. Note if you work with Keycloak OIDC server, make sure the base URL is in the following format: 'https://host:port/auth/realms/{realm}' where '{realm}' has to be replaced by the name of the Keycloak realm.

[quarkus.oidc.token.issuer](https://quarkus.pro/guides/security-openid-connect-multitenancy.html#quarkus-oidc_quarkus.oidc.token.issuer)

Expected issuer 'iss' claim value.

**Comment by jwie-idirect** [comment]
I think it does. By configuring it explicitly it should also take away any security related concerns.

**Comment by miguelborges99** [comment]
still revelant

**Comment by SirSkizo** [comment]
Related: https://github.com/quarkusio/quarkus/issues/16294
