### ISSUE TITLE
oidcConfig.userIDClaim is apparently ignored

### ISSUE THREAD

**Issue by joel-bluedata** [oauth2-proxy/oauth2-proxy#1973]
## Expected Behavior

The alphaConfig.configData.providers[].oidcConfig.userIDClaim property is documented as:

> UserIDClaim indicates which claim contains the user ID
> default set to 'email'

From some code inspection, experimentation, and reading other issues... I would expect that this property's value would identify which token claim populates the "user" field of the session, which could then be referenced in e.g. injectResponseHeaders.

So with this:
```
      oidcConfig:
        userIDClaim: my_username_claim
```
and this:
```
    injectResponseHeaders:
      - name: My-Username-Header
        values:
          - claim: user
```
I would expect the "My-Username-Header" header to be injected, with a value taken from the "my_username_claim" claim. (Similar things do work as expected for oidcConfig.emailClaim and oidcConfig.groupsClaim.)

## Current Behavior

The header is not injected. Also, when I examine the oauth2-proxy logs I see that the user field of the Session record is empty.

## Possible Solution

Doing a bit of code inspection, my first thought is that newProviderDataFromConfig is failing to set p.UserClaim as it should. But I'm new to the codebase so I'm far from sure about that.

I also see some relevant discussion in issue #1960 , but since the overall topic there is different, I decided to go ahead and file this.

## Steps to Reproduce (for bugs)

I'm currently using oauth2-proxy as an Istio extensionProvider for authorizing access to various virtual services. A (somewhat sanitized) copy of my Istio meshConfig, and the values.yaml that I used as input for deploying oauth2-proxy using the oauth2-proxy helm chart version 6.5.0 (for oauth2-proxy 7.3.0), are attached.

[issue-attach.zip](https://github.com/oauth2-proxy/oauth2-proxy/files/10416252/issue-attach.zip)

## Context

We don't always have complete freedom to specify the header values expected by the services and/or the claims that provide them. I understand that oauth2-proxy doesn't yet provide fully generic token-claim-to-header-value mapping, but this little bit of flexibility would be good to have.

## Your Environment

K8s 1.21 (and later), Istio 1.13.5, oauth2-proxy 7.3.0

**Comment by miguelborges99** [comment]
I don't think it was a good idea to open a new thread for the same issue (#1960). Consider to close this issue and add a comment there. Otherwise, we will be discussing in two places.

**Comment by joel-bluedata** [comment]
It didn't seem like this falls under the topic of "Some claims in OIDC token not accessible by ClaimSource" but if this is in the end covered by the same problem, then sure. Any maintainer can feel free to close this and I'll watch that other issue.

**Comment by JoelSpeed** [comment]
I think this could be a bug, it would suggest that either, we can't find your claim in the token or on the user profile, which would then suggest that there's been a misconfiguration on your end. However, if we aren't initialising the user id claim properly, then you would also get the same result.

I would suggest trying to follow through the flow of the code and work out where the user ID claim is being configured, and then, maybe, we can add some debug logic to make sure it is being set correctly
