### ISSUE TITLE
"Authorization: Basic" only works when prefer-email-to-user is true - is this a regression or by design?

### ISSUE THREAD

**Issue by wthrbtn** [oauth2-proxy/oauth2-proxy#1974]
## Expected Behavior
Regardless of prefer-email-to-user true or false I would like to be able to use the "Authorization: Basic " header.

## Current Behavior
prefer-email-to-user=true is needed to enable the basic authorization header

## Possible Solution

Is this due to #1116 ?? Or unrelated?

## Steps to Reproduce (for bugs)

set basic-auth-password: "123456" to provide a static basic auth password to upstream

## Context

Trying to use the Basic Authentication feature when protecting old legacy site.
However, I can only get the Basic authentication header when prefer-email-to-user is true.
Would like to avoid changing all the accounts name on the legacy system to email addresses.

## Your Environment

Kubernetes 1.24
Helm chart version 6.7.3 
oauth-proxy 7.4.0
behind traefik v2 ingress

**Comment by miguelborges99** [comment]
Do you want to detail a little more about your configuration? What errors do you see in the logs, if any? Maybe the community might help.

**Comment by b2ronn** [comment]
same problem. I get the "Authorization: Basic " header only if I turn on prefer_email_to_user. config - 
http_address="0.0.0.0:9095"
upstreams="http://localhost:8080"
cookie_secret="REDACTED"
email_domains="REDACTED.com"
basic_auth_password="0123456789"
provider="azure"
client_id="REDACTED"
client_secret="REDACTED"
azure_tenant="REDACTED"
oidc_issuer_url="https://login.microsoftonline.com/REDACTED/v2.0"
prefer_email_to_user=false
