### ISSUE TITLE
[Documentation] [Question] auth-url should be a .svc.cluster.local

### ISSUE THREAD

**Issue by giuliohome** [oauth2-proxy/oauth2-proxy#1977]
First of all, thank you for sharing.
This is not a bug but a question about the documentation.
I refer to paragraph https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/docs/configuration/overview.md#configuring-for-use-with-the-nginx-auth_request-directive
In particualr to 
```yaml
nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
```

## Expected Behavior

I would expect you suggest the shortest path (directly going to the service and no further to the ingress), the simplest and the safest thing to do here:
 something like, assuming a service `oauth2-proxy-service-name` under the `default` namespace

```yaml
nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy-service-name.default.svc.cluster.local/oauth2/auth
```

## Current Behavior

Currently you suggest a longer path (and an unneeded https), that implies reaching kubernetes dns and the ingress for oauth. (It is more demanding also in terms of regex patterns, SSL certificates, cookie secured, tests when one uses the other main app ingress as a reverse proxy...)

## Possible Solution
Already written above, do you have any reasons not to update the mentioned paragraph to reflect such a suggestion?

```yaml
nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy-service-name.default.svc.cluster.local/oauth2/auth
```

## Steps to Reproduce (for bugs)
This is not a bug

## Context

I think this is especially relevant when one uses the feature allowed_groups and a reverse auth proxy to a static website.

## Your Environment

Kubernetes (e.g. AKS)

- Version used:

Latest 7.4.0 (at the time of writing)

**Comment by braunsonm** [comment]
Hey @giuliohome 

It really depends on your environment. `$host` is just an example, oauth2-proxy could be hosted outside of the cluster, it could be behind a proxy that has HTTPS, etc. That is why the doc doesn't try to make any assumptions, it isn't necessarily saying to setup an ingress and go outside of the cluster (I wouldn't recommend that as you said), it's just trying to be generic.

**Comment by giuliohome** [comment]
Perfect. Thank you very much for your clarification.

**Comment by giuliohome** [comment]
### off-topic
By the way, excuse my ignorance, how do you configure the same domain name (which the `$host` variable would be expanding) for two different kubernetes clusters? Maybe I'm confused reading [this issue](https://github.com/kubernetes-sigs/external-dns/issues/2748) and the answer is surely very trivial: I don't want to waste your time, youst point me to a doc/link, if you have any chance to easily share it with me. Thanks anyway
