### ISSUE TITLE
Azure AKS workload identity support

### ISSUE THREAD

**Issue by mblaschke-daimlertruck** [oauth2-proxy/oauth2-proxy#1979]
## Expected Behavior

Support Azure AKS workload identity support like the feature request for GKE workload identity #1808

It's described here:
https://azure.github.io/azure-workload-identity/docs/

## Possible Solution

Azure AKS workload identity is providing the JWT token file at the location of the environment variable `AZURE_FEDERATED_TOKEN_FILE` (default `/var/run/secrets/azure/tokens/azure-identity-token`) which gets updated regularly with a new token.

these examples env vars are set automatically by Azure AKS workload identity which might eliminate the configuration of the serviceprincipal at all:
```
AZURE_CLIENT_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
AZURE_TENANT_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
AZURE_FEDERATED_TOKEN_FILE: /var/run/secrets/azure/tokens/azure-identity-token
AZURE_AUTHORITY_HOST: https://login.microsoftonline.com/
```

the token could be loaded for every run

**Comment by miguelborges99** [comment]
Are you able to do a pull request for this issue?
