### ISSUE TITLE
Authentication is in progres message while Authentication is being performed by Oauth2proxy

### ISSUE THREAD

**Issue by vishrana** [oauth2-proxy/oauth2-proxy#1983]
I am using oauth2proxy with Azure AD. It is working fine.

Issue: After first login. Do not access the website for 1 hours and after 1 hour when I hit the website url again it keep me showing blank page for 5-7 seconds. The time delay is at Azure AD side because it is trying to validate the user again and it needs couple of api calls.

## Expected Behavior

after 1 hour when I hit the website url again. OAuth2Proxy should be able to show a static html page. Where I can show a message you are being authenticated with a loader sign. The html page design should be configurable.

## Current Behavior

After first login. Do not access the website for 1 hours and after 1 hour when I hit the website url again it keep me showing blank page for 5-7 seconds. The time delay is at Azure AD side because it is trying to validate the user again and it needs couple of api calls.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:
v7.4.0

**Comment by miguelborges99** [comment]
The blank page that you are referring to, does it occurs because the sessions is being refreshed? Or, because user is redirected to a login page and it takes some time to show that page? Or, the delay occurs after the login page, i.e. the authentication server takes some time to call the oauth2 redirect url?

**Comment by vishrana** [comment]
It occurs when session is being refreshed. It takes 5-7 seconds and then the intended webpage appears. I guess the delay is from AAD side.

**Comment by miguelborges99** [comment]
Did you tried to solve at the application level, i.e. add some loading icons before a request is made?

**Comment by vishrana** [comment]
Yes, I have tried that but application do not have chance to perform any task. 

I have a web app running in separate pod and oauth2proxy running in separate pod in K8.

Flow is - 
1. As soon as request goes to the web app it is redirected to oauth2proxy using Virtual Service.
2. oauth2proxy perform authentication 
3. On successful authentication, the oauth2proxy forward request to web app.
So, step 2 is taking time and application does not have chance to show the loader.

So, hoping oauth2proxy can be configured to show a custom static web page while performing authentication.

**Comment by miguelborges99** [comment]
Maybe the community have some ideas. Your request is not easy to implement, since it is necessary to perform a redirect to a loading page, while refreshing the session and another redirect to the destination page when session is refreshed.

**Comment by vishrana** [comment]
Sharing a thought - I think before making the synchronous operation we can just redirect to Oauth2Proxy static web page (example message on the static html page -  Re-authenticating ......), and then perform existing redirects to refresh the session. Once the static page is shown it will keep showing it until the token is refreshed. Once the session is refreshed, redirect back to the original page.

**Comment by braunsonm** [comment]
I don't think there's anything oauth proxy should be doing here. The redirect to Azure is part of the OAuth spec and must continue.

If you mean just the single API call to exchange the auth token, then that shouldn't take very long and I can't see a way we could reasonably mitigate that... You should keep your users session up to date by sending a request to keep the cookie session refreshed with the refresh token from Azure instead. We will update the token in the session when it is going to expire if there is a refresh token.

This way you don't need to reauthenticate each time.
