### ISSUE TITLE
Change `action` version to `v3`

### ISSUE THREAD

**Issue by OmAximani0** [oauth2-proxy/oauth2-proxy#1984]
Since `action/checkout@v2` uses `Node 12.x.x` and it is [deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) I think we must use `action/checkout@v3`

https://github.com/oauth2-proxy/oauth2-proxy/blob/f753ec1ca5c42cd4c4e400afa1f76817638f3010/.github/workflows/ci.yaml#L18-L22

**Comment by miguelborges99** [comment]
Can you do a pull request?
