### ISSUE TITLE
Providing scope arguments to Azure provider breaks authorization code flow

### ISSUE THREAD

**Issue by syst0m** [oauth2-proxy/oauth2-proxy#1987]
## Expected Behavior

Being able to provide a specific set of scopes to get passed with the authorization request.

## Current Behavior

Providing a specific set of arguments for the scope results in an error:
![Screenshot 2023-01-25 at 14 26 47](https://user-images.githubusercontent.com/15815107/214597847-afb80d2d-2239-428c-a828-22eed4d4a3e9.png)

## Possible Solution

Looks like the `.default` scope is always used with v2.0 endpoints:
https://github.com/oauth2-proxy/oauth2-proxy/blob/f753ec1ca5c42cd4c4e400afa1f76817638f3010/providers/azure.go#L99:L102

Removing the scope override from the config, results in a working flow. Seemingly, because the `.default` scope is then used.

## Steps to Reproduce (for bugs)

```      configFile: |-
        azure_tenant = "XXX"
        cookie_domains = "XXX"
        cookie_expire = "168h"
        cookie_name = "XXX"
        cookie_refresh = "0"
        cookie_secure = "true"
        email_domains = [ "*" ]
        provider = "azure"
        scope = "profile User.Read"
        whitelist_domains = "XXX"
        oidc_issuer_url = "https://login.microsoftonline.com/XXX/v2.0"
```

## Context

Provide a limited set of scopes, rather than always using `.default` scope.

## Your Environment

```  chart:
    name: oauth2-proxy
    repository: https://oauth2-proxy.github.io/manifests
    version: 6.8.0
...
    image:
      repository: "quay.io/oauth2-proxy/oauth2-proxy"
      tag: "v7.4.0"
```

**Comment by miguelborges99** [comment]
What scope set would you suggest, instead of .default?
