### ISSUE TITLE
Options to not send oauth2-proxy specific cookies to upstreams

### ISSUE THREAD

**Issue by segaura** [oauth2-proxy/oauth2-proxy#1993]
Oauth2-proxy cookies, especially in cookie storage mode, can be big in size, think of a access, refresh and id token combination stored inside cookies, for instance.

## Expected Behavior

Oauth2-proxy could accept a new configuration parameter which allows to remove its own cookies from requests to be sent to upstreams.

## Current Behavior

Currently there are solutions in place to stip entire headers, but the `Cookie` header mixes oauth2-proxy own cookies with ones for other destinations.
So while my spring-boot upstream needs only its `"JSESSIONID"` cookie, it now receives also `_oauth2_proxy_0` and `_oauth2_proxy_1` which are more than 6KB together.

## Possible Solution

In headers.go, along with others header treatment, which already take care of stripping some of them and removing configured informations, it should be possible to split the `Cookie` content and remove oauth2-proxy specific cookies from it.

## Context

My main concern regards performance, because in cookie storage mode, cookie size is typically 6KB in my context.
We find some of our Tomcat-based upstreams rejecting requests because they exceeded the 8KB default limit for headers size.

## Your Environment

- Version used:

7.4.0

**Comment by wollomatic** [comment]
I'd say the redis storage is already a working solution: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/session_storage#redis-storage

**Comment by segaura** [comment]
Thank you.
This is not a solution for our environment because we do not have a Redis
in place and are relaying on httpOnly cookies.
Also I am curious on what happens to session cookie when using Redis:  is
it still sent to upstreams?

Luca

Il giorno lun 6 feb 2023 alle ore 14:58 Wolfgang Ellsässer <
***@***.***> ha scritto:

**Comment by JoelSpeed** [comment]
I would recommend, if the cookies are causing issues, to try a server side session storage, this will greatly reduce the size of the cookie being sent to the upstream.

Right now, the only implementation we have is redis, but I'm open to PRs for other server side session stores based on the same interface

**Comment by segaura** [comment]
Sure, we understand that with server side storage, redis, jdbc or something else the problem is not present.

My point is that now with cookie storage, oauth2-proxy encrypted cookies are travelling two sections:
- the first _from the browser to oauth2-proxy_, which is necessary
- the second, _from oauth2-proxy to any upstream_, which is not necessary, and this will not change because upstreams can't decrypt them

That holds also for server side storage, it is not necessary to forward the small-redis-key-cookie to upstream.

Are you open to implement or accept a PR implementing a switch to prevent this cookie forwarding to upstreams?

**Comment by JoelSpeed** [comment]
I'm open to including an option for this sure, would need someone to raise a PR for it

**Comment by segaura** [comment]
No bot, please don't close this, we are considering sending a PR to implement it.

**Comment by dorinclisu** [comment]
Still valid

**Comment by Magnum5234** [comment]
Here is a quick patch that worked for me.
Be mindful I'm using version 7.8.1

```diff
Subject: [PATCH] remove session cookies from request data for upstream
---
Index: oauthproxy.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/oauthproxy.go b/oauthproxy.go
--- a/oauthproxy.go	(revision 04cc932976c0336cb0393165b939a9c5eb160030)
+++ b/oauthproxy.go	(date 1785740408045)
@@ -430,7 +430,24 @@
 		return alice.Chain{}, fmt.Errorf("error constructing request header injector: %v", err)
 	}
 
-	return alice.New(requestInjector, responseInjector), nil
+	return alice.New(requestInjector, responseInjector, getOAuthCookieRemover(opts)), nil
+}
+
+func getOAuthCookieRemover(s *options.Options) alice.Constructor {
+	cookieNameRegex := regexp.MustCompile(fmt.Sprintf("^%s(_\\d+)?$", s.Cookie.Name))
+	return func(next http.Handler) http.Handler {
+		return http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
+			cs := req.Cookies()
+			req.Header.Del("Cookie")
+			for _, c := range cs {
+				if cookieNameRegex.MatchString(c.Name) {
+					continue
+				}
+				req.AddCookie(c)
+			}
+			next.ServeHTTP(rw, req)
+		})
+	}
 }
 
 func buildSignInMessage(opts *options.Options) string {

```
