### ISSUE TITLE
set-xauthrequest=true does not set  X-Auth-Request-User, X-Auth-Request-Group, X-Auth-Request-Preferred-Username 

### ISSUE THREAD

**Issue by knfoo** [oauth2-proxy/oauth2-proxy#1995]
I have configured oauth2-proxy v7.4.0 to use azureAD:
```
        - --http-address=http://:4180
        - --upstream=file:///dev/null
        - --provider=oidc
        - --client-id=some id
        - --client-secret=some secret
        - --proxy-prefix=/oauth2
        - --reverse-proxy=true
        - --real-client-ip-header=X-Forwarded-For
        - --redirect-url=https://domaincom/oauth2/callback
        - --oidc-issuer-url=https://login.microsoftonline.com/<someid>/v2.0
        - --redis-connection-url=redis://redis-master
        - --redis-password=test
        - --session-store-type=redis
        - --email-domain=*
        - --cookie-name=domain_com
        - --cookie-secret=secret
        - --cookie-secure=true
        - --cookie-expire=24h
        - --scope=email openid profile
        - --oidc-email-claim=preferred_username
        - --pass-user-headers=true
        - --set-xauthrequest=true
        - --show-debug-on-error=true
        - --auth-logging=true
```

When I authenticate I only get the `X-Auth-Request-Email`, `X-Forwarded-For`, and `X--Forwarded-Proto` headers even the auth Session provides a group as well.

```
[AuthSuccess] Authenticated via OAuth2: Session{email:kn@foo.com user:msr<numbers> PreferredUsername:kn@foo.com token:true id_token:true created:2023-02-01 20:30:38.990062544 +0000 UTC m=+36.710622965 expires:2023-02-01 21:40:41.958886179 +0000 UTC m=+4239.679446600 groups:[azure-group-id1 azure-group-id2... azure-group-id100]}
```

## Expected Behavior

I would expect that  `X-Auth-Request-User`, `X-Auth-Request-Group`, and  `X-Auth-Request-Preferred-Username` would be set with the values from the `Session`

## Current Behavior

I only get get the `X-Auth-Request-Email`, `X-Forwarded-For`, and `X--Forwarded-Proto` headers

## Your Environment

I use containous/whoami from dockerhub to print out the header information.

- Version used: v7.4.0

**Comment by JoelSpeed** [comment]
The headers you want, aren't provided by default, but can be configured using the headers configuration within the alpha configuration

**Comment by ceastman-r7** [comment]
@JoelSpeed can you provide an example using the alpha configuration?

@vdksystem with regards to istio, what was your fix?

**Comment by vdksystem** [comment]
If I remember correctly my issue was in Istio configuration
`
headersToUpstreamOnAllow:
            - x-forwarded-access-token
            - authorization
            - path
            - x-auth-request-user
            - x-auth-request-email
            - x-auth-request-access-token
            - x-auth-request-preferred-username
`
I didn't have  ` - x-auth-request-preferred-username` initially

**Comment by Gerry9000** [comment]
Adding another data point for anyone using nginx `auth_request` (not Istio). With `--set-xauthrequest=true`, all the headers ARE set in the `/oauth2/auth` response — but `X-Auth-Request-User` may not contain what you expect.

With Kanidm as the OIDC provider and `--user-id-claim=preferred_username`:
- `X-Auth-Request-User` → UUID (`sub` claim), e.g. `a1b2c3d4-5678-9abc-def0-1234567890ab`
- `X-Auth-Request-Preferred-Username` → actual username, e.g. `gerry.burde`

If your upstream application needs the username (not the UUID), use the preferred-username header in your nginx config:

```nginx
auth_request_set $auth_user $upstream_http_x_auth_request_preferred_username;
proxy_set_header X-Forwarded-User $auth_user;
```

This is consistent with @vdksystem's Istio fix above — `x-auth-request-preferred-username` is a separate header that needs to be explicitly forwarded/read.

(oauth2-proxy v7.14.2, Kanidm OIDC provider, nginx auth_request pattern)
