### ISSUE TITLE
Environment Variable Config Not Supported With Alpha Config

### ISSUE THREAD

**Issue by rkimmel-hv** [oauth2-proxy/oauth2-proxy#1997]
At the moment I am running oauth2proxy as a container in kubernetes and using a configmap to mount in a config file. As well as using the config file, I use the environment variables OAUTH2_PROXY_CLIENT_SECRET, OAUTH2_PROXY_CLIENT_ID, and OAUTH2_PROXY_COOKIE_SECRET, which are mounted in from a secret. I am now trying to move to using the alpha config style since it has features I would like to use but I am getting this error from the container `[2023/02/02 15:40:49] [main.go:54] invalid configuration:
  provider missing setting: client-id
  missing setting: client-secret or client-secret-file`
  
  Are these environment variables intended to be supported while using the alpha config? I would prefer not to have my secrets be in plain text but that would necessitate putting the entire apha config file into a kubernetes secret rather than just the secret information.

## Expected Behavior

Using alpha config option I should be able to specify OAUTH2_PROXY_CLIENT_SECRET, OAUTH2_PROXY_CLIENT_ID, and OAUTH2_PROXY_COOKIE_SECRET environment variables from a secret.

## Current Behavior

I get this error message when the alpha config file does not contain client_id, client_secret and cookie_secret
`[2023/02/02 15:40:49] [main.go:54] invalid configuration:
  provider missing setting: client-id
  missing setting: client-secret or client-secret-file`

## Possible Solution

Please allow use of these environment variables or help me understand what the replacement behavior should be

## Context

Just trying to take advantage of some of the alpha features while keeping my secret information secret still

## Your Environment

Running in Azure on k8s v1.22.11

- Version used: v7.4.0

**Comment by rkimmel-hv** [comment]
I ended up working around this issue by mounting in a kubernetes secret with the client secret in it and specifying that secret as the client_secret_file property

**Comment by edwardzjl** [comment]
I encountered a similar issue. I was following this document section: <https://oauth2-proxy.github.io/oauth2-proxy/configuration/alpha-config#using-env-variables-in-the-alpha-configuration>

```yaml
...
    providers:
    - provider: gitlab
      clientID: ${PROVIDERS_GITLAB_CLIENTID}
      clientSecret: ${PROVIDERS_GITLAB_CLIENTSECRET}
      ...
```

and providing the environment variable through secret:

```yaml
...
          envFrom:
            - secretRef:
                name: oauth2-proxy
...
```

However it does not work:

```console
[2025/04/23 05:38:04] [main.go:72] WARNING: You are using alpha configuration. The structure in this configuration file may change without notice. You MUST remove conflicting options from your existing configuration.   
[2025/04/23 05:38:04] [main.go:53] invalid configuration:
  provider missing setting: client-id
  missing setting: client-secret or client-secret-file
```
