### ISSUE TITLE
"Cookie settings:" Logger Output Does Not List All Cookie-related Startup Settings

### ISSUE THREAD

**Issue by GuyPaddock** [oauth2-proxy/oauth2-proxy#2006]
## Expected Behavior
When starting OAuth2 Proxy in a Docker container, the `cookie_csrf_per_request` and `cookie_csrf_per_request` options/values should appear in the `Cookie settings:` console output so that it's easy to confirm that the values being set by environment variables have taken effect, just like `cookie_samesite` and `cookie_refresh` do.

## Current Behavior
The output omits the current value of these options on startup:
```
Cookie settings: name:authentication_session secure(https):true httponly:true expiry:24h0m0s domains: path:/ samesite:strict refresh:disabled
```

## Possible Solution
It looks like the [associated logger line](https://github.com/oauth2-proxy/oauth2-proxy/blob/f753ec1ca5c42cd4c4e400afa1f76817638f3010/oauthproxy.go#L167) needs to be updated after #1708 got merged.

## Steps to Reproduce (for bugs)
Either:
- Start OAuth2 proxy with `OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST` set to `true` in the environment; or
- Start OAuth2 proxy from the command line, passing `--cookie-csrf-per-request`.

## Context
Without this, it is difficult to know whether the `OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST` environment variable in the Docker container is taking effect. I was eventually able to determine that it was by setting the environment variable to a garbage value like `flooble` to observe that the container crashed. This leads me to conclude this is just a log output issue.

## Your Environment
- Running in Docker
- Version used: 7.4.0

**Comment by JoelSpeed** [comment]
I wonder if we need some broader scoped way to check the loaded configuration, I can see this issue being repeated over and over. How would you feel about a full `--print-config` option that you could pass to the application to get it to print out a full configuration structure which would then allow you verify what config has been loaded?

**Comment by GuyPaddock** [comment]
@JoelSpeed I'd be on-board with that, as long as only recognized options make their way into the config. That would save a lot of time with debugging!
