### ISSUE TITLE
Fragment (#) in request url is not mapped to path in state-parameter

### ISSUE THREAD

**Issue by euhansen** [oauth2-proxy/oauth2-proxy#2014]
When calling an url with a fragment (#) the fragment is not preserved in the path-part of the state-parameter sent to the provider in an authorize-request.

## Expected Behavior

The fragment is appended to the path-part of the state-parameter in the authorize-request.

Example:

* Incoming request url:
   `https://kdashboard.mycommpany.com/#/workloads?namespace=myapp-ns`
* Redirect url to provider:
   `https://idp.mycompany.com/oauth2/authorize?approval_prompt=force&client_id=my_oidc_client&redirect_uri=https%3A%2F%2Fkdashboard.mycommpany.com%2Foauth2%2Fcallback&response_type=code&scope=openid+profile&state=4Tok6upv5N4dMJHazX84knDvTDper1hcNbR5lr-7Fu0%3A%2F%23%2Fworkloads%3Fnamespace%3Dmyapp-ns`
* Decoded state-parameter:
   `state=4Tok6upv5N4dMJHazX84knDvTDper1hcNbR5lr-7Fu0:/#/workloads?namespace=myapp-ns`

## Current Behavior

The fragment is removed from path-information in the state-parameter.

Example:

* Incoming request url:
   `https://kdashboard.mycommpany.com/#/workloads?namespace=myapp-prod`
* Redirect url to provider:
   `https://idp.mycompany.com/oauth2/authorize?approval_prompt=force&client_id=my_oidc_client&redirect_uri=https%3A%2F%2Fkdashboard.mycommpany.com%2Foauth2%2Fcallback&response_type=code&scope=openid+profile&state=4Tok6upv5N4dMJHazX84knDvTDper1hcNbR5lr-7Fu0%3A%2F`
* Decoded state-parameter:
   `state=4Tok6upv5N4dMJHazX84knDvTDper1hcNbR5lr-7Fu0:/`

This only seems to be a problem when using a direct link with no session cookie. After successful authentication urls with fragments behave as expected.

Using a header with a redirectUri containing a fragment seems to work as well as demonstrated by this `curl`-call:

```bash
  $ curl -v -H "X-Auth-Request-Redirect: /#/workloads?namespace=myapp-ns" https://kdashboard.mycommpany.com/
  ...
  > GET / HTTP/1.1
  > Host: kdashboard.mycommpany.com
  ...
  < HTTP/1.1 302 Found
  < location: https://idp.mycompany.com/oauth2/authorize?approval_prompt=force&client_id=my_oidc_client&redirect_uri=https%3A%2F%2Fkdashboard.mycommpany.com%2Foauth2%2Fcallback&response_type=code&scope=openid+profile&state=4Tok6upv5N4dMJHazX84knDvTDper1hcNbR5lr-7Fu0%3A%2F%23%2Fworkloads%3Fnamespace%3Dmyapp-ns
```

## Possible Solution

Add the fragment to the state-parameter as it is done when using a header to set a redirectUri.

Looking at the code in `oauthproxy.go` it's maybe the [`director.GetRedirect`-method used in the `doAuthStart`-method](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L772) which should be extended to append a possible fragment to the returned uri. But if this has unwanted effects on other parts of the code is not clear to me.

## Steps to Reproduce (for bugs)

1. Send a request with an url containing a fragment to a web-application fronted by oauth2-proxy
2. Verify the state-parameter in the redirect-url sent to the idp-providers authorize-endpoint

Verification can be done in the tool-window in a browser or with curl as illustrated above.

## Context

In single-page javascript applications it is normal to use [hashrouting for navigation](https://medium.com/web-dev-freelancing/what-is-hash-routing-e61b14ebec83). A prominent example is the [Kubernetes dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) where hashrouting is used to navigate to specific parts of the dashboard (see the screenshots in the documentation). The Kubernetes dashboard works fine with Oauth2 Proxy in front, except when the oauth2-cookies are missing or expired. In these cases navigation-information in the fragment is dropped by Oauth2 Proxy, and the user is redirected to the application root instead of the intended page.

## Your Environment

Oauth2 Proxy version 7.1.3 running on a Kubernetes cluster with Envoy as ingress-controller.

**Comment by baez90** [comment]
I'm encountering a similar issue. I'll try to prepare a PR and see if this is breaking any existing test cases but I'd be happy to get some feedback if there are any known edge cases why this might not be desired 😅

Probably a config flag could be added to keep the current behavior as default but allowing to take fragments into account if requested?

**Comment by JoelSpeed** [comment]
I don't think what you want to achieve is actually possible. URL fragments are client side, they aren't sent to the server which means when your browser says `https://kdashboard.mycommpany.com/#/workloads?namespace=myapp-ns`, OAuth2 Proxy will only ever see `https://kdashboard.mycommpany.com/`, it's not that there's a bug here, AFAIK this is the design of a URL fragment. 

If someone can find anything to suggest I'm wrong, happy to accept a PR, but pretty sure I looked into this before, when I used to run the Kube dashboard behind OAuth2 Proxy

**Comment by euhansen** [comment]
I think you're right. And I feel a bit dumbfounded now. Why didn't I check the browser behavior before opening a bug report? I had prepared a PR with better fragment handling, but that's of course to no avail if a fragment isn't received in the first place.

You can close the bug report. Probably a good idea to keep it as reference if someone else is wondering about fragments and Oauth2 Proxy in the future?

Thanks for your answer and the job you're doing as maintainer of the project :-)
