### ISSUE TITLE
Redirect path not correctly registered when using different path in `--redirect-url`

### ISSUE THREAD

**Issue by imnotjc** [oauth2-proxy/oauth2-proxy#2017]
Redirect path not correctly registered when using different path in `--redirect-url`

## Expected Behavior

When specifying a raw redirect url as "https://example.com/auth/callback" (the redcirect path is "/auth/callback"), after redirect from IdP the request should be handled as a callback.

## Current Behavior

"/auth/callback" is not registered as callback, so the response is a 401 Unauthorized.

## Possible Solution

From https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L321 the redirect path is hardcoded as "${ProxyPrefix}/callback", so the redirect url is always fixed.

We can register redirect path according to the actual redirect url instead of a const.

We have that "actual usd redirect url" in OAuthProxy so we can parse path from it.

## Steps to Reproduce (for bugs)

1.  Register an OIDC app with redirect URL: "http://localhost:4180/auth/callback"
2. Start oauth2-proxy with redirect URL: "http://localhost:4180/auth/callback"
3. Try to login, and the user will not be able to login unless change the url to "http://localhost:4180/oauth2/callback?code=**&state=**"

## Context

We can only use "/oauth2/proxy" in the redirect url without making change to the code.

## Your Environment

- Version used: oauth2-proxy v7.4.0 (built with go1.19.2)

**Comment by kr4sv** [comment]
Hey, wouldnt it solve your issue to set the ProxyPrefix to `/auth` ?

**Comment by gfrankliu** [comment]
The suggestion to use ProxyPrefix would only work if only prefix is different. What if the whole callback URL is different, say /auth/handler.

When testing oauth2-proxy as a replacement for an existing solution, we may need to keep the old callback URI since that is already allowlisted in the oauth provider.

**Comment by JoelSpeed** [comment]
> The suggestion to use ProxyPrefix would only work if only prefix is different. What if the whole callback URL is different, say /auth/handler.

This is not currently supported unless you can put something in front of OAuth2 Proxy (eg Nginx) and rewrite the request on the way in
