### ISSUE TITLE
Refresh Token on Demand

### ISSUE THREAD

**Issue by cmbaatz** [oauth2-proxy/oauth2-proxy#2019]
Within our application identity details are stored back up in our IDP (keycloak).  When a detail like user roles is updated we need to issue a new JWT to reflect the change.  Is there an endpoint, etc that I can use to force oauth2-proxy to refresh it's token that it has stored in the session store?

## Expected Behavior
Ideally I would like a /oauth2/refresh endpoint that we could hit, which would refresh the token linked with the session.  

## Current Behavior
Currently the only way I understand that the token is refreshed is after the cookie_refresh time.

## Possible Solution
Add a new /oauth2/refresh endpoint that calls the provider.RefreshSession funciton.

- Version used: 7.4.0

**Comment by cmbaatz** [comment]
I've completed code for this back in February, which has been waiting on a code review since.  How do I get this on the docket to be reviewed?

**Comment by cmbaatz** [comment]
I'm still waiting on some type of review for the addition I created for this issue.  The PR has a minor code climate finding that I have a method with 5 parameters instead of 4.  My organization has been using this solution in production now for a couple of months and would like to see if contributed back to the project.

**Comment by jaakkom** [comment]
I would like to see this feature in next version too :)

**Comment by JoelSpeed** [comment]
There are several ways to invalidate the sessions, the easiest way is to change the cookie secret, have you tried that as a solution rather than having an endpoint? What's the benefit of having an endpoint that forces refresh?

How are you planning to force your users to refresh? A user could also initiate the auth flow themselves which again would refresh the session

**Comment by cmbaatz** [comment]
@JoelSpeed 
The idea here is that there are specific user attributes like assigned tenant that we want to have included in the JWT.  Which not only makes it easier to access, but allows us to verify that the user is allowed to have that value (otherwise it couldn't be included in the JWT).  We control our authentication layer, so when a user changes one of these values we want the ability to request oauth to refresh the JWT so that new requests contain the new values.  We do not want to force our users to reauthenticate just because they changed one of these values.

**Comment by antoniocasagrande-airia** [comment]
@JoelSpeed any chance this will be merged in upcoming releases?
