### ISSUE TITLE
Only default redis username is sent when using --redis_cluster_connection_urls

### ISSUE THREAD

**Issue by henriduflot** [oauth2-proxy/oauth2-proxy#2020]
I tried to connect oauth2-proxy to redis cluster by providing username and password inside the `redis_cluster_connection_urls` parameter. But I can't use specific username.

**config.cfg**

```
### REDIS CONFIG ###
session_store_type="redis"
redis_use_cluster=true
redis_cluster_connection_urls="redis://username:password@cluster-hostname:7000"
```

## Expected Behavior

oauth2-proxy should authenticate on redis with provided username and password

## Current Behavior

Instead of 'username' the authentification is done with 'default'

Note : username:password configuration works well when using with redis_connection_url (non cluster mode)

The only way to make it work is to use redis_password parameter, but I can't use a specific username (default is used) : 

```
### REDIS CONFIG ###
session_store_type="redis"
redis_use_cluster=true
redis_cluster_connection_urls="redis://cluster-hostname:7000"
redis_password="password"
```

## Steps to Reproduce (for bugs)

Use a redis cluster and provide username/password inside the redis_cluster_connection_urls

## Your Environment

- oauth2-proy: v7.4.0.linux-amd64
- Redis : 6.0.14

**Comment by henriduflot** [comment]
I'm not very comfortable with the go language. Would it be enough to simply add Username parameter here ?

https://github.com/oauth2-proxy/oauth2-proxy/blob/fd50a35784457d4766e487a1edb9677f8e93cc30/pkg/sessions/redis/redis_store.go#L118-L136

For information here is how it is done for the standalone mode. I think opt already contains username paremeter parsed from connection_url :

https://github.com/oauth2-proxy/oauth2-proxy/blob/fd50a35784457d4766e487a1edb9677f8e93cc30/pkg/sessions/redis/redis_store.go#L138-L158

**Comment by JoelSpeed** [comment]
Looks like it, the go-redis struct (https://pkg.go.dev/github.com/go-redis/redis/v9#ClusterOptions) has a `username` field, so we would need to pass something through to that

**Comment by henriduflot** [comment]
I builded app with this fix :

```
	if opts.Password != "" {
		opt.Password = opts.Password
	}

	client := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs:           addrs,
		Password:        opt.Password,
		Username:        opt.Username,
		TLSConfig:       opt.TLSConfig,
		ConnMaxIdleTime: time.Duration(opts.IdleTimeout) * time.Second,
	})
	return newClusterClient(client), nil
```

I checked with different case of configuration : 

- With username and password in url : 🆗 

```
redis_use_cluster=true
redis_cluster_connection_urls="redis://default:secret@redis-cluster"
```

- With username in url and password as variable : 🆗 

```
redis_use_cluster=true
redis_cluster_connection_urls="redis://default@redis-cluster"
redis_password="secret"
```

- With password in variable but without username : 🆗 

```
redis_use_cluster=true
redis_cluster_connection_urls="redis://redis-cluster"
redis_password="secret"
```

Given above tests, it should not have a negative impact. But like I said I'm not a developper 
Do you think I can submit Pull Request with the fix ?
