### ISSUE TITLE
Kubernetes-dashboard token not refreshing

### ISSUE THREAD

**Issue by markandersontrocme** [oauth2-proxy/oauth2-proxy#2022]
## Expected Behavior
I should either be logged in or it should ask me to login.

## Current Behavior
After you have logged in to the dashboard for a while the next time you navigate to the URL you are unauthorized. I am assuming it is due to the token no longer being valid, but in that case should the oauth2-proxy request me to login again? 

In order to fix this you need to clear the cookie, refresh, then login

![image](https://user-images.githubusercontent.com/16004416/220455536-1b423a31-14f6-440b-81eb-e43dd72a3dc2.png)

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

kubernetes-dashboard values.yaml:
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: >-
      https://${LOGIN_BASE_URL_EXT}/oauth2/start?rd=https://$host$request_uri
    nginx.ingress.kubernetes.io/auth-url: http://${LOGIN_BASE_URL}/oauth2/auth
    ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
  hosts:
    - ${K8S_DASHBOARD_HOST}

extraArgs:
  - --token-ttl=691200
```
- Version used:

**Comment by JoelSpeed** [comment]
You will want to tune the cookie expire/refresh options based on how long your IDP allows the ID Token for, if you have this tuned correctly, you can get it to auto-refresh in the background, or sign users out once the ID Token is expired.

Try setting the refresh to the same expiry as the ID Token and see if that helps

**Comment by avmp2208** [comment]
@markandersontrocme  do you mind to share your configuration for the kubernetes dashboard and proxy ? Im facing the same issue, Im able to login successfully but the dashboard always say unauthorized, 
Im using k3s, btw
@JoelSpeed I also configure the expire and refresh as expected but cannot have it done!. 
here is the issue opened
https://github.com/oauth2-proxy/oauth2-proxy/issues/2294
