### ISSUE TITLE
Skip Authorization header set for hosts list

### ISSUE THREAD

**Issue by anannaya** [oauth2-proxy/oauth2-proxy#2027]
We use oauth2-proxy front-end with the tools like grafana, Kibana,kiali,jaeger..etc  kibana,homer, tomat does not respect Authorization headers which causes failure to login.
Is there any way to skipping the Authorization bearer header set  for a host like grafana ?

Appreciate if any hacky solution to unset the header at oauth2-proxy for perticular hosts.

**Comment by JoelSpeed** [comment]
Are you sharing one instance? Are you using some sidecar method? Can you please explain a bit more about your setup else it's hard to make suggestions for how to fix this.

The authorization header is an optional feature, so you must have turned this on, in theory you could turn it off, but depending on your setup this may affect more than just grafana. If you are using something like ingress-nginx, then it's an annotation on the ingress object that you need to remove. That's just two examples of what could be the answer 😅

**Comment by anannaya** [comment]
Yes. I deployed 2 oauth2-proxy one with Auth header set and another without Auth header. My question was is there any way can achieve with single oauth2-proxy with some kind condition implementation?

**Comment by JoelSpeed** [comment]
I don't think there's a way to do this conditionally right now no, headers are set generically across all upstreams, perhaps in the future they can be configured per upstream but this would mean some amount of rework to how they're implemented right now IIRC
