### ISSUE TITLE
--skip-auth-route does not match on query string

### ISSUE THREAD

**Issue by adrillon** [oauth2-proxy/oauth2-proxy#2029]
## Expected Behavior

`--skip-auth-route` should match query strings in URLs.

## Current Behavior

It does not.

## Possible Solution

Make it so it does.

## Steps to Reproduce (for bugs)

1. Start oauth2-proxy with `--skip-auth-route='.*test.*'`
2. Confirm it works by seeing `Skipping auth - Method:  | Path: .*test.*` in the output
3. Go to `https://example.com/?test` and get redirected to a login page

The regex is valid, as evidenced by `https://example.com/test` being properly matched.

## Context

I'm trying to put an instance of [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge) behind a login wall, but still have direct access to generated feeds. I need URLs with `action=display` to be accessible without login, for use in RSS readers.

## Your Environment

- Version used: 7.4.0
- OS: NixOS
- OIDC provider: Keycloak
- oauth2_proxy is behind a reverse proxy (Caddy)

**Comment by JoelSpeed** [comment]
Hmm, the concern I'd have here is that it would change the behaviour for existing users and could allow users access who previously didn't have access, we might have to make this optional somehow.

Given query strings can easily be modified by a user, do you think this might make a bit of a security hole within the project? Eg if I know I can skip auth for `public`, then maybe adding `?public` to the end of any URI would make it accessible without auth, which wouldn't make much of a difference to the backend, where a separate path would?

**Comment by adrillon** [comment]
Thanks for your reply.

I suppose the security implications depend on the app being protected. The regex could be made to only match valid query args, which will be recognized by the app.

Let me explain my use case a bit more. I have an instance of [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge), which is a tool to generate RSS feeds. It has no support for any external auth whatsoever (LDAP, OpenID...). I want the instance to be accessible to logged in users only (even if the tool does not store or access any data which isn't already public, I do not want it to be open, in order to reduce the attack surface).

I use an RSS reader webapp to access the feeds, which is hosted on the same server. The URLs of the RSS feeds must not be behind OAuth so the reader can access them, hence the need to match `?action=display`. For added security I can configure Caddy to only allow the server's own IP on these URLs.

I understand it's a niche use case and I'm probably not doing things the best way possible, but I believe matching query strings can be useful in some cases. It can be implemented in an optional manner, like you said, maybe with another parameter like `--skip-auth-query`.

**Comment by djarillo** [comment]
I am using oauth with k8s+ingress-nginx. The way nginx redirects to oauth is always through the annotation 
nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth

So it always reaches oauth with the URL /oauth2/auth.

If I set /oauth2/auth in skip_auth_routes any ingresses that have the above annotation will skip authentication. This is correct, but I need to add the URL of the ingress ($escaped_request_uri) to configura this url like skip route and for that I need to pass it as a parameter. 

The --skip-auth-query configuration option would be useful in this case. I don't see a way to configure URLs for skip the authentication  with the oAuth+k8s+ingress-nginx combination.

**Comment by diegopazosrego** [comment]
HI @adrillon , @djarillo 

I have the same behavior, I have configured K8S+ingress+oauth2-proxy and I want to skip the authentication in the root of the domain / but I want to add it in /admin for a double authentication ( oauth2-proxy + local) 

I am trying to skip in the route and add in /admin but it is impossible it never works neither with skip-auth-route nor with skip-auth-regexp 

Any idea ?

**Comment by djarillo** [comment]
Hi,
With oauth2 for me was impossible skip urls. I used one trick with nginx.
For example, the url that you need skip is "/someurl/moreurl" but this url now is with oauth in your ingress. I added other ingresses with a prefix in the  URL that use the same service "/noauth/someurl/moreurl" . Using the redirex 

https://kubernetes.github.io/ingress-nginx/examples/rewrite/

You can skip the oAuth for the URL that you configure in you new ingresses with the same service. For me, the service is one api in java and the endpoints wiht this trick sare the same.
