### ISSUE TITLE
Clarify cookie session refresh/invalidation

### ISSUE THREAD

**Issue by eladbs** [oauth2-proxy/oauth2-proxy#2031]
Hello!

I am using Oauth2 Proxy (with nginx, redis as a store) and Auth0 as IDP.
I have a question regarding the cookie refresh and validation period.

To test the scenario I configured the cookie/tokens TTLs like this:
Cookie expire: 1 minute.
Cookie refresh: 15 seconds.
ID Token expiration: 15 seconds.
Refresh token expiration: 1 day.

After logging in I get a cookie and (while using the app) every 15 seconds the cookie is refreshed as it should. 
So in 1 minute I will get 4 different cookies.
In this example, all 4 cookies are valid until 1 minute has passed from the original login.

My question is: shouldn't an "old" cookies be invalid by the time a new cookie is given?
What is the point of cookie refresh then?

Thanks!

**Comment by JoelSpeed** [comment]
That's an agressive refresh period! Not seen them set that short before, but, kudos 😅 

But to the point, the new cookies should be valid for 1 minute past the time they were issued, not the time from the original authentication. The whole point of the authentication refresh is that it extends the expiry, but from my read of your situation, it seems that is not the case.

What happens at the 1 minute mark? Does it require you to re-authenticate or does it refresh and continue working?
