### ISSUE TITLE
Go Get deprecation

### ISSUE THREAD

**Issue by avila-m-6** [oauth2-proxy/oauth2-proxy#2033]
Readme instructions use `go get` to install the library, but [it's been deprecated since Go v1.17][gogetdeprecate]. It should now use `go install` instead.

## Expected Behavior

Install the library

    $ go get github.com/oauth2-proxy/oauth2-proxy/v7
    go: downloading github.com/oauth2-proxy/oauth2-proxy/v7 v7.4.0
    go: downloading github.com/oauth2-proxy/oauth2-proxy v3.2.0+incompatible
    go: downloading github.com/gorilla/mux v1.8.0
    ...

## Current Behavior

    $ go get github.com/oauth2-proxy/oauth2-proxy/v7
    go: go.mod file not found in current directory or any parent directory.
            'go get' is no longer supported outside a module.
            To build and install a command, use 'go install' with a version,
            like 'go install example.com/cmd@latest'
            For more information, see https://golang.org/doc/go-get-install-deprecation
            or run 'go help get' or 'go help install'.

## Possible Solution

Replace for `go install` and add `latest` tag.

    $ go install github.com/oauth2-proxy/oauth2-proxy/v7@latest

## Steps to Reproduce (for bugs)

1.  `git clone https://github.com/oauth2-proxy/oauth2-proxy/`
2.  `$ go get github.com/oauth2-proxy/oauth2-proxy/v7`

## Context

I want to install the project as a standalone library, meaning I won't run it within a module.

## Your Environment

* Ubuntu v22.04 under WSL2
* `go version go1.19.3 linux/amd64`

- Version used:
- oauth2-proxy V7.4.0

[gogetdeprecate]: https://go.dev/doc/go-get-install-deprecation

**Comment by JoelSpeed** [comment]
Thanks for raising this, yep, haven't updated the docs in a while, we will need to whip up a PR to resolve this, do you have time to fixup the docs?

**Comment by avila-m-6** [comment]
Sure, will do
