### ISSUE TITLE
Api-Route entry in oauth2-proxy.cfg is not being recognized

### ISSUE THREAD

**Issue by SilvioSodre** [oauth2-proxy/oauth2-proxy#2034]
The Api-Route entry in oauth2-proxy.cfg is not being recognized.

## Expected Behavior

OAuth2-Proxy starts normally and send  401 (unauthorized) error instead 302 (redirect) response when accessed path matches with the regex which is configured in api-route entry.

## Current Behavior

OAuth2-Proxy crashs with the followind error: 
* '' has invalid keys: api-route

## Possible Solution

Because the api-route feature was released in the latest version (7.4.0), I guess this issue could be related to a problem in code merge.

## Steps to Reproduce (for bugs)

1.  Put an 'api-route' entry in oauth2-proxy.cfg like 
> api-route="^/api"

2. Start Oauth2-Proxy with 
> oauth2-proxy --config=/etc/oauth2-proxy.cfg

Oauth2-Proxy will crash with "* '' has invalid keys: api-route" message.

## Context

I just want to config OAuth2-Proxy to use with REST APIs.

## Your Environment

- Version used: 7.4.0

**Comment by kr4sv** [comment]
Try “api-routes” - its only singular when passed as command line option (where it can be passed multiple times).

**Comment by SilvioSodre** [comment]
I tested with OAUTH2_PROXY_API_ROUTES environment variable and now I see the expected behavior. Thank you!
