### ISSUE TITLE
Add scope validation to auth endpoint to support M2M scenarios

### ISSUE THREAD

**Issue by IgorMilavec** [oauth2-proxy/oauth2-proxy#2035]
I'm trying to expose multiple API endpoints on K8s+Nginx+Oauth2_Proxy. I need to check for authorization for users (through groups) and services (through scopes). OAuth2 Proxy currently does not support checking for scopes on auth endpoint.

## Expected Behavior

The auth endpoint would check for scopes in the token.

## Current Behavior

Authorization for services fails as we are using Client Credentials Grant.

## Possible Solution

I propose to treat the scope claim the same as groups claim. So given `allowed_groups=x/yz` it would match either a group `x/yz` or a (custom) scope `x/yz`.

Another option is to add a new parameter `allowed_scopes`. But existing parameters on auth endpoint have an implicit AND semantics, while `allowed_groups` and `allowed_scopes` require OR semantics, which would make things more difficult to reason about. This is why I would try to avoid this solution.

## Context

I'm trying to expose multiple API endpoints on K8s+Nginx+Oauth2_Proxy. I need to check for authorization for users (through groups) and services (through scopes). OAuth2 Proxy currently does not support checking for scopes on auth endpoint.

## Your Environment

- Version used: 7.4.0

**Comment by JoelSpeed** [comment]
If the auth token can be exposed to your backend application, could it do this check itself do you think? I'm wondering whether we want this within OAuth2 Proxy or whether it's relatively straight forward to handle the Authz externally 🤔

**Comment by IgorMilavec** [comment]
In general I agree that AuthZ should be handled at the backend. However, for simple cases where one has many backend services who just need simple access authorization and the deployment is managed by single entity, this would really simplify the system. Besides, Oauth2 Proxy already does AuthZ through allowed_groups and allowed_scopes so this would not introduce a new feature, just extend the implementation.

**Comment by sabinayakc** [comment]
I would like this feature. Anybody wanna share ideas on how to implement this in the current code base?

Maybe we can start a PR.
