### ISSUE TITLE
Certain injected request headers are not included

### ISSUE THREAD

**Issue by blevine** [oauth2-proxy/oauth2-proxy#2043]
I've defined a number of headers to be included via injectRequestHeaders. Only some of the headers are actually included

## Your Environment

- Version used: 7.4.0
- Running against Keycloak 12.0.4

I include the following in my alpha config:

`scope: "openid profile email roles"`

```
injectRequestHeaders:
  - name: X-Forwarded-Groups
    values:
      - claim: groups
  - name: X-Forwarded-User
    values:
      - claim: sub
  - name: X-Forwarded-Email
    values:
      - claim: email
  - name: X-Forwarded-Preferred-Username
    values:
      - claim: preferred_username
  - name: X-Forwarded-Access-Token
    values:
      - claim: access_token
  - name: X-Forwarded-User-ID
    values:
      - claim: sub
  - name: X-Forwarded-First-Name
    values:
      - claim: given_name

The X-Forwarded-User, X-Forwarded-User-ID and X-Forwarded-First-Name headers are not included.  The other headers are included as expected.

**Comment by JoelSpeed** [comment]
The claims that you're trying to extract are not currently available. We only have a certain limited subset available so sub and given_name aren't there yet. The plan is to extend the session to include custom claims which would then allow you to achieve this, but we haven't got there yet

**Comment by blevine** [comment]
Ok. Thanks for the update. You're call on whether to close this issue now or close it once support for custom claims is implemented.

**Comment by miguelborges99** [comment]
I think, you can also call /oauth2/userinfo endpoint and get these claims. With these information you can inject in the headers, but do you really need to have all of them?

**Comment by benni336** [comment]
Well I think having user, e-mail and group information is quite useful to identify the user and to grant access to resources (or not).

**Comment by Hadatko** [comment]
+1

**Comment by jdbranham** [comment]
Still plans to implement custom claim mapping?

**Comment by JoelSpeed** [comment]
I would like to see this feature supported, but, personally don't have time as a maintainer anymore to implement new features
