### ISSUE TITLE
Unable to pass ID token to upstream host 

### ISSUE THREAD

**Issue by sfc-gh-mdwarasila** [oauth2-proxy/oauth2-proxy#2044]
Hi , I have been trying to use ID token from headers in my application. But i'm unable to fetch it through authorization header

## Expected Behavior

I should be able to  get id token from authorization header or some custom header

## Current Behavior

i'm unable to fetch ID Token through authorization header

I'm using it in Istio Service Mesh environment and Okta is Identity provider

- Version used: 7.4.0

**Comment by sfc-gh-mdwarasila** [comment]
I have passed below flags in oauth2-proxy configuration

        - --set-xauthrequest=true
        - --set-authorization-header=true
        - --pass-authorization-header=true 
        - --pass-host-header=true
        - --pass-access-token=true

**Comment by sfc-gh-mdwarasila** [comment]
Can anyone help me with this ? I'm unable to see id token in headers but able to see access token

**Comment by phllpmcphrsn** [comment]
Correct me if I'm mistaken, but isn't the handling of the ID token separate from what oauth2-proxy is meant for? If you're getting the access token then I think oauth2-proxy - and your configuration for that matter - is working properly

**Comment by sfc-gh-mdwarasila** [comment]
Hi @phllpmcphrsn , oauth2-proxy collects both ID token and Access Token from Okta when user authenticates. As per Oauth2-proxy documentation , we should be be able to extract ID token through headers. But currently, it's not happening. am i missing something ?

**Comment by alank976** [comment]
+1. I am also confused by this here. According to this docs [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/behaviour):

> The request is forwarded to the upstream server with added user info and authentication headers (depending on the configuration)

A httpbin instance is deployed behind my oauth2-proxy (i.e. upstream: httpbin) to verify the received headers from upstream point of view. It only receives no forwarded tokens but the cookie with OP's configuration options.

**Comment by JoelSpeed** [comment]
Have you tried using the example local test environments? They currently produce an authorization header with the ID Token IIRC. So perhaps you can test that out and try to switch over to okta to see what is different? 

IIRC, Okta initially sends you light tokens anyway, I think some additional configuration is required to get "fat tokens" that contain the information needed
