### ISSUE TITLE
Install oauth2-proxy on docker rpi4 error

### ISSUE THREAD

**Issue by Macrisu** [oauth2-proxy/oauth2-proxy#2049]
I try to install on my rPi 4 [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) via docker.

I've used this [docker-compose.yaml](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/docker-compose.yaml), but oauth2-proxy is reporting 

I run _docker-compose up -d_ and all ok

The problem is that I get an error

`ERROR: failed to load config: unable to load config file: read /oauth2-proxy.cfg: is a directory`

Where do I take a working oauth2-proxy.cfg ?

**Comment by kr4sv** [comment]
Did you place the oauth2-proxy.cfg file into the same folder your docker-compose file is located? Looks like mounting the config failed
