### ISSUE TITLE
OAuth2 proxy + basic auth configuration.

### ISSUE THREAD

**Issue by ZENALC** [oauth2-proxy/oauth2-proxy#2056]
Hey folks,

I have implemented OAuth2 Proxy with nginx and KeyCloak, and it works fantasticly when configuring it with frontend applications. My question is, for applications that are in the backend, how can I make them communicate with each other once they're protected with the OAuth2 proxy?

My initial thought process was to get an access token from KeyCloak and pass that in, but that doesn't really seem to work as it keeps complaining that the aud parameter is set to account, and that that's not a valid aud param? 

Then I thought, it'd be annoying to keep asking for tokens, so I'd just use basic auth in this case, but I can't seem to figure this one out? I couldn't really find any documentation anywhere.

- Version used:  7.4.0

**Comment by JoelSpeed** [comment]
For the backend tokens, you can configure `--extra-jwt-issuers` which can then share similar configuration to the normal keycloak instance, but with a secondary audience.

For basic auth, I think you need to create an `htpasswd` file, and then send the header you need to send looks roughly like `Authorization: Basic base64(user:password)`, by which I mean, base64 encode the user and password separated by a colon
