### ISSUE TITLE
404 Error when using allowed_groups query string on /auth enpoint

### ISSUE THREAD

**Issue by henriduflot** [oauth2-proxy/oauth2-proxy#2057]
I would like to pass allowed_groups query parameter to auth_request on nginx.
Maybe this is not a bug, it's possible that my nginx configuration is bad, I need some help :)

## Expected Behavior

I expect to have 202 Accepted response.

## Current Behavior

Nginx transfert the request to oauth2_proxy with encoded query param `%3Fallowed_groups=/admin`. Oauth2-proxy send 404 response.

` "/oauth2/auth%3Fallowed_groups=/admin" HTTP/1.0 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50" 404 19 0.035`

## Steps to Reproduce

Below my nginx configuration :

```
location /myapp/ {
        auth_request /oauth2/auth?allowed_groups=/admin;
        error_page 401 = /oauth2/sign_in;

        proxy_pass              http://localhost:9090/;
}

location /oauth2/ {
        proxy_pass              http://localhost:4180;
        proxy_set_header Host                    $host;
        proxy_set_header X-Real-IP               $remote_addr;
        proxy_set_header X-Scheme                $scheme;
        proxy_set_header X-Auth-Request-Redirect $request_uri;
}

location = /oauth2/auth {
        proxy_pass              http://localhost:4180;
        proxy_set_header Host             $host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Scheme         $scheme;
        # nginx auth_request includes headers but not body
        proxy_set_header Content-Length   "";
        proxy_pass_request_body           off;
        client_max_body_size    0;
}

```

Keycloak configurationed with oauth2-proxy client with oidc-group-membership-mapper

## Your Environment

- Version used:
nginx version: nginx/1.20.2
oauth2_proxy version : 7.4.0
keycloak version : 20.0.5

**Comment by JoelSpeed** [comment]
Have you configured the allowed groups flag to include the groups you're trying to allow through here? I believe there needs to be overlap

**Comment by oddlama** [comment]
@henriduflot
Since nginx escapes paths in `auth_request`, you have to work around that by using regular `auth_request /oauth2/auth` and instead modify the proxy pass in the match block for `/oauth2/auth`:

```nginx
location = /oauth2/auth {
    proxy_pass http://localhost:4180/oauth2/auth?allowed_groups=member;
    # ...
}
```
