### ISSUE TITLE
Specific Headers are still sent to Upstream even after disabling them

### ISSUE THREAD

**Issue by VF-mbrauer** [oauth2-proxy/oauth2-proxy#2061]
## Expected Behavior

If we for example set the following value
```
 env:
     - name: OAUTH2_PROXY_PASS_USER_HEADERS
       value: "false"
```
which includes
``` 
pass X-Forwarded-User, X-Forwarded-Groups, X-Forwarded-Email and X-Forwarded-Preferred-Username 
information to upstream
```
we would expect that those headers will not be passed to the upstream Webserver. Because of the `false` flag
it should be blocked and skipped.

## Current Behavior

We can still see that in the upstream Webserver this Header has been passed. So, the `false` flag has not blocked them from
being sent to the destination.

## Possible Solution

By setting the **OAUTH2_PROXY_PASS_USER_HEADERS** to `false` skip sending this header to upstream servers.

## Steps to Reproduce (for bugs)

Just change OAUTH2_PROXY_PASS_USER_HEADERS flag between `false` and `true` and dump the headers at the upstream.

**Comment by VF-mbrauer** [comment]
This issue describes already the same behavior:
https://github.com/oauth2-proxy/oauth2-proxy/issues/1902

**Comment by JoelSpeed** [comment]
This sounds like it could be a bug, have you tried using the flag value rather than the env var? I wonder if there could be a bug in the conversion between the two

**Comment by VF-mbrauer** [comment]
@JoelSpeed I tried that right now

```
 containers:
 - args:
   - --http-address=0.0.0.0:4180
   - --config=/bitnami/oauth2-proxy/conf/oauth2_proxy.cfg
   - --pass-user-headers=false
```

**Without** success. Still seeing the header send to upstream.

**Comment by VF-mbrauer** [comment]
(!) Quick update. I guess it is because of the OR condition

```
if l.PassBasicAuth || l.PassUserHeaders {
		requestHeaders = append(requestHeaders, getPassUserHeaders(l.PreferEmailToUser)...)
		requestHeaders = append(requestHeaders, getPreferredUsernameHeader())
	}
```

so with that
``` 
- args:
  - --http-address=0.0.0.0:4180
  - --config=/bitnami/oauth2-proxy/conf/oauth2_proxy.cfg
  - --pass-user-headers=false
  - --pass-basic-auth=false
```
it works.

The question is if this concept makes sense. Please check the possibilities and the usability of this.

**Comment by VF-mbrauer** [comment]
@JoelSpeed Any news here on my last comment? Thanks.

**Comment by VF-mbrauer** [comment]
@JoelSpeed What are we going to do with that issue? Seems that here is no news so far?

**Comment by VF-mbrauer** [comment]
@JoelSpeed  What are we going to do with that issue? Seems that here is no news so far?

**Comment by JoelSpeed** [comment]
I think this needs someone to spend the time to investigate and work out exactly what is wrong and then come up with the appropriate fix, do you have time to come up with a fix?
