### ISSUE TITLE
Fragment is lost after redirect if --skip-provider-button is set to true

### ISSUE THREAD

**Issue by pxnis** [oauth2-proxy/oauth2-proxy#2068]
Fragment is lost after redirect if --skip-provider-button is set to true.

## Expected Behavior

Fragment is preserved after redirect, even if "--skip-provider-button=true".

## Current Behavior

Fragment is lost after redirects if "--skip-provider-button=true".
If "--skip-provider-button=false" (or unset), and you manually press the provider button, the fragment is preserved.

## Possible Solution

Seems that the fragment/hash is preserved in:
/pkg/app/pagewriter/sign_in.html (line 103)

This code is never run, if the page is skipped?

## Steps to Reproduce (for bugs)

BUG:
Setup where oauth2-proxy is configured with "--skip-provider-button=**true**"
1.  Open an url with fragment. e.g.: example.com/my/path#/my/fragment
2.  Provider-button-page is skipped and redirect directly to provider
3.  Authenticate with your provider
4.  oauth2-proxy redirects back to original request and fragment is lost. e.g.: example.com/my/path

WORKING:
Setup where oauth2-proxy is configured with "--skip-provider-button=**false**" (or unset)
1.  Open an url with fragment. e.g.: example.com/my/path#/my/fragment
2.  Click your provider at the provider-button-page redirect to provider
3.  Authenticate with your provider
4.  oauth2-proxy redirects back to original request and fragment is preserved. e.g.: example.com/my/path#/my/fragment

## Context

We save some page-state in the fragment. This state is lost if the end-user starts their session from a fragment-url.
Not critical as this is not widespread behavior and the end-user can fix it by clicking the link again after authentication.

## Your Environment

oauth2-proxy v7.4.0 using official docker images.
Running behind as reverse-proxy (HAProxy), which is responsible for SSL termination, redirects, domain/path-validation and more.
Using rh-sso (Keycloak 18) as provider.

**Comment by pxnis** [comment]
Still relevant

**Comment by pxnis** [comment]
Still relevant

**Comment by JoelSpeed** [comment]
The only way to resolve this would be to change the way the skip provider button works to actually load the page still, run some javascript to capture the fragment, and then continue the redirect.

Currently the page isn't displayed at all and we go straight to the next step, however, fragments are not sent to the server, so they cannot be included. The only way to capture a fragment is client side.

**Comment by jerome-blanche** [comment]
Still relevant

**Comment by jerome-blanche** [comment]
> Still relevant

+1

**Comment by ricardo-mestre** [comment]
I think this is still relevant, would be great if a javascript redirection happens seamlessly to keep the fragment for redirection
