### ISSUE TITLE
Azure and CORS

### ISSUE THREAD

**Issue by zoriax** [oauth2-proxy/oauth2-proxy#2072]
## Expected Behavior

Allow oauth2-proxy to refresh cookie on ajax call with Azure and prevent cors problem

## Current Behavior

Actually, if the cookie as expired and an Ajax call is done, browser failed with cors problem

```
Access to XMLHttpRequest at 'https://login.microsoftonline.com/1234/oauth2/v2.0/authorize?approval_prompt=force&client_id=id&redirect_uri=https://myapp/oatuh2/callback&response_type=code&scope=openid+email+profile' (redirected from 'https://myapp/app/ajax') from origin 'https://myapp/app/ajax' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
````

## Possible Solution

For now, the only way to prevent this behavior is to extend cookie lifetime. I'm not sure if the problem is related to (in chain)

Azure --> Oauth2-Proxy --> Nginx --> Upstream (for me it's Azure but...)

Your help is **warmly welcome**. Maybe a solution already exists with oauth2 or with Azure but I definitely can't find the way to solve this.

Something here but it's not totally clear : https://github.com/oauth2-proxy/oauth2-proxy/issues/987

## Steps to Reproduce (for bugs)

Azure and application with Ajax call. Delete cookie and try to do an ajax call.

## Your Environment
Version used:  v 7.4.0

**Comment by JoelSpeed** [comment]
I remember looking at this about 2 or 3 years ago and I had thought we had got ajax calls working. I think this will need someone to dig into the issue to try and understand what request is being made and what response is being sent back.

Where is the log line you mention coming from for example?

**Comment by zoriax** [comment]
Hi !

Thanks for your feedback. 

The log I provided come from my browser console. After reaching MS Azure Support, it looks like it doesn't support CORS by default, it's not fully clear but Microsoft didn't have any satisfying answer about CORS.

It's certainly possible to use oauth2 for having a correct behavior when an Ajax call is done but effectively we need some help because I'm not a specialist :-)

Let see if someone can help us.

**Comment by puneety95** [comment]
@zoriax Please let me know if you find any solutions. Facing the same problem.

**Comment by zoriax** [comment]
Hi @puneety95 ! 

No nothing found yet to solve this behavior :-( ! As I said previously I think we need some more help. I'm not a specialist, so it's difficult for me to debug.

**Comment by NeutronSelector** [comment]
Hi

This issue occurs because the proxy returns an HTTP 302 return on the connection URL of the provider used. This behavior is prohibited by browsers by the cors "same-origin" policy applied to XHR requests.
One solution, I think, will be to differentiate response behavior based on request type (XHR or classic) and return an HTTP 401 when the request is of type XHR.
In this case, no CORS policy error occurs on XHR calls and the HTTP 401 is easy to handle in the client application to redirect to the application login page or a refresh page to trigger a reconnection by a non-XHR request.
Or alternatively, 302 redirect in XHR request to app login page rather than provider login page should also work. This URL could be given in the configuration.

Making a configuration to manage this behavior will be nice.

I hope I have provided some ideas/solutions.

**Comment by zoriax** [comment]
I reopen this case because the problem is not solved.

**Comment by fabianboerner** [comment]
Same iss ue here.

**Comment by jeffwmiles** [comment]
I've encountered this issue as well - is it possible to re-open?

**Comment by hnaidin** [comment]
I've encountered the same issue, the setup i have is (kubernetes) nginx ingress -> oauth2_proxy -> spa -> api. Microsoft as IDP
I've worked around this issue by adding offline_access to the scope, then setting a cookie_refresh smaller than cookie_expiry.
This way, each time the session refreshes, the access token is refreshed successfully.
This did not solve the inactive tab situation where the user would switch tabs for a few hours, then come back to an error screen, so ultimately i had to add a polling mechanism in one of the frontend calls to the api. This guarantees that the session gets refreshed in time, even when the user is not in the browser tab.
