### ISSUE TITLE
allowed_group for url paths

### ISSUE THREAD

**Issue by mtmSchoenberger** [oauth2-proxy/oauth2-proxy#2073]
how can i define per url path which groups have access to it?
e.g. /Service1: Group1
/Servuce2:Group2 ?

## Current Behavior
if i use the allowed_group option, users with this group can access all services but i want to allow different groups to access different services  

## Possible Solution
I think I need to set my config correctly however I can't find the right way from the documentation.

## Your Environment
```
allowed_groups = [
  "/backend:admins",
  "/backend:user
]
```

Nginx reverse Proxy
oAuth2 Proxy v. 7.4.0
Windows Server

**Comment by tolleiv** [comment]
I think this is a duplicate of #2011
