### ISSUE TITLE
Need guidance for "Error redeeming code during OAuth2 callback: could not verify id_token" error with generic OIDC provider

### ISSUE THREAD

**Issue by C-Duv** [oauth2-proxy/oauth2-proxy#2074]
## Expected Behavior

Once the user is redirected to the redirect URL (`oauth2/callback`) from the authorization server he should see the upstream's page.

## Current Behavior

Instead, on the redirect URL he gets a gets an error message:

> 500 Internal Server Error
>
> More Info: could not verify id_token: failed > to verify token: failed to verify signature: failed to verify id token signature Request ID: 543ed244-8197-4054-a52b-d1e3973eb73c

OAuth2 Proxy logs confirm the error, adding it's about code redeeming:

> Error redeeming code during OAuth2 callback: could not verify id_token: failed to verify token: failed to verify signature: failed to verify id token signature

## Steps to Reproduce (for bugs)

1. User opens https://my-app.example.com
2. User is displayed the "Authenticate using…" page from OAuth2 Proxy
3. User clicks on the "Sign in with a …" button
4. User gets served the login form from the authorization server (on https://auth.example.com)
5. Users logs in and give it's consent
6. User is redirected back to OAuth2 Proxy where it gets the error message

Here is my OAuth2 Proxy configuration file for [`oidc` provider](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#openid-connect-provider) (I am running it locally for test):

```lang-toml
http_address = "127.0.0.1:80"
https_address = "127.0.0.1:443"

tls_cert_file = "/etc/ssl/certs/ssl-cert-snakeoil.pem"
tls_key_file = "/etc/ssl/private/ssl-cert-snakeoil.key"

redirect_url = "https://my-app.example.com/oauth2/callback"

# Using the very simple web site https://perdu.com as an example upstream for tests:
upstreams = [
    "https://perdu.com"
]

whitelist_domains = [
    ".example.com",
    "my-app.example.com",
    "perdu.com"
]

ssl_upstream_insecure_skip_verify = true

email_domains = [
    "*"
]
insecure_oidc_allow_unverified_email = true

provider = "oidc"

oidc_issuer_url = "https://auth.example.com"

oidc_email_claim = "email"

client_id = "my-app"
client_secret = "my-app-secret"

code_challenge_method = "S256"

ssl_insecure_skip_verify = true

cookie_name = "_oauth2_proxy"
cookie_secret = "3Wvi9Yv0YOsU4GNvldd9bRSUfNW6u9P_WPxjPAipZB0="
cookie_domains = ".example.com"
cookie_samesite = "lax"
cookie_expire = "168h"
cookie_refresh = "4h"
cookie_httponly = false
cookie_csrf_per_request = true

show_debug_on_error = true
```

And the *Relying Party* configuration of my authorization server (an OpenID Connect Provider implemented by [LemonLDAP::NG](https://lemonldap-ng.org), see [documentation](https://lemonldap-ng.org/documentation/2.0/idpopenidconnect.html)):

* OpenID Connect claims:
  * `email`
  * `id`
  * `preferred_username`
  * `username`
* Basic options:
  * Client ID: my-app
  * Client secret: my-app-secret
  * Public client: true
  * Redirection addresses :
    * https://my-app.example.com
    * https://my-app.example.com/oauth2/callback
* Advanced options:
  * Bypass consent: false
  * User attribute: *(none/empty)*
  * Force claims to be returned in ID Token: false
  * Use JWT format for Access Token: false
  * Release claims in Access Token: false
  * Additional audiences: *(none/empty)*
  * Use refresh tokens: false
* Security options:
  * ID Token signature algorithm: HS512
  * Access Token signature algorithm: RS256
  * Userinfo response format: JSON
  * Require PKCE: false
  * Allow offline access: false
  * Allow OAuth2.0 Password Grant: false
  * Allow OAuth2.0 Client Credentials Grant: false
  * Authentication Level: *(none/empty)*
  * Access Rule: *(none/empty)*
* Timeouts options:
  * Authorization Code expiration: *(none/empty)*
  * ID Token expiration: *(none/empty)*
  * Access token expiration: *(none/empty)*
  * Offline session expiration: *(none/empty)*

## Context

My ultimate goal is to add SSO authentication to an existing simple web app without implementing auth in the app (can't really alter the code of the application).

For now I am just manually executing OAuth2 Proxy but in the end I'll use Træfik or Nginx with `auth_request`.

I blindly tried disabling `code_challenge_method` or changing it to `plain` without success.

How can I debug the received code?

I also noticed that the authorization server was receiving a `POST /oauth2/token` followed by a `GET /oauth2/jwks` from OAuth2 Proxy (see full logs below).
But as this authorization server is also used for authentication with other OpenID Connect compatible applications (such as Mattermost) I can compare and, with theses the authorization server receives a `POST /oauth2/token` **followed by a `GET /oauth2/userinfo`** (not a `/oauth2/jwks`).

## Environment

- OAuth2 Proxy version used: 7.4.0
- OS: Ubuntu 22.04
- Browser: Firefox

## Logs

<details>
  <summary>Full OAuth2 Proxy logs</summary>

  ```
  127.0.0.1:48784 - d51481a0-c867-4a71-ba6d-8ea595380af4 - - [2023/03/31 11:55:21] my-app.example.com GET - "/oauth2/start?rd=%2F%3F" HTTP/1.1 "Firefox" 302 422 0.000
  [2023/03/31 11:55:22] [oauthproxy.go:823] Error redeeming code during OAuth2 callback: could not verify id_token: failed to verify token: failed to verify signature: failed to verify id token signature
  127.0.0.1:48784 - 543ed244-8197-4054-a52b-d1e3973eb73c - - [2023/03/31 11:55:22] my-app.example.com GET - "/oauth2/callback?code=515c…fa38&session_state=335f…QkE9&state=M631…rt_I%3A%2F%3F" HTTP/1.1 "Firefox" 500 2872 0.127
  [2023/03/31 11:55:22] [oauthproxy.go:959] No valid authentication in request. Initiating login.
  ```
</details>

<details>
  <summary>Full HTTP LemonLDAP::NG `access.log`</summary>

  ```
  2.2.2.2 - - [31/Mar/2023:11:57:27 +0200] "GET /oauth2/authorize?approval_prompt=force&client_id=my-app&code_challenge=-RQC…ffdc&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fmy-app.example.com%2Foauth2%2Fcallback&response_type=code&scope=openid+email+profile&state=M631…rt_I%3A%2F%3F HTTP/1.1" 302 5 "https://my-app.example.com/" "Firefox"
  2.2.2.2 - my-app [31/Mar/2023:11:57:27 +0200] "POST /oauth2/token HTTP/1.1" 200 623 "-" "Go-http-client/1.1"
  2.2.2.2 - - [31/Mar/2023:11:57:27 +0200] "GET /oauth2/jwks HTTP/1.1" 200 749 "-" "Go-http-client/1.1"
  2.2.2.2 - - [31/Mar/2023:11:57:27 +0200] "POST / HTTP/1.1" 200 107 "https://auth.example.com/" "Firefox"
  ```
</details>

**Comment by C-Duv** [comment]
Problem solved by setting the "ID Token signature algorithm" of the authorization server to **RS256** (instead of "HS512").

It looks a similar solution as the one in https://github.com/oauth2-proxy/oauth2-proxy/issues/1338#issuecomment-1293806744.

**Comment by alank976** [comment]
Hi @C-Duv 

What if I really want to use **HS512** for my authorization server? How can I configure oauth2-proxy to verify the ID token verification algorithm to be something else?

Currently, I am skipping OIDC discovery and using `--oidc-jwks-url`. The endpoint response of the JWK set only provides two entries and both are not RS but ES algos:
```
{
  "keys" : [
    {
      "alg" : "ES512",
      "crv" : "P-521",
      "kid" : "XzdHuAU2ndBynboG3Ki-XanX1wk",
      "kty" : "EC",
      "use" : "sig",
      "x" : "AdFhBw5sWnRB75WGbTnibyZllv0xntc1KV3Tz9h0LQxtC0ycC4uUnxLB3tuNBSxp4FvOdL7vklKtCPOcRk64KbOC",
      "x5c" : [
        "MIIBwzCCASWgAwIBAQIQQSUzKz/CSFG3Ziq6eSHhBzAKBggqhkjOPQQDBDAgMR4wHAYDVQQDExVodHRwOi8vYXV0aC5hYXphaS5jb20wHhcNMjMwNDI2MTQxNDUxWhcNMzMwNDI2MTQxNDUxWjAgMR4wHAYDVQQDExVodHRwOi8vYXV0aC5hYXphaS5jb20wgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAHRYQcObFp0Qe+Vhm054m8mZZb9MZ7XNSld08/YdC0MbQtMnAuLlJ8Swd7bjQUsaeBbznS+75JSrQjznEZOuCmzggCM2rYtxuPwq3r5wuoXRiT/nZvWJZhq/Lpkn1CMejEjCLkthlzmnsBPZXoL46KD2tKxETBF3THnDQHMjOprVp7psjAKBggqhkjOPQQDBAOBiwAwgYcCQTGy35/dKxk0huMqK9c4TpsTas2CALyOGcXgJC3eZvvNeQ0KjfG784qo5X+8ChswMZNaGV5e/0VkYt+0qj3oJgUpAkIBTiK4Y6Mmjx6Ce02wIrp6aw2rMl57tnMDKZLzxZUA5ZHS3w86MzLKkKIH/WaKyNlI3MtimBa4jxPFVaEZ3DYgMaA="
      ],
      "x5t" : "XzdHuAU2ndBynboG3Ki-XanX1wk",
      "x5t#S256" : "Gx5bbNBkCv8kSfGplPcvtCKfMllBTpx_vyjhKUCvluk",
      "y" : "AIzati3G4_CrevnC6hdGJP-dm9YlmGr8umSfUIx6MSMIuS2GXOaewE9legvjooPa0rERMEXdMecNAcyM6mtWnumy"
    },
    {
      "alg" : "ES512",
      "crv" : "P-521",
      "kid" : "QuH9FcETVYTjqBKv1nPgho7lh0s",
      "kty" : "EC",
      "use" : "sig",
      "x" : "AP_kvJKL0hpvWnJEA7MwjkZ3TIuraKm0IiQeIdCgrSkZombsVgscO2RbQe9FmsjsROAly6yMHqrT7bBJj657ZtIE",
      "x5c" : [
        "MIIBxTCCASagAwIBAQIRAN+zWE+lx0cvjprA/hyNc2kwCgYIKoZIzj0EAwQwIDEeMBwGA1UEAxMVaHR0cDovL2F1dGguYWF6YWkuY29tMB4XDTIzMDQyNjE0MTQ1MVoXDTMzMDQyNjE0MTQ1MVowIDEeMBwGA1UEAxMVaHR0cDovL2F1dGguYWF6YWkuY29tMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQA/+S8kovSGm9ackQDszCORndMi6toqbQiJB4h0KCtKRmiZuxWCxw7ZFtB70WayOxE4CXLrIweqtPtsEmPrntm0gQBHZwD5bCQCk7XLWjwUsvCqT7MTAPzGNITlfGGtu0unQM3livZxVqpaF+YP3t4HzyVox5K+R1DvldUgwTJ8RjfAFYwCgYIKoZIzj0EAwQDgYwAMIGIAkIBaZRSvOvNtpQOZ0tQRrwp6XPz+Y+6o9iEtSPnN6D3AvQHALYo+vhs4RVnHdUZ8BwmcCWxS+yFo4a6RAw4vFHwt80CQgDrWAiGpZS9+FyPagqyKCoc+qlCceCssjFs1Cf16ati/9WFL4qzBqvjburxtNZZ4D3Ly5+yyGb9i52hKLQmccEYjw=="
      ],
      "x5t" : "QuH9FcETVYTjqBKv1nPgho7lh0s",
      "x5t#S256" : "btbIoe40c67OEum69mVxLnL4xsWiCAzrwwP7eQx7h34",
      "y" : "AR2cA-WwkApO1y1o8FLLwqk-zEwD8xjSE5XxhrbtLp0DN5Yr2cVaqWhfmD97eB88laMeSvkdQ75XVIMEyfEY3wBW"
    }
  ]
}
```

(Asked similar question in https://github.com/oauth2-proxy/oauth2-proxy/issues/1100#issuecomment-1523497828)

**Comment by C-Duv** [comment]
> What if I really want to use **HS512** for my authorization server? How can I configure oauth2-proxy to verify the ID token verification algorithm to be something else?

I guess you can't because it seems to be hardcoded: https://github.com/oauth2-proxy/oauth2-proxy/blob/d9416c3630d4b888441425691b57f01dab64bda8/providers/logingov.go#L217

**Comment by mhsraft** [comment]
@C-Duv 
I have the same issue. here is my oauth2-proxy config

provider = "oidc"
oidc_issuer_url= "https://.salesforce.com"
redirect_url= "https://mydomain/oauth2/callback"
profile_url=    "https://mydomain/services/oauth2/userinfo"
scope= "openid email profile"
pass_host_header = true
reverse_proxy = true
auth_logging = true
cookie_httponly = true
cookie_refresh = "4m"
cookie_secure = true
email_domains = "*"
pass_access_token = true
pass_authorization_header = true
request_logging = true
session_store_type = "cookie"
set_authorization_header = true
set_xauthrequest = true
silence_ping_logging = true
skip_provider_button = true
skip_auth_strip_headers = false
ssl_insecure_skip_verify = true
standard_logging = true
upstreams = [ "static://200" ]
whitelist_domains = [".mydomain"]
code_challenge_method = "S256"


I am getting the same error
```
Error redeeming code during OAuth2 callback: token exchange failed: Post
```
As I know salesforce uses RS256 

],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],

how should I change oauth2-proxy to support RS256.

I am getting 500 error
