### ISSUE TITLE
Load Testing 

### ISSUE THREAD

**Issue by thebestgin** [oauth2-proxy/oauth2-proxy#2078]
Has anyone done some load testing yet? With cookies and redis?

As reverse proxy and with nginx auth_request? 

I would like to understand how much routing is restricted. Without redis it is possible to scale. With redis the performance depends on redis. 

Are there any results on this yet?

**Comment by JoelSpeed** [comment]
Not something maintainers have explored to my knowledge, if any does know how to do this and has an interest in building some benchmarks I think that would be cool to see though
