### ISSUE TITLE
aud claim in access token missing "api://" prefix

### ISSUE THREAD

**Issue by seumassoltysik** [oauth2-proxy/oauth2-proxy#2083]
I am using the oauth2-proxy/oauth2-proxy:v7.2.1-amd64 docker image with an Azure AD application. The access token created by oauth2-proxy specifies an audience claim that looks like this:
**"aud": "95283728-3dda-4a9e-a3af-e3d0586a4cac",**
However, when I go to validate this token in my backend service with the MSAL library, the token does not validate because the expectation is that the aud value should look like this:
**"aud": "api://95283728-3dda-4a9e-a3af-e3d0586a4cac",**

Is this an issue with how the token is generated by oauth2-proxy or could this be an issue with the MSAL library, or even how the Azure app itself is configures?

**Comment by EA12** [comment]
I run into the same issue. Did you found a solution? Can you please share it?
thanks!
