### ISSUE TITLE
Update Docker Image(and change update cycle)

### ISSUE THREAD

**Issue by T2brozz** [oauth2-proxy/oauth2-proxy#2091]
The Docker Image is currently only getting build after a full release. But in this half year there were a couple vulnerabilities: libcrypto and libssl. I think there were less if the Image dependencies were up-to-date 

## Expected Behavior

A docker image with Up-to-date dependencies. 

## Current Behavior

[12 vulnerabilities ](https://quay.io/repository/oauth2-proxy/oauth2-proxy/manifest/sha256:2393626f07ad63d92a31dfc5e133e3dfff9d2758b638363bf171467578742b77?tab=vulnerabilities)

## Possible Solution

Build the Docker image weekly

**Comment by tolleiv** [comment]
see also #2051

**Comment by T2brozz** [comment]
welp saw there are GitHub actions, that build the docker container, but it never gets published. I think it could be relative simple to publish it to dockerhub.
