### ISSUE TITLE
Session refresh doesn't work for azure provider using v2.0 api (Microsoft Identity Platform)

### ISSUE THREAD

**Issue by nhahn1312** [oauth2-proxy/oauth2-proxy#2095]
When using the oauth proxy with the azure ad provider and the v2.0 api the session refresh doesn't work. "Session is expired".

## Expected Behavior

The session refresh works as intended after the "cookie_refresh" is due.

## Current Behavior

The session refresh doesn't work because the oauth proxy expects an "expires_on" field in the response of azure ad.
This field is present for v1.0, but not for v2.0.

See these sample responses for further information :

POST https://login.microsoftonline.com/{tenant}/oauth2/token
{
    "token_type": "Bearer",
    "expires_in": "3599",
    "ext_expires_in": "3599",
    "expires_on": "1682359943",
    "access_token": "example_access_token",
    "refresh_token": "example_refresh_token",
    "id_token": "example_id_token"
}

POST https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token
{
    "token_type": "Bearer",
    "scope": "profile openid email User.Read User.Read.All",
    "expires_in": 4037,
    "ext_expires_in": 4037,
    "access_token": "example_access_token",
    "id_token": "example_id_token"
}

There are two sections in the code, where the azure provider  expects "expires_on", but should expect "expires_in" for v2.0:

- Redeem "Method"
- redeemRefreshToken "Method"

## Possible Solution

See MR 

## Steps to Reproduce (for bugs)

1.  Follow the steps to connect a v2.0 azure provider in the documentation
2.  Set cookie_refresh to a short time. I. e. "1m" => oauth proxy logs "session expired"

- Version used: V.7.4.0

**Comment by JoelSpeed** [comment]
Seems like we need separate v1 and v2 providers for Azure, they seem to be incompatible in many ways. This will need someone with a vested interest in Azure to take a look at restoring the old v1 provider and creating a separate v2 provider IMO
