### ISSUE TITLE
How to configure oauth2-proxy to use TLS to redis

### ISSUE THREAD

**Issue by lmsurpre** [oauth2-proxy/oauth2-proxy#2099]
I'm deploying oauth2-proxy with the redis subchart via helm.
This was working fine, but when I set redis.tls.enabled to true, oauth2-proxy can no longer write to the store.

## Expected Behavior

oauth2-proxy works with redis that uses TLS

## Current Behavior

Error during startup:
> [2023/04/26 13:36:11] [main.go:54] invalid configuration:
  unable to set a redis initialization key: write: broken pipe
  unable to delete the redis initialization key: write: broken pipe

## Possible Solution

I found https://github.com/oauth2-proxy/oauth2-proxy/pull/2040/files which documents a config parameter `--redis-insecure-skip-tls-verify`.
When I add that to my deploy (via "extraArgs"), it changes the error message a little but still no luck:
> [2023/04/26 13:27:58] [main.go:54] invalid configuration:
  unable to set a redis initialization key: write tcp 10.244.8.57:36230->10.0.195.90:6379: write: connection reset by peer
  unable to delete the redis initialization key: write tcp 10.244.8.57:36258->10.0.195.90:6379: write: connection reset by peer

## Steps to Reproduce (for bugs)

1. Create a helm override file to deploy oauth2-proxy with the following settings:
    * redis subchart is enabled
    * redis tls is enabled (i also set `redis.tls.autoGenerated: true` for simple cert management)
    * optionally, set `redis-insecure-skip-tls-verify: "true"` under "extraArgs"
2. Deploy oauth2-proxy via the helm chart 

Note that the oauth2-proxy pod fails to start because it cannot write to redis.

## Context

I'd like to ensure all traffic is encrypted (TLS).
I don't see anything in the docs about using a secure redis deployment.
Is it supported?
Am I doing something wrong?

## Your Environment

Azure Kubernetes Service (AKS)

Version used:
* application version:  7.4.0
* chart version:  6.8.0

**Comment by JoelSpeed** [comment]
Not something I've ever tried to be honest. We have a local environment for testing that has oauth2-proxy and redis set up with docker-compose, have you tried manually configuring that for TLS to see if that presents the same behaviour?

**Comment by tiehfood** [comment]
Did you tried to change the connection to `rediss://...`. It works for me using the Azure Redis Cache with SSL

**Comment by tuunit** [comment]
@lmsurpre did you get it working with the url scheme suggested by @tiehfood ?

**Comment by lmsurpre** [comment]
Finally got back to this and it seems to be working with oauth2-proxy chart version 6.23.x when I set
```
extraArgs:
  redis-insecure-skip-tls-verify: "true"
```
and 
```
redis:
  enabled: true
  tls:
    enabled: true
    authClients: false
    autoGenerated: true
  ...
```

not sure what i had done wrong previously.
i did not try changing the connection to explicitly use `rediss://` anywhere... was going to try that next if this didn't work :-)
