### ISSUE TITLE
different oidc behavior between 7.3 and 7.4

### ISSUE THREAD

**Issue by federicobarera** [oauth2-proxy/oauth2-proxy#2100]
## Expected Behavior

As in 7.3, access tokens requested via client_credentials are authorized

## Current Behavior

In 7.4, the same proxy configuration returns 403. To fix the issue, must change configuration to  `--email-domain=*`

## Steps to Reproduce (for bugs)

Using `oidc` provider with azure ad v2 (not azure provider). Following configuration. Need two azure ad applications. 

* for the proxy **{oauth2-proxy-app}**
* for the client **{client-app}**

Proxy Config

```
- --reverse-proxy=true
- --provider=oidc
- --provider-display-name=...
- --oidc-issuer-url=https://login.microsoftonline.com/{{ .Values.tenantId }}/v2.0
- --http-address=***
- --cookie-name=***
- --cookie-secure=true
- --email-domain=contoso.com
- --pass-access-token=true
- --pass-user-headers=true
- --pass-authorization-header=true
- --upstream=***
- --set-xauthrequest=true
- --skip-jwt-bearer-tokens=true
- --client_id={oauth2-proxy-app}.client_id
- --client_secret={oauth2-proxy-app}.client_secret
- --cookie_secret=***
- --exclude-logging-path=/ping
```

Token Acquisition

```
POST /{tenant}/oauth2/v2.0/token HTTP/1.1               // Line breaks for clarity
Host: login.microsoftonline.com:443
Content-Type: application/x-www-form-urlencoded

scope={oauth2-proxy-app}/.default
&client_id={client-app}.client_id
&client_secret={client-app}.client_secret
&grant_type=client_credentials
```

## Context

The access_token doesn't contain email claims. What verifications are done on the access token, given the `--skip-jwt-bearer-tokens=true`. What is the intended behavior? What claims are necessary to be added to the access token to pass verification?

## Your Environment

AKS
quay.io/oauth2-proxy/oauth2-proxy:v{{ .Values.appVersion }}

- Version used: 7.3, 7.4

**Comment by JoelSpeed** [comment]
I believe the issue is that the scope has changed, have you tried manually setting the scope to include the `email` parameter, I guess it should be `openid email profile` but worth double checking as I know Azure has some additional stuff depending on the version

**Comment by federicobarera** [comment]
@JoelSpeed I am not sure this is related to aad. The issue is for clients using client_credentials flow, hence not initiating the flow via the oauth proxy. The way the client is requesting tokens to aad has not changed. The same token is accepted by 7.3 and rejected by 7.4.

Since this is a server to server flow, there is no email claim.

**Comment by JoelSpeed** [comment]
@federicobarera Did you get to the bottom of this issue?
