### ISSUE TITLE
OpenID with Okta provider - using Okta assigned group instead of a user does not pass authentication 

### ISSUE THREAD

**Issue by kaplanben** [oauth2-proxy/oauth2-proxy#2103]
We're trying to see how (and if possible) to configure authentication to our app using Okta groups.
When assigning a user directly to the application in Okta all seems to work as expected, but when the user is assigned indirectly via an Okta group we get `User is not assigned to the client application` error.

## Expected Behavior
Oauth2-proxy to infer from the Okta user group membership if he's a member of a group that is assigned to the Okta application.
The flow we first expected to occur is:
- Is the requested user a member of a group that is currently assigned to the Okta app?
- If so, he should be able to log in.
- by reading the user's Okta groups in the request headers we can set the wanted permissions to the user.

## Current Behavior
Getting `403` error and `User is not assigned to the client application` in logs.

## Steps to Reproduce (for bugs)

1.  Create an OpenID Okta app
2.  Create Okta group
3.  Assign the group to the Okta app
4.  Try to log in using a member of that group.

## Context
We're trying to control both authentication and authorization with Okta+oauth2-proxy.
Using the `groups` claim oauth2-proxy is aware of the Okta groups that the user is a member of.
So we can control our app authorization by using the `groups` claim just fine.

However, the only way we managed to pass authentication is by assigning the user directly (not via a group) to the Okta app.

- This means that we need to manage all users that should be authenticated over the Okta app
- In addition, we need to assign each user to the proper groups for ACLs and permissions

## Your Environment
1. Nginx in front of oauth2-proxy 
2. config files are taken from [here](https://developer.okta.com/blog/2022/07/14/add-auth-to-any-app-with-oauth2-proxy)

- Version used: oauth2-proxy v7.4.0 (built with go1.19.2)

**Comment by kaplanben** [comment]
still relevant

**Comment by kaplanben** [comment]
still relevant

**Comment by ilangersht1** [comment]
Following this

**Comment by tuunit** [comment]
This seems to be a feature of Okta itself. Which is not generic to OIDC. Meaning this would require a new custom Okta provider to be created.

**Comment by JoelSpeed** [comment]
Is the error `User is not assigned to the client application` shown by OAuth2 Proxy, or is it show as part of the Okta dashboard? Can you provide any more detail about where in the flow this occurs?

**Comment by kaplanben** [comment]
@JoelSpeed, seems that this error is from the Okta side. When trying to log in via oauth2-proxy:

- The first response is a `302` redirect to our Okta domain `/oauth2/v1/authorize?approval_prompt=force...`
- The response for the above redirect is another `302` redirect back to oauth2-proxy which issues a `403` status
- The `403` error page states a request ID e.g. `Login Failed: The upstream identity provider returned an error: access_denied Request ID: c1c65f8d-8b76-454b-8371-2456562d04e3`
- And the redirect URI (from Okta to oauth2-proxy) contain the error in it `https://<oauth2_protected_service>/oauth2/callback?...&error=access_denied&error_description=User+is+not+assigned+to+the+client+application`

I confirm that I am a member of a group that is assigned to this app on the Okta side. To reproduce this error I removed my user which was explicitly assigned to the Okta app in addition to the group assignment 

![Xnip2023-11-06_13-18-41](https://github.com/oauth2-proxy/oauth2-proxy/assets/77549469/0a1f34b9-8a35-4863-b01f-4b29cd5fad15)

**Comment by kaplanben** [comment]
ping

**Comment by kaplanben** [comment]
ping

**Comment by kaplanben** [comment]
:(

**Comment by Leifs-life** [comment]
This would be a great feature. Currently it's only possible to use applications implementing the "Everyone" group, which doesn't help when trying to use specific groups. Any comment from the team would be greatly appreciated!
