### ISSUE TITLE
--cookie-refresh broken with azure provider

### ISSUE THREAD

**Issue by mikefab-msf** [oauth2-proxy/oauth2-proxy#2108]
Sessions with Azure provider are broken for two reasons:
- #2095
- Refresh token is not returned because 'remote_access' is not added to scope.

## Expected Behavior

jsonResponse from Azure provider should return refresh_token if --cookie-refresh is set to an amount of time.

## Current Behavior

Refresh token is not returned and session is unable to be refreshed.

## Possible Solution

If --cookie-refresh exists and is set to a non zero value, add 'offline_access' to azureV2Scope.

## Steps to Reproduce (for bugs)

1.  Follow the steps to connect a v2.0 azure provider in the documentation
2.  Set cookie_refresh to a short time. I. e. "1m" => oauth proxy logs "session expired"

## Your Environment

- Version used:  V.7.4.0

**Comment by JoelSpeed** [comment]
I think the documentation probably needs an update, rather than guessing what users meant, they should just add `offline_access` to the scope when they configure the project. Adding configuration for users like this doesn't tend to age well
