### ISSUE TITLE
AuthFailure Invalid authentication via OAuth2: unable to obtain CSRF cookie

### ISSUE THREAD

**Issue by codevally** [oauth2-proxy/oauth2-proxy#2110]
## Expected Behavior
Expecting a successful login from IE mode over Edge

## Current Behavior
Getting a 403 response: "AuthFailure Invalid authentication via OAuth2: unable to obtain CSRF cookie"

## Possible Solution
Applied most of the possible options and configurations, but no luck.
Tried #1937, but didn't helped.

## Steps to Reproduce (for bugs)
Every time when I try to login from IE mode over Edge. Chrome is working fine.

## Your Environment
OAuth-Proxy 7.4.0
EKS 1.23

Startup parameters:

          - --http-address=0.0.0.0:4180
          - --metrics-address=0.0.0.0:44180
          - --redirect-url=https://site.mydomain.com/oauth2/callback
          - --oidc-issuer-url=https://sso.mydomain.com/dex
          - --whitelist-domain=.mydomain.com
          - --client-id=hidden
          - --client-secret=hidden
          - --cookie-secret=hidden
          - --provider=oidc
          - --scope=openid profile email
          - --email-domain=email.com
          - --skip-provider-button=true
          - --session-store-type=cookie
          - --cookie-samesite=lax
          - --cookie-secure=true
          - --reverse-proxy=true
          - --pass-access-token=true
          - --pass-authorization-header=true
          - --cookie-csrf-per-request=true
          - --cookie-csrf-expire=5m
          - --cookie-refresh=5m
          - --set-xauthrequest=true
          - --set-authorization-header=false
          - --skip-oidc-discovery=true
          - --login-url=https://sso.mydomain.com/dex/auth
          - --oidc-jwks-url=https://sso.mydomain.com/dex/keys
          - --redeem-url=https://sso.mydomain.com/dex/userinfo

- Version used:
v7.4.0

**Comment by aleks-programmer** [comment]
Maybe 5 minutes is passed since the request.
I am talking about cookie-csrf-expire
