### ISSUE TITLE
Can't install on Amazon Linux 2023

### ISSUE THREAD

**Issue by chadmyers** [oauth2-proxy/oauth2-proxy#2115]
Spin up a fresh EC2 instance on Amazon Linux 2023/arm64, install golang 1.19, attempt to install oauth2-proxy but get error:  `go: github.com/oauth2-proxy/oauth2-proxy@v7.4.0: github.com/oauth2-proxy/oauth2-proxy@v7.4.0: invalid version: go.mod has post-v7 module path "github.com/oauth2-proxy/oauth2-proxy/v7" at revision v7.4.0`

## Expected Behavior

oauth2-proxy to be installed with no errors

## Current Behavior

Error from go: 
```
go: github.com/oauth2-proxy/oauth2-proxy@v7.4.0: github.com/oauth2-proxy/oauth2-proxy@v7.4.0: invalid version: go.mod has post-v7 module path "github.com/oauth2-proxy/oauth2-proxy/v7" at revision v7.4.0
```

## Steps to Reproduce (for bugs)

Launch a new Amazon Linux 2023 EC2 instance on arm64 (I used a t4g.medium instance type) and connect to it and then run:

```
sudo dnf update -y -q
sudo dnf install golang -y -q
sudo go install github.com/oauth2-proxy/oauth2-proxy@v7.4.0
```

I also tried:
```
sudo go install github.com/oauth2-proxy/oauth2-proxy@latest
```

But that attempts to install v3.2.0 and, after installing several modules, fails with error:

```
go: finding module for package gopkg.in/fsnotify/fsnotify.v1
/root/go/pkg/mod/github.com/oauth2-proxy/oauth2-proxy@v3.2.0+incompatible/watcher.go:11:2: cannot find module providing package gopkg.in/fsnotify/fsnotify.v1: gopkg.in/fsnotify/fsnotify.v1@v1.6.0: invalid version: go.mod has non-....v1 module path "github.com/fsnotify/fsnotify" at revision v1.6.0
```

## Your Environment

AWS, EC2,  Amazon Linux 2023 (most recent AMI as of 10-May-2023), arm64

- Version used: golang 1.19,  oauth2-proxy v7.4.0 and v3.2.0

**Comment by chadmyers** [comment]
This is still relevant

**Comment by tuunit** [comment]
Hi @chadmyers,

please try:
`go install github.com/oauth2-proxy/oauth2-proxy/v7@latest`

**Comment by kvanzuijlen** [comment]
@chadmyers Can you confirm above suggestion by @tuunit worked for you?
