### ISSUE TITLE
Limit groups OAuth2-proxy Azure AD

### ISSUE THREAD

**Issue by bmgante** [oauth2-proxy/oauth2-proxy#2125]
Need some guidance on how to limit oauth2-proxy (v7.3.0) to specific azure ad groups (using with nginx):

This is my spec:

    spec:
      containers:
      - args:
        - --provider=oidc
        - --user-id-claim=oid
        - --cookie-expire=12h
        - --azure-tenant=xxxxx
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --oidc-issuer-url=https://login.microsoftonline.com/xxxxxx/v2.0 # replace with your tenant id
        - --allowed-group="Observability Admin"
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: xxx
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: xxx
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: xxx
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
In azure ad application i´ve added that group to Users and Groups as per snapshot below and also added the entry below in the app manifest, however keep getting 403 forbidden when trying to login. Can someone please provide some guidance on how to achieve the expected result?

"groupMembershipClaims": null, ---> "groupMembershipClaims": "ApplicationGroup, SecurityGroup"

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/27358817/89b57cbc-ef6d-4737-837e-9793bcc68dd9)

Many thanks

**Comment by bmgante** [comment]
@jobinjosem thanks for that. Indeed i just added Directory.Read.All and User.Read. I guess Directory.Read.All shoud be enough but it does not work.
I managed to control the access directly on the azure application itself, enabling the feature "assignment required".

**Comment by wangenbao1001** [comment]
This config worked for me, need api permissions openid and profile from Microsoft.Graph
--oidc-groups-claim=roles
--scope=openid profile
--allowed-group: {role}

**Comment by mishael-o** [comment]
@bmgante this is how I got it to work. I just modified your config, so it matches your use case as I use the configuration file on my side.

```
- args:
  - --provider=azure
  - --oidc_email_claim=upn
  - --oidc-issuer-url=https://login.microsoftonline.com/xxxxxx/v2.0 # replace with your tenant id
  - --allowed-group="<group_id>" # Azure group id for your group
  # your other config below....
 ```
