### ISSUE TITLE
Can this proxy be used on the client side instead of the service side?

### ISSUE THREAD

**Issue by benze** [oauth2-proxy/oauth2-proxy#2129]
I am looking for a solution which would allow me to inject Auth tokens in API calls to services at the client side for server-to-server authentication.

This would mean that my client app could be designed with non authenticated REST calls, and in my deployment, ensure that all calls route through an outgoing proxy.  The proxy would be configured with several different URL/ClientIds/secrets.  Outgoing API calls would me matched by the proxy against the configuration list, and the proxy would be responsible for doing ClientSecret auth calls to retrieve the necessary OAuth tokens and inject them into the outgoing API requests.

From the Client application perspective the entire Auth process would be transparent - only the Proxy would have the required secrets and inject the appropriate tokens in outgoing requests.

Can the OAuth2-Proxy be configured to be used in this manner, or that is a completely different use-case?

**Comment by tolleiv** [comment]
I think that's not the usecase for oauth2-proxy. What you're looking for is sth like https://mitmproxy.org/ or https://github.com/AdguardTeam/gomitmproxy.
