### ISSUE TITLE
Does oath2-proxy support Treafik when its running in 'kubernetes ingress' mode only.

### ISSUE THREAD

**Issue by steven-cherry** [oauth2-proxy/oauth2-proxy#2132]
This is just a general query, not a bug or feature request.

I'm using Traefik in 'kubernetes ingress' mode and not CDR mode. I've been unable to get it to work successfully. Details of the differences of the two Treafik modes are here,
[https://doc.traefik.io/traefik/providers/kubernetes-crd/#traefik-kubernetes](https://doc.traefik.io/traefik/providers/kubernetes-crd/#traefik-kubernetes)
All examples I could find of Traefik integration with oauth2-proxy are where it’s running in CRD mode, including the example on the oauth2-proxy site. I was only able to find one example of someone claiming to have it working with Traefik in kubernetes ingress mode here,
[https://doc.traefik.io/traefik/providers/kubernetes-crd/#traefik-kubernetes](https://g-c.dev/notes/oauth2proxy-azuread-traefik)
Does anyone know if oauth2-proxy  supports Treafik when running in 'kubernetes ingress' mode only?
Thanks

**Comment by JoelSpeed** [comment]
There are many issues through the project history about Traefik, I don't know if you've had a chance to read through them. I know users have had varying success making it work. Sadly I'm not a Traefik user so can't particularly comment other than, good luck!
