### ISSUE TITLE
Make `ReadHeaderTimeout` configurable

### ISSUE THREAD

**Issue by alsterg** [oauth2-proxy/oauth2-proxy#2146]
## Expected Behavior

We have a probe that probes a service protected behind Istio/Oauth2proxy/Keycloak every 1m. We noticed spontaneous 403s from Oauth2proxy. It turned out that there is a race condition between this timer expiring and the periodic request. The connections are keep-alive (with new connections that would not have been an issue). It would be nice to be able to change the value of `ReadHeaderTimeout` to workaround this issue, without changing the istio or the client.

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/6640287/78f3b36d-35e7-4d11-8c4e-666712065b84)

## Current Behavior

ReadHeaderTimeout=1m 

## Possible Solution

Make it configurable.

## Steps to Reproduce (for bugs)

1.  Open a long lived connection.
2.  Send a request over the same connection at exactly 1m interval.
3.  If left to run long enough, 403s should pop up.

## Your Environment

- Version used: oauth2-proxy:v7.4.0, but it should apply to latest too

**Comment by JoelSpeed** [comment]
If you have time to raise a PR to resolve this issue, it feels like it makes sense to make this configurable.
