### ISSUE TITLE
Update official docker container

### ISSUE THREAD

**Issue by Ziomal12** [oauth2-proxy/oauth2-proxy#2147]
Current docker image if over 6 months old and is  vulnerable to few CVE (according to [quary.io 14](https://quay.io/repository/oauth2-proxy/oauth2-proxy/manifest/sha256:f81637250eb3b5d902fba3c4ade3d3b1e34cc7f2350bc30402f1e62adfdf17aa?tab=vulnerabilities&fixable=true) ) that has been fixed in main repo. Also according to quary version bump of two packages should fix.
#1994 #2047

**Comment by sathieu** [comment]
dup of https://github.com/oauth2-proxy/oauth2-proxy/issues/2051 ?
