### ISSUE TITLE
Documentation does not describe how to pass lists as environment variables

### ISSUE THREAD

**Issue by FAUSheppy** [oauth2-proxy/oauth2-proxy#2151]
The docs say `--alowed-group` can bis specified  multiple times and therefore becomes `OAUTH2_PROXY_ALLOWED_GROUPS` as an environment variable.

This works when a single group is specified e.g.:

    OAUTH2_PROXY_ALLOWED_GROUPS:  group1

but not with two groups:

    OAUTH2_PROXY_ALLOWED_GROUPS:  group1 group2

I tried multiple variants with quotation marks and commas and nothing seems to be working.

## Expected Behavior

The documentation [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#environment-variables) should clearly state how to correctly pass a list via an environment variable.

## Your Environment
oauth2proxy 7.3.0 with Keycloak

**Comment by MarkDPierce** [comment]
If this is going into a helm file
```yaml
- name: OAUTH2_PROXY_ALLOWED_GROUPS
   value: Group1,GroupFoo,GroupBar
```
The docs seem fine.

**Comment by FAUSheppy** [comment]
Ok you are, I don't know what I was thinking. I'm sorry.
