### ISSUE TITLE
Can not specific other usernames rather than `default` when using Redis Cluster or Redis Sentinel as session storage

### ISSUE THREAD

**Issue by ming-zhang-SN** [oauth2-proxy/oauth2-proxy#2153]
Can not specific other usernames rather than `default` when using Redis Cluster or Redis Sentinel as session storage.

## Expected Behavior
Could be able to specific other usernames.

## Current Behavior
When using Redis Cluster or Redis Sentinel as session storage, we can not specific other usernames rather than `default` user.

## Possible Solution
When setting the client, I think we should pass the username to the opts too:
https://github.com/oauth2-proxy/oauth2-proxy/blob/d9416c3630d4b888441425691b57f01dab64bda8/pkg/sessions/redis/redis_store.go#L129-L134

Just like what we did for singleton Redis:
https://github.com/oauth2-proxy/oauth2-proxy/blob/d9416c3630d4b888441425691b57f01dab64bda8/pkg/sessions/redis/redis_store.go#L140C1-L158 

## Steps to Reproduce (for bugs)
1.  Prepare a Redis Cluster
2. Create username and password, the username should be something rather than `default`, eg. `main`.
3. Set up oauth2-proxy, eg:
```
    - name: OAUTH2_PROXY_SESSION_STORE_TYPE
       value: redis
    - name: OAUTH2_PROXY_REDIS_CONNECTION_URL
       value: redis://[username]:[password]@[redis-url]:[redis-port]/0
    - name: OAUTH2_PROXY_REDIS_USE_CLUSTER
       value: "true"
```

## Your Environment
oauth2-proxy on kubernetes

- Version used:
oauth2-proxy v7.3.0 (built with go1.17.10)

**Comment by ming-zhang-SN** [comment]
Could anyone help on this?

**Comment by tuunit** [comment]
@ming-zhang-SN as you already looked into the code. Feel free to try your best at raising a PR for this. Obviously, we can try to support as soon as the basis of code changes are done :)

**Comment by ming-zhang-SN** [comment]
Hi @tuunit 

Thank you for the comments, I just added a PR here:
https://github.com/oauth2-proxy/oauth2-proxy/pull/2198
Since it's the first time for me to contribute this project, please let me know if there is any mistake.

Thank you

**Comment by rossigee** [comment]
Always a PITA when github-actions prematurely closes a still-valid bug report :facepalm:
