### ISSUE TITLE
Azure Provider: "Groups assigned to the application" not honored, all groups belonging to the user returned

### ISSUE THREAD

**Issue by bosch-ch** [oauth2-proxy/oauth2-proxy#2154]
Selecting the "groups assigned to the application" option in the claim configuration of an App Registration should mean that the 

## Expected Behavior

If the App registration claim config is "Groups assigned to the application", the groups retrieved should ONLY be the groups assigned to the enterprise application which is associated to the App Registration. i.e. a subset of the groups assigned to the user.

## Current Behavior

If the user has too many group memberships, the OAuth token from Azure does not contain groups and they must be retrieved via another API call. Currently this returns ALL the groups the user is a member of, even if the "groups assigned to the application" option is selected in the App Registration claim configuration.

## Possible Solution

Suggest it could be something in the second API call for group memberships - or perhaps the wrong API call is used. I did look into the provider code but I am no familiar with the language and could not narrow down what request is being made. I also looked to see if I could increase logging to log those requests but was unsuccessful there as well.

## Steps to Reproduce (for bugs)

1. Setup a user in AD with a large number of groups ~200 for JWT. 
2. Setup an Azure App registration with "groups assigned to the application" selected. In the app registration manifest this is
     `"groupMembershipClaims": "ApplicationGroup",`
6. In the Enterprise App associated to the App registration, assign a subset of the user's groups to the application.
8. Sign in using, the Group-Member header should have ALL the groups of the user, not just the assigned subset

## Context

All the member groups are returned, the header is overly (too) large, and there is a risk the list is truncated if there are more than 200 groups, and a group membership is missed at the application

## Your Environment
- Version used: 7.4.0
- n.b. we are setting up OAuth2 Proxy with NGinX to route traffic per https://developer.okta.com/blog/2022/07/14/add-auth-to-any-app-with-oauth2-proxy#add-nginx-to-route-traffic
- config below, probably lots of unnecessary settings from playing around trying to get it to work.
```
docker run -d -p 4180:4180 -p 8080:8080 --name oauth2proxy bitnami/oauth2-proxy:latest \
    --http-address="0.0.0.0:4180" \
    --cookie-secure=true \
    --cookie-secret=***** \
    --cookie-samesite=lax \
    --cookie-refresh=0 \
    --cookie-expire=4h \
    --provider=azure \
    --client-id=**** \
    --client-secret=**** \
    --azure-tenant=***** \
    --oidc-issuer-url=https://login.microsoftonline.com/******/v2.0 \
    --email-domain='*' \
    --redirect-url=***** \
    --cookie-name=SESSION \
    --pass-user-headers \
    --set-xauthrequest \
    --skip-provider-button \
    --pass-access-token \
    --pass-authorization-header \
    --errors-to-info-log=true \
    --show-debug-on-error \
    --prefer-email-to-user \
    --azure-graph-group-field=displayName \
    --oidc-email-claim=sub \
    --standard-logging=true --auth-logging=true --request-logging=true
```

**Comment by aarnaud** [comment]
Same here, it's seem to be a regression, it wasn't the case before.

**Comment by hskiba** [comment]
The reason this doesn't work is that the current implementation of the Azure provider always queries the the Microsoft Graph API for all groups associated with the user as opposed to using groups provided in a token claim. If using less than 200 groups by limiting the groups to only those assigned to the application, you should be able to fall back to using regular OIDC, which will correctly put the groups in a groups claim (note this ~somewhat related to #1972). I tested this with a groups claim configured only to return groups assigned to the application and was successful in getting it to return only groups assigned to the application, but it would only return the group IDs--not the displayName/sAMAccountName values--despite configuring the claim to return that.

```bash
./oauth2-proxy \
   --oidc-issuer-url="https://login.microsoftonline.com/********/v2.0" \
   --cookie-secret "$(openssl rand -hex 16)" \
   --client-id "*****" \
   --client-secret '***********' \
   --email-domain "*" \
   --provider oidc \
   --redirect-url http://localhost:4180/oauth2/callback
```

<img width="573" alt="image" src="https://github.com/oauth2-proxy/oauth2-proxy/assets/16367391/6fe5afb5-ee68-47ce-967a-890d12cea081">

**Comment by hskiba** [comment]
It seems like it's not possible to get the group names in the groups claim (see https://github.com/MicrosoftDocs/azure-docs/issues/38625).

In any case, I think the Azure provider should be modified to always look at the groups claim as this will properly take into account the settings of the app registration. If there are more than 200 groups, the Azure provider should detect it and do something like [this](https://developer.hashicorp.com/vault/docs/auth/jwt/oidc-providers/azuread#optional-azure-specific-configuration) to retrieve all the intended groups for the claim. It would significantly clean up the permissions required.

**Comment by tuunit** [comment]
Hi @bosch-ch, @hskiba,

as you seem to be really knowledgeable regarding the proper handling and retrieving of groups in Azure and have access to an environment for testing this. We highly appreciate that you are working on PR #1972. Unfortunately, none of the maintainers currently have access or the time to setup an Azure account to test this. Therefore we have to heavily rely on community support.
