### ISSUE TITLE
AADSTS70011: The provided request must include a 'scope' input parameter

### ISSUE THREAD

**Issue by imranrazakhan** [oauth2-proxy/oauth2-proxy#2158]
I am encountering an error while trying to authenticate via AzureAD for the AKS Kubernetes dashboard.

`AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://aks-aad-server.azure.com/user.read https://graph.microsoft.com/openid https://graph.microsoft.com/.default is not valid. .default scope can't be combined with resource-specific scopes.`

## Current Behavior

The error mentioned above is being raised due to the default scope "https://graph.microsoft.com/.default" being added by oauth2-proxy. To further verify this, I enabled traces and observed that oauth2-proxy is making a call to the following URL by adding default scope. Please find the trace below.

```
........HTTP/1.1 302 Found
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Content-Type: text/html; charset=utf-8
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Location: https://login.microsoftonline.com/***/oauth2/v2.0/authorize?approval_prompt=force&client_id=***&redirect_uri=***&response_type=code&scope=https%3A%2F%2Faks-aad-server.azure.com%2Fuser.read+https%3A%2F%2Fgraph.microsoft.com%2Fopenid+https%3A%2F%2Fgraph.microsoft.com%2F.default&state=****%3A%2F
Set-Cookie: _oauth2_proxy_csrf= Path=/; Expires=Wed, 12 Jul 2023 18:57:31 GMT; HttpOnly; Secure
X-Accel-Expires: 0
Date: Wed, 12 Jul 2023 18:42:31 GMT
Content-Length: 486
```

## Possible Solution

if scope config has been provided then oauth2-proxy should not add this default scope. One more observation above trace is showing past date in  Expires.

## Your Environment

- Version used: 7.4.0

Following is my oauth2-proxy config

```
            - --http-address=0.0.0.0:4180
            - --https-address=0.0.0.0:4443
            - --metrics-address=0.0.0.0:44180
            - --show-debug-on-error=true
            - --silence-ping-logging=true
            - --provider=azure
            -  --oidc-issuer-url=https://login.microsoftonline.com/***/v2.0
            - --email-domain=*
            - --azure-tenant= ...
            - --client-id= ...
            - --client-secret= ...
            - --cookie-secret= ...
            - --scope=https://aks-aad-server.azure.com/user.read https://graph.microsoft.com/openid
            - --set-xauthrequest=true
            - --pass-access-token=true
            - --skip-provider-button=true
            - --set-authorization-header=true
            - --pass-authorization-header=true
            - --pass-user-headers=true
            - --pass-host-header=true
            - --skip-jwt-bearer-tokens=true
```

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/8535886/500dc6b0-ef5d-4869-b51d-9995a3584593)

**Comment by tuunit** [comment]
Hi @imranrazakhan, as none of the maintainers are Azure experts or have access to a proper account for testing. We heavily rely on community support. Therefore it would be amazing if you could find the time to raise a PR for this.

**Comment by mattintech** [comment]
Hi @tuunit, not an Azure exper, but maybe this will help. MS does offer some free developer sandbox access to a limited selection of the Office365 services (including Azure AD)  -  https://developer.microsoft.com/en-us/microsoft-365/dev-program

Gives 25 accounts - and includes access to "Azure Active Directory for building advanced identity and access management solutions" as well as a few other services.

**Comment by gittobey** [comment]
No active or final resolution yet
