### ISSUE TITLE
Example of a self contained setup to provide oauth2 for basic apps

### ISSUE THREAD

**Issue by rgarrigue** [oauth2-proxy/oauth2-proxy#2160]
Hi there

I'm running Kubernetes cluster with Contour as an ingress controller. They don't have a very mature solution yet for OAuth2. So I'm looking for a simple alternative to provide OAuth over apps that don't have any, like a static code documentation website.

A sidecar container could be a solution, like it's suggested in this bit of Prometheus community "stack" chart [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L781). I could embed that in my generic-service chart. But that would be quite some work to get it right.

So I was thinking, I could just have a nginx+oauth2-proxy container, or traefik+oauth2-proxy, I don't really care about the underlying tool, as long as I can drop a config file stating "this hostname => this kubernetes service, that hostname => that kubernetes service", etc. Looking for existing reference, I found https://nginxproxymanager.com/, but it's almost too much, as I don't see why I'ld care about a database for the very small usage I have.

Maybe someone out here got a configuration example or a prepackaged solution like nginxproxymanager.com to recommend ?

**Comment by tuunit** [comment]
The following essentially does what you are asking for:

https://levelup.gitconnected.com/efficiently-authenticate-your-kubernetes-applications-with-oauth2-proxy-part-2-bcab394e8787

https://github.com/veerashayyagari/oauth2-proxy-auth0/tree/main/k8s


You will not be able to use the chart obviously as you are using Contour instead Nginx as your ingress but you can add your own nginx container with a config similar to:

https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/nginx.conf

I hope that helps.
