### ISSUE TITLE
Azure provider: "unable to find userPrincipalName: type assertion to string failed"

### ISSUE THREAD

**Issue by adeturner** [oauth2-proxy/oauth2-proxy#2162]
## Expected Behavior

I've two accounts, a normal user account x.y@org.com, and an admin@org.onmicrosoft.com admin account. I get an error with the admin account

The normal account has settings for { "User principal name", "Email" } and works fine. 

The admin account has 
- "email" = nil
- "user principal name"= "admin@org.onmicrosoft.com"
- "other emails" = [ "forename.surname@org.com" ]

## Current Behavior

Login for the admin account gives

```
500 internal server error
unable to get email address from profile URL: empty email address: type assertion to string failed
```

Logs show

```
[2023/07/14 06:46:16] [azure.go:447] unable to find userPrincipalName: type assertion to string failed
[2023/07/14 06:46:16] [oauthproxy.go:830] Error creating session during OAuth2 callback: unable to get email address from profile URL: empty email address: type assertion to string failed
```

## Possible Solution

Unsure, the [code](https://github.com/oauth2-proxy/oauth2-proxy/blob/d9416c3630d4b888441425691b57f01dab64bda8/providers/azure.go#L412) looks ok. 

## Steps to Reproduce (for bugs)

Just login

## Context

Its a team site for the Cloud Engineering team, and we all use admin accounts and rarely use our own.

## Your Environment

- Version used:
Helm chart: 6.15.0
Image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0

**Comment by RegturH** [comment]
any solutions on this?

**Comment by adeturner** [comment]
The undesirable workaround was to set the primary email address for the admin user

**Comment by JoelSpeed** [comment]
Did you get anywhere debugging this? I don't have access to Azure to attempt to debug unfortunately

**Comment by adeturner** [comment]
Hey @JoelSpeed, sorry not tried after the workaround was found.

I can offer test data...?  with the assumption that I've got the url correct, [see code](https://github.com/oauth2-proxy/oauth2-proxy/blob/20244470a44ad1c841be5d0fc56e39aabb1016d2/providers/azure.go#L55)

Note that otherMails isn't present., and also there is nothing wrong with userPrincipalName..

```
$ TOKEN=$(az account get-access-token --resource-type ms-graph)
$ curl https://graph.microsoft.com/v1.0/me -H "Authorization: Bearer $TOKEN"

{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
	"businessPhones": [],
	"displayName": "forename lastname",
	"givenName": "forename",
	"jobTitle": null,
	"mail": "admin@org.onmicrosoft.com",
	"mobilePhone": null,
	"officeLocation": null,
	"preferredLanguage": null,
	"surname": "surname",
	"userPrincipalName": "admin@org.onmicrosoft.com",
	"id": "xxxxxxxx-8adb-4a4d-a0aa-xxxxxxxx84a4"
}
```

**Comment by nbarlowATI** [comment]
Hi, I have come across this issue as well.   For our application, some users are able to login to Azure and use the app with no problem, while other people (those who have nil "email"  in their profile) get this same 500 error with "unable to find userPrincipalName".

Digging a bit deeper, it seems that the code correctly looks for "email" in the profile JSON, then falls back on "otherMails", and if still nothing, looks for "userPrincipalName", all in the `getEmailFromProfileAPI` function.   However, the API endpoint called in this function is `https://graph.microsoft.com/oidc/userinfo`, whose response doesn't contain "userPrincipalName" as a field (only "sub", "name", "family_name", "given_name", "picture", "email").

It is surprising to me, looking at the code, that this is the API endpoint used in `getEmailFromProfileAPI`, as it does look in lines 55-59 of `azure.go` do seem to set the (at least "default") profileURL to `https://graph.microsoft.com/v1.0/me`, which _does_ have "userPrincipalName" (so I think is the correct one!).   But somehow this URL is not the one that is used.

I can try and investigate a bit more, but if anyone has tips on where the AzureProvider might be getting the `/oidc/userinfo` URL from, it could save me some time!
