### ISSUE TITLE
Allow insecure redirects

### ISSUE THREAD

**Issue by evozniak** [oauth2-proxy/oauth2-proxy#2165]
Same problem as https://github.com/oauth2-proxy/oauth2-proxy/issues/786

## Expected Behavior

Add a parameter to allow `unsafe` redirects.
https://foo.bar/redirect?param=https://customurl.com/path|12345

## Current Behavior

There are a lot of security concerns on this redirect, but there are legit use cases for it.
What do you think of adding a new option `--allow-insecure-redirects`

## Possible Solution

We can set the invalidRegex based on that flag, and we can add a big disclaimer in the documentation just like all insecure options.

Grabbing one solution from https://github.com/oauth2-proxy/oauth2-proxy/pull/790

[Validator.go L16](https://github.com/oauth2-proxy/oauth2-proxy/blob/d9416c3630d4b888441425691b57f01dab64bda8/pkg/app/redirect/validator.go#L16C24-L16C24)
E.g.
```
if !allowInsecureRedirects {
  invalidRedirectRegex = regexp.MustCompile(`[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
} else {
  invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
}
```

## Steps to Reproduce (for bugs)

1. open the application using the URL: [https://some-host.com/route/?param=https://sub-host.com/sub-route|12345](https://some-host.com/route/?param=https://sub-host.com/sub-route%7C12345)
2. Log in to the application;. I'm using: Core OS Dex.
3. After login, it will redirect using a empty URL `/`, without route and query.
4. I can see in the logs the message: `[2020/09/18 21:08:37] [logger.go:490] Rejecting invalid redirect "/route/?param=https://sub-host.com/sub-route|12345": not an absolute or relative URL.`

## Context

In some edge cases, we can't rewrite the URLs, so a configuration will make the application more flexible and customizable.

**Comment by andersonvcv** [comment]
+1

**Comment by axel7083** [comment]
+1

**Comment by JoelSpeed** [comment]
In general I'm not in favour of adding yet more insecure options, can you provide a handful or real world examples of cases where this is causing an issue? Particular applications that _need_ this option?
