### ISSUE TITLE
api-routes with nginx-ingress not working

### ISSUE THREAD

**Issue by michalpie** [oauth2-proxy/oauth2-proxy#2166]
api-routes setting with nginx-ingress is not working as expected. 
Here is my api_routes setting: 
    api_routes=".*echo"

I tried also other variants like ".*echo.*", "^(.*)echo"...

## Expected Behavior
If no valid Bearer token is passed, 401 error should be returned for routes matching the api-routes setting, otherwise 302.

## Current Behavior

The nginx-ingress returns 302 for all routes if no valid Bearer token is passed, even for those that match the api-routes setting:
```
< HTTP/2 302
< date: Wed, 19 Jul 2023 21:11:09 GMT
< content-type: text/html
< content-length: 138
< location: https://xxxxxxxxxxxxx/oauth2/start?rd=%2Fecho
<
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Below are the logs from oauth2-proxy.
You can see there that API route is correctly set and then 3 requests.
1.  /echo - with response status 401
2. /abc/assets... - with correct token and response status 202
3. /abc/assets... - with incorrect token and response status 401

Responses 1 and 3 return get 302 status in nginx-ingress. BTW in my ingress setting I added "target" request param to be able to see the target URL in the logs:
```
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.host }}/oauth2/auth?allowed_groups={{ .Values.security.allowedGroups }}&target=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.host }}/oauth2/start?rd=$escaped_request_uri"
```
```
[2023/07/19 20:58:34] [main.go:75] WARNING: You are using alpha configuration. The structure in this configuration file may change without notice. You MUST remove conflicting options from your existing configuration.
[2023/07/19 20:58:34] [provider.go:55] Performing OIDC Discovery...
[2023/07/19 20:58:35] [proxy.go:83] mapping path "/dev/null" => file system "/dev/null"
[2023/07/19 20:58:35] [oauthproxy.go:152] Skipping JWT tokens from configured OIDC issuer: "https://xxxxxx"
[2023/07/19 20:58:35] [oauthproxy.go:162] OAuthProxy configured for OpenID Connect Client ID: xxxxxxxx
[2023/07/19 20:58:35] [oauthproxy.go:168] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains:xxxx path:/ samesite: refresh:after 1m0s
[2023/07/19 20:58:35] [oauthproxy.go:496] API route - Path: .*echo
100.65.0.84:47748 - 0a70d6c12a73c62a2dc34c176e5228d5 - - [2023/07/19 20:58:44] xxxxxx GET - "/oauth2/auth?allowed_groups=xxxxx&target=%2Fecho" HTTP/1.1 "curl/8.0.1" 401 13 0.000
100.65.0.84:56312 - 4c74caa66d554966faaa0a36c362ea5a - - [2023/07/19 21:00:17] xxxxxx GET - "/oauth2/auth?allowed_groups=xxxxx&target=%2Fabc%2Fassets%2Fabc_icon_2.png" HTTP/1.1 "curl/8.0.1" 202 0 0.119
[2023/07/19 21:00:25] [jwt_session.go:51] Error retrieving session from token in Authorization header: invalid authorization header: "Bearer"
100.65.0.84:56312 - 93c4332977c1b823cfd94b5b0c41baee - - [2023/07/19 21:00:25] xxxxxx GET - "/oauth2/auth?allowed_groups=xxxxx&target=%2Fabc%2Fassets%2Fabc_icon_2.png" HTTP/1.1 "curl/8.0.1" 401 13 0.000
```

## Possible Solution

Maybe /auth endpoint is not supporting api routes setting?
If /auth is supporting it, does it check the path /auth?.., or the initial path which the user is trying to access (visible as "target" param that you can see in the logs)

Additionally, is nginx-ingress capable of supporting this feature? 

## Your Environment

nginx-ingress:
```
nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.host }}/oauth2/auth?allowed_groups={{ .Values.security.allowedGroups }}&target=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.host }}/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, authorization"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # pass Authorization header
      auth_request_set $token $upstream_http_authorization;
      add_header Authorization $token;

      # make refresh token work when cookie is split into several cookied
      auth_request_set $varname_set_by_you $upstream_cookie__oauth2_proxy_1;

      access_by_lua_block {
        if ngx.var.varname_set_by_you ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.varname_set_by_you .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
```

- Version used: 7.4.0

**Comment by michalpie** [comment]
I think I have found the solution to this problem based on the ingress configuration (https://github.com/oauth2-proxy/oauth2-proxy/issues/1522). 
For the API related routes a dedicated ingress resource needs to be configured which does not contain the nginx.ingress.kubernetes.io/auth-signin annotation.

**Comment by rburgst** [comment]
@michalpie how did you configure the ingress in detail? Our problem is that only the backend sends the 401 which triggers the auth flow. The frontend containers are only nginx which serve a static angular app.
