### ISSUE TITLE
When can we expect the PR #2025 to be Merged ? 

### ISSUE THREAD

**Issue by Mahesh-Gunda-Maersk** [oauth2-proxy/oauth2-proxy#2170]
[#2025](https://github.com/oauth2-proxy/oauth2-proxy/pull/2025) 

We have an air-gapped environment we are looking for Embedded Style Sheets.  
## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by Mahesh-Gunda-Maersk** [comment]
any update on this ?

**Comment by tuunit** [comment]
@Mahesh-Gunda-Maersk it has been merged. Release is pending.

**Comment by kvanzuijlen** [comment]
@JoelSpeed This issue can be closed
