### ISSUE TITLE
Missing Ability to configure Proxy for provider discovery

### ISSUE THREAD

**Issue by wahlflo** [oauth2-proxy/oauth2-proxy#2172]
## Expected Behavior

I expect to have the possibility to configure a proxy for requests made by the OAuth2 proxy to other entities.

## Current Behavior

HTTP_PROXY and HTTPS_PROXY environment variables are not picked up. Also, there is no other configuration possibility.

## Possible Solution

I will create a pull request 😄

**Comment by JoelSpeed** [comment]
PR was closed, has this issue been resolved?

**Comment by wahlflo** [comment]
yes kind of...  it is possible to configure it with HTTP_PROXY, ``HTTPS_PROXY`` and ``NO_PROXY``. They are picked up.
