### ISSUE TITLE
Code Dx -  detected security vulnerabilities.

### ISSUE THREAD

**Issue by adarshsingh2** [oauth2-proxy/oauth2-proxy#2173]
Code Dx Finding 533197: https://codedx.orl.eng.com/codedx/projects/170;branchId=152/findings/533197Cryptographic Issue detected by tool - AppScan Source

**Issue 1**

http.go

CWE 310 - Cryptographic Issues ([MITRE](https://cwe.mitre.org/data/definitions/310.html))

Code Dx Finding 533198: https://codedx.orl.eng.com/codedx/projects/170;branchId=152/findings/533198Cryptographic Issuedetected by tool - AppScan SourceAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/authentication/basic/htpasswd.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 44d14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\authentication\basic\htpasswd.go:5ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show moreAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/authentication/basic/htpasswd.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 47d14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\authentication\basic\htpasswd.go:15ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show moreAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/authentication/basic/htpasswd.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 4dd14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\authentication\basic\htpasswd.go:163ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show moreAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/authentication/basic/htpasswd.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 50d14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\authentication\basic\htpasswd.go:170ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show moreAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/authentication/basic/htpasswd.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 4ad14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\authentication\basic\htpasswd.go:112ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show more Policy ViolationsThis finding violates 1 policy:HV Security GatingSource CodeThe finding occurs in hv-css/oauth2-proxy/pkg/authentication/basic/htpasswd.goNo source available for file hv-css/oauth2-proxy/pkg/authentication/basic/htpasswd.go

**Issue 2**
utils.go

CWE 310 - Cryptographic Issues ([MITRE](https://cwe.mitre.org/data/definitions/310.html))

Code Dx Finding 533210: https://codedx.orl.eng.com/codedx/projects/170;branchId=152/findings/533210Cryptographic Issuedetected by tool - AppScan SourceAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/encryption/utils.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 53d14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\encryption\utils.go:6ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show moreAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/encryption/utils.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 56d14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\encryption\utils.go:78ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show moreAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/encryption/utils.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 5dd14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\encryption\utils.go:125ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show moreAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/encryption/utils.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 59d14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\encryption\utils.go:104ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show more Policy ViolationsThis finding violates 1 policy:HV Security GatingSource CodeThe finding occurs in hv-css/oauth2-proxy/pkg/encryption/utils.goNo source available for file hv-css/oauth2-proxy/pkg/encryption/utils.go

**issue 3**

cookie.go

CWE 310 - Cryptographic Issues ([MITRE](https://cwe.mitre.org/data/definitions/310.html))

Code Dx Finding 533212: https://codedx.orl.eng.com/codedx/projects/170;branchId=152/findings/533212Cryptographic Issuedetected by tool - AppScan SourceAppScan Source / Cryptography.InsecureAlgorithmDetection Method Static AnalysisLocation source/hv-css/oauth2-proxy/pkg/apis/options/options.goTool AppScan SourceTool Category N/ATool Code Cryptography.InsecureAlgorithmCWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]CVE(s) N/ASeverity HighASoC Application Name CitadelASoC Cause IDs WB_InsecureCryptoStorageASoC Issue ID 2cd14694-ddff-ed11-800f-14cb65725114ASoC Location source\oauth2-proxy\pkg\apis\options\options.go:137ASoC Report Title ${ProjectName} static scanASoC Security Risk IDs sensitiveInformationASoC Threat Classification catInformationLeakageDate Created May 30, 2023Date Updated May 30, 2023Discovery Method SASTTimestamp May 30, 2023Tool Rule Description show moreContextual Description show moreData Flow show more Policy ViolationsThis finding violates 1 policy:HV Security GatingSource CodeThe finding occurs in hv-css/oauth2-proxy/pkg/apis/options/options.goNo source available for file hv-css/oauth2-proxy/pkg/apis/options/options.go© 2023 Synopsys, Inc. All rights reserved worldwide.

**Issue 4**

htpasswd.go

CWE 310 - Cryptographic Issues ([MITRE](https://cwe.mitre.org/data/definitions/310.html))
AppScan Source / Cryptography.InsecureAlgorithm
Detection Method Static Analysis
Location source/hv-css/oauth2-proxy/pkg/upstream/http.go
Tool AppScan Source
Tool Category N/A
Tool Code Cryptography.InsecureAlgorithm
CWE 327 - Use of a Broken or Risky Cryptographic Algorithm [MITRE ]
CVE(s) N/A
Severity High
ASoC Application Name Citadel
ASoC Cause IDs WB_InsecureCryptoStorage
ASoC Issue ID 79d14694-ddff-ed11-800f-14cb65725114
ASoC Location source\oauth2-proxy\pkg\upstream\http.go:27
ASoC Report Title ${ProjectName} static scan
ASoC Security Risk IDs sensitiveInformation
ASoC Threat Classification catInformationLeakage
Date Created May 30, 2023
Date Updated May 30, 2023
Discovery Method SAST
Timestamp May 30, 2023
Tool Rule Description show more
Contextual Description show more
Data Flow show more
Policy Violations
This finding violates 1 policy:
HV Security Gating
Source Code
The finding occurs in hv-css/oauth2-proxy/pkg/upstream/http.go
No source available for file hv-css/oauth2-proxy/pkg/upstream/http.go
© 2023 Synopsys, Inc. All rights reserved worldwide.

**Comment by adarshsingh2** [comment]
Hi @JoelSpeed  & Team, Are these detections safe to ignore?

**Comment by tuunit** [comment]
The issues in your second comment can be dismissed. As we don't offer any input on the sign_in_page and error_page. I don't see how XSS should be possible. The error_page only displays information and the sign_in page is just a button to trigger a redirect without any inputs accepted by the user.

**Comment by tuunit** [comment]
Regarding your first comment.

**Issue 1:** When using basic authentication we allow the user entries in the `.htpasswd` file to be encrypted with bcrypt or sha1. In my opinion this can be dismissed as the user has the option to use one of the two which is in line with the apache2 standard.

**Issue 2:** Can be dismissed. Not valid. sha256 is still one of the most secure encryption algos. I don't understand why the library import would be flagged.


**Issue 3:** Cannot check this issue. It mentions the `cookie.go` at the top but only `options.go` in the analysis below without any lines specified.

**Issue 4:** We currently still use HMAC v1 for the signature to communicate with the upstream. Therefore the MD5 header is necessary. At some point we should migrate to HMAC v2 but that isn't a priority right now. This signature is used between oauth2-proxy and it's upstreams (only internally).
