### ISSUE TITLE
Azure AD Restrict Access by Groups

### ISSUE THREAD

**Issue by cnhsn** [oauth2-proxy/oauth2-proxy#2176]
Hello everyone,

I am using oauth2-proxy with Azure AD on NGINX. I am currently using it to authorize access to my applications defined as reverse proxies (https://example.com/application1) and the system is working fine. What I would like to add to my reverse proxy server blocks is to allow users to access reverse proxies by controlling the groups of users who authenticated on Azure AD.

## Expected Behavior

For example, I added someone with the email address "name.surname@example.com" to the "Application1" user group in Azure AD. When this person tries to access the "http://example.com/application1" application, I want them to be able to access it. However, since the same user is not included in the "Application2" user group in Azure AD, I want to prevent this user from accessing the "http://example.com/application2" application. But I want this application to be easily accessible to members of the "Application2" group under the same azure tenant. If another user belongs to both groups, I want them to have seamless access to both applications.

## Context

By restricting access in this way, I want to manage the access of many users with a single Azure application in an Azure tenant.

## Your Environment
- NGINX 1.20.1
- OAuth2-Proxy
- Azure AD

- Version used: v7.4.0

**Comment by jobinjosem1** [comment]
@cnhsn Please take a look at htis issue. Looks related?
https://github.com/oauth2-proxy/oauth2-proxy/issues/1703

**Comment by marianobilli** [comment]
I created a custom lua script that you can mount in your nginx and then via annotation of your application ingress you can allow people with certain groups 

check my repo https://github.com/marianobilli/auth-auth-nginx-lua-oauth2/tree/main

**Comment by tuunit** [comment]
Hi @cnhsn,

you will most probably have to setup multiple oauth2-proxies with different `allowed_groups`. A single OAuth2-Proxy instance is not meant to protect different endpoints with different restrictions. This can only be done with multiple instances or custom reverse-proxy / load balancer logic.

**Comment by marianobilli** [comment]
> > I created a custom lua script that you can mount in your nginx and then via annotation of your application ingress you can allow people with certain groups
> > check my repo https://github.com/marianobilli/auth-auth-nginx-lua-oauth2/tree/main
> 
> That looks great, but I am not using k8s for oauth2-proxy. Oauth2-proxy and NGINX running as a service on my linux machine. How can I implement your script to my current setup?
> 
> I'd be grateful if you could help me.

Sorry. Super busy but here kubernetes does not play any role. You can do the same for sure without kubernetes. Instead of ingress annotations you will configure directly your nginx.Conf

**Comment by marianobilli** [comment]
Still relevant

**Comment by lukeyeager** [comment]
This seems to be working for me. Am I missing something?
```toml
provider = "oidc"
client_id = "{id}"
client_secret = "{secret}"
oidc_issuer_url = "https://login.microsoftonline.com/{tenant}/v2.0"
scope = "openid email profile"
oidc_groups_claim = "roles"
email_domains = "*"
allowed_groups = [ "{group}" ]
```
With this, I don't need to request admin approval of `Group.Read.All` for my application. I can just setup "app roles" and assign individuals/groups to each role as desired.
