### ISSUE TITLE
Multiple dynamic oauth2 proxies in the same subdomain causes cookie confusion 

### ISSUE THREAD

**Issue by bit-herder** [oauth2-proxy/oauth2-proxy#2177]
We use mutliple oauth2 proxies behind the same subdomain so that we can auth agains different sets of teams in github.

site1.domain.com -> Oauth2 proxy 1
site2.domain.com -> Oauth2 proxy 2
site3.domain.com  -> Oauth2 proxy 3 

This works fine on first visit in an incognito window. I can visit and of the sites in a private window, go thru auth, and everything is fine. 

However, if within the same incognito session I visit say site1 and go thru auth and get connected, but then visit site 2, site 2 will error with a 500. If try again I get `This application has made an unusually high number of requests to access your account. Please reauthorize the application to continue.`

What I think im seeing here is that when I visit the 2nd site, the cookie for the 1st site is being used instead of the auth flow, but since its for a different oauth proxy, its getting in some sort of redirect loop and erroring. 

here are my configs 

proxy 1 

```
        email_domains = [ "*" ]
        provider = "github"
        github_org = "myorg"
        github_team = "some team"
        whitelist_domains = [ ".domain.com" ]
        cookie_domains = [ ".domain.com" ]
        redirect_url = "https://oauth.proxy1.com/oauth2/callback"
        cookie_secure = "false"
```

proxy 2

```
        email_domains = [ "*" ]
        provider = "github"
        github_org = "myorg"
        github_team = "team2"
        whitelist_domains = [ ".subdomain.domain.com" ]
        cookie_domains = [ ".subdomain.domain.com" ]
        redirect_url = "https://oauth.proxy2.com/oauth2/callback"
        cookie_secure = "false"
```

in the logs for the 2nd proxy I get 

```
[2023/08/08 19:42:05] [stored_session.go:77] Error loading cookied session: cookie signature not valid, removing session
[2023/08/08 19:42:05] [cookies.go:21] Warning: request host "oauth2-proxy-eaat.oauth2-proxy.svc.cluster.local" did not match any of the specific cookie domains of ".dev.k8s.domain.com"                                                                                                                             
[2023/08/08 19:42:05] [cookies.go:84] Warning: request host is "oauth2-proxy-eaat.oauth2-proxy.svc.cluster.local" but using configured cookie domain of ".dev.k8s.domain.com"
10.100.3.37:52288 - e9bf35e74d13a774436995d7fe47ead7 - - [2023/08/08 19:42:05] oauth2-proxy-eaat.oauth2-proxy.svc.cluster.local GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" 401 13 0.000                          10.100.1.168:37740 - a1b673114fea994a513b562a214c9395 - - [2023/08/08 19:42:05] oauth-eaat.dev.k8s.domain.comGET - "/oauth2/start?rd=https%3A%2F%2Fbill-test-app.dev.k8s.domain.com%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
[2023/08/08 19:42:06] [github.go:273] Found Github Organization:"Company" Team:"Team" (Name:"Company DS Web App Developers")                                                                                                                                                               [2023/08/08 19:42:06] [internal_util.go:69] 200 GET https://api.github.com/ {"current_user_url":"https://api.github.com/user","current_user_authorizations_html_url":"https://github.com/settings/connections/applications{/client_id}","authorizations_url":"https://api.github.com/authorizations","code_search_url":"http
10.100.1.168:37740 - af3af48e272453130f43d84681b4cead - user@gmail.com [2023/08/08 19:42:06] [AuthSuccess] Authenticated via OAuth2: Session{email:user@gmail.com user:bit-herder PreferredUsername: token:true created:2023-08-08 19:42:06.500013674 +0000 UTC m=+1310630.709611810 expires:2023-08-110.100.1.168:37740 - af3af48e272453130f43d84681b4cead - - [2023/08/08 19:42:06] oauth-eaat.dev.k8s.domain.com GET - "/oauth2/callback?code=b99975483597d4b3d086&state=0idzH_zlYJujG9AXxjgFGBFwjkoy0SeM8a7yW2N1qz0%3Ahttps%3A%2F%2Fbill-test-app.dev.k8s.domain.com%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X
[2023/08/08 19:42:07] [stored_session.go:77] Error loading cookied session: cookie signature not valid, removing session
```

I assume i could fix this by adding a subdomain so that these cookies would not get confused. Is it solvable in any other fashion? 

## Expected Behavior

Each site uses its configured proxy to log in 

## Current Behavior

500 errors

## Possible Solution

moving to a subdomain-per-oauth2 model

## Steps to Reproduce (for bugs)

see above

## Context

I am trying to accomplish using multiple oauth2 proxies under the same domain. 

## Your Environment

kubernetes 1.25 

- Version used:

7.2.1

**Comment by bit-herder** [comment]
I fixed this by setting both proxies cookie_domain and whitelist_domain to "subdomain.domain.com" 

The cookie is invalidated when accessing one proxy vs the other in the same browser session but I am no longer getting a redirect loop on successful auth. 

This stuff isnt easy to debug!

I dont know if this is the recommended method for using 2 proxies for the same subdomain but it does seem to work.

**Comment by hofq** [comment]
you should be able to change the cookie name on one instance and then be fine
