### ISSUE TITLE
404 returned by oauth2-proxy after successful login

### ISSUE THREAD

**Issue by marianobilli** [oauth2-proxy/oauth2-proxy#2178]
I am using oauth2-proxy in a kubernetes cluster in combination with nginx module ngx_http_auth_request_module, dex and azure.

Everything works fine, whoever when our users go directly to login page (oauth2-proxy) after successful login oauth2-proxy shows a 404 when going to the root path. 

Is this normal? should oauth2-proxy show some more friendly UI after login?

## Expected Behavior
Some other page showing a successful login maybe?

## Current Behavior

1- User goes to login page
2- oauth2-proxy goes to /oauth2/sign_in
3- oauth2-proxy redirects to dex
4- dex redirects to azure
5- user logs in in azure
6- azure makes the callback to dex
7- dex makes the callback to oauth2-proxy
8- oauth2-proxy shows 404

![Screenshot 2023-08-09 at 14 13 54](https://github.com/oauth2-proxy/oauth2-proxy/assets/14143004/0b74ff84-378d-4116-b934-a871f54dc2ed)

## Possible Solution

not sure.

## Steps to Reproduce (for bugs)

1.  deploy oauth2-proxy
2. configure an idp
3. from browser go to /oauth2-proxy/sign_in
4. login in IDP

## Context

While this is not a problem it is confusing for the users to see a 404 after login.

If the user goes to any other of our applications the browser has the cookie, and this will work authenticating users via the ngx_http_auth_request_module.

## Your Environment

Kubernetes: v1.24
DEX: 2.37.0
oauth2-proxy: 7.4.0

Diagram of the setup 

![Screenshot 2023-08-09 at 14 18 51](https://github.com/oauth2-proxy/oauth2-proxy/assets/14143004/257c1a05-fdbf-41f8-9741-4f4fa5767b48)

**Comment by afirth** [comment]
duplicate, https://github.com/oauth2-proxy/oauth2-proxy/issues/1724 and https://github.com/oauth2-proxy/oauth2-proxy/issues/1669, fixed but not released

**Comment by inmotiv** [comment]
Hi, I'm having the same issue, and no clue what the reason could be. I looked at the logfiles, but those don't mention a reason.
Do you have any updates or solution?
I have Oauth2-Proxy running in a Docker container, and the upstream is in another container. When I curl from the Oauth2-Proxy container to the upstream address, it gives an http 200 and the response that I expect.
Also when I try to access a path below /, there is a 404. Hope someone knowns the reason and a solution. Thx!

**Comment by tuunit** [comment]
Hi @marianobilli, @inmotiv,

no this behaviour is not as expected. The base path should allows redirect to the upstream application if you are signed in. Can you share some more details regarding your config? Maybe provide your oauth2-proxy config / flags and your nginx config?

**Comment by shairozan** [comment]
I'm seeing the same here, and figured i could pipe in. Using the newest release behind an NGINX proxy:

# Nginx Config

TLS is offloaded above in the main configuration, but here's the location mapping for oauth2

```
location /desktop/ {
	proxy_pass http://127.0.0.1:4180;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 1;
        proxy_send_timeout 30;
        proxy_read_timeout 30;
}
```

## Oauth2-proxy config

```shell
## OAuth2 Proxy Config File
## https://github.com/oauth2-proxy/oauth2-proxy

## <addr>:<port> to listen on for HTTP/HTTPS clients
 http_address = "127.0.0.1:4180"
# https_address = ":443"

## Are we running behind a reverse proxy? Will not accept headers like X-Real-Ip unless this is set.
reverse_proxy = true

## Provider Settings
provider = "oidc"
provider_display_name = "Provider"
oidc_issuer_url = "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_pool_id"

proxy_prefix="/desktop"

# Skipping hte Discovery and Populating manually
skip_oidc_discovery = false
scope="openid profile email aws.cognito.signin.user.admin"


## the OAuth Redirect URL.
# defaults to the "https://" + requested host header + "/oauth2/callback"
redirect_url = "https://4a5b92f8590745078b4166400f613aab.mydomain.com/desktop/callback"

## the http url(s) of the upstream endpoint. If multiple, routing is based on path
 upstreams = [
     "http://127.0.0.1:8080/guacamole"
 ]

## Logging configuration
#logging_filename = "oap.log"
logging_max_size = 100
logging_max_age = 7
logging_local_time = true
logging_compress = false
standard_logging = true
standard_logging_format = "[{{.Timestamp}}] [{{.File}}] {{.Message}}"
request_logging = true
request_logging_format = "{{.Client}} - {{.Username}} [{{.Timestamp}}] {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}"
auth_logging = true
auth_logging_format = "{{.Client}} - {{.Username}} [{{.Timestamp}}] [{{.Status}}] {{.Message}}"

 email_domains = [
     "*"
 ]

## The OAuth Client ID, Secret
client_id = "REDACTED"
client_secret = "REDACTED"

## Pass OAuth Access token to upstream via "X-Forwarded-Access-Token"
pass_access_token = false
ssl_insecure_skip_verify = false

cookie_name = "_oauth2_proxy"
cookie_secret = "REDACTED"
# cookie_domains = ""
cookie_expire = "168h"
# cookie_refresh = ""
cookie_secure = false
# cookie_httponly = true

redis_connection_url= "redis://localhost"
session_store_type = "redis"
```

It's worth nothing that we set the proxy_prefix in the config file. Everything works fine up to the point of login. When I try to access `.../desktop` as a URL (which is the location at with oauth2-proxy is hosted), I just get a 404. Even if I try to access "guacamole" via `.../desktop/guacamole` I get a 404. 

The below log line appears during startup
```
[2023/08/29 15:14:45] [proxy.go:89] mapping path "/guacamole" => upstream "http://127.0.0.1:8080/guacamole"
```

But trying to access `...proxy_prefix/guacamole` doesn't work. Always get a 404. Is there a way to view / force mappings beyond just as an array? IE map in the config "key" => "upstream"?

**Comment by marianobilli** [comment]
Still relevant

**Comment by marianobilli** [comment]
> @WestFarmer this issue is specifically for a 404 on the root page, while everything else works. If you are experiencing 404 on all pages, this is almost certainly a configuration issue. I guess that somehow your config is not being picked up, because you specify cookie_secure=true but log line says false. additionally perhaps allowed_roles needs to be in `[]`. Regardless, you might want to open a new issue or pursue other support forums if you can't get forwards.

Thanks for answering. I was about to say the same

**Comment by tuunit** [comment]
> I am facing same problem with version 7.5.1 my oauth2-proxy was exposed at https://api.itps.xxx.com/ and upstream is http://pus.itps-services.svc.cluster.local/pus
> 
> inside oauth2-proxy container I can access that endpoint:
> ...
> @tuunit

https://oauth2-proxy.github.io/oauth2-proxy/docs/next/configuration/overview#upstreams-configuration

If you instead provide http://127.0.0.1:8080/some/path/ then it will only be requests that start with /some/path/ which are forwarded to the upstream.

So in your case the proxing will only work if you request the subpaths: 

- https://api.itps.xxx.com/pus
- https://api.itps.xxx.com/pms

**Comment by marianobilli** [comment]
Still relevant

**Comment by curlup** [comment]
Stumbled upon the same but behind traefik (not nginx)

**Comment by acidbotmaker** [comment]
@curlup 
Yep, it's happening with me on traefik

**Comment by curlup** [comment]
see my solution here https://github.com/oauth2-proxy/oauth2-proxy/issues/1297#issuecomment-2004788570

**Comment by ferdinandmehlan** [comment]
Thank you. I had the same issue with a setup in traefik and docker. Auth redirect would work, but after that the proxy would just return 404 instead of anything upstream. And I already set `OAUTH2_PROXY_UPSTREAM=static://200`
but notice the missing `S`.

The documentation at:  https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/ specifies it without an s, but that doesn't work. The same missing `S` in the documentation applies to the variable `OAUTH2_PROXY_SKIP_AUTH_ROUTES`

**Comment by curlup** [comment]
> The documentation at: https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/ specifies it without an s, 

@ferdinandmehlan actually docs do say if you're using env vars you need an `S` for multi-valued options https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#environment-variables

**Comment by Momotoculteur** [comment]
@curlup you saved my week, thanks a lot
