### ISSUE TITLE
Access policies with Keycloak

### ISSUE THREAD

**Issue by daniel-pimenta-DME** [oauth2-proxy/oauth2-proxy#2179]
## Expected Behavior

I'm trying to use OAuth2 Proxy to add authentication and authorization to an unprotected Resource Server (Demo App).
My goal is to have the following flow:
(When authorized)
User -> Nginx -> OAuth2 proxy -> Keycloak -> Nginx -> Demo App
(When not authorized)
User -> Nginx -> OAuth2 proxy -> Keycloak -> Nginx -> 403 Forbidden

Ideally, access permissions would be only set on Keycloak Admin UI (clients -> oauth2-proxy -> authorization -> resources/policies/permissions).

As an example, I've created a /premium resource with role-based-permission meaning only users with a premium role should be allowed to access the /premium endpoint.

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/105205108/e9ca359a-4f50-4e72-88b3-5ca561835868)

But, with my current implementation, all users, with or without premium role, have access to the /premium endpoint.
Am I able to achieve what's described using Nginx and Oauth2-proxy? Am i missing something?
Thank you.

## Your Environment

Using a docker-compose file with Demo App (Spring boot app), Keycloak, OAuth2 Proxy, Nginx, Redis (storage for sessions), Postgres (Keycloak database)

- Version used:
quay.io/oauth2-proxy/oauth2-proxy:v7.4.0

**Comment by tuunit** [comment]
Hi @daniel-pimenta-DME,

unfortunately, the provider does not support full keycloak integration. Meaning the resources you setup are not considered or even read from the keycloak api. The provider only enables you to restrict on the basis of user assigned roles:

Documentation: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#keycloak-oidc-auth-provider
