### ISSUE TITLE
Keycloak 12.0.4 with Oauth2-proxy to Authenticate NGINX requests

### ISSUE THREAD

**Issue by cnhsn** [oauth2-proxy/oauth2-proxy#2185]
Hello everyone,

I use a reverse proxy to access some of my applications with NGINX. I currently protect my reverse proxies with Oauth2-proxy and authorize accessing users with Azure AD. Instead of using Azure AD directly with Oauth2-proxy, I decided to use Keycloak as IdP. I installed Keycloak and it is working fine now. I also added Azure AD as a provider and it works fine. What I want to do now is, I want to use Keycloak as a provider in the oauth2-proxy module. I would also like to define allowed_groups in the oauth2-proxy config file and define a different access group for each reverse proxy and make group-based access management. How can I do that? I'd really appreciate your help.

## Expected Behavior

- Use Keycloak as provider on Oauth2-proxy
- Group based access for each proxy

## Current Behavior

Azure AD integrated to keycloak and running well.

## Your Environment

- Keycloak v12.0.4
- Version used: v7.4.0

**Comment by tuunit** [comment]
Hi @cnhsn,

please have a look at the documentation regarding the Keycloak OIDC provider:
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#keycloak-oidc-auth-provider

You can provide keycloak roles to the provider you want to allow the acces for. Which will then be set as the allowed groups internally. The provider does not support reading / using "keycloak groups / user collections" as of now.
