### ISSUE TITLE
Calculate cookie-expire and cookie-refresh from actual OIDC Access-Token and Refresh-Token

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/oauth2-proxy#2186]
I wonder if it's necessary to set those values at all and if they have to be adjusted every time the OAuth2-Provider changes the expire times of the access and refresh tokens.

Shouldn't it be possible to calculate the values like:

* cooke-expire := accessToken.lifetime
* cookie-refresh := refreshToken.lifetime - 1m

## Expected Behavior

Cookies are synced with Token lifetimes (if not by default then at least as an option)

Or at least a better documentation :-)

## Current Behavior

Cookie lifetimes have to be carefully adjusted to OAuth2 client's token lifetimes?

## Possible Solution

see above

## Steps to Reproduce (for bugs)

-

## Context

OAuth2-Proxy with Keycloak

## Your Environment

-

- Version used: 7.4.0

**Comment by JoelSpeed** [comment]
The issue with this is that some people agree with you, while others do not. They want the tokens to exist for a specific time or to never expire, or to expire as part of the browser session. So we have to make this configurable. The easiest way to do that is just to get the user to set the values to match their IDP, as we do today. An auto option could be considered though
