### ISSUE TITLE
Failing to validate JWT access token

### ISSUE THREAD

**Issue by freedrikp** [oauth2-proxy/oauth2-proxy#2190]
## Expected Behavior

Hi, we are trying to use Oauth2-proxy in our Kubernetes cluster together with ingress-nginx to provide authentication/authorization for our services. We would like to be able to do this for both human browser-based interaction but also for machine-to-machine interaction for REST APIs in the same services.

Thus, we would like pass a JWT token in the Authorization header and be let through to the service by the proxy.

We are using the OIDC provider against an app in Azure.

## Current Behavior

At the moment we have got the human browser-based flow working correctly. And by setting the following configuration options we have got some tokens to go through correctly. Specifically using the ID token as can be retrieved from the /oauth2/auth endpoint after signing in through the browser.

```
pass_access_token=true
pass_authorization_header=true
set_xauthrequest=true
set_authorization_header = true
pass_user_headers = true
skip_jwt_bearer_tokens = true
```

However, the problem we face is that we can't acquire the ID token programmatically whereas we can generate an access token. Also reading about OIDC it seems preferable to use the access token for authentication/authorization in APIs.

How can we get Oauth2-proxy to validate the access token?

## Possible Solution

The error we get from Oauth2-proxy when passing an access token in the Authorization header is:

```
[2023/08/21 06:56:53] [jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, failed to verify token: failed to verify signature: failed to verify id token signature]
```

Has anyone managed to get Oauth2-proxy to validate access tokens as opposed to just ID tokens before?

**Comment by freedrikp** [comment]
We've managed to sort out our problem.

It turns out that the access token you can get from the /auth endpoint in oauth2-proxy does not have a valid signature. Whereas the ID token do have a valid signature.

However, if we generate an access from Azure directly it goes through validation just fine.

**Comment by JoelSpeed** [comment]
> It turns out that the access token you can get from the /auth endpoint in oauth2-proxy does not have a valid signature. Whereas the ID token do have a valid signature.

I believe if you search the issues, others have found this same issue before. I never worked out why this was and I'm not an Azure user at present so am unlikely to be able to help diagnose the issue either

**Comment by freedrikp** [comment]
@rolandkool Hi, so the problem we had was how the tokens were generated as per my comment above.

If even the ID token that you can get from oauth2-proxy's /auth endpoint isn't valid then it smells to me like a configuration issue with ouath2-proxy in general.
