### ISSUE TITLE
custom  claims for injectionResponseHeaders

### ISSUE THREAD

**Issue by redboxstudio** [oauth2-proxy/oauth2-proxy#2193]
>Just to let you all know, the current plan is to get https://github.com/oauth2-proxy/oauth2-proxy/pull/826 merged (reviews welcomed) and then create a new PR to add --alpha-config which allows users to use the new structured configuration for headers and upstreams that we have been working on recently. Hopefully we can get this merged in the next month or two.
>
>Then it will be a case of a user setting up a file with their header values like:
>
> ```
> injectRequestHeaders:
> - name: "WHATEVER_YOU_WANT_FOR_STATIC_VALUE"
>   values:
>   - value: <Some B64 encoded string>
> - name: "SOME_VALUE_FROM_SESSION"
>   values:
>   - claim: "email"
> ```
Hi, I didn't find a usage description in thread 903. I built a master branch but the custom claim functionality doesn't work. or does this only work for injectRequestHeaders
 i did so
injectionResponseHeaders:
- name: MY_HEADER
  values:
  - value: MY_CLAIM

Or maybe my mistake is that it is necessary to specify the claim value in base64 ?

_Originally posted by @redboxstudio in https://github.com/oauth2-proxy/oauth2-proxy/issues/631#issuecomment-1691079847_

**Comment by JoelSpeed** [comment]
Custom claims isn't implemented, currently it only works for claims that are supported in the session already. There's a switch case somewhere within the code that shows which are supported

I also left this comment on the other thread before I found it here, lets just continue on the other thread
