### ISSUE TITLE
Traefik v2 configuration in documentation contains deprecated headers

### ISSUE THREAD

**Issue by maxromanovsky** [oauth2-proxy/oauth2-proxy#2195]
Traefik v2 [configuration in documentation](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#configuring-for-use-with-the-traefik-v2-forwardauth-middleware) contains [headers that have been deprecated](https://doc.traefik.io/traefik/middlewares/http/headers/#general) at least as of Traefik v2.10:
- `sslRedirect`
- `sslHost`

## Expected Behavior

Documentation contains configuration based on non-deprecated Traefik behaviour: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#configuring-for-use-with-the-traefik-v2-forwardauth-middleware

**Comment by tuunit** [comment]
@maxromanovsky please feel free to raise a PR with updated documentation:
https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/docs/configuration/overview.md
