### ISSUE TITLE
Compatibility with GCP Cloud Run to Cloud Run

### ISSUE THREAD

**Issue by AurelienBegou** [oauth2-proxy/oauth2-proxy#2199]
My goal is to use oath-proxy in a server less environment on Google Cloud Platform (Cloud Run).

The idea is to deploy a Cloud Run instance with oauth2-proxy and protect another instance of Cloud Run.

## Expected Behavior

oauth2-proxy retrieve Oauth2 token to call the other Cloud Run instance.

## Current Behavior

No token is retrieved and propagated so it doesn't work

## Possible Solution

When on GCP, retrieve an Oauth2 token and call the other Cloud Run instance.

## Steps to Reproduce (for bugs)

1.  Deploy oauth2-proxy on Cloud Run
2.  Deploy a sample app on Cloud Run
3.  Configure oauth2-proxy to forward request to "app"
4.  Try to open oauth2-proxy url

## Context

We are trying to keep the "proxy auth" pattern on server less environment (cloud run) without using provider service.

**Comment by tuunit** [comment]
@AurelienBegou did you make any progress on this? If please provide a bit more details about the oauth2-proxy version and the configuration used.

**Comment by AurelienBegou** [comment]
> @AurelienBegou did you make any progress on this? If please provide a bit more details about the oauth2-proxy version and the configuration used.

I didn't find a solution so I switched using envoy with Oauth2, GCP auth and JWT filter. more complex configuration but it work. I will switch back on oauth2-proxy once Google will release in GA the Cloud Run Sidecar

**Comment by tuunit** [comment]
Happy to here that you found a solution. Even if it is somewhat of a complex workaround. Do you still want to keep this issue open?

**Comment by AurelienBegou** [comment]
I think we can close it. oauth2-proxy will be automatically compatible in 2024 once it's GA. here the link for documentation. https://cloud.google.com/blog/products/serverless/cloud-run-now-supports-multi-container-deployments

Thanks for your feedbacks
