### ISSUE TITLE
How to config apisix with oauth2-proxy

### ISSUE THREAD

**Issue by xtha** [oauth2-proxy/oauth2-proxy#2202]
I'm using apisix as ingress controller installed by helm chart, but have trouble to know how exactly config oauth2-proxy  and apisix, can anyone help ?

**Comment by kvanzuijlen** [comment]
Hi @xtha,

Although I don't use apisix myself and have no experience with it, something like this might work: https://apisix.apache.org/docs/apisix/plugins/forward-auth/

I myself use NGINX as described in this blogpost (there's others): https://www.callumpember.com/Kubernetes-A-Single-OAuth2-Proxy-For-Multiple-Ingresses/.

The forward-auth plugin looks the most similar to this solution I could find

**Comment by xtha** [comment]
thank you for responding, i checked the documents before, but still feel confused with the options "auth-url and auth-signin" , not sure where to set them correctly for the forward-auth plugin, since it seems that only the "uri" is available for setting url

> Hi @xtha,
> 
> Although I don't use apisix myself and have no experience with it, something like this might work: https://apisix.apache.org/docs/apisix/plugins/forward-auth/
> 
> I myself use NGINX as described in this blogpost (there's others): https://www.callumpember.com/Kubernetes-A-Single-OAuth2-Proxy-For-Multiple-Ingresses/.
> 
> The forward-auth plugin looks the most similar to this solution I could find

**Comment by k-e-r-n-e-l-p-a-n-i-c** [comment]
Hello @xtha , I am stuck with a similar situation. Were you able to figure out where to set both the settings in forward-auth plugin? Thanks.

**Comment by xtha** [comment]
Haven’t found out the right way to set it up
