### ISSUE TITLE
CSRF Issues with Keycloak in Kubernetes

### ISSUE THREAD

**Issue by 98jan** [oauth2-proxy/oauth2-proxy#2210]
## Expected Behavior

After logging in with Keycloak Credentials the user should be successfully forwarded to the application. (redirect url)

## Current Behavior

After successfully logging in I am redirected back to the application and a redirect starts again which resolves in to many redirects and finaly in a `AuthFailure Invalid authentication via OAuth2: unable to obtain CSRF cookie` (oauth2-proxy log entry).

## Steps to Reproduce (for bugs)

1. After configuring Keycloak as defined here (using Keycloak in version 21.1.1): https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#keycloak-oidc-auth-provider. 

2. Install oauth2-proxy as a helm chart with flux
The following helm chart was used: https://oauth2-proxy.github.io/manifests in version 6.16.1

There I configured following entries:
```
- OAUTH2_PROXY_PROVIDER (tried oidc and keycloak-oidc both result in same error)
- OAUTH2_PROXY_OIDC_ISSUER_URL
- OAUTH2_PROXY_WHITELIST_DOMAINS
- OAUTH2_PROXY_COOKIE_DOMAIN
- OAUTH2_PROXY_SCOPE
- OAUTH2_PROXY_REVERSE_PROXY: true (nginx is used)
- OAUTH2_PROXY_COOKIE_SECURE: true (all routes are certified with lets-encrypt)
- OAUTH2_PROXY_EMAIL_DOMAINS: "*"
- OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: true
-  OAUTH2_PROXY_PASS_ACCESS_TOKEN: true
-  OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: true
- OAUTH2_PROXY_SET_XAUTHREQUEST: true
- OAUTH2_PROXY_CLIENT_ID
- OAUTH2_PROXY_CLIENT_SECRET
```

3. Configure ingress annotations:
```
    nginx.ingress.kubernetes.io/auth-signin: https://auth.<domain>/oauth2/start?rd=https://<application>.<domain>
    nginx.ingress.kubernetes.io/auth-url: https://auth.<domain>/oauth2/auth
```

`<domain>` - for application, oauth2-proxy and keycloak same main domain is used and every service has it's own subdomain.
`<application>` - the redirect url to redirect afterwards to the application on successfull login

## Context

I am trying to secure all applications with oauth2-proxy instead of basic auth, to benefit from SSO.

## Your Environment

- Kubernetes 1.28.0
- Flux: v2.0.1
- nginx-ingress: 4.6.1 (helm chart version) and 1.7.1 (application version)
- Keycloak: 21.1.1

**Comment by JoelSpeed** [comment]
What is the value of your cookie domain? It should be set to `.<domain>`. The many redirects sounds likely to be a cookie configuration issue

**Comment by 98jan** [comment]
Whitelist-domain and cookie-domain is set to `.<domain>` and I can see the CSRF Token in the F12 Menu, where the domain of oauth2-proxy is shown as domain of the token `auth.<domain>`

**Comment by 98jan** [comment]
with some changes I am getting now following messages in the oauth2-proxy log output:
```
[2023/09/03 19:53:13] [cookies.go:21] Warning: request host "auth.<domain>" did not match any of the specific cookie domains of "[\".<domain>\"]"
[2023/09/03 19:53:13] [cookies.go:84] Warning: request host is "auth.<domain>" but using configured cookie domain of "[\".<domain>\"]"
2023/09/03 19:53:13 net/http: invalid Cookie.Domain "[\".<domain>\"]"; dropping domain attribute
```

I have set following arguments:
OAUTH2_PROXY_COOKIE_DOMAINS: `.<domain>`
OAUTH2_PROXY_WHITELIST_DOMAINS: `.<domain>`

**Comment by 98jan** [comment]
Could fix the issue, removed the "." for the COOKIE_DOMAINS and now working as expected, weird behaviour but happy that it is working now for me.

**Comment by 98jan** [comment]
Alright so inspected it a bit further, so the "." wasn't really the issue, the issue was more or less to not use oauth2-proxy in combination with a configured basic auth, this can also cause this issue and was also the real issue for me.

Could be helpful if anyone get's the same issue.

**Comment by tuunit** [comment]
Hi @98jan to better understand your issue. You had an additional basic auth in front or behind oauth2-proxy?
