### ISSUE TITLE
Multiple hostnames

### ISSUE THREAD

**Issue by Renizmy** [oauth2-proxy/oauth2-proxy#2212]
Hello,

I'm trying to apply rules based on the input hostname, for example:

- grafana.example.com ---> restrict access to all authenticated users
- portainer.example.com ---> restrict access to admin group users

I found the upstreams but they apply to URIs, not hosts. 
Does anyone have any ideas other than deploying an instance per input hostname ?

Best regards

**Comment by hevans-dglcom** [comment]
@Renizmy are you using the /auth endpoint with a reverse proxy?

**Comment by Renizmy** [comment]
Not really, As picture is worth a thousand words. This is the idea :

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/62422302/2a83a00d-2648-4a80-b44c-dd9528af878b)

What do you mean with the /auth endpoint ?

**Comment by hevans-dglcom** [comment]
So you would have to change the architecture a little bit, but what you are looking to do is possible using nginx with a subrequest architecture.

https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints/#auth

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/84313465/b21d8a8e-2928-4a8a-b831-213a50b21a0c)

**Comment by hevans-dglcom** [comment]
Here is an example config:

https://medium.com/devops-dudes/using-oauth2-proxy-with-nginx-subdomains-e453617713a

to restrict access for the portainer service, you would do something like this in the portainer server block

```
auth_request /oauth2/auth?allowed_groups=gid1,gid2,gid3;
```

**Comment by Renizmy** [comment]
Wow, thank you for your answer
I test it and I come back to you

**Comment by ymuichiro** [comment]
@hevans-dglcom 
I have tried the method you described, but I was wondering if you could tell me about it.
I have prepared the following oauth2-proxy + Auth0 verification environment.

docker-compose.yml
```docker-compose.yml
version: "3"
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  server:
    build:
      context: ./node
      dockerfile: ./Dockerfile
  auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.0
    ports:
      - 4180:4180
    environment:
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_CLIENT_ID: 01234567890123456789012345678901
      OAUTH2_PROXY_CLIENT_SECRET: 01234567890123456789012345678901
      OAUTH2_PROXY_REDIRECT_URL: http://localhost/oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://01234567890123456789012345678901.us.auth0.com/
      OAUTH2_PROXY_COOKIE_SECRET: 01234567890123456789012345678901
      OAUTH2_PROXY_COOKIE_SECURE: false
      OAUTH2_PROXY_COOKIE_NAME: "demo"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_UPSTREAMS: http://server:3001/
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: true
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: true
      OAUTH2_PROXY_SET_XAUTHREQUEST: true
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true
```

default.conf
```default.conf
server {
  listen 80;
  server_name localhost;
  error_log /var/log/nginx/error_log debug;

  location /oauth2/ {
    proxy_pass       http://auth:4180;
    proxy_set_header Host                    $host;
    proxy_set_header X-Real-IP               $remote_addr;
    proxy_set_header X-Scheme                $scheme;
    # proxy_set_header X-Auth-Request-Redirect $request_uri;
    # or, if you are handling multiple domains:
    proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
  }
  location = /oauth2/auth {
    proxy_pass       http://auth:4180;
    proxy_set_header Host             $host;
    proxy_set_header X-Real-IP        $remote_addr;
    proxy_set_header X-Scheme         $scheme;
    # nginx auth_request includes headers but not body
    proxy_set_header Content-Length   "";
    proxy_pass_request_body           off;
  }

  location / {
    auth_request /oauth2/auth;
    error_page 401 = /oauth2/sign_in?rd=https://$host$request_uri;
    auth_request_set $user   $upstream_http_x_auth_request_user;
    auth_request_set $email  $upstream_http_x_auth_request_email;
    proxy_set_header X-User  $user;
    proxy_set_header X-Email $email;
    auth_request_set $token  $upstream_http_x_auth_request_access_token;
    proxy_set_header X-Access-Token $token;
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $auth_cookie;
    auth_request_set $auth_cookie_name_upstream_1 $upstream_cookie_auth_cookie_name_1;
    if ($auth_cookie ~* "(; .*)") {
        set $auth_cookie_name_0 $auth_cookie;
        set $auth_cookie_name_1 "auth_cookie_name_1=$auth_cookie_name_upstream_1$1";
    }
    if ($auth_cookie_name_upstream_1) {
        add_header Set-Cookie $auth_cookie_name_0;
        add_header Set-Cookie $auth_cookie_name_1;
    }
    proxy_pass http://server:3001;
  }
}
```

The expected behavior is that the application at the destination of `proxy_pass` would like to receive the JWT in bearer token format as shown below. This is because OAuth2-proxy alone can receive JWT in bearer token format, but when it goes through nginx, it will receive JWT in basic format.

expect
```
header: {
  Authorization: bearer **********
}
```

actual 
```
header: {
  Authorization: basic **********
}
```

I know that the JWT is stored in x-access-token instead, but is there any way to configure it to work as expected? (The reason I want to do this is because I want to authenticate the user in the same way as Easy Auth, etc. used on Azure.)

**Comment by ymuichiro** [comment]
Sorry. I should have used a different header. Self solved.
