### ISSUE TITLE
Version 7.5.0 not available at quay.io

### ISSUE THREAD

**Issue by falzm** [oauth2-proxy/oauth2-proxy#2214]
## Expected Behavior

Pulling container image `quay.io/oauth2-proxy/oauth2-proxy:v7.5.0` succeeds.

## Current Behavior

Version 7.5.0 is not deployed on the container image registry Quay: https://quay.io/repository/oauth2-proxy/oauth2-proxy

## Possible Solution

Deploy the version 7.5.0 on Quay

## Steps to Reproduce (for bugs)

1. Reference `image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.0` in a Kubernetes Pod spec
2. Executing the Pod deployment results in `imagePullBackoff` error

**Comment by JoelSpeed** [comment]
Sorry, hit the ran the push command for the images and moved onto something else, didn't check back to check it had completed. Seems I'd overwritten my Quay push credentials. Images should be uploaded now.
