### ISSUE TITLE
Unable to find a valid CSRF token. Version 7.4.0 and 7.5.0

### ISSUE THREAD

**Issue by carre140** [oauth2-proxy/oauth2-proxy#2216]
## Expected Behavior

Trying to generate a token refresh
Looking for a 200 response after a successful login 

## Current Behavior

Getting a 403 response: "http: named cookie not present" and in Oauth2-Proxy logs: AuthFailure Invalid authentication via OAuth2: unable to obtain CSRF cookie

## Possible Solution

Have read the manual, logs, looked online, tried secure / insecure and all the options in oauth2-proxy, nothing seems to fix it.
Have used ticket #1937 to try to solve this but not succeed

## Steps to Reproduce (for bugs)

happens every time i try (with below configurations / run command).
Sending curl request to get a token refresh:
curl https://login.microsoftonline.com/xxxxxx-xxx-xxxx-xxxx/oauth2/v2.0/authorize?client_id=xxx-xxx--xxx-xxx-xxx&response_type=code&redirect_uri=https%3A%2F%mlflow.test.devops-fwk.net/oauth2/callback&scope=xxx-xxx-xxx%2F.default+offline_access+openid+profile&state=SRtmcFZesJQnkzYT&code_challenge=oiWYvPd2557KDubuNx4hbY7o2x30U9aXD5mLE1hxURE&code_challenge_method=S256&nonce=b50a6ee9f15bb449ff826e7e06323b77c0408690d58578aec66ac01399629306&client_info=1

## Your Environment

Kubernetes v1.22.8

- Version used:
Oauth2-Proxy Version used: v7.4.0 (and try again with V7.5.0)

Oauth2 Proxy configuration from values.yaml:
config:
  clientID: "xxxx-xxxx-xxxx-xxx-xxxxxxx"
  clientSecret: "xxxx~xxxxx~xxxxxxxxxxxxxxxxxxxxxx"
  cookieSecret: "xxxxxx_xxxxxxxxxxxxxxxxxx-xxxxxx="
  cookieName: ""
  configFile: |-
    provider = "azure"
    azure_tenant = "xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx"
    email_domains = [ "*" ]
    http_address = "0.0.0.0:4180"
    oidc_issuer_url = "https://login.microsoftonline.com/xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx/v2.0"
    extra_jwt_issuers = "https://login.microsoftonline.com/xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx/v2.0=xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx"
    whitelist_domains = "*.devops-fwk.net"
    cookie_domains = ".devops-fwk.net"
    cookie_secure = false
    cookie_httponly = true
    skip_provider_button = true
    set_xauthrequest = true
    ssl_insecure_skip_verify = false
    redirect_url = "https://mlflow.test.devops-fwk.net/oauth2/callback"
    login_url = "https://login.microsoftonline.com/xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx/v2.0/authorize"
    redeem_url = "https://login.microsoftonline.com/xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx/oauth2/v2.0/token"
    cookie_csrf_per_request = true
    cookie_csrf_expire = "5m"

ingress:
  enabled: true
  className: nginx
  path: /oauth2
  pathType: Prefix
  hosts:
    - mlflow.test.devops-fwk.net
  labels: {}
  tls:
   - secretName: mlflow-secret
     hosts:
      - mlflow.test.devops-fwk.net

resources: {}

sessionStorage:
  type: redis

redis:
  enabled: true

**Comment by sudmis** [comment]
I am also facing similar issue. is there a workaround it?

**Comment by miguelborges99** [comment]
I found strange in your configuration, the fact that you have a cookie named "". 

config:
clientID: "xxxx-xxxx-xxxx-xxx-xxxxxxx"
clientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
cookieSecret: "xxxxxx_xxxxxxxxxxxxxxxxxx-xxxxxx="
cookieName: ""

Maybe this is the reason, why cookie cannot be found.
See documentation in https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview

**Comment by kvanzuijlen** [comment]
Duplicate of #1937

**Comment by miguelborges99** [comment]
> Hello Thanks for answering. cookieName is set to "" in values.yaml because it will be set to default value "_oauth2_proxy" To be sure to set it, I set it to "my_secret_cookie_name" In browser, I can see the cookie ![image](https://user-images.githubusercontent.com/74602903/268217692-48add56a-468d-4390-b723-a639ca108019.png) But in oauth2 proxy logs, still can see error message "AuthFailure Invalid authentication via OAuth2: unable to obtain CSRF cookie" ![image](https://user-images.githubusercontent.com/74602903/268218296-bd215332-e1b6-4fed-bdad-4ba40dddee8d.png)

In the image, I see that there is no CSRF cookie, so the error must occur. 
What you need to understand is where the CSRF cookie was created, please check in previous requests. Was the CSRF cookie created in the same domain, or it was created in a different domain? It could be your cookie configuration.

I know that if you have samesite=Strict then you face an issue like [1663](https://github.com/oauth2-proxy/oauth2-proxy/issues/1663)
