### ISSUE TITLE
Inconsistent arm tagging on v7.5.0 release

### ISSUE THREAD

**Issue by michael-baraboo-cnr** [oauth2-proxy/oauth2-proxy#2218]
We clone oauth2-proxy releases to our own container registry, specifically for amd64 and arm64 manifests.
When trying to clone the 7.5.0 release our workflow ran into the following error:
```
Step 1/1 : FROM quay.io/oauth2-proxy/oauth2-proxy:v7.5.0
v7.5.0: Pulling from oauth2-proxy/oauth2-proxy
no matching manifest for linux/arm64/v8 in the manifest list entries
```
It looks like there's a slight difference in how the tags were generated, as seen below. (screenshots taken from the [quay repository page](https://quay.io/repository/oauth2-proxy/oauth2-proxy?tab=tags))

We used to rely on the image tag suffixed with `-arm64` in the past, but moved to using the combined manifest once it started support arm64 linux. If necessary we can go back to that approach.

## Expected Behavior

v7.4.0 had a manifest for `arm64`
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/96433463/19a35b0b-18ed-46ec-a226-7dc8978562cf)

## Current Behavior

v7.5.0 does not have a manifest for `arm64`, but rather two `arm` manifests.
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/96433463/f8e3b7a0-750d-4bd6-a214-7c9eb2ec5254)

## Steps to Reproduce (for bugs)

1.  Start a terminal in a docker-enabled, arm64 linux machine.
2.  `echo 'FROM quay.io/oauth2-proxy/oauth2-proxy:v7.5.0' > /tmp/Dockerfile`
3.  `docker build -f /tmp/Dockerfile .`

**Comment by kvanzuijlen** [comment]
#2220 might fix this as well as my test push to ghcr.io looks like this:
<img width="699" alt="image" src="https://github.com/oauth2-proxy/oauth2-proxy/assets/8818390/84f6a112-009a-4ed4-9440-93521ac8e309">
