### ISSUE TITLE
v7.5.0 breaks my keycloak-oidc login

### ISSUE THREAD

**Issue by sstidl** [oauth2-proxy/oauth2-proxy#2222]
After upgrading my docker installation to latest today (v7.5.0) the logon to keycloak 19 fails,

## Expected Behavior

login should work as it did with v7.4.0

## Current Behavior

Invalid scope error is the error message. 
I don't define the scope in my docker-compose, so i suppose, the default scope setting changed.

## Possible Solution

give any hint, which scope is requested or which scope should be used.

## Your Environment
    command:          
    - --code-challenge-method=S256
    - --tls-min-version=TLS1.2
    environment:
      OAUTH2_PROXY_CLIENT_ID: CCCCCCCCCC
      OAUTH2_PROXY_CLIENT_SECRET: AAAAAAAAAAAAAAAAA
      OAUTH2_PROXY_CODE_CHALLENGE_METHODS: S256
      OAUTH2_PROXY_COOKIE_NAME: __Host-XXX
      OAUTH2_PROXY_COOKIE_REFRESH: 120s
      OAUTH2_PROXY_COOKIE_SECRET: xxxxxxxxxxxxxxxx
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'                            
      OAUTH2_PROXY_FORCE_HTTPS: "true"
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://KC/auth/realms/RE
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_PASS_XAUTHREQUEST: "true"
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_REDIRECT_URL: https://xxxx/oauth2/callback
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_TLS_CERT_FILE: /cert.crt
      OAUTH2_PROXY_TLS_KEY_FILE: /cert.key
      OAUTH2_PROXY_UPSTREAM_TIMEOUT: 2m
      OAUTH2_PROXY_UPSTREAMS: https://xxx
      OAUTH2_PROXY_WHITELIST_DOMAINS: yyy.yyy.at:*

- Version used:
v7.5.0 / latest as of 6th of Sept 2023

**Comment by sstidl** [comment]
It seems that the default scope for keycloak-oidc is empty.
Setting 
```
OAUTH2_PROXY_SCOPE: 'openid email profile'
```
repairs this problem.

**Comment by tuunit** [comment]
Fixed by #2197

**Comment by tuunit** [comment]
Fixed with release 7.5.1
