### ISSUE TITLE
Provider page should be skipped for SSO but not if app is directly used

### ISSUE THREAD

**Issue by umershaekoor** [oauth2-proxy/oauth2-proxy#2225]
Application A and B both use the same provider. 

Case A:

- User logs into application a. 
- After some changes switches to application b.
- Is authorized via skipping the provider login page and goes directly to /oauth2/start
- Hence finished single sign on.

Case B: 
- User wants to access application b directly. 
- Calls the url for application b.
- Sees the provider login page (or url for custom login page <-- how to do this?)
- Clicks on login button that makes a redirect to /oauth2/start.
- User is authenticated and can use application b.
## Expected Behavior

Both the flows function at the same time, based on incoming requests.

## Current Behavior

The current behaviour is that you can either skip the login page, in which case the redirect is directly to the /oauth2/start endpoint OR you can set the page to be displayed. This inhibits use cases where both functionalities are required depending on client/user.

## Possible Solution

Maybe application A makes the request using a certain request param that enables the skipping of provider page in order for single sign on to work?

## Context

We are unable to use single sign on and login page when accessing Application B directly to work at the same time.

## Your Environment

Environment is immaterial for the issue.

- Version used: 7.4.0

**Comment by tuunit** [comment]
Hi @umershaekoor, the flag `skip-provider-button` is used to skip the oauth2-proxy login page.
The flags `custom-templates-dir`, `custom-sign-in-logo`, `banner`, `footer` can be used to customize this page. You cannot have different behaviors for the same oauth2-proxy. Either you will always have a instant redirect to the provider or you will always see the login page. Which to be honest is not much of a login page, more of a manual confirmation page to tell the user that a redirect has to be done.
