### ISSUE TITLE
Skipnonce is configured insecurely by default

### ISSUE THREAD

**Issue by t-animal** [oauth2-proxy/oauth2-proxy#2230]
## Expected Behavior

Oauth2 proxy should be configured securely by default, validating the token nonce to [prevent replay attacks](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest).

## Current Behavior

The configuration to skip nonce verification is reasonably prefixed with `insecure`, but the default value is `true`, indicating that oauth2-proxy is insecure by default.

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/1775745/ee87c5fd-b93f-408a-b0bb-a82ddf06d558)

## Possible Solution

Set the default value to false.  Individual providers can still set the value to ~~false~~ true.

- Version used:
7.5.0

**Comment by tuunit** [comment]
Hi @t-animal, thank you for the opening the issue. I'll have to check the actual implementation.

**Comment by JoelSpeed** [comment]
If I remember correctly, this was set to true so that it would be backwards compatible. Not all providers support the nonce implementation so, if we want to make it the default, it must be changed in a major release. Perhaps we can add this issue to the v8 milestone

**Comment by t-animal** [comment]
[This comment](https://github.com/oauth2-proxy/oauth2-proxy/blame/854401ec00f0f784b3e60738f72f9f20c7f22b03/pkg/apis/options/providers.go#L210) indicates that this may have been intended all along. Judging from [this search](https://github.com/search?q=repo%3Aoauth2-proxy%2Foauth2-proxy%20InsecureSkipNonce&type=code) the built-in providers could override the value and set it to `true`, if needed. Of course, this doesn't help people who have already deployed the insecure default config and depend on it being insecure.

**Comment by t-animal** [comment]
I think this is still relevant.

**Comment by t-animal** [comment]
I think this is still relevant, but I won't keep bumping this issue every 2 months just to keep it alive...
