### ISSUE TITLE
Idea: Simplify cookie backend by pass OIDC tokens to client as-is

### ISSUE THREAD

**Issue by jkroepke** [oauth2-proxy/oauth2-proxy#2233]
## Current Behavior

Reading about Cookie Session Store at [docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/session_storage) and code, oauth2-proxy seems merge all OIDC tokens into one cookie and do additional mutation with cookie, e.g. sign, encrypt and compress.

If using Azure AD as OIDC provider, the cookie cant used because it goes over 4KB. Cookie splitting is required which adds additional complexility.

## Possible Solution

Instead do alle the mutations with the cookie, could it be possible to pass all 3 OIDC token (access, ID, token) to the client of the browser? In general, such tokens are already signed by upstream OIDC provider which already prevents client modifications. Additionally, such tokens rarely touches the 4KB sizes, unless the user is in tons of AD groups (which can be limits to Azure AD side)

## Context

I'm trying to implement oauth2-proxy as stateless variant and I not able to deploy an redis service. However I'm constantly hitting the 4KB cookie size.

## Your Environment

- Version used: 7.5.0

**Comment by JoelSpeed** [comment]
Azure tokens can be massive, we've seen this many times, seeing cookies that need to be 8kb or more.

With Azure, the only real way we can handle this is to split the cookies or use some persistent storage. The persistent storage mechanism btw, is designed to be expandable. If you can't deploy redis, is there some other storage you could use were it to be implemented?

The OAuth2 Proxy needs to be able to retrieve the tokens from a session, yes, in theory it could pass them directly to the client, but they'd then need to be stored in multiple cookies which is not currently how the project is architected

**Comment by jkroepke** [comment]
> but they'd then need to be stored in multiple cookies which is not currently how the project is architected

Thats basically the request. Use independent cookies for access_token, refresh_token and maybe have an option to NOT store the id_token (This IDToken required to stored?) They should normally not go over 4KB by default, otherwise Application like Azure Portal are also not working.

**Comment by tuunit** [comment]
The id_token is required to be stored! By design oauth2-proxy is stateless and always reconstructs the session with the user information and details from the token and does verification on the validity and integrity via the JWT payload. Otherwise oauth2-proxy will not be able to recognize which using you are. Therefore all those details have to be stored somewhere. Either in a cookie or an external storage like redis. In the cause of external storage solutions like redis a cookie with a reference to the stored session information (including the id_token) has to be stored on the client side.

**Comment by jkroepke** [comment]
> The id_token is required to be stored!
> ... Otherwise oauth2-proxy will not be able to recognize which using you are.

Why this is ALWAYS a requirement? Why oauth2-proxy **always** needs to know, where am I?

On Kubernetes, together with nginx (auth_request), the job of oauth2-proxy is validing access_token, refresh tokens and initialize the login flow. Even the access token contains a subject claim which can be used for logging

id_token contains additional claims like groups. But this can be validated once on callback + refresh. 

Of course, if 

* --set-authorization-header
* --set-xauthrequest
* --set-basic-auth

is defined, then the ID Token needs to be stored. Thats correct. But none of the flags are enabled by default. Do I miss other edges, where the IDToken needs to be stored?

**Comment by tuunit** [comment]
Unfortunately, the access token does not have to contain any data it can just be a random string. As defined by the oauth2 and oidc specification. Therefore we have to rely on the id_token. For some providers with introspection capabilities it might be an option to reconstruct the details from the introspect endpoint. This is currently an open PR. I acknowledge that this might not be optimal and more and more people are using oauth2-proxy for application directed communication which it wasn't originally designed for.

**Comment by jkroepke** [comment]
Fair enough.

I never saw an non JWT access_token from a OIDC compliant provider but the spec doesnt define a standard for access_token.

Thanks for the hint about this.

Then access_token could be throw away by default?

**Comment by tuunit** [comment]
Hi @jkroepke,

yes unfortunately some enterprise solutions like PingID and ForgeRock Identity Management sometimes use random strings for access tokens. I've recently read something about an initiative by the oauth2 foundation / committee to define JWT as the standar format for access-tokens as well in the future.

As of now oauth2-proxy isn't really a pure **oauth2 proxy**. It is better regarded as an odic proxy. It would in theory be possible to adapt the flow in a way that by always checking the access-token with the identity provider for each request we could support pure oauth2.

**Comment by jkroepke** [comment]
Looking forward to #1751 seems a good idea. Calling an external API for each request sounds like an overhead, but the requests from auth_requests can be cache by nginx internally via `proxy_cache`.
