### ISSUE TITLE
Update Go version?

### ISSUE THREAD

**Issue by superlazyname** [oauth2-proxy/oauth2-proxy#2234]
https://github.com/oauth2-proxy/oauth2-proxy/blob/225dc92adf09c03f7414e260b5a7c29fd371f035/go.mod#L3

go 1.19 is end of life as of about a month ago https://endoflife.date/go

I recommend updating to go 1.21 (or 1.20, but that version won't have as long of a life span).

**Comment by tuunit** [comment]
Will be taking into account for the next major release. Either v7.6.0 or v8.0.0. I added the milestone v8.0.0 for now. Thank you for the suggestion.

**Comment by tuunit** [comment]
We are currently still blocked. The upgrade to go 1.21 is taking place in #2235. Unfortunately, a complete refactoring of how we test our configuration is necessary.

**Comment by tuunit** [comment]
Hi @superlazyname,

finally found a solution to resolve the issues and we can upgrade the upgrade to go 1.21 soon.
