### ISSUE TITLE
kubeapps did not redirect to Keycloak authentication page

### ISSUE THREAD

**Issue by cwyj** [oauth2-proxy/oauth2-proxy#2241]
## Expected Behavior
I deploy a kubeapps app to managing k8s cluster apps which is authenticated by Keycloak server.
When i type http://9.199.116.70:8080/（my kubeapps web address） in the browser,and then i click "login via oidc provider" ,link jumps to Keycloak authentication page.

## Current Behavior

When i type http://9.199.116.70:8080/ in the browser,link jumps to http://9.199.116.70:8080/#/login.
And then i click "login via oidc provider" on web,link jumps to http://9.199.116.70:8080/oauth2/start/.(/oauth2/start/ is oauthLoginURI which default value set in kubeapps helm chart values.yaml).Finally browser leave me a Blank page.
So i think i was never redirected to my identity provider.
<img width="777" alt="image" src="https://github.com/oauth2-proxy/oauth2-proxy/assets/22216714/fd81f188-4531-40b0-ad07-3fb6dcc7a385">
<img width="588" alt="image" src="https://github.com/oauth2-proxy/oauth2-proxy/assets/22216714/a4f9de3d-531d-489e-bd69-964c3660d5df">

I have already start a kubeapps issue  https://github.com/vmware-tanzu/kubeapps/issues/6734.

## Steps to Reproduce (for bugs)
The main reference documents which I deploy Keycloak and kubeapps is https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-keycloak/.
Here is my oauth2-proxy configuration:
`      - args:
        - --provider=oidc
        - --client-id=kubeapps
        - --client-secret=ZoCV6nCBSPCEtjcWJibcj5zcv3N6u3Fy
        - --cookie-secret=bm90LWdvb2Qtc2VjcmV0Cg==
        - --upstream=http://localhost:8080/
        - --http-address=0.0.0.0:3000
        - --email-domain=*
        - --pass-basic-auth=false
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --skip-auth-regex=^\/config\.json$
        - --skip-auth-regex=^\/favicon.*\.png$
        - --skip-auth-regex=^\/static\/
        - --skip-auth-regex=^\/$
        - --scope=openid email groups
        - --ssl-insecure-skip-verify
        - --cookie-secure=false
        - --scope=openid email groups
        - --oidc-issuer-url=https://11.39.228.48:8443/realms/kubeapps
        - --set-authorization-header=true
        image: docker.io/bitnami/oauth2-proxy:7.1.2-debian-10-r22
`

Any other suggestions for me to figure out why the web did not redirect to Keycloak authentication page?thanks.

**Comment by JoelSpeed** [comment]
Do you have any logs from the OAuth2 Proxy to show that it received the request to `/oauth2/start`? I think adding logs here would help to understand what happened
