### ISSUE TITLE
error loading cookied with redis

### ISSUE THREAD

**Issue by redboxstudio** [oauth2-proxy/oauth2-proxy#2246]
hi, I built oauth2-proxy from the master branch. Now I want to use it in a place with redis, but when I turn it on, errors appear in the console, until I noticed that this affects the operation of my application as if everything was working. Could you tell me what these errors affect? Does this mean that sessions are useless and are created anew every time?
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/0bc0f944-997d-465f-aceb-0f0465b3c66b)
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/2daf0c8d-b715-4d8f-ae9b-fe605e0904e3)

**Comment by JoelSpeed** [comment]
Your screenshot has truncated the error message, can you paste the full error message so that we can understand what exactly went wrong?

**Comment by redboxstudio** [comment]
oh, I forgot to close this, the error was apparently related to the lack of a refresh token, I think this is normal behavior when the session time expires, it is deleted from radish and the next time it is not found
