### ISSUE TITLE
Restrict access to subpages with Azure AD group objectId with "allowed-group" and Nginx

### ISSUE THREAD

**Issue by cnhsn** [oauth2-proxy/oauth2-proxy#2249]
I am using Azure AD as provider. When I first log in to my website, after successfully logging in to Azure AD, when I check the "/oauth2/userinfo" link, I can see the group objectIds I am a member of in Azure AD. So the system fetchs user information without any problem. What I want to do here is, I don't want there to be any restrictions when you go to "https://cnhsn.test/". All AAD users should have access to this page. But when a user visits the link "https://cnhsn.test/paris" they should not be able to see this page unless they belong to the group with object ID "aaaaaaa-bbbb-cccc-dddd-eeeee". If they are a member of that group, they should be able to log in directly without any warning or notification. I would like to do the same for the other subpages. How can I do that? I am using NGINX as proxy server.

## Expected Behavior

Make pages on the website according to Azure AD groups accessible only to group members.

## Current Behavior

Oauth2-proxy is working very well and there is no problem with user control. But right now all azure ad users can access every page of the website.

## Possible Solution

Maybe I can do something about it using the "allowed-group" variable. I tried to add "allowed_groups" variable at the end of "oauth2/auth" connection but I got 500 internal server error. I have already used the "allowed-group" variable as "allowed_groups" in my "oauth2-config.cfg" file. I think I may have made a mistake here too.

## Context

I can't control the access of website users and this way I will be able to. Only users authorized by me will be able to access pages that contain important data.

## Your Environment

RHEL7.9
Nginx 1.20.1
- Version used: 7.4

**Comment by mhktc** [comment]
we have the same scenario but with aws cognito we are trying to solve.

**Comment by cnhsn** [comment]
> we have the same scenario but with aws cognito we are trying to solve.

I am still researching. Did you get any results?

**Comment by mhktc** [comment]
no not really.
we only had some ideas about putting multiple instances of oauth2_proxy on a server and then a apache reverse proxy in front of it.
but this isnt really scalable.

**Comment by tuunit** [comment]
Hi @cnhsn,

currently oauth2-proxy does not support route based authorization. You would essentially have to either deploy multiple oauth2-proxy instance with different configs / allowed groups and share the cookie between them via your nginx config or replace your basic nginx with openresty and build your own filter logic based on the groups and routes.

Furthermore, there is a PR open for routed based authorization that could be interesting to you. Full disclosure, I haven't checked if it would be of use to you for this use case:
https://github.com/oauth2-proxy/oauth2-proxy/pull/2011

**Comment by cnhsn** [comment]
> Hi @cnhsn,
> 
> currently oauth2-proxy does not support route based authorization. You would essentially have to either deploy multiple oauth2-proxy instance with different configs / allowed groups and share the cookie between them via your nginx config or replace your basic nginx with openresty and build your own filter logic based on the groups and routes.
> 
> Furthermore, there is a PR open for routed based authorization that could be interesting to you. Full disclosure, I haven't checked if it would be of use to you for this use case: #2011

Thank you @tuunit !

Ben de bu sekilde yapmayi dusunuyorum. Birden fazla oauth2-proxy deploy ederek bunlarin her birini yalnizca bir context path'i auth edecek sekilde ayarlayacagim. Fakat yine bir konuda yardiminiza ihtiyacim var. 
> share the cookie between them via your nginx config
How can I do this? Could you please explain it briefly?

Thanks for your answer.

**Comment by tuunit** [comment]
Hi @cnhsn,

you usually don't have to do much. As long as you use the same Identity provider and your users have a valid session after the first login. The oauth2 flow will transparently happen in the backend.

On the other hand if you are using multiple different domains / subdomains that might be another story, depending on how strict your setup is. You might want to have a look into setting cross domain / [proxied cookies](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_domain) in that case. Which would be fine because the content is still a jwt id_token that can be verified by oauth-proxy.
