### ISSUE TITLE
keep getting sign in with google instead of azure

### ISSUE THREAD

**Issue by ITBeyder** [oauth2-proxy/oauth2-proxy#2250]
## Expected Behavior

with application version 7.1.3 i'm able to log in with azure ad.

## Current Behavior

getting only log in with google option .

i reinstalled the helm chart with this command 

❯ helm install oauth2-proxy  oauth2-proxy/oauth2-proxy -n kubernetes-dashboard --version 6.17.1 \
  --set configuration.clientID="e07df4f5-xxx-xxx-xxx-xxxx" \
  --set configuration.clientSecret="xxxxxxxx~xxxxxxxx~xxxxxxx" \
  --set configuration.cookieSecret="xxxxxxx==" \
  --set configuration.oidcIssuerUrl=https://login.microsoftonline.com/e741d71c-xxxx-xxxxxxxxxxxxx/v2.0 \
  --set configuration.redirectUrl="https://xxxx.kubeui.xxxxxxxx.com/oauth2/callback"

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by Tipsmark** [comment]
Same issue here - in helm/values add or use command line as you do.
    extraArgs:
      - --provider=azure

**Comment by kvanzuijlen** [comment]
@ITBeyder does the solution provided by @Tipsmark solve your issue?

**Comment by ITBeyder** [comment]
> @ITBeyder does the solution provided by @Tipsmark solve your issue?

No

**Comment by tuunit** [comment]
@ITBeyder please provide your error logs.

**Comment by cudneys** [comment]
This solution is not helpful in my case.  Even with the provider set to azure, the provider is set to Google.

I'm using the quay.io/oauth2-proxy/oauth2-proxy:v7.6.0 image.

**Comment by gl1tch** [comment]
I'm having the same problem using the chart [here](https://oauth2-proxy.github.io/manifests) i've tried using a values.yaml file configuration and setting the provider to "azure" in the **config** section. But when I go to my URL i'm presented with Google Sign In.

Also followe the instructions [here ](https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/azure)
