### ISSUE TITLE
add tls sni to outbound connections

### ISSUE THREAD

**Issue by ceastman-r7** [oauth2-proxy/oauth2-proxy#2254]
## Expected Behavior

I expect the outbound connections to utilize tls sni.

## Current Behavior

sni is not set, so outbound connections just appear as tcp connections to port 443. 

istio-proxy log attached to the oauth2-proxy:

{"downstream_remote_address":"10.1.28.101:49254","requested_server_name":null,"response_duration":null,"user_agent":null,"x_b3_parentspanid":null,"request_id":null,"request_duration":null,"x_b3_sampled":null,"upstream_local_address":"10.1.28.101:49258","response_flags":"-","bytes_sent":10978,"authority":null,"x_forwarded_for":null,"protocol":null,"method":null,"duration":90223,"x_b3_traceid":null,"downstream_local_address":"3.33.147.176:443","response_tx_duration":null,"bytes_received":1876,"start_time":"2023-09-29T18:39:17.890Z","upstream_cluster":"PassthroughCluster","path":null,"upstream_host":"3.33.147.176:443","response_code":0,"x_b3_spanid":null,"connection_termination_details":null}

versus

istio-proxy from another pod that used curl that sets the sni correctly:

{"duration":350,"protocol":null,"authority":null,"connection_termination_details":null,"x_b3_spanid":null,"x_forwarded_for":null,"user_agent":null,"response_flags":"-","response_duration":null,"method":null,"upstream_host":"142.250.191.228:443","bytes_sent":25642,"start_time":"2023-09-29T18:52:57.047Z","request_id":null,"bytes_received":883,"requested_server_name":"www.google.com","downstream_local_address":"142.250.191.228:443","upstream_local_address":"10.1.10.128:54148","x_b3_traceid":null,"request_duration":null,"downstream_remote_address":"10.1.10.128:54132","response_tx_duration":null,"path":null,"x_b3_sampled":null,"response_code":0,"upstream_cluster":"PassthroughCluster","x_b3_parentspanid":null}

notice requested_server_name has the name of the website curl was requesting

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Context

This will help organizations to accomplish egress filtering by knowing what websites are being requested.

## Your Environment

- Version used:
7.5.0 and 7.5.1

**Comment by JoelSpeed** [comment]
Have you looked into the `pkg/upstream` code to understand what's happening here? I'm not entirely sure whether this is a bug or whether it's a misconfiguration issue

**Comment by ceastman-r7** [comment]
@JoelSpeed sorry my golang skills are very lacking. I found this while googling: https://github.com/vulcand/oxy/pull/145/files 

looks like they went from
TLSClientConfig:   &tls.Config{InsecureSkipVerify: true}

to

TLSClientConfig: &tls.Config{
InsecureSkipVerify: true,
ServerName:         request.Host,
},

**Comment by ceastman-r7** [comment]
In other languages this typically fixes the issue, setting the tls server name for outbound connections.

I found two references to tls client config:
https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/upstream/http.go#L153
and
https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/upstream/http.go#L207

**Comment by JoelSpeed** [comment]
This seems like it would be a fairly innocuous change, if we can get a PR for the change then I don't have an issue with merging it given appropriate updates to tests.

Existing users will see a hostname change, but, given the expected usage of OAuth2 Proxy, I wouldn't expect that backends are relying on whatever is currently set in that host header anyway. It's most likely people are proxying to localhost or other network aliases rather than real FQDNs.

**Comment by FAUSheppy** [comment]
It seems this is still not fixed?

**Comment by tuunit** [comment]
@FAUSheppy as of yet no solution / PR for this has been raised

**Comment by FAUSheppy** [comment]
Ok I will have a look at it on the weekend and suggest a PR.

**Comment by FAUSheppy** [comment]
Got it working

in http.go - newReverseProxy & WSProxy

    parsedURL, err := url.Parse(upstream.URI)
    if err != nil {
        transport.TLSClientConfig.ServerName = parsedURL.Host
    }

and in ServeHTTP:

    parsedURL, err := url.Parse(h.upstream.URL)
    if err != nil {
        req.Host = parsedURL.Host
        req.URL.Host = parsedURL.Host
    }

but I also realized there might be a compatibility Issue here:

    setProxyUpstreamHostHeader

..sets the Host-Header based on the request, meaning if the request has `example.com` but the upstream points to `test.com`, then the Host-Header sent to the upstream would still be "example.com". Somebody might be relying on that - even though it somewhat silly behavior.

How should this be handled?

**Comment by ceastman-r7** [comment]
I can try that this week, thank you for the suggestion.
