### ISSUE TITLE
Add multiple allowed-group: in the extraArgs: tag of oauth2-proxy

### ISSUE THREAD

**Issue by pulkit0627** [oauth2-proxy/oauth2-proxy#2259]
Hi Currently my application is using oauth2proxy version 7.1.3 and proxy is mapped to single group. I want to mapp the proxy to multiple groups. Can you suggest if it is implemented in any latest release please.

## Expected Behavior
  oauth2-proxy:
    extraArgs:
      allowed-group: 
      - usrsGroup1
      - usrsGroup2

## Current Behavior
  oauth2-proxy:
    extraArgs:
      allowed-group:  usrsGroup1

Team who is part of usrsGroup1 can access the tekton using Keycloak to that project only. So pain area is that the team has to be part of all the groups in order to access the other products just to access tekton for build status. So we want to add multiple groups to the product so that the team of other groups can also access the tekton via keycloak SSO access.

## Possible Solution

I read that the allowed-group:   can be a string or list in future releases so want to understand if below is possible and in which release its available.
  oauth2-proxy:
    extraArgs:
      allowed-group: 
      - usrsGroup1
      - usrsGroup2
      
In argoCD, I saw the --allowed-group[usrsGroup1 usrsGroup2] but that didnt work with oauth2proxy - oauth2-proxy:4.2.2
I also read that we can add the allowed-group tag multiple times  like below but that also didnt work and took the last group as usrsGroup2
      allowed-group: usrsGroup1
      allowed-group: usrsGroup2

- Version used: 7.1.3

**Comment by tuunit** [comment]
@pulkit0627 please use the alpha-config or config files for this use case. In the files you can specify multiple groups.

Legacy Config: https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints#auth
Alpha Config: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config#provider

**Comment by kvanzuijlen** [comment]
@pulkit0627 as we haven't heard from you I'll close this issue now. Please add a comment (mentioning) me if you have any additional questions.

**Comment by HWiese1980** [comment]
> @pulkit0627 please use the alpha-config or config files for this use case. In the files you can specify multiple groups.
> 
> Legacy Config: https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints#auth Alpha Config: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config#provider

The links are down. All the links I can find in issues like this are down. Man, this is annoying... 

Really no offense meant...
