### ISSUE TITLE
[QUESTION] Inquiry regarding oauth2-proxy's support polciy

### ISSUE THREAD

**Issue by ishaqkhattana** [oauth2-proxy/oauth2-proxy#2263]
## Expected Behavior
To find a support policy defined somewhere in the documentation.

## Current Behavior
Unable to find support policy in the documentation.

## Possible Solution
A dedicated section in the Readme outlining the support policy/supported versions.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Context
We're looking to adopt oauth2-proxy and we always find it comforting to know the support policy of all our external dependancies so that we can plan upgrades accordingly and ensure everything runs smoothly. Any help would be appreciated

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
This is not a commercial open source project, it does not have a team of people working on it. Those who do maintain it do so on their own time as a passion project. Any support is best effort and is not guaranteed.

**Comment by tuunit** [comment]
We try our best to keep the project up to date but as Joel already mentioned we do it in our free time. Nevertheless, I would like to add that I currently pursue the goal to get more automation and more regular builds up and running.
