### ISSUE TITLE
OAuth state parameter characters incompatible with AWS Cognito

### ISSUE THREAD

**Issue by haavardw** [oauth2-proxy/oauth2-proxy#2264]
OAuth2-Proxy seems to set a state variable that contains characters not supported by AWS Cognito as the IdP, i.e the backslash-character in the "redirect url" part of the state variable.

## Expected Behavior

Successful invocation of the authorization endpoint

## Current Behavior

I end up at the authorization endpoint with this URL:

https://<custom-cognito-domain>/authorize?idp_identifier=<redacted>&redirect_uri=https://<app-domain>/oauth2/callback&response_type=code&client_id=<redacted>o&state=NSkle<redacted>g62kjIjZHT-_yj39Mb0k:\/&scope=openid%20email%20profile

which results in a 400 response from Cognito.

## Possible Solution

It seems like manually removing the \\-character from the state variable makes the rest of the flow work as expected.

## Your Environment

Running the oauth2-proxy container inside a AWS Fargate ECS cluster. AWS Cognito hosted in a separate account.

- Version used: 7.5.1

**Comment by tuunit** [comment]
will be fixed by https://github.com/oauth2-proxy/oauth2-proxy/pull/2239

**Comment by mrnim94** [comment]
I'm encountering this issue.
It causes us not to access all web via oauth2-proxy + Cognito
