### ISSUE TITLE
callback request getting 403

### ISSUE THREAD

**Issue by prabhapa** [oauth2-proxy/oauth2-proxy#2268]
I am using oauth2 proxy for securing my local apps using okta. configured the oauth2-proxy in my k8s cluster.
my callback request getting 403. compared okta and oauth2-proxt configuration. All is well. similar set up for other app works fine. Since auth2-proxy is not printing the logs for this 403 error, not able to figureout root cause.Please help.

## Expected Behavior

callback should be succeeded.

## Current Behavior

[2023/10/13 05:03:43] [oauthproxy.go:959] No valid authentication in request. Initiating login.
10.149.137.27:37486 - 6a38d75610bcb721d94a5b9f466925af - - [2023/10/13 05:03:43] xxxx.xxx.xxx GET - "/_dashboards/oauth2/callback?code=-XdEZnTMnvOm6jSvuB7yE0VDVVH0k1Z3v4sA9zAsXds&state=NaknsRu0dVliZ3VXsZV72Ggf-okGLig_4dfuNqkYwTQ%3A%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4950.0 Safari/537.36" 403 8634 0.000

## Possible Solution

full logs to understand why the callback fails.

## Steps to Reproduce (for bugs)

1) please create oauth proxy with okta with below configs.

2) try to open the app url.it should take you to auth flow.

3)once you enter the credentials , they are succeeded on the okta .

4) But at the end of it callback fails.

**my config map for oauth config:**
apiVersion: v1
data:
  oauth2_proxy.cfg: |
    provider = "oidc"
    redirect_url = "https://xxx.xxx.xxx/_dashboards/oauth2/callback"
    oidc_issuer_url = "https://xxx.xxx.xxx/oktapreview.com"
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: oauth2-proxy-opensearch
    meta.helm.sh/release-namespace: cloud
  labels:
    app: oauth2-proxy
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/instance: oauth2-proxy-opensearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/version: 7.4.0
    helm.sh/chart: oauth2-proxy-6.16.1
  name: oauth2-proxy-opensearch
  namespace: cloud

**my deployemnt spec:(part of it)**

  spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --http-address=0.0.0.0:4180
        - --https-address=0.0.0.0:4443
        - --metrics-address=0.0.0.0:44180
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        - --auth-logging=true
        - --standard-logging=true
        - --request-logging=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: oauth2-proxy-opensearch
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: oauth2-proxy-opensearch
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie-secret
              name: oauth2-proxy-opensearch
        - name: OAUTH2_PROXY_UPSTREAMS
          value: http://kibana-proxy.cloud.svc.cluster.local      
        - name: OAUTH2_PROXY_COOKIE_REFRESH
          value: 15m  
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          name: http
          protocol: TCP
        - containerPort: 44180
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 5m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/oauth2_proxy/oauth2_proxy.cfg
          name: configmain
          subPath: oauth2_proxy.cfg
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: oauth2-proxy-opensearch
      serviceAccountName: oauth2-proxy-opensearch
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: oauth2-proxy-opensearch
        name: configmain

**secrets:**
client id,secret ,cookie secrets are configured correctly as the interaction between okr

## Context

I am using oauth2 proxy for securing my local apps using okta. configured the oauth2-proxy in my k8s cluster.
my callback request getting 403. compared okta and oauth2-proxt configuration. All is well. similar set up for other app works fine. Since auth2-proxy is not printing the logs for this 403 error, not able to figureout root cause.Please help.

## Your Environment

kubernetes 1.27

- Version used: v7.4.0

**Comment by tuunit** [comment]
Hi @prabhapa,

first of all you set your upstream in two locations:

cfg file:
```
upstreams = [ "file:///dev/null" ]
```

deployment environment variables:
```yaml
  - name: OAUTH2_PROXY_UPSTREAMS
    value: http://kibana-proxy.cloud.svc.cluster.local/
```

**Comment by prabhapa** [comment]
Hello @tuunit , thanks for the reply. yep sure i will fix this. But i am sure that not causing this issue as the similar config works for another app.I guess the environment variable takes the preference as per my observation.

**Comment by ianroberts** [comment]
> redirect_url = "https://xxx.xxx.xxx/_dashboards/oauth2/callback"

> 10.149.137.27:37486 - 6a38d75610bcb721d94a5b9f466925af - - [2023/10/13 05:03:43] xxxx.xxx.xxx GET - "/_dashboards/oauth2/callback?code=....

How are you configuring the ingress that exposes oauth2-proxy on `https://xxx.xxx.xxx/`?

The callback URL is `/oauth2/callback` by default so you will either need to configure `proxy_prefix = "/_dashboards/oauth2"` (to tell oauth2-proxy that the endpoints are under `/_dashboards` rather than at the root) or configure the ingress to rewrite the URL path to remove the `/_dashboards` prefix and pass the request through to oauth2-proxy as just `/oauth2/callback`.  Which of those two options works likely depends on exactly how you've configured kibana.
