### ISSUE TITLE
Unable to use proxy on http only with http (h2c)

### ISSUE THREAD

**Issue by jmasek** [oauth2-proxy/oauth2-proxy#2270]
I am using the Kubernetes Nginx ingress controller as a reverse proxy that also provides TLS termination. In the container, I have a GRPC service that is using http2.

## Expected Behavior

OAuth2 proxy is able to validate tokens sent in the http2 header and forward the request.

## Current Behavior

The Proxy is communicating in http/1.1 resulting in a communication error. 

## Possible Solution

I believe the reason for that is that without TLS there is no way to upgrade the connection from http1.1 to http2 using ALPN.  However, it seems that it should be possible to use the http2 Server instead of the standard one (https://pkg.go.dev/golang.org/x/net/http2/h2c). Maybe when setting some special option? Would it be possible, what do you think?

## Steps to Reproduce (for bugs)

Use proxy on http (without https) to access grpc service (http2).

## Context

In the current state, I believe that proxy cannot be used in the Kubernetes environment for GRPC services.

## Your Environment

- Version used: 7.5.1

**Comment by tuunit** [comment]
Hi @jmasek,

thank you for bringing this up. The project currently uses the standard net/http library which as of now does not support http2: https://github.com/golang/go/discussions/60746

Therefore a simple flag won't do for now. A proper feature implementation will be necessary to support this. Feel free to give it a try and raise a PR. For now we will keep this issue open.

**Comment by Mahagon** [comment]
I would also like to see http2 support :) (commented to re.activate this ticket)
