### ISSUE TITLE
[Help needed] Can I Use oauth2-proxy without frontend?

### ISSUE THREAD

**Issue by pbxqdown** [oauth2-proxy/oauth2-proxy#2280]
I'm developing a react native android app that already implements signin-with-google page. May I pass the token/userinfo from app to oauth2-proxy(e.g. through calling some api endpoint) such that oauth2-proxy can record user info and use it to do authentication?

Following is the auth flow i would like to have:
```
request with jwt info
|
v
k8s ingress nginx  ----> oauth2-proxy
|
v
my app backend
```

**Comment by tuunit** [comment]
Hi @pbxqdown yes you can pass the id_token as a Bearer Authentication header and skip the frontend.

flag to be set to true for this purpose `--skip-jwt-bearer-tokens=true`

> will skip requests that have verified JWT bearer tokens (the token must have [aud](https://en.wikipedia.org/wiki/JSON_Web_Token#Standard_fields) that matches this client id or one of the extras from extra-jwt-issuers)

https://oauth2-proxy.github.io/oauth2-proxy/docs/behaviour
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#command-line-options

**Comment by pbxqdown** [comment]
Thank you @tuunit ! I'm wondering which api endpoint of oauth proxy shall my android app call?
By adding skip-jwt flag, will my app not able to embed jwt in http request for auth? I thought oauth proxy would return a jwt token if I call it.

**Comment by tuunit** [comment]
If I correctly understand you. Your app already manages the oauth2 login and you just want to communicate with a backend that is protected via oauth2-proxy without retriggering a login process, right?

If so you just send the jwt token with all your requests to the backend and oauth2-proxy will validate that the jwt isn't expired and create a session for it and redirects your user to the backend. No special calls to any endpoints necessary.

**Comment by pbxqdown** [comment]
make sense, i think google's id_token is jwt token. So I can record this token in client cookie. For each subsequent request, this id_token is in http header and oauth2-proxy is responsible for validating it?

**Comment by tuunit** [comment]
The odic specification defines that id_tokens are only allowed to be valid jwt tokens.

After your app has done the authentication. You will need to store the id_token in any way you like and use it as an Authentication header: `Authentication: Beater <token>`

Additionally you will have to ensure that your ingress controller forwards the authentication header. For security reasons ingresses are often configured to drop headers.

**Comment by pbxqdown** [comment]
yup thank you for the detailed explanation @tuunit ! oauth2-proxy will relieve me from writing an auth service my own :)

**Comment by tuunit** [comment]
If you encounter any issues. Feel free to get back in touch.

**Comment by pbxqdown** [comment]
Hi @tuunit thanks for the previous help! i think i'm almost done, but run into following issue when try to pass an http request with bear token through oauth2-proxy.
`[2023/10/30 00:56:57] [jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, not implemented]`
wondering what may be the cause of issue? I already passed `skip-jwt-bearer-tokens`, `provider` and `clientID` flag to oauth2-proxy.

**Comment by tuunit** [comment]
What's the content of your Bearer Token?

**Comment by pbxqdown** [comment]
yes, I'm using format Bear [id_token].
Just resolved the problem, it seems that i need to specify --extra-jwt-issuers=[issuer]=[aud] flag. Guess oauth2-proxy will check if issuer will match aud in jwt token.
