### ISSUE TITLE
Passkeys

### ISSUE THREAD

**Issue by gedw99** [oauth2-proxy/oauth2-proxy#2281]
Hey @JoelSpeed 

Is passkey support something that is wanted in this repo ?

https://developers.google.com/identity/passkeys

**Comment by tuunit** [comment]
Hi @gedw99,

I don't really see how passkeys would play a role for oauth2-proxy. The providers have to support passkeys but the oauth2 'handshake' between oauth2-proxy and the provider would stay exactly the same. The user just won't have to enter a password on the provider page.

**Comment by gedw99** [comment]
I don’t have enough depth of knowledge about it, but I can see your point.

**Comment by tuunit** [comment]
As oauth2-proxy only awaits the callback response I don't think it will have any effects on the logic and implementation of oauth2-proxy. If a ID provider is going to support passkeys instead of passwords.

@braunsonm what's your view on this?

**Comment by braunsonm** [comment]
@tuunit your understanding is correct. This would be on the IdP to implement, not oauth2-proxy. We already are compliant with IdPs that support passkeys.

**Comment by gedw99** [comment]
@braunsonm i searched for any code that does Sign in with Apple but did not find any.

**Comment by tuunit** [comment]
Hi @gedw99,

Apple always marches to the beat of their own drum. They never fully want to admit that they follow a standard like OIDC but as far as I understand it there "innovative" ["Sign in with Apple"](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple) is based on OIDC with minor changes. You could test if it will just work with our default oidc provider but it might be necessary to write a custom provider for it. If that is of interest to you. Feel free to open another issue asking for help with setting up Apple Sign In. (Add the "help wanted" label to it 😄)

**Comment by tuunit** [comment]
Someone wrote a details article about the Apple implementation:
https://medium.com/@isharaaruna/what-is-apple-sign-in-challenges-and-way-forward-with-wso2-identity-server-f1faa1b715cc#:~:text=Apple%20Sign%20in%20protocol%20is,generate%20it%20on%20the%20fly.

**Comment by gedw99** [comment]
thanks @tuunit 

I just now created an issue here with the required info.

https://github.com/oauth2-proxy/oauth2-proxy/issues/2298

I don’t know how to tag it as “ help wanted”
