### ISSUE TITLE
OIDC provider fails to retrieve claim (ADFS backend)

### ISSUE THREAD

**Issue by ph4nt0m** [oauth2-proxy/oauth2-proxy#2287]
## Expected Behavior

The OIDC provider is expected to work with an ADFS backend providing v1.0 ID tokens. It did work in version 7.2.1.

## Current Behavior

Disclaimer: Im neither an OIDC nor a Go expert, but this is what I found out:

When the OIDC provider fails to extract the claim `preferred_username` from the ID token (which is not present in v1.0 tokens according to specification), it tries to fetch it by making a request to the profile URL. This request fails with code 401 in my case:

`Error redeeming code during OAuth2 callback: could not get claim "preferred_username": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "401":`

Apparently, this behaviour was introduced with 9670513 and could explain some of the issues described in #1666 and https://github.com/oauth2-proxy/oauth2-proxy/issues/1715#issuecomment-1367957338.

## Possible Solution

It should either be possible to skip extraction of the `preferred_username` claim via configuration or to disable the profile URL request altogether (setting `--profile-url` to `""` does not work because the URL is discovered automatically).

## Your Environment

- Microsoft ADFS server (set up to be used as an Open ID provider)
- Version of oauth2-proxy used: 7.3.0, 7.5.1

**Comment by itay-grudev** [comment]
We've also encountered this on `7.5.1` with alpha configuration. It's preventing us from using `oauth2-proxy`.

**Comment by JoelSpeed** [comment]
Yeah I think `preferred_username` shouldn't be required to be found, so if we can't find it, we should not error for that particular case.

There's long been an intention to slim down which claims we extract and make it obvious which are required and which are optional, we should try to accelerate that.

But for now, a bug fix to stop this claim being required would probably be helpful

**Comment by ph4nt0m** [comment]
The issue is still relevant, but unless someone finds time to submit a bug fix, there is nothing we can do at the moment.

**Comment by ph4nt0m** [comment]
This issue is still relevant.

**Comment by pettermk** [comment]
I've been browsing several variants of this issue which seem to have the same root cause, and in v7.6.0 the simplest fix is to apply
`OAUTH2_PROXY_SKIP_CLAIMS_FROM_PROFILE_URL=true`
Context: https://github.com/oauth2-proxy/oauth2-proxy/pull/2329
thanks to @nilsgstrabo for fixing!

**Comment by ph4nt0m** [comment]
Thank you @nilsgstrabo for implementing and @pettermk for pointing out the new parameter. In my case, it fixes the issue.
