### ISSUE TITLE
AJAX request return 302 when cookie expire

### ISSUE THREAD

**Issue by redboxstudio** [oauth2-proxy/oauth2-proxy#2292]
I see a lot of questions about this; an additional api-routes check was even introduced to ajax.
But judging by the code or the checks I performed, these checks are never performed
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/08408ccf-c580-4b77-9f35-25bc6d0c229d)
Requests always go through the AuthOnly branch and never go to Proxy
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/65087f3c-fffc-4a08-90c6-439dafaae0a3)
When a keycloak session expires or a cookie expires, all requests fail in a method error getAuthenticatedSession
but I would like the requests to fall into the Proxy branch so that the Accept aplication/json header works for ajax or api-routes checks, to which I added a regex for processing my api requests
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/c3bd089c-bd13-4d96-b8ae-adf6dbf18dc2)
And so when the session expires, my application stops working and receives a 302 response in spa ajax mode until you forcefully refresh the page. from the tests I see that the initial login happens through receiving a 401 response and going to keycloak for a token, so I think if api-routers or isAjax worked I would get a 401 instead of a 302 and the magic of primary end-to-end authentication would happen without having to refresh the page

**Comment by redboxstudio** [comment]
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/76a82efe-7f79-45e6-a1a5-e7b54cfac2a5)

**Comment by redboxstudio** [comment]
ok, I figured out from the code that in order to submit to the desired branch you need to configure the upstream, but after configuration everything goes smoothly

**Comment by redboxstudio** [comment]
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/716c5694-6cef-4b52-8fd7-770651c8d1db)
I adjusted the tests to suit my case and they were successful, one question remains, why in real conditions requests never fall into the proxy branch?

**Comment by redboxstudio** [comment]
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/dad25f0c-edda-4fd2-8c36-a20f539c6433)
I use nginx and the prefix is ​​always oauth2/auth, so it turns out I can never connect to the proxy?
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/df036d01-30db-4cef-b2d1-6601abc88bd2)

**Comment by tuunit** [comment]
Hi @redboxstudio,

thank you for all the details and doing a first code analysis as well. I will try to have a deeper look at this at some point. Unfortunately, it might take a while until I come around to this.

**Comment by redboxstudio** [comment]
> Hi @redboxstudio,
> 
> thank you for all the details and doing a first code analysis as well. I will try to have a deeper look at this. Unfortunately, it might take a while until I have time to do so.

I moved on and seem to have lost the thread of the solution. During the initial pass or refreshing the page, the browser sends the correct requests
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/b692ced8-0df3-4a8f-8b4c-c22957af680a)
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/9c126a0e-577a-4cfb-90f7-7a7db9c39483)
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/7aa6ac37-65b6-4651-a11e-be0e5089b6ee)
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/f4f249e4-eb27-44b4-8978-8a242dbb59ae)
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/f76106ec-18f0-420a-8cdf-bd74ad05a2c8)

when the session expires, the ajax request receives 302 and the browser generates a preflight options request instead of get, and the negotiate header with the Kerberos ticket is not attached to it
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/65025d6e-42e1-472b-9171-3aedf5ef1e06)
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/56bf9eed-5acf-48ee-8de9-09c372a13378)

I can’t understand why in one case these are GET requests 302 401 302 302 200 and in the other case these are 302 200 preflight OPTIONS method

**Comment by redboxstudio** [comment]
I thought it might help me to set Skip_auth_preflight=true, but the OPTIONS request does not go through oauth2-proxy, but goes to keycloak

**Comment by redboxstudio** [comment]
This is what I found on the Internet. this is the same thing that happens to me
https://stackoverflow.com/questions/55285168/keycloak-returns-http-204-on-http-options-request
possible implementation will help me if it is 307 instead of 302?
https://github.com/oauth2-proxy/oauth2-proxy/issues/1289

**Comment by redboxstudio** [comment]
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/e7a0225a-dcef-47b6-a4c6-e0cb535a2a3b)
and so I tested 307 308 301
but the browser always does options

**Comment by redboxstudio** [comment]
ok I found the reason why Ajax requests stopped at OPTIONS requests, I was using a very old version of firefox
![Screenshot from 2023-11-09 09-16-23](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/16ca8eab-bbf0-47b0-b353-0f45f3f82704)
Now my requests go to keycloak, but it does not authorize them, citing cookies, and this is what I see with Ajax requests: there is no request cookie, and a newly created one comes in response
![Screenshot from 2023-11-09 08-50-13](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/06e01d88-a02b-41d9-b22e-d34434280813)

**Comment by redboxstudio** [comment]
> ![image](https://user-images.githubusercontent.com/7893253/281320823-d57b130e-a113-46cf-85b0-6782f4d83225.png)
> 
> and so I tested 307 308 301 but the browser always does options
as you can see in oauth2 csrf is hooked and it is there in both cases, but who hooks a cookie to a request to keycloak?

**Comment by redboxstudio** [comment]
ok I fixed it, it was a Cors problem. I had to move keycloak from my domain to the application domain under subpath.
use it http-relative-path=/keycloak   and  my app.domain.local with keycloak location  app.domain.local/keycloak
but now I received a new error: a method in which authentication was required was a post, after all the manipulation and exit from the callback, my method is re-sent as a get, as I understand the callback processes oauth2-proxy, how can I fix this?

**Comment by redboxstudio** [comment]
https://github.com/oauth2-proxy/oauth2-proxy/issues/1289
https://github.com/oauth2-proxy/oauth2-proxy/issues/1349
I tried this by replacing 302 with 307 with keycloak and I get 415

**Comment by redboxstudio** [comment]
ok, I wanted to modify the oauth2-proxy code to transmit the original request type in the headers of the original request being transmitted, but I encountered a problem that when using nginx and the reverse proxy mode, auth_request is used, which already comes with the GET type in /oauth2/auth gets 401 and goes GET in sign_in. From this it follows that you either need to find out how to save the request type with auth_request or catch the original type on nginx and try to send it as a header to oauth2

**Comment by redboxstudio** [comment]
ok I get the required method type on nginx and pass it proxy_set_header to oauth2-proxy. now I see it in SignIn() req.Headers.Get("my_header")
but it is not passed further to keycloak and back to oauth2/callback and then 302 to the original request, all transitions contain headers installed by the application, but the header I added is overwritten in the first step? where can I look and fix this?

**Comment by redboxstudio** [comment]
and so the transmission of headers is limited by the HTTP specifications, this is really a consequence of the 302 status code, as a solution it is proposed to have a buffer on the server side to save the headers. It seems to me that I found something similar in the oauth2-proxy implementation
// we are authenticated
p.addHeadersForProxying(rw, session)
p.headersChain.Then(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
rw.WriteHeader(http.StatusAccepted)
})).ServeHTTP(rw, req)

but this code works if we are authenticated, and at the same time we see the original header at all stages
this is auth 401 signin 302 keycloak auth 302 calllback 302
Is absolutely every redirect enriched with original headers? where the enrichment occurs and how the request is matched with its headers. I thought this could be in the session, but at the authentication stage we do not have a session until the callback moment until the keylock is released
[tuunit](https://github.com/tuunit)
[JoelSpeed](https://github.com/JoelSpeed) How its works?

**Comment by redboxstudio** [comment]
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/272eb1c8-f073-409a-8b6c-a017fdeea8f9)
and so I studied a little code, found these methods, read the article from the code comments and came to the conclusion that the data from the initial request is cached in the browser and then matched with 302 requests automatically, then I need to modify my application so that it sets the required header with the original type request. One question remains: why, on the first pass or after re-authentication, the request types are set to correct, but the request for which re-authentication was required loses its type?
I think this can be raised as a separate question as a bug?
