### ISSUE TITLE
Need to refresh or renew tokens via CLI

### ISSUE THREAD

**Issue by Taurophylax** [oauth2-proxy/oauth2-proxy#2304]
## Expected Behavior

When a user access an API via CLI, they pass their token via headers (using the --skip-jwt-bearer-tokens) this works as long as the token has not expired. Ideally, we would like it to refresh or pull a new token without authenticating via the web browser. 

## Current Behavior

Currently, the user must obtain their token via the web browser then paste it into their API script so that it sends the token in the header of the API call. When the token expires (our policy is about 12 hours) the user must obtain a new token and update their script. 

## Possible Solution

Is it possible to use a refresh token to accomplish this? My understanding is that it's another token with a longer expiration time and can be used to renew the "regular" token if expired? 

## Context

Removes some unnecessary work from people that want to use the API without having to get a new token from the website. 

## Your Environment

Flask web app sits on a K8s container along side OAuth2 Proxy that intercepts the traffic and authenticates with our Key Cloak server.
--skip-jwt-bearer-tokens enabled so that we can pass the token in the header of the API request. 

- Version used:
7.5.1

**Comment by ianroberts** [comment]
This isn't really a job for oauth2-proxy, rather the CLI app needs to implement the refresh algorithm itself, cacheing the latest access and refresh tokens on disk somewhere.  The flow would be something like:

- try to load saved tokens
- if no saved tokens at all, or if current access _and refresh_ tokens have expired
  - start auth flow with `offline_access` scope (device code flow should work anywhere, alternatively run a localhost web server and use that as the redirect for a normal auth code flow in a local browser)
  - save resulting tokens
- else if access token is still valid
  - use that
- else if refresh token is still valid
  - use the current refresh token to obtain a new access/refresh token pair and save those to the cache

**Comment by Taurophylax** [comment]
> This isn't really a job for oauth2-proxy, rather the CLI app needs to implement the refresh algorithm itself, cacheing the latest access and refresh tokens on disk somewhere. The flow would be something like:
> 
> * try to load saved tokens
> * if no saved tokens at all, or if current access _and refresh_ tokens have expired
>   
>   * start auth flow with `offline_access` scope (device code flow should work anywhere, alternatively run a localhost web server and use that as the redirect for a normal auth code flow in a local browser)
>   * save resulting tokens
> * else if access token is still valid
>   
>   * use that
> * else if refresh token is still valid
>   
>   * use the current refresh token to obtain a new access/refresh token pair and save those to the cache
> 
> [Here's an example](https://gitlab.com/european-language-grid/platform/python-client/-/blob/master/elg/authentication.py?ref_type=heads) of how we did this using the "out-of-band" auth code flow in a project I was involved in a few years back (at that time the version of Keycloak we were using didn't support the device code flow, but that's what we would have used if we were doing the same thing now).

That is exactly what I needed. I was misunderstanding the role of oauth in this and that clears things up. Thank you!

**Comment by ianroberts** [comment]
There may be a ready-made solution you can leverage here, for example there are tools like https://github.com/int128/kubelogin that are designed to work as plugins to `kubectl` against Kubernetes clusters that use JWT authentication.  While this is _designed_ to be called by `kubectl` there's no reason why you can't invoke it yourself with the right options - it will perform the sequence of steps I detailed above (use a cached token if it is valid, refresh if it can, prompt for authentication if it can't) and print the eventual bearer token on its stdout in a JSON envelope that you could parse and use in your own tool.
