### ISSUE TITLE
[QUESTION] Inconsistency between Command-Line Flags and Environment Variables: Intended Design?

### ISSUE THREAD

**Issue by Hyuga-Tsukui** [oauth2-proxy/oauth2-proxy#2306]
I've been working with oauth2-proxy and noticed an inconsistency between the command-line flags and their corresponding environment variables. This discrepancy has made it challenging to determine the correct environment variable based on the documentation, often leading me to delve into the source code to decipher the right variable.

For example, the `--whitelist-domain` flag corresponds to the `OAUTH2_PROXY_WHITELIST_DOMAINS` environment variable. While there is documentation on the prefix, **it wasn't immediately clear that the environment variable would be in the plural form.** I had to resort to reading the code to understand this.

**Is this discrepancy an intended design decision?**

From my perspective, it would be beneficial to have consistency between these, though I'm unsure about the broader implications of such a change. I get the feeling that many oauth2-proxy users might be primarily using flags, but I wonder about the general consensus on this matter.

It would be great to get some clarity on this and perhaps consider aligning the two for a more intuitive user experience.

**Comment by tuunit** [comment]
Hi @Hyuga-Tsukui,

sorry for the unfortunate situation. Command line flags are going to become deprecated and we are working on migrating all options to the new structured config implementation for V8 of oauth2-proxy. As part of this migration we are planning to do a complete overhaul of the documentation and all flags and environment variables available.

https://github.com/oauth2-proxy/oauth2-proxy/issues/532

**Comment by Hyuga-Tsukui** [comment]
@tuunit 

Thank you for the update! I'm looking forward to V8.
