### ISSUE TITLE
Documentation for skip-auth-routes is missing a letter

### ISSUE THREAD

**Issue by horihel** [oauth2-proxy/oauth2-proxy#2310]
## Expected Behavior

documentation should have the option "--skip-auth-routes"

## Current Behavior

documentation has the option "--skip-auth-route" - resulting in an "invalid key" error.

## Possible Solution

add an _s_

## Context

this took us quite a while to figure out until we stumbled across #1154 which already mentions it.

- Version used:
7.5.1

**Comment by ianroberts** [comment]
The _command line flag_ is `--skip-auth-route` (singular), the _config file option_ is `skip_auth_routes` (plural).  Most other array-valued options follow the same pattern, singular for the command line, plural for the config file:

> Every command line argument can be specified in a config file by replacing hyphens (-) with underscores (_). If the argument can be specified multiple times, the config option should be plural (trailing s). [docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#config-file)

**Comment by horihel** [comment]
looks like at least 4 eyes over here missed that part... I'm sorry. I'll try and read more thoroughly in the future.
