### ISSUE TITLE
If access denied (403 forbidden) due to restricting login to users with specific roles, user stuck in 403 page

### ISSUE THREAD

**Issue by dasvh** [oauth2-proxy/oauth2-proxy#2313]
User successfully authenticates with the `keycloak-idc` identity provider but is not authorized for a lack of assigned roles in keycloak and is redirected to the `/oauth2/callback` URL and greeted with:

> **403 Forbidden**
> You do not have permission to access this resource. 

There is no recourse from this point on, the user is stuck on this `403 Forbidden` page and has no option to go **Back** or **Sign in** since the user is already authenticated. 

## Expected Behavior
Unauthorized user is authenticated by the identity provider but redirected to a `403 Forbidden` site.
Has option to return to the login page and login as a different user.

## Current Behavior
Unauthorized user is authenticated by the identity provider but redirected to a `403 Forbidden` site.
Has _no option_ to leave the page and is stuck for the duration of session or until the cookie is deleted.

## Possible Solution
An option to either:
* Initiate a sign out/termination of the session if the user is not authorized based on the user's membership in Keycloak `groups`, `realm roles`, and `client roles`
* Destroy the cookie of an unauthorized user by redirecting to the provider logout URL

via the `Go back` or `Sign in` button.

## Steps to Reproduce (for bugs)

1.  Create `testuser` user in keycloak
2. Assign no roles / clients / groups to the `testuser`
3. Login with the `testuser`

## Context

User may have access to other domains in the scope of the identity provider but not to this specific domain. Since we are using SSO, we would prefer to restrict access by not authorizing an user instead of limiting the access in the upstream URL.

This issue is not new either: https://github.com/oauth2-proxy/oauth2-proxy/issues/885

## Your Environment
```
KEYCLOAK_VERSION="21.1.2"
sso session idle = 30 minutes
access token lifespan = 5 minutes
---
reverse_proxy = true
skip_provider_button = true
real_client_ip_header = "X-Forwarded-For"
pass_authorization_header = false
ssl_insecure_skip_verify = true
user_id_claim = "sub"
cookie_refresh = "1m"
---
--provider=keycloak-oidc
--allowed-role=admin
--client-id=example-client
--ssl-insecure-skip-verify=false
--cookie-name=oauth2_proxy_cookie
--cookie-secure=true
--cookie-httponly=true
--cookie-refresh=1m
--user-id-claim=sub
--scope=openid
--skip-oidc-discovery=true
--oidc-issuer-url=https://myissuerurl.com/auth/realms/testrealm
--login-url=https://myissuerurl.com/auth/realms/testrealm/protocol/openid-connect/auth
--oidc-jwks-url=https://myissuerurl.com/auth/realms/testrealm/protocol/openid-connect/certs
--redeem-url=https://myissuerurl.com/auth/realms/testrealm/protocol/openid-connect/token
--redirect-url=https://myissuerurl.com/oauth2/callback
--whitelist-domain=*.myissuerurl.com
--upstream=http://localhost:8094
--skip-jwt-bearer-tokens=true
--pass-access-token=true
--skip-auth-route=GET=^\/health\/.*
```

- Version used: `7.5.1`

**Comment by dasvh** [comment]
@tuunit is there anything I could do to help this move forward? I would love to use the `--allowed-role` option to handle authorization at the oauth2-proxy level but with its current implementation, a user with an insufficient role is stuck and has no option to logout other than deleting the cookies. That isn't really a suitable workaround for non-technical users.

Please let me know how I can help.

**Comment by tuunit** [comment]
Hi @dasvh,

I wasn't aware that this bug exists. Unfortunately I wasn't able to work on the project for the past 1-2 months and I'll have to do some catching up on open PRs and refactorings before circeling back to this bug. If you have the time, feel free to try and dig into the code yourself :)

**Comment by tuunit** [comment]
Hi @dasvh,

as dicussed on slack. My suggestion to get started on this topic:

Have a look at `oauthproxy.go`:

https://github.com/oauth2-proxy/oauth2-proxy/blob/36f8dbcbccf254dbd7000c576c29a883ecf89cb0/oauthproxy.go#L987-L990

`authOnlyAuthorize(...)` is run if the user is authenticated (logged in) and checks for the authorization (access rights through either groups, emails or email domains). In case the authorization fails, we will have to call the backend logout logic.

The following PR essentially already implemented the provider specific extend-ability Nick was talking about in #885  
https://github.com/oauth2-proxy/oauth2-proxy/pull/1876/files

**Comment by timpatt** [comment]
Pretty sure this is still a valid issue...

**Comment by swinkelp1** [comment]
Indeed, seeing the issue as well!

**Comment by revolunet** [comment]
this should be reopened as the bug is still present

**Comment by revolunet** [comment]
I found a workaround which work in my case : add a "logout" link to the footer that allow HTML

example
```
OAUTH2_PROXY_FOOTER=<a href="/oauth2/sign_out?rd=https%3A%2F%2Fidp_host%2Fapi%2Fv2%2Fsession%2Fend%3Fpost_logout_redirect_uri%3Dhttps%253A%252F%252Fmyapp_host/oauth2/sign_out">Logout</a>
```
