### ISSUE TITLE
Keycloak and missing or bad scope (error 403/500)

### ISSUE THREAD

**Issue by jcz1** [oauth2-proxy/oauth2-proxy#2315]
Hello.

With my keycloak setup, i had to set OAUTH2_PROXY_SCOPE: "openid". Without that there was an error right on first client connection on oauth2-proxy:

403 Forbidden
Login Failed: The upstream identity provider returned an error: invalid_scope 

With OAUTH2_PROXY_SCOPE: "email" i was successfully redirected to idP (Keycloak), but after login there was another error on auth2-proxy:

500 Internal Server Error

and in container logs:

[oauthproxy.go:834] Error redeeming code during OAuth2 callback: token response did not contain an id_token

So i think where is missing scope ("openid") in docs for keycloak-oidc or bad default value (for keycloak-oidc).

My docker compose cfg:

    environment:
      OAUTH2_PROXY_CLIENT_ID: "..."
      OAUTH2_PROXY_CLIENT_SECRET: "..."
      OAUTH2_PROXY_COOKIE_SECRET: "..."
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_UPSTREAMS: "http://web"
      OAUTH2_PROXY_SCOPE: "openid"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://id.domain.com/realms/some_realm"
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: "S256"

Image detail:

ID 	sha256:2ab8a2cd16911d95f1683e9187cb9e0aed47eed589c695786e14c067e5c7542f
Size 	34.6 MB
Created 	2023-09-22 15:50:13
Build 	Docker on linux, amd64

From container console:

~ $ /bin/oauth2-proxy --version
oauth2-proxy v7.5.1 (built with go1.19.10)

**Comment by jcz1** [comment]
Check https://github.com/oauth2-proxy/oauth2-proxy/issues/2222. Is fix really in 7.5.1?
I have this image: quay.io/oauth2-proxy/oauth2-proxy:latest but there is different sha256 on quay.io (?)

**Comment by tuunit** [comment]
Were you able to fix your problem?

The default scope should be "openid email profile"
