### ISSUE TITLE
Rest api access via Oauth2Proxy

### ISSUE THREAD

**Issue by umershaekoor** [oauth2-proxy/oauth2-proxy#2319]
Im trying to access a rest api via the oauth2proxy by settting the `skip_jwt_bearer_tokens ` flag in the config file. But and error occurs.

## Expected Behavior

The error doesn't occur and access is provided to the rest api

## Current Behavior
The id token provided in the bearer token gives the error: 

`[jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, not implemented`

## Steps to Reproduce (for bugs)

Cant reproduce due to specific environment. Also should be irrelevant. 

## Context

Same as summary

## Your Environment and steps undertaken
1. A simple rest API. 
2. ID Token (this is the token that is in the x-forwarded-access-token header thats forwarded upstream via the oauth2proxy) generated from keycloak as provider first via disabling the `skip_jwt_bearer_tokens` flag.
3. After generating an id token, use it as a bearer token for the rest api request.
4. Result in error.

- Version used:
7.4

**Comment by umershaekoor** [comment]
Please delete. Problem has been fixed. It was a problem with the aud extra jwt issuers flag, needed to add an aud entry from the tokens as a value to the issuer property in the string.

**Comment by zoriax** [comment]
Hi @umershaekoor ,

I'm facing the same issue, could you please elaborate how you solve this problem a bit more ? 

Thanks
