### ISSUE TITLE
Linkedin is only working with oidc provider

### ISSUE THREAD

**Issue by selamanse** [oauth2-proxy/oauth2-proxy#2324]
As of the current developer experience, Linkedin is providing only access via a "Product" that they call "Sign In with LinkedIn using OpenID Connect"

The current linkedin provider implementation within oauth2-proxy fails with this new api baseline because:

- scope is different (may be set under configuration but...)
- api access is restricted to /v2/userinfo only
- some other "semicolon" semantics are not resolved when code challenge is done

I can cleanly connect with the oidc provider implementation against linkedin but:

- I need to set `insecure_oidc_skip_issuer_verification = true` because
- linked ins discovery address differs from the issuer value ("https://www.linkedin.com/oauth" vs. "https://www.linkedin.com")

## Expected Behavior

- linkedin provider should use oidc logics but maybe as in the current impl the endpoint for discovery is default (I don't know if that makes sense
- linkedin provider config docs are changed to oidc config with the insecure settings mentioned above.... or....
- discard of linkedin provider and just keep a clean docs about how to configure linkedin

## Current Behavior

- linkedin provider does not work against current linkedin app (oidc)
- oidc only works with insecure settings
- minimal settings that work for me:

#### oauth2_proxy.cfg
```properties
    provider = "oidc"
    oidc_issuer_url = "https://www.linkedin.com/oauth"
    insecure_oidc_skip_issuer_verification = true
```

## Possible Solution

see Expected Behaviour... I started looking into improvements [here](https://github.com/selamanse/oauth2-proxy/tree/linkedin_oidc) but found out later that oidc provider just works fine ... so my suggestion would be a clean documentation, removing the linkedin provider (or wrapping oidc in some sort) and discarding the old method which isn't supported anymore. I could put that into my branch shortly if of interest.

## Steps to Reproduce (for bugs)

- minimal settings that work for me:

#### oauth2_proxy.cfg
```properties
    provider = "oidc"
    oidc_issuer_url = "https://www.linkedin.com/oauth"
    insecure_oidc_skip_issuer_verification = true
```

- minimal settings with linkedin provider that do not work:

#### oauth2_proxy.cfg
```properties
    provider = "linkedin"
```

## Your Environment

- Version used: v7.5.1

**Comment by tuunit** [comment]
Hi @selamanse,

if they truly is no need for the customized linkedin email fetching in `providers > linkedin.go > GetEmailAddress`. I would be fine with removing the customized provider. Feel free to open a PR for this change.

**Comment by JoelSpeed** [comment]
I think first lets start with getting the docs up to date, and then we can start deprecating the linkedin provider if we think it's truly not needed. Perhaps we should retitle this issue to deprecating the linkedin provider to see if anyone spots it and has counter arguments to that suggestion?

**Comment by selamanse** [comment]
re-activate

**Comment by lswartsenburg** [comment]
@selamanse I created this PR to add support for linkedin openid login:

https://github.com/strapi/strapi/pull/19622
