### ISSUE TITLE
Releases sha256sum files

### ISSUE THREAD

**Issue by mgstoyanov** [oauth2-proxy/oauth2-proxy#2332]
The sha256sum files in the Releases page contain sha256 values for the oauth2-proxy executable and not the archive. 

## Expected Behavior

I would expect the sha256sum files to have the sha256 sums of the archive, so I don't have to extract the archive and then verify if the extracted file(s) match the checksum(s), but verify that the archive itself is correct. 

## Current Behavior

The sha256sum files have the checksum of the oauth2-proxy executable itself, eg:

```
29265b2c3b1708fa3b3c2f7d1e3ede764cbd0b7f489cbfe14b132c4bba1e0744  oauth2-proxy-v7.5.1.linux-arm64/oauth2-proxy
```

## Possible Solution

Either provide checksum files of the archive or don't archive the executables at all and provide the current checksum files.

## Steps to Reproduce (for bugs)

1.  Download the checksum [file](https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v7.5.1/oauth2-proxy-v7.5.1.linux-arm64-sha256sum.txt) and look inside. 
2.  Calculate the checksum of the [archive](https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v7.5.1/oauth2-proxy-v7.5.1.linux-arm64.tar.gz) 

## Context

I am trying to save myself the extra step of extracting a possibly corrupt archive file.

## Your Environment

- Version used: any

**Comment by kvanzuijlen** [comment]
Thx, I put in a PR. As you can see in the PR we might opt to add additional files rather than replacing them.
