### ISSUE TITLE
Question: passing X-Forwarded-Email from upstream to service

### ISSUE THREAD

**Issue by Fran-Rg** [oauth2-proxy/oauth2-proxy#2337]
## Expected Behavior

Not a bug but a question.
I'm mostly following this: https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
Configuring 2 ingress with one that requires authentication by passing it to the oauth2-proxy.

My oauth2-proxy config is:
```
provider = "oidc"
redirect_url = "REDACTED"
whitelist_domains = ["REDACTED"]
oidc_issuer_url = "REDACTED"
email_domains = [ "*" ]
upstreams = [ "file:///dev/null" ]
skip_provider_button =  true
pass_access_token = false
pass_basic_auth = true
pass_user_headers = true
proxy_websockets = true
```
with env vars for client-id/secret/cookie.

This works but I'm looking to pass back some headers from the --pass-basic-auth option, mostly: `X-Forwarded-Email`

I've tried the following (using k8s nginx ingress):
```
      "nginx.ingress.kubernetes.io/auth-response-headers" : "X-Forwarded-User, X-Forwarded-Email, X-Forwarded-Preferred-Username"
      "nginx.ingress.kubernetes.io/auth-url"    : "https://$host/oauth2/auth"
      "nginx.ingress.kubernetes.io/auth-signin" : "https://$host/oauth2/start?rd=$escaped_request_uri"
      "nginx.ingress.kubernetes.io/configuration-snippet" : """
    proxy_set_header X-User $upstream_http_x_forwarded_user;
    proxy_set_header X-Role "user";
    proxy_set_header X-First-name "FIRST";
    proxy_set_header X-Last-name "LAST";
"""
```

I would like the header "X-User" to be set to the value of "X-Forwarded-Email". At the moment it doesn't get set.

## Current Behavior

The headers being set are:
```
X-Role: user
X-First-name: FIRST
X-Last-name: LAST
```
But not `X-User`

## Context

I'm trying to integrate with: https://github.com/dbeaver/cloudbeaver/wiki/Reverse-proxy-header-authentication

## Your Environment

- Version used: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1

**Comment by Fran-Rg** [comment]
Potentially a dup with https://github.com/oauth2-proxy/oauth2-proxy/issues/1769

**Comment by Robin-Sch** [comment]
I don't know why, but for my the header `Gap-Auth` contains the email, and not X-Forwarded-User

**Comment by RytisLT** [comment]
@Robin-Sch you're missing --set-xauthrequest=true

**Comment by Robin-Sch** [comment]
I've set the environment variable `OAUTH_PROXY_SET_XAUTHREQUEST=true`. So it should work right? Or can't I set this using this environment variable?

**Comment by JoelSpeed** [comment]
If you hit the `/oauth2/auth` endpoint directly, what headers do you see being set? You are correct, you should be able to use the env var as you've shown in the last comment. You should also check the session creation log, to make sure there is actually data to populate the header

**Comment by Robin-Sch** [comment]
There is no X-Forwarded-User or whatever, only the following:
`gap-auth`, `x-auth-request-email`, `x-auth-request-groups`, `x-auth-request-preferred-username`, `x-auth-request-user` (which is a userID?, not username)

**Comment by tuunit** [comment]
Please check the documentation:

https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview

If you search for "X-Forwarded-User" you will find you will have to use the `--pass-user-headers" flag or "PASS_USER_HEADERS" env variable.
