### ISSUE TITLE
Google OAuth2 support for Cloud Identity group authorization

### ISSUE THREAD

**Issue by Roymprog** [oauth2-proxy/oauth2-proxy#2338]
## Expected Behavior

I'd envision Google Oauth working similarly to how [Grafana OAuth2](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/google/) works, based on Cloud Identity groups.  I'd like to implement OAuth2 using Cloud Identity Groups, this requires getting user profile data from https://www.googleapis.com/auth/cloud-identity.groups.readonly. 

## Current Behavior

Scopes are [hardcoded](https://github.com/oauth2-proxy/oauth2-proxy/blob/464f3bcf53fcaa281adb2eca260a730ed38f680d/providers/google.go#L257C21-L257C21) to `admin.AdminDirectoryUserReadonlyScope` and `admin.AdminDirectoryGroupReadonlyScope`.

## Possible Solution

Allow the Google provider to look at the `scopes` from configuration or add the option to define `google-scopes`.

## Steps to Reproduce (for bugs)

N/A

## Context

The current Google OAuth2 implementation is based on the Admin SDK. This is based on the Google Workspace, which is not supported in my organization.

## Your Environment

- Version used: 7.5.1

**Comment by Roymprog** [comment]
reactivate

**Comment by Roymprog** [comment]
Can this issue be re-opened?

**Comment by JoelSpeed** [comment]
How would this co-exist with the existing google provider implementation? Have you tried using the generic OIDC provider implementation at all?
