### ISSUE TITLE
What does upstream=file:///dev/null achieve

### ISSUE THREAD

**Issue by nbx3** [oauth2-proxy/oauth2-proxy#2340]
What does using the configuration upstream=file:///dev/null do, its used in lots of samples but its not explained in the docs.

## Expected Behavior

Documentation should say what behaviour is expected from this configuration.

## Current Behavior

Unsure

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

N/A

## Context

Unable to decide on configuration to use

## Your Environment

N/A

- Version used:

v7.5.1

**Comment by kvanzuijlen** [comment]
@nbx3 Can you please link where those samples are, I can only find it here in one of the contrib files: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/kubernetes/values.yaml#L57.

In this case, it sets the upstream to the /dev/null path, which is the null device, which discards all data written to it without responding in a failure. This can for example be useful in setups where your ingress (i.e. nginx) can handle auth for you (which is what the nginx annotations in that same file are for). In that case, your oauth2-proxy doesn't function like a proxy (it doesn't have an upstream (=/dev/null)), but more like an authentication server.
