### ISSUE TITLE
Keycloak OIDC provider config fails: invalid keys

### ISSUE THREAD

**Issue by GownerCode** [oauth2-proxy/oauth2-proxy#2341]
## Expected Behavior
The config should load and work correctly.

## Current Behavior
The config fails:
```
 ERROR: failed to load config: error unmarshalling config: 1 error(s) decoding:

* '' has invalid keys: email_domain
```

## Possible Solution
I have no idea.

## Steps to Reproduce (for bugs)
Create config file as shown below (in the context section) and run oauth2-proxy with it.

1. Create config file as shown below (in the context section)
2. Run oauth2-proxy with it

## Context
For context, I will provide my config file:
```
provider = "keycloak-oidc"
client_id = "oauth2-proxy"
email_domain = "*"
client_secret = "my_secret"
oidc_issuer-url = "my_url"
redirect_url = "another_url"
code_challenge-method = "S256"
```
This config was created according to this part of the docs:

Keycloak OIDC Auth Provider
```
    --provider=keycloak-oidc
    --client-id=<your client's id>
    --client-secret=<your client's secret>
    --redirect-url=https://internal.yourcompany.com/oauth2/callback
    --oidc-issuer-url=https://<keycloak host>/realms/<your realm> // For Keycloak versions <17: --oidc-issuer-url=https://<keycloak host>/auth/realms/<your realm>
    --email-domain=<yourcompany.com> // Validate email domain for users, see option documentation
    --allowed-role=<realm role name> // Optional, required realm role
    --allowed-role=<client id>:<client role name> // Optional, required client role
    --allowed-group=</group name> // Optional, requires group client scope
    --code-challenge-method=S256 // PKCE
```

## Your Environment
Ubuntu 22.04.3 LTS

- Version used:
7.5.1

**Comment by kvanzuijlen** [comment]
Hi @GownerCode,

The docs state that 'If the argument can be specified multiple times, the config option should be plural (trailing s).', which is the case for the `--email-domain` parameter. It therefore should be `email_domains`, also see this [example config file](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/oauth2-proxy.cfg.example).

I do agree that this can be easily overlooked, so we'll have to discuss if/how this can be made more obvious.

**Comment by col-panic** [comment]
There seem to be additional issues, where the `oidc` provder behaves different to the `keycloak-oidc` provider, e.g. https://github.com/oauth2-proxy/oauth2-proxy/pull/355#issuecomment-1884896464

I wonder - what is the specific advantage of using the keycloak provider? Should one revert to the generic oicd provider?

**Comment by tuunit** [comment]
@col-panic the difference is that the `keycloak-oidc` provider properly extracts the client roles and the realm access roles

**Comment by tuunit** [comment]
As @kvanzuijlen already mentioned your issue is or was that you tried to use `email_domain` instead of `email_domains`
