### ISSUE TITLE
Documentation is incorrect for 'OAUTH2_PROXY_UPSTREAMS' environment variable

### ISSUE THREAD

**Issue by fr-orionfollett** [oauth2-proxy/oauth2-proxy#2349]
The documentation on this page: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview
Refers to a command line option called '--upstream'
Following the convention, I converted the format to an env variable: OAUTH2_PROXY_UPSTREAM, but this did not apply.

When I change to 'OAUTH2_PROXY_UPSTREAMS' (plural), then the the upstream started working properly.

## Expected Behavior
The docs should specify the correct spelling for the actual command line arg / env variable. The format convention should match between them.

- Version used:
7.5.1 for docs and for image.

**Comment by kvanzuijlen** [comment]
Hi,

Thanks for using oauth2-proxy. Right after the replacing hyphens with underscores, the docs say this;

> If the argument can be specified multiple times, the config option should be plural (trailing s).

So it works as documented.
