### ISSUE TITLE
/ping doesn't return 200 - returns a 404

### ISSUE THREAD

**Issue by MikeHingley22** [oauth2-proxy/oauth2-proxy#2351]
I am attempting to set up Oauth2-proxy and using /ping to confirm - now I will admit that I'm running 7.2 - but it doesn't seem to work in newer versions either

## Expected Behavior
pointing browser to /oauth2/ping returns 200

## Current Behavior
returns 404 page not found

## Your Environment

using Oauth through NGINX redirect proxy

- Version used:
7.2.X & 7.5.X

**Comment by jacksgt** [comment]
Hi @MikeHingley22 ,

we're also using version 7.2 and it works fine.
Please note that the healthcheck endpoint is exposed at `/ping` (not `/oauth2/ping` as mentioned in the OP).
If it still doesn't work when using `/ping`, please share all the config you're using for oauth2-proxy (command-line flags, env vars, config file).

**Comment by tuunit** [comment]
As @jacksgt already mentioned you have to use `/ping`

**Comment by MikeHingley22** [comment]
can confirm that works - not sure why I was trying to access on /oauth2 - I think I had that set up as a subdomain - but have managed to get it to work.
