### ISSUE TITLE
[QUESTION] The ingress-nginx configuration-snippet annotations have already been deprecated, but the oauth2-proxy documentation has not been updated.

### ISSUE THREAD

**Issue by mmmommm** [oauth2-proxy/oauth2-proxy#2368]
The ingress-nginx configuration-snippet annotations is deprecated because [security issue](https://github.com/kubernetes/ingress-nginx/issues/7837).

But oauth2-proxy latest version(v7.5.x) document section [Configuring for use with the Nginx auth_request directive](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#configuring-for-use-with-the-nginx-auth_request-directive) is still use this annotation.

I have now solved this problem by explicitly setting [allow-snippet-annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#allow-snippet-annotations) to true, but this is a temporary measure, not a permanent one. 
If a solution has already been found and it's just that the documentation hasn't been updated, I would appreciate if you could let me know.

I've opened an issue as I couldn't find a similar one. I apologize if there already is one, thank you.

**Comment by tuunit** [comment]
@mmmommm I don't think the snippet is necessary. The official ingress-controller example for using oauth2-proxy doesn't include anything of that sort either. https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

I'll have to do some testing to figure out why this example manipulates the cookie name and set the header manually.

**Comment by mmmommm** [comment]
Thank you for your response.
I would like to try removing it here as well to see if it works without any problem.

**Comment by martinlindner** [comment]
> I'll have to do some testing to figure out why this example manipulates the cookie name and set the header manually.

It looks like this was introduced to work around an issue where Nginx ignores subsequent `Set-Cookie` headers if oauth2-proxy's cookie is split into multiple parts. This is apparently only happening if the cookie is larger than 4KB.

See #29 for details.

It would be interesting to see if recent Nginx versions can handle this without the snippet.

**Comment by andrewconnors** [comment]
Hi, was there any clarity on whether the configuration snippet is required or not? If not, was there a change in nginx or oauth2_proxy to make it obsolete? We've been using the configuration snippet in our ingress' and we'd like to remove it if we don't need it because it's a security issue in multi-tenant clusters

**Comment by mmmommm** [comment]
I forgot to report the follow-up, but my team's cluster worked fine even after removing the configuration-snippet. 

When removing it, I first deleted the configuration-snippet from the ingress and confirmed it was working.
Next, I set allow-snippet-annotation in the configmap to false.

The versions we are using are as follows
- oauth2-proxy v7.5.1
- ingress-nginx controller v1.9.3
