### ISSUE TITLE
Get error responses from API without modification by OAuth2 Proxy

### ISSUE THREAD

**Issue by mfinkoleukeleu** [oauth2-proxy/oauth2-proxy#2369]
## Expected Behavior

Error responses from our API returned to client without modification by OAuth2 Proxy.
Specifically the status text in the response.

## Current Behavior

We have an API for which we are using Tornado. For some endpoints we specified custom error
messages, using the 'reason' in the [tornado.web.HTTPError](https://www.tornadoweb.org/en/stable/web.html#tornado.web.HTTPError)
exception. In the client (frontend) these reasons can be read in the response statusText.
However, the OAuth2 Proxy layer overrides these custom error messages and replaces them with the default error
message for the received status code. For example if we set the response status code to 400, instead of
our custom message in statusText, we are getting the default "Bad request" message.

## Steps to Reproduce (for bugs)

1. Get any API that works with Tornado and uses OAuth2 Proxy (for Azure provider).
2. Create an endpoint that raises the HTTPError with a custom error message (status text) with some error status code, e.g. 400.
3. Send any request to your API (GET or POST, doesn't matter) that should return that error.
4. Response statusText contains default (e.g. "Bad request") and not the custom message.

## Your Environment

API that uses Tornado and OAuth2 Proxy (with Azure provider).

**Comment by tuunit** [comment]
If you want custom error handling or proxying of this behaviour you will most likely have to use a different setup:

nginx -> auth -> oauth-proxy
|
v
your-application

This way you can control exactly what you want nginx to proxy back to your client
