### ISSUE TITLE
Feature request: opentracing

### ISSUE THREAD

**Issue by haf** [oauth2-proxy/oauth2-proxy#237]
It would be nice if oauth2_proxy tied into tracing one has configured for the other deployments, e.g. by specifying a jaeger/zipkin agent/collector hostname/port. Example: https://www.ory.sh/docs/hydra/debugging#distributed-tracing

**Comment by agolomoodysaada** [comment]
FYI... OpenTracing has now been merged with https://github.com/open-telemetry

**Comment by haf** [comment]
@agolomoodysaada I didn't know. Thanks! Good to know. Strange they haven't also updated their readme's for the client libs...

**Comment by haf** [comment]
.

**Comment by haf** [comment]
.

**Comment by jankatins** [comment]
.

**Comment by jankatins** [comment]
Yes, still interested

**Comment by JoelSpeed** [comment]
This came up in discussion recently, we should definitely be adding this at some point, not sure what the best way to do this is though

**Comment by lathspell** [comment]
Can this be reopened? As "first in the request chain", oauth2-proxy would be the best place to initially generate a tracing id.
It would even be ok to just generate it, if it is not present and do no further handling like creating spans etc.

It seems to me that there is even a (transitive) dependency to opentracing already present (I'm no go expert but that's how I interpret this: 
```
    $ go mod graph | grep opentracing                      
    github.com/go-kit/kit@v0.10.0 github.com/opentracing/opentracing-go@v1.1.0
    github.com/lightstep/lightstep-tracer-go@v0.18.1 github.com/opentracing/opentracing-go@v1.0.2
    github.com/openzipkin-contrib/zipkin-go-opentracing@v0.4.5 github.com/opentracing/opentracing-go@v1.1.0
```
