### ISSUE TITLE
`Dockerfile`: `/etc/nsswitch.conf` workaround no longer necessary

### ISSUE THREAD

**Issue by polarathene** [oauth2-proxy/oauth2-proxy#2370]
The following was [added in Feb 2020 as a workaround fix](https://github.com/oauth2-proxy/oauth2-proxy/pull/400) for Go DNS logic:

https://github.com/oauth2-proxy/oauth2-proxy/blob/52ad31752d0d0b38673d419e56ddfc4cb2f56857/Dockerfile#L48

https://github.com/oauth2-proxy/oauth2-proxy/blob/52ad31752d0d0b38673d419e56ddfc4cb2f56857/nsswitch.conf#L1

---

That concern was [resolved with Go 1.16](https://github.com/golang/go/commit/c80022204e8fc36ec487888d471de27a5ea47e17) (_released in Feb 2021_).

If you need more info / proof that it's no longer necessary, [see this comment](https://github.com/ory/hydra/issues/3685#issuecomment-1871576282).

**Comment by tuunit** [comment]
Thanks for bringing this up :)

**Comment by polarathene** [comment]
Closing as resolved in https://github.com/oauth2-proxy/oauth2-proxy/pull/2371
