### ISSUE TITLE
Cookie-secret is mandatory with redis session storage

### ISSUE THREAD

**Issue by albgus** [oauth2-proxy/oauth2-proxy#2374]
## Expected Behavior
The documentation states: `It is mandatory to set a cookie-secret which will ensure data is encrypted within the cookie data.` under the Cookie Storage header at: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/session_storage/

This makes it sounds like the Cookie-secret is only mandatory when using the cookie storage engine, and is not used at all when using the Redis storage engine.

## Current Behavior
Starting the oauth2-proxy 

## Possible Solution
If the redis session storage does not use the cookie-secret to encrypt data it should not be a mandatory parameter when not using the cookie session store.

Otherwise the documentation should be updated to make it clear that the cookie-secret is indeed mandatory for the Redis session storage as well.

## Steps to Reproduce (for bugs)
Start oauth2-proxy with `--session-store-type=redis` and without `--cookie-secret`

## Your Environment
- Version used: v7.5.1

**Comment by vnea** [comment]
Hello,

I have the same issue, is it possible to give an explanation please?

Is the `cookie-secret` really use when using `redis` mode?

**Comment by tuunit** [comment]
Hi @vnea, @albgus,

yes it is mandatory. When using redis you still have a cookie that contains the redis session id. Otherwise how would you identify which browser/user has access to which session. It acts as an intermediate "token"
