### ISSUE TITLE
[Feature]: Home Assistant provider

### ISSUE THREAD

**Issue by domdomegg** [oauth2-proxy/oauth2-proxy#2393]
### Motivation

Many people use oauth2-proxy to secure their home server setups. Home Assistant (HA or HASS) is a frequently used service in these setups that offers a built-in authentication provider.

Some other tools similar to oauth2-proxy, like [vouch-proxy](https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example_homeassistant), support Home Assistant as a provider.

### Possible solution

Implement based on the Home Assistant authentication API: https://developers.home-assistant.io/docs/auth_api/

It largely follows the OAuth2 specification, with a couple extensions.

We could look at the way [others implemented Home Assistant authentication](https://github.com/vouch/vouch-proxy/pull/146/files).

### Provider

new provider

**Comment by LeVraiRoiDHyrule** [comment]
Have you tried this ? https://github.com/BeryJu/hass-auth-header The configuration given is for Authentik but it should work with Oauth2-proxy too, if you change the `username_header:` variable. I can confirm it works well with Authentik.
