### ISSUE TITLE
[Feature]: Warn on unused OAUTH2_PROXY environment variables

### ISSUE THREAD

**Issue by domdomegg** [oauth2-proxy/oauth2-proxy#2394]
### Motivation

If users set environment variables starting OAUTH2_PROXY, but they are not recognised this is probably a configuration error by the user.

It would be helpful in these cases to log a warning, indicating to users this might be the problem.

### Possible solution

One possible version of this would be to error if the environment variable is simply not recongised at all in the possible options.

A smarter version (but maybe overcomplicating it) would be to determine which environment variables are actually read based on the provider. So even if a variable might be valid in some cases, for the users given provider / other settings it doesn't make sense.

Implementing the first version as an initial step would likely be a big benefit to the user experience of setting up oauth2-proxy.

### Provider

None

**Comment by tuunit** [comment]
We use the automatic environment variable detection of viper. 

Readme of Viper:
https://github.com/spf13/viper?tab=readme-ov-file#working-with-environment-variables

Code:
https://github.com/oauth2-proxy/oauth2-proxy/blob/c7185e700514e75d800496fdb7ecd7258ebb0d7d/pkg/apis/options/load.go#L25-L31

As far as I understand, the environment variables are only checked when trying to access the actual values. Maybe the logic can be extended with a validator of some sort. Someone will need to do a little bit of research.
