### ISSUE TITLE
[Support]: Configuring OAuth2-Proxy for Authorization based on roles created in Keycloak

### ISSUE THREAD

**Issue by believerHSP** [oauth2-proxy/oauth2-proxy#2395]
### OAuth2-Proxy Version

v7.5.1

### Provider

keycloak-oidc

### Current Behaviour of your Problem

**What I Expect to happen:** I want to configure authorization in OAuth2-Proxy in such a way that a user with a specific client-role created in Keycloak, would redirect to a upstream server with a specific endpoint. And when a user with different client role authenticated by keycloak comes to OAuth2-proxy it goes to the same upstream server with a different endpoint.

**What happens instead is that:** 
1. I have configure the upstream enpoint as upstreams = [ "http://192.168.122.1:8334/files/himansu/" ].
2. It throughs me a 404 Error i.e. page not found error.
3. The same URL "http://192.168.122.1:8334/files/himansu/" is working fine in my browser.

### Configuration details or additional information

404 , Page not found error.

### Steps To Reproduce

1. Keycloak running in a container.
2. A realm is created.
3. A client is created within this realm.
4. A client role is created within this client.
5. A user is assigned this role.
6. OAuth2 proxy is configured with options to authenticate based on role of a user.

**Comment by tuunit** [comment]
You cannot configure this use case with a single oauth2-proxy. You would need to have a nginx or similar reverse-proxy in-front and different oauth2-proxy configs. In the future it might be possible using the results in PR https://github.com/oauth2-proxy/oauth2-proxy/pull/1923
