### ISSUE TITLE
[Support]: Issue in getting the authorization header in request/response

### ISSUE THREAD

**Issue by winweb123** [oauth2-proxy/oauth2-proxy#2398]
### OAuth2-Proxy Version

latest

### Provider

keycloak

### Current Behaviour of your Problem

We are using keycloak identity provider along with oauth2 proxy and nginx ingress controller.Authentication is successful and token validation is happening successfully but we are not able to get the access token and authorization headers even after setting the pass access token and pass authorization header flags in oauth2 proxy config file.We have also added the authorization in the ingress controller auth response headers annotations.Please let us know how to achieve the same.

### Configuration details or additional information

oauth2 roxy config details

**Comment by winweb123** [comment]
Oauth2 proxy config file
apiVersion: v1
data:
  oauth2-proxy.cfg: |-
    # Provider config
    provider="keycloak"
    provider_display_name="Keycloak"
    login_url="http://keycloak.keycloak:8080/auth/realms/IPNM-Realm/protocol/openid-connect/auth"
    redeem_url="http://keycloak.keycloak:8080/auth/realms/IPNM-Realm/protocol/openid-connect/token"
    validate_url="http://keycloak.keycloak:8080/auth/realms/IPNM-Realm/protocol/openid-connect/userinfo"
    profile_url="http://keycloak.keycloak:8080/auth/realms/IPNM-Realm/protocol/openid-connect/userinfo"
    ssl_insecure_skip_verify=true
    standard_logging=true
    auth_logging=true
    request_logging=true
    set_xauthrequest=true
    #skip_issuer_verification=true
    # Client config
    client_id="ipnm-test-be"
    client_secret="yzNGkJC8Wuhk63K5xNpAgXpEEg7tiGYX"
    cookie_secret="7IC68eY_2qxWv3eFGeX0KD1v9QSqYucSn9KdFRNHkPM="
    #cookie_secure="false"
    redirect_url="http://localhost/oauth2/callback"
    #skip_jwt_bearer_tokens=true
    # Upstream config
    http_address="0.0.0.0:4180"
    upstreams="http://localhost"
    email_domains=["*"]
    oidc_issuer_url="http://keycloak.keycloak:8080/auth/realms/IPNM-Realm"
    cookie_domains=["localhost"]
    scope="openid"
    whitelist_domains=[".localhost:*"]
    pass_authorization_header = true
    pass_access_token = true
    pass_user_headers = true
    set_authorization_header = true
    prefer_email_to_user = true
    skip_auth_strip_headers = false
    #session_store_type="redis"
    #redis_connection_url="redis://10.108.104.57:6379"
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: test

**Comment by winweb123** [comment]
We are checking the developer tools - network tab to get these headers X-Auth-Request-Access-Token , X-Forwarded-User, X-Forwarded-Email and X-Forwarded-Preferred-Username but not able to see them

**Comment by tuunit** [comment]
Hi @winweb123,

I will need to understand how your architecture is designed?

Are you trying one of the following:

1. upstream behind oauth2-proxy
```
user -> oauth2-proxy -> upstream
```

2. upstream behind nginx using oauth2-proxy auth module
```
user
|
v
nginx ----> oauth2-proxy
|
v
upstream
```

3. upstream behind oauth2-proxy using nginx as a reverse-proxy
```
user -> nginx -> oauth2-proxy -> upstream
```

**Comment by tuunit** [comment]
As your upstream you configured localhost with port 80. What is running on port 80?

**Comment by tuunit** [comment]
Furthermore, never ever share your cookie or client secrets.

**Comment by winweb123** [comment]
> Hi @winweb123,
> 
> I will need to understand how your architecture is designed?
> 
> Are you trying one of the following:
> 
> 1. upstream behind oauth2-proxy
> 
> ```
> user -> oauth2-proxy -> upstream
> ```
> 
> 2. upstream behind nginx using oauth2-proxy auth module
> 
> ```
> user
> |
> v
> nginx ----> oauth2-proxy
> |
> v
> upstream
> ```
> 
> 3. upstream behind oauth2-proxy using nginx as a reverse-proxy
> 
> ```
> user -> nginx -> oauth2-proxy -> upstream
> ```

we are using 2nd option

**Comment by winweb123** [comment]
> As your upstream you configured localhost with port 80. What is running on port 80?




Application frontend is running in port 80

**Comment by tuunit** [comment]
Hi @winweb123,

please share your nginx configuration.

The headers will he send to nginx and will need to configure nginx properly to forward the headers to your upstream.

**Comment by tuunit** [comment]
Furthermore, you should not configure an upstream or just a static upstream like `upstream: ["static://202"]`

**Comment by tuunit** [comment]
> We are checking the developer tools - network tab to get these headers X-Auth-Request-Access-Token , X-Forwarded-User, X-Forwarded-Email and X-Forwarded-Preferred-Username but not able to see them

As you are running oauth2-proxy behind nginx you are not supposed to see any of those headers in the browser communication. Unless you specifically configure nginx to do so.

**Comment by tuunit** [comment]
> we are using 2nd option

if you are really trying to build the second option you are using the wrong flags.

instead of using`pass_user_headers`, `pass_access_token`, `pass_authorization_header` you will need to use the following:

| Flag | Type | Description | 
| --- | --- | --- |
| --set-xauthrequest | bool | set X-Auth-Request-User, X-Auth-Request-Groups, X-Auth-Request-Email and X-Auth-Request-Preferred-Username response headers (useful in Nginx auth_request mode). When used with --pass-access-token, X-Auth-Request-Access-Token is added to response headers. |
| --set-authorization-header | bool | set Authorization Bearer response header (useful in Nginx auth_request mode) |
| --set-basic-auth | bool | set HTTP Basic Auth information in response (useful in Nginx auth_request mode) |

**Comment by winweb123** [comment]
Thank you for the inputs . We are able to get the headers .

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I am highly interested into the "second option" as well but I'm trying to do it with Caddy's forward_auth, which should be an equivalent to nginx's auth_request. Did you succeed to make it work ? If yes, could you please share your complete oauth2-proxy configuration ? Thanks in advance for any answer and have a great day

**Comment by TrevorOchmonek** [comment]
I's struggling with this too.
Also got option 2 and trying to pass the token(s) from azure provider to my backend after login so it can access an api with that token.
No matter what options I try, the backend never recieves any auth-headers - only one (huge) cookie header that seems to contain data from the login process but I don't know what that is tbh ;)

**Comment by JoelSpeed** [comment]
When debugging something like this, the first step is to ascertain whether OAuth2 Proxy is returning the correct headers. Jan already mentioned the correct headers in https://github.com/oauth2-proxy/oauth2-proxy/issues/2398#issuecomment-1904871520, once you've done that, I'd suggest hitting `/oauth2/auth`, use dev tools, and check which headers are being replied with.

Given the flags Jan mentioned, assuming your authentication had an ID Token (which you should be able to check from the auth success log), it should return the Authorization header, and then with nginx at least, you can use `auth_request_set` to pass it along to the backend
