### ISSUE TITLE
pass azure AD id_token to the frontend

### ISSUE THREAD

**Issue by vincentzhou2013** [oauth2-proxy/oauth2-proxy#2460]
### Motivation

the Azure id_token has role field for authorization.  the front end need this information to show different contents.  

### Possible solution

pass id_token , just like the way to pass access token. 

### Provider

azure

**Comment by Flo0806** [comment]
This feature will be great for keycloak, too. In keycloak we need the id_token to "disable" the confirm logout screen. But at this time we have no way to get the id_token from oauth2-proxy.
