### ISSUE TITLE
[Bug]:  websocket requestis is responsed with 301 if url contains double slash

### ISSUE THREAD

**Issue by aep** [oauth2-proxy/oauth2-proxy#2461]
### OAuth2-Proxy Version

7.5.1

### Provider

None

### Expected Behaviour

novnc in kubevirt-manager behind oauth2-proxy should work

### Current Behaviour

chrome says websockets are "error 1006", but the underlying issue is something else, so ignore this

### Steps To Reproduce

the real issue is that a double slash after domain will induce a redirect to single slash

```

curl -i 'https://virt-manager.foo//k8s/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/win10/vnc'

HTTP/2 301 
location: /k8s/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/win10/vnc
date: Wed, 24 Jan 2024 20:54:33 GMT
content-length: 0

```

**Comment by JoelSpeed** [comment]
Are you certain that OAuth2 Proxy is the one initiating the redirect here? Are there logs/code you can share that suggests where it might be doing it?

Do you know why there's a double slash in the first place? It seems odd, and in the usual case, correct to sanitise the URL no?
