### ISSUE TITLE
[Support]: CSRF Token Expiration Issue with Keycloak and OAuth2 Proxy

### ISSUE THREAD

**Issue by alperencelik** [oauth2-proxy/oauth2-proxy#2474]
### OAuth2-Proxy Version

7.5.0

### Provider

keycloak

### Current Behaviour of your Problem

I am experiencing an issue with my stack consisting of OAuth2 Proxy, Keycloak, ingress-nginx, and my UI application. The issue arises when a user logs out of the UI application and is redirected to a customized Keycloak login page, where another OAuth2 flow is initiated. If the user remains on the login page for longer than the CSRF token expiration time, a 403 error is encountered due to `Login Failed: Unable to find a valid CSRF token. Please try again.`  I am seeking assistance to reinitiate the OAuth2 flow after landing on the Keycloak login page and pressing the login button on Keycloak.

### Configuration details or additional information

oauth2_proxy.cfg: |
  provider = "oidc"
  provider_display_name = "Keycloak"
  oidc_issuer_url = "https://keycloak-ingress/auth/realms/realmName"
  email_domains = [ "*" ]
  scope = "openid profile email"
  cookie_domains = ".company.com"
  cookie_samesite = "none"
  whitelist_domains = ".company.com"
  pass_authorization_header = true
  pass_access_token = true
  skip_provider_button = true
  pass_user_headers = true
  set_authorization_header = true
  set_xauthrequest = true
  cookie_refresh = "50m"
  cookie_expire = "168h"
  upstreams = [ "file:///dev/null" ]
  redirect_url = "https://login.vedge-dev.axon-networks.com/oauth2/callback"
  auth_logging_format = true
  oidc_groups_claim = "groups"
  skip_auth_routes = ["^/foo", "^/foo", "^/(.*)/foo(/|$)(.*)", "^/API/login/foo"]
  skip_jwt_bearer_tokens = true
  extra_jwt_issuers = "https://keycloak-ingress/auth/realms/realmName=realmName,https://keycloak-ingress/auth/realms/realmName=account,https://keycloak-ingress/auth/realms/realmName=user"
  oidc_jwks_url = "https://keycloak-ingress/auth/realms/realmName/protocol/openid-connect/certs"
  skip_auth_preflight = true
  pass_basic_auth = false
  insecure_oidc_allow_unverified_email = true
  cookie_csrf_expire = "30m"

# UI ingress configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: x-Auth-Request-User, x-Auth-Request-Email,
      x-Auth-Request-Access-Token, X-Auth-Request-Preferred-Username, X-Auth-Request-Groups
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2proxy-ingress/oauth2/start?rd=$scheme://$best_http_host$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth2proxy-ingress/oauth2/auth
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: ingress-name
  namespace: namespace-name
spec:
  rules:
  - host: instance.company.com
    http:
      paths:
      - backend:
          service:
            name: ui-application
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - instance.company.com
    secretName: instance-tls

OAuth2 Proxy version: 7.5.0
Keycloak version: 22.0.7
Ingress-nginx version: v1.8.2

### Steps To Reproduce

1. User accesses the UI application through ingress-nginx, triggering OAuth2 Proxy authentication flow.
2. User is redirected to a custom Keycloak login page for credentials.
3. Upon successful login, the user is redirected back to the UI application.
4. User logs out from the UI application, leading to a redirection to the custom Keycloak login page, and another OAuth2 flow starts.
5. If the user waits on the login page beyond the CSRF token expiration time, a 403 error is encountered with the message `Login Failed: Unable to find a valid CSRF token. Please try again.`

**Comment by alperencelik** [comment]
@eminaktas

**Comment by remkolodder** [comment]
I believe I have something similar:

```
## OAuth2 Proxy Config File
## https://github.com/oauth2-proxy/oauth2-proxy

## <addr>:<port> to listen on for HTTP/HTTPS clients
http_address = ":4180"

## Are we running behind a reverse proxy? Will not accept headers like X-Real-Ip unless this is set.
reverse_proxy = true

## TLS Settings
# tls_cert_file = ""
# tls_key_file = ""

## the OAuth Redirect URL.
# defaults to the "https://" + requested host header + "/oauth2/callback"
# redirect_url = "https://internalapp.yourcompany.com/oauth2/callback"
redirect_url = "https://auth.mydomaing/oauth2/callback"

## the http url(s) of the upstream endpoint. If multiple, routing is based on path
upstreams = [
    "file:///dev/null"
]

## Logging configuration
#logging_filename = ""
logging_max_size = 100
logging_max_age = 7
logging_local_time = true
logging_compress = false
standard_logging = true
standard_logging_format = "[{{.Timestamp}}] [{{.File}}] {{.Message}}"
request_logging = true
request_logging_format = "{{.Client}} - {{.Username}} [{{.Timestamp}}] {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}"
auth_logging = true
auth_logging_format = "{{.Client}} - {{.Username}} [{{.Timestamp}}] [{{.Status}}] {{.Message}}"

pass_basic_auth = true
pass_user_headers = true
pass_host_header = true

email_domains = [
    "mydomain"
]
pass_access_token = true

skip_provider_button = true
code_challenge_method = "S256"
oidc_issuer_url="https://sso.mydomain/realms/<realmname>"
cookie_secret = "<cookie_secret>"
client_secret = "<client_secret>"
client_id = "<client_ID>"
whitelist_domains = [".mydomain]
allowed_groups = ["/<GROUP>"]
provider = "keycloak-oidc"
cookie_domains = [".mydomain"]
cookie_csrf_per_request = true
cookie_csrf_expire = "5m"
cookie_samesite = "lax"
#scope = "email:user"

## SESSION
session_store_type = "redis"
redis_password = "<redis password>"
redis_connection_url = "redis://oauth2-proxy-oauth2_redis-1"
pass_authorization_header = true
#set_xauthrequest = true
set_authorization_header = false
#skip_auth_preflight = true
```

With my Caddyfile:

```
  @my_domain host mydomain
  handle @my_domain {
    reverse_proxy site_container:80
    reverse_proxy /oauth2/* http://oauth2-proxy-oauth2_proxy-1:4180
    forward_auth http://oauth2-proxy-oauth2_proxy-1:4180 {
      uri /oauth2/sign_in?rd=https://mydomain/
      copy_headers Authorization X-Auth-Request-Access-Token
    }
  }
}
```

**Comment by cuberinooo** [comment]
we have the same issue here. 
Happens also if the user resets credential in this flow: Clicks on 'reset password' -> user gives username -> user receives mail -> clicks on 'reset password'-link on the mail -> if he waits longer than 5mins (not 100 sure but maybe longer) and then submits the form keycloak response with 403 csrf invalid token.

**Comment by phongpg284** [comment]
@cuberinooo default CRSF token expire time is 15m for **--cookie-csrf-expire** https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#config-file Maybe you could try extends it

**Comment by Ashish2712** [comment]
I am also facing the same issue, is there any update on this ?
