### ISSUE TITLE
[Bug]: Authorization: Bearer always set, even if --pass-authorization-header	is false

### ISSUE THREAD

**Issue by rwblokzijl** [oauth2-proxy/oauth2-proxy#2478]
### OAuth2-Proxy Version

7.5.1

### Provider

google

### Expected Behaviour

The Authorization: Bearer header should not be set by default since --pass-authorization-header is false by default.

### Current Behaviour

The Authorization: Bearer header is set as explained in steps to reproduce

### Steps To Reproduce

I set up the bitnami docker image with the following settings:
```terraform
resource "docker_container" "oauth2_proxy" {
  name    = "oauth2-proxy"
  image   = docker_image.oauth2_proxy_latest.image_id
  restart = "always"
  networks_advanced {
    name = var.docker_network_name
  }
  volumes {
    container_path = "/config"
    host_path      = "/opt/user-volumes/oauth2-proxy"
  }
  env = [
    "OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:80",
    "OAUTH2_PROXY_REDIRECT_URL=https://${var.hostname}/oauth2/callback",
    "OAUTH2_PROXY_CLIENT_ID=${var.oauth_client_id}",
    "OAUTH2_PROXY_CLIENT_SECRET=${var.oauth_client_secret}",
    "OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE=/config/authenticated_emails.txt",
    "OAUTH2_PROXY_COOKIE_SECRET=${local.cookie_secret}",
    "OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS=true",
    "OAUTH2_PROXY_EXTRA_JWT_ISSUERS=https://accounts.google.com=32555940559.apps.googleusercontent.com", # google sdk issuer
    "OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=false",
    "OAUTH2_PROXY_REVERSE_PROXY=true",
  ]
  command = ["--upstream=http://gitlab/"]
}
```
I connected to the instance with:
curl -H "PRIVATE-TOKEN: redacted" -H "Authorization: Bearer $(gcloud auth print-identity-token)" --include 'https://hostname/api/v4/projects'

The request comes trough upstream (tcpdump capture), but Authorization: Bearer was still there:
```
GET /api/v4/projects HTTP/1.1
Host: hostname
User-Agent: curl/8.5.0
Accept: */*
Authorization: Bearer redacted
Private-Token: redacted
X-Forwarded-Email: redacted
X-Forwarded-For: 86.83.5.178,86.83.5.178, 172.18.0.7
X-Forwarded-Host: hostname
X-Forwarded-Method: GET
X-Forwarded-Port: 443
X-Forwarded-Proto: https,https
X-Forwarded-Scheme: https
X-Forwarded-Server: hostname
X-Forwarded-Ssl: on
X-Forwarded-Uri: /api/v4/projects
X-Forwarded-User: 102418810797293211109
X-Original-Method: GET
X-Original-Url: https://hostname/api/v4/projects
X-Real-Ip: 86.83.5.178,86.83.5.178
Accept-Encoding: gzip
```

In my case this makes gitlab trip up and return me a 403.

### Possible Solutions

1. Dont pass Authorization header
2. Introduce a "Proxy-Authorization" header (like the Google IAP does) to avoid these issues altogether and allow usage of Authorization header for Upstream services.

**Comment by JoelSpeed** [comment]
Have you tried the `--skip-auth-strip-headers` flag?

I believe in the alpha config we expose much more control over headers and you should be able to control what you need. However, I think in your case, at the moment, you are sending an authorization header, and we just pass that straight on, since OAuth2 Proxy isn't configured to manage this header, we assume it's there for the backend to consume.

A workaround would be to use OAuth2 Proxy in a more sidecar like mode and use a proper reverse proxy, eg nginx, as the actual proxy to your backend
