### ISSUE TITLE
[Support]: got 404 not found error when fetching keys oidc

### ISSUE THREAD

**Issue by pbxqdown** [oauth2-proxy/oauth2-proxy#2479]
### OAuth2-Proxy Version

7.5.1

### Provider

oidc

### Current Behaviour of your Problem

I saw following error popping up when sending jwt token to `/auth` from client.
Error log:

> ```[2024/02/05 07:24:09] [jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, not implemented, failed to verify token: failed to verify signature: fetching keys oidc: get keys failed: 404 Not Found <html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 404 (Not Found)!!1</title><style nonce="n3yXZqrSh4j6PPkSMJCkPQ">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><main id="af-error-container" role="main"><a href=//www.google.com><span id=logo aria-label=Google role=img></span></a><p><b>404.</b> <ins>That’s an error.</ins><p>The requested URL was not found on this server. <ins>That’s all we know.</ins></main>]```

I'm wondering what may cause the issue. It used to work but stopped working recently. None of oauth2-proxy configuration is changed. But I updated my client to a newer version recently.

### Configuration details or additional information

Following is the script i use to install oauth2-proxy with helm:
```
helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
helm repo update
helm upgrade \
  oauth2-proxy oauth2-proxy/oauth2-proxy \
  --install \
  --namespace oauth2-proxy \
  --create-namespace \
  --set extraArgs.extra-jwt-issuers=https://accounts.google.com=[my-app-aud]
  --set extraArgs.skip-jwt-bearer-tokens=true
```

**Comment by JoelSpeed** [comment]
If you are using the OIDC provider, check the issuer URL, looks like it may be hitting an incorrect page
