### ISSUE TITLE
[Support]: Redirect loop after successful authentication

### ISSUE THREAD

**Issue by ollie-nye** [oauth2-proxy/oauth2-proxy#2486]
### OAuth2-Proxy Version

Helm chart 6.23.1, oauth2-proxy 7.5.1

### Provider

oidc

### Current Behaviour of your Problem

When I visit the exposed endpoint and log in with auth provider, I get redirected back to oauth2-proxy where it redirects to itself until Chrome throws a `ERR_TOO_MANY_REDIRECTS`.

Logs show the same line repeated (bar timestamps) until Chrome gives up:

`10.244.2.5:34004 - <request id> - <email> [2024/02/06 22:53:34] <public hostname> GET / "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" 302 0 0.003`

Same experience in a fresh incognito window too, so it's not old cookies hanging around I don't think

### Configuration details or additional information

Current config:

```
upstreams = "http://dashboard-kubernetes-dashboard.dashboard.svc.{{ .Values.clusterName }}"
redirect_url = "https://<public hostname>/oauth2/callback"
oidc_issuer_url = "https://<idp hostname>"
email_domains = [ '*' ]
cookie_domains = [ '<root domain>' ]
provider = "oidc"
provider_display_name = "Internal"
allowed_groups = [ "kubernetes" ]
oidc_email_claim = "email"
oidc_groups_claim = "groups"
cookie_secure = false
show_debug_on_error = true
set_authorization_header=true
set_xauthrequest=true
pass_access_token=true
pass_authorization_header=true
pass_user_headers=true
pass_host_header=true
skip_jwt_bearer_tokens=true
```

Oauth2-proxy is running behind `ingress-haproxy` with no extra annotations. Requests make it through HAProxy but seem to be redirected with a `302` to the same path for some reason

Thanks for any help anyone can give!

**Comment by chananelb** [comment]
we're seeing the same thing @ollie-nye did you end up finding a solution?

**Comment by luka-mikec** [comment]
@ollie-nye @chananelb Maybe you have multiple session stores? E.g. multiple Redis instances, or multiple oauth2-proxy instances using files as he session store. This could cause one instance saving the session, but another instance not seeing it and redirecting to /authorize

**Comment by JoelSpeed** [comment]
Doesn't look like a session store problem to me, but maybe try switching the backend out. I know the Kube dashboard typically redirects on first visit, it's possible that the 302 is actually coming from the dashboard, and that for some reason the path isn't being sent to the backend correctly.

**Comment by ollie-nye** [comment]
@luka-mikec I do have multiple deployments of the proxy, but attached to one exposed service each and no shared volumes or anything. Not sure if there's another way those pods might be sharing state though!

@JoelSpeed That sounds like a good shout, I'll try and see where that redirect is actually coming from

**Comment by luka-mikec** [comment]
@ollie-nye The problem would actually come from not sharing state, since requests might be routed to different instances, and these instances could be unaware that a session already exists in another instance. A simple temporary solution would be to use sticky sessions, so all requests from one user come to the same instance

**Comment by ollie-nye** [comment]
Ah I see! That shouldn't be the case here then, there's one proxy pod in front of one dashboard pod, but a separate proxy in front of each of a few other services like Argo and Grafana. They're all on separate host ingresses, all the dashboard requests end up at the same proxy instance so they should behave like they're isolated from the others entirely

**Comment by tirelibirefe** [comment]
Hello @ollie-nye 
I have a similar setup with yours but I use Istio. Each app has dedicated proxy and dedicated virtualservice (ingress).
Were you able to manage to pinpoint the source of the problem? I have the same problem in an environment which is used Istio.
