### ISSUE TITLE
[Support]: Use Kubernetes Service as Upstream

### ISSUE THREAD

**Issue by NiroDeveloper** [oauth2-proxy/oauth2-proxy#2491]
### OAuth2-Proxy Version

7.5.1

### Provider

oidc

### Current Behaviour of your Problem

After successful login at the oauth2 proxy, it tries to upstream to http://my-kubernetes-service:80/

The oauth2 proxy receives this 503 response from Istio:
`upstream connect error or disconnect/reset before headers. reset reason: connection termination`

The kubernetes service is correctly implemented, i can see that from the following.
I also installed curl on the oauth2 proxy container, if i run `curl http://my-kubernetes-service:80/` or `curl http://my-kubernetes-service` i get a 200 response as expected.
Somehow the proxy sends different requests than curl.

### Configuration details or additional information

If i set a wrong upstream domain or port on purpose, it show a different error.
Is it possible that it tries to use SSL/TSL on a HTTP url?

### Steps To Reproduce

1. Deploy a Kubernetes HTTP application with service
2. Deploy the oauth2 proxy and set the Upstream URL to the Kubernetes Service Name.

**Comment by andrescolodrero** [comment]
Hi, 
this configuration works as expected for me:
oauth2_proxy.cfg: |-
    provider = "github"
    email_domains = [ "*" ]
    upstreams = [ "http://myservice:8080" ]

i never use por 80 as a service in kubernetes (mostly because some systems requires toot for use ports <1024)

**Comment by NiroDeveloper** [comment]
Thanks for your tip, but it didn't completely solve my problem.
I also changed my port to 8080, now i receive a 502.
With curl it is still working correctly, if i use curl with a wrong port on purpose i also get the 502.
So does the proxy ignore the given port? `[proxy.go:89] mapping path "/" => upstream "http://my-kubernetes-service:8080"`

**Comment by NiroDeveloper** [comment]
I found the cause of the Problem.
The oauth2 proxy has `--pass-host-header` enabled by default.
But istio checks this header and blocks the request, because `http://my-kubernetes-service:8080 ` !=  `http://my-service.com`.
So if i disable `--pass-host-header`, i can access the service.
Now i just need a solution so the webserver at the end knows his own url for e.g. redirects.

**Comment by NiroDeveloper** [comment]
So the communication is working with` --pass-host-header` disabled.
But i think a X-Forwarded-Host header should be send as sustainable solution: #2494
