### ISSUE TITLE
[Feature]: custom lua script for modify request or response headers, path, query string

### ISSUE THREAD

**Issue by wei840222** [oauth2-proxy/oauth2-proxy#2495]
### Motivation

hi, I want to do this approch https://discuss.elastic.co/t/bypass-login-page/337047/3, to by pass Kibana login page via add add the Basic Authentication header to upstream (Kibana).
I know it can do by a extra nginx proxy. but I want to make a less a possible component to deploy it.

If contributors feel that this feature can be added to oauth proxy, I can provide PR to add this feature.

### Possible solution

https://github.com/Shopify/go-lua
https://github.com/yuin/gopher-lua

and add a new config for user select whicj lua file will user in pre-request to upstream and post-response after upstream

### Provider

None

**Comment by JoelSpeed** [comment]
I think we need to reject this. At the end of the day, the OAuth2 Proxy project provides functionality for authentication, and we have extended that somewhat on a theme to allow users to modify authentication related changes and some tweaks to headers. We have, for example, the ability to modify some headers in the alpha configuration.

What I don't want to do is to make this project a jack of all trades, master of none reverse proxy.

For complex use cases, using something with more of a community and commercial support behind it such as nginx is a much better fit here.

This feature to me seems beyond our scope, and beyond what our volunteer team can reasonably support in the long term.

If you want to provide documentation for using OAuth2 Proxy in conjunction with nginx, I'd support that for this use case

**Comment by wei840222** [comment]
okay i see, thx for your reply
