### ISSUE TITLE
[Feature]: When do you plan to make a release?

### ISSUE THREAD

**Issue by geemorin** [oauth2-proxy/oauth2-proxy#2497]
### Motivation

When do you plan to make a release? It has been 6 months and I see in your doc that you aim to release once a quarter. We would really like to have what has been merged since september 23 in prod. Thank you!

### Possible solution

[Release creation guide](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/RELEASE.md)

### Provider

None

**Comment by kvanzuijlen** [comment]
Release was done yesterday/a couple of hours ago (depending on the timezone). Sorry it took so long, we've all been quite busy.

**Comment by geemorin** [comment]
Thank you!
