### ISSUE TITLE
Cookie problem

### ISSUE THREAD

**Issue by InSpectre6** [oauth2-proxy/oauth2-proxy#2503]
### OAuth2-Proxy Version

7.5.1

### Provider

keycloak

### Expected Behaviour

There are 2 clients in keycloak. Both are on the same realm. redis session storage. Oauth2proxy uses the same database for both clients. When it's time to update the cookie, oauth2proxy should correctly unload the session from redis and update the cookies

### Current Behaviour

When refreshing a page on a site protected by oauth2proxy, I get a 502 error. In the oauth2proxy logs Error loading cookied session: failed to load the session state with the ticket: error loading redis session: redis: nil, removing session
Error loading cookied session: failed to load the session state with the ticket: error loading redis session: context canceled, removing session
Error removing session: error clearing the session from redis: context canceled
Although redis has keys

### Steps To Reproduce

1. Create 2 clients in Keycloak
2. Create 2 configs for oauth2proxy
3. Use the same database for both oauth2proxy
4. Add the cookie-refresh parameter. When the cookie refresh time comes, an error should appear

### Possible Solutions

1. Use different realms in Keycloak
2. Remove the cookie-refresh parameter, but then you will have to manually refresh the page to re-authorize

**Comment by drdj85** [comment]
I'm experiencing the same issue auth to azure. Single client though, same error. Any clarification on cause/fix would be great.

**Comment by InSpectre6** [comment]
I found solution. Cookie_domains and whitelist_domains parameter must be equal fqdn of service that closes by oauth2proxy. Example: cookie_domains=["domain.example.org"}. If you use nginx reverse proxy for keycloak/azure, increase proxy buffer size
