### ISSUE TITLE
Access tokens are not usable for authorization without a session

### ISSUE THREAD

**Issue by Anonymous-Coward** [oauth2-proxy/oauth2-proxy#2509]
### OAuth2-Proxy Version

7.5.1

### Provider

oidc

### Current Behaviour of your Problem

I am trying to test oauth2-proxy with an API endpoint. The relevant part of the configuration is:

```
client_id = "..."
client_secret = "..."

oidc_issuer_url="https://sso.company.com"
provider="oidc"
provider_display_name="company-sso-dev"

api_routes = [
	"^/api"
]

upstreams = [
	"http://test.app.redirect.url:12345"
]

pass_authorization_header = true
scope = "openid"
validate_url = "https://sso.company.com/as/introspect.oauth2"
```

The configuration is as follows:
- nginx running locally with a self-signed certificate
- a single upstream running locally (as depicted in the oauth2-proxy configuration snippet above)
- oauth2-proxy also running locally behind nginx:

```
	upstream oauth2-proxy { 
		server localhost:12347 
	}
```

The upstream is just a simple node server that copies the request headers and body plus more detailed information about the JWT, if present, to the response. 

Multiple host names are all mapped to 127.0.0.1 by manipulating `/etc/hosts`, so that nginx can properly route everything, and that the redirect from the OIDC server, when sending back an authentication code, works properly on local.

I first get an access token from the SSO directly:

```
$ curl -vvv "https://sso.company.com/as/token.oauth2" -H "Content-type: application/x-www-form-urlencoded" -H "Accept: application/json" -H "Authorization: Basic ..." --data-raw "grant_type=client_credentials&scope=openid"

{"access_token":"0201QV5cXYWwFif6dmonsijPDbh0","token_type":"Bearer","expires_in":1799}
```

Then I use it to do a request through the oauth2-proxy - to which I get a `401 Not authorized` even if an authorization header is present and valid:

```
$ curl -kv  "https://test.app.redirect.url/api/some/path" -H "Authorization: Bearer 0201QV5cXYWwFif6dmonsijPDbh0"

< HTTP/1.1 401 Unauthorized
< Server: nginx/1.24.0
< Date: Sat, 17 Feb 2024 18:26:59 GMT
< Content-Type: application/json
< Content-Length: 2
< Connection: keep-alive
```

If I do a similar request without /api/:

```
curl -kv  "https://kbv-test.app.tbintra.net/some/path" -H "Authorization: Bearer 0201QV5cXYWwFif6dmonsijPDbh0"
```

I get a `403` Forbidden with a body prompting me to log in using the configured OIDC provider.

No request to verify the access token is made to the OIDC provider - I checked using tcpdump that no single packet is exchanged with the SSO server during those requests. 

Using an alternate solution, developed in-house, using the access token works flawlessy - I can call the introspection endpoint to get all the available user info. If I bypass the oauth2 proxy and go directly to the upstream, I get proper responses in both cases. If I use a browser to go to a non-API URL, I do get the login prompt, where I can use the same credentials, log in and access the backend application.

I can see no more specific information than this in the oauth2-proxy logs (timestamps and other irrelevant info stripped):

```
[oauthproxy.go:970] No valid authentication in request. Initiating login.
GET - "/some/path" HTTP/1.0 "curl/8.0.1" 403 8503 0.000
[oauthproxy.go:964] No valid authentication in request. Access Denied.
GET - "/api/some/path" HTTP/1.0 "insomnia/8.6.0" 401 2 0.000
```
I looked into the code, and it seems oauth2-proxy always wants some session to proxy requests. But API calls are typically stateless - i.e. no session.  And it's a pretty common use case for API usage for clients to pass an access token only for authorization, but for the API itself to expect a JWT - with something like oauth2-proxy in between to perform the conversion.

How can oauth2-proxy be used in front of APIs which do expect a JWT in the authentication header, but where clients fetch only an access token using the client credentials grant directly from the authorization server? Is this use case supported at all?

### Configuration details or additional information

client_id = "..."
client_secret = "..."

oidc_issuer_url="https://sso.company.com"
provider="oidc"
provider_display_name="company-sso-dev"

api_routes = [
	"^/api"
]

upstreams = [
	"http://test.app.redirect.url:12345"
]

pass_authorization_header = true
scope = "openid"
validate_url = "https://sso.company.com/as/introspect.oauth2"

### Steps To Reproduce

This might be difficult to reproduce locally because it uses the corporate OIDC provider. But it should be reproducible with any compliant OIDC provider, using the flow described above:

1. fetch an access token from the OIDC provider
2. make a request to a resource using the access token

Expected result: the resource server receives a JWT in the authorization header and returns the resource
Actual result: the request is never proxied, and instead rejected because there's no already established session.

**Comment by rbange** [comment]
keep open

**Comment by markbaumgarten** [comment]
In this issue a comment mentions how tokens **must** be accessed via sessions.... https://github.com/oauth2-proxy/oauth2-proxy/issues/2339

I would like to know why.
