### ISSUE TITLE
[Support]: Possible Documentation Error

### ISSUE THREAD

**Issue by mister-dj** [oauth2-proxy/oauth2-proxy#2511]
### OAuth2-Proxy Version

7.6.x

### Provider

azure

### Current Behaviour of your Problem

When using docker compose files, the cookie domains environment variable must be plural (i.e. "OAUTH2_PROXY_COOKIE_DOMAINS" instead of "OAUTH2_PROXY_COOKIE_DOMAIN" without an 'S').
(I'm assuming this will be an issue when using cli options directly as well.)

Documentation lists this option in the singular.

This was confirmed after troubleshooting 403 errors.

Docker logs which occurred when the env was singular:
AuthFailure Invalid authentication via OAuth2. Error while loading CSRF cookie: http: named cookie not present

### Configuration details or additional information

Compose snippet:
  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: auth
    networks:
      - proxy
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      OAUTH2_PROXY_EMAIL_DOMAINS: ${BASE_DOMAIN}
      OAUTH2_PROXY_WHITELIST_DOMAINS: '*.${BASE_DOMAIN}'
      OAUTH2_PROXY_COOKIE_SECRET: ${COOKIE_SECRET}
      OAUTH2_PROXY_COOKIE_DOMAINS: ${BASE_DOMAIN}
      OAUTH2_PROXY_SESSION_STORE_TYPE: redis
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis:6379
      OAUTH2_PROXY_CLIENT_ID: ${CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH2_PROXY_PROVIDER: azure
      OAUTH2_PROXY_AZURE_TENANT: ${TENANT_ID}
      OAUTH2_PROXY_REDIRECT_URL: 'https://auth.${BASE_DOMAIN}/oauth2/callback'
      OAUTH2_PROXY_OIDC_ISSUER_URL: 'https://login.microsoftonline.com/${TENANT_ID}/v2.0'
      OAUTH2_PROXY_REVERSE_PROXY: true

**Comment by wollomatic** [comment]
Isn't this the behaviour just like [documented here](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#environment-variables):

> Environment variables
[...] If the argument can be specified multiple times, the environment variable should be plural (trailing S).

**Comment by JoelSpeed** [comment]
> Documentation lists this option in the singular.

Can you link the snippet where it suggests that it is singular?

**Comment by mister-dj** [comment]
> > Documentation lists this option in the singular.
> 
> Can you link the snippet where it suggests that it is singular?

https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#command-line-options

This actually isn't an error, just differing behavior/option names when using CLI vs ENV. In the CLI it's --cookie-domain whereas the corresponding environment variable is OAUTH2_PROXY_COOKIE_DOMAINS (plural).

Thanks to @wollomatic for pointing out the difference when using ENVs!
