### ISSUE TITLE
[Bug]: Keycloak scopes not being added to refresh token call

### ISSUE THREAD

**Issue by brunomedeirosdedalus** [oauth2-proxy/oauth2-proxy#2514]
### OAuth2-Proxy Version

7.6.0

### Provider

keycloak-oidc

### Expected Behaviour

The scopes passed to the first call to get the tokens from Keycloak, should also be passed to the subsequent calls to the refresh token endpoint. 

From https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-09.html#section-4.3.3 one can read:

_"The authorization server MAY revoke the old refresh token after issuing a new refresh token to the client. If a new refresh token is issued, the refresh token scope MUST be identical to that of the refresh token included by the client in the request."_

### Current Behaviour

The scopes are not being passed to the refresh token endpoint. Maybe this is the code ? https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/oidc.go#L146

### Steps To Reproduce

1. Setup Oauth2 to use Keycloak;
2. Create an optional scope in Keycloak that injects some claims into the id token.
3. Explicit set Oauth2 to accept the scope created in 2.
4. The claims will be in the first ID token, but no to the next ID tokens acquired via refresh token.

### Possible Solutions

Pass the same scopes set by the user to the calls performed when calling the refresh token endpoint.

**Comment by JoelSpeed** [comment]
Is this a regression or does the same behaviour exhibit on previous versions as well? Are you aware of any providers not keycloak that require this?

**Comment by brunomedeirosdedalus** [comment]
@JoelSpeed  If you agree with the change I can have a look at the source code and try to implement a fix of my own.

**Comment by brunomedeirosdedalus** [comment]
bumo

**Comment by brunomedeirosdedalus** [comment]
Just in case someone else faces the same problem. The problem was actually in the Keycloak side, after creating the scope, one should also set 'Include In Token Scope' to 'ON' otherwise it will not be used while acquiring the refresh tokens.
