### ISSUE TITLE
Retrieve Client Secret from Secret Manager (Vault/Akeyless)

### ISSUE THREAD

**Issue by shashrath** [oauth2-proxy/oauth2-proxy#2515]
### Motivation

Currently, the Client ID and Client Secret are being stored as plain text, Is there a way we can retrieve these secrets dynamically from Secret Managers using some kind of plugin?

### Provider

None

**Comment by JoelSpeed** [comment]
Not currently possible, but you can set them as env vars, which depending on your deployment topology, may help.

Not currently a planned feature and personally, not something I see us supporting any time soon
