### ISSUE TITLE
[OAuth2-Proxy] Custom error page giving out 403 Forbidden Nginx error

### ISSUE THREAD

**Issue by Dexterzprotege** [oauth2-proxy/oauth2-proxy#2516]
### OAuth2-Proxy Version

7.6.0

### Provider

azure

### Expected Behaviour

I have defined custom error pages: error.html and sign_in.html for our OAuth2-proxy with following argument:
`- --custom-templates-dir=/var/oauth2-proxy/templates`

And when this is deployed, any application using this OAuth2-proxy should show up the error.html when they are not authenticated

### Current Behaviour

But instead, I am getting following error:

![Screenshot 2024-02-20 at 16 44 41](https://github.com/oauth2-proxy/oauth2-proxy/assets/42378552/d0f29374-b89e-48e2-8e9f-f37e642824d8)

### Steps To Reproduce

1. We setup a replica of OAuth2-proxy in one of our Docker container
2. We have some applications which use this OAuth2-proxy as form of authentication
3. We define the nginx-ingress in each of application like this:
nginx.ingress.kubernetes.io/auth-url: https://endpoint.com/oauth2
4. And in the OAuth2-proxy, we define custom error page like this:
- --custom-templates-dir=/var/oauth2-proxy/templates
5. And the templates folder has: error.html and sign_in.html

**Comment by JoelSpeed** [comment]
This is an nginx configuration issue. If you access the the OAuth2 Proxy directly it should show your custom pages, however, in this case, nginx auth request is only looking at the auth request response, and is rendering its own error page. You need to configure nginx to handle the error page display

**Comment by skarampatakis** [comment]
Hi, I am facing the same issue although not in Azure but on a local deployment with docker. Almost everything works fine, but when it comes to errors I still only get the nginx error pages. I tried changing the configuration of nginx to make it work, mostly by setting the proxy_intercept_errors directive to off, although this is the default, with no success. It would be helpful for a working example.

I would like to avoid providing custom pages for nginx, the ones from oauth2 proxy are already well defined and work for the purpose. For now the only possible solution would be to define custom error pages on the nginx configuration. Thanks a lot in advance!
