### ISSUE TITLE
[Support]: '{"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience.","innerError":{"date":"2024-02-20T13:53:31","request-id":"8d9fc07c-848f-4ef7-8444-69e722c3ecc3","client-request-id":"8d9fc07c-848f-4ef7-8444-69e722c3ecc3"}}}'

### ISSUE THREAD

**Issue by elucyad** [oauth2-proxy/oauth2-proxy#2517]
### OAuth2-Proxy Version

Latest

### Provider

azure

### Current Behaviour of your Problem

When am trying to use the received bearer token and query graph api am getting the below error

 '{"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience.","innerError":{"date":"2024-02-20T13:53:31","request-id":"8d9fc07c-848f-4ef7-8444-69e722c3ecc3","client-request-id":"8d9fc07c-848f-4ef7-8444-69e722c3ecc3"}}}'

I am getting my client id as the audience in my bearer token and in the manifest of oauth2-proxy am setting scope as "openid profile"
 
below is my code snippet

import requests

# Define the Microsoft Graph API endpoint to fetch user details
graph_api_endpoint = 'https://graph.microsoft.com/v1.0/me'

# Define headers with Authorization bearer token
headers = {
    'Authorization': 'Bearer eyk8eXAiOiJKV1QiLCJub25jZSI6IlFxdDBGX05lMEtRWTdBdy1NLWgtMHhmZml0TDh0dVRGZU1nXzdpVjNSWmMiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtXYmthYTZxczh3c1RuQndpaU5ZT2hIYm5BdyIsImtpZCI6ImtXYmthYTZxczh3c1RuQndpaU5ZT2hIYm5BdyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC85MmU4NGNlYi1mYmZkLTQ3YWItYmU1Mi0wODBjNmI4Nzk1M2YvIiwiaWF0IjoxNzA4NTEwNjUyLCJuYmYiOjE3MDg1MTA2NTIsImV4cCI6MTcwODUxNTk3OCwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iXSwiYWlvIjoiQWJRQVMvOFZBQUFBWm8wZnd4cDd4WmxEMnVaNjRFSS9WNm9xRzc3d0NPZ241Y2hBQUtxcmRHUlVzakVBc2M5S1pGMkhuWmIxQ3NuNHVJWmlVeDkzcVQyek13UDlRUisvdlpXR0t3SkVSV0RtaGhCREV6Y1BnZzFBOW15U1pIODZ1bm5PMWtjSU1nYStvYjV5VGE1U3NSS2xoMDZUK3lGSm1wSTBmM3dvRlB4NEttVnRUR2hzd25xWWRZT2lNY2taU1dWL0dFWmFLUmxVU2VPQ09EYzh2NEwyL1NudVFrYTJ1bXhBNGxVOXBibm4rRUVvMjJWa0I2Yz0iLCJhbXIiOlsicnNhIiwibWZhIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIEV4cGxvcmVyIiwiYXBwaWQiOiJkZThiYzhiNS1kOWY5LTQ4YjEtYThhZC1iNzQ4ZGE3MjUwNjQiLCJhcHBpZGFjciI6IjAiLCJkZXZpY2VpZCI6IjBiYzZiYTRmLTYyNzMtNDNjYS04NTE1LWIxODY5MjRlZDZkYSIsImZhbWlseV9uYW1lIjoiWWFkYXYiLCJnaXZlbl9uYW1lIjoiTHVja3kiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxMDMuOTUuODMuMjA4IiwibmFtZSI6Ikx1Y2t5IFlhZGF2Iiwib2lkIjoiNGI5Njk3ZGYtZGY0Mi00MWIwLWI2NTEtMWRiYmMxNTExNzcyIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTE1Mzg2MDczMjQtMzIxMzg4MTQ2MC05NDAyOTUzODMtMzExOTc3IiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDM3RkZFOEZGNTA5NkQiLCJyaCI6IjAuQVJFQTYwem9rdjM3cTBlLVVnZ01hNGVWUHdNQUFBQUFBQUFBd0FBQUFBQUFBQUFSQUU0LiIsInNjcCI6IkFjY2Vzc1Jldmlldy5SZWFkLkFsbCBBY2Nlc3NSZXZpZXcuUmVhZFdyaXRlLkFsbCBBZ3JlZW1lbnQuUmVhZC5BbGwgQWdyZWVtZW50LlJlYWRXcml0ZS5BbGwgQWdyZWVtZW50QWNjZXB0YW5jZS5SZWFkIEFncmVlbWVudEFjY2VwdGFuY2UuUmVhZC5BbGwgQVBJQ29ubmVjdG9ycy5SZWFkLkFsbCBBUElDb25uZWN0b3JzLlJlYWRXcml0ZS5BbGwgQXBwQ2F0YWxvZy5SZWFkV3JpdGUuQWxsIEFwcGxpY2F0aW9uLlJlYWQuQWxsIEF1ZGl0TG9nLlJlYWQuQWxsIEF1dGhlbnRpY2F0aW9uQ29udGV4dC5SZWFkLkFsbCBBdXRoZW50aWNhdGlvbkNvbnRleHQuUmVhZFdyaXRlLkFsbCBCb29raW5ncy5NYW5hZ2UuQWxsIENhbGVuZGFycy5SZWFkV3JpdGUgQ29udGFjdHMuUmVhZFdyaXRlIEN1c3RvbUF1dGhlbnRpY2F0aW9uRXh0ZW5zaW9uLlJlYWQuQWxsIEN1c3RvbUF1dGhlbnRpY2F0aW9uRXh0ZW5zaW9uLlJlYWRXcml0ZS5BbGwgRGV2aWNlTWFuYWdlbWVudEFwcHMuUmVhZC5BbGwgRGV2aWNlTWFuYWdlbWVudEFwcHMuUmVhZFdyaXRlLkFsbCBEZXZpY2VNYW5hZ2VtZW50Q29uZmlndXJhdGlvbi5SZWFkLkFsbCBEZXZpY2VNYW5hZ2VtZW50Q29uZmlndXJhdGlvbi5SZWFkV3JpdGUuQWxsIERldmljZU1hbmFnZW1lbnRNYW5hZ2VkRGV2aWNlcy5Qcml2aWxlZ2VkT3BlcmF0aW9ucy5BbGwgRGV2aWNlTWFuYWdlbWVudE1hbmFnZWREZXZpY2VzLlJlYWQuQWxsIERldmljZU1hbmFnZW1lbnRNYW5hZ2VkRGV2aWNlcy5SZWFkV3JpdGUuQWxsIERldmljZU1hbmFnZW1lbnRSQkFDLlJlYWQuQWxsIERldmljZU1hbmFnZW1lbnRSQkFDLlJlYWRXcml0ZS5BbGwgRGV2aWNlTWFuYWdlbWVudFNlcnZpY2VDb25maWcuUmVhZC5BbGwgRGV2aWNlTWFuYWdlbWVudFNlcnZpY2VDb25maWcuUmVhZFdyaXRlLkFsbCBEaXJlY3RvcnkuQWNjZXNzQXNVc2VyLkFsbCBEaXJlY3RvcnkuUmVhZC5BbGwgRGlyZWN0b3J5LlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZFdyaXRlLkFsbCBHcm91cC5SZWFkLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIEdyb3VwTWVtYmVyLlJlYWQuQWxsIElkZW50aXR5Umlza0V2ZW50LlJlYWQuQWxsIE1haWwuUmVhZFdyaXRlIE1haWxib3hTZXR0aW5ncy5SZWFkV3JpdGUgTm90ZXMuUmVhZFdyaXRlLkFsbCBPbmxpbmVNZWV0aW5nQXJ0aWZhY3QuUmVhZC5BbGwgT25saW5lTWVldGluZ3MuUmVhZCBvcGVuaWQgUGVvcGxlLlJlYWQgUGVvcGxlLlJlYWQuQWxsIFBvbGljeS5SZWFkV3JpdGUuQXV0aGVudGljYXRpb25NZXRob2QgcHJvZmlsZSBSZXBvcnRzLlJlYWQuQWxsIFNjaGVkdWxlLlJlYWQuQWxsIFNjaGVkdWxlLlJlYWRXcml0ZS5BbGwgU2l0ZXMuRnVsbENvbnRyb2wuQWxsIFNpdGVzLk1hbmFnZS5BbGwgU2l0ZXMuUmVhZFdyaXRlLkFsbCBUYXNrcy5SZWFkV3JpdGUgVGVhbU1lbWJlci5SZWFkLkFsbCBUZWFtTWVtYmVyLlJlYWRXcml0ZS5BbGwgVXNlci5SZWFkIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIFVzZXIuUmVhZFdyaXRlLkFsbCBVc2VyQXV0aGVudGljYXRpb25NZXRob2QuUmVhZFdyaXRlLkFsbCBlbWFpbCIsInNpZ25pbl9zdGF0ZSI6WyJkdmNfbW5nZCIsImR2Y19jbXAiLCJrbXNpIl0sInN1YiI6IkU2SXVQZDBBaThxWHM3eWdjdWw4THJwSWQtVzYwMl9MMncweGpoMzdNTmciLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiI5MmU4NGNlYi1mYmZkLTQ3YWItYmU1Mi0wODBjNmI4Nzk1M2YiLCJ1bmlxdWVfbmFtZSI6Imx1Y2t5LnlhZGF2QGVyaWNzc29uLmNvbSIsInVwbiI6Imx1Y2t5LnlhZGF2QGVyaWNzc29uLmNvbSIsInV0aSI6IjdMR2Mycmk1dTA2cTZWZmhIVnNTQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2MiOlsiQ1AxIl0sInhtc19zc20iOiIxIiwieG1zX3N0Ijp7InN1YiI6IjF6OUJraFY1ZmxtRzJkNk1nMEdYaTJNLUp5X2Y4NkNYUE16WmJPREZzV0kifSwieG1zX3RjZHQiOjE0MDEyNjg3MjgsInhtc190ZGJyIjoiRVUifQ.QOCsLUacrq9pG0_wpMreQElVDF7CPmLaJ1bi2EgkoQqACQi3jn4ZwX4o2e3Rdg5tPi1CYDuGUI15xSasdEflRSmLNaqdy57H4fJi4k7Zm4SWT6BesoqE3xoftwJxRaSZsTTCAOL9yfrRWs_eU7CMeN-QhSXCaqRpQk7QBbS77DFfoahfWZhlckZHRcqRdr2u1FHnkHzLKSrRlrGHmpLHO0H6hvoun7Qk2EOpUqebDfrv8H6N3s43aujXMOOeo2Z5FBbCVs20wb4Y7Tm4ija6HVp-OQzBVvwalPgJvUw-4ZHKxXS9r1rhrZsCq9y5f-hF6gdWgBzd2kzpB4p7FzpszQ'
}

try:
    # Make a GET request to the Microsoft Graph API
    response = requests.get(graph_api_endpoint, headers=headers)

    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        # Parse and print the user details from the response JSON
        user_details = response.json()
        print('User ID:', user_details.get('id'))
        print('User Principal Name:', user_details.get('userPrincipalName'))
        print('User Display Name:', user_details.get('displayName'))
        print('User Email:', user_details.get('mail'))
        # Add more user details as needed

    else:
        # Print an error message if the request was not successful
        print('Error:', response.status_code, response.text)

except Exception as e:
    print('An error occurred:', e)

### Configuration details or additional information

  - name: "OAUTH2_PROXY_SCOPE"
    value: "openid profile"

**Comment by HoussemEs** [comment]
i'm not sure that i can solve your problem, but i'm pretty sure that the token you provided isn't from ms graph, or isn't correctly created. to use teams api, you should create an access token from microsoft graph and assign permissions to the token you created so you can do whatever you want.
here, check access token on behalf of a user.
https://learn.microsoft.com/en-us/graph/auth-v2-user?tabs=http

i wish this would help
