### ISSUE TITLE
[Support]: oauth2-proxy access token validation

### ISSUE THREAD

**Issue by superlazyname** [oauth2-proxy/oauth2-proxy#2523]
Does oauth2-proxy validate access tokens? I found some source code that validates id tokens, but not access tokens.

This is what I would consider "validation":
1. Some code to check that the signature on the access_token matches, and that the jwt has not been tampered with
2. A check to make sure the issuer and audience are what we expect

## Cases

Happy path:
- A client authenticates to an Authentication Server with e.g. client_credentials, and then gets a JWT in return
- The JWT is from the expected authentication server, oauth2-proxy forwards the request upstream

Token forgery path 1:
- A hacker creates their own JWT (signed by their own computer), that appears to be a real access token, but it didn't come from the real authentication server
- oauth2-proxy should reject this request, because the signature does not match

Token forgery path 2:
- A hacker connects to an authentication server and gets a JWT to access some service
- They present that JWT to the wrong service
- oauth2-proxy should reject this request, because e.g. audience does not match.

Will oauth2-proxy fall for these "forged" tokens? I want to read the code and find out.

**Comment by geemorin** [comment]
Should'nt oauth2-proxy revalidate the stored token once upon obtention to prevent token forgery before considering it valid?

**Comment by superlazyname** [comment]
Bump. Any ideas?

**Comment by JoelSpeed** [comment]
There is no standard for access tokens, they can be arbitrary strings. Some providers implement them as JWTs, some implement them as opaque strings. This is why we expect users to prefer to leverage ID tokens for authn, which do have standards, and which we do verify.
