### ISSUE TITLE
[Feature]: Google Groups via Cloud Identity API

### ISSUE THREAD

**Issue by Pionerd** [oauth2-proxy/oauth2-proxy#2525]
### Motivation

Currently, Google groups are retrieved by using a separate service account with domain wide delegation. 

Recently, the Cloud Identity API  started supporting groups. This new approach does not longer require the separate service account. It's implemented (that I know of) in Grafana 10.3 and also this PR may be of interest: https://github.com/jkroepke/openvpn-auth-oauth2/pull/196

### Provider

google

**Comment by SLoeuillet** [comment]
Just implemented it in headscale repo.
Inspired by grafana code too

**Comment by Pionerd** [comment]
Please be aware of https://github.com/grafana/grafana/issues/85067, possible solution: https://github.com/jkroepke/openvpn-auth-oauth2/pull/242
