### ISSUE TITLE
How to skip the OAUTH2-Proxy spalsh screen and directly redirect to auth portal ?

### ISSUE THREAD

**Issue by CyberSeppi** [oauth2-proxy/oauth2-proxy#2527]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Current Behaviour of your Problem

At the moment the OIDC Site appears with button "Login to OIDC Provider".
I´m looking for a way to avoid this screen and directly open the oidc´s providers login screen.
With which configuration parameter can I achieve this ?

Thanks!

### Configuration details or additional information

-

### Steps To Reproduce

-

**Comment by tuunit** [comment]
--skip-provider-button	bool	will skip sign-in-page to directly reach the next step: oauth/start	false

**Comment by CyberSeppi** [comment]
works like a charm. 

Thank you very much!
