### ISSUE TITLE
OIDC groups claim ignored

### ISSUE THREAD

**Issue by duemila2** [oauth2-proxy/oauth2-proxy#2529]
### OAuth2-Proxy Version

v7.6.0

### Provider

oidc

### Expected Behaviour

I would like to authorize only JWT tokens having a groups claim called "_app_groups_" containing the value "_prefect_", for example:
```
"app_groups": [
    "ml-flow",
    "prefect"
  ]
```

I've tried the following different configurations:
- set environment variable OAUTH2_PROXY_OIDC_GROUPS_CLAIM=app_groups
- set environment variable OAUTH2_PROXY_OIDC_GROUPS_CLAIM="app_groups"
- pass command line argument --oidc-groups-claim=app_groups
- pass command line argument --oidc-groups-claim="app_groups"

and I expected that the token is validated, because I also set the env var OAUTH2_PROXY_ALLOWED_GROUPS=prefect

### Current Behaviour

In all of this cases the validation of the token doesn't work.
Instead, if I insert the groups into a claim called "_groups_", the validation of the token goes well.
Then I suspect that the oidc-groups-claim env var or arguments are ignored or I set them wrong.

Could you please help me to analyze the issue?

Thank you very much

### Steps To Reproduce

- set environment variable OAUTH2_PROXY_OIDC_GROUPS_CLAIM=app_groups or
- set environment variable OAUTH2_PROXY_OIDC_GROUPS_CLAIM="app_groups" or
- pass command line argument --oidc-groups-claim=app_groups or
- pass command line argument --oidc-groups-claim="app_groups" or

and set OAUTH2_PROXY_ALLOWED_GROUPS=prefect, then try to pass a token having a claim: 

```
"app_groups": [
    "ml-flow",
    "prefect"
  ]
```

**Comment by MironovOleg** [comment]
Hi, @duemila2!

I also faced this problem.

Try setting the parameter like this `OAUTH2_PROXY_SCOPE="openid email profile"`. Maybe this will help? Because the authorization request begins to include a scope `groups` when `OAUTH2_PROXY_OIDC_GROUPS_CLAIM` is set.
