### ISSUE TITLE
Bug: CSRF failure when logging in with the same account from multiple devices

### ISSUE THREAD

**Issue by dsb3** [oauth2-proxy/oauth2-proxy#254]
In a previous version of oauth2_proxy I was able to log in with the same gmail account on multiple devices (desktop + mobile).

In the most recent, when I try to do so the first device can log in, and subsequent devices get "Invalid authentication via OAuth2: csrf token mismatch, potential attack"

Some variation of changing the cookie name; OAuth secret and restarting allows me to invert which device can log in, and which gets the csrf error.

I have tried to go back through prior tags to determine which release allowed multiple devices to use the same account, but was not successful in finding it (all prior tags I tested failed in the same way).

## Expected Behavior

I would expect one account to be usable across multiple devices simultaneously.

## Current Behavior

The first device to log in with a given gmail account is successful.  Subsequent logins with the same account on other devices fail.

## Possible Solution

I would consider an option to disable this, but would expect a way to - e.g. - allow the newest device to invalidate the prior device rather than be locked out indefinitely.

## Steps to Reproduce (for bugs)

1.  Configure gmail authentication and valid email file
2.  Authenticate on one device (successfully)
3.  Attempt to authenticate on a different device (which will fail)

## Context

I use oauth2 proxy in front of a home automation web interface.  I need to access the interface from multiple devices.

As a work-around I have manually added additional gmail accounts which one device can authenticate as, allowing each device to use a separate account and avoid the bug.

## Your Environment

- Version used: v4.0.0 (latest)

docker-compose -- nginx front end; oauth2 proxy configured per the example docs; traffic that passes authenticated successfully is passed through to a separate container with a webserver feeding content.

**Comment by JoelSpeed** [comment]
This is a curious bug and certainly isn't present within our setup. I can log into our sites protected by the proxy from both my phone and laptop, though we are using the OIDC provider rather than the gmail provider. I would suggested therefore to start the bug hunt in the gmail provider itself 🤔 

That said I'm not aware of any changes that have been made to the provider since we have taken over the project. Have you recently switched from Bitly or another fork to using ours?

**Comment by dsb3** [comment]
Thanks for the detailed reply, Joel.  Perhaps it's something else amiss at my end.  I'll try to re-duplicate the problem, and see if I can also recreate using OIDC.

If nothing changed in the app that would cause this, I wonder if Chrome itself changed in the way it synchs cookies between devices and is causing the issue.  I'll take a look into that when I have time and report any findings.

To the other Q, no, I've been using this same fork for the entire time.

**Comment by dsb3** [comment]
I've done some more testing on this.  It looking like unexpected behaviour in google's synching of (presumably cookies) between devices logged in to the same account.

I just logged in once from my mobile, and once from an incognito window using the same gmail account to authenticate with zero issues.

**This is not a bug in oauth2**, but there might be a feature request hiding in here to handle this odd behaviour better, or at least detect when it might be happening and throw out a more useful error message.

**Comment by JoelSpeed** [comment]
@dsb3 Are you happy to close this issue?

**Comment by dsb3** [comment]
I would prefer to re-categorize as an enhancement, so as to help anyone in the future who also runs into the same issue.

**Comment by dhess** [comment]
FYI, I'm getting this error with the latest `oauth2_proxy` from `master` and Okta.

**Comment by teralype** [comment]
What error was this?

**Comment by dmahisingh** [comment]
I am facing couple of Issues when I accessing my application which is deployed on Azure Kubernetes from iPhone browser, it is working fine with Android phone-  I am using Azure as provider.
1) In few devices, I am getting below error - 403 Permission Denied http: named cookie not present
The oauth2 proxy pod logs shows this error - [AuthFailure] Invalid authentication via OAuth2: unable too obtain CSRF cookie
2) In few devices, I am getting below error 
Origin <application url> is not allowed by Access-Control-Allow-Origin
Please help me resolving these.

**Comment by lyda** [comment]
If @dhess could share the cause I'd love to know since I suspect I have a similar issue!

**Comment by dhess** [comment]
@lyda Sorry, I no longer recall the details about what the problem was. In the meantime, I've switched to https://github.com/thomseddon/traefik-forward-auth for the purposes of putting an OAuth2 proxy in front of my web service.

**Comment by marcus-sa** [comment]
I'm hitting this error with all providers.
