### ISSUE TITLE
[Bug]:  duplicate redis sessions with multiple oauth2-proxy

### ISSUE THREAD

**Issue by redboxstudio** [oauth2-proxy/oauth2-proxy#2543]
### OAuth2-Proxy Version

7.4.1

### Provider

keycloak

### Expected Behaviour

one redis session for all oauth2-proxy instances

### Current Behaviour

own sessions for each oauth2-proxy instance

for 15k users in keycloak with two oauth2-proxy in general redis I get 30k entries, also in the oauth2 logs I see that each instance does its own authsuccess and refreshsession

### Steps To Reproduce

deploy sheme nginx-oauth2-proxy-redis-keycloak-app
configure balancing of several oauth2-proxy via nginx upstream
configure one redis for all oauth2-proxy instances
use a common cookie-secret for all oauth2-proxy instances, as well as the default cookie-prefix _oauth2_proxy

**Comment by redboxstudio** [comment]
temporary solution to change nginx balancing type to ip_hash

**Comment by JoelSpeed** [comment]
Odd, I wonder why that's happening. My understanding was that there was a sharing of sessions across instances, so either something is misconfigured here, or we have introduced a bug 🤔 

Did you ever work this one out?
