### ISSUE TITLE
[Feature]: [OIDC] Add a configuration to skip id_token expiration verification 

### ISSUE THREAD

**Issue by cguy** [oauth2-proxy/oauth2-proxy#2553]
### Motivation

In OIDC provider, when we want to [use refresh token to get a new access token](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/oidc.go#L140), one of the first steps is to [verify the id_token](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/oidc.go#L188).

In my company, the SSO server (which has OIDC implementation) is configured to keep `id_token` with small expiration for security purpose.

I am wondering if it could be acceptable to add configuration to set [`SkipExpiryCheck`](https://github.com/coreos/go-oidc/blob/v3/oidc/verify.go#L285) to true from the go-oidc library you are using. The same way you allow to configure [`SkipIssuerCheck`](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/providers/oidc/provider_verifier.go#L84).

### Possible solution

```golang
// toOIDCConfig returns an oidc.Config based on the configured options.
func (p ProviderVerifierOptions) toOIDCConfig() *oidc.Config {
	return &oidc.Config{
		ClientID:             p.ClientID,
		SkipIssuerCheck:      p.SkipIssuerVerification,
		SkipExpiryCheck:      p.SkipExpiryVerification, // ` p.SkipExpiryVerification` is a proposal
		SkipClientIDCheck:    true,
		SupportedSigningAlgs: p.SupportedSigningAlgs,
	}
}
```

### Provider

oidc

**Comment by segaura** [comment]
We also need this, far the same reason.
The `id_token` is short lived and not refreshable (IDP is Novell Access Manager).
We thus need to build with this `SkipExpiryCheck: true` thing and also some method to refresh the Access Token and currently we managed to do this using the code from #2431 .

...until hopefully both issues get closed.
