### ISSUE TITLE
[Bug]: Broken content-type in v7.6.0 (probably a breaking change from v7.4.0) 

### ISSUE THREAD

**Issue by CesarStef** [oauth2-proxy/oauth2-proxy#2568]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Expected Behaviour

Hi,
The oauth2-proxy v.7.4.0 served correctly our old angular application:
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/5521388/ca6d819e-a833-49fa-ba2e-785353300c80)

### Current Behaviour

With the same exactly infrastructure and same frontend, v7.6.0 return all the content types as "text/html":
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/5521388/ec69dbfd-76b8-4129-b85b-fba6ff41550f)

### Steps To Reproduce

Working in progress.

Things I know at the moment:
- types are not explicit declared for [<script>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type) and [<style>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#type), as suggested by MDN
- It may be associated with nginx, because we serve these Angular frontend from containers and to expose them we have inside every container nginx configured this way: server {
  listen 80;
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
}

### Configuration details or additional information

This happens on 2 different Angular frontends with different Angular version so probably the problem is not Angular (or at least not a specific version of it)

In the next days I will try to find some time to deploy oauth2-proxy version v7.5.0 and v7.5.1 to try to understand when the behavior change

Thanks in advance for any help you can give me!

**Comment by tuunit** [comment]
Hi @CesarStef,

could you try to adding `include /etc/nginx/mime.types;` to your nginx server block.
