### ISSUE TITLE
[Feature]: Support for Redis alternatives

### ISSUE THREAD

**Issue by zoc** [oauth2-proxy/oauth2-proxy#2572]
### Motivation

The redis licence has recently changed to increase restrictions on distributors. Major linux distributions, like Fedora, are already considering removing the software from their future releases.

It would be nice to add support for alternatives, or document the ones that are already compatible with oauth2 proxy, if any.

### Provider

None

**Comment by JoelSpeed** [comment]
The interface is there and relatively straightforward to implement with little knowledge of OAuth2 Proxy internals required, taking the redis version as a sample.

We are open to new alternatives, both Kube (Via secret objects) and etcd have been proposed in the past. Also open to other key value stores such as dynamo

**Comment by tuunit** [comment]
On top you can just switch to KeyDB which is a multi threaded fork of Redis and the redis client library in go should be fully compatible with it.

**Comment by gabrielgbs97** [comment]
Valkey project may be an in-place alternative to Redis https://github.com/valkey-io/valkey

**Comment by tuunit** [comment]
Valkey is the official replacement sponsored by the linux foundation but KeyDB is actually more performant
