### ISSUE TITLE
[Bug]:/internal-auth/oauth2/auth not working

### ISSUE THREAD

**Issue by redboxstudio** [oauth2-proxy/oauth2-proxy#2574]
### OAuth2-Proxy Version

7.4.1

### Provider

keycloak-oidc

### Expected Behaviour

auth request should work /internal-auth/oauth2/auth
https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/nginx.conf

### Current Behaviour

/internal-auth/oauth2/auth  eror log nginx print  404

### Steps To Reproduce

configure the nginx config according to the published documentation

I have a working configuration based on auth_request /oauth2/auth
location /oauth2/auth
I saw changes in the configs and decided to update mine
but when changes are made
auth_request /internal-auth/oauth2/auth
location /internal-auth/
everything stops working

**Comment by redboxstudio** [comment]
[error] 13879#0: *81832886 auth request unexpected status: 404 while sending to client
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/d882c72e-fcdf-459d-a575-7b4b350a817d)
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/7893253/5d935191-e670-4539-82dc-ce6efe0a6909)

**Comment by JoelSpeed** [comment]
For anyone who finds this later, I think probably this needed the proxy-prefix option setting to move the location that oauth2 proxy expects its own paths to be accessed from
