### ISSUE TITLE
[Bug]: Possible README Inaccuracy

### ISSUE THREAD

**Issue by anonhostpi** [oauth2-proxy/oauth2-proxy#2577]
### OAuth2-Proxy Version

7.6.0

### Provider

None

### Expected Behaviour

_README states:_
https://github.com/oauth2-proxy/oauth2-proxy/blob/36f8dbcbccf254dbd7000c576c29a883ecf89cb0/README.md?plain=1#L29-L32

So, checking GOROOT with:
```bash
# go install github.com/oauth2-proxy/oauth2-proxy/v7@latest
ls $(go env GOROOT)/bin
```
should get (according to the docs)
```
oauth2-proxy
```

### Current Behaviour

On OpenWRT, when checking go root with:
```bash
# go install github.com/oauth2-proxy/oauth2-proxy/v7@latest
ls $(go env GOROOT)/bin
```

you get:

```
go     gofmt
```

If you check GOPATH:

```bash
# go install github.com/oauth2-proxy/oauth2-proxy/v7@latest
ls $(go env GOPATH)/bin
```

you get:

```
oauth2-proxy
```

### Steps To Reproduce

```bash
# OpenWRT 23.05.3 x86-64
# opkg update && opkg install golang

go install github.com/oauth2-proxy/oauth2-proxy/v7@latest

ls $(go env GOROOT)/bin
ls $(go env GOPATH)/bin
```

### Possible Solutions

Update the README

### Configuration details or additional information

I am unfamiliar with the nuances of golang, so I'm not entirely sure if this is caused by environment, or if the readme genuinely has an error.

Most OpenWRT implementations are single user, and use the root user heavily. My environment is the default x86-64 image, which uses root.

**Comment by anonhostpi** [comment]
> I am unfamiliar with the nuances of golang, so I'm not entirely sure if this is caused by environment, or if the readme genuinely has an error.

With that said, I am also not entirely familiar with what implications putting OAuth2-proxy in GOPATH may have over GOROOT.

I'm sure I will find out as play around with it.

**Comment by JoelSpeed** [comment]
I think you may be correct, I'd have expected that to be GOPATH and not GOROOT, wonder where/when that came in 🤔

**Comment by tuunit** [comment]
I think there always has been confusion between GOROOT and GOPATH in the go community 🤔

Isn't GOPATH to be deprecated in the future:
https://github.com/golang/go/issues/30329

**Comment by tuunit** [comment]
I just checked the blame history of it and indeed the mistake has been in the Readme since the beginning when it was developed at bitly.

Furthermore, I checked the golang faq / docs:

> Is the GOPATH variable being removed?
No. The GOPATH variable (set in the environment or by go env -w) is not being removed. It will still be used to determine the default binary install location, module cache location, and checksum database cache location, as mentioned at the top of this page.

Therefore, I would suggest let's just fix it.

**Comment by tuunit** [comment]
@anonhostpi thanks for making us aware of this really old inaccuracy.

Will be fixed with #2578

CC: @JoelSpeed

**Comment by anonhostpi** [comment]
To be fair, I'm probably going to be one of your few end users that uses the `go install` method without being a go developer.

Most of you go developer probably didn't even think twice about it.

**Comment by tuunit** [comment]
Anyways thank you for spotting it!
