### ISSUE TITLE
providers: azure: no support for cookie refresh in the code

### ISSUE THREAD

**Issue by slashbeast** [oauth2-proxy/oauth2-proxy#260]
## Expected Behavior
The cookie gets refreshed

## Current Behavior

No cookie gets refreshed, as provider lacks code for refresh and just defaults to returing false in bool context, oauth2_proxy terminate session and require user to re-login.

## Possible Solution

Implementing RefreshSessionIfNeeded function into azure provider.

## Steps to Reproduce (for bugs)

1.  Configure Azure/Office365 provider
2. Set cookie refresh
3. Look into logs for failed cookie refresh.

## Context

I wanted to take advantage of time-based group membership on the Active Directory, for that setting the cookie expire to 15 minutes and refresh to 10 minutes were supposed to give me a working solution with up to 15 minutes drift, however, as azure provider seems to lack code for cookie refresh, the moment oauth2_proxy want to refresh cookie, it fails to do so and in the process invalidate the session.

## Your Environment

oauth2_proxy behind nginx on AWS behind application load balancer.

- Version used: 4.0.0

**Comment by slashbeast** [comment]
This issue is still relevant.

**Comment by JoelSpeed** [comment]
Could this possibly be fixed by #308 ?

**Comment by slashbeast** [comment]
I think the https://github.com/pusher/oauth2_proxy/pull/278 is the fix

**Comment by slashbeast** [comment]
This issue is still relevant.

**Comment by slashbeast** [comment]
This issue is still relevant.
