### ISSUE TITLE
[Bug]: Docs - htpasswd-file description does not mention SHA1 encryption

### ISSUE THREAD

**Issue by anonhostpi** [oauth2-proxy/oauth2-proxy#2603]
### OAuth2-Proxy Version

N/A

### Provider

None

### Expected Behaviour

While reading over the docs and scouring through the source code to get more details about how OAuth2-Proxy works, I discovered that the htpasswd-file entry on the docs (and in the usage statements) have a discrepancy. They state that the htpasswd-file requires bcrypt, when according to the source code for the basic auth validator, both bcrypt *and SHA1* are supported:
https://github.com/oauth2-proxy/oauth2-proxy/blob/fc701bfd6a992bb074671b91ac89b50a79d3dc3d/pkg/authentication/basic/htpasswd.go#L154-L174

### Current Behaviour

Potentially incorrect docs:

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/130698314/7943c16f-1148-47c7-b5a6-fdea71663ad6)

Potentially incorrect usage statement:

https://github.com/oauth2-proxy/oauth2-proxy/blob/fc701bfd6a992bb074671b91ac89b50a79d3dc3d/pkg/apis/options/options.go#L139

### Steps To Reproduce

N/A

### Possible Solutions

Change the line to:

```md
...Entries must be created with `htpasswd -B` for bcrypt encryption or `htpasswd -s` for SHA1 encryption.
```

### Configuration details or additional information

I'm not completely familiar with the doc flow for this repo yet. Not sure if changes need to be made to both the flagset lines as well as the docs, or if there is some kind of automated flow that links them.

If I knew, I would just submit a PR instead of bothering anyone with a GH issue 😅

**Comment by anonhostpi** [comment]
> I'm not completely familiar with the doc flow for this repo yet. Not sure if changes need to be made to both the flagset lines as well as the docs, or if there is some kind of automated flow that links them.
> 
> If I knew, I would just submit a PR instead of bothering anyone with a GH issue 😅

Again, sorry. Not my best GH issue.

**Comment by JoelSpeed** [comment]
I believe this is deliberate. We used to support sha1 only, but it has proven to be insecure. We moved to bcrypt to allow a more secure hash, but kept the old hash as not to break existing users.

Documentation wise, we should consider sha1 deprecated and I hope we can remove it in a future release. So I think the docs can stay as they are.
