### ISSUE TITLE
[Bug]: 500 (Internal Server Error) on invalid cookie

### ISSUE THREAD

**Issue by Primexz** [oauth2-proxy/oauth2-proxy#2604]
### OAuth2-Proxy Version

7.6.0

### Provider

keycloak

### Expected Behaviour

If I change the sessionstore (e.g. Cookie Storage to Redis) Storage, I expect that no Internal Server Error (500) is displayed for the user.
Changing the session store changes the layout of a cookie, which means that old cookies can no longer be parsed.

As a user, I expect the sign-in page of the OAuth2 proxy to be displayed by default instead of the error page.

### Current Behaviour

If I currently change the session store as administrator, all users with an old cookie are currently shown an Internal Server Error (500).

If a user has a broken cookie (regardless of the value), an internal server error is currently displayed

### Steps To Reproduce

1. login with the provider
2. manipulate the session cookie (enter something wrong, e.g. "foobar")
3. reload the page
4. an Internal Server Error should be displayed.

### Possible Solutions

Forwarding to the OAuth2 provider if the cookie cannot be parsed.

**Comment by JoelSpeed** [comment]
A workaround for this would be to change the session cookie name when you change the backing store from cookie to redis
