### ISSUE TITLE
[Bug]: Infinite loop if the Csrf cookie is set twice

### ISSUE THREAD

**Issue by Primexz** [oauth2-proxy/oauth2-proxy#2606]
### OAuth2-Proxy Version

7.6.0

### Provider

None

### Expected Behaviour

If I have two invalid CSRF cookies as a user, I expect to be able to log in without deleting my cookies.

### Current Behaviour

As soon as the CSRF token is set twice, a user will end up in the endless loop and will no longer be able to log in without deleting their cookies.

![Screenshot 2024-04-10 at 15 13 59](https://github.com/oauth2-proxy/oauth2-proxy/assets/76482511/adf551bb-ce33-4450-a989-5159cf9f58b1)

https://github.com/oauth2-proxy/oauth2-proxy/assets/76482511/d4236318-53a1-4f98-8ef9-467deef9d904

### Steps To Reproduce

1. Set two cookies with the same name (preferably with two different domains, in this example the wildcard "." was used)
2. try to log in (you will see a 403)
3. try to press Login in the error form of the OAuth2 proxy
4. you will end up on the 403 page again

### Possible Solutions

The solution I have in mind is to search all cookies with the correct name to see if a matching CSRF cookie can be found.

**Comment by diegopazosrego** [comment]
I solved this bug adding this 2 options in the deployment of Oauth2-proxy @Primexz !

```
"--cookie-csrf-per-request=true",
"--cookie-csrf-expire=5m", 
``` 

After add this, you have to restart your deployment.
