### ISSUE TITLE
[Feature]: options for add files in /oauth2/static/

### ISSUE THREAD

**Issue by devildant** [oauth2-proxy/oauth2-proxy#2614]
### Motivation

My goal is to be able to put images, and files like a manifest file for webapps, in the static directory of oauth2-proxy (/oauth2/static/)
and use this in the login page (override)
`<link rel="manifest" href="/oauth2/static/custom/manifest.webmanifest" />`

for implementation, mount a volume directory in docker, and indicate via config the path to use as for page override (--custom-templates-dir)
the options could have the following name
--custom-statics-dir

### Provider

None

**Comment by tuunit** [comment]
We had similar requests in the past. This to me sounes like feature creep and we most likely aren't going to support this. Use existing solutions dedicated for providing static files like nginx and setup proper routing for your files.

@JoelSpeed any other opinion on this?

**Comment by tuunit** [comment]
Furthermore, don't we already have an option that serves static files anyway?

--custom-templates-dir	string	path to custom html templates?

**Comment by devildant** [comment]
> We had similar requests in the past. This to me sounes like feature creep and we most likely aren't going to support this. Use existing solutions dedicated for providing static files like nginx and setup proper routing for your files.
> 
> @JoelSpeed any other opinion on this?
for me it would be a gas factory, having to put an nginx server on the front end.
I use a reverse proxy on Synology but impossible to write the conf.
therefore this would amount to putting an nginx container in front of oauth2-proxy just for images and a manifest file.
Hence my feature request :p

it would just be a matter of being able to bind a volume, and its contents appear in a directory /oauth2/static/custom for example

> Furthermore, don't we already have an option that serves static html files anyway?
> 
> --custom-templates-dir string path to custom html templates?
> 
> anything further than that like images, css and etc. should be provided from somewhere else

yes i use it (--custom-templates-dir) to customize the login and error page and it works well, but unfortunately I cannot define manifest or images for certain meta tag which requires a file on the server (base64 does not work)

I tried to put my images and manifest files in the directory (custom-templates-dir), but I can't find a route to access them

**Comment by devildant** [comment]
with the customization of templates it seems logical to me to be able to define static files :)

**Comment by devildant** [comment]
...

**Comment by AyanamiAkaha** [comment]
came to this issue searching about why my style isn't applied

> Furthermore, don't we already have an option that serves static html files anyway?

Do I understand correctly that this works *only* for `error.html` and `sign_in.html`, and not the associated styles? Is there a way styles can be included? (I thought some sort of including css and js files would be available, if templating is available...)

The only way I managed to get the styling working (without adding yet another reverse-proxy layer for serving static files...) is to include it in the HTML itself, but this requires CSP with `style-src: unsafe-inline`.
