### ISSUE TITLE
[upstream with basic auth]: upstream may require basic auth

### ISSUE THREAD

**Issue by ptimofee** [oauth2-proxy/oauth2-proxy#2664]
### Motivation

Oauth2-proxy can be used to expose some (upstream) services through SSO to users.
I. e. as a proxy, that asks a user for SSO login and if it succeeds proxy sends requests to upstream service.
That upstream service may not support any kind of auth, so it's nice to have oauth2-proxy to protect it.
Or that upstream service may support some auth, but too simple one, like basic auth. Oauth2-proxy would help here as well, it just needs to support basic auth to talk to the upsteam.

`user` --sso--> `oauth2-proxy` --basicAuth--> `upstream`

My particular example is alertmanager. This is an opensource tool that supports only basic auth. I want a better authentication for alertmanager UI so I took oauth2-proxy and put it in front of it.
The only problem here is that by security requirement there still should be some auth between oauth2-proxy and alertmanager, even a basic one.

### Possible solution

N/A

### Provider

None

**Comment by rekup** [comment]
This is already possible e.g. by using `injectRequestHeaders`:

```yaml
injectRequestHeaders:
- name: Authorization
  values:
    - value: QmFzaWMgWkdWdGJ6cGtaVzF2
```
