### ISSUE TITLE
[Bug]: OIDC provider don't redeem access token after authorization request

### ISSUE THREAD

**Issue by YvannPONCE** [oauth2-proxy/oauth2-proxy#2671]
### OAuth2-Proxy Version

7.6

### Provider

oidc

### Expected Behaviour

The Oauth2 flow with Microsoft Azure AD should ask for access token on the /token endpoint after receiving the response of the /authorization

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/85893692/320cdd8d-b87d-4ffa-8d8d-8d9ab4888552)

### Current Behaviour

After the /authorization, oauth2 proxy directly redirect to the web application instead of asking for access and refresh token on the /token endpoint 

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/85893692/975875b9-c8bd-4a91-be01-480ccfe56501)

### Steps To Reproduce

Config on Kubernetes
---
server:
  BindAddress: '0.0.0.0:4180'
metricsServer:
  BindAddress: '0.0.0.0:44180'
injectResponseHeaders:
- name: X-Auth-Request-User
  values:
  - claim: oid
- name: X-Auth-Request-Email
  values:
  - claim: email
- name: X-Auth-Request-Preferred-Username
  values:
  - claim: preferred_username
- name: X-Auth-Request-Groups
  values:
  - claim: groups
providers:
- clientID: ${OAUTH2_PROXY_CLIENT_ID}
  clientSecret: ${OAUTH2_PROXY_CLIENT_SECRET}
  id: oauth2-proxy
  redeemURL: https://login.microsoftonline.com/{tenantid}/v2.0/oauth2/token
  oidcConfig:
    audienceClaims:
    - aud
    emailClaim: email
    groupsClaim: groups
    insecureSkipNonce: false
    issuerURL: https://login.microsoftonline.com/tenantid/v2.0
    userIDClaim: email
  provider: oidc
  scope: "openid profile email offline_access"
upstreamConfig:
  upstreams:
  - id: static
    path: /
    static: true

**Comment by stanislav-c** [comment]
I believe this part is done server-side, not client-side. Check the [redeemCode](https://github.com/oauth2-proxy/oauth2-proxy/blob/f8efdbae5fadd312fe528213c48277387a4078c4/oauthproxy.go#L879) logic and its [Azure implementation](https://github.com/oauth2-proxy/oauth2-proxy/blob/66bfd8ebd57d6ef7d51d2e1ecbf0d3a1091c7308/providers/azure.go#L154).
