### ISSUE TITLE
[Support]: Syntax for specifying lists in env variables

### ISSUE THREAD

**Issue by ginkel** [oauth2-proxy/oauth2-proxy#2672]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Current Behaviour of your Problem

Hi there,

I was wondering what would be the correct syntax to specify multiple values via an env variable for a config option that supports lists. For example, `--skip-auth-route` (which should become `OAUTH2_PROXY_SKIP_AUTH_ROUTES`). But what about the value(s)?

I know that env variables will become deprecated, but I have some legacy deployment that I'd like to continue to use for now.

Thanks!

### Configuration details or additional information

n/a

**Comment by aliktb** [comment]
Hi 👋 

I had the same issue. It doesn't seem to be documented anywhere (that I could find) but it seemed to work when I set it as a comma-separated list (no spaces) in my Kubernetes configmap. E.g.

```
OAUTH2_PROXY_EMAIL_DOMAINS: "emaildomain1.com,emaildomain2.com"
```

I assume running the application outside of K8s/Docker would still work like this?

**Comment by aliktb** [comment]
Regarding:

> I know that env variables will become deprecated, but I have some legacy deployment that I'd like to continue to use for now.

Have you found documentation somewhere saying env vars are/will be deprecated? I know the [alpha config](https://oauth2-proxy.github.io/oauth2-proxy/configuration/alpha-config) switches from TOML to YAML but not sure about environment variables themselves that are prefixed `OAUTH2_PROXY_`

**Comment by TuningYourCode** [comment]
this issue can be closed as the documentation was adjusted to include information how to specify lists.

**Comment by tuunit** [comment]
Furthermore, two weeks ago I added all toml attributes to the documented config options. Which are the basis for the environment variable names and include the plural form.
