### ISSUE TITLE
Integration with WSO2 Identity Server provider

### ISSUE THREAD

**Issue by masalinas** [oauth2-proxy/oauth2-proxy#2678]
### Motivation

Is possible integrate outh2-proxy with WSO2 Indentity Server provider?

### Provider

new provider

**Comment by tuunit** [comment]
Please try to use our docs:
https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/openid_connect

And WSO2 docs:
https://is.docs.wso2.com/en/latest/guides/authentication/oidc/discover-oidc-configs/
