### ISSUE TITLE
[Bug]: --skip-auth-route fails to match URL after first slash

### ISSUE THREAD

**Issue by SSchwaiger** [oauth2-proxy/oauth2-proxy#2687]
### OAuth2-Proxy Version

7.6.0

### Provider

keycloak

### Expected Behaviour

--skip-auth-route ^/develop/abc does exclude /develop/abcdef route

### Current Behaviour

--skip-auth-route ^/develop/abc does **not** exclude /develop/abcdef route

### Steps To Reproduce

I need to exclude a path from authentication.

For this I added --skip-auth-route ^/develop/abc to exclude /develop/abcdef routes.

Unfortunately, the regex is not matched. If I set ^/develop/ as exclude regex, it works.

**Comment by janbaer** [comment]
I have a similar problem with trying to skip auth for `/healthcheck` but it's not working. I see in the logs that the configuration is accepted `Skipping auth - Method: ALL | Path: /healthcheck` but when I query this path, I still get a 302 redirect status code.
