### ISSUE TITLE
[Bug]: Cookie expiration causes CORS problems

### ISSUE THREAD

**Issue by LuckyChen666** [oauth2-proxy/oauth2-proxy#2708]
### OAuth2-Proxy Version

v7.5.1

### Provider

None

### Expected Behaviour

When the cookie expires, re-authentication through SSO should not cause CORS problems

### Current Behaviour

![image](https://github.com/user-attachments/assets/17978ae3-fb11-403e-9650-9e2c758fbb0f)
When I access my own interface, the cookie expires and returns 302, requiring re-authentication in first url.
As you can see, ingress-nginx wants to re-authenticate with SSO, but since the authentication URL and service URL are from different sources, a cors error occurs.
Since the request was intercepted by the oauth2 proxy, my backend could not receive any messages at all, and could not do anything.
This is my ingress config:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "https://sso.int.xxxx.com/oauth2/start?rd=https://$host$uri"
    nginx.ingress.kubernetes.io/auth-url: "https://sso.int.xxxx.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/auth-response-headers: >-
      authorization, x-auth-request-user, x-auth-request-email,
      x-auth-request-group, x_auth_request_access_token,
      Access-Control-Allow-Origin, Access-Control-Allow-Methods,
      Access-Control-Allow-Headers
```
But refreshing the page will not cause this problem.

### Steps To Reproduce

1. set ingress-nginx annotations in ingress
2. Start the service, 
3. clear cookies, and 
4. call any api

### Possible Solutions

oauth2 proxy supports cors and adds Access-Control-Allow-Origin header

**Comment by JcGKitten** [comment]
@LuckyChen666  could you figure out something yet? I'm facing the same problems.
