### ISSUE TITLE
[Feature]: Hashbang URLs encoding

### ISSUE THREAD

**Issue by gaelayo** [oauth2-proxy/oauth2-proxy#2716]
### Motivation

If the upstream URL looks like `https://mysite.com/#example`, (which seems to  be quite frequent with single page applications) then, because what is after the `#` character is not sent to the server, `oauth2-proxy` would store a state like `something:https://mysite.com/` dropping what is after the hash. When we return to oauth2-proxy after the authentication flow, we will be redirect to `https://mysite.com/`, without the hashbang URL. 
Is there a way to circumvent this ? By having `oauth2-proxy` or another middleware using a small JS script to encode the hashbang state somehow, before having `oauth2-proxy` redirecting the request ? 
Because `oauth2-proxy` is often placed *before* the application, I believe it is not possible to manage this application side (expect dropping the use of hashbang URLs altogether).

Is there a known way to manage hashed URLs with oauth2-proxy ?

Thank you very much

### Provider

None

**Comment by JoelSpeed** [comment]
In case anyone comes here, I believe if you leverage the login page (without the `--skip-provider-button`), then I believe it uses javascript to capture the URL fragement, and therefore can be preserved. But JS is the only way we can achieve this as far as I'm aware, any solution that redirects the first request will lose the fragment
