### ISSUE TITLE
[Support]: Configure OIDC Provider to enable support for Okta DPoP

### ISSUE THREAD

**Issue by rastogin-rp** [oauth2-proxy/oauth2-proxy#2722]
### OAuth2-Proxy Version

7.6.x

### Provider

oidc

### Current Behaviour of your Problem

We are currently facing an issue where we receive `"invalid_dpop_proof: The DPoP proof JWT header is missing"` when configuring the OIDC provider in Oauth2Proxy to work with Okta Web App Client [^1] with the `DPoP` (Demonstrating Proof of Possession) option enabled.

Given Okta Web Client Apps now support enabling DPoP [^2], the configuration example provided in the documentation only works when `DPoP` is disabled. Any guidance on how to configure OIDC to support Okta `DPoP` option will be valuable, as the provided documentation does not cover DPoP-specific settings.

**Expected Result** - The OIDC provider should be able to handle DPoP with the Okta Client without issues, if needed, through the use of an additional environment variable/flag to enforce this.

**Actual Result** - The configuration fails with the error "The DPoP proof JWT header is missing." post-authentication leading to a `500 error`.

[^1]: [Oauth2Proxy 7.6.x Okta OIDC Documentation](https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/openid_connect#okta)
[^2]: [Okta DPoP Support Release Notes](https://help.okta.com/en-us/content/topics/releasenotes/production.htm#panel2).

### Configuration details or additional information

We follow the same configuration setup as shown in the official Oauth2Proxy Documentation for setting up [OIDC Provider with Okta Web App Client](https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/openid_connect#okta).

```yaml
# config.yaml

provider = "oidc"
redirect_url = "https://example.corp.com/oauth2/callback"
oidc_issuer_url = "https://corp.okta.com/oauth2/abCd1234"
upstreams = [
    "https://example.corp.com"
]
email_domains = [
    "corp.com"
]
client_id = "XXXXX"
client_secret = "YYYYY"
pass_access_token = true
cookie_secret = "ZZZZZ"
skip_provider_button = true
```

### Steps To Reproduce

1. Follow the [Oauth2Proxy's OIDC Okta Configuration Guide](https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/openid_connect#okta) for setting up the Okta Web App Client.
2. Create an OIDC Provider config following the [Oauth2Proxy's OIDC Okta Configuration Guide](https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/openid_connect#okta).
3. Over on Okta Web App Client, [select/enable `Require Demonstrating Proof of Possession (DPoP) header in token requests`](https://developer.okta.com/docs/guides/dpop/oktaresourceserver/main/#create-an-app) checkbox as shown below:

   ![image](https://github.com/user-attachments/assets/4deaaa29-7820-489b-a465-c40b433c6d3c)

**Comment by rastogin-rp** [comment]
@JoelSpeed - It's nice to e-meet you, I noticed that you are one of the principal engineers on this project, if you can point us in the right direction it would be extremely helpful.

**Comment by tuunit** [comment]
Hi @rastogin-rp,

we currently do no support this feature of the oauth2.0 specification and there don't exist any active plans or open PRs to add it as of now.

**Comment by rastogin-rp** [comment]
Thank you for your quick response @tuunit, :) as the DPoP option is not supported do you have any recommendations on what would be the best course of action? Is it ok to keep it disabled given how the tokens are handled inside of oauth2-proxy?

**Comment by tuunit** [comment]
Demonstrate Proof of Possession is a rather new addition to the OAuth2 specification and has only been proposed in December 2023: https://datatracker.ietf.org/doc/html/rfc9449

Therefore most providers don't support it yet anyways and most no one has adopted it yet. As long as you deem the current standard used by everyone else as security enough. You should be fine without activating it.

**Comment by rastogin-rp** [comment]
Thank you so much for the document reference, I will make sure to pass this along internally to my teammates! 

P.S. Awesome solution, really love the simplicity it offers. If you all have any swag/stickers would love to show it off, and for sure I will be relaying the buzz forward to all my teammates and friends. :)

**Comment by porobd** [comment]
Any plans to support DPoP in oauth2-proxy in the near future ?
