### ISSUE TITLE
[Bug]: trusted_ip conf doesn't bypass authentication for trusted ips

### ISSUE THREAD

**Issue by cat-paylead** [oauth2-proxy/oauth2-proxy#2728]
### OAuth2-Proxy Version

v7.6.0

### Provider

keycloak-oidc

### Expected Behaviour

Our oauth2-proxy enables authentication to a service via keycloak-oidc.
This service needs to be accessible without authentication within our private network.

According to the documentation, this should be possible using the following configuration:
```
real_client_ip_header = "X-Forwarded-For" (we checked, this header is set)
reverse_proxy = "true"
trusted_ips = "10.43.0.0/16"
```

### Current Behaviour

However, with this configuration, oauth2-proxy manages correctly the human users authentication to the service via keycloak-oidc, but it blocks access to the service from within the private network.

Here is the error message we get:
```
curl -v -k https://10.43.0.121
...
< HTTP/1.1 302 Found
...
< Location: https://auth.xxxr/auth/realms/xxx/protocol/openid-connect/auth?xxx
...
```

And here are the oauth2-proxy logs:
```
Aug 02 14:35:38 xxx oauth2-proxy[1710370]: [2024/08/02 14:35:38] [oauthproxy.go:1017] No valid authentication in request. Initiating login.
Aug 02 14:35:38 xxx oauth2-proxy[1710370]: 10.43.0.20 - 57b14df4-c488-4631-842d-b5bc03c6c262 - - [2024/08/02 14:35:38] 10.43.0.121 GET - "/" HTTP/1.1 "curl/7.88.1" 302 421 0.001
```

For reference, this is the oauth2-proxy log when a human user connects to the service:
```
Aug 02 15:16:07 nexus-scw-02 oauth2-proxy[1711323]: xxx - 0463cc7b-8ffe-4b61-ac37-68663e3ba4d4 - user@email [2024/08/02 15:16:07] [AuthSuccess] Authenticated via OAuth2: Session{xxx}
```

When we set `reverse_proxy = false`, the curl goes through, but human users can't connect to the service via oidc, local login and password are needed.

### Steps To Reproduce

1. Set up a keycloak instance, version 24.0.1
2. Set up any service that uses SSO
3. Install oauth2-proxy version v7.6.0 on the same server with the following configuration:
```
cookie_secret = "xxx"
provider = "keycloak-oidc"
client_id = "xxx"
client_secret = "xxx"
oidc_issuer_url = "xxx"
upstreams = "http://127.0.0.1:8081"
email_domains = "xxx"
skip_provider_button = "true"
code_challenge_method = "S256"
trusted_ips = "10.43.0.0/16"
reverse_proxy = "true"
real_client_ip_header = "X-Forwarded-For"
allowed_groups = ""
https_address = ":443"
tls_cert_file = "xxx.cert.pem"
tls_key_file = "xxx.key.pem"

```
4. On another machine in the same private network, try to access the machine hosting the service and oauth2-proxy:
`curl -v -k https://10.xx.xx.xx`

### Possible Solutions

We have no idea why we don't get the expected behavior.

**Comment by bjencks** [comment]
Are the clients in the trusted network also connecting through the reverse proxy, or are they connecting directly? If `reverse_proxy` is enabled, oauth2-proxy will *only* get client IPs from the header; if the header is unset it will never match the trusted IPs.

**Comment by cat-paylead** [comment]
Thanks, adding a reverse proxy for the clients in the trusted network solved the issue!
