### ISSUE TITLE
[Feature]: Multi-tenant / separate config per upstream

### ISSUE THREAD

**Issue by ltickett** [oauth2-proxy/oauth2-proxy#2742]
### Motivation

I want to provide access to different private sites to different people:

- Site1 (company A and company B)
- Site2 (company A and company C)
- Site3 (company C)

It sounds like this overlaps a little with https://github.com/oauth2-proxy/oauth2-proxy/issues/926 but from what I can see that's simply about allowing multiple providers but not tying each provider to a different config/upstream.

As a first step being able to tie upstreams, oidc config and email-domains together would probably work.

But then going further with trusted ips etc

If it helps, i'm currently testing running Oauth2-Proxy in AWS AppRunner (which I figure should hopefully not cost much more than $3/mo).

Keep up the good work. I hope I may be able to help contribute, but i'm primarily a C# / Ruby-on-Rails / JavaScript developer :/

### Provider

None

**Comment by tuunit** [comment]
Already addressed in:
https://github.com/oauth2-proxy/oauth2-proxy/pull/1923
