### ISSUE TITLE
[Support]: Possibilities of using "allowed_groups" and "allowed_users" together with "auth_url"

### ISSUE THREAD

**Issue by sivarama-p-raju** [oauth2-proxy/oauth2-proxy#2749]
### OAuth2-Proxy Version

v7.6.0

### Provider

azure

### Current Behaviour of your Problem

We have configured ingress resource in Kubernetes to use oauth2-proxy auth url:

nginx.ingress.kubernetes.io/auth-url: https://<oauth2-proxy-ingress-url>/oauth2/auth?allowed_groups=AAD-group

This works for most of the users in the group. However, there are a few users in the group that are part of a huge # of Groups, due to which the token received on authentication with Azure AD does not contain any groups they are part of, as a result of which they get a "403 Forbidden" - as equal to not being part of the AAD group.

We have a case ongoing with Azure support but there has been no progress yet.

I believe we are hit with the issue described [here](https://github.com/gravitational/teleport/issues/21795)

As a workaround, I tried to use "allowed_emails", and see that this helps for those users that fail when "allowed_groups" is used, who are part of more than 200 groups.

nginx.ingress.kubernetes.io/auth-url: https://<oauth2-proxy-ingress-url>/oauth2/auth?allowed_emails=user-email-ID

My question is, are there possibilities of using both "allowed_groups" and "allowed_emails" together on the same "auth_url" annotation ?

Example:

nginx.ingress.kubernetes.io/auth-url: https://<oauth2-proxy-ingress-url>/oauth2/auth?allowed_groups=AAD-group&allowed_emails=user-email-ID

Request you to please let me know what other options are possible, if the above is not possible.

Thanks a lot in advance.

Thanks and regards,
Sivarama Raju P

### Configuration details or additional information

NA

Please let me know if more information is needed and I will be happy to provide.

### Steps To Reproduce

This can be reproduced for those users who are part of a large number of AD groups (> 200).

**Comment by tuunit** [comment]
Hi @sivarama-p-raju,

why didn't you just try to use both parameters together? :)

But nevertheless, yes indeed you can use them together:
![image](https://github.com/user-attachments/assets/7016ac76-cf10-4e15-a136-8c4a1f6dab14)

They are processed sequentially and if either constraint matches the users will be allowed to go through.

**Comment by sivarama-p-raju** [comment]
Hi @tuunit 

Thank you for your response.

I did try to use them together, but it does not work. When I only have "allowed_emails", then it works but not together with "allowed_groups":

- Does not work (403 forbidden):

```
nginx.ingress.kubernetes.io/auth-url: https://<oauth2-ingress-url>/oauth2/auth?allowed_groups=<group>&allowed_emails=<email ID>
```

Below is the corresponding log from oauth2-proxy:
```
<email ID> [2024/08/21 10:57:08] <oauth2-ingress-url> GET - "/oauth2/auth?allowed_groups=<group>&allowed_emails=<email ID>" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" 403 10 0.000
```

- Works:

```
nginx.ingress.kubernetes.io/auth-url: https://<oauth2-ingress-url>/oauth2/auth?allowed_emails=<email ID>
```

Below is the corresponding log from oauth2-proxy:
```
<email ID> [2024/08/21 11:01:02] <oauth2-ingress-url> GET - "/oauth2/auth?allowed_emails=<email ID>" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" 202 0 0.000
```

Could you please let me know if the annotation is incorrect somehow and needs correction ?

Thanks and regards,
Sivarama Raju P

**Comment by tuunit** [comment]
@sivarama-p-raju mhh. In this case I guess it is an conjuction (and) operation and not an or operation. Meaning using both parameters together technically works but now oauth2-proxy expects your user to have one of the emails **and** to be in one of the groups.

**Comment by tuunit** [comment]
@sivarama-p-raju mhh. In this case I guess it is an conjuction (and) operation and not an or operation. Meaning using both parameters together technically works but now oauth2-proxy expects your user to have one of the emails **and** to be in one of the groups.

I don't think there is anything you can configure to make this work as you expect. 

One hacky option / workaround would be to have another nginx/openresty layer in-between your ingress and oauth2-proxy

```
ingress <-> custom reverse proxy deployment <-> oauth2-proxy
|
v
your service
```

and configure your nginx/openresty to filter for specific emails using a lua script and the headers send back by oauth2-proxy to then either respond with 200 or 403

**Comment by sivarama-p-raju** [comment]
Please note that I got a workaround for this issue by configuring the Azure App to use an optional claim -> Edit Group Claims -> Groups assigned to the application.

I then added all the groups that are used with "allowed_groups" on all of our ingress resources under "Users and groups" to the Azure app for Oauth2-proxy.

With this, the token received on authentication with Azure only contains the groups that the user is part of that are added to the "Users and groups" on the Azure App for OAuth2-proxy.

This is not ideal, as now any new group that needs allowed, will first need to be added to the Azure App before it can be used with "allowed_groups". However, this unblocks us.
