### ISSUE TITLE
[Support]: provider_ca_file - bad key name for toml in docs

### ISSUE THREAD

**Issue by mikolajtkaczyk64** [oauth2-proxy/oauth2-proxy#2778]
### OAuth2-Proxy Version

7.6.x

### Provider

keycloak-oidc

### Current Behaviour of your Problem

* '' has invalid keys: provider_ca_file

### Configuration details or additional information

The key in toml in docs should be in plural form as it can be a list of ca files:
provider_ca_file -> **provider_ca_files**

### Steps To Reproduce

1. Create a configuration file with key: provider_ca_file
2. Run OAuth2-Proxy
3. View logs

**Comment by tuunit** [comment]
Do you want to fix it yourself in a PR?
