### ISSUE TITLE
502 Bad Gateway after successful login

### ISSUE THREAD

**Issue by gangadharjannu** [oauth2-proxy/oauth2-proxy#2783]
### OAuth2-Proxy Version

7.6.0

### Provider

keycloak-oidc

### Expected Behaviour

redirect to app as logged in 

### Current Behaviour

502 Bad Gateway with below URL

https://bank1.localho.st/oauth2/callback?state=o945plKg-UhUOclaX4nkrYMSktb8CRCq_61qoyGmbpk%3A%2F&session_state=18f28f36-1e46-4ca2-8fed-75a175b2581b&iss=https%3A%2F%2Fbank1-keycloak.localho.st%2Frealms%2Fmyrealm&code=d1817f20-9a5c-4503-8488-4e2301519c4f.18f28f36-1e46-4ca2-8fed-75a175b2581b.58819c4f-6b8a-4e02-ae8a-3859e660ffee

And the logs from oauth2 proxy

```
127.0.0.1 - 0a3eebb0eb3a17bf61d7ef3cd28ef157 - - [2024/09/18 12:21:27] bank1.localho.st GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 401 13 0.000
127.0.0.1 - 199d76eb03f0161bc50bc66d4ffcce2f - - [2024/09/18 12:21:27] bank1.localho.st GET - "/oauth2/sign_in?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 200 9316 0.001
127.0.0.1 - 039d34d550010d393bc45f3c1cde8483 - - [2024/09/18 12:21:27] bank1.localho.st GET - "/oauth2/static/css/bulma.min.css" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 200 207302 0.016
127.0.0.1 - 59299b7984871d90db1b58dc0d18cf5d - - [2024/09/18 12:21:28] bank1.localho.st GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 401 13 0.000
127.0.0.1 - 66d45a19bd1c18edf3478d885db3a8d2 - - [2024/09/18 12:21:28] bank1.localho.st GET - "/oauth2/sign_in?rd=%2Ffavicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 200 9338 0.016
127.0.0.1 - c9632a20f9ef4f10625a0218ad664821 - - [2024/09/18 12:21:33] bank1.localho.st GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 302 421 0.001
127.0.0.1 - 68888cbd04dac50e7e241fffd6abf8d3 - myuser@bank1-keycloak.localho.st [2024/09/18 12:21:34] [AuthSuccess] Authenticated via OAuth2: Session{email:myuser@bank1-keycloak.localho.st user:4ef8d537-1e0c-43b0-9843-d4b2d69fa9cf PreferredUsername:myuser token:true id_token:true created:2024-09-18 12:21:34.669695 +0000 UTC m=+1538.474146001 expires:2024-09-18 12:26:34.669175 +0000 UTC m=+1838.473656001 refresh_token:true groups:[role:default-roles-myrealm role:offline_access role:uma_authorization role:account:manage-account role:account:manage-account-links role:account:view-profile]}
127.0.0.1 - 68888cbd04dac50e7e241fffd6abf8d3 - - [2024/09/18 12:21:34] bank1.localho.st GET - "/oauth2/callback?state=oFt9m_5ZNnu6GlMkn4QpONCRQO2NNLtabPxXS7N6p7A%3A%2F&session_state=18f28f36-1e46-4ca2-8fed-75a175b2581b&iss=https%3A%2F%2Fbank1-keycloak.localho.st%2Frealms%2Fmyrealm&code=9d947b4e-0bd1-4be7-989e-a06237e55893.18f28f36-1e46-4ca2-8fed-75a175b2581b.58819c4f-6b8a-4e02-ae8a-3859e660ffee" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" 302 24 0.020
```

### Steps To Reproduce

1. Set up oauth2 proxy 7.6.0 in K8s
2. Set up keycloak in kubernetes
3. Configure keycloas as shown in https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/keycloak_oidc
4. Configure oauth2-proxy as shown in https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/keycloak_oidc
5. Setup a front-end with nginx, add the required annotations
6. Access front-end
7. It redirects you to oauth2 login page
8. Click on "Sign in with Keycloak OIDC"
9. You see 502 Bad Gateway

### Possible Solutions

add debug information on oauth2 proxy side why it is failing

### Configuration details or additional information

This is similar to the error https://github.com/oauth2-proxy/oauth2-proxy/issues/646 but I don't see any error log neither at oauth2-proxy nor at keycloak. 

I also tried adding `nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"` at UI ingress, oauth2-proxy ingress but none seems to work.

I am using `k8s`, `helm`, `nginx`

oauth2-proxy config:

```
email_domains = "bank1-keycloak.localho.st"
provider = "keycloak-oidc"
redirect_url = "https://bank1.localho.st/oauth2/callback"
oidc_issuer_url = "https://bank1-keycloak.localho.st/realms/myrealm"
skip_oidc_discovery = true
login_url = "https://bank1-keycloak.localho.st/realms/myrealm/protocol/openid-connect/auth"
redeem_url = "http://keycloak.keycloak.svc.cluster.local:8080/realms/myrealm/protocol/openid-connect/token"
oidc_jwks_url = "http://keycloak.keycloak.svc.cluster.local:8080/realms/myrealm/protocol/openid-connect/certs"
code_challenge_method = "S256"
show_debug_on_error = true
```
oauth2-proxy env:

```
OAUTH2_PROXY_CLIENT_ID : myclient
OAUTH2_PROXY_CLIENT_SECRET : pEsVlV6CY7RvSxfUBzAi2dzE8H4RTOCq
OAUTH2_PROXY_COOKIE_SECRET : enAxSVBaYURSVHVuWUhUUDkzQkk2ckNhR21xSHFhdXo=
```
keycloak config:

realm name: myrealm
client id: myclient
client secret: pEsVlV6CY7RvSxfUBzAi2dzE8H4RTOCq
keycloak url: https://bank1-keycloak.localho.st

**Comment by gangadharjannu** [comment]
Passing 256k to oauth2-proxy NGINX config worked

**Comment by mehdi-eaton** [comment]
> Passing 256k to oauth2-proxy NGINX config worked

where you passed this? @gangadharjannu

**Comment by mateuszdrab** [comment]
> > Passing 256k to oauth2-proxy NGINX config worked
> 
> where you passed this? [@gangadharjannu](https://github.com/gangadharjannu)

`nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"` in annotations of the oauth-proxy ingress resource

Just solved my issue with the same annotation
