### ISSUE TITLE
Helm chart - site not found - github pages gone

### ISSUE THREAD

**Issue by davidroth** [oauth2-proxy/oauth2-proxy#2849]
https://oauth2-proxy.github.io/manifests as documented [here](https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy) returns a 404

![image](https://github.com/user-attachments/assets/3dd3b1d2-e8cf-4ccb-a798-3767ad029ad8)

**Comment by FelipeEmerimRandon** [comment]
In our case, we see the page as expected
![image](https://github.com/user-attachments/assets/f2445708-52a4-4f5c-906c-10c2112178c7)

But we receive a 404 when accessing the index.yaml file

**Comment by janaki-sasidhar** [comment]
> In our case, we see the page as expected ![image](https://private-user-images.githubusercontent.com/165281086/385276332-f2445708-52a4-4f5c-906c-10c2112178c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTM2OTUsIm5iZiI6MTczMTQxMzM5NSwicGF0aCI6Ii8xNjUyODEwODYvMzg1Mjc2MzMyLWYyNDQ1NzA4LTUyYTQtNGY1Yy05MDZjLTEwYzIxMTIxNzhjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxMjA5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzYxNjA4Y2Y5NjVmNGE1M2E3YmU2NjgyNjE2ZTQ2YzM2MzU5ZGNmNzU0NzUzM2NiNjk5MDJhZTIyZWQzM2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zSVWYNRJ9D0hhmanOKXvmgjjtVi6NK__CNd76FS1hlQ)
> 
> But we receive a 404 when accessing the index.yaml file

same here. index.yaml doesnt work

**Comment by davidroth** [comment]
tracked here: https://github.com/oauth2-proxy/manifests/issues/252

**Comment by tuunit** [comment]
Issue has been resolved!
