### ISSUE TITLE
[Support]: How does it compare to vouch-proxy

### ISSUE THREAD

**Issue by adjenks** [oauth2-proxy/oauth2-proxy#2866]
### OAuth2-Proxy Version

latest

### Provider

keycloak-oidc

### Current Behaviour of your Problem

Trying to choose an nginx auth proxy. I found this one and also:https://github.com/vouch/vouch-proxy

How is this project different from vouch-proxy?

### Configuration details or additional information

They seem to do pretty much the same thing, no?

**Comment by tuunit** [comment]
If you want to discuss different solutions please use an appropriate channel like our slack channel. These support issues are meant to ask for help regarding the configuration of oauth2-proxy and not to discuss another software solution.

I personally have never heard of vouch proxy before but it seems to do fairly similar things. I cannot comment on the extent of its features.
