### ISSUE TITLE
Additional Tests for X-Forwarded-Proto

### ISSUE THREAD

**Issue by jmickey** [oauth2-proxy/oauth2-proxy#294]
PR #285 introduces additional logic that checks if the `X-Forwarded-Proto` header is set before redirecting to HTTPS if the `force-https` option is set to `true`. 

This code will need some additional tests to cover the likely failure scenarios. E.g.

- Upstream proxy connects over TLS, but `X-Forwarded-Proto` is `http`. This should not redirect.
- Upstream proxy terminates HTTPS and sets `X-Forwarded-Proto` to `https`.
- Both of the above are true - Upstream proxy connects over TLS and `X-Forwarded-Proto` is `https`.

**Comment by jmickey** [comment]
BAD BOT, NO CLOSEY

**Comment by jmickey** [comment]
![I will destroy you gif](https://media.giphy.com/media/pBk8lbm68n23S/giphy.gif)

**Comment by JoelSpeed** [comment]
@jmickey do you think this was resolved by #619?

**Comment by jmickey** [comment]
I was thinking about this the other day when I reviewed the PR - yes I think this is sorted now. I will close the issue!
