### ISSUE TITLE
Not working with Rundeck?

### ISSUE THREAD

**Issue by dennisbrouwer91** [oauth2-proxy/oauth2-proxy#333]
Hi,

I'm trying to setup oauth2_proxy in front of Rundeck, as described on their documentation you can use the preauthentication https://docs.rundeck.com/docs/administration/security/authentication.html#preauthenticated-mode-using-headers

Login through Okta is working as expected and in the oauth2_proxy logs i can see i'm logged in. But for some reason Rundeck is redirecting me to the /user/login form again.
Anyone here has any expierence with Rundeck + oauth2_proxy?

**Comment by dcarrion87** [comment]
I'm currently working through this at the moment too. Samples out there just do not work. Will drop notes back here as I figure it out.

**Comment by rnsc** [comment]
hello @dcarrion87 , had any luck with your integration?

**Comment by leshik** [comment]
I posted my solution here: https://github.com/rundeck/rundeck/issues/5656#issuecomment-621059856

**Comment by danifr** [comment]
I think OP config might be wrong. Hard to know from the original message.
Anyway, what I am experiencing is, authentication works fine BUT roles are not passed correctly.

Therefore Rundeck gives you this error:
![image](https://user-images.githubusercontent.com/7135482/80578154-5c3b8f00-8a08-11ea-9b06-02dadb723452.png)

I believe this is a Rundeck bug and not a oauth2_proxy one.

**Comment by leshik** [comment]
Rundeck works fine if you pass correct headers. I'd suggest putting `httpbin` behind the `oauth2-proxy` instead of rundeck, then examining headers.

**Comment by mkhpalm** [comment]
Posted an updated/simplified solution here: https://github.com/rundeck/rundeck/issues/5656#issuecomment-1129414985
