### ISSUE TITLE
Support username list

### ISSUE THREAD

**Issue by tg44** [oauth2-proxy/oauth2-proxy#342]
Some of the providers (github/gitlab) have a [GetUserName](https://github.com/pusher/oauth2_proxy/blob/7663565cd3ebdfffa2002e8b0664cff41a2faa51/providers/provider_default.go#L114) implementation. It would be straightforward to use a username list as access control. (Something like: `AUTHENTICATED_USERNAMES=you,me,others`) Also for shorter lists, it would be nice to feed the allowed emails as a comma-separated list instead of a file.

**Comment by JoelSpeed** [comment]
Hey @tg44, what is the benefit/use case for this that differs from having groups authenticated? I've tried managing individuals on systems like this in the past and it's often cumbersome. Managing the authenticated users via a group is the way I've tended to go in the past (updating a GitHub group vs deploying an update to the config of an application)

If there's a good use case, I don't think this would add much or be too hard to implement

**Comment by tg44** [comment]
My use-case is that we are not an organization, just random devs. I don't want to make a orgs/groups just to share some site, or pieces of my dev infra. I think this could be really useful for not closely related freelancers. (Yes as a freelancer I have a dev infra :) )

**Comment by yyoshiki41** [comment]
I create a pr (https://github.com/pusher/oauth2_proxy/pull/421) that fixes this issue.
Currently, my dev environment works well.
