### ISSUE TITLE
Redirection target for Force HTTPS not always useful

### ISSUE THREAD

**Issue by cfra** [oauth2-proxy/oauth2-proxy#348]
Checking the 4.1.0 update for https://github.com/cfra/heroku-buildpack-oauth2-proxy I ran into an issue again with cookies not being set on HTTPS as described in #259.

Happily I saw that this feature request has been implemented in #285 and enabled it. However, this caused me to be stuck in a redirect loop.

## Expected Behavior

oauth2 proxy should redirect to the same URL but with HTTPS as schema, or possibly a user-defined entry-point which is also a full URL with protocol spec.

## Current Behavior

oauth2 proxy redirects to the configured HTTPS address, so to ":443" in my case.
The HTTPS address will usually not be a valid redirection target.

Also, even if this worked, we would lose the path information of the original request during the redirect.

## Possible Solution

a) Redirect to the original URL but with schema replaced by "https".
Not sure if this works if oauth2-proxy is running behind a reverse proxy as on Heroku.

b) Have a user configurable destination `httpsRedirectionTarget` and redirect to
`httpsRedirectionTarget + pathOfOriginalUrl`.

**Comment by cfra** [comment]
I am still facing this issue.
I still feel that redirecting to the HTTPS address is not useful in many cases.

**Comment by JoelSpeed** [comment]
I'd consider this to be a bug, I think we need to come up with some resolution for this

**Comment by JoelSpeed** [comment]
Does anyone have time to look into this?
