### ISSUE TITLE
404 after successful logging to okta  Traefik ingress

### ISSUE THREAD

**Issue by milijander88** [oauth2-proxy/oauth2-proxy#349]
I got 404 after successful logging to okta I am using Treafik ingres.

This is from logs of oauth proxy :

```

> 121212- -sic@test [2df020/01/12 09:00:07] auth-monitoring.mongodb.test.20test GET - "/oauth2/auth_or_start?rd=https://alertmanager-monitoring.mongodb.test.20test" HTTP/1.1 "Amazon CloudFront" 404 19 0.000
```

Traefik doesn't have a redirection option as nginx so If I use :
oauth2/sign_in and then oauth2/auth I will able to open my page,

## Expected Behavior

I expected to access to this page:
https://alertmanager-monitoring.mongodb.test.20test

## Current Behavior

oauth proxy trying to open access to this:
`GET - "/oauth2/auth_or_start?rd=https://alertmanager-monitoring.mongodb.test.20test" HTTP/1.1 "Amazon CloudFront" 404 19 0.000`

## Your Environment

I am using helm chart https://github.com/helm/charts/tree/master/stable/oauth2-proxy 
```
      ingress.kubernetes.io/ingress.class: traefik
      ingress.kubernetes.io/auth-type: forward
      ingress.kubernetes.io/auth-remove-header: 'false'
      ingress.kubernetes.io/auth-trust-headers: 'true'
      ingress.kubernetes.io/auth-response-headers: 	Content-Length,Content-Md5,Content-Type,Date,Authorization, X-Forwarded-User, X-Auth-Request-Access-Token,X-Forwarded-Email, X-Forwarded-Access-Token,Cookie, Gap-Auth
      ingress.kubernetes.io/auth-url: ${auth_url}

```
- Version used:

**Comment by JoelSpeed** [comment]
Hey @milijander88, Once you've attempted to log in, if you manually visit the `/oauth2/auth` URL, do you get an authorized or unauthorized response?

I suspect what is happening here is that the path in your `rd` is not being accepted as a valid redirect.
Have you set a `whitelist-domain` option when configuring the OAuth2 Proxy?

**Comment by jeffersonbabuyo** [comment]
@JoelSpeed - I am experiencing the same issue. accessing `/oauth2/auth` manually will only show white space. I tried accessing it without logging in and it gives me `unathorized` message

**Comment by JoelSpeed** [comment]
If you see white space, then you are successfully logged in on that domain. You can use the developer tools in your browser to inspect the session cookie and check that it meets your expectations/requirements for your environment

**Comment by jeffersonbabuyo** [comment]
@JoelSpeed - Yes, thank you it working fine.
