### ISSUE TITLE
Auth-Digest X-Forwarded-User is int, not str for Google provider

### ISSUE THREAD

**Issue by Alives** [oauth2-proxy/oauth2-proxy#369]
I'm passing basic auth to upstream, but upstream is seeing what seems to be the Google user ID, not the username.  I'm getting a 21 digit int instead of $user@$domain as expected.

## Expected Behavior

I'd assume I should be able to get $user@$domain for X-Forwarded-User or the user portion of auth-digest instead, or at least have a flag to override this behavior.

## Current Behavior

In the past I've seen this come across as $user@$domain, but right now it's showing up as a User ID (int) which is breaking my access.

My X-Forwarded-User header and the User side of auth-digest is showing as this 21 digit integer instead of the email string I'm expecting.

## Possible Solution

Provide a flag to override the user portion of the auth-digest to match X-Forwarded-Email.

- Version used: 5.0

**Comment by JoelSpeed** [comment]
@Alives Could you confirm whether or not this was working in a previous version of the proxy, have we broken something?

**Comment by Alives** [comment]
I feel like I ran into this a few years ago but cannot find any mention of it in pusher/oauth2_proxy issues or the bitly/oauth2_proxy archive.  IIRC it's an issue on Google's side, where an int (the userID from their end) is returned as X-Forwarded-User instead of the username, which breaks a lot of the upstream stuff I have set to map to specific usernames.  I now have to add the 21 digit integer instead as username.

**Comment by jordancrawfordnz** [comment]
I suspect the `-prefer-email-to-user` configuration option will resolve this, looking at https://github.com/pusher/oauth2_proxy/blob/master/oauthproxy.go#L941

However, if (like in my case) you're using the `-pass-user-headers` option rather than the `-pass-basic-auth` option, this will option will have no impact. I'm considering adding `-pass-user-headers` support to the `-pass-user-headers` option.

**Comment by Alives** [comment]
Yeah, it's strange.  Now that I'm testing to see if that flag works, the Google provider isn't returning the int, but the email instead (as it should).  Next time this comes up I'll see if this flag helps.  Thanks
