### ISSUE TITLE
Bug: User with unverfied primary email in GitHub is an "Invalid Account", no sensible logs

### ISSUE THREAD

**Issue by deiga** [oauth2-proxy/oauth2-proxy#374]
## Expected Behavior

A user with an unverified email logs in gets an error message about email verification failed. Logs have a mention about the user having an unverified email.

## Current Behavior

A user of ours was trying to log in but got 403 every time. Logs didn't have anything close to mentioning a problem with their email.

## Possible Solution

Add clearer logging stating that verification of users email is lacking.

## Steps to Reproduce (for bugs)

1.  Set up a GitHub backed oauth2_proxy
2.  Try to log in with a user who has an unverified primary email
3.  Profit

## Your Environment

- Version used: Tried with 4.0.0 and 5.0.0

**Comment by JoelSpeed** [comment]
This has come up before though I haven't managed to find where from my quick scan of issues. We definitely need to take a look at this and make this more obvious

**Comment by GuyPaddock** [comment]
I'm also seeing this issue with Azure and guest accounts.

**Comment by deiga** [comment]
> 
> In our case, this turned out to be that we had the `--email-domain` option set to only allow users with our domain instead of any email domain. So, that's why we were only seeing this with guest users on Azure. Now that we've passed-in `*` it works correctly. So... carry on.
> 
> Not sure if the OP is having the same kind of problem with GH or something different.

We have email domain as `"*"`

**Comment by deiga** [comment]
How could this be approached? I'd love to help, but I've never contributed to this project so starting feels quite cumbersome and hard to grasp

**Comment by JoelSpeed** [comment]
I guess the solution would be to add some logging in the GitHub provider if the primary email is not verified?
