### ISSUE TITLE
Is implicit flow supported?

### ISSUE THREAD

**Issue by zarkoc** [oauth2-proxy/oauth2-proxy#376]
Hi All,

I think the title says it.
Im testing oauth2_proxy why our custom Identity Provider, and I see that the grant type that the proxy is sending to the idP is **authorization_code**. Is the **implicit** flow supported?

Thanks.

**Comment by JoelSpeed** [comment]
Hi @zarkoc, could you elaborate on what you are trying to achieve with the implicit flow? This is the flow in which only the access token is returned IIRC. At the moment we normally specify the response type `code` with `openid` within the scope which should return the access token and the ID token, so you should be able to get the access token as required?
