### ISSUE TITLE
Issue accessing app from iphone browser - using oauth2 proxy

### ISSUE THREAD

**Issue by dmahisingh** [oauth2-proxy/oauth2-proxy#377]
Hello,
I am facing couple of Issues when I am trying to access the application in iphone - It is browser based app and deployed in Azure Kubernetes. It is working fine with Android phone - I am using Azure as provider.

In few devices, I am getting below error - **403 Permission Denied http: named cookie not present**
The oauth2 proxy pod logs shows this error - **[AuthFailure] Invalid authentication via OAuth2: unable too obtain CSRF cookie**
In few devices, I am getting below error
**Origin "app link" is not allowed by Access-Control-Allow-Origin**
Please help me resolving these.

**Comment by dmahisingh** [comment]
Joel, any suggestions on these issues?

**Comment by dmahisingh** [comment]
Any suggestions please????

**Comment by JoelSpeed** [comment]
Hey @dmahisingh, I don't feel like I have enough context to add anything useful to this conversation, apologies.

Perhaps if you provided more detail about your setup I might be able to add something?

**Comment by dmahisingh** [comment]
Thanks Joel for the response.
We are developing one angular 7 application which is deployed in Azure Kubernetes envrionment. To have azure based authentication, we are using oauth2 proxy. please see below for the files which are deployed to kubernetes cluster 
oauth2_proxy file - [oauth2_proxy.txt](https://github.com/pusher/oauth2_proxy/files/4169027/oauth2_proxy.txt)

ingress yaml file - [ingress.txt](https://github.com/pusher/oauth2_proxy/files/4169045/ingress.txt)

It is working fine from desktops and android mobiles. When we are trying to access from ios (ipad/iphone), the application is not working. It will ask for Microsoft login page and after login we are getting below errors
1) In few devices, I am getting below error in the browser console, not even above 403 error -
**Origin https://test.domain.com is not allowed by Access-Control-Allow-Origin
https://login.microsoftonline.com/tenantid/oauth2/authorize?approval_prompt=force&client_id=........ Failed to load resource: Origin https://test.domain.com is not allowed by Access-Control-Allow-Origin.**
2) In few devices, I am getting below error - 
The mobile browser (safari) shows this error - **403 Permission Denied http: named cookie not present**
The oauth2 proxy pod logs shows this error - **[AuthFailure] Invalid authentication via OAuth2: unable too obtain CSRF cookie**

**Comment by dmahisingh** [comment]
I am trying to alter the oauth2_proxy container args alot, but not working out any thing - Request your help for solving this issue

**Comment by JoelSpeed** [comment]
Honestly, I'm a bit stumped by this one. If it's working fine in some browsers but not iOS, that's very very strange. I don't really have any suggestions, I've never seen anything like this before

**Comment by dmahisingh** [comment]
But do you see the configuration looks good?
In general, when do you get the 403 error, I think it is coming with old browsers...when we get the Invalid auth via OAuth2, the user is getting authenticated properly...I can see the user full profile displayed in the oauth2 proxy log
What causes these kind of issues?

**Comment by dmahisingh** [comment]
FYI - If I remove the oauth2 proxy (authentication part), the app is working from ios along with other browsers.

**Comment by dmahisingh** [comment]
Joel, any comments on this please? We are stuck here and not able to go ahead with project.

**Comment by dmahisingh** [comment]
Joel, I see below code in https://github.com/pusher/oauth2_proxy/blob/master/oauthproxy.go

	nonce := s[0]
	redirect := s[1]
	c, err := req.Cookie(p.CSRFCookieName)
	if err != nil {
		logger.PrintAuthf(session.Email, req, logger.AuthFailure, "Invalid authentication via OAuth2: unable too obtain CSRF cookie")
		p.ErrorPage(rw, 403, "Permission Denied", err.Error())
		return
	}

this is the same error we are getting at the back end. As ios generally uses safari, is there any issue with csrf cookie with all safari and old chrome browsers?? Please check once

**Comment by JoelSpeed** [comment]
There are no known issues with this area of the codebase, but I agree, I suspect this is the source of your problem. I wonder if there is a problem with the cookie name possible?

Which session storage are you using also? Can I ask you to try the Redis based session storage if you aren't already

**Comment by johejo** [comment]
Hi, it might be helpful occurs in ios12.
https://www.chromium.org/updates/same-site/incompatible-clients

Set cookie-samesite=lax might solve.
https://pusher.github.io/oauth2_proxy/configuration

**Comment by domenzain** [comment]
Hi,

I've recently noticed this too with older iPhones using the google provider:
`Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1`

Users that can log in through a computer somehow get rejected when doing so through an iPhone with the same account.

I have tried out @johejo's suggestion above without success (same behavior).

**Comment by domenzain** [comment]
The bug is still in oauth2_proxy v5.1.0
@johejo, I had put the `cookie-samesite="lax"` in the configuration file, forgetting to replace the dash with an underscore.
Your suggestion does work.

CC @dmahisingh @JoelSpeed

**Comment by Morriz** [comment]
`cookie-samesite="lax"` is not working for us unfortunately...the configuration is correctly loaded, but we see this:
```
Error loading cookied session: Cookie "_oauth2_proxy" not present
```
Regular browser passes it correctly. Could it be that mobile browsers don't support coookie splitting? We have 8k+ cookies

**Comment by JoelSpeed** [comment]
Cookie splitting is being deprecated. Please switch to using redis for session storage. See #482 for further details. We have also noted there that we want to support server side sessions other than redis, please add your thoughts if you have anything to add

**Comment by sneko** [comment]
In case some people still have iOS/MacOSX issue with cross-origin cookie, see my issue https://github.com/oauth2-proxy/oauth2-proxy/issues/830 and its related PR to fix it https://github.com/oauth2-proxy/oauth2-proxy/pull/832
