### ISSUE TITLE
Support for direct access (aka resource owner) grant ?

### ISSUE THREAD

**Issue by philpep** [oauth2-proxy/oauth2-proxy#390]
Hi,

I'm quite new to oauth2 and oauth2_proxy. I use oauth2_proxy with keycloak and nginx and I'm very happy with it as long as we stay in a browser.

I have some http APIs I would like to authenticate through a proxy with basic authentication or opaque tokens using existing keycloak IDP. Typically users use CLI tools (curl / others) to request APIs, some of them doesn't supports other authentication than basic auth.

In oauth2 specification, there's a direct access grant, also called resource owner credential grant. For a auth2 client (like the proxy) this mean we can issue jwt token with a POST request on ``/token`` and passing ``grant_type=password``, ``client_id=xxx``, ``client_secret=xxx``, ``username=jdoe``, ``password=secret``.

So the proxy could have a endpoint like ``/oauth2/auth`` (suitable for nginx auth_request) accepting basic auth (username, password), authenticate by issuing a jwt token and return "200 OK" or "401 Unauthorized". Eventually he could also cache a hash of user/password for a reasonable time. And to avoid sending user/password, maybe also issue opaque tokens for end-user application supporting it.

By reading the documentation, looks there's some options about basic-auth / authorization header but by reading the code I didn't see a support for ``grant_type=password``.

Also note that I'm not sure this is the correct way to handle such "legacy" applications with a proxy.

Thanks for answers!

**Comment by sribee** [comment]
dex now has support for password grant - https://github.com/dexidp/dex/pull/1621
Is that going to be useful for supporting this feature in oauth2_proxy?

**Comment by mlazowik** [comment]
Reopen?

**Comment by JoelSpeed** [comment]
OAuth2 Proxy already supports accepting basic auth as a form of authentication, it also supports accepting JWTs as a form of authentication from requests, would either of these solve the issue that has been described?

**Comment by mlazowik** [comment]
The point here is to parse the basic auth coming from the client, and convert it into a [Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3) query sent to the IdP `token` endpoint. By adding `scope=openid` you can get the `id_token` in response, and from there do exactly the same things you do with the browser auth flow.

**Comment by JoelSpeed** [comment]
Ack, that makes sense. Perhaps we should be adding support for this, I'm not really sure how this would integrate with the existing codebase though, would be good to discuss what is needed and where this might hook into before we implement this

**Comment by snkshukla** [comment]
@JoelSpeed Can this be reopened?

**Comment by philippe-granet** [comment]
Can this be reopened?

**Comment by JoelSpeed** [comment]
My previous comment is still outstanding, we don't understand what the requirements are for this or how this would hook into the existing project, would be good to understand that so we can evaluate the implications before anyone starts an implementation

**Comment by mlazowik** [comment]
.

**Comment by mlazowik** [comment]
Ok, so one way this could work is that if you enable a config option, the proxy will send [`WWW-Authenticate`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) header (maybe with configurable `realm` too?) in response to unauthorized requests, and for requests that do have an `Authorization: Basic` header it'll read the creds and send the [Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3) request to the IdP.

In response it'll get a token that can be the pass accordingly to regular existing config flags. A variant of the `/oauth2/auth` endpoint could be made too.

The RFC is pretty straightforward to read, you just need to remember about splitting username and pass by the first `:` only (`:` is illegal in username, but legal in password) + urlencode.

Here's an example of how we're handling this via openresty, the code has some custom specifics but should be a pretty good overview of the "translation" process: https://pastebin.com/GZwEXzph

**Comment by mfettig** [comment]
Is this still being considered?

I'm in a very similar situation as @philpep using oauth2-proxy with keycloak and would like to be able to use http basic auth for some HTTP API endpoints

**Comment by Yaytay** [comment]
Same here, and I'm very happy to discuss my requirements. 
I already have a setup doing this via Gravitee using a custom plugin, but that is more complex than I'd like, so if I can just use oauth2-proxy it would make my life that little bit better.
