### ISSUE TITLE
The user email is lost after the id token is refreshed by the gitlab provider

### ISSUE THREAD

**Issue by conet** [oauth2-proxy/oauth2-proxy#411]
## Expected Behavior

I expect the user email to be available in `X-Forwarded-Email` for the entire user session.

## Current Behavior

The user email is lost after the id token is refreshed.

## Steps to Reproduce (for bugs)

1. authenticate using gitlab
```
[AuthSuccess] Authenticated via OAuth2: Session{email:a@b.com user:a ...} 
```
2. wait for the id token refresh
```
refreshed id token Session{email: user:a ...}
```
3. notice that the email is lost, that is because it is update [here](https://github.com/pusher/oauth2_proxy/blob/master/providers/gitlab.go#L115) but the function producing that struct [never sets that field](https://github.com/pusher/oauth2_proxy/blob/master/providers/gitlab.go#L200).

## Context

If the backend relies on `X-Forwarded-Email` the auth breaks.

## Your Environment

- Version used:
`v5.0.0`

**Comment by conet** [comment]
Seems like it was introduced in PR #231

**Comment by JoelSpeed** [comment]
@conet Do you have time to raise a fix for this? I think getting the email from the updated ID Token makes sense, assuming it's set, so maybe we can make sure it's set and set it to the old value if not/use the userinfo endpoint?

**Comment by conet** [comment]
I’m pretty busy these days and worked around this by replacing gitlab auth with keycloak auth, I’ll try to come up with a patch if I find some time.

**Comment by tcordeu** [comment]
@conet @JoelSpeed I am facing this problem, can I work on these issue or is anyone else working on it?

**Comment by JoelSpeed** [comment]
I don't think this is currently being worked on, feel free to pick it up
