### ISSUE TITLE
AWS cognito as OIDC provider cookie not present

### ISSUE THREAD

**Issue by rogerscuall** [oauth2-proxy/oauth2-proxy#423]
Using AWS Cognito as OIDC provider, I'm able to login in Cognito login page and then I get redirected to the application but I'm seeing in the log the error:
```
[oauthproxy.go:745] Error loading cookied session: Cookie "_oauth2_proxy" not present
```
## Expected Behavior
It is the first time I use AWS Cognito as OIDC provider, but I have used Github and Google and after the initial login, I can see a cookie named `_oauth2_proxy` in my browser that is what oauth2_proxy needs to let the traffic to the upstream servers. But instead of that cookie, I'm getting another one `_oauth2_proxy_csrf`. The expected behavior is the generation of` _oauth2_proxy`.

## Current Behavior

Comparing Google and Github provider with this one, during the redirect I get two cookies, the `_oauth2_proxy_csrf` and `_oauth2_proxy`. Then the redirect creates a few console log messages one of those messages is:
<IP_ADDRESS> - USERNAME@gmailcom [2020/02/28 14:41:36] [AuthSuccess] Authenticated via OAuth2: Session{email:USERNAME@gmail.com user:USERNAME token:true created:2020-02-28 14:41:36.441346407 +0000 UTC m=+342.954424968}.
While if AWS Cognito is used:
```
[2020/02/28 14:41:05] [oauthproxy.go:745] Error loading cookied session: Cookie "_oauth2_proxy" not present
```

## Steps to Reproduce (for bugs)

This is the configuration of oauth2_proxy used as a container inside kube using helm.
```
  client-id: "XXXXXX"
  client-secret: "XXXXXX"
  cookie-secret: "XXXX"
  email-domain: "*"
  provider: oidc
  redirect-url: https://backend.dev.mydomain.org/oauth2
  scope: openid
  cookie-secure: true
  whitelist-domain: .mydomain.org
  cookie-domain: .dev.mydomain.org
  upstream: file:///dev/null
  oidc-issuer-url: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_QvWQqo9q7
```
1.  Go to  `https://backend.dev.mydomain.org/`
2.  It gets redirected to AWS Cognito Login page.
3.  Enter credentials
4.  Is redirected again to `https://backend.dev.mydomain.org/oauth2`
5. Check the console with kubectl logs -f POD
6. Find the error message:
```
 [oauthproxy.go:745] Error loading cookied session: Cookie "_oauth2_proxy" not present
```
7. In the browser console check the cookies present, notice `_oauth2_proxy` missing and `_oauth2_proxy_csrf` present in all requests.

## Context

Integrate with AWS Cognito, as it works with the other providers.

## Your Environment

- Version used:
I'm using `https://github.com/helm/charts/tree/master/stable/oauth2-proxy` and the values: 
```
  client-id: "XXXXXX"
  client-secret: "XXXXXX"
  cookie-secret: "XXXX"
  email-domain: "*"
  provider: oidc
  redirect-url: https://backend.dev.mydomain.org/oauth2
  scope: openid
  cookie-secure: true
  whitelist-domain: .mydomain.org
  cookie-domain: .dev.mydomain.org
  upstream: file:///dev/null
  oidc-issuer-url: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_QvWQqo9q7
```
defined in the section `extraArgs`.
I have played with multiple options like changing `whitelist-domain`, `cookie-domain`

**Comment by JoelSpeed** [comment]
If you already had the proxy working correctly with another provider, switching provider shouldn't break any of the whitelist/cookie settings.

Can you provide some more snapshots of your logs? The named cookie not present message is pretty common and generated any time a request is made by an unauthed user, it doesn't necessarily mean your auth has failed. If the auth were to fail, you would not expect to see your backend application

**Comment by rogerscuall** [comment]
The backend service endpoint (appliation/FlogCall) protected by oauth2_proxy is just displaying the header of the request, when Google or Github is used we get this:
```
{"x-request-id":"b41448919687647733e5abd1e1cff498","x-forwarded-proto":"https","accept-language":"en-US,en;q=0.5","cookie":"_oauth2_proxy=eyJBY2Nlc3NUb2tlbiI6ImEwaTVLR2tKK0dhN015Szh6bEZ5c2ZUN0YxdkExOERDaXg1Z050NmtqTjlOcHE4VGxIZ1hCMkJMVUZjVXYxM0JTWEtRUW5RSGJ0MD0iLCJFbWFpbCI6IkdjdzlNQ2xEWkhSQ2VIem5nMFlmZXVlR3dlc1JLZXNqS2Q5b2EySkFnTmlCZ2UwSC9RPT0iLCJVc2VyIjoibkZpZ2RXT1BRUDJkVDFaQ25tSDBSU0JsaG5OTFhpSE0wSmo4IiwiQ3JlYXRlZEF0IjoiMjAyMC0wMi0yOVQxODo1ODo0My4zNTEzODQwNjVaIn0=|1583002723|-BIjdjVweTndfbcH_ZvTes23vds0=","x-auth-request-email":"devtestqa1@gmail.com","x-forwarded-port":"443","x-forwarded-for":"X.X.X.X","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","x-real-ip":"X.X.X.X","x-forwarded-host":"knoblab-backend.dev.mydomain.org","host":"knoblab-backend.dev.mydomain.org","upgrade-insecure-requests":"1","x-scheme":"https","accept-encoding":"gzip, deflate, br","x-auth-request-user":"devtestqa1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0"}
```
And the redirect looks like this:

`https://knoblab-backend.dev.mydomain.org/oauth2/callback?code=9af11818a79d37ede7bb&state=df79bf7c7e13c745a17c52fa6046c8a9%3A%2Fapplication%2FlogCall`

When we try Cognito using OIDC provider, the redirect URL looks like this:

`URL:https://vlm-test1.auth.us-east-1.amazoncognito.com/login?approval_prompt=force&client_id=5viapbmum1ftg896opd1pau76t&redirect_uri=https%3A%2F%2Fknoblab-backend.dev.mydomain.org%2Foauth2%2F_callback&response_type=code&scope=openid&state=e973e50ba24dca4787ace606f884263e%3A%2Fapplication%2FlogCall`

The logs show the following:

```
[2020/03/02 20:21:58] [oauthproxy.go:745] Error loading cookied session: Cookie "_oauth2_proxy" not present
75.40.51.43 - - [2020/03/02 20:21:58] knoblab-backend.dev.mydomain.org GET - "/oauth2/_callback?code=1860ca41-aeed-4e9f-aee0-39550aaf763f&state=e973e50ba24dca4787ace606f884263e:/application/logCall" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0" 403 2601 0.000
[2020/03/02 20:21:59] [oauthproxy.go:745] Error loading cookied session: Cookie "_oauth2_proxy" not present
3.230.155.218 - - [2020/03/02 20:21:59] knoblab-backend.dev.mydomain.org GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0" 401 21 0.000
75.40.51.43 - - [2020/03/02 20:21:59] knoblab-backend.dev.mydomain.org GET - "/oauth2/start?rd=%2Ffavicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0" 302 348 0.000
```
And I'm still not able to see the service protected by oauth2_proxy, because I get a 403 from oauth2_proxy service in the browser.

Looking in the logs of Cognito I can see the authentication is successful acording to Cognito.
Thanks.

**Comment by rogerscuall** [comment]
Hi @JoelSpeed , please when time permit let me know if you have any idea about this issue.

**Comment by cmanzi** [comment]
@rogerscuall I am using Cognito as an idP as well (though in conjunction with nginx, using auth_requests to oauth2-proxy), and it is working fine for me. These are my configs for reference:
```
(flags)
--exclude-logging-paths=/ping
--oidc-issuer-url=https://<cognito_oidc_issuer_url>
--provider=oidc
--scope=openid email profile
--set-authorization-header=true
--whitelist-domain=dev.example.com
--config=/etc/oauth2_proxy/oauth2_proxy.cfg
...
(config)
    ## The OAuth Client ID, Secret
    client_id = "__CLIENT_ID__"
    client_secret = "__CLIENT_SECRET__"
    pass_basic_auth = true
    pass_user_headers = true
    pass_host_header = true
    pass_access_token = true
    cookie_name = "_oauth2_internal"
    cookie_secret = "__COOKIE_SECRET__"
    cookie_domain = "dev.example.com"
    cookie_expire = "168h"
    cookie_refresh = "4h"
    cookie_secure = true
    cookie_httponly = true
```

**Comment by pacoja84** [comment]
Hello,

I was suffering the same issue than you and finally got resolved.

My system:
OIDC provider: Azure
oauth2-proxy and backend service deployed on kubernetes and exposed via ingress controller.

In my case, I suffer 2 big issues. The key of the solution was the ingress controller logs, not the oauth2-proxy logs.
**1. Token from azure was too big**
Ingress controller throw an error saying that a header exceed the allowed size.
This can be solve extending the buffer size on the ingress controller configuration.
Add the following annotations:

    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"

Another option could be reduce the token size if you can handle it.

When I fix this issue I could see how the cookies are set correctly.

**2. Ingress controller pod(a.k.a. nginx) could not contact with auth-url:**
This is only an issue if the hostname that you are using in your ingress is not accesible by your nginx pod. To avoid this, you can use cluster URLs, instead of public ones. This URL is used internally:

nginx.ingress.kubernetes.io/auth-url: "http://<service-name>.<namespace>.svc.<cluster-prefix>:4180/oauth2/auth"

Hope this help.

Regards

**Comment by sitaramkm** [comment]
@pacoja84 thanks for your comments. I have been troubleshooting Okta + Oauth2 proxy for a few hours and eventually stumbled on your post to look at the nginx ingress controller logs and I see the below error. Quick question - were you able to resolve this by adding the proxy buffer annotations to the ingress controller pod or the ingress controller svc? Wasn't sure which specific resource you added the annotations. I am hoping to resolve it by making the same change you made. I am not using Azure.  

`020/06/08 14:46:10 [error] 15599#15599: *6000200 upstream sent too big header while reading response header from upstream, client: 192.168.82.107, server: sample1.stage.example.com, request: "GET /oauth2/callback?code=oUvsE2DJNnkPRMqMRSUd&state=5233c44bae54842f43da78d33d1830a1%3Ahttps%3A%2F%2Fsample1.stage.example.com%2F HTTP/2.0", upstream: "http://192.168.27.122:4180/oauth2/callback?code=oUvsE2DJNnkPRMqMRSUd&state=5233c44bae54842f43da78d33d1830a1%3Ahttps%3A%2F%2Fsample1.stage.example.com%2F", host: "sample1.stage.example.com"`

**Comment by pacoja84** [comment]
> @pacoja84 thanks for your comments. I have been troubleshooting Okta + Oauth2 proxy for a few hours and eventually stumbled on your post to look at the nginx ingress controller logs and I see the below error. Quick question - were you able to resolve this by adding the proxy buffer annotations to the ingress controller pod or the ingress controller svc? Wasn't sure which specific resource you added the annotations to. I am guessing it's the ingress-nginx-controller ConfigMap resource but want to confirm.
> I am hoping to resolve it by making the same change you made. I am not using Azure.
> 
> `020/06/08 14:46:10 [error] 15599#15599: *6000200 upstream sent too big header while reading response header from upstream, client: 192.168.82.107, server: sample1.stage.example.com, request: "GET /oauth2/callback?code=oUvsE2DJNnkPRMqMRSUd&state=5233c44bae54842f43da78d33d1830a1%3Ahttps%3A%2F%2Fsample1.stage.example.com%2F HTTP/2.0", upstream: "http://192.168.27.122:4180/oauth2/callback?code=oUvsE2DJNnkPRMqMRSUd&state=5233c44bae54842f43da78d33d1830a1%3Ahttps%3A%2F%2Fsample1.stage.example.com%2F", host: "sample1.stage.example.com"`

Hello,

annotation is on the ingress.

Let me share with you mine:

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "http://test-ingress-openid-oauth2-proxy.{{ .Values.ingress.namespace }}.svc.{{ .Values.ingress.internalClusterSufix }}:4180/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  name: echo-api-with-oauth2-proxy
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          serviceName: echoapi-svc
          servicePort: 2080
        path: /
  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
      secretName: test-ingress-openid-tls-secret

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  name: oauth2-proxy
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          serviceName: test-ingress-openid-oauth2-proxy
          servicePort: 4180
        path: /oauth2
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: test-ingress-openid-tls-secret`


I had 2 ingress, first one is the ingress for the services that you want to protect.
The second one is the ingress that expose the ouath2 proxy service.

I put the annotation on both, but I guess that only is needed on the first one.

Hope it helps.

**Comment by sitaramkm** [comment]
@pacoja84 your information about the Ingress was perfect. Thank you! 
I can tell you for sure which one definitely needs the annotations. It's the Ingress pointing to the oauth2-proxy service. I had it just for the other one and it does not work.
