### ISSUE TITLE
X-Real-IP only meaningful to mostly CloudFlare users

### ISSUE THREAD

**Issue by Izzette** [oauth2-proxy/oauth2-proxy#424]
## Expected Behavior

* Address displayed by logging should by default not include any non-standard semantics like treating `X-Real-IP` as the original forwarded IP.
* Most users with a reverse proxy will be using the `X-Forwarded-IP` as the defacto-standard for reflecting the original client IP.
* Using `X-Real-IP` is mostly done by CloudFlare, and gives a private organisation an unfair advantage for an otherwise neutral opensource project.

## Current Behavior

* The logger displays the address in `X-Real-IP` in various contexts.

## Possible Solution

* Add a configuration option to select what header to grab the real client IP from.

## Context

* Relates to desired other feature needed.

**Comment by ploxiln** [comment]
Adding support for `X-Forwarded-For` is a good idea.

But, just by the way, `X-Real-IP` is not Cloudflare specific in the slightest, and long predates CloudFlare. Most people configure Apache or Nginx to set it. One example from 2008 (before Cloudflare was started in 2009): https://andytson.com/blog/2008/04/page-level-caching-with-nginx-0-6/ and here's a mention from 2005: https://aprelium.com/data/doc/2/abyssws-win-doc-html/servergeneral.html

**Comment by Izzette** [comment]
Yes of course, but `X-Forwarded-For` is really the defacto-standard.  `X-Real-IP` comes in when you start having a couple of layers of reverse proxy.

**Comment by Izzette** [comment]
Will be closed by #503
