### ISSUE TITLE
Make it configurable which claim is user id (currently = email)

### ISSUE THREAD

**Issue by holyjak** [oauth2-proxy/oauth2-proxy#431]
According to https://github.com/pusher/oauth2_proxy/blob/master/providers/oidc.go#L208 an id token must contain an email. But some of our tokens don't have (the users use their phone number instead), which makes the proxy unusable for us. Is email a hard requirement? Why? Thank you!

## Expected Behavior

Email should not be required (or there should be an option to make it optional).

## Current Behavior
The callback url fails with 

> Error redeeming code during OAuth2 callback: unable to update session: id_token did not contain an email

## Implementation

I see the assumption that email is there is baked into the code. It is used f.ex. for logs. We could replace the use of `session.Email` with something like `session.DisplayableUserId` that would be sot to Email if available and fall back to Subject (which, I _believe_, is always present in the token).

We would also need to make email validation optional. Perhaps add a new option (or is there a nice way not to need that?) to make emails optional.

## Steps to Reproduce (for bugs)

Log in with a user whose claims do not include an email.

## Your Environment

- Version used: v5.0.0

**Comment by JoelSpeed** [comment]
A flag like `--user-id-claim` which would select which claim from the token to use would be preferable I think. Something that allows people to specify this generically would be more useful in the long run

**Comment by holyjak** [comment]
Thank you! I will look into that.

In our case I would still need to `--user-id-claim sub` (which is always present) because some of our users only have `phone_number`, some only have `email` (some have both). Alternatively we could make `--user-id-claim` a list where the first present gets used. But I guess the complexity cost of that is not worth this likely rare use case.

**Comment by holyjak** [comment]
FYI I am going to work on a fix soon.

**Comment by holyjak** [comment]
BTW I think about making `--user-id-claim` a list where you can specify multiple claims, the first present will be used - this is best for our use case where people have either email or phonenumber. And you can always use just a single value (default = email).

@JoelSpeed I am not sure what you meant by

> Something that allows people to specify this generically would be more useful in the long run

Could you please elaborate?

**Comment by JoelSpeed** [comment]
> BTW I think about making --user-id-claim a list where you can specify multiple claims, the first present will be used - this is best for our use case where people have either email or phonenumber. And you can always use just a single value (default = email).

I like the idea of a `--user-id-claim` flag but I don't believe it should be a list. I think we should keep this as a single option and if it's not present, the user should not be logged in. I don't know if it's safe to have failbacks in this situation. I haven't seen any other projects having failbacks for the user claims and this makes me think we should probably follow suit

> Could you please elaborate?

I want a flag that allows you to choose any claim from within the ID token, basically as you have desccribed

**Comment by holyjak** [comment]
>  I think we should keep this as a single option and if it's not present, the user should not be logged in. I don't know if it's safe to have fallbacks in this situation.

It was not intended as a fallback but rather as alternatives. My context is a big org that migrates users of different origins to a single system. For historical reason, some use email while others user phone number as their login (and frequently do not have the other registered). So being able to specify both would be optimal for us. If `--user-id-claim` only supported a single value, we would need to "hack around" and use `sub`, which is always present, as the user id. I don't think there is much difference in complexity between 1 or a list. What do you think?

**Comment by JoelSpeed** [comment]
Honestly, my opinion is that your case is probably quite a niche case and I'd rather not be creating lots of additional niche cases within the project to support single users. Are you aware of others who have similar problems? Are there other projects with similar features to this?

**Comment by holyjak** [comment]
I understand. Basing the work on #466 instead and being able to use JMESPath instead of just a claim name would satisfy my need and, I guess, be acceptable for you as well.

**Comment by nickwilliams-codynamic** [comment]
I also have this requirement. I've worked on a fair few IDAM solutions in the past and not having an email included in an id_token or from a userinfo endpoint I think is reasonably common to be honest. As phone number sign up and passwordless are being used more and more, I think it will become more common too.

**Comment by xellsys** [comment]
We have also the same need. 
Background: Azure B2C does not enrich the token with the "email" claim, see [here](https://social.msdn.microsoft.com/Forums/en-US/fa2599b3-38df-40db-b2ff-78fcae0fb6b5/azure-b2c-how-can-i-get-email-address-from-claim?forum=WindowsAzureAD), which makes the oauth2-proxy essentially unusable for Azure B2C.
Is this on the roadmap of the upcoming release? Can you give a timeframe for the feature?

**Comment by JoelSpeed** [comment]
@xellsys Please follow the #516 for release conversation

**Comment by harveyjing** [comment]
I found that option --user-id-claim exist in version 6.x but missing in 7.x and latest version 7.4.x. So how can I solve this problem now and WHY this option deprecated? Thanks
