### ISSUE TITLE
Cannot change the path used in an upstream server.

### ISSUE THREAD

**Issue by chkohner** [oauth2-proxy/oauth2-proxy#456]
Current behavior when mapping an upstream source with a path is to map only that path. For example:

`http://private.me.com/site/`

Will result in binding the path `/site/...` in the proxy server, but in this case, the upstream's `/site/` is the "root" of the website in question.

## Expected Behavior

The current implementation uses the fragment portion of a `file:///` URL to "remap" the path that it binds in the proxy. This is very useful for servers as well.

## Current Behavior

Upstream servers may only bind the exact path that part of their URL.

## Possible Solution

Expanding on the fragment-based "binding hint" used for local file URLs would accomplish this discrepancy and further enable multi-upstream mappings to be much more flexible. Allowing the path remapping would also permit path-based forwarding to separate servers. E.g.
* `http://api.private.com/#/api/`
* `http://static.private.com/#/static/` 
* ...

## Context

For Azure Blob storage, the URL for accessing content is `https://myaccount.blob.core.windows.net/mycontainer/myblob`. Notably, the `mycontainer` part is required, making oauth2_proxy unable to pull from Azure Blob Storage without also including the container as part of the original request URL.

- Version used: master (362cdf7713b7f3cb25647e6afd94f370d7c6cd7d)

**Comment by steakunderscore** [comment]
Hi @chkohner :wave: To make sure that I have understood your issue correctly. You would like oauth2-proxy to support path remapping in an http upstream just like we support it for static files. Is that correct?

**Comment by chkohner** [comment]
Correct. #460 implements this functionality.

**Comment by chkohner** [comment]
Not stale

**Comment by JoelSpeed** [comment]
@chkohner Do you think this would be solved by the new configuration introduced in #591, once that is exposed to the end user at least?

**Comment by chkohner** [comment]
It's hard to to tell without really digging into that change, but it seems that you're at least attempting to account for it using the `path` element in that new setup. One thing worth checking is whether you're correctly doing the query arg combining in that rewrite, as it's required in some CDN scenarios (see #460 for examples).

**Comment by JoelSpeed** [comment]
I will have to take a look into the query arg thing, this is when you want to provider your upstream with query arguments by default, and then also add some from the user request right? 

Eg, all requests to upstream go to `http://<upstream>/bar?arg1=arg`, where arg1 is some internal value for authentication or something?

**Comment by chkohner** [comment]
Yep. For instance, when serving [protected content via Verizon CDN](https://docs.microsoft.com/en-us/azure/cdn/cdn-token-auth), you need an authentication token.
