### ISSUE TITLE
Using some extra args with Azure results in error 400 and 500

### ISSUE THREAD

**Issue by edemen** [oauth2-proxy/oauth2-proxy#458]
Edit: When using the following `extraArgs` with `provider: azure`, successful authentication will lead to error 400 returned from login.live.com and result in error 500 shown to the user:
- `cookie-refresh`
- `pass-authorization-header: true`
- `set-authorization-header: true`
- `pass-access-token: true`

Original text:
> When going to the application URL (e.g. app.private.example.com), redirect to oauth2 proxy (at auth.private.example.com) and then to authentication provider (azure) happens fine. I put in my credentials and log in, it redirects me back to oauth2 proxy and then to application URL. However, I never get to the application as error 500 is shown.
> Subsequent attempts to go to the application domain go straight to error 500.
> 
> Been banging my head on this for the past 12 hours and would appreciate any help.

## Expected Behavior

Expected to see the application

## Current Behavior
See error 500

During subsequent attempts (after having logged in) I can see in nginx ingress controller log the following:
```
2020/03/26 15:24:33 [error] 1864#1864: *564714 auth request unexpected status: 400 while sending to client, client: 10.244.0.1, server: app.private.example.com.com, request: "GET / HTTP/2.0", host: "app.private.example.com.com", referrer: "https://login.live.com/"
10.244.0.1 - - [26/Mar/2020:15:24:33 +0000] "GET / HTTP/2.0" 400 0 "https://login.live.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0 0.130 [kube-system-kubernetes-dashboard-80] [] 51.140.27.8:443 0 0.004 400 4f6d118409e294abff873e46eb91c583
10.244.0.1 - - [26/Mar/2020:15:24:33 +0000] "GET / HTTP/2.0" 500 579 "https://login.live.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 7764 0.130 [kube-system-kubernetes-dashboard-80] [] - - - - 4f6d118409e294abff873e46eb91c583
10.244.0.1 - - [26/Mar/2020:15:24:33 +0000] "GET /oauth2/auth HTTP/1.1" 400 635 "https://login.live.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 827 0.000 [] [] - - - - c56c2e5b45b728ff5e41cbf3373e418a
2020/03/26 15:24:33 [error] 1864#1864: *564714 auth request unexpected status: 400 while sending to client, client: 10.244.0.1, server: app.private.example.com.com, request: "GET /favicon.ico HTTP/2.0", host: "app.private.example.com.com", referrer: "https://app.private.example.com.com/"
10.244.0.1 - - [26/Mar/2020:15:24:33 +0000] "GET /favicon.ico HTTP/2.0" 400 0 "https://app.private.example.com.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0 0.003 [kube-system-kubernetes-dashboard-80] [] 51.140.27.8:443 0 0.004 400 90f74ae4624554e74b4cb0802e586130
10.244.0.1 - - [26/Mar/2020:15:24:33 +0000] "GET /favicon.ico HTTP/2.0" 500 579 "https://app.private.example.com.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 7698 0.003 [kube-system-kubernetes-dashboard-80] [] - - - - 90f74ae4624554e74b4cb0802e586130
10.244.0.1 - - [26/Mar/2020:15:24:33 +0000] "GET /oauth2/auth HTTP/1.1" 400 635 "https://app.private.example.com.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 740 0.000 [] [] - - - - 7f27222dcedfa1f275105a787fd5e882
```

Logs of oauth2 proxy show nothing except kube-probe pings.

I have checked and I can see the cookies _oauth2_proxy_0, _oauth2_proxy_1 and _oauth2_proxy_2 that appear to be being set correctly.

## Steps to Reproduce (configurations)

Dashboard ingress
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-dashboard
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-url: "https://auth.private.example.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.private.example.com/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"

spec:
  tls:
  - hosts:
    - app.private.example.com
    secretName: tls-secret-kubernetes-dashboard
  rules:
  - host: app.private.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-dashboard
          servicePort: 80

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret-kubernetes-dashboard
  namespace: kube-system
spec:
  secretName: tls-secret-kubernetes-dashboard
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName:  app.private.example.com
  dnsNames:
  -  app.private.example.com
  renewBefore: 720h
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - app.private.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
```

oauth2 proxy values.yaml
```
config:
  existingSecret: oauth2-proxy-creds

extraArgs:
  provider: azure
  azure-tenant: <redacted>
  whitelist-domain: .private.example.com
  cookie-domain: .private.example.com
  cookie-secure: true
  redirect-url: "https://auth.private.example.com/oauth2/callback" # If we don't specify this, redirect URL sent to provider may use HTTP rather than HTTPS, which may be picked as a mismatch (e.g. in Azure)
  scope: openid offline_access User.Read
  cookie-refresh: 24h
  cookie-samesite: none # Chrome won't play with anything except none with HTTPS

extraEnv:
- name: OAUTH2_PROXY_AZURE_TENANT
  value : <redacted>

authenticatedEmailsFile:
  enabled: true
  restricted_access: |-
    support@example.com

ingress:
  enabled: true
  path: /
  hosts:
    - auth.private.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
  tls:
    - secretName: oauth2-proxy-https-cert
      hosts:
        - auth.private.example.com
```

## Context
I am trying to set up external authentication with oauth2 proxy, kubernetes dashboard, ingress and  letsencrypt.
For now, I only want authentication when logged in with support@example.com.

## Possible Solution

I'm sure this has to be something in configuration.

I have tried to add the following bits to extraArgs for oauth2 proxy:
```
  set-authorization-header: true
  reverse-proxy: true
  pass-authorization-header: true
  pass-access-token: true
  pass-basic-auth: true
  pass-host-header: true
  pass-user-headers: true
  set-xauthrequest: true
```

and (at the same time) the following to Dashboard ingress annotations:
```
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
```
But this had no effect.

I am really at a loss. It looks the error 400 is produced by oauth2 proxy container, but there is nothing in its logs.

## Your Environment

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"20c697423de11d4d5d08c6832a513217ca11a6aa", GitTreeState:"clean", BuildDate:"2020-02-21T10:47:45Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
nginx-ingress 0.30.0

- Version used:
oauth2-proxy 5.0.0

**Comment by robinMcA** [comment]
I've had this same problem, looking at the nginx  and oauth2-proxy logs, when i het the `app.private.example.com` path the nginx throws a 5** and there is no logging in the proxy.
When i go go /oauth2/start i can go through the oauth dance, the nginx throws an error.

**Comment by edemen** [comment]
@robinMcA 
> I've had this same problem, looking at the nginx and oauth2-proxy logs, when i het the `app.private.example.com` path the nginx throws a 5** and there is no logging in the proxy.
> When i go go /oauth2/start i can go through the oauth dance, the nginx throws an error.

Do you also get errors 400+ in the general ingress nginx controller pod logs?
What I guess is happening is:

the request first goes to `app.private.example.com` ingress
redirected to `auth.private.example.com/oauth2/auth`
redirected to `auth.private.example.com/oauth2/start`
redirected to `login.live.com`, where we are already logged in
redirected back to `app.private.example.com`
redirected to `auth.private.example.com/oauth2/auth`, which returns the 400 error
ingress nginx for `app.private.example.com` gets this 400 error and returns error 500 to the original client

I just don't see where else would the error 400 would be coming from.
However, as the logs in oauth2 proxy are empty, I'm not sure.

I wonder if there is a flag to install oauth2 proxy in some sort of debug mode so that it actually logs everything that's happening. Right now it seems to only log actual log in attempts but not authentication status checks (that probably happen when `auth.private.example.com/oauth2/auth` is visisted?)

**Comment by JoelSpeed** [comment]
@edemen In your example, did you omit some steps between `login.live.com` and redirect back to `app.private.example.com`, as you should go to `auth.private.example.com/oauth2/callback` in between those two steps and if you aren't, this could indicate a misconfiguration of you identity provider

**Comment by edemen** [comment]
Hi @JoelSpeed 
Thanks for your comment.
I was just guessing at what's happening really. I don't actually know for sure. Just trying to reason about where the error 400 may be coming from.
You are right though, the redirect should be going to `auth.private.example.com/oauth2/callback` from the external provider.

Checking the Azure app, it is configured as follows:
Allow Redirect URIs:
```
https://auth.private.example.com/oauth2/sign_in
https://auth.private.example.com/oauth2/callback
```
My understanding is that this is just a whitelist, Azure will just redirect back to whatever was in the query arg `redirect_uri`. I have tried to remove the `sign_in` one but it made no difference.

Logout URL:
```
https://auth.private.example.com/oauth2/sign_out
```
I probably don't need one, but it looks like I should fill it in.

When I have no oauth cookies for  .private.example.com and try going to `app.private.example.com`, and I am actually not logged in at the external provider, I see the log in screen and the full address in the address bar is:
```
https://login.microsoftonline.com/<redacted>/oauth2/authorize?approval_prompt=force&client_id=<redacted>&redirect_uri=https%3A%2F%2Fauth.private.example.com%2Foauth2%2Fcallback&response_type=code&scope=openid+offline_access+User.Read&state=8a56b0773156913c6ad5b0850b8b94e1%3Ahttps%3A%2F%2Fapp.private.example.com%2F
```

Not sure what this `state` arg is, but it seems to be sent back to oauth2 proxy.

Once I log in, I am redirected to the app.private.example.com URL and see the 500 error.
However, the successful authentication is logged in oauth2 proxy pod logs:
```
[AuthSuccess] Authenticated via OAuth2: Session{email:support@example.com user: token:true id_token:true created:2020-04-01 19:26:18.444578405 +0000 UTC m=+533908.131529290 expires:2020-04-01 20:26:18 +0000 UTC refresh_token:true}
10.244.0.140 - - [2020/04/01 19:26:18] auth.private.example.com GET - "/oauth2/callback?code=AQABAAI7g0g...&state=8a56b0773156913c6ad5b0850b8b94e1%3ahttps%3a%2f%2fapp.private.example.com%2f&session_state=fe47e...
```

So far so good, but no indication of why we ended up with the error.

Ingress nginx logs have the following:
```
10.244.0.1 - - [01/Apr/2020:19:26:18 +0000] "GET /oauth2/callback?code=AQABAAIAAAAm-0...&state=8a56b0773156913c6ad5b0850b8b94e1%3ahttps%3a%2f%2fapp.private.example.com%2f&session_state=fe47e... HTTP/2.0" 302 58 "https://login.live.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 1537 0.473 [oauth2-proxy-oauth2-proxy-80] [] 10.244.0.173:4180 58 0.476 302 70b3607cf363cd0f56d52ae139d5ae06
10.244.0.1 - - [01/Apr/2020:19:26:19 +0000] "GET / HTTP/2.0" 400 0 "https://login.live.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0 0.006 [kube-system-kubernetes-dashboard-80] [] 51.140.27.8:443 0 0.004 400 80fc080f7b50fd5d85d04172cec6616b
2020/04/01 19:26:19 [error] 1982#1982: *4187682 auth request unexpected status: 400 while sending to client, client: 10.244.0.1, server: dash.private.agenarisk.com, request: "GET / HTTP/2.0", host: "app.private.example.com", referrer: "https://login.live.com/"
```
I have not noticed this before, but the first mention of error 400 appears to be associated with `[kube-system-kubernetes-dashboard-80]`. Now it is relevant to say that the `app.private.example.com` is the Kubernetes dashboard service.

In order to exclude a problem with the kubernetes dashboard I have tried to point the ingress for `app.private.example.com` to another service that works fine.

After doing that and trying to open the page for `app.private.example.com` I still see error 500 in the browser and ingress log shows an error similar to what it was before.
```
10.244.0.1 - - [01/Apr/2020:21:41:12 +0000] "GET / HTTP/2.0" 400 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0 0.007 [default-demo-asia-d2-80] [] 51.140.27.8:443 0 0.004 400 62be12de395e1f2d810f6a9e4bac9c00
```

So I have to assume that the problem is not with the service at `app.private.example.com`. In fact, nginx logs for that pod do not appear to contain any requests, so the whole thing falls apart before it actually gets to the final service.

**Comment by edemen** [comment]
I have been able to get this to work with Github as external provider, so there must be more Azure-related config that I am missing... Interesting.

**Comment by GuyPaddock** [comment]
The 5xx error is caused by specifying `cookie-refresh`; refresh is apparently not implemented fully/properly for Azure. Just ran into this myself.

See:
- https://github.com/oauth2-proxy/oauth2-proxy/issues/260
- https://github.com/oauth2-proxy/oauth2-proxy/pull/278 (stale)

**Comment by edemen** [comment]
Wow. I would not have thought to try to remove that. As soon as I commented out cookie-refresh it started working.
You are a saviour, thanks!

**Comment by edemen** [comment]
I have just discovered that the same thing (error 400 -> error 500) happens if I use `set-authorization-header: true`
This is rather unfortunate as I am trying to get auth header working.
Any ideas why this setting would cause an error 400?

**Comment by JoelSpeed** [comment]
@edemen The azure provider doesn't implement a lot of the features and unfortunately a lot of our flags are not compatible with the provider. This is something I'd like to address but I doubt I'll have any time to look at that in the near future.

I would suggest you look into using the OIDC provider with Azure (it should be compatible, I know other have had success in the past with it), then the features you want will be available

**Comment by edemen** [comment]
I have tried to use OIDC with Azure just now.
```
provider: oidc
oidc-issuer-url: https://sts.windows.net/<tenant>/
```
Funny how the trailing slash is obligatory else I get the error about issuer mismatch.
Discovery seems to work fine and I can log in, as with `provider: azure`
Side note: If I use URL `https://login.microsoftonline.com`, the actual issuer returned from the server is the `sts.windows.net`.

However, as soon as I add `set-authorization-header: true`, the same error 400 comes back in Ingress logs, and I see error 500 on the screen.

I'm really not sure what to do with this. Somebody else suggested to use `set-authorization-header: true` in https://github.com/MicrosoftDocs/azure-docs/issues/23789 and looks like for them it even seemed to work when provider was azure.

I suppose I could abandon the idea of setting headers from authentication and skip the dashboard sign-in, but I really liked the idea of being able to access the dashboard as the user who is logged in.

**Comment by JoelSpeed** [comment]
@edemen There's nowhere in the code that an error can be caused, that I can see, by adding this option, can you please provide the config file or args as they appear once deployed rather than through the helm template as you've provided, this might help to understand what settings are actually causing this issue

Could you clarify for me, are you clearing your sessions between testing?

I suspect you are being hit by a problem with your cookies when they are being encrypted, the following line sets up a cipher to encrypt cookies depending on which config options you provide, this aligns with when you're seeing the error. I suspect the problem is that your cookies are becoming split and being too large for nginx.
https://github.com/oauth2-proxy/oauth2-proxy/blob/bdc686103e534a24eda0a04f897fe363ef9a90fd/options.go#L334

I would recommend switching from cookie storage to redis storage for your sessions, enable these options and see if that works

**Comment by edemen** [comment]
@JoelSpeed 

Thanks

> Could you clarify for me, are you clearing your sessions between testing?

Yes, I am clearing all browser cookies between testing attempts.

```
kubectl edit deployment oauth2-proxy -n oauth2-proxy

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-09T16:28:03Z"
  generation: 1
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-2.4.1
    heritage: Helm
    release: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
  resourceVersion: "64087258"
  selfLink: /apis/apps/v1/namespaces/oauth2-proxy/deployments/oauth2-proxy
  uid: d00acd7e<redacted>9187b2549d10
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oauth2-proxy
      release: oauth2-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: c4<redacted>c1
        checksum/config-emails: 01<redacted>6b
        checksum/google-secret: e3<redacted>55
        checksum/secret: e3<redacted>55
      creationTimestamp: null
      labels:
        app: oauth2-proxy
        release: oauth2-proxy
    spec:
      containers:
      - args:
        - --http-address=0.0.0.0:4180
        - --cookie-domain=.private.example.com
        - --cookie-samesite=none
        - --cookie-secure=true
        - --oidc-issuer-url=https://sts.windows.net/fd172<redacted>f6f/
        - --provider=oidc
        - --redirect-url=https://auth.private.example.com/oauth2/callback
        - --scope=openid offline_access User.Read user:email
        - --set-authorization-header=true
        - --whitelist-domain=.private.example.com
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: oauth2-proxy-creds
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: oauth2-proxy-creds
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie-secret
              name: oauth2-proxy-creds
        image: quay.io/pusher/oauth2_proxy:v5.1.0
        imagePullPolicy: IfNotPresent
...
```

Just to confirm, this ends up with an error after a successful login. However, if I remove `- --set-authorization-header=true` editing the deployment in place, clear cookies and retry, I can access protected domain fine.

> I suspect the problem is that your cookies are becoming split and being too large for nginx.

I think I had some problem with that, which was mitigated by adding an annotation to the protected service's ingress:
`nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"`
I will try to set up a redis and see if I can get it working, but never used it before so will probably need to set some time aside for that.

Cheers

**Comment by onixie** [comment]
Hi @JoelSpeed 

I'm also encountering the same issue but everything was fine until I was forcibly changed to use multi-factor authentication(using an SNS message with a verificaton code everytime I login). 

The weired thing is my colleagues can still login (without need to input verification code) without any errors. We compared the cookie and there is no big difference in sizes.

**Comment by onixie** [comment]
I found the failure in my case was actually caused by Azure AD with security defaults enabled. After turning it off, the MFA stops asking me for verification code during logging-in and the nginx ingress controller in my k8s stops yield 400 errors even the login succeeds. I'm now able to login to kubernetes dashboard again.

https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults

**Comment by AMoghrabi** [comment]
Hello @onixie or @edemen,

I'm trying to configure our kubernetes-dashboard in the same fashion as you are but I'm struggling. I was hoping I could get your help.

Here is what I'm passing into my `oauth2-proxy` service (I'm using the helm chart):

```
      provider: oidc
      upstream: "file:///dev/null"
      http-address: "0.0.0.0:4180"
      oidc-issuer-url: https://sts.windows.net/<tenant_id>/
      scope: openid offline_access User.Read user:email
``` 

Upon logging into Azure, I receive a 500. The oauth2 proxy throws the following error:

```
Error redeeming code during OAuth2 callback: unable to update session: couldn't extract claims from id_token (&{%!e(string=id_token did not contain an email)})
```

Would really appreciate your help as I've been working on this for quite some time now. Thanks

**Comment by edemen** [comment]
> Hello @onixie or @edemen,
> 
> I'm trying to configure our kubernetes-dashboard in the same fashion as you are but I'm struggling. I was hoping I could get your help.
> 
> Here is what I'm passing into my `oauth2-proxy` service (I'm using the helm chart):
> 
> ```
>       provider: oidc
>       upstream: "file:///dev/null"
>       http-address: "0.0.0.0:4180"
>       oidc-issuer-url: https://sts.windows.net/<tenant_id>/
>       scope: openid offline_access User.Read user:email
> ```
> 
> Upon logging into Azure, I receive a 500. The oauth2 proxy throws the following error:
> 
> ```
> Error redeeming code during OAuth2 callback: unable to update session: couldn't extract claims from id_token (&{%!e(string=id_token did not contain an email)})
> ```
> 
> Would really appreciate your help as I've been working on this for quite some time now. Thanks

Could this be due to cookie size? Do you have anything like this in the ingress' annotations for the dashboard?
```
nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
```

**Comment by onixie** [comment]
Hi @AMoghrabi 

The buffer size of the ingress nginx is definitely one thing I would like to check. Beside that, could you confirm the token configuration to see if you have the email included in the claim.

![image](https://user-images.githubusercontent.com/817073/86419595-98dc7d00-bd0e-11ea-9b1b-d3e5da2a4a9c.png)

**Comment by edemen** [comment]
I don't have any claims in token configuration.
Btw I am also not using OIDC for Azure. See my opening post for detailed configuration I was using.

**Comment by AMoghrabi** [comment]
Thanks to both of you :) I can't remember if I tried setting the buffer size, I'll try that tomorrow. Also I am positive I didn't have claims so I'll give that a go as well. Thank you!

**Comment by v01d-bak3r** [comment]
@edemen I'm facing the same error for ADFS. However removing the args :
```cookie-refresh
pass-authorization-header: true
set-authorization-header: true
pass-access-token: true
``` doesn't resolve the issue. Is there something else I'm missing here?

**Comment by dulakm** [comment]
This issue is still very present. I relate with everything said here so far and can replicate it on oauth2-proxy:v7.2.0.

**Comment by engineerXIII** [comment]
I am able to replicate issue with ADFS provider on oauth2-proxy:v7.2.1.  @edemen  Any workaround found?
