### ISSUE TITLE
Cannot use an upstream URL with an escaped path (%2F)

### ISSUE THREAD

**Issue by chkohner** [oauth2-proxy/oauth2-proxy#459]
If you try to add an upstream URL with an escaped path such as `http://127.0.0.1:8000/a%2Fb/` it will instead bind to the unescaped path `/a/b/` (and the unescaped upstream version as well: `http://127.0.0.1:8000/a/b/`).

## Expected Behavior

Using any valid upstream URL with a path should be retained exactly in the proxy's mapping table and not changed during the process.

## Current Behavior

If you try to add an upstream URL with an escaped path such as `http://127.0.0.1:8000/a%2Fb/` it will instead bind to the unescaped path `/a/b/`.

## Possible Solution

In my investigation into this bug, it looks like there's an underlying failure in Go's `http.NewServeMux()` as well, that even if the parsing in oauth2_proxy is fixed, Go's path multiplexor exhibits the same behavior, and calling `serveMux.Handle('/a%2Fb/', proxy)` results in it registering the '/a/b/' path instead. So every request to the proxy thereafter just results in an unmatched handler for that path.

I haven't tested to see if <https://github.com/gorilla/mux> has the same issue, but it may be a viable alternative.

## Context

This particular issue is probably not that serious, but it was discovered while writing some unit tests to ensure the path is retained correctly. 

- Version used: 5.0.0/master (362cdf7713b7f3cb25647e6afd94f370d7c6cd7d)

**Comment by bruegth** [comment]
Maybe related to this one:

> Note that the Path field is stored in decoded form: /%47%6f%2f becomes /Go/. A consequence is that it is impossible to tell which slashes in the Path were slashes in the raw URL and which were %2f. This distinction is rarely important, but when it is, the code should use RawPath, an optional field which only gets set if the default encoding is different from Path.

(https://golang.org/pkg/net/url/#URL)

**Comment by chkohner** [comment]
Yeah, it is. The built-in serveMux doesn't use RawPath, I'm guessing because that came in afterward and they are loathe to break existing functionality (even when that functionality is technically a bug in many cases).

**Comment by chkohner** [comment]
Not stale.

**Comment by JoelSpeed** [comment]
If we can drop in a different mux that will fix this without breaking existing routing then I'm happy to accept that change, question is whether we should consider this a breaking change or not for our users
