### ISSUE TITLE
Support for proxying API and returning 401 on not authentiacted

### ISSUE THREAD

**Issue by ScottGuymer** [oauth2-proxy/oauth2-proxy#461]
## Expected Behavior

Im looking to use the proxy to secure an API. When an invalid token is passed in the Auth header I would like the proxy to return a 401 and not redirect to the provider.

Is this possible with config?

## Current Behavior

The current behaviour is to validate the token and if invalid returns a 302 to the provider login which is not valid as this is just an API

## Possible Solution

Allow configuration for "API mode" that just does validation of the token and returns the proxied result or a 401

**Comment by JorenZ** [comment]
Setting `- --upstream=static://200` (https://oauth2-proxy.github.io/oauth2-proxy/configuration) might yield the desired behavior. Would that work?

**Comment by JoelSpeed** [comment]
I would suggest using something like Nginx with the auth request mode to achieve this

**Comment by ScottGuymer** [comment]
In the end I used Envoy proxy to proxy our API and validate the tokens.
