### ISSUE TITLE
Docs does not work

### ISSUE THREAD

**Issue by sepich** [oauth2-proxy/oauth2-proxy#465]
## Expected Behavior
Project link on top of page https://oauth2-proxy.github.io/oauth2-proxy should show the page correctly.
The same with link in Readme:
Read the docs on our Docs site (https://pusher.github.io/oauth2_proxy).

## Current Behavior
First link - site is broken (js, css - 404)
Second link - 404

## Steps to Reproduce (for bugs)

1.  https://oauth2-proxy.github.io/oauth2-proxy
2.  https://pusher.github.io/oauth2_proxy

## Context
I was trying to understand how to use the proxy, but unable to find docs ;(

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
Hi, we are currently migrating the project from one location/name to the other (see #464)

The docs will be fixed once the migration is complete.

Apologies for any inconvenience in the mean time.

If you have ruby on your machine I would encourage you to check out the code locally and run `make -C docs serve` to show the docs site locally

**Comment by JoelSpeed** [comment]
Docs are back, please reopen if you find issues with them now that they have been migrated
