### ISSUE TITLE
Merge of Keycloak Gatekeeper into this Project?

### ISSUE THREAD

**Issue by bruegth** [oauth2-proxy/oauth2-proxy#470]
@JoelSpeed @abstractj @stianst
Are there any plans to move the Keycloak's Gatekeeper Project (https://github.com/keycloak/keycloak-gatekeeper) into this oauth2-proxy Project (Both are written in Go)?

**Comment by kfox1111** [comment]
Different goals I think. oauth2-proxy seems to be gaining a lot of features and becomes sort of like a lightweight Keycloak in addition to Gatekeeper. oauth2-proxy provides a way to let the user multiplex between a lot of different auth mechanisms and do auth termination of multiple backend services. In Keycloak there is clear delineation of those two tasks. The first is handled by Keycloak. The second is handled by multiple Gatekeepers.

**Comment by bruegth** [comment]
From Readme of Gatekeeper:
>  The Gatekeeper is most happy in the company of Keycloak, but is also able to make friends with other OpenID Connect providers.

**Comment by stianst** [comment]
We are actually working on moving Gatekeeper out of the Keycloak project to make it a standalone project. It already does support other providers than Keycloak, but the aim is to make this more obvious when it is moved to a new repository.

**Comment by stianst** [comment]
@kfox1111 if your statement that oauth2-proxy seems to become a sort of a lightweight Keycloak then I think it may be providing features or capabilities that it shouldn't be doing. It's a proxy right? Not an IdP or Authorization Server. Can you elaborate on what you mean by this statement?

**Comment by JoelSpeed** [comment]
@kfox1111 I'd also be intrigued to hear your thoughts about why oauth2-proxy is like a mix of keycloak and gatekeeper, if you have time to elaborate on that, please do!

**Comment by kfox1111** [comment]
> @kfox1111 I'd also be intrigued to hear your thoughts about why oauth2-proxy is like a mix of keycloak and gatekeeper, if you have time to elaborate on that, please do!

I was under the impression based on this graphic:
https://cloud.githubusercontent.com/assets/45028/4970624/7feb7dd8-6886-11e4-93e0-c9904af44ea8.png
that multiple auth providers could be configured at once and the user could choose between them, like Keycloak does. After digging a bit recently, I'm not sure that actually is the case? Is that a planned/existing feature?

If that's not the case, the other thing I can think of is the amount of code in oauth2_proxy that is specific to each auth provider. There's a lot of code there. In a keycloak + gatekeeper arrangement, gatekeeper itself has very little code relating to auth provider and instead, a lot of the provider specific code is in Keycloak.

I guess the other feature, as I mentioned previously, is the multiplexing setup. In a Keycloak setup, you have one keycloak and each backend service gets its own gatekeeper. With an oauth2_proxy setup, you may have one proxy terminating several backends. That makes it more centralized like keycloak. One thing deals with the auth provider, and then multiple backends are hung off of that. But, you don't need to run it that way.

This is just some musings after using both for a while. I could be wrong.

**Comment by JoelSpeed** [comment]
> I was under the impression based on this graphic:
https://cloud.githubusercontent.com/assets/45028/4970624/7feb7dd8-6886-11e4-93e0-c9904af44ea8.png
that multiple auth providers could be configured at once and the user could choose between them, like Keycloak does. After digging a bit recently, I'm not sure that actually is the case? Is that a planned/existing feature?

This is not currently the case, you can only use a single provider right now. Though I hope to enable multiple providers once we make the move to a structured configuration file. This would allow us to define each of the provider options multiple times as part of a list of `provider` objects

> If that's not the case, the other thing I can think of is the amount of code in oauth2_proxy that is specific to each auth provider. There's a lot of code there. In a keycloak + gatekeeper arrangement, gatekeeper itself has very little code relating to auth provider and instead, a lot of the provider specific code is in Keycloak.

In my experience, users have been reluctant to run a second process for this purpose. Numerous times I have suggested users run Dex and connect OAuth2 Proxy to that to get the features they require, but I kept getting resistance.

I appreciate your musings, very interesting to see you draw a comparison in this way, I now understand where your previous comment came from, thanks :)
