### ISSUE TITLE
Login URL ignored

### ISSUE THREAD

**Issue by livius100** [oauth2-proxy/oauth2-proxy#472]
Hello everyone,

I'm trying to run a oauth2-proxy v.5.0.0 in docker using a custom build with gitlab (local build) as provider, but no mater what I put under "login_url" is being ignored and it redirects to "https://gitlab.com/users/sign_in" 
## Expected Behavior
Being redirected the my gitlab local build URL
## Your Environment
Dockerfile:
`FROM alpine

ENV OAUTH2_PROXY_URL="https://github.com/oauth2-proxy/oauth2-proxy/releases/download"
ENV OAUTH2_PROXY_CLIENT_SECRET="(deleted)"
ENV OAUTH2_PROXY_CLIENT_ID="(deleted)"
ENV OAUTH2_PROXY_COOKIE_SECRET="(deleted)"

RUN apk --update --no-cache add curl

RUN curl -Lo /tmp/oauth2_proxy-v5.0.0.linux-amd64.go1.13.6.tar.gz \
             ${OAUTH2_PROXY_URL}/v5.0.0/oauth2_proxy-v5.0.0.linux-amd64.go1.13.6.tar.gz \
    && tar -xzvf /tmp/oauth2_proxy-v5.0.0.linux-amd64.go1.13.6.tar.gz -C /tmp/ \
    && chmod +x /tmp/oauth2_proxy-v5.0.0.linux-amd64.go1.13.6/oauth2_proxy \
    && mv /tmp/oauth2_proxy-v5.0.0.linux-amd64.go1.13.6/oauth2_proxy /bin/oauth2_proxy

COPY ./oauth2-proxy.cfg /etc/oauth2-proxy.cfg
ENTRYPOINT ["/bin/oauth2_proxy", "-config=/etc/oauth2-proxy.cfg" ]
`
oauth2-proxy.cfg:
`http_address = "0.0.0.0:4180"
redirect_uri = "(deleted)"
login_url = "(deleted)/oauth/authorize"
redeem_url = "(deleted)/oauth/token"
validate_url = "(deleted)/api/v4/user"
email_domains = "*"
upstreams = "(deleted)"
provider = "gitlab"
scope = "read_user"
approval_prompt = "disable"
`
Can somebody please suggest what I'm missing?
Thank you!

**Comment by tambetliiv** [comment]
try `oidc_issuer_url = "https://on.premise.gitlab.company.com"`
instead of 
```
redirect_uri = "(deleted)"
login_url = "(deleted)/oauth/authorize"
redeem_url = "(deleted)/oauth/token"
validate_url = "(deleted)/api/v4/user"
```
source https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#gitlab-auth-provider
