### ISSUE TITLE
provider-display-name does not change the display name

### ISSUE THREAD

**Issue by joker32** [oauth2-proxy/oauth2-proxy#476]
Hello.

I have added the option "provider-display-name" to my config file. Provider is defined as "azure". Unfortunately the display name does not change, it still says "Azure".

provider = "azure"
provider-display-name = "Custom Name"

![image](https://user-images.githubusercontent.com/2000896/78348333-24c0fa80-75a2-11ea-9e15-dc4681483b69.png)

Thanks!
Max

**Comment by JoelSpeed** [comment]
@joker32 Options in config files need to use underscores instead of hyphens, double check your config as it should be `provider_display_name` not `provider-display-name`

**Comment by joker32** [comment]
Damn, rookie mistake. ;)
Thanks!
