### ISSUE TITLE
Match skip-auth-regexs option against X-ORIGINAL-URI header

### ISSUE THREAD

**Issue by RaoulDijksman** [oauth2-proxy/oauth2-proxy#477]
The `/oauth2/auth` endpoint is used with the NGINX auth_request directive. In such a setup, the OAuth2Proxy is not a reverse proxy and the `skip-auth-regexs` doesn’t work as the URI is always `/oauth2/auth`. It would be nice if this endpoint used the `X-ORIGINAL-URI` header to match against the list of regexes. 

## Expected Behavior

`/oauth2/auth` returns a 202 when the URI in the `X-ORIGINAL-URI` header matches with a regex from the `skip-auth-regexs` config option

## Current Behavior

`/oauth2/auth` returns a 401 even when the original URI is passed in the `X-ORIGINAL-URI` header and matches against one of the passed regexes in the `skip-auth-regexs` config option.
## Possible Solution

Check the `X-ORIGINAL-URI` header and fallback to `req.URL.Path` if no header is set. Code location:
https://github.com/oauth2-proxy/oauth2-proxy/blob/8d0149ccf8eeefaf5672a41d3b9ee5d943748da1/oauthproxy.go#L612

## Context

We would like to whitelist a few paths while using the OAuth2Proxy with the NGINX auth_request directive.

## Your Environment

We are running on kubernetes with the nginx-controller. Our service ingress definition contains the auth_url and auth_redirect annotations. 

- Version used: 5.0.0

**Comment by JoelSpeed** [comment]
Can this not be configured inside Nginx? It would make more sense to skip the authentication within Nginx and not even attempt an auth request to the proxy for the paths you don't want validated

**Comment by RaoulDijksman** [comment]
It is possible to do that in Nginx. That is exactly the work around that I went for. However, we are using Kubernetes and this solution involves creating a second Ingress definition. Which is more work than just adding a config value. I agree with you that configuring it in Nginx is the better solution, if you feel like that is the recommended solution, feel free to close this issue.

**Comment by JoelSpeed** [comment]
I'm trying to keep this project lightweight and not have too many features of the bulkier proxies, I don't want this to become a full fledged reverse proxy

I believe handling in Nginx is better in the long run, and that having two ingress files isn't that much extra effort so I'm going to close this with the Nginx route as the recommendation.

**Comment by RaoulDijksman** [comment]
I understand, agreed!

**Comment by tobiasr** [comment]
+1

I'm also in a situation where I would like to whitelist some paths from authentication on kubernetes and I had to do some digging to realise why the `skip-auth-regexs` setting didn't work.

In the end I have a solution working with an extra ingress as suggested here.

To me it would have been better if the configuration solution that I verified worked when running the proxy locally (but didn't verify running as NGINX auth_request). That would have been smoother UX.

To me, perhaps it comes down to the documentation vs how easy this feature would be to implement?

I'm fine with the above decision. Just wanted to chime in that I felt confused about this aswell.

**Comment by wahyd4** [comment]
I had the same issue here when I was trying to skip auth for some path under a domain. I agree with you guys that it might be better to handle this outside the proxy.

But  I really hope we can update the document about `skip-auth-regex` giving it doesn't work as expected.
