### ISSUE TITLE
Keycloak auth provider should be using OIDC provider underneath

### ISSUE THREAD

**Issue by lmm-git** [oauth2-proxy/oauth2-proxy#479]
The documented and implemented Keycloak auth provider is using the Keycloak API but not featuring all the functionality of OIDC.

## Expected Behavior
When authenticating via Keycloak a Bearer Auth token should get sent to upstream if switch enabled.

## Current Behavior
Not sent due to the fact the Keycloak auth provider is using the keycloak API and not OIDC.

## Possible Solution
Use OIDC. Even more, the stock OIDC provider works with Keycloak. This config works for me:

```
--cookie-secret some-secret --provider=oidc --provider-display-name="Keycloak OIDC" --oidc-issuer-url=https://keycloak.some/auth/realms/someRealm --http-address=0.0.0.0:4180 --client-id kubernetes-dashboard --client-secret some-other-secret --email-domain=* --upstream=http://127.0.0.1:8100 --pass-authorization-header=true
```

## Steps to Reproduce (for bugs)

Just use the Keycloak auth provider as documented.

## Context

I want to use the oauth2-proxy together with the k8s-dashboard. Therefore I needed the possibility to proxy a bearer token. It is not very obvious that the Keycloak adapter is not supporting this (I mean, it is really, really not obvious). Only after debugging the application it became clear to me that the implementation does not provide any session.IdToken and therefore no bearer token.

My wish would be to at least document this behavior. I also do not understand the necessity of the Keycloak provider at all as it does not provide any real benefit (beside the check for the group membership which can't be done with the generic OIDC connector I think).

## Your Environment

- Version used: latest (from master)

**Comment by JoelSpeed** [comment]
Given keycloak supports OIDC, do you think the keycloak provider could be written to reuse the OIDC provider and just override the group membership?

**Comment by lmm-git** [comment]
Yes, I think this would be more or less easily possible.

**Comment by JoelSpeed** [comment]
I think we should try to do this at some point then, would hopefully reduce the amount of code we have to maintain and ideally, we can do it in a non-breaking way

**Comment by arianvp** [comment]
Why doesn't the `oidc` provider support matching arbitrary claims?

Keycloak has an `oauth2_proxy` competitor called GateKeeper that works for any oidc provider. https://www.keycloak.org/docs/latest/securing_apps/index.html#claim-matching

and it can do things like this:


```yaml
match-claims:
  aud: openvpn
  iss: https://keycloak.example.com/auth/realms/commons
  groups: admin

```

matching a token like

```json
{
  "iss": "https://sso.example.com",
  "aud": "openvpn",
  "group": ["perm1", "perm2"]
}
```

Reason I'm still using `oauth2_proxy` is because of its nginx `auth_request` support.

If we'd support this kind of generic claim matching we could perhaps get rid of all these "Specific" providers and use OIDC one where possible

**Comment by ploxiln** [comment]
@arianvp see #466 which allows using arbitrary expressions on claims

**Comment by arianvp** [comment]
Amazing. that's exactly what I was looking for!

**Comment by EvgeniGordeev** [comment]
here is an example for docker-compose when keycloak is used as OIDC provider https://github.com/oauth2-proxy/oauth2-proxy/pull/604.

**Comment by JoelSpeed** [comment]
This should still be fixed at some point
