### ISSUE TITLE
Improve Okta Docs

### ISSUE THREAD

**Issue by trevorbox** [oauth2-proxy/oauth2-proxy#480]
The redirect_url configuration within the documentation section [CONFIGURING THE OIDC PROVIDER WITH OKTA](https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#configuring-the-oidc-provider-with-okta) did not work as expected. It should match the Endpoint as documented.

Additionally, it would be nice to have a localhost example for Okta.

## Expected Behavior

The documentation correctly describes the callback url path and adds a localhost example.

## Current Behavior
The example's redirect_url = "https://example.corp.com"
No localhost example exists.

## Possible Solution

I have updated the documentation on my own fork and will submit a PR.
It updated the callback url crrectly and adds a localhost example.

## Steps to Reproduce (for bugs)

See steps in current documentation [CONFIGURING THE OIDC PROVIDER WITH OKTA](https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#configuring-the-oidc-provider-with-okta)

## Context
Improving docs.

## Your Environment
Tried my configs within containers and against current Okta admin portal.

- Version used: v5.1.0

**Comment by steakunderscore** [comment]
With #481 now merged, closing as done.
