### ISSUE TITLE
Full RBAC proxy

### ISSUE THREAD

**Issue by alexec** [oauth2-proxy/oauth2-proxy#492]
I'd like to understand if we can use oauth2-proxy for both authn and RABC authz.

Currently I have a service which has REST level 2 API (not POX or level 1) that could therefore be access controlled based just on the HTTP method and path.

I'm wondering if this is something you'd support?

**Comment by JoelSpeed** [comment]
Personally, I'd prefer to keep OAuth2 Proxy as focused on AuthN as possible and try to avoid adding too many AuthZ features, that said, we do already have some support for certain checks (Does a user meet certain restrictions), I'm not sure if we support that path based or not

**Comment by alexec** [comment]
Could you pass the claims through in a header for the downstream service to interpret?

**Comment by JoelSpeed** [comment]
Yeah this sort of thing could be done, you can already pass the ID Token using `set/pass-authorization-header` which could then be interpreted by the downstream, would that work?

**Comment by alexec** [comment]
So downstream unpacks the JWT header ?

**Comment by JoelSpeed** [comment]
Yeah, that's how the integration with things like Kubernetes works with this project

**Comment by alexec** [comment]
Excellent. My thinking has changed on this. Only the downstream service really understands the various resources and action, so it must do the RBAC, and passing the JWT would work for us.

Thank you!
