### ISSUE TITLE
Github Deprecating API authentication through query parameters - November 13, 2020 at 4:00 PM UT

### ISSUE THREAD

**Issue by PacketShepard** [oauth2-proxy/oauth2-proxy#496]
Has anyone looked into updating the built-in Github profile's authentication to Authorization header statements rather than query parameters? I'm getting constant emails when I auth that query parameters are deprecated. 

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

**The deadline for this change is November 13, 2020 at 4:00 PM UTC.**

There will be brown outs on these dates:

September 30, 2020

From 7:00 AM UTC - 10:00 AM UTC
From 4:00 PM UTC - 7:00 PM UTC
October 28, 2020

From 7:00 AM UTC - 10:00 AM UTC
From 4:00 PM UTC - 7:00 PM UTC

Version used:
5.1.0

**Comment by ploxiln** [comment]
should be fixed by https://github.com/oauth2-proxy/oauth2-proxy/pull/385
