### ISSUE TITLE
redirectURL isn't the callback path and no way to set it

### ISSUE THREAD

**Issue by stedaniels** [oauth2-proxy/oauth2-proxy#498]
It seems that this has flipflopped.  It was initially set so that redirectURL didn't affect the callback path.  It was then _fixed_ so that callback path was _correctly_ set to be the redirectURL.  Then it was reverted.  #9 

## Expected Behavior

When working with oidc and ADFS setting the redirect_uri/redirectURL is the same as setting the callback path.  If I use e.g. /sso/redirect as my redirect uri ADFS will redirect via it.  oauth2-proxy should respond to the request as it is the callback url.

## Current Behavior

oauth2-proxy isn't listening for requests on that URL it's listening on /oauth2/callback - we just get:

`[oauthproxy.go:867] Error loading cookied session: Cookie "_oauth2_proxy" not present
GET - "/sso/redirect?code=W3hwgrg2Nt0uey_pkNl-arg.Q3_sEJ3n1wiqC8bnlMZR6qd4w58.e_jQvIMHA7_9An09rqmnGzhYRq6sklspPZbFOUqAt66hEkjCYrXA27ICAx3AHrY392bgXye4JlY3HhRHYwpYZmvFvWIZLXrjKYRVqtlyod53RpZkof8_88SufmRAwiKzhtMRnhHuNw4BVyjhfTPRDlk-rb_n75fz1Ts8cLS-biLyaqji2gdIy3e2u3esSbXBzPpTjFAZ3avJ6C_p0vT2gstEBb-obvEvK7JMDAeWo24COugLESpOo_mKN5G69115ksgexKEef258EwFMWqP1_OGRbs4het_4sGQI0KUmYYI7tqc7ss5ouy2E-o3hGdunpGJEfoc3UPpEjxnT7v-ge1B6FZg&state=03e374eee123ceqwec968c96776fbb67:/&client-request-id=8d4de10d-0298-4ab3-7905-0180000000ad" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 403 2663 0.000
`

In the logs and it goes into a redirect loop.

## Possible Solution

I don't know OIDC well enough, but why doesn't oauth2-proxy use the redirectURL as the callback?
Instead of forcing the situation, add yet another var to manually configure the callback path, then at least those of us who require it can set it the same as the redirectURL.

I don't really know go, so no PR supplied, though if you'd accept an additional variable I can probably figure it out, there's plenty of precedent within the code for me to follow.

## Steps to Reproduce (for bugs)

`
provider = "oidc"
redirect_url = "https://example.corp.com/sso/redirect"
oidc_issuer_url = "https://adfs.corp.com/adfs"
proxy_prefix = "/sso"
upstreams = [
    "https://example.corp.com"
]
email_domains = [
    "corp.com"
]
client_id = "XXXXX"
client_secret = "YYYYY"
pass_access_token = true
cookie_secret = "ZZZZZ"
skip_provider_button = true
`
## Context

I'm trying to migrate from lua-resty-openidc to oauth2-proxy, I have multiple OIDC client applications connecting to ADFS all using /sso/redirect.  Being able to specify the callback would allow seamless migration.

I'll try and workaround it with redirects or nginx location proxy_pass shenanigans.

## Your Environment

ADFS

- Version used: v5.1.0

Thanks for your time

**Comment by JoelSpeed** [comment]
For context, the change was reverted in #101 based off of the discussion in #9 after it was reopened.

@stedaniels It is common for a OAuth2 provider to have a static and non-configurable callback path. With the redirect_url option you can, as you've suggested set an alternative for the proxy to tell the IDP as the redirect URL. This is intended as an option for users behind a reverse proxy to be able to adjust the callback URL for their own reasons.

You are right in that we can fix this with an extra option, though I'm a bit reluctant to suggest we do that right now as I don't see that it really adds that much value. It would, as you say, help users as yourself who need to do a migration, but I don't think it would really be used by anyone else, do you agree? 

My suggestion here would have been, as you've suggested, set up Nginx to do a rewrite in front of OAuth2 Proxy for the moment, and then change your Azure configuration to put the callback back to the Oauth2 Proxy callback once you've migrated, then remove the Nginx rewrites. I apologise this probably isn't that helpful

**Comment by stedaniels** [comment]
You are right, thank you for the reply.  It is helpful that I now have a firm direction to go in.  With the use for it previously, I thought there might have been some demand there for it.  I'll temporarily workaround it with nginx redirects and then get the ADFS IDP configuration updated to match oauth2-proxy callback URL.

Thanks again for the reply.

Steve
