### ISSUE TITLE
Questions around OpenShift and auto-logout (looking to use this instead)

### ISSUE THREAD

**Issue by a-roberts** [oauth2-proxy/oauth2-proxy#506]
Hi all, we've been using https://github.com/openshift/oauth-proxy to secure the Tekton Dashboard https://github.com/tektoncd/dashboard for many months now and it appears to be too inactive for our requirements.

One suggestion to get around a couple security concerns we have, is to use this project as a solution instead.

I have two questions before I dig in and start kicking the tires, hoping I can get some insights first to save some time!

1) How good is the OpenShift support? So specifically at the moment one has to log in to OpenShift and that's how you'll get to the Dashboard, otherwise there is no login functionality. https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration doesn't mention OpenShift as a provider
2) Can we auto-logout users?
https://github.com/tektoncd/dashboard/issues/1254 is something we'd like to address, but https://oauth2-proxy.github.io/oauth2-proxy/configuration doesn't mention anything in terms of a timeout or anything done automatically

Any insights would be great, thanks in advance everyone

**Comment by ploxiln** [comment]
`cookie-expire` and `cookie-refresh` are the most relevant config options (there is no other kind of auto-logout). oauth2-proxy signs a timestamp along with the rest of the cookie so it can be sure the cookie is no longer trusted after intended expiry.

**Comment by ploxiln** [comment]
(and there's also a manual logout endpoint, `/auth2/sign_out`, and the user could theoretically be redirected there by an upstream application/service)

**Comment by davidkarlsen** [comment]
@a-roberts did you get it to work with openshift?
