### ISSUE TITLE
🎉🍾🎉 Woot Woot 1000 Commits  🎉🍾🎉

### ISSUE THREAD

**Issue by Izzette** [oauth2-proxy/oauth2-proxy#508]
<img width="1002" alt="Screenshot 2020-04-29 at 20 57 20" src="https://user-images.githubusercontent.com/7987724/80635457-3049f900-8a5c-11ea-8ade-45d397ae6b47.png">

**Comment by JoelSpeed** [comment]
We've come a long way since taking over from Bitly! Though I hadn't realised quite how far! 🎉

**Comment by Izzette** [comment]
Closing as there is now more than 1000 commits on master.
