### ISSUE TITLE
OAuth Security Report

### ISSUE THREAD

**Issue by Mik317** [oauth2-proxy/oauth2-proxy#511]
Hi Team,
I'm a security researcher from HackerOne (Mik317).
Recently I came across a piece of code that I believe contains a possible attack that would allow malicious actors to break the behaviour of the proxy.

Let me know if I can share here all the infos or if I have to send you infos through mail :)

Regards,
Mik

**Comment by JoelSpeed** [comment]
Please reach out to me on the Gophers slack or email me from the email listed on my GitHub profile

Please do not post any further details publicly

**Comment by Mik317** [comment]
Hi @JoelSpeed :),
I'm sending you the email with all the information at Joel.speed@hotmail.co.uk ;)

Best, Mik

**Comment by Mik317** [comment]
Hi @JoelSpeed :),
I've sent the issue info to your mailbox right now :)

Regards, Mik

**Comment by JoelSpeed** [comment]
I've received the details for this and am looking into a fix.

I've removed all the details I can from this issue as the particulars of the report should not be public until a fix is found.

If anyone finds a security issue in the future and see's this issue, please follow my advice from above and email me on the public email from my GitHub profile.

Locking this issue now
