### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by marcosnils** [oauth2-proxy/oauth2-proxy#516]
Seems like there's been several commits since the last release and we're specifically waiting for https://github.com/oauth2-proxy/oauth2-proxy/commit/a659b9558eaa65ed5792b064bc7b3a35f0e80fbe to use the official images internally. Are there any plans to craft a new release soon? Is there something we can help with to make this happen?

**Comment by JoelSpeed** [comment]
We had a discussion between maintainers earlier this year and decided we would like to try a quarterly release schedule (End of March, June, September, December) if we are doing breaking changes, to give us time to get as many breaking changes in as possible and hopefully reduce the frequency of major version bumps.

Currently, we have a number of breaking changes merged into master so I would like to keep to the schedule, end of June for the v6.0.0 release.

That said, there are, as you've pointed out, a number of non-breaking changes merged as well. I could potentially cherry-pick some of the non-breaking changes on top of the 5.1.0 release and create a non-breaking 5.2.0 release.

I'd be intrigued to know how other org members feel about this idea @syscll @steakunderscore @ploxiln @gargath 

This is complicated, potentially, by the move to `oauth2-proxy/oauth2-proxy` so it may not be viable

**Comment by ploxiln** [comment]
The moved project and slight renaming seems like a good excuse to do the next major release earlier than planned. With flag and config changes, and some other refactorings, it seems like backporting fixes may not be trivial.

I suggest making a beta release first, and telling people who want a release ASAP to use that, and then a few weeks later making the "stable" release.

**Comment by marcosnils** [comment]
> I suggest making a beta release first, and telling people who want a release ASAP to use that, and then a few weeks later making the "stable" release.

Looks like a good plan. We're happy to be beta testers here :)

**Comment by xellsys** [comment]
Hi, from our side an earlier release (also with a limited feature set) would be beneficial. We are especially looking forward to configuring the user id claim.
Thanks for all your hard work on this repository. We are looking to contribute if we can.

**Comment by JoelSpeed** [comment]
I had a chat with @steakunderscore yesterday and we concluded that we would be happy to create a new release once we have a few issues/PRs sorted. So we are going to try and prioritise those
In particular I know we mentioned:
- #520 
- #530 
- #414 
- #515 
Bonus points, would be nice to get #524 in too

As for helping to get this out, it's always helpful if you can review other PRs that have been raised looking for code quality and breaking changes in particular, plus how the PRs may affect other users

**Comment by xellsys** [comment]
Any chance #431 could make the cut? We (my team) might be able to support as well. Be it PR or otherwise.

**Comment by JoelSpeed** [comment]
#431 is already fixed in master so it will be in the next release

I've also opened #535 which is a breaking change so I'd like to get that into the next release as well

**Comment by JoelSpeed** [comment]
I'd also like to get #537 in as it's a breaking change that is blocking some other work

**Comment by gps035** [comment]
Am I correct in thinking that #431 has not yet been released? I was just trying to add `--user-id-claim` after seeing it in the docs and arrived here after debugging. Unfortunately I need that flexibility as my IDP is returning the email claim with a different key, so would it be best to build a docker image myself for now?

**Comment by JoelSpeed** [comment]
@gps035 That's correct, it will be part of the v6.0.0 release. Apologies that the docs are not in sync with the current release, we should fix that

**Comment by JoelSpeed** [comment]
I believe #558 has highlighted a bug that should be considered a release blocked.

I also created a project to track all of the outstanding work before the next release which you may be interested in following https://github.com/oauth2-proxy/oauth2-proxy/projects/2

**Comment by JoelSpeed** [comment]
New release has been cut, docker images coming soon, closing this for now
