### ISSUE TITLE
Documentation: Azure AD Logout URL path when using multiple redirect URIs?

### ISSUE THREAD

**Issue by scyto** [oauth2-proxy/oauth2-proxy#517]
I have configured my nginx and Azure AD as described in the documentation.
I use the same azure app registration for multiple apps as per the docs.
I am specifying in AAD multiple host URIs for each service I have internally:

- https://service1.mydomain.tld/oauth2/callback
- https://service2.mydomain.tld/oauth2/callback
- https://serviceN.mydomain.tld/oauth2/callback

This is because wildcards are not supported.

However there is only one Logout URL per azure app registration and I am unclear what this should be - for example do i need to be creating a generic logout server that points to some ouath proxy logout page?

Currently I have it just set to https://service1.mydomain.tld/oauth2/sign_out.

BTW everything seems to works ok, just this part of the Azure AD UI coupled with no mention of it in the wiki docs confused me as to what was a best practice / right approach.

If someone can clarify here I  will happily do my small part and update the docs.

**Comment by JoelSpeed** [comment]
@scyto Could you please clarify, are you attempting to use one single instance of OAuth2 Proxy or do you have one set up for each subdomain?

**Comment by scyto** [comment]
One instance of oauth2 docker container.
In nginx there is a server section per service that points to the oauth container.
In Azure it looks like this the following picture.
As I say everything it working ok and my apps are not designed to responds to any form of logoff.
So maybe it doesn't matter?

![image](https://user-images.githubusercontent.com/11369180/81194816-f2743580-8f71-11ea-905e-d601df44505f.png)

**Comment by JoelSpeed** [comment]
You should be able to host a single oauth2 proxy on say `oauth2-proxy.example.com` behind your nginx, then set up your Azure to point to just that one instance.

You'll need to whitelist domain the service names you wish to redirect to unless they are all under the same domain, in which case you can whitelist all subdomains of a certain domain
