### ISSUE TITLE
Invalid instructions for okta?

### ISSUE THREAD

**Issue by ghostsquad** [oauth2-proxy/oauth2-proxy#518]
## Expected Behavior

The documentation accurately describes how to setup Okta and the Oauth2proxy configuration.

## Current Behavior

https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#configuring-the-oidc-provider-with-okta

> Navigate to Applications then select Add Application.

>    Select Web for the Platform setting.
>    Select OpenID Connect and click Create
>    Pick an Application Name such as Example App.
>    Set the Login redirect URI to https://example.corp.com.

> Create a configuration file like the following:

> provider = "oidc"
> redirect_url = "https://example.corp.com/oauth2/callback"

When the Okta "Redirect URI" is set such as "https://example.corp.com"

But the Oauth2PRoxy Redirect URI is set such as "https://example.corp.com/oauth2/callback"

Okta complains with a 400 Bad Request. The 'redirect_uri' must be an absolute URI that is whitelisted in the client app settings.

## Possible Solution

Update the documentation, or possibly help with why this doesn't work as expected.

## Steps to Reproduce (for bugs)

```
- args:
        - -provider=oidc
        - -oidc-issuer-url=https://example.okta.com
        - -http-address=0.0.0.0:8080
        - -cookie-secure=true
        - -cookie-domain=.k8s.nonprod.us-west-2.example.com
        - -cookie-expire=8h
        - -cookie-refresh=1h
        - -cookie-name=_oauth2_proxy_web_gemini-web
        - -redirect-url=https://my-app.k8s.nonprod.us-west-2.example.com/oauth2/callback
        - -upstream=http://web.my-namespace.svc.cluster.local:80
        - -email-domain=*
        - -whitelist-domain=.k8s.nonprod.us-west-2.example.com
```

okta side - `Login redirect URIs`

```
https://my-app.k8s.nonprod.us-west-2.example.com 
```

## Context

I'm trying to wrap my head around what is expected on the Okta side vs the Oauth2proxy side. 

## Your Environment

- Version used: `v.5.1.0`

**Comment by ghostsquad** [comment]
Other information, unlike the many articles out there, I'm trying to get this to work without using the nginx ingress.

So my ingress simply sends all traffic through the oauth2proxy. No special annotations.

**Comment by JoelSpeed** [comment]
I think the docs are wrong, the redirect URI that you configure in OKTA should match that set in OAuth2 Proxy, it should be `"https://example.corp.com/oauth2/callback"` I believe.

Can you give that a try and let me know if that fixes it?

**Comment by ghostsquad** [comment]
Yes, when the URLs match it works

I don't understand how this relates to the domain-whitelist flag

**Comment by JoelSpeed** [comment]
The whitelist domain is not relevant for your setup I don't think. It's just a list of allowed redirect targets in case you are protecting multiple domains with a single proxy

**Comment by ghostsquad** [comment]
Well, I would like to protect multiple domains with a single proxy, but the documentation doesn't explain how to do that well.

**Comment by ghostsquad** [comment]
I suppose that's a separate issue, do you want me to open a new issue?

**Comment by JoelSpeed** [comment]
Preferably we would keep this issue focused on the broken Okta docs

**Comment by sitaramkm** [comment]
@ghostsquad have you managed to get oauth2 proxy to work with Okta. I had success with GitHub but running into issues with the right set of args in the OAuth2 proxy deployment resource. Also, not sure if any additional annotations are needed for the Ingress resource. Can you share what you have configured ? The documentation unfortunately is lacking a bit for Okta and OAuth2 proxy.

On a separate note, I have managed to protect multiple domains with a single proxy (again with GitHub). Let me know if you have a created a separate issue and I will provide the information I have.

**Comment by yongzhang** [comment]
I saw there's an `upstreams` parameter there, can anyone help to clarify what it is and is it required? Thanks.

**Comment by Rohlik** [comment]
@yongzhang 

> Upstream represents the configuration for an upstream server. Requests will be proxied to this upstream if the path matches the request path.

**Comment by Rohlik** [comment]
For new visitors from internet, the Okta docs was moved here - https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#okta
