### ISSUE TITLE
Code scanning workflow breaks forks due to codeql

### ISSUE THREAD

**Issue by chkohner** [oauth2-proxy/oauth2-proxy#521]
It looks like once this change 842d764a5f4f56c9f021c8d32421ae3fb68d1c97, is pulled into a fork (for example to sync with upstream changes), it causes that repo to start failing because of:

```
##[error]The repo on which this action is running is not opted-in to CodeQL code scanning.
```

I can't locate any documentation as to how to enable this or what else must be done, so effectively I get failure messages any time I push to my fork. 😢 

## Expected Behavior

Pushes to forks do not fail.

## Current Behavior

Build failure notifications on every push.

## Steps to Reproduce (for bugs)

1. Fork oauth2-proxy
2. Push a change to your fork.
3. Observe email.

**Comment by chkohner** [comment]
@greysteil Any thoughts here?

**Comment by greysteil** [comment]
Sorry about that. @jhutchings - can we disable that check for forks tomorrow?

**Comment by jhutchings1** [comment]
This will require a code change, but I'm supportive. I'll backlog it and see how quickly we can address. Thanks!

**Comment by chkohner** [comment]
Any sort of ETA on this, @jhutchings1?

**Comment by jhutchings1** [comment]
The team is working on it, but it's a little gnarly, so I'm not able to share a specific ETA. Thanks for your patience on this one @chkohner !

**Comment by jhutchings1** [comment]
Hey folks, I'm glad the stale bot reminded me here! I'm going to send you a patch which uses the latest guidance which works with pull requests.

**Comment by nolyoi** [comment]
> This issue has been inactive for 60 days. If the issue is still relevant please comment to re-activate the issue. If no action is taken within 7 days, the issue will be marked closed.

i just got it
![image](https://user-images.githubusercontent.com/59351042/110970130-0bcad880-831f-11eb-8353-9a5d1a6b8edf.png)


How can I fix or bypass this?

**Comment by jhutchings1** [comment]
@nolyoi The error you called out happens on private repositories if you don't have GitHub Advanced Security enabled for the repository. If you're seeing it on a public repository, suggest you contact support so we can have a look. https://github.blog/changelog/2021-01-07-github-advanced-security-can-now-be-enabled-disabled-at-the-repository-or-organization-level/
