### ISSUE TITLE
Clarification of Redirect URLs

### ISSUE THREAD

**Issue by JoelSpeed** [oauth2-proxy/oauth2-proxy#531]
## Expected Behavior

Options should be easy to understand and not confusing for users

## Current Behavior

The `--redirect-url` and `--whitelist-domain` options are completely separate yet are often confused. Similarly, within the codebase we have `GetRedirect` and `GetRedirectURI` which are used in completely separate parts of the flows.

## Possible Solution

I would propose that we rename these options and rename the code as well.

As far as I can tell there are two separate things. There are identity provider redirects (`--redirect-url`), as in, where should the identity provider be told to redirect to once auth has finished, and there are client-redirects (`--whitelist-domains`), as in, where are clients allowed to redirect to after OAuth2 Proxy has logged them in. The former is `GetRedirectURI` and the latter is `GetRedirect`.

I would suggest we rename the options to something like `--provider-redirect-url` and `--client-redirect-urls` and similarly replace the parts of the code that are affected.

Do we think those names would make it more obvious what the options do?

**Comment by ploxiln** [comment]
I think the word "client" may be a bit overloaded in the context of oauth2, would be nice to avoid. Maybe just renaming `--redirect-url` to `--provider-redirect-url` would help. Another idea is `--callback-url`. If it is still desired to rename `--whitelist-domain`, an idea is `--app-redirect-domain`.

**Comment by JoelSpeed** [comment]
Ack, you're right, client is very overly used so probably best to avoid. What do you think to `--provider-callback-url`? My thinking is that it's explicitly to do with the provider, and including callback URL I believe matches what the providers expect it to be called, they normally ask you to enter a list of callback URLs right?

I was thinking about this one earlier and wondered if we should keep some sort of whitelist/allow terminology for the user redirection post auth flow, was thinking `--allowed-redirect-domain` but it seems quite long, alternatively, `--allowed-redirect`? #NamingIsHard

**Comment by ploxiln** [comment]
`--provider-callback-url` and `--allowed-redirect` are good

**Comment by JoelSpeed** [comment]
This is still important and we should do it. Based on some conversation https://github.com/oauth2-proxy/oauth2-proxy/pull/552#issuecomment-656206123 in a recent PR, I think `--trusted-redirect` might be a better name, this would align with the trusted IP option that we are adding there

**Comment by drewwells** [comment]
whitelist has a negative association with it. `trusted-redirect` would be more clear and remove the inherent bias in the terminology.
