### ISSUE TITLE
"unknown shorthand flag: 'c' in -config" on latest docker build

### ISSUE THREAD

**Issue by CaptInsano** [oauth2-proxy/oauth2-proxy#541]
## Expected Behavior
oauth2-proxy should load

## Current Behavior
oauth2-proxy loads perfectly on version 5.1.1, 

I am using docker images from: https://quay.io/repository/pusher/oauth2_proxy

but the most recent update to :latest (current manifest number fb8603ab6234) causes the container to fail to load with the following error.

`"unknown shorthand flag: 'c' in -config=/etc/oauth2/oauth2_proxy.cfg"`

There has been no change in configuration files between these two versions and If I downgrade to build :v5.1.1-amd64 it again works perfectly.

My config file (personal info removed) which  I have been using for years

```
## OAuth2 Proxy Config File
## https://github.com/cheesemarathon/oAuth2-Proxy-Docker-Container

## <addr>:<port> to listen on for HTTP/HTTPS clients
http_address = "0.0.0.0:4180"

## the http url(s) of the upstream endpoint. If multiple, routing is based on path
upstreams = [
     "http://127.0.0.1:4180/oauth2/login"
]

## Log requests to stdout
request_logging = true

## The OAuth Client ID, Secret
client_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com"
client_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

## Authenticated Email Addresses File (one email per line)
authenticated_emails_file = "/etc/oauth2/emails.cfg"

## Templates
## optional directory with custom sign_in.html and error.html
## custom_templates_dir = "/etc/oauth2/templates/"

## Cookie Settings
## Name     - the cookie name
## Secret   - the seed string for secure cookies; should be 16, 24, or 32 bytes
##            for use with an AES cipher when cookie_refresh or pass_access_token
##            is set
## Domain   - (optional) cookie domain to force cookies to (ie: .yourcompany.com)
## Expire   - (duration) expire timeframe for cookie
## Refresh  - (duration) refresh the cookie when duration has elapsed after cookie was initially set.
##            Should be less than cookie_expire; set to 0 to disable.
##            On refresh, OAuth token is re-validated. 
##            (ie: 1h means tokens are refreshed on request 1hr+ after it was set)
## Secure   - secure cookies are only sent by the browser of a HTTPS connection (recommended)
## HttpOnly - httponly cookies are not readable by javascript (recommended)
cookie_name = "_oauth2_proxy"
cookie_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
cookie_domain = "xxxxxxxxxxxx.com"
cookie_expire = "168h"
cookie_refresh = "75h"
cookie_secure = true
cookie_httponly = true

```

Thanks for your work

**Comment by JoelSpeed** [comment]
Hey @CaptInsano, we do not support users running the latest master builds in production. These are for testing purposes only. If you are testing this, then you will need to check the changelog to see if any breaking changes have been introduced that may have caused this issue.

In this case, I know that we have introduced a change that requires all flags to use double dashes, so you will need to change `-config` to `--config` to restore functionality.

**Comment by CaptInsano** [comment]
Changing the docker repo from https://quay.io/repository/pusher/oauth2_proxy to https://quay.io/repository/oauth2-proxy/oauth2-proxy fixed the problem of master builds rather than release builds being pushed to my system.

Thanks for you help
