### ISSUE TITLE
Websocket HTTP Logs missing Authenticated User portion

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#544]
For the HTTP logging, some of my users are reporting websocket requests logs are missing the authenticated user (in cases where one is present and auth isn't skipped)

It also appears the upstream address usually passed via the `GAP-Upstream-Address` temp header also isn't logged.

## Expected Behavior

The username that is passed along via the GAPMetadata would be extracted and logged in `wsHandler http.Handler` just the same as it is for the standard `handler httpHandler`

## Current Behavior

Sample logs (with redactions) of a standard HTTP request followed by a websocket request:
```
127.0.0.1 - REDACTED_USER [2020/05/11 11:58:16] localhost:5000 POST localhost:1323 "/v1/start" HTTP/1.1 "REDACTED_USERAGENT" 202 242 0.034
127.0.0.1 - - [2020/05/11 11:58:24] localhost:5000 GET - "/v1/watch" HTTP/1.1 "REDACTED_USERAGENT" 0 0 4.622
```

The second websocket log is missing both the User & Upstream address usually passed in via GAP headers.

## Possible Solution

I tried to dig into the standard vs websocket handlers (and websocket's Hijack()) wrapped in the logging_handler -- but I'm afraid this code is beyond my understanding.  It appears somehow the `ExtractGAPMetadata` isn't happening (or is and the headers aren't present) for websocket requests.

## Steps to Reproduce (for bugs)

Send a websocket request to oauth2-proxy protected route.

## Context

Logs aren't providing authenticated user details that would be very nice for security auditing purposes.

## Your Environment

Locally & in K8s.  For the app attempting to use websockets: OIDC provider w/PKSE. Not using sessions or cookie-secret, passing Bearer tokens via header for auth using `--skip-jwt-bearer-tokens` and having that validate against the issuer url + client id.

- Version used:
v5.1.0 -- In K8s, binary is copied from `quay.io/pusher/oauth2_proxy:v5.1.0` to a `scratch` image.

**Comment by JoelSpeed** [comment]
This still needs addressing

**Comment by NickMeves** [comment]
Still needs addressing.

Thoughts: Are we able to store user details in the `context` to pass around rather than adding & deleting HTTP headers internally (`GAP-*` headers).  Will the data then get to websocket logs.

**Comment by JoelSpeed** [comment]
We should be putting this information into the request scope and reading it from there instead of using the headers IMO. Just need to make sure the request scope injector is passed through for every request (means moving it up the chain a bit from where it is now)

**Comment by NickMeves** [comment]
Someday...

**Comment by NickMeves** [comment]
I have a branch in progress on this that just needs tests. Once #964 merges (the fix has some middleware refactoring for logging) -- I'll get something up in draft form.
