### ISSUE TITLE
Migrate CI to GitHub actions

### ISSUE THREAD

**Issue by JoelSpeed** [oauth2-proxy/oauth2-proxy#546]
I would like to see code coverage, linting and testing status checks for all PRs to the project. Currently with Travis, we just get the one build check. Also, because we put the code coverage ID in a travis secret, this doesn't work on PRs from forks of the repos

I think if we move to GitHub actions, we get more information from the events that trigger builds that might allow us to create conditional statements that allow our actions to run and perform code coverage only when being PR'd to the OAuth2 Proxy. What we should avoid is getting code coverage reports whenever anything is pushed to any branch of any fork.

Likewise our CodeQL action is also broken and only works for pushes to this repository and not forks. It would be good to fix that too.

**Comment by shinebayar-g** [comment]
I can migrate your travis configuration to github actions if you want

**Comment by JoelSpeed** [comment]
If you have experience with actions, that would be appreciated

**Comment by JoelSpeed** [comment]
I would still like to see this done

**Comment by shinebayar-g** [comment]
Opened PR

**Comment by JoelSpeed** [comment]
Just had a look at the PR, looks like a great start, thanks!
