### ISSUE TITLE
If id_token lifespan is shorter than access_token, while using cookie-refresh set to the id_token lifespan, refresh fails because access_token and session are not expired.

### ISSUE THREAD

**Issue by jbreiding** [oauth2-proxy/oauth2-proxy#549]
Given Okta for IDP, the id_token lifespan is hard coded to 1 hour. Using acces_token lifespan of 6 hours and refresh_token lifespan of 7 days. Login sessions get an expiration window matching the access_token. Setting the cookie-refresh to the shortest lifespan here results in refresh failing validation.

Once the interval for cookie refresh has lapsed, the refresh flow starts. However because this condition occurs, 
https://github.com/oauth2-proxy/oauth2-proxy/blob/v5.1.1/providers/oidc.go#L72
The token is not refreshed, and fails in validation on,
https://github.com/oauth2-proxy/oauth2-proxy/blob/v5.1.1/oauthproxy.go#L899
because the id_token is expired and was not refreshed. It looks like a failure refreshing, however the refreshing was skipped.

## Expected Behavior

Refresh to inspect both tokens for expiration before skipping redeeming the refresh token for another set of tokens.

## Current Behavior

sad trombone.
Refresh skips redeeming the refresh token and fails validation before saving the new session, but there isn't a new one. 

## Possible Solution

vetted by adjusting the access_token policy in Okta to be 1 hour to match the id_token and the cookie-refresh to be 1 hour.

Also adjusted the cookie-refresh to be match with the access_token lifespan to ensure the session is expired when refresh interval comes due.

Deeper inspection of the session, or better guidance for IDP configuration to ensure that the access_token lifespan, where the session expiration is derived from, is the equal to or the shortest lifespan of all the tokens.

## Steps to Reproduce (for bugs)

set cookie-refresh to 1 hr, set id_token lifespan to 1 hr, set access_token and refresh_token to be much longer.

Let the cookie-refresh lapse.

## Context

This has caused us to have at most a 1 hour valid session before having to refresh through the full auth flow and not being able to take advantage of refresh tokens.

## Your Environment

oauth2-proxy v5.1.1, Okta IDP, configured behind k8s-ingress, running on aws ec2.

- Version used:
v5.1.1

**Comment by JoelSpeed** [comment]
This behaviour was changed in #335 by @howzat so I'd appreciate his input on this please

To me it looks as though Okta is a bit of a special case. Their Access Tokens look like ID Tokens which I don't think is the norm for OIDC. I normally would have expected the access token to expire before the ID Token as well. Additionally, the field we are taking the expiry from, I would have expected to match the ID Token expiry in most cases. Perhaps we should be looking up the earliest expiry, either from the original redemption response or from the ID Token and setting that as the expiry? 

I also note, we leave the old ID Token around if the refresh did not contain one, this will then fail validation on the next call. So we need to make a decision as to whether we require ID Tokens on refresh, and if we decide we don't, then we need to ensure the ID Token is removed from the session.

Are there any specific reasons why Okta isn't returning the ID Token on refresh @howzat, is that a config issue?

**Comment by jbreiding** [comment]
> Are there any specific reasons why Okta isn't returning the ID Token on refresh @howzat, is that a config issue?

If I'm misunderstanding the question, I apologize, but this seems to me like it misses the point of the bug. The refresh isn't happening or being attempted because the sessions isn't expired and instead validation is happening on the set of tokens in the previous session. Which fails because the id_token is in fact expired.

The validation step is called explicitly on the id_token and sessions expiration is based on the access token. The tokens from okta are identified as distinct types, the comment about access tokens looking like id tokens seems strange.

**Comment by jbreiding** [comment]
@JoelSpeed you asked me to try this in v5.0.0, sorry for not addressing that. This issue started for us with that version. But it's also the first time we started using cookie refresh, we undertook the task of solving this and upgrading to the latest version at the same time.

**Comment by howzat** [comment]
Hi @JoelSpeed and @jbreiding 

I encountered a bug in the previous implementation where the refresh token exchange failed when an id_token was not present in the response. I learned a lot in that exercise, but I'm certainly no expert. However...

According to the spec, ID Tokens are _optional_ in the refresh response (i.e. you have to read your OIDC providers docs to know if you are going to get one), see here: https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokens. The conclusion I drew is that there is no specified way to refresh an ID token. The only specified behaviour of the refresh  relates to the status of the access token and therefore the timing of the refresh should be primarily driven by the access token expiry.

I found this thread to be very informative: https://stackoverflow.com/questions/25686484/what-is-intent-of-id-token-expiry-time-in-openid-connect

Which is why is does seem a little odd that Okta make the id_token timeout so short. Since different providers have different expectations about how ID tokens should be handled, my 2 pence would be to do as @jbreiding suggests. Check both expiry times as the trigger for the refresh in an attempt to keep both tokens up to date.

Hope that helps.

**Comment by JoelSpeed** [comment]
I think the solution will be as you've said, to check both expirations and refresh when either of them is expiring.

I think we should also remove the old ID Token if the refresh does not include one, do you agree?

**Comment by Jc2k** [comment]
Any chance that this can be re-opened? It's still an issue, and i'm aware of other idp's that have short lifetimes for their id tokens.

**Comment by JoelSpeed** [comment]
There is some work going on to change the behaviour of token refreshing presently. This issue may be solved in the not too distant future

**Comment by Jc2k** [comment]
Is there an update on this? There have been 3 attempts at a PR that would have fixed it [here](https://github.com/oauth2-proxy/oauth2-proxy/pull/886), [here](https://github.com/oauth2-proxy/oauth2-proxy/pull/915) and [here](https://github.com/oauth2-proxy/oauth2-proxy/pull/946). I am actually using v2 successfully but don't want to get stuck on an old patched version.

**Comment by Jc2k** [comment]
Will https://github.com/oauth2-proxy/oauth2-proxy/pull/1086 help with this?

**Comment by JoelSpeed** [comment]
Yeah I think it should resolve this, @NickMeves can confirm

**Comment by Jc2k** [comment]
I believe this is still a problem.

**Comment by Jc2k** [comment]
I think this is still a problem..

**Comment by eamelink** [comment]
This also affects Azure, which has Id tokens with a default lifetime of one hour, and access tokens that may live much longer: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes

**Comment by Jc2k** [comment]
As above https://github.com/oauth2-proxy/oauth2-proxy/pull/1086 should help with this, this isn't released yet though so right now I believe this is still an issue.
