### ISSUE TITLE
Hosted Docs should reflect the current release

### ISSUE THREAD

**Issue by JoelSpeed** [oauth2-proxy/oauth2-proxy#550]
## Expected Behavior

Docs (https://oauth2-proxy.github.io/oauth2-proxy) should be up to date with the current latest release.

## Current Behavior

The docs reflect the state of the master branch and as such, when new features are added, these are documented, but not available

## Possible Solution

- Create a separate docs branch to pin the docs to the latest release and make part of the release process to update those docs
- Create a separate docs repo (org level GitHub pages?) and copy docs over on every release?

**Comment by shinebayar-g** [comment]
I guess Github pages doesn't support multiple versions/deployments. Does https://github.com/pmarsceill/just-the-docs support versioned deployments?

**Comment by JoelSpeed** [comment]
I don't believe either support versioned deployments at the moment.

I'm leaning towards having a separate repository that would be hosted at `oauth2-proxy.github.io` that contains the latest release docs, and keeping the existing docs hosted for master branch but adding some sort of warning to it that these are release docs

Would only be able to do this if we somehow created some release automation that updated the published docs whenever a release tag was pushed 🤔

**Comment by shinebayar-g** [comment]
Well that sounds kinda .. lame. For now docs could simply mention that when / which release this feature was introduced. Ideally one could setup documentation builder such as [docusaurus](https://v2.docusaurus.io/docs/versioning/) which supports versioning. But they suggest that versioning isn't great idea.

**Comment by JoelSpeed** [comment]
> Well that sounds kinda .. lame. 

Brutal honesty! Totally fair 😅 

> For now docs could simply mention that when / which release this feature was introduced.

That sounds reasonable, we should probably do that going forward

> Ideally one could setup documentation builder such as docusaurus which supports versioning.

I'm totally open to switching how we host the docs if there's a feature we want, I'd like to keep it on github pages though (I would like to move to the root of our github pages) so it needs to be jekyll or able to generate the static site files

> But they suggest that versioning isn't great idea.

Yes I can see that versioning may have issues with updating older docs, I guess we get around that by just not updating the old docs once they're published.

Would you expect the latest release to be the default docs you see, or would you expect the current master branch to be the latest docs?

**Comment by shinebayar-g** [comment]
I guess I'd expect latest release version docs..

**Comment by JoelSpeed** [comment]
Still want to do this, not worked out how to make it work yet though

**Comment by gysel** [comment]
It is an option to create a `release/latest` branch and publish the docs based on this branch?

(I too lost quite some time figuring out why a configuration option did not work.)

**Comment by JoelSpeed** [comment]
GitHub pages allows us to publish the docs to a `gh-pages` branch, we could potentially go via that route as an intermediate step. Ultimately I'd prefer to go with something that gives versioned docs though.

**Comment by shinebayar-g** [comment]
https://docusaurus.io gives versioned docs.

**Comment by JoelSpeed** [comment]
I had a look at docusaurus, looks great! Looks like it might take a little work to set up, have to configure some automation to build and publish the pages but they have that so it's more a copy paste effort than anything else. Supports all the things I think we need and the versioning would be very useful.

@NickMeves Have you seen https://docusaurus.io/, any thoughts?

**Comment by shinebayar-g** [comment]
We at erxes.org use it heavily. I think I can help with initial setup. It can run github pages.

**Comment by JoelSpeed** [comment]
If you have the time to set that up or even could link to examples then that would help. I would imagine we can publish the source from the master branch to a gh-pages branch and then set up pages to host from that branch, does that seem like a reasonable approach based on what you've seen in the past?

**Comment by shinebayar-g** [comment]
docs live inside docs folder of master (or any) branch. And rest is automated.

**Comment by JoelSpeed** [comment]
Ok, well I'd suggest for us we use a gh-pages branch for now and then we can keep the automated commits out of the main code base, but we can keep the source for the build in docs on master as it is currently if I've understood right?

**Comment by shinebayar-g** [comment]
https://github.com/erxes/erxes/tree/master/docs take a look at the example here. automated commits are made to gh-pages branch not main.

**Comment by JoelSpeed** [comment]
Had a look through the erxes setup, looks pretty slick to me, let's try to reproduce that! Only thing they don't seem to be doing is versioned docs, so not sure how we would set that up, I'm sure a little time in the Docusaurus docs should tell us though

**Comment by JoelSpeed** [comment]
I've created a PR to migrate to Docusaurus. Once that is merged, I will create a PR that sets up docs for the 6.1 release so that these are the default (until v7.0 is released)

**Comment by shinebayar-g** [comment]
New docs looks great! Great job @JoelSpeed 🚀
