### ISSUE TITLE
Can we use our own auth provider?

### ISSUE THREAD

**Issue by mallow111** [oauth2-proxy/oauth2-proxy#553]
## Expected Behavior

I expect that we can use oath2_proxy with our own auth provider rather than the default ones(google,facbook,azure, linkedin, github and etc)
## Current Behavior

Maybe I did not understand the product well enough, it look like that users who need to use oath2-proxy can only use the default auth provider. I am thinking of using oath2_proxy for our team's authN, but we have our only authN provider, which is something unique for our team, is that configurable to use differnt authN provider?
## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Context
we need to add authN for our web service.

## Your Environment
salesforce internal development.

- Version used:
We did not use yet, still in research phase.

**Comment by JoelSpeed** [comment]
We have a generic OIDC provider that can be used with any OIDC compatible authentication provider. This depends on the authentication protocol of your own authN server

**Comment by mallow111** [comment]
Great, our underlying architecture use keycloak, it should work, right?

**Comment by JoelSpeed** [comment]
We have a dedicated Keycloak provider, but you can also use the OIDC provider with Keycloak, they have different features available unfortunately, they need aligning
