### ISSUE TITLE
Too Many Colons error when using Redis session store 

### ISSUE THREAD

**Issue by blt** [oauth2-proxy/oauth2-proxy#554]
## Expected Behavior

I am trying to enable redis session storage when using oauth2-proxy v5.1.1. I have the following flags in place:

```
--redis-use-cluster=true \
--redis-cluster-connection-urls=redis://redis-0:6379 \
--session-store-type=redis
```

I'm running kubernetes and the `redis-0` resolves properly. I expect to be able to go through the normal auth flow with these flags set. 

This 

## Current Behavior

When I auth against oauth2-proxy with these flags in place I see the following in the logs:

```
oauth2-proxy 127.0.0.1 - btroutwine@goodwatercap.com [2020/05/14 00:25:49] [AuthSuccess] Authenticated via OAuth2: Session{email:btroutwine@goodwatercap.com user:106428469046097333554 PreferredUsername: token:true id_token:true created:2020-05-14 00:25:49.180657438 +0000 UTC m=+39.577027380 expires:2020-05-14 01:25:48 +0000 UTC refresh_token:true}                                                                                                              
oauth2-proxy [2020/05/14 00:25:49] [oauthproxy.go:792] 127.0.0.1:49444 ("127.0.0.1") dial tcp: address redis://redis-0:6379: too many colons in address
```

This results in an HTTP 500 from oauth2-proxy. 

## Possible Solution

Unsure. The error message "too many colons in address" comes up often after a quick search, such as https://github.com/go-redis/redis/issues/864. 

## Steps to Reproduce (for bugs)

1. Posses a functional oauth2-proxy setup using cookie session store.
2. Configure this oauth2-proxy to use redis session store. 
3. Re-authenticate and observe the logs. 

I have confirmed this is reproducible with an IP address, without the `redis://` and I tried without an explicit port but this appears to be obligatory despite the documented optionality. 

## Context

I am unable to use redis for session storage. 

## Your Environment

I am running in GKE with oauth2-proxy behind an nginx-ingress. We have found that refresh cookies are too large for our current nginx-ingress header max sizes and wanted to avoid increasing this maximum by pushing session storage to redis and away from cookies. 

- Version used: v5.1.1

**Comment by JoelSpeed** [comment]
Could you just confirm for me which of these you've tried/could you try ones you haven't?
```
redis://redis-0:6379
redis://redis-0:6379/
http://redis-0:6379
http://redis-0:6379/
redis-0:6379
redis-0:6379/
```
Do they all result in this same issue? I know this has been working in the past and I don't think anything has changed so it may just be there are only certain formats working at the moment (though we should fix it if this is the case)

**Comment by blt** [comment]
@JoelSpeed good question. Some of these variants I have not tried and I'll work through the lot of them and report back.

**Comment by blt** [comment]
| variant | result |
|--------|-------|
| `redis://redis-0:6379` | too many colons | 
| `redis://redis-0:6379/` | too many colons | 
| `http://redis-0:6379` | too many colons | 
| `http://redis-0:6379/` | too many colons | 
| `redis-0:6379` | functional | 
| `redis-0:6379/` | functional | 

The functional result only kind of works. I do get an error message stating "This instance has cluster support disabled" but that's a separate issue and surely a result of my redis configuration.

**Comment by JoelSpeed** [comment]
I did not notice you were using cluster originally, this may have something to do with it. Are you intending to use redis cluster?

**Comment by blt** [comment]
We are and using the `redis-0:6379` form we're in good shape now. I didn't confirm if the use redis, use sentinel flags had the same issue.

**Comment by JoelSpeed** [comment]
Ok, I've not tested with redis cluster but perhaps this is a bug specific to that implementation. It will need some further investigation

**Comment by amnay-mo** [comment]
Hi,
I have submitted a PR to fix this bug: https://github.com/oauth2-proxy/oauth2-proxy/pull/573
Cheers!
