### ISSUE TITLE
Issues with authentication when the ELB is behind a firewall

### ISSUE THREAD

**Issue by DimitrijeManic** [oauth2-proxy/oauth2-proxy#557]
Hi there, we have an internal ingress controller which is simply a classic AWS ELB with a security group that restricts all traffic unless it's coming from a specific IP.

With this setup the OAuth2 proxy times out and fails to authenticate.

Changing the security group on the ELB to allow traffic from ALL IPs resolves the issue and the OAuth2 proxy functions as normal. 

It seems the issue comes from something attempting to talk to the OAuth2 proxy pod but can't as it is hidden behind a firewall.

Are there specific configs that need to be set or IP ranges that need to be white listed? I am using Googles OAuth API. 

Thanks!

## Expected Behavior

Authentication should work behind a firewall.

## Current Behavior

OAuth proxy fails to authenticate and hangs until timeout.

## Steps to Reproduce (for bugs)
1. Place the OAuth proxy behind a firewall which allows connections only from a specific IP.
2. Attempt to authenticate

## Your Environment
Kubernetes v1.14
Nginx-ingress controller
AWS classic ELB
Google OAuth2

- Version used:

**Comment by JoelSpeed** [comment]
Hi @DimitrijeManic, can you provide any logs from the OAuth2 Proxy, is it even receiving the requests that you are attempting to make to it? Do you allow outbound egress from the OAuth2 Proxy pod, as it will need to communicate with Googles API directly, but otherwise, shouldn't be communicating with anything other than your upstreams if you have those set

**Comment by DimitrijeManic** [comment]
@JoelSpeed Thanks for helping out, Adding an additional inbound rule to allow the clusters network interface IP resolved my issue. 

I believe the I ran into this issue due to the K8s pattern with the following annotations. 
```
'nginx.ingress.kubernetes.io/auth-url': 'https://$host/oauth2/auth',
'nginx.ingress.kubernetes.io/auth-signin': 'https://$host/oauth2/start?rd=$escaped_request_uri'
```

My assumption is that it is the ingress controller that makes a request to the OAuth2 pod and this request came from the clusters network interface IP which was not white listed.

Having the ingress controller attempt to talk to the Oauth2 pod through the local address instead of the public address should also fix this issue.
