### ISSUE TITLE
Fetching User ID claim fails if claim not present in ID Token

### ISSUE THREAD

**Issue by rveve** [oauth2-proxy/oauth2-proxy#558]
I have built the latest master branch, a configuration that used to work perfectly with the stable version v5.1.1.

is not working anymore with the current master branch code, now it is checking for email field, and failing my previous working configuration, any idea on how to workaround this ?.

[2020/05/15 20:02:10] [oauthproxy.go:890] Error retrieving session from token in Authorization header: couldn't extract claims from id_token (&{%!e(string=claims did not contains the required user-id-claim 'email')})
[2020/05/15 20:02:10] [oauthproxy.go:901] Error loading cookied session: cookie "_oauth2_proxy" not present

Thank you.

**Comment by JoelSpeed** [comment]
@rveve we do not normally support users that are running master. We are making breaking changes on master and so it is expected that you may encounter problems when running this branch.

If you could share with us your configuration then we may be able to help identify what is wrong. It looks like #499 has broken your config so might be worth looking through this to try and identify what has changed there

**Comment by JoelSpeed** [comment]
I've just had a look and I believe there may have been a breaking change introduced in #499 that we might have missed. 

https://github.com/oauth2-proxy/oauth2-proxy/blob/d228d5a928176575364e9e1fb4bb4e417c91de3f/providers/oidc.go#L244-L276

Before, if the claim didn't exist, it would have been empty and we would have fallen back to checking the ProfileURL. Now if it doesn't exist, we return an error.

I think what should happen is we check the rawclaims, then check the profile URL for the UserID claim, and then return an error if that fails. This would restore the old behaviour. CC @holyjak WDYT?

**Comment by holyjak** [comment]
Yes! My bad, sorry!
