### ISSUE TITLE
Filter logs based on UserAgent

### ISSUE THREAD

**Issue by strboul** [oauth2-proxy/oauth2-proxy#564]
I have my application deployed at AWS ElasticBeanstalk and I'm getting such logs from EB health checker like every 5 seconds:
```
172.18.0.5 - - [2020/05/19 14:23:02] 173.31.50.29 GET - "/oauth2/auth" HTTP/1.0 "ELB-HealthChecker/2.0" 401 21 0.000
172.18.0.5 - - [2020/05/19 14:23:02] 173.31.50.29 GET - "/oauth2/sign_in" HTTP/1.0 "ELB-HealthChecker/2.0" 200 2858 0.000
[2020/05/19 14:23:05] [oauthproxy.go:895] Error loading cookied session: cookie "_oauth2_proxy" not present
```

I've read the documentation but couldn't find a flag/option for the `oauth2_proxy.cfg` file that can allow filtering some certain requests based on a auth logging variable e.g. UserAgent. It'd be great if there's a way to have oauth2_proxy ignore these rather than filtering them on my own.

Using oauth2_proxy version, from the Docker image: [quay.io/pusher/oauth2_proxy:v5.1.1](https://quay.io/repository/pusher/oauth2_proxy/)

Thanks a ton!

**Comment by ploxiln** [comment]
You can have the health check request hit the "ping path" (by default `/ping`, configurable with the `--ping-path` option) and then use `--exclude-logging-paths` option to avoid logging those requests.

**Comment by ploxiln** [comment]
(equivalent and maybe easier, there's also a `--silence-ping-logging` option)

**Comment by chkohner** [comment]
I had a similar issue that was not solvable by `--exclude-logging-paths`, so I wrote https://github.com/oauth2-proxy/oauth2-proxy/pull/567 just recently.

**Comment by JoelSpeed** [comment]
I'd like to know why @ploxiln's suggestions don't work and what other cases we need to consider before making any code changes

**Comment by strboul** [comment]
Thanks @ploxiln for the responses. But I can't understand how those flags can help filter the requests by User Agent. For testing, I am able to create a fake healthcheck request in local, which is by `curl -I -H "User-Agent: ELB-HealthChecker/2.0" http://localhost`, but I don't know how to have it as a "path". Would you post an example for this case? Besides, the PR from @chkohner seems interesting.

**Comment by ploxiln** [comment]
Those flags help you filter health-check requests by path, instead of by User-Agent. I expected that any load-balancer would allow you to configure the health check path, or would use some reasonable health check path. It seems this may not be true for all load-balancers, but it appears  to be true for ElasticBeanstalk: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.healthstatus.html#using-features.healthstatus.understanding

**Comment by JoelSpeed** [comment]
This issue was solved, we now have a `--ping-user-agent` option
