### ISSUE TITLE
How are domains to be delimited? 

### ISSUE THREAD

**Issue by blt** [oauth2-proxy/oauth2-proxy#571]
I'm trying to set multiple cookie domains, ultimately with an eye toward serving different domains from the same oauth2-proxy install, not unlike in #216. The [documentation](https://oauth2-proxy.github.io/oauth2-proxy/configuration) for `--cookie-domain` notes the type is `string | list` and I'm setting the domain like so:

```
--cookie-domain=.labs.example.com,.prod.example.com
```

The documentation is silent on how delimiting works here so I'm sort of guessing that the comma is the right delimiter. 

## Expected Behavior

My expectation is that oauth2-proxy will now accept cookies from anything sub labs.example.com or prod.example.com.

## Current Behavior

What I find is that oauth2-proxy believes the domain to use for cookie matching is `.labs.example.com,.prod.example.com`. From my logs:

```
2020/05/21 21:23:29 net/http: invalid Cookie.Domain ".labs.example.com,.prod.example.com"; dropping domain attribute
```

## Your Environment

- Version used: v5.1.1

**Comment by ploxiln** [comment]
Version 5.1.1 does not support multiple possible cookie domains, that feature was added after the 5.1 release branch, and is only available in master currently.

**Comment by blt** [comment]
That explains it. Thank you. 

I’m correct in my understanding that more recent releases use commas as delimiters? The documentation doesn’t say.

**Comment by ploxiln** [comment]
The flag parsing library is also changed in master, and it does separate multi-value options on commas, whereas previously oauth2-proxy would only work with multi-value options by specifying them multiple times, like `--whitelist-domain=.labs.example.com --whitelist-domain=.prod.example.com`

**Comment by blt** [comment]
Perfect. This is exactly what I needed.
