### ISSUE TITLE
SPA Hashrouter not working

### ISSUE THREAD

**Issue by nicoschuck** [oauth2-proxy/oauth2-proxy#578]
I have running an Angular Application in my Kubernetes Cluster which use Hash Router.
When my IP redirects me back after succesfully authentification, the whole Hash Path ist lost.

## Current Behavior

For example I try to enter the following page:
https://example.com/home/#/subrouter1/subroute2
after login on IP I get redirected to:
https://example.com/home/

## Expected Behavior

It should me redirect to the same origin page:

https://example.com/home/#/subrouter1/subroute2 -> https://example.com/home/#/subrouter1/subroute2

## Possible Solution

The callback route of the oauth2-proxy has following parameter:

_...&state=fa82dc6f1018ffa9c2861eeef6f71aff%3a%2fhome%2f&session_state=..._
Maybe there is a config setting for the state parameter?

Or is there any other nginx variable which I should use? Currently I use the same like in the documentation:

```
nginx.ingress.kubernetes.io/auth-url: "https://example.com/oauth2/auth"
nginx.ingress.kubernetes.io/auth-signin: "https://example.com/oauth2/start?rd=$escaped_request_uri"
```

**Comment by ploxiln** [comment]
see #473

**Comment by nicoschuck** [comment]
Thank you!
