### ISSUE TITLE
Cookie secret must be 16, 24, or 32 bytes to create an AES cipher. Got 30 bytes.

### ISSUE THREAD

**Issue by DimitrijeManic** [oauth2-proxy/oauth2-proxy#579]
Latest release of the image `quay.io/pusher/oauth2_proxy:latest` is returning the error 
```SHELL
Cookie secret must be 16, 24, or 32 bytes to create an AES cipher. Got 30 bytes.
```

Despite the `OAUTH2_PROXY_COOKIE_SECRET` being set correctly. 
reverting back to image v5.1.1 works as expected

## Expected Behavior
OAUTH2_PROXY_COOKIE_SECRET should work as before

## Current Behavior
Fails to start with the error posted above

## Steps to Reproduce (for bugs)

1.  Deploy with the latest image

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
We are in the process of preparing a large major release which has a number of breaking changes.

We fixed a bug in the proxy that would allow incorrect lengthed ciphers to be created.
We now also encrypt all sessions now.

Please review the changelog for further details.

Please check your cookie secret length and make sure it is either 16, 24 or 32 bytes.

Please do not use the latest tag. We do not provide support for users using the latest tag.

**Comment by usamaB** [comment]
any update on this? v5.1.1 works but going to v6+ gives error 44 bytes in my case

**Comment by JoelSpeed** [comment]
Your cookie secret must have somehow been invalid before the upgrade, I suggest creating a new secret and trying `cookie-session-minimal` unless you are relying on any token headers being produced by the proxy
