### ISSUE TITLE
Can you guys add liveness probe check for all providers

### ISSUE THREAD

**Issue by mallow111** [oauth2-proxy/oauth2-proxy#581]
## Expected Behavior

Expected to have liveness probe check for all provider, similar as gcpHealthcheck(https://github.com/oauth2-proxy/oauth2-proxy/blob/236c7fa60ef6c1adaf74e163f129eb337c369bc1/http.go), in this case, user can check if the oauth2 proxy container is healthy or not.
## Current Behavior
only gcpHealthcheck has liveness probe check

## Possible Solution
Add liveness probe code for generic use, it can be simple but at least user can know if the container is up.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Context

test in local with simple hello world as upstream, and use oidc as provider
## Your Environment
mac os

- Version used:
v5.1.1

**Comment by JoelSpeed** [comment]
We already support a health check endpoint via the ping path option, have you tried this to solve your issue?

The gcp healthcheck you found is for GCP load balancers which have special requirements for health checking the proxy itself, this shouldn't be necessary for most health checks

**Comment by mallow111** [comment]
just found it here https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/5_endpoints.md,
and tested it out, works great, thanks!

```    
    livenessProbe:
          httpGet:
            path: /ping
            port: 5678
```
