### ISSUE TITLE
Question: Do you have a plan for support Slack oAuth

### ISSUE THREAD

**Issue by pyama86** [oauth2-proxy/oauth2-proxy#584]
Hi there!
oauth2-proxy is very useful and I use it heavily!

I have a question.
Do you have a plan for support Slack oAuth?
can I create PR if don't you have a plan?

I want to hear your opinion.
Because maintenance cost is increased if I add it.

thanks.

**Comment by JoelSpeed** [comment]
We don't currently plan to include support for Slack. I have reservations over adding support for it. 

Perhaps you can explain a little more about why you'd prefer to use Slack as your identity provider over any other

**Comment by pyama86** [comment]
I think that github.com(or Enterprise) and Google oAuth Provider are often used in companies.

However, if there is a business-to-business transaction, there may be cases where the other company employee wants to access our company server(for example outsourcing)
In that case, github.com and G Suite must add accounts for a fee, but Slack can add up to 5 external users for free.
https://slack.com/intl/en-in/resources/slack-for-admins/external-collaboration-in-slack

I think that Free is better and Slack is used a lot for global.

**Comment by JoelSpeed** [comment]
If your use case is that you want to provide login for your own employees and some external customers, we have authorization controls in place for this kind of thing already. 

Eg, you could add a GitHub user as a collaborator to a particular repository, or if logging in via google, you could add their email to the authorized emails file I believe.

Personally, if it were me doing this, I wouldn't be using slack as my authentication, primarily because they are effectively a proxy, I as a user of slack require other credentials to log in (ie slack login is normally via some SSO already)

**Comment by pyama86** [comment]
This is true for use in open source projects, but I think that Github Enterprise and G Suite used by companies can't handle this kind of thing.
For example, You have to share Github Enterprise with github.com and you should publish G Suite apps from the internal limitation to the outside.

**Comment by JoelSpeed** [comment]
From the next release, we have a GitHub user option, all this does is check that the authenticated user has the right GitHub username, this would get around letting having to add them as a collaborator.

> should publish G Suite apps from the internal limitation to the outside

I'm not following this bit sorry

I know users have definitely gotten around these limitations in the past, by allowing users outside of G Suite organisations to log in, I will try to find the relevant issues

**Comment by pyama86** [comment]
> From the next release, we have a GitHub user option, all this does is check that the authenticated user has the right GitHub username, this would get around letting having to add them as a collaborator.

That's amazing! But I think Github Enterprise needs another approach, Because Github Enterprise charges per user.

> I know users have definitely gotten around these limitations in the past, by allowing users outside of G Suite organisations to log in, I will try to find the relevant issues

As you said, you don't necessarily have to add an account to G Suite if you publish your application externally, but that is a trade-off with the complexity of managing an account at your company.

**Comment by JoelSpeed** [comment]
> That's amazing! But I think Github Enterprise needs another approach, Because Github Enterprise charges per user.

Based on your examples above, which are business to business transactions, I'm not convinced the extra costs of a user per month or so would be that prohibitive, in the grand scheme of things, the amount of money a company would spend on this kind of outsourcing would dwarf the costs of an extra few GitHub users or temporary GSuite accounts

But I can see now that my other suggestions won't work.

> As you said, you don't necessarily have to add an account to G Suite if you publish your application externally, but that is a trade-off with the complexity of managing an account at your company.

I'm afraid I'm still not understanding your point here

**Comment by pyama86** [comment]
When performing authentication using google's G Suite, there is a setting whether to make the oAuth application closed to our company G Suite's user or to make it externally disclosed.
Do you know this?

**Comment by JoelSpeed** [comment]
> When performing authentication using google's G Suite, there is a setting whether to make the oAuth application closed to our company G Suite's user or to make it externally disclosed.
> Do you know this?

I haven't set up a Google project in a while, previously you would just send a hosted domain parameter. Is this what you're referring too?

**Comment by pyama86** [comment]
Would you check below.
https://support.google.com/cloud/answer/6158849?hl=en

> Public and internal applications

I think that G Suite user will use it in most cases.

**Comment by JoelSpeed** [comment]
This seems to be a new feature since I last configured Google OIDC, seems to have the same effect as the hosted domain parameter, except it is enforced Google side, rather than by the OAuth2 Proxy

**Comment by pyama86** [comment]
I understand.
If you're a G Suite administrator for a company, don't you want to avoid registering external users individually when possible?

**Comment by pyama86** [comment]
I understood the development policy. Thank you very much.
