### ISSUE TITLE
when provider is oidc, is that possible to use a config a file rather than provide oidc-issuer-url

### ISSUE THREAD

**Issue by mallow111** [oauth2-proxy/oauth2-proxy#586]
## Expected Behavior
currently when use oidc provider, it seems that we need to provide oidc-issuer-url flag, is that possible to provide a config that contains the content of this url. The reason is that when we use in our production environment, we got some acl issue.

## Current Behavior
when provider is oidc, the only option is to use flag oidc-issuer-url, seems cannot use config file to provide the content.

## Possible Solution
add a config support so that when users app is not  able to talk to the url directly, they can talk to the config file.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Context
try to avoid acl issue when oidc-issuer-url is not reachable in certain cluster.

## Your Environment

- Version used:
the latest version

**Comment by mallow111** [comment]
Or should I just use insecure-oidc-skip-issuer-verification=true flag in my deployment.

**Comment by JoelSpeed** [comment]
You can provide a config file with the `--config` flag. Any flag that can be set via the command line can also be set in the config file. Please read through the configuration docs for details as the names are changed slightly depending on the flag.

Eg `--oidc-issuer-url` would become `oidc_issuer_url` in the config file

**Comment by JoelSpeed** [comment]
It seems I misunderstood the question slightly, you can try the `--skip-oidc-discovery` flag, but in that case you need to provide `--login-url`, `--redeem-url` and `--oidc-jwks-url` which will allow the proxy to run without using the discovery

**Comment by mallow111** [comment]
@JoelSpeed thanks for the explaination, how to turn on the implicit flow for oidc provider, since I need the authorization server return an access  token directly back to the client.

**Comment by JoelSpeed** [comment]
If you want the OIDC ID Token, you can use `set-authorization-header` or `pass-authorization-header` to get the ID Token in a header in responses/proxied requests

**Comment by mallow111** [comment]
@JoelSpeed  let me give a try, thanks!

**Comment by mallow111** [comment]
@JoelSpeed, in our production enviroment, we somehow got a oidc-issue-url that cannot be reached directly, we need a http proxy before it, for instance, ideally, in our production host, we are supposed to do curl  -v https://our-oidc-issue-url, but in reality, we need to do curl -I -k -x http://public0-proxy1-0-avc:1234 -L https://our-oidc-issue-url in the host, is there any flag in oauth2-proxy that can pass in this http://public0-proxy1-0-avc:1234? Thanks!

**Comment by mallow111** [comment]
@JoelSpeed  never mind, I figured out how to add http proxy, we can add env in deployment file with http proxy url, I will close this. Also I submitted a PR to implement oidc implicit work flow.
