### ISSUE TITLE
Redirect URI getting trimmed or not accepted at all

### ISSUE THREAD

**Issue by ayushmpb95** [oauth2-proxy/oauth2-proxy#587]
The `redirect_uri` passed from nginx to `oauth2-proxy` server gets washed away even though it is passed via `proxy_set_header X-Auth-Request-Redirect $request_uri;`

## Expected Behavior
It shouldn't care about the request_uri and return it back as it is.
## Current Behavior
Right now oauth2-proxy server redirects back to `/`.
## Possible Solution
Not sure
## Steps to Reproduce (for bugs)
I have a nginx server running on domain `http://abc.com` which authenticates via `oauth2-server`. The configurations are as follow:
```
        location /oauth2/ {
          proxy_pass http://127.0.0.1:4180;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
          proxy_set_header X-Auth-Request-Redirect $request_uri;
          proxy_connect_timeout 5s;
          proxy_read_timeout 5s;
        }

        location / {
          auth_request /oauth2/auth;
          auth_request_set $user   $upstream_http_x_auth_request_user;
          auth_request_set $email  $upstream_http_x_auth_request_email;
          error_page 401 = /oauth2/sign_in;
          proxy_set_header    X-User $user;
          proxy_set_header    X-Email $email;

          proxy_pass          $proxy_pass_url;
          proxy_set_header    Host $http_host;
          proxy_set_header    X-Real-IP $remote_addr;
          proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header    X-Forwarded-Proto $scheme;
          proxy_set_header    X-Forwarded-Host $http_host;
        }
```
The URL I'm passing: `http://abc.com/app/xyz#/tool/efg?_g=()` and gets redirected to `http://abc.com` instead of `http://abc.com/app/xyz#/tool/efg?_g=()`

## Context

Setting up OIDC on nginx.
## Your Environment
Staging 

- Version used:
Latest

**Comment by ayushmpb95** [comment]
@JoelSpeed Any you help here please?

**Comment by JoelSpeed** [comment]
@ayushmpb95 Have you configured whitelist domains at all? Are all requests being sent to the same domain? 

In the latest version, if there's a problem with the redirect, it should be logging what that issue is, have you noticed any logs that suggest why the redirect isn't being accepted?

> The URL I'm passing: http://abc.com/app/xyz#/tool/efg?_g=() and gets redirected to http://abc.com instead of http://abc.com/app/xyz#/tool/efg?_g=()

FYI, `#` in a URL starts the fragment, this is not sent as part of the request by a browser, so if you go to a browser and go to `http://abc.com/app/xyz#/tool/efg?_g=()`, Nginx will recieve the request as `http://abc.com/app/xyz` and the fragment will be lost, this is a limitation of the HTTP protocol

**Comment by ayushmpb95** [comment]
> FYI, # in a URL starts the fragment, this is not sent as part of the request by a browser, so if you go to a browser and go to http://abc.com/app/xyz#/tool/efg?_g=(), Nginx will recieve the request as http://abc.com/app/xyz and the fragment will be lost, this is a limitation of the HTTP protocol

Exactly this is what is happening. Can't do much here as it is not even passed to the request.
Thanks for your help. Closing this.
