### ISSUE TITLE
acr_values is sent empty with each request

### ISSUE THREAD

**Issue by ScottGuymer** [oauth2-proxy/oauth2-proxy#588]
When configuring an OIDC provider if not specified then "" (empty string) is provided as the `acr_values` for an auth code request. The provider i am configuring against (at least) does not accept empty string and errors when this is provided. 

There is no way in the config to tell it not to send this end parameter by default

This is new behaviour we encountered when upgrading from 5.0.0. > 5.1.1

## Expected Behavior

Expect that unless configured `acr_values` parameter is not sent on auth request.

## Current Behavior

`acr_values` is always sent and there is no way to turn it off

## Possible Solution

By default acr_values parameter should not be sent unless a value is explicitly configured.

## Steps to Reproduce (for bugs)

1. configure oidc (or any) provider without configuring acr_values
2. send request
3. inspect and see empty `acr_values=` parameter by default

## Context

5.0 version worked and now 5.1.1 does not allow login because IdP returns an error from invalid acr_values

**Comment by JoelSpeed** [comment]
Sounds like we need to check for an empty string before adding the parameter. I know this was changed recently so must have been in the 5.0 to 5.1 release, marking as a bug

**Comment by ScottGuymer** [comment]
Yes this was fine in 5.0 and reverting back to that version solved the problem.

I could have a go at fixing it.

Should be simple enough even for my golang skills.. 🤣

**Comment by JoelSpeed** [comment]
If you have the time to raise a fix, that would be greatly appreciated 😄

Should just be a case of wrapping this in an if statement, and preferably, adding a test case. https://github.com/oauth2-proxy/oauth2-proxy/blob/f7b28cb1d362f54d13379136c37f0edc1303a1b0/providers/provider_default.go#L97

**Comment by ScottGuymer** [comment]
Opened #598 

A quick change to the code to validate thinking.  Would appreciate feedback on it and anything you see that needs changing

Still need to update docs a little
