### ISSUE TITLE
How to setup SSO?

### ISSUE THREAD

**Issue by K7-Lenovo** [oauth2-proxy/oauth2-proxy#594]
Can I build a SSO with this project? like [sso](https://github.com/buzzfeed/sso) but support Azure.
That I can login all site in my domain in one time by using a sso site.
where sso-site is the OAuth2 provider for sso-proxy and MS Azure is the OAuth2 provider for sso-site.

**Comment by JoelSpeed** [comment]
You may want to look at [Dex](https://github.com/dexidp/dex) and use that in conjunction with this project, if I've understood what you're trying to achieve, you would have Dex as your internal IDP, connected to Azure, then OAuth2 Proxy would be a client of Dex and provide the authentication for your other sites

**Comment by K7-Lenovo** [comment]
Thanks, l‘ll try it.
