### ISSUE TITLE
Specify a group claim for use with oidc provider

### ISSUE THREAD

**Issue by obikay200** [oauth2-proxy/oauth2-proxy#600]
## Current Behavior

Currently you can set a custom userid claim using --user-id-claim ( ref 5.1.1) 
m using the oauth2_proxy in conjunction with nginx.

i would like to be able to pass group from a custom claim to upstream services. 

for example
--group-claim=cognito:groups

and have the results available in X-Auth-Request-User-Groups

**Comment by JoelSpeed** [comment]
I would like to see this implemented, definitely in favour of having this customisable

**Comment by stefansedich** [comment]
+1 was just looking at how to do this, would be very handy for my case where I want a single GH App and Dex instance, and manage group level perms at the oauth2-proxy level.

**Comment by stefansedich** [comment]
@obikay200 @JoelSpeed just opened https://github.com/oauth2-proxy/oauth2-proxy/pull/616 which adds this support, would be interested to hear your thoughts.
