### ISSUE TITLE
Github enterprise does not enforce SSO

### ISSUE THREAD

**Issue by dchen71** [oauth2-proxy/oauth2-proxy#602]
## Context

I am trying to have a two layered approach to logging into my web application. In one layer, you must have a specific email domain and be part of a specific Github organization as part of my github enterprise account to access the first layer. The second layer, is to enforce my company's SSO policy as part of Github Enterprise to be able to identify as the user. The first part works and I am able to get to the Github screen asking to authorize access in the organization however, I can click continue to skip it and it will work. 

I would like to enforce authorization via SSO to gain access to the web site and not allow users to skip this single sign on step.

## Expected Behavior

In the SSO screen, users should not be able to click Continue to skip organizational authorization.

## Current Behavior

Users can choose to authorize or skip it completely.

## Possible Solution

Not sure but assume it has something to do with the endpoint when you click continue.

## Steps to Reproduce (for bugs)

github-org: <enterprise org>
email-domain: <enterprise email domain>
The other recommended github enterprise settings were not used as it's hosted on github cloud

## Your Environment

AKS
Github Enterprise Cloud
stable/oauth2-proxy 5.1
nginx-ingress

- Version used:
oauth2-proxy 5.1 via helm chart stable/oauth2-proxy

**Comment by JoelSpeed** [comment]
HI @dchen71, thanks for raising this question, though I'm not sure I particularly understand 

> The second layer, is to enforce my company's SSO policy as part of Github Enterprise to be able to identify as the user. The first part works and I am able to get to the Github screen asking to authorize access in the organization however, I can click continue to skip it and it will work.

This implies you are having a second OAuth2 Proxy? Is that correct?

> I can click continue to skip it and it will work.

Can you upload a screenshot/provide more details on this, I'm not aware of being able to skip anything so I'd like to understand exactly where this is happening?

**Comment by dchen71** [comment]
There is only 1 oauth2 proxy. My company uses a two factor authentication to verify access to any enterprise github organization and associated repo. The picture below should make this more clear.

![ex](https://user-images.githubusercontent.com/4143686/83675612-2dc44d00-a58e-11ea-995f-a5387f310099.png)

The picture above is expected since I am using organizational filtering scope which checks for membership in a given organization. As I using it as part of an enterprise account, the application should have the additional SAML sign on which should be enforced in oauth applications as well. When I click the authorize button for the organization, I get my company's two factor authentication and failure and success work as expected. It's the continue button which skips it.

**Comment by JoelSpeed** [comment]
Ok this makes slightly more sense now. I've not seen this before and I can't find any reference in the documentation to it. Normally you have to click authorize, I've never seen a continue button before.

Can you try reviewing the GitHub configuration for you OAuth app, perhaps there is some configuration there that disallows this button

In the mean time, you could look at our `--github-org` flag, I would assume that if they haven't authorized for the org, then the checks there would fail

**Comment by dchen71** [comment]
I emailed github support about it and it doesn't seem like the continue button can be removed from their side. I am wondering if this is an issue with some parameter of oauth2-proxy causing scoping issues or if it's potentially coming from nginx-ingress. 

The `github-org` flag actually is necessary to go to this step. Without that scope, any user can sign up/log into the application. So technically, although it is a enterprise organization and the app does require membership to the organization but it doesn't enforce SSO authorization which is secure and insecure :)

**Comment by JoelSpeed** [comment]
> I emailed github support about it and it doesn't seem like the continue button can be removed from their side. I am wondering if this is an issue with some parameter of oauth2-proxy causing scoping issues or if it's potentially coming from nginx-ingress.

It could well be, I haven't managed to find any documentation about this though

**Comment by dchen05** [comment]
In my nginx ingress `auth-signin`, I have https://auth.int.{{domain}}/oauth2/start?rd=https%3A%2F%2F$host$request_uri

In the continue link as part of the callback response_type and request_uri, I see `skip_sso=true`. Changing that to false fails as expected. Is my redirect with nginx correct or is there another redirect I can do?

**Comment by dchen71** [comment]
In my nginx ingress auth-signin, I have https://auth.int.{{domain}}/oauth2/start?rd=https%3A%2F%2F$host$request_uri

In the continue link as part of the callback response_type and request_uri, I see skip_sso=true. Changing that to false fails as expected. Is my redirect with nginx correct or is there another redirect I can do?

**Comment by JoelSpeed** [comment]
> In the continue link as part of the callback response_type and request_uri, I see skip_sso=true. Changing that to false fails as expected. Is my redirect with nginx correct or is there another redirect I can do?

By this you mean the URL constructed and sent as the redirect from OAuth2 Proxy? 

As far as I can see your redirect is correct

**Comment by dchen71** [comment]
Yes, the URL constructed for the redirect. It has the organization and email scope along with the skip_sso=true.  

```
callback&response_type=code&scope=user%3Aemail%20read%3Aorg&skip_sso=true
```

**Comment by JoelSpeed** [comment]
That URL is contstructed here https://github.com/oauth2-proxy/oauth2-proxy/blob/1683aa59780cd910e49561e7c046fe1782649fc8/providers/provider_default.go#L92-L111

As you can see, it's not setting `skip_sso`, but does include params from the login URL that you've set, can you double check you haven't set it in your login URL?

**Comment by dchen71** [comment]
For the loginurl, are you referring to the callback url? The callback url is `https://auth.int.{{domain}}/oauth2/auth`. But none of the urls during any of the processes have `skip_sso` in them so the continue button does actually add it after the scope. I am not the most familiar with the internals of oauth but would I not be able to modify the authorization redirect url to forcibly include skip_sso=false to try to counteract the button to potentially skip?
