### ISSUE TITLE
local-environment: nginx option doesn't authenticate

### ISSUE THREAD

**Issue by EvgeniGordeev** [oauth2-proxy/oauth2-proxy#603]
## Expected Behavior

```bash
cd contrib/local-environment
make nginx-up
# Access one of the following URLs to initiate a login flow:
#    - http://oauth2-proxy.localhost
#    - http://httpbin.oauth2-proxy.localhost
# login flow works
```

## Current Behavior
1. nginx starts before oauth-proxy and thus throws an error: 
```
nginx: [emerg] host not found in upstream "oauth2-proxy" in /etc/nginx/conf.d/default.conf:10

``` 

2. after second `make nginx-up` authentication flow doesn't work:
* go to http://httpbin.oauth2-proxy.localhost
* redirected to http://oauth2-proxy.oauth2-proxy.localhost/
* after successful login to http://dex.localhost:4190/ the redirect back to http://oauth2-proxy.oauth2-proxy.localhost/ gets stuck OR it's redirected back to http://oauth2-proxy.oauth2-proxy.localhost/ sign-in option

## Possible Solution

1. use `restart: always` or `depends_on: ["oauth2-proxy"]`on nginx service in docker-compose-nginx.yaml.
2. unknown

- Version used: master at 3aeca4368c3c9f4d1f02af8c662c39c679a7fc96 (as of 2020-06-03)

## Suggestion

Can we use wildcard hosts at http://readme.localtest.me/ for proper hostname resolution? Then 
modifying /etc/hosts becomes obsolete. 

## Environment
Chrome incognito

**Comment by JoelSpeed** [comment]
Hey @EvgeniGordeev, could you just confirm for me, this is when trying to run the `v5.1.1` image as is default or trying to run an image built from master at the commit specified?

> Can we use wildcard hosts at http://readme.localtest.me/ for proper hostname resolution? Then
modifying /etc/hosts becomes obsolete.

This is awesome! I didn't know this existed, I definitely think this would help us out so non-chrome users don't have to add host entries!

**Comment by JoelSpeed** [comment]
I've found the issue, we updated the config with one of the breaking changes due in the next release, for `v5.1.1` this option should read `cookie_domain` without the trailing `s`

https://github.com/oauth2-proxy/oauth2-proxy/blob/160bbaf98e603fc4dfa18b19e39eccb05b0ad416/contrib/local-environment/oauth2-proxy-nginx.cfg#L11

**Comment by EvgeniGordeev** [comment]
Hey @JoelSpeed , it tooks some time - keycloak is very much enterprice-ish - but here is another example for keycloak as IDP as well as `.localtest.me` https://github.com/oauth2-proxy/oauth2-proxy/pull/604. 

Would be easier with nginx but I found a workaround with `alpine/socat` to make it work in the container as well as outside of it.

**Comment by EvgeniGordeev** [comment]
@JoelSpeed I am using the default image `v5.1.1.` as it is defined in docker-compose.yaml.

**Comment by JoelSpeed** [comment]
> As for s typo in cookie-domains it actually worked in my case AS IS - https://github.com/oauth2-proxy/oauth2-proxy/pull/604/files#diff-58b28d949ca23d99247dcab0ad264c44R6

Because you only have a single host example, you don't actually need to set the cookie domain, so the option is being ignored by the code and it's just setting to whatever the request host is, which happens to work in your example case
