### ISSUE TITLE
How to deal with users bookmarking the OIDC provider?

### ISSUE THREAD

**Issue by jonerer** [oauth2-proxy/oauth2-proxy#607]
Thanks for a great project! We've had great use of it, and the code has been very readable for when we need to dig deeper.

## Expected Behavior

We've set up an oauth2-proxy to a OIDC provider (AWS Cognito). Normally, for an unauthenticated users, the auth flow is like this:
- user goes to our app
- gets redirected to oauth2-proxywhich sets "_csrf"-cookie
- gets redirected to the OIDC provider
- user logs in
- gets redirected to oauth2-proxy, which reads "_csrf"-cookie
- gets redirected to app

## Current Behavior

But now we have an issue where the flow is like this:
- user goes to our app
- gets redirected to oauth2-proxywhich sets "_csrf"-cookie
- gets redirected to the OIDC provider
- user **bookmarks the OIDC provider login page**
- months pass
- user goes to the OIDC provider login page (not, via oauth-proxy)
- user logs in
- gets redirected to oauth2-proxy, which tries to read "_csrf"-cookie (which doesn't exist anymore)
- users is presented with "403 Permission Denied: http : named cookie not present"
- Logs say `10.0.59.113 - [... user name here] [2020/06/05 08:07:05] [AuthFailure] Invalid authentication via OAuth2: unable too obtain CSRF cookie`

## Your Environment

- Version used: 5.1.0

So my question is: what is the normal way to solve this type of issue with oauth2-proxy?

**Comment by JoelSpeed** [comment]
I've never heard of anyone doing this before 😅  I can't really think of a workaround apart from telling the users not to bookmark the login page, I suspect you'd have the same issue with other SSO type projects as well.

Has this been hit by many of your users?

**Comment by lulzmachine** [comment]
Yeah it took quite a bit of debugging. But I _think_ this is what happens. I can reproduce it this way at least.

We don't have a high customer count, so I can't provide any statistical analysis. But it happens often enough that we want to do something about it.

Does adding a "--csrf-failure-redirect-url" make sense to you?

**Comment by JoelSpeed** [comment]
I wonder if this could somehow be linked with the work being undertaken in #605?

**Comment by rabbers** [comment]
The function of #605 is to recognise error conditions from the identity provider and provide an automated redirect to a url (normally back to the identity provider). A CSRF failure redirect would be in response to an application condition within oauth2_proxy.

**Comment by JoelSpeed** [comment]
Hmm yes I see. I wonder what other projects or sites do when their is a CSRF failure, do we think there is precedence for a redirect if CSRF fails?

**Comment by vanschelven** [comment]
This is the top hit in my search engine for the generic problem of users bookmarking the OIDC provider, and this leading to a false positive CSRF exception because the state was never set in the client application.

Too bad it got auto-closed, since the discussion is still an open end, and I haven't found many other references on the internet about this problem. One notable exception is https://lists.jboss.org/pipermail/keycloak-user/2017-August/011623.html 

The most actionable remark in that thread is:

> Have you tried putting a message on the login page to say, "Don't 
> bookmark this"

Regarding the question above:

> Has this been hit by many of your users?

In my context: yes.
