### ISSUE TITLE
Multitab authentication race condition failure

### ISSUE THREAD

**Issue by jonerer** [oauth2-proxy/oauth2-proxy#611]
When trying to authenticate with oauth2proxy with an OIDC provider on multiple tabs simultaneously, there is a race condition. This happens when you for instance restart a web browser with multiple tabs open on the same oauth2-proxy-based app.

There are two issues: One issue occurs because the "_csrf"-cookie is cleared in the OAuthCallback function in oauthproxy.go. And one occurs because the old cookie is overwritten.

## Expected Behavior

Starting conditions: You are logged into the OIDC provider, but the oauth2proxy cookie has expired. You start 10 tabs to your app. All tabs should go through this flow:

- Try to load app, get redirected to oauth2proxy
- Oauth2proxy sets csrf cookie, redirects to provider
- Provider redirects to oauth callback on oauth2proxy
- Oauth2proxy redirects back to app

## Current Behavior

Starting conditions: You are logged into the OIDC provider, but the oauth2proxy cookie has expired. You start two tabs to your app. Both tabs should go through this flow successfully:

An example using two tabs. Tabs denoted "1" and "2".

- 1. Try to load app, get redirected to oauth2proxy
- 2. Try to load app, get redirected to oauth2proxy
- 1. Oauth2proxy sets csrf cookie, redirects to provider
- 2. Oauth2proxy sets csrf cookie, redirects to provider
- 1. Provider redirects to oauth callback on oauth2proxy
- 1. Oauth2 proxy deletes csrf cookie redirects back to app
- 2. Provider redirects to oauth callback on oauth2proxy
- 2. Oauth2 finds no CSRF cookie, responds with HTTP 403 and prints an error message

In log: <user name> [2020/06/11 06:13:30] [AuthFailure] Invalid authentication via OAuth2: unable too obtain CSRF cookie
On screen: 403 Permission Denied: http : named cookie not present

In some cases we see another failure. On the screen it says: 403 Permission Denied csrf failed

This happens when the race happens in another way. Unsure exactly how.

## Possible Solution

For the issue "Invalid authentication via OAuth2: unable too obtain CSRF cookie":
    Probably OAuthCallback in oauthproxy.go should not remove the CSRF cookie. Just leave it with a rather short timeout (say 5 minutues or so).

   Or in the cases where we can detect that we have an authentication cookie, then perhaps we can just ignore the authentication attempt and redirect back to the app, skipping CSRF Cookie checks?

For the issue "csrf failed" I'm a bit unsure how to proceed

## Steps to Reproduce (for bugs)

1.  Go to your oauth2-proxy backed app. Make sure your are authenticated to the OIDC-provider.
2.  Remove your oauth2-proxy auth cookie
3.  Hold ctrl on windows or cmd on mac and spam-click a link on your app
4.  Some tabs succeed, others fail

## Context

This occurs when the user restarts her browser

## Your Environment

- Version used: 5.1.0
- Provider: OIDC (AWS Cognito)

**Comment by JoelSpeed** [comment]
This is a common problem across many implementations of this kind of project. I agree it's an issue but I don't know how we can tackle this right now. 

Perhaps we can have the proxy detect that a valid session has been created in the interim and not error out, if we go that route, we would need to have a good think about the security implications of that

**Comment by r-kotagudem** [comment]
any solutions/work around for this issue? We are seeing same issue
