### ISSUE TITLE
GCP HealthCheck option should be deprecated

### ISSUE THREAD

**Issue by JoelSpeed** [oauth2-proxy/oauth2-proxy#614]
## Expected Behavior

We should not duplicate behaviour

## Current Behavior

There is an explicit GCP HealthCheck middleware that is filtering requests when the GCP HealthCheck option is provided.

This checks that the request path is `/readiness_check` or `/liveness_check`, or that the user agent is the Google user agent, and responds with an `ok` response if any of these are true.

I would argue that this is no longer required.

The `/readiness_check` and `/liveness_check` checks are intended to support Google App Engine 
[split health checks](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml#updated_health_checks), but these could just be configured to the `PingPath` option and would be functionally equivalent.

The User Agent check could be solved by `PingUserAgent` which was introduced in #567 if I've understood correctly.

## Possible Solution

- Rip out the GCP HealthCheck and remove the option. Provide documentation for those who were using it that it is no longer supported and how to migrate
- Keep the option, but somehow keep the behaviour, by making ping path and ping user agent lists and checking each one in `IsPingRequest`

CC @timothy-spencer @chkohner

**Comment by kskewes** [comment]
Not using this functionality but it took me on a detour when doing silent ping PR.
Ripping out and providing migration docs seems reasonable.
Could pick up if so.

**Comment by JoelSpeed** [comment]
I've also been considering reworking the health checking and this may be relevant if we are ripping this out. What if we move the `ping` logic to a middleware (like the GCP HealthCheck) that checks the path or the user agent and returns the ping response, or if not, continues to the next flow. If the ping was implemented there, I think when `--silence-ping-logging` is enabled, we could register the middlewares `Ping(LoggingHandler(oauthproxy))` so that there's no request logging, that way we don't need any of the silent stuff recently introduced? If it's disabled we do `LoggingHandler(Ping(oauthproxy))` and then the ping requests are logged

**Comment by JoelSpeed** [comment]
@kskewes I had a go at my theory from the above comment in #620, it currently preserves the flag, though we could/should still be deprecating it in the future. Would certainly appreciate a review from you if you have the time

**Comment by JoelSpeed** [comment]
We will include this in the next major release

**Comment by JoelSpeed** [comment]
Still relevant

**Comment by JoelSpeed** [comment]
We should deprecate this as part of the next release

**Comment by netgusto** [comment]
This is still required on GKE (Google k8s engine), and not only on App Engine!

On GKE, while it's possible to set the readiness and liveness checks paths for deployments, it's not possible to set the path of the ingress healthchecks. The ingress expects the `/` of the backend to answer `200` and everything else (including `302`) is considered `unhealthy`.

Please, don't deprecate this.

**Comment by JoelSpeed** [comment]
Could you please link documentation that supports this? When I looked before I couldn't see anything within the documentation that says that you have to have the root of the application act as a healthcheck

**Comment by netgusto** [comment]
@JoelSpeed Sure!

Here: https://cloud.google.com/load-balancing/docs/health-check-concepts#criteria-protocol-http
and in https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#def_inf_hc, look for "Expected Response"

**Comment by netgusto** [comment]
@JoelSpeed and you're right, the documentation says the path can be changed, and it should use the `readinessProbe` pathn but it seems the ingress never picks it up (probably would have to be destroyed and re-created for this to happen)

**Comment by JoelSpeed** [comment]
Ok, so just to clarify, this _can_ be configured on the Google side, and should be configured on the google side, so a specific google health check option isn't actually needed in OAuth2 Proxy.

Alternatively, you can still configure a user agent check (which is all the google health check option does) which will retain the existing behaviour.

As a final clarification, we are planning to remove the option, but all that option does is configure another option, so you would just have to configure that option to maintain the behaviour

**Comment by netgusto** [comment]
> As a final clarification, we are planning to remove the option, but all that option does is configure another option, so you would just have to configure that option to maintain the behaviour

@JoelSpeed thank you, that helped! I'm now using the `--ping-user-agent "GoogleHC/1.0"` argument which does the trick. To provide more context to my previous statements, while it's possible to edit the path of a LB healthcheck in the google console (and probably using the `gcloud` cli as well), I was not able to set it using kubernetes resources.
