### ISSUE TITLE
Access Token and Authorization [Clarification/Confusion]

### ISSUE THREAD

**Issue by neuralsandwich** [oauth2-proxy/oauth2-proxy#618]
I believe `--[set|pass]-authorization-header` and `--pass-access-token` are confusingly named. In regards to OAuth and OpenID, I'd expect to have the authorization header that was sent to my application to be the access token. I may be mistaken but I can't seem to find any material on sending ID tokens via that header.

I know what I am suggesting would break setups going forward so I'd be _really_ happy if what I was saying was mistaken. A solution could be allowing to set a header/token mapping, so users could configure them as they wanted might be an easier solution.

I'm currently using the following Nginx config as a workaround:

```
auth_request_set $access_token $upstream_http_x_auth_request_access_token;
proxy_set_header Authorization "Bearer $access_token";

auth_request_set $id_token $upstream_http_authorization;
proxy_set_header X-Forwarded-ID-Token $id_token;
```

## Expected Behavior

* `--[pass|set]-authorization-header` to set the header `Authorization: Bearer $ACCESS_TOKEN`
  * or it should take a parameter to specify which token it should pass to aid in current behavior
* `--[pass|set]-access-token` to set the header `X-Forwarded-Access-Token: $ACCESS_TOKEN`
* `--[pass|set]-id-token` to set the header `X-Forwarded-ID-Token: $ID_TOKEN`

## Current Behavior

Setting `--[pass|set]-authorization-header` send the ID token to an application expecting an access token.

- Version used: v5.1.1

**Comment by JoelSpeed** [comment]
> I may be mistaken but I can't seem to find any material on sending ID tokens via that header.

When this was originally implemented, it had the Kubernetes use case in mind, for example, the Kubernetes Dashboard project expects the ID Token in the authorization header.

Long term, I would like to remove all of the existing set/pass header options and make a more flexible configuration that allows users to define their own header to value mappings, however, before we do that, we really need to do some refactoring to migrate towards a structured configuration as described in #532 

For now, I would rather not change anything until we have got to that stage and can introduce the flexible header injector

**Comment by mdgilene** [comment]
Been a while since this issue was brought up. Don't see any firm progress on #532 that you mentioned, however this remains a problem. Doesn't seem right to lmit the functionality to only one specific use case when the vast majority of applications will be expecting an Access Token in the Authorization header rathen than an ID Token. Would you consider re-evaluating the need for a stop gap here? Or maybe just an update on the timeline for the configuration overhaul issue.

**Comment by JoelSpeed** [comment]
This can now be done if you use our alpha configuration, we are still working towards #532 but it is a larger effort so unfortunately will take some time

**Comment by mdgilene** [comment]
Ahh, thank you. My brain did not make the connection between the "Alpha Configuration" topic on the docs site and that issue.
