### ISSUE TITLE
algorithm to decode cookie?

### ISSUE THREAD

**Issue by Llewellin** [oauth2-proxy/oauth2-proxy#623]
I've followed along the tutorials, but I really cannot find the answer for this. This might be a very easy question, but I am really confused on how to solve it.
I'm using `google oauth2` + `oauth2-proxy` + `k8s` + `nginx ingress`. I am able to get cookie `_oauth2_proxy` in my service, but i don't know how to decode it. I've set `cookie-secret` already but I don't know what kind of algorithm cookie used to encode data.

I tried to decode it with command: `echo "cookie content here" | base64 --decode`
It shows something like this
```
{"AccessToken":"qjnJUKaSj5UY9OQMV6GNHxgmr51zIzqEuNUxvZAjWN+lG01ku/Ab5yz+Kbjmue3PafbF8SXiq+9LDcr6AH0pme6pQNDqAFQ5OXyNuczfiZtzhQrS4uFRHH8EWavzelrs9+1fKqYNH2ApJfw3Z4MVGuhlBkkMAsv3mmC1vbCvaBKotN5qExy6Ne8ZW30pjSZMIPqCqqaqCnC+sg1vVdzWyY2FmYBFZJGvwOp0/3hWmgbv9ZLRvfHWSFfL","IDToken":"lbQSd++3HP//UPnS0YuerDa8WLUpKpzGUCawrV43wLm1L7AGhHHKopRMR5W8bsXaoq51aSP0GgntNpMYeihMTLuPRvPH+j/L1LEB584QJvge/CSPkbTn01Y4ljboSCPmrOxRYVhx+HE4larRg9Wud7jqDe5Uyj1AAXo4u5X5a8UN9sz3DvuoPhqRUKqIyvogKgcHyxM7zHnKj4MujpIOsnMtS569FRdMllzq/RKKX1Q5590joIG6PNV52kpsDSzCkYeubQmIIfEAw9k0DlCbPGj/uPzch+VpWh6WLNbD4YtMZ0P7H0z4gpo2ifDFLevGCX0fTH0/rB1XRfDQ0ucoSJL8bXquN/o1SW2ltFqn+1BU1gJV+NaB6mZ8PPiGcon19l4twPqMzEi+Fnbbh1fuuQ9XG/3vPsTF/RpWPYidQ1APdt0yhQE7rzLe/QC6a9ZtLCHj3ASc7oBmsDdod/h+Yv2mY1xzKbXCsnH3MSuiL4c8WDesl1Qk5Y+bAisu3bDOx0jMXDDOo+9zUYARnuv5gOT9WWgNdgdrWKTAyvfh/06VsE/HMN4GmZjx1mNWOskHjhbjUTzTVJjGS8LMh/wqvU9l0iGR4RKQlLwRe7Kmm2suAH4UpeR5Qsns47YEnloX8wWW2qOTCVGYUroYGd2F6yY4puRd94i6g5GVQZKDha7QBZxkJIjOX7JyhI5OH21r2zXPKZmdpUJrYy944OvsSIsF/WDNC3RTewa6txrGDPU/ZQENe0/tJ1sQfwe/Pj/j5ZuFHDGvQSyONGBxV7zKPjVHew0ea279KaZc9vyzUjbHzXyzzuYcjt+UQKiSQY3mcJVfbck3wXZ49IzWL9BaVusMmgDCb4XeZjC9KvR5rKt/PDwftGlTrwxFi+IiJBS5PSH61gMz5lLzaNSVJRK0K58MrpofHJXgvvKy/0pEJVkkNy+0M+VCeu8zW7ahH25zvNnvylLe6snwA5jBYyFfKPA3x5595TWOWPeSE72xjIHDtcDbqzleJBwSya3nWW2PeAQIewsiW0znCL4soJbiQVG0kjJ65ypKfF3+lTdPKkFJMUAhDWHf10esJgSLRCaRfieGSmjSe+mcNPJu9uCLdnidZ8yUQQd5otuB5JZ3n7Ts9bhFVXHqWjwf5IoMq7AWBsc3lMkHMydnSV3GeZScvBBKC7kNCH+baPx9aPATmM8sRg9FobMnF2cU2Tme3e8sCxLMEr4n","CreatedAt":"2020-06-16T13:35:36.219927066Z","ExpiresOn":"2020-06-16T14:35:35Z","RefreshToken":"xVyFjVPx3bqHr8EagI95KqGTnow51iA7lhuVPlSScJUNV4PgYXO7wYQfm321metmmE6a0lJuu+XCreCkiWEnIxs1UFetbEaUKVL/DdPi3bDoPl2OFmjoiodDCOj2Xu1T5sFwnwLriM7TNdWoNA+8oztiB4C1+MI=","Email":"wN2CVTHCWkw8wLCV22TLD7oGmJGYkKf6kIjDrUVgKT5w5nhdcQ==","User":"uEC60i7tut4jnf3JALEmWacV6QRRPFKgtvFIcrKc2rXgUqZzFA=="}%
```

Apparently some data is returning but the data inside is wrong. If you scroll to the end you can notice that the `email` field and `user` field are making no sense at all.
## Expected Behavior

Show correct `User` and `Email`

## Current Behavior

Partially-correct data for cookie`_oauth2_proxy`

**Comment by JoelSpeed** [comment]
Hi @Llewellin, You shouldn't be trying to decode the cookie in your application and instead, should be using options like `--set-xauth-request` or `--pass-xauth-request` to have the OAuth2 Proxy project inject headers into the request or response.

We are currently making a lot of changes to the sessions as they are encoded in cookies and would not be considering these breaking changes as we consider the sessions data to be an internal API rather than a user facing one

**Comment by Llewellin** [comment]
@JoelSpeed 
Thank you then I get the idea.

One more question, in the case of `google oauth2`, some data has also returned from `https://www.googleapis.com/oauth2/v2/userinfo?access_token=` endpoints. With the current header setting, I can only get `user id` and `user email` from the headers. How can I get those additional info like `given name`, `family name`, `locale` or `picture` via header settings?

**Comment by JoelSpeed** [comment]
I believe you'd have to add additional scopes but I don't have experience myself so I'm not sure what those are

**Comment by NickMeves** [comment]
@Llewellin This discussion that started today is semi-related: https://github.com/oauth2-proxy/oauth2-proxy/issues/631#issuecomment-649750682

At the moment, there is no way to get other richer claims you might get in an IDToken with the `profile` scope via easy to access headers.  Only User, Email & PreferredUsername claims are extracted and part of the session & forwarded via headers.

BUT -- you can use the `--pass-authorization-header` flag to pass the IDToken to your backend in the `Authorization` header.  Only catch is your backend application would need to process the JWT and extract the claims itself.

Hope that helps!
