### ISSUE TITLE
Flag provided but not defined: -github-user?

### ISSUE THREAD

**Issue by shinebayar-g** [oauth2-proxy/oauth2-proxy#627]
I'd like to use github provider with using --github-user flag. Started oauth2_proxy with following flags, but it's not starting?

```
/bin/oauth2_proxy \
--http-address=0.0.0.0:4180 \
--provider=github \
--client-id=123redacted123 \
--client-secret=123redacted123 \
--cookie-secret=123redacted123 \
--email-domain=* \
--github-user="shinebayar-g"
```

## Expected Behavior

Authenticate successfully with my github account

## Current Behavior

It's giving error:

```
flag provided but not defined: -github-user
```

Also why its showing all options with single dash `-` while [configuration](https://oauth2-proxy.github.io/oauth2-proxy/configuration#command-line-options) uses double dash `--`?
[This](https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#github-auth-provider) documentation uses single dash. Which one is correct or preferred?

## Steps to Reproduce (for bugs)

1.  

Start release 5.1.1 docker image with following flags. (quay.io/oauth2-proxy/oauth2-proxy:v5.1.1)

```
/bin/oauth2_proxy \
--http-address=0.0.0.0:4180 \
--provider=github \
--client-id=123redacted123 \
--client-secret=123redacted123 \
--cookie-secret=123redacted123 \
--email-domain=* \
--github-user="shinebayar-g"
```

## Your Environment

- Version used:
5.1.1

**Comment by shinebayar-g** [comment]
Looks like `--github-repo` flag is also missing. I'm getting `flag provided but not defined: -github-repo` error.

**Comment by JoelSpeed** [comment]
New version is imminent, I think there just a single PR left on the waiting list and I'm waiting for review from another maintainer for that ideally

Apologies that the docs are tracking master instead of the latest release, we do have an issue to fix that but we haven't gotten around to it just yet (See #550)

**Comment by shinebayar-g** [comment]
Works like a charm in 6.0.0, ty.

**Comment by shinebayar-g** [comment]
Just noticed that usernames should be case sensitive to make it work. Even though github login works insensitive. What do you think? @JoelSpeed

**Comment by JoelSpeed** [comment]
Would be good to make it case insensitive if it isn't already, fan you raise a new issue for this and hopefully we can get a small patch prepared
