### ISSUE TITLE
Extra Headers to Upstream

### ISSUE THREAD

**Issue by kfox1111** [oauth2-proxy/oauth2-proxy#631]
## Expected Behavior

There to be a configuration option to inject arbitrary request headers when contacting the upstream after authentication

## Current Behavior

No option exists

**Comment by kfox1111** [comment]
https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L980 may be the place to do it?

**Comment by JoelSpeed** [comment]
I have been thinking about this recently and intend to split the `addHeadersForProxying` code up soon. What I would like to do is create middlewares that can be configured to add headers based on a structured configuration, I'm thinking we will need three middlewares:
1. To strip headers that are given in a request that we should be proxying to an upstream (eg if the user supplies X-Forwarded-Email, this should be stripped before we set it in the next step)
2. To inject headers to requests being proxied to upstreams (to cover `--pass-xxx` options)
3. To inject headers to responses (to cover `--set-xxx` options)

To enable this I would like to think about how we can have a structured configuration for the headers that is flexible to cover the use cases we currently have, something like:

```
injectHeaders:
- name: X-Forwarded-Email
  claim: email // This comes from the session state
- name: X-Forwarded-Authorization
  claim: id-token
  prefix: Bearer // So that we can create the header `X-Forwarded-Authorization: Bearer <token>`
- name: X-API-Key
  value: <raw-string>
- name: Authorization // Name is required and must be unique, forced to `Authorization` if basicAuth provided
  basicAuth:
    claim: userid
    password: $BASIC_AUTH_PASSWORD // when loading the config file, envsubst this value
```

How does that sound to you? CC @NickMeves @steakunderscore I'd also appreciate your feedback on the above idea

**Comment by NickMeves** [comment]
I have been thinking the same thing recently! My mind has drifted to potential OIDC use cases of flagging arbitrary claims (I'm not sure what other providers implementation would look like).  IE a setting of a list of claims to be considered a `user-header` that would be passed based on the 2 potential flags that trigger that as `X-Forwarded-<ClaimName>` or `X-Auth-Request-<ClaimName>` headers. 

We default to giving OIDC the scope of `openid profile email` but we have no real way to expose the potential rich `profile` claims users might want besides passing the IDToken and leaving it to the backend application to decode.

I think Keycloak Gatekeeper had a concept similar to this.

This likely cleans up the special claims in a session that more and more users have been requesting lately (user-id-claim, the recent groups claim PR, etc).

**Comment by NickMeves** [comment]
In essence then, we can have a couple that are special based on potential integrations with auth or email lookup endpoints of the issuer (likely `subject` -> user and email) then any others (ie preferred_username) we can have set with arbitrary claims list.

**Comment by JoelSpeed** [comment]
+1 to having an arbitrary claims list eventually, I imagine we would have a core set of claims in the session state and then maybe an `extra_claims` map that could store any extra claims that the user has requested to be extracted from the token or userinfo endpoint

**Comment by NickMeves** [comment]
This related semi-related PR is taking a look at just getting Groups exposed as an additional header:

https://github.com/oauth2-proxy/oauth2-proxy/pull/616

**Comment by JoelSpeed** [comment]
I just had a quick skim, I'll take a proper look later, maybe we include it for now but go with my other suggestion as a longer term solution? @kfox1111  I'd still appreciate your feedback on the suggestion I made, does that sound good to you?

**Comment by kfox1111** [comment]
Yeah, I like the injectHeaders idea. Very flexible and mirrors how k8s's api works for environment variables. Gives the ability to extend the api with lots of different options in the future without breaking the existing api.

**Comment by kfox1111** [comment]
A way to use environment variable values would be useful as well in the injectHeaders api.

**Comment by JoelSpeed** [comment]
> A way to use environment variable values would be useful as well in the injectHeaders api.

I was trying to demonstrate that with the final basic auth example, suggesting we allow any field to be envsubst'd before setting up the proxy, do you mean for something more explicit?

**Comment by kfox1111** [comment]
Oh, yeah. I missed that the second time I read through it. Sorry. I think that would work.

**Comment by InfoSec812** [comment]
> I have been thinking the same thing recently! My mind has drifted to potential OIDC use cases of flagging arbitrary claims (I'm not sure what other providers implementation would look like). IE a setting of a list of claims to be considered a `user-header` that would be passed based on the 2 potential flags that trigger that as `X-Forwarded-<ClaimName>` or `X-Auth-Request-<ClaimName>` headers.
> 
> We default to giving OIDC the scope of `openid profile email` but we have no real way to expose the potential rich `profile` claims users might want besides passing the IDToken and leaving it to the backend application to decode.
> 
> I think Keycloak Gatekeeper had a concept similar to this.
> 
> This likely cleans up the special claims in a session that more and more users have been requesting lately (user-id-claim, the recent groups claim PR, etc).

I would love the ability to add arbitrary fields from the JWT token as headers as it would solve a lot of issues I am trying to manually work around right now. For example, I am using KeyCloak+OIDC with oauth2-proxy and I would love for the mapped "roles" attribute to be passed as `X-Forwarded-Groups` to my SonarQube and Nexus servers.

**Comment by NickMeves** [comment]
@InfoSec812 Hopefully I can get to that Claim->Header idea in the next few weeks.

In the near term, this PR is looking to make Groups a canonical header (at least for OIDC): https://github.com/oauth2-proxy/oauth2-proxy/pull/616

**Comment by JoelSpeed** [comment]
So you're aware, I started working on something that might help with the arbitrary claim mapping in #705. Since we won't get the structured config for a while still, I'd like to get #636 in, release that, and integrate it with #705 so that the extra headers get converted to static valued headers from a "secret" value.

**Comment by loicoudot** [comment]
+1 
We actually use keycloak-gatekeeper/louketo for now. We use the `addClaims` options to add jwt claims onto the upstream headers wich are used by istio for dynamic routing.

We definitively need this fonctionnality to be able to migrate to Oauth2-proxy.

**Comment by loicoudot** [comment]
This is the last feature that is missing to use oauth2-proxy with istio for dynamic routing.

**Comment by JoelSpeed** [comment]
Just to let you all know, the current plan is to get #826 merged (reviews welcomed) and then create a new PR to add `--alpha-config` which allows users to use the new structured configuration for headers and upstreams that we have been working on recently. Hopefully we can get this merged in the next month or two.

Then it will be a case of a user setting up a file with their header values like:
```
injectRequestHeaders:
- name: "WHATEVER_YOU_WANT_FOR_STATIC_VALUE"
  values:
  - value: <Some B64 encoded string>
- name: "SOME_VALUE_FROM_SESSION"
  values:
  - claim: "email"
```

**Comment by loicoudot** [comment]
Good job 👍

**Comment by kfox1111** [comment]
how close is this now?

**Comment by JoelSpeed** [comment]
Everything code wise is merged, so can be used with our new alpha config options. The only thing that is missing is the documentation for the new alpha configuration which I am hoping to work on over the next week or so

**Comment by kfox1111** [comment]
Awesome. Thanks. :)

Should I close this now or would you rather wait for the docs to merge first?

**Comment by JoelSpeed** [comment]
We can leave open until the docs are merged to make sure we cover this use case

**Comment by shalin-hudda** [comment]
@JoelSpeed great work here, I am looking forward to using this feature, is it available in master? Also, are the docs merged?

**Comment by JoelSpeed** [comment]
Everything is available on master except from documentation, which I'm working on in #903, Perhaps you could take the docs for a spin and see if you can work it out? (Note, we are documenting the fields and the format for the configuration but not specific uses at the moment)

**Comment by Hadsch** [comment]
Is there a plan for when these features will move from the "alpha" version to the official version?

**Comment by JoelSpeed** [comment]
Currently there isn't a plan, I had hoped to create a v8 once we had finalised the entire structured config, but it's not really making progress right now as myself and the other maintainers haven't the time to work on it.

We could look into moving some parts to a non-alpha but it's going to create more toil in the long term

**Comment by redboxstudio** [comment]
> Просто чтобы вы знали: текущий план состоит в том, чтобы объединить #826 (обзоры приветствуются), а затем создать новый PR для добавления `--alpha-config`, который позволит пользователям использовать новую структурированную конфигурацию для заголовков и восходящих потоков, над которой мы недавно работали. Надеюсь, мы сможем объединить это в ближайшие месяц или два.
> 
> Тогда это будет случай, когда пользователь настраивает файл со значениями заголовка, например:
> 
> ```
> injectRequestHeaders:
> - name: "WHATEVER_YOU_WANT_FOR_STATIC_VALUE"
>   values:
>   - value: <Some B64 encoded string>
> - name: "SOME_VALUE_FROM_SESSION"
>   values:
>   - claim: "email"
> ```
Hi, I didn't find a usage description in thread 903. I built a master branch but the custom claim functionality doesn't work. or does this only work for injectRequestHeaders
 i did so
injectionResponseHeaders:
- name: MY_HEADER
  values:
  - value: MY_CLAIM

Or maybe my mistake is that it is necessary to specify the claim value in base64 ?

**Comment by redboxstudio** [comment]
> Just to let you all know, the current plan is to get #826 merged (reviews welcomed) and then create a new PR to add `--alpha-config` which allows users to use the new structured configuration for headers and upstreams that we have been working on recently. Hopefully we can get this merged in the next month or two.
> 
> Then it will be a case of a user setting up a file with their header values like:
> 
> ```
> injectRequestHeaders:
> - name: "WHATEVER_YOU_WANT_FOR_STATIC_VALUE"
>   values:
>   - value: <Some B64 encoded string>
> - name: "SOME_VALUE_FROM_SESSION"
>   values:
>   - claim: "email"
> ```

Hi, I didn't find a usage description in thread 903. I built a master branch but the custom claim functionality doesn't work. or does this only work for injectRequestHeaders
i did so
injectionResponseHeaders:

name: MY_HEADER
values:
value: MY_CLAIM
Or maybe my mistake is that it is necessary to specify the claim value in base64 ?

**Comment by JoelSpeed** [comment]
Custom claims isn't implemented, currently it only works for claims that are supported in the session already. There's a switch case somewhere within the code that shows which are supported
