### ISSUE TITLE
Guidance request on "failed to verify id token signature" in OIDC setup

### ISSUE THREAD

**Issue by demurray** [oauth2-proxy/oauth2-proxy#633]
## Expected Behavior

We would like our `oauth2-proxy` that is configured against an in-house Okta as an OIDC provider to properly issue cookies and redirect users. It had been working before and then started to fail when attempting to redeem a code for an oauth token.

oauth2-proxy, the same setup as issue https://github.com/oauth2-proxy/oauth2-proxy/issues/64, is configured as follows:

```
        - --http-address=0.0.0.0:4180
        - --cookie-httponly=false
        - --cookie-refresh=1h
        - --cookie-secure=false
        - --email-domain=nike.com
        - --oidc-issuer-url=https://nike.okta.com
        - --provider=oidc
        - --set-xauthrequest=true
        - --skip-provider-button=false
        - --whitelist-domain=.nikecloud.com,.nike.com
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
       (client secret and cookie secret configured via env vars)
```

## Current Behavior

After we are redirected to a page with message "Authenticate using @nike.com" and button "Sign in with OpenID Connect" and we click to log in, we are redirected to a page with "500 Internal Error". The logs for oauth2-proxy are as follows:

```
[2020/06/24 18:59:34] [oauthproxy.go:263] mapping path "/dev/null" => file system "/dev/null"
[2020/06/24 18:59:34] [oauthproxy.go:291] OAuthProxy configured for OpenID Connect Client ID: nike.niketech.epdam-operations
[2020/06/24 18:59:34] [oauthproxy.go:297] Cookie settings: name:_oauth2_proxy secure(https):false httponly:false expiry:168h0m0s domains: path:/ samesite: refresh:after 1h0m0s
[2020/06/24 18:59:34] [http.go:58] HTTP: listening on 0.0.0.0:4180
[2020/06/24 19:00:01] [oauthproxy.go:910] Error loading cookied session: cookie "_oauth2_proxy" not present
172.30.253.21:44198 - - [2020/06/24 19:00:01] dmur13.epdam-test.nikecloud.com GET - "/oauth2/auth" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36" 401 21 0.000
172.30.253.21:44200 - - [2020/06/24 19:00:01] dmur13.epdam-test.nikecloud.com GET - "/oauth2/sign_in" HTTP/1.0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36" 200 2686 0.000
172.30.251.211:49038 - - [2020/06/24 19:00:04] dmur13.epdam-test.nikecloud.com GET - "/oauth2/start?rd=%2Falerts%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36" 302 325 0.000
[2020/06/24 19:00:05] [oauthproxy.go:796] Error redeeming code during OAuth2 callback: could not verify id_token: failed to verify signature: failed to verify id token signature
172.30.251.211:49038 - - [2020/06/24 19:00:04] dmur13.epdam-test.nikecloud.com GET - "/oauth2/callback?code=SuCWNaHtxiIhwOLrTTlv&state=d9f8101c08e022eccc98180b3cc95518%3A%2Falerts%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36" 500 331 0.287
```

## Possible Solution

We do not suspect an issue with oauth2-proxy, since a similar error redeeming the code is observed on multiple versions, but are looking for guidance about how to debug further and/or what might have caused this issue to start to occur.

- Version used:

We are on 3.3.0, but have reproduced on 5.1.0 and :latest as of 6/24/2020.

**Comment by JoelSpeed** [comment]
It sounds like potentially you have an issue with the length of your key rotation on your identity provider. When OAuth2 Proxy is verifying the claim, it fetches the JWKS from the identity provider to check the signature, if the key that was used to sign the token has been rotated out already, then the verification will fail. Do you happen to know if you've set the key rotation to a smallish value within Okta?

**Comment by demurray** [comment]
Thanks @JoelSpeed. This does not appear to be the issue: our keys change infrequently, and we were not at the point where we had a token with a signature to check, since the code was not redeemed successfully.

We did identify the problem, which was that our `oidc-issuer-url` was set to `https://nike.okta.com`, such that a code was retrieved from a default server, but attempted to be redeemed from a different auth server. Specifying a server explicitly, as:

```
--oidc-issuer-url=https://nike.okta.com/oauth2/<id-of-server>
```

did the trick.
