### ISSUE TITLE
Specifying alternative provider TLS trust source(s) from command line or config.

### ISSUE THREAD

**Issue by k-wall** [oauth2-proxy/oauth2-proxy#635]
For my use-case, the OIDC provider in use may use a server-cert signed by private CA that may not be trusted by the default SystemCertPool.

It is possible to specify the `SSL_CERT_DIR` environment variable, as this currently supports only a single directory, it means you need to use a script to centralise all the required trust (upstream, provider) into a single directory.    This works but is inconvenient, especially if the trust is projected from config maps in the Kubernetes world.  

## Expected Behavior

It'd be useful is the oauthproxy accepted additional trust source(s) perhaps from a command line/conig option,`--cacert`  (borrowing arg name from from cURL) to specify an additional file(s) to add to the pool.

## Current Behavior

As described above

## Possible Solution

As described above

## Steps to Reproduce (for bugs)

-
## Your Environment

- Version used:

**Comment by k-wall** [comment]
I'd could put together a PR, if a patch along these lines sounds useful..

**Comment by JoelSpeed** [comment]
I think I'd prefer to have an option such as `provider_ca_file` that is expected to be a path to the provider's ca bundle file, this would then be used only in requests to the provider, how does that sound? You can also use the `ssl_insecure_skip_verify` option for the moment as an insecure workaround, but would be good to support self signed certs

**Comment by k-wall** [comment]
> I think I'd prefer to have an option such as `provider_ca_file` that is expected to be a path to the provider's ca bundle file, this would then be used only in requests to the provider, how does that sound? You can also use the `ssl_insecure_skip_verify` option for the moment as an insecure workaround, but would be good to support self signed certs

@JoelSpeed  Thanks for the reply. Yeah - that'd suite my use-case.  For the upstream trust, relying of SSL_CERT_DIR is sufficient, so an argument that supplemented the provider's trust would work.  I'll try putting together a PR.
