### ISSUE TITLE
pass_user_bearer_token = false broken

### ISSUE THREAD

**Issue by kfox1111** [oauth2-proxy/oauth2-proxy#640]
I use:
    pass_user_bearer_token = false
In the config for some stable/oaut2-proxy instances. When upgrading, its saying its not an option anymore. Just laving it out doesnt' work though as its still having the = true behavior. Was this option renamed?

**Comment by NickMeves** [comment]
Are you looking for this option to pass the user's IDToken to the backend in an `Authorization: Bearer <TOKEN>` header?

```
--pass-authorization-header | bool | pass OIDC IDToken to upstream via Authorization Bearer header | false
```

**Comment by ploxiln** [comment]
oauth2-proxy used to not error-out on unrecognized options in the config, that is a recent-ish change, see https://github.com/oauth2-proxy/oauth2-proxy/issues/500 (I think that `pass_user_bearer_token` was never exactly a real option)

**Comment by JoelSpeed** [comment]
Agreed, I don't think that was ever an option, are you seeing headers passed that you don't want? What headers are they?

**Comment by kfox1111** [comment]
I thought I needed it for one deployment. Its possible it never worked, yeah.

I'll test without it and still if it works with the newer version. I'll reopen if I run into issues. Thanks!
