### ISSUE TITLE
Cannot find package "github.com/go-redis/redis/v7" on go get

### ISSUE THREAD

**Issue by linuxgemini** [oauth2-proxy/oauth2-proxy#642]
The command `go get github.com/oauth2-proxy/oauth2-proxy` fails with a "not found" error.

## Expected Behavior

```
root@crane:~# go get github.com/oauth2-proxy/oauth2-proxy
root@crane:~#
```

## Current Behavior

```
root@crane:~# go get github.com/oauth2-proxy/oauth2-proxy

package github.com/go-redis/redis/v7: cannot find package "github.com/go-redis/redis/v7" in any of:
        /usr/local/go/src/github.com/go-redis/redis/v7 (from $GOROOT)
        /root/Projects/Uno/src/github.com/go-redis/redis/v7 (from $GOPATH)
root@crane:~#
```

## Possible Solution

I didn't come up with one.

## Steps to Reproduce (for bugs)

`go get github.com/oauth2-proxy/oauth2-proxy`

## Context

The v6.0.0 release does not have assets available.

## Your Environment

```
root@crane:~# go version
go version go1.14.1 linux/amd64

root@crane:~# uname -a
Linux crane 4.4.0-184-generic #214-Ubuntu SMP Thu Jun 4 10:14:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

root@crane:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

**Comment by JoelSpeed** [comment]
Release assets have now been added, apologies for the delay. Docker images are coming shortly.

Not sure why there is an issue doing go get, that shouldn't happen 🤔 Need to work that one out

**Comment by JoelSpeed** [comment]
Go-redis requires module support [1], so try `GO111MODULE=on go get github.com/oauth2-proxy/oauth2-proxy` and you may get it working

[1]: https://github.com/go-redis/redis#installation

**Comment by linuxgemini** [comment]
Alright that worked, I forgot that env very quickly (like I used it literally yesterday for the gitlab-group PR).

I think this should be mentioned on README.

**Comment by silcowitz** [comment]
Sorry for the confusion here, I realize that I most likely did get the latest version using the command
`# GO111MODULE=on go get github.com/oauth2-proxy/oauth2-proxy`

Anyway, it would be great if the output of `oauth2-proxy --version` would provide the real version number or maybe the git rev. used, or at least in the HTML displayed when it's running (here it also says undefined, so it could cast doubt on whether it's running a vulnerable, outdated version or not)

Thanks anyway,
Morten

**Comment by JoelSpeed** [comment]
@silcowitz The version is injected by the build target in our makefile. If you use `make build` to build the binary, you will see a proper version number with git information if it is an untagged commit.

**Comment by silcowitz** [comment]
@JoelSpeed Thanks I'll try that
