### ISSUE TITLE
Inconsistent flag unknown flag: --cookie-domains

### ISSUE THREAD

**Issue by shinebayar-g** [oauth2-proxy/oauth2-proxy#643]
## Expected Behavior

Command line flag works same as env or config line option.

## Current Behavior

I've read the **v6.0.0** release notes. 

> Allow multiple cookie domains to be specified
> Multiple cookie domains may now be configured. The longest domain that matches will be used.
> The config options cookie_domain is now cookie_domains
> The environment variable OAUTH2_PROXY_COOKIE_DOMAIN is now OAUTH2_PROXY_COOKIE_DOMAINS

Looks like `cookie_domain` config line or `OAUTH2_PROXY_COOKIE_DOMAIN` env is changed to `cookie_domains` & `OAUTH2_PROXY_COOKIE_DOMAINS` respectively. But `--cookie-domain=` command line flag isn't updated. It gives `unknown flag: --cookie-domains` error. Does it mean `--cookie-domain` flag will work same as `cookie_domains` config line or it'll work same as in **v5.1.1**? I know it's not biggy, just wanted to this behaviour exists in new version :)

## Possible Solution

Consistent env, command line flag, config file options.

## Steps to Reproduce (for bugs)

1. start oauth2-proxy with `--cookie-domains=.auth.example.com`

## Your Environment

- Version used: v6.0.0

**Comment by ploxiln** [comment]
Yes, `--cookie-domain` is compatible with how it worked in v5.1.1, but now you can also, specify multiple, e.g. `./oauth2-proxy --cookie-domain=first.com --cookie-domain=second.com ...` (which is why the command-line flag uses the singular form, while the config file now has the plural form, this is similar to a few existing options)

**Comment by shinebayar-g** [comment]
Ah that makes sense. Never knew I had to use the option like that.

**Comment by JoelSpeed** [comment]
I think this can be closed right?
