### ISSUE TITLE
Header too large

### ISSUE THREAD

**Issue by GregoireW** [oauth2-proxy/oauth2-proxy#644]
With oauth2-proxy v6.0.0  I got an error on my upstream "Header is too large: size 8193>8192". 

## Expected Behavior

This error is linked to "oauth2-proxy_x" cookies. Those header are only intended for oauth2-proxy and in my opinion should not be transferred to the back-end.

Or at least there should be an option to activate / deactivate this token to be sent to back-end.

## Steps to Reproduce (for bugs)

You need to have a token that is big enough to trigger the cookie split ( WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead. )

**Comment by NickMeves** [comment]
I'm attempting to address the large cookie session sizes here: https://github.com/oauth2-proxy/oauth2-proxy/pull/632

Do you think a smaller cookie size suffices? Or are you thinking we need a full session cookie strip before the backend? I think that has been asked for as well, I just can't find an existing Issue or PR -- so maybe I imagined it 🤔

**Comment by GregoireW** [comment]
I checked existing issue, so I hope you imagined the issue asking to strip the session cookies  ( else it means I also have  an issue with my eyes :D ) 

In my use case, the id_token is quite large. So I guess it is why I had 2 cookies, the second one was around 7500 bytes. Even with LZ4, I will bet one day or the other a payload will break data in 2 cookies.   

I think it is best to strip the session cookie as it is not use by the backend, no need to overload applications with something they will never use. 

Anyway, in my usecase, I added a redis cache, not really secured (who cares if it restart, people will get authenticated automatically ) it reduce a lot the cookie size so people will not transfer 15kb of data just to get a 1kb data page ;)  (HTTP/2 help a lot, but a smaller cookie is cleaner for me)

**Comment by NickMeves** [comment]
> In my use case, the id_token is quite large. So I guess it is why I had 2 cookies, the second one was around 7500 bytes. Even with LZ4, I will bet one day or the other a payload will break data in 2 cookies.

The second cookie alone was 7500? I would've thought we split into as many as needed to keep the value of the cookie under 3840 bytes. If that isn't getting you to 3, 4, etc cookies I think I need to look at that logic more.

> Anyway, in my usecase, I added a redis cache, not really secured (who cares if it restart, people will get authenticated automatically ) it reduce a lot the cookie size so people will not transfer 15kb of data just to get a 1kb data page ;) (HTTP/2 help a lot, but a smaller cookie is cleaner for me)

DB based sessions have a unique session key + encryption key in the session cookie portion.  So the data in the DB isn't decryptable with DB access alone (you'd need the user's session cookie). So you can rest a little easier even if the redis DB isn't secured to your liking that the sessions are decently safe from stealing + user spoofing.

**Comment by GregoireW** [comment]
Ok thank you. For the cookie size, i'm not quite sure about the size, I notice the 2nd one was perhaps 500 byte shorter than the first one, I was thinking the 1st cookie was 8kb but I did not check so perhaps it was 3840 and 3300 byte

**Comment by johejo** [comment]
related https://github.com/oauth2-proxy/oauth2-proxy/issues/482

**Comment by BrianHuf** [comment]
In my case, `--session-cookie-minimal true` resulted in `id_token claim for header "Authorization" requires oauth tokens in sessions. session_cookie_minimal cannot be set`

I was able to avoid the `WARNING: Multiple cookies are required...` issue by adding `--scope openid email` (no `profile`)

**Comment by JoelSpeed** [comment]
If you are seeing split cookies, our recommendation is to switch to using redis for the session storage

**Comment by GuyPaddock** [comment]
With the Azure AD provider, the solution @BrianHuf worked! We used both `--session-cookie-minimal true` and `--scope openid email` and were able to fix the size error with cookies.

**Comment by Bhautik0110** [comment]
@JoelSpeed I have the same error HTTP 431 when `pass_authorization_header=true`. If I set it to `false` it works as expected. I didn't understand why this is happening because the upstream server header capacity size is greater than 4kb and oauth2 proxy should be responsible to pass requests to the upstream server.

**Comment by JoelSpeed** [comment]
Your authorization header, depending on the provider, could be huge, what does your backend set the capacity to? Have you tried making it say 32kb and seeing if that suffices? Have you inspected the OAuth2 Proxy cookies to see how many cookies they split into?

**Comment by mcrapts** [comment]
When enabling FMA with Azure AD the cookies grew too large for me. Increasing the proxy buffer size didn't work (don't know why).
The definitive fix for me was to use Redis for session storage. If this might sound scary to you - it's not. You can spin up a Redis instance with zero configuration and use all the defaults, then configure oauth2-proxy as follows:
1. Set `--session-type` or ` OAUTH2_PROXY_SESSION_STORE_TYPE` to: `redis`
2. Set `--redis-connection-url` or `OAUTH2_PROXY_REDIS_CONNECTION_URL` to: `redis://<redis_hostname>`

**Comment by munkyjunky** [comment]
For anyone coming across this issue using the Helm chart, the solution for me was to switch to Redis for session storage as @mcrapts has posted above. In the Helm chart, this was update `values.yml` with the following:
```yml
redis:
  enabled: true
sessionStorage:
  type: redis
```

**Comment by edemen** [comment]
I am still getting `431 Request Header Fields Too Large` using latest helm installation and using a redis store.
Anything else I could try?

**Comment by taladar** [comment]
I think the problem is actually the csrf Cookies for failed attempts to redirect background requests (like API ones) to the OIDC provider for a login. Those accumulate and the Cookie Header grows larger and larger.

**Comment by sw506** [comment]
> I think the problem is actually the csrf Cookies for failed attempts to redirect background requests (like API ones) to the OIDC provider for a login. Those accumulate and the Cookie Header grows larger and larger.
At least in standalone mode you should be able to mitigate this with the api_routes directive. But unfortunately, in reverse proxy mode the directive doesn't do anything as always 401 is returned when unauthenticated

**Comment by sw506** [comment]
I was able to emulate the api_routes behaviour in nginx:
below
` error_page 401 =301 /oauth2/sign_in;
`
add
`   if ($request_uri ~ "^/(rest|api|favicon.ico)" ) {
    error_page 401 = @ret_401;
  }`
and in server block
`        location @ret_401 {
           return 401;
        }`
