### ISSUE TITLE
Blocked by CORS

### ISSUE THREAD

**Issue by cccs-cat001** [oauth2-proxy/oauth2-proxy#647]
When my app hits the oauth2-proxy for the manifest.json, I get the following error: 
```
Access to manifest at 'https://<auth-url>/oauth2/start?rd=%2F<url>%2Fmanifest.json' (redirected from 'https://<url>/manifest.json') from origin 'https://<url>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Is there a way to add the origin to the access control list? I don't see a parameter I can set...

## Your Environment

- Version used: I believe I'm using 6.0.0, but it was definitely happening in 5.1.1. 
oauth2-proxy is running in a container on a kubernetes cluster. The app that's trying to access it is as well in a container on the kubernetes cluster (two different namespaces though but that shouldn't matter). They both have the same dns zone, one is auth.<dns-zone> and the other is app.<dns zone>

**Comment by JoelSpeed** [comment]
I don't think we have any CORS support, how are you running the proxy? On it's own or with something like nginx doing a subrequest for the authentication?

**Comment by cccs-cat001** [comment]
Wasn't an oauth issue at all.

**Comment by HashiBeliver** [comment]
how did you solve this issue?

**Comment by cccs-cat001** [comment]
I didn't, it just wasn't an issue lol

**Comment by boomaker** [comment]
FYI I solved the issue with activating CORS on the Ingress with the annotation:

`nginx.ingress.kubernetes.io/enable-cors: true`

**Comment by alexrandaccio** [comment]
I am getting blocked by CORS and I don't understand this, so if someone could help me out I would really appreciate it--

I am running an app in docker with the oauth2-proxy image. I want to use the oauth2-proxy image to authorize users with github. So I redirect users to /oauth2/sign_in. Then when I try to access the user's profile from the client app with a request to the oauth2-proxy server at /oauth2/userinfo, I get blocked by CORS. The whole reason I am using oauth2-proxy is to get around CORS issues when authorizing with github. So how do I make /oauth2/userinfo work?

**Comment by sfl-andrej** [comment]
For those who came across this issue and didn't find the solution yet. 

I solved this issue by adding `crossorigin="use_credentials"` to manifest link:
```html
<link rel="manifest" href="/manifest.json" crossorigin="use-credentials">
```

@marcinjahn I know it is little bit too late, but adding cors to oauth2-proxy ingress doesn't really help because manifest is not served by oauth2-proxy. It should be added to service that exposes manifest.json.

**Comment by aaktaev** [comment]
Thank you, @sfl-andrej !

It worked for me!

**Comment by tram98** [comment]
> For those who came across this issue and didn't find the solution yet.
> 
> I solved this issue by adding `crossorigin="use_credentials"` to manifest link:
> 
> <link rel="manifest" href="/manifest.json" crossorigin="use-credentials">
> [@marcinjahn](https://github.com/marcinjahn) I know it is little bit too late, but adding cors to oauth2-proxy ingress doesn't really help because manifest is not served by oauth2-proxy. It should be added to service that exposes manifest.json.

You're a legend! Thank you so much, random person on the internet, to help me solve my problem 😊 

It may make sense to add a note in the docs of oauth2-proxy that points to this solution.
