### ISSUE TITLE
Does GAP-Signature functionality work? Any existing users?

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#648]
Our `signature-key` option provides a way to HMAC sign canonical headers in that case where a protected backend is across the internet from the oauth2-proxy and the user wanted to protect against spoofing `X-Forwarded-*` user headers or `Authorization` headers from requests with unverifiable authenticity (since the oauth-proxy is across the internet and not local)

https://github.com/oauth2-proxy/oauth2-proxy/blob/4313553122358912a52a88403dbc2bfba0081277/oauthproxy.go#L47

But one of the included canonical headers (`GAP-Auth`) is an internal header that is never passed to the backend.  So any backends that might want to use this can't validate the signed header.

https://github.com/oauth2-proxy/oauth2-proxy/blob/4313553122358912a52a88403dbc2bfba0081277/logging_handler.go#L50

## Expected Behavior

All headers we sign for the signature are present on the backend request.

## Current Behavior

GAP-Auth isn't a verifiable header.  I wonder if anyone has ever used this successfully?

## Possible Solution

We rip it out and deprecate it since there seems to be no demand.

OR

We cleanup the headers we consider the canonical headers in the signature.

Additionally, as our X-Forwarded-* user headers might become more variable in the future, we might want to send a second header specifying which headers are the canonical headers for HMAC auth. I believe this is what DKIM does for email headers for its signing (albeit with pub/priv key signing via public keys in DNS TXT records).

Is there an analogous header/format for signed headers in HTTP like DKIM for email?

**Comment by NickMeves** [comment]
Those code hasn't really been touched in 5 years.  Here's the original bitly issue: https://github.com/bitly/oauth2_proxy/issues/146

**Comment by ploxiln** [comment]
I think it still works. The "GAP-Auth" header is copied from the _response_ being prepped to the _request_ to the upstream, before the logging removes that header (which happens after the upstream responds):

https://github.com/oauth2-proxy/oauth2-proxy/blob/v6.0.0/oauthproxy.go#L135-L137

```go
func (u *UpstreamProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("GAP-Upstream-Address", u.upstream)
	if u.auth != nil {
		r.Header.Set("GAP-Auth", w.Header().Get("GAP-Auth"))
		u.auth.SignRequest(r)
	}
...
```

Is it really useful to anyone, I don't know.

**Comment by NickMeves** [comment]
Does the logging handler delete it with all the other `GAP` headers though (the second snippet above)? I'll need to check again, I don't think I've seen any GAP headers when I do dummy tests with httpbin.

**Comment by NickMeves** [comment]
Nevermind -- ignore me 😄   I just needed to set the `signature-key` appropriately.  I see it now.

I guess my question errors more toward the second part then: is this used, and do we want to be more dynamic about why headers we use as canonical headers?

**Comment by JoelSpeed** [comment]
My 2 cents is that the list of signature headers should include any that we are setting as part of the proxy, so if we implement the more flexible header implementation that has been suggested a few times, we will probably want this list to be dynamic with that

**Comment by NickMeves** [comment]
We will tackle this at some point.

**Comment by JoelSpeed** [comment]
I wonder, given the lack of activity on this issue, should we consider deprecating this feature?

**Comment by NickMeves** [comment]
That has my vote 😄 

What do you think, small PR in v7 to make a warning in `validation` if we see this setting set with an important note in the CHANGELOG?  Then aim to completely remove it in v8?

**Comment by JoelSpeed** [comment]
> What do you think, small PR in v7 to make a warning in validation if we see this setting set with an important note in the CHANGELOG? Then aim to completely remove it in v8?

This seems reasonable to me yeah

**Comment by iCreateJB** [comment]
I'm actually having trouble getting this to work after specifying the`--signature-key`.

I'm expecting the `GAP-Auth` header to be present but I'm not seeing it. Has there been any other issues around this or perhaps am I missing a flag ?

I am seeing a `_oauth_proxy` cookie but I don't think that's part of it. 

```
/oauth2-proxy  \
  --cookie-secure=false \
  --cookie-secret=${COOKIE_SECRET} \
  --client-id=${CLIENT_ID} \
  --client-secret=${CLIENT_SECRET} \
  --email-domain=${EMAIL_DOMAIN} \
  --provider=${PROVIDER} \
  --provider-display-name=${PROVIDER_NAME} \
  --redirect-url=${REDIRECT_URL} \
  --oidc-issuer-url=${OIDC_ISSUER_URL} \
  --http-address="http://0.0.0.0:4180" \
  --set-xauthrequest=true  \
  --signature-key=${SIGNATURE_KEY} \
  --set-authorization-header=true \
  --reverse-proxy=true
  ```
  cc @NickMeves
