### ISSUE TITLE
Keycloak provider does not honor --set-authorization-header option

### ISSUE THREAD

**Issue by sushiMix** [oauth2-proxy/oauth2-proxy#651]
When using OIDC provider with --set-authorization-header option the authorization header is returned when calling /oauth2/auth whereas with Keycloak provider it does not (I also set --x-auth-request=true).

## Expected Behavior
--set-authorization-header works with set-authorization-header
the call to /oauth2/auth shall return the Authorization header with bearer token

## Current Behavior
It does not return the authorization header

## Possible Solution

1. update Keycloak implementation 
2. Add group claim support in OIDC provider so no need to keep Keycloak provider. 

## Steps to Reproduce (for bugs)

Create a configuration with Keycloak provider and --set-authorization-header==true

1. login using sign_in api
2. call auth api
## Context

I'd like to use Keycloak provider to support the Keycloak group management (which is not supported in OIDC provider).
Passing back to OIDC provider requires to add a component to handle the group management.

## Your Environment

Use in kubernetes context with Nginx ingress controller and x-auth-request=true.

- Version used: 5.1.1 and 6.0.0

**Comment by JoelSpeed** [comment]
This is a known issue, the keycloak provider doesn't store the ID Token so it can't set it in the header. You could try switching over to the OIDC provider instead as that is known to work with keycloak

You may be interested in #479

**Comment by sushiMix** [comment]
I already switched to OIDC Provider but I lost the group claim (which ease the user management).
In fact I need :  #466 to support the group claim token with auth_request and set-authorization-header to fully solve the issue

**Comment by JoelSpeed** [comment]
Ahh, I believe #466 isn't likely to be completed any time soon, but we are making progress on the groups issue in #616, would that PR resolve your issue?

**Comment by sushiMix** [comment]
Hello, #616 can solve my issue.
