### ISSUE TITLE
500 Error When Using OIDC and Azure AD (After Authentication)

### ISSUE THREAD

**Issue by AMoghrabi** [oauth2-proxy/oauth2-proxy#652]
## Expected Behavior

Hello,

I am hoping I can get some help configuring the oauth2-proxy to use oidc so I can authenticate using to the kubernetes-dashboard and Azure AD single sign-on. I have tried looking for similar issues and related documentation but unfortunately I'm stumped.

I have the following configured on my oauth2-proxy (I'm using the helm chart):

```
     provider: oidc
     upstream: "file:///dev/null"
     http-address: "0.0.0.0:4180"
     oidc-issuer-url: https://sts.windows.net/<tenant_id>/
```

I also have NGINX annotations configured on my dashboard ingress:

```        
kubernetes.io/ingress.class: nginx
nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=https://$escaped_request_uri"
nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
```

I am expecting (or at this point, praying, lol) that it would authenticate me to the dashboard.

## Current Behavior

Upon authenticating with Azure, I receive the following in the logs of the proxy:

```
Error redeeming code during OAuth2 callback: unable to update session: couldn't extract claims from id_token (&{%!e(string=id_token did not contain an email)})
```

I am not exactly sure how to solve this. I do apologize, I am a bit new to OAuth and OIDC. I would really appreciate your help!

## Your Environment

- Kubernetes 1.17.7
oauth2-proxy version: 5.1.0

**Comment by JoelSpeed** [comment]
I'm not familiar with the helm chart, but what you will likely need to look at is the `scope` parameter, it should include probably `openid email profile`, but I'm not sure what they default it to. If `email` is present in the scope, then Azure should return a token with the email present. Hopefully that points you in the right direction.

Also, I would like to recommend updating to the latest version of the project, there have been a couple of security disclosures since v5.1.0

**Comment by AMoghrabi** [comment]
Thanks a lot Joel :) I was actually able to get an alternative going. I have oauth-proxy working for our other dashboards without using oidc. Works perfectly.

Thanks again :)

**Comment by letsbringachange** [comment]
@AMoghrabi i am stuck at the same point as you with azure OIDC for Kubernetes dashboard - "couldn't extract claims from id_token", even though the redirect URL shows '&scope=openid+email+profile'

If i change the provider to "azure" authentication works, but i dont see authorization header being passed to kubernetes dashboard. Can you share how you went past this issue / the alternate solution?

**Comment by AMoghrabi** [comment]
Hey @letsbringachange , unfortunately I was not able to get it going with `oauth2-proxy`. Instead I am using the following image: `quay.io/gambol99/keycloak-proxy:v2.2.1`

If you plan to use this image as your proxy and need some help configuring it, let me know. 

My other dashboard that use this oauth2-proxy is Grafana. That doesn't seem to have any issues, but the again I don't think Grafana expects an id_token.

Good luck.
