### ISSUE TITLE
Miniredis session tests appear to leak file descriptors

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#653]
Now that we've added redis cluster tests in addition to standard and sentinel, we appear to have too many miniredis's trying to get going.  Without upping my `ulimit` past the default OSX setting of 256, I fail about 168 tests in of the 243 specs:

```
              Unexpected error:
                  <*net.OpError | 0xc000c90f00>: {
                      Op: "read",
                      Net: "tcp",
                      Source: {IP: [127, 0, 0, 1], Port: 65173, Zone: ""},
                      Addr: {IP: [127, 0, 0, 1], Port: 64908, Zone: ""},
                      Err: {},
                  }
                  read tcp 127.0.0.1:65173->127.0.0.1:64908: i/o timeout
              occurred
```

I even tried to reuse miniredis instances and ran `FlushAll` between specs, but then I eventually still got `socket: too many open files occurred` attempting to talk to the miniredis server.

## Expected Behavior

The tests work locally with sensible default system settings on most developers systems so they don't get tripped up by tests failing on the redis sessions.

## Current Behavior

Tests fail unless I run `ulimit -n 1024` to up my system resources limit.

## Possible Solution

I tried to reuse the same miniredis between all specs and flushed the redis data in between tests, but that didn't seem to fix the issue easily.  Still had issues with resources on the socket connections eventually at the same point.  So I'm out of quick and easy ideas.

I also tried to limit the max file descriptors with a buffered channel.  I couldn't get that to work well either.  I don't know how we get around systems being slow to release open file descriptors after a `miniredis.Close()` since they are likely sitting in a `TIME_WAIT` state or whatever it is for a bit of time afterwards.

## Steps to Reproduce (for bugs)

1.) ulimit -n 256
2.) go test ./...

**Comment by JoelSpeed** [comment]
I suspect actually this is a problem with the redis sentinel tests. I had some issues with them on my machine as well and in the end had to hack to get them to work. I think there are problems when minisentinel shuts down so we should probably look there first

**Comment by NickMeves** [comment]
I think its all redis tests because of the way it spins up a server on localhost and has a redis client speak to it.  I ditched all the sentinel & clusters tests and just did the standard tests in a loop 10 times.  Ran into the limit resource around the same point:

```
Ran 729 of 729 Specs in 0.454 seconds
FAIL! -- 254 Passed | 475 Failed | 0 Pending | 0 Skipped
--- FAIL: TestSessionStore (0.47s)
```

Since I also ran out of file descriptors when I tried reusing the same miniredis across all tests with DB flushes in between, my hunch is our issue is with the redis client itself in the session store, since a new one is spun up and grabs a new ephemeral port on its side of the TCP communication for every test.

When I tried using a channel to limit the new tests before an old test had closed, when I attempted to look at `mr.CurrentConnectionCount()` it always had 1.  Which I'm assuming is the client from the just finished spec. So maybe relying on standard garbage collection for each of those per spec is too delayed?

**Comment by NickMeves** [comment]
Related to sentinel:  I think this issue might've only really appeared because of the added cluster tests.  That pushed us over the 256 file descriptor edge to make it apparent with default Mac ulimit of 256. I wonder if this issue was always present even with the old test architecture, we just never exhausted our file descriptors?

**Comment by JoelSpeed** [comment]
I see, I've just pushed a branch with an idea of a fix for this on, do you think you could try it out? Seems to fix the issue based on my experimenting https://github.com/oauth2-proxy/oauth2-proxy/tree/redis-test-client-close

**Comment by NickMeves** [comment]
Looks like it fixed it for me too.  I even set the ulimit arbitrarily low and it still passed 👍 

Nice work!

```
$ ulimit -n 100

$ ulimit -n
100

$ go test
Running Suite: Redis SessionStore
=================================
Random Seed: 1593787816
Will run 243 of 243 specs

•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 243 of 243 Specs in 0.221 seconds
SUCCESS! -- 243 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok  	github.com/oauth2-proxy/oauth2-proxy/pkg/sessions/redis	3.335s
```

**Comment by JoelSpeed** [comment]
Awesome, PR is open and ready to go from my perspective if you have a minute to review it
