### ISSUE TITLE
[BUG] v6.0.0 - EXTRA_JWT_ISSUERS config no longer allows scheme on issuer URL

### ISSUE THREAD

**Issue by PaulCharlton** [oauth2-proxy/oauth2-proxy#655]
My old configuration had:

OAUTH2_PROXY_EXTRA_JWT_ISSUERS: "https://sts.windows.net/{tenant}/=https://management.core.windows.net/"

with v6.0.0 this now fails with 

```
[2020/07/04 00:20:19] [main.go:43] invalid configuration:
  error building verifiers: parse " https://sts.windows.net/{tenant}/.well-known/jwks.json": first path segment in URL cannot contain colon
```

workaround:
OAUTH2_PROXY_EXTRA_JWT_ISSUERS: "sts.windows.net/{tenant}/=https://management.core.windows.net/"

**Comment by JoelSpeed** [comment]
This is weird, I was just looking at the code, and nothing appears to have changed there in the last release, perhaps a dependency update has caused this but I don't think we've updated the relevant dependencies either

**Comment by PaulCharlton** [comment]
looks like it was specific to my build environment and updated modules in the oidc namespace.   The error message does not even exist in the Oauth2-proxy code base.   Definitely something to keep an eye on as external modules dependencies are updated.

**Comment by JoelSpeed** [comment]
Interesting, thanks for the heads up!

**Comment by oscarlofwenhamn** [comment]
Just ran into this problem for any cli-passed url; `--login-type`, `--redeem-url`, `--validate-url` `--redirect-url` all afflicted, in `latest` version of the image. When passing them from a config file, however, it works.

**Comment by dicolasi** [comment]
have exactly the same problem

**Comment by JoelSpeed** [comment]
I wonder if it's to do with that leading space, perhaps `--redeem-url=https://...` might work? Never did track down what changed here, could be an underlying Go library change

**Comment by iceman91176** [comment]
@dicolasi maybe you are runnign into the same problem i was experiencing ?

When passing args to the proxy you can't use parentheses 

This one fails 
<pre>
      containers:
      - args:
        - --provider=keycloak
        - --login-url="https://xxx/realms/yyyprotocol/openid-connect/auth"
        - ....
</pre>

but this one works

<pre>
      containers:
      - args:
        - --provider=keycloak
        - --login-url=https://xxx/realms/yyyprotocol/openid-connect/auth
        - ....
</pre>

I had to learn that parentheses are bad in **all** other parameters, too ;-) Especially in --scope. I you enclose the scopes in them, you get this one https://github.com/oauth2-proxy/oauth2-proxy/issues/847

When passing the parameters as ENV or from configfile, parentheses are fine.

**Comment by mabusaa** [comment]
It was a the tricky leading space that took me 30 min to find it. and that is the end of the story .
