### ISSUE TITLE
[FEATURE] add config options to determine contents of Oauth2-proxy cookie

### ISSUE THREAD

**Issue by PaulCharlton** [oauth2-proxy/oauth2-proxy#659]
Recent breaking changes to OAuth2-Proxy, especially in the azure provider, have exploded the size of the cookie from approximately 1kb to over 7kb, wreaking havoc with compatibility of both browser clients, front end servers, middleware servers,  and backend server configurations which were fine tuned to buffer http header sets smaller than 8kb.  Likewise having large encrypted cookies completely breaks header compression provided by http2 protocol.

The proposed workaround of "use the redis" state storage for oauth2-proxy is unavailable in many shops without substantial re-work of their infrastructures and operational management policies.

Performance of XHR transactions also suffers dramatically since many such API transactions tend to have small http request/response bodies, contrasted with the now large request/response headers.

This proposal is to categorize cookie contents on a spectrum from "required" for correct operation (AuthToken), to "nice-to-have" such as IdToken which may not be used by many back ends and has a lot of information redundant with the AuthToken.  Stated differently, there is AuthN data for consumption by machines, AuthN data for consumption by UI rendering, and AuthZ data for both machines and UI.  AuthN for UI, and all AuthZ information are generally not required for correct operation of front-end auth server.   With that categorization, have a configuration knob or collection of booleans to enable/disable various parts of the cookie content.

The secondary proposal is to restore the cookie to its previous size and behavior with a boolean config flag, defaulting to such value that is not a breaking change on the current code-base.

**Comment by PaulCharlton** [comment]
#632 another way to reduce session state ... compress it.

**Comment by JoelSpeed** [comment]
> Recent breaking changes to OAuth2-Proxy, especially in the azure provider, have exploded the size of the cookie from approximately 1kb to over 7kb, wreaking havoc with compatibility of both browser clients, front end servers, middleware servers, and backend server configurations which were fine tuned to buffer http header sets smaller than 8kb. Likewise having large encrypted cookies completely breaks header compression provided by http2 protocol.

I wasn't aware of any breaking changes in the Azure provider, though if we are now storing ID Tokens, that may explain the problem

> The proposed workaround of "use the redis" state storage for oauth2-proxy is unavailable in many shops without substantial re-work of their infrastructures and operational management policies.

We have been discussing other workarounds by implementing other session stores, is there a server side store implementation that you think would like to see? Please check out #482 

> This proposal is to categorize cookie contents on a spectrum from "required" for correct operation (AuthToken), to "nice-to-have" such as IdToken which may not be used by many back ends and has a lot of information redundant with the AuthToken. Stated differently, there is AuthN data for consumption by machines, AuthN data for consumption by UI rendering, and AuthZ data for both machines and UI. AuthN for UI, and all AuthZ information are generally not required for correct operation of front-end auth server. With that categorization, have a configuration knob or collection of booleans to enable/disable various parts of the cookie content.

I was discussing with @NickMeves on Thursday about having the ability for customising sessions (eventually) so that we have a minimal required set of claims that we store in the session, and then allow an additional claims section which allows users to specify which extra claims they would like us to be storing. We need to put together a decent design idea for this though as it will be a large change to the existing code base. If you're interested in helping with that, any help is greatly appreciated.

@NickMeves Is currently working through a bunch of improvements to the sessions to try and reduce the size of the cookies, so we are definitely aware of this issue

**Comment by PaulCharlton** [comment]
ps: I am available to create some code solutions, and I also see that there is already a lot of major refactoring in the works and I do not want to end up creating rework for those efforts.  Let's discuss how to achieve both gracefully.

**Comment by PaulCharlton** [comment]
the change to the azure provide came in with https://github.com/oauth2-proxy/oauth2-proxy/commit/c8a89eca0800ca64da09ab09f758d78b98bc974f, was part of the `v4.1.0` release, and added both the IdToken and the RefreshToken to the session state cookie.

**Comment by NickMeves** [comment]
After wrapping up the session encoding & compression work -- I'm curious to take a look at what exactly is going into the session & why.

The cause of the bloat is the Token trifecta (IDToken, Access Token, Refresh Token).  But I bit upon some analysis, we can figure out what flags cause an environment to need that specific token, and intelligently drop certain fields from sessions if they aren't needed.

IE

`--cookie-refresh` results in a Refresh Token being needed
`--pass-access-token` requiring the access token
`--pass-authorization-header` requiring the IDToken.

I'm sure there's more subtle interactions with flags that we can figure out with a bit of analysis.

**Comment by JoelSpeed** [comment]
Long term, @NickMeves and I had discussed making the whole session configurable with a set of basic claims, and then optional extra claims. This work would rely on us making some fairly major changes though, and should probably coincide with the structural config changes. So for now it looks like we should probably enable a quick fix to minimise the sessions, looks like @NickMeves is ahead of me on that though (#673)

**Comment by JoelSpeed** [comment]
We still want to do this

**Comment by PaulCharlton** [comment]
still needed

**Comment by NickMeves** [comment]
Is this still needed?

6.1.1 brought support for `lz4` compressed `msgpack` encoded cookies.  The average size has decreased by 50%  and I don't know if anyone is really hitting the cookie splitting (4kb) or 8kb header max thresholds anymore.

If they are, we also added support for a cookie minimal flag to not store the tokens, only the extracted User, Email, Groups, etc.

**Comment by PaulCharlton** [comment]
@NickMeves I will revisit this -- We've had http2 disabled on our WAF depending on the outcome of this issue.   In my mind, the minimal cookie still needs at least one JWT token (the Auth Token) or some other signed payload trusted by upstream internal services.  Unsigned naked user/email/groups would not cut it.

**Comment by NickMeves** [comment]
Give the full one a shot - they are much smaller now with the compression (always enabled, no opt out); see if that fixes your issue.  If you were at 7kb cookies, they'll likely go down to about ~4kb which is well under the 8kb header limits.

**Comment by therc** [comment]
For what it's worth: we want to use --cookie-refresh. With Cognito, even compression isn't enough and the state (IIRC, about 6KB) will be split across two cookies. We had to work around this by hacking the minimal cookies option to clear access and ID token as before, while leaving the refresh token alone. We can keep running our own fork for a while, but would rather stick with a permanent solution upstream.

**Comment by JoelSpeed** [comment]
The permanent solution to this would be to use a server side session store, currently your only option is redis, but I'm open to other implementations as long as they make sense. Any key value store could be used, I'd even stretch to someone using Kubernetes secrets to store the data if that would help folks out
