### ISSUE TITLE
Not redirecting correctly after login

### ISSUE THREAD

**Issue by diabda2** [oauth2-proxy/oauth2-proxy#664]
I am deploying auth2-proxy with Azure to SSO Kibana users, under kubernetes with helm.
I tried to follow this procedure : https://www.elastic.co/blog/user-impersonation-with-x-pack-integrating-third-party-auth-with-kibana
But I encounter an issue with auth2-proxy.

## Expected Behavior
Users use the url https://example.com/oauth2 to connect to Kibana
 => Will be authenticatied with Azure
Then redirected to https://example.com/app/kibana 
with header so Kibana allow the connection

## Current Behavior
User use the url https://example.com/oauth2 => Works
 => Will be authenticatied with Azure => Works

Once authenticated users are redirected to https://example.com and not to https://example.com/app/kibana
Is that the normal behavior? How I can go to https://example.com/app/kibana?

## My configuration
Oauth2:
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    kubernetes.io/proxy_set_header: Authorization "Basic MYBASIC64AUTH"
    kubernetes.io/proxy_set_header: es-security-runas-user $http_x_forwarded_user
    nginx.ingress.kubernetes.io/auth-signin: "https://example.com/oauth2/start?rd=https://example.com/app/kibana"
  path: /oauth2
  hosts:
    - example.com
  tls:
    - secretName: authproxy-oauth2-proxy
      servicePort: 80
      hosts:
        - example.com

config:
  clientID: "MYCLIENTID"
  clientSecret: "MYCLIENTSECRET"
  cookieSecret: "MYCOUCKIESECRET"
  cookie-domain: "example.com"
  cookie-name: "_oauth2_proxy"
  cookie-secure: false
  upstream : "file:///dev/null"
  configFile: |-
    redirect_url = "https://example.com/oauth2/callback"
    approval-prompt = "auto"

extraArgs:
  provider: azure
  azure-tenant: "AZURETENANTID"
  email-domain: "MYEMAILDOMAIN.com"
  whitelist-domain: "example.com"

@JoelSpeed , Please help.

**Comment by JoelSpeed** [comment]
Which version of the project are you using?

Are your users starting the flow at ` https://example.com/oauth2` as suggested in your description? They should be starting the flow where they want to be authenticated normally. Ie they would access `https://example.com/foo/bar`, you woudl set the auth-signin to `https://example.com/oauth2/start?rd=https://$host$uri` and then it will redirect them to `example.com/foo/bar` at the end

**Comment by Goodsmileduck** [comment]
if you need to set header to auth in kibana, try this kibana ingress config. Works for me with github oauth
note: it's not oauth ingress, but kibana ingress
replace `${basic_auth$` with your base64,
```
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=https://$host$request_uri"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Authorization "Basic ${basic_auth}";
        rewrite /login https://$host/oauth2/sign_in redirect;
```

**Comment by diabda2** [comment]
Thank you @JoelSpeed and @Goodsmileduck.

Sorry I was not working since months, and now I am back and saw that the topic is still needed and not done :)

@Goodsmileduck, I am trying Kibana + Oauth2 + Azure AD, could you please share more how you proceeded to make it work with GitHub?
In the meanwhile I will try what you recommended.

Thank you.

**Comment by Goodsmileduck** [comment]
So there only those annotations were required for kibana ingress. If you use Nginx ingress controller of course.
So I have 2 ingress with same domain but different paths locations
- kibana ingress routes for requests to /
- oauth ingress routes for requests to /oauth

**Comment by diabda2** [comment]
My Kibana ingress routes for requests to /analytics/app/Kibana, I couldn't change it because used by all users.
I need to change context /oauth? Or add something else?

Thank you

**Comment by Goodsmileduck** [comment]
@diabda2 that depends on you, you just need to have same path for oauth ingress and in github app settings. You could have a different domain name for oauth as well. But need to make sure you set your oauth url right on every side, and auth-signin redirect to right url where kibana exist.
just a note you can change variables to a real domains, that just nginx allows to use those variables
for example `nginx.ingress.kubernetes.io/auth-url: https://mydomain.com/oauth2/auth` etc

```
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=https://$host$request_uri"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Authorization "Basic ${basic_auth}";
        rewrite /login https://$host/oauth2/sign_in redirect;
```

**Comment by diabda2** [comment]
@Goodsmileduck, I would like to thank you for your help :)

It works partially, here my Kibana.yml (ingress part):

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=https://$host$request_uri"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Authorization "Basic XXXXXX";
        rewrite /login https://$host/oauth2/sign_in redirect;
  path: /analytics
  hosts:
    - mydomain.com
  tls:
    - secretName: kibana-tls
      hosts:
        - mydomain.com
…
kibanaConfig:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    server.basePath: "/analytics"
…

The behavior:
https://mydomain.com/analytics
=> Redirected to sign in
=> Sign in OK
=> Redirected to https://mydomain.com/#

Then try :
https://mydomain.com/analytics/app/Kibana => OK

So the issue is only the redirection to https://mydomain.com/analytics/app/Kibana 

Many thanks for your help ;)

**Comment by Goodsmileduck** [comment]
Good. Maybe you need to play with `nginx.ingress.kubernetes.io/auth-signin` annotation
in official nginx controller docs I saw 
```
nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
```
or maybe try
```
nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=https://$host/analytics"
```

**Comment by diabda2** [comment]
I tried already "...$host/analytics" but didn't work.

I just tried the below and it works perfectly!
nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"

@Goodsmileduck, Thank you very very much :)

**Comment by krupakar1329** [comment]
How to set this in a sidecar container
