### ISSUE TITLE
Redundant triming("=") when decode base64 encoded secret

### ISSUE THREAD

**Issue by wassan128** [oauth2-proxy/oauth2-proxy#665]
## Expected Behavior
In [pkg/encryption/utils.go](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/encryption/utils.go#L18), `TrimRight` has called to ignore "=" when decode secret. I think it is redundant because `base64.RawURLEncoding.DecodeString` omits "=" when decode without do anything by manualy.
https://golang.org/pkg/encoding/base64/#pkg-variables

Worse still, the trim process makes unnecessary byte. FYI: simple sample at go playground https://play.golang.org/p/13AvjH00c6x

## Current Behavior
As shown above

**Comment by JoelSpeed** [comment]
Looks like a valid deduction to me, CC @NickMeves as you've touched that recently, WDYT?

**Comment by ploxiln** [comment]
The extra byte with value `10` is because that is what you put in the base64 encoded value.

You wrote:
```go
enc := "YWJjCg=="  // base64 encode of "abc([97 98 99] in byte array)"
```

But that base64 encodes a newline char:

```python
# quick check using python for convenience
>>> base64.b64encode("abc".encode('utf-8'))
b'YWJj'
>>> base64.b64encode("abc\n".encode('utf-8'))
b'YWJjCg=='
```

**Comment by ploxiln** [comment]
(sorry, didn't see the discussion in the related PR)

**Comment by wassan128** [comment]
@ploxiln Thanks for your review. It was my misstake to encode with out no `-n` option when `echo`.
As I commented in #666 , I will close this issue and PR.
