### ISSUE TITLE
In proxy caching of authentication

### ISSUE THREAD

**Issue by JoelSpeed** [oauth2-proxy/oauth2-proxy#667]
## Expected Behavior

When lots of requests hit the proxy at the same time from the same user, we should only need to validate the credentials once.

Likewise, if a session needs to be refreshed, we should only attempt to refresh it once. If we try multiple times, we are likely to fail and force the user to log out.

## Current Behavior

We validate the session for each request which can lead to many requests to identity providers.
We refresh the same session concurrently which leads to users being logged out.

## Possible Solution

Implement some sort of caching and locking mechanism (maybe https://github.com/go-chi/stampede/ or https://pkg.go.dev/golang.org/x/sync/singleflight?tab=doc) so that when we load and validate a session, we only do it once concurrently for each user (which we can key from the cookie value if present)

Ensure that refreshes are synchronous and that the same session isn't being refreshed twice simultaneously by using singleflight.

Once this is done, we can re-enable the no-cache headers on the `/oauth2/auth` endpoint and users will be able to leverage in proxy caching rather than having to set this up in the likes of nginx

**Comment by NickMeves** [comment]
What are your thoughts for handling this in highly available environments? `singleflight` can protect us from a single node potentially spamming a refresh endpoint -- but what options do we have with parallel nodes (I imagine 3x is a likely common replica size to match AWS availability zones).

Do we somehow "prep" for an upcoming cookie-refresh a percentage of time before the expiration and set a cookie tagging some sort of node-id that is delegated to handle the refresh operation (so multiple nodes don't try to do it simultaneously)?  And other nodes would ignore until some percentage of time later we deem too long of it not hitting and force them to try refreshing?

**Comment by JoelSpeed** [comment]
We can't completely eradicate the problem using this solution, for that we would need to have the sessions locked in the session store (possible for server side), but this will give us some reduction at the least. When we've set up caching in Nginx before, we've also set up sticky sessions, so in theory, if all the requests can be sticky to the same OAuth2 Proxy backend, then that should minimise the conflicts, not a perfect solution, but a lot better than we have now I think

**Comment by NickMeves** [comment]
Agreed -- there's no 100% solution without a central locking store or sticky sessions in an HA environment to avoid contention.

I'm just curious what probabilistic algorithms we might have in our arsenal that could act as a greedy algorithm that might solve it 99% of the time natively in oauth2-proxy alone without requiring sticky sessions (they just scream 2000s LAMP stack to me, I'm not a fan if I can avoid them in modern HA architectures) or a disk (redis) lock store. Then some users can still opt for sticky sessions themselves if they want the 100% assurances of no contention but we do our best to support users who do simple HA.

For instance, maybe we use a variant of probabilistic counting algorithms to track backend node flow in the session. This way we count probilistically (ie 1% chance we up a counter by 100) to estimate counts/time per node -- but this way it doesn't result in a new set-cookie or redis save every request (only 1/100 requests).

Then, with details on client->backend flow ratios built into the session, we can intelligently attempt to elect a sole 'refresher' when the refresh time is about to expire.

**Comment by NickMeves** [comment]
This is the variant of the logarithmic counting algorithm Redis for instance uses to count up to 32/64 bit numbers in an 8bit space I was thinking of: http://antirez.com/news/109 

We'd use it more to save `set-cookie` or Redis `SET` session saves as our valuable resource rather than reducing counter bit increases to save disk space - but motivation would be similar if we ever wanted to embark on this type of heuristics tracking of HA nodes in the session itself.

**Comment by JoelSpeed** [comment]
In an ideal world, we would implement a form of lock so that if two threads try to update the session at the same time, one of them will fail and reload the newly updated session, eg like Kubernetes does with the resource version and 409 conflicts. Once we implement a K8s storage backend, that will be relatively easy to achieve. For redis, I'm not so sure, I guess we have to implement some sort of locking mechanism?

Frankly, the idea of having probabilistic algorithms for this implemented within the proxy scares me. I think we are potentially over-complicating the problem if we go that far down the rabbit hole, we may end up implementing more code to ensure we have atomic sessions than it takes to make the proxy work in the first place.

I think for server side stores, we can provide distributed locks based on the session storage, for cookie sessions, if people want the guarantees, they can use sticky sessions (which may help), or switch to server side storage once we have more options for them.

**Comment by NickMeves** [comment]
Was thinking about a potential design of a shared session cache/store that would've required a cluster bus: https://github.com/oauth2-proxy/oauth2-proxy/issues/482#issuecomment-658831910

I think there's potentially viable use cases for preventing refresh stampedes  using a cluster bus concept. We hash a session state and delegate its refresh management to a node in the cluster. Over the cluster bus, delegate the refresh operation to the hashed node over a subrequest so it is the sole requester & can manage contention internally with singleflight.
