### ISSUE TITLE
Support for ory hydra oauth2

### ISSUE THREAD

**Issue by salmanisd** [oauth2-proxy/oauth2-proxy#670]
Hello,

I am using the ory hydra as oauth provider (https://www.ory.sh/hydra/docs/). While its oauth flow works fine with my nodejs apps,I want to integrate it with nginx.

I am guessing oauth2-proxy is not going to work out of the box with it.? Can anyone tell me what I can do to maybe add support for hydra?

**Comment by JoelSpeed** [comment]
Hydra supports OIDC so you should be able to get started by using the OIDC provider and going from there. We have an example you may want to look at using Dex as an OIDC provider within the `contrib/local-environment` folder

**Comment by salmanisd** [comment]
Hi Joel,

Does this mean I can use the oidc.go provider as the generic option with my hydra server+werther identity provider?

I am a little confused because I see oauth2_proxy(also vouch_proxy) supporting different companies even though they all provide the same oauth standard but for oidc only one is required?

Thanks

**Comment by JoelSpeed** [comment]
Unfortunately, most of the providers are implementing some specific logic around a particular implementation of OAuth2, which for most of the providers has some very minor tweak.

The providers that duplicate that OIDC flow also have some minor tweaks as the companies aren't implementing the OIDC spec exactly as it is, the spec is open to interpretation after all, so again, we end up with minor differences.

You should try the OIDC provider first, as it is likely to work to some extent, but maybe Hydra also needs some minor tweaks.

**Comment by salmanisd** [comment]
thanks for the info...I will give OIDC a try...

**Comment by pommelinho** [comment]
@salmanisd  I also want to use my ory hydra implementation as oauth2/oidc provider.  Just want to check out if you were  able to integrated it with oauth2-prox?

**Comment by salmanisd** [comment]
@pommelinho yes hydra worked perfectly as an OIDC provider with oauth2-proxy.
