### ISSUE TITLE
Adjust `--skip-auth-strip-headers` and `--pass-basic-auth` defaults

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#677]
Since #624 is targeting a minor release, we're holding off on making the default values secure by default.

## Expected Behavior

Basic auth isn't passed by default & authentication headers are stripped in allowlisted non-auth routes by default (to prevent spoofing)

## Current Behavior

V6 behavior preserved, but is slightly more insecure by default.

## Possible Solution

Undo this commit: https://github.com/oauth2-proxy/oauth2-proxy/pull/624/commits/43a9bd69c5b672c5012ff0822eff880319ce33ec

**Comment by NickMeves** [comment]
Waiting for V7 to merge

**Comment by JoelSpeed** [comment]
@NickMeves I think this can be closed now?
