### ISSUE TITLE
sign_out endpont does not clear the splitted cookies on my end even though this bug was fixed in 2019

### ISSUE THREAD

**Issue by zhengyang1988** [oauth2-proxy/oauth2-proxy#681]
I find that the oauth2-proxy sign_out endpoint does not clear the splitted cookies. It only tries to clear the cookie with the key `_oauth2_proxy`

I saw there was a PR trying to solve this: #70 . But I don't know why the bug still exists 

## Expected Behavior
When a request with cookies `_oauth2_proxy_0`, `_oauth2_proxy_1` comes to the endpoint `/oauth2/sign_out` , these cookies should all be cleared by setting their values to be empty. 

## Current Behavior
You see in the image below, the request to the to `/oauth2/sign_out` carries two oauth2-proxy related cookies `_oauth2_proxy_0`, `_oauth2_proxy_1` , but the response tries to clear the cookie `_oauth2_proxy` which does not even exist.

![image](https://user-images.githubusercontent.com/5608908/87476501-7db61b00-c5f4-11ea-8327-8b8d7feff0f4.png)

## Your Environment

- Version used: 6.0.0

**Comment by JoelSpeed** [comment]
@NickMeves Do you think your recent changes to the cookie naming for large/split cookies might have affected this?

@zhengyang1988 Could you please tell us a little bit more about how you use the project, are you accessing it directly, through another proxy, via something like an auth request mode or external auth in nginx or envoy. This kind of information is very helpful for us when trying to debug issues like this

**Comment by NickMeves** [comment]
Hmm - in this particular case, I don't think my recent change would've affected this (and I think since this is v6, it doesn't have my change).

But it does bring to light a corner case I missed: https://github.com/oauth2-proxy/oauth2-proxy/blob/bb5977095faf0a033a5e01c67597641a7c6db38b/pkg/sessions/cookie/session_store.go#L75

That raw regex check won't find the super corner case cookies I handled where the length was near 256 (so the _\d part would've been truncated): https://github.com/oauth2-proxy/oauth2-proxy/blob/bb5977095faf0a033a5e01c67597641a7c6db38b/pkg/sessions/cookie/session_store.go#L198

**Comment by zhengyang1988** [comment]
Sorry, it's my fault. there is an envoy proxy in the gateway concatenating the cookie splits in the request into to one cookie named `_oauth2_proxy` before sending it to the sign_out endpoint. So the sign_out endpoint only get the `_oauth2_proxy` cookie. Thus it only clears that cookie.

But I really hope there is an bool option in the oauth2-proxy configuration to prevent oauth2-proxy splitting large cookies into multiple parts. So I don't need to write code to concatenate them.

**Comment by JoelSpeed** [comment]
I don't understand why you would want to be concatenating them again? They're are supposed to only be interacted with via the OAuth2 Proxy itself. If you concatenate them, they will be over the 4kb cookie limit and most browsers would drop them.

If you have large split cookies, I would suggest you move to a server side session store. We only have one implementation of this, Redis, presently, but we are looking to implement more (see #482)
