### ISSUE TITLE
proxy to oauth2_proxy to upstream

### ISSUE THREAD

**Issue by kfox1111** [oauth2-proxy/oauth2-proxy#684]
Say you setup a reverse proxy coming in at foo.com/mysite/ and it rewrites all traffic under that path to oauth2-proxy at /
This allows the upstream to not know that it is /mysite rather then just serving off of / simplifying configuration of the upstream.

Oauth2-proxy is not configurable enough in this environment, because it only has one setting ProxyPass, which it uses both for returning urls to the user to contact it back with, and for determining which url to match for oauth2 purposes.

In this config, the url returned to the user should look like:
/mysite/oauth2-proxy

while the url that should be pattern matched against for oauth2 purposes should be /oauth2-proxy

So there needs to be an option to specify the pattern matching prefix that is different from the urls returned to the user.

So we need something like:
ProxyPath = /mysite/oauth2-proxy
and
ProxyHttpPath = /oauth2-proxy
if ProxyHttpPath is not set, then it would just use ProxyPath.

I think then the only thing needed to be done is change:
https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L330-L336
to be ProxyHttpPath instead of ProxyPath?

**Comment by JoelSpeed** [comment]
Have you tried setting the `proxyPrefix` to `/mysite/oauth2`? If you did that and could prevent the rewrite in the upstream proxy for OAuth2 Proxy's path, this should provide a workaround I believe
