### ISSUE TITLE
Unable to set `username` when using Keycloak provider

### ISSUE THREAD

**Issue by aizzi** [oauth2-proxy/oauth2-proxy#686]
I am setting up the following environment:

User 
   |
Nginx
   |
Oauth2 <---> Keycloak
   |
Grafana

This is the `nginx` configuration (following the example [here](https://oauth2-proxy.github.io/oauth2-proxy/configuration)):

```
server {
        listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;

        ssl_certificate /etc/nginx/ssl/nginx_vas_cz.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx_vas_cz.key;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        location /grafana/ {
                auth_request /oauth2/auth;
                error_page 401 = /oauth2/sign_in;

                # pass information about the user to the backend
                # requires oauth2-proxy to run with --set-xauthrequest flag
                auth_request_set $user $upstream_http_x_auth_request_user;
                auth_request_set $email $upstream_http_x_auth_request_email;
                auth_request_set $name $upstream_http_x_auth_request_preferred_username;
                proxy_set_header X-Username $user;
                proxy_set_header X-Email $email;
                proxy_set_header X-Name $name;

                proxy_pass http://grafana.vas.cz:3000/;
        }

        location /oauth2/ {
                proxy_pass http://oauth.vas.cz:4180;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Scheme $scheme;
                proxy_set_header X-Auth-Request-Redirect $request_uri;
        }

        location = /oauth2/auth {
                proxy_pass http://oauth.vas.cz:4180;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Scheme $scheme;
                # nginx auth_request includes headers but not body
                proxy_set_header Content-Length "";
                proxy_pass_request_body off;
        }
}
```
When I access `https://nginx.vas.cz/grafana/`, I get redirected to Keycloak login page, perform the login and then sent to Grafana, but without login.

If I change `proxy_set_header X-Username $user;` to `proxy_set_header X-Username "<new user>";` (in other words I force the login user), the user gets created in Grafana with the following profile:

* Name = `<my email>`
* Email = `<my email>`
* Username = `<new user>`

which tells me that everything is correctly configured (or I will not be able to login).

According to your documentation, the `--set-xauthorequest` option should enable the following headers: `X-Auth-Request-User`, `X-Auth-Request-Email` and `X-Auth-Request-Preferred-Username`, so apparently the `X-Auth-Request-User` is not resolved.

This is the authentication result I get in the oauth2-proxy log:

```
[2020/07/17 14:10:45] [requests.go:26] 200 GET http://keycloak.vas.cz:8080/auth/realms/tutorial01/protocol/openid-connect/userinfo {"sub":"f4bb8645-f16f-4237-a9e4-58dea9e046f7","email_verified":false,"name":"<name surname>","groups":["/admin"],"preferred_username":"<username>","given_name":"<name>","family_name":"<surname>","email":"<email>"}
192.168.56.5:57446 - <email> [2020/07/17 14:10:45] [AuthSuccess] Authenticated via OAuth2: %!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)
[2020/07/17 14:10:45] [cookies.go:48] Warning: request host "nginx.vas.cz" did not match any of the specific cookie domains of ""
```
Keycloak is returning all the expected information from the user.

So, I tried a different test:

```
proxy_set_header X-Username "newuser";
proxy_set_header X-User-Email "email";
proxy_set_header X-User-Name "name";
```

and again the user gets created with 

* Name = "name"
* Email = "email"
* Username = "newuser"

Putting together the two tests:

`$upstream_http_x_auth_request_email` = `<email in KC>` OK

`$upstream_http_x_auth_request_preferred_username` = `<email in KC>`, which is wrong. Note how the "preferred_username" in KC reply is the "<username>", not the email.

`$upstream_http_x_auth_request_user` is resolved to `<email in KC>` too. To verify this, I made the following test:

```
proxy_set_header X-Username "new_user";
proxy_set_header X-User-Email $email;
proxy_set_header X-User-Name $user;
```

and I got the user created with "Name" = `"<email>"`.

This is my configuration for oauth2:

```
./oauth2/oauth2-proxy --provider=keycloak --client-id=oauth2 --client-secret=<secret> --login-url="http://keycloak.vas.cz:8080/auth/realms/tutorial01/protocol/openid-connect/auth" --redeem-url="http://keycloak.vas.cz:8080/auth/realms/tutorial01/protocol/openid-connect/token" --validate-url="http://keycloak.vas.cz:8080/auth/realms/tutorial01/protocol/openid-connect/userinfo" --keycloak-group=/admin --email-domain=* --cookie-secret=<secret> --http-address="http://192.168.56.8:4180" --scope=openid --set-xauthrequest=true
```

## Expected Behavior
`$upstream_http_x_auth_request_email` = `<email in KC>` OK

`$upstream_http_x_auth_request_preferred_username` = `<preferred username in KC>` i.e. the shortname uid

`$upstream_http_x_auth_request_user` = `<name surname>` i.e. the "name" filed in KC response.

## Current Behavior

Everything is apparently mapped to the user's email

**Update**: apparently, after further investigation, it seems that `$upstream_http_x_auth_request_preferred_username` and `$upstream_http_x_auth_request_user` are not returned at all.

## Steps to Reproduce (for bugs)

The above should be enough. Let me know if you need something more.

## Context

I'm setting authentication behind a authorization proxy.

## Your Environment

- Version used:
oauth2-proxy v6.0.0 (built with go1.14.2)

**Comment by JoelSpeed** [comment]
> 192.168.56.5:57446 - <email> [2020/07/17 14:10:45] [AuthSuccess] Authenticated via OAuth2: %!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)

This log line hints at a programming error within the construction of the keycloak provider, looks like this is some sort of internal bug that means we aren't setting some of the fields correctly.

The rest of your configuration looks ok from my initial scan. If you access `/oauth2/auth` what headers do you see returned?

**Comment by aizzi** [comment]
Is this what you are asking for?

```
>curl -v -L --insecure https://nginx.vas.cz/oauth2/auth
*   Trying 192.168.56.5...
* TCP_NODELAY set
* Connected to nginx.vas.cz (192.168.56.5) port 443 (#0)
* schannel: SSL/TLS connection with nginx.vas.cz port 443 (step 1/3)
* schannel: disabled server certificate revocation checks
* schannel: verifyhost setting prevents Schannel from comparing the supplied target name with the subject names in server certificates.
* schannel: sending initial handshake data: sending 168 bytes...
* schannel: sent initial handshake data: sent 168 bytes
* schannel: SSL/TLS connection with nginx.vas.cz port 443 (step 2/3)
* schannel: encrypted data got 1391
* schannel: encrypted data buffer: offset 1391 length 4096
* schannel: sending next handshake data: sending 93 bytes...
* schannel: SSL/TLS connection with nginx.vas.cz port 443 (step 2/3)
* schannel: encrypted data got 242
* schannel: encrypted data buffer: offset 242 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with nginx.vas.cz port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /oauth2/auth HTTP/1.1
> Host: nginx.vas.cz
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 368
* schannel: encrypted data buffer: offset 368 length 103424
* schannel: decrypted data length: 339
* schannel: decrypted data added: 339
* schannel: decrypted data cached: offset 339 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 339 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 339
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 401 Unauthorized
< Server: nginx/1.14.0 (Ubuntu)
< Date: Mon, 20 Jul 2020 14:36:07 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 21
< Connection: keep-alive
< Cache-Control: no-cache, no-store, must-revalidate, max-age=0
< Expires: Thu, 01 Jan 1970 00:00:00 UTC
< X-Content-Type-Options: nosniff
<
unauthorized request
* Connection #0 to host nginx.vas.cz left intact
```

**Comment by JoelSpeed** [comment]
We would need to see an authenticated request, so if you log in in the browser, then visit that URL, you should see a blank page. If you open your web browser developer tools you should be able to see the headers that are returned

**Comment by aizzi** [comment]
Sorry for the delay in answering. Here are the response headers I get:

HTTP/1.1 404 Not Found
Server: nginx/1.14.0 (Ubuntu)
Date: Tue, 28 Jul 2020 14:45:20 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 19
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Expires: Thu, 01 Jan 1970 00:00:00 UTC
X-Auth-Request-Email: <my correct email>
X-Auth-Request-User: 
X-Content-Type-Options: nosniff

**Comment by JoelSpeed** [comment]
I think there may be a bug within the Keycloak provider, it should be returning a username but your comment suggests that the username is empty. We need to look at where it is constructing the session and see why the username isn't being populated there.

**Comment by aizzi** [comment]
Should you be interested in the environment I used to reproduce, you can find it detailed [here](https://aizzi.github.io/tutorials/nkpg.html).

**Comment by hanswieheiri** [comment]
> 192.168.56.5:57446 -  [2020/07/17 14:10:45] [AuthSuccess] Authenticated via OAuth2: %!s(PANIC=String method: runtime 

I get the same error and have the same problem

**Comment by captnbp** [comment]
I have the same issue with the following setup:

User
|
Ingress Nginx
|
Oauth2 <---> Keycloak 11.0.1
|
Rundeck 

Username and `x-forwarded-user` are always empty with provider keycloak. 
I also had to create a specific client scope in keycloak named "api" to avoid the following blocking error : `Invalid scope: api`

If I use Gitlab/OIDC providers, username is filled.
I tried with v6.1.1 and `stefansedich:group-claim` fork

**Comment by JoelSpeed** [comment]
The panic issue should be resolved as of v6.1.1. If you upgrade to this version the session information should print correctly which will allow us to see which parts of the session are populated which I believe will help to narrow down the issue

**Comment by oscarlofwenhamn** [comment]
I'm also affected by this situation, and would be happy to help out in troubleshooting if given some guidance in what you need to see to narrow it down. It is a quite limiting bug for us, so I'm happy to give it much attention to keep an active discussion.

**Comment by oscarlofwenhamn** [comment]
As per request above, the following headers are returned at `.../oauth2/auth`. Does the keycloak provider-settings only look at the headers and ignore the data in the `x-auth-request-access-token`?

```
content-length: 0
date: Fri, 09 Oct 2020 14:40:32 GMT
server: nginx/1.17.10
status: 202
strict-transport-security: max-age=15724800; includeSubDomains
x-auth-request-access-token:  {correct jwt containing correct claims, username, etc}
x-auth-request-email: email@domain.com
x-auth-request-user: 
```

In my case, for troubleshooting, I am running with `pass_access_token = true`, but no `X-Forwarded-Access-Token` is set despite this. 
I have an instance of `mendhak/http-https-echo` set up which echoes all headers sent to the page, which when set up behind the oatuth2-proxy imho should include more than just the `x-auth-request-email` when it comes to user data, but this is all that is set.

**Comment by oscarlofwenhamn** [comment]
FTR: Using `provider=oidc` to connect to Keycloak results in both Email and Preferred Username being passed into the headers. This could be a possible workaround for @aizzi if this issue is still relevant.

**Comment by JoelSpeed** [comment]
It looks as though the keycloak provider isn't filling in the details from the session as required, the header extraction should be agnostic of the provider assuming they have filled the session correctly

**Comment by oscarlofwenhamn** [comment]
> keycloak provider
I.e. the external Keycloak instance, or the oauth2-proxy keycloak "interface", for lack of a better word?

What are the required details that should be filled by the keycloak provider? 
I could maybe look into establishing some sort of listener between oauth2-proxy and Keycloak to log what is being set where. Alternatively, we could reach out to the Keycloak team with a bug report, so we can verify the details are being set correctly.

**Comment by JoelSpeed** [comment]
> I.e. the external Keycloak instance, or the oauth2-proxy keycloak "interface", for lack of a better word?

The oauth2-proxy keycloak interface

To enable this, the session needs the fields filling in when it is created, I would recommend taking a look at how this is done in the OIDC provider for guidance

**Comment by oscarlofwenhamn** [comment]
Cheers, will do when I get the chance.

**Comment by insanemal** [comment]
Please reopen. This is still happening.

if I log in and go to oauth2/userinfo I get

```
{
"user": "",
"email": "correct@email.com",
"groups": [
"valid",
"yup",
"works",
"youknowit",
"somegroup"
]
}
```

This is kinda huge and breaking

**Comment by insanemal** [comment]
Still an issue.

**Comment by insanemal** [comment]
Still an issue....

**Comment by mccallumjeff** [comment]
still an issue.

**Comment by insanemal** [comment]
Yep still borked

**Comment by oscarlofwenhamn** [comment]
Very much assuming this is still an issue?

**Comment by prein** [comment]
If I go to `oauth2/userinfo` I am getting
```
{
"user":"00u5m1caot35SRiTe4i9",
"email":"me@foo.io",
"preferredUsername":"me@foo.io"
}
```
which is different from what @insanemal is getting, is seemingly random string in `user` field, and `groups` missing

**Comment by babs** [comment]
It seems that kc provider doesn't retain `user` and `preferred-username` in session.
I've opened a bug (#1813) and the related PR (#1815) for that matter.
