### ISSUE TITLE
support for Add -bypass-auth-except-for to protect only paths matched by a regex

### ISSUE THREAD

**Issue by r-kotagudem** [oauth2-proxy/oauth2-proxy#691]
@JoelSpeed 

currently we have --skip-auth-regex to specify paths which needs to be skipped. which says protect all except ones configured in 
-skip-auth-regex 

Required functionality
Bydefault do not apply auth to all paths. 
apply authentication to only specific paths(like allowedpaths) which are configured.
this would be useful.please let me know if there is such an option already.

want to acheive below:
included urls: (if empty applies auth to all paths)
included urls:  prefix: /productpage (apply only to /productpage/*)
excluded urls: /productpage/static files

**Comment by JoelSpeed** [comment]
Could you not achieve this by writing a negative regex using the `--skip-auth-regex` pattern.

@NickMeves This makes me think about the behaviour  of `Deny` within the request authorization that we've been discussing, should it block the request, or request the user to authenticate? Is there a third policy to consider?

**Comment by NickMeves** [comment]
I think Deny should definitely still be a hard block (no fallback to auth like missing all allow rules) - IE for IP denylist scenarios.

In my last draft I did add this `NoOpPolicy` that at the moment I was just using as an internal fallthrough from an unmatched rule when traversing a whole ruleset:

https://github.com/oauth2-proxy/oauth2-proxy/pull/685/files#diff-69783d8f229cbcc31a890fc3c014ea4eR6

Could potentially have something like an `Auth` policy that breaks out of the rules chains and forces auth at that point (and doesn't let a later Allow/Deny force those code paths)

**Comment by r-kotagudem** [comment]
> Could you not achieve this by writing a negative regex using the `--skip-auth-regex` pattern.
> 
> @NickMeves This makes me think about the behaviour of `Deny` within the request authorization that we've been discussing, should it block the request, or request the user to authenticate? Is there a third policy to consider?

Thanks for reply
It seems golang re is limited in negative lookaheads and doesn't support expression like below
^((?!path).)*$

Can you suggest an expression negating the path match

**Comment by JoelSpeed** [comment]
> It seems golang re is limited in negative lookaheads and doesn't support expression like below
^((?!path).)*$

Ahh that is a good point, I'm not sure entirely on the specifics of this tbh with you.

If you have a large number of paths you don't want to protect and then a subset that you do, have you considered using something like nginx as the main proxy and setting OAuth2 Proxy in auth_request mode for the paths you do want to be protected? I imagine that would likely be easier to resolve.

> Could potentially have something like an Auth policy that breaks out of the rules chains and forces auth at that point (and doesn't let a later Allow/Deny force those code paths)

That's a potential, but it feels a bit weird to me, I think you're right on `Deny` should be deny though, I wonder how many use cases there are for a third option of force auth for this set of conditions, that's kind of the default normally isn't it.

I guess we could consider expanding the regex part of the work we are doing to make it a list of regexs and have an operator for the regex matches? eg `AllOf`, `AnyOf`, `NoneOf` etc

**Comment by NickMeves** [comment]
> I guess we could consider expanding the regex part of the work we are doing to make it a list of regexs and have an operator for the regex matches? eg `AllOf`, `AnyOf`, `NoneOf` etc

In the future state, I think we would want to keep the `path` portion of the authorization rule simple.  But we could get this functionality by adding the `AuthPolicy` we talked about.

Then people in this scenario would add `AuthPolicy` rules higher in the chain for the few routes they want to auth (I've done this before IE only protecting a backend session API route on an app). Then at the end they have an `AllowPolicy` on `.*` path.

**Comment by r-kotagudem** [comment]
> Ahh that is a good point, I'm not sure entirely on the specifics of this tbh with you.
> 
> If you have a large number of paths you don't want to protect and then a subset that you do, have you considered using something like nginx as the main proxy and setting OAuth2 Proxy in auth_request mode for the paths you do want to be protected? I imagine that would likely be easier to resolve.
> 

We are using envoy proxy as gateway here, tried per route config for ex_authz filter(which call oauth2-proxy), but that doesnt work in the istio 1.6. Will try again.
thanks for your support.

**Comment by r-kotagudem** [comment]
> > I guess we could consider expanding the regex part of the work we are doing to make it a list of regexs and have an operator for the regex matches? eg `AllOf`, `AnyOf`, `NoneOf` etc
> 
> In the future state, I think we would want to keep the `path` portion of the authorization rule simple. But we could get this functionality by adding the `AuthPolicy` we talked about.
> 
> Then people in this scenario would add `AuthPolicy` rules higher in the chain for the few routes they want to auth (I've done this before IE only protecting a backend session login API route on an app). Then at the end they have an `AllowPolicy` on `.*` path.

Hi @NickMeves 
Is this functionality to add allowed paths/policy going to be available in next release? We have are stuck with lack of this option for our cluster.

**Comment by r-kotagudem** [comment]
> > > I guess we could consider expanding the regex part of the work we are doing to make it a list of regexs and have an operator for the regex matches? eg `AllOf`, `AnyOf`, `NoneOf` etc
> > 
> > 
> > In the future state, I think we would want to keep the `path` portion of the authorization rule simple. But we could get this functionality by adding the `AuthPolicy` we talked about.
> > Then people in this scenario would add `AuthPolicy` rules higher in the chain for the few routes they want to auth (I've done this before IE only protecting a backend session login API route on an app). Then at the end they have an `AllowPolicy` on `.*` path.
> 
> Hi @NickMeves
> Is this functionality to add allowed paths/policy going to be available in next release? We have are stuck with lack of this option for our cluster.

thanks

**Comment by lino-layani-ssq** [comment]
Hi, I encounter the same issue here. @r-kotagudem did you find any workaround other that fronting oauth2proxy by a nginx proxy ?

**Comment by kacifer** [comment]
Now `--skip-auth-regex` supports NOT operator, for example `GET!=path_regex` or `!=path_regex`
