### ISSUE TITLE
Keycloak provider does not verify group membership

### ISSUE THREAD

**Issue by carrot-hub** [oauth2-proxy/oauth2-proxy#693]
## Current Behavior
Let's say I have one Keycloak server and I have two groups created (**user** and **admin**).
I have a user X assigned only to group **user**.

I have site A which is secured by oauth2-proxy, configured to only provide access to users that are part of **user** group.
I have site B which is secured by another oauth2-proxy, configured to only provide access to users that are part of **admin** group.

Now if user X goes to site A (and is successfully authorized), and then goes to site B with cookie being set from previous step, the user is allowed to access site B as well (even though user X is not member of **admin** group).

If I clear the cookies and go straight to site B, I get 403 which is correct behavior.

## Expected Behavior
User X is declined by site B at all times.

## Possible Solution
It seems that group membership is being checked only if cookie is not present in the request.

## Context
Both proxies from the scenario above verify same users in same Keycloak but require different group membership.
Both proxies use same cookie name.

### Oauth2-proxy for site A:
```
 containers:
  - args:
    - --provider=keycloak
    - --email-domain=*
    - --upstream=file:///dev/null
    - --http-address=0.0.0.0:4180
    - --login-url=https://my.domain.com/auth/realms/authentication/protocol/openid-connect/auth
    - --redeem-url=https://my.domain.com/auth/realms/authentication/protocol/openid-connect/token
    - --validate-url=https://my.domain.com/auth/realms/authentication/protocol/openid-connect/userinfo
    - --whitelist-domain=.my.domain.com
    - --cookie-domain=.my.domain.com
    - --oidc-issuer-url=https://my.domain.com/auth/realms/authentication
    - --keycloak-group=/user
    - --cookie-name=keycloak
    - --proxy-prefix=/first-oauth2
```

### Oauth2-proxy for site B:
```
 containers:
  - args:
    - --provider=keycloak
    - --email-domain=*
    - --upstream=file:///dev/null
    - --http-address=0.0.0.0:4180
    - --login-url=https://my.domain.com/auth/realms/authentication/protocol/openid-connect/auth
    - --redeem-url=https://my.domain.com/auth/realms/authentication/protocol/openid-connect/token
    - --validate-url=https://my.domain.com/auth/realms/authentication/protocol/openid-connect/userinfo
    - --whitelist-domain=.my.domain.com
    - --cookie-domain=.my.domain.com
    - --oidc-issuer-url=https://my.domain.com/auth/realms/authentication
    - --keycloak-group=/admin
    - --cookie-name=keycloak
    - --proxy-prefix=/second-oauth2
```

## Your Environment
Kubernetes version: 1.18.5
Keycloak version: jboss/keycloak:10.0.2
Proxy version: quay.io/oauth2-proxy/oauth2-proxy:v6.0.0

**Comment by kfox1111** [comment]
A workaround for now would be to use a different cookie name and cookie secret per instance.

**Comment by JoelSpeed** [comment]
@NickMeves and I have been discussing this recently during some refactoring work. We are planning to add some generic request authorization that will be performed on each request  once the session is loaded. That should allow you to set the restrictions you need.

In the mean time, the workaround @kfox1111 will get you started. You may also be interested in #616 which might help with the issue
