### ISSUE TITLE
Handle/Ignore Basic Auth

### ISSUE THREAD

**Issue by dev-cr-ka** [oauth2-proxy/oauth2-proxy#697]
How can I use oauth2-proxy for OIDC authN of user, but keep Basic Auth for machine authentication?

## Question

I have set up oauth2-proxy with Istio EnvoyFilter. Every unauthenticated request is redirected to my IDP (Azure AD). User can login and is redirected to my app. Thanks for your great app and easy setup!

There is a REST endpoint where another application sends POST requests to the application. The request has an Authorization Header with Basic Auth Credentials.

The question is: 
Do we have to refactor the app to send an Authorization Header with AzureAD token or can we accept the Basic Auth Header somehow?

Please let me know if you need further information. Thanks in advance.

## Your Environment

- Kubernetes 1.15 
- Istio 1.6 
- Redis:Alpine latest
- AzureAD

- Version used:
Latest

**Comment by NickMeves** [comment]
Hey there,

I think you have a couple of potential options depending on your security requirements to support human + machine users concurrently.

1.) Use the `--htpasswd-file` option to create single factor accounts. Passwords/Api Keys can be setup in with SHA1 or Bcrypt format. If this option is enabled, it will be added to the session middleware chain and for machine users it will create a session of just the `User`. ...I haven't used this myself, but I think this should work looking at the code?

2.) (This is what I do to support humans + machines users securely) - Use the `--extra-jwt-issuers` flag to specify additional OIDC providers that can validate a JWT with a JWKS. You can use projected service account tokens feature of K8s to get auto-refreshing JWTs mounted to volumes in your pods: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection

The tricky part is getting a viable OIDC `/.well-known/openid-configuration` & `/.well-known/jwks.json` files to verify JWTs issued by K8s.  AWS IRSA uses this technique and there's a few tutorials floating around on setting this up outside of AWS EKS (we just care about the service account private key => JWKS part): https://medium.com/getamis/aws-irsa-for-self-hosted-kubernetes-e045564494af

**Comment by NickMeves** [comment]
And a third option I've seen -- if your backend only needs machine users to access a few select routes, you can use `--skip-auth-regex` to skip authentication on those requests and manage the API authentication yourself in your backend application.

**Comment by dev-cr-ka** [comment]
Thanks mate, it's just one route, so I guess I'll go with option 3 👍
