### ISSUE TITLE
Which OAuth Flows are supported?

### ISSUE THREAD

**Issue by steffakasid** [oauth2-proxy/oauth2-proxy#698]
Hi,

I searched regarding any information of supported OAuth Flows? As I want to use the oauth2-proxy together with m2m communication can you tell me if the client-credential flow (https://auth0.com/docs/flows/concepts/client-credentials) is supported?

Regards
Steffen

**Comment by JoelSpeed** [comment]
We don't support machine logins, only user logins, however, if you have a third party OIDC issuer who can grant your machine's with tokens, we can verify the tokens using the `--skip-jwt-bearer-token` option, so you can allow m2m to access the resources but you will need to generate their credentials using something else

**Comment by steffakasid** [comment]
Hi @JoelSpeed,

thanks for your reply.

Regards
Steffen
