### ISSUE TITLE
`trusted-ip` should be `trusted-ips`

### ISSUE THREAD

**Issue by ghostsquad** [oauth2-proxy/oauth2-proxy#702]
`TrustedIPs         []string `flag:"trusted-ip" cfg:"trusted_ips"``

The flag name does not follow the convention in the documentation, such that if it's a list or allows a list, it's "plural". Additionally, the flag name is different from the `cfg` name, which is just confusing.

- Version used: v6.0.0

**Comment by JoelSpeed** [comment]
The option is in fact correct and fits the convention across the options.

From the docs:

> Every command line argument can be specified in a config file by replacing hypens (-) with underscores (_). If the argument can be specified multiple times, the config option should be plural (trailing s).

This is meant to mean that if a flag option (eg `--trusted-ip`) can be set multiple times (eg `--trusted-ip=1.2.3.4 --trusted-ip=5.6.7.8`, then when it is in the config file, which is toml based, it should be a list there and have a trailing `s`, (eg `trusted_ips=["1.2.3.4", "5.6.7.8"]`

You can see the pattern in other flags too such as `upstream`, `whitelist-domain`, etc

> Additionally, the flag name is different from the cfg name, which is just confusing.

I 100% agree that it is very confusing! But it is a convention that predates me joining the project that we decided to carry on until we overhaul the configuration and make it structured (see #532). We are hoping to get this done within the next few months and get this overhaul into `v7`

**Comment by ghostsquad** [comment]
Thanks for the detailed explanation. Hopefully this will serve to help others should they run into the same confusion.
