### ISSUE TITLE
release notes about cookie-domain invalid?

### ISSUE THREAD

**Issue by ghostsquad** [oauth2-proxy/oauth2-proxy#703]
The release says the `cookie-domain` is now `cookie-domains` (s) but that seems incorrect.

> #412/#559 Allow multiple cookie domains to be specified

    Multiple cookie domains may now be configured. The longest domain that matches will be used.
    The config options cookie_domain is now cookie_domains
    The environment variable OAUTH2_PROXY_COOKIE_DOMAIN is now OAUTH2_PROXY_COOKIE_DOMAINS

https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v6.0.0?ts=4

The documentation doesn't reflect that, and also the app:

```
unknown flag: --cookie-domains
```

- Version used: v6.0.0

**Comment by JoelSpeed** [comment]
This is the same as #702, everything there is actually correct, though confusing. The flag has remained as `--cookie-domain`, the config file options is `cookie_domains` and the environment option is `OAUTH2_PROXY_COOKIE_DOMAINS` .
