### ISSUE TITLE
OIDC: JWT Bearer Passthrough fails to validate Token

### ISSUE THREAD

**Issue by suhrm1** [oauth2-proxy/oauth2-proxy#709]
## Expected Behavior

1. client retrieves valid Access Token from _OpenID Provider_
2. client accesses Oauth2-proxy with HTTP request containing `Authorization: Bearer {access token}` header
3. Oauth2-proxy validates Token and proxies request to upstream

## Current Behavior

1. see above
2. see above
3. Oauth2-proxy cannot validate the access token

Log message:

```
[oauthproxy.go:901] Error retrieving session from token in Authorization header: unable to verify jwt token Bearer eyJhbGciOiJS...
```

I have verified the token against the `/userinfo` endpoint of the _OpenID Provider_.

Normal OIDC flow works like a charm, only the `skip_jwt_bearer_tokens` directive does not seem to work as expected.

## Possible Solution

I would primarily require help to further debug the current behaviour.

## Context

I am currently testing Oauth2-proxy as a generic solution for protecting REST API resources; ultimately, clients will be machines more often than human users meaning that Token-based authentication & authorization is the primary feature required. 

## Your Environment

I'm running a `docker-compose` set-up with `jwilder/nginx-proxy` and Let's encrypt reverse proxy combo in front of the `oauth2-proxy` Docker container; Redis container and upstream webserver container are part of the same Docker network. See [docker-compose.yml](https://gist.github.com/suhrm1/46a6ca9272eda220ef5f01db4663afa2)

`oauth2-proxy.cnf` file contains the following:

```
http_address = "0.0.0.0:8080"

## The OAuth Client ID, Secret
client_id = "..."
client_secret = "..."

provider = "oidc"
oidc_issuer_url = "https://keycloak.sso.gwdg.de/auth/realms/academiccloud"
redirect_url = "https://vm17020.virt.gwdg.de/oauth2/callback"
email_domains = [
    "*"
]
reverse_proxy = true

cookie_name = "_oauth2_proxy"
cookie_secret = "..."
cookie_domains = "vm17020.virt.gwdg.de"
cookie_expire = "168h"
cookie_secure = true
cookie_httponly = false

session_store_type = "redis"
redis_connection_url = "redis://redis"

skip_jwt_bearer_tokens = true
```

I also tested with the additional `oidc_jwks_url = "https://keycloak.sso.gwdg.de/auth/realms/academiccloud/protocol/openid-connect/certs"` in the configuration file which did not change the outcome.

- Version used: 6.0.0 Docker image

**Comment by NickMeves** [comment]
This error potentially giving more details is shadowed at the moment in v6.0.0 😢 : https://github.com/oauth2-proxy/oauth2-proxy/blob/d9af3ffc5ec0daf4f198100e80175f07de5d2208/oauthproxy.go#L1147

But this usually fails when the OIDC Provider library Verifier.Verify method has issues.  Usual culprit is the issuer/audience in the Bearer IDToken JWT doesn't match the issuer/audience the OIDC Provider Verifier builds from the `client_id` + `oidc_issuer_url`.

Does that all line up?

**Comment by NickMeves** [comment]
Oh `Access Token` 🤔 

The OIDC Provider Verifier library is usually looking for the IDToken in the `Verify` method -- maybe that's the issue?

**Comment by NickMeves** [comment]
FYI - v6.0.0 currently has a bug if the IDToken you submit doesn't have an email address claim (IE machine users) AND you only verify those bearer JWTs via the primary OIDC issuer/client details (not via an `--extra-jwt-issuers`) you will run into issues unless you explicity set `--user-id-claim` to `subject` (it's a weirdly named flag, its really talking about the Email session field...)

This PR I want to get in v6.1.0 looks to fix that: https://github.com/oauth2-proxy/oauth2-proxy/pull/700

**Comment by suhrm1** [comment]
Thank you for the suggestions. I guess it is actually and ID Token, not Access Token. Still new to the whole OIDC business. But the Token payload decodes to what I looks more like an ID Token to my eyes:

```
{
  "jti": "5b61042d-109e-4a03-9c4e-83c019fc836b",
  "exp": 1596463816,
  "nbf": 0,
  "iat": 1596463516,
  "iss": "https://keycloak.sso.gwdg.de/auth/realms/academiccloud",
  "aud": "account",
  "sub": "5ceff674-810b-476a-8fcc-f5a76870ff5e",
  "typ": "Bearer",
  "azp": "{client_id}",
  "auth_time": 1596463516,
  "session_state": "f09e37c9-d84d-4512-9a10-048cb7679d76",
  "acr": "1",
  "allowed-origins": [
    "https://vm17020.virt.gwdg.de"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "profile goeId email",
  "uid": "{username}",
  "email_verified": true,
  "goe_id": "{internal account id}",
  "name": "{firstname lastname}",
  "preferred_username": "{internal account id}",
  "given_name": "{firstname}",
  "family_name": "{lastname}",
  "email": "{email address}"
}
```
But if I got your meaning in your [first comment](#issuecomment-669647154), `iss` and `aud` claims must be the same as `client_id` and `oidc_issuer_url` configuration parameters? Even if it's not respectively (`iss` and `oidc_issuer_url` are a match in this case), `aud` and `client_id` are entirely different.

**Comment by NickMeves** [comment]
Use this field -- you can add as many iss=aud pairs as you'd like:

```
--extra-jwt-issuers | string | if --skip-jwt-bearer-tokens is set, a list of extra JWT issuer=audience pairs (where the issuer URL has a .well-known/openid-configuration or a .well-known/jwks.json) |
```

**Comment by suhrm1** [comment]
Yes, I got it to work like that. I added the following to my config file:
```extra_jwt_issuers = "https://keycloak.sso.gwdg.de/auth/realms/academiccloud=account"```
i.e. `"{iss}={aud}"` as were provided by the ID Token.

 Thank you very much!
