### ISSUE TITLE
Adding support for groups in Azure Active Directory

### ISSUE THREAD

**Issue by jeremych1000** [oauth2-proxy/oauth2-proxy#71]
Hi :)

Currently I'm using oauth2-proxy in putting tools and applications behind Azure AD integration. It works very well, thanks.

However, there is currently no option to get groups from AD, and pass this in a header back onto the tools and applications to do RBAC.

There is an open pull request on the old fork - any chance we can get this reviewed and merged?

https://github.com/bitly/oauth2_proxy/pull/347

## Expected Behavior
Upon successful auth from Azure AD, I should get a list of groups the user is in, in AD. This list of groups should be put in a header, that can then be passed back upstream.

From the above pull request, 
> `pass-groups` flag to enable an additional X-Forwarded-Groups header that contains a pipe-separated list of groups to which the user belongs.

## Current Behavior
There is no way to pass group information upstream.

## Possible Solution
Review and merge https://github.com/bitly/oauth2_proxy/pull/347

## Steps to Reproduce (for bugs)
1. Configure oauth2-proxy to talk to Azure AD
2. Check there is no group information in the returned data.
3. Check there is no option to parse, and pass group data in a header back upstream.

## Context
Trying to implement RBAC on tools and applications. The tools and applications are configured with HTTP header authentication, and currently log the user in based on x-auth-request-user. I want the ability to give the user different access based on the AD group they are in.

e.g. admin, dev, read_only

## Your Environment
Deployed with the official helm chart, and configured with Azure provider. Nginx (kubernetes ingress controller) is configured with auth-url and auth-signin to proxy auth to oauth2-proxy.

Config: 
```
set-xauthrequest: true
set-authorization-header: true
provider: azure
azure-tenant: <redacted>
<+ other unrelated config>
```
- Version used:
```
repository: "quay.io/pusher/oauth2_proxy"
tag: "v3.1.0"
```

**Comment by omerlh** [comment]
I want something similar - having similar ability to `-google-group`: specifying a group that the user must be a member of in order to be able to login.

**Comment by jeremych1000** [comment]
Hello - I'm guessing this is still being discussed behind-the-scenes? Will it be considered?

**Comment by sylr** [comment]
I would really like this too!

**Comment by bhvr-fmarceau** [comment]
I'd really like that as well! 

+1 for the feature request!

**Comment by JoelSpeed** [comment]
Hi all, I've had a pass over the original PR to bitly and think this is definitely something we should be supporting. I'm a bit concerned about the breaking changes it introduces though, we still need to work out how to handle those since taking over the project!

Does anyone have time to try and get a PR opened here based on the changes from the original PR? Perhaps @pasoroki?

**Comment by dekimsey** [comment]
While trying to develop support for azure's app roles, I did notice it was very easy to trip the cookie size limit on the browser when Groups started being populated. I know AWS auto-splits the cookie, and that may be required (max 11k) to reasonably support this.


Background: I wanted access to Azure Application Roles, which forced having to create an Azure v2.0 provider, the current implementation is against the v1 api. I did base the changes off of the PR regarding Groups. So if we have a good direction on this, I'd like to see Roles get included (separate pr likely).

The WIP implementation is [here](https://github.com/dekimsey/oauth2_proxy/commit/9d8816adfeb8bc25bc9f4bf1b8245267111b0cf1).

**Comment by JoelSpeed** [comment]
> While trying to develop support for azure's app roles, I did notice it was very easy to trip the cookie size limit on the browser when Groups started being populated. I know AWS auto-splits the cookie, and that may be required (max 11k) to reasonably support this.

Just as an FYI, we have session cookie splitting built into the proxy so if you do start overflowing the 4k limit, we can handle that already 😄
https://github.com/pusher/oauth2_proxy/blob/908ac24257840b197163c6e0bec8954b56ca3656/oauthproxy.go#L325-L327

Also, we are making an effort to introduce sever-side sessions which will mitigate this problem (see #147 & #148)

**Comment by vkadiwala** [comment]
This is the really needed feature. When it will get merged?

**Comment by morganchristiansson** [comment]
It can already be done via the Accesss-Token header which contains JWT token JSON

However this requires custom support to read this header in the application which only works in some scenarios.

**Comment by rnsc** [comment]
Hello @JoelSpeed ,

Is this still on the radar?
Looking at the original PR, I don't see any breaking change on the Google provider (the requester kept the Google groups flags but mentioned them as deprecated).
Or is there something else preventing this fork to integrate this change?

**Comment by JoelSpeed** [comment]
There are some outstanding comments on the PR, if the PR author can fix these then I'll re-review and hopefully it will be ready for merge

**Comment by dkutetsky** [comment]
Any updates?
