### ISSUE TITLE
Anonimous user

### ISSUE THREAD

**Issue by ba1dr** [oauth2-proxy/oauth2-proxy#713]
Actually, how can oauth-proxy raise not HTTP401, but some response for "Anonimous user"?

Say, we have a page that could be shown to all users - both authorized and anonimous. Known users will have more personalized content and could have more buttons available while just unknown visitors will see only default settings and "Log In" button which they can click to get access. Backend decides itself what to show.

I want to be able to authenticate users with existing restrictions (allowed emails/domains only) but also to skip authentication at all.
If user selects to log in - oauth2-proxy keeps the session and refreshes tokens as usual. If token expires or user was not logged in - nothing, but default user returned.

I use nginx as a reverse proxy in front of my app.

**Comment by NickMeves** [comment]
Hey there,

I don't think this is possible at the moment. We are exploring the potential for rich authorization hierarchical rulesets where this may be possible, but that won't be available until at least our v7 release which is at least 2-3 months out.

This PR has started designing that archtiecture: https://github.com/oauth2-proxy/oauth2-proxy/pull/685

**Comment by JoelSpeed** [comment]
This request doesn't really fit into the current design of the OAuth2 Proxy. The project is intended to be used to require authentication on a path or not, a middle ground of some users was never really considered.

You may be able to do something now by using the nginx auth_request module and having the auth request error page do nothing, you application would then handle the presence of the headers returned from OAuth2 Proxy or not. (Use set-xauthrequest to get userinfo headers).

Your app would need a login button that redirects the user to start the OAuth2 Proxy login flow, but it sounds like that shouldn't be too hard as that's what you want right?

If you can get Nginx to ignore the auth_request status code, then you should be able to make something work with the existing project

**Comment by ba1dr** [comment]
Yes, I tried to do this with nginx too - to check for cookie or token in headers. I just thought if maybe there would be an easier way.
I've confused with nginx settings - config become very ugly with all these clauses.
You may keep this issue as a minor feature request or close if you do not plan to implement this feature. Thanks.

**Comment by JoelSpeed** [comment]
Does Nginx need to know if the user is authenticated or not? Surely you just want to inject the headers into the request to your upstream service, I would assume that could interpret the empty header as an anonymous user? (I'm making some assumptions here that this is something you reasonably control, and that it's not some off the shelf product 😅 )

**Comment by ba1dr** [comment]
Well, theoretically there could be 3 possible cases as I see it:

* user clicks "log in" and succesfully obtains token/cookie
* user tries to log in, but fails by some reason (wrong credentials or not allowed user)
* new anonimous user

in case (2) when login not successful it would be useful to have some flag for the backend app to interpret it and show a warning maybe. If anonimous users are allowed - no need to return HTTP403 here. If not allowed - you've got error 403 and kicked off the site.
