### ISSUE TITLE
Azure provider does not let you to ask for approval

### ISSUE THREAD

**Issue by carrot-hub** [oauth2-proxy/oauth2-proxy#716]
## Current Behavior
When using Azure provider and having an application which requires admin consent before letting me through, the proxy does not even proceed to state when Azure offers me to ask administrator for approval. 

The flow goes like this:
1) Sign in page.
2) Password page.
3) Page asksing me if I want to stay logged in.
4) Callback resulting in 500 internal server error.

## Expected Behavior

The flow should goes like this (this is how it works if I go directly without oauth proxy):
1) Sign in page.
2) Password page.
3) Page asksing me if I want to stay logged in.
4) Page asking me to consent.
5) In case of admin approval is required, page asks me to reason why I need the access.
6) Callback resulting in success if I don't need approval from the administrator, otherwise 401.

## Other information
The proxy basically finishes the initial flow after asking me if I want to stay logged in. It then goes directly to /callback without printing any error in logs.

Logs in nginx:
```
2020/08/07 12:21:49 [error] 5741#5741: *4574945 auth request unexpected status: 400 while sending to client, client: 10.244.0.1, server: myapp.westeurope.cloudapp.azure.com, request: "GET /bg/explorer/ HTTP/2.0", host: "myapp.westeurope.cloudapp.azure.com", referrer: "https://login.microsoftonline.com/"
10.244.0.1 - - [07/Aug/2020:12:21:49 +0000] "GET /bg/explorer/ HTTP/2.0" 500 579 "https://login.microsoftonline.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 6812 0.004 [namespace-explorer-80] [] - - - - 9cfea3c5bbf27fce23a71a9e40309bcf
```

I assume that redeem phase fails as it can not get token without the admin consent, but I'm not really sure as it fails silently. 

Also when I approve the application and the user in advance, the flow completes successfully. **The issue is that I need to have an option to ask for the admin approval, which is not possible right now**.

- Version used: v6.0.0

**Comment by JoelSpeed** [comment]
Is there any documentation from the Azure side on how this works? I imagine you have to add some extra parameter to the login url to enable this consent screen, that's how these things normally work at least

**Comment by carrot-hub** [comment]
Yes, it is described here: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

The problem is that if I put `prompt=consent` I need to approve every time I sign in. 
I expect the flow to ask me for consent only in case I'm signing-in for the first time and then simply do not ask as the consent has been already granted (I can also see it in Azure AD, that I'm allowed to use application, yet it still forces me to consent every time). This is how it works without proxy so I simply assumed the proxy does not support this function.

**Comment by JoelSpeed** [comment]
> This is how it works without proxy so I simply assumed the proxy does not support this function.

How do you mean? As in using Azure AD with some other OAuth2 client?

I suspect other clients use a cookie to track whether the user has authenticated before or not. 

I wonder if this is an issue with other providers before, perhaps we need to have some sort of configuration for a prompt that can change depending if a consent cookie is present or not
