### ISSUE TITLE
Azure APIM to Oauth2 proxy

### ISSUE THREAD

**Issue by dmahisingh** [oauth2-proxy/oauth2-proxy#723]
## Context
Requesting for a suggestion - 

As all our back end services are secured by oauth2 proxy with AuthProvider as Azure AD. Now we want to expose these services to downstream application via Azure APIM - so how should I authenticate the request coming from Azure APIM to oauth2 proxy? 

My Azure APIM may go via oauth2 proxy to invoke application services and Azure APIM may not be able to authenticate with Azure AD - so how do we need to handle this scenario?

Please provide your inputs.

**Comment by dmahisingh** [comment]
Nick - Is this approach not working with new version of oauth2 proxy 6.1.1??

**Comment by NickMeves** [comment]
I haven't heard any follow up questions. Assuming the answers are sufficient and closing.

This article gives additional detail on machine auth with OAuth2-Proxy if it helps: https://medium.com/in-the-weeds/service-to-service-authentication-on-kubernetes-94dcb8216cdc
