### ISSUE TITLE
Respect X-Forwarded-Host in OAuthStart's GetRedirectURI call

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#724]
oauthproxy.go explicitly uses `req.Host` as the hostname in `p.GetRedirectURI(req.Host)` before creating a LoginURL to redirect to.

In environments behind an API or access gateway, the `Host` header might be changed to the backend internal hostname and the original Host the client sent is set to the `X-Forwarded-Host`

This results in the post authentication final redirect attempting to redirect to a potential internal domain that has 2 potential issues:

(1) The domain isn't accessible to the user
(2) If it is, the domain doesn't have the CSRF token that was set on the initial domain.

## Expected Behavior

We are aware of `X-Forwarded-Host` headers and will smartly construct a redirect URL querystring parameter in the Login URL appropraitely.

## Current Behavior

Post login flow redirects to the wrong domain in environments with this architecture.

## Possible Solution

Make this section aware of `X-Forwarded-Host`:

https://github.com/oauth2-proxy/oauth2-proxy/blob/5fa5b3186f39f068c1bc7558884e9d14cc376755/oauthproxy.go#L750

## Steps to Reproduce (for bugs)

Have a `Host` header for a request that gets to OAuth2-Proxy that isn't on the original domain the client requested.

## Your Environment

Duo Network Gateway (Access Proxy) -> K8s Nginx Ingress (internal domain) -> OAuth2-Proxy -> App

DNG understandable changes the Host header from its public domain to the internal domain so the host based routing at the Nginx ingress layer works normally.

- Version used:

v6.0.0

**Comment by holyjak** [comment]
I have the same problem. My app is served via AWS CloudFront at myapp.example.com, the backend - protected by oauth - is running on AWS Fargate at api.example.com. The AWS Application Load Balancer sets `x-forwarded-host` to "myapp.example.com" while `host` is the internal "api.example.com".

I currently solve this by hardcoding `OAUTH2_PROXY_REDIRECT_URL="https://myapp.example.com/api/oauth2/callback"` but it would be simpler if I did not need to do that.

**Comment by bryantbiggs** [comment]
@holyjak this might be a longshot, but would you be able to share your setup for running on Fargate? I can't seem to figure out why my hosts aren't registering as healthy and all the docs I can find are on running on K8s. if not, no worries - thanks!
