### ISSUE TITLE
Trying to secure ingress resources with oauth2-proxy / okta

### ISSUE THREAD

**Issue by donch** [oauth2-proxy/oauth2-proxy#725]
Hi,

I'm trying the latest version of oauth2-proxy with okta as an oidc provider to secure ingress resources (using nginx ingress controller v0.21.0 and Kubernetes 1.15)

## Expected Behavior

When i'm visiting an endpoint secured, i should be redirected to Okta, and be redirected to my resource once i'm logged in.

## Current Behavior

After the request from Okta to the URI /oauth2/callback, i'm getting a 502 error and i'm unable to access the secured resource.

I'm getting this 502 error when i use the versions v4.1.0, v5.1.0, v6.0.0 of oauth2-proxy. 
For a long time, we use a custom version for internal usage (that we used with Dex(LDAP) which work well: `quay.io/joelspeed/oauth2_proxy:kubernetes-1` and i tried it with Okta as an oidc provider and it also works. But we wanted to update it to an up 2 date version.

So, i guess there is a misconfiguration or something I've missed to get the latest version working properly. 

Here is the logs of the proxy when i get a 502 error : 

```
okta-oauth-proxy-oauth2-proxy-795bdb4dcd-r227f oauth2-proxy 10.189.10.13:2712 - - [2020/08/19 13:11:21] $FQDN GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 401 21 0.000
okta-oauth-proxy-oauth2-proxy-795bdb4dcd-r227f oauth2-proxy 10.189.10.13:2714 - - [2020/08/19 13:11:21] $FQDN GET - "/oauth2/start?rd=https://example.com/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 302 360 0.000
okta-oauth-proxy-oauth2-proxy-795bdb4dcd-r227f oauth2-proxy 10.189.10.13:2714 - username@gmail.com [2020/08/19 13:11:37] [AuthSuccess] Authenticated via OAuth2: Session{email:username@gmail.com user:XXXXXXXX PreferredUsername:username@gmail.com token:true id_token:true created:2020-08-19 13:11:37.216333594 +0000 UTC m=+145.260523643 expires:2020-08-19 14:11:36.924722957 +0000 UTC m=+3744.968913049}
okta-oauth-proxy-oauth2-proxy-795bdb4dcd-r227f oauth2-proxy 10.189.10.13:2714 - - [2020/08/19 13:11:36] $FQDN GET - "/oauth2/callback?code=9fPg7aCcJYnSr1hLTqhrEwErzXKNG-51EelZjdINWhU&state=0e58098e3cb3ee8ab3122fb4d1de5c48%3Ahttps%3A%2F%2Fexample.com%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 302 56 0.636
```

The last call logged by the proxy is a 302, and not a 502. I don't understand why i'm getting this error. 

In addition, we use the following annotations for our ingress resources to secure : 

```
    nginx.ingress.kubernetes.io/auth-signin: https://$FQDN/oauth2/start?rd=https://$host$request_uri$is_args$args
    nginx.ingress.kubernetes.io/auth-url: https://$FQDN/oauth2/auth
```

It could be very nice if we can get some help on it please.

Thanks

**Comment by donch** [comment]
Hi, 

Thanks for your help.

Here is the oauth2 configuration we use : 
`  configFile: |-
    provider = "oidc"
    redirect_url = "https://XXXXXX.kube.dm.gg/oauth2/callback"
    oidc_issuer_url = "https://dev-XXXXXX.okta.com"
    email_domains = "*"
    client_id = "XXXXX"
    client_secret = "XXXXX"
    pass_access_token = true
    cookie_secret = "XXXXX"
    skip_provider_button = true
    scope = "openid profile email offline_access groups"
    whitelist_domains =  ".dm.gg"
    cookie_domains = ".dm.gg"
    upstreams = [ "file:///dev/null" ]
    set_xauthrequest = true
    ssl_insecure_skip_verify = true
    set_authorization_header = true
    cookie_secure = false`

The ingress domain we want to secure is like `XXXX.pub.kube.dm.gg` and what we want to do is what you describe in (2).

Our configuration seems good ?

**Comment by NickMeves** [comment]
Yeah - unfortunately nothing is jumping out at me as a misconfiguration. I'm a little stumped as to why you are seeing a 502 instead of a 302 like the logs say. I'm assuming something else in your stack potentially that I don't have visibility on?

**Comment by JoelSpeed** [comment]
It could be something to do with the headers coming back from the proxy being larger than the buffers in nginx, you could try setting a larger buffer and see if that helps? `proxy-buffer-size` is the options people normally change I think

**Comment by donch** [comment]
Thanks @JoelSpeed , i will try to play with these proxy parameters.

@NickMeves , the only component between Okta (which doing the requests) and the oauth proxy is my nginx ingress controller (In its logs, nginx show a 502 from the upstream (oauth-proxy).

**Comment by donch** [comment]
Good news @JoelSpeed , by tweaking `proxy-buffer-size` to `8k`, all is working fine ! Thanks a lot for your help.
