### ISSUE TITLE
How to retrieve new access token from the IDP

### ISSUE THREAD

**Issue by newtoworld999** [oauth2-proxy/oauth2-proxy#726]
Hi
We implemented the Oauth2 proxy with ingrss-nginx in AKS. When i give the application url oauth2 proxy is redirecting to the IDP login page and after authentication is done iam just displaying the user info and its working as expected. But IDP has set the access token expiry and once the access token is expired its redirecting again to the login page instead of just refreshing the access token directly from IDP, May i know what configuration needs to be done for the same
My Ouath2 proxy Config
   spec:
      containers:
      - args:
        - --provider=oidc
        - --oidc-issuer-url=
        - --pass-authorization-header=true
        - --set-authorization-header=true
        - --set-xauthrequest=false
        - --pass-access-token=false
        - --user-id-claim=sub
        - --skip-oidc-discovery=false
        - --cookie-secure=false
        - --whitelist-domain=XXXX
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: oauth2-proxy
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret

Ingress object config
		
 kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Access-Token,x-auth-request-user,x-auth-request-email,Authorization
    nginx.ingress.kubernetes.io/auth-signin: http://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie_oauth2_proxy_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }

**Comment by newtoworld999** [comment]
this is the one deployed. 
quay.io/oauth2-proxy/oauth2-proxy:Latest

**Comment by newtoworld999** [comment]
is there any way to session timeout similar to id token expiry time instead of access token expiry time in oauth2 proxy config?

**Comment by JoelSpeed** [comment]
Please use a tagged version rather than `latest`, current release is `v6.0.0`. We may publish a breaking change to the `latest` tag at any point which would break your systems.

You can set the `--cookie-refresh` flag to match the time of your access token expiry, that should try to refresh the tokens at that point.
