### ISSUE TITLE
How can we pass the url parameters to the backend application using oauth2 proxy

### ISSUE THREAD

**Issue by newtoworld999** [oauth2-proxy/oauth2-proxy#727]
Hi 
we implemented the oauth2 proxy in AKS. APplication is working as expected when user clicks the link along with url there are additional parameters that are passed as url parameters is there any way we can pass the url parameters to the backend AKS app using oauth2 proxy configuration

**Comment by JoelSpeed** [comment]
Do you mean that the callback has additional parameters? Or do you just need to put some extra args into the request for every request to the upstream server? What sort of information is contained in these values?
