### ISSUE TITLE
Support Google Cloud Identity Groups API for authorizing google group members.

### ISSUE THREAD

**Issue by maxbischoff** [oauth2-proxy/oauth2-proxy#728]
## Expected Behavior

oauth2-proxy should support the new [Cloud Identity Groups API](https://gsuiteupdates.googleblog.com/2020/08/new-api-cloud-identity-groups-google.html) to validate groups of users authenticating via Google.

## Current Behavior

Currently only the Admin SDK is supported to validate the groups of a user according to [the documentation](https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#restrict-auth-to-specific-google-groups-on-your-domain-optional).

## Possible Solution

An additional flag besides `--google-group` can be introduced for configuring which API to use.

## Context

I am currently using the Admin SDK for validating groups, but as I am not admin in my organization configuring this is quite a hazzle.

## Your Environment

- Version used: `v5.1.0`

**Comment by JoelSpeed** [comment]
This looks like an interesting new API that they've released. I would definitely be in favour of us moving (if we can in a non-breaking way) to this new API. If we can't, we should look into a nice way to support both. I've configured this google group stuff myself in the past and agree, the current way is a bit of a pain. I think we need to do some more research into this new API.

The only concern I have is that this is brand new, I wonder if it may be subject to frequent changes, perhaps we should wait for it to stabilise a bit?

**Comment by VictorBersy** [comment]
Thanks for opening this issue! I'm interested too, because indeed, it's quite painful to configure currently.
I'm commenting to reopen the issue 👍

**Comment by debojitkakoti** [comment]
@JoelSpeed I have one PR ready for this feature and it's working and I am using it. However I don't have any tests written yet.
