### ISSUE TITLE
Sessions duration a bit too short on Azure

### ISSUE THREAD

**Issue by yene** [oauth2-proxy/oauth2-proxy#732]
We are using oauth2-proxy, and I noticed that I get logged out a bit too much.
Is it possible to increase the session duration on Azure?

Thank you for your time.

- Version used: 6.0.0

**Comment by JoelSpeed** [comment]
Have you tried deploying refreshing of the tokens? You should be able to request a refresh token from Azure which would allow the proxy to refresh your session silently for you

**Comment by yene** [comment]
Thank for the fast response JoelSpeed.

Are you referring to cookie-refresh, I thought Azure does not support it #260

**Comment by JoelSpeed** [comment]
I would suggest trying the OIDC provider rather than the Azure provider, it might not give you all of the features of the Azure provider, but it should work and should handle cookie refreshing. If you need both, we may need to add it as a new feature
