### ISSUE TITLE
Whitelisting IP instead of domain

### ISSUE THREAD

**Issue by salmanisd** [oauth2-proxy/oauth2-proxy#734]
I am running oauth2-proxy behind nginx webserver. The webserver has no domain name and can only be accessed through a local ip (e.g. 192.168.1.111).

Overall everything works fine apart from the unauthenticated redirects. 
e.g) when i try to access <deviceip>/location1 in my browser ,I am redirected to the login screen. After loggin in I am redirected to the homepage instead of /location1. (due to whitelist-domain option not being set)

I can make everything work if I add the ip address in the option  "OAUTH2_PROXY_WHITELIST_DOMAINS=192.168.1.111"  but this doesnt seem to be a clean solution.(ip can be changed)

Is there like a option to disable this whitelist check or make it something like a wildcard?
thanks

**Comment by JoelSpeed** [comment]
@salmanisd How are you setting the redirect location? Could you provide some more detail about your setup so that we can understand how your particular scenario is working

**Comment by salmanisd** [comment]
oauth2-proxy running on a device using nginx as reverse proxy. The nginx is configured to have no domain name and is only reachable through a static local ip (e.g 192.168.1.111)

**Login Flow with OAUTH2_PROXY_WHITELIST_DOMAINS option empty**

1.  I access 192.168.1.111/foo from another PC.
2. I am redirected to my login page (the log shows ``` oauth2-proxy[30164]: [2020/06/20 12:55:53] [oauthproxy.go:636] Rejecting invalid redirect "http://192.168.1.111/foo": domain / port not in whitelist```)
3.  After entering credentials and successfully authenticating, I am logged in to the homepage at 192.168.1.111 (not taken to 192.168.1.111/foo).
4. After logging in I have to manually take myself again to 192.168.1.111/foo (which works fine)

The only way to avoid the "reject" in step 2 is to add the device ip address to oauth2-proxy like this
"OAUTH2_PROXY_WHITELIST_DOMAINS=192.168.1.111"

But that means anytime the ip of the device changes, I will have to add it to oauth2-proxy whitelist and restart oauth2-proxy.
Thats what I want to avoid.

**Comment by JoelSpeed** [comment]
>I am redirected to my login page (the log shows oauth2-proxy[30164]: [2020/06/20 12:55:53] [oauthproxy.go:636] Rejecting invalid redirect "http://192.168.1.111/foo": domain / port not in whitelist)

@salmanisd So how do you set the redirect? Are you using nginx auth request mode for example and setting the login url to redirect to `/oauth2/start?rd=...`?

**Comment by salmanisd** [comment]
yes.
This is whats in my nginx conf 
```server {
        listen 80 default_server;

        auth_request /internal-auth/oauth-proxy/auth;
        error_page 401 = http://$host/oauth-proxy/start?rd=$scheme://$host$request_uri;
         #rest of unrelated conf redacted
```

**Comment by JoelSpeed** [comment]
Try making the rd parameter of that config just `rd=$request_uri` removing the host and scheme. This should work if  OAuth2 Proxy is available on the same host

**Comment by salmanisd** [comment]
- i changed the directive to
```       error_page 401 = http://$host/oauth-proxy/start?rd=$request_uri;```
- restarted nginx
- cleared browser and tried deviceip/foo
- logged in
- same issue - saw 192.168.1.111 instead of 192.168.1.111/foo
oauth2-proxy log say
 ``` Jun 08 15:49:15 oauth2-proxy[19744]: [2020/06/08 15:49:15] [oauthproxy.go:636] Rejecting invalid redirect "http://192.168.1.111/foo": domain / port not in whitelist```

**Comment by salmanisd** [comment]
aah my bad @JoelSpeed . You were right... I tried your suggestion on some other locations and they work if I use
 ```error_page 401 = http://$host/oauth-proxy/start?rd=$request_uri;```

Only this one particular location I used for testing is being rejected. I can look into it further. Thanks for your quick help.

**Comment by JoelSpeed** [comment]
Sounds like this is resolved? Can we close the issue?
