### ISSUE TITLE
CORS preflight blocked when using with kubernetes auth-url

### ISSUE THREAD

**Issue by niraizik** [oauth2-proxy/oauth2-proxy#735]
When the browser send the a CORS preflight OPTIONS request it must send it without credentials.
the flag --skip-auth-preflight only work when using oauth2 as a proxy and not with nginx ingress external auth subrequest.

## Expected Behavior
When enabling the flag --skip-auth-preflight a preflight request should return 202 in /auth endpoint

## Current Behavior
preflight request are blocked when using with nginx ingress external auth subrequest

## Possible Solution
the AuthenticateOnly handler should also check something like in IsWhitelistedRequest 
but is should check the request method in header X-Original-Method because nginx ingress change the request method to by default 

## Your Environment
kubernetes nignx ingress

- Version used:
v6.0.0

**Comment by niraizik** [comment]
possible fix in https://github.com/niraizik/oauth2_proxy/tree/auth_preflight_pass

**Comment by tsiaGeorge** [comment]
Hi @niraizik. I'm dealing with the same issue. Do you have an estimate on when the relevant branch will be merged? Thank you in advance.

**Comment by JoelSpeed** [comment]
Could this not lead to a potential security issue? 

If I were to `curl -H "X-Original-Method: OPTIONS" http://something.example.com/secure`, as a GET, would that not allow me to access the page even though I technically shouldn't? 

Is there any way to handle this in NGINX directly?

**Comment by niraizik** [comment]
1. I think that the ingress overwriter "X-Original-Method" header when it send the request to oauth2-proxy.
But I agree that checking in this header is problematic, I don't know if other ingresses use the this exact same header.

We can set in the ingress config to preserve the request method when sending the request to oauth2-proxy with
```yaml
nginx.ingress.kubernetes.io/auth-url: http://foo.com/external-auth
nginx.ingress.kubernetes.io/auth-snippet: |
    proxy_method $request_method;
```

But with this `OPTIONS` requests to `/oauth2/auth` get caught in
```go
case p.IsWhitelistedRequest(req):
		p.SkipAuthProxy(rw, req)
``` 
which forward the request and don't return 202 to the ingress

we can move this case before the default case and after all special endpoint paths are checked
and then in AuthenticateOnly we only need to check the flag and the request method

2. kubernetes nginx ingress have basic CORS handling, but the external auth handling happe  before the CORS handling
so CORS request will still get forward to oauth2-proxy

**Comment by JoelSpeed** [comment]
I would prefer to keep the existing behaviour of not having it also read a header, sounds like there's a workaround for that as you've suggested above.

If the `skipAuthPreflight` is not returning a 202 for the authenticate only page, then I'd consider that a bug and we should resolve that.

**Comment by rborer** [comment]
I stumbled upon the same problem & figured out a fix with works for me using the following Nginx configuration:

```
  location = /oauth2/auth {
    ## Allow preflight requests (with origin set) to go through unauthenticated
    set $PF "";
    if ($request_method = 'OPTIONS') {
        set $PF O;
    }
    if ($http_origin) {
      set $PF "${PF}O";
    }
    if ($PF = OO) {
        return 204;
    }
    ## End preflight requests handling

    proxy_pass       http://127.0.0.1:4180;

[...]
}
```

Sharing it here to help others with the same need.

**Comment by hacst** [comment]
Under the assumption that all options requests should pass unauthenticated the minimal workaround we implemented is to add the following annotation to the nginx Ingress objects in kubernetes:
```yaml
metadata:
  annotations:
    # Workaround for https://github.com/oauth2-proxy/oauth2-proxy/issues/735
    nginx.ingress.kubernetes.io/auth-snippet: |
      if ($request_method = "OPTIONS") {
        return 202;
      }
```
It would still be highly preferable to have this issue fixed in oauth2-proxy itself.

**Comment by twitchyliquid64** [comment]
Note that the above workaround may be insecure if oauth2-proxy fronts a service that doesn't check the HTTP method when generating its reply. Make sure a request with method `OPTIONS` doesn't result in a normal response with curl or similar.

**Comment by jonaskello** [comment]
@twitchyliquid64 I think you are referring to @hacst work-around above? I was thinking to implement that but I wanted to understand your warning about it. Would it not be that all OPTIONS requests would be terminated directly by ingress-nginx with 202 with this config? So OPTIONS requests could never reach the backend service?

**Comment by twitchyliquid64** [comment]
My understanding (and I could be wrong) was that snippet would pass the auth request generated by nginx (due to that rule oauth2-proxy would never be consulted), so the underlying request would then proceed unmodified.

**Comment by jonaskello** [comment]
Aha, I think I understand what you mean now. I did read the annotation carefully enough to realize it says `auth-snippet` rather than `server-snippet`. 

As I understand it now that snippet will only handle the auth part, not the actual request. I guess in that case you are right that all original requests would proceed all the way to the backend service as long as they are done with the OPTIONS verb, so if the backend service just checks the path and not the verb, you would be able to fetch data for any path with the OPTIONS verb.

Perhaps a `server-snippet` that just returns 202 could work to always terminate OPTIONS with 202 and not reach the backend service?
