### ISSUE TITLE
Error redeeming code during OAuth2 callback: token exchange: oauth2: cannot fetch token: 400 Bad Request

### ISSUE THREAD

**Issue by r-kotagudem** [oauth2-proxy/oauth2-proxy#736]
Hi @JoelSpeed 
We are seeing below error at  token exchange step.
[2020/08/25 18:05:16] [oauthproxy.go:798] Error redeeming code during OAuth2 callback: token exchange: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_request","error_description":"Invalid Domain","secondary_message":"Domain in request is missing"}

We had to pass below header with this request unless which we see this error.
X-OAUTH-IDENTITY-DOMAIN-NAME: TestDomain

Is there a way to configure  'the name of the identity domain' in X-OAUTH-IDENTITY-DOMAIN-NAME to be passed as header in token redeem request?

**Comment by JoelSpeed** [comment]
Hi @r-kotagudem, I don't think we currently have this kind of ability, though it is something we could look into supporting.
Which provider are you using out of interest? (I assume OIDC)
Who/what is your identity provider?

**Comment by r-kotagudem** [comment]
> Hi @r-kotagudem, I don't think we currently have this kind of ability, though it is something we could look into supporting.
> Which provider are you using out of interest? (I assume OIDC)
> Who/what is your identity provider?

thanks for the reply.

It is Oracles oauth implementation. Oracle Access Manager 12c OAuth Services

**Comment by adamdecaf** [comment]
I'm seeing the same error with GitHub auth. I can load `/oauth2/start` in the browser and it'll grab a new OAuth token and let me through.

**Comment by futurelm** [comment]
get same error with Gitlab auth, seems related with gitlab group number, when i quit some gitlab group, it works
