### ISSUE TITLE
v6.0.0 docker release can't set cookies

### ISSUE THREAD

**Issue by sarojkandel12** [oauth2-proxy/oauth2-proxy#738]
While deploying oauth2-proxy via the docker tagged image v6.0.0, I keep getting an error in Chrome console saying the "Set-Cookie header is ignored in response from url… Cookie length should be less than or equal to 4096 characters", and the browser redirects too many times and eventually errors out.

However, I cloned the latest repo and created a docker image (docker.io/sarojkandel/oauth2-proxy:v6.0.0) based on the Dockerfile in the repo, and the cookie is set properly when deployed using this image. 

There might be a discrepancy between the pushed docker image, and the repo.

**Comment by JoelSpeed** [comment]
There were some fixes merged into master after the v6.0.0 release that I think will have helped with this. There was a problem with the way we were calculating the cookie size to cut on. Please try the official v6.1.0 release image that was published yesterday and see if this has the same issues

**Comment by sarojkandel12** [comment]
Hmm still seeing that issue on the latest image.

**Comment by JoelSpeed** [comment]
To confirm, the code you have in your image for v6 is working, but the main image isn't and neither is v6.1.0 from our main image? 

I ran your code and can see that it is supporting `--session-cookie-minimal`, however no version information was set, looks like you may have somehow created an image that is somewhere between v6.0 and v6.1.

If you use `make docker` when building your images it will include this version information and could help us identify exactly where the issues are

**Comment by JoelSpeed** [comment]
Closing this as we've not had any responses recently, I'm assuming the answer I gave helped solve the issue
