### ISSUE TITLE
Suggestions for implementing multi-tenancy proxy with Keycloak 

### ISSUE THREAD

**Issue by a8m** [oauth2-proxy/oauth2-proxy#739]
Hey! Thanks for this really useful project, you did an amazing work here!

I want to use it in one of my projects, but it's currently missing a functionality that blocks me from using it and I would like to hear if you have other suggestions for implementing my use case, or you're open for a feature request (that I'll implement of course).  

I want to use this proxy in a multi-tenancy mode. The use case is that I have a "realm" (in Keycloak) for each tenant in my system. In the current implementation, I'm using a subdomain in my website to get the tenant (relam) name and do the login/auth/etc through this relam in Keycloak. For example: 

```
https://<tenant>.website.com => https://<keycloak-host>/realms/<tenant>/protocol/openid-connect/auth
```

At the start, I tried to implement an openid-connect service, but the incoming auth request didn't contain any information regarding the proxied-request. So, I thought about suggesting a feature that is not tightly coupled to my use case and maybe will be useful for others as well.

The main idea is to add support for Go template in some of the config parameters (like `login-url`) and inject the proxied-request as an argument to the template executor. For example:
```
--login-url="https://<keycloak-host>/realms/{{ $.Header.Tenant }}/protocol/openid-connect/auth"
```
In my case, I can add this "Tenant" header in my ingress configuration and then use it in the proxy. 

Any thoughts or comments?

**Comment by JoelSpeed** [comment]
As an immediate workaround, could you not just deploy an instance of the OAuth2 Proxy for each of your tenants?

I'd be keen to find out how common this requirement is, if it's a must for the keycloak users then I definitely think we should find a solution. I think this templating idea is good, but I'd like to have a think for alternatives before we decide on an approach.

Would also be keen to hear other maintainers opinions.

**Comment by a8m** [comment]
Hey @JoelSpeed and thanks for your response 😃 

> As an immediate workaround, could you not just deploy an instance of the OAuth2 Proxy for each of your tenants?

We actually can't do it, because we have dozens of tenants and we create/delete them dynamically using the Keycloak API.

About the templating solution - I tried to propose something that is not too coupled to our use case, and can be expanded to other providers except Keycoack.

**Comment by JoelSpeed** [comment]
@a8m Do you think we could raise a PR for the templating suggestion and then we can take a look at the complexity it adds and evaluate it there?

**Comment by a8m** [comment]
Sure, @alexsn from my team already started to work on that. We'll submit a PR in the upcoming days.

**Comment by a8m** [comment]
Hey, we ended up with a different solution, so I'm closing this issue. Thanks

**Comment by asudhakarreddy** [comment]
@a8m we are looking similar solution, can you please let us know what solution you used?

**Comment by peadarDoyle** [comment]
I'm evaluating oauth2-proxy at the moment and was hoping to find a feature like this since we too will be doing `<tenant>.website.com` where each customer has a dedicated keycloak realm. So we need some way of dynamically changing the various login/redeem/validation urls based on the requested resource.

The above example of templating looks like a good fit.

**Comment by alexsn** [comment]
We didn't end up using oauth2-proxy, we used keycloak connect instead.

**Comment by ch3rub1** [comment]
I was searching a solution to handle multi realm auth easily and I just found this issue.  
Does the multi-tenacy implementation within oauth2-proxy is still a thing or the idea was abandoned with the closure of this issue ?

**Comment by sTb1337** [comment]
We also have the feature request for multi-tenancy for Open ID Connect. Are there any updates? I hope this feature request didn't die?

**Comment by ilyesAj** [comment]
We're having the same issues here , is there any updates here ?

**Comment by stleon** [comment]
+1, this would be a super useful feature! Any updates or plans to revisit this? 🚀
