### ISSUE TITLE
Feature Request: Host-dependent configuration

### ISSUE THREAD

**Issue by haslersn** [oauth2-proxy/oauth2-proxy#749]
Hi, I'd like to proxy access to several endpoints on different subdomains where each endpoint might or might not need an access token (in order to access some resource server on behalf of the user). This can currently be done with `pass_access_token = true`. However, endpoints shall obtain an access token with as few scopes as possible (i.e. only the required scopes). Therefore it would be nice to set the `client_id`, `client_secret` and `scope` configuration options depending on the requested host. This could be done via new configuration options `match_client_ids`, `match_client_secrets` and `match_scopes`.

## Requested host

But what is the "requested host"? oauth2-proxy should extract the host from the URL contained in the `X-Original-URL` header, falling back to the `Host` header if the former is not present.

## Example

Suppose we have four clients configured in our identity provider. Their credentials (resp. allowed scopes) are:

* `app1:s3cr3t` (resp. `openid,profile,email,action1`)
* `app2:p4ssw0rd` (resp. `openid,profile,email,action2`)
* `my_client:123457` (resp. `openid,profile,email,action3`)
* `default_client:supersecurepassword` (resp. `openid,profile,email`)

`app1` is intended for a service running on sub1.example.com, `app2` is intended for a service running on sub2.example.com, `my_client` is intended for every service running on a subdomain of .sub3.example.com and `default_client` can be used for every other host where no access token is required. In that case it would be nice to be able to configure oauth2-proxy as follows.

```
match_client_ids = [
    "sub1.example.com:app1"
    "sub2.example.com:app2"
    ".sub3.example.com:my_client"
]
# fall back to `client_id` if no specification in `match_client_ids` matches.
client_id = "default_client"

match_client_secrets = [
    "sub1.example.com:s3cr3t"
    "sub2.example.com:p4ssw0rd"
    ".sub3.example.com:123457"
]
# fall back to `client_secret` if no specification in `match_client_secrets` matches.
client_secret = "supersecurepassword"

match_scopes = [
    "sub1.example.com:openid profile email action1"
    "sub2.example.com:openid profile email action2"
    ".sub3.example.com:openid profile email action3"
]
# fall back to `scope` if no specification in `match_scopes` matches.
scope = "openid profile email"
```

**Comment by JoelSpeed** [comment]
My immediate reaction to this is that this is a prime example of where you could/should just run three separate proxies.

OAuth2 Proxy is a fairly lightweight and stateless application, you should be able to run one per provider like this with relative ease

**Comment by DaveOHenry** [comment]
https://github.com/oauth2-proxy/oauth2-proxy/pull/204

**Comment by haslersn** [comment]
> My immediate reaction to this is that this is a prime example of where you could/should just run three separate proxies.
> 
> OAuth2 Proxy is a fairly lightweight and stateless application, you should be able to run one per provider like this with relative ease

You are right. I think the better solution would be to have separate oauth2-proxy instances. In the case of Kubernetes, it would be nice if somebody writes an “oauth2-proxy-operator” with an `Oauth2Proxy` CRD that configures an oauth2-proxy instance.
