### ISSUE TITLE
Can't Validate Token with "Keycloak Provider"

### ISSUE THREAD

**Issue by janevits** [oauth2-proxy/oauth2-proxy#751]
I'm implementing oauth2-proxy on k8s with Keycloak.
## Expected Behavior
it will log in successfully and can validate the token success and return user info

## Current Behavior
I got code from Keycloak but I got an error  "403 Permission Denied Invalid Account"

## Steps to Reproduce (for bugs)

1.  Now i create k8s local 
2.  deploy ingress.yaml like this
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/auth-url: "http://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k

spec:
  rules:
  - host: hello-world.{IP}.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-server
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  rules:
  - host: hello-world.{IP}.nip.io
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2`
3.  config oauth2-proxy.yaml
`apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=keycloak
        - --email-domain=*
        - --upstream=static://200
        - --http-address=0.0.0.0:4180
        - --login-url=http://auth.{IP}.nip.io/auth/realms/myrealm/protocol/openid-connect/auth
        - --redeem-url=http://auth.{IP}.nip.io/auth/realms/myrealm/protocol/openid-connect/token
        - --validate-url=http://auth.{IP}.nip.io/auth/realms/myrealm/protocol/openid-connect/userinfo
        - --set-authorization-header=true
        - --scope=openid
        - --client-id=myclient
        - --client-secret={my secret}
        - --ssl-insecure-skip-verify=true
        - --pass-authorization-header=true
        - --http-address=0.0.0.0:4180
        - --cookie-domain={IP}
        - --standard-logging=true
        - --auth-logging=true
        - --request-logging=true
        - --set-xauthrequest=true
        - --skip-provider-button=true
        - --skip-auth-preflight=true
        - --cookie-secure=false
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: {COOKIE_SCRET}
        - name: OAUTH2_PROXY_COOKIE_DOMAIN
          value: "*.{IP}"
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
`
4. and deploy keycloak to another deploment and another ingress like this
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
spec:
  tls:
    - hosts:
      - auth.{IP}.nip.io
  rules:
  - host: auth.{IP}.nip.io
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 8080`
5. when i access to hello-world.{IP}.nip.io it should redirect to auth.{IP}.nip.io in Keycloak login page and then I log in with my user and redirect to hello-world.{IP}.nip.io/callback with code and then return  "403 Permission Denied Invalid Account"
## Context
I inspect in Keycloak service i got 
`type=USER_INFO_REQUEST_ERROR, realmId=myrealm, clientId=null`
clientId is null I don't know why.

## Your Environment

{!--- Include as many relevant details about the environment you experienced the bug in --}
my k8s environment.

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by JoelSpeed** [comment]
If you haven't already, please take a look at the local testing environment implemented #604, it may help you out.

Are there any logs in OAuth2 Proxy that may be relevant to share?

**Comment by janevits** [comment]
@JoelSpeed  thank you.
I implemented it from #604 and works, it very helps full.
