### ISSUE TITLE
Adopting the oauth2-proxy helm chart

### ISSUE THREAD

**Issue by secustor** [oauth2-proxy/oauth2-proxy#752]
As the standard [helm repo](https://github.com/helm/charts) will be deprecated on the [13th of November](https://github.com/helm/charts/blob/master/README.md#deprecation-timeline) and it seems that no one has picked it up yet. 

The community could still handle the development and it would prevent issues like right now that the by default deployed version is the `5.1.0`. 

I hope you will consider it.

**Comment by JoelSpeed** [comment]
We are actively discussing the issue of Helm in #608, this could be considered a duplicate issue, please see the discussion in the other thread

**Comment by JoelSpeed** [comment]
This is being tracked in the other issue so I think we can close this one
