### ISSUE TITLE
Flag display-htpasswd-form has no influence

### ISSUE THREAD

**Issue by ofir-amir** [oauth2-proxy/oauth2-proxy#761]
After https://github.com/oauth2-proxy/oauth2-proxy/pull/687 was merged the configuration flag display-htpasswd-form has no influence any more

## Expected Behavior
Setting display-htpasswd-form to false should prevent the username/password fields from being displayed in the login form, even if the htpasswd file is present

## Current Behavior
The username/password fields are always displayed in the login form if htpasswd-file is present

## Possible Solution
https://github.com/oauth2-proxy/oauth2-proxy/blob/ef08d01b982fa37a94ba31e6bbcf14452f970974/oauthproxy.go#L220 should be changed to something like
```
displayHtpasswdForm: basicAuthValidator != nil && opts.DisplayHtpasswdForm
```

## Steps to Reproduce (for bugs)

1.  set htpasswd-file with a valid file
2.  set display-htpasswd-form to false
3.  Check login page 

## Your Environment
Docker based

- Version used: 6.1.1

**Comment by JoelSpeed** [comment]
Good catch, I agree with your analysis of this bug, would you be able to create a PR with your proposed fix?
