### ISSUE TITLE
Outdated documentation for htpasswd encryption

### ISSUE THREAD

**Issue by lentzi90** [oauth2-proxy/oauth2-proxy#763]
The [documentation suggests](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/configuration/configuration.md) that only SHA encryption is supported for htpasswd (search for `htpasswd-file`), but bcrypt [is actually also supported](https://github.com/oauth2-proxy/oauth2-proxy/commit/008ffae3bb5f1d068f2ea4dddb88ea80a6697297).

## Expected Behavior

Change the documentation to encourage bcrypt instead of SHA for better security.

## Current Behavior

Only the SHA encryption is listed as supported, and there is no mention of it being insecure.

## Possible Solution

I can create a PR with the necessary changes. :slightly_smiling_face: 

## Context

I was a discouraged from using oauth2-proxy with htpasswd when I though it only supported SHA encryption.

## Your Environment

Not applicable

- Version used: Latest docs?

**Comment by JoelSpeed** [comment]
If you're happy to raise a PR, that would be appreciated. We should just stop mentioning SHA in my opinion and suggest bcrypt is the only supported option. @NickMeves and I had discussed this previously IIRC
