### ISSUE TITLE
AuthFailure only on FireFox

### ISSUE THREAD

**Issue by salmanisd** [oauth2-proxy/oauth2-proxy#768]
I have a setup  with nginx, oauth2-proxy, login+oauth2 provider all running on a single host. The device can only be accessed over a static local ip and has no domain/server name.

While it works perfectly with chrome/edge I am having issues signing in with FireFox.

With Firefox I get this error page after trying to login
```
403 Permission Denied

http: named cookie not present
```
The logs 
```
oauth2-proxy[19611]: [::1]:32840 - admin@my-domain.com [2020/07/05 09:27:39] [AuthFailure] Invalid authentication via OAuth2: unable too obtain CSRF cookie
oauth2-proxy[19611]: [::1]:32840 - - [2020/07/05 09:27:38] 192.168.0.101 GET - "/oauth-proxy/callback?code=Vy9TSGO3ckZAsPCPSVC3Kw1gmwFC8LB6n4T55l3tnQo.DUMXIebYsSpDKZinLRyTHy_SJO0D_xk454JTMdVSPJU&scope=openid%20email%20profile%20roles&state=16893ced00a59da6a5b7aa57477e1419%3A%2F" HTTP/1.0 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" 403 358 1.215
```
From the login and oauth2 server logs everything seems to be fine. The Firefox test I am doing with a clean cache/history.

```
http_address="0.0.0.0:4180"
cookie_secret="OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
provider="oidc"
email_domains="my-domain.com"
oidc_issuer_url="http://localhost:4444/"
client_secret="b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK"
client_id="oauth2-proxy"
cookie_secure="false"
insecure_oidc_skip_issuer_verification="true"

set_xauthrequest="true"
pass_access_token="true"
scope="openid email profile roles"
pass_authorization_header="true"
proxy_prefix="/oauth-proxy"

request_logging="true"
auth_logging="true"
standard_logging="true"

redirect_url="http://localhost/oauth-proxy/callback" 
```
I am assuming that this missing cookie is "_oauth2_proxy_csrf" ? anything I can do to debug this issue?

**Comment by JoelSpeed** [comment]
I would advise using the Firefox developer tools to inspect what it is doing with the cookies as the different responses set them. IIRC Firefox does some weird stuff with cookies like always setting the cookie to include subdomains, perhaps it doesn't work well with IP based cookies?

**Comment by salmanisd** [comment]
The problem was the wrong date/time set on the server side which resulted in invalid "Expires" cookie attribute. That made oauth2-proxy generate and send cookies with an already expired date to the browsers. (I was also focused on the "Domain" atttribute so completely missed that)

Firefox would quietly discard these cookies but apparently chrome had no issues sending them back and the login worked perfectly. Setting the correct time on the server solved the login issue. 

Right now the option I see to handle this vast date/time difference issue is to use the ```Max-Age``` attribute as an option which replaces the absolute expiry date with a relative one(relative to when the browser receives the cookie). 

I dont see the attribute currently being used in oauth2-proxy. Does it make sense to have it as an additional config option?

**Comment by JoelSpeed** [comment]
Wouldn't you normally expect either the explicit expiry or max-age to be set, not both?

**Comment by salmanisd** [comment]
Yes. only one of Expires or Maxage is needed.

From my understanding Maxage seems to be a better option than Expires. Since I dont know the reason why oauth-proxy uses Expires, I thought instead of outright replacing Expires ,maybe an additional option to use Maxage can be added?

**Comment by JoelSpeed** [comment]
I think I'd rather we only have one option rather than the other, though I don't think it would be too hard to support both, just maybe confusing for users? 

We should try to work out if there has been previous discussion about why to use expires over max-age, my initial thought is perhaps it's better to protect against timing attacks?

**Comment by salmanisd** [comment]
I don't know about the security differences between the two attributes so can't comment.

In my use case, the oauth2-proxy is installed on different embedded devices which can accessed through a browser from another computer. These devices have the option that the user can manually set the date/time. If the customer sets a date in the past (for whatever reason) compared to the date his local computer/browser uses then he is basically blocked from logging in next time.
On my side I have modified oauth2-proxy and added the MaxAge attribute in makecookie functions and no longer have to worry about this date sync problem.

I just thought to bring this issue up in case someone else also runs into a similar problem. Please feel free to close or track this issue as you see fit.

**Comment by JoelSpeed** [comment]
> I don't know about the security differences between the two attributes so can't comment.

My concern is that if you use `maxAge`, that a user could adjust the time on their computer to extend how long the cookie stays around for. While OAuth2 Proxy should be checking the expiry time anyway, it would be easier for bugs to enable timing attacks if we don't use an explicit expiry I would imagine

@NickMeves Do you have any thoughts about this?

**Comment by JoelSpeed** [comment]
We don't plan to make any changes to the cookie maxAge/expires any time soon. Closing this until a need comes up for making changes in this area.
