### ISSUE TITLE
Can't login with user without email (Keycloak provider)

### ISSUE THREAD

**Issue by urbanpawel90** [oauth2-proxy/oauth2-proxy#769]
We have the use case where we want to allow users defined in KeyCloack to log in to some website after successful login and we use OAuth2 Proxy for that. The issue is that we have those user defined without email addresses in KeyCloak and OAuth2 proxy reports an error because of that.

## Expected Behavior

I expect that it is possible to login for users that do not have email defined in KeyCloak.

## Current Behavior

As for now OAuth2 Proxy reports 403 error:

> 403 Permission Denied
> Invalid Account

With following line in logs:
`172.17.0.1:40206 - - [2020/09/08 10:19:38] [AuthFailure] Invalid authentication via OAuth2: unauthorized`

## Possible Solution

Introduce some kind of option/flag to allow to login email-less users and modify email validator code (https://github.com/oauth2-proxy/oauth2-proxy/blob/d69fd6af22751974364e35cc697f9eaaaef160d3/validator.go#L90) to treat empty emails as valid.

## Steps to Reproduce (for bugs)

1.  Setup some example realm and client in KeyCloak following OAuth2 Proxy guide/docs.
2.  Create explicit user in KeyCloak and DO NOT fill the email field for him.
3.  Configure OAuth2 Proxy with KeyCloak provider as mentioned in guide.
4.  Try to login as a user created in step 2
5.  You'll see 403 Permission Denied error page.

## Your Environment

- Version used: v6.1.1

## Code references

Error log source: https://github.com/oauth2-proxy/oauth2-proxy/blob/73f00944861f223a5d66206f56c606d1a71cdd1b/oauthproxy.go#L817
Validator login for empty email: https://github.com/oauth2-proxy/oauth2-proxy/blob/d69fd6af22751974364e35cc697f9eaaaef160d3/validator.go#L90

**Comment by urbanpawel90** [comment]
I'll post the Pull Request today or tomorrow which fixes the issue.

**Comment by urbanpawel90** [comment]
I also wonder if it's not a bug in case we set `email-domain` to `*`. Shouldn't we allow empty emails then?

**Comment by JoelSpeed** [comment]
I think I would have expected a user to be allowed if they have no email and the wildcard was set. Not sure if this would constitute a breaking change or not 🤔

**Comment by urbanpawel90** [comment]
Good question @JoelSpeed. I would say that it's not breaking and it wasn't explicitly described in docs before. I think a lot of people could have expected that ALL emails will be validated as docs say `Use * to authenticate any email`.

**Comment by NickMeves** [comment]
> I think I would have expected a user to be allowed if they have no email and the wildcard was set. Not sure if this would constitute a breaking change or not 🤔

I've thought many times this line https://github.com/oauth2-proxy/oauth2-proxy/blob/ef08d01b982fa37a94ba31e6bbcf14452f970974/validator.go#L100 should be at the top before the blank returning false check.

I think when I last looked into it, this behavior is why so many token -> session converter parts of the code set the session.Email to claim.Subject if there's no claim.Email.

**Comment by urbanpawel90** [comment]
OK, guys. Regarding your comments here and in PR - I see that is going to be released with the next minor or major release. When do you plan such a release? When could we expect it to land in some official Docker image?

BTW. Are there any more actions required from my side for now?

**Comment by urbanpawel90** [comment]
One more thing which might be also the solution for security concerns, tool stability and probable fastest release date. Maybe we could introduce some extra flag to allow/disallow empty email (regardless of `email-domain` parameter)? 
By default it would disallow empty email as it does right now, so it won't be a breaking change, but some users (me for example ;) ) will be able to turn on the empty email users.

What do you think?

**Comment by avanier** [comment]
I get a sense that with what @macrame reported in #766 this might actually be due to the emails not being available in the checked claims. Either because they're not set properly by the mappers, or because the claims are not read properly.

I'm digging a bit more right now. I'm experiencing the same problem.

**Comment by avanier** [comment]
Nevermind, I have no idea what the problem is, and it's not the mappers.

**Comment by avanier** [comment]
Nevernevermind. It **was** the mappers.

The default mapper for groups in Keycloak does something, and it's not the right thing.

Creating a custom mapper for groups with the `Mapper Type` set to `Group Membership` does the trick. :tada:

**Comment by gustabart** [comment]
Hi,
I have the same problem. I think it is not okay for the proxy to fail if the email claim is empty.
The openid specification says nothing about this restriction.  
I think the --allow-empty-emails flag proposed by @urbanpawel90 is a good option.

I would like you to reconsider this issue.
Thanks!

**Comment by NickMeves** [comment]
@gustabart If you are using Keycloak I recommend you connect to it via the OIDC Provider instead of the Keycloak provider until this PR is merged: https://github.com/oauth2-proxy/oauth2-proxy/pull/1107

The `keycloak` provider is horribly out of date and missing functionality. We are looking to deprecate it once the OIDC-based Keycloak provider is setup instead.

**Comment by NickMeves** [comment]
Otherwise set `--email-domains` or whatever the flag is to `*`. That allows `SessionStates` that are missing the `Email` field by the email domain authorization check.

**Comment by gustabart** [comment]
Thanks for the reply Nick.
I am using the 'oidc' provider. I also tried --email-domains = * but unfortunately it doesn't work for empty email claims. Inspecting the validator.go (v7.1.0) code I can see:

```go
func newValidatorImpl(domains []string, usersFile string,
	done <-chan bool, onUpdate func()) func(string) bool {
	validUsers := NewUserMap(usersFile, done, onUpdate)

	var allowAll bool
	for i, domain := range domains {
		if domain == "*" {
			allowAll = true
			continue
		}
		domains[i] = fmt.Sprintf("@%s", strings.ToLower(domain))
	}

	validator := func(email string) (valid bool) {
		if email == "" {
			return
		}
		email = strings.ToLower(email)
		for _, domain := range domains {
			valid = valid || strings.HasSuffix(email, domain)
		}
		if !valid {
			valid = validUsers.IsValid(email)
		}
		if allowAll {
			valid = true
		}
		return valid
	}
	return validator
}
```
The first if is the problem, when email == "", the function returns regardless of whether **allowAll** is true.

**Comment by NickMeves** [comment]
If you are using this for Bearer auth, this is the fallback code for no `email` claim:

https://github.com/oauth2-proxy/oauth2-proxy/blob/5497310673a4527487cf8850fbfda53b442bace9/providers/oidc.go#L192

If you are interactive, and you still get nothing from the userinfo endpoint during the EnrichSession stage, I recommend you have in `--oidc-email-claim` and set it to `sub`. Then `--email-domains=*` will work on it.

**Comment by gustabart** [comment]
Ok, with --oidc-email-Claim set to sub, it works!  
Anyway, this is a workaround.  
I think a real solution is necessary. Thanks.
