### ISSUE TITLE
Azure JWT not passing signature upstream

### ISSUE THREAD

**Issue by zachaller** [oauth2-proxy/oauth2-proxy#771]
## Expected Behavior

I would expect the jwt passed upstream to including the signature

## Current Behavior

What we are currently getting is the header the data but no signature it just ends at the second period.

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJh<redacted>.
```

## Steps to Reproduce (for bugs)

Set `--pass-authorization-header=true` and then look upstream and notice the jwt is incomplete we use are using AzureAD

## Your Environment

- Version used: 6.1.1

**Comment by dev-cr-ka** [comment]
Had the same problem and got it working. Needed these four flags:

```
 - --set-authorization-header=true
 - --pass-access-token=true
 - --pass-authorization-header=true 
 - --pass-user-headers=true
```

**Comment by NickMeves** [comment]
Hmmm - I might need to defer to the Azure community that uses that provider (I have no experience with it myself)...

The area that takes your session's IDToken and puts it into the upstream `Authorization` header looks fine:

https://github.com/oauth2-proxy/oauth2-proxy/blob/a87beab1a06a439e0cb9a47d0000032d7eafa1e1/oauthproxy.go#L977

I've been seeing a decent amount of activity lately on Azure's more confusing uses of Access Tokens vs IDTokens (I think there's a few PRs trying to reconcile its more complex settings that were recently submitted).

I'll try to find time to take another glance at the provider to see if anything odds jumps out to me, but I don't think we've touched that provider in several versions besides some request builder refactors 🤔
