### ISSUE TITLE
Support for custom claim headers

### ISSUE THREAD

**Issue by gboor** [oauth2-proxy/oauth2-proxy#772]
## Expected Behavior

oauth2-proxy currently supports passing a number of claims as headers to the upstream by setting pass-basic-auth. It would be nice if we could add configurable headers for any claim. I don't always want to pass the whole token; in some cases I just want to pass groups, or roles, but this is currently not possible.

## Current Behavior

Claims that are passed as headers are fairly fixed. There is some that can be turned on and off, but nothing to random claims.

## Possible Solution

Add a config option for a list of claims to pass as headers, i.e.;

```
pass_claim_headers = [
  "groups",
  "roles"
]
```

And pass these as X-Forwarded-Groups and X-Forwarded-Roles. If the claim is a list, comma separate the values. If it's something more complex (like a whole object), it should probably be logged as a warning and dropped.

It would also be nice to allow for nested values, like;

```
pass_claim_headers = [
  "resource_access.name.groups"
]
```

Which should probably still be X-Forwarded-Groups

## Context

Some of the backends I have are very light weight and require only 1 value from the access token. I don't really want to add the overhead of adding in a JWT library and doing the token decoding, especially since it was already decoded in the proxy.

## Your Environment

- Version used: 6.1.1

**Comment by JoelSpeed** [comment]
I'm already refactoring the code to allow for this sort of custom injection, see #705 for the first part of that implementation. There was already some discussion about this in #631 that you may be interested in.

**Comment by gboor** [comment]
I can't believe I missed that one! It looks like my full use-case will be covered there, or am I missing something?

**Comment by JoelSpeed** [comment]
I think pretty much everything apart from your nested claims idea, we are talking about storing extra claims as part of a different issue IIRC though, so I think we have tracking issues for everything described here

**Comment by gboor** [comment]
I'll follow the other issue(s) then and close this one for now. Thanks for the heads up!
