### ISSUE TITLE
The page shows 403 Permission Denied with Invalid Account

### ISSUE THREAD

**Issue by Macrame** [oauth2-proxy/oauth2-proxy#776]
I started up the oauth2-proxy to run in a docker container, below is my args:(assume my domain is abc.com and my realm is abcdef)
```
--provider keycloak --http-address 0.0.0.0:8080 --upstream http://172.18.27.88:6000
--login-url https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/auth 
--redeem-url https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/token 
--validate-url https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/userinfo 
--email-domain * 
--cookie-secret aW1hZ2Vnb2ltYWmlZ29paWFn 
--client-id nexus --client-secret e65e1031-b122-4b86-9e38-cf2e432b74b8 
--scope openid --scope email  
--cookie-secure false
```
After authenticated successfully, there was a page showed 403 Permission Denied with Invalid Account

## Context

I use KeyCloak as my OIDC server and create my account with a correct email address.

## Your Environment

TLS is handled by the HAProxy server.

- Version used:
**quay.io/oauth2-proxy/oauth2-proxy:v6.1.1-amd64**

![image](https://user-images.githubusercontent.com/10723556/93160847-d6fd1080-f743-11ea-9fba-174b3aa3c0f0.png)

Here is the logs printed by oauth2-proxy:
```
172.17.0.1:52068 - - [2020/09/15 02:55:32] nexus-xxxx.abc.com GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36" 403 2672 0.000
172.17.0.1:52068 - - [2020/09/15 02:55:38] nexus-xxxx.abc.com GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36" 302 300 0.000
172.17.0.1:52068 - ayden@abc.com [2020/09/15 02:55:40] [AuthFailure] Invalid authentication via OAuth2: unauthorized
172.17.0.1:52068 - - [2020/09/15 02:55:40] nexus-xxxx.abc.com GET - "/oauth2/callback?state=71e970b716ca881aa065ab4fe22669d1%3A%2F&session_state=bfaef82c-42f5-4438-a8b5-dd7f2e9c7f4e&code=56f1b0b4-c1f6-4fb3-9f05-902a1f6effc2.bfaef82c-42f5-4438-a8b5-dd7f2e9c7f4e.c56b56d9-063f-422c-8772-004b9e21634a" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36" 403 338 0.021
```

**Comment by burnedikt** [comment]
It think you also need to set the `--keycloak-group` parameter indicating which group a authenticating user needs to belong to. And the group name should start with a slash as described [here](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/2_auth.md#keycloak-auth-provider)

**Comment by Macrame** [comment]
I tried to use `--keycloak-group` parameter and it did not effect. Is there any completed example that guides user to finish this process step by step?
By the way, today I deployed another one running on Kubernetes to protect my prometheus web page, it worked well. The main different is I used a configuration file as configmap on kubernetes but pamareters on docker(The failed example).
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-proxy-config
  namespace: monitoring
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  oauth2-proxy.cfg: |
    http_address = "0.0.0.0:8080"
    https_address = ":443"
    reverse_proxy = true
    redirect_url = "https://prometheus-dashboard-test.abc.com/oauth2/callback"
    upstreams = [
        "http://prometheus:9090/"
    ]
    pass_host_header = true
    email_domains = [
        "*"
    ]
    cookie_secure = false
    cookie_secret = "aW1hZ2xxxxxxxlZ29pbWFn"
    client_id = "prometheus-dashboard-test"
    client_secret = "185ce3c5xxxxxxxxxxxab559e859"
    provider = "keycloak"
    login_url = "https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/auth"
    redeem_url = "https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/token"
    validate_url = "https://oidc.abc.com/auth/realms/abcdef/protocol/openid-connect/userinfo"
    scope = "openid"
```

By the way, how to specify more than one scope? I tried 
```
scope =  [
   "openid" ,
   "email"
]
```
Regardless of whether there is the comma, it complains `fail to parse xxxx` than means it expects a string but receives an interface.

**Comment by Macrame** [comment]
I found the key point is `--email-domain * ` should be `--email-domain "*" `.  It'll fail if you set email domain to * without **quotes**.
