### ISSUE TITLE
Session expiry is not validated if token refresh is disabled

### ISSUE THREAD

**Issue by Chippiewill** [oauth2-proxy/oauth2-proxy#780]
When the cookie duration is longer than the session duration of the upstream provider and token refresh is disabled there is no check that the session is still valid which means a browser can send valid cookies with invalid sessions and oauth2 proxy will accept it.

## Expected Behavior

When the session has expired requests to `/oauth2/auth` should not return 202 Accepted.

## Current Behavior

When session has expired, but the cookie has not, `/oauth2/auth` returns 202 Accepted despite the session having expired and containing invalid access tokens.

## Possible Solution

A fix and a sensible mitigation:

- Cookie durations should be bounded by the session time if refresh is disabled
- Session expiries should always be checked, even if refresh is disabled

The specific problematic code is here https://github.com/oauth2-proxy/oauth2-proxy/blob/d69fd6af22751974364e35cc697f9eaaaef160d3/pkg/middleware/stored_session.go#L115-L132, on line 116 it checks if refresh is disabled and skips the refresh code - however the only expiry validation check is on line 129 and is never run. Having the expiry check inside the refresh function feels wrong to me, it should be always checked (even if the session was just refreshed) directly after `refreshSessionIfNeeded` is called in `getValidatedSession`.

## Steps to Reproduce (for bugs)

(Other steps might reproduce but this is our specific setup)

- Setup OIDC provider with 10 hour sessions
- Setup oauth2 proxy with 12 hour cookies and no refresh
- Authenticate with oauth2 proxy
- Wait 10 hours
- Try to reuse session
- oauth2 proxy returns 200 on /oauth2/auth but the access token expiry is in the past

## Context

When users reuse a very old session/cookie >10 hours our oauth2 proxy deployment continues to accept the sessions as valid but our backend services reject the underlying auth tokens because they're expired.

## Your Environment
- oidc provider against okta
- running in k8s, container/pod/app config:
```
    Image:         quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    Image ID:      docker-pullable://quay.io/oauth2-proxy/oauth2-proxy@sha256:791aef35b8d1d2a325028b188d5a650605d69985a0dab1233c06079e7321eee0
    Port:          4180/TCP
    Host Port:     0/TCP
    Args:
      --http-address=0.0.0.0:4180
      --provider=oidc
      --oidc-issuer-url=<redacted>
      --cookie-expire=12h0m0s
      --cookie-name=<redacted>
      --cookie-secure=true
      --cookie-samesite=lax
      --email-domain=<redacted>
      --redirect-url=<redacted>
      --pass-access-token=true
      --set-xauthrequest=true
      --scope=openid profile email <redacted>
      --skip-jwt-bearer-tokens
      --extra-jwt-issuers=<redacted>
    Environment Variables from:
      login-latest  Secret with prefix 'OAUTH2_PROXY_'  Optional: false
```

- Version used: v6.1.1

**Comment by JoelSpeed** [comment]
I think we should treat this as a bug, do you think you'd be able to raise a fix?

**Comment by JoelSpeed** [comment]
I've discussed this with other maintainers today and we agreed that we are not going to fix this issue.

Our cookied sessions are not necessarily tied to the lifetime of your ID or Access Tokens. If you wish to tie them together, you can set the cookie-expire to match the lifetime of your ID/Access token.

There are use cases out there where you may want to have the cookied session live for a longer period than your access token.

**Comment by cr1st1p** [comment]
I bumped into the same issue as the reporter. Oauth2-proxy v7.2.0

I do not know extremely well the oidc/oauth details but I feel that he is at least partially right, and you dismissed his report way too quick.

You are saying that you do not want to correlate lifetime session of cookie with lifetime session of an access token.
Ok, but still, as the code is, and *exactly* where the original author is mentioning, you completely ignore to do any check to see if the Access token has expired - *regardless* of the session timing.

I think you should add in the condition above also the check "|| session.IsExpired()" (check which happens now ONLY if session *refresh* time is expired....)
In my case, with Keyloack as oidc, it is setting an access token expiration of 5 minutes. I think also that documention is saying that it does not support 'cookie-refresh' or something. So after 5 minutes, the request goes with success through oauth2-proxy but the end application is saying 'jwt expired'.

And the only way to make it work was to enable and *tie* the cookie refresh time to the access token validity time (I had to set cookie-refresh=4m).

So I'd say it is a bug, and it looks like a critical one to me.

**Comment by houz42** [comment]
> There are use cases out there where you may want to have the cookied session live for a longer period than your access token.

Sorry for replying to a closed issue. But can you please explain more about such use cases. And I'm wondering, if such use cases need the cookie live longer, then is it possible that checking and refreshing the upstream token without refreshing the cookied session. And will the fix be accepted if the solution exists?

**Comment by zfrhv** [comment]
@JoelSpeed could you please revisit this issue?

**Comment by NeurekaSoftware** [comment]
This is a major security issue for me, and I cannot use oauth2-proxy because of this. It basically means I cannot revoke access to a resource because the cookie is still valid despite the token being invalid.

**Comment by JoelSpeed** [comment]
There's another thread open about this that I responded to recently. We cannot change this behaviour without it being considered a breaking chanage, and so the behaviour must be changed on the move to v8. However, I still believe in allowing the old use case.

If we want to solve this, my suggestion is to create a new flag, `--insecure-ignore-token-expiration` that defaults, for now, to `true`. The flag would then control whether or not, expired ID/Access Tokens cause a session to be considered invalid or not. We could change the default then as we move to v8.

> It basically means that I cannot revoke access to a resource because the cookie is still valid despite the token being invalid.

Typically, the way this was expected to work was that the token refresh would be the thing that kicks out. The token is valid for a period, and you cannot revoke ID tokens once issued. What you can do however, is prevent the refresh. By tying the two times together, and forcing a refresh at the end of the ID Token validity, you can revoke tokens as they expire.

I haven't run this project in production in 5 years now, but that certainly is how we used to get around this issue. It meant, for us at least, we were exposed for up to an hour. If we needed immediate revocation, then we could rotate keys at the IDP layer which would force everyone to re-authenticate.
