### ISSUE TITLE
Google Group is required as setting, but actually is optional according to the docs

### ISSUE THREAD

**Issue by marcus-sa** [oauth2-proxy/oauth2-proxy#781]
## Expected Behavior
Being able to start the service without specifying a Google Group and authorize a user successfully.

As the section states [RESTRICT AUTH TO SPECIFIC GOOGLE GROUPS ON YOUR DOMAIN. (OPTIONAL)](https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#restrict-auth-to-specific-google-groups-on-your-domain-optional) the setting shouldn't be mandatory.

**EDIT:**
I've just realized that a Google Service Account key is also mandatory. which it shouldn't be since it's only used when the `google-group` setting is applied.

## Current Behavior
```
[2020/09/17 11:46:52] [logger.go:490] invalid configuration:
  missing setting: google-group
```

## Possible Solution
It should be optional

## Steps to Reproduce (for bugs)
Don't think its needed, pretty self explanatory.

## Context
Pretty much been trying to get OAuth2 Proxy to work for almost 3 days now without any luck whatsoever.

## Your Environment

- Version used: `quay.io/oauth2-proxy/oauth2-proxy:v6.1.1`

**Comment by JoelSpeed** [comment]
As far as I'm aware that option isn't necessary normally, which provider are you using?

**Comment by marcus-sa** [comment]
@JoelSpeed Google ?
It's not about whether or not it's necessary, it's about it being currently an requirement in `oauth2-proxy` 😁

**Comment by JoelSpeed** [comment]
Got ya, sorry, I meant normally you aren't asked for that option, so it must be a provider specific thing 😅 

https://github.com/oauth2-proxy/oauth2-proxy/blob/55a941b76e15aaf3abd214b24365ac0113c44dba/pkg/validation/options.go#L197-L207

Looking at the above code, it seems there are three options that are all required together, do you have one of `google-groups`, `google-admin-email` or `google-service-account-json` set? I don't think you need any of these if you don't want groups

**Comment by marcus-sa** [comment]
@JoelSpeed you were indeed right! Thanks a lot :+1: 
I went through the CLI flags before I read the specific provider guide and assumed that I had to provide all the flags.

**Comment by veerendra2** [comment]
Hi @JoelSpeed, we ran into same issue for the version `v7.4.0`. From the `v7.4.0` docs, say "[Restrict auth to specific Google groups on your domain. (optional)](https://oauth2-proxy.github.io/oauth2-proxy/7.4.x/configuration/oauth_provider/#google-auth-provider)" 

```
[2025/07/08 14:06:57] [main.go:54] invalid configuration:
missing setting: google-group
```

Looking the `v7.4.0` code -> https://github.com/oauth2-proxy/oauth2-proxy/blob/v7.4.0/pkg/apis/options/legacy_options.go#L719-L723 


I can't find any `if` conditions and it seems mandatory?!

If it is not optional, can you agree, documentation needs to update?
