### ISSUE TITLE
Question: Can OAuth2-Proxy be configured to only validate JWTs and not redirect to provider

### ISSUE THREAD

**Issue by lyndon160** [oauth2-proxy/oauth2-proxy#785]
My use case is that I have an ingress that needs to accept requests from users, as well as requests from machines/clients.

In this particular case, I am using Keycloak as an OIDC provider, and the machine clients are able to get their own JWT tokens.

The following ENVs are used to enable this type of flow:
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"

When a user's session expires or does not exist, the user is redirected to the provider page, this is expected.

However, the same thing happens for a machine call, this is not ideal as the response code from a login page is a 200, meaning that it can't handle the error. 

With the correct configuration, the provider is capable of throwing 403s in this case. However, this configuration depends on the provider, and not all support it in the same way.

**Is there a way to configure OAuth2-proxy to stop from redirecting to the provider login page (and provide 403) when either a token is not present, or a token is invalid?**

## Expected/desired Behavior

For a machine flow, we should be able to configure it to do the following

No  bearer token present -> 403 (No redirect)

Expired or invalid bearer token -> 403 (No redirect)

## Current Behavior

No bearer token present -> Redirect to provider login

Expired or invalid bearer token -> Redirect to provider login

## Your Environment

      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_CLIENT_ID: test-cloud
      OAUTH2_PROXY_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${SESSION_KEY}
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SECURE_DOMAIN: "localhost"
      OAUTH2_PROXY_UPSTREAMS: http://whoami:80/
      OAUTH2_PROXY_REDIRECT_URL: http://whoami.localhost:8080/oauth2/callback
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_OIDC_ISSUER_URL: <REMOVED>
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_AUTH_LOGGING: "true"
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_REQUEST_LOGGING: "true"
      OAUTH2_PROXY_STANDARD_LOGGING: "true"
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"
      OAUTH2_PROXY_COOKIE_DOMAIN: whoami.localhost
      OAUTH2_PROXY_PREFER_EMAIL_TO_USER: "true"
      OAUTH2_PROXY_SESSION_STORE_TYPE: "cookie"
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://cookie-monster:6379
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"

- Version used: 6.1.1

**Comment by JoelSpeed** [comment]
> With the correct configuration, the provider is capable of throwing 403s in this case. However, this configuration depends on the provider, and not all support it in the same way.

Could you elaborate on this point please? Do you have a workaround?

**Comment by lyndon160** [comment]
@JoelSpeed thanks for the response.

By configuring the Keycloak client used by OAuth2-Proxy to only allow service accounts/ client-credentails flow, when the client is redirected to keycloak after presenting an invalid token, keycloak returns a 403 saying "unsupported_response_type", presumably because the standard login flow has been disabled on the client.

This solves the issue, in that it lets an OAuth machine client know that there's something wrong with it's session. As mentioned before, ideally, with the correct config (redirects turned off somehow), a 403 could be thrown straight from OAuth2-Proxy.

Keycloak client config for achieving 403 on invalid session (after OAuth2-Proxy redirects):
![Screenshot 2020-09-21 at 07 44 40](https://user-images.githubusercontent.com/5150703/93738693-53796e80-fbde-11ea-9cc9-de71f2441d4e.png)

Keycloak 403 response:
![Screenshot 2020-09-21 at 07 38 58](https://user-images.githubusercontent.com/5150703/93738701-55dbc880-fbde-11ea-9cb2-162db32ec231.png)

**Comment by JoelSpeed** [comment]
Right, that makes a lot more sense. I had thought initially that you'd found a workaround for configuring OAuth2 Proxy to make it work.

I'm not too familiar with machine to machine authentication, but I know @NickMeves is so he may have some input on this issue

I guess my question would be how do you envisage the proxy being able to tell the difference between the humans and machines to return the correct response?

**Comment by NickMeves** [comment]
https://github.com/oauth2-proxy/oauth2-proxy/blob/55a941b76e15aaf3abd214b24365ac0113c44dba/oauthproxy.go#L857

I think I might not be hitting this issue because my machine to machine use cases are consuming a JSON REST API with the proper request headers set.

I feel like this PR that went stale is tangentially related to this? https://github.com/oauth2-proxy/oauth2-proxy/pull/555

**Comment by NickMeves** [comment]
Is `403 Forbidden` instead of `401 Unauthorized` a hard requirement for this use case?

**Comment by lyndon160** [comment]
@NickMeves thanks for this. It does look like #555 is related.

Currently, the implementation you have shown fits my use case quite well, but I'm concerned around the points raised in #555, such as support for GRPC, and other protocols.

In the interest of not changing clients (in some cases this is not possible), I agree with @JoelSpeed on https://github.com/oauth2-proxy/oauth2-proxy/issues/551#issuecomment-682431877 that having a user option for defining request headers would be useful.

If the other issues and PRs related to this go stale, I'd be happy to create a PR implementing this as well as adding details to the docs around its support for SPA and m2m.

**Comment by p53** [comment]
it would be good also to turn off using sessions => for m2m you don't usually set cookies...

**Comment by p53** [comment]
it would be also good to turn off session, usually with m2m auth you are not setting cookies...

**Comment by JoelSpeed** [comment]
When you receive a request that does have the correct M2M auth, it will load this over trying to load a cookied session.

What behaviour are you seeing that you would want to disable when using M2M?

**Comment by p53** [comment]
i would like to turn off claim validation completely, i am doing claim validation on opa for greater flexibility...

**Comment by Djiit** [comment]
Also interested in this for M2M flows. Can we help in any way ?

**Comment by NickMeves** [comment]
I have a tentative fix in this WIP PR for the bug that arose in v6.0.0 that broke M2M bearer auth for non-OIDC providers (keycloak & gitlab I think, maybe google). https://github.com/oauth2-proxy/oauth2-proxy/pull/869

Context on the bug: https://github.com/oauth2-proxy/oauth2-proxy/issues/773

I have a blog post on setting all this up that should be published later today once my editors approve, I'll post that here for context when it is up.

**Comment by NickMeves** [comment]
https://medium.com/in-the-weeds/service-to-service-authentication-on-kubernetes-94dcb8216cdc
