### ISSUE TITLE
OAuth 2.0 token exchange flow

### ISSUE THREAD

**Issue by a1tan** [oauth2-proxy/oauth2-proxy#792]
Is there a plan to implement OAuth 2.0 token exchange flow linked below? Or is it already implemented and I am missing it?

https://tools.ietf.org/html/rfc8693
https://www.keycloak.org/docs/latest/securing_apps/#_token-exchange

**Comment by JoelSpeed** [comment]
As far as I'm aware this is not implemented, nor have we planned to implement this so far.

Could you estimate how much work and roughly what would be needed to integrate this flow with what we have already?
