### ISSUE TITLE
Oauth2 Proxy should also be able to perform silent login when Accept: application/json header is set

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#802]
## Expected Behavior

With:

```
--prompt=none
--skip-provider-button=true
```

is set.

If 'Accept: application/json' is set in the header of the user request and a user is logged on to the IDP, but no session cookie has been set for the application, the Oauth2 proxy will silently log the user on with prompt=none, and if this is unsuccessful, 401 unauthorized will be responded.

## Current Behavior

If `Accept: application/json` is set, the Oauth2 proxy skips the oauth2 flow to login the user silently.
```
session, err := p.getAuthenticatedSession(rw, req)
	switch err {
	case nil:
		// we are authenticated
		p.addHeadersForProxying(rw, req, session)
		p.serveMux.ServeHTTP(rw, req)

	case ErrNeedsLogin:
		// we need to send the user to a login screen
		if isAjax(req) {
			// no point redirecting an AJAX request
			p.ErrorJSON(rw, http.StatusUnauthorized)
			return
		}

		if p.SkipProviderButton {
			p.OAuthStart(rw, req)
		} else {
			p.SignInPage(rw, req, http.StatusForbidden)
		}

	default:
		// unknown error
		logger.Errorf("Unexpected internal error: %v", err)
		p.ErrorPage(rw, http.StatusInternalServerError,
			"Internal Error", "Internal Error")
	}
```

## Possible Solution

If `Accept: application/json` is set as header in the user request, the oauth2 proxy should also be able to silenty login the user and respond with a json response in case of an error.

## Context

If a user has logged in and is already authenticated for backend api requests for an application, I want to enable the user also access another backend api application that requires a different access token.

## Your Environment

I have different backend microservices that are registered as app in my IDP. Via different frontend clients like single page applications I want to send authenticated requests to these backend microservices. In between I use oAuth2 proxy to handle sessions and tokens.
When changing pages, it can happen that the user suddenly communicates via the Frontend Client with another backend microservice, for which he must also be authorized. For this backend microservice, however, a different access token is required because, for example, other scopes are important. The oAuth2 Proxy should get such a possible access token from the IDP, if the user is logged in there.

- Version used:
v6.1.1

**Comment by JoelSpeed** [comment]
Maybe I'm missing something, but what exactly is creating the request with the `Accept: application/json`, is this some sort of SPA or something? 

Typically a request that comes through with that header is an ajax request, will ajax requests follow redirects?

**Comment by Bibob7** [comment]
Yes correct, this could be a SPA.

Yes Ajax requests should follow redirects. Only CORS policies have to be considered, if I'm not mistaken.

**Comment by JoelSpeed** [comment]
If that's the case, then perhaps we need to make this kind of behaviour configurable. We have had some discussion in the past about trying to integrate an option that allows users to define which requests should get a 401 vs which requests should get redirected, but I don't think it went anywhere in the end

I believe #551 may be related to this conversation
