### ISSUE TITLE
Unable to get the Auth failure logs on incorrect password attempt

### ISSUE THREAD

**Issue by nehap4** [oauth2-proxy/oauth2-proxy#803]
I have configured Azure as auth provider for the oauth2-proxy container running in my local kubernetes setup..Once I try to login using correct username password I am able to see the "AuthSuccess" logs.However in correct password entered during login doesnt give my "AuthFailure" logs.

I have referred following page to refer the types of logs:
https://oauth2-proxy.github.io/oauth2-proxy/configuration

Is there any configuration required to get the AuthFailure logs? or what are the scenarios in which AuthFailure logs come.

- Version used:v5.1.1

**Comment by JoelSpeed** [comment]
OAuth2 Proxy doesn't ever know if you fail to log in on the provider side, you aren't entering your password into OAuth2 Proxy, you're entering into the provider.

Typically, you would only every see AuthSuccess if the identity provider has accepted the login.

For AuthFailure logs, you would see these if the user logs in correctly with the identity provider but they don't pass the authorization checks within the proxy. For example, if their email address doesn't match the `email_domains` option.
