### ISSUE TITLE
unknown flag: --oidc-groups-claim when using image v6.1.1

### ISSUE THREAD

**Issue by piotrgwiazda** [oauth2-proxy/oauth2-proxy#807]
I am getting an error
```
unknown flag: --oidc-groups-claim 
```
when using image quay.io/oauth2-proxy/oauth2-proxy:v6.1.1 which is current latest
Then in logs I have a usage info, and the oidc-groups-claim is not on the list

## Expected Behavior

oidc-groups-claim and allowed-group should work as in documentation

## Current Behavior

Proxy won't start with --oidc-groups-claim parameter set

## Possible Solution

--
## Steps to Reproduce (for bugs)

Start a container quay.io/oauth2-proxy/oauth2-proxy:v6.1.1  with --oidc-groups-claim option set

## Context

Tryling to limit access to a resource to given roles only (set as "roles" claim rather than "groups" in JWT)

## Your Environment

Running in Kubernetes

- Version used: 6.1.1

**Comment by r-kotagudem** [comment]
I think oidc-groups-claim will be in release v7.0

**Comment by piotrgwiazda** [comment]
Ok, so it seems that the public documentation is a little bit ahead.

**Comment by xxxbobrxxx** [comment]
Can you please estimate when v7.0 will be released? Thanks!

**Comment by r-kotagudem** [comment]
@JoelSpeed  can you please let us know the estimated time for release v7.0

**Comment by xxxbobrxxx** [comment]
I tried to use this feature with **oidc** provider and Kubernetes Ingress with auth-url technique: https://www.digitalocean.com/community/tutorials/how-to-protect-private-kubernetes-services-behind-a-github-login-with-oauth2_proxy
Looks like this combination can not work out of the box because it causes cyclic redirects because:

- proxy returns 403 if token has no required group
- nginx redirects to .../start URL
- OIDC server provides token
- proxy returns 403 because token again has no required group...

May be you have some recipe for this case? Thanks!

**Comment by JoelSpeed** [comment]
Apologies for the docs not representing the current release, we are aware of the issue (#550) and are hoping to come up with a solution for it eventually.

We had our last release at the end of August so I would expect we would cut v7 no later than the end of November, but we may decide to cut it earlier if we get a reasonable number of PRs merged. I need to evaluate all the upcoming breaking changes and try to make sure we capture as many as possible in this release.

> proxy returns 403 if token has no required group
> nginx redirects to .../start URL

Can you share a snippet of your Nginx configuration? Nginx should only be redirecting to the start on a 401 response, not on a 403. I would expect the OAuth2 Proxy to show some unauthenticated page if the user is not in the correct group, are you not seeing this?

**Comment by xxxbobrxxx** [comment]
Sorry my report was not exact. I talked about feature introduced in commit https://github.com/oauth2-proxy/oauth2-proxy/commit/9d59519a96c5e57ac858473bcd4ca9d411a5f679 
We tried to use new `--allowed-group` feature.
Sample oauth2 configuration:
```OAUTH2_PROXY_CLIENT_SECRET=***
OAUTH2_PROXY_COOKIE_SECURE=true
OAUTH2_PROXY_REDIRECT_URL=https://oauth2.subdomain.example.net/oauth2/callback
OAUTH2_PROXY_COOKIE_DOMAINS=.subdomain.example.net
OAUTH2_PROXY_CLIENT_ID=subdomain.example.net
OAUTH2_PROXY_PROVIDER=oidc
OAUTH2_PROXY_ALLOWED_GROUPS=access
OAUTH2_PROXY_EMAIL_DOMAINS=example.net
OAUTH2_PROXY_OIDC_GROUPS_CLAIM=roles/subdomain.example.net
OAUTH2_PROXY_HTTP_ADDRESS=:4180
OAUTH2_PROXY_SCOPE=openid email profile
OAUTH2_PROXY_COOKIE_SECRET=***
OAUTH2_PROXY_WHITELIST_DOMAINS=.subdomain.example.net
OAUTH2_PROXY_OIDC_ISSUER_URL=https://iam.example.net/auth/realms/realm
OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=Provider
```

Sample configuration of protected service: 

```
nginx.ingress.kubernetes.io/auth-signin: https://oauth2.subdomain.example.net/oauth2/start?rd=https://$host$escaped_request_uri
nginx.ingress.kubernetes.io/auth-url: https://oauth2.subdomain.example.net/oauth2/auth
```

This configuration causes circular redirect because auth-url returns 403 on `--allowed-group` check.
I want to propose check `--allowed-group` in both `/oauth2/auth` and `/oauth2/callback` URLs - it will make possible to display 403 error to user explicitly instead of circular redirection.

For current implementation there is a workaround:

```
nginx.ingress.kubernetes.io/auth-signin: https://oauth2.subdomain.example.net/oauth2/sign_in?rd=https://$host$escaped_request_uri
nginx.ingress.kubernetes.io/auth-url: https://oauth2.subdomain.example.net/oauth2/auth
```

It will not cause circular redirection, but on 403 error user will always see login page and will not see it - he will see login page.

Sorry for my english =)

**Comment by grebois** [comment]
@JoelSpeed how should I configure the groups when my JWT looks like this:

```
{
  “iss”: “ redacted”,
  “aud”: [
    “ redacted”
  ],
  “groups”: “|group1|group2|“,
  “mail”: “ redacted”,
  “sub”: “ redacted”,
  “at_hash”: “ redacted”,
  “c_hash”: “ redacted”,
  “iat”: redacted,
  “exp”: redacted
}
```

is it possible?

**Comment by NickMeves** [comment]
This PR is looking to handle string values for a groups claim: https://github.com/oauth2-proxy/oauth2-proxy/pull/816

It will unfortunately treat that whole string as a single group though.

As an aside, I know `groups` isn't an official OIDC claim, but there's pretty universal conventions most IdPs have established. Why do some IdPs keep doing weird stuff like this 🤣

**Comment by JoelSpeed** [comment]
I'd be intrigued to know which IDP is using pipes like that as the group separator 🤔  Is there a way to configure it?

**Comment by anannaya** [comment]
I am using out proprietarily OIDC provider , which intern return profile like this . All the Groups information is part of memberof   I am using set_xauthrequest option Any idea why  X-Auth-Request-Groups  header is missing ?  Email and User I am able to get it.  What I am missing here ?
 {
     "access_level": "4",
     "sub": "xxxxxx",
     "manager": "uid=xxxxx,OU=dddddd,O=cco.xxxxx.com",
     "company": "xxxxxxxxxx.",
     "fullname": "Anand Nayak",
     "memberof": [
         "CN=EMSUDEMY,OU=Groups,O=cco.xxx.com",
         "CN=all-xxxx-people,OU=xxxx Groups,O=cco.xxxx.com"
     ],
     "given_name": "Anand",
     "title": "xxxxxxxxx",
     "family_name": "Nayak",
     "email": "ananayak@xxxxxx.com"
 }

**Comment by r-kotagudem** [comment]
> This PR is looking to handle string values for a groups claim: #816
> 
> It will unfortunately treat that whole string as a single group though.
> 
> As an aside, I know `groups` isn't an official OIDC claim, but there's pretty universal conventions most IdPs have established. Why do some IdPs keep doing weird stuff like this

@NickMeves even our IDP(Oracle 12c oauth provider )sends groups claim as single concatenated string of groups like below

"SSO_GROUP": "GMA:AFS:MBOND:ZOO"

and oracle has no way to modify of the format of the claim to list instead of string does #816 addresses my requirement

**Comment by NickMeves** [comment]
This space is unfortunately all over the place 😭 

I'm thinking we do our best to make sure the extraction -> header portion works in all cases ([]string, string, []interface{}, interface{}) so just processing an IDToken doesn't crash people.  And we at least get the data into an `X-Forwarded-Groups` header for the backend to possibly handle.

Where I'm fearful is the internal `allowed-groups` authorization logic. If we start trying to handle all the bazillion corner cases for formats that seem to be arising to parse groups into an array is looking like it will be a mess.

So for that reason, I want to punt on that aspect until potentially after V8 where we have structured configs to make this more configurable.

**Comment by r-kotagudem** [comment]
> This space is unfortunately all over the place 
> 
> I'm thinking we do our best to make sure the extraction -> header portion works in all cases ([]string, string, []interface{}, interface{}) so just processing an IDToken doesn't crash people. And we at least get the data into an `X-Forwarded-Groups` header for the backend to possibly handle.
> 
> Where I'm fearful is the internal `allowed-groups` authorization logic. If we start trying to handle all the bazillion corner cases for formats that seem to be arising to parse groups into an array is looking like it will be a mess.
> 
> So for that reason, I want to punt on that aspect until potentially after V8 where we have structured configs to make this more configurable.

@NickMeves  got it. Thank you very much

**Comment by yburke94** [comment]
Hi,

@JoelSpeed Are you guys any closer to shipping v7?

I also require this functionality and do not want to bake my own image if the official release is round the corner.

**Comment by NickMeves** [comment]
January most likely. With the holiday season approaching, there will be a lot less work until 2021 and we are back in normal working cadences.

**Comment by rickardp** [comment]
Any chance enabling pushing the prereleases to the repo from your GH actions? It would be highly useful integrating and evaluating features such as this while waiting for the proper release.

**Comment by JoelSpeed** [comment]
I'm not a fan of pushing images for master branches. We've had (numerous times) issues in the past with breaking people's installations by continuously pushing changes.

Having a constantly updating docker tag can encourage people to use it, which I would rather not do.

I would much prefer those who want to test the code, make the effort to build an image themselves, thereby taking their own conscious action to update their installations.

Our docker images are designed in such a way that everything is self contained, you can either `make docker` or `docker build .` and it will build the image with minimal set up (assuming you have docker installed)

**Comment by georgewfisher** [comment]
I'm really looking forward to this feature. Any chance of a release forecast? Are we looking at days, weeks, or perhaps waiting until Feb? I'm wondering whether I should hack in a temporary solution in a local build to unblock myself or if it's almost here.

**Comment by JoelSpeed** [comment]
We are tracking the final two PRs to go across the line in the [v7 project](https://github.com/oauth2-proxy/oauth2-proxy/projects/3). Both PRs are very near to completion and should hopefully merge over the next few days, once they have done so we will start the release process. I would expect us to have this sorted by EOW if everything goes smoothly
