### ISSUE TITLE
How to invoke a backend api secured with oauth2-proxy from cli

### ISSUE THREAD

**Issue by koyadume** [oauth2-proxy/oauth2-proxy#809]
I have a VueJS application, a number of REST APIs and oauth2-proxy deployed on docker. Nginx is running on docker as reverse proxy and using oauth2-proxy as authentication proxy. I have configured oauth2-proxy against auth0 and backend api calls from VueJS app are working fine after successful authentication in Auth0. Now I want to test these backend APIs from a non browser client (e.g. cli, postman etc) but wondering how to proceed on this. My understanding is that first I need to get an access token from Auth0 for a user and then pass this token as bearer token in Authorization header. However I am not sure if oauth2-proxy handles this usecase or not. While I can call backend APIs directly in my local development environment, this will not be possible in production where APIs will be invoked though nginx only.

## Context
I want to invoke my backend APIs from a non browser client for testing purpose or for integration with other non web applications.

- Version used: v6.1.1

**Comment by p53** [comment]
you would need to make curl request with bearer token+set saving cookies+accept header application/json as fas as i know...i created issue for this https://github.com/oauth2-proxy/oauth2-proxy/issues/811

**Comment by JoelSpeed** [comment]
You will want to enable the `--skip-jwt-bearer-tokens` option which then allows requests with a valid `Authorization: Bearer <token>` header to pass through the proxy as normal

**Comment by p53** [comment]
@koyadume you must also give there also extra-issuers because main oidc-issuer-url is used for auth_code flow - user authentication

**Comment by JoelSpeed** [comment]
If you are using `--skip-jwt-bearer-tokens` and the `oidc` provider (and hence `oidc-issuer-url`) we have logic to include the OIDC issuer from there as jwt issuer already, so no need for `extra-jwt-issuers` unless they aren't the main OIDC issuer

**Comment by koyadume** [comment]
@JoelSpeed  - Any reason why `--skip-jwt-bearer-tokens` default value is `false`? IMO it should be `true` because that is the requirement in almost all the scenarios. Otherwise one will end up with an API which can be invoked from browser based clients ONLY and so will not be very useful.

**Comment by JoelSpeed** [comment]
> Otherwise one will end up with an API which can be invoked from browser based clients ONLY and so will not be very useful.

The primary use case for OAuth2 Proxy historically has been to protect browser based applications (eg some sort of internal documentation website, or a UI like the Kube dashboard or Grafana) and we didn't want to break that contract as we've been adding new features.

We may be at the point where actually more people are using this to protect APIs than applications but that definitely wasn't the case even a year ago (because this feature had only just been introduced) and I have no evidence to say either way at the moment. My gut feeling is to leave it as is as exposing more features like this as on by default expands the surface area for attacks for the average user.

**Comment by JoelSpeed** [comment]
Closing this as we've not had any responses recently, hope my last comment helped to understand the primary purpose of the project

**Comment by gyanprakash48** [comment]
hello @JoelSpeed  when i am trying this , i am facing  this error 

 "unable to verify bearer token, failed to verify token: oidc: id token issued by a different provider, expected "https://login.microsoftonline.com/<tentant>/v2.0" got "https://sts.windows.net/<id>/"

What i am doing 

1. oprinting   x-auth-request-access-token   to as user when they call /api/gettoken enpoind  )
2. But when they are using this token in Postman, getting above error. I am confused as token  header is attached  on auth header by nginx based on microsoft login itself  Any suggestion would be much appreciated

**Comment by JoelSpeed** [comment]
@gyanprakash48 I don't know if you got anywhere with this, but the issue you're seeing is because you are mixing the Azure v1 and v2 API endpoints, I'd suggest reviewing the Azure issues and docs as folks have got things working with Azure v2 now and the error you've seen has definitely been posted around here before

**Comment by umershaekoor** [comment]
Hi, 

How would the signing out work when securing an api? We surely wouldn't need to call the /oauth2/sign_out/ endpoint, right? Because that identifies an individual session via cookies and which are ofcourse not available while working with an api.

**Comment by koyadume** [comment]
There is no concept of cookie and session when securing an API. While invoking an API, you will need to pass JWT token which comes with some validity. You get a new JWT token once the old one expires.

**Comment by umershaekoor** [comment]
@koyadume Thankyou for your reply. 

The token that you set as the bearer token was the id token that you got from your provider or from the oauth2 proxy?

**Comment by tuunit** [comment]
If you want to use the bearer token to authenticate with oauth2-proxy. It currently most be an id_token or access_token in JWT format. Some IDPs like ForgeRock don't provide access_tokens as jwt but a random string. Which is allowed by the official spec of oauth2 but currently not supported by oauth2-proxy.

**Comment by yemaney** [comment]
> If you want to use the bearer token to authenticate with oauth2-proxy. It currently most be an id_token or access_token in JWT format. Some IDPs like ForgeRock don't provide access_tokens as jwt but a random string. Which is allowed by the official spec of oauth2 but currently not supported by oauth2-proxy.

Hi. Is this still the case? I tried with  github provider. Set `- --skip-jwt-bearer-tokens=true` in args and made a curl request:
I'm passing a gh token in the header. Should I be passing something else

```sh
$ curl -H "Authorization: Bearer ghp_xxxxLt" https://domain.com
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

$ kubectl logs my-release-oauth2-proxy-b9c96bc8d-s95dz 
[2025/10/16 19:07:20] [proxy.go:83] mapping path "/dev/null" => file system "/dev/null"
[2025/10/16 19:07:20] [oauthproxy.go:162] Skipping JWT tokens from configured OIDC issuer: ""
[2025/10/16 19:07:20] [oauthproxy.go:176] OAuthProxy configured for GitHub Client ID: Ovxxxxx
[2025/10/16 19:07:20] [oauthproxy.go:182] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains:.https://domain.com path:/ samesite: refresh:disabled
192.168.4.1:38442 - 2d372ffe-0421-4042-b721-bd8bf0f9f228 - - [2025/10/16 19:07:21] 192.168.4.41:4180 GET - "/ready" HTTP/1.1 "kube-probe/1.33" 200 2 0.000
[2025/10/16 19:07:27] [jwt_session.go:54] Error retrieving session from token in Authorization header: no valid bearer token found in authorization header
````
