### ISSUE TITLE
M2M auth - client credentials grant

### ISSUE THREAD

**Issue by p53** [oauth2-proxy/oauth2-proxy#811]
Usually when using oauth for m2m auth is used client credentials grant for getting TOKEN and on target only validation of Bearer Access token, not using auth_code flow

like https://github.com/louketo/louketo-proxy

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by JoelSpeed** [comment]
OAuth2 Proxy has primarily been for user authentication historically but we are trying to include more M2M features going forward.

What is the adverse effect you are seeing of having the user authentication still enabled?

**Comment by p53** [comment]
first i don't see any reason why cookie session should be enabled, but that could be minor issue apart from bigger security risk attack, but e.g. i would like to turn off claim validation (which is possible with louketo), i am doing claim validation with other component with greater flexibility (this component is not proxy)

**Comment by JoelSpeed** [comment]
>first i don't see any reason why cookie session should be enabled

I could see us having an option for this

>  i would like to turn off claim validation 

We are planning to make all claim validation optional once we switch to structured configuration. There will be a migration path for those who have already set up the proxy but for new users there will be no claim validation by default.

**Comment by adevnoob** [comment]
Hi, 
m2m authentication became very important for my current project. 
I did not found any proxy alternatives regarding the m2m-auth-issue. So it would be great if oauth2-proxy would be enabled for this.

Considering the  [rfc 6749](https://tools.ietf.org/html/rfc6749#section-4.4) there are 2 requests necessary for the client:

Token-Request:
```
curl -X POST "https://[Auth-Server-Host]/token" \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=[clients name]' \
--data-urlencode 'client_secret=[clients secret]' \
--data-urlencode 'grant_type=client_credentials'
```

You'll get an access token with valid credentials. No user is involved in this request.

```
curl -X GET "https://[Application-Host]/protectedResource" \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIA.shortened'
```

I'm not sure with the endpoint for the token-validation. Looking at the Keycloak-Provider it could be solved against the token-introspection endpoint, right?
In case of a valid token an active-key would be sent in a json-body with boolean value.
