### ISSUE TITLE
How to handle redirects when protecting multiple sub-domains?

### ISSUE THREAD

**Issue by ginkel** [oauth2-proxy/oauth2-proxy#812]
Hi there,

I am trying to use oauth2-proxy to protect a bundle of subdomains (`*.<domain>`). This is working well, except for the fact that I can't figure out how to redirect to the right subdomain (from the original request) after login. My reverse proxy (traefik) is set up so that all requests to `*.<domain>" end up at oauth2-proxy.

As I have to enter a static list of valid redirect URIs in my OIDC provider, I am using `--redirect-url https://redirect.<domain>` to have all redirects show up at that one location. What I can't seem to figure out is how to make oauth2-proxy to perform a redirect to the original subdomain afterwards. I have also set `--whitelist-domain .<domain>` and `--cookie-domain .<domain>`.

Any Idea what I may be missing? Is my interpretation of the docs wrong and such a feature does not exist? ;-)

Thanks,
Thilo

**Comment by TheAnachronism** [comment]
What solution did you come to (if you did)?
I'm trying to do the same thing but running into some problems while using keycloak as the provider.

**Comment by alex88** [comment]
Same here, did any of you solve it?
