### ISSUE TITLE
Redirect to /oauth2/auth despite OAUTH2_PROXY_PROXY_PREFIX being set

### ISSUE THREAD

**Issue by ginkel** [oauth2-proxy/oauth2-proxy#815]
## Expected Behavior

I have configured an instance of oauth2-proxy behind a Traefik reverse proxy using forward auth, so that I can protect select Docker containers at an ingress level. I have set `OAUTH2_PROXY_PROXY_PREFIX=/generic-oauth2-proxy` to make sure I don't get any namespace collisions with other containers that natively use `/oauth2` for their OAuth2 handling. Traefik is configured to forward all requests for `/generic-oauth2-proxy/*` to the oauth2-proxy instance.

## Current Behavior

After hitting `https://<fqdn>/generic-oauth2-proxy/callback?[...]` during the authentication flow I am redirected to `https://<fqdn>/oauth2/auth`, which ends up with a 404 as no one is registered to handle requests to this path.

Shouldn't that redirect target also be nested below the proxy prefix?

AFAICS the `/oauth2/auth` path is supplied with the initial request to the IDP as part of the "state" query param:

```
https://sso.<domain>/auth/realms/<realm>/protocol/openid-connect/auth?approval_prompt=force&client_id=generic-oauth2&redirect_uri=https%3A%2F%2F<fqdn>%2Fgeneric-oauth2-proxy%2Fcallback&response_type=code&scope=openid+email+profile&state=<redacted>%3A%2Foauth2%2Fauth
```

## Context

Configuration:

```
"OAUTH2_PROXY_ALLOWED_GROUP=generic-oauth2"
"OAUTH2_PROXY_CLIENT_ID=generic-oauth2"
"OAUTH2_PROXY_CLIENT_SECRET=<redacted>"
"OAUTH2_PROXY_COOKIE_HTTPONLY=true"
"OAUTH2_PROXY_COOKIE_REFRESH=60m"
"OAUTH2_PROXY_COOKIE_SECRET=<redacted>"
"OAUTH2_PROXY_COOKIE_SECURE=true"
"OAUTH2_PROXY_EMAIL_DOMAINS=*"
"OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180"
"OAUTH2_PROXY_OIDC_ISSUER_URL=https://sso.<domain>/auth/realms/<realm>"
"OAUTH2_PROXY_PROVIDER=oidc"
"OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=SSO"
"OAUTH2_PROXY_REVERSE_PROXY=true"
"OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true"
"OAUTH2_PROXY_PROXY_PREFIX=/generic-oauth2-proxy"
```

## Your Environment

- Version used: 6.1.1 (quay.io/oauth2-proxy/oauth2-proxy:latest)
- Keycloak 11.0.2
- Traefik 2.3.1

**Comment by JoelSpeed** [comment]
I'm not familiar with Traefik myself, but you may want to take a look at the thread for #762 as I think the people there may have some explanations.

Otherwise, is there any way in which you know that you can set either the redirect parameter via query string (`?rd=https://<my.site>`) or via a header `X-Auth-Request-Redirect` when starting the initial authentication flow?

**Comment by esteiner** [comment]
I have the same problem with using the proxy prefix. I see no feedback that my configured value is used. Should there be a log entry (on startup?) when using (--proxy-prefix | proxy_prefix | OAUTH2_PROXY_PROXY_PREFIX)? For example like with other configs:
[2020/12/01 11:15:06] [logger.go:490] compiled skip-auth-regex => ".*"

**Comment by JoelSpeed** [comment]
There wouldn't normally be a log for this no. But if you were to try accessing `<proxy-prefix>/sign_in` once you've got the proxy started it should show you the login page, if it hasn't worked, it will be registered instead at `/oauth2/sign_in` (which shouldn't work if you change the proxy prefix)
