### ISSUE TITLE
CORS for isAjax requests

### ISSUE THREAD

**Issue by POD666** [oauth2-proxy/oauth2-proxy#822]
I have a SPA that is running separately from API webserver:
SPA -> oauth2-proxy -> API webserver

When OAUTH2_PROXY_COOKIE_REFRESH cookie expires, SPA gets 401 in response but without CORS headers and so blocked by a browser.

## Expected Behavior

401 Response can be handled

## Current Behavior

401 Response is blocked by a browser because of  CORS:
```
Access to XMLHttpRequest at 'http://localhost:4180/api/v1/features' from origin 'http://localhost:7777' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Where http://localhost:7777 is my SPA.

## Possible Solution

Following changes [here](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L1067-L1071) work for me:
```go
// ErrorJSON returns the error code with an application/json mime type
func (p *OAuthProxy) ErrorJSON(req *http.Request, rw http.ResponseWriter, code int) {
	rw.Header().Set("Content-Type", applicationJSON)
	origin := req.Header.Get("Origin")
	if origin != "" {
		rw.Header().Set("Access-Control-Allow-Origin", origin)
		rw.Header().Set("Access-Control-Allow-Credentials", "true")
	}
	rw.WriteHeader(code)
}
```

Is it good enough to prepare PR? Is there a better solution/workaround?

**Comment by NickMeves** [comment]
Is this potentially resolved by better handling of the token refresh process? We've identified a need to allow the refresh to happen before an access token is expired (ie at 90% of the lifespan) so you don't get these boundary 401 errors.

We've also discussed the stampede issue that comes with this refresh process here too: https://github.com/oauth2-proxy/oauth2-proxy/issues/667

**Comment by POD666** [comment]
I'm not handling any tokens in SPA, just sending requests with cookies to my API and popup login page on 401. So all I want is a response not to be blocked by a browser - the CORS issue.

What exactly do you propose for handling of tokens?

**Comment by NickMeves** [comment]
I was thinking we don't wait for the `401` to hit the client -- we allow sessions to automatically refresh the access tokens via the refresh token before they expire while they are still alive.

Or is this more an issue with the whole session expiring (not the refresh timer) -- and getting a 401 back triggering a re-auth? In that case, I'll need to think more about CORS

**Comment by POD666** [comment]
Yeah, this is more about the whole session expiring. I think I will add something to continuously refresh user sessions but until then I need to be able to handle 401. And even after, I guess 401 errors may occur in different scenarios, no?

**Comment by POD666** [comment]
I have tried to perform an auth check before API calls by using `/oauth2/auth` endpoint but it also fails with the CORS issue.

**Comment by POD666** [comment]
Moving forward, I got the same issue with `/oauth2/sign_out` endpoint (fixed as erlier):
```
Access to XMLHttpRequest at 
'http://keycloak:8081/auth/realms/master/protocol/openid-connect/logout?post_logout_redirect_uri=http://localhost:4180/app/' 
(redirected from 'http://localhost:4180/oauth2/sign_out?rd=http%3A%2F%2Fkeycloak%3A8081%2Fauth%2Frealms%2Fmaster%2Fprotocol%2Fopenid-connect%2Flogout%3Fpost_logout_redirect_uri%3Dhttp%3A%2F%2Flocalhost%3A4180%2Fapp%2F') 
from origin 'http://localhost:4180' has been blocked by CORS policy: 
Response to preflight request doesn't pass access control check: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Also, it's a bit confusing that my js app needs to know what to set for the `rd` parameter, I would prefer oauth2-proxy to extract it from the OIDC provider metadata ([ref](https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints#sign-out)). Does it sound like something worth opening a feature request? 🙂

**Comment by J3m5** [comment]
How did you solved this issue @POD666 ?

**Comment by POD666** [comment]
@J3m5 just forked this repo with all the fixes I mentioned before. But after all, we decided not to use oauth2-proxy for now.

**Comment by phllpmcphrsn** [comment]
@POD666 did you wind up rolling with your own solution or did you find another proxy?

**Comment by POD666** [comment]
@phllpmcphrsn we end up with direct communication to an auth backend, so no need for any proxy in our case.

Anyway would be nice if oauth2-proxy adds support for such cases.
