### ISSUE TITLE
--extra-jwt-issuers doesn't work

### ISSUE THREAD

**Issue by POD666** [oauth2-proxy/oauth2-proxy#823]
Just upgraded to the latest master and it appears that `--extra-jwt-issuers` doesn't work and `extraJwtBearerVerifiers` variable is not used at all. `--extra-jwt-issuers` is still present in the docs.

## Expected Behavior

`--extra-jwt-issuers` are used

## Current Behavior

`[jwt_session.go:60] Error retrieving session from token in Authorization header: not implemented`

## Possible Solution

It seems to be a part of a big refactoring that was released in 6.1.0, so I stick to 6.0.0

**Comment by NickMeves** [comment]
This still works for me & it is still supported.

If I recall, these logs are a little confusing - the extra-jwt-issuers checks are chained (main provider's `CreateSessionStateFromBearerToken` first -- then direct OIDC verify attempts against direcly pulled jwks.json files based on the issuer you provide).

The chain is a done in a list until a success or fails if all in the chain fail to validate. Any errors in the middle are logged causing noise.

The OIDC provider is the only one that has implemented `CreateSessionStateFromBearerToken` -- all the others return the error `not implemented` which you see above.

**Comment by JoelSpeed** [comment]
> The chain is a done in a list until a success or fails if all in the chain fail to validate. Any errors in the middle are logged causing noise.

We should drop this noise really, it doesn't help with debugging I don't think, maybe we can only log when no session is matched?

**Comment by NickMeves** [comment]
When you have `--skip-jwt-bearer-tokens` set and a list of extra `issuer=audience` pairs in `--extra-jwt-issuers` -- do you get any failures logged for the extra issues that should process after your Keycloak primary provider fails for a bearer header?

It should skip keycloak after the failure and try the direct OIDC verifiers.  If you aren't getting log messages from those if they are also failing, you might want to make sure you have them configured

**Comment by NickMeves** [comment]
FYI - This will hopefully be fixed here: https://github.com/oauth2-proxy/oauth2-proxy/pull/869

**Comment by NickMeves** [comment]
This was fixed
