### ISSUE TITLE
Nginx configuration to enable Authorization Header for upstream requests

### ISSUE THREAD

**Issue by rpateljci** [oauth2-proxy/oauth2-proxy#827]
Hi, 

I am unable to see any Authorization token added by oauth2 proxy in my kubernetes enviornment. 

**OAuth Proxy config**
```
          - --email-domain=*
          - --scope=openid authorizationapi offline_access
          - --reverse-proxy=true
          - --session-store-type=cookie
          - --http-address=0.0.0.0:4180
          - --client-id=oauthproxy_client
          - --client-secret=oauthproxy_client_secret
          - --cookie-secure=true
          - --cookie-samesite=none
          - --cookie-httponly=true
          - --provider=oidc
          - --oidc-issuer-url=https://10.211.55.29/authorization-v2
          - --profile-url=https://10.211.55.29/authorization-v2/connect/userinfo
          - --redirect-url=https://10.211.55.29/oauth2/callback
          - --oidc-issuer-url=https://10.211.55.29/authorization-v2
          - --login-url=https://10.211.55.29/authorization-v2/connect/authorize
          - --redeem-url=https://10.211.55.29/authorization-v2/connect/token
          - --oidc-jwks-url=https://10.211.55.29/authorization-v2/.well-known/openid-configuration/jwks
          - --user-id-claim=sub
          - --ssl-insecure-skip-verify=true
          - --insecure-oidc-skip-issuer-verification=true
          - --skip-provider-button=true
          - --pass-access-token=true
          - --pass-authorization-header=true
          - --set-authorization-header=true
          - --set-xauthrequest=true
          - --whitelist-domain=10.211.55.29:*
```

**Ingress Setup**
```
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/auth-signin: 'https://$host/oauth2/start?rd=$request_uri'
     nginx.ingress.kubernetes.io/auth-url: 'https://$host/oauth2/auth'
     nginx.ingress.kubernetes.io/auth-response-headers: 'X-Auth-Request-Access-Token, Authorization'
     nginx.ingress.kubernetes.io/configuration-snippet: |
     auth_request_set $token $upstream_http_authorization;
     proxy_set_header Authorization $token;
```
**Proxy Logs**
```
[2020/10/07 18:30:02] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.211.55.2 - - [2020/10/07 18:30:02] 10.211.55.29 GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0" 401 21 0.000
10.211.55.2 - - [2020/10/07 18:30:02] 10.211.55.29 GET - "/oauth2/start?rd=%2Fauth%2Flogin" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0" 302 329 0.000
10.211.55.29 - - [2020/10/07 18:30:03] 10.42.154.41:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.17" 200 2 0.000
10.211.55.2 - 5f7dfb94ec7ba4feae84dd54 [2020/10/07 18:30:08] [AuthSuccess] Authenticated via OAuth2: Session{email:5f7dfb94ec7ba4feae84dd54 user:5f7dfb94ec7ba4feae84dd54 PreferredUsername: token:true id_token:true created:2020-10-07 18:30:08.116319432 +0000 UTC m=+3405.728669148 expires:2020-10-07 19:30:08.115994212 +0000 UTC m=+7005.728343923 refresh_token:true}
10.211.55.2 - - [2020/10/07 18:30:08] 10.211.55.29 GET - "/oauth2/callback?code=vpcisWmjOTvculRwvcDhC0KjzbA5OnlmsAOiEhKV9kk&scope=openid%20authorizationapi%20offline_access&state=c655a6bfc50f55f2fdae9a9782f4d27d%3A%2Fauth%2Flogin&session_state=SnO-aIo_NKsIHrey_Ub2vEckEuOw00DlIfbbrIZ38R0.s-T9RYkDPNaYGIhmieMywA" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0" 302 34 0.039
10.211.55.2 - 5f7dfb94ec7ba4feae84dd54 [2020/10/07 18:30:08] 10.211.55.29 GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0" 202 0 0.000
```
## Expected Behavior

On successfully logging into the system, Authorization header should be available for upstream requests

## Current Behavior

Oauth Proxy is able log the user, redirect to the appropriate upstream. The authorization header is not available.

Note: I am able to see the Authorization correctly passed to upstream requests, when the solution is run locally (outside of kubernetes)

- Version used: 6.1.1

**Comment by JoelSpeed** [comment]
Do you have access to the OAuth2 Proxy instance from the internet? Once you have authenticated, could you manually visit the `/oauth2/auth` endpoint and use your browsers developer tools to check the headers that are returned? 

You may also want to check the nginx logs in case there are any errors there to do with header sizes

**Comment by rpateljci** [comment]
thanks @JoelSpeed. I can confirm that oauth2_proxy returns tokens when I access /oauth2/auth ep. I also checked the nginx logs and there are no errors. 

The oauth2_proxy docs talk about using Lua scripting on the nginx. Specifically this 
`nginx.ingress.kubernetes.io/auth-response-headers: Authorization
nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
nginx.ingress.kubernetes.io/configuration-snippet: |
 auth_request_set $name_upstream_1 $upstream_cookie_name_1;

  access_by_lua_block {
    if ngx.var.name_upstream_1 ~= "" then
      ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
    end
  }
`

Is this required for the access_token to be passed upstream? Are there any other requirements (for nginx) apart from the code block above?

**Comment by JoelSpeed** [comment]
So it looks like NGINX isn't reading that header for some reason. Could you check the size of the header in the response from `/oauth2/auth`? Maybe Nginx is dropping it because it is too large? 

Otherwise I'm not entirely sure, looks like OAuth2 Proxy is behaving as expected

**Comment by rpateljci** [comment]
It was an nginx configuration issue, I am able to see the token upstream after I changed the configuration-snippet from 

```
nginx.ingress.kubernetes.io/configuration-snippet: |
     auth_request_set $token $upstream_http_authorization;
     proxy_set_header Authorization $token;
```
to 
```
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_x_auth_request_access_token;
      add_header 'Authorization' $token;
```

Thanks for you help.

**Comment by dsantanu** [comment]
> ```
>     nginx.ingress.kubernetes.io/configuration-snippet: |
>       auth_request_set $token $upstream_http_x_auth_request_access_token;
>       add_header 'Authorization' $token;
> ```
was trying to make it work for over a day and wasn't going anywhere. Finally got saved by this.
Thanks for posting!!
