### ISSUE TITLE
Publish manifest lists with multiple architectures

### ISSUE THREAD

**Issue by mattmoor** [oauth2-proxy/oauth2-proxy#828]
## Expected Behavior

`quay.io/oauth2-proxy/oauth2-proxy` is a manifest list with multiple architectures.

## Current Behavior

`crane` is a tool from `github.com/google/go-containerregistry` for exploring container images.

```
crane manifest quay.io/oauth2-proxy/oauth2-proxy
2020/10/07 21:31:44 No matching credentials were found, falling back on anonymous
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 2797,
      "digest": "sha256:099d79cd2cb6979bfed5a7172b780976231ace8d9c98cc7d01bbea21b08456ab"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2813316,
         "digest": "sha256:cbdbe7a5bc2a134ca8ec91be58565ec07d037386d1f1d8385412d224deafca08"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 159,
         "digest": "sha256:056f200e279bf97b1fcf4ba62cfb6f2e62e8832a0b017c820c57398e7131e887"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 114546,
         "digest": "sha256:7f7065e8315a353e129eb442250fa75c9f1397e8a66c1860a973e9b237dd5f98"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 11475078,
         "digest": "sha256:c34cd6d4927ba26f15b293e295ab69582ad6dedccbcc4cfc38e60adb2e1998ec"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 190,
         "digest": "sha256:2c4c1758958604f922f18c1726b402174e0d9bb1e7c2bd7b039472976a763a42"
      }
   ]
}
```

## Possible Solution

We recently shipped multi-architecture support in `github.com/google/ko`, which cross-compiles for every architecture present in the base image and then produces a manifest list on top of that with each of the respective Go binaries (see output below).  By default this uses `gcr.io/distroless/static:nonroot`, which supports amd64 and arm64.

```
master @ github.com/oauth2-proxy/oauth2-proxy
knative-arm > KO_DOCKER_REPO=docker.io/mattmoor ko publish --platform=all  -B .
2020/10/07 21:30:10 Using base gcr.io/distroless/static:nonroot for github.com/oauth2-proxy/oauth2-proxy/v7
2020/10/07 21:30:12 Building github.com/oauth2-proxy/oauth2-proxy/v7 for linux/amd64
2020/10/07 21:30:20 Building github.com/oauth2-proxy/oauth2-proxy/v7 for linux/arm64
2020/10/07 21:30:29 Publishing docker.io/mattmoor/v7:latest
2020/10/07 21:30:31 pushed blob: sha256:cd98654e03737b2949f542200b11d700c955a5e0f9eff6f148b8a71f285bced9
2020/10/07 21:30:31 pushed blob: sha256:72164b581b02b1eb297b403bcc8fc1bfa245cb52e103a3a525a0835a58ff58e2
2020/10/07 21:30:32 pushed blob: sha256:5c7fe08dec514a5105d43dfcae1a5a45be002bcd3251dd178ced702aecfb7531
2020/10/07 21:30:35 pushed blob: sha256:621048c4af879012ce703fb8795c7da42f5f84bdb51bc2823a211d04f0abe3df
2020/10/07 21:30:35 index.docker.io/mattmoor/v7@sha256:6304278544733532481dfaceedffc3809d4a559e6f5c1750956a4d908296c25c: digest: sha256:6304278544733532481dfaceedffc3809d4a559e6f5c1750956a4d908296c25c size: 751
2020/10/07 21:30:35 existing blob: sha256:72164b581b02b1eb297b403bcc8fc1bfa245cb52e103a3a525a0835a58ff58e2
2020/10/07 21:30:37 pushed blob: sha256:7d4b265a3655a416f65b66aa73e665f5dc794489f8827e2c5141f91e47823354
2020/10/07 21:30:37 pushed blob: sha256:ae766dd45b82b868906b003ee4aa33a7fd0329b1d24060f301e5fd8f94622c76
2020/10/07 21:30:41 pushed blob: sha256:07cbfba62ffa43528e92847f72482c62a014d3e5f5d2ce3574b5bfdbf68e1d17
2020/10/07 21:30:41 index.docker.io/mattmoor/v7@sha256:40cde456a3ec8a05e458bf40ae55914fec1fcc356e2403a3eb2407e9ad39dc21: digest: sha256:40cde456a3ec8a05e458bf40ae55914fec1fcc356e2403a3eb2407e9ad39dc21 size: 751
2020/10/07 21:30:41 docker.io/mattmoor/v7:latest: digest: sha256:c5d41226885108cb6c214b4b4328c134b74ea26e9bd41ffb9e84a166139be1fe size: 529
2020/10/07 21:30:41 Published docker.io/mattmoor/v7@sha256:c5d41226885108cb6c214b4b4328c134b74ea26e9bd41ffb9e84a166139be1fe
docker.io/mattmoor/v7@sha256:c5d41226885108cb6c214b4b4328c134b74ea26e9bd41ffb9e84a166139be1fe

master @ github.com/oauth2-proxy/oauth2-proxy
knative-arm > crane manifest docker.io/mattmoor/v7@sha256:c5d41226885108cb6c214b4b4328c134b74ea26e9bd41ffb9e84a166139be1fe | jq .
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "manifests": [
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 751,
      "digest": "sha256:6304278544733532481dfaceedffc3809d4a559e6f5c1750956a4d908296c25c",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "size": 751,
      "digest": "sha256:40cde456a3ec8a05e458bf40ae55914fec1fcc356e2403a3eb2407e9ad39dc21",
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    }
  ]
}
```

## Steps to Reproduce (for bugs)

N/A

## Context

I've been on a bit of a multi-architecture push the last few weeks trying to make as much of [Knative](https://github.com/knative) and its respective samples support amd64 and arm64, and I sometimes run oauth2-proxy in from of my Knative services ([see also](https://medium.com/@mattmoor/authenticating-knative-services-with-oauth2-proxy-4f9e7a8d714b)), but the image I've been using doesn't seem to be a multi-architecture image.

## Your Environment

I have historically used GKE (amd64), but I'm looking to use Graviton EKS (arm64) for more of my development.  Above I was looking at `:latest` as of filing this issue.

**Comment by JoelSpeed** [comment]
As far as I'm aware, Quay doesn't support multi architecture manifests, but I may be out of date on that. Do you happen to know one way or the other on this? 

I would absolutely love to have multi arch images published for the project if possible, though I'm hesitant to move away from Quay as I'm not sure what else we could get away with using with zero budget that's not docker hub (given their recent changes to policy).

**Comment by mattmoor** [comment]
Hmm, good question.  Lemme ask some folks at Redhat.

**Comment by mattmoor** [comment]
I wonder if this was a "schema 2" thing, since Quay took a really long time to implement that, and that's where multi-arch landed, but AIUI that's enabled now (or at least can be).

Let's see if we can get a more authoritative answer...

**Comment by JoelSpeed** [comment]
I work for Red Hat so I can reach out internally and find out if there isn't an easily authoratitive answer somewhere in the docs

**Comment by mattmoor** [comment]
LOL, ok.  Well @markusthoemmes talked to @bbrowning and apparently it should support it.  🤞

**Comment by JoelSpeed** [comment]
Ok, well, based on that, your original research above and a quick read through some [docker manifest docs](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md), it looks like it does now, which is awesome!

We currently build amd64, arm64 and armv6 images for each release by using multi step Dockerfiles, if we migrate I would suggest we retain the same tags for a few releases while also supporting all of these on the normal (non-suffixed) tags to allow people to migrate.

I'm not familiar with how we would actually build and push the multiarch images, your suggestion of `ko` sounds like it will do the job though I haven't had a look into it just yet.

I saw you mentioned `gcr.io/distroless/static:nonroot` is the normal base, two questions:
- You mention it supports `amd64` and `arm64`, do you know if it also supports `armv6`? If not I can take a look at another point
- Does this image support CGO? This project requires CGO to be built and so won't work on some base images (IIRC something to do with `musl` vs `glibc` 🤔)

**Comment by mattmoor** [comment]
I'm curious what you need CGO for?  distroless has a `base` image which includes glibc to support things that need it, but `ko` passes `CGO_ENABLED=0` so it can use `static`, which doesn't have glibc.

**Comment by JoelSpeed** [comment]
> I'm curious what you need CGO for?

Ignore me, we don't! Just double checked and we are building the binaries with `CGO_ENABLED=0` so ignore my prevous comment about CGO

I think we should be able to go ahead with this if I've understood everything correctly.

Perhaps you've done this already, but if you scan through our [Dockerfile](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/Dockerfile), does anything stand out as a potential blocker for this? I had a look through and can't see anything that is concerning me

**Comment by mattmoor** [comment]
Not that I can see.

The architectures have already expanded to include `s390x` (and there's a PR for `ppc64le` open, link below), so that should land soon.  No `armv6`, but I hope it would be relatively straightforward to add: https://github.com/GoogleContainerTools/distroless/pull/622 🤞 

I've mostly tested the `ko` multi-arch stuff with amd64/arm64 due to hardware, but if you have stuff to test armv6 it'd be great to validate things are WAI.

cc @jonjohnsonjr

**Comment by JoelSpeed** [comment]
Great this sounds good. I guess the only blocker is the armv6, but it doesn't look too hard to add that if the container tools people are receptive.

Are you interested in/have time to come up with a PR to move our make targets from using Docker to Ko to build the multi arch? 

> I've mostly tested the ko multi-arch stuff with amd64/arm64 due to hardware, but if you have stuff to test armv6 it'd be great to validate things are WAI.

I think we should be able to emulate the architectures using QEMU or something to try it out 🤔  That or I can dig out an old raspberry pi 😅

**Comment by mattmoor** [comment]
The way the distroless stuff works is all cross-compiled, so you don't need the target architecture to build for it.  We would want to test it, and I opened https://github.com/google/ko/issues/224 to track that in `ko`.

**Comment by JoelSpeed** [comment]
I more meant Qemu would allow local testing of any images we build for archs it supports right? Will follow that issue thanks

**Comment by mattmoor** [comment]
I landed the `ko publish` tests for multi-arch today, which run a simple cross-compiled Go binary on amd64, arm64, s390x, and PowerPC, which afaik are the only supported options for Travis, but also all distroless currently supports.

I think arm64 may support running 32-bit arm processes, so it might be worth trying to test that as well.  I suspect that earlier arm versions may not be right yet because they needed `GOARM={version}` to be set, but we could probably test this by adding a variant of the tests that use something like `alpine` for the base 🤔

**Comment by JoelSpeed** [comment]
What can we do to make progress on this? What do we need to do in our repo?

I'm guessing:
- Update the Dockerfile
- Set up Make target to build images
- Work out a way to keep existing armv6 support

**Comment by mattmoor** [comment]
I was just bugging @jonjohnsonjr about the armv6 support in `ko` a few minutes ago.

You should be able to delete the Dockerfile, and replace these with `ko publish --platform=all ./path/to/binary`:
https://github.com/oauth2-proxy/oauth2-proxy/blob/65016c8da155396ce68f7221d8e10703c89f0342/Makefile#L63

**Comment by JoelSpeed** [comment]
Definitely want to do this long term

**Comment by xxxbobrxxx** [comment]
You can do that using docker buildx
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
This article also contains github pipeline example.
