### ISSUE TITLE
Couldn't extract claims from id_token because group claim has invalid structure

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#838]
The group claim from my OIDC Provider looks like this:

```
"groups": [
    {
      "groupId": "CIDAAS_ADMINS",
      "roles": [
        "ADMIN"
      ]
    }
  ],
```

## Expected Behavior

The used group claim structure provided by my OIDC Provider can be handled.

## Current Behavior

[2020/10/13 09:26:15] [logger.go:508] Error redeeming code during OAuth2 callback: unable to update session: couldn't extract claims from id_token (failed to parse default id_token claims: json: cannot unmarshal object into Go struct field OIDCClaims.Groups of type string)

## Possible Solution

The custom group structure by my OIDC provider can be handled
or
at least it is possible to disable the group check.

## Steps to Reproduce (for bugs)

Use a group claim structure like above and perform the login flow.

- Version used:

I used the current master version. So the group check is not yet released.

**Comment by NickMeves** [comment]
Fixed in #839
