### ISSUE TITLE
Oauth2-proxy and Envoy in Kubernetes

### ISSUE THREAD

**Issue by anst270125** [oauth2-proxy/oauth2-proxy#840]
Hi, can I do OIDC Authentication with only Oauth2-proxy and Envoy, in a Kubernetes cluster ? Or are other components like Nginx Ingress or Istio needed ?

**Comment by JoelSpeed** [comment]
I believe people have made this work with Envoy before, though it's not something I have ever tried personally. I would recommend searching through past issues that mention Envoy to see what others have achieved

**Comment by NickMeves** [comment]
Closing this since it looks like Joel's answer pointed you in the right direction.
