### ISSUE TITLE
Oauth Proxy allows access with expired access token

### ISSUE THREAD

**Issue by nicoschuck** [oauth2-proxy/oauth2-proxy#841]
I have a Kubernetes Cluster running on Azure (AKS) with a nginx-ingress as a reverse proxy in front.
Behind the proxy the oauth proxy should protect my apps with Azure AD as IDP.
Actually everything works fine but since a couple weeks I noticed that some users access the page and facing some unexpected errors.
The issue is that the AAD access token is expired (trying to access the graph api from azure with the token which is provided by oauth_proxy):

```
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token has expired.",
    "innerError": "date": "2020-10-14T07:32:03",
    "request-id": "370c835f-.....\",
    "client-request-id": "370c835f-...."
  }
}
```

From my understanding the oauth proxy should notice that and redirect to the IPD instead of forwarding to the application?

**Comment by NickMeves** [comment]
The `OAuth2-Proxy` has its own `SessionState` with its own expiration and refresh that happens to contain your various tokens (in addition to other fields based on your Provider): https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/apis/sessions/session_state.go

The best practice to keep this in sync with your Access/ID Token & Refresh Token from your provider if you intend to use those in your backend application is to sync their lifespans with the `--cookie-expire` and `--cookie-refresh` options: https://oauth2-proxy.github.io/oauth2-proxy/configuration#command-line-options

**Comment by weinong** [comment]
why can't it just refresh when it expires?

**Comment by NickMeves** [comment]
> why can't it just refresh when it expires?

Some people might not care about the underlying ID/Access Token TTL, and don't want a refresh network round trip to occur in the middle of a standard request. It really only matters if you inject the token into the backend request Authorization header and use it in the backend.

Other users don't even have access if they use minimal cookies (no tokens are in the cookies).
