### ISSUE TITLE
Listen both http & https to ease force_https redirection

### ISSUE THREAD

**Issue by jdequatrebarbeszenvalue** [oauth2-proxy/oauth2-proxy#842]
I tried to use force_https but, as far as I understand that feature, a proxy seems mandatory to redirect both http and https requests to oauth2-proxy.

## Expected Behavior

When force_https is activated, oauth2-proxy should serve http and https.
Then http request would be redirected to https, by existing force_https feature.

## Current Behavior

Either the http address is listened, or it's the https, never both.

## Possible Solution

	func (s *Server) ListenAndServe() {
		if s.Opts.TLSKeyFile != "" || s.Opts.TLSCertFile != "" {
			s.ServeHTTPS()

			// Another thread may listen to HTTP
			if s.Opts.ForceHTTPS {
				go func() {
					s.ServeHTTP()
				}
			}

		} else {
			s.ServeHTTP()
		}
	}

**Comment by JoelSpeed** [comment]
I agree, this behaviour seems odd. I guess we could try supporting both HTTP and HTTPS servers simultaneously 🤔 

Before we implement anything though, I'd be intrigued to do some archeology and look up when the HTTPS stuff was added originally and see if there was any discussion at the time about having one vs two servers

**Comment by jdequatrebarbeszenvalue** [comment]
SSL support  was added in June 2015.
I did not find any discussions about its implementation.
https://github.com/bitly/oauth2_proxy/pull/99

A a pull request proposing a redirection http to https was submitted but never merged.
It included listening to http streams on an "https-redirector-address".
https://github.com/bitly/oauth2_proxy/pull/324/commits/2fb2145b3a121bd434cf840acb92c7a2a7282a45

**Comment by JoelSpeed** [comment]
Ok, in that case, I'm supportive of us running both HTTP and HTTPS servers at once. We would have to consider this a breaking change though I think as this may start serving an extra server for some people.

I think we will want the HTTPS listener off by default, I think that's the case now though.

**Comment by JoelSpeed** [comment]
This will be available once #1047 merges, if you are willing to use the alpha config

**Comment by jdequatrebarbeszenvalue** [comment]
Thanks!

**Comment by JoelSpeed** [comment]
This is now implemented with our alpha configuration
