### ISSUE TITLE
Support group in github auth provider

### ISSUE THREAD

**Issue by TommyLike** [oauth2-proxy/oauth2-proxy#845]
Provide group detail when using github provider and configured multiple `github teams`

## Current Behavior

the `X-Auth-Request-Group` is empty even if the authorized user is from github team and `set-xauthrequest` turned on.

## Possible Solution
Can we fill the `X-Auth-Request-Group` header if the user belongs to one specific org or team? that can be utilized for fine grained control.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by NickMeves** [comment]
I'm setting the stage for support for this in these 2 PRs I'm wrapping up:

https://github.com/oauth2-proxy/oauth2-proxy/pull/796
https://github.com/oauth2-proxy/oauth2-proxy/pull/797

I've started cleaning up the Github provider a little bit, but I've noticed several areas where its Group/Repo/Org based AuthZ needs some refactoring.

I'm not a Github provider user myself, so I'll likely look to the community for supporting development of this.
