### ISSUE TITLE
Azure Token not refreshing

### ISSUE THREAD

**Issue by cccs-cat001** [oauth2-proxy/oauth2-proxy#846]
## Expected Behavior
Token should refresh before it expires..

## Current Behavior
When a token expires (after about an hour), nothing happens. When I try to access our services with the expired token I get "Expired JWT" errors.

## Possible Solution
This PR might be a solution https://github.com/oauth2-proxy/oauth2-proxy/pull/754? I'm not entirely sure. I don't know enough about oauth to understand. 

## Steps to Reproduce (for bugs)

1.  Get authorized with your proxy.
2.  wait for token to expire (For us it's an hour but I think mileage may vary)
3. Refresh your page, and you'll get an access denied, or expired token, or something to indicate that your token has expired. 

## Your Environment

- Version used: using version 6.1.1 in a bitnami image (`bitnami/oauth2-proxy:6.1.1-debian-10-r38`)

**Comment by NickMeves** [comment]
Does my answer over on this related question cover your scenario? https://github.com/oauth2-proxy/oauth2-proxy/issues/841

**Comment by JoelSpeed** [comment]
I think this should be closed as a duplicate of #841, any objection @cccs-cat001?
