### ISSUE TITLE
Add DynamoDB Session Store Support

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#848]
Currently Redis is our only supported persistent session store as an alternative to encrypted cookie sessions. Redis provides greater security, but has friction in initial setup which likely makes most users opt for cookie based sessions.

Let's aim to start supporting the table DBs of the big 3 cloud vendors, starting with DynamoDB.

## Current Behavior

Only Redis is supported. It has a lot of setup friction and results in managing more secure credentials (Redis & Sentinel passwords). Plus operational costs of managing a deployment of Redis.

## Possible Solution

We use the AWS SDK to hook into DynamoDB and wrap its Save, Load & Clear operations with our `persistence.Manager` https://github.com/oauth2-proxy/oauth2-proxy/blob/3fa42edb7350219d317c4bd47faf5da6192dc70f/pkg/sessions/persistence/manager.go

We add no new configuration, and instead rely on the expected environment variables or config files of the AWS SDK's configuration chain so users can choose the best authentication route for their environment (static envvar keys, config file, EC2 Metadata API, EKS IRSA, etc).

**Comment by NickMeves** [comment]
I might take this on in 2-3 months, but if someone wants to give it a whirl first, that would be greatly appreciated!

This PR from a few months back set the stage to ease the integration of any new sessions stores.  All the complex logic of session tickets & encryption best practices is abstracted away and just needs a `Store` that can Save/Load/Clear sessions.

https://github.com/oauth2-proxy/oauth2-proxy/pull/682

**Comment by JosephWoodward** [comment]
>We add no new configuration, and instead rely on the expected environment variables or config files of the AWS SDK's configuration chain so users can choose the best authentication route for their environment (static envvar keys, config file, EC2 Metadata API, EKS IRSA, etc).

So to clarify, no explicit option to use Dynamo, but rely on the presence of AWS environment variables (config file etc) to infer the user wishes to use Dynamo?

**Comment by JoelSpeed** [comment]
I was inferring from the description that the `--session-store` flag would infer that you want to use dynamo, but there would be no options for the credentials as these would be supplied as part of the SDK

**Comment by JosephWoodward** [comment]
@JoelSpeed Great, thanks for the clarification. How about the table, would the name be a static table name, created by OAuth2 proxy?

**Comment by JoelSpeed** [comment]
I would assume that would be a new flag/configuration option. If you look at how we have implemented options for the redis session store, I think this will show how we have handled things like this in the past

**Comment by JosephWoodward** [comment]
@JoelSpeed Thanks, I was taking the "We add no new configuration" literally.

**Comment by JoelSpeed** [comment]
No worries! Let's try minimise what we do add until people ask for it, but the essentials will still be needed 😅

**Comment by NickMeves** [comment]
Ah yeah -- table name makes sense.  Customizable, but with a sensible default 😄 

And yes, new `dynamodb` legal value for the existing `--session-store` flag.

I mostly had no new configurations for credentials on my mind.  I didn't want us to iterate through potential options for all the auth creds for AWS. I wanted to ride the defaults to leave the many mechanisms to get access (raw creds, IAM Role, STS, etc etc) up to the user based on their security architecture.

**Comment by JosephWoodward** [comment]
I've made a start on this.

**Comment by JosephWoodward** [comment]
Draft PR can be found [here](https://github.com/oauth2-proxy/oauth2-proxy/pull/876). I'm quite new to Go so any feedback as I go would be much appreciated.

**Comment by JosephWoodward** [comment]
@JoelSpeed @NickMeves I'm thinking it makes more sense for oauth proxy to create the session store table in Dynamo, in which what are your thoughts on also adding the provisioned throughput (read/write capacity units) as flags?

**Comment by NickMeves** [comment]
I'll give my thoughts, but I'd defer to @JoelSpeed since he might have a better pulse of the landscape for something like this being a maintainer of Dex as well (which also has pluggable storage engines):

In general, I like to keep software vs infrastructure separate (for maintainability & security). So I'd assume everything needed for `OAuth2-Proxy` to consume a table is in place ahead of time via Terraform, AWS Console, etc (IAM Roles/User, IAM Policy, DynamoDB table setup, etc).

I think we mirror the Redis session store setup in validation:  We validate the DB store exists and we perform a set of Save/Load/Clear operations to ensure its health on startup -- otherwise we don't startup and we give a validation message specifying the failed started reasons based on the given configuration. A table's existence could be one of those checks.

**Comment by JoelSpeed** [comment]
I agree with Nick here, I don't think we should be creating the table in Dynamo, I would have expected something to have set this up already as Nick says. From a security perspective as well, I would expect that the proxy IAM permissions would be limited to only what is need to operate, reading and writing keys, I wouldn't expect table permissions to be granted to a proxy like this since it would only be a one time operation

**Comment by JosephWoodward** [comment]
This is still active, I've just not had time to work on it recently as I've had to focus on something else. Hopefully be back on this in the next few days.
