### ISSUE TITLE
jwt-session's createSessionStateFromBearerToken should respect insecure-oidc-allow-unverified-email

### ISSUE THREAD

**Issue by holyjak** [oauth2-proxy/oauth2-proxy#852]
I _assume_ that the `insecure-oidc-allow-unverified-email` config should apply also to the additional issuers from `extra-jwt-issuers` (for use with `skip-jwt-bearer-tokens`).

## Expected Behavior

A token form an additional issuer should not be rejected due to unverified email address when `insecure-oidc-allow-unverified-email = true`. 

## Current Behavior

Currently ID tokens sent via `Authorization: Bearer ...` when `skip-jwt-bearer-tokens=true` are required to have `email_verified=true`, see https://github.com/oauth2-proxy/oauth2-proxy/blob/420a34f8146c3f93268d3cdee0ad8606b69d30c1/pkg/middleware/jwt_session.go#L154

But it should be similar to what the [oidc provider does](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/oidc.go#L212).

## Possible Solution

Pass config options to the function somehow, skip verifying if not required. (I would send a PR for this but am not sure what would be a preferable way of getting the option(s) to the decision point.)

## Context

Currently we are trying to open our API (used only by our frontend until now) to another application. The application uses the same OIDC provider but a different client id (and thus audience). Therefore it must be added to `extra-jwt-issuers` (as `<the same issuer>=<the other apps' oidc client id>`). But it then fails to extract session from the token because it has unverified email, even though we don't care for email verification. (Another problem is that we would also like to extract the phone_number claim but I can add that one in a separate PR.)

## Your Environment

- Version used: 6.1.1

**Comment by JoelSpeed** [comment]
I would suggest making https://github.com/oauth2-proxy/oauth2-proxy/blob/420a34f8146c3f93268d3cdee0ad8606b69d30c1/pkg/middleware/jwt_session.go#L138 a member of a struct which has the configuration within it, then passing through the configuration option to this point https://github.com/oauth2-proxy/oauth2-proxy/blob/420a34f8146c3f93268d3cdee0ad8606b69d30c1/pkg/middleware/jwt_session.go#L23 to set up that struct with the correct option

**Comment by NickMeves** [comment]
So I'm hesitant to conflate any OIDC Provider specific configuration settings into the `extra-jwt-bearers`. Especially since we have other provider users utilize the extra jwt issuers additionally (We get questions about Keycloak using this a lot).

This happened a few versions ago and resulted in a lot of corner case bugs we had to fix.

Long term -- I'm an advocate for this to replace `--extra-jwt-issuers` https://github.com/oauth2-proxy/oauth2-proxy/issues/835

Short term -- This should be its own flag to configure the `--extra-jwt-issuers` auth chain, not mixed in any way with an existing Provider flag.

**Comment by NickMeves** [comment]
@JoelSpeed - I'm gonna flip the label to `enhancement` -- I think this is behaving as expected at the moment with the OIDC Provider ability to allow unverified emails only for the provider methods.

**Comment by JoelSpeed** [comment]
We should try to focus on multi-provider support. I think this would solve a lot of the issues we see that are similar to this 🤔

**Comment by harshitmahapatra** [comment]
I would also really like this feature. 

We have a use-case which can benefit from this enhancement:

We exposing our backend api for an app and we use keycloak as the identity provider. The app gets the access token directly from keycloak and uses the token to call the api secured by oauth2-proxy with skip-jwt-bearer enabled. We don't really care about the email as long as the user exists in the keycloak database becuase the user registration process in keycloak has captcha verification enabled.
