### ISSUE TITLE
[QUESTION] What is the current recommended GitLab.com config

### ISSUE THREAD

**Issue by halvardssm** [oauth2-proxy/oauth2-proxy#857]
Hi! I am trying to set up this proxy with the [Adminer image](https://hub.docker.com/_/adminer) with GitLab cloud (gitlab.com, not self-hosted). I am a bit confused by the docs, and I can't find any examples anywhere using v6 or newer. Would it be possible to give a minimal example of how to use this proxy with GitLab restricted to a group?

Thanks in advance for any help with this!

**Comment by NickMeves** [comment]
@papey Do you have any ideas on this one?

I don't think any of the current maintainers use this Provider, so we'll need to lean on the community to help answer this one.  This PR is taking a look at sprucing up the `Gitlab` provider - its prerequisite PRs are hopefully merging in soon.

https://github.com/oauth2-proxy/oauth2-proxy/pull/630

**Comment by halvardssm** [comment]
I managed to make it work after digging through some merge requests and old commits 💪 

I will make a doc PR, but this is the config which worked for me:

```
    --email-domain="*"
    --approval-prompt="disable"
    --redirect-url="https://myapplication.com/oauth2/callback"
    --client-id=GITLAB_CLIENT_ID
    --client-secret=GITLAB_CLIENT_SECRET
    --cookie-secret=SOME_RANDOM_COOKIE_STRING
    --provider="gitlab"
    --gitlab-group="my-group"
```
