### ISSUE TITLE
Add Prometheus Metrics endpoint

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#858]
Expose high level metrics for Prometheus to scrape & generate potential alerts.

## Expected Behavior

Host a `/metrics` endpoint on its own port (not the same one as the `/oauth2/*` default proxy). This will allow easier configurations so the metrics aren't exposed publicly.

Not sure what good metrics would be to collect -- other reverse proxies would be good to look at for motivation.

## Current Behavior

No metrics.

## Possible Solution

https://prometheus.io/docs/guides/go-application/

**Comment by NickMeves** [comment]
Definitely looking for input from the community on what metrics would be good to aggregate.

**Comment by JoelSpeed** [comment]
We had some previous discussion about this in #580
