### ISSUE TITLE
Using oauth2_proxy with Envoy's external authorization filter

### ISSUE THREAD

**Issue by anst270125** [oauth2-proxy/oauth2-proxy#862]
I'm trying to place oauth2_proxy into an Envoy external authorization filter(envoy.ext_authz). The ext_authz filter expects a 200 response in order to redirect the user to the desired cluster. I'm using Keycloak as identity provider. To make sure the problem is not with the Envoy filter, I replaced outh2_proxy with a dummy NodeJs server that returns code 200, and I'm indeed redirected to the desired location.
So, I'm having issued with oauth2_proxy. It's been a week since I'm trying to tweak the proxy configuration (adding, removing, modifying configuration variables), but no luck so far. 

I'm forwarding port 4180 from the oauth2_proxy service to the local machine, so localhost:4180 is oauth2_proxy-svc:4180.
Here is my proxy configuration(everything is in a Kubernetes cluster):

```
[...]
- args:
        - --provider=keycloak
        - --client-id=bench-api
        - --client-secret=fdeb5207-e044-4a52-9675-3caa394f5266
        - --login-url=http://10.1.162.22:8080/auth/realms/bench/protocol/openid-connect/auth
        - --redeem-url=http://10.1.162.22:8080/auth/realms/bench/protocol/openid-connect/token
        - --validate-url=http://10.1.162.22:8080/auth/realms/bench/protocol/openid-connect/userinfo
        - --keycloak-group=/groups
        - --email-domain=*
        - --cookie-secret=SvoHyYPISY3FA5YRLEtxOA==
        - --http-address=0.0.0.0:4180

        - --pass-access-token=true
        - --pass-authorization-header=true      
        - --pass-basic-auth=true
        - --pass-host-header=true
        - --pass-user-headers=true
        - --set-xauthrequest=true
        - --set-authorization-header=true      
        
        - --standard-logging=true
        - --auth-logging=true
        - --request-logging=true
        - --skip-provider-button=true

        - --cookie-samesite=none
        - --cookie-secure=false
        - --scope=openid
        - --upstream=static://200
        - --redirect-url=http://localhost:4180/oauth2/callback        
        - --skip-auth-preflight=false
[...]
```

Here is what happens:
1. I go to Envoy's IP, and am successfully redirected to the Keycloak login page
2. I enter my creds, and click log in
3. I get "403 Permission Denied" http: named cookie not present, and a Sign in link underneath. I click on Sign in.
4. I'm redirected to localhost:4180, and only see the message "Authenticated" in my browser
5a. I go again to Envoy's IP, and am back again at step 3. 
5b. If I rather hit back at this point, instead of going to Envoy's IP, I get "500 Internal Server Error" Internal Error, and the Sign in link, underneath

```
[2020/10/21 17:47:08] [logger.go:490] mapping path "/" => static response 200
[2020/10/21 17:47:08] [logger.go:490] OAuthProxy configured for Keycloak Client ID: bench-api
[2020/10/21 17:47:08] [logger.go:490] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite:none refresh:disabled
[2020/10/21 17:47:08] [logger.go:490] HTTP: listening on 0.0.0.0:4180
**[1]**
[2020/10/21 17:48:11] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.1.162.29:47950 - - [2020/10/21 17:48:11] 10.1.162.29:10000 GET - "/" HTTP/1.1 "" 302 295 0.009
**[2]**
127.0.0.1:57068 - asd@asd [2020/10/21 17:48:38] [AuthFailure] Invalid authentication via OAuth2: unable to obtain CSRF cookie
127.0.0.1:57068 - - [2020/10/21 17:48:38] localhost:4180 GET - "/oauth2/callback?state=c6a838c8103879e40ead4bb0c99f9930%3A%2F&session_state=f9be3858-39ad-4646-99de-b648bd126919&code=2685eec5-c99a-44f9-8528-8615211d1cf8.f9be3858-39ad-4646-99de-b648bd126919.b1c8f129-2079-41c0-9317-a2f35155944d" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 403 353 0.034
**[3]**
127.0.0.1:57842 - - [2020/10/21 17:51:27] localhost:4180 GET - "/oauth2/sign_in" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 302 295 0.002
127.0.0.1:57842 - asd@asd [2020/10/21 17:51:27] [AuthSuccess] Authenticated via OAuth2: Session{email:asd@asd user: PreferredUsername: token:true}
127.0.0.1:57842 - - [2020/10/21 17:51:27] localhost:4180 GET - "/oauth2/callback?state=dadea6a25eb63610d4e868b11ebe43ee%3A%2F&session_state=f9be3858-39ad-4646-99de-b648bd126919&code=5dbc9642-7d5a-4dcd-8863-c9bf000c3ba2.f9be3858-39ad-4646-99de-b648bd126919.b1c8f129-2079-41c0-9317-a2f35155944d" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 302 24 0.025
127.0.0.1:57842 - asd@asd [2020/10/21 17:51:27] localhost:4180 GET static://200 "/" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 200 13 0.000
**[5b]**
[2020/10/21 17:54:36] [logger.go:508] Error redeeming code during OAuth2 callback: no access token found {"error":"invalid_grant","error_description":"Code not valid"}
127.0.0.1:58518 - - [2020/10/21 17:54:36] localhost:4180 GET - "/oauth2/callback?state=5e78b06cd86904bd5f106ffa45c9251d%3A%2F&session_state=f9be3858-39ad-4646-99de-b648bd126919&code=944d6277-dcd9-483a-bc08-4f36777703d2.f9be3858-39ad-4646-99de-b648bd126919.b1c8f129-2079-41c0-9317-a2f35155944d" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 500 345 0.004
```

You can see the output of steps 1-5 in the log above.

Any idea what I'm doing wrong ? I went through all the issues in this repo, tried everything mentioned, but got all kinds of errors. It's the closest I got, with the current configuration.

**Comment by anst270125** [comment]
I also made a screen recording to see more easily what happens: [https://youtu.be/XpNewO8SDZA](https://youtu.be/XpNewO8SDZA)

**Comment by anst270125** [comment]
### **Update**

I (temporarily) solved the CSRF cookie issue by making all Kubernetes services (Keycloak, Envoy and Oauth2_proxy) accessible from localhost (NodePort services).
The issue I'm still having is related to the redirection after the authentication. This is the current workflow:

1. I go to Envoy's IP and am redirected to the Keycloak login page. I enter my creds and log in.
2. I'm redirected to http://localhost:30418/ (oauth2-proxy's IP), with code 200 and the message "Authenticated"

```
[2020/10/23 10:59:12] [logger.go:490] mapping path "/" => static response 200
[2020/10/23 10:59:12] [logger.go:490] OAuthProxy configured for OpenID Connect Client ID: bench-api
[2020/10/23 10:59:12] [logger.go:490] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite:none refresh:disabled
[2020/10/23 10:59:12] [logger.go:490] HTTP: listening on 0.0.0.0:4180
[1]
[2020/10/23 11:00:01] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.0.2.15:48280 - - [2020/10/23 11:00:01] localhost:30000 GET - "/" HTTP/1.1 "" 302 295 0.000
[2]
10.0.2.15:40690 - asd@asd [2020/10/23 11:00:34] [AuthSuccess] Authenticated via OAuth2: Session{email:asd@asd user:375771d3-16cf-4a09-a425-472abb86fcc3 PreferredUsername:asd token:true id_token:true created:2020-10-23 11:00:34.802817422 +0000 UTC m=+82.700092579 expires:2020-10-23 11:05:34.799071491 +0000 UTC m=+382.696346651 refresh_token:true}
10.0.2.15:40690 - - [2020/10/23 11:00:34] localhost:30418 GET - "/oauth2/callback?state=42d2f4d7bab39b84a95501258b372827%3A%2F&session_state=b3acaf19-b208-4a9e-b296-e5895b7a74f9&code=ba52741f-49bb-48a0-b548-8ab291604a89.b3acaf19-b208-4a9e-b296-e5895b7a74f9.b1c8f129-2079-41c0-9317-a2f35155944d" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 302 24 0.016
10.0.2.15:40690 - asd@asd [2020/10/23 11:00:34] localhost:30418 GET static://200 "/" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 200 13 0.000
```

Any ideas why I'm not redirected to my Envoy cluster after logging in ?

**Comment by JoelSpeed** [comment]
I think you need to provider either a header (`X-Auth-Request-Redirect`) or a query string param (`rd`) with where you'd like to be redirected to after authentication on that initial request that starts the authentication flow.

I don't know how the envoy external AuthZ modules works but is there a way you could add one of these?

**Comment by anst270125** [comment]
Thanks Joel, I'll try it later today.
Here is the Envoy configuration:

```
static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
              - name: envoy.http_connection_manager
                typed_config:
                  '@type': "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
                  stat_prefix: http_proxy
                  route_config:
                    name: all
                    virtual_hosts:
                      - name: bench_cluster
                        domains:
                          - '*'
                        routes:
                          - match: { prefix: "/"}
                            route:
                              cluster: bench_cluster
                  http_filters:
                      - name: envoy.ext_authz
                        config:
                          http_service:
                            server_uri:
                              uri: 10.0.2.15:30418
                              cluster: ext-authz
                              timeout: 3.25s

                      - name: envoy.router
      clusters:
        - name: ext-authz
          connect_timeout: 5.25s
          type: strict_dns
          lb_policy: round_robin
          hosts:
          - socket_address:
              address: 10.0.2.15 #oauth2-proxy
              port_value: 30418

        - name: bench_cluster
          connect_timeout: 5s
          type: strict_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: bench_cluster
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: 10.0.2.15 #my main app
                        port_value: 30030
```

The relevant part is the envoy.ext_authz filter. In my view, the ext authz filter is quite simple. From Envoy docs: _"On authorization response status HTTP 200 OK, the filter will allow traffic to the upstream_" So, when I try to reach Envoy's IP, I'm redirected to 10.0.2.15:30418 (which is oauth2-proxy) If I get status 200, I'm allowed "upstream", to my main cluster (10.0.2.15:30030).

As described previously, if I replace oauth2 proxy in the ext authz filter with a nodeJs server that returns 200 OK, I'm allowed upstream. But with oauth I get the 200 Authenticated message but am not redirected upstream.

I'll try the thing with the redirect header and come back with an update.

**Comment by JoelSpeed** [comment]
```
                  http_filters:
                      - name: envoy.ext_authz
                        config:
                          http_service:
                            server_uri:
                              uri: 10.0.2.15:30418?rd=...
                              cluster: ext-authz
                              timeout: 3.25s

**Comment by anst270125** [comment]
It doesn't work that way, but it works by setting the `X-Auth-Request-Redirect` header. Here is the ext_authz filter.:

```
                   http_filters:
                      - name: envoy.ext_authz
                        config:
                          http_service:
                            server_uri:
                              uri: 10.0.2.15:30418
                              cluster: ext-authz
                              timeout: 3.25s

                            authorization_request:
                              headers_to_add:
                              - key: x-auth-request-redirect
                                value: http://localhost:30000

                              allowed_headers:
                                patterns:
                                - exact: "cookie"
```

I also had to add the cookie header part, in order to make it work.

**Comment by JoelSpeed** [comment]
We should try and add something to our docs about this 🤔  Just to confirm it is now working?

**Comment by anst270125** [comment]
Yes, the log in and redirection part seem to work now, thanks Joel :)
But I am now facing some other issues, regarding accessing oauth2-proxy's [endpoints](https://oauth2-proxy.github.io/oauth2-proxy/endpoints) and logging out.

So, this is what I'm doing:

1. I go to Envoy's IP, am redirected to Keycloak, log in, and am redirected back to Envoy, everything alright
2. I now try to access the following endpoints, with the url being _**envoyIP**/endpoint_:

    - /oauth2/userinfo
    - /oauth2/auth
    - /ping
    - /something

3. I now try to access the same endpoints, with the url being _**oauth2-proxyIP**/endpoint_


```
[2020/10/26 16:42:01] [logger.go:490] mapping path "/" => static response 200
[2020/10/26 16:42:01] [logger.go:490] OAuthProxy configured for Keycloak Client ID: bench-api
[2020/10/26 16:42:01] [logger.go:490] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite:none refresh:disabled
[2020/10/26 16:42:01] [logger.go:490] HTTP: listening on 0.0.0.0:4180
[1]
[2020/10/26 16:42:17] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.0.2.15:56030 - - [2020/10/26 16:42:17] localhost:30000 GET - "/" HTTP/1.1 "" 302 322 0.000
10.0.2.15:33746 - asd@asd [2020/10/26 16:42:19] [AuthSuccess] Authenticated via OAuth2: Session{email:asd@asd user: PreferredUsername: token:true}
10.0.2.15:33746 - - [2020/10/26 16:42:19] localhost:30418 GET - "/oauth2/callback?state=131a5c59432aa41957ce13d0aca4f4fd%3Ahttp%3A%2F%2Flocalhost%3A30000&session_state=dea8834f-a8ef-4ba6-98c2-66ffcef75d19&code=06d92518-3157-461c-99c6-95d42ca6e261.dea8834f-a8ef-4ba6-98c2-66ffcef75d19.b1c8f129-2079-41c0-9317-a2f35155944d" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 302 45 0.011
10.0.2.15:56030 - asd@asd [2020/10/26 16:42:19] localhost:30000 GET static://200 "/" HTTP/1.1 "" 200 13 0.000
[2]
10.0.2.15:56030 - - [2020/10/26 16:43:24] localhost:30000 GET - "/oauth2/userinfo" HTTP/1.1 "" 200 20 0.001
10.0.2.15:56030 - asd@asd [2020/10/26 16:43:35] localhost:30000 GET - "/oauth2/auth" HTTP/1.1 "" 202 0 0.000
10.0.2.15:56030 - - [2020/10/26 16:43:41] localhost:30000 GET - "/ping" HTTP/1.1 "" 200 2 0.000
10.0.2.15:56030 - asd@asd [2020/10/26 16:43:48] localhost:30000 GET static://200 "/something" HTTP/1.1 "" 200 13 0.000
[3]
10.0.2.15:34596 - - [2020/10/26 16:44:36] localhost:30418 GET - "/oauth2/userinfo" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 200 20 0.000
10.0.2.15:34596 - asd@asd [2020/10/26 16:44:40] localhost:30418 GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 202 0 0.000
10.0.2.15:34596 - - [2020/10/26 16:44:45] localhost:30418 GET - "/ping" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 200 2 0.000
10.0.2.15:34596 - asd@asd [2020/10/26 16:44:49] localhost:30418 GET static://200 "/something" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0" 200 13 0.000
```

When trying to access the endpoints using Envoy's IP, it looks like all 4 endpoints are proxied upstream, not only the last one, as it's supposed to be. When accessing the endpoints with oauth's IP, I get the expected output for the first three, and `/something` is proxied upstream. Now I'm not sure if the problem is with oauth2-proxy or Envoy.

**Comment by anst270125** [comment]
Problem solved, it was Envoy's fault and it makes sense. The ext_authz filter also applies for oauth2's endpoints. That means, when accessing oauth2's endpoints, Envoy will still redirect upstream in the case of a `200` response.
So, endpoints like _/ping_ and _oauth2/userinfo_ were forwarded upstream because they return a `200` response. The _oauth2/auth_ endpoint caused a failed authentication, because it returns `202` while ext_authz expects `200`. So it now clear to me that oauth2 endpoints don't need to pass through the ext_authz filter, since it can only do redirection upstream or cause failed authentication.

Luckily Envoy makes it possible to disable the ext_authz filter for certain paths. I now redirect all /oauth2/* traffic to the oauth2-proxy cluster, and am able to access oauth2's endpoints(except ping and robots) using _envoyIP/endpoint_.

<pre>
virtual_hosts:
                      - name: bench_cluster
                        domains:
                          - '*'
                        routes:
                          <b>- match:
                              prefix: "/oauth2"
                            route:
                              cluster: ext-authz #oauth2-proxy cluster
                            typed_per_filter_config:
                              envoy.filters.http.ext_authz:
                                "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                                disabled: true</b>

                          - match:
                              prefix: "/"
                            route:
                              cluster: bench_cluster
</pre>

**Comment by andreyprezotto** [comment]
@anst270125 I'd like to ask for some information about your stack because I'm facing a very similar issue 
My provider is Okta and the full description of the issue is here #867 

1. I go to Envoy IP and get redirected to Okta and performs login
2. I get back to Envoy and the oauth2_proxy handles the /callback request 
3. I get redirected to the upstream service but I don't see the Authorization header or X-Forwarded-Access-Token header in this final request 

So, in your case do you see or use them in anyway?
What Envoy version are you using?
What oauth2-proxy version?

**Comment by andreyprezotto** [comment]
Thanks for sharing @anst270125. 
I have quite similar config here but I don't see these headers being forwarded to my java app.
I'll try to debug using a simple nodeJS server and you did and see what I get

**Comment by dippynark** [comment]
Sorry if this is not useful but I have written up my steps for getting this working with Istio and an EnvoyFilter [here](https://www.blog.jetstack.io/blog/istio-oidc/) -- I use `--provider=oidc` but maybe there are some clues

**Comment by regicsolutions** [comment]
Has anyone been successful with getting Okta working with Istio?
