### ISSUE TITLE
Can't add outh2-proxy protected datasource to grafana

### ISSUE THREAD

**Issue by nmass-betpawa** [oauth2-proxy/oauth2-proxy#868]
Grafana has such switch in datasource configuration - `Forward OAuth Identity`
I'm trying to add oauth2-proxy protected prometheus as datasource and don't understand what the problem is.
First of all from standart chrome a heve such messages in console
```
Access to fetch at 'https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=202594446066-0krpj25of2ddiq0fptpjeq2dc77kf9ba.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fprometheus.qa-new.xxx.com%2Foauth2%2Fcallback&response_type=code&scope=profile+email&state=dd0335c5f4bc3ce25b0a4b4ee8de9494%3A%2Fapi%2Fv1%2Fquery%3Fquery%3D1%252B1%26time%3D1603485165.006' (redirected from 'https://grafana.xxx.com/api/datasources/proxy/27/api/v1/query?query=1%2B1&time=1603485165.006') from origin 'https://grafana.xxx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
I tryed to run Chrome with CORS turned off and it doesn't show cors errors but now it stucks at such request
```
Request URL: https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=202598444066-0krpj25of2ddiq0fptpjeq2dc77kf9ba.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fprometheus.qa-new.xxx.com%2Foauth2%2Fcallback&response_type=code&scope=profile+email&state=850c45ad35aa645cf8051644fd84a46d%3A%2Fapi%2Fv1%2Fquery%3Fquery%3D1%252B1%26time%3D1603486894.032
```
as i understood callback doesn't fired
oauth2-proxy shows in logs
```
Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
```
Directly all works perfect...

**Comment by NickMeves** [comment]
If you are missing cookies, you might want to take a look at `cookie-domains` flag in case you are jumping between domains? And if that's the case, if you run into more issues, you might need to set the same domains in `whitelist-domains` for the allowed redirect domains if not the originating domain (that's usually the second problem people have if their first problem was fixed by setting `cookie-domains` 😉 )

**Comment by NickMeves** [comment]
Haven't heard a response. Closing this and assuming the answer helped solve your problem.
