### ISSUE TITLE
Getting 404 on requests coming from trusted IPs

### ISSUE THREAD

**Issue by rafaelfelix** [oauth2-proxy/oauth2-proxy#871]
## Expected Behavior
Requests coming from IPs with the ranges specified in `trusted_ips` should receive a 2xx response (ideally 202 Accepted, same as a valid oauth2 session sent via cookie would yield).

## Current Behavior
Requests coming from IPs with the ranges specified in `trusted_ips` are receving a 404 Not Found response, regardless the specified path.

## Possible Solution

Maybe I'm being too simplistic, but replacing `p.serveMux.ServeHTTP(rw, req)` with something like `rw.WriteHeader(http.StatusAccepted)` around here should do the trick:

https://github.com/oauth2-proxy/oauth2-proxy/blob/8abc4e6d876b2e4a5c348e05927b2c472fdfef9b/oauthproxy.go#L891-L896

From a quick search, I see that the `SkipAuthProxy` method isn't really called anywhere else.

## Steps to Reproduce (for bugs)

1.  add your client ip address to the `trusted_ips` configuration option in oauth2_proxy.cfg, or specify it via `--trusted-ip`. In my case, I run oauth2-proxy behind a reverse proxy so I'm setting `reverse_proxy = true` as well
2. start oauth2-proxy 
3. `curl localhost:4180/` (you get a 404 Not Found back. Remove the `trusted_ips` and you get the 403 Forbidden with the sign in page as expected).

## Context

I need to allow access from trusted IPs to some domains. If the IP is trusted (I make sure we're not vulnerable to spoofing through a reverse proxy in front of it), I expect the request to the /auth endpoint to behave the same way as when a valid oauth2 session is sent via cookie (202 Accepted). If the client is connecting from an "untrusted" IP, the user should be redirected to the start of the oauth2 flow.

## Your Environment

- Version used: v6.1.1 on the official docker image. Tested on docker for mac and in an EKS cluster running on linux instances, same behavior.

**Comment by NickMeves** [comment]
What is your `upstream` configured to? If you come from a `trusted-ip` we will directly proxy the request to whatever your `upstream` server is set to on the same path (in your example case, `/`).  So if an alternative cookied session from an untrusted IP hit those same paths, you'd get the same status code: whatever your backend returned.

If you need a dummy 2XX status code, you can use the `static://200` or `static://202` upstream for the paths you want it on.  Check out the docs for multi upstream support on multiple paths.

Or are you looking for this to work in the `/oauth2/auth` endpoint?  I think I see the mistake in the logic in that case: the original `trusted-ips` PR piggy-backed off the `skip-auth-regex` skip logic.  That only applied to proxied paths (which for path skipping, makes sense, we wouldn't skip core `/oauth2` paths via that.  But for IP based allowlists, that logic doesn't fully translate as you seem to have uncovered 😅

**Comment by rafaelfelix** [comment]
hi @NickMeves, thanks for the quick response. My `upstream` was set to `file:///dev/null`, so your explanation regarding the `trusted-ips` logic acting weird makes total sense to me now. I'd consider rewriting it to act more as an allowlist instead, as the current behavior is not really helpful for use cases where oauth2-proxy is behind a reverse proxy, and not acting as one. What do you think? btw, I'm using oauth2-proxy as described here: https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

Regarding the `/oauth2/auth` being skippable when a trusted IP is connecting: if I understood correctly, `/oauth2/auth` is not the one that actually performs authentication (that would be `/oauth2/start`). `/oauth2/auth` validates whether the user has a valid session or not (returning either 401 or 202). What I'm suggesting here is that, if the user is coming from a `trusted-ip`, it means the user is authorized, so why not return `202` in this case?

Hope I made myself clear. Looking forward to hear from you.

**Comment by NickMeves** [comment]
So I actually had strong security apprehensions about even supporting `trusted-ip` + `reverse-proxy` at the same time due to spoofing concerns when that PR originally was presented a few months ago.  We decided to go with a strict warning to help prevent people from setting up architectures vulnerable to this (it is more difficult to architect securely than to inadvertently leave a huge security hole, hence the warning):

https://github.com/oauth2-proxy/oauth2-proxy/blob/d8b0d9059da0ba7d20b60803b847be67c1466549/pkg/validation/allowlist.go#L21

For this reason, and especially for how easy it is to configure kubernetes ingress annotations without a user having the ability to easily protect themselves from this vulnerability, I don't want to merge this into the main branch.  You can fork if you'd like.

What I actually recommend is to keep your setup secure is that you manage the IP trust list at your nginx proxy layer (instead of the oauth2-proxy auth subrequest layer).

This ingress annotation is available to you: `nginx.ingress.kubernetes.io/whitelist-source-range`

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#whitelist-source-range

**Comment by rafaelfelix** [comment]
I understand @NickMeves, thanks for the clarification. I understand that's not the direction you want to go with oauth2-proxy and I respect the reasons you presented. Regarding using a second ingress, I don't think this will produce the desired effect, of having a logical OR between IP allowlist and oauth2 (if the former is not matched, then perform the latter). I'll try to sort this out in a different way.

**Comment by JoelSpeed** [comment]
> But truthfully, I'm not sold an /oauth2/auth endpoint should be skippable with any sort of allowlist -- the purpose of it is to perform authentication.

I've always assumed this to be an is the user allowed based on the rules provided endpoint, so actually, I would expect a valid IP to return 202 here. But I think this is worth some discussion before we make any changes. I'd imagined once we restructured that this endpoint would be after all of the authn modules 🤔

**Comment by NickMeves** [comment]
Yeah - my explanation is better phrased as:

> the purpose of it is to authorize an authenticated session

My biggest fear is `/oauth2/auth` is used most heavily by Kubernetes ingress most likely. There's not much configurable knobs for people to make sure the reverse proxy + trusted IP combo operation isn't spoof-able.

We had the assumption that users that wanted to mix these paradigms would understand the risks and secure the reverse proxy layer well enough to prevent `X-Forwarded-For` or `X-Real-IP` stuffing.

I fear Kubernetes ingress integration is too easy to configure and the ability to "Footgun" will be large.  Leaving a wake of insecure `OAuth2-Proxy` deployments.

**Comment by NickMeves** [comment]
I'm actually curious, when reached via subrequest: what does OAuth2-Proxy even see as the Client IP? Does it see the nginx ingress pod's IP as the client IP -- or does it do similar proxying logic and convert the request IP to an `X-Forwarded-For` chain as if it were a proxy even though it creates a distinct subrequest?
