### ISSUE TITLE
Question: Allow requests without existing session

### ISSUE THREAD

**Issue by Bibob7** [oauth2-proxy/oauth2-proxy#872]
I'm not sure if this is against the idea of the oauth2-proxy, but let me explain what we want to achieve and maybe there is already a way to do it.

## Expected Behavior

For different backend endpoints we would like the enable the following behavior:
When a customer sends a request the request can contain an oauth2-proxy session cookie or not. If it contains a session cookie oauth2-proxy should just decrypt the cookie, refreshes the access and id token if necessary and passes the id_token and/or access_token via the response to the upstream service
If the request does not contain the session cookie, the request should directly be forwarded to the upstream service. So in the end the oauth2-proxys task is just to decrypt the authentication information if their are available and passes them to the upstream.

## Current Behavior

Based on my investigations, it is not configurable to accept requests without session cookies.
Either the oauth2-proxy redirects to the IDP to create a session or in case of ajax requests, 401 is returned immediately.

## Possible Solution

Add a configuration flag to also accept requests without session cookie don't perform a redirect for login.

**Comment by JoelSpeed** [comment]
Typically the proxy is meant to reject all requests that aren't authenticated.

In this scenario, where would the OAuth2 Proxy cookie come from? Is the idea that you can access the site and then sign in and get more access if you are signed in? 

I wonder if you could achieve this by using nginx and the auth_request module but handling the error from the auth_request differently, ie, just proxying to the backend if the auth_request fails

**Comment by Bibob7** [comment]
Yeah, you might be right about that. I also think that it should probably be decided on the Ingress side. But I haven't found anything yet. At least not with nginx ingress.

**Comment by Bibob7** [comment]
> In this scenario, where would the OAuth2 Proxy cookie come from? Is the idea that you can access the site and then sign in and get more access if you are signed in?

Exactly! I can give a concrete example: So let's say we want to display a buy box on a product detail page of an e commerce website. If the user is not logged in, he should only see the price and shipment costs. If he is logged in, he should see additionally some individual discount. So there are two versions, for authenticated users and for not authenticated users.

Do you have in general an idea, how to deal with this?

**Comment by Bibob7** [comment]
What about introducing a new endpoint like /auth, but it will always response with 200. If there is a valid session, we could append for example the authorization header and if not, it will be empty.
