### ISSUE TITLE
Plan to handle multiple providers at once?

### ISSUE THREAD

**Issue by Aerion** [oauth2-proxy/oauth2-proxy#88]
Is there any plan to support **multiple providers**?

It would be useful if the service wants to authenticate two users X and Y where:
* X has a Google account but **doesn't have** a Github account
* Y **doesn't have** a Google account but has a Github account

This could be presented as follows.
![multiple_providers_idea](https://user-images.githubusercontent.com/9089317/53901189-a6142980-403e-11e9-83ea-0f07056014fc.png)

_This question was asked before the fork: https://github.com/bitly/oauth2_proxy/issues/509_

**Comment by pixelblender** [comment]
bump. +1

**Comment by deiga** [comment]
What would this require in the current implementation to be achievable?

**Comment by jdequatrebarbeszenvalue** [comment]
That would be very useful!

Options: configuration must allow prodiver-related keys mutliple values(`provider`, `client_id`, `client_secret`...)

OAuthProxy:
- the single `provider` by must be replacer by an array,
- the sign-in template must offer multiple providers,
- `OAuthStartPath`, `OAuthCallbackPath` and `redirectURL` must become provider specific.

**Comment by JoelSpeed** [comment]
This might become possible once we introduce structured configuration (#532)

**Comment by tambetliiv** [comment]
Any plans to continue with this?

**Comment by JoelSpeed** [comment]
We ended up continuing this conversation in a new issue https://github.com/oauth2-proxy/oauth2-proxy/issues/926
