### ISSUE TITLE
Possible to use oauth2-proxy to authenticate user to services with oauth provider support?

### ISSUE THREAD

**Issue by niklasgrewe** [oauth2-proxy/oauth2-proxy#881]
Hi, i use docker and traefik on my own server to provide my services. Now it is so that I have many services where I have to login, for example Portainer, Gitlab, RocketChat etc. To be honest, it is quite annoying when you have to enter your login data everywhere. I have read about it that traefik also handles Forward-Auth. Is it therefore possible to use oauth2-proxy for global authentication for my docker services? 

I imagine the Login Flow like this:
1. the user visits `http://chat.domain.com`
2. the user is redirected to `auth.domain.com`
3. he can select his preferred auth provider (e.g. Google) via ui
4. the user is forwarded to the selected Auth-Provider
5. he will be redirected to `auth.domain.com` and then to the destination `chat.domain.com`
6. the user is automatically logged in to the chat app
7. if he now go to `gitlab.domain.com`, he is also already logged in

Is there any way to implement this with oauth2-proxy or any other library? Would it also be possible to set up a dashboard maybe at `auth.domain.com/dashboard` where users can see what services they can access? I am looking forward to your ideas and suggestions

**Comment by NickMeves** [comment]
I'm hoping to have a blog post up within the next 2-3 weeks detailing how to use `OAuth2-Proxy` as a central "Access Proxy" in a corporate network as the central SSO solution, so all the apps can ride the same session cookie at the `.example-corporate.domain` domain scope. The key integration point on Kubernetes being the ingress annotations to easily connect everything.

As far as allowable apps, that isn't something we envisioned being done in OAuth2-Proxy as far as I know. That's a responsibility I think is best left to the IdP?  E.g. if I go to my IdP (OneLogin), I can see the applications I've been granted access to.

**Comment by NickMeves** [comment]
For stage (3) in your vision, we've had multi-provider support requested before -- it just hasn't been a priority yet compared to other refactors and new features we want to tackle in the next few months.

We are targeting structured configs for v8, I think that sets the stage nicely for multi-provider support to potentially come next.

**Comment by niklasgrewe** [comment]
thank you for your quick response. If you received the blog article, could you link it here? Of course I would be very interested. I don't work with Kubernetes but I'm sure I can learn a thing or two for Docker...

that you had imagined something different for oauth2-proxy, I thought so, but what exactly do you mean by ldp (One Login) ? Do you think I should rather use ldap for authentication so that users can see what resources they can access?

**Comment by NickMeves** [comment]
IdP = Identity Provider.  Mine is OneLogin. Okta, Ping are other big players in the OIDC vendor space.
