### ISSUE TITLE
Possible to access backend application using either IP address or Domain name?

### ISSUE THREAD

**Issue by ashp71** [oauth2-proxy/oauth2-proxy#882]
I have a custom OIDC Provider (IdentityServer) along with some other applications deployed in a k8 cluster. The ingresses to applications deployed in the cluster are protected by oauth2-proxy (reason for this setup is because we want to protect 3rd party UI that have no built in access control).
 
The system works as expected when: 
a. the cluster is accessed via IP addr & oauth-proxy is configured to use OIDC Provider by its IP addr.
b. the cluster is accessed via Domain name & oauth-proxy is configured to use OIDC Provider by its domain name.

I have tried to access the cluster using IP addr (when oauth-proxy is pointing to domain name) and vice versa, but I end up getting a 403 error "http: named cookie not present" in either case.  

So, is it even possible to access backend application using either IP addr or domain name while having a static oauth2-proxy configuration? What would I have to change to achieve it? 

Thank you,
A.P 

- Version used: 6.1.1

**Comment by JoelSpeed** [comment]
> The system works as expected when:
> a. the cluster is accessed via IP addr & oauth-proxy is configured to use OIDC Provider by its IP addr.
> b. the cluster is accessed via Domain name & oauth-proxy is configured to use OIDC Provider by its domain name.

OIDC providers are supposed to have a single name, based on what is in the well known configuration endpoint, are you suggesting that your IDP gives back a different issuer URL based on how you access it?

> I have tried to access the cluster using IP addr (when oauth-proxy is pointing to domain name) and vice versa, but I end up getting a 403 error "http: named cookie not present" in either case.

What options are you configuring here? This isn't very clear what you mean by "pointing to domain name"
