### ISSUE TITLE
Refactor OIDC `profileURL` call to `EnrichSessionState`

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#883]
Currently a call to the `profileURL` is embedded inside of the `findClaimsFromIDToken` as a fallback in case the claims are missing.

This logic doesn't belong there -- it should be implemented in `EnrichSessionState` to be more uniform with other providers in how they do secondary calls with an Access Token to enrich the session with more data.

This will additionally remove the need for this corner case logic for bearer sessions (since bearer sessions don't have an Access Token to use) here: https://github.com/oauth2-proxy/oauth2-proxy/blob/3fa42edb7350219d317c4bd47faf5da6192dc70f/providers/oidc.go#L247

This is because `EnrichSessionState` is only called in the `Callback` flow after the `Redeem` method.

**Comment by JoelSpeed** [comment]
What do we use the `profileURL` for at the moment? IIRC it's used to try and find a claim if the ID Token doesn't contain the claim right?

Is there some way we can make a generic claim extraction that tries to get a claim and if not falls back to the profile URL? But do so in a way that the profile URL is called at most once 🤔 This is something I was thinking about for when we support any additional claim users want us to try and look up, we will need some logic like this I would imagine

**Comment by NickMeves** [comment]
If any claims are missing from the IDToken (email & potentiall groups in the future) -- OIDC provider attempts to get it from the `profileURL` here: https://github.com/oauth2-proxy/oauth2-proxy/blob/65016c8da155396ce68f7221d8e10703c89f0342/providers/oidc.go#L257

We are migrating this logic in the other providers to `EnrichSessionState` (a lot of them previously had it in `GetEmailAddress`). Makes sense to do the same in OIDC.

Also helps reduce the complexity of the logic where we try to figure out how `findClaimsFromIDToken` is called (since in the Bearer auth case the function is also used, we do not want call the profileURL, we take what we get)

**Comment by NickMeves** [comment]
> Is there some way we can make a generic claim extraction that tries to get a claim and if not falls back to the profile URL? But do so in a way that the profile URL is called at most once 🤔 This is something I was thinking about for when we support any additional claim users want us to try and look up, we will need some logic like this I would imagine

Forgot to address this part: This is the benefit of moving the logic to `EnrichSessionState`, it is only called at the moment immediately after the initial `Redeem` method during initial sign in.

**Comment by anannaya** [comment]
Hopefully https://github.com/oauth2-proxy/oauth2-proxy/pull/850#discussion_r513963529 changes 
will be part of this issue.

**Comment by NickMeves** [comment]
This is done.
