### ISSUE TITLE
If the access is denied (403) due the email restriction, it's not possible to sign in with another user

### ISSUE THREAD

**Issue by xcabur1** [oauth2-proxy/oauth2-proxy#885]
If a user successfully authenticate to the okta oicd provider but is not authorized, because the email is not in the authenticated_emails_file, the message "403 Permission Denied" occures. So far so goot, but now it's not possible to login with a other user. If I call the /sign_in endpoint I will be signed in automatically with the same user and get the 403 error again. I guess this is because the provider authantication token still exist.

## Expected Behavior
If the "403 Permission Denied" error occures it should be possible to login with a other user

## Current Behavior
If the "403 Permission Denied" error occures I can't login with a other user because I'm allready authenticated

## Possible Solution
If the "403 Permission Denied" error occures call the provider logout URL to destroy the provider authentication cookie
This may requires a new configuration parameter to specify the provider logout URL instead pass it by the rd parameter of the /sign_out endpoint

## Steps to Reproduce (for bugs)
**oauth2 proxy config:**
```
provider = "oidc"
redirect_url = "https://myapp.com/oauth2/callback"
oidc_issuer_url = "https://dev-1234.okta.com/oauth2/default"
whitelist_domains = ".okta.com"

client_id = "123456789"
client_secret = "987654321"
authenticated_emails_file = "C:\\oauth2-proxy\\mail_allow.cfg" #contains test1@myapp.com

cookie_secure = true
cookie_secret = "P@ssw0rdP@ssw0rd"
pass_access_token = true
reverse_proxy = true
```
**Okta Config:**
```
Application: Web
Domain: dev-1234.okta.com
Grant Types: Auhtorization Code, Refresh Token
Login redirect URIs: https://myapp.com/oauth2/callback	
Logout redirect URIs: https://myapp.com/oauth2/sign_in
Asigned User: test1@myapp.com, test2@myapp.com
```
**Do:**
```
1. https://myapp.com/oauth2/sign_in
2. Sign in with test2@myapp.com
```

## Your Environment
- Version used: 6.1.1
- Okta oidc provider
- nginx 1.19.3

**Comment by NickMeves** [comment]
Thanks for the idea, I see the potential merit in this -- I would implement it differently though.  I think adding a `SignOut` method on the provider interface and letting each provider configure how it operates is the most scalable and seamless user experience (endusers wouldn't need to worry about a querystring parameter on the sign out endpoint).

Thing we need to avoid is I think most users wouldn't want a sign-out in 1 OAuth2-Proxy app for the IdP to kill all the users SSO sessions in the IdP. For that reason, I am torn if this is something that we would want to take the effort to implement.

In absence of that:

I recommend controlling access with the app you've configured inside of Okta (groups, userlist, whatever).  And trust everything you get from Okta with `OAuth2-Proxy` and ditch the `authenticated_emails_file`

**Comment by xcabur1** [comment]
Thank you for your assessment, I am not sure if the situation has been correctly assessed. In my opinion it is not about a feature, it is about an issue. I use the Oauth2 Proxy as an auth request module in nginx to authenticate third party applications that do not have integrated authentication. This limits my ability to react to the behavior when Oauth2 proxy does not. If a "403 access denied" occurs (for whatever reason), there is no automatic logout to the provider and oauth2 will automatically log back on. I think this behavior should be unwanted.

I am of the same opinion controlling trust in user management instead of the authenticated_emails_file configuration, but not all OIDC providers offer this possibility.

**Comment by NickMeves** [comment]
If implemented, this needs to be scalable to all future providers & extensions in the code.  So I think it needs to be core to the `provider` interface that all potential Provider plugins can use if they support it (with the default implementation returning an `Error Not Implemented` of some sort.

Then we can handle the proper route of connecting the `sign out` callback method in the main proxy object to the interface generically.

**Comment by xcabur1** [comment]
> If implemented, this needs to be scalable to all future providers & extensions in the code. So I think it needs to be core to the `provider` interface that all potential Provider plugins can use if they support it (with the default implementation returning an `Error Not Implemented` of some sort.
> 
> Then we can handle the proper route of connecting the `sign out` callback method in the main proxy object to the interface generically.

Sounds right

**Comment by Antiarchitect** [comment]
Suffering from this now, please reopen. I know we need to investigate towards:

```
GET /end/session/endpoint?id_token_hint=<hint>&post_logout_redirect_uri=<?????>&state=<somestate>
```

**Comment by ben-wallis** [comment]
I'm having the same issue as @xcabur1 describes above - when using oauth2-proxy with Keycloak and logging in with a user lacking a role configured in `allowed_roles` it results in the user getting stuck as they have a valid Keycloak session which oauth2-proxy accepts (but then returns 403 due to the missing role), with no way for the user to log out or attempt login with different credentials.

**Comment by tuunit** [comment]
Replaced by #2313
