### ISSUE TITLE
Question: Format of Regex in config file

### ISSUE THREAD

**Issue by omnibrain** [oauth2-proxy/oauth2-proxy#887]
I'm trying to configure a skip_auth_route Regex but I'm always getting this error:

```
[2020/11/02 08:07:02] [logger.go:508] ERROR: Failed to load config: error unmarshalling config: 1 error(s) decoding:

* '' has invalid keys: skip_auth_route
```

I tried to find an example of how the Regex should look like, but as far as I saw there isn't a single example regex in the documentation. I'm trying to exclude every route starting with /actuator/*. Here's what I've tried:

```
skip_auth_route = "/actuator/*"
skip_auth_route = "/actuator/.*"
skip_auth_route = "\/actuator\/*"
skip_auth_route = "\/actuator\/.*"
skip_auth_route = "\\/actuator\\/.*"
skip_auth_route = "\\/actuator\\/.\*"
skip_auth_route = "/\/actuator\/.\*"
```

Unfortunately I don't know any Go so I can't check the code.

I'm surprised no one had the same problem so the answer is probably super obvious and I'm doing a stupid mistake.

**Comment by TommyLike** [comment]
looks like the option is not recognized, check the binary version and try skip_auth_regex instead

**Comment by JoelSpeed** [comment]
This feature has merged into master but as far as I'm aware, isn't in a release yet. The docs currently show what's on master, we are working on a solution to make sure we only show the latest release in the docs.

The feature you're looking for will be available in v7.0.0 which we will hopefully have published by the end of 2020

**Comment by omnibrain** [comment]
OK I see, thanks for the explanation. Feel free to close this issue then.

**Comment by komalarg2010** [comment]
I get the same error even in version v7.1.3

[2021/07/06 23:46:17] [main.go:43] ERROR: failed to load config: error unmarshalling config: 1 error(s) decoding:

* '' has invalid keys: skip_auth_route

configuration: 

    skip_auth_route=["GET=/path/*"]

Which version is it available?

**Comment by JoelSpeed** [comment]
IIRC, this is one of those options where the name differs in the config/env because it can be set multiple times on the command line, try `set_auth_routes` instead

**Comment by komalarg2010** [comment]
> IIRC, this is one of those options where the name differs in the config/env because it can be set multiple times on the command line, try `set_auth_routes` instead

works, Thank you !!
