### ISSUE TITLE
M2M calls with AWS Cognito and oauth2-proxy not possible due to missing `aud` field

### ISSUE THREAD

**Issue by lyndon160** [oauth2-proxy/oauth2-proxy#891]
## Context

I'm trying to use the AWS Cognito identity provider with oauth2-proxy for machine to machine (m2m) calls.

When using the authorisation_code flow (for web login) with Cognito, the **ID token** returns included everything required for oauth2-proxy to allow the request (include the aud field).

For m2m calls, the client creds flow is used. The docs show that `--skip-jwt-bearer-tokens` is required, and depending on the audience,   `--extra-jwt-issuers` is also required. I've tested this configuration previously with Keycloak and it works as expected. Additional documentation added in https://github.com/oauth2-proxy/oauth2-proxy/pull/851/commits/c358750c521061d34a31802ee2d9df043ed9dbfa confirms that the 'aud' field is required:

> (the token must have [`aud`](https://en.wikipedia.org/wiki/JSON_Web_Token#Standard_fields) that matches this client id or one of the extras from `extra-jwt-issuers`)

However, when using client_creds flow, only an **access token** is returned, which with AWS Cognito does not return the 'aud' field. As far as I understand, this makes it not compatible with oauth2-proxy, as either the `aud` must be matched against either an audience provided in extra-jwt-issuers or an audience that matches the client configured in the proxy.

Here's the payload of a token

```
{
  "sub": "xxxxxxxxxxxxxxxxxx",
  "token_use": "access",
  "scope": "xxxxxx",
  "auth_time": 1604476544,
  "iss": "https://cognito-idp.eu-west-2.amazonaws.com/xxxxxxxx",
  "exp": 1604480144,
  "iat": 1604476544,
  "version": 2,
  "jti": "xxxxxx",
  "client_id": "xxxxxxx".     <------- replaces aud claim (feature of AWS Cognito)
}
```

This appears to be because AWS Cognito uses the `client_id` claim instead: https://stackoverflow.com/questions/53148711/why-doesnt-amazon-cognito-return-an-audience-field-in-its-access-tokens

Quote from https://tools.ietf.org/html/rfc7519
> If the principal processing the claim does not identify itself with a value in the "aud" claim when this claim is present, then the JWT MUST be rejected.

According to the above quite, not including `aud` is fine, and rejecting based on `aud` is only required if the `aud` claim is present. 

## Expected Behavior

oauth2-proxy should work with AWS Cognito for m2m calls.

## Current Behavior

oauth2-proxy rejects calls, due to a missing `aud` field in the access token (shown above) used to make the call. 

## Possible Solution

Assuming I've not misunderstood the oauth2-proxy docs, and there isn't a solution to this then:

- Offer an option to only require the issuer for validation (this is ok depending on how the cognito pool is used, and is supported by the JWT RFC)
- Add a configuration option for the to be able to validate against the a custom claim (`client_id`) instead of `aud` then this would work as expected

## Version used:
6.1.1

**Comment by NickMeves** [comment]
Well that's annoying of them...

This is deeper in the OIDC library we use out of our code: https://github.com/coreos/go-oidc/blob/v2/verify.go#L79

Hardcoded to pull that from the `aud` claim.  We'd need to allow skipping the aud check via (`SkipClientIDCheck`).

Not sure I'm OK with the security implications of allowing us to customize skipping the `aud` -- leaves you open to replay attacks with IDTokens taken from other apps and replayed where the `aud` doesn't match & isn't checked.

**Comment by lyndon160** [comment]
Hi @NickMeves thanks for providing more detail to the underlying issue.

Yes I agree, it's pretty annoying of them.

As for `SkipClientIDCheck`, I understand that depending on the deployment, not doing the clientID check would mean that clients from the same realm/instance would be validated with one another. For my use case, that validation doesn't add anything, as there is only one client which I need all other clients to be able to validate against within the provider instance.

I'll submit an issue to go-oidc relating to the use and validation of `aud` in conjunction with AWS Cognito (looking through the issue history, that has not been their only issue with Cognito).

As that might take quite a while to come through, is there interest for oauth2-proxy to support Cognito with m2m calls (presumably by flagging `SkipClientIDCheck` and extending the way `--extra-jwt-issuers` accepts arguments)?

**Comment by NickMeves** [comment]
I think this would need to wait until v8.X.

In that major release, we intend to introduce structured configs.  Once that is in place, we aim to allow `Bearer` authentication to be a chain of providers that might enable it (instead of `--extra-jwt-issuers` that is a little bit of a hack addon).

THEN, I think that opens up us to allow each provider to customize if they `SkipClientIDCheck` for themselves.

**Comment by lyndon160** [comment]
Ok, good to know. Thanks for your time on the issue.

I'll have to find an alternative solution in the meantime.

**Comment by lyndon160** [comment]
FYI the reply here https://github.com/coreos/go-oidc/issues/280#issuecomment-722777188 shows an example of how this could be resolved using the go-oidc library.

After the chain providers functionality is supported, I'll happily create a PR to support Cognito if required.

**Comment by kschu91** [comment]
@lyndon160 I just came across the same issue, which is currently impeding me :(. Did you found any workaround to get client credentials access tokens from Cognito verified by oauth2-proxy?

Has there been any changes in oauth2-proxy supporting this use case? @NickMeves 

I am also willing to support with a PR if we can agree on how oauth2-proxy could support it.

**Comment by kschu91** [comment]
FYI: we are currently working on a PR to support this.
