### ISSUE TITLE
Can't compile from repo when following the instructions

### ISSUE THREAD

**Issue by knightian** [oauth2-proxy/oauth2-proxy#896]
`go version go1.15.3 linux/amd64` - Ubuntu 20.04

Installed the latest golang as per the golang site instructions for linux and set $PATH accordingly.

When using the command as per the instructions: `go get github.com/oauth2-proxy/oauth2-proxy`

It fails with the following message:

 ```
go get github.com/oauth2-proxy/oauth2-proxy
cannot find package "github.com/vmihailenco/msgpack/v4" in any of:
        /usr/local/go/src/github.com/vmihailenco/msgpack/v4 (from $GOROOT)
        /home/wkit/go/src/github.com/vmihailenco/msgpack/v4 (from $GOPATH)
cannot find package "go.opentelemetry.io/otel/api/global" in any of:
        /usr/local/go/src/go.opentelemetry.io/otel/api/global (from $GOROOT)
        /home/wkit/go/src/go.opentelemetry.io/otel/api/global (from $GOPATH)
cannot find package "go.opentelemetry.io/otel/api/metric" in any of:
        /usr/local/go/src/go.opentelemetry.io/otel/api/metric (from $GOROOT)
        /home/wkit/go/src/go.opentelemetry.io/otel/api/metric (from $GOPATH)
cannot find package "go.opentelemetry.io/otel/api/trace" in any of:
        /usr/local/go/src/go.opentelemetry.io/otel/api/trace (from $GOROOT)
        /home/wkit/go/src/go.opentelemetry.io/otel/api/trace (from $GOPATH)
```

I do note that $GOPATH and $GOROOT are empty.

Also trying with the instructions here: https://oauth2-proxy.github.io/oauth2-proxy/installation

Specific command: `go get github.com/oauth2-proxy/oauth2-proxy/v7`

Produces the result:

```
go get github.com/oauth2-proxy/oauth2-proxy/v7
cannot find package "github.com/oauth2-proxy/oauth2-proxy/v7" in any of:
        /usr/local/go/src/github.com/oauth2-proxy/oauth2-proxy/v7 (from $GOROOT)
        /home/wkit/go/src/github.com/oauth2-proxy/oauth2-proxy/v7 (from $GOPATH)
```

I have a feeling it has something to do with the blank $GOROOT and $GOPATH but I've been reading how to set them online and had no joy, and even found correspondence suggesting that these are deprecated now?

**Comment by JoelSpeed** [comment]
I believe the first example is broken because of the way go mod works with semantic versioning, and the second example is broken because we haven't actually released v7 yet. This should fix itself when we publish the next release.

In the mean time I suggest git cloning the repository manually, once that's done things should work as expected IIRC

**Comment by knightian** [comment]
> I believe the first example is broken because of the way go mod works with semantic versioning, and the second example is broken because we haven't actually released v7 yet. This should fix itself when we publish the next release.
> 
> In the mean time I suggest git cloning the repository manually, once that's done things should work as expected IIRC

Thanks for reply, if I clone manually I would still need to kick off a build right?

**Comment by JoelSpeed** [comment]
That's correct yes

I would recommend setting up a `GOPATH` environment variable in your profile and creating the expected structure within that from older go versions, go modules aren't quite ready everywhere yet so a lot of projects still depend on the old structure

**Comment by knightian** [comment]
> That's correct yes
> 
> I would recommend setting up a `GOPATH` environment variable in your profile and creating the expected structure within that from older go versions, go modules aren't quite ready everywhere yet so a lot of projects still depend on the old structure
If I have ~/go/bin it would be fine for me to make my GOPATH $HOME/go/bin right? 

Then what do I do? Literally never touched go till now.

**Comment by JoelSpeed** [comment]
I would suggest reading through https://golang.org/doc/gopath_code.html as this explains how it should be set up

Your GOPATH should be something like `~/go` and GOBIN would be `$GOPATH/bin`, packages are then downloaded into `$GOPATH/src/<project>`, eg `$GOPATH/src/github.com/oauth2-proxy/oauth2-proxy`

**Comment by knightian** [comment]
> https://golang.org/doc/gopath_code.html

Thanks for your help, I'll give that a crack.

**Comment by knightian** [comment]
It looks like some dependencies that this project is referencing do not exist in the same place anymore.

For example, it is trying to find code at:

```
cannot find package "go.opentelemetry.io/otel/api/trace" in any of:
        /usr/local/go/src/go.opentelemetry.io/otel/api/trace (from $GOROOT)
        /home/wkit/go/src/go.opentelemetry.io/otel/api/trace
```

When I browse to `/home/wkit/go/src/go.opentelemetry.io/otel/` I can see that trace.go exists, however it is not in a folder named 'api' which this error is saying it should be. If you clear your src folder I bet you have the errors I am.

**Comment by knightian** [comment]
I will try and move the contents of otel into a folder named api and see if it works

**Comment by JoelSpeed** [comment]
There is a problem with your environment rather than the project, I just ran this to ensure that clean builds work
```
$ docker run --rm -it golang:1.15 bash // Gives a clean go environment
$ mkdir -p $GOPATH/src/github.com/oauth2-proxy
$ cd $GOPATH/src/github.com/oauth2-proxy
$ git clone https://github.com/oauth2-proxy/oauth2-proxy
$ cd oauth2-proxy
$ make build
```
How are you building the project, are you using the make target?

**Comment by knightian** [comment]
> There is a problem with your environment rather than the project, I just ran this to ensure that clean builds work
> 
> ```
> $ docker run --rm -it golang:1.15 bash // Gives a clean go environment
> $ mkdir -p $GOPATH/src/github.com/oauth2-proxy
> $ cd $GOPATH/src/github.com/oauth2-proxy
> $ git clone https://github.com/oauth2-proxy/oauth2-proxy
> $ cd oauth2-proxy
> $ make build
> ```
> 
> How are you building the project, are you using the make target?

These instructions work perfectly.... this just built in my environment.

These instructions do not match the install instructions for this project. If you follow the install instructions in the readme, you end up with some semi pulled git repos and references to non existent folders.

**Comment by knightian** [comment]
Thank you for your help @JoelSpeed , your instructions to make it were the key 🥇

**Comment by knightian** [comment]
I will make some edits to the readme file to replicate your instructions and that should solve this issue.
