### ISSUE TITLE
Question: Is there a possibility to use the functionality as library

### ISSUE THREAD

**Issue by fratschi** [oauth2-proxy/oauth2-proxy#910]
Hi,

is there a possiblity to use (some) the functionality of the oauth2 proxy directly within a go rest service?

**Comment by JoelSpeed** [comment]
OAuth2 Proxy hasn't really been designed as a library, but you possibly could consume some parts of the project if you wanted to. Which parts in particular did you want to integrate?

I will say though, if you do use this project as a library, please be aware that we do not expect this, and as such, we don't really provide any guarantees about the internals of the project. We may change or remove interfaces and other parts of the project that are internal without warning

**Comment by fratschi** [comment]
Thank you for your answer!
We are using the proxy actually together with our microservices in a kubernetes cluster with a keycloak.
Thats fine (works great) but i was thinking about to use the oauth-handling directly in out services to reduce
the amount of https calls and the overall amount of of deployed services in kubernetes. 

Since its not designed for usage as library, the effort of extracting/modifiyng/integrating (and maintaining!) seems to high to me and not appropriate.

So i have two options: leave everything at it is or write a small library my myself!

thanks again for your time!
frank
