### ISSUE TITLE
Extend the --email-domain functionality with subdomain 

### ISSUE THREAD

**Issue by morarucostel** [oauth2-proxy/oauth2-proxy#927]
The existing AuthZ part of the oauth-proxy, supported by `--email-domain` allows fixed match or `*` - allowing all emails, functionality is somehow limited and difficult to configure and mantain in a context where the organisation has 100+ domains like: us.example.com, de.example.com, example.com, etc.

The current available option that we have is to provide at start-up the full list of email domains as args, which has to be updated every time a new subdomain is created or removed. 

## Expected Behavior

The oauth2-proxy should allow the `*` as part of the email-domain to extend the current AuthZ capabilities. This way, it can be configured to run with `*example.com` which will allow all the example's subdomains. This should not impact the already existing `*` option. 

## Current Behavior

The suggested behavior will increase the configuration options regarding the email subdomain allowance. 

## Possible Solution

Change the Validator to interpret the `*` also inside the email-domain defition. 

## Context

Extremely difficult to configure and mantain in an organisation with 100+ subdomains. Extend the AuthZ capabilities to ease the configuration.

## Your Environment

- Version used: v6.1.1

**Comment by NickMeves** [comment]
For security reasons, I lean against supporting any wildcards in a partial domain.

E.g. you set `*mydomain.com` as the domain validator with a `google` provider thinking you protect your `sub1.mydomain.com` & `sub2.mydomain.com`.  But an attacker can go ahead and register `evilprefixmydomain.com`.

At least only allowing `*` -- an admin is very aware they get absolutely no domain level authorization protections and knows to setup appropriate mitigating controls.

Truthfully, `email-domain` is more legacy AuthZ mechanism of years ago, primarily meant for providers that were more global and couldn't be setup solely for your org (e.g. Google vs an OIDC IdP).

Moving forward, all the Groups based AuthZ we are wrapping up for V7 is the ideal route to Authorize your users. Which provider do you use? Has a contributor or maintainer picked up adding any sort of group/role support to that provider yet?

**Comment by morarucostel** [comment]
Hi @NickMeves , great catch on the security subdomain problem. 

What if we apply the solutioin that is currently protecting the --email-domain exact match? 
What I mean is, instead of allowing `*mydomain.com` (which allows for the attack you detailed earlier) we can allow anything under that specific domain, so the validator will pick-up the characters and allow subdomains of that domain, basically prefixing a `.` in front of the domain. Thus, even if the user is entering, `*mydomain.com`, the validator will allow `*.mydomain.com`. Whould this solution expose any risks?

**Comment by morarucostel** [comment]
Hi @NickMeves, thanks for the reply. 

> Moving forward, all the Groups based AuthZ we are wrapping up for V7 is the ideal route to Authorize your users. Which provider do you use? Has a contributor or maintainer picked up adding any sort of group/role support to that provider yet?

Are you saying that starting with v7, the `--email-domain` is going to be removed and the AuthZ will solely rely on Groups, or just deprecate its usage? 
What about the `--authenticated-emails-file` AuthZ mechanism? In the next major version will that still be an `OR` based condition with the other AuthZ mechanisms?

**Comment by NickMeves** [comment]
They'll likely remain for a while, but I've always had my eye on them due to the hacky aspects of the code that have popped up because of them -- Sessions copying a subject into the email claim when an email isn't present being the hackiest aspect.

> What if we apply the solutioin that is currently protecting the --email-domain exact match?
> What I mean is, instead of allowing `*mydomain.com` (which allows for the attack you detailed earlier) we can allow anything under that specific domain, so the validator will pick-up the characters and allow subdomains of that domain, basically prefixing a `.` in front of the domain. Thus, even if the user is entering, `*mydomain.com`, the validator will allow `*.mydomain.com`. Whould this solution expose any risks?

We do subdomain logic in `whitelist-domain` where if the first character is a `.`, we allow redirects to any subdomains under the domain.

I think reusing that design fits this use case perfectly and keeps the behavior of the code consistent:

`strings.HasPrefix(configDomain, ".") && strings.HasSuffix(emailDomain, configDomain)`

**Comment by JoelSpeed** [comment]
> We do subdomain logic in whitelist-domain where if the first character is a ., we allow redirects to any subdomains under the domain.

I'd agree that reusing this pattern would be the best approach to allow subdomains, it fits with what we have already and we should be able to extract the logic so we only have to have it implemented once.

As a second point, we had been considering integrating OPA into the proxy, the idea being that you could disable all existing authz checks and use your own OPA policy to validate sessions instead. This would allow total flexibility for users to set up the authz as they desire. This is my preferred long term solution.

**Comment by morarucostel** [comment]
Hey @NickMeves @JoelSpeed , 

I would like to revive this issue and bring it to closure. 
I pushed a new PR as a fix, #1233 (just to keep it cleaner).

**Comment by morarucostel** [comment]
Keeping it open until the PR is merged.

**Comment by morarucostel** [comment]
Thanks @JoelSpeed and @NickMeves for the review and merge of the PR #1233 .
This can be closed now.
