### ISSUE TITLE
Roadmap + Community forum

### ISSUE THREAD

**Issue by malys** [oauth2-proxy/oauth2-proxy#929]
Hi, 
I'm looking documentation defining roadmap and release date. I would know when 0.7.0 will be released.
I have tried to communicate using a chat, forum dedicated to O2P but I didn't find it.
gophers.slack.com is not public (impossible to sign in) Have you any gitter channel ...?

Thx

**Comment by NickMeves** [comment]
There's a few lingering PRs wrapping up Authorization logic in a couple Providers. Then we should be ready to roll out the Authorization themed V7 major release: https://github.com/oauth2-proxy/oauth2-proxy/projects/3

**Comment by malys** [comment]
@NickMeves Thanks gor your answer. What is the best way to communicate with community? (GH issue?, channel from ???)

**Comment by NickMeves** [comment]
GitHub issues are best for feature requests or bug reports.

Security issues should be emailed to a maintainer directly and left off the public internet (so no Github issues for those).

For questions, people use GitHub issues or ask directly in the slack channel. The gophers slack isn't public, but anyone can make an account.

**Comment by malys** [comment]
Thanks
