### ISSUE TITLE
Helm Chart needs critical attention

### ISSUE THREAD

**Issue by apeschel** [oauth2-proxy/oauth2-proxy#930]
It looks like there's a discussion in an existing issue covering this, but the existing issue is broad, the discussion is leisurely, and unfortunately this specific issue has become critical.

https://github.com/oauth2-proxy/oauth2-proxy/issues/608

The "stable" helm repository is now EOL, and should no longer be used. This means the stable/oauth2-proxy chart should also no longer be used.

This is problematic for two reasons:

1) The stable repository, and the stable/oauth2-proxy chart specifically are used by [this very project](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/kubernetes/Chart.yaml#L7-L13)
2) As this project has not provided an official method for Kubernetes deployments, the chart has been the defacto standard for deploying oauth2-proxy with Helm. This means the EOL has rendered oauth2-proxy unusable for most Helm users.

I understand there's a few considerations going into this:

* The stable/oauth2-proxy chart is not maintained by this repository or this organization, and is a legacy from when this project was owned by bitly.
* There are potentially licensing issues around the chart
* There is no repository at the moment to put this chart into.
* Maintainers for the chart need to be found.

If we can get a clear direction on where to go with this, I would be glad to contribute work towards that direction.

**Comment by apeschel** [comment]
I have created this PR to address thew fact that this repository was still using the old stable chart URL: https://github.com/oauth2-proxy/oauth2-proxy/pull/931

Please keep in mind this is only a dirty fix, and the use of the stable repository is actively advised against by the maintainers.

**Comment by NickMeves** [comment]
We have an outstanding question regarding licensing with the original maintainer of the 3rd party chart. Once that's resolved, we have a dedicated repo under the project ready for the chart community to help migrate it over: https://github.com/oauth2-proxy/manifests

**Comment by JoelSpeed** [comment]
I'd actually suggest at this point that we just try and do the migration without attempting to change the license. I don't think it's going to be an issue having one license for the manifests and a different license for the project itself.

CC @desaintmartin @tlawrie

**Comment by JoelSpeed** [comment]
FYI I created a branch that copies the old chart over preserving the history, we need to add the license to this, and I assume a bunch of CI stuff etc, but this has the basic chart at least, perhaps someone who knows helm better can advise what we need to do now https://github.com/oauth2-proxy/manifests/tree/migration

**Comment by erkannt** [comment]
Just raised a PR to add the license and introduce CI stuff for lint-testing and making a release using gh-pages. https://github.com/oauth2-proxy/manifests/pull/1

We rely on this chart at eLife and I'm happy to help with further PRs to get the chart up to date with the current release of oauth2-proxy.

**Comment by tlawrie** [comment]
Hey @erkannt @JoelSpeed in comparing this chart to the one we [built](https://github.com/boomerang-io/charts/tree/main/bmrg-auth-proxy) I think the main differences are as follows. I can meet with Costel, should we raise a separate PR to track the differences and then we can do a PR if there is support for them?

**1. We can set the 'authenticatedEmailsFile' as a secret, depending on what mechanism is wanted.**
```
  allowEmailList:
    enabled: false
    # How the email-list file will be projected, via a configmap or secret
    persistence: configmap
    # Name of the external secret/configmap to use as allow email-list
    # If not provided it will generate the file based on the provided values
    name:
    # List of allowed email addresses
    emailList:
    - test@ibm.com
    - sample@sample.com
```

**2. Redis is an embedded subchart**
We have added Redis for the session persistence as the default.

@costelmoraru lets chat this week to go over, I know our configuration mechanism is very different but I don't think it causes any implementation issues. And the affinity and nodeSelectors etc are available

**Comment by erkannt** [comment]
Feel free to tag me in an issue. I'm happy to make more PRs once  https://github.com/oauth2-proxy/manifests/pull/1is merged.

**Comment by morarucostel** [comment]
> @costelmoraru lets chat this week to go over, I know our configuration mechanism is very different but I don't think it causes any implementation issues. And the affinity and nodeSelectors etc are available

I did get notified because the tagger username is an old one for which I don't have access to that email. :) 
The correct one is @morarucostel

**Comment by JoelSpeed** [comment]
The first PR is now merged, so we have a chart on main now. The release action didn't work but I think I might fix that with https://github.com/oauth2-proxy/manifests/pull/2

**Comment by pierluigilenoci** [comment]
Any news?

**Comment by JoelSpeed** [comment]
The helm chart is now available and being hosted in https://github.com/oauth2-proxy/manifests, please raise any issues on that repo going forward
