### ISSUE TITLE
Each subdomain requires authentication in multi sub-domain setup.

### ISSUE THREAD

**Issue by manipulator01** [oauth2-proxy/oauth2-proxy#932]
Hello wonderful people,

I am using oauth2_proxy with nginx to provide authentication to 10 subdomains. (*.mydomain.com) I am using Google auth method.

The problem that I am facing is: **I need to login to every single subdomain when I visit them. Logging in once is not enough.**

**I think I am missing some redirection and or HTTP header tricks...** Please help me to overcome this challenge.

```

server {
listen 80;
server_name auth.mydomain.com;
charset utf-8;

location /oauth2/ {
    proxy_pass http://localhost:4180;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
}


location /oauth2/auth {
    proxy_pass http://localhost:4180;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header Content-Length   "";
    proxy_pass_request_body off;
}

location / {
    try_files $uri $uri/ =404;

    auth_request /oauth2/auth;
    error_page 401 = /oauth2/sign_in;
    auth_request_set $user   $upstream_http_x_auth_request_user;
    auth_request_set $email  $upstream_http_x_auth_request_email;
    proxy_set_header X-User  $user;
    proxy_set_header X-Email $email;
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $auth_cookie;

    }
```

and here one of my subdomain configuration:

```
server {
listen 80;
server_name myapp.mydomain.com;
charset utf-8;


location / {
    proxy_pass http://localhost:8080;
    proxy_set_header Host $host;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    auth_request /oauth2/auth;
    error_page 401 = /oauth2/sign_in;

    auth_request_set $user   $upstream_http_x_auth_request_user;
    auth_request_set $email  $upstream_http_x_auth_request_email;
    proxy_set_header X-User  $user;
    proxy_set_header X-Email $email;
    auth_request_set $token  $upstream_http_x_auth_request_access_token;
    proxy_set_header X-Access-Token $token;


}


location /oauth2/ {
    proxy_pass http://localhost:4180;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Auth-Request-Redirect $request_uri;
}
```

I fried my brain... and I am here to get some help. I feel like I need to do something in my subdomain config to route the request to auth.mydomain.com but I am not sure.

Note: I am using docker image v6.1.1 and I have configured following variables:

```
OAUTH2_PROXY_CLIENT_ID=***REMOVED***
OAUTH2_PROXY_CLIENT_SECRET=***REMOVED***
OAUTH2_PROXY_COOKIE_NAME=***REMOVED***
OAUTH2_PROXY_COOKIE_SECRET=***REMOVED***

OAUTH2_PROXY_COOKIE_EXPIRE=12h
OAUTH2_PROXY_EMAIL_DOMAINS=mydomain.com
OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
OAUTH2_PROXY_REVERSE_PROXY=true
OAUTH2_PROXY_SET_XAUTHREQUEST=true
```

**Comment by NickMeves** [comment]
Take a look at the configuration options [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/):

You'll want `--cookie-domain` & `--whitelist-domain`. Those can each be set with a leading `.` to allow everything under the subdomain.

`--cookie-domain` will get you session cookie set to your top domain. `--whitelist-domain` will allow you to redirect back to multiple domains besides the one its hosted on (might not be applicable in your setup).

**Comment by Mearman** [comment]
My set up is following this guide to use NPM in unRAID.
https://www.reddit.com/r/unRAID/comments/kl8q9d/success_google_auth_using_oauth2proxy_w_with/

can the cookie and whitelist domains be set in the config file?

**Comment by JoelSpeed** [comment]
You can use the `cookie_domains=[...]` and `whitelist_domains=[...]` config file options for them
