### ISSUE TITLE
Howto rewrite the incoming URL before it is send to the upstream?

### ISSUE THREAD

**Issue by esteiner** [oauth2-proxy/oauth2-proxy#939]
Is it possible to rewrite the incoming URL before it is send to the upstream?

## Expected Behavior

We would like to send requests like "http://localhost:8000/proxy/app1/service" to the oauth2-proxy and have the oauth2-proxy then send the request as "http://localhost:9000/app1/service" to the upstream.

## Current Behavior

Neither using:

proxy_prefix = "/proxy/" 

in the cfg file, nor setting an env var

OAUTH2_PROXY_PROXY_PREFIX=/proxy/

seems to work.

There is also no log entry, that the configured prefix is (or is not) used. It would help if there was a log entry like with other configs.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

As a docker container (quay.io/oauth2-proxy/oauth2-proxy:v6.1.1).

- Version used: v6.1.1

**Comment by JoelSpeed** [comment]
I don't know if this is currently possible. I suggest taking a look at #909 and perhaps leaving some feedback there about how you might expect this to work. I'd urge you to have a play with the new alpha config options as well to see if you can get this to work.

The proxy prefix option only affects the paths under which the OAuth2 Proxy pages are registered, it does not affect any of the upstream proxying

**Comment by esteiner** [comment]
Thanks for the answer. The important information for me is that "the proxy prefix option only affects the paths under which the OAuth2 Proxy pages are registered, it does not affect any of the upstream proxying". Because I wanted it for rewrite the URL, which is passed to the upstream.
