### ISSUE TITLE
Error loading cookied session: cookie "_oauth2_proxy" not present, removing session

### ISSUE THREAD

**Issue by philthynz** [oauth2-proxy/oauth2-proxy#941]
## Expected Behavior

set-cookie header is present on login page, and no errors are logged

## Current Behavior

Error console shows:

```
Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
```

In a browser I can see the "/oauth2/callback/ has the cookie, but not the "/" or "login?redirect=/"

## Possible Solution

Unknown

## Steps to Reproduce (for bugs)

Nginx config:
```
server {
    listen 443 default ssl;
    server_name servername;
    ssl_certificate /etc/letsencrypt/live/servername/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/servername/privkey.pem;
    add_header Strict-Transport-Security max-age=2592000;
    proxy_buffers 4 256k;
    proxy_buffer_size 128k;
    server_tokens off;

    location / {
        proxy_pass http://127.0.0.1:4180;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Auth-Request-Redirect $request_uri;
        proxy_connect_timeout 1;
        proxy_send_timeout 30;
        proxy_read_timeout 30;

   }
}
```
Running oauth2-proxy with:
```
/opt/oauth2-proxy/oauth2-proxy \
--provider=azure \
--redirect-url=https://servername/oauth2/callback \
--skip-provider-button \
--email-domain=*  \
--client-id=id \
--client-secret=secret \
--upstream=http://localhost:4430/ \
--cookie-secret=secret \
--cookie-httponly=false \
--reverse-proxy=true
```

## Context

I'm trying the add the proxy in front of puppet enterprise.

## Your Environment

Centos7 server with puppet enterprise installed

- Version used:

oauth2-proxy-v6.1.1

**Comment by NickMeves** [comment]
Try without the `--redirect-url` flag. That doesn't look like what you want (It is intended for redirecting your users back to your app after authentication).

Unless you need it, its better to not set it and let the proxy figure it out from HTTP Host headers: https://github.com/oauth2-proxy/oauth2-proxy/blob/87c67b09a7bcb07eabcdf13c713613bf2e1bf79e/oauthproxy.go#L371

**Comment by JoelSpeed** [comment]
I think the issue may be that you've not set your cookie domain, since you've seen its present on your OAuth2 endpoint, you can check there what the domain is set to.

If you are protecting multiple domains under a common subdomain you can use a `.` at the begining of the cookie domain to allow all subdomains

**Comment by philthynz** [comment]
So I tried with:

```
/opt/oauth2-proxy/oauth2-proxy \
--provider=azure \
--cookie-domain=.subdomain.TLD-domain.Root-domain \
--skip-provider-button \
--email-domain=* \
--client-id=<id> \
--client-secret=<secret> \
--upstream=http://localhost:4430/ \
--cookie-secret=<secret> \
--cookie-expire=24h0m0s \
--tls-cert-file=/etc/letsencrypt/live/FQDN/fullchain.pem \
--tls-key-file=/etc/letsencrypt/live/FQDN/privkey.pem
```

And nginx gave me a 502. So it needs the redirect-url.

```
/opt/oauth2-proxy/oauth2-proxy \
--redirect-url=https://FQDN/oauth2/callback \
--provider=azure \
--cookie-domain=.subdomain.TLD-domain.Root-domain \
--skip-provider-button \
--email-domain=* \
--client-id=<id> \
--client-secret=<secret> \
--upstream=http://localhost:4430/ \
--cookie-secret=<secret> \
--cookie-expire=24h0m0s \
--tls-cert-file=/etc/letsencrypt/live/FQDN/fullchain.pem \
--tls-key-file=/etc/letsencrypt/live/FQDN/privkey.pem
```

The website should be at `subdomain.subdomain.TLD-domain.Root-domain`. So I image using `.subdomain.TLD-domain.Root-domain` for the `--cookie-domain` should work, however I still have the error:

```
Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
```

**Comment by NickMeves** [comment]
What does the `Set-Cookie` header look like in the response from OAuth2-Proxy as your are finishing up the initial OAuth authentication flow?

That should give some hints where to tweak your configuration.

Since you had issues when you removed `--redirect-url`, where when it is omitted it defaults to the `/oauth2/callback` path under either the `Host` or `X-Forwarded-Host` it extracts from the request automatically (which you are essentially hardcoding in that `redirect-url`, I wonder if nginx isn't getting the headers setup properly for OAuth2-Proxy, so OAuth2-Proxy sees `localhost:4180` and therefore is setting cookies oddly with the `host`-to-`cookie-domains` security logic.

Your auth & request logs on the OAuth2-Proxy side might have more details about what it considers the `Host` based on headers.

Do you have a sample of those?

**Comment by philthynz** [comment]
When I hit the URL and it redirects to the Azure login, for the `/` location the status is `302`, and the set-cookie header is:
```
Set-Cookie | _oauth2_proxy_csrf=7ed70e24053537b4b8b4562f7c48ec27;  Path=/; Domain=tld-domain.root-domain; Expires=Thu, 10 Dec 2020 19:15:53 GMT;  HttpOnly; Secure; SameSite
```

And the oauth2-proxy logs:
```
[2020/12/09 19:15:41] [logger.go:490] HTTPS: listening on [::]:443
[2020/12/09 19:15:53] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.100.62.4:20966 - - [2020/12/09 19:15:53] tst.puppet.education.govt.nz GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0" 302 322 0.000
[2020/12/09 19:15:54] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.100.62.4:20976 - - [2020/12/09 19:15:54] tst.puppet.education.govt.nz GET - "/" HTTP/1.1 "" 302 322 0.000
[2020/12/09 19:16:10] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.100.62.7:32048 - - [2020/12/09 19:16:10] tst.puppet.education.govt.nz GET - "/" HTTP/1.1 "" 302 322 0.001
[2020/12/09 19:16:24] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.100.62.4:21046 - - [2020/12/09 19:16:24] tst.puppet.education.govt.nz GET - "/" HTTP/1.1 "" 302 322 0.000
[2020/12/09 19:16:40] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.100.62.7:32136 - - [2020/12/09 19:16:40] tst.puppet.education.govt.nz GET - "/" HTTP/1.1 "" 302 322 0.000
[2020/12/09 19:16:54] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.100.62.4:21108 - - [2020/12/09 19:16:54] tst.puppet.education.govt.nz GET - "/" HTTP/1.1 "" 302 322 0.000
[2020/12/09 19:17:10] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
```

**Comment by NickMeves** [comment]
So the CSRF cookie is set when you initiate the OAuth2 flow with your IdP. You want to look at the cookies set by `/oauth2/callback` or whatever it is when your IdP sends you back to the proxy.

At that point OAuth2-Proxy finishes the OAuth flow and creates a session for you and redirects you to your original page and has the `Set-Cookie` with your session.

**Comment by philthynz** [comment]
Thanks for the help. So the headers look like this:

![image](https://user-images.githubusercontent.com/17504095/102299894-b2216f00-3fb8-11eb-8a0e-44915c4ddb93.png)

![image](https://user-images.githubusercontent.com/17504095/102300340-a5e9e180-3fb9-11eb-814b-6c497636671a.png)

Is there an issue ignoring the error? The page still redirects and I can login to the app fine.

**Comment by NickMeves** [comment]
Interesting... those must be some massive OIDC Tokens you are getting back from azure if you are still getting cookie splitting. Historically that was frequently an issue for Azure users going over the 8k header limit with session cookies that were too large. This was mostly fixed with us refactoring for MessagePack encoding + LZ4 compression on our sessions.

I wonder if you are in 1 of 2 boats:
(1) Your _oauth2_proxy_0 and _oauth2_proxy_1 cookies are too big still (those both look large...). Would be handy for you to look at your request headers and confirm they have those both in the `Cookie` header for requests where you get issues.
(2) We have a regression in cookie splitting logic in the code and most users haven't seen it lately since cookie splitting, while once common, has become rare with compression to get over the 4kb limit.

If you need a quick fix, you can try `--session-cookie-minimal` or switch to a Redis session store and see if that fixes your problem.

**Comment by NickMeves** [comment]
Adding bug label in case this is related to cookie splitting logic.

**Comment by JoelSpeed** [comment]
You may also want to try using redis session storage as an option for reducing the cookie size to eliminate any cookie splitting issues that may arise

**Comment by htdat148** [comment]
I followed this tutorial https://alex.thom.ae/2019/10/20/protect-website-oauth2_proxy-traefik/ and got the same issue. I am using the latest version, I tried your suggestion but It did not work for me. Here is the log from the container

> 
[2021/05/05 05:45:15] [oauthproxy.go:142] OAuthProxy configured for Google Client ID: 309936706134-6mre34kidh10hncvohiu8mvre77171g5.apps.googleusercontent.com
[2021/05/05 05:45:15] [oauthproxy.go:148] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:after 1h0m0s
[2021/05/05 05:45:15] [http.go:57] HTTP: listening on 0.0.0.0:4180
[2021/05/05 05:45:54] [stored_session.go:75] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
171.253.133.36 - - [2021/05/05 05:45:54] grafana.ubuntu.mydomain.org GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 401 21 0.000
[2021/05/05 05:45:54] [stored_session.go:75] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
171.253.133.36 - - [2021/05/05 05:45:54] grafana.ubuntu.mydomain.org GET - "/http://oauth:4180/oauth2/sign_in" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 403 2537 0.000

**Comment by 5w0ng** [comment]
Same as above;  
```
[2021/05/06 15:19:54] [stored_session.go:76] Error loading cookied session: cookie "oauth2_proxy" not present, removing session
10.24.15.104:54646 - - [2021/05/06 15:19:54] oauth2-proxy.oauth2-proxy.svc.cluster.local GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 401 13 0.000
[2021/05/06 15:19:54] [stored_session.go:76] Error loading cookied session: cookie "oauth2_proxy" not present, removing session
10.24.15.104:40616 - - [2021/05/06 15:19:54] oauth2.centaur-platform-dev.com GET - "/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 302 324 0.00
```

Any help would be greatly appreciated!

**Comment by htdat148** [comment]
@5w0ng and @rtrive , Have you looked the URL in your browser. Here is the URL in my case: `https://prometheus.ubuntu.precisionag.org/oauth2/start?rd=%2F` The ?rd=%2F, I think it should point to the oauth service

**Comment by JoelSpeed** [comment]
The `rd` parameter should point to where you want OAuth2 Proxy to redirect you to _after_ the authentication has completed. Eg this could be the root of your application. If you set it to the OAuth2 Proxy service, then you will, as you've seen, post login, be sent to the start of the login process again.

If you are getting infinity loops without this, then I suggest you check the responses from the OAuth2 Proxy and inspect the cookies that it sets. I expect they are not on the correct domain and therefore aren't accessible when traefik does its own checks with OAuth2 Proxy

**Comment by htdat148** [comment]
I changed a minor configuration then I was able to be routed to **Choose an Account** but after that, it returned a 500 Server Internal Error. Here is my log in oauth service

```
paddy_oauth.1.6njfzs6iilb5@ip-172-31-30-68    | 171.253.128.139 - 1110b772-c9e9-4aa4-b4a0-ecccaa8bfe34 - - [2021/05/17 03:22:23] prometheus.ubuntu.domain.org GET - "/oauth2/sign_in?rd=%2F" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 200 7922 0.017
paddy_oauth.1.6njfzs6iilb5@ip-172-31-30-68    | 171.253.128.139 - 1c7e2ae7-f93f-4e47-a35f-82cb176572f8 - - [2021/05/17 03:22:24] prometheus.ubuntu.domain.org GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 302 389 0.006
paddy_oauth.1.6njfzs6iilb5@ip-172-31-30-68    | [2021/05/17 03:22:32] [oauthproxy.go:748] Error redeeming code during OAuth2 callback: unexpected status "401": {
paddy_oauth.1.6njfzs6iilb5@ip-172-31-30-68    |   "error": "invalid_client",
paddy_oauth.1.6njfzs6iilb5@ip-172-31-30-68    |   "error_description": "Unauthorized"
paddy_oauth.1.6njfzs6iilb5@ip-172-31-30-68    | }
paddy_oauth.1.6njfzs6iilb5@ip-172-31-30-68    | [2021/05/17 03:22:32] [oauthproxy.go:475] Rejecting invalid redirect "/oauth2/callback?state=ysaUk0tcouk6qu2wcHEpL8UWHGXqMH4bBpBUdQA3aT0:/&code=4/0AY0e-g5NxkkbwIv-9hYB5S-jnDhVCMuB4RJjMXlFWUFoFC4eWmlwo6rJKgLzRHb5KlIFjQ&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=1&hd=domain.org&prompt=consent": not an absolute or relative URL
paddy_oauth.1.6njfzs6iilb5@ip-172-31-30-68    | [2021/05/17 03:22:32] [oauthproxy.go:989] Invalid redirect generated from X-Forwarded-Uri header: /oauth2/callback?state=ysaUk0tcouk6qu2wcHEpL8UWHGXqMH4bBpBUdQA3aT0:/&code=4/0AY0e-g5NxkkbwIv-9hYB5S-jnDhVCMuB4RJjMXlFWUFoFC4eWmlwo6rJKgLzRHb5KlIFjQ&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=1&hd=domain.org&prompt=consent

```

**Comment by 5w0ng** [comment]
Hi @JoelSpeed,

I could really use some expert guidance if you have capacity to assist?

Here is my config;
```
  configFile: |-
    provider = "oidc"
    oidc_issuer_url = "https://myoidc.okta.com/oauth2/default"
    client_id = "redacted"
    client_secret = "redacted"
    redirect_url = "https://oauth2.my-platform-dev.com/oauth2/callback"
    login_url = "https://myoidc.okta.com/oauth2/default/v1/authorize"
    redeem_url = "https://myoidc.okta.com/oauth2/default/v1/token"
    validate_url = "https://myoidc.okta.com/oauth2/default/v1/userinfo"
    profile_url = "https://myoidc.okta.com/oauth2/default/v1/userinfo"
    email_domains = [ "*" ]
    upstreams = [ "http://127.0.0.0:8080/" ]
    http_address = "0.0.0.0:4180"
    pass_access_token = true
    cookie_name = "oauth2_proxy"
    cookie_secret = "redacted"
    cookie_domains = ".my-platform-dev.com"
    whitelist_domains = ".my-platform-dev.com"
    skip_provider_button = true
```

My ingress for kubernetes-dashboard is as follows;
```
nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local:80/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.my-platform-dev.com/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "authorization"

    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie_oauth2_proxy;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "oauth2_proxy=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
```

The error is still the same as above;
```
[2021/05/06 15:19:54] [stored_session.go:76] Error loading cookied session: cookie "oauth2_proxy" not present, removing session
10.24.15.104:54646 - - [2021/05/06 15:19:54] oauth2-proxy.oauth2-proxy.svc.cluster.local GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 401 13 0.000
[2021/05/06 15:19:54] [stored_session.go:76] Error loading cookied session: cookie "oauth2_proxy" not present, removing session
10.24.15.104:40616 - - [2021/05/06 15:19:54] oauth2.mydomain.com GET - "/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" 302 324 0.00
```


I've tried many different combinations but clutching straws now due to my lack of understanding and the challenge of sieving through the documentation for Okta/Helm/K8s.  Any help would be greatly appreciated!

**Comment by JoelSpeed** [comment]
If you login and directly access `https://oauth2.my-platform-dev.com/oauth2/auth`, what kind of result do you get? I suspect you may need to set the auth-url to the public URL rather than using the internal URL as shown in your example

**Comment by 5w0ng** [comment]
> If you login and directly access `https://oauth2.my-platform-dev.com/oauth2/auth`, what kind of result do you get? I suspect you may need to set the auth-url to the public URL rather than using the internal URL as shown in your example

Hi @JoelSpeed,

I reverted to add the oauth2-proxy dns back into the kubernetes-dashboard ingress as follows;
```
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2.my-platform-dev.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.my-platform-dev.com/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "authorization"
```

If I access this path directly, I get the message '**Unauthorized**'

If I look at the nginx-ingress controller logs I see this;
```
2021/05/19 08:20:37 [warn] 219#219: *6231109 upstream server temporarily disabled while connecting to upstream, client: 10.252.248.202, server: k8sdashboard.my-platform-dev.com, request: "GET / HTTP/2.0", subrequest: "/_external-auth-Lw", upstream: "https://10.24.24.37:443/oauth2/auth", host: "k8sdashboard.my-platform-dev.com"
2021/05/19 08:20:37 [error] 219#219: *6231109 upstream timed out (110: Operation timed out) while connecting to upstream, client: 10.252.248.202, server: k8sdashboard.my-platform-dev.com, request: "GET / HTTP/2.0", subrequest: "/_external-auth-Lw", upstream: "https://10.24.24.37:443/oauth2/auth", host: "k8sdashboard.my-platform-dev.com"
```

The oauth2-proxy pod logs still show this;
```
10.24.27.100:37876 - - [2021/05/19 08:20:17] oauth2.my-platform-dev.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" 401 13 0.000
[2021/05/19 08:20:17] [stored_session.go:76] Error loading cookied session: cookie "oauth2_proxy" not present, removing session
```

What are your thoughts, is it looking like the upstream?

**Comment by yashmehrazs** [comment]
I am also facing the same error can you please provide resolution

**Comment by htdat148** [comment]
@yaegashi , for my case I used OAuth with Treafik in docker environment. You have to create a dummy address for OAuth and be careful with the environment variables, some are plural. You can check more detailed in the docs

**Comment by droslean** [comment]
Also, this problem appears only in Chrome. My app works fine when accessed with firefox, and no errors are being generated.
