### ISSUE TITLE
--extra-jwt-issuers does not support google service account jwt issuers

### ISSUE THREAD

**Issue by CoryHagerman** [oauth2-proxy/oauth2-proxy#942]
Google has jwks available for Service Accounts at the following url: https://www.googleapis.com/service_accounts/v1/jwk/<service_account_email>

I should be able to provide this url as an extra jwt issuer and use a jwt signed with the service account private key to authenticate. 

I may be using this parameter wrong but cannot find anything describing how to directly specify the jwks

## Expected Behavior

I should be able to specify an issuer url that is the direct url to the jwks

## Current Behavior

The url tried to validate the JWT issuer has the well known endpoint suffix's appended before trying.

## Possible Solution

In options.go in the method newVerifierFromJwtIssuer add an additional uri to try if the first 2 attempts fail. Just use the provided issuer if the other 2 fail.  The below code works but I am not sure if I am just configuring it wrong for something that actually works. 

```
func newVerifierFromJwtIssuer(jwtIssuer jwtIssuer) (*oidc.IDTokenVerifier, error) {
	config := &oidc.Config{
		ClientID: jwtIssuer.audience,
	}
	// Try as an OpenID Connect Provider first
	var verifier *oidc.IDTokenVerifier
	provider, err := oidc.NewProvider(context.Background(), jwtIssuer.issuerURI)
	if err != nil {
		// Try as JWKS URI
		jwksURI := strings.TrimSuffix(jwtIssuer.issuerURI, "/") + "/.well-known/jwks.json"
		response := requests.New(jwksURI).Do()
		if response.Error() != nil || response.StatusCode() != 200 {

			// for when the provided issuerURI is a direct link to the jwks.json
			jwksURI = strings.TrimSuffix(jwtIssuer.issuerURI, "/")
			response := requests.New(jwksURI).Do()
			if response.Error() != nil || response.StatusCode() != 200 {
				return nil, err
			}
		}

		verifier = oidc.NewVerifier(jwtIssuer.issuerURI, oidc.NewRemoteKeySet(context.Background(), jwksURI), config)
	} else {
		verifier = provider.Verifier(config)
	}
	return verifier, nil
}
```

## Steps to Reproduce (for bugs)

Set the extra-jwt-issuers to: https://www.googleapis.com/service_accounts/v1/jwk/<service_account_email>=<aud_in_token>"

Try to authenticate with the jwt as the Bearer Token

## Context

I am trying to use a jwt signed by my service account credentials

- Version used:
6.1.1

**Comment by NickMeves** [comment]
It looks like that google JWKS url doesn't align with our fallback format for `extra-jwt-issuers`.

The current logic looks for OIDC `/.well-known/openid-configuration` under the issuer and falls back if that isn't found to the most common `/.well-known/jwks.json` path for the actual JWKS we want.

It looks like google doesn't align to that OIDC convention for its JWKS that we target with this functionality.

We are looking to overhaul how bearer tokens work with specific providers in 2 major releases. We should keep an eye on how Google does it here and see how we can support.

**Comment by kregerre** [comment]
Any chance you can put Cory's update into the master branch?

**Comment by NickMeves** [comment]
So `--extra-jwt-issuers` making adhoc OIDC IDToken Verifiers for non-providers will likely be going away in v8 with structured configs in favor of chainable "Bearer Auth" providers (where migrating from `--extra-jwt-issuers` you'd configure each entry as an OIDC provider).

So I'm not too keen on spending time developing & merging anything into master that will in the next few months be removed.

BUT - to prep for that (and make this work now if Google is your main provider). Google needs this method implemented if it has special logic (or it needs to setup an `oidc.IDTokenVerifier` in its init function to use the default): https://github.com/oauth2-proxy/oauth2-proxy/blob/d67d6e3152e2a1c9614906ee9bd9890f8da9a007/providers/provider_default.go#L128

I'm not a Google provider user myself, so I'll need to lean on the community to make a PR for this feature if there's demand.

**Comment by heyrun** [comment]
Hi guys, 
I am using Google as my provider as my oauth2-proxy and I am currently having issues generating a token with Google service account. 
Can you please confirm if this has been resolved.
