### ISSUE TITLE
Populate Session with IDToken Claims in GitLab Provider

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#945]
Use the upcoming global OIDC helper methods to populate the session with ID Token claims in Gitlab

## Expected Behavior

Use the claims to populate our sessions fields and make GitLab ready for user-defined claim-> session mappings.

From: https://github.com/oauth2-proxy/oauth2-proxy/pull/630#issuecomment-738715337

sub | string | The ID of the user
-- | -- | --
sub_legacy | string | An opaque token that uniquely identifies the userDeprecation notice: this token isn’t stable because it’s tied to the Rails secret key base, and is provided only for migration to the new stable sub value available from GitLab 11.1
auth_time | integer | The timestamp for the user’s last authentication
name | string | The user’s full name
nickname | string | The user’s GitLab username
email | string | The user’s email addressThis is the user’s primary email address if the application has access to the email claim and the user’s public email address otherwise
email_verified | boolean | Whether the user’s email address was verified
website | string | URL for the user’s website
profile | string | URL for the user’s GitLab profile
picture | string | URL for the user’s GitLab avatar
groups | array | Names of the groups the user is a member of

Source : https://docs.gitlab.com/ee/integration/openid_connect_provider.html

## Current Behavior

Gitlab provider uses the Gitlab userinfo/profileURL to populate the Email & Groups details.

## Context

Make OIDC capable providers use common methods to scale long-term OIDC related enhancements to multiple providers.

CC: @papey

**Comment by NickMeves** [comment]
@papey I'll attempt a spike of this concept once #936 merges. But I could use a hand with a GitLab user to make sure it works beyond unit tests I would add.

**Comment by papey** [comment]
Sure, ping me if needed :+1:

**Comment by NickMeves** [comment]
This is another provider that might benefit from this proposed refactor as well: https://github.com/oauth2-proxy/oauth2-proxy/issues/956

Can the GitLab provider completely inherit the OIDC provider implementations with a couple of modifications for a `--gitlab-projects` support?

This will allow it to be forward-compatible with all the new OIDC features based on IDToken claims that are coming soon.
