### ISSUE TITLE
Unable to Decrypt access token from oauth2-proxy cookie

### ISSUE THREAD

**Issue by Naveenrajelothunkal** [oauth2-proxy/oauth2-proxy#950]
I have set up a cluster with Nginx-ingress, oauth2-proxy & keycloak . Created a nodejs application and linked to nginx ingress. Oauth2-proxy configurations are given below:

        - --http-address=0.0.0.0:4180
        - --client-id=xxxx
        - --client-secret=xxxxx
        - --login-url=xxxxx/auth
        - --provider=keycloak
        - --provider-display-name=Login
        - --redeem-url=xxxx/token
        - --set-xauthrequest=true
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        - --email-domain="*"
        - --cookie-secure=true
        - --validate-url=xxxx/userinfo
        - --keycloak-group=xxxx
        - --redirect-url=xxxx/oauth2/callback
        - --oidc-issuer-url=xxxx
        - --insecure-oidc-allow-unverified-email=true
        - --email-domain=example.com
        - --pass-user-headers=true
        - --ssl-insecure-skip-verify=true
        - --cookie-name=testcookie
        - --pass-access-token=true
        - --pass-authorization-header=true 

Once i have configured keycloak , i am able to redirect to keycloak login page and after login, it comes back to my website.
I can see cookie "testcookie" has created and it is encrypted . 

when i use oauth2-proxy version 5.1.1 , i am able to decode cookie  (it was used SHA1 encryption) . and i have encrypted access token using AES cypher algorithm with cookie-secret (in golang api, not in NODEJS ).

I have updated oauth2-proxy version to 6.1.1 , i am not able to decode cookie value. (it is encrypted in sha256, i guess)

  

## Expected Behavior

It should decrypt cookie value and get me access token 

## Current Behavior

I could not find out which algorithm used to encrypt cookie value ?
It should get me access token from encrypted cookie.

## Possible Solution

If i would know algorithm used to encrypt cookie value, easy to decrypt access token . 
is there any alternative way to pass access token from oauth proxy to each pod which connect to nginx -ingress in kubernete cluster?

## Steps to Reproduce (for bugs)

1. install nginx-ingress ,keycloak  & auth2-proxy
2. deploy applications
3. Do keycloak configuration  & above auth2-proxy configuration as well
4. create cookie secret with random value
5. update oauth2-proxy docker image version to 6.1.1
6. Copy cookie value 
7. try to decode manually

## Context

If you could help me with proper example would be appreciated. Thank you.

- Version used: 6.1.1

**Comment by NickMeves** [comment]
Any details you need from the session, you should use the various `X-Forwarded-*` headers that you can configure to extract session fields and pass to the backend. Or from the backend, use the session cookie to query the Userinfo endpoint.

The session cookie isn't intended to be decrypted by backend applications (a pattern that wouldn't work at all using redis or dynamodb session stores).

BUT if you really want to and want to have the `cookie-secret` footprint wider than just the proxy and in your backend app (which I again really discourage this pattern for security & maintainability reasons):

The cookies are SHA256 HMAC signed now. The underlying contents are the Base64 AES-CFB encryption of an LZ4 compressed, MessagePack encoded session object. It was previously uncompressed with individual fields encrypted in the JSON values and Base64'd there (and then base64'd again at the end).  The new messagepack/lz4/encryption design cut session cookie sizes in half: https://github.com/oauth2-proxy/oauth2-proxy/blob/a5466bb96dabd46a222b9a2c63303ffac753832e/pkg/apis/sessions/session_state.go#L103

**Comment by NickMeves** [comment]
`--pass-access-token=true` which you have set is what you want to get the Access Token specifically.

**Comment by NickMeves** [comment]
You might also want to follow this issue. I think there's some significant feature gaps in the `keycloak` provider at the moment and you'd get much more functionality hooking your Keycloak instance into the `oidc` provider: https://github.com/oauth2-proxy/oauth2-proxy/issues/956

**Comment by Naveenrajelothunkal** [comment]
Thank you for update !!

I would like to know how can i get access token in X-Forwarded-* headers?. As above mentioned, i have enabled --pass-access-token=true . But when i log request data, i could not see any header attribute which serve access-token.

I can see only cookie data which is encrypted. 

if i hook keycloak instance to oidc provider , will i get access token in X-Forwarded-* headers ???

Or 

Just need a clarification , will Keycloak provider come with new update where we will get access token in the X-Forwarded-* headers ???

Eagerly waiting for reply !!!

**Comment by NickMeves** [comment]
Take a look at `--pass-user-headers` in this table: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/

It should get you what you need in request headers for your backend app to consume.

Tokens will not be in logs for security reasons. The only piece of session data in your access logs will be either the user or email (whichever you toggle to be in the logs as the user field).

**Comment by Naveenrajelothunkal** [comment]
Thanks again Nick!! .. 

I have enabled --pass-user-headers= true , as you can see in the above configuration. Still i could not get any access token related data except encrypted cookie . 

we are stuck here!! What are other possible way to get keycloak user & roles data to outh2-proxy and how can we pass to tool which is in same ingress ?  (if we get access token , it is easy to parse and get user details)

Any thoughts on this?? your prompt response would be much appreciated !!!

**Comment by Naveenrajelothunkal** [comment]
Hi Guys .... Thank you all for helping me out ...

I found the issue and got fixed .. When we update oath2-proxy to latest version (6.1.1), we have a way to get "x-auth-request-accesss-token".
