### ISSUE TITLE
X-Forwarded-User is Empty using Keycloak

### ISSUE THREAD

**Issue by yoshixmk** [oauth2-proxy/oauth2-proxy#955]
By default, I was able to confirm that passing X-Forwarded-Email was proxied after authenticating. But I noticed that X-Forwarded-User is empty.  
I think X-Forwarded-User eq UserModel's id on Keycloak, and proxy as "X-Auth-Subject" in keycloak gatekeeper.  
cf: https://www.keycloak.org/docs/latest/securing_apps/#upstream-headers

I also added a claim called user as a mapper and tried it, but it doesn't work
![image](https://user-images.githubusercontent.com/6196702/102006619-adb14800-3d65-11eb-854b-8c2a6275d205.png)

https://github.com/oauth2-proxy/oauth2-proxy/blob/87c67b09a7bcb07eabcdf13c713613bf2e1bf79e/contrib/local-environment/oauth2-proxy-alpha-config.yaml#L9-L11

Is there a solution?

**Comment by yoshixmk** [comment]
refs: #631 #843

**Comment by NickMeves** [comment]
I just wrote this up based on helping someone out with `keycloak` in the `#oauth2-proxy` slack channel: https://github.com/oauth2-proxy/oauth2-proxy/issues/956

I think at the moment, your best bet is to hook Keycloak into the OIDC provider to get the most features.
