### ISSUE TITLE
Keycloak Provider is just Barebones OAuth - Doesn't Expose OIDC Potential

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#956]
We have a `keycloak` provider that most Keycloak users likely gravitate to by default.

It is a very barebones implementation mostly riding our default `OAuth` provider methods, only overriding the Userinfo call to populate the email & groups.

Keycloak is OIDC compatible, plugging it into the `oidc` provider instead of the Keycloak provider results in all functionality the `keycloak` provides with the following additions:

- An IDToken in the session
- User, Email & Groups extraction from the IDToken claims
- Session Refresh support (missing from current `keycloak` provider)
- Bearer auth support using IDToken and OIDC JWKS file.

And future improvements such as adhoc IDToken claim -> Session + `X-Forwarded-*` mapping.

## Expected Behavior

We take full advantage of OIDC in a Keycloak provider if we have a split provider from the generic `oidc` provider.

This PR in particular we should strongly figure out if `keycloak` needs a refactor or not before hand: #767 . It will pull Keycloak role data from an Access Token, which a default `oidc` provider wouldn't have. That PR needs Keycloak's OIDC elements anyway to verify the Access Token before pulling roles from the JWT claims.

## Current Behavior

Keycloak is generic OAuth only. It uses the scope `api` (instead of `openid email profile` for oidc). And only gets Email & Groups by querying the Userinfo endpoint with the Access Token.

## Possible Solution

We are starting to have a few OIDC based providers (Gitlab, Login.gov, Keycloak, Azure (?), and OIDC itself). Our current `provider_defaults.go` implementations of the provider interface are just generic OAuth implemenations.

Should we split and have both OAuth OR OIDC base implementations that providers can extend?

Currently the OIDC ones all seem to reimplement very similar OIDC logic. Ripe opportunity for code consolidation.

**Comment by NickMeves** [comment]
I'm actually becoming very keen on splitting our base implementations to `oauth2` vs `oidc`.

We could even make `oauth2` base (replacing `provider_defaults`) an implementable provider -- adding support for Userinfo JSONPath rules to extract email/groups from outputs. That seems to be the only reason some of the corner case providers (digitial ocean, nextcloud, etc) get implemented, just different schemas for userinfo response.

**Comment by JoelSpeed** [comment]
> We could even make oauth2 base (replacing provider_defaults) an implementable provider -- adding support for Userinfo JSONPath rules to extract email/groups from outputs. That seems to be the only reason some of the corner case providers (digitial ocean, nextcloud, etc) get implemented, just different schemas for userinfo response.

I would really like to try and convert some of the providers into basically configuration for a centralised provider, this sounds like it leans toward that. If the only differences are default profile URLs or different userinfo formats, perhaps that can be encapsulated in configuration somehow

**Comment by NickMeves** [comment]
`--oauth-email-jsonpath` & `--oauth-groups-jsonpath` something like that? Only other main area where I was variability was the extra headers potentially needed in a `profileURL` or `validateURL`, so we could make that configurable as well (they mostly just need `Accept: application/json` added so they call the `makeOIDCHeader` helper)

Slightly related, but potentially out of scope for generic `oauth` since they are OIDC based: Azure & Login.gov had extra LoginURL parameters. Login.gov in particular, besides the extra `nonce` parameter it adds, seems like it is pure OIDC and probably should just use struct composition around `OIDCProvider` and ride it's functionality if it wants to keep up with feature improvements.

**Comment by JoelSpeed** [comment]
Do we need to make explicit flags or could we be clever about the options we have already, eg email claim, then just look through the path if it's got a period separating multiple parts of the path?

Very much in favour of wrapping the core OIDC provider if we have providers that could do this

**Comment by NickMeves** [comment]
This is done: https://github.com/oauth2-proxy/oauth2-proxy/pull/1210
