### ISSUE TITLE
Cookies with trailing underline in the name doesn't work properly for large tokens

### ISSUE THREAD

**Issue by peppered** [oauth2-proxy/oauth2-proxy#960]
## Expected Behavior
Having a cookie with name `_auth_`:
1. Split cookie into multiple ones (e.g. `_auth__0` and `_auth__1`)
2. Join splitted cookie

The original and joined cookies are equal. In particular, the names are qual (both `_auth_`).

## Current Behavior

After joining the splitted cookie the trailing `_` is removed. Original and joined cookies names are different — `_auth_` and `_auth`.

## Possible Solution

Replace `TrimRight` in the [cookie/session_store.go joinCookies](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/sessions/cookie/session_store.go#L239) with `TrimSuffix`.

## Steps to Reproduce (for bugs)

Modify [Test_splitCookie_joinCookies](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/sessions/cookie/session_store_test.go#L141) in the following way:

```golang
func Test_splitCookie_joinCookies(t *testing.T) {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

	v := make([]byte, 251)
	for i := range v {
		v[i] = charset[mathrand.Intn(len(charset))]
	}
	value := strings.Repeat(string(v), 1000)

	nameSizes := []int{1, 10, 50, 100, 200, 254}
	nameSuffixes := []string{"", "_", "__", "__0"}
	for _, nameSize := range nameSizes {
		for _, nameSuffix := range nameSuffixes {
			testName := fmt.Sprintf("%d length cookie name with \"%s\" suffix ", nameSize, nameSuffix)
			t.Run(testName, func(t *testing.T) {
				adjustedNameSize := nameSize
				if adjustedNameSize+len(nameSuffix) > 254 {
					adjustedNameSize -= len(nameSuffix)
				}
				cookie := &http.Cookie{
					Name:  strings.Repeat("n", adjustedNameSize) + nameSuffix,
					Value: value,
				}
				splitCookies := splitCookie(cookie)
				joinedCookie, err := joinCookies(splitCookies)
				assert.NoError(t, err)
				assert.Equal(t, *cookie, *joinedCookie)
			})
		}
	}
}
```

## Context
I used oauth2-proxy with Azure Active Directory and setup `--cookie-name=_auth_`. I was geeting the message telling me that cookie is not provided

## Your Environment

- Version used: 6.1.1

**Comment by JoelSpeed** [comment]
Good find, looks like a bug to me! Would you be able to raise a fix PR?

**Comment by peppered** [comment]
Sure.

**Comment by NickMeves** [comment]
Linking this other issue that might be session cookie splitting related in case we have a regression: https://github.com/oauth2-proxy/oauth2-proxy/issues/941

**Comment by NickMeves** [comment]
This was fixed
