### ISSUE TITLE
Deploying in an Istio service mesh results in crashes and 503's

### ISSUE THREAD

**Issue by braunsonm** [oauth2-proxy/oauth2-proxy#961]
## Expected Behavior

OAuth2-proxy should work as expected when deployed in the service mesh.

## Current Behavior

Currently if you deploy Oauth2-proxy inside a Istio service mesh with a sidecar and mTLS enabled (as it is by default). You will experience 503's when trying to contact any internal Kubernetes service. You can still curl to those services just fine, the oauth2-proxy will still 503. Nginx also works fine.

If you configure Oauth2-proxy with the external URL (https) of a service hosted by the mesh, oauth2-proxy will crash without any log output.

## Possible Solution

You can disable mTLS or enable permissive mTLS which fixes the above issues. However it should work with mTLS as does nginx and curl.

## Steps to Reproduce (for bugs)

1.  Deploy Istio to a Kubernetes cluster
2.  Deploy oauth2-proxy to the istio service mesh
3.  Attempt to wire it to an internal service/ClusterIP

## Context

I use `cf-for-k8s` project and was deploying oauth2-proxy as a binary with their `Procfile` buildpack. CF apps are part of the service mesh.

## Your Environment

- Version used: v6.1.1
- Kubernetes SaaS: AKS

**Comment by JoelSpeed** [comment]
Am I right in thinking that OAuth2 Proxy doesn't actually need to handle any of the mtls stuff and that the envoy sidecar container handles this? 

Can you share the logs for OAuth2 Proxy when it is returning 503s?

**Comment by braunsonm** [comment]
That's correct @JoelSpeed it should be completely transparent to oauth2-proxy, similar to how curl has no idea it's happening.

There's nothing that interesting in the logs:
```
127.0.0.1:34860 - SNIP@example.com [2020/12/16 20:24:12] example.com GET servicename.namespace.svc.cluster.local:8080 "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" 503 95 0.02
```

The request never actually makes it to the service, it fails somewhere along the way.

**Comment by JoelSpeed** [comment]
> If you configure Oauth2-proxy with the external URL (https) of a service hosted by the mesh, oauth2-proxy will crash without any log output.

Could it be perhaps that this is something like a CA cert issue? When you say the external URL, is this it trying to proxy to an upstream service? Perhaps you could elaborate on this a bit, or share some of your config so we can try to work out what's happening here

**Comment by braunsonm** [comment]
I don't think it's a CA cert issue. My config isn't really anything interesting, the only change I made was instead of having the upstream as an internal Kubernetes service url (which is using HTTP), I just tried having that service behind an LB with an external IP. This means cert manager gave it a valid certificate so I tried changing `oauth2-proxy` to upstream to that HTTPS URL instead. This results in crashes.

Nginx can proxy_pass the same URL without issues.

**Comment by JoelSpeed** [comment]
Certs are about the only thing we can easily tweak, just to be sure, have you tried adding `--ssl-upstream-insecure-skip-verify` to OAuth2 Proxy when you're using mTLS configuration?

If that fails, I think we need to add some debug logic to the upstream handler in [http.go](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/upstream/http.go)

**Comment by braunsonm** [comment]
No I did not try that, they are valid certs though. Unfortunately I don't have an environment to test this since production cannot have anymore interruptions.

**Comment by JoelSpeed** [comment]
My concern is that while they may be valid certs, the CA certs may not be loaded into the container correctly and causing artificial certificate errors. If you can try to reproduce in a different environment, that would be greatly appreciated, otherwise, I don't really know how to proceed here unless someone else has an env that they can reproduce this is in

**Comment by braunsonm** [comment]
As far as I know this is still an issue.

**Comment by braunsonm** [comment]
Can the bot ignore issues?

**Comment by bgoldiing** [comment]
Where trying to use the OIDC provided and uses a keyclock idam that is setup for mTLS (e.g. client certs). 

Below is our oauth2-proxy args

```
- --http-address=0.0.0.0:4180
          - --metrics-address=0.0.0.0:44180
          - --cookie-domain=.proteus-mda.io
          - --cookie-expire=24h0m0s
          - --insecure-oidc-allow-unverified-email=true
          - --login-url=https://idam-staging.proteus-mda.io/auth/realms/luna/protocol/openid-connect/auth
          - --oidc-issuer-url=https://idam-staging.proteus-mda.io/auth/realms/luna
          - --oidc-jwks-url=https://idam-staging.proteus-mda.io/auth/realms/luna/protocol/openid-connect/certs
          - --pass-access-token=true
          - --pass-authorization-header=true
          - --pass-user-headers=true
          - --provider=oidc
          - --provider-display-name=XYZ Staging IDAM
          - --redeem-url=https://idam-staging.xyz.com/auth/realms/luna/protocol/openid-connect/token
          - --redirect-url=https://staging.xyz.com/oauth2/callback
          - --reverse-proxy=true
          - --scope=openid
          - --set-authorization-header=true
          - --set-xauthrequest=true
          - --skip-jwt-bearer-tokens=false
          - --skip-oidc-discovery=true
          - --ssl-insecure-skip-verify=true
          - --validate-url=https://idam-staging.xyz.com/auth/realms/luna/protocol/openid-connect/userinfo
          - --whitelist-domain=.xyz.com
          - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
```

We see the redirect to IDAM and user get logged with token but oauth2-proxy is giving us this error:

```
[2021/08/23 15:59:24] [oauthproxy.go:748] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 400 Bad Request
Response: <html>
<head><title>400 No required SSL certificate was sent</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>No required SSL certificate was sent</center>
<hr><center>nginx</center>
</body>
</html>
```

Any idea on how to configure oauth2-proxy to support mutual tls/client certs?

**Comment by JoelSpeed** [comment]
I don't think we support mTLS in this way right now, you'd have to deploy something like Envoy or something alongside to intercept the calls and provide the mTLS (like in Istio)
