### ISSUE TITLE
How authenticate with JWT with Google provider?

### ISSUE THREAD

**Issue by jessicabarbalho** [oauth2-proxy/oauth2-proxy#962]
I'm using oauth2_proxy with a Google provider to authenticate users but I want a way to authenticate server-to-server.

## Expected Behavior
Authenticate with a JWT Bearer token

## Current Behavior
I've tried so many configurations and ways to generate the JWT token but it always returns the login page with the error:
`Error retrieving session from token in Authorization header: unable to verify jwt token`

## Context
I already use the proxy to authenticate users and it works perfectly, but I never was able to authenticate a server, I've read all the documentation but I don't have a clue how to do it and I hope you could help me on it.

## Your Environment
```
http_address = "127.0.0.1:4180"
https_address = ":443"
redirect_url = "https://mydomain/oauth2/callback"
upstreams = UPSTREAM_ARRAY
standard_logging = true
pass_basic_auth = true
skip_jwt_bearer_tokens = true
oidc_issuer_url = "https://accounts.google.com"
email_domains = [
     "mydomain.com"
]
client_id = GOOGLE_OAUTH2_CLIENT_ID
client_secret = GOOGLE_OAUTH2_CLIENT_ID
cookie_name = COOKIE_NAME
cookie_secret = COOKIE_SECRET
cookie_expire = "168h"
cookie_secure = true
cookie_httponly = true
```

- Version used: 6.1.1

**Comment by NickMeves** [comment]
We only support Bearer token auth for OIDC based providers that implement some variant of this method to use on an ID Token: https://github.com/oauth2-proxy/oauth2-proxy/blob/d2ffef2c7e0a622295c42cb2fdd70ef14593d03c/providers/oidc.go#L181

Or directly via adhoc OIDC issuers with the `--extra-jwt-issuers`.

The reason being is an OIDC ID Tokens have the authorization details we rely on in their claims (`sub`, `email`, `groups`). So those can be quickly extracted on a stateless/sessionless basis to populate our internal session object that is used for all the authentication & authorization.

The challenge here with non-OIDC OAuth2 providers is they usually just provide an Access Token, which doesn't contain enough details in its claims to populate a session.

In the human flow, during the login, a call is made to the User Info endpoint of your provider with the Access Token to get all those details and persist longterm in the session cookie. But on a stateless per-request basic with the Access Token as a Bearer header, that would result in an underlying HTTP subrequest to your provider userinfo endpoint for every request.

Coming up in v7, regardless of your provider, if you set the appropriate `oidc-issuer` related flags, there's a default implementation of `CreateSessionFromToken` if you happen to have a valid ID Token to use.

**Comment by NickMeves** [comment]
Maybe that subrequest to a userinfo endpoint in every `CreateSessionFromToken` call is a time-penalty some users/providers are willing to pay if they only have Access Tokens 🤔 

But I think something like that would need us to implement https://github.com/golang/groupcache first in our requests library to fix the thundering herd problem (this is a problem on our mind with session refresh requests for chatty applications).

CC: @JoelSpeed

**Comment by NickMeves** [comment]
Out of curiosity with Google, what does the machine to machine workflow look like with Google? How does a machine get its token? You end up with Access Tokens in the end I take it?

Maybe we start implementing Access Token based `CreatedSessionFromToken` based methods in more traditional non-OIDC OAuth2 providers that have machine to machine use cases.

It will just be slower if implemented due to the userinfo subrequest requirement.

**Comment by jessicabarbalho** [comment]
Thank you for the clarifications!
Regarding how Google does machine gets the token, usually, it uses a gcloud lib for it, but I don't know the implementation details. My hope was that you implemented it, so I could use it here, but since it is not the case I will investigate there deeper or try to use an OIDC issuer.

**Comment by smazurov** [comment]
In case anyone stumbled on this, I wrote up a blog post that covers this use case plus service accounts: [Server to Server Authentication with Google Provider in oauth2-proxy](https://www.mazurov.dev/posts/server-to-server-jwt-with-oauth2-proxy/)

**Comment by RichardSieg** [comment]
@smazurov Thanks for the awesome blog post! Do you know whether this approach can be combined with google groups authentication?

**Comment by pfuhrmann** [comment]
I could not make it work based on the @smazurov's blog post. oauth2-proxy keeps refusing the token witth the "not implemented" message. Does anyone have actually working solution to have JWT together with google groups?

**Comment by RichardSieg** [comment]
> I could not make it work based on the @smazurov's blog post. oauth2-proxy keeps refusing the token witth the "not implemented" message. Does anyone have actually working solution to have JWT together with google groups?

@pfuhrmann It seems to be related to https://github.com/oauth2-proxy/oauth2-proxy/issues/1803 . As you posted there already as well I guess we have to watch for that PR to merge.

**Comment by driv** [comment]
@smazurov You solution works fine with the version you used in the post (`7.2.1`), I could not make it work with any newer version. Did something change?
