### ISSUE TITLE
Support X-Request-ID in Access Logs

### ISSUE THREAD

**Issue by NickMeves** [oauth2-proxy/oauth2-proxy#965]
Use a configurable client header (default `X-Request-ID`) where incoming clients can specify a UUID for easier tracing as a templated variable to use in access logs.

## Expected Behavior

Something like `{{.RequestID}}` is available to be used in the templating language if users desire (probably not a default templated value).

## Current Behavior

No `X-Request-ID` variable for use in log templates.

## Possible Solution

Add the configured request ID header to the request scope then implement a `util.GetRequestID(req *http.Request)` method that can extract it.

This can then be added to the request template here: https://github.com/oauth2-proxy/oauth2-proxy/blob/3a4660414a1cdb8eb93253284872a30cec065465/pkg/logger/logger.go#L252

## Context

Add more logs & tools for operator debugging. This might also come in handy if we implement open tracing.

**Comment by NickMeves** [comment]
@JoelSpeed With the new error template you made - I'm thinking this might be good to incorporate in those?

Debug or not toggled, we include the Request ID in the error page. That way a user can pass the value to an admin to correlate the failed request to all the pertinent logs (so we'd add the `{{.RequestID}}` to all our log templates.

I would extend this to do either `X-Request-ID` set by the request or a random UUID set by the proxy if the client request didn't have one.

**Comment by JoelSpeed** [comment]
Yep, I think that makes sense! I'd put the request ID in the more info box on the error page so users see it only if they want to.

And yes, generating a request ID if not present would be useful, this could go into the scope middleware initialisation process
