### ISSUE TITLE
Is there any equivalent of "--authenticated-emails-file" for command line flag, instead of reading a file?

### ISSUE THREAD

**Issue by shinebayar-g** [oauth2-proxy/oauth2-proxy#968]
## Expected Behavior

Is there any equivalent of `--authenticated-emails-file`? I mean this option requires a file to read. I would rather pass it as a list of strings. But couldn't find any relevant flag.

## Current Behavior

For some reason my kubernetes deployment cannot read the file as configmap with `--authenticated-emails-file`.  It says no such file or directory when file clearly exists. I can even run the oauth2-proxy server if I run the command inside pod manually. But as soon as I just run it regularly pod crashes. I assume it has something to do with the symlink or file ownership. It's strange that it works just fine if I run command manually.

Edit: Found my error! Turns out I didn't need "" on my key value.

```yml
containers:
  - name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    args:
      - --authenticated-emails-file="/etc/oauth2_proxy/auth_users" # this was wrong, should be just --authenticated-emails-file=/etc/oauth2_proxy/auth_users
```

- Version used:
6.1.1

**Comment by JoelSpeed** [comment]
A few people have been hit recently by the flag parsing and having quotes around their values in YAML. It would be good to check what actually gets sent to the container as an argument (I assume escaped quotes around the value) and possibly see if we can handle this.

Not sure I've seen this issue on other projects so maybe there's a config option for the flag library we have missed or something 🤔

**Comment by shinebayar-g** [comment]
Yeah escaping quotes around key values is a good practice I believe. Everything in kubernetes does this thing and I put quotes instinctively.

In this case I think there is a little bug or something.


passing command line arguments with kubernetes' `args` syntax doesn't work.

```yml
containers:
  - name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    args:
      - --authenticated-emails-file="/etc/oauth2_proxy/auth_users" # this doesn't work

...

containers:
  - name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    args:
      - --authenticated-emails-file=/etc/oauth2_proxy/auth_users # this works
```

But running the same command manually with or without quotes behave same.

```console
$ oauth2-proxy --authenticated-emails-file=/etc/oauth2_proxy/auth_users
[2021/01/01 20:36:48] [logger.go:490] using authenticated emails file /etc/oauth2_proxy/auth_users
[2021/01/01 20:36:48] [logger.go:490] watching /etc/oauth2_proxy/auth_users for updates
[2021/01/01 20:36:48] [logger.go:490] OAuthProxy configured for Google Client ID: REDACTED
[2021/01/01 20:36:48] [logger.go:490] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
[2021/01/01 20:36:48] [logger.go:490] HTTP: listening on 127.0.0.1:4180


$ oauth2-proxy --authenticated-emails-file="/etc/oauth2_proxy/auth_users"
[2021/01/01 20:37:00] [logger.go:490] using authenticated emails file /etc/oauth2_proxy/auth_users
[2021/01/01 20:37:00] [logger.go:490] watching /etc/oauth2_proxy/auth_users for updates
[2021/01/01 20:37:00] [logger.go:490] OAuthProxy configured for Google Client ID: REDACTED
[2021/01/01 20:37:00] [logger.go:490] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
[2021/01/01 20:37:00] [logger.go:490] HTTP: listening on 127.0.0.1:4180
```

I also found out that oauth2-proxy reads the file without need of reloading. Thus makes it possible to sync with the configmap without bringing down the pods, which is quite nice.

**Comment by JoelSpeed** [comment]
Yeah I think this is just a case of Kubernetes being Kubernetes. I don't really think there's anything we can do here apart from attempt to handle escaped quotes `\"`, but that could cause other issues!

I think this may just have to be one of those things that we are aware of and warn people about somehow 🤔
