### ISSUE TITLE
DUO MFA not working with Azure AD

### ISSUE THREAD

**Issue by amitkatyal** [oauth2-proxy/oauth2-proxy#977]
### **Azure AD Configuration**
 _- Configured DUO MFA_

### **Issue Details**
While accessing the application, the oauth2 proxy is redirecting to AZURE IDP for authentication. After successful authentication to the AZURE IDP, AZURE IDP is redirecting back to the configured redirect URL with authorization code.

While getting the access token (from authorization code) from the AZURE IDP Oauth2 proxy is getting the below error 
from the AZURE IDP.

### **Access Token Request**
GET - "/oauth2/callback?code=0.AR8A_0GKNdlG00milzcNiU6uaucpy8HMXMxAnFFbFEZkQ-QfAAA.AQABAAIAAABeStGSRwwnTq2vHplZ9KL45djYYeq4gTAYH_-1lxwi6HDH5Dt5QX4o682DvS6i4x0bqMm6TSuLWUK7W2z3yap22EjzW9aXaYRAqZTz1RT3sN3lnOvQX5aHwyEMEObwJWfh5D1PxTvP_2Mebli2qtUz2g0ieQ-wkmW6BxfmwGob7Oipp-0-TmhXgHLYlJ4YccwRYLXU2pXJ8NOzeaOtovBXyWkbDYDmwSJG3lnHQG1E3hxjwk4eY5wmx84Wo6tfSToKlQpZZQKs0aox8R-p6UmVJjAVaiyoz-4U98RNoSzhhiN_7NVTTdr3UrYi8Uobw-yyfwVLVLezUMMfnI_o4uPMtg_kEJLiCfCauCqbjy56TFiOwf5OMP6uZ3aPpqx1QYmuJjQoAPt-dZP7hC6kAmvnI3eBwXt8sZU-akAhT1_My7HNT5gX9fHBsfA9hSFM0yUF1gL4p9xJPKQlxYk8Avx6HiW-FZEBwiloa-9b_nFELYbLCYw4KarMVIMpA-CgqXErMq4F4LfIGo3PujRDo3PiW7gsnFaQC3cVWZSlCW2SnV51ZrxWi6EtQQLmawahmGgBHl_5lVsYQGDEEIlOa0jxiqz7LJGuuK-

### **Error Response**
[2020/12/22 06:49:22] [logger.go:508] Error redeeming code during OAuth2 callback: unexpected status "400": **{"error":"interaction_required","error_description":"AADSTS50158: External security challenge not satisfied. User will be redirected to another page or authentication provider to satisfy additional authentication challenges**.\r\nTrace ID: 5171a074-db5b-4fe1-a3c6-ccfa2d1b4400\r\nCorrelation ID: f30ba252-ab09-42cd-ad54-71e1f016c153\r\nTimestamp: 2020-12-22 06:49:22Z","error_codes":[50158],"timestamp":"2020-12-22 06:49:22Z","trace_id":"5171a074-db5b-4fe1-a3c6-ccfa2d1b4400","correlation_id":"f30ba252-ab09-42cd-ad54-71e1f016c153","error_uri":"https://login.microsoftonline.com/error?code=50158","suberror":"basic_action","claims":"{\"access_token\":{\"capolids\":

{\"essential\":true,\"values\":[\"af33833a-cef9-4307-b996-3b4ab44f1e4a\"]}
}}"}

**interaction_required | The request requires user interaction. For example, an additional authentication step is required. | Retry the request with the same resource, interactively, so that the user can complete any challenges required.
-- | -- | --**

Error Code | 50158
-- | --
Message | External security challenge not satisfied. Users will be redirected to another page or authentication provider to satisfy additional authentication challenges.
Remediation | The user is required to satisfy additional requirements before finishing authentication and was redirected to another page (such as terms of use or a third party MFA provider). This code alone does not indicate a failure on your user's part to sign in. The sign-in logs may indicate that this challenge was successfully passed or failed.

As per the AZURE AD documentation, An additional authentication step is required but it is not clear if the oauth2 proxy needs to redirect the client to the DUO security for MFA?

**Comment by NickMeves** [comment]
OAuth2-Proxy shouldn't be involved with Duo MFA in this flow -- It just communicates with Azure AD with the 3-legged OAuth flow per the OAuth2 spec.

Usually any integration with something like Duo MFA from an Identity Provider is configured there and all that happens during the User signin/authentication stage with the IdP (first part of OAuth flow after OAuth2-Proxy redirects a user to the IdP Login URL). Once we get the stage 2 redirect from the IdP to our callback URL, all the sign-in operations with the IdP should be finished.

**Comment by amitkatyal** [comment]
> OAuth2-Proxy shouldn't be involved with Duo MFA in this flow -- It just communicates with Azure AD with the 3-legged OAuth flow per the OAuth2 spec.
> 
> Usually any integration with something like Duo MFA from an Identity Provider is configured there and all that happens during the User signin/authentication stage with the IdP (first part of OAuth flow after OAuth2-Proxy redirects a user to the IdP Login URL). Once we get the stage 2 redirect from the IdP to our callback URL, all the sign-in operations with the IdP should be finished.

Thanks, NickMeves !!

**Comment by NickMeves** [comment]
Happy to help!
