### ISSUE TITLE
Auto-configure authentication skipping using OpenAPI in upstreams, if available

### ISSUE THREAD

**Issue by rassie** [oauth2-proxy/oauth2-proxy#981]
## Expected Behavior

Currently, if securing an API with unauthenticated or optionally authenticated endpoints with `oauth2-proxy`, one needs to provide a regular expression to `--skip-auth-regex`/`--skip-auth-route` (latter also supports defining methods for which to skip authentication). However, in most cases this information is available in upstream's code and might be exported as a "Security requirement object" in an OpenAPI specification (https://swagger.io/specification/#security-requirement-object). In this case, clean documentation of API endpoints and their authentication by upstream's developer should be rewarded by an auto-configuration of `oauth2-proxy` for this upstream.

**Comment by JoelSpeed** [comment]
Interesting idea 🤔

Would you pull this information at startup or would it need to be pulled regularly to ensure that the routes were up to date? The latter feels like it would add a lot of complexity

**Comment by rassie** [comment]
Probably once at start time for now. There are probably a myriad of ways to notify at runtime depending on the environment (as opposed to polling), but if we assume a sidecar deployment, start time should be enough.

**Comment by JoelSpeed** [comment]
It would be good for us to find examples of other projects that have implemented this feature, ideally there is some library we can use to make this really easy to implement into this project
