### ISSUE TITLE
Feature: asymmetric JWT signing

### ISSUE THREAD

**Issue by benmccann** [oauth2-proxy/oauth2-proxy#983]
Pomerium, AWS, and Google all do asymmetric signing of a JWT whereas `oauth2-proxy` does a symmetric signature of the request. I would like an option to make `oauth2-proxy` conduct signing in a similar manner to these other service providers.

## Expected Behavior

Allow an application to support `oauth2-proxy` in the same manner as other identity proxies:
* https://www.pomerium.io/docs/topics/getting-users-identity.html
* https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html
* https://cloud.google.com/iap/docs/signed-headers-howto

## Current Behavior

Symmetric signing of the request
https://oauth2-proxy.github.io/oauth2-proxy/docs/features/request_signatures/

## Possible Solution

Add a configuration option to sign the request in either way. This could possibly be configured on an upstream-basis as different upstream services may support different signature verification methods. Also add an endpoint where the upstream can fetch the public key.

## Context

I'm building an application and I'd like users to be able to use it with whatever SSO solution they might be using including Pomerium, oauth2-proxy, Google, AWS, etc. The fact that `oauth2-proxy` is using a different mechanism for request signing than these other SSO solutions makes it more work to support them all. While we would like to advertise that we support `oauth2-proxy`, we probably would not support it in the current state because it's different enough from the other SSO providers that it doesn't seem worth building support just for it.

**Comment by NickMeves** [comment]
You might be interested in this issue touching on this: https://github.com/oauth2-proxy/oauth2-proxy/issues/648

The current `GAP-Signature` functionality is 5+ years old and hasn't aged well with the codebase. I lean toward deprecating support for it completely.

If it were replaced, I would want the signed request headers to by dynamic and listed in a header (e.g. like DKIM for email) -- And asymmetric.

What do you mean by "signed JWT" though? We don't make our own tokens and use whatever is provided by your Identity Provider in our session stores. If you setup ID Token forwarding to your backend, the ID Token forwarded in the Bearer header is your ID Token from your provider and it is signed by them.

**Comment by NickMeves** [comment]
It seems like looking at the links you submitted, you are looking for an OIDC IDToken sent to your backend where you can pull out the user details from the claims (`sub`, `email`, `groups`, etc).

Use this config option: `--pass-authorization-header` -- then you backends can validate those OIDC ID Tokens' signatures normally pulling the `openid-configuration` and `jwks_uri` from the issuer URL.

**Comment by benmccann** [comment]
Thanks. That does look like what I want. It looks like OIDC ID Tokens are JWTs.
