### ISSUE TITLE
Show customized Forbidden page for unauthorized users

### ISSUE THREAD

**Issue by vrindanayak** [oauth2-proxy/oauth2-proxy#986]
I've searched the list of open / closed issues / pull requests, documentation and OAuth2 Proxy code, but I haven't found any way to customize an error / forbidden page shown to unauthorized users. Please advise if there is already a way to configure this - in case I have missed out looking in the right place; else I would like to be able to configure a customized error page displayed to unauthorized users.

## Expected Behavior

Enable / allow some option to show a customized *Forbidden Page* template to an unauthorized user

## Current Behavior

Default OAuth2 Proxy's **403 Permission Denied** page is displayed to an unauthorized user.

![Screenshot_20210112_104647](https://user-images.githubusercontent.com/15785031/104297811-929c3a00-54c3-11eb-9a97-0835884193a8.png)

## Possible Solution

Providing some option similar to Keycloak-Gatekeeper's [--forbidden-page](https://keycloak.discourse.group/t/gatekeeper-redirect-to-a-page-on-access-forbidden/1326) would be of help. 

![Screenshot_20210112_104814](https://user-images.githubusercontent.com/15785031/104298018-c70ff600-54c3-11eb-98af-b318af8c144e.png)

## Steps to Reproduce

- Secured [DCM4CHEE Archive and Elastic Stack](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-secured-archive-services-and-Elastic-Stack-on-a-single-host#use-docker-command-line) : This link explains how Kibana can be secured using Keycloak-Gatekeeper (Points 11 and 12)
- Additionally as we plan to [replace Keycloak-Gatekeeper using OAuth2 Proxy](https://github.com/dcm4che/dcm4chee-arc-light/issues/2820#issue-718183061), [Kibana is additionally secured using OAuth2 Proxy](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Secure-Kibana-using-OAuth2-Proxy) on our test environment

## Context

Customize error pages shown to unauthorized users.

## Your Environment

- Version used: Linux Ubuntu 18.04.4 LTS

## Related issues / info : 
- [Secure Kibana using OAUth2 Proxy](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Secure-Kibana-using-OAuth2-Proxy) motivated by [termination of development on Keycloak-Gatekeeper and Louketo by RedHat](https://github.com/dcm4che/dcm4chee-arc-light/issues/2820)
- [Update Overview.md : Add missing option "keycloak-group", rectify multi valued flag names "upstream" and "provider-ca-file"](https://github.com/oauth2-proxy/oauth2-proxy/pull/984)

**Comment by JoelSpeed** [comment]
You can at the moment provide a Go template in an html file `error.html`, however, this is completely undocumented at the moment, it would be great to get some documentation on this feature and maybe expand it as well

It uses the flag `--custom-templates-dir` to provide both the error page template and the sign_in page template. This was implemented before any of the current maintainers took over the project though so I'm pretty much working out how this works via archaeology and looking at the `templates.go` file in the root of the repository

**Comment by vrindanayak** [comment]
@JoelSpeed : Thank you for your response. I will try it out.

**Comment by JoelSpeed** [comment]
Please let me know how you get on! If it works we should try and document this somewhere

**Comment by vrindanayak** [comment]
Your suggestion worked except for one thing - The OAuth2 Proxy container won't start unless I also specify a sign_in.html in the custom templates directory. For testing purpose, I saved the page source of Keycloak's sign-in page as sign_in.html and tested the error.html to show the same forbidden page as in case of Keycloak Gatekeeper. 

The point is : I don't want to customize sign in page, as Keycloak auth provider is doing this when OAuth2 Proxy successfully redirects the flow to Keycloak. 

@JoelSpeed  : Is there a way to customize only error page and not sign_in page?

**Comment by JoelSpeed** [comment]
As far as I'm aware, at present you must supply both, my suggestion would be that we include our standard templates as resources in the repository somewhere and ensure that users can just copy the standard one in if they only want to customise one of them. Do you think that sounds reasonable?

**Comment by vrindanayak** [comment]
Either way, if this custom templates directory requires both to be present, for now we can create a static dummy sign in page which will anyway not be used as I also use `OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"`. Once these templates are available as resources, we could see how to customize just one of them as per our requirement.
