### ISSUE TITLE
[Question] How to clear proxy cookie on browser close?

### ISSUE THREAD

**Issue by aashishkoirala** [oauth2-proxy/oauth2-proxy#990]
I need the proxy cookie to be written without an expiry timestamp so that it behaves as a "session cookie" - i.e. it gets removed when the browser is closed. I can't seem to find anything in the docs that mention how to do this or whether this is supported. Thanks!

**Comment by NickMeves** [comment]
We always set the `Expires` field on the Go `http.Cookie` based on the `--cookie-expire` option. The codebase doesn't support not setting an expiration at the moment.

Our recommendation is you set the `--cookie-expire` setting to the same duration (or less) as your provider's Refresh Tokens lifespan and `--cookie-refresh` to the same duration as your Access/ID Tokens lifespan (if you want to refresh them).

**Comment by aashishkoirala** [comment]
Thanks, that's helpful to know.
