### ISSUE TITLE
Inject request and response headers even for skipped routes

### ISSUE THREAD

**Issue by rassie** [oauth2-proxy/oauth2-proxy#992]
(loosely connected to #985 and #979) 

## Current Behavior

Currently, `oauth2-proxy` supports two modes of operation:

1. Protect an endpoint and either return 401 if unauthenticated or proxy endpoint's response if authenticated
2. Provide full access without any intervention if `--skip-auth-route` is set for the endpoint.

It's an all-or-nothing approach, however, there is quite a bit of middle ground to be covered. For example:

1. An endpoint which can optionally accept authentication
2. An endpoint which requires complex groups and roles evaluation from the token
3. An endpoint which needs to check for user permissions based on business logic 

At the same time, `oauth2-proxy` does a lot of heavy lifting, which makes implementing a custom authentication solution undesirable. 

## Expected Behavior

If a route is excluded from authentication handling by setting `--skip-auth-route`, authentication headers should still get injected if authenticated.

## Possible Solution

In my local code, I've managed to make this work by applying the following patch.

```diff
@@ -977,6 +977,10 @@ func (p *OAuthProxy) AuthOnly(rw http.ResponseWriter, req *http.Request) {
 
 // SkipAuthProxy proxies allowlisted requests and skips authentication
 func (p *OAuthProxy) SkipAuthProxy(rw http.ResponseWriter, req *http.Request) {
+       session, err := p.getAuthenticatedSession(rw, req)
+       if err == nil {
+               p.addHeadersForProxying(rw, req, session)
+       }
        p.headersChain.Then(p.serveMux).ServeHTTP(rw, req)
 }
```

However:
1. I can't explain to myself why this works. From what I gather from the code, `p.addHeadersForProxying` has nothing to do with header injection, which is handled in `p.headersChain`, which looks like it should be doing the injection already, but does not.
2. I failed to understand the structure of request/response tests, so I couldn't write one (which is not really surprising, considering I have written about 3 lines of Go in my life). 

## Steps to Reproduce (for bugs)

1. Set `--skip-auth-routes` to something like `.*` or anything else you can easily grab
2. Set injection configuration to inject something in response headers (because it's easily seen in browser)
3. Make sure you are authenticated (by calling `/oauth2/sign_in`)
4. Open browser's developer tools 
5. Open a skipped endpoint in browser
6. Observe that request in developer tools noticing missing injected response header 

## Your Environment
- Version used: latest `master` git snapshot

**Comment by JoelSpeed** [comment]
When authentication is skipped using `skip-auth-route`, there is no session from which to get the information for injecting headers.

Which headers are you trying to get into the response when you are excluding routes?

**Comment by rassie** [comment]
It's perfectly possible I'm abusing the tool at this point :)

Let's forget about response headers injection for a bit, I'm injecting the Access Token since I need in in the frontend for a direct API call, but that could and maybe should change in the future. We'll focus on the request headers for now.

I need to work with optionally authenticated routes. The data they return is either public or private.  If something is public, it doesn't need a token or any authentication data. If it's private, it needs to be matched against currently authenticated user and possibly permissions (groups, roles, etc) which *can* be transmitted in some special header, but it's easier to just transmit the token (`Authorization: Bearer xxxxxx`, it's existing code after all).

This is where skipped routes come into play. Since there is a possibility for unauthenticated access, I need to `skip-auth` this particular route. However the route still needs an authentication token for private access, which can be provided by the request header injection.

> When authentication is skipped using `skip-auth-route`, there is no session from which to get the information for injecting headers.

If I understand the concept correctly, a skipped route can't *initiate* an authentication, but the user can already be authenticated by other means, e.g. if the application redirects accordingly on particular events (e.g. clicking on "Login" buttons, receiving status code 401 from the backend etc.). So if the user presents a session cookie and this session is still valid, authorization headers can be injected into a given request.

Am I missing something about cookies and session which makes this impossible (apart from this stuff already working on my machine, even though I don't exactly know why :))

**Comment by JoelSpeed** [comment]
Ok so I'm going to restate this as I understand it, just to be certain we are on the same page, correct me if I'm wrong.

- You have users who may or may not be authenticated
- When an authenticated user hits a skip-route page (ie they don't need access) no headers are passed to the backend
- When an authenticated user hits a non skip-route page (ie they do need access), headers are passed to the backend

I believe (and this may not be the case), that the flow we want to have through the proxy is:
- Request is received
- We try to load any sessions
- Perform Authz checks on the session (which should include skip-auth-route)
- Inject headers
- Proxy to upstream

Your proposed fix at the top of this seems like it fits what I think should be happening here, whether it is the correct approach or not I'm not 100% sure. We keep having this smattering of code snippets pasted in that flow, we need to identify all of the things that should have headers injected and perform this once. I think the problem here is the organisation of the switch that leads into that `SkipAuthProxy` method, perhaps the SkipAuthProxy check needs to come later in the flow

**Comment by ianroberts** [comment]
This would be very useful for my use case too - in my case I have a webapp with some pages that need to be accessible only to authenticated users and some that can be accessed without authentication, but even on pages that don't _require_ authentication there are parts of the page that adapt if the user is authenticated (e.g. adding an "admin" link to the navbar if the visitor is logged in as a user with admin privileges).

Ideally I'd like some kind of configuration that's a halfway house between "require" authentication (i.e. if not authenticated then redirect to login or return 403) and "skip" authentication (just forward the request as-is without any auth-related headers), whereby _if_ there's a cookie set then add the headers, but if there isn't then just pass through without them.

**Comment by ianroberts** [comment]
I've implemented the "possible solution" above (#1065), guarded by a new config option so the current behaviour remains the default.  I won't be offended if you shoot me down in flames - this is my first proper foray into golang...

**Comment by ianroberts** [comment]
This will become the default behaviour once #1128 is merged.

**Comment by pjeby** [comment]
Not technically inactive, I think, since #1128 is still in progress?  Last discussion there was 4 days ago.

**Comment by ianroberts** [comment]
Indeed - this issue is still open at present, until #1128 is complete.
