### ISSUE TITLE
Support Contour Project

### ISSUE THREAD

**Issue by nissimbitan** [oauth2-proxy/oauth2-proxy#996]
Hi There is any way to use oauth2 proxy with other ingress controller then nginx.
i use contour and i want to use oauth2 proxy with it.

is there any way to use?

**Comment by NickMeves** [comment]
I don't see a parallel of the simple nginx auth annotations that ingress has to make this easy via subrequests.

I do see this as an option: https://projectcontour.io/docs/main/config/client-authorization/

The other route is to not connect to OAuth2 Proxy via subrequest from your ingress, but instead make OAuth2 Proxy a proxy in the request chain between your ingress and backend pods.

Ideally, this is a sidecar container in your application pods and you applications are hosted on localhost behind it (this is what I do the most in my environment, but I've setup tooling to inject the proxy into all our pods). But could also be an OAuth2 Proxy service that the ingress routes to and the proxy's upstream is configured to your backend application's service.

**Comment by nissimbitan** [comment]
@NickMeves Hi Thanks for the answer.
Then you using envoy proxy with ext_authz?

**Comment by NickMeves** [comment]
I don't use envoy myself -- I either use nginx subrequests with these annotations: https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

Or I put it in my application pods directly as a sidecar container.

So I can't help with the `ext_authz` question.

**Comment by jpeach** [comment]
xref #958 

Contour will work with anything that supports the Envoy gprc protocol.

**Comment by telamonian** [comment]
> Ideally, this is a sidecar container in your application pods and you applications are hosted on localhost behind it (this is what I do the most in my environment, but I've setup tooling to inject the proxy into all our pods). But could also be an OAuth2 Proxy service that the ingress routes to and the proxy's upstream is configured to your backend application's service.

@NickMeves Could you please possibly add some more info and specifics about how to set each of these options up? Either in this thread or the docs?

I'm in the same boat as the OP; by fiat of company X, on our internal cloud platform I have to use both OIDC authentication and a contour ingress. So I think my best option will be one of the two you described
