### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by fmotrifork** [oauth2-proxy/oauth2-proxy#999]
Hi,

Thanks for maintaining this great tool!

I would love to use some of the new features that has been merged since last release.
When is the expected release date for next patch version?

**Comment by NickMeves** [comment]
This week or next. Looks like 1 last issue left in the v7 project: https://github.com/oauth2-proxy/oauth2-proxy/projects/3

**Comment by JoelSpeed** [comment]
This has been done, check the releases page for the latest releases
